### ISSUE TITLE
Company Communicator issue: fail to send messages to users

### ISSUE THREAD

**Issue by githubclaw** [OfficeDev/microsoft-teams-apps-company-communicator#1002]
When I am sending messages to members of the M365 Group (5th option), message delivery to all users fails and I receive this error.

System.ArgumentException: 'serviceUrl' cannot be null or empty (Parameter 'serviceUrl')
   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.SendMessageAsync(IMessageActivity message, String conversationId, String serviceUrl, Int32 maxAttempts, ILogger log) in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 62
   at Microsoft.Teams.Apps.CompanyCommunicator.Send.Func.SendFunction.Run(String myQueueItem, Int32 deliveryCount, DateTime enqueuedTimeUtc, String messageId, ILogger log, ExecutionContext context) in C:\home\site\repository\Source\CompanyCommunicator.Send.Func\SendFunction.cs:line 176

Before this, I re-synced the App Service on Azure to resolve another error that says "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." And this is resolved successfully, now this is a new error. May I know how I can solve this issue?

**Comment by gsv022** [comment]
Hi @githubclaw ,
Thanks for raising the query. Please repo URL and branch that has been during the template creation.
Here are the steps.
--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png">

--Click on  Microsoft template

<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png">

 -- Then select **inputs** from left section where you can find the GitHub repo URL and Branch that are used. Please share them.
 <img width="943" alt="image" src="https://user-images.githubusercontent.com/98143492/204268766-d68c11c0-d767-4bbc-beda-566a5b1abe48.png">

**Comment by angtany** [comment]
@gsv022  - Facing the same issue.

**Comment by gsv022** [comment]
Could you please share the GitHub repo and branch. To check it please follow the above mentioned instructions. And share the screenshot for better troubleshooting.

**Comment by githubclaw** [comment]
![image](https://user-images.githubusercontent.com/128158217/232645195-1bf545ca-76f8-431b-91b6-861934c035cb.png)
the github repo: https://github.com/cristianoag/microsoft-teams-apps-company-communicator.git
the branch: master

**Comment by gsv022** [comment]
@githubclaw ,
We had discussion with the team. Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version. 

Hope you understand.

**Comment by gsv022** [comment]
@githubclaw , We are closing the issue request. If there are any issues related to standard version of CC, please log a new issue. We are happy to assist.
