### ISSUE TITLE
Domains that my organization should allow to use CC

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#1006]
Hi,

My organization plans to block access to unnecessary domains.
We want to block .blob.core.windows.net, will this affect CC usage?

Regards.

**Comment by gsv022** [comment]
Hi @MK202204,
Thanks for raising the query. We will discuss with our team and get back to you with proper response soon.

**Comment by MK202204** [comment]
Hi @gsv022 & Team,

When I checked the [wiki](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Data-stores#azure-table-storage), it was stated that CC uses Azure Table Storage as a data store, so access to "<storage account name>.table.core.windows.net" is necessary, but access to ".blob.core.windows.net" is unnecessary.
Please let me know if this understanding is wrong.

Thankyou.

**Comment by gsv022** [comment]
@MK202204 ,
We do not recommend making any changes to the deployed Azure resources as it may impact the overall functionality. Our finding says that there is a dependency on blob storage as well. Hence disabling blob.core.windows.net will effect the functionality.
Please let us know if have any queries.

**Comment by MK202204** [comment]
@gsv022
Thankyou for your reply.

OK.Rather than allowing *.blob.core.windows.net, I want to allow only domains used in my organization.
I think that specifying the storage account as shown below will not effect the functionality.
**https://<storage-account>.blob.core.windows.net**
How about this?
please let me know your opinion.

Thanks.

**Comment by gsv022** [comment]
@MK202204 , Ideally this should work. But you need to check it on your own. We can't give assurance on this.

**Comment by gsv022** [comment]
@MK202204 ,Please let us know if you have any queries related to CC. Otherwise we can make it to closure.

**Comment by MK202204** [comment]
@gsv022 
Thankyou for your reply.
I understand your answer.
Please close this thread.
