### ISSUE TITLE
Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request.

### ISSUE THREAD

**Issue by ghost** [OfficeDev/microsoft-teams-apps-company-communicator#1007]
I need help on Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request.

I have checked the client secret, it has not expired. I also restarted the app service and function apps.

![](https://user-images.githubusercontent.com/112813965/229040436-3a66ad3a-6962-40b5-88de-0724714c7390.png)

I verify the setup authentication - (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) steps are already done as per the deployment guide.

![](https://user-images.githubusercontent.com/112813965/230000516-876d2caf-7302-4078-a803-15a6f7e8acce.png)

![](https://user-images.githubusercontent.com/112813965/230000971-d29313b2-7e8c-45e2-8d6e-ce4c12aaa097.png)

![](https://user-images.githubusercontent.com/112813965/230001275-ae2c393a-51ce-4cf0-8e3d-5863a0b615a2.png)

Kindly assist urgently.

**Comment by gsv022** [comment]
Hi @OlufemiOlaoye ,
Thanks for doing the necessary.  There is a chance that secrets might have incorrectly configured. To check the secrets, here is the procedure. Please do compare and verify.

- Go to  Key vault Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets

**Comment by OlufemiOlaoye** [comment]
@gsv022 thanks for the response.

I have gone through the steps and the secrets are different from what I created.

See below.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/112813965/231112657-3c629f02-6664-46f5-a9d4-6beb2d75610f.png">

<img width="509" alt="image" src="https://user-images.githubusercontent.com/112813965/231113917-ceab872d-11b6-4b2a-9793-10147c26b987.png">

From the screenshots, you will see that the secret is different and this is the same for User and Graph apps.

Regards,

**Comment by gsv022** [comment]
@OlufemiOlaoye ,
Please click on the GUID present below the **CURRENT VERSION**. You will find show secret. Click on view secret and compare it with the actual secret present in the app registration.

Do the same for all app secrets

**Comment by OlufemiOlaoye** [comment]
@gsv022 ,
Okay, so it's the same for all app secrets. 
The app secrets is the same for each of the apps, it didn't change.

**Comment by gsv022** [comment]
@OlufemiOlaoye , Just trying to understand secrets are compared and they are same right! If yes, please share your outlook id so that we can discuss the issue internally.

**Comment by OlufemiOlaoye** [comment]
@gsv022 , how do you mean Outlook ID?
I prefer a Teams call.

**Comment by gsv022** [comment]
Yes, Please share the Teams Id. So we can continue the conversation internally.

**Comment by OlufemiOlaoye** [comment]
Thanks, @gsv022 
Already shared with you.

**Comment by gsv022** [comment]
@OlufemiOlaoye , I am not able to see it anywhere. Please share it again. Even here it would be much better.

**Comment by OlufemiOlaoye** [comment]
Dear Sai,

I hope you get this meeting invite.

Let me know when you get it.

Regards,
________________________________

**Comment by OlufemiOlaoye** [comment]
@gsv022 , 
See meeting invite link - https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZWFiNzA1ZjItZjI3NC00NmI2LWE5NjktNDFlOTgyOTdkYjdj%40thread.v2/0?context=%7b%22Tid%22%3a%2218f15a3f-ea52-4261-b725-0b0f0d1bab03%22%2c%22Oid%22%3a%22a64fad20-54be-4e59-8387-ed55f81bc59d%22%7d

**Comment by OlufemiOlaoye** [comment]
You can share with olufemi.olaoye@ubagroup.com

**Comment by OlufemiOlaoye** [comment]
ok

**Comment by gsv022** [comment]
We are having this issue discussion internally

**Comment by OlufemiOlaoye** [comment]
This is noted. Thank you.

**Comment by gsv022** [comment]
There is an ongoing issue regarding syncing all users. We will notify you as soon as it is resolved.

**Comment by gsv022** [comment]
We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
