### ISSUE TITLE
Messages Queued

### ISSUE THREAD

**Issue by willcotton** [OfficeDev/microsoft-teams-apps-company-communicator#1008]
Hi, I have deployed the Author App to a Team and added the User App to the Teams client, however when I send messages to either a Team or the Client App the messages are queued. 

I have tried restarting the App Service and functions. 

![CCMessages](https://user-images.githubusercontent.com/129864172/231204324-4f1bc323-047d-4bc8-acd8-34abc729d16d.JPG)

**Comment by gsv022** [comment]
Hi @willcotton ,
Thanks for raising the query. There are multiple reasons for this issue.

- What is the version of the app?
- One of the reasons might be incorrect configuration. Please verify the configuration end-end.
- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
Author-multiple
User-multiple
Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

Hope it helps

**Comment by willcotton** [comment]
Hi, 

App is v5.3
App Registrations: 
- Author-multiple
- User-multiple
- Graph-multiple (I have just switched this to my organization and restarted the App)

I have deployed the App in a single tenant and I have used Front Door.  We have uploaded the author app package to a Teams channel and then uploaded the User App to the same Teams client and then attempted to send messages directly to the User App and the Team Channel.  

![APP](https://user-images.githubusercontent.com/129864172/231418072-70dabd6a-d30f-4148-8f51-b688a609ea4e.png)

Thanks

**Comment by gsv022** [comment]
On switching the supported account type from multiple organization to my organization, able to send the message?

**Comment by willcotton** [comment]
No exactly the same issue.

**Comment by willcotton** [comment]
![Graph App_1](https://user-images.githubusercontent.com/129864172/231496708-2d891ad4-c981-4944-95f7-b3f077a6a0d8.png)
![Graph App_2](https://user-images.githubusercontent.com/129864172/231496769-ac5f34b7-a066-40be-8630-351e4d271bfa.png)
![Graph App_3](https://user-images.githubusercontent.com/129864172/231496785-15e9632b-5500-4bd3-a03c-7d1e8b49e24c.PNG)
![Manifest_Authors](https://user-images.githubusercontent.com/129864172/231496795-e9ea01de-aeca-4cd3-a897-7c8cc55060cf.PNG)

![Manifest_Authors_1](https://user-images.githubusercontent.com/129864172/231496809-67aec9e5-2480-4daa-90b4-2e7be9ee62ee.png)

**Comment by gsv022** [comment]
Hi @willcotton ,
Could you please share the deployment status of each prep-function. Here is the reference.

- Please share the screenshot of the logs section of prep-function. Here is the reference.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/98143492/231065979-3d2ebfe7-cdeb-478d-b1ec-b8f914c22396.png">

**Comment by willcotton** [comment]
![PREP_1](https://user-images.githubusercontent.com/129864172/231758934-f5788934-3f7f-452b-8446-511a6b3fa8b4.PNG)
![PREP_2](https://user-images.githubusercontent.com/129864172/231758951-5152ca67-9676-4b5f-bded-728ca3d11caf.PNG)
![PREP_3](https://user-images.githubusercontent.com/129864172/231758984-858b87c1-70d6-422b-bd19-27c2f442e353.PNG)

**Comment by gsv022** [comment]
@willcotton ,  It seems that function apps got failed/not connected to the repository. Please follow the below procedure.
-  To reach failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select  Data-Function from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository.
- Or Please click on refresh in the logs section to know the status of the resource. if the resource is connected to the intended repository and status showing as failed, please click on **SYNC**.

- Please repeat the same for remaining function apps i.e., prep-function and function.
- Once the status turns to Success(active) in the logs section, try sending a message.

Keep us posted

**Comment by willcotton** [comment]
Hi, I have updated all functions to > https://github.com/OfficeDev/microsoft-teams-apps-company-communicator. 

Messages are still not sending, however they are no longer queued. 
![CC_2](https://user-images.githubusercontent.com/129864172/232535819-a87ac612-e08e-4605-9151-b4e1279b8575.PNG)
![CC_4](https://user-images.githubusercontent.com/129864172/232535833-b1085f67-621c-4636-9fe4-e104b59d7b34.PNG)
![CC_3](https://user-images.githubusercontent.com/129864172/232535913-5b105c54-497e-417e-9f68-ea7c6b6cf18e.PNG)

**Comment by gsv022** [comment]
Could you please share the screenshot of prep-function deployment status

> ![PREP_1](https://user-images.githubusercontent.com/129864172/231758934-f5788934-3f7f-452b-8446-511a6b3fa8b4.PNG)

**Comment by willcotton** [comment]
![PREP_STATUS](https://user-images.githubusercontent.com/129864172/232993646-488cfc49-d6b9-486c-9004-f0c86d304916.png)
![PREP_STATUS_1](https://user-images.githubusercontent.com/129864172/232995447-2acdb2c2-23e7-49b4-b89b-91f119b3e067.png)

**Comment by gsv022** [comment]
@willcotton ,Could you please cross verify the secrets. Please refer to the issue no:[992](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/992)

**Comment by willcotton** [comment]
Hi, I can confirm the secrets are correct in key vault for App, Author and User. 

Thanks

**Comment by gsv022** [comment]
Hi @willcotton ,
Please share the Zipped manifest files

**Comment by willcotton** [comment]
[manifest.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11296191/manifest.zip)

Hi, I have taken the company name out most places. 

Thanks

**Comment by v-royavinash** [comment]
@willcotton It appears to be a configuration issue. The quickest solution is to clean up the resources and start a fresh deployment. However, if you prefer not to redeploy, please double-check the [authentication setup step](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication). If the issue persists, please share your Outlook ID.

**Comment by willcotton** [comment]
Hi, I have verified the authentication setup and this is configured as the deployment guide. 
![authen](https://user-images.githubusercontent.com/129864172/234576688-1906cbcd-2ad0-466e-aa01-34a43146e96f.png)

My Outlook ID > willcotton@hotmail.co.uk

**Comment by v-jaygupta** [comment]
@willcotton ,

Thank you for providing the mail id, will track the conversation internally.

**Comment by willcotton** [comment]
Hi, are you wanting to do a remote session via my Outlook ID? 

Thanks

**Comment by gsv022** [comment]
Hope you received the message internally.

**Comment by willcotton** [comment]
Hi, I have received the email notification from here to my work email but nothing else. 

Thanks

**Comment by gsv022** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
