### ISSUE TITLE
Upgrade to NET6 - Functions failed to start

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#1009]
Hello,

I have just recently tried to upgrade our installation of Company Communicator from version 5.2.0 to the latest 5.3.0. 

The upgrade instructions were followed exactly as provided but the Function Apps (all 3) where failing to start, throwing the error: **AZFD0005**:

```
Message
Error building configuration in an external startup class.
Details
Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error building configuration in an external startup class. ---> Microsoft.Azure.WebJobs.Script.HostInitializationException : One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType DurableTaskWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289' does not meet the required minimum version of 2.4.1. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.4.1 or later. ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later (...)
```

The error is basically saying I'd need to update NuGet references to use the latest versions for some libraries. It does not make much sense to me as the libraries being referenced by CC are already versions greater than the minimum required.

Anyone else had this issue? And how to solve it?

Thank you in advance.

![AZFD0005](https://user-images.githubusercontent.com/42776398/231492593-c0f6570a-e4dd-4128-8680-b9f6f4c36955.PNG)

**Comment by cristianoag** [comment]
Also seeing this in a deployment. The sync log shows D:\home\site\repository\Source\CompanyCommunicator\Microsoft.Teams.Apps.CompanyCommunicator.csproj : error : Version 3.1.426 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
Failed exitCode=1, command=nuget.exe restore "D:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln" -MSBuildPath "D:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin"

**Comment by victorsimonlee** [comment]
@cristianoag - have you upgraded the .net version to NET6 for the Function app? 

Ex: az functionapp config set --net-framework-version v6 -n "basename-prep-function" -g "RG NAME"

**Comment by cristianoag** [comment]
Yes. the framework config was changed, but it looks like the code for the functions require msbuild 16.7 and the only version installed is 16.4. inside the function instance you only see D:\Program Files (x86)\MSBuild-16.4 and older versions.

**Comment by gsv022** [comment]
Hi @victorsimonlee ,
Thanks for raising the query. Please give us sometime to look into this issue and will get back to you with proper response soon.

**Comment by cristianoag** [comment]
I solve the issue. Ended up the config was pointing to master instead of main. The team was attempting to update an older version that was still pointing to the master branch. That was changed somewhere between v4 and v5 to main. We changed the branch to main in all resources and resynced. the problem is now fixed.

**Comment by gsv022** [comment]
@victorsimonlee , Please note that the latest features such DOTNET upgrade .NET 6 , Azure Functions(~4), App service compatible to .NET 6 are part of latest version i.e., 5.3. This latest version code will be always be present in **main** branch of official repository. If the branch is pointing  to main then functions will fail for sure.

Please let us know if you have any queries.

**Comment by victorsimonlee** [comment]
Hello @gsv022,

As stated in my previous comment, the problem was indeed with the AzureWebJobsDashboard setting (it is not compativle with ~4 runtime).

I have then removed the _AzureWebJobsDashboard_ App Setting entry from my environment (all functions & app service), re-deployed everything and it is now working as expected.

Thank you for your time looking into this.

I will close this ticket.

Cheers.
Victor.
