### ISSUE TITLE
Error with extension File

### ISSUE THREAD

**Issue by Crawford1002** [OfficeDev/microsoft-teams-apps-company-communicator#1010]
I am getting this error when looking at deployment for the function groups:

Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func: Could not load file or assembly 'Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by Crawford1002** [comment]
Changing the runtime from 3 to 4 seemed to fix the issue.

**Comment by gsv022** [comment]
Hi @Crawford1002 ,
Thanks for raising the query. Please respond to the below queries.

- At which point the error was noticed?(which place?). Please share the screenshot
- Are you doing the migration from existing version to latest? If yes, what is the existing version?
- 
- 

> Changing the runtime from 3 to 4 seemed to fix the issue.

As you mentioned the issue got fixed. Please let us know if you have any queries.

**Comment by gsv022** [comment]
@Crawford1002 , Could you please let us know the status. If nothing is requires from our end, we can make it to closure.

**Comment by gsv022** [comment]
@Crawford1002 , We would like to inform you that the query you raised has been adequately addressed, and therefore, we are now closing this request. However, if you encounter any issues with the company communicator, please do not hesitate to raise a new issue, and we will be glad to offer further assistance.
