### ISSUE TITLE
Fresh deployment failing azure app service

### ISSUE THREAD

**Issue by Sandeep-FED** [OfficeDev/microsoft-teams-apps-company-communicator#1011]
I'm doing an fresh deployment, initially the prep function, data function & app service got failed.

After re-syncing these, prep & data function synced successfully. but when it comes to Azure app service it keeps failing & throws the below error:

`Restoring npm packages (this can take several minutes)

added 655 packages, and changed 40 packages in 14m
npm notice 

npm notice New major version of npm available! 8.19.2 -> 9.6.4
141 packages are looking for funding
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.4>
  run `npm fund` for details
npm notice Run `npm install -g npm@9.6.4` to update!
Building the client app (this can take several minutes)
npm notice 

> company-communicator@5.3.0 build
> react-scripts build

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './util'
Require stack:
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\node_modules\source-map\lib\source-map-generator.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\node_modules\source-map\source-map.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\dist\minify.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\dist\index.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\dist\cjs.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\config\webpack.config.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\scripts\build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
Failed exitCode=1, command=npm run build
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
An error has occurred during web site deployment.
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\node_modules\source-map\lib\source-map-generator.js:9:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\node_modules\\terser\\node_modules\\source-map\\lib\\source-map-generator.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\node_modules\\terser\\node_modules\\source-map\\source-map.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\node_modules\\terser\\dist\\bundle.min.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\dist\\minify.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\dist\\index.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\dist\\cjs.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\react-scripts\\config\\webpack.config.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\react-scripts\\scripts\\build.js'
  ]
}
npm notice \r\nnpm notice New major version of npm available! 8.19.2 -> 9.6.4\r\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.4>\r\nnpm notice Run `npm install -g npm@9.6.4` to update!\r\nnpm notice \r\nnode:internal/modules/cjs/loader:936\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module './util'\r\nRequire stack:\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\node_modules\source-map\lib\source-map-generator.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\node_modules\source-map\source-map.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\dist\minify.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\dist\index.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\dist\cjs.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\config\webpack.config.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\scripts\build.js\r\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\r\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\r\n    at require (node:internal/modules/cjs/helpers:102:18)\r\n    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\terser-webpack-plugin\node_modules\terser\node_modules\source-map\lib\source-map-generator.js:9:14)\r\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\r\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\r\n    at Module.load (node:internal/modules/cjs/loader:981:32)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\r\n    at Module.require (node:internal/modules/cjs/loader:1005:19) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: [\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\node_modules\\terser\\node_modules\\source-map\\lib\\source-map-generator.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\node_modules\\terser\\node_modules\\source-map\\source-map.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\node_modules\\terser\\dist\\bundle.min.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\dist\\minify.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\dist\\index.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\terser-webpack-plugin\\dist\\cjs.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\react-scripts\\config\\webpack.config.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\react-scripts\\scripts\\build.js'\r\n  ]\r\n}\r\nC:\Program Files (x86)\SiteExtensions\Kudu\99.50201.6113\bin\Scripts\starter.cmd deploy.cmd`

**Comment by gsv022** [comment]
Hi @Sandeep-FED ,
Thanks for raising the query.  We are checking it from our end and will get back to you with proper response soon

**Comment by Sandeep-FED** [comment]
@gsv022 FYI - I'm doing cross tenant deployment, i.e., Azure subscription is in one tenant and App registration is in other tenant(M365 - All users are in this tenant), I had referred the tenant ID of the M365 account's in the CC ARM template.

**Comment by Sandeep-FED** [comment]
Hi @gsv022, Any update on this?

**Comment by gsv022** [comment]
Hi @Sandeep-FED , Please respond to the below queries.

- Please share the repo url and branch that has been used for deployment
- Upon our testing it is found that the issue is not happening from our end. If the resource is connected to official repo and branch it should get successful. So please try disconnecting and connecting the repo.

Keep us posted.

**Comment by Sandeep-FED** [comment]
Hi @gsv022 ,
I'm using the official repo only and the branch is in main.

Let me try to disconnect and resync once again.

**Comment by gsv022** [comment]
Yes, please keep us posted

**Comment by gsv022** [comment]
@Sandeep-FED , Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
