### ISSUE TITLE
Renamed all services by modifying the deploy.ps1

### ISSUE THREAD

**Issue by rajivcoomar** [OfficeDev/microsoft-teams-apps-company-communicator#1012]
Hi Team,

I modified all the services name (not to use resource base name) like front door to start with FD, function to start with Func, storage account with ST ..etc.
Now after successful deployment, the manifest.json use function app name instead of front door url which results in failing to config fetch.
I changed the manifest.json to use front door url(and generated the zip) but now after bot install, it's ask for sign in and  after giving all details it failed saying token Id not found.

My question:
Does rename of all services supported? Or naming is tightly coupled?
If allowed, how to resolve FrontDoor name different then base resource name error of token_id
![image001~3](https://user-images.githubusercontent.com/32197733/231935207-db5ce98c-42d8-424e-960c-6d4e771bfb9e.png)

**Comment by gsv022** [comment]
Hi @rajivcoomar ,
Thanks for raising the query. Please respond to the below query

- _Does rename of all services supported? Or naming is tightly coupled?_
Basically once the base resource name is given during ARM template creation all the resources will be created with the same name only. It is not recommended to change the name of  all resources once it is given. Is there any specific reason to change the name?

**Comment by rajivcoomar** [comment]
We are trying to comply with Azure naming convention. Like storage with ST, function with Func, etc

**Comment by gsv022** [comment]
Hi @rajivcoomar ,
As per our standard version, once the base resource name is given then the same name will be added to prefix of almost  all the resources and it is taken care internally. We completely understand that updating the resource name is mandatory for you. But our support scope will be very limited we are not sure like what the change has been done even. We won't be able to assist on that.

**Comment by rajivcoomar** [comment]
Understood. Thank you

**Comment by gsv022** [comment]
Please let us know if you have any queries, otherwise we can make it to closure

**Comment by rajivcoomar** [comment]
One question: the api://domain name what will be it's value if are changing Front door, function app etc. And under which AD app under api exposure it value should be added i.e user, author or graph?

**Comment by gsv022** [comment]
@rajivcoomar , 
If the front door name is changed. configuration also needs to be changed accordingly.

- It should be under Graph App, api domain need to be added.
- App Service configuration need to be updated.

-

**Comment by gsv022** [comment]
@rajivcoomar ,We would like to inform you that the query you raised has been adequately addressed, and therefore, we are now closing this request. However, if you encounter any issues with the company communicator, please do not hesitate to raise a new issue, and we will be glad to offer further assistance.
