### ISSUE TITLE
The user does not receive messages, apparently due to a change in surname

### ISSUE THREAD

**Issue by StanleyLl0yd** [OfficeDev/microsoft-teams-apps-company-communicator#1015]
The user has changed her last name (for example Jane Doe to Jane Smith) and now does not receive messages. Is this possible because the UPN has remained the same (jane.doe@domain.com)? What and how is it better to change so that message delivery resumes? And one more similar case - the user has a different first name from UPN and email address (for example his first name in AD is Anthony and last name is Jones, but Display Name is Tony Jones and UPN\email is tony.jones@domain.com). The question is the same.

**Comment by gsv022** [comment]
Hi @StanleyLl0yd ,
Thanks for raising the query. We will replicate the issue from our end and get back to you with proper response soon.

**Comment by StanleyLl0yd** [comment]
Hi @gsv022 ,

Just in case - we're using version 5.0.1

**Comment by gsv022** [comment]
@StanleyLl0yd , Meanwhile please share the **repo url** and **branch** that has been used for deploying CC.

**Comment by StanleyLl0yd** [comment]
@gsv022 
https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git
master

**Comment by StanleyLl0yd** [comment]
One more nuance - the users are in a group, the sending goes to this group, but when I export the detailed results of the sending, these users are not in the Message_Delivery file at all.

**Comment by gsv022** [comment]
@StanleyLl0yd , 

- Is this happening with the user who has changed the name?

- Please share the detailed export results of the latest sent message
- Please share the screenshot of author app-sent messages section(over all view).
- Share the screenshot of latest sent message by clicking view status.

**Comment by StanleyLl0yd** [comment]
- Yes, it happened with user who changed the las name and with user with different first name and display name\upn\email
- Unfortunately I can't, but as I said there are no entries with these two users
- <img width="913" alt="AuthAppSent" src="https://user-images.githubusercontent.com/131160519/233930836-c0047e46-507d-4a5a-b137-5f49fe391edd.png">
- <img width="500" alt="ViewStat" src="https://user-images.githubusercontent.com/131160519/233930891-e5a41d82-8ae5-4cda-93e7-f6721447bae7.png">
Failed delivery - users who have blocked the app.

**Comment by StanleyLl0yd** [comment]
Hello @v-jaygupta ,
Write to me at stanleylloyd@gmail.com

**Comment by StanleyLl0yd** [comment]
Did not receive any email

**Comment by gsv022** [comment]
We are making a follow up internally

**Comment by gsv022** [comment]
@StanleyLl0yd , The issue has been resolved over the call. Please let us if you have any relevant queries otherwise we can make it to closure.

**Comment by StanleyLl0yd** [comment]
The issue has been successfully resolved. Thanks.
There are no more questions.
