### ISSUE TITLE
Issue Deploying Company Communicator - Add Client Secret fails

### ISSUE THREAD

**Issue by Macca79** [OfficeDev/microsoft-teams-apps-company-communicator#1017]
I am trying to install the Company Communicator.  The install fails when creating the azure ad app client secrets.

Updating app secret...
az : ERROR: argument --id: expected one argument
At C:\microsoft-teams-apps-company-communicator-main\Deployment\deploy.ps1:339 char:26
+ ... appSecret = az ad app credential reset --id $app.appId --append | Con ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: argument...ed one argument:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Examples from AI knowledge base:
az ad app credential reset --id 00000000-0000-0000-0000-000000000000
append or overwrite an application's password or certificate credentials (autogenerated)
az ad app credential reset --id 00000000-0000-0000-0000-000000000000 --cert "@~/cert.pem"
Append a certificate to the application with the certificate file.
https://docs.microsoft.com/en-US/cli/azure/ad/app/credential#az_ad_app_credential_reset
Read more about the command in reference docs

**Comment by gsv022** [comment]
Hi @Macca79 ,
Thanks for raising the query. Could you please respond to the below queries.
- What is the Azure CLI version?
- Is it a same tenant deployment or cross tenant deployment?
- To unblock you from this issue. Please try [Manual Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

**Comment by Macca79** [comment]
``Hi,

What is the Azure CLI version? - "azure-cli": "2.46.0",
Is it a same tenant deployment or cross tenant deployment? It's for single deployment.
To unblock you from this issue. Please try [Manual Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) We have tried this but that also failed.

![image](https://user-images.githubusercontent.com/122471435/233119032-91a542c7-5945-4f32-99d6-e9ddb4ed2a69.png)

**Comment by gsv022** [comment]
@Macca79 ,
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select  Function from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository.
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
**Note** : - Do the same for all failed resources.

**Comment by v-royavinash** [comment]
@Macca79 Could you please confirm if any further assistance is required for the issue logged.
