### ISSUE TITLE
Issue with install 

### ISSUE THREAD

**Issue by barne77** [OfficeDev/microsoft-teams-apps-company-communicator#1019]
During the install i got issues with these areas 

UKS-ELHT-CC/web
UKS-ELHT-CC-prep-function/web
UKS-ELHT-CC-prep-function/web

How do i resolved them

[UKS-ELHT-CC-prep-functionweb.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11275598/UKS-ELHT-CC-prep-functionweb.txt)
[UKS-ELHT-CC-functionweb.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11275599/UKS-ELHT-CC-functionweb.txt)

**Comment by barne77** [comment]
[UKS-ELHT-CCweb.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11275615/UKS-ELHT-CCweb.txt)

**Comment by barne77** [comment]
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Category 'AppServiceHTTPLogs' is not supported."
    }
}

**Comment by barne77** [comment]
After a redeploy i have got

UKS-ELHT-CC/web
UKS-ELHT-CC-prep-function/web
UKS-ELHT-CC-prep-function/web

to complete successfully. but still get this
![image](https://user-images.githubusercontent.com/17065302/233211892-b7ed0da9-245c-4f27-bf29-86502bbf0510.png)

**Comment by gsv022** [comment]
Hi @barne77 ,
Thanks for raising the query. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by gsv022** [comment]
We will be tracking the issue internally.

**Comment by gsv022** [comment]
@barne77 , As we are tracking internally. We are closing out the issue here
