### ISSUE TITLE
RecipientNotFound (404)

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#1020]
Hello,

I have a situation where I get a "RecipientNotFound (404)" error for a (growing) number of users. 

1. The error is always for the same users.
2. The users received a successful message (201) in the past, but at some point they started getting 404 for every message.
3. Every broadcast a few users start getting the 404 error - so the number of users failing to receive a message grows every broadcast.

Error Details:

AllSendStatusCodes = 404
DeliveryStatus = RecipientNotFound
ErrorMessage = Failed

Exception = 
```
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'   at
 Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)   at
 Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)   at
 Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)   at
 Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at
 Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)   at
 Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94--- End of stack trace from previous location where exception was thrown ---   at
 Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)   at
 Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94
```

Any help is appreciated. :)

**Comment by gsv022** [comment]
Hi @victorsimonlee ,
Thanks for raising the query. Could you please respond to the below queries

- Please share the screenshot of author app-sent messages section(over all view).
- Share the screenshot of latest sent message by clicking view status.

**Comment by victorsimonlee** [comment]
Hi @gsv022 

Below, the screenshot:

![image](https://user-images.githubusercontent.com/42776398/233380588-ceedb7a5-c773-447f-9329-22cf9e1497d9.png)

**Comment by gsv022** [comment]
@victorsimonlee ,We would like to inform you that the query you raised has been adequately addressed, and therefore, we are now closing this request. However, if you encounter any issues with the company communicator, please do not hesitate to raise a new issue, and we will be glad to offer further assistance.

**Comment by gsv022** [comment]
Hi @victorsimonlee ,

- Please share the export results of latest sent messages
- And confirm whether the users who are not receiving the messages are part of organization and active

**Comment by v-royavinash** [comment]
@victorsimonlee , Sometimes, failures occur due to inactive users or invalid user aliases. Out of the 9 failures, is there any valid user email ID for which the message is not being delivered? 

If so, could you please create a test team by adding the same user and a few other valid users, and observe the behavior? Please check if the message fails or sends successfully, and confirm the outcome with screenshots to help better understand the issue.

**Comment by victorsimonlee** [comment]
Hi. Thanks for the replies.

I will make some tests as suggested. 

Besides the 9 failures, I am also observing 44 (number increases on each broadcast) users which are in the security group but the tool is not picking them up (the report says 404-not found). Which is weird, as they are in the Security Group as stated.

I will run some tests and post the results here. 

Thanks again.

**Comment by gsv022** [comment]
@victorsimonlee ,
Yes, Please keep us posted
