### ISSUE TITLE
Idempotency issue in SendFileCardActivity

### ISSUE THREAD

**Issue by NullPointer4096** [OfficeDev/microsoft-teams-apps-company-communicator#1022]
**Description:**
In the provided Azure Functions code for the SendFileCardActivity class, there is an idempotency problem related to the Microsoft.Bot.Builder::ITurnContext.SendActivityAsync API. If a failure occurs after sending the activity but before the function completes, subsequent retries may result in duplicate activities being sent to the user.

**Steps to reproduce:**
1. Deploy the Azure Function with proper environment configurations.
2. Simulate a failure after sending the activity but before the function completes. This can be done by introducing a breakpoint or throwing an exception.
3. Trigger the function execution.
4. Let this function automatically retry with the same input (this time the failure is optional)

**Expected Behavior**
The SendFileCardActivityAsync function should send the activity to the user without causing duplicates or unexpected behavior when retried. That is, each message should only be sent once.

**Actual Behavior:**
The function may cause duplicate activities to be sent to the user or other unexpected behavior when retried after a failure between sending the activity and the function completion.

**Suggested fix:**
Introduce idempotency checks in the SendFileCardActivityAsync function to ensure that activities are sent only once for each unique message. This can be achieved by:
Though the deviation of the prevalence counter is not a huge problem, such an issue can be resolved by maintaining a LastRequestId field in each table entry and blob entry, which stores the invocation id of the last SendFileCardActivity function call. The invocation id is constant across Azure Function retries. Before updating a table/blob entry, if the comparison finds item.LastRequestId == FunctionContext.InvocationId, so no more redundant action would be required. Otherwise, if item.LastRequestId != FunctionContext.InvocationId, update the prevalence counter and the LastRequestId field with FunctionContext.InvocationId.

Thank you for your contribution to the Github community and I really appreciate your effort in following through this issue.

**Comment by v-jaygupta** [comment]
Hi @NullPointer4096 ,
Thanks for raising the issue. We are checking it from our end and will get back to you soon with proper response soon.

**Comment by gsv022** [comment]
Hi @NullPointer4096 ,
We are closing this issue as it has been added to backlog and will be planned in the future releases of CC based on priority
