### ISSUE TITLE
Template deploy old version

### ISSUE THREAD

**Issue by Fadel1949** [OfficeDev/microsoft-teams-apps-company-communicator#1025]
Do you have link for deploy old version e.g. 5.0 
![image](https://user-images.githubusercontent.com/126840838/234847571-c0f377d2-1d44-432e-aa7d-c7cc3207559b.png)

**Comment by v-jaygupta** [comment]
Hi @Fadel1949 ,

Could you please let us know the issue that you are facing with CC?
We would strongly recommend you to use the latest version i.e. v5.3 for any fresh deployments and in case you are using any previous version, please upgrade to v5.3 using the steps mentioned in the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide)

**Comment by gsv022** [comment]
@Fadel1949 ,
Please let us know if you have any queries with Company Communicator or else we can make it to closure.

**Comment by Fadel1949** [comment]
@v-jaygupta  @gsv022   Because I want to use another CC Branch which I have already installed. It worked 1 year ago, but now that Branch is still not updated so I can't use the current Deploy link, so I want to use the old Deploy link, probably around version 5.0.
