### ISSUE TITLE
add Company Communicator to MS Teams

### ISSUE THREAD

**Issue by nyusra** [OfficeDev/microsoft-teams-apps-company-communicator#1027]
As a pilot to broaden the reach of communication add Company Communicator to MS Teams

we are unable to configure the company communicator Application in MS-Teams in Azure environment, kindly help us to resolve this issue.

we can have discussion over a call to understand this better.

**Comment by nyusra** [comment]
can you some one please help us here on this issue?

**Comment by gsv022** [comment]
Hi @nyusra ,
Thanks for raising the query. Please respond to below queries.

- Are you upload the zipped manifest files to the teams?
- If uploaded already, what is the issue that is happening. Please share a supporting screenshot.
- If above two are not the scenarios, please give more details of the issue

**Comment by nyusra** [comment]
Classification: Confidential
Hi Sai,

Thanks for the response will get back to you soon with requested information.

Adding my Peer @Dinesh Chandrakant ***@***.***>.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by nyusra** [comment]
Classification: Confidential
Hi Sai,

Please let us know if you had a chance to check on the details shared below.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]




From: Dinesh Chandrakant Konkar ***@***.***>
Sent: Thursday, May 4, 2023 6:55 PM
To: Najmul Irfan ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hello Sai,
Greetings!
We have following below KB for CC implementation.
We have completed Azure registration but Azure subscription not happening so need your  help

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

Warm Regards,
Dinesh Konkar
UCC Services - Lead
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+919920951038
[Background pattern  Description automatically generated with low confidence]

From: Najmul Irfan ***@***.******@***.***>>
Sent: Thursday, May 4, 2023 1:01 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; Dinesh Chandrakant Konkar ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hi Sai,

Thanks for the response will get back to you soon with requested information.

Adding my Peer @Dinesh Chandrakant ***@***.***>.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by nyusra** [comment]
Hi Sai,

Good day.

Could you please advice us on this issue & help us with further proceedings?

Thanks,
Najmul Irfan

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Najmul Irfan ***@***.***>
Sent: Friday, 5 May, 2023, 3:38 pm
To: Dinesh Chandrakant Konkar ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hi Sai,

Please let us know if you had a chance to check on the details shared below.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress™
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]




From: Dinesh Chandrakant Konkar ***@***.***>
Sent: Thursday, May 4, 2023 6:55 PM
To: Najmul Irfan ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hello Sai,
Greetings!
We have following below KB for CC implementation.
We have completed Azure registration but Azure subscription not happening so need your  help

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

Warm Regards,
Dinesh Konkar
UCC Services - Lead
HCLTech
Supercharging Progress™
hcltech.com<http://www.hcltech.com/>
+919920951038
[Background pattern  Description automatically generated with low confidence]

From: Najmul Irfan ***@***.******@***.***>>
Sent: Thursday, May 4, 2023 1:01 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; Dinesh Chandrakant Konkar ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hi Sai,

Thanks for the response will get back to you soon with requested information.

Adding my Peer @Dinesh Chandrakant ***@***.***>.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress™
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by nyusra** [comment]
Classification: Confidential
Hi Sai,

Thanks for the response, Can we have a call either today or tomorrow as per your feasibility so that we can get this addressed in one go?

Once you share you time window will send out an invite with link to join the meeting.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
@nyusra , Before proceeding to the call. Please elucidate on the issue so that it would be helpful for better troubleshooting

**Comment by nyusra** [comment]
Classification: Confidential
@Dinesh Chandrakant ***@***.***>

++ Adding my peer here.

**Comment by nyusra** [comment]
Classification: Confidential
@Dinesh Chandrakant ***@***.***>,,

Please provide your inputs so that we can schedule a call & get this resolved as quickly as possible.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by nyusra** [comment]
Classification: Confidential
Hi Sai,

Please let us know if you had a chance to check on the below details share below.

Also kindly let us know your feasible time for a meeting today or tomorrow. Awaiting response.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]




From: Dinesh Chandrakant Konkar ***@***.***>
Sent: Monday, May 15, 2023 6:37 PM
To: Najmul Irfan ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hello Sai,
Greetings!
As we mentioned in our earlier email we followed the  below KB for CC implementation.
We have completed Azure registration but Azure subscription not happening so need your  help. Can we have call so I cam explain better

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide



Warm Regards,
Dinesh Konkar
UCC Services - Lead
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+919920951038
[Background pattern  Description automatically generated with low confidence]

From: Najmul Irfan ***@***.******@***.***>>
Sent: Thursday, May 11, 2023 7:47 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; Dinesh Chandrakant Konkar ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
@Dinesh Chandrakant ***@***.***>,,

Please provide your inputs so that we can schedule a call & get this resolved as quickly as possible.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Generally App registration doesn't require the subscription to be there but as you have mentioned subscription issue is observed for 2nd step as per deployment guide. What is the error observed. Supporting screenshot would be more helpful for better troubleshooting.

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Dinesh Chandrakant ***@***.***>,

Could you please share the error observed with screenshot as requested below?



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Sai ***@***.***>,

Please let us know your feasible time for a short call to understand this issue?



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]




From: Dinesh Chandrakant Konkar ***@***.***>
Sent: Monday, May 22, 2023 5:12 PM
To: Najmul Irfan ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hello All,
We are following the KB "https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide" to configure the company communicator.
We have successfully completed the app registration but we are failed to complete the second steps Deploy Azure subscription.  When we try to click Deploy to azure we are getting screen mentioned in screenshot 2
We are not sure what we have select there.

Screenshot 1

***@***.***

Screenshot 2

***@***.***


Warm Regards,
Dinesh Konkar
UCC Services - Lead
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+919920951038
[Background pattern  Description automatically generated with low confidence]

From: Najmul Irfan ***@***.******@***.***>>
Sent: Monday, May 22, 2023 2:04 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; Dinesh Chandrakant Konkar ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hi @Dinesh Chandrakant ***@***.***>,

Could you please share the error observed with screenshot as requested below?



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Hi @nyusra 
Sorry, I am unable to see the screenshots that you shared as they are in a masked state. Could you please share them directly here.

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Sai ***@***.***>,

I've attached the whole email please let us know if it's clear now.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by dinesh** [comment]
Sg

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Sai ***@***.***>,

Could you please advice us further on this issue please?

Attached is the email containing the information you requested.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Hi @nyusra ,
Extremely sorry
I am not able to see the screenshots  over the mail or here. Please send those screenshots here in doc format. If they are considered as confidential please keep the document in this thread once I acknowledge it you can delete them.
<img width="738" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/78060281-9068-4322-bdaa-5939602f977c">

**Comment by nyusra** [comment]
Classification: Public
Hi @Sai ***@***.***>,

PFA doc with the details & screen shot. Kindly do the needful.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by v-jaygupta** [comment]
@nyusra ,

We are unable to receive the attachments via email. Requesting you to add the attachments directly to the[ Issue #1027](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1027) thread on GitHub.

**Comment by nyusra** [comment]
![MicrosoftTeams-image (1)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/132257367/1a37a486-3749-4736-9987-8b0f9f0c9d01)
![MicrosoftTeams-image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/132257367/3a2a7fb9-799c-41d4-a9d0-171ad0ef3a9e)

**Comment by nyusra** [comment]
We are following the KB “[https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2FDeployment-guide&data=05%7C01%7Cnajmul.irfan%40hcl.com%7Ce84709e9f1e44534695908db5ab99898%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C638203525403261336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JkV08QUo%2BYqBl4AsjmVg2AlqOsN5XsuB1q%2B%2BCZlr1No%3D&reserved=0)” to configure the company communicator.

We have successfully completed the app registration but we are failed to complete the second steps Deploy Azure subscription.  When we try to click Deploy to azure we are getting screen mentioned in screenshot 2

We are not sure what we have select there.

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Sai ***@***.***> @***@***.***>,

I've attached the screenshot's on the case directly. Kindly check & let us know when can we have a call today / tomorrow?

We are working from 12:30 PM IST to 9 PM IST. Will share an invite once you confirm the time window. Awaiting response.


Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Hi @nyusra,
Please try this link -[deploy to azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOfficeDev%2Fmicrosoft-teams-company-communicator-app%2Fmain%2FDeployment%2Fazuredeploy.json)

**Comment by nyusra** [comment]
Classification: Confidential
Adding -- @Dinesh Chandrakant ***@***.***>,

**Comment by nyusra** [comment]
Classification: Confidential
Hi Sai,

This is link the same which we already have. I've already sent an invite now please let us know if its feasible for your time & if its ok then request you to join.

Incase you need an another time kindly suggest the window.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Sai ***@***.***>,

We are waiting for you to join the call.

Thanks in advance for your support.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]




From: Najmul Irfan
Sent: Thursday, June 8, 2023 10:21 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>; Dinesh Chandrakant Konkar ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] add Company Communicator to MS Teams (Issue #1027)

Classification: Confidential
Hi Sai,

This is link the same which we already have. I've already sent an invite now please let us know if its feasible for your time & if its ok then request you to join.

Incase you need an another time kindly suggest the window.



Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Hi @nyusra ,
It is permitted to schedule a call from your side. Please provide your outlook id(mail id) we will do the necessary

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Sai ***@***.***>,

Thanks for the response. Please send an invite for Monday 2:30 PM IST time, as my peer Dinesh is on leave for this week & his presence is needed for the call.


Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Please send the mail id(outlook id) so that I can do the necessary.

**Comment by nyusra** [comment]
Classification: Confidential
Hi @Sai ***@***.***>,

Here are the id's.

***@***.******@***.***>
***@***.******@***.***>

please share an invite at 2:30 PM IST Tuesday 20th June.


Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Hi @nyusra ,
During our entire conversation, we have not received actual email IDs or Outlook IDs due to the masked format of the provided information. Instead of forwarding or writing emails, I kindly request you to share the Outlook ID directly as a comment on the GitHub platform. This will allow us to internally discuss the issue in a seamless manner.

Thank you.

**Comment by nyusra** [comment]
Classification: Confidential
Hi sai,

Sure let me do as you mentioned below.

**Comment by nyusra** [comment]
Here are the id’s.

 

[Najmul.irfan@hcl.com]

[dineshchandra.konka@hcl.com]

 

>>>>>>>  please share an invite at 2:30 PM IST Tuesday 20th June.

Thanks.

**Comment by nyusra** [comment]
Hi Sai,

As  advised by you we are working with our AD team to add a subscription to dinesh's account & proceed further.

Will keep you posted soon on the update. Thanks for your support

**Comment by gsv022** [comment]
Hi @nyusra ,
As per our discussion in the call, once the [pre-requisites](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#prerequisites) for the CC are fulfilled, kindly proceed with the remaining steps of deployment.

For now, we will be closing this ticket as we have addressed your query. If you encounter any issues during the deployment process, please feel free to log a new issue. We are more than happy to assist you.

Wishing you a smooth and successful deployment!

**Comment by nyusra** [comment]
Classification: Confidential
Hi Sai,

Sorry to say this but, issue is not resolved yet. And how can you close the case with out any intimation.

Yesterday itself I updated the case directly in portal that we are working on your advice & shall keep you posted.

Kindly reopen the case & hold for a while will keep you posted.

Note: Please do a reply all to this email always.

Warm Regards,
Najmul Irfan
UCC Services
HCLTech
Supercharging Progress(tm)
hcltech.com<http://www.hcltech.com/>
+918123458040
[Background pattern  Description automatically generated with low confidence]

**Comment by gsv022** [comment]
Hi @nyusra ,
As per the discussion in the call,  for the subjected issue we recommended you to gather all the prerequisites necessary for deploying CC. Once the deployment is started and face any issues please raise a new one, we are happy to assist you.
