### ISSUE TITLE
List of users

### ISSUE THREAD

**Issue by ricbm11** [OfficeDev/microsoft-teams-apps-company-communicator#1030]
Hi, I did the deploy and I'm doing tests. I cannot insert a recipient group as shown in the figure. I may be forgetting to do something, I will be very grateful if someone can help me. Thanks. The sender UPN list it is ok !

![image](https://user-images.githubusercontent.com/104456849/235922906-259cea78-a2cb-412a-8896-6aeb9d4d1ec5.png)

**Comment by GhustintheWizard** [comment]
I am having the same issue (deployed yesterday, 05/02.)

![CC_Authors](https://user-images.githubusercontent.com/20958145/236052576-221fc176-6f01-4105-970d-a0f33d4630f2.PNG)

**Comment by gsv022** [comment]
Hi @ricbm11 ,
Thanks for raising the query. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by ricbm11** [comment]
Hi, @gsv022 tks for your suport and my apology , your comment work well. But, now I receive a new error when I send a message. 

![image](https://user-images.githubusercontent.com/104456849/236295400-70d0cf8e-35c1-4a32-8f18-19b6a9d81989.png)

I created a new Issues about this error.
