### ISSUE TITLE
CC Deployment Failure

### ISSUE THREAD

**Issue by pgriziotti** [OfficeDev/microsoft-teams-apps-company-communicator#1031]
Deploying the company communicator the AppService sync fails, 

![image](https://user-images.githubusercontent.com/73021448/236250019-274b40eb-597a-4b24-a99d-4ca62b300ae8.png)

looking at the sync logs there are several errors shown below

Is anyone having the same problem? Has anyone solved this yet?
[Issue.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11398876/Issue.txt)

Thank you

npm http GET https://registry.npmjs.org/types/color-hash
**npm ERR! Error: 3124:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:openssl\ssl\s23_clnt.c:602:
npm ERR! 
npm ERR!     at CleartextStream._puller (tls.js:501:24)
npm ERR!     at CleartextStream._pull (tls.js:432:19)
npm ERR!     at SecurePair.cycle (tls.js:727:20)
npm ERR!     at EncryptedStream.write (tls.js:130:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!     at Socket.emit (events.js:67:17)
npm ERR!     at TCP.onread (net.js:367:14)
npm ERR!  [Error: 3124:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:openssl\ssl\s23_clnt.c:602:
npm ERR! ]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>**

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-audit"
npm ERR! cwd C:\home\site\repository\Source\CompanyCommunicator\ClientApp
npm ERR! node -v v0.6.20
npm ERR! npm -v 1.1.37
npm ERR! message 3124:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:openssl\ssl\s23_clnt.c:602:
npm ERR! message

**Comment by gsv022** [comment]
Hi @pgriziotti,
Thanks for raising the query. Please follow the below steps.

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select  App Service from list of resources
- Go to configuration section-->Add the below parameter.
**WEBSITE_NPM_DEFAULT_VERSION: 8.19.2**

- Save it
- Then go to deployment center-->Do SYNC again.

Hope it helps.

**Comment by pgriziotti** [comment]
It works!
Thanks a lot!

**Comment by gsv022** [comment]
Hi  again @pgriziotti ,
Please let us know if you have any queries otherwise we make it to closure.

**Comment by pgriziotti** [comment]
You can close, Thanks again!
