### ISSUE TITLE
Error When I send a message.

### ISSUE THREAD

**Issue by ricbm11** [OfficeDev/microsoft-teams-apps-company-communicator#1032]
Hi When I send a message I receive this error bellow.

![image](https://user-images.githubusercontent.com/104456849/236291703-bc477581-86ab-4c25-a9fd-4b74a55dfedc.png)

**Comment by gsv022** [comment]
Hi @ricbm11 ,
Thanks for raising the query. We are testing this scenario from our end and will keep you posted.

**Comment by gsv022** [comment]
@ricbm11 ,Could you please respond to the below queries.

- Is this issue happening for all sending options?
- Is this the first message?
- What is the version of the app?
- Please verify the configuration end-end  once again

**Comment by ricbm11** [comment]
I did a fresh install and it fixed it.
