### ISSUE TITLE
Company Communicator App not working in Production Environment 

### ISSUE THREAD

**Issue by ayushsaxena21** [OfficeDev/microsoft-teams-apps-company-communicator#1033]
We have Company Communicator App version 4.1.3 installed for Microsoft Teams however, it has stopped working from Author and End User aspect. We are getting 500 Response code when accessing Author app as Tab.    

[https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview](url)
![CC app error](https://user-images.githubusercontent.com/132606440/236293002-c17c426e-00c2-4b17-84b2-2a9daa63a80f.png)

**Comment by gsv022** [comment]
Hi @ayushsaxena21 ,
Thanks for raising the query. Could you please check and confirm the working status of CC app by opening in browser.  Please let us know if the same issue appears.

**Comment by ayushsaxena21** [comment]
Hello Sai,

This issue can be replicated with web and desktop client both.

Thanks & Regards,
Ayush Saxena

**Comment by gsv022** [comment]
@ayushsaxena21 , Could you please share a screenshot of the working status of CC in your browser

**Comment by gsv022** [comment]
Hi @ayushsaxena21 ,
- What is the version of the app?
-Could you please check app secrets. There is a chance that they might have expired

**Comment by ayushsaxena21** [comment]
Hello Sai,

Our version is 4.1.3 and secret key is active.

Thanks & Regards,
Ayush Saxena

**Comment by gsv022** [comment]
Hi @ayushsaxena21 ,
Please share the repo URL and branch that has been used to deploy CC-v4.1.3

**Comment by gsv022** [comment]
@ayushsaxena21 , Could you please share the repo url and branch that has been used for deploying CC.
