### ISSUE TITLE
App not getting upgraded after running .NET 6 migration script

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#1034]
I successfully ran the .Net 6 migration script by following the steps given the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) for v5.0 to v5.3.
I am able to see the .Net 6 version and runtime version 4 in Azure. But still the app does not have the latest features.

I have already tried sign out and sign in again to Teams application, also cleared the Teams cache. Still the app is not upgraded to v5.3.
Can you please assist on this?

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thank you for raising the query. Could you please provide supporting screenshots that show the function apps runtime version is approximately 4, and that the app service is compatible with .NET 6? This will help us investigate the issue further.

**Comment by PrithuMahisha** [comment]
Please find the screenshots below.
![image](https://user-images.githubusercontent.com/15922771/236796747-961e999d-ec9f-4b44-9473-142aad609fdc.png)

----------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/15922771/236799105-ad799ca7-9db1-470b-aa43-3a1b36543e3a.png)

**Comment by PrithuMahisha** [comment]
@gsv022 , I just noticed that I am getting this message in all the functions. Can you please guide me on how to resolve this?

![image](https://user-images.githubusercontent.com/15922771/236799530-9c5ad5b8-ee65-40fd-b495-f5df496591e7.png)

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Once the migration steps are performed. Please do restart the function apps. And for app service please do SYNC again.
To do that Go to  App service deployment center--> Click on SYNC. 

Please let us know if the issue persists

**Comment by PrithuMahisha** [comment]
@gsv022 Messages are also not being sent from the Author app. Status is showing 'Queued'. We suspect that this could be because of the error message received in the Azure functions. 
Please assist.

**Comment by gsv022** [comment]
@PrithuMahisha , Please provide your outlook id so that we can discuss the issue internally.

**Comment by PrithuMahisha** [comment]
@gsv022 Please schedule a call for tomorrow 12-May-2023 at 3.30PM IST.
Email ID: CompanyCommTest@devtenanttesting.onmicrosoft.com

**Comment by gsv022** [comment]
Following the issue internally

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
