### ISSUE TITLE
The redirect URI specified in the request does not match the redirect URIs 

### ISSUE THREAD

**Issue by erctechdev** [OfficeDev/microsoft-teams-apps-company-communicator#1035]
Hi folks,
In the first attempt to deploy CC,  sign in wasn't working and the error was 'App resource defined in manifest and iframe origin do not match'.  So that install was deleted and did a fresh set up from scratch. However, experiencing the exact same issue. 

It complains :

'AADSTS50011: The redirect URI '**https://xxxxxxxxxxxx.azurewebsites.net/signin-simple-end**' specified in the request does not match the redirect URIs configured for the application '99b2112e-4210-464c-97e9-7067bbf4621c'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.' 

However, I've checked and double checked the URI and it is set properly. 
I managed to get the URL that contains the actual uri and it is correctly set. 

https://login.microsoftonline.com/[removed for security]/oauth2/v2.0/authorize?**redirect_uri=https%3a%2f%2f[removed for security].azurewebsites.net**%2fsignin-simple-end&client_id=99b2112e-4210-464c-97e9-7067bbf4621c&response_type=id_token&response_mode=fragment&scope=https%3a%2f%2fgraph.microsoft.com%2fUser.Read+openid+profile&nonce=[removed for security]&state=e4bf1987-cdc3-4c5f-8d01-83c1d6e81793&login_hint=[removed for security]

Is there a possibility that our firewall or proxy may be interfering?  
I can't see anything wrong with the set up and configuration. All the secrets and bot IDs match etc. 
Would anyone have any idea as to what is blocking / stopping it from working?

Much thanks,
Alan

**Comment by erctechdev** [comment]
Hiya,
Here are the screen shots as requested,
much thanks.
<img width="439" alt="Deployment_centre_01" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131354948/8473838a-9196-4602-9a41-6062d635507a">
<img width="616" alt="Deployment_centre_02" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131354948/ca092ccc-8fb1-4394-8978-9b7db4ad0561">

**Comment by gsv022** [comment]
Thanks for sharing the zip files. Could you please share the application insight logs.
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat.
<img width="605" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/25b36a22-887e-48c3-b38a-2312273c5263">

**Comment by gsv022** [comment]
@erctechdev ,
Please share your outlook id so that we can discuss the issue internally.

**Comment by erctechdev** [comment]
Hi Sai,
Could you just clarify what you mean by Outlook ID?  Do you request an email address for discussion via that channel?
Thanks
Alan

**Comment by gsv022** [comment]
Please share your mail id(outlook id) so that we can continue the conversation internally via Teams platform

**Comment by erctechdev** [comment]
Sorry, but don't follow what this is. In terms of what 'Outlook id' is, can you treat me as an absolute beginner here and explain exactly what it is and what you require as I'm not familiar with this? Much appreciated!

**Comment by erctechdev** [comment]
Ok, I have a Microsoft email account that I can share here in the public space, but I can't share my actual corporate email address. I hope this is ok. You can email me at: alanr@thedevgarden.onmicrosoft.com

**Comment by gsv022** [comment]
We have sent you a mail. Please respond to that.

**Comment by gsv022** [comment]
Following the issue internally.

**Comment by gsv022** [comment]
We are closing the issue as we have provided the required response. Please raise a new issue if you face any issue with CC. We are happy to assist you.
