### ISSUE TITLE
Getting 502 Error while deploying App

### ISSUE THREAD

**Issue by catchzafar** [OfficeDev/microsoft-teams-apps-company-communicator#1036]
Dear Team,
 We are trying to deploy the app in Azure without using PowerShell. Getting 502 error, any suggestions are welcome.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"message":"Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass348_1.<<UpdateSiteSourceControl>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl)."}]}

**Comment by gsv022** [comment]
Hi @catchzafar ,
Thanks for raising the query. Could you please send the screenshot of the failed resources. Here is the reference.
<img width="737" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/937ae90a-1f68-4233-986f-182c09f00f17">

**Comment by catchzafar** [comment]
Please find the error screenshot

![CC-App-Error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/19735599/93f23268-5d07-4cdb-a096-3f74ecf2375c)

**Comment by catchzafar** [comment]
I have tried redeploying today and got a different issue, Please find the details:

{"code":"BadRequest","message":"There was a conflict. Conflict with existing ScmType: ExternalGit","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"},{"code":"BadRequest"},{}]}

Screenshot:

![CC-App-Error-New](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/19735599/46b7551e-9eae-4cc7-b27a-c766eb6b5d4a)

**Comment by catchzafar** [comment]
Hi @gsv022,
 Thanks for the previous reply, I tried the option and again deployed and got a different error, please find the detail below:

{"code":"BadRequest","message":"There was a conflict. Conflict with existing ScmType: ExternalGit","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"},{"code":"BadRequest"},{}]}

![503-Error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/19735599/777f6de8-3692-4c81-ab3d-ff9d42bf50f8)

**Comment by gsv022** [comment]
@catchzafar , please follow the above steps. The app service(web app) got failed. Please sync it. To reach webapp, please follow the above steps that I provided. Once the status turns success then proceed with the remaining steps of deployment.

**Comment by catchzafar** [comment]
Thanks @gsv022, I have tried Sync and Status is showing success in the logs tab. I will try the next steps.

**Comment by gsv022** [comment]
Please let us know if you have any issues otherwise we will make it to closure.

**Comment by gsv022** [comment]
Please raise a new request if you face any issue- further. We are happy to assist you. We will be closing this issue as we have given required response.

**Comment by catchzafar** [comment]
Thanks @gsv022, App installed successfully.
