### ISSUE TITLE
Message Error

### ISSUE THREAD

**Issue by ricbm11** [OfficeDev/microsoft-teams-apps-company-communicator#1037]
Hi Everyone! 
It´s my first deploy the app by Powershell and I receive this error bellow:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/104456849/81f2feba-3c0f-4260-b635-fefa2268712a)

**Comment by gsv022** [comment]
Hi @ricbm11 ,
Thanks for raising the query. Could you please try deploying the CC using manual deployment guide. Here is the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki)

**Comment by ricbm11** [comment]
I did a fresh install and it fixed it.
