### ISSUE TITLE
Error while sending the message on the app

### ISSUE THREAD

**Issue by johnadetola** [OfficeDev/microsoft-teams-apps-company-communicator#1039]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/90269279/ceeedc84-b90d-42a0-9d87-db748ace27d5)
This was the error i encountered "Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request."

**Comment by gsv022** [comment]
Hi @johnadetola ,
Thanks for raising the query. Could you please respond to the below queries.

- Is this issue happening for all sending options?
- Is this the first message?
- What is the version of the app?
- Please verify the configuration end-end  once again

**Comment by johnadetola** [comment]
> * Is this issue happening for all sending options?
I've tried most of the options, the same response. 
> * Is this the first message?
I've not successfully send any message
> * What is the version of the app?
5.4
> * Please verify the configuration end-end  once again
I've done that.

**Comment by gsv022** [comment]
Hi @johnadetola ,
- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
Author-multiple
User-multiple
Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

**Comment by gsv022** [comment]
Could you please let us know the status of the issue otherwise we will make it to closure

**Comment by johnadetola** [comment]
I've checked that, the supported type is the same as suggested by you.

**Comment by gsv022** [comment]
Hi @johnadetola,
Could you please share the screenshot of Company Communicator UI

**Comment by gsv022** [comment]
Please respond to the above query otherwise we come to conclusion that the issue has been resolved and make it to closure.
