### ISSUE TITLE
Why res group Contribute permissions are not enough

### ISSUE THREAD

**Issue by funzel1** [OfficeDev/microsoft-teams-apps-company-communicator#1043]
Our developers do not have 
 'Microsoft.Authorization/roleAssignments/write role
 What the reason why Contribute is not enough ?
 Access management  is forbidden for developers.

**Comment by gsv022** [comment]
Hi @funzel1 ,
Thanks for raising the query. Could you please elaborate more on the issue

**Comment by funzel1** [comment]
It is related to article 
Goto the subscription page in Azure portal. Then, goto Access Control(IAM) and click on View my access button.
Click on your role and in search permissions text box, search for Microsoft.Authorization/roleAssignments/Write.
If your current role does not have the permission, then you can grant yourself the built in role User Access Administrator or create a custom role.
and error message if missing
az : ERROR: {"error":{"code":"InvalidTemplateDeployment","message":"Deployment failed with multiple errors: 'Authorization failed for template resource '**************cdcada' of type 'Microsoft.Authorization/roleAssignments'.

**Comment by v-royavinash** [comment]
@funzel1 Please refer our [Prerequisites](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#prerequisites). RBAC role is require to create and assign roles while creating the resources during deployment.  

Only having contributor access will throw the errors while deployment and for now we don't have any workaround to it.

**Comment by funzel1** [comment]
Understood, so I have to find a solution , like a pipeline with the required permissions or splitting the deployment
because role and permission management is a SOX controlled  process in our company and reason why most people have only contribute.
You can close. Thanks a lot
