### ISSUE TITLE
Company communicator permanently sending

### ISSUE THREAD

**Issue by iainRclark** [OfficeDev/microsoft-teams-apps-company-communicator#1044]
We have deployed a second instance of company communicator v5.1.

When a message is sent, no matter how (to channel, individuals, etc.), the message status proceeds to 'Sending... 0 of 5' and goes no further. When cancelling a message it remains in the 'Canceling' status. There are no warnings or errors shown on the message in teams, and no errors that I can find in azure.

I have resynced all function apps and the service app and no success. I have however noticed that all the logs are empty and have the message 'No deployments found. If you have just configured CI/CD, refresh logs to find the latest deployments.'.

<img width="686" alt="TeamUI" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/6458861/68d97c6a-702e-474e-b0c8-360db72bbfb8">

Any help would be appreciated.

**Comment by ngaither19** [comment]
I have found the same trouble in my deployment when "proactivelyinstallapp" is set to true. I set it to false, restarted all the endpoints, then setup a teams app policy to push the app. Messaged successfully sent after that.

**Comment by gsv022** [comment]
Hi @iainRclark ,
Thanks for reaching out to us. As you mentioned the version deployed was v5.1. Upon sync of all function apps, app service updated the latest version. Could you please check this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) whether these mentioned steps are followed correctly or not.

**Comment by iainRclark** [comment]
Thanks for the suggestions.

> I have found the same trouble in my deployment when "proactivelyinstallapp" is set to true. I set it to false, restarted all the endpoints, then setup a teams app policy to push the app. Messaged successfully sent after that. @iainRclark

Set "proactivelyinstallapp" to false, restarted functions and service, and verified app policy was set to push app. Unfortunately no change.

> Hi @iainRclark , Thanks for reaching out to us. As you mentioned the version deployed was v5.1. Upon sync of all function apps, app service updated to the latest version. Could you please check this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) whether these mentioned steps are followed correctly or not.

Ran the script and followed the steps and no change.

**Comment by gsv022** [comment]
Hi @iainRclark ,
Please share the screenshots of deployment status of App Service and function apps. As you mentioned script steps has been followed, please share the function runtime version and app service .Net version as recommended in migration guide.

**Comment by iainRclark** [comment]
We just opted to do a complete redeploy without specifying version.

We now receive the following error:

The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure, Target: /subscriptions/387b269e-8136-4a24-bf56-dd7d2e660b5c/resourceGroups/pw-az-d1-m365-dev-rg/providers/Microsoft.Web/sites/pwazd1m365dev/sourcecontrols/web)

![DeployError](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/6458861/1d436c16-f3ce-4822-9435-fb1c58d67712)

**Comment by iainRclark** [comment]
We were able to get this deployed, issue had to do with our network preventing syncing.

Thanks,
