### ISSUE TITLE
Click-to-button tracking

### ISSUE THREAD

**Issue by lgarciab0717** [OfficeDev/microsoft-teams-apps-company-communicator#1045]
Do I need to keep track of the messages read and the clicks on the buttons added in the messages, how can I do it?

**Comment by gsv022** [comment]
Hi @lgarciab0717 ,
Thanks for reaching out to us. The message reads, clicks are the features yet be added to CC. Since this feature is already added to our backlog and will be considered in future releases of CC based on the priority.

**Comment by v-royavinash** [comment]
@lgarciab0717 We are closing this issue as the feature has already been added to our backlog. It will be considered for future releases of CC based on its priority.
