### ISSUE TITLE
HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by ismnilsonzegarra** [OfficeDev/microsoft-teams-apps-company-communicator#1047]
I deployed the app, the deployment was correct the message is: Success (active) with message: CC v5.4 changes (#1028) * CC v5.4 changes.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/123601657/fb1bccb8-3481-4cff-9ca2-1f372d295252)

But trying to load the app i get the HTTP Error 500.30 - ASP.NET Core app failed to start.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/123601657/06195399-7a6c-4227-ba7c-7bef69a9bad2)

**Comment by gsv022** [comment]
Hi @ismnilsonzegarra ,
Thanks for raising the query. Could you please respond to the below queries.

- Is this a fresh deployment or migration from older version?
-  Could you please share the manifest files that you tried to upload.

**Comment by ismnilsonzegarra** [comment]
Hi, this is a fresh deployment using the manual deployment, the powershell deployment don't work for me (i'm in macos).

The response come when i load the webpage or when i do the step 4 from the deployment manual granting permission to the URL. 

 https://login.microsoftonline.com/common/adminconsent?client_id=%appId% 

When i do the consent, the response is this page.

The manifest generated for authors app have the same message inside, there is a way to send you the manifest on private?.

**Comment by gsv022** [comment]
Please share your outlook id so that we can discuss the issue internally

**Comment by ismnilsonzegarra** [comment]
Thanks, mi Outlook is nilson.zegarra@ism.global

**Comment by ismnilsonzegarra** [comment]
Hi, any news about it?

**Comment by gsv022** [comment]
Hi @ismnilsonzegarra , We can discuss the issue internally

**Comment by gsv022** [comment]
Hi Nilson,
Please let us know how the testing goes. If there is a issue we recommend you to go for default domain option.

**Comment by ismnilsonzegarra** [comment]
Hi, after the session to fix the setup we started with the test adding more users, at the moment the app is working fine at the moment.

Thanks for the support

**Comment by gsv022** [comment]
We are closing the issue as we have provided the required response. Please raise a new issue if you face any issue with CC. We are happy to assist you.
