### ISSUE TITLE
User-assigned vs System-assigned identites

### ISSUE THREAD

**Issue by KyleHammackRS** [OfficeDev/microsoft-teams-apps-company-communicator#1048]
Is it possible to run this application using User-assigned Identities instead of the System-assigned ones? I know I can assign the user-assigned identities to the app services and grant the user-assigned identity the same roles that are being assigned to the system-assigned identities, but will the application code support it? Is there any further configuration needed to make it work?

**Comment by gsv022** [comment]
Hi @KyleHammackRS ,
Thanks for raising the query. Please give us sometime and we will get back to you with proper response soon

**Comment by KyleHammackRS** [comment]
@gsv022 This deployment currently deploys all resources with system-assigned identities and then assigns RBAC roles to those identities. I have need to grant a customer access to run the communicator deployment frequently who is not allowed to have access to Azure RBAC assignments. I can easily create a User-Assigned Identity, grant all RBAC roles to that User-Assigned Identity, and modify the ARM template resources to use that identity instead of the System-Assigned Identity.

My question for you is if I do that will the application still work as expected? Is there anything additional I need to do to make this work?

**Comment by v-royavinash** [comment]
@KyleHammackRS Based on the existing design, using User-Assigned Identity would not affect the functionalities. However, as our support is limited with the default implementation and without updating the deployment template and thoroughly testing the functionality we cannot confirm on this to ensure that there are no impacts on the CC functionalities.

**Comment by KyleHammackRS** [comment]
Not a problem, I already made template updates, just wanted confirmation that the code would support it, and if there were any app configs needed.

**Comment by gsv022** [comment]
Please let us know if you have any queries with the standard version of Company Communicator otherwise, we can make it to closure

**Comment by KyleHammackRS** [comment]
nope, good thanks
