### ISSUE TITLE
how to change the display name for Company communicator application

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#1049]
Is it possible to change the display name of the application in the highlighted area referred in the below screenshot? If yes, could you please provide screenshots of the corresponding parameters in Azure?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/b949d7c7-f565-4a30-bc12-135567e10fb3)

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query here. Please follow the below steps.
To update name of CC

- Login to Azure Portal with Global Admin Credentials (portal.azure.com)
- Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
-  Click on Azure Bot(user) --> under settings click bot profile-->Change display name as per the organizational need.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/98143492/213981428-e5af8e1e-8623-4731-b413-8cc62cc3c475.png">

- Please repeat the above steps for Azure Bot(Author)

- And update the icons name in the manifest files for both author and user. Re-upload the manifest files again.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/98143492/213983428-68678fb4-03ae-4a95-933e-0d8e4b4f802d.png">


**Note**:- 
- There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.

And if company communicator is of 5.x version, needs the header text needs to changed then follow this 
[link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-)
<img width="715" alt="image" src="https://user-images.githubusercontent.com/98143492/213982701-b95cb3ca-524a-4b4f-bcf0-e227f2c7f87f.png">

- To change the header text, Update the Reactapp header text as per your organizational requirement present in the configuration section of App service.
- Save it and then restart the app service.

**Comment by gsv022** [comment]
@PrithuMahisha , Could you please let us know the status

**Comment by PrithuMahisha** [comment]
Hi @gsv022, thanks for providing the inputs. I tried to change the names as mentioned. I am able to change name in React App header text. However, changing name in Azure Bot(user) --> under settings click bot profile helps to change the name only in the App store (highlighted in the image shown below), not in the intended place.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/4175148b-d6ca-450a-8fee-5a2a68d56a18)

**Comment by gsv022** [comment]
@PrithuMahisha , Please make sure that author bot profile has been updated in the resource group and if it is not reflecting try opening the web version of CC

**Comment by PrithuMahisha** [comment]
@gsv022 We have checked in web version, the header text has been changed but the Tab name is still showing the old name.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/0671165a-5229-4f6e-9358-aa3bb122c094)

**Comment by gsv022** [comment]
Please make sure that Author manifest is updated with the required names. And in the azure portal, Azure Bot(author)  is updated with the required name. These are the two places to be updated. If already done and not reflecting, please share the author manifest file and screenshot showing Bot profile section of Azure Bot(Author)

**Comment by PrithuMahisha** [comment]
Please find the below screenshots:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/89b7f523-ce34-4378-9708-8ac6ba94d1ee)
Screenshot of Manifest file:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/4abaaadd-a5c3-4e22-8a69-9f05e006fc97)

**Comment by James99IT** [comment]
> Hi @PrithuMahisha , Thanks for raising the query here. Please follow the below steps. To update name of CC
> 
> * Login to Azure Portal with Global Admin Credentials (portal.azure.com)
> * Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
> * Click on Azure Bot(user) --> under settings click bot profile-->Change display name as per the organizational need.
> 
> <img alt="image" width="749" src="https://user-images.githubusercontent.com/98143492/213981428-e5af8e1e-8623-4731-b413-8cc62cc3c475.png">
> 
> * Please repeat the above steps for Azure Bot(Author)
> * And update the icons name in the manifest files for both author and user. Re-upload the manifest files again.
> 
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/98143492/213983428-68678fb4-03ae-4a95-933e-0d8e4b4f802d.png">
> 
> **Note**:-
> 
> * There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.
> 
> And if company communicator is of 5.x version, needs the header text needs to changed then follow this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) <img alt="image" width="715" src="https://user-images.githubusercontent.com/98143492/213982701-b95cb3ca-524a-4b4f-bcf0-e227f2c7f87f.png">
> 
> * To change the header text, Update the Reactapp header text as per your organizational requirement present in the configuration section of App service.
> * Save it and then restart the app service.



> Hi @PrithuMahisha , Thanks for raising the query here. Please follow the below steps. To update name of CC
> 
> * Login to Azure Portal with Global Admin Credentials (portal.azure.com)
> * Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
> * Click on Azure Bot(user) --> under settings click bot profile-->Change display name as per the organizational need.
> 
> <img alt="image" width="749" src="https://user-images.githubusercontent.com/98143492/213981428-e5af8e1e-8623-4731-b413-8cc62cc3c475.png">
> 
> * Please repeat the above steps for Azure Bot(Author)
> * And update the icons name in the manifest files for both author and user. Re-upload the manifest files again.
> 
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/98143492/213983428-68678fb4-03ae-4a95-933e-0d8e4b4f802d.png">
> 
> **Note**:-
> 
> * There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.
> 
> And if company communicator is of 5.x version, needs the header text needs to changed then follow this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) <img alt="image" width="715" src="https://user-images.githubusercontent.com/98143492/213982701-b95cb3ca-524a-4b4f-bcf0-e227f2c7f87f.png">
> 
> * To change the header text, Update the Reactapp header text as per your organizational requirement present in the configuration section of App service.
> * Save it and then restart the app service.

Thank you for this, but also where do I re upload the manifest files after update
