### ISSUE TITLE
Communicator app "Preview new message" does not work

### ISSUE THREAD

**Issue by JasGo00** [OfficeDev/microsoft-teams-apps-company-communicator#1050]
When creating new message via the Send App using the communicator app and trying to preview the message we get following error message : _" Ooops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists."_

**Comment by gsv022** [comment]
Hi @JasGo00 ,
Thanks for raising the query. Could you please share the application insight logs. Here is the reference.
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and send it as a text file.
<img width="602" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a572c666-a35b-46d4-bdae-00cd89e93fa8">

- If there are any dependencies logs noted please share them too.

**Comment by JasGo00** [comment]
Hello
I do not see where I can copy the logs the only option to copy is the link or the message call stack for each error.

I see 9 failures for Preview Draft Notification there are 38K dependencies ...here are the screenshots:

***@***.***
***@***.***

***@***.***

**Comment by JasGo00** [comment]
here are the screenshots again 
![Failure2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/8cff2b15-253e-461e-b6cc-d2a99abdcf8f)
![Failure1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/4ef2e727-84d7-45a3-83d6-6a8ecc88c772)
![Failure3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/19f9e41b-d51e-4e19-8bd0-cf3fd0093581)

**Comment by gsv022** [comment]
Hi @JasGo00 , one query

- Please confirm whether messages are getting delivered via all sending options.

**Comment by JasGo00** [comment]
Yes messages are being delivered

Jasmin Gokovic

UC Collaboration - MS Teams/Skype Build/Design (CI/PWU4)
Robert Bosch LLC | 38000 Hills Tech Dr. | Farmington Hills, MI 48331 | USA | www.bosch.us
Tel. +1 248 310-2978
________________________________

**Comment by gsv022** [comment]
Hi @JasGo00 ,
Please check the authentication step i.e., 2nd step as per deployment guide was correctly done or not

**Comment by JasGo00** [comment]
Yes this was all done properly and it worked for few months with no issue

**Comment by gsv022** [comment]
There is a chance that app secrets might have expired. Please check and confirm

**Comment by JasGo00** [comment]
Checked all secrets and they are valid for another year, so no they have not expired

**Comment by JasGo00** [comment]
Hello
Issue was fixed by deleting the table from the database and reinstalling the Send app in the Team channel.

Thanks for your efforts


Best regards

Jasmin Gokovic

UCC Services - MS Teams/Skype Build and Design (CI/PWU4)
Mobile +1(248)310-2978 | ***@***.******@***.***>
Robert Bosch GmbH

**Comment by gsv022** [comment]
We are closing it out as the issue got resolved.
