### ISSUE TITLE
Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.

### ISSUE THREAD

**Issue by magafaterr** [OfficeDev/microsoft-teams-apps-company-communicator#1051]
Hello,

I am following the manual deployment guideline, and always get the same error message for the 3rd time, even after trying a few other recommendations that seemed to have worked for others as found on other reported issues here.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/31663497/a680b25a-d591-47b7-9543-3da27ee0b63d)

@gsv022 I noticed you have helped at least one more person with this issue, can you please provide some assistance here as well?

I bet there is more than this error,

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/31663497/d8ee12b7-9382-438d-84b9-84a93c48f25f)

**Comment by gsv022** [comment]
Hi @magafaterr ,
Thanks for logging the query. We are following this issue internally

**Comment by gsv022** [comment]
Hi @magafaterr,
Please let us know if you face any issues otherwise we can make it to closure

**Comment by magafaterr** [comment]
Thank you! This issue was resolved yes, but **unfortunately** while uploading the Authors zip I am getting an error shared via email to you @gsv022. If you have a chance and can take a look, much appreciated!

**Comment by gsv022** [comment]
@magafaterr , Please share the author manifest file

**Comment by magafaterr** [comment]
Thank you Sai Venkat , and Cristiano. I found the issue in the manifest, the app domain was not correct. This is now resolved. And you can close this open issue. I truly appreciate the amazing support!

Sent from my iPhone

On May 26, 2023, at 3:13 AM, Sai Venkat ***@***.***> wrote:

﻿

@magafaterr<https://github.com/magafaterr> , Please share the author manifest file
