### ISSUE TITLE
Deployment to european Azure Datacenter keeps failing

### ISSUE THREAD

**Issue by MSFT-klpinhac** [OfficeDev/microsoft-teams-apps-company-communicator#1052]
Hi,

trying to deploy the latest version of the Company Communicator keeps failing
( a previous deployment to the East US-Datacenter has been successful, but a deployment within europe is required due to legal reasons)

Most resources are deployed successfully, but the deployment of web app fails with errors:
`{ "status": "Failed",    "error": { "code": "ResourceDeploymentFailure", "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'." }}`
or
`{ "status": "Failed",  "error": {  "code": "BadRequest", "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",        "details": [ {  "message": "There was a conflict. Conflict with existing ScmType: ExternalGit" }, { "code": "BadRequest" }, {} ] }}`
or 
`Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway. at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at ...`

Following the [Troubleshooting#1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure) did not resolve these errors, nor did setting the official repo as source for external git in the settings of the deployment center.

**Comment by gsv022** [comment]
Hi @MSFT-klpinhac ,
Thanks for raising the query. We are making a follow up on this issue internally.

**Comment by gsv022** [comment]
The issue has been responded internally. Please raise a new issue if you face any with CC. We are happy to assist you.
