### ISSUE TITLE
Cost estimation document has misleading information

### ISSUE THREAD

**Issue by cristianoag** [OfficeDev/microsoft-teams-apps-company-communicator#1053]
Hi team. The default deployment for the Company Communicator app template enables Azure Front Door, however the cost estimate document (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Cost-estimate) just ignore that and provide the calculation without front door. 

Could you please review the document mentioning that? The estimated cost of the solution considering the default configuration is around 250, not 150 as stated.

**Comment by gsv022** [comment]
Hi @cristianoag ,
Thanks for the suggestion. We have noted your point. We will check and update the cost-estimation guide post the discussion with the team.

**Comment by gsv022** [comment]
Hi @cristianoag,
As you mentioned the default configuration is 250. Could you please provide your calculation on this. Thanks

**Comment by cristianoag** [comment]
The document is just missing the cost of azure front door and is mentioning wrongly 150 as the default configuration cost.

My ask is to review the cost document available on GitHub wiki and update it to have the correct cost for the default config.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gsv022** [comment]
Hi @cristianoag,
Sorry for the late reply. This will be acknowledged in the upcoming release of Company Communicator.

**Comment by gsv022** [comment]
Hi @cristianoag ,
Cost-Estimation guide has been updated. Please have a look and let us know if you have any queries/concerns.
