### ISSUE TITLE
Deployment form mentions that custom domains are recommended

### ISSUE THREAD

**Issue by cristianoag** [OfficeDev/microsoft-teams-apps-company-communicator#1054]
The documentation correctly states the advantages of having Azure Front Door for company communicator, however the deployment form we get when executing the default ARM deployment template states that custom domains are recommended. Could you please review that?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/48498602/77cb332a-88bd-4fb8-b60a-d76fb773647e)

**Comment by gsv022** [comment]
Hi @cristianoag ,
Thanks for highlighting. We will check on this.

**Comment by gsv022** [comment]
Hi @cristianoag ,
In the new release, the above mentioned correction has been taken care. Please let us know if you have any concerns.
<img width="474" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b7cd63a7-2e2e-4b86-af8e-1e2b33226fc9">
