### ISSUE TITLE
I can't export. (Allow button)

### ISSUE THREAD

**Issue by Fadel1949** [OfficeDev/microsoft-teams-apps-company-communicator#1056]
I can't export. (Allow button)
stuck here
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/126840838/77019d3d-0525-4f01-af83-ad2d9e468160)

But if using mobile can export but if using desktop can't.

**Comment by gsv022** [comment]
Hi @Fadel1949 ,
Thanks for raising the query. This is already a known issue. The fix has been identified. Currently it is in the phase of testing and hopefully it will be available by the end of June.

**Comment by Fadel1949** [comment]
Hi @gsv022  
Thank you

**Comment by Fadel1949** [comment]
Hi @gsv022,
Do you have any update on this issue?

**Comment by gsv022** [comment]
Hi @Fadel1949 ,
Thanks for the patience. The issue has been fixed by the concerned team. Please check and confirm the export functionality working status from your end.

Keep us posted
