### ISSUE TITLE
Hi Can add format text Like this ? how to edit

### ISSUE THREAD

**Issue by Fadel1949** [OfficeDev/microsoft-teams-apps-company-communicator#1057]
Hi Can add format text Like this ? how to edit

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/126840838/8ed7302c-85e6-44d1-888a-dcf8cab178b3)

Thank you.

**Comment by gsv022** [comment]
Hi @Fadel1949 ,
Thanks for raising the query. We have the text formatting feature already implemented, but for each formatting the buttons as you highlighted has already added to the backlog. It will implemented in the future releases of CC .
