### ISSUE TITLE
how to change the display name for Company communicator application

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#1060]
In reference to the issue raised earlier in [this ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1049)link, please find the screenshots below.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/86308388-116f-472f-9198-2ad28ce37cd5)
Screenshot of Manifest file:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/0f6a9d61-aaec-4129-ab04-bd17c9ac1d1f)

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Correct me if I am wrong. The tab name is only place not changing even after updating the manifest and bot profile section in azure portal.

**Comment by PrithuMahisha** [comment]
yes, that is correct

**Comment by gsv022** [comment]
@PrithuMahisha , we will check it out from our end and keep you posted.

**Comment by gsv022** [comment]
Hi @PrithuMahisha,
Thanks for the patience. The tab name can be changed by just expanding the dropdown and click on rename option.
<img width="659" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5ed9629d-470b-4671-83d6-fea869e32e14">

**Comment by PrithuMahisha** [comment]
It works. Thanks for providing the solution.

**Comment by gsv022** [comment]
@PrithuMahisha , we are closing this request as we have provided the inputs for the query raised. If you face any issue with Company Communicator please raise a new issue for further assistance.

Thank you
