### ISSUE TITLE
BatchRecipientsActivity failed after renewing secret

### ISSUE THREAD

**Issue by dahazeman** [OfficeDev/microsoft-teams-apps-company-communicator#1061]
There is a similar issue about this, but there are no details explaining how it was resolved. I recently had to generate a new secret for the GraphAppPassword in the key vault. I've confirmed that the GraphAppPassword in the app service and the prep service have both been updated, as well as the AzureAD:ClientSecret value in the app service. I've confirmed all other key vault values in all four services are current and correct. I've re-synced and restarted all services. Yet I still get this error when I try to push out a message:

`Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.". See the function execution logs for additional details.`

EDIT: I am not sure how to find the function execution logs. If I had those, perhaps I could resolve this on my own.

Interestingly, today I was able to preview the message in the author Team channel, whereas up until now I could not. But sending the message out to a group still failed.

[Previous issue](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/962)

The previous issue about this stated "Attended the call and resolved the issue" but there are zero details about what was done to resolve it. Any help would be appreciated, as our global HR department has been waiting for a week to get this working.

**Comment by gsv022** [comment]
Hi @dahazeman ,
Thanks for raising the query. Could you please respond to the below queries.

- What is the version of the app?
- Please share the application insight logs. Here is the reference.
Go to resource group-->Application Insights-->Under investigate click Failures. Please copy all the logs and send it in the form of file.
<img width="602" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a3e36457-14a4-4962-b739-79a97c9dfef9">

- Share the screenshot of deployment status of App service.
<img width="885" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a48666e2-5583-4575-afb9-84cc1e56be24">

**Comment by dahazeman** [comment]
Hi @gsv022 

I think we are on version 5.4.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/12838488/f6c60623-2945-40cb-bd0d-349b8c9fae32)

Is this the log information you were looking for?

[BatchRecipientsActivity_error.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11677703/BatchRecipientsActivity_error.txt)

**Comment by dahazeman** [comment]
I may have found the source of the problem, but I don't know how to resolve it. I'm new to Azure storage but I used to be a .NET developer a number of years ago.

I was toggling the log info found on the Failures page described above. I came across the following:

`11:01:59.947 AM	Request	Name: BatchRecipientsActivity, Successful request: false, Response time: 383.9 ms
11:01:59.977 AM	Trace	Severity level: Information, Message: Executing 'BatchRecipientsActivity' (Reason='(null)', Id=fba1b5d7-2176-4eda-8dd5-021da7648405)
11:01:59.996 AM	Dependency	Name: GET xxxxxxxxxxxxx/SentNotificationData, Type: Azure table, Call status: true, Duration: 10 ms, Data: https://xxxxxxxxxxxxx.table.core.windows.net:443/SentNotificationData?$filter=PartitionKey%20eq%20%272517163235375372990%27`

Then I learned about Azure Storage Explorer and installed that. When I browse to the SendNotificationData table and filter with the PartitionKey value in the above GET call, it does return zero results.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/12838488/e0eb9c2c-327c-46f0-8eb8-c05bda462f90)


Where is that PartitionKey value defined for the current process? Is it a configuration value, or linked to the current message that is being sent out?

**Comment by dahazeman** [comment]
I just noticed that the entire SentNotificationData table has not been updated since BEFORE I changed the GraphAppPassword client secret. I assume this is because the send function is failing and never getting around to logging anything.

**Comment by gsv022** [comment]
We notice that there is a version change from time to time. Could you please confirm if the migration steps were followed correctly. If yes, please share the screenshots as mentioned in the [v5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version) migration guide.

**Comment by dahazeman** [comment]
Hello @gsv022 
Everything was working until the GraphAppPassword client secret expired. The last upgrade I performed explicitly was in December 2022 as seen in the screenshot above. Everything was definitely working fine after that, up until this client secret expiration. I only noticed the version number of 5.4 when you asked which version we were using, and since I saw it in that screenshot, I assumed that it occurred as some sort of automatic update when I initiated the redeployment on June 5, 2023 in an attempt to get things moving.

What do you suggest? Should I be going through the upgrade process as if I had mad a conscious decision to upgrade from 5.3 to 5.4, even though I didn't actually initiate that upgrade to get to where we are?

**Comment by dahazeman** [comment]
Hello @gsv022 
I went through the upgrade steps in the v5 migration guide. Most configuration items were already set correctly, since it was coming from v5.3 to v5.4. Once the app service and all three functions had re-synced, and been restarted, I signed out and back into Teams. I then attempted to send a message to a small recipient list (members of the CC authors Team). I received the exact same error as mentioned in the initial post on this thread.

**Comment by dahazeman** [comment]
Does anyone else have any ideas? This has been going on for weeks and our global HR department is getting pissed that they can't send out any messages. One suggestion every three days is not very helpful  to me at this point. Please help.

**Comment by dahazeman** [comment]
Sure, but I'm deleting this comment as soon as you contact me @gsv022 

jason.gingrich@sonova.com

**Comment by gsv022** [comment]
I have noted the id

**Comment by dahazeman** [comment]
Today I reviewed the v5 upgrade instructions again. Everything was fine. So then I reviewed the initial installation instructions. I found that the app registration authentication was no longer configured. https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication
I also found that the graph app permissions were lost and had to be re-selected and re-granted. https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app

After restarting the app service and the functions, I signed out and back into Teams. I tried sending a message again. It gave me an error on this call: GET /api/groupdata/verifyaccess
The client secret for the app registration which I had regenerated the other day was expired again...or so the message stated. The secret I had generated the other day was still there and valid. So I removed the 5 or 6 expired secrets and retried sending the message again. This specific error did not appear again, but I'm back to the very beginning of this thread...with the same error on the same BatchRecipientsActivity.

So around the circle we go again...

**Comment by dahazeman** [comment]
Thanks to @gsv022 for taking the time to contact me and go through our app instance. In the end, it turns out the client secrets for all three app registrations (primary app, authors, users) had expired.

In the app service config, find values for AuthorAppId, GraphAppId and UserAppId. Search app registrations for those three guid's. Each app registration has a client secret. When they expire, generate a new one and copy the value. Delete all expired secrets. Browse to the resource group for your app and find the key vault. Create new entries for each of: AuthorAppPassword, GraphAppPassword and UserAppPassword using the copied values from the new secrets (not the secret ID!! - be sure to enter the secret value). Set all old vault secret entries to Disabled. Copy the Secret Identifier for the enabled and current secret for each password. Paste those Identifiers (URL's) back in the app service and three functions, under AuthorAppPassword, AzureAd:ClientSecret (mapped to the Graph App password), GraphAppPassword and UserAppPassword. After updating the values on each of the app service and functions, save each and restart each (from the Overview page).

**Comment by dahazeman** [comment]
Issue resolved

**Comment by Theoroi-MS** [comment]
Reminder: There are one Web App and multiple Function Apps in this solution. 
When client secrets expires, it needs to be renewed and updated on all Web App and Function Apps. 
The error message is thrown by one of the Function Apps.
