### ISSUE TITLE
Deployment Failed - Microsoft.Web/sites/sourcecontrols - badrequest

### ISSUE THREAD

**Issue by Mubarak86** [OfficeDev/microsoft-teams-apps-company-communicator#1062]
Resource: BaseResourceName/WEb

Type: Microsoft.Web/sites/sourcecontrols

Status : BadRequest

{"code":"BadRequest","message":"There was a conflict. Conflict with existing ScmType: ExternalGit","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"},{"code":"BadRequest"},{}]}

**Comment by gsv022** [comment]
Hi @Mubarak86 ,
Thanks for raising the query. Please perform the below procedure.
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select  App Service from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository.
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.

Hope we conveyed.

**Comment by Mubarak86** [comment]
I got the same error even after updated repository in App Service

**Comment by Mubarak86** [comment]
![Capture](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/37930899/d7004e2d-d08f-447d-89c7-1ac88ab0b2df)

**Comment by gsv022** [comment]
@Mubarak86 , once after following the above-mentioned procedure, please don't for re-deploy again. Upon app service/web app gets successful proceed with the next steps of deployment

**Comment by gsv022** [comment]
Please share your outlook id(mail id) so that we can discuss the issue internally.

**Comment by Dave365CH** [comment]
What was the solution here? I got the same problem.
