### ISSUE TITLE
Powershell deploy method fails if Azure CLI > 2.36.0 installed.

### ISSUE THREAD

**Issue by nmarsham-jhg** [OfficeDev/microsoft-teams-apps-company-communicator#1064]
Issue:
If an Azure CLI version newer than the April 2022 release is installed, Azure app creation via the powershell deploy script will fail with the following message:

`ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False`

This is presumably due to the breaking change announced at the following URL: https://learn.microsoft.com/en-us/cli/azure/microsoft-graph-migration

Reproduction:
Attempt to run the powershell deploy.ps1 on any machine that already has an up-to-date version of the Azure CLI tool installed.

Workaround:
Uninstall up to date version of Azure CLI, and install version 2.36.0 available at https://azcliprod.blob.core.windows.net/msi/azure-cli-2.36.0.msi

**Comment by gsv022** [comment]
Hi @nmarsham-jhg ,
Thanks for raising the query. The present code is compatible with  Azure CLI 2.30.0.  After 2.30.0 of CLI i.e., >2.30.0 version the parameter(--available-to-other-tenants) has been changed. This is the reason for updated version of CLI it shows as unrecognized arguments. If the parameter has been updated with latest one then the previous version of CLI will start breaking.

So the workaround is to go for uninstalling the latest version of CLI and install 2.30.0 CLI version then go for PowerShell deployment.

Hope I conveyed.

**Comment by gsv022** [comment]
@nmarsham-jhg , please let us know if you have any queries.

**Comment by nmarsham-jhg** [comment]
Hey @gsv022  -- using a down-level version of Azure CLI is absolutely a workaround, but it's not a fix.

For any company that manages the versions of their tooling, having a specific more than one-year-deprecated version of the Azure CLI required for irregular deployments of the company communicator app is a non-starter.

The correct fix in this instance would be to update the azcli commands to the current non-deprecated versions, and to have the deployment script check for the azcli version and fail if outdated.

Failing with an unhandled error is certainly not the correct way to handle the problem.

**Comment by spikedfuel** [comment]
Hi @gsv022  -- looks like the pre-run script is now saying that 2.36.0 isn't new enough and 2.49 is required to run the script:
**********************
Windows PowerShell transcript start
Start time: 20231106114845
Username: xxxx
RunAs User: xxxx
Configuration Name: 
Machine: xxxxxxxx (Microsoft Windows NT 10.0.22621.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 5980
PSVersion: 5.1.22621.2428
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2428
BuildVersion: 10.0.22621.2428
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\xxx\Documents\PowerShell_transcript.xxx.pHR8dww8.20231106114845.txt
PS C:\xxx\TeamsCommunicator\microsoft-teams-apps-company-communicator-main\Deployment> az --version
azure-cli                         2.36.0 *

core                              2.36.0 *
telemetry                          1.0.6 *

Dependencies:
msal                              1.17.0
azure-mgmt-resource               20.0.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\xxx\.azure\cliextensions'

Python (Windows) 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 22:57:10) [MSC v.1929 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


You have 3 updates available. Consider updating your CLI installation with 'az upgrade'

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
PS C:\xxx\TeamsCommunicator\microsoft-teams-apps-company-communicator-main\Deployment> .\deploy.ps1
Checking if Azure CLI is installed.
Please make sure the installed version of Azure CLI is 2.49.0 or higher.
You have version  installed.
Please refer to the prerequisites section of powershell deployment guide
PS C:\xxx\TeamsCommunicator\microsoft-teams-apps-company-communicator-main\Deployment> Stop-Transcript
**********************
Windows PowerShell transcript end
End time: 20231106114903
**********************

**Comment by gsv022** [comment]
Hi @nmarsham-jhg ,
We are closing this issue as it has been added to backlog and will be planned in the future releases of CC based on priority

**Comment by allthetrouts** [comment]
this should be re-opened. You guys need to actually fix this app. Why do I need to edit the file because cli after 2.32 doesnt work, but yet you require 2.49 + in your code. Like come on, I deploy dozens of apps daily and this is the absolute worst one everytime an update comes up.
