### ISSUE TITLE
User cannot receive messages by company communicator

### ISSUE THREAD

**Issue by motley2546** [OfficeDev/microsoft-teams-apps-company-communicator#1066]
Dear support,

I tried to find a similar issue in previous thread but I couldn't find any solution.
We are trying to troubleshoot a problem that is having a user in our company. No one complained about the same issue so far, so we assume that it is the only case.

The communicator worked for the user before the last October, then it just suddenly stopped.

We are currently distributing the app using the global application permission policy, and install on their clients using setup policy in Teams

Below the checks and tests we made.

We checked if the user had blocked ti application.
We tried to remove the user from the app permission policy.
We tried to create personalized App permissions and setup policies to install manually the app using powershell.
We tried to add the user to a group and to send the notifications to the group.

Every time we tried to reinstall the app we noticed that it always gets the same ID.

Is there any other method we can try?

Thank you in advance for your help!

**Comment by gsv022** [comment]
Hi @motley2546 ,
Thanks for raising the query. Could you please respond to the below queries.

- Please share the export results where the specified user is present 
- And share the latest export result where the specified user is not receiving the message.
- What is the version of the app?
- Is that specific user still active in the organization?
- And it is mentioned that a team is created and that specific user got added and tried sending messages. What is the status here?

**Comment by WaldekBarros** [comment]
Guys, good afternoon!

I'm trying to preview a message in the channel before sending and I get an error.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/6c1a6a8e-8881-463e-8f5c-1f2d2c2223ee)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/74cbfd5c-272d-4c00-b0c8-e11a8374726b)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/d29de0c0-2130-462a-a457-d5671025046b)

The same error occurs when trying to export the report.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/9c2d2cab-c9dd-4e59-b6f0-fc3fa63a970a)

**Comment by motley2546** [comment]
Dear @gsv022,

Sorry if I kept you waiting but I did further checks.
Unfortunately I did not create the environment for the app myself therefore I would ask you a bit of assistance in gathering the information requested in the first point "Please share the export results where the specified user is present"

For other points below the answers:

- The latest report I could find contained this error for the user: "8c334095-45f0-42f5-9777-dac4279d6893,disclosed.user@ext.dom.int,Disclosed User,Member,Failed,403 : User blocked the conversation with the bot.". We connected remotely with the user and checked if the bot has been blocked but on client and web application we could only find the option to block it.
- The published version of the app is 5.0.2
- Yes, the user is still active in our organization's tenant
- Sorry if I did not add the detail, the user didn't receive the message even with this test.

Thanks in advance for your help!

**Comment by gsv022** [comment]
Hi @motley2546 ,
We will check it from our end and get back to you with proper response soon.

**Comment by motley2546** [comment]
Dears, after many tests and tries we gave up but suddenly it started working. We have no clue how, but yesterday the user received the message for all the company. We tested the message to the dedicated team and she received that as well.

If there is a way to identify what caused the issue we would be glad to investigate.

Best regards and thanks.
