### ISSUE TITLE
 Error viewing, sending and exporting report in Company Communicator.

### ISSUE THREAD

**Issue by WaldekBarros** [OfficeDev/microsoft-teams-apps-company-communicator#1067]
Guys, good afternoon!

I'm trying to preview a message in the channel before sending and I get an error.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/6c1a6a8e-8881-463e-8f5c-1f2d2c2223ee)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/74cbfd5c-272d-4c00-b0c8-e11a8374726b)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/d29de0c0-2130-462a-a457-d5671025046b)

The same error occurs when trying to export the report.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/9c2d2cab-c9dd-4e59-b6f0-fc3fa63a970a)

_Originally posted by @WaldekBarros in https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1066#issuecomment-1587773622_

**Comment by gsv022** [comment]
Hi @WaldekBarros ,
Thanks for raising the query. Could you please respond to the below queries.

- What is the version of the app?
- Is this a fresh deployment?
- Just trying to understand, whether not able to send the message via any sending option?
- If yes, please check the configuration end-end.

**Comment by gsv022** [comment]
Hi @WaldekBarros ,

- As you mentioned it was working normally at the beginning of the year, could you please share the deployment status of App service. Here is the reference.

<img width="941" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d7c7cca0-32ad-4515-9290-70539b10a7d6">

- To get more information on the errors. Here is the reference.
Go to resource group-->Application Insights-->Under investigate click Failures.
<img width="503" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a67e799e-35a0-43c7-a2b6-844e7aa66f70">

**Comment by gsv022** [comment]
@WaldekBarros , I can see the last sync for app service done a day back. Could you please check whether the steps mentioned in [v5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version) migration guide have been followed correctly or not
If followed correctly, please share the screenshots as mentioned in migration guide

**Comment by WaldekBarros** [comment]
Hi @gsv022, good morning!

I performed the migration procedure for and the first error reported is no longer appearing, but I am unable to send any message due to the following error.

Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.". See the function execution logs for additional details.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/0f12ad5f-dafd-4a2a-85ae-f4b1ebc6150a)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/09235869-1b86-4fd8-bf27-26421d3d650f)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/90f9f424-eb90-4842-8647-9335335a8fad)

**Comment by gsv022** [comment]
Please share your outlook id(email id) so that we can discuss the issue internally.

**Comment by gsv022** [comment]
Please let us know if the issue persists otherwise we will make it to closure.

**Comment by WaldekBarros** [comment]
@gsv022, tks for your help.

I was able to resolve the error by adjusting the key that had expired in App Service and the 3 functions.
