### ISSUE TITLE
cannot upload app to Teams admin

### ISSUE THREAD

**Issue by sharepointchic** [OfficeDev/microsoft-teams-apps-company-communicator#1068]
Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error

I have tried this in demo environment and my own environment but still get this error.  I have uploaded apps in the past with no problem.  Some blogs suggest something wrong in the manifest file but I think that was an old issue.  Seems to be a problem. If it cannot be fixed we cannot test it and therefore it will not be any use for an organisation.

**Comment by gsv022** [comment]
Please respond to the above query

**Comment by sharepointchic** [comment]
Unable to upload the manifest folder to this location. Please assist .  Thank you
