### ISSUE TITLE
Network Security Group For Company Communicator deployment

### ISSUE THREAD

**Issue by Jasvindars** [OfficeDev/microsoft-teams-apps-company-communicator#1071]
We have security requirement, wherein need to deploy NSG for all VNET's utilized by Company communicator's Apps and components.

**Comment by Jasvindars** [comment]
While deploying Company Communicator, it creates App Service, Function Apps. We have configured Function Apps to use VNET (Network Settings). As a security best practices, we need to create "Network Security Groups" with Inbound and Outbound rules and attach it to Subnet (VNET).

**Comment by Jasvindars** [comment]
> While deploying Company Communicator, it creates App Service, Function Apps. We have configured Function Apps to use VNET (Network Settings). As a security best practices, we need to create "Network Security Groups" with Inbound and Outbound rules and attach it to Subnet (VNET).

**Comment by Jasvindars** [comment]
Dear @gsv022 Thank you very much for putting in efforts and looking into the issue. One last query, do we need to allow any taffic from Microsoft Teams in the NSG rule or only the traffic suggested by you.

**Comment by gsv022** [comment]
We haven't tested allowing the traffic for MS Teams so can't comment on that. However, you can reach out to Azure support team for further configuration details and securing your resources.

**Comment by Jasvindars** [comment]
> We haven't tested allowing the traffic for MS Teams so can't comment on that. However, you can reach out to Azure support team for further configuration details and securing your resources.

Sure Thank You @gsv022 . You have been of great help.
