### ISSUE TITLE
there are no security issues with 5.4 and below?

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#1072]
Hi 
Sorry for the detailed question about CC 5.4.1 release.
Is「security alert fixes.」in realse note mean fix alert message of user interface?
- Upgraded packages (fluentui, typescript, react-redux/scripts) for better UI and security alert fixes.

I want to make sure there are no security issues with 5.4 and below.

Regards,
Lee
@ATshirai

**Comment by gsv022** [comment]
Hi @MK202204,
Thank you for your inquiry. The security alerts pertain to GitHub's dependabot alerts. These alerts prompt the upgrade of insecure packages to their secure counterparts. These security alerts were addressed in v5.4.1. So, we recommend you upgrade to the latest version and provide your feedback.

**Comment by MK202204** [comment]
Thank you for your reply @gsv022 
I understood that there was a security alert in the fluentui, typescript, react-redux/scripts packages.
Will it affect C.C, which is already deployed?
The CC version we deployed is 4.1.

**Comment by gsv022** [comment]
No, It won't affect the versions which were already deployed.

**Comment by MK202204** [comment]
@gsv022 
Thank you for your reply.
I'm relieved to hear that it didn't affect deployed CC.
Please close this issue.

Regards,
