### ISSUE TITLE
Explanation of Error Codes

### ISSUE THREAD

**Issue by malikahoffer** [OfficeDev/microsoft-teams-apps-company-communicator#1073]
Hello, I need an explanation of the error codes we get from the message delivery file for the Company Communicator: 403, 429, 500, 502. Is there a page where we can find it.
Thank you

**Comment by gsv022** [comment]
Hi @malikahoffer ,
Thanks for raising the query. Here is list of errors with reasons.

- 403-Forbidden Error message
Sorry, you do not have permission to access this page. Please contact your administrator to be granted permission.

- 429- when there are too many requests within a given amount of time error 429 occ

- 500- internal error if the draft notification method throws an unhandled exception.

- 200- When the message delivers successfully gives the status code 200 ok.

**Comment by gsv022** [comment]
@malikahoffer , Please let us know if you have any queries.

**Comment by malikahoffer** [comment]
> @malikahoffer , Please let us know if you have any queries.

Thank you, for now I am fine

**Comment by gsv022** [comment]
@malikahoffer , We are closing the issue request as we provided the required response. Please feel free to reach out to us if any issue or concern related to Company Communicator. We are happy to assist you.

Thank you
