### ISSUE TITLE
Card button doesn't work after message sent 

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-company-communicator#1075]
Hi, 
on my CC 5.1 I'm having this issue: has been created a message with a button with this link
https://helpdesk.xyz.com/sp?id=kb_article_view&sys_kb_id=d9410e5b1b57a1103be864a5604bcb83

During preview check anything it's worked fine but after that message has been sent, if users click on button receive an error message because destination page doesn't exist because link is changed to https://helpdesk.xyz.com/sp?id=kb_article_view

How it's possible? There are limitations to use '&' or what?

Regards

**Comment by gsv022** [comment]
Hi @faalive ,
Thanks for raising the query. We will check the button link from our side and get back to you.

**Comment by gsv022** [comment]
Hi @faalive ,
Thanks for the patience. We have tested the first url(https://helpdesk.xyz.com/sp?id=kb_article_view&sys_kb_id=d9410e5b1b57a1103be864a5604bcb83) it is working fine and not converting into  https://helpdesk.xyz.com/sp?id=kb_article_view. Here are the screenshots

<img width="431" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/bd8a2baf-49ae-4486-ae2f-a48b29b70dfc">

<img width="535" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b3880b50-bb73-433a-ab56-c84a633a3666">
