### ISSUE TITLE
The upgrade from v4 to v5 via powershell does not go beyond the creation/modification of app registration.

### ISSUE THREAD

**Issue by frisisuas** [OfficeDev/microsoft-teams-apps-company-communicator#1076]
Hello,
I am encountering problems upgrading an existing version of V4 and when I want to upgrade to V5, I always encounter the same error via powershell:

DeployARMTemplate : You cannot bind the argument to the 'authorappId' parameter because it is null.
En C:\XXXXXXXXXXXXXX\microsoft-teams-apps-company-communicator-5.4.1\Deployment\deploy.ps1: 1134 character: 67
 ...  = DeployARMTemplate $graphAppCred.appId $authorAppCred.appId $userAp ...
                                             ~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidData: (:) [DeployARMTemplate], ParameterBindingValidationException
     FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,DeployARMTemplate

Reading deployment outputs...
Encountered an error during ARM template deployment. Exiting..

I have tried from my test environment and with the same code I can upgrade a v4 version. I have replicated the roles in the test tenant and without success. In my lab it works U_U

Any idea what could be happening?

Thanks.

**Comment by gsv022** [comment]
Hi @frisisuas ,
Thanks for raising the query. Please respond to the below queries.

- Did V4 of CC working initially?
- Hope you have followed the migration guide in this order 
 a)[v4-to-v5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5)
 b)[v5-latest version](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version)

- At which point, you have encountered the error, please share the supporting screenshot for better troubleshooting.

**Comment by frisisuas** [comment]
Hi again,
I review first the permissions in case we are doing something wrong.
Application administrator for the app registration creation and owner on the subscription.

V4 installed and deployed correctly. Some problem at the beginning but it deployed.

We have followed the steps of migrations from v4 to v5 that you have in the repository.

The problem always happens when creating the app registration of the V5 update that are created with the script. the first one is created and then the client fails.
In my test tenant, with a user expressly with the same permissions and roles as in client I do not have the same problem and I can not reproduce the problem. Simply in the creation phase of the apps there is something wrong.

Client deployment:
![client_deployment_fail](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/aedce0f1-6287-4a40-accd-b85d2ce26440)
On my tenant:
![rcb_tenant_deployment](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/7db38ece-2b11-46d1-ac7e-96bce74a73a7)

Same code, only changing the json for the variables.

**Comment by gsv022** [comment]
@frisisuas , Please note that app registrations are not needed to be created again. The same id's that are created during v4 deployment can be used again while migrating to v5.x. To avoid the ambiguity follow the manual deployment procedure . The links for manual migration already share in the above response.

**Comment by frisisuas** [comment]
Good morning,
I have indeed read the update procedure. I am left with the doubt, if I simply update using the arm template indicating the existing app id and app password of the old deployments would it work. It is the only thing left to test.

**Comment by gsv022** [comment]
For migration, keeping the same app id's and password would do the needful. For more clarification please refer deployment guide.

**Comment by frisisuas** [comment]
Good morning,
I may have missed something, but I think it is clear that something is happening with the upgrade.
Is it possible to make a backup of version 4 to implement an updated version and import the history?

**Comment by frisisuas** [comment]
Making the deployment through the deployment the error we get is the following:
"details: [
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Not allowed to update tenant ID, application ID, principal ID and scope."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Not allowed to update the tenant ID, application ID, principal ID or scope."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Not allowed to update the tenant ID, application ID, principal ID or scope."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Not allowed to update the tenant ID, application ID, principal ID or scope."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Not allowed to update tenant ID, application ID, principal ID or scope."
    }
  ]
}

I imagine it is because of some specific role in Azure AD that does not allow me to modify the App Registration. In theory with the App Administrator role should be enough to have control over the manipulation of the app registration.

In the last attempt we only got the error at that point:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44669926/415dc7ad-ef9c-4002-a6ae-a3e197d0b272)

We have tried with a GUID generator and it has also failed us. The part I don't quite understand is why there are 3 of the 7 that do work and the rest don't. In my test environment I have never had any problems with those GUIDs. In my test environment I have never had any problems with those guid.

**Comment by gsv022** [comment]
Hi @frisisuas ,
Go for re-deploy but this time update the guid's which are failed. The role assignment issue will be resolved.

**Comment by frisisuas** [comment]
Good morning,
We have managed to deploy a third version of the application for a TESTS environment. All through powershell and had to modify the GUIDs about 50 times. So I have no permissions problems.
I'm still having problems with the DEV version but I'm clear on certain issues.
I'm going to keep digging. I will keep asking you with the next attempts.
Best regards.

**Comment by gsv022** [comment]
Thanks for the confirmation. If any issue arises please log a new issue, we are happy to assist you.
