### ISSUE TITLE
Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error

### ISSUE THREAD

**Issue by sharepointchic** [OfficeDev/microsoft-teams-apps-company-communicator#1077]
Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error

I have tried this in demo environment and my own environment but still get this error. I have uploaded apps in the past with no problem. Some blogs suggest something wrong in the manifest file but I think that was an old issue. Seems to be a problem. If it cannot be fixed we cannot test it and therefore it will not be any use for an organisation.

**Comment by gsv022** [comment]
Hi @sharepointchic ,
Please share the zipped manifest files

**Comment by sharepointchic** [comment]
[microsoft-teams-apps-company-communicator-5.4.1.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11879857/microsoft-teams-apps-company-communicator-5.4.1.zip)

**Comment by sharepointchic** [comment]
I am having trouble trying to attach the files. Copy and paste not working neither is drag and drop?

**Comment by sharepointchic** [comment]
Error file type not supported.

**Comment by sharepointchic** [comment]
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "5.4.0",
  "id": "1c07cd26-a088-4db8-8928-ace382fa219f",
  "packageName": "com.microsoft.teams.companycommunicator.authors",
  "developer": {
    "name": "<<companyName>>",
    "websiteUrl": "<<websiteUrl>>",
    "privacyUrl": "<<privacyUrl>>",
    "termsOfUseUrl": "<<termsOfUseUrl>>"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Company Communicator (Authors)",
    "full": "Company Communicator (Authors)"
  },
  "description": {
    "short": "Broadcast messages to multiple teams and people in one go",
    "full": "Broadcasts messages to multiple teams and individuals through channel posts and chat messages"
  },
  "accentColor": "#64A2CC",
  "configurableTabs": [{
    "configurationUrl": "https://<<appDomain>>/configtab",
    "canUpdateConfiguration": true,
    "scopes": [
      "team"
    ]
  }],
  "bots": [{
    "botId": "<<botId>>",
    "scopes": [
      "team"
    ],
    "supportsFiles": true,
    "isNotificationOnly": true
  }],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "<<appDomain>>"
  ],
  "webApplicationInfo": {
    "id": "<<botId>>",
    "resource": "api://<<appDomain>>"
  }
}

**Comment by sharepointchic** [comment]
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "5.4.0",
  "id": "148a66bb-e83d-425a-927d-09f4299a9274",
  "packageName": "com.microsoft.teams.companycommunicator",
  "developer": {
    "name": "<<companyName>>",
    "websiteUrl": "<<websiteUrl>>",
    "privacyUrl": "<<privacyUrl>>",
    "termsOfUseUrl": "<<termsOfUseUrl>>"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Company Communicator",
    "full": "Company Communicator"
  },
  "description": {
    "short": "Broadcast messages to multiple teams and people in one go",
    "full": "Broadcasts messages to multiple teams and individuals through channel posts and chat messages"
  },
  "accentColor": "#64A2CC",
  "bots": [{
    "botId": "<<botId>>",
    "scopes": [
      "personal",
      "team"
    ],
    "supportsFiles": false,
    "isNotificationOnly": true
  }],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "<<appDomain>>"
  ]
}

**Comment by sharepointchic** [comment]
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "5.4.0",
  "id": "148a66bb-e83d-425a-927d-09f4299a9274",
  "packageName": "com.microsoft.teams.companycommunicator",
  "developer": {
    "name": "<<companyName>>",
    "websiteUrl": "<<websiteUrl>>",
    "privacyUrl": "<<privacyUrl>>",
    "termsOfUseUrl": "<<termsOfUseUrl>>"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Company Communicator",
    "full": "Company Communicator"
  },
  "description": {
    "short": "Broadcast messages to multiple teams and people in one go",
    "full": "Broadcasts messages to multiple teams and individuals through channel posts and chat messages"
  },
  "accentColor": "#64A2CC",
  "bots": [{
    "botId": "<<botId>>",
    "scopes": [
      "personal",
      "team"
    ],
    "supportsFiles": false,
    "isNotificationOnly": true
  }],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "<<appDomain>>"
  ]
}


(sorry the above message missed copy end of file)
