### ISSUE TITLE
deploy failed with error "There was a conflict. Conflict with existing ScmType: ExternalGit""

### ISSUE THREAD

**Issue by prasadpetkar** [OfficeDev/microsoft-teams-apps-company-communicator#1078]
"There was a conflict. Conflict with existing ScmType: ExternalGit"" getting error while deployment. 

Status message

    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",
        "details": [
            {
                "message": "There was a conflict. Conflict with existing ScmType: ExternalGit"
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}

**Comment by LuckyWave27** [comment]
Hi team, 
I am working with Prasad and here are some more information.
Screenshot:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/30038463/0ecc39be-fcdb-4bba-85d2-923e193864a8)

Status message:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/30038463/bb3b576d-21fd-4b02-b135-721ff38f0af6)

trackid: d76e1f25-bdf2-4529-85dd-2d49cc21595f
servicerequestid: 3e546fb0-8dc3-4994-8f73-a01676649829
Deployment correlation ID: e9a7d72c-c2c9-4161-952f-5a0863f8a646


I tried to reproduce it in my account but I encountered another one. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/30038463/5438e4b8-6b08-4bf3-a57b-91e911beab5f)

Correlation id: 712406c0-03a5-4462-a535-2fb2829fc39e
Tracking id: 08a530cf-c012-4f2d-a11e-cf6d39e2297b
Request Id: 9fbfb2a6-60a4-43f5-8b20-604ba688bacc

Looking further about the template, it should be an simple one which only update the source control (scmType).
The apiVersion seems to be outdated so I correct them manually to 2016-08-01.
(3/4 source control, there is one staying in 2016-08-1 already.)
However, I still got “Bad request” after I fix the version. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/30038463/84a673d4-a32a-4e0b-ac33-2011cf993b3c)

"code": "BadRequest",
  "message": "Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway

Qustion:
Do you receive similar report or seen this issue before? Does the new deployment work for you right now?
Why do you keep two kinds of api version for source control (2015-08-01 and 2016-08-01)? Would that bring any difference?

**Comment by gsv022** [comment]
Hi @prasadpetkar ,
Thanks for raising the query. It is obvious that the time for deployment to be completed is around 40 minutes. During this process if any resource gets failed, deployment status shows as "Deployment failed". If the deployment is failing, check for resource which is failing.

- Now in your case,  prep-function and data-function resources are failed. Please follow the below steps
<img width="687" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0f25c093-1919-4945-9477-29e8816045b4">

- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select  prep-function from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository.
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.

**Comment by LuckyWave27** [comment]
Hi @gsv022 
Thanks for getting back.
There are two issues in two different deployments we encountered:

Issue 1:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/30038463/3f579dd3-6cba-4e7a-ab80-9e8b1ccc2676)

Issue 2:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/30038463/adbf1240-4234-4cef-a2bd-4cdb696558f2)

In addition, there would be outputs in the end of the deployment.
    "keyVaultName": {
      "type": "string",
      "value": "[variables('keyvaultName')]"
    },
    "authorBotId": {
      "type": "string",
      "value": "[parameters('authorClientId')]"
    },
    "userBotId": {
      "type": "string",
      "value": "[parameters('userClientId')]"
    },
    "appDomain": {
      "type": "string",
      "value": "[if(variables('useFrontDoor'), variables('frontDoorDomain'), concat('Please create a custom domain name for ', variables('botAppDomain'), ' and use that in the manifest'))]"
    }
    
    It would not be straight forward if users need those information. 
    Do we have any idea why the template deployment failed and do we have plan to fix it?

**Comment by lazarovidiu** [comment]
Hi @gsv022
I have verified all the functions and they connect to GitHub fine.
However, every redeployment comes back with the same error for the x/web Resource:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/cade4d1f-fcf3-4335-8ec7-5d1db7fb9f70)

**Comment by Dave365CH** [comment]
Hi all, i have the exact same problem. I changed the external Git settings, but the redeployment always shows the "there was a conflict" error.

**Comment by gsv022** [comment]
Hi @prasadpetkar ,
As per the discussion in the call even though the deployment section shows app service got failed but it was successful when visited individually. We suggested to proceed with the remaining steps of deployment. Please let us know if you face any issue otherwise we can make it to closure.

Thank you.

**Comment by Schulro** [comment]
Dear All,

I had the same issue. My solution was to disconnect the external Repository (from the App Service, not the Function Apps), wait a while and connect it again. You are not allowed to do a Sync afterwards, just connect it and do the redeployment and then it was successful at my end.
