### ISSUE TITLE
Not all users receive the messages from Company Communicator.

### ISSUE THREAD

**Issue by karloscri** [OfficeDev/microsoft-teams-apps-company-communicator#1080]
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound' at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken) at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken) at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken) at Microsoft.Bot.Builder.TurnContext.[]c__DisplayClass31_0.[[SendActivitiesAsync]g__SendActivitiesThroughAdapter|1]d.MoveNext()--- End of stack trace from previous location where exception was thrown --- at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken) at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.[]c__DisplayClass3_1.[[SendMessageAsync]b__1]d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94--- End of stack trace from previous location where exception was thrown --- at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext) at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext) at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.[]c__DisplayClass3_0.[[SendMessageAsync]b__0]d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94

**Comment by karloscri** [comment]
What is the version of the app? **5.2.0**
What the count of members in the team? **3121 users**
Please share Success and failure count, supporting screenshot would be helpful - 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/137891002/179ea7c4-de23-40c3-b904-4ae4a4e43388)

Is this a first message? no

**Comment by gsv022** [comment]
Hi @karloscri ,
Please try uninstalling the author, user app and re-upload it . Then try sending the message. Please keep us posted.

**Comment by WaldekBarros** [comment]
I had a similar problem, where the error occurred due to a manual lock made by the user.

I don't know if this can help.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129632590/3c21316d-d09f-4fcd-9774-67a7bbc36b5f)

**Comment by JG-OC** [comment]
Thanks will check that too.
________________________________

**Comment by gsv022** [comment]
Please do not block the app. 

> Hi @karloscri , Please try uninstalling the author, user app and re-upload it . Then try sending the message. Please keep us posted.

**Comment by JG-OC** [comment]
As per the other thread:

So we believe this has been cause by the user deleting the message from Teams. The bot cannot then send a message to the user they way around it is to:

Logged on, cleared cache from roaming

C:\Users\<User.Name>\AppData\Roaming\Microsoft\Teams\Cache\Cache_Data

Sometimes thats enough, if not is a reinstall of Teams. If anyone else could confirm their end user deleted the chat too and it fixed it?

**Comment by karloscri** [comment]
I installed the latest version and I still have the same error 5.4.1

**Comment by sambetts** [comment]
> As per the other thread:
> 
> So we believe this has been cause by the user deleting the message from Teams. The bot cannot then send a message to the user they way around it is to:
> 
> Logged on, cleared cache from roaming
> 
> C:\Users<User.Name>\AppData\Roaming\Microsoft\Teams\Cache\Cache_Data
> 
> Sometimes thats enough, if not is a reinstall of Teams. If anyone else could confirm their end user deleted the chat too and it fixed it?

Just out of interest, if the user's deleted the conversation, surely a quick fix would be to delete the storage account table entry for the user instead?

**Comment by karloscri** [comment]
I have this same problem again, How can I reopen the case?
