### ISSUE TITLE
Teams app in iPhone crashes when using Company Communicator app in iOS versions 15.x and above

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#1081]
When using Company communicator User app in Teams from iPhone, Teams application crashes.
Device is iOS 15.7.6, Model - iPhone 7 Plus. Also faced other crash on iOS 15.5, Model - iPhone 7, iPhone SE. 

We have checked that Teams app is up to date.
We uninstalled Teams app on iPhone and reinstalled. At first, it seemed to be stable. we were able to scroll through our existing posts. We were also able to click for a couple of times into our news that will open a web browser. But after some time the app crashes as before, without any notice in advance or error screen.

Please help to resolve this issue.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query. Company Communicator v5.4.1 complies with Microsoft accessibility standards and guidelines for Web, Windows and Mac OS (Grade C). Also please note Company Communicator is not supported for Mobile version. It's already been added to the backlog. The support for mobile version will be part of next release.

**Comment by PrithuMahisha** [comment]
@gsv022 , Could you please confirm if the support is not available for both Company Communicator Author and User apps in mobile?

**Comment by PrithuMahisha** [comment]
Also let us know the ETA for the next release which will support mobile version.

**Comment by gsv022** [comment]
@PrithuMahisha ,The tentative release for Company Communicator application mobile support is planned by end of July 2023.

**Comment by PrithuMahisha** [comment]
@gsv022, Requesting to provide confirmation on the below one as well.
Could you please confirm if the support is not available for both Company Communicator Author and User apps in mobile?

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
As of now the support for mobile version i.e., for author and user app is not available.  We will let you know about the support for iPadOS version.

**Comment by PrithuMahisha** [comment]
We are still waiting to get the information about support for iPadOS versions.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
It is confirmed that support for iPadOS versions won't be provided.
