### ISSUE TITLE
Default retry policy of Company Communicator App

### ISSUE THREAD

**Issue by ChrisClurit** [OfficeDev/microsoft-teams-apps-company-communicator#1082]
Hello, 
is there a default retry policy on already sent messages? In particular if the message delivery fails for any reason for some users or if the sending operation is canceled by an author, will the app try to deliver the message later automatically?

**Comment by gsv022** [comment]
Hi @ChrisClurit ,
Thanks for raising the query. 

- _Is there a default retry policy on already sent messages?_ - Yes, each messages will be retried for 10 times sequentially without any wait time.
- _In particular if the message delivery fails for any reason for some users or if the sending operation is canceled by an author, will the app try to deliver the message later automatically?_ - Yes, the app will automatically attempt to deliver the message up to 10 times in case of delivery failure. However, if the sending operation is canceled by the author, automatic retries will not be initiated.

**Comment by gsv022** [comment]
Please let us know if you have any queries otherwise we will make it to closure

**Comment by ChrisClurit** [comment]
Hello,
So the counter of failed deliveries for the message on the App UI is the final counter after all the 10 retries?

Thank you,
Christian



Christian Sileo

Cluster Reply
Via del Giorgione, 59
00147 - Roma - ITALY
phone: +39 06 844341
***@***.******@***.***>
www.reply.it<http://www.reply.it> <http://>
IM: ***@***.***

[Cluster Reply]
Da: Sai Venkat ***@***.***>
Inviato: venerdì 30 giugno 2023 15:36
A: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Christian Sileo ***@***.***>; Mention ***@***.***>
Oggetto: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Default retry policy of Company Communicator App (Issue #1082)


Please let us know if you have any queries otherwise we will make it to closure

**Comment by ChrisClurit** [comment]
Hello,
So the counter of failed deliveries for the message on the App UI is the final counter after all the 10 retries?

Thank you,
Christian

**Comment by gsv022** [comment]
Yes, it will be single count as failed after 10 retries
