### ISSUE TITLE
Failed to send message after upgrading to V5.4

### ISSUE THREAD

**Issue by TomSawyer03** [OfficeDev/microsoft-teams-apps-company-communicator#1086]
Hi, 

Can you help me how to resolve the issue below after I renew my certificate then upgrade to version 5.4
I followed **Upgrading from v5.x to latest version**
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide

Name GET /api/groupdata/verifyaccess
Response Code: 500

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85331597/5a260088-a326-431f-8d42-46cc79e60b43)

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
Thanks for raising the query. Please respond to the below queries.

- From which version (v5.1/v5.2/v5.3) of CC has been updated to 5.4.1?
- Could you please elaborate on the certificate renewal.

**Comment by TomSawyer03** [comment]
From V5.0 to latest version

Instead of using the default azure domain, we use specific SSL certificate for custom domain setting.

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,

- Please confirm during previous version v5.0, the application was working fine?
- Just trying to understand, once the default domain got replaced with custom domain it started giving 500 issue
- If you want to proceed with custom domain, we won't be able to help out as our support scope is limited to official version.
For more information please visit [Custom domain option](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option)

**Comment by TomSawyer03** [comment]
Yes it is working, 
but now I tried to send a message, the status stays "Queued" status. The error message says Verify access to Login.microsoft.com

**Comment by TomSawyer03** [comment]
The issue happen after I upgrade to 5.4

**Comment by gsv022** [comment]
There are mainly two possibilities for queue. Either app secrets might have expired/incorrectly configured or supported accounted type for app registration might be kept incorrect as per deployment guide.

-  Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
Author-multiple
User-multiple
Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

- If secrets were expired. Please follow this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/992).

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
Please let us know the working status of CC

**Comment by TomSawyer03** [comment]
This has been check and configured correctly but the Communicator still not sending a message.

**Comment by gsv022** [comment]
Please share your outlook id(mail id) so that we can discuss the issue internally

**Comment by TomSawyer03** [comment]
@gsv022  rtomas@archgroup.com

**Comment by CeciliaRavera** [comment]
@gsv022 @TomSawyer03 any update on this?
We are facing the same problem

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
