### ISSUE TITLE
Old Messages

### ISSUE THREAD

**Issue by ricbm11** [OfficeDev/microsoft-teams-apps-company-communicator#1087]
Hi all!

A simple question, how can I delete the old messages sent by authors? Thanks in advanced

**Comment by gsv022** [comment]
Hi @ricbm11 ,
Thanks for raising the query. Please respond to the below queries.

- Are you referring to deleting old messages from the database?
- Should we delete old messages from all users?
- Do you mean deleting the messages that were sent by authors by mistake?

**Comment by gsv022** [comment]
Hi @ricbm11 ,
Please respond to the above queries

**Comment by ricbm11** [comment]
Hi ! It´s about old messages from the database.

**Comment by gsv022** [comment]
Hi @ricbm11 ,
The feature is not present at the moment. It is in progress and will be included in the upcoming releases of CC. For now we consider this as an enhancement.

**Comment by ricbm11** [comment]
Ok !!! Tks for your attention!

And what about ?

"Do you mean deleting the messages that were sent by authors by mistake?"

what can I do?

**Comment by gsv022** [comment]
After clicking the send option, message starts getting delivered , there will be a option called "cancel" . One can utilized this option. Once the message is delivered successfully deletion can't be implemented from author side.
<img width="692" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/65742069-d2b9-4a2c-b964-08aeb319c7d5">

**Comment by ricbm11** [comment]
Thank you for your suport
