### ISSUE TITLE
How to disable send to options?

### ISSUE THREAD

**Issue by lazarovidiu** [OfficeDev/microsoft-teams-apps-company-communicator#1088]
Hello,

We would like to know if it is possible to disable some of the send to options for the authors.
In my case I would like to only allow the option to send via distribution groups and disable the highlighted options:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/d8cb21a1-c5d0-4d28-ae33-0400863c01ea)

**Comment by v-jaygupta** [comment]
Hello @lazarovidiu,

Currently, we don't have enable disable feature for respective sending options.
This has been added to our backlog list and will be planning to implement it in future releases post the discussion with our internal team.
