### ISSUE TITLE
Error when exporting or previewing

### ISSUE THREAD

**Issue by lazarovidiu** [OfficeDev/microsoft-teams-apps-company-communicator#1089]
When clicking on the "Export detailed results" button I get the error "Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists."
Same thing happens if I click on the 'Preview In this channel" button from any draft message.

The Teams channel is not private and I tried on a different channel as well.
This is a second instance of the company communicator in our environment and the first instance works fine. Teams settings are the same for both.

I tried syncing and restarting the App Service and Function Apps but the issue persists.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/19857a85-fdd5-44ad-8621-b79f216c01d1)

**Comment by v-jaygupta** [comment]
Hello @lazarovidiu ,

Thank you for raising the issue for Company Communicator app. 
Could you please confirm on the below points - 

- Is this a new deployment?
- What is the version of the deployed application?
- Please share deployment status screenshots of all the Function apps and App service from the deployment centre. Here is the reference for App service status. Please do the same for 3 function apps(Data Function, Send Function, Prep Function)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/360d5e3b-12a3-42ec-b58f-d6ebea1f57fd)

**Comment by lazarovidiu** [comment]
Hi @v-jaygupta 
This is the second deployment in our tenant. The first one works fine.
We are on the latest version, 5.4.1 - we deployed directly to this version so there was no update involved.
The screenshots requested are as follows:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/4e1cd094-371c-4910-9186-3de04b5456ed)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/954423bf-74f0-4bda-ae6b-ba18e6ef536b)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/84ab0f7c-7ac8-44a5-8ea5-ea7bef0a4e15)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/33673691-439b-4fe5-baf6-48feec2fce9c)

**Comment by gsv022** [comment]
Hi @lazarovidiu ,

- There is a chance of incorrect configuration, have a thorough check from start-end and mainly verify the all three app client secret is correctly copied while creating ARM template or not. Attaching the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911) where you can compare and check on secrets.
- Please cross verify the set-up authentication part again. 
<img width="673" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5d97b1ef-a490-46df-93bf-f403aab579df">

- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
    Author-multiple
    User-multiple
    Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

**Comment by lazarovidiu** [comment]
Hi @gsv022 
I have checked all the secrets and the setup authentication and everything is correct.

The "Supported type" parameter for app registration was not correctly set. All three were set to multiple.
I have changed the Graph to "My organization only" and restarted all four services but the issue persists.
Is there anything else I need to check after changing this setting?

**Comment by lazarovidiu** [comment]
Hi @gsv022 
We copied the Secrets' Value not the ID from the three apps. I have also verified this multiple times and they are correct in the resource group vault.

If you are sure the secrets are behind these issues we could generate new ones and update and test them.
Let me know if you think this is worth doing.

**Comment by gsv022** [comment]
Please share the manifest files

**Comment by gsv022** [comment]
Hi @lazarovidiu ,
Please share the zipped manifest files which will be done at the last but one stage of deployment process. Here is the reference.
<img width="569" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/1637e778-811b-4ba1-8e84-d21bc2825fe2">

**Comment by lazarovidiu** [comment]
Hi @gsv022, please find the requested manifest files attached.
[manifest.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/12122214/manifest.zip)

**Comment by gsv022** [comment]
Hi @lazarovidiu ,
Thanks for the patience. Please modify the manifest files.

- Please update the both highlighted places with author bot id(Author application id)
<img width="421" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/444c35c0-0e8f-432f-a096-b68c4771f974">

- Please keep the id as it is unless there are multiple instances deployed to teams 

<img width="557" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/249362a1-374d-4468-9a24-9dfb33e600cb">

- **Note:-** It is not recommended to change the version.
<img width="539" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/725879da-e708-412a-9092-8098e0acad21">
