### ISSUE TITLE
Permission Needed to chat memebers of a M365 Group

### ISSUE THREAD

**Issue by teiselt96** [OfficeDev/microsoft-teams-apps-company-communicator#1099]
We recently ran into an issue where Company Communicator authors cannot send out a communication to a specific M365 group, they could earlier this year. Has something changed where that is not allowed anymore? 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/34378652/72faf1c1-446a-4ea4-9654-f3b9a9275a94)

**Comment by gsv022** [comment]
Hi @teiselt96 ,
Thanks for raising the query. Please respond to the below queries.

- Please share the repository link and branch that has been used for deployment.
- Check for API permissions has been added and granted admin consent or not.
<img width="712" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6f8ac349-55a8-43a2-8c9a-d3fa763eaccb">

**Comment by gsv022** [comment]
Hi @teiselt96 ,
Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version.
