### ISSUE TITLE
error while fetching Teams Group and Members

### ISSUE THREAD

**Issue by catchzafar** [OfficeDev/microsoft-teams-apps-company-communicator#1100]
Hi Team, 
we are facing the challenge after installing the app and it is showing "We couldn't find any match" in Choose how you want to send the message.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/19735599/aca1e994-4551-4e8a-a4ac-ba509cbcffd1)

**Comment by gsv022** [comment]
Hi @catchzafar ,
Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by catchzafar** [comment]
OK, let us check on that we'll get back to you

**Comment by gsv022** [comment]
Please let us know if the above response helped in resolving the issue.
