### ISSUE TITLE
Messages remain in queue after upgrading to V5.4

### ISSUE THREAD

**Issue by DaniOnyx75** [OfficeDev/microsoft-teams-apps-company-communicator#1101]
Hi,

I followed Upgrading from v5.x to latest version following the guide. After the update we have the messages the Service Bus Namespace queues that are not delivered.

Can you help me how to resolve this issue?

Before the upgrade all was working fine.

**Comment by gsv022** [comment]
Hi @DaniOnyx75 ,
Thanks for raising the query.  Could you please confirm whether [scripting procedure](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#1-update-the-net-version-of-azure-functions-and-app-service-to-support-net-60-) performed to update the azure functions and app service. If so, please share the screenshots.

**Comment by gsv022** [comment]
@DaniOnyx75 , Please respond to the above query.

**Comment by Git-Onyx** [comment]
Hi @gsv022 ,

I confirm you that the scripting procedures have been executed as you can see from screenshots:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/63337746/9dc2bc17-5fb7-400f-83fa-0818f038cd4d)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/63337746/ebf17667-d9e6-48d6-b793-eb02e0dc23f1)

But messages remains in the queues:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/63337746/44eb23bf-316b-4af8-8c95-49d68a7aa768)

**Comment by gsv022** [comment]
HI @DaniOnyx75 ,
Could you please check if the secret values at the app registration are the same as mentioned in the app service configuration, 3-function app configurations. To check and compare, here is the procedure.
- Go to Azure Portal
- Go to App registration
- Grab secret value of app registration, 
<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">

- Compare the secret  with concerned app registration. 
- If the secrets are not visible, Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets

- Compare them. Do the same for other app registrations

**Comment by Git-Onyx** [comment]
Hi @gsv022 ,

I confirm you that I have 3 App Registrations (Communicator App, Communicator Author, Communicator User) and the secrets are the same of the secret in the Key Vault (vaultGraphAppPassword, vaultAuthorAppPassword, vaultUserAppPassword).

**Comment by gsv022** [comment]
@DaniOnyx75 , Please share your email-id(outlook id) so that we can continue to conversation internally

**Comment by gsv022** [comment]
Hi @Luba97 ,

- Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly done or not. Especially check for **supported account type** should be- **My Organization** only for graph app.
Author app- Multiple Organization
User app- Multiple Organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">
- Share the zipped manifest files

**Comment by gsv022** [comment]
Please respond to the above queries

**Comment by Luba97** [comment]
> Hi @Luba97 ,
> 
> * Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly done or not. Especially check for **supported account type** should be- **My Organization** only for graph app.
>   Author app- Multiple Organization
>   User app- Multiple Organization
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">
> 
> * If it is found that incorrectly done, modify it and try sending a message again
> * Share the zipped manifest files(Both author and user)

Dear gsv022, sorry for late reply!
I am sending the manifest files by e-mail. Please reopen the case.

Thank you

**Comment by gsv022** [comment]
Hi @DaniOnyx75 ,
please open the new issue for better tracking.
