### ISSUE TITLE
Failed to create conversation with teams user

### ISSUE THREAD

**Issue by jeff-bb** [OfficeDev/microsoft-teams-apps-company-communicator#1103]
Long time user of platform that has been running successfully for years at this point. Last message was sent less than a month ago.

Authors can create a draft, as well as attempt to send to a channel/group/etc. It reports failure, and exporting the failure results in this message.

Warnings
Failed to create conversation with teams user: 29:1FkUJsJkNh7t1g6St__hRX7aRXhdL9GM_jV1BGdelIZtOB7KtX72CdicPU67Ui6xUKO8Ftgs-tOzH9EwGdM3gxw.
Exception: Failed to acquire token for client credentials.
(AADSTS700016: Application with identifier '762b2456-51ce-4ee4-ada0-4a02614815ca' was not found in the directory 'Bot Framework'.
This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 40e4f174-18c5-4bd3-b30e-7d86411c4000 Correlation ID: 3e468351-307a-44f2-9eb3-51a930667186 Timestamp: 2023-07-24 21:47:21Z)

762b2456-51ce-4ee4-ada0-4a02614815ca is the author application id. I've verified within the App registration that the permissions are correct (delegated graph user.read, consent to org). Went into Teams Admin Center and re-consented. No change. Verified the secrets are not expired or in an otherwise bad state (they are not, we just refreshed them in Feb 2023 and have sent multiple messages since that time).

Deployment is pointed to https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git (main), we have been running 5.3 since February 2023. As part of this, I reployed and took it to 5.4.1. No change in behavior. I restarted all the functions and app service, no change in behavior.

**Comment by gsv022** [comment]
Hi @jeff-bb ,
There might be multiple reasons for this issue. Could you please check if the secret values at the app registration are the same as mentioned in the app service configuration, 3-function app configurations. To check and compare, here is the procedure.
- Go to Azure Portal
- Go to App registration
- Grab secret value of app registration, 
<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">

- Compare the secret  with concerned app registration. 
- If the secrets are not visible, Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets

**Comment by jeff-bb** [comment]
I've reconfirmed the secrets are correct in the 4 locations. (App service and 3 functions). I've reconfirmed they haven't changed or modified since Feb 2023 when they were updated due to expiration. I've reconfirmed that it has functioned since Feb, as recently as just 3 weeks ago.

What else can cause this?

**Comment by gsv022** [comment]
Hi @jeff-bb ,

- Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly done or not.
- Share the zipped manifest files

**Comment by jeff-bb** [comment]
Authentication looks correct. Here is the manifest for the graph application.

[manifest.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/12173288/manifest.zip)
