### ISSUE TITLE
How to mark down text when adding multiple lines in the Summary section?

### ISSUE THREAD

**Issue by Fadel1949** [OfficeDev/microsoft-teams-apps-company-communicator#1104]
From the image, when I use Enter, the Preview does not display as it was actually written.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/126840838/34657b5a-835e-4c13-ad75-4c871dd4f514)

**Comment by gsv022** [comment]
Hi @Fadel1949 ,
Thanks for raising the query. 

- We will check the scenario from our end.

- Could you please share the repo URL and branch that has used during deployment

**Comment by Fadel1949** [comment]
Hi @gsv022 ,
Thanks .
The Repos come from https://github.com/cristianoag/microsoft-teams-apps-company-communicator/wiki
I think the Format text should occur in every Repos."

**Comment by gsv022** [comment]
Hi @Fadel1949 ,
We have checked this from our end and it is happening at the official repository. For now, we will consider this as bug and will be addressed in the future releases of  CC.

**Comment by Fadel1949** [comment]
Hi @gsv022  ,
Ok let me know if there is a fix.
thank you very much

**Comment by gsv022** [comment]
We have added this issue to our backlog and will take the necessary action.
