### ISSUE TITLE
Restrict results from 'Send in chat to members using groups'

### ISSUE THREAD

**Issue by reece-r** [OfficeDev/microsoft-teams-apps-company-communicator#1105]
Is there any way to restrict the results of option 'Send in chat to members using groups' for the Authors app? We have a security issue with the Author App Registration having Application level access to 'GroupMember.Read.All' scope which I believe allows the app to read all groups in our tenant.

We have made a modification to the code to remove the 'Send in chat to everyone' option, however our environment has large Distribution Lists which normally have Exchange restrictions to a certain group of allowed senders. For the Author App, the Exchange sending restriction rules do not apply, and so we have a security risk for allowing authors to use the app.

Is it possible for us to specify which groups the Author App can find in the 'Send in chat to members using groups' option?

**Comment by gsv022** [comment]
Hi @reece-r ,
Thanks for raising the query. Please give us sometime, we will discuss with our team and get back to you.

**Comment by gsv022** [comment]
Hi @reece-r ,
In response to your query-->_Is it possible for us to specify which groups the Author App can find in the 'Send in chat to members using groups' option?_, 
It is not possible because there is no specific api permission available to author which he can select specific groups.
As of now this feature is considered as enhancement and added to backlog. Depending on the bandwidth and priority, this will be taken into consideration in the future releases.

**Comment by reece-r** [comment]
Thanks @gsv022 , is there any limitations to using multiple Teams App Permission Policies with the Company Communicator App? The only other way we can think of working around this security issue is to only allow author to send to M365 Groups and then use a new App Permission Policy for each Teams Company Communicator App instance within the same tenant.

**Comment by v-royavinash** [comment]
@reece-r It is perfectly acceptable to utilize multiple permission policies for controlling user and author app access in various instances of the company communicator. To achieve this, you can create a permission policy, include the corresponding app, and assign it to the appropriate users. Please note that messages will only be delivered to users who are allowed to use the user app of the CC, even if they are part of the DL.

Let us know if you have any further queries.
