### ISSUE TITLE
Transfer data from old version to new deployment?

### ISSUE THREAD

**Issue by frisisuas** [OfficeDev/microsoft-teams-apps-company-communicator#1106]
Good morning,
I keep having some problems with the migration and I would like to know if there is an option to transfer the data from one version to a new deployment and not be able to migrate to a higher version.
Best regards

**Comment by gsv022** [comment]
Hi @frisisuas ,
Thanks for raising the query. 
- Please let us know the issues that you are facing during migration performance. Supporting screenshots would be more helpful.
- As of now, we don't have the option/procedure to transfer the data from one version to latest version unless migration procedure has been performed.

**Comment by frisisuas** [comment]
Thanks for the info.
You can close the issue.

Best regards
