### ISSUE TITLE
Error sending Message to Everyone and M365 groups

### ISSUE THREAD

**Issue by catchzafar** [OfficeDev/microsoft-teams-apps-company-communicator#1107]
Dear Team,
 We have given admin consent to Graph App 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/19735599/c58a6746-4827-4cb3-a999-715c607512f7)

but getting unauthorized errors while sending messages to Everyone and M365 groups

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/19735599/ac7ebd95-5aa1-4b06-9b77-a53299612861)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/19735599/cd47b8a6-3bdb-4a29-8d87-fcf5ea857fcd)

**Comment by gsv022** [comment]
Hi @catchzafar ,
Thanks for raising the query. Please respond to the below queries.
- What is the version of the app?
- Is the message getting delivered using 1st and 2nd sending options?
- Could you please check if the secret values at the app registration are the same as mentioned in the app service configuration, 3-function app configurations. To check and compare, here is the procedure.

1.    Go to Azure Portal

2.  Go to App registration

3. Grab secret value of app registration, 

<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

4. Then go to resource group. Select key vault from list of resources.

5.  Click on secrets under object section.

<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">

6. Compare the secret  with concerned app registration. 

7. If the secrets are not visible, Go to Access Policy--> Click on Create

<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

8.  Select **Key, secret and certificate management**

<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

9. Give the Id through which one can view the secrets

<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

10. 3rd step is optional

11.  Go for Review+Create

12. Then go to Secrets. You will be able to view the secrets

13.  Compare them. Do the same for other app registrations

**Comment by catchzafar** [comment]
Thanks @gsv022 I will check the same and let you know.

**Comment by gsv022** [comment]
@catchzafar , Please let us know the status of the issue
