### ISSUE TITLE
Users not receiving the messages consistently

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#1108]
We have sent 3 messages to around 10,700 users. Some users are not receiving the messages consistently.
For example, some users have not received the 1st message but had got the 2nd and 3rd messages. Some has received the 1st message but not the 2nd and 3rd ones. There was no change done in the policy settings in between the messages being sent.

Screenshot from Delivery status report for these users are given below. We have confirmed that necessary app permission policies are in place for these users. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/eda1a7bd-0765-4cbd-aad5-e022893065a5)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/74b5661a-6944-4b38-827a-ea7180eb16ea)

Please assist to understand why the users are not receiving all of the messages.

**Comment by reece-r** [comment]
@PrithuMahisha  just confirming we are having the exact same issue in our tenant, users in Teams App Permission policy are getting this error after we try to send them a message with the 'ProactivelyInstallApp' set to true. We had some resolution after waiting 72h> and after that point the Teams App Permission Policy seemed to have allowed the app to be installed, but for another policy we have waited over 96h> and still the same error as your issue (despite the App being 'allowed' in the App Permission Policy.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Please share the application insight logs. Here is the procedure.

- Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat.
<img width="502" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6a3f5ebd-839b-4a71-946f-7bb074ebd2fb">

**Comment by reece-r** [comment]
Hi @gsv022 our team is experiencing the exact same issue - should I raise as a new issue to upload our Application Insight Logs?

**Comment by PrithuMahisha** [comment]
@gsv022 , Below are the details from App Insights.

**Log from Microsoft Storage:**
<html>
<body>
<div class="event-property-panel-section" role="region" aria-label="Dependency Properties" style="box-sizing: inherit; margin-bottom: 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;"><span role="presentation" style="box-sizing: inherit;">Dependency Properties</span><div class="float-right" role="button" aria-controls="aria-249" tabindex="0" focusable="true" style="box-sizing: inherit; margin-left: auto;"><span class="text-button" style="box-sizing: inherit; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; color: rgb(1, 92, 218); cursor: pointer; font-size: 14px;">Show all</span></div></div>

Event time | 7/31/2023, 5:00:00.4923962 AM (Local time) |  
-- | -- | --
Type | Azure blob |  
Result code | 409 |  
Call status | false |  
Duration | 298 ms |  
Name | PUT rwmysp56knjuo |  

</div><div class="event-property-panel-section" role="region" aria-label="Command" style="box-sizing: inherit; margin-bottom: 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section-title action-textbox" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px 0px; width: 467px; display: flex; flex-direction: row;"><span class="event-property-panel-section-title-text" role="presentation" style="box-sizing: inherit; white-space: nowrap;">Command</span><div class="action-buttons-container action-textbox" style="box-sizing: inherit; display: flex; flex: 1 1 0%; overflow: hidden; line-height: 30px; font-size: 12px; margin-top: -7px; font-weight: normal; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; margin-left: 0px;"><div class="sg-resize-container" style="box-sizing: inherit; overflow: hidden; height: 35px; width: 396.531px;"><ul class="width-aware-toolbar action-items-table panel-section-command-bar" aria-label="" role="menubar" tabindex="-1" style="box-sizing: inherit; list-style: none; padding: 0px; margin: 0px; width: 396.531px; overflow: visible !important; display: flex; justify-content: flex-end;"><li class="width-aware-item" role="none" title="Copy" style="box-sizing: inherit; display: inline-block; flex: 0 0 auto; cursor: pointer; height: 35px;"><div class="sg-resize-container" style="box-sizing: inherit; overflow: hidden; height: 35px; width: 60.6094px;"><div class="width-aware-item-elem-ref" style="box-sizing: inherit; height: 35px;"><div role="menuitem" title="Copy to clipboard" tabindex="0" class="blade-control-button azure-clickable" focusable="true" style="box-sizing: inherit; cursor: pointer; display: flex; position: relative; font-size: 13px; margin: 0px; padding: 0px 5px; height: 35px; vertical-align: middle;"><div class="blade-control-icon" style="box-sizing: inherit; display: inline-block; line-height: 35px; height: 16px; width: 16px; margin-right: 5px;"><div class="action-icon invert" style="box-sizing: inherit; display: inline-block; width: 16px; height: 16px; margin-right: 8px; vertical-align: sub;"><svg viewBox="0 0 14 16" role="presentation" aria-hidden="true" focusable="false"><path d="M14,6.3V16H4V13H0V0H6.7l3,3h1ZM4,3H8.3l-2-2H1V12H4Zm9,4H10V4H5V15h8ZM11,6h1.3L11,4.7Z"></path></svg></div></div><span class="blade-control-label" style="box-sizing: inherit; display: inline-block; line-height: 35px;">Copy</span></div></div></div><iframe class="sg-resize-monitor" tabindex="-1" aria-label="resize-iframe" src="about:blank" style="box-sizing: inherit; display: block; position: absolute; top: 0px; left: 0px; height: 475px; width: 529px; overflow: hidden; pointer-events: none; z-index: -1; border: none;"></iframe></li></ul></div><iframe class="sg-resize-monitor" tabindex="-1" aria-label="resize-iframe" src="about:blank" style="box-sizing: inherit; display: block; position: absolute; top: 0px; left: 0px; height: 475px; width: 529px; overflow: hidden; pointer-events: none; z-index: -1; border: none;"></iframe></div></div><div aria-readonly="true" aria-multiline="true" role="textbox" aria-label="Command" class="selectabletextbox selectable-wrappable-textbox" contenteditable="true" spellcheck="false" style="box-sizing: inherit; position: relative; font-size: 12px; background: rgb(243, 243, 243); border: 1px solid rgb(192, 192, 192); margin: 5px 0px 0px; font-family: Consolas, &quot;Courier New&quot;, Courier, monospace; padding: 5px; overflow: auto; max-height: 250px; white-space: pre-wrap;">https://rwmysp56knjuo.blob.core.windows.net/exportdatablobs?restype=container</div></div><div class="event-property-panel-section related-items" role="region" aria-label="Related Items" style="box-sizing: inherit; margin-bottom: 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;">Related Items</div></div>
</body>
</html>






**Log from Azure Blob:**

<html>
<body>
<div class="event-property-panel-section" role="region" aria-label="Dependency Properties" style="box-sizing: inherit; margin-bottom: 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;"><span role="presentation" style="box-sizing: inherit;">Dependency Properties</span><div class="float-right" role="button" aria-controls="aria-77" tabindex="0" focusable="true" style="box-sizing: inherit; margin-left: auto;"><span class="text-button" style="box-sizing: inherit; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; color: rgb(1, 92, 218); cursor: pointer; font-size: 14px;">Show all</span></div></div>

Event time | 8/1/2023, 5:00:00.5402902 AM (Local time) |  
-- | -- | --
Type | Azure blob |  
Result code | 409 |  
Call status | false |  
Duration | 437 ms |  
Name | PUT rwmysp56knjuo |  

</div><div class="event-property-panel-section" role="region" aria-label="Command" style="box-sizing: inherit; margin-bottom: 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section-title action-textbox" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px 0px; width: 467px; display: flex; flex-direction: row;"><span class="event-property-panel-section-title-text" role="presentation" style="box-sizing: inherit; white-space: nowrap;">Command</span><div class="action-buttons-container action-textbox" style="box-sizing: inherit; display: flex; flex: 1 1 0%; overflow: hidden; line-height: 30px; font-size: 12px; margin-top: -7px; font-weight: normal; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; margin-left: 0px;"><div class="sg-resize-container" style="box-sizing: inherit; overflow: hidden; height: 35px; width: 396.531px;"><ul class="width-aware-toolbar action-items-table panel-section-command-bar" aria-label="" role="menubar" tabindex="-1" style="box-sizing: inherit; list-style: none; padding: 0px; margin: 0px; width: 396.531px; overflow: visible !important; display: flex; justify-content: flex-end;"><li class="width-aware-item" role="none" title="Copy" style="box-sizing: inherit; display: inline-block; flex: 0 0 auto; cursor: pointer; height: 35px;"><div class="sg-resize-container" style="box-sizing: inherit; overflow: hidden; height: 35px; width: 60.6094px;"><div class="width-aware-item-elem-ref" style="box-sizing: inherit; height: 35px;"><div role="menuitem" tabindex="0" class="blade-control-button azure-clickable" focusable="true" title="Copy to clipboard" style="box-sizing: inherit; cursor: pointer; display: flex; position: relative; font-size: 13px; margin: 0px; padding: 0px 5px; height: 35px; vertical-align: middle;"><div class="blade-control-icon" style="box-sizing: inherit; display: inline-block; line-height: 35px; height: 16px; width: 16px; margin-right: 5px;"><div class="action-icon invert" style="box-sizing: inherit; display: inline-block; width: 16px; height: 16px; margin-right: 8px; vertical-align: sub;"><svg viewBox="0 0 14 16" role="presentation" aria-hidden="true" focusable="false"><path d="M14,6.3V16H4V13H0V0H6.7l3,3h1ZM4,3H8.3l-2-2H1V12H4Zm9,4H10V4H5V15h8ZM11,6h1.3L11,4.7Z"></path></svg></div></div><span class="blade-control-label" style="box-sizing: inherit; display: inline-block; line-height: 35px;">Copy</span></div></div></div><iframe class="sg-resize-monitor" tabindex="-1" aria-label="resize-iframe" src="about:blank" style="box-sizing: inherit; display: block; position: absolute; top: 0px; left: 0px; height: 475px; width: 529px; overflow: hidden; pointer-events: none; z-index: -1; border: none;"></iframe></li></ul></div><iframe class="sg-resize-monitor" tabindex="-1" aria-label="resize-iframe" src="about:blank" style="box-sizing: inherit; display: block; position: absolute; top: 0px; left: 0px; height: 475px; width: 529px; overflow: hidden; pointer-events: none; z-index: -1; border: none;"></iframe></div></div><div aria-readonly="true" aria-multiline="true" role="textbox" class="selectabletextbox selectable-wrappable-textbox" contenteditable="true" spellcheck="false" aria-label="Command" style="box-sizing: inherit; position: relative; font-size: 12px; background: rgb(243, 243, 243); border: 1px solid rgb(192, 192, 192); margin: 5px 0px 0px; font-family: Consolas, &quot;Courier New&quot;, Courier, monospace; padding: 5px; overflow: auto; max-height: 250px; white-space: pre-wrap;">https://rwmysp56knjuo.blob.core.windows.net/exportdatablobs?restype=container</div></div><div class="event-property-panel-section related-items" role="region" aria-label="Related Items" style="box-sizing: inherit; margin-bottom: 15px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;">Related Items</div></div>
</body>
</html>

**Comment by gsv022** [comment]
Hi @PrithuMahisha,
Please delete the existing author, user manifest files and re-upload them again at the admin center level. Then try sending the message. Please keep us posted

**Comment by PrithuMahisha** [comment]
Hi @gsv022 ,
It is not possible now for us to delete the existing Author and user apps from Admin portal because we are already in Production. 

Requesting to provide alternate suggestions/solutions for the mentioned issue.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Please note that re-uploading the manifest files will not erase the previous history.

**Comment by PrithuMahisha** [comment]
Hi @gsv022 , Any other suggestions please?

**Comment by gsv022** [comment]
Hi @PrithuMahisha,
I have sent a procedure to perform over the mail. Please check it out and do let us know how it goes.

**Comment by gsv022** [comment]
Please let us know the status of the issue

**Comment by PrithuMahisha** [comment]
The issue still exists. The number of recipients keeps decreasing. Please have a look at the below screenshot - some users are not there in neither success list nor error list. For example, 

Total number of users - 10,742
Numbers of users for whom message has been sent successfully - 10479
Numbers of users for whom message sending failed - 17
Remaining users - 246


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15922771/7d63af48-d972-48d9-9129-dde8b772a102)

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Please share the export results for the latest message.

**Comment by gsv022** [comment]
Could you please share the export results.

**Comment by PrithuMahisha** [comment]
@gsv022 Due to data privacy/security policy reasons, we are not supposed to share the exact delivery status report. Instead, we have prepared a consolidated report having the error codes and reasons.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mythili.shanmugam/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mythili.shanmugam/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Delivery   Status | Status Reason | Error | Remarks - No.   of users who has the delivery status and reason
-- | -- | -- | --
Succeeded | 201 : OK |   | 10277 users
Failed | -2 : App Not   Installed |   | 140   users - Necessary policy is already assigned to these users
Failed | 403 : Failed | Microsoft.Bot.Schema.ErrorResponseException:   Operation returned an invalid status code 'Forbidden' | 36   users - Necessary policy is already assigned to these users
ResultPredicates`1   shouldRetryResultPredicates | Func`5 onRetryAsync | I | 36 users
CancellationToken cancellationToken) |   |   | 72 users



</body>

</html>

**Comment by PrithuMahisha** [comment]
@gsv022, Any update on this? Do you need any further information from us?

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
We will continue the conversation internally.
