### ISSUE TITLE
Minor changes need to be updated in Product Tips tab

### ISSUE THREAD

**Issue by anandpawar0508** [OfficeDev/microsoft-teams-apps-company-communicator#1109]
1)We should have two drop-down menus 
       a)SEGMENT – A drop-down field with a list of SEGMENTS.
       b)MODULE – A Drop-down field with a list of our Temenos Modules.
2)In the Product Tips Author segment of teams, when we submit the Product Tips Author tab after filling in all the information, all changes should be reflected in the team as a draft message.

kindly connect to me on 9036002345 if you need any clarification.

**Comment by gsv022** [comment]
Hi @anandpawar0508 ,
Thanks for raising the query. Could you please elaborate what modifications you are referring to with supporting screenshots or  links.

**Comment by v-royavinash** [comment]
@anandpawar0508 Could you please share your contact email so that we can understand the requirements and requested features in detail?

**Comment by gsv022** [comment]
Please respond to the above query.
