### ISSUE TITLE
About renewing Client Secret

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#1111]
Hi, teams.

When a client secret will be expired, I think I need to update some passwords, AuthorAppPassword and UserAppPassword and so on,  with a new Client Secret Vaue. 
What about  a new client secret ID ? Also what about an expired old client secret?
May I remove an expired client secret?

**Comment by gsv022** [comment]
Hi @ATshirai ,
Thanks for raising the query. 

- Once the secret is generated, it gives two values. One is secret value and another is secret id. As per the deployment guide, it is recommended to note the secret value. Secret id is negligible.
- If the secrets are expired, generate the new one. Copy the new secret value not the secret id and update it in respective places(author app password, user app password, graph app password).
- After updating resources with new secret values, expired secret can be deleted in app registration section.

**Comment by ATshirai** [comment]
Hi, @gsv022 ,

Thanks for your quick answer. 
But I'm sorry, our Company Communicator is v4, not v5.
When we deployed it , we generated two Client Secrets.
One was for Authore app, another was for User app.

Web app and Azure functions 
have had Client secret IDs, AuthorAppId and UserAppId and AzureAd:ClientId,  on their configrations. Also, we pasted Client secret ID into botId in Teams manifest files, and uploaded them intoTeams.

May I really remove expired client secrets?

**Comment by ATshirai** [comment]
Hi, @gsv022 , 

Thanks for your quick answer.
But I'm sorry I forget to tell a version. our Company Communicator is v4, and v5.
I can remove expired client secrets on Company Communicator v4, right?

**Comment by gsv022** [comment]
Hi @ATshirai ,
- Once the new secret is generated and secret values are updated in the key vault.
- Updating the respective secret Identifiers(present in keyvault) in all the app service, function apps is done. These two steps are applicable to v5
- Since the version used is of v4, update the newly generated secret values directly in app service, 3-function apps. 
- Then try sending a message again. If everything seems to be fine then expired secrets can be deleted from the app registration section

**Comment by ATshirai** [comment]
Hi, @gsv022 

Thank you for kindly reply.
Yes. We do update them directly.
And after checking to send messages successfully , we will remove expired client secrets.

Thanks again.

**Comment by albert-widjaja** [comment]
Can the client secret rotation be automated using this https://learn.microsoft.com/en-us/azure/key-vault/secrets/tutorial-rotation method or must it be manually generated before it expires?
