### ISSUE TITLE
Option to compose and send message from external source

### ISSUE THREAD

**Issue by GhustintheWizard** [OfficeDev/microsoft-teams-apps-company-communicator#1114]
I don't see any mention of an option to tap into, like Graph API, that would allow me to compose and send a message outside of the Teams app UI.  I might have missed something, but please let me know if there is an option to do something along those lines.

We have a WebUI that is used with other alert-type services, so they are asking if we can tie this same feature (Company Communicator) into that single interface.

Thanks!

**Comment by gsv022** [comment]
Hi @GhustintheWizard ,
Thanks for raising the query. We will check with our team and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @GhustintheWizard ,
Currently, we don't have the option to send the messages to outside of Teams app. We will consider this as a enhancement and depending on bandwidth, priority we will take it for future releases post the discussion with the internal team.

Thank you.
