### ISSUE TITLE
Company communicator does not allow sending messages to M365 groups

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1116]
Hi everyone,
When I try to send a message using M365 group, I get the error message "**Permissions needed. Ask your IT admin to enable this option for you.**"

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/423f5959-f5d8-438b-a4e6-b2583fd49946)

Can you please instruct how to resolve this issue?

Below are additional details to help with the investigation.

- The company communicator was previously on version 3 and I have successfully upgrade company communicator from v3 to v4 by following https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide
- After clicking on the sync button, the upgrade straight away gone to version 5.3 on 2nd May
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/f424a9b8-3603-4668-84fa-e5cf8978c2ce)

- The GitHub repo is pointing to main branch of https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git after the sync
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/24f09c0b-17ae-4c74-a3ed-006eeb5c2f8b)

- The Company communicator app registration API permission for v5.3 has the admin consent done which I have followed [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/661a874b-275b-401e-971e-b47353364f0a)

- I have verify the graph app [set up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) step was correctly configured & check mainly on API permissions.

- This issue is same as https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/920 but I do not know how @jmcastillog resolved their issue.

Thanks

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thanks for raising the query. 

- Upon sync it will connect to the latest version of Company Communicator that is what happened in your case. We recommend you to disconnect the existing repository **main** and connect to particular version i.e., v4.x
<img width="800" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/573553c2-8d2e-4ad4-a0ae-2e628f9fa4df">

- Do this for all 3-function apps, app service. 
- Once the status is successful in the logs section of each resource, please open the CC application in browser to avoid any cache issue.

**Comment by David-Liong** [comment]
Thanks @gsv022 

I also reviewed the API permission for communicator app registration and found out that I missed the step for giving **GroupMember.Read.All**l application permissions after reading https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/fe778e5e-7ce2-4460-935c-242fcf00b4d2)
 
I am getting the Global Administrator to approve the admin consent and will later test to send message with M365 groups and update this ticket on the outcome.

**Comment by gsv022** [comment]
Hi @David-Liong ,
The v5.x is having another app registration called graph app registration without that 4th sending option or export functionality won't work. If v4.x is the target, please go with above mentioned approach i.e., connecting to v4.x. And re-installing the app won't do the needful.

Having the Admin consent would be more helpful.

**Comment by David-Liong** [comment]
Hi @gsv022 
The intent was to upgrade to v4.x as being the temporary target from v3.x. Then ultimately upgrade from v4.x to v5.x

OK I will go with above mentioned approach i.e., sync to v4.x main branch repository for all 3-function apps, app service.

After I have sync repo to https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/v4.x  can you please confirm:

- that I will then need to follow instruction https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5 to upgrade CC from v4.x to v5?
- After clicking on the syn button of step 13 in [section 4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#4-deploy-to-your-azure-subscription) will the sync be connected to the latest version of Company Communicator and which version e.g. v5.4?
- If the sync connects to latest version, after upgrading to v5.x do I still then need to follow wiki to upgrade[ from v5.x to latest](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version) or is this final step optional?

Please advise on the right migration path.

Thanks.

**Comment by gsv022** [comment]
Yes, migration process will be from v3.x-->v4.x then v4.x-->v5.x

**Comment by David-Liong** [comment]
Hi @gsv022 
I have disconnect and tried to reconnect the web app repository but failed with error message after I click on the save button.
The error message is:
"Failed to set up deployment:  Cannot find SourceControlToken with name GitHub."

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/db4a0e3d-0e58-40b1-b1a3-95397040adf9)

Have I got the correct input configuration settings?
**Source**: External Git
**Repository**: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/v4.x
**Branch**: main
**Repository Type**: Public

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,
It may happened due to disconnection is still in progress i.e., previous code still getting deleted. Please refresh the page, try to connect the repo and branch again.

**Comment by David-Liong** [comment]
Hi @gsv022 

I just had to wait for Azure to disconnect and delete the old code in the background. I was then able to to sync successfully on the wep apps and the 3 function apps (fun-data, fn-prep & fun-send).

So repo is sync to branch v4.x on version #706
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/be2c50c9-c3bd-4156-af52-563b236fe2ca)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/634292f2-f3d6-45f9-b60a-07e0faabf1c5)

However when I tried to check if the URL of the 3 function apps are running via web browser, I get this error 
"Function host is not running"
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/5416bb5a-4a7d-4e8f-ad00-d4bfd527fbea)
I have restarted the function app service but still get the error.

Why?

**Comment by gsv022** [comment]
Hi @David-Liong ,
I see some obstacles here. 
- **Base Resource Name Character Limitation**:

The chosen base resource name appears to exceed the character limit, which may lead to issues.
<img width="234" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b2bf8029-5581-4135-8f50-f02b8c9861ba">


- **Function Apps Update**:
Function apps previously based on an older version are no longer supported. In the latest version of CC, the function apps have been updated to a newer version. Additionally, the latest version of CC utilizes .NET 6.0, whereas the previous version (v4.x) used .NET 3.1.

- If retaining previous data is not a concern, consider performing a **fresh deployment** to resolve potential issues with the current setup.

**Comment by David-Liong** [comment]
Hi @gsv022 
I want to retain all previous data that used in v.3 after upgrading to v5.x - This is a user business requirement.

What if I just ignore testing CC v4.x after upgrading from v3 to v4 and instead follow the Wiki instruction to complete upgrade from v4.x to v5.x, which will have automatically fixed the existing base resource name URL character limitation, when CC will by then utilizer .NET v6.

Then do the full proper testing of CC v5.x as the benchmark to get v5 fully operational going forward.

Will my recommendation work?

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,
I doubt that the procedure that you are suggesting will lead to the improper working status only due to the above 3 mentioned points shared by me. The only way is to go for fresh deployment only.
Thank you.

**Comment by David-Liong** [comment]
Hi @gsv022 

FYI When I did an upgrade from v3 to v5 (not supported by GitHub community) b accident, I know that the 3 function apps base resource name was running and thus appears to have NO character limit with e.g. https://racwa-dcc-npe-npeteamscommunicator-fn-send.azurewebsites.net/

So, I hope that upgrade from v4 to v5 will fix this issue and then do a rebase line testing of v5.

I will let you know how I go

**Comment by gsv022** [comment]
Hi @David-Liong ,
Yes, it may work in v3 or v4. But in v5 we have a new resource called key vault where the base resource name with key vault as suffix will be appended if that new appended name exceeds the limit of 24 characters eventually results in deployment failure due to key vault resource name violation.

**Comment by David-Liong** [comment]
hi @gsv022 

I have successfully done an upgrade from v4 to v5 and sync the GitHub repo with main branch for both CC web services and the 3 function apps. I haven't yet done a full testing of v5 post deployment.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/b1e59569-060d-4a5f-b5fd-03962e6b4930)

My only question is that because I only follow the Wiki steps to upgrade [from v4 to v5 ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5)

**Do I still have to follow the last instruction to upgrade from v5.x to latest version?**

I ask because when you look at the deployment log version, it shows that 5.4.1 was being built.
and Commit ID: 70f1d623842106f4e8eb57763cf4d9eb01b5cea3

Is v5.4.1 the latest after sync?

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,
When syncing, the system automatically retrieves the most up-to-date code from the CC-repository, which currently stands at version 5.4.1. If you've diligently followed the migration guide, there's no need to repeat any of the steps. Please double-check to ensure that every instruction in the guide has been meticulously executed.

**Comment by gsv022** [comment]
Please let us know the status

**Comment by David-Liong** [comment]
I have done a full new installation of CC v5.5 

The drop down list of M365 group is enabled in v5.5
