### ISSUE TITLE
Author App not working

### ISSUE THREAD

**Issue by MNL79** [OfficeDev/microsoft-teams-apps-company-communicator#1119]
In App Services, I've changed the REACT_APP_HEADERTEXT to a new name (Announcement) from another name (SCOTS Communicator). After clicking Save and then Sync this in Deployment Center, this shows as successful - but no changes have been made.

On attempting to send a test message from the author app, I'm getting an error that doesn't make sense - as the app isn't blocked. I've attached screenshots.

I've tried deleted the Teams apps and recreating them numerous times, but it appears to be the Azure Service that is not right. It is like it looking for the old Teams app. New app created with a new name for roll out.

From the error message it is saying it is failing to install app ID - 2da05f33-e40d-4120-a40b-f6ea71eb7b0e - but the new app ID is a90bdbf3-004b-40e0-a36e-4b80cb1c8e48. I'm guessing the app it is trying to install is the old app??

Anything I've missed?

<img width="481" alt="App Permissions TAC - apps are allowed" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/f69a16c0-28bd-4ba3-8211-50d5a3b049e6">
<img width="302" alt="Error on send of test from app" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/f1e5ede8-9f3e-46a7-97ae-960ac422bdf0">
<img width="634" alt="No Name Change - old name still showing" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/cb7b0ad4-b6ed-4dc6-968c-be8bf08da19f">
<img width="532" alt="Deployment Center Log" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/0cfe957c-abca-428d-9937-92879fb0c2f1">
<img width="778" alt="App Service Configuration REACT_APP_HEADERTEXT" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/739596b9-0d05-4184-9fc6-936c5d002d7a">

**Comment by gsv022** [comment]
Hi @MNL79 ,
Thanks for raising the query. 

- Please try opening the teams in private browser to avoid any cache issue. The name change will reflect.
- Please try sending the message after deleting the **UserappId** in the storage account.

<img width="951" alt="image" src="https://user-images.githubusercontent.com/98143492/194497087-b10d14e8-4aba-46ca-91f4-a0bc952ad2c9.png">

**Comment by MNL79** [comment]
Thanks for the reply 🙂

This has helped with the name of the service - that is now updated.

However, still having issues sending. It is failing to send to any user and if I click to get the Diagnostic report - I get another error.

New app ID is now showing in AppConfig - so that is good.

Is it the author app now, that is the issue?

Screenshots below....
<img width="665" alt=
<img width="548" alt="Error - Diagnostic" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/e9528ea5-a762-4166-b3be-d2dfe537a204">
"Error Sending" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/b06cfc83-363f-4c34-a84c-6dd7e21b5cfe">

**Comment by MNL79** [comment]
<img width="665" alt="Error Sending" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/8c5a0a99-e8cf-4130-93f0-a2855d26a7d6">

**Comment by MNL79** [comment]
<img width="359" alt="Send Summary" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/e6d80142-32e7-45d6-8b3f-ca30959fa77e">

**Comment by MNL79** [comment]
Ok, after deleting the app from the Team and the re-adding it; slightly different problem now.

It shows the attached - but no prompt appears in Chat to allow it to upload to my OneDrive.
<img width="541" alt="Export Queued" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/13de5ac8-f4d0-4e95-89bb-ba42b073bd31">

**Comment by MNL79** [comment]
Not sure if this is just really delayed and it will just start working again?

Further test messages have now got it delivering the message successfully to one user, but not the other 6 - screenshot attached.

User has confirmed they are receiving it too.
<img width="547" alt="Success to 1" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/ab3f6434-0781-47d4-9700-6eab8c32e676">

**Comment by MNL79** [comment]
Further testing update....

Sent a message to a group at 11:47 and it failed for all 7 users. Then sent it again at 12:16 and 2 users received it. It is very odd.

Attached is one of the users that received the message and then then two tests showing in the author app.
<img width="729" alt="User app received for a user" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/ecab4827-5a67-46cc-b03f-594871205722">
<img width="653" alt="fail and then some success" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/8e4bb5e5-81e9-47c5-838e-b23c68d14040">

**Comment by gsv022** [comment]
Hi @MNL79 ,
Please share the export results for latest sent message.

**Comment by MNL79** [comment]
I can't get to them. If I click to get them, it says the export is queued and that I'll be notified in chat to then allow it to upload to my OneDrive - but nothing appears in Chat.

Are they available anywhere else?
<img width="541" alt="Export Queued" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/cc888a65-5df6-4f6b-ae57-bf30d8b3d058">

**Comment by MNL79** [comment]
Not been good - not really working at all - happy to try anything. 

At this point, looks like we'll have to not use this tool/app.

<img width="619" alt="Failures" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/f0c5b870-00a5-4e2b-8a5e-6f526fef32b6">

**Comment by MNL79** [comment]
<img width="877" alt="Forbidden" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/2d7b6062-43a2-4925-9401-63090f97cf2d">

**Comment by MNL79** [comment]
It's working - not sure how or why
