### ISSUE TITLE
Author App - added to Team, but not showing for anyone but me....

### ISSUE THREAD

**Issue by MNL79** [OfficeDev/microsoft-teams-apps-company-communicator#1120]
Had some major issues over the last week, since renaming the app - however, as of Saturday, all is now working again. Assuming it was something I missed or just took time to catch up with the changes.

However, I've created a Team for the app and added it to it - however, if I add members to that Team (that also have author permissions in Azure/app); they do not see the tab/app. So currently, only I can send messages.

Digging about in Azure>Resource Groups, I can see under Channels, in the app - that there are issues with Teams. See attached screenshots.

The app is not disabled by admin, is allowed in app permissions group and in Azure App Registration for the User and Author apps.

Anything I've done wrong or that I can try to resolve this?

<img width="663" alt="SCOTSMess Issue1" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/a512b8b4-51c0-4c78-ae28-a1f053f02ae3">
<img width="254" alt="SCOTSMess Issue2" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134615175/d67faba5-c8f6-4a69-bd86-a95c3e574861">

**Comment by gsv022** [comment]
Hi @MNL79 ,
Thanks for raising the query. I am trying to understand you are able to send the message but others are not. If this is the case, please add their id's to the **senderupn** list in the configuration of app service to get access to the CC-author app. Here is the reference.

<img width="944" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/24ef21d9-28ed-4b04-b68a-c42c67b14a8c">

**Note**:- Each UPN should be separated by semicolon(**;**)
<img width="569" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/01b1ccbe-0231-44ad-8287-f69d41d009fc">
