### ISSUE TITLE
Company Communicator - Rename App?

### ISSUE THREAD

**Issue by erctechdev** [OfficeDev/microsoft-teams-apps-company-communicator#1121]
Hi,
Is it possible to easily rename the app so that instead of the messages appearing from 'Company Communicator' they would appear from for example 'Communications Department' ?   Please see the screen shot of what I am talking about.
Much appreciated,
AR. 
<img width="355" alt="Company Communicator - rename query" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131354948/1c65df7a-c9e0-4b24-a20b-79d011126dd6">

**Comment by gsv022** [comment]
Thanks for raising the query here. Please follow the below steps.
To update name of CC

- Login to Azure Portal with Global Admin Credentials (portal.azure.com)
- Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
-  Click on Azure Bot(user) --> under settings click bot profile-->Change display name as per the organizational need.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/98143492/213981428-e5af8e1e-8623-4731-b413-8cc62cc3c475.png">

- And update the names in the manifest files for user. Re-upload the manifest file again. Here is the place for reference. Please do it for user manifest file
<img width="280" alt="image" src="https://user-images.githubusercontent.com/98143492/213983428-68678fb4-03ae-4a95-933e-0d8e4b4f802d.png">


**Note**:- 
- There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.

**Comment by gsv022** [comment]
Hi @erctechdev ,
Please let us know the status of the issue
