### ISSUE TITLE
Send messages to large set of users from CSV

### ISSUE THREAD

**Issue by ShalinShah84** [OfficeDev/microsoft-teams-apps-company-communicator#1123]
Hi,

Can we increase size of the message in the database so that we can send messages from CSV to 5000 users.
We tried to send a message to around 1000 users and it failed for us.
Any feedback will be appreciated.

**Comment by gsv022** [comment]
Hi @ShalinShah84 ,
Thanks for raising the query. I kindly request the sharing of a screenshot demonstrating the CSV message sending option you're utilizing.

**Comment by ShalinShah84** [comment]
Hi,

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/103025523/3ad5b35b-a348-40d9-a025-33c1d6c048c4)

We don't get any error message while sending messages, but the CSV does not send message to users if the csv file consists of more than 500 records.

**Comment by ShalinShah84** [comment]
We used the following repo
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/v4.1.5

**Comment by gsv022** [comment]
Hi @ShalinShah84 ,
The option feature- _send in chat to list of users provided in a valid CSV_ is yet to be implemented in our official CC. We consider this a customized version. 
Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. 

Please let us know if you have any issues with the standard version.
