### ISSUE TITLE
Need assistance in fixing issue with Company communicator. This is Urgent request and would require faster response please.

### ISSUE THREAD

**Issue by ravikumarpi** [OfficeDev/microsoft-teams-apps-company-communicator#1125]
This is Impact  on our production. please Treat this as Critical.
Message sent from Company communicator are not delivering and We can see on App registration certificate is showing expired.

**Comment by gsv022** [comment]
Hi @ravikumarpi ,
Thanks for raising the query. The procedure is applicable for v5.x of CC. 
- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.
<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">
- If the secrets are not visible, Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
<img width="359" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/eec3cc6d-1455-477f-8918-dd44eb5b2290">

- Grab the new  secret identifier 
<img width="516" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/046b83b5-e8b6-42f4-a4e6-8184cb8d9584">

- Paste it in the configuration sections of  app service, 3-function apps. If it is author app password then update the password like in below sections.
<img width="779" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d9444a9a-fe5b-4d09-8f96-53b70ab40121">

- If it is graph app, please update the password in AzureAd Client Secret as well.

**Comment by gsv022** [comment]
@ravikumarpi , Please let us know the status of the issue
