### ISSUE TITLE
Messages Queued after updating from 5.1.0 to 5.4.1

### ISSUE THREAD

**Issue by DJRaWGOV** [OfficeDev/microsoft-teams-apps-company-communicator#1126]
After updating from version 5.1.0 to 5.4.1 using the instructions provided messages sent are showing as queued.

When reviewing the functions I can see the following errors:

Functions runtime error
microsoft.azure.webjobs.script: Error building configuration in an external startup class. Microsoft.Azure.WebJobs.Script: One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions.ExtensionStartupType DurableTaskWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289' does not meet the required minimum version of 2.4.1. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.4.1 or later.ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later..

AZFD0005
Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error building configuration in an external startup class. ---> Microsoft.Azure.WebJobs.Script.HostInitializationException : One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType DurableTaskWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289' does not meet the required minimum version of 2.4.1. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.4.1 or later. ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later. at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.ValidateExtensionRequirements(List`1 startupTypes) at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 330 at async Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetExtensionsStartupTypesAsync() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 216 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__10_0() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 53 at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication,Boolean useDefaultConstructor) at System.Lazy`1.CreateValue() at System.Lazy`1.get_Value() at Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.GetStartupTypes() at /_/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs : 68 at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalConfigurationStartup(IWebJobsConfigurationBuilder builder,IWebJobsStartupTypeLocator startupTypeLocator,WebJobsBuilderContext context,ILoggerFactory loggerFactory) at D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs : 362 at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayClass7_3.<AddScriptHostCore>b__8(IWebJobsStartupTypeLocator locator) at /_/src/WebJobs.Script/ScriptHostBuilderExtensions.cs : 253 End of inner exception

When going to the function URLs we are getting the following error:

Function host is not running.

[App Service Deployment Center Log.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/12474927/App.Service.Deployment.Center.Log.txt)

**Comment by gsv022** [comment]
Hi @DJRaWGOV ,
Thanks for raising the query.  Have you performed the scripting that is present in the migration guide. If yes, please share the screenshots of function apps showing the run time version as ~4 and app service is set to .NET 6.0. Here is the reference [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#1-update-the-net-version-of-azure-functions-and-app-service-to-support-net-60-)

**Comment by DJRaWGOV** [comment]
Thank you for your response.

I can confirm I did complete the all the steps listed.

![Data-function](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/81504c30-bfe4-4bf7-948c-629e26e19d9d)
![Function](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/081f5864-2f55-4820-af9b-0570a176193c)
![Prep-function](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/dc5e2596-4858-49c9-95c4-59dbe8ecb307)
![Web App](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/fe88dc52-52dc-4e6c-a8c0-271214495a36)
![Script output](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/b6823bb0-f493-4265-a68b-eb75fb0294e3)

**Comment by DJRaWGOV** [comment]
> Hi @DJRaWGOV , Thanks for raising the query. Have you performed the scripting that is present in the migration guide. If yes, please share the screenshots of function apps showing the run time version as ~4 and app service is set to .NET 6.0. Here is the reference [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#1-update-the-net-version-of-azure-functions-and-app-service-to-support-net-60-)

Do you need any more details?

**Comment by gsv022** [comment]
Hi @DJRaWGOV ,
We are going through the logs that you shared.  Meanwhile, Please let us know what is happening at the teams level whether able to send a message  or not and supporting screenshot would be helpful

**Comment by DJRaWGOV** [comment]
Hi @gsv022 ,
I am afraid the messages are still not sending.

![Screenshot 2023-09-04 072315](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/65da01c2-22e6-4c2a-9f30-f39c3f166ce5)

**Comment by gsv022** [comment]
Hi @DJRaWGOV ,
We doubt that secrets might have incorrectly configured. Please cross-check the secrets. Here is the procedure.
- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.
<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">

- If the secrets are not visible, Go to Access Policy--> Click on Create

<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Compare with the secret value in  author/user/graph app registration section

**Comment by DJRaWGOV** [comment]
Hi @gsv022 
I have compared the first few characters of the secrets that are already there and I can confirm that they are the same.

Please ignore this if it isn't relevant but I have also just looked at the functions themselves and can see that they don't have anything listed:
![data-Function](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/a6bd6809-50d9-47d2-8438-e9b928b855ca)
![Function](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/766f16a7-4b7d-4eba-9c00-8a8533590e01)
![prep-Function](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143606758/ac6c5318-8364-445c-a8d8-873faeae7c91)

Is this correct?

**Comment by gsv022** [comment]
Hi @DJRaWGOV ,
Please share your mail id(outlook id) so that we can discuss the issue internally.

**Comment by DJRaWGOV** [comment]
Hi @gsv022,
Please contact me via DJRaWGOV-GITHUB@richmondandwandsworth.gov.uk and I will share the details with you privately after that.

**Comment by gsv022** [comment]
@DJRaWGOV , It is confirmed that issue got resolved upon sync to latest version. Hence closing out the issue. If there is any issue faced please log a new issue we will be more than happy to assist you.
