### ISSUE TITLE
Permission Needed to chat memebers of a M365 Group

### ISSUE THREAD

**Issue by Boy2607** [OfficeDev/microsoft-teams-apps-company-communicator#1127]
When I try to send a message using M365 group, I get the error message "Permissions needed. Ask your IT admin to enable this option for you.", we could use earlier this week and occurred this error on yesterday.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/1b4cc8ad-98ea-45be-b5ed-df3b1a0fc7fc)

Below are additional details to help with the investigation.
**1.** The version of the app is 5.4.1
**2.** The GitHub repo is pointing to https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git
**3.** Branch is pointing to https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/01695d79-7472-45c3-926b-87c9d5daec97)
**4.** Check for API permissions has been added and granted admin consent
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/28e6383c-02b9-4790-8824-a8cbd737fcaf)
**5.** I have verify the graph app [set up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) step was correctly configured
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/050ff348-3d20-4b52-8635-7763253f7d54)
**6.** Client secret can use.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/f3787763-c623-46fe-8bc6-5f31694bf56c)
**7.** All test messages are gone from main page (We've tested 4 messages)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/df215a24-965f-43db-8165-b93ac6385b07)
**8.** We also unable to send the message through remaining 3 sending options

Please assist to understand why we can't use this option and instruct how to resolve this issue. Thank.

**Comment by gsv022** [comment]
Hi @Boy2607 ,
Thanks for raising the query. Please respond to the below queries.

- Were you able to use the 4th sending option previously?
- Are you able to export the results for other three sending options?

**Comment by Boy2607** [comment]
Were you able to use the 4th sending option previously?
**Answer**: this is a fresh deployment (not from migrate with the old version)

Are you able to export the results for other three sending options?
**Answer**: Just "Send in chat to everyone" option that could create a draft. For the rest, it's not show team name when we input the name
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/ec1c9689-a305-4d69-b752-f781e0dd5a9c)

**Comment by Boy2607** [comment]
Hi,
It seems this option is available now. Please explain us about why this issue was occurred and how to resolve this issue if it's happen in the future.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/49b21277-9bac-4500-b17d-c9b46b0e7b40)

**Comment by gsv022** [comment]
Hi @Boy2607 ,

- For 1st and 2nd sending options, as you highlighted that in the dropdown getting as- _Couldn't find any matches_. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue.
- Great that 4th sending option is working fine. Since we didn't get a chance to look through entire configuration right we can't comment on that.
