### ISSUE TITLE
Timeout when calling microsoftTeams.authentication.notifySuccess(); in company communicator.

### ISSUE THREAD

**Issue by chenguyuan** [OfficeDev/microsoft-teams-apps-company-communicator#1128]
Issue

=========

[Extensibility] Timeout when calling microsoftTeams.authentication.notifySuccess(); in company communicator. 

 

Background

=========

Customer used Microsoft app templates "Company communicator" and deployed an customized app, no code change.

[https://learn.microsoft.com/en-us/microsoftteams/platform/samples/app-templates](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__learn.microsoft.com_en-2Dus_microsoftteams_platform_samples_app-2Dtemplates%26d%3DDwMFAg%26c%3DYd6fwksshA3zI-LNKA26tw%26r%3DCWYGXlOOuXAISx5SLQTIP7Wrzx9W4LsXIBeIYQo50p4%26m%3DETfO43aY9y1dbEPBWVAVZaeiGpM6cJlwtATZLpoUnVWK6xUW37zRtQrXsWsomS-q%26s%3DS2RZy0jTZqMVwn01wgwaeQT7KM3MUtivnLrPwJAEnAA%26e%3D&data=05%7C01%7CGuyuan.Chen%40microsoft.com%7C10d06681fb9d445669b108dba9330882%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638289809583963005%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y40oXpKMuvUVldSNuocZffFq1vNt7T56bP1mGrJPwRQ%3D&reserved=0)

 

The customized app was working when between June-July, but the "draft message" function is not working since middle of Augest.

the expected behavior is a popup tab with editing message window. 

<img width="707" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8943620/dc853cd2-735b-466e-a3ca-a523b728f6a4">

 

Troubleshooting

============

 logs shared with microsoft onedrive: https://microsoftapc-my.sharepoint.com/:f:/g/personal/guc_microsoft_com/EuR-LLMGJ2ZBg2wNfzpHXysBxdbmWyTGYquYaG2sKzOlzA?e=SF4p4m 

1. collect fiddler and client log, all fiddler trace showing 20X no error located.

Client log indicates the popup tab is timed out for notifySuccess() when doing some authentication task in the popup tab

2023-08-25T03:19:19.475Z Inf             ExtensionTabBase: **Tab timedout waiting for notifySuccess()**: App id = 6ba272cb-595f-4515-bdee-e324b8d7df85, AppSessionId =  177d031b-0ae9-42a6-b59e-a362daa6f143, AppLaunchId =  7d7705c0-d163-4304-89e8-f2e1792b88e7

 

2. I checked the company communicator github, it called microsoftTeams.authentication.notifySuccess(); 

…..

const hashParams: any = getHashParameters();

    if (hashParams["error"]) {

      // Authentication/authorization failed

      microsoftTeams.authentication.notifyFailure(hashParams["error"]);

    } else if (hashParams["id_token"]) {

      // Success

      microsoftTeams.authentication.notifySuccess();

    } else {

      // Unexpected condition: hash does not contain error or access_token parameter

      microsoftTeams.authentication.notifyFailure("UnexpectedFailure");

    }

The challenge is how to troubleshooting further on this timeout. thanks.

**Comment by gsv022** [comment]
Hi @chenguyuan ,
Thanks for raising the query. We will check it out and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @chenguyuan ,
Please share the repo URL and branch that has been connected during the deployment. Here is the reference.
<img width="854" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/543be073-79c4-48d9-8f3a-6805cc2bc0ab">

**Comment by chenguyuan** [comment]
> Hi @chenguyuan , Please share the repo URL and branch that has been connected during the deployment. Here is the reference. <img alt="image" width="854" src="https://user-images.githubusercontent.com/98143492/266225427-543be073-79c4-48d9-8f3a-6805cc2bc0ab.png">

Hi @gsv022 , sorry for the delay, the customer just replied. following is the URL and branch:

[https://github.com/cristianoag/microsoft-teams-apps-company-communicator.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcristianoag%2Fmicrosoft-teams-apps-company-communicator.git&data=05%7C01%7CGuyuan.Chen%40microsoft.com%7Ccfb0eae495f94a6b14ed08dbb829e3f7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638306262382286344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0%2Bc2eTWTtcicXC0EqkWLWfIx5PxH1vTIdnXHy%2FmDPGY%3D&reserved=0)
<img width="724" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8943620/7ae5efda-b70a-42c8-9918-44458d81a4bf">

**Comment by gsv022** [comment]
Hi @chenguyuan ,
Please note that our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version. 
Here is our repository- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
