### ISSUE TITLE
User Application not found while trying to send message in Company Communicator

### ISSUE THREAD

**Issue by Nadeem21210** [OfficeDev/microsoft-teams-apps-company-communicator#1129]
Dear team

I am getting error that user application cannot be found while trying to send message.
The Application is already uploaded via Manage Apps and is visible over there.
Also, while testing company Communicator locally with Author group the application does not get pinned although i have pinned it to myself manually.

Apprecaite your support on priority.

Regards
Nadeem

**Comment by gsv022** [comment]
Hi @Nadeem21210 ,
Thanks for raising the query. Within the sending options page whether able to see the teams names under dropdown. If no, Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by Nadeem21210** [comment]
user 
![userapp](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140392236/cc0810b2-a1c2-451e-9202-a517ffca52d6)
app is installed for everyone.
Attached is the screenshot for reference.

**Comment by gsv022** [comment]
Please give us sometime we will get back to you soon.

**Comment by gsv022** [comment]
Hi @Nadeem21210 ,
Please keep us posted if anything comes up otherwise we can make it to closure.
