### ISSUE TITLE
Unable to company Communicator to send messages to Office 365 Groups

### ISSUE THREAD

**Issue by Heindrick03** [OfficeDev/microsoft-teams-apps-company-communicator#1130]
Hello,

I'm unable to company Communicator to send messages to Office 365 Groups
Deployment has been deployed successfully without error and the graph permissions are verified.

GitRepoURL : https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git
GitBranch: Main

Regards,
Heindrick

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
Thanks for raising the query. Could you please respond to the below queries.

- Is this a fresh deployment?
- Are you able to send the messages using other three sending options.
- Please share the error that is getting displayed for 4th sending option with a supporting screenshot.
- Are you able to export the results for the sent messages?

**Comment by gsv022** [comment]
Please respond to the above queries.

**Comment by Heindrick03** [comment]
Hi Sai,

Sorry for my late reply.
Please find my answers below.


Cordialement / Regards,



Didier TAIN
Digital WorkSpace

Tel: +33 1 86 99 88 88
Email: ***@***.******@***.***>

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
Please cross-verify the authentication steps mentioned in the deployment guide and confirm with supporting screenshots. Here is the[ link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication).

**Comment by Heindrick03** [comment]
Hello Sai,

As I did not configure this, from which app should I provide the screenshots?
Please find the 3 apps below and their configuration :

***@***.***

***@***.***

***@***.***


Cordialement / Regards,



Didier TAIN
Digital WorkSpace

Tel: +33 1 86 99 88 88
Email: ***@***.******@***.***>

**Comment by Heindrick03** [comment]
Hello Sai,

As I did not configure this, from which app should I provide the screenshots?
Please find the 3 apps below and their configuration :

***@***.***

***@***.***

***@***.***

Cordialement / Regards,



Didier TAIN
Digital WorkSpace

Tel: +33 1 86 99 88 88
Email: ***@***.******@***.***>

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
We are not able to see the screenshots that has been shared. They are in masked state. Please share the screenshots of graph app as per the link shared above

**Comment by Heindrick03** [comment]
Hello Sai,

I hope it’s the requested information.
Please find the permissions for the 3 apps:

***@***.***

***@***.***


***@***.***



Cordialement / Regards,



Didier TAIN
Digital WorkSpace

Tel: +33 1 86 99 88 88
Email: ***@***.******@***.***>

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
This is how we are getting the screenshots. Please post it directly here.
<img width="521" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/7dd26b1e-5d4e-4082-8cc5-476fd86d0236">

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
Thanks for sharing them here. How about Authentication, expose an API, manifest in graph app? Please share the screenshots of them for better troubleshooting. Here is the[ link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication).

**Comment by Heindrick03** [comment]
Hi @gsv022 ,

Here are the screenshots:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144246703/aef16838-2a7e-409f-b072-3a271b009334)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144246703/d3a68eff-ddba-491d-b0ed-c6cf76c0de77)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144246703/913cf96b-e31f-4db0-abd5-8e790e59d36d)

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
In the graph app, the authentication part is yet to filled. Please refer the deployment guide. 
<img width="673" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5d97b1ef-a490-46df-93bf-f403aab579df">

**Comment by Heindrick03** [comment]
Hi @gsv022 ,
Can you please guide me how to do this?
The apps have been deployed by someone who left the company.
Which one should I add (App, Author or User)?
What is the value for %appDomain% or AppName?

**Comment by gsv022** [comment]
Hi @Heindrick03 ,

- _Which one should I add (App, Author or User)?_
Ans: - App(i.e., graph app)

- _What is the value for %appDomain% or AppName?_
Ans: -It is Base resource name that has been given during ARM template filling. Here is the reference.
<img width="950" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/778b033c-7715-4787-bf80-8866a4c51542">

- Follow the deployment guide for next steps. If any issue comes, please post here. We will assist you.
