### ISSUE TITLE
Bot fails to send a message to a user

### ISSUE THREAD

**Issue by rmerino06** [OfficeDev/microsoft-teams-apps-company-communicator#1132]
We are testing our second Company Communicator to smalls groups and found that the bot was unable to send the message to some users. 

We have tried sending with the option "Sent in chat to people in teams" and "Sent in chat to members of the following groups" with the same result. We have tried cleaned Teams cache and problem persists.  

Version App: Version 5.4.1

The error report is details below:

User ID,UPN,Name,User   Type,Delivery Status,Status Reason,Error
--
3adde888-7b8a-4ce8-hhhhhhhhhhhhh,yyyyyyyyy@xxxxxxx.com, zzzzzzzzzzzzz,Member,Failed,403 :   Failed,"Microsoft.Bot.Schema.ErrorResponseException: Operation returned   an invalid status code 'Forbidden'
at   Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String   conversationId, String activityId, Activity activity, Dictionary`2   customHeaders, CancellationToken cancellationToken)
at   Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations   operations, String conversationId, String activityId, Activity activity,   CancellationToken cancellationToken)
at   Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext   turnContext, Activity[] activities, CancellationToken cancellationToken)
at   Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter\|1>d.MoveNext()
--- End of stack trace from previous   location ---
at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity   activity, CancellationToken cancellationToken)
at   Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext()   in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94
--- End of stack trace from previous   location ---
at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3   action, Context context, CancellationToken cancellationToken,   ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1   shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount,   IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean   continueOnCapturedContext)
at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context   context, CancellationToken cancellationToken, Boolean   continueOnCapturedContext)
at   Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext()   in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94"
df771efa-d816-4af9-9336-xxxxxxxxx,yyyyyyyyy2@zzzzzz.com,xyz ,Member,Succeeded,201 : OK,

**Comment by gsv022** [comment]
Hi @rmerino06 ,
 Thanks for raising the query. Please respond to the below queries.
- Are you able to send the messages using other two sending options?
<img width="258" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/ce73fa0a-29fb-484a-b6b8-bfb54712a01d">

- Is second instance of CC added to the same team where first instance is added. Please clarify.

**Comment by rmerino06** [comment]
Hi gsv022.
I tried with the option "Send to the General Channel of specific teams" and it post the message successfully. I didn't tried the "send in chat to everyone" because we are testing.
And yes, the second instance of CC is added to the same Team where first instance was added. 

R

**Comment by gsv022** [comment]
Hi @rmerino06 ,
Please try adding the author app and user app to a different team and try testing it. It is fine to have multiple instances in the same tenant but not in the same team.

**Comment by rmerino06** [comment]
I tried what you recommend but I've got the same result.

**Comment by CarlosGuadamuz** [comment]
Same here

**Comment by gsv022** [comment]
Hi @rmerino06 ,

- Navigate to Azure portal and open company communicator deployed resource group.

- Click on “Storage account”.

- Expand “Tables” section.

- Open “AppConfig” table.

- Delete the second record where Rowkey is entered as “UserAppId”.
<img width="617" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/e9ca4677-cb8b-4bc2-9c25-96cf4a40e1ff">

**Comment by rmerino06** [comment]
Still not working

**Comment by gsv022** [comment]
Hi @rmerino06 ,
Please share your mail id (outlook id) so that we can continue the conversation internally.

**Comment by rmerino06** [comment]
Still waiting on a respond

**Comment by gsv022** [comment]
Hi @rmerino06 ,
Could you please send it here directly here as the mail id  is in masked state we are not able to see it.

**Comment by catchzafar** [comment]
Hi Team,
 I am also getting same error, Any help?
 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/zraza/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/zraza/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Member | Failed | 403 : Failed | Microsoft.Bot.Schema.ErrorResponseException:   Operation returned an invalid status code 'Forbidden'             at   Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String   conversationId, String activityId, Activity activity, Dictionary`2   customHeaders, CancellationToken cancellationToken)             at   Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations   operations, String conversationId, String activityId, Activity activity,   CancellationToken cancellationToken)             at   Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext   turnContext, Activity[] activities, CancellationToken   cancellationToken)             at   Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter\|1>d.MoveNext()          --- End of stack trace from previous location ---             at   Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity,   CancellationToken cancellationToken)             at   Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext()   in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94          --- End of stack trace from previous location ---             at   Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context   context, CancellationToken cancellationToken, ExceptionPredicates   shouldRetryExceptionPredicates, ResultPredicates`1   shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount,   IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean   continueOnCapturedContext)             at   Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context,   CancellationToken cancellationToken, Boolean continueOnCapturedContext)             at   Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext()   in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94
-- | -- | -- | --




</body>

</html>

**Comment by catchzafar** [comment]
Dear Team,
Just to update that, we find out that the app was unavailable to few users due to custom App policy was enabled for users, due to that global org policy was not applied to them. We disabled all test policy and tried to send message to everyone, and it sends to all without any failure. Hope this may work for you as well.

_PS: it may take up to 24 hours to rollout the updated policy for users._

**Comment by gsv022** [comment]
@rmerino06 , I have mailed you. Could you please check and reply

**Comment by rmerino06** [comment]
I had replied several times with my availability for a meeting. We haven't met yet.

**Comment by gsv022** [comment]
Hi @rmerino06 ,
i have sent a meeting invite. Hope you have received it.

**Comment by gsv022** [comment]
Hi @rmerino06 ,
Thanks for joining the call. Upon clearing the data in the tables of storage account, messages started getting delivered again. For delete message functionality, upgrade to the latest version.  please refer to this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) for upgradation
Please let us know if anything is required otherwise we can make it to closure.
