### ISSUE TITLE
unknown issue

### ISSUE THREAD

**Issue by andrewh-tecex** [OfficeDev/microsoft-teams-apps-company-communicator#1139]
Hi i seem to have all the correct permissions but it keeps failing.
[logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/12607798/logs.zip)

**Comment by gsv022** [comment]
Hi @andrewh-tecex ,
Thanks for raising the query. We see that role-assignments got failed. Please follow this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#2-app-deployment-failure---roleassignmentupdatenotpermitted) to fix the issue

Keep us posted

**Comment by andrewh-tecex** [comment]
SOrry and the final thing, the app deployed but i am getting this
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/84127074/dfd9ddee-4a7d-46d8-b572-696065439243)

**Comment by gsv022** [comment]
Hi @andrewh-tecex ,
Please let us know the status

**Comment by andrewh-tecex** [comment]
> Hi @andrewh-tecex , Please let us know the status

[logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/12616780/logs.zip)

Hi i tried to redeploy and it is saying the deployment is too large

**Comment by gsv022** [comment]
Thanks for the update. It is confirmed that the issue got resolved. Hence closing out the issue.
