### ISSUE TITLE
Would it be possible to change the notification?

### ISSUE THREAD

**Issue by Hejhejhalla** [OfficeDev/microsoft-teams-apps-company-communicator#1140]
Hi,

Would it be possible to change from a card being sent to normal text?
For example the text that is entered in the "Summary" field.

**Comment by gsv022** [comment]
Hi @Hejhejhalla ,
Thanks for raising the query.  Could you please brief us on your requirement.

**Comment by Hejhejhalla** [comment]
Instead of an adaptive card being sent, would it be possible to just send out a normal text message?
Currently when we send out a message it is being displayed as in this picture: https://user-images.githubusercontent.com/57713084/68764211-965fd280-061a-11ea-9650-bd05a914616d.jpg

For us it would be more beneficial if we could replace that text with the value of "Summary" for example.

Here they have done something similar I believe but it's a static text:
https://techcommunity.microsoft.com/t5/iis-support-blog/how-to-change-notification-text-when-bot-sends-an-adaptive-card/ba-p/1945008


Guess our requirement is to have an option to choose between sending an adaptive card (with buttons, images etc..) or a normal text chat. :)

**Comment by gsv022** [comment]
Hi @Hejhejhalla ,
While our application does facilitate message broadcasting through adaptive cards, please note that customization according to your specific requirements is indeed possible. However, it's important to highlight that we have not yet explored this customization aspect internally. Our support scope is very limited with the standard version. We can't assist on customizing the message notification. 

Please let us know if you have any queries.

**Comment by Hejhejhalla** [comment]
Would it be possible to get pointed in a direction on what file or files that need to be edited? Or which directory

**Comment by gsv022** [comment]
@Hejhejhalla , We can't comment on this as we don't know the exact outcome. Please let us know if you have any queries w.r.t standard version of CC otherwise we can make it to closure.
