### ISSUE TITLE
Web App Fail

### ISSUE THREAD

**Issue by andrewh-tecex** [OfficeDev/microsoft-teams-apps-company-communicator#1141]
Hi i am getting a conflict and a bad request error
[logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/12618270/logs.zip)

**Comment by gsv022** [comment]
Hi @andrewh-tecex ,
Thanks for raising the query.
- As you mentioned app service resource is failed. Please follow the below steps

- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select  webapp from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository.
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well(if there are any other failed resources)

**Comment by gsv022** [comment]
Hi @andrewh-tecex ,
Please let us know the status
