### ISSUE TITLE
CC Message history only goes back about 12 days

### ISSUE THREAD

**Issue by EMEAWebEnvironmentsTeam** [OfficeDev/microsoft-teams-apps-company-communicator#1142]
Hello,

We are using CC version 5.3 and have started noticing an issue in the last couple of weeks where scrolling up through the received message history from the CC stops at around 12 days in the past. As time goes on this stopping point progresses too, for instance previously we could only scroll to messages from 05/09, and today we can only scroll to messages from 06/09.

Searching for past messages (before say 06/09) does find them and allows you to scroll freely through past messages.

Is this something others have seen, is it perhaps an issue with the storage account or some settings somewhere which is limiting the amount of messages which appear?

Appreciate any advice, thanks!

**Comment by gsv022** [comment]
Hi @EMEAWebEnvironmentsTeam ,
Thank you for bringing up this query. In the CC Author app, the default page displays 25 rows in the 'Sent Messages' section. If you require access to more than 25 rows, kindly visit the Azure Portal and navigate to the resource group within the storage account for further options.

**Comment by EMEAWebEnvironmentsTeam** [comment]
> Hi @EMEAWebEnvironmentsTeam , Thank you for bringing up this query. In the CC Author app, the default page displays 25 rows in the 'Sent Messages' section. If you require access to more than 25 rows, kindly visit the Azure Portal and navigate to the resource group within the storage account for further options.

Hi @gsv022,

Thanks for your response. In this case we aren't referring to the CC Author app, but the User App where the messages are appearing. In the past we have been able to see the entire message history, but recently we are only able to scroll up to a certain point before it stops and does not reveal any further communications.
The communications from further in the past definitely exist as they can be searched for, and they also appear in the Azure storage

**Comment by gsv022** [comment]
Hi @EMEAWebEnvironmentsTeam ,

- Please check the same in browser version of teams to avoid any cache issues.
- If the issue still exists, we recommend you to check with the Teams platform support team for further troubleshooting.

**Comment by EMEAWebEnvironmentsTeam** [comment]
Hi @gsv022,

The issue remains in the browser version. It appears to be ok on the mobile version, however.
We will raise this as an issue with the Teams support team in that case, thanks for your help.

**Comment by gsv022** [comment]
We are closing the issue as we suggested to reach out to Teams platform support team to look into the issue further.
