### ISSUE TITLE
Error while sharing message

### ISSUE THREAD

**Issue by chandni-agarwal** [OfficeDev/microsoft-teams-apps-company-communicator#1144]
Hi Team, The company communicator resource had been migrated to a new subscription and front door had also been created in new subscription, however, facing the following issue while sharing the message.
<img width="314" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/23003280/5163c64e-c84b-4519-80ec-3166fa20708c">

**Comment by gsv022** [comment]
Hi @chandni-agarwal ,
Thanks for raising the query.  Please share the apps insight logs  for further investigation.

**Comment by gsv022** [comment]
It has been followed up internally.

**Comment by gsv022** [comment]
Hi @chandni-agarwal ,
Since it has been followed up internally, we are closing the issue here.
