### ISSUE TITLE
False success message received in the Delivery Status Report

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#1148]
Hi Team,

1. We have come across a scenario in which we have received a false success (202: OK) for a user. What could be the root cause for this issue?
2. Users are not receiving the messages consistently. For example, some users have not received the 1st message but had got the 2nd and 3rd messages. There was no change done in the policy settings in between the messages being sent. What could be the root cause for this issue?

Background:
We are sending messages to around 11k users in which we are facing these issues. 
Reference Github link: [https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1108](url)

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by PrithuMahisha** [comment]
Hi @gsv022,

Is there any update on this?

Additional info: For 2nd query, we have performed the following testing as suggested.
1. Created a small distribution group of around 20 users who did not receive the message in the larger group, however policy is assigned to them.
2. Tried sending the message to this distribution group.
3. Same behavior is observed. Messages were not delivered to any of these users.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,

- Could you please confirm that 20 users are having valid teams license. 
- There is a possibility that users might have deleted the CC -user app within the chat section of their teams. Please cross-verify.
- Coming to the above two points highlighted in the issue, this might be due to sync issue. Did you get a chance to perform the workaround that has been shared over mail to you in the last conversation? if not, please try it and let us know.
```

- We have come across a scenario in which we have received a false success (202: OK) for a user. What could be the root cause for this issue?

- Users are not receiving the messages consistently. For example, some users have not received the 1st message but had got the 2nd and 3rd messages. There was no change done in the policy settings in between the messages being sent. What could be the root cause for this issue?

```

**Comment by PrithuMahisha** [comment]
Hi @gsv022 

- Could you please confirm that 20 users are having valid teams license.
   Ans: We have confirmed that these 20 users have valid Teams license and also have necessary App permission policies assigned.

- There is a possibility that users might have deleted the CC -user app within the chat section of their teams. Please cross-verify.
  Ans: We have cross-verified that the users did not delete the CC app. We send messages on a bi-weekly basis and they do not receive all of those messages. Also, some users have received false success message.
  

- Coming to the above two points highlighted in the issue, this might be due to sync issue. Did you get a chance to perform the workaround that has been shared over mail to you in the last conversation? if not, please try it and let us know.

  Ans: We have performed the workaround steps mentioned in the email. As mentioned already, same behavior is observed. Messages were not delivered to any of the affected users.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
We will get back to you shortly.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Could you please let us know the status

**Comment by PrithuMahisha** [comment]
I have shared the Application Insights logs over email

**Comment by gsv022** [comment]
We have shared the observations.

**Comment by PrithuMahisha** [comment]
We will check the given feedback and provide an update. Please do not close the case.

**Comment by gsv022** [comment]
yup, please keep us posted

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Could you please let us know the status

**Comment by PrithuMahisha** [comment]
Hi @gsv022 ,

Thanks for your support so far. We have got the feedback that the issue is not reproducible now. So please close this case.

**Comment by gsv022** [comment]
Thank you for the update.
