### ISSUE TITLE
Company Communicator

### ISSUE THREAD

**Issue by cholman1** [OfficeDev/microsoft-teams-apps-company-communicator#1149]
We got the failed error below when trying to set up Company Communicator in our test tenant
.

There was a conflict. Conflict with existing ScmType: ExternalGit (Target: /subscriptions/08e746cf-1e01-453a-8bf1-6e3369d8a8e2/resourceGroups/CompanyCommunicatorRG/providers/Microsoft.Resources/deployments/Microsoft.Template-20230920150920)

_______________________________________

**Comment by cholman1** [comment]
![MicrosoftTeams-image (2)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145700698/29002a0a-f5d5-46fb-86df-e7311e1c93a9)
![MicrosoftTeams-image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145700698/0f894c6c-5331-4bd9-bd32-3ee928a072da)

**Comment by Khiron91** [comment]
Actually have the same issue but came one step further in deleteting the webapp and redeploying it --> I have left the rest untouched and the app deployed without any issue now BUT i have now a different issue which seems solveable in generating new GUIDs but have to test it with enother deployment run now

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124042836/2b887374-769b-43f6-afb7-117e4b9b5847)


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124042836/0c1242ff-ad55-4e84-b114-78f1b0a0be88)

**Comment by Khiron91** [comment]
i had to delete the web app + change the servicebus web / storage web guid (changing the last character to a different one) and now the deployment is complete

**Comment by gsv022** [comment]
Hi @cholman1 ,
Thank you for logging the issue. Please let us know if anything is required from our side otherwise we can make it to closure.

**Comment by cholman1** [comment]
Ah, ok.  Can you show a example of (change the servicebus web / storage web guid (changing the last character to a different one)

**Comment by Khiron91** [comment]
First as written you have to deleted the faulty web app 
Then, select the resource group where you made your deployment and click on redeploy to your last deployment (see screenshot)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124042836/42422d49-32f7-44d7-a4d2-50f1e60854ac)

You will get some fields to get re-filled like the 3 AppIDs (User, Author, Graph) + on the bottom the GUIDs. Here you have to change the listed Storage + Service Bus Web GUIDs. it is written in HEX so i have raised the last character one letter: b-->c 1--2

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124042836/6b16c068-1ffb-407a-b481-938b13ec2fa5)

after this changes my re-deployment suceeded

**Comment by gsv022** [comment]
Hi @cholman1 ,
Since you went for re-deployment, the default GUID's has already been used for 1st deployment. When we go for re-deploy it is mandatory to change the 7 GUID's as shown above to avoid the role assignment issues. And changing a alphabet or a numeric may or may not guarantee the GUID to be valid. It is always better to choose valid generator GUID tool . Here is the [reference](https://www.guidgenerator.com/online-guid-generator.aspx)

Please let us if you have any queries.

**Comment by cholman1** [comment]
Hello Khiron91,
I am trying to delete the faulty web app, not sure if I did, where do I go to delete it?
Also, where can I find the second screen shot, the Guid to make the last character change?
I am learning this and this would be great if you can point that out.

**Comment by Khiron91** [comment]
On your first screenshot you have made a screenshot of the deployment center within the problematic app. This is the web app which you have to delete. The Delete Option should be available when you click in the Navigation to Overview or within the Resource Group View.

After you have deleted the web app you have to click on your Resource Group where all your stuff is in and in the Resource Group you have in the Navigation "Deployments" where you should see your Initial deployment + you have the option there on the top to re-deploy. --> this is the screenshot which i posted. after you click on re-deploy you will get the ID´s and all things.

**Comment by cholman1** [comment]
Thank you, it has been resolved.

**Comment by cholman1** [comment]
I was successful, but now adding the app to Teams I am getting the below for the Author but Users is ok. :



***@***.***

**Comment by gsv022** [comment]
Hi @cholman1 ,
We are not able to see the issue screenshots as they are in masked state. We request you to share them here directly.

**Comment by cholman1** [comment]
After uploading.

***@***.***

**Comment by gsv022** [comment]
Hi @cholman1 ,
The screenshot is appearing like this. Please share it directly here
<img width="503" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/bd6d8300-767d-40a5-9aec-3bedcd9d86dc">

**Comment by cholman1** [comment]
I get the first image for a quick second and then get the second one with the error.

First Screen shot:

***@***.***
Second Screen Shot:

***@***.***

**Comment by cholman1** [comment]
Ok, looks like it works in the local Client Teams but not in the Cloud Teams, does it not work for the Cloud Teams?  I was able to tested messages on the local client to a group but it failed to send to a Teams group, see below.   Any thoughts??

***@***.***

From: Clifford Holman ***@***.***>
Sent: Friday, September 29, 2023 11:23 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Company Communicator (Issue #1149)

I get the first image for a quick second and then get the second one with the error.

First Screen shot:

***@***.***
Second Screen Shot:

***@***.***

**Comment by cholman1** [comment]
I am getting the below message when trying to send a message to a team.  Please see second screen shot on error received.


***@***.***

***@***.***



From: Clifford Holman
Sent: Friday, September 29, 2023 1:02 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Company Communicator (Issue #1149)

Ok, looks like it works in the local Client Teams but not in the Cloud Teams, does it not work for the Cloud Teams?  I was able to tested messages on the local client to a group but it failed to send to a Teams group, see below.   Any thoughts??

***@***.***

From: Clifford Holman ***@***.******@***.***>>
Sent: Friday, September 29, 2023 11:23 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Company Communicator (Issue #1149)

I get the first image for a quick second and then get the second one with the error.

First Screen shot:

***@***.***
Second Screen Shot:

***@***.***

**Comment by gsv022** [comment]
Hi @cholman1 ,
Still the screenshots are in masked state. We recommend you to share the screenshots directly here.

**Comment by cholman1** [comment]
Here is the images attached in this comment, unable to complete a send of a message from Company Communicator, it failes going to the Teams Group. 
![Image01](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145700698/90e3c053-03bd-458c-ab75-ae8daf8f69d9)
![image02](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145700698/c4873f3c-1092-43be-803d-4a4d36efbc4b)

**Comment by cholman1** [comment]
Just recent a attachment through the Githup open case.

**Comment by gsv022** [comment]
Hi @cholman1 ,

- How about other sending options?
-Please check you tenant id within the deployment section. It seems incorrect. Here is the reference. 
<img width="953" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6ce0decb-3c09-4fdb-91d6-c1824d34145a">

- And make sure to **grant admin consent** within the Graph app- API permissions.

**Comment by cholman1** [comment]
The other sending options will not let me choose and group etc., it is not searchable.
I have verified the Tenant ID and it is correct.

**Comment by gsv022** [comment]
Hi @cholman1,
Please share the mail id(outlook id) so that we can discuss the issue internally
