### ISSUE TITLE
Users in different environment

### ISSUE THREAD

**Issue by cathprado10** [OfficeDev/microsoft-teams-apps-company-communicator#1150]
Hello,
I've create the app in Tenant account  (@tentant.com...for example) on Azure...and we'll send messages from tenant to o365 account (where everybody from the company is)....for example: @users.com

The author app...I've already add on tenant account (Teams group)...not i'm having trouble to add the user app on general teams because  it's not on the same environment (@tenant.com X @user.com)

Somebody could help me? :)

**Comment by gsv022** [comment]
Hi @cathprado10 ,
Thanks for raising the query. Could you please elaborate more on the issue.
