### ISSUE TITLE
New message - unexpected error

### ISSUE THREAD

**Issue by BintMi** [OfficeDev/microsoft-teams-apps-company-communicator#1153]
Hi, we have upgraded company communicator from v5.4 to v5.5 and now we get an error when creating a new message.
_Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists._
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/52733444/c24c3187-90d0-4676-bdda-eb2fa86e4dcc)

In DevTools I can see a request with status code 500
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/52733444/3ac86aa6-f7cc-44a2-99f1-69301ca9f6b4)

Application Insights:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/52733444/d51209ae-bd38-40c4-b088-003f3174cda4)

Thanks for your support!

**Comment by gsv022** [comment]
Hi @yinaa ,
Thanks for trying out the newer version.  Could you please respond to the below queries.

- Was v5.4.1 working fine previously? if so please share the screenshot showing the messages delivered.
- Hope you have updated the app service configuration with the below parameters before sync. Here is the migration [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-)
<img width="370" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/517ce742-efd2-4410-becd-2f23d9b5af39">

- Then SYNC need to be performed.

**Comment by BintMi** [comment]
The value for **AzureAd:ClientSecret** in the app service configuration in the app setting was wrong. After I corrected this, it now works again. Thanks for your support!
