### ISSUE TITLE
v5.5 scheduled messages aren't working

### ISSUE THREAD

**Issue by alexl-2397** [OfficeDev/microsoft-teams-apps-company-communicator#1155]
Hiya,
I'm having some issues with the scheduled messages in v5.5.
I setup a message to test this feature after upgrading, and they dont appear to be sending.
<img width="928" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/105488615/2aca2bf9-9a05-4648-a529-f561dd5093ca">
There's no issues sending the messages normally (without scheduling) so I'm unsure what it could be myself.

**Comment by gsv022** [comment]
Hi @alexl-2397 ,
Thanks for trying out the latest version. Please respond to the below queries

- Is it a fresh deployment?
- Other than schedule message functionality, all are working fine?
- Please share the application insight logs with screenshots. Here is the reference to reach to the logs section. 
<img width="503" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8dce9cea-e1e7-49c3-84dd-f036eefaab53">

**Comment by alexl-2397** [comment]
Hi Sai,
It's not a fresh deployment, I synced the deployment on the 21st of September.
<img width="1016" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/105488615/e4080715-5a30-4fea-ad2b-d41a33b36be0">
All functionalities work, just not the scheduled ones.
Here's a screenshot of the application log for the timestamp of the above scheduled message
<img width="1066" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/105488615/ecbe3fca-464e-42b1-ae68-3b29220ed0dd">

**Comment by gsv022** [comment]
Hi @alexl-2397 .
Please share your mail id(outlook id/teams id) so that we can discuss the issue internally.

**Comment by gsv022** [comment]
Following up internally

**Comment by gsv022** [comment]
Hi @alexl-2397 ,
Please let us know if you have any queries otherwise we can make it to closure.
