### ISSUE TITLE
{"error":{"code":"ConversationNotFound"

### ISSUE THREAD

**Issue by mustafafarooq** [OfficeDev/microsoft-teams-apps-company-communicator#1156]
In one of my deployments I am getting this issue for a particular user. The user reported that they accidentally deleted the communicator chat and since then they are not receiving any new messages from the app and they cannot see the previous messages either. Tested this also by placing this user and a second user in a M365 user group and set it as the Target Audience in the Communicator app. The first user does not receive any message at all while the second user is receiving it just fine. They also seem to be not receiving any messages in the pinned communicator app that are sent orgwide. 

![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/1696026/b76f0ef6-ca85-401f-a2df-448986357879)

I have checked the app registrations for the graph app and the supported account types was changed to Single Tenant, but after switching it back to Multi-tenant the issue still remains. The User and Author app registrations are set to Multi-Tenant as well. I have checked the Api permissions and they have been granted.

![image](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/1696026/a3fe5b8a-2e17-421c-aba8-6a7d9d87d91a)

The Recipients status only shows the status of the message received successfully by the second user there is no entry in the detailed reports either if the message receiving was a success or failure.

![WhatsApp Image 2023-09-25 at 15 02 46](https://github.com/cristianoag/microsoft-teams-apps-company-communicator/assets/1696026/917af064-8fb0-4ee9-91a0-6380b77d9244)

**Comment by gsv022** [comment]
Hi @mustafafarooq ,
Thanks for raising the query. Please respond to the below queries.

- Any specific reason for changing the supported account type from my org to multiple org for graph app?
- Coming to Graph API permissions , it seems to be having more permissions than required. Please keep the permissions that are as per deployment guide.

**Comment by mustafafarooq** [comment]
because the app was deployed from the custom CC repo, both of these were mentioned in the guide, are these configurations causing this issue ?

**Comment by gsv022** [comment]
Hi @mustafafarooq ,
Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version.

**Comment by mustafafarooq** [comment]
can you guide me if this same issue occurs with the standard version where a user has deleted the chat by accident and is not receiving the messages , if this error 'ConversationNotFound' would be present in the standard versions code as well

**Comment by gsv022** [comment]
Hi @mustafafarooq ,
Please give us sometime and will get back to you

**Comment by gsv022** [comment]
Hi @mustafafarooq ,
Please share your mail id(outlook id/teams id) so that we can discuss the issue internally

**Comment by mustafafarooq** [comment]
mustafa.farooq@aboutxtreme.com

**Comment by gsv022** [comment]
We will continue the conversation internally

**Comment by gsv022** [comment]
User confirmed that the issue can be closed.
