### ISSUE TITLE
Not able to send messages to everyone

### ISSUE THREAD

**Issue by cathprado10** [OfficeDev/microsoft-teams-apps-company-communicator#1157]
Hello, 
the communicator works fine to send messages to groups...
but when I try to send to all company I recieve this message
<img width="542" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145389768/ebe4a2af-3c9d-43f5-a989-8415b3e63fe2">

the first 2 options work fine...but the  third one (the one we want to use...) is not the working...we need this to send message to +45000 employees :)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145389768/95c62e6d-e9fa-42b1-bcd5-61ab92087c8d)

Someone could help me?

**Comment by gsv022** [comment]
Hi @cathprado10 ,
Thanks fir raising the query. Could you please respond to the below queries.

- What is the version of the app?
- Please share the application insights logs. Go to resource group-->Application Insights-->Under investigate click Failures. Share the logs. Here is the reference
<img width="502" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/74e9d912-c065-47da-81f0-af1471762cab">

**Comment by cathprado10** [comment]
Hello, 
<img width="532" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145389768/10795cd2-c818-466b-860b-94d0928ddae3">

Logs: 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145389768/f71f8c10-2711-47e7-999c-06fcc2ab891c)

**Comment by gsv022** [comment]
Hi @cathprado10 ,
Please try sending a message using 3rd sending option after performing the below procedure.
```
- Navigate to Azure portal and open company communicator deployed resource group.

- Click on “Storage account”.

- Expand “Tables” section.

- Open “AppConfig” table.

- Delete the second record where Rowkey is entered as “UserAppId”.
```
<img width="617" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/e9ca4677-cb8b-4bc2-9c25-96cf4a40e1ff">

**Comment by cathprado10** [comment]
Hello...
There's no "UserAppID" row...
here's the screenshot:
<img width="960" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145389768/b21ab5b2-e481-4edb-9b82-d99a30ec8101">

**Comment by gsv022** [comment]
Hi @cathprado10 ,
Could you please delete the author app, user app from teams and re-upload them again via teams admin center. Then try sending the message using 3rd sending option

**Comment by cathprado10** [comment]
Didn't work...same error
and now i'm not able to send messages to individual in a group (the second option)

is it possible to schedule a call for someone to help me with this deployment?

**Comment by gsv022** [comment]
Hi @cathprado10 ,
Please share your mail id(outlook id or teams id) so that we can continue the conversation internally.

**Comment by cathprado10** [comment]
catherine.prado@arcadis.com

**Comment by gsv022** [comment]
Hi @cathprado10 ,
We can continue the conversation internally from now on

**Comment by victorsimonlee** [comment]
why keeping the resolution private????????????
