### ISSUE TITLE
App Says Something Went Wrong When Trying To Open

### ISSUE THREAD

**Issue by andrewh-tecex** [OfficeDev/microsoft-teams-apps-company-communicator#1159]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/84127074/4114073d-dded-442a-9736-cb8c3e40db94)

Hi after i deployed to teams it says something went wrong.

**Comment by gsv022** [comment]
Hi @andrewh-tecex ,
Thanks for raising the query. Could you please respond to the below queries.

- Is it happening with both the author and user manifest files?
- Were they added on teams admin center or directly on teams? If they were added via admin center, please give sometime to reflect in the teams platform.

**Comment by andrewh-tecex** [comment]
Hi I found my fault thanks
