### ISSUE TITLE
Issue while adding Company Communicator Author to my Teams group

### ISSUE THREAD

**Issue by cholman1** [OfficeDev/microsoft-teams-apps-company-communicator#1160]
Issue while adding Company Communicator Author to my Teams group

"Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists."

![ErroCompanyCommScreenshot 2023-09-28 091844](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145700698/4906241f-2b64-4d5b-be19-625d24832100)

**Comment by gsv022** [comment]
Hi @cholman1 ,
Thanks for raising the query. There might be multiple reasons for this issue.
- Could you please verify the configuration end-end again.  
- Please share the screenshot of  function app . Below is the reference. Do the same for remaining 2 function apps(Prep-Function, Data Function) and App Service. To reach here, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select Function app from list of resources-->Go to Deployment Center-->Click on logs
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98143492/208047784-2a9aa840-735d-48a4-afc3-c016db6f6811.png">

- Please do the above step  for app service as well.

**Comment by cholman1** [comment]
I have check all logs for the Function Apps and App Service and all Status is Success (Active).

**Comment by gsv022** [comment]
Hi @cholman1 ,

- What is the version of the app?

- Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication). Please share the screenshots as shown in deployment guide it would be helpful for better troubleshooting.
