### ISSUE TITLE
Error Sync 5.3-5.5

### ISSUE THREAD

**Issue by Michel22222** [OfficeDev/microsoft-teams-apps-company-communicator#1161]
**Hi, when syncing the app service to the newest version I get this error:**

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 01925D3F v8::internal::Heap::AllocateExternalBackingStore+1551
Failed exitCode=134, command=npm run build
An error has occurred during web site deployment

**For the functions there is no problem syncing. Should I try to add memory? If yes, how to do that?
Regards and Thanks!**

**Here is the log:**

Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.411

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)

npm notice 
changed 43 packages in 9m
npm notice New major version of npm available! 8.19.2 -> 10.1.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>

247 packages are looking for funding
npm notice Run `npm install -g npm@10.1.0` to update!
npm notice 
  run `npm fund` for details
Building the client app (this can take several minutes)

> company-communicator@5.4.1 build
> react-scripts build

Creating an optimized production build...

<--- Last few GCs --->

[5288:0497C340]   452430 ms: Mark-sweep 496.9 (522.5) -> 493.6 (523.5) MB, 6145.5 / 0.3 ms  (average mu = 0.193, current mu = 0.034) allocation failure scavenge might not succeed
[5288:0497C340]   458867 ms: Mark-sweep 498.1 (523.8) -> 495.0 (525.0) MB, 6301.9 / 0.1 ms  (average mu = 0.122, current mu = 0.021) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 01925D3F v8::internal::Heap::AllocateExternalBackingStore+1551
Failed exitCode=134, command=npm run build
An error has occurred during web site deployment.`

**Comment by gsv022** [comment]
Hi @Michel22222 ,
Thanks for raising the query. What is the app service plan been used for CC? Please mention

**Comment by Michel22222** [comment]
Hi, the plan is Basic (B1).

**Comment by gsv022** [comment]
Hi @Michel22222 ,
Please upgrade to S1 or S2. We recommend you to upgrade to S2 for better performance.

Keep us posted.

**Comment by Michel22222** [comment]
Thats 2.5 times the price for S2. S1 has same cores and Ram like B1. What is the big difference between 5.3 and 5.5 which needs more ressources? We use the app only to send a few messages a month.

**Comment by Michel22222** [comment]
OK. I changed to B2, made the sync which was successfull, and changed back to B1. Thanks for the help.

**Comment by gsv022** [comment]
Hi @Michel22222 ,
Thanks for the update. We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
