### ISSUE TITLE
Notifications not being sent to users even though they are in the correct groups

### ISSUE THREAD

**Issue by EMEAWebEnvironmentsTeam** [OfficeDev/microsoft-teams-apps-company-communicator#1162]
Hello,

We are currently using v5.3 of the company communicator, and have seen a few users having issues with receiving messages.
They don't have the bot blocked, muted or hidden, they have just never received the messages. Permissions in the teams admin center look ok and they have the user app installed.

When a message is sent they are not on the list of recipients at all even though it is going to their group (note below how the message sent to 3 users only, when there are 4 in the group)

<img width="312" alt="cc1" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124071148/1febde4f-e64c-4d2a-a127-9b8136f3442e">

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124071148/c29180d2-2074-4f2f-b322-59c26c9e3314)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124071148/7adec138-55a8-4a41-9f3c-5d7833bea65e)

Is there anything else we can try to resolve this for the affected users?

**Comment by gsv022** [comment]
Hi @EMEAWebEnvironmentsTeam ,
Thanks for raising the query. Could you please try sending the message using 4th sending option-DL

Keep us posted

**Comment by EMEAWebEnvironmentsTeam** [comment]
Hi @gsv022 
Thanks for your response. These messages are being sent via the 4th option (DL), as below:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124071148/77d1535d-534f-4360-b9e1-518a29d9376c)

**Comment by gsv022** [comment]
@EMEAWebEnvironmentsTeam , Could you please try other sending options now including 3rd option.

**Comment by EMEAWebEnvironmentsTeam** [comment]
Hi @gsv022,

Thanks for your response.
Option 1: They are able to see the notifications when they are sent to the general channel of one of their teams
Option 2: They still don't receive the notifications this way (completely missing from the recipients when the results are exported, same as Option 4)
Option 3: We wouldn't be able to test this unfortunately as we are quite a large company and only send notifications to sub-groups. But I suspect the result would be the same as option 2 and 4

**Comment by gsv022** [comment]
Hi @EMEAWebEnvironmentsTeam ,
Please share your email id(outlook id or teams id) so that we can continue discuss the issue internally.

**Comment by EMEAWebEnvironmentsTeam** [comment]
Hi @gsv022,

I can be reached at rayner.obrien1@computershare.co.uk
I look forward to hearing from you.

**Comment by gsv022** [comment]
Hi @EMEAWebEnvironmentsTeam ,
I have sent a procedure to the given mail. Please perform and keep us posted.
