### ISSUE TITLE
Unable to add Company Communicator Author app in Teams  

### ISSUE THREAD

**Issue by ayushsaxena21** [OfficeDev/microsoft-teams-apps-company-communicator#1163]
Error on Webpage: The webpage at https://msteams-apps-companycommunicator.mdlz.com/configtab might be temporarily down or it may have moved permanently to a new web address.

**Comment by gsv022** [comment]
Hi @ayushsaxena21 ,
Thanks for raising the query. When I am accessing the link, I got the message as expected. Please check once again and confirm.
<img width="950" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/210148a7-19b4-43f7-9e94-5012579480a3">

**Comment by ayushsaxena21** [comment]
Hello Sai,

I was getting same response when hitting below URL however, author app was not accessible. This issue still persists.

Thanks & Regards,
Ayush Saxena

**Comment by gsv022** [comment]
Hi @ayushsaxena21 
Please complete the deployment guide [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) to get access to the CC application. Check out the last step i.e., zipping the manifest files and uploading to teams.

**Comment by ayushsaxena21** [comment]
Hello Sai,

We don’t see this plan feasible due to reinstallation process. Can you suggest us a time to schedule a call so we can discuss it further.

Thanks & Regards,
Ayush Saxena

**Comment by gsv022** [comment]
Hi @ayushsaxena21 ,
The deployment is almost completed from your side. Did you complete the last 2 steps of deployment guide? Please confirm.

**Comment by ayushsaxena21** [comment]
Hello Sai,

We did not reupload the manifest file as there could be other issues due to high user database. There is another issue with app where URL button is missing out.

Can you mention possible outcome of reinstalling the app.

Thanks & Regards,
Ayush Saxena

**Comment by gsv022** [comment]
Hi @ayushsaxena21 ,

- What is the version of the app?
- The below URL seems to be a custom domain URL. 
 https://msteams-apps-companycommunicator.mdlz.com/configtab 

- Hope you have followed the  [custom-domain](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option) recommendations

**Comment by ayushsaxena21** [comment]
Hello Sai,

App version is 5.4.1 however, let me check on custom domain recommendation.

Thanks & Regards,
Ayush Saxena

**Comment by ayushsaxena21** [comment]
Hello @***@***.***>,

Yes, we are following custom domain recommendations.

Best Regards,
_____________
Chetan Kattarmal,
UC Ops Lead MEU (Mondelez Digital Services)
Teams Central & M365 Learning <https://teams.mdlz.com/sites/msteams>
Please follow our CFOCUS<https://intranet.mdlz.com/sites/Finance/Pages/CFOCUS-Program.aspx> guidelines.
[Teams-24x24]Chase me in ***@***.***> | Schedule a Quick Connect with ***@***.***> | Call me in ***@***.***> | +44 121 393 5400

From: Saxena, Ayush (Contractor) ***@***.***>
Sent: 10 October 2023 10:52
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>; Kattarmal, Chetan D ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to add Company Communicator Author app in Teams (Issue #1163)

Hello Sai,

App version is 5.4.1 however, let me check on custom domain recommendation.

Thanks & Regards,
Ayush Saxena

**Comment by gsv022** [comment]
Hi @ayushsaxena21 ,
 We haven't implemented CC using custom domain format. Our support scope is very limited with respect of standard version of CC and won't be able to assist on this.
