### ISSUE TITLE
Company Communicator error - Error message: Permits are needed. Ask your Information Systems Administrator to enable this option

### ISSUE THREAD

**Issue by elise-charles** [OfficeDev/microsoft-teams-apps-company-communicator#1165]
-I am created this case on behalf of a customer.
-They are following this article to deploy Company Communicator: 
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

-when they're trying to set it up, they're getting the following error below:
Permits are needed. Ask your Information Systems Administrator to enable this option

-They have already tried looking into the other forums below but they're still getting this issue:
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/556
https://learn.microsoft.com/en-us/answers/questions/909365/permissions-needed-ask-your-it-admin-to-add-app-to

Any assistance would be appreciated, thank you!

**Comment by gsv022** [comment]
Hi @elise-charles ,
Thanks for raising the query. There are multiple reasons for this issue.
- There is a chance of incorrect configuration, have a thorough check from start-end and mainly verify the all three app client secret is correctly copied while creating ARM template or not. Attaching the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911) where you can compare and check on secrets.
- Please cross verify the set-up authentication part again. 
<img width="673" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5d97b1ef-a490-46df-93bf-f403aab579df">

- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
    Author-multiple
    User-multiple
    Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">
