### ISSUE TITLE
Company Communcator metrics

### ISSUE THREAD

**Issue by dlenclume** [OfficeDev/microsoft-teams-apps-company-communicator#1166]
Hello

I was wondering the Company Communicator app provided information on who reads the messages sent via the app.  I thought I'd seen that this was possible in an earlier version but I can't seem to see it now.

Thanks

David

**Comment by gsv022** [comment]
Hi @dlenclume ,
Thanks for raising the query. As of now we don't have the feature- number of reads. It is yet to be implemented. This has been already added to the backlog and planned in the future releases of Company Communicator. 

- What is the version that is installed currently?
- In which version of CC this read feature has been observed? Please send a supporting screenshot if you have any reference.

**Comment by dlenclume** [comment]
Thanks for getting back to me.  You can close this issue.
