### ISSUE TITLE
News Bot / prevent block and delete chat

### ISSUE THREAD

**Issue by freserovski** [OfficeDev/microsoft-teams-apps-company-communicator#1167]
To make sure all users always receive messages - as official company communication path - is it possible to configure bot in that way that users can't block it and/or delete chat?
If that would be possible that 404 and 403 errors would be also gone...

**Comment by v-saikirang** [comment]
Hi @freserovski ,

Thanks for reaching out to us.

Please allow us some time. We will check and get back to you on this.
Thanks.

**Comment by gsv022** [comment]
Hi @freserovski ,
Thanks for raising the query. From our application, we don't have control on those options. Even Microsoft Teams doesn't provide an option to disable or remove the "Delete" or "Disable" options in the chat section for individual users. If it is still an requirement, we recommend you to reach out to support team of  MS Teams. 

Please let us know if you have any queries with respect to standard version of CC.
