### ISSUE TITLE
Sorry an error occurred while trying to access this service

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1168]
Hi
Can someone please help me with this issue below as soon as possible?
_For quicker response you can also contact me via Microsoft Teams and do a video sharing session at [david.liong@rac.com.au](mailto:david.liong@rac.com.au)_ 
I am available for a video call during office hours from 9am to 5pm (UTC+8) Perth local time zone if someone is also in my similar time zone to assist which will be greatly appreciated.

**Problem**
I get this message below when opening the communicator Author app from a tab in a general channel of Teams 
_Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists_
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/0b3db84c-cde5-4f66-9f73-a6b660137db3)

**Further Background Info**

- The communicator app was an upgrade from version 3 to version 5.4.1
I have followed the instructions in Wiki to 
- Successfully upgraded from version 3 to version 4 by following  https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide
- Successfully upgrade from version 4 to version 5 by following https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5
- The deployment center log on the web app and 3 x function app services had a successful sync on September 6th from  from PR#1113 [source code in GitHub](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/pull/1113)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/194d2359-024e-43ca-b173-12f7e7b8311c)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/83ed96d0-90c7-48b2-b1ba-711e7b716784)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/97cffb7c-589c-4e6a-b4a9-9e41887c7aca)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/fb5a4175-6e4a-491d-bbd2-385918edbff8)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/cbcff82a-59a3-4b15-8fef-2a9986ec1651)

- The app registration for v5 was setup for single tenant according to Wiki instruction

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/27f96b4e-9e89-46da-bf10-56e34b58d350)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/397fdf0f-fc0a-44a1-8a5b-cfcca559275a)

- The graph client app registration (client id 49941655-a4c8-4636-8a4d-811a1a39b7bb) was setup for single tenant (not in Wiki instruction)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/5b834016-8df4-4d21-8599-9ae53b4977f2)

- The client secret had expired for company v5 app registration, which I had renewed.

- After renewing the new client secret, the client ID (d0f83203-415f-4055-8a21-512adbce0959) and its client secret password (hard coded) of app registration v5 was copied correctly in the configuration setting across the web app and the 3 function apps
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/ff587794-8eb1-4a0d-8950-aca7e20d7824)

- Can you please tell me what other steps you want me to check that might be overlooked?

- Do I need to click the sync button from the deployment center for web app and the 3 function apps every time, the configuration setting has been updated with changes. e.g. renewing client secret

- What is the root cause?

Thanks.
David

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thanks for raising the query and sharing a quite an information. Please respond to the below queries.

- Please confirm which one is  graph app registration.
<img width="521" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0dfd3b1c-38aa-4ca8-b763-906f341fbd3e">

- It is said that secrets expired and updated them accordingly. Could you please confirm whether **secret value** is copied or **secret ID**  within the app registrations.

**Comment by David-Liong** [comment]
hi @gsv022 

The graph app registration is this (client ID: 49941655-a4c8-4636-8a4d-811a1a39b7bb)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/a8bb2a43-9247-4d8b-837c-dfe05e6c4b9f)

- The client secret that was going to expired in Nov is the company app registration in red box (client ID d0f83203-415f-4055-8a21-512adbce0959)

- The new secret that was created to be expired in 2 years is in yellow box

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/5e63893f-91e2-4c8c-a628-19dfce537d08)


I copied the new client secret password & client id d0f83203-415f-4055-8a21-512adbce0959 for company app registration in yellow box across to the configurations of web app and the 3 function apps on the setting:

- AuthorAppId
- AuthorAppPassword
- UserAppId
- UserAppPassword

**Comment by David-Liong** [comment]
So I also took the liberty of updating the web app configuration setting to change the banner title and logo for the author app below.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/c8178a2b-282e-44d8-a90f-7857d26b31aa)

 According to https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Frequently-Asked-Questions-(FAQ)#12-how-to-update-the-banner-title-and-the-logo 

I follow its instruction (step 4) to sync the web app repo
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/ba16d36f-71d4-4d38-879c-b8ebd0edd80f)

The sync is attempting to **upgrade source code from version 5.4.1 to 5.5** (PR #1147 )
 
However there is a sync error "_FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory_"
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/2c900685-5605-4708-97f2-36f90affb8ed)


Can you instead look at **fixing the sync error message** instead of the original error in title?
Why is sync failing?

**Comment by David-Liong** [comment]
hi @gsv022 

Below is the extracted log file from the sync error of:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/23fe4bf2-7e6b-4135-a632-9317797c7bb3)

### Error Log
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)

up to date in 5m

247 packages are looking for funding
  run `npm fund` for details
Building the client app (this can take several minutes)

> company-communicator@5.4.1 build
> react-scripts build

Creating an optimized production build...

<--- Last few GCs --->

[4912:045A7578]   643035 ms: Scavenge (reduce) 499.8 (523.0) -> 499.7 (523.5) MB, 332.5 / 0.0 ms  (average mu = 0.497, current mu = 0.432) allocation failure 
[4912:045A7578]   653743 ms: Mark-sweep (reduce) 500.5 (523.8) -> 499.3 (523.5) MB, 10643.9 / 0.1 ms  (average mu = 0.325, current mu = 0.170) allocation failure scavenge might not succeed
[4912:045A7578]   653788 ms: Scavenge (reduce) 499.7 (523.5) -> 499.7 (524.0) MB, 8.2 / 0.0 ms  (average mu = 0.325, current mu = 0.170) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 01265D3F v8::internal::Heap::AllocateExternalBackingStore+1551
Failed exitCode=134, command=npm run build
An error has occurred during web site deployment.
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock.json file was created with an old version of npm,\r\nnpm WARN old lockfile so supplemental metadata must be fetched from the registry.\r\nnpm WARN old lockfile \r\nnpm WARN old lockfile This is a one-time fix-up, please be patient...\r\nnpm WARN old lockfile \r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\n\r\n<--- Last few GCs --->\r\n\r\n[4912:045A7578]   643035 ms: Scavenge (reduce) 499.8 (523.0) -> 499.7 (523.5) MB, 332.5 / 0.0 ms  (average mu = 0.497, current mu = 0.432) allocation failure \r\n[4912:045A7578]   653743 ms: Mark-sweep (reduce) 500.5 (523.8) -> 499.3 (523.5) MB, 10643.9 / 0.1 ms  (average mu = 0.325, current mu = 0.170) allocation failure scavenge might not succeed\r\n[4912:045A7578]   653788 ms: Scavenge (reduce) 499.7 (523.5) -> 499.7 (524.0) MB, 8.2 / 0.0 ms  (average mu = 0.325, current mu = 0.170) allocation failure \r\n\r\n\r\n<--- JS stacktrace --->\r\n\r\nFATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory\r\n 1: 01265D3F v8::internal::Heap::AllocateExternalBackingStore+1551\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.50803.6381\bin\Scripts\starter.cmd deploy.cmd

**Comment by gsv022** [comment]
@David-Liong ,What is the app service plan used for deployment?

**Comment by David-Liong** [comment]
@gsv022 

The app service plan is currently on S1.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/0d513d3e-f1b9-4894-8738-001200369c4d)

Are you suggesting that I should upgrade the service plan to S2 to increase resources will prevent error message "...Reached heap limit Allocation failed - JavaScript heap out of memory" from appearing when I do a sync repo code of the web app service after changing plan to S2?

**Comment by gsv022** [comment]
Hi @David-Liong ,
Please try upgrading to S2 and try for SYNC again.

**Comment by David-Liong** [comment]
Hi @gsv022 

I have upgrade to S2 run the sync again for web app. Successfully deployed and upgrade to v5.5
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/b5b4c695-5c31-4366-a08f-e5d59b4f457b)
I have ran the sync on the 3 functions app and it too got uprade to v5.5 successfully.

When I open the author app in Teams, I now get the same error message as originally posted during loading of the screen page. 

https://user-images.githubusercontent.com/71060262/274206707-0b3db84c-cde5-4f66-9f73-a6b660137db3.png

Where do I go from here to fix this error?
"Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists" 

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,
This seems to be configuration issue and needs a proper check from start to end. Could you please cross-verify the configuration as a whole again. 

Please let us know if anything observed otherwise we will reach out to you via Teams.

**Comment by David-Liong** [comment]
Hi @gsv022 

I have put on hold the upgrade process from v4 to v5. 

Instead, I focus my effort on doing a completely successfully brand-new fresh installation of communicator v5.5 by following all the instructions at https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/f1a5bf36-9666-4b0d-b971-6a5363130b7d)

What I notice is with this instruction to deploy latest communicator version from scratch was that it clearly stated the need to create 3 separate app registrations. (this wasn't mention in upgrade from v4 to v5).


Anyway I am about to post my first posted news. Why isn't the list of Teams channel available from the drop down
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/7e5b9a13-4cb6-4c5b-9251-8d54d9add671)

I can manually type a Team channel but won't allow me to enter space and the saft draft button is still grey out and I can't save it.

What additional steps am I missing in the installation of v5.5?

Below are additional settings of the services to help you investigate further.

- Web app and the 3 function apps was successfully sync to v5.5 (PR #1147 )
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/1bcb9a6c-e8a2-4dd4-a152-b6e0f8cbe2fc)

- 3 company app registrations were created 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/758fffcd-4c2b-457f-bb6f-fbb2934b7608)

1. Application (client) ID for the **user** bot - 4201a3d7-7cd9-4ac2-b178-b219dee1e627 (Company Communicator Users)
2. Application (client) Id for the **author** bot - d497116e-9d46-472d-afc3-ca1e885a6368 (Company Communicator Author)
3. Application (client) Id for the Microsoft Graph App - 0d5eb059-a1d9-4720-905b-b8918630c036 (Company Communicator App)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/2ef8314c-abeb-4493-b7a0-1ecce2856c24)

API permission for the Company Communicator Users & Authors were BOTH only have **User.Read** deletegated
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/a1952877-e3f8-4e67-b688-87d6be791c2b)

**Comment by gsv022** [comment]
Hi @David-Liong ,
It is good that you went for fresh deployment. Coming to the issue-Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue. 

Keep us posted

**Comment by David-Liong** [comment]
Hi @gsv022 
Great I have install communicator user app to the team general channel that will be receiving the posted news sent from the communicator author app.

I have sent the posted news to the general channel
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/bc3d1070-5bb2-4f3c-b7f8-ea1d01117cff)

However, the posted news is still in queue where I am still waiting now for over 10 minutes.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/149a17f4-64d0-43ee-9b63-8fcc30906af3) and haven't sent to the recipient and haven't sent the news to the general channel either.

Why is sending a message so slow? How long do I have to wait? How can I configure the performance of sending message quicker?

Thanks.

**Comment by David-Liong** [comment]
Hi @gsv022 

In summary I only have 1 issue after the installation of CC v5.5

**Issue 1 - Delay with sending message**
I have now 3 messages in queue and still not posting after 3 hours later of waiting.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/14765552-973d-4222-adf3-baff33f69dc5)

- Test Travel News 1 (copy) is waiting to be sent to everyone in the organisation. Currently we have over 100 users in the tenant
- Test news 2 is waiting to be sent to people who are member (5 users) of a specific team
- Test Travel News 1 is waiting to be sent to the general channel of a particular team (There are 5 users who are members of the general channel)

**Comment by gsv022** [comment]
Hi again,
There are majorly two possibilities for this issue
- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
    Author-multiple
    User-multiple
    Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

-----------------------------------------------------------------------------------------------

- Please cross-verify secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by David-Liong** [comment]
Hi @gsv022 

Below are my response to your questions:

1. Check whether the Supported type parameter for app registration is as per the deployment guide. Here is the reference.

- Company Author app rego -multiple org
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/7a24cbed-b34a-4b6f-9568-5678d90c231f)

- Company User app rego -multiple org
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/56c59d66-6d93-4744-b0fc-bec3492e48e9)

- Graph app rego - my organization
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/685df19c-3cc6-40da-8fd1-3bb89655586a)


2. Check to cross-verify each client secrets in CC vault matches with client secrets of each CC app registration - Yes
I have managed to give and Admin AAD group (where I am a member of that Admin AAD group) all access to CC vault 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/c2ad3803-8641-40b3-8d5a-b3f5723991e7)

and I can see all the secrets stores in CC vault. I have compared the latest/current version for each author, graph and user app secret value in CC vault with the secret values in each respective CC app registration. The secret values match across CC vault and CC app registration.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/dbc3534e-d170-4d1f-a95b-9c8be1c3abb1)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/2421e2f8-6c0e-41f0-b3bb-f692cdb9c2a9)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/67772ecb-291f-4090-9757-f1c594f5b18a)

I have verified that each secrets store in the configuration of web app and the 3 function apps matches with current secret version as in the CC vault.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/7ef220ee-054f-4f8f-8a6c-af3940aadb22)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/fec28bf7-988a-434d-a9c1-3288da46f2de)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/2e02a022-d1b4-40c5-8cf2-f0114968bec9)


Did you want me to look at the log files and which log do I look at?

**Comment by David-Liong** [comment]
Hi @gsv022 
In summary user, author and graph secret values all match that are stored across in CC vault, the 3 CC app registrations in the configurations of the web app and the 3 function apps.

I did however saw the error log message in the function send and prep in the last 24 hours. No errors found in the data function app
Error code: BadRequest
Message: Encountered an error (ServiceUnavailable) from host runtime.

Below is sample screenshot
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/8b4f30f6-940e-4b2c-838c-de24fdefa267)
JSON sample
"resourceId": "/subscriptions/0a665cc4-710c-470e-93d5-ee839efb27be/resourceGroups/racwa-dcc-arg-npe-128/providers/Microsoft.Web/sites/racwa-dcc-npe-npeteamscommv5-fn-send/host/default",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "BadRequest",
        "localizedValue": "Bad Request (HTTP Status Code: 400)"
    },
    "submissionTimestamp": "2023-10-18T23:03:20Z",
    "subscriptionId": "0a665cc4-710c-470e-93d5-ee839efb27be",
    "tenantId": "2f83fb84-24df-45d5-9137-da51abb46251",
    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": null,
        "statusMessage": "{\"Code\":\"BadRequest\",\"Message\":\"Encountered an error (ServiceUnavailable) from host runtime.\",\"Target\":null,\"Details\":[{\"Message\":\"Encountered an error (ServiceUnavailable) from host runtime.\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"Code\":\"BadRequest\",\"Message\":\"Encountered an error (ServiceUnavailable) from host runtime.\"}}],\"Innererror\":null}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/0a665cc4-710c-470e-93d5-ee839efb27be/resourceGroups/racwa-dcc-arg-npe-128/providers/Microsoft.Web/sites/racwa-dcc-npe-npeteamscommv5-fn-send/host/default",
        "message": "Microsoft.Web/sites/host/sync/action",
        "hierarchy": "2f83fb84-24df-45d5-9137-da51abb46251/67a6c994-5f66-4e0d-924a-6832060243de/a3f1fbab-5635-4644-9eb8-9843888c7b28/03a56604-fac2-4c7a-b8db-069762926dc9/0a665cc4-710c-470e-93d5-ee839efb27be"
    },
    "relatedEvents": []
}
BTW all 3 function app have the same general settings using:

**- .NET Version:** .NE 6(LTS)
**- Runtime version:** ~4
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/b877bb09-95f8-4aca-ad25-de8de9ae418d)

- And all 3 function apps had a successful sync to v5.5
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/a04e10ed-b42e-4074-8f27-43d2216f0a63)


Could the errors detected in the 2-function apps (send and prepare) cause the message to be queue?

### 
There was also an error at the last deployment on the resource group deployment center. The 2 distinct errors were:

- web app - "There was a conflict. Conflict with existing ScmType: ExternalGit"  :This error is fixed by running the sync repo code for web app
- "Tenant ID, application ID, principal ID, and scope are not allowed to be updated. (Code: RoleAssignmentUpdateNotPermitted)"  : What does this error mean and if it is causing the message to queue?

### 
What was the solution for other tickets in the past having issues with message been queued?

**Comment by David-Liong** [comment]
Hi @gsv022 

Can we do a quick call via Teams and share screen to fast track the trouble shooting and get a resolution as turnaround response time is slow?

I am in the UTC+8 time zone in Perth Western Australia and hope you are in the same time zone as me.

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,

- That's a good catch, Please use this [link](https://www.guidgenerator.com/online-guid-generator.aspx) to generate the valid GUID's. Go for redeploy with the same app registrations and update the GUID's. 

Keep us posted.

**Comment by David-Liong** [comment]
I have generated 7 new GUID and deployment was successful. I also follow instruction trouble shooting #4 https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#4-multiple-instance-of-company-communicator-in-the-same-tenant-action-items to update “User App External Id” and install the Author and user app in Teams.


There was only have 1 deployment error "There was a conflict. Conflict with existing ScmType: ExternalGit" on the web app.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/28d9b0ca-87d9-4078-8a88-d86ffa884295)

- I think this error relates to sync issue. So ran repo sync again on both web app and the 3 function apps.

- Client secrets in configuration did not get change after sync and the secret value in configurations match with the secret value store in CC vault.
- I posted a new message but still in queue after 30 minutes
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/dcc02f37-53b0-4cf8-9c32-b57a215bc60d)

Here is the overview failures from application insight
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/c52e0866-fb30-4fb1-8711-f126977a9ede)

Where do I start to drill down from application insight to find out why message is still being queue?

I am at the end of the ropes as I have done the full end to end installation process and need to reach out with you or someone who is available to take the time live with screen sharing to have faster turnaround resolution as we **want to go live next 2 weeks** but holding us back due to this issue.

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,
We can continue conversation internally

**Comment by David-Liong** [comment]
great @gsv022 
Can we chat via MS Teams during business hours? When are you available and if we want to setup a calendar invite?
My email for you to send a meeting invite is: david.liong@rac.com.u 

Let me know.

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,
I have already pinged you via teams. Please confirm and reply there
<img width="690" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/90c908c0-15a8-4982-a7e3-0618f73ecc50">

**Comment by David-Liong** [comment]
Thanks I have replied to your message in Teams. Lets chat in Teams to keep updated in faster response time.

**Comment by gsv022** [comment]
@David-Liong 
- As a part of troubleshooting we noticed that there is a issue coming for each function app- "Collison for Host ID 'baseresourcename-added suffix' was detected in the storage account"

- This condition usually occurs due to truncation of similar function app names when the host ID value is generated. Here is the link for [reference.](https://learn.microsoft.com/en-us/azure/azure-functions/errors-diagnostics/diagnostic-events/azfd0004#options-for-addressing-collisions)
- We recommended to go for a fresh deployment and said to keep the name unique and not too lengthy.

**Comment by David-Liong** [comment]
Hi @gsv022 
Just updating this ticket from out chat in Teams. In Summary:

- Message was sent but taking 3-4 days delay due to naming of function app was not a unique name within the first 32 characters. So I redeploy with new function app name as advised.
- Remove all components from resource group 127 & 128

- Uninstall and remove Teams apps for users and author

- Deployment (8th time) was completed with [no error log]

- I have ensure [CC vault] has the latest version of secrets was stored from the author, graph and user app registration

- The configuration setting for AuthorAppPassword, AzureAd:ClientSecret, GraphAppPassword & UserAppPassword was updated to use the latest secret version from CC vault across the web app and 3 function apps. Reset the services.

- Install Teams app for author and users via Teams Admin

- Add author app to communicator app general channel

The new issue is smoke testing has failed when opening author app in teams
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/ea55fdcb-83b3-4c53-b2d1-fd91eae6049a)

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thank you for the patience. 

- The app service authentication issue is now resolved, and the changes have been pushed to Company Communicator GitHub repository. 

- If current version of the Company Communicator application is pointing to v5.5, please follow the below procedure to resolve the issue 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center --> Click on SYNC

- Once the status shows successful within logs section of Deployment Center.
<img width="833" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9eb1d9a7-02f0-4583-8cd5-6f257eaa9ba8">

 
**Note**: Please make sure the Repo URL and Branch name is pointing to below values in Deployment Center Screen of app service 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6e5045cb-27de-4e4f-9d22-7a7ef300888a)


- Please go to the Overview Section from and restart the app service.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6bb3fe8e-dbf2-4763-98f8-730460dd556d)

- Try accessing the CC application on Teams web client to avoid any cache related issue.

- If current deployed version of the Company Communicator application is pointing to v5.4.1 or previous versions, please upgrade your app to latest version by following the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) as the fix is pushed to the main branch in Company Communicator's GitHub repo.

 
Please let us know if you are still facing the issue.
