### ISSUE TITLE
Default company communicator header has a broken feedback link

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1169]
Hi

I notice that in company communicator version 5.4.1 when you click on the feedback link icon on top right corner of the header, it directs users to the site https://communityandadoption.powerappsportals.com/d365community/

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/bea6a3b7-a366-4113-a3a8-693a6976dff9)

However the site https://communityandadoption.powerappsportals.com/d365community/ had a 403 error
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/5ca25300-5c38-4c8f-a250-dbb4d5f6fcb8)

Can the broken feedback link icon be fixed by updating the configuration settings in the web app?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/cc3a881d-f9bf-4cc5-804d-a6a7b8720cc0)
I ask because I know there is a Wiki where you can change the logo and title of the header by updating the configuration.

Or is this a bug that needs to be fixed in the GitHub repo?

Thanks
David

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thank you for your inquiry. The feedback link went into restricted mode. We will resolve this issue and will make it available soon.

**Comment by David-Liong** [comment]
Hi @gsv022 
Do you have a time frame of when this issue will be resolved?

**Comment by gsv022** [comment]
Hi @David-Liong ,
Soon, it is going to be resolved and will keep you posted on this.

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thanks for the patience. The feedback link is working as expected. Please check and confirm

**Comment by David-Liong** [comment]
Hi @gsv022 

I can confirm that site https://communityandadoption.powerappsportals.com/d365community/ is back online.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/df914947-dabd-4700-bce0-4386170cb261)

You can now close this ticket.

**Comment by gsv022** [comment]
Thanks for the confirmation. We are closing the issue
