### ISSUE TITLE
Communicator Author App Not Showing in MS Teams App

### ISSUE THREAD

**Issue by mkrupeydeloitte** [OfficeDev/microsoft-teams-apps-company-communicator#1170]
When loading the app in MS Teams, the page is just blank. The app doesn't show at all. When clicking the drop down on the tab menu and navigating directly to the web application, the site loads fine.

After some additional exploration, if we use a Website app in MS Teams and point to the Communicator Authors website URL and navigate there. It will start the login process and go through MFA and the site loads fine. If I then go back to another channel showing the MS Teams app, the app will now show properly.

Somehow perhaps the MFA/token isn't getting generated properly from the MS Teams app. Any ideas on why it won't show up in MS Teams app? We have set the webresource tag in the manifest to point to the Azure app id and are using api://12345... etc.

**Comment by gsv022** [comment]
Hi @mkrupeydeloitte ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @mkrupeydeloitte ,
Could you please share more details like error observed with supporting screenshots

**Comment by mkrupeydeloitte** [comment]
i was out of the office last week, can this be reopened or should I submit a new issue?

**Comment by mkrupeydeloitte** [comment]
![communicator-picture1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144729232/52bae319-d2c0-4e0e-b801-0c5c01c0ce88)
