### ISSUE TITLE
Pausing Communicator

### ISSUE THREAD

**Issue by LycheeYum** [OfficeDev/microsoft-teams-apps-company-communicator#1171]
Hello, 

I've setup communicator, but my organization is not ready to roll it out yet.  I'd like to deactivate the app, and stop incurring cost as much as possible for now and then reactivate the app again when we're ready.

Is stopping the App service the best approach?

**Comment by gsv022** [comment]
Hi @LycheeYum ,
Thanks for raising the query.  We will look into this and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @LycheeYum ,
Thanks for the patience. 

-App service is the actual web application that will be deployed. When we stop the App Service, it deallocates the resources assigned to it, and you generally won't incur charges for the App Service itself while it's stopped.

- The App Service Plan incurs charges based on its pricing tier, and these charges continue even if the associated App Service is stopped.
- One way is to downgrade the app service plan (eg: if existing app service plan is S2 then it can downgraded to S1). The will reduce the cost associated with app service plan by half. When the app is in usage then it can reverted to actual plan

**Comment by LycheeYum** [comment]
Thank you!

**Comment by gsv022** [comment]
If you are in the latest version of CC, we recommend you to have app service plan-S2. If you are having version-4.x or below it is ok to have S1.

**Comment by LycheeYum** [comment]
Thanks again!
