### ISSUE TITLE
Company Communicator show error when try create new messager

### ISSUE THREAD

**Issue by evandroaraujou7** [OfficeDev/microsoft-teams-apps-company-communicator#1173]
When I try create a new Company communicator messages the error below show up

"company communicator Oops! An unexpected error seems to have occurred"

![Screenshot_2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/67134274/39323a71-03aa-4b46-aa0e-016b47adb6e6)

I reviewed the app graph permissions and seems to be OK

**Comment by gsv022** [comment]
Hi @evandroaraujou7 ,
Thanks for raising the query. There might be many possibilities for this issue.

- What is the version of the app?
- Could you please verify the configuration end to end again whether it is as per deployment guide or not.

**Comment by evandroaraujou7** [comment]
I'm using the latest version, 5.5.

I do that, verify the configuration end to end

**Comment by gsv022** [comment]
Hi @evandroaraujou7 ,
Could you please cross verify the secrets. Here is the procedure to compare the secrets

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by evandroaraujou7** [comment]
Thanks a lot, after verify configuration end to end, I realise that authorBotId was different in manifest file
