### ISSUE TITLE
Company Communicator APP issue

### ISSUE THREAD

**Issue by ManasaMShastri** [OfficeDev/microsoft-teams-apps-company-communicator#1174]
Company Communicator been getting an error while sending messages inside Corp Comm (Authors) application added inside Teams channel.
 
 All the members/owners added in the Team are facing the same issue behavior.
The issue is persistent on Teams Desktop and web app.
While sending the communication to the users we are getting the attached error.
![ErrorCorpComm](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148181089/22c9b9c2-50e6-42a0-8a03-eb52d52a7624)

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
Thanks for raising the query. We don't have this sending option -**send in chat to list of users provided in a CSV file.** . Our support scope is limited to the standard version of CC. Please let us know if you have any queries w.r.t official version of CC. We are more than happy to assist you.

**Comment by ManasaMShastri** [comment]
Hi 

Can we upgrade the company from current version to V5 version we need support for the same.

**Comment by gsv022** [comment]
Hi again,
Since the deployed version is of custom type, we recommend you to go with fresh deployment of CC pointing to official version of Company Communicator.

Please let us know if there are any points holding on to stay with the same custom version only.
