### ISSUE TITLE
After deploy using custom domain option the webapp is not correctly deployed

### ISSUE THREAD

**Issue by diegoriera** [OfficeDev/microsoft-teams-apps-company-communicator#1176]
After deploy using custom domain option the webapp is not correctly deployed.

Tried to re-deploy but it still responding with 404 error for all path

/health
/configtab
/signin-simple-end

**Comment by gsv022** [comment]
Hi @diegoriera ,
Thanks for raising the query. Have you followed the recommendations provided in this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option).

**Comment by diegoriera** [comment]
Yes, I did

**Comment by gsv022** [comment]
Hi @diegoriera ,
Could you please check  and confirm whether the default URL is updated in graph app authentication and in manifest files

**Comment by diegoriera** [comment]
Hi @gsv022 , if you take a look on recommendations provided in this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option), step 3 ask to Pause after Step 2 on deployment document.
Step 4 ask to assign custom domain
Step 5 ask to Bind SSL
Step 6 ask to check if custom URL is working.

If so, steps that you are mentioning are after step 6.

The current status is, I could not receive a 200 ok as mentioned on step 6 for custom url.

Also a new deployment using default URL is not responding with 200 ok for /health.

**Comment by gsv022** [comment]
Hi @diegoriera ,
As you mentioned that default domain URL is not working. Could you please share the places where default domain has been updated with supporting screenshots.

**Comment by diegoriera** [comment]
Hi @gsv022 looks like we are not on the same page.

Keeping Custom domain option as default (Azure Front Door) it is also not working, it means that, the deployment is not provisioning company communicator correctly.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/15849138/7a8ba79b-8ed4-4008-a1ad-430893f3ef1f)

Even re-deploying App Service and Function App the status keeps the same, all paths keep returning 404.

**Comment by gsv022** [comment]
Hi @diegoriera ,
User went with default domain and there were some configuration issues observed. They were corrected. And user confirmed that issue can be closed.
