### ISSUE TITLE
Error While Deploying CC "Failed to Create or update User app in AAD"

### ISSUE THREAD

**Issue by rcoleta** [OfficeDev/microsoft-teams-apps-company-communicator#1178]
Hi, hope you are well.

I'm receiving the error bellow when deploying the CC:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148382422/d60db76b-d6b7-478b-8aa7-61929974b442)

Could you help me to fix this? I've checked the permissions, but the account that I'm using is Global Admin.

**Comment by gsv022** [comment]
Hi @rcoleta ,
Thanks for raising the query.  Uninstall the existing Azure CLI version. Here is the link for required [Azure CLI version](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazcliprod.blob.core.windows.net%2Fmsi%2Fazure-cli-2.30.0.msi&data=05%7C01%7Cv-saigattu%40microsoft.com%7C96f6405461e34308c80d08db255701dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638144827909333431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U3KvaAtJ2MR1veaSxaLw9aJdKxWYBG4eKSFtMovEdcw%3D&reserved=0) and try the procedure again.

**Comment by rcoleta** [comment]
Hi @gsv022 !
Tks for the fast reply. I made the uninstall and install of the az cli version mentioned and the problem seens resolved. Sometime after running the application and resources are created, but I received these errors:
![IMG_5278](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148382422/d56f219a-4afb-49e7-8099-c864d6102194)
![IMG_5279](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148382422/66eada99-2460-4149-be9e-e314183b4521)

could it be access permition?

**Comment by gsv022** [comment]
Hi @rcoleta ,
Could you please share the deployment logs. And meanwhile we recommend you to proceed with the manual deployment to unblock yourself

**Comment by rchlofrzcaio** [comment]
Hi gsv022.Hi gsv022.

Here is the logs from the issue that  @rcoleta is handling

[logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13055441/logs.zip)

Thank you

**Comment by rcoleta** [comment]
Hi!

Any update about this issue?

**Comment by gsv022** [comment]
Hi @rcoleta ,

- **_RoleAssignmentUpdateNotPermitted_** is the error observed in logs that has been shared. Please update the below 7places with new GUID's. Here is the [link](https://www.guidgenerator.com/online-guid-generator.aspx) to generate new GUID's.

<img width="471" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0c16d01d-d4c8-4dbb-ba8a-ad26aa63825a">

- Then go for re-deployment. If there is any issue observed please share the logs. Meanwhile to keep yourself unblocked go for manual deployment.
