### ISSUE TITLE
error on powershell deployment

### ISSUE THREAD

**Issue by gyrantol** [OfficeDev/microsoft-teams-apps-company-communicator#1179]
I have uninstalled and let the deployment install the azure cli but I am still getting the following error.

Creating Azure AD App: Company_Communicator-users...
ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False

Examples from AI knowledge base:
az ad app create --display-name mytestapp --optional-claims @manifest.json
Create an application with optional claims

az ad app create --display-name mytestapp --identifier-uris https://mytestapp.websites.net --app-roles @manifest.json
Create an application with a role

https://docs.microsoft.com/en-US/cli/azure/ad/app#az_ad_app_create
Read more about the command in reference docs
Waiting for app creation to finish...
Azure AD App: Company_Communicator-users is created.
Updating app secret...
ERROR: argument --id: expected one argument

Examples from AI knowledge base:
az ad app credential reset --id 00000000-0000-0000-0000-000000000000
append or overwrite an application's password or certificate credentials (autogenerated)

az ad app credential reset --id 00000000-0000-0000-0000-000000000000 --cert "@~/cert.pem"
Append a certificate to the application with the certificate file.

https://docs.microsoft.com/en-US/cli/azure/ad/app/credential#az_ad_app_credential_reset
Read more about the command in reference docs
Azure AD App: Company_Communicator-users registered successfully.
Failed to create or update User app in Azure Active Directory. Exiting...

**Comment by gsv022** [comment]
Hi @gyrantol ,
Thanks for raising the query.  Uninstall the existing Azure CLI version. Here is the link for [Azure CLI version](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazcliprod.blob.core.windows.net%2Fmsi%2Fazure-cli-2.30.0.msi&data=05%7C01%7Cv-saigattu%40microsoft.com%7C96f6405461e34308c80d08db255701dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638144827909333431%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U3KvaAtJ2MR1veaSxaLw9aJdKxWYBG4eKSFtMovEdcw%3D&reserved=0) and try the procedure again.

**Comment by gyrantol** [comment]
if I do that I get this error 

PS C:\temp\microsoft-teams-apps-company-communicator-main\Deployment> .\deploy.ps1
Checking if Azure CLI is installed.
Please make sure the installed version of Azure CLI is 2.49.0 or higher.
You have version  installed.
Please refer to the prerequisites section of powershell deployment guide
PS C:\temp\microsoft-teams-apps-company-communicator-main\Deployment>
