### ISSUE TITLE
CC App sent message result all failure!

### ISSUE THREAD

**Issue by mavistangtpl** [OfficeDev/microsoft-teams-apps-company-communicator#1180]
<img width="520" alt="Screenshot 2023-10-19 105931" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/d651492a-ffd4-4bc7-b26c-7b7869bcd479">

There just select "send to the General channel of specific teams" will be success ，it's send to cc app (user).
Now, When I select  "send in chat to members of the following teams" or "send in chat to everyone", the result all failure.
How can I solve the problem.
thanks.

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Thanks for raising the query. Could you please cross-verify the configuration end-end and especially
- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
    Author-multiple
    User-multiple
    Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , Thanks for raising the query. Could you please cross-verify the configuration end-end and especially
> 
> * Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
>   Author-multiple
>   User-multiple
>   Graph-my organization
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

same to you!
Author-multiple
User-multiple
Graph-my organization

The problem didn't solve, please help.

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Please cross verify the secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , Please cross verify the secrets. Here is the procedure for comparison.
> 
> * Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)
> * Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources
> * Go to Access Policy--> Click on Create
> 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">
> 
> * Select **Key, secret and certificate management**
> 
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">
> 
> * Give the Id through which one can view the secrets
> 
> <img alt="image" width="475" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">
> 
> * 3rd step is optional
> * Go for Review+Create
> * Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

sorry, when I Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id) there are "Client secret values cannot be viewed, except for immediately after creation. Be sure to save the secret when created before leaving the page." I can't see the value.

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
It is correct  as you mentioned secret value won't appear in full. please grab the first 3 letter and compare it in key vaults.

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , It is correct as you mentioned secret value won't appear in full. Please grab the first 3 letters in app registrations and compare it in key vaults.

When I use first 3 letters in app registrations and compare it in key vaults --> create an access policy --> Select Key, secret and certificate management  -->  Principal  , there are "No results found."

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Please go for above procedure if you are getting _unauthorized to view the secrets_ in SECRETS section.
<img width="881" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/4055dfa2-c997-4891-a8b4-e1ae8048908f">

- if you are getting the above message, then go to access policy and follow the previous response that I shared. Within the principal give you mail id(UPN) through which you want to have access.

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl ,
> 
> * Please go for above procedure if you are getting _unauthorized to view the secrets_ in SECRETS section.
> 
> <img alt="image" width="881" src="https://user-images.githubusercontent.com/98143492/278254053-4055dfa2-c997-4891-a8b4-e1ae8048908f.png">
> * if you are getting the above message, then go to access policy and follow the previous response that I shared. Within the principal give you mail id(UPN) through which you want to have access.

<img width="634" alt="Screenshot 2023-10-26 165217" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/ec62aa15-521c-4993-8f51-4aa94bede047">

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Could you please write what you are expecting

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , Could you please write what you are expecting

I hope when I select "send in chat to members of the following teams" or "send in chat to everyone", the result success.

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Great, how about other sending options?

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , Great, how about other sending options?

send to channel is success. 
When I select "send in chat to members of the following teams" or "send in chat to everyone", the result all failure.

**Comment by gsv022** [comment]
@mavistangtpl , How about 4th sending option? Please try that let us know

**Comment by mavistangtpl** [comment]
> @mavistangtpl , How about 4th sending option? Please try that let us know

@gsv022 , I can not find any groups in the option 4th,  there are just "Note: This option sends the message to all the members of the group who have access to the User app."

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
For 4th option, please type the group/team name within the search bar. Once it appears. Select it.

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , For 4th option, please type the group/team name within the search bar. Once it appears. Select it.

I can not search any group/team.

**Comment by gsv022** [comment]
Could you please share the error that you are facing with supporting screenshot w.r.t 4th sending option
