### ISSUE TITLE
CC App Author Keep Prompting for Authentication

### ISSUE THREAD

**Issue by weixian-zhang** [OfficeDev/microsoft-teams-apps-company-communicator#1182]
CC App Author perpetually prompting for authentication by popping up and closing a blank browser window

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/83f1db08-4ed4-4620-90f5-0936b355815e)
  
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/d5254162-1e52-48ee-bf05-e7e795417db2)

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Thank you for raising the query. Could you please verify the graph-app authentication part is correctly done or not. Here is the [reference](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication).

- Check supported account type- Myorg 
- Check API permissions and Grant Admin Consent is given or not.
- Check URL in authentication and expose an API.

**Comment by weixian-zhang** [comment]
Hi @gsv022,

Thanks a lot its working fine now after I setup the graph-app authn portion.
This also solves [issue 1183](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1183)
