### ISSUE TITLE
CC App Author Cannot find Teams channel in "New Message"

### ISSUE THREAD

**Issue by weixian-zhang** [OfficeDev/microsoft-teams-apps-company-communicator#1183]
CC App Author cannot find CC App User "registered" Teams channel.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/3475b1ff-f214-4e12-bf31-cd35672c9ca9)

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Thanks for raising the query. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue.

Keep us posted

**Comment by weixian-zhang** [comment]
Thanks for troubleshooting guide, I did add "CC App User" to a specific Teams channel, but I am still not able to find any channel in CC App Author "New Message"

**Comment by weixian-zhang** [comment]
Solved with [issue 1182](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1182)
Thanks.
