### ISSUE TITLE
App Registration  Multi Tenant

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1187]
Our company policy is not allowed to create app registration with multi tenant ( account in any organization directory ) .  

Can the communicator works with single tenant app registration ? are there any workaround like without multi tenant registration

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/67a8b9f1-1b2c-4476-beba-8d3e32490544)

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Thank you for raising the query. By switching to the supported account type as **my organization** for author and user bots it will break the functionality. As of now, there is no workaround for this requirement.

**Comment by sponlinedev** [comment]
I have one more clarification. 

There are 3 app registration to be created and in the guide permission are mentioned for one app registration. Other 2 app registration permission are not mentioned.  Does that mean we create those 2 app registration without permission?

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Yes, that's correct. For author and user app registrations no permissions are needed. For graph app registration, permissions are required which are already mentioned in the deployment guide.

**Comment by sponlinedev** [comment]
Thanks for the information .

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Please let us know if you have any queries otherwise we can make it to closure.

**Comment by sponlinedev** [comment]
I have one more query. Is there any roadmap to support single tenant app registration?

Our organization currently don't allow app registration with multi tenant

**Comment by gsv022** [comment]
Hi @sponlinedev ,
As of now, we don't have any roadmap to support single tenant app registration.  Our support scope is very limited to official/standard version of CC.

**Comment by sponlinedev** [comment]
@gsv022  i have one more query have raised new issue 
1195

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Shall we make this issue to closure?

**Comment by sponlinedev** [comment]
yes can be closed
