### ISSUE TITLE
Intermittent Issue with Author App

### ISSUE THREAD

**Issue by chandni-agarwal** [OfficeDev/microsoft-teams-apps-company-communicator#1188]
Hi Team,

The author app is facing intermittent issue in New Teams and sometimes over browser. However, works fine for Classic Teams.
<img width="566" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/23003280/1721e7fd-54c0-4dc9-81cc-36b25e6d08f8">

**Comment by gsv022** [comment]
Hi @chandni-agarwal ,
Thanks for raising the query. 

- Could you please share the application insight logs. Here is the reference.

<img width="630" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/7516c8af-06ae-4ff6-a6d1-d45e1098e373">

- What is the version of the app?
