### ISSUE TITLE
Update from v5.4.1 to v5.5 -- Draft Messages are Gone!

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#1190]
Hello.

I have just upgraded from version 5.4.1 to the latest v5.5, and to my surprise after restarting Teams and opening the Company Communicator Tab on my team as usual, to check on the new features, I noticed all my draft messages were gone!

I then realized the draft messages were still in the database, in the _NotificationData_ table, but not showing in the app UI.

I was unable to recover the drafts, but since I was still able to read its data directly from the DB, I ended up creating new Drafts and copy/pasting the text I could grab from the database...

Not sure what happened, or if this was "expected" with this upgrade - nonetheless no information or warning was provided on the release notes.

Can anyone let me know if this release breaks the existing drafts (be it because of DB schema changes, or anything like that)?

Also serves as a warning/info to others, in case they run into the same.

Thank you.

**Comment by gsv022** [comment]
Hi @victorsimonlee ,
Thanks for raising the query. We will check this scenario from our end and get back to you with proper response.

**Comment by gsv022** [comment]
We have added this into our backlog. We will perform one round of testing for this scenario. If this exists, We will take this as priority and plan it for the future releases.
