### ISSUE TITLE
v5.4.1 - Recipients Dropdown not taking spaces

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#1191]
Hi, this is an issue introduced with version 5.4.1:

When typing the name of a team or group in the "recipients" dropdown, one can't use SPACES anymore.

For example:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/42776398/3b698690-61ef-4387-ac37-78e055e9b75b)

Whenever I hit the "space" bar, the app understands as an "enter", and selects the current input.

For that, I had to rename all my groups, replacing spaces in their names, by dashes "-".

**Comment by gsv022** [comment]
Hi @victorsimonlee ,
Thank you for raising the query.  Instead of searching for the team, just click on the dropdown menu. You'll see a list of teams, but remember, these teams will only show up if the user app is added to that specific teams.

**Comment by victorsimonlee** [comment]
Hi @gsv022 - thanks for the reply. 

Although it works for the TEAM option. It does not work for the last option (M365 or security groups) - the dropdown it initially empty and you have to type to search. 
Before, it was possible to search for groups with spaces in their names - this is not possible anymore.

**Comment by AlexVincent1** [comment]
I am seeing this issue when searching from security groups and distribution lists. Pressing the space bar can lead to accidental selection of the wrong group or DL. This could result in a message being sent to the wrong recipients

**Comment by gsv022** [comment]
Hi @victorsimonlee ,

- 1st and 2nd sending options will be having list within a dropdown. Author can select one or multiple teams from the list within the dropdown.

-  And for the fourth sending option, author can search for team or group names without using spaces, and the system will provide relevant prompts. Similar to the other options, users can select one or multiple teams from the search results. As of now it won't consider spaces within the search bar.

**Comment by AlexVincent1** [comment]
Pressing the space bar acts like pressing the Enter key which can lead to accidental selection of the wrong group or DL. This could result in a message being sent to the wrong recipients. Definitely needs addressing
