### ISSUE TITLE
The role assignment failure when I do the deployment even I am the subscription owner

### ISSUE THREAD

**Issue by qinqingxu** [OfficeDev/microsoft-teams-apps-company-communicator#1192]
I try to follow this guidance to do the deployment:
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

And all the steps are succeeded. only the deployment occur some error.
The error show the role assignment failed:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/93512957/75d30661-3d27-4ff1-8d80-a3e0804bfdcc)

**Comment by gsv022** [comment]
Hi @qinqingxu ,
Thank you for raising the query. Please refer to q.no: [3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#2-app-deployment-failure---roleassignmentupdatenotpermitted) to know more about the issue.

Here is the [link](https://www.guidgenerator.com/online-guid-generator.aspx) to generate valid GUID's. Update all the seven GUID's and go for redeployment.
