### ISSUE TITLE
Communicator Author App Not Showing in MS Teams App

### ISSUE THREAD

**Issue by mkrupeydeloitte** [OfficeDev/microsoft-teams-apps-company-communicator#1193]
When loading the app in MS Teams, the page is just blank. The app doesn't show at all. When clicking the drop down on the tab menu and navigating directly to the web application, the site loads fine.

After some additional exploration, if we use a Website app in MS Teams and point to the Communicator Authors website URL and navigate there. It will start the login process and go through MFA and the site loads fine. If I then go back to another channel showing the MS Teams app, the app will now show properly.

Somehow perhaps the MFA/token isn't getting generated properly from the MS Teams app. Any ideas on why it won't show up in MS Teams app? We have set the webresource tag in the manifest to point to the Azure app id and are using api://12345... etc.

![communicator-picture1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144729232/4b902f75-8df1-476c-a1ee-2f02c5b680f6)

**Comment by gsv022** [comment]
Hi @mkrupeydeloitte ,]
Thank you for raising the query. 

- Could you please provide more details like logs within application insights. Here is the reference.
<img width="958" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d96bc3b0-acd0-48d8-88ac-9baadec94bcc">

- Any additional information would be more helpful

**Comment by mkrupeydeloitte** [comment]
I'm trying to get access to that area in our environment to see if any errors are being thrown. My assumption is that this an authentication issue where using the communicator from MS Teams is not getting through MFA and therefore not showing on the screen. As mentioned though, if I authenticate through a MS Team Website app it will force me to login with MFA and then the MS Teams app will display.

There is an open Microsoft case TrackingID#2306060030003647 with HAR traces from MS Teams.

**Comment by gsv022** [comment]
Hi @mkrupeydeloitte ,
Please share your mail id(outlook or teams id) so that we can discuss the issue internally.

**Comment by mkrupeydeloitte** [comment]
we are federated with Microsoft so a Teams chat or email will work. for contacting, place the @ between my name and my company in my user name.

**Comment by gsv022** [comment]
Hi @mkrupeydeloitte ,
Thank you for joining the call.  Here is the summary.

- Application was developed from the scratch as per their organizational needs. It works fine with VPN but when accessing it directly on teams giving issue. 

- We mentioned that our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version.
Please let us know if you have any issues with the standard version.
