### ISSUE TITLE
Regarding Teams users App and graph Permission 

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1195]
1. Our User case is to send message to DL / Security group in communicator app . In this use case should we deploy the teams user app compulsory  or when sending to DL or security group users will receive the message as 1:1 chat where there is no need to deploy the user app to all users
 
3. If we don't enable this permission TeamsAppInstallation.ReadWriteForUser.All  what are the impact which function will not work

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Thank you for raising the query. 

- User app must be present at the tenant level so that DL selected through 4th sending option where each user within the DL/M365 group will be installed with user app otherwise messages won't be delivered.
- If we don't enable the permission-TeamsAppInstallation.ReadWriteForUser.All, 4th sending option won't work.

**Comment by sponlinedev** [comment]
If the message to be viewed teams user app should be deployed and made available for all the users so that they can see the message broadcasted.

If we deploy and made the app available for anyone so we still need the permission mentioned above?

**Comment by sponlinedev** [comment]
would like to clarify  ,  let say from the teams admin center we install the user app and made available for all users .  Do we still need the grant permission for TeamsAppInstallation.ReadWriteForUser.All

**Comment by gsv022** [comment]
Hi @sponlinedev ,
User app must be added at the tenant level and the permission need to be kept because members in the team is not fixed(may get added/removed).

**Comment by sponlinedev** [comment]
in one of the issue its mentioned auto install when message is sent or install and made available via teams admin center 
if we install install and made available can proactive install can be disabled thus the graph permission is not required.


**From other Issue** 
This is the permission that allows for the proactive app installation feature that was part of the V3 release. Before this feature was available, only users that had the Company Communicator app installed would receive a message sent to them. Meaning you would either need to install the app for all users via the Teams admin center or ask everyone to side-load the app.


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/f2a12a2c-a9c0-4098-a16e-e1f4cc5597a8)
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/240

**Comment by sponlinedev** [comment]
@gsv022  Any updates on this query

**Comment by gsv022** [comment]
Hi @sponlinedev ,

- When the message is about to deliver to the user, there will be a check whether user app is installed at the tenant level or not. If proactive installation is set to true and permission is granted within API permission then user will get installed with the user app. 

- If the members count in team is same , this process is a one time activity.  But practically this wont be the scenario, members in the team will be dynamic(increase/decrease). When new user joins, CC will install the user app to new user with the help of proactive installation and then will send the message.
