### ISSUE TITLE
Step 6.3 Issue

### ISSUE THREAD

**Issue by fbosiocedi** [OfficeDev/microsoft-teams-apps-company-communicator#1197]
Good afternoon, 

After completing all the steps, when I want to add the application to the teams catalog I get an error saying that there is already an application with the same app ID.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/106543233/c051a39f-c927-46bb-bef8-0effe11e2746)

Could you help me?
Thank you.
Regards.

**Comment by gsv022** [comment]
Hi @fbosiocedi ,
Thanks for raising the query. It seems that there is already an application installed to the same tenant with the same id. Please change the id parameter in the manifest and re-upload. Here is the reference.
<img width="449" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f95e23bf-e305-42d6-8329-62260b553d95">

**Comment by fbosiocedi** [comment]
> Hi @fbosiocedi , Thanks for raising the query. It seems that there is already an application installed to the same tenant with the same id. Please change the id parameter in the manifest and re-upload. Here is the reference. <img alt="image" width="449" src="https://user-images.githubusercontent.com/98143492/280235790-f95e23bf-e305-42d6-8329-62260b553d95.png">

Thank you gsv022, I think that I need to change de ID in the appservice configuration. This ID should be the same, right?

**Comment by gsv022** [comment]
Hi @fbosiocedi ,
If it is a user app that is giving the issue. Please create a new GUID, update the same in manifest and in app service configuration. Here is the reference.
<img width="647" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a6625d50-7dbd-46f9-b1ea-906f16184b3e">
