### ISSUE TITLE
Unable to send messages after refreshing storage account access keys

### ISSUE THREAD

**Issue by alexl-2397** [OfficeDev/microsoft-teams-apps-company-communicator#1200]
I refreshed my Communicator's storage account keys recently and this seems to have broken my Communicator.
At first it stopped me accessing the author app on Teams, but I quickly realised what I had done, and I updated the storage account access connection string within the keyvault, and updated StorageAccountConnectionString within the environment variables of the app service, and all 3 data functions.

However today I have noticed I cannot send messages, I can access the Author App fine, however each message just stays in "Queued...".
I have checked the App Insight and it is failing on the storage account from the looks of things, I'm just unsure where.
<img width="1053" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/105488615/21edcff4-9b19-494a-9402-d8159c86d66f">

Any advice on this would be appreciated.

**Comment by gsv022** [comment]
Hi @alexl-2397 ,
Thanks for raising the query. 

1. Please cross-verify the steps that has been performed for updating storage account connection string. 
2. Before refreshing the keys, was application working fine?
3. What is the version of the app?

**Comment by alexl-2397** [comment]
Hi @gsv022,
1.
Renewed the Access Key's for a PowerBI report
Realised access wasn't working to author
Went into the keyvault, updated the vault key with the newest access key, copied the connection string
Replaced the storage account old connection string inside the app service with the new keyvault reference
Authr access worked.
Realised I couldn't send messages
Replaced the storage account connection strings inside the the functions with the new keyvault reference
Still unable to send messages

2. Before refreshing the keys it was working, the last message was sent roughly 2 days before.

3. The version is the most recent, v5.5.

Thank you.

**Comment by gsv022** [comment]
Hi @alexl-2397 ,
Please share your mail id (Outlook id or teams id) so that we can discuss the issue internally.

**Comment by alexl-2397** [comment]
Hi @gsv022,
I'm available between 8AM-4PM GMT, any day of the week.
Thank you.

**Comment by gsv022** [comment]
Timings is fine. Please share your **mail id** (Outlook id or teams id) so that we can discuss the issue internally.

**Comment by alexl-2397** [comment]
Hi @gsv022
Sorry! It's Alex.Lanning@Somerset.gov.uk
Thank you.

**Comment by gsv022** [comment]
@alexl-2397 ,
It is confirmed that issue got resolved upon restarting the function apps.
