### ISSUE TITLE
Company Communicator - User has all permission as author but can't  open the Company Communicator application

### ISSUE THREAD

**Issue by e-mujica** [OfficeDev/microsoft-teams-apps-company-communicator#1204]
User has same permissions as other users, who are able to author messages. He is the only one who can't access the application, although he is even listed as Owner.  He gets the following error, any help is appreciated.
![MicrosoftTeams-image (3)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/127960941/638c1a98-38df-4e75-a053-f6b3393a7bd3)

**Comment by gsv022** [comment]
Hi @e-mujica ,
Thank you for raising the query. Could you please check whether the user who is trying to access the application has his UPN present in the "authorizedCreatorUPN" list or not. Please make sure UPN is added to that parameter. Here is the reference.
<img width="810" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f7a26674-9d51-4e87-880c-b0e960e14e84">

**Comment by e-mujica** [comment]
Hi @gsv022,  could you tell me how to navigate to that particular setting?  I I'm having issues finding it in our portal.  Thx

**Comment by gsv022** [comment]
@e-mujica ,
Sure, here is the procedure. 
Open Azure Portal--> Go to resource Group-->Select rg (where CC is deployed)-->Pick Web app/App service from a list of resources-->Go to configuration-->Search for UPN. It will be found.
