### ISSUE TITLE
changes required after migrating frontdoor from classic to Premium

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1205]
Hi 
Would like to check if there is any change  we need to do in Communicator Azure solutions or app registration if we migrate our frontdoor from classic to Premium.

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Thank you for raising the query. CC works fine with Azure Front Door Classic. Almost both shares the same features/optimizations. Any specific reason to migrate to premium?

**Comment by sponlinedev** [comment]
to configure waf rules with latest baseline (2.1)

**Comment by gsv022** [comment]
Hi @sponlinedev ,
We haven't tested with Azure FD-Premium type. Please test it out from your side and let us know how it goes.
