### ISSUE TITLE
Teams App Authentication Fail

### ISSUE THREAD

**Issue by weixian-zhang** [OfficeDev/microsoft-teams-apps-company-communicator#1206]
I deployed CC App using Powershell deployment and also double checked the authentication setup using this guide [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) to setup authentication but met with the follow authn issue.
Can you please advise, thanks.  

<b>my version of Teams client </b>
<img width="326" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/eb45bf77-91b0-4776-b1a0-cd4e67cbecd4">

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/754082d3-6bfa-4c33-9ca7-3a07b454affa)  

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/72aad563-0741-4cf6-a7aa-df9f9280f6ea)  

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/ef988907-f938-45ee-8297-7ca7aeb3707c)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/606a735b-e6e1-4369-910d-3c6891029227)  

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/6f1b076c-b71a-4574-8960-853de03ed8ac)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/2d946827-5b82-4918-84ae-7487ca24063d)

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Thanks for raising the query. We are checking this issue on priority and will keep you posted.

**Comment by weixian-zhang** [comment]
Thanks, I have some minor updates to issue description
