### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1207]
[company-communicator-users.zip.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13308079/company-communicator-users.zip.zip)

Hi, 

Any idea on what I have done wrong with this?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Please rename the file-manifest **_user** to manifest and zip it again. This time it works.
<img width="278" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6c6430b2-9b75-4f2a-9fca-162533cf5b28">

**Comment by ahlim0011** [comment]
All good thanks
