### ISSUE TITLE
Opening the Author App is giving MismatchCert Issue

### ISSUE THREAD

**Issue by grsandeep** [OfficeDev/microsoft-teams-apps-company-communicator#1209]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/28734783/fe26c880-d2d3-42a0-a366-5a6076faa1e8)

Seeing the above error from last few min when opening the Author App in MS Teams

**Comment by gsv022** [comment]
Hi @grsandeep ,
Thank you for raising the query. Please respond to the below queries.

- What is the deployment approach followed for CC?
- What is the version of the app?
- Please share the application insight logs. Here is the reference.
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in a text file. Share it here.
<img width="947" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0fc4ae9c-7301-4c1b-a8c0-672a986efeb8">
