### ISSUE TITLE
Company Communicator Reading Error

### ISSUE THREAD

**Issue by Cazara2912** [OfficeDev/microsoft-teams-apps-company-communicator#1210]
The Company Communicator app has been successfully installed within Azure without any issues. An inspection of the app's installation, its connectors, and resources shows no errors. Therefore, it is presumed that the issue lies within the template.

Here are the errors observed in the app:

Reading of communications is incorrect, and it doesn't display accurate indicators of users who have viewed the sent messages.
A functionality test has been conducted, which provided the following indicators:

A communication with an attached Forms link was sent.
464 users received the communication.
31 users have read the message.
108 individuals clicked on the attached link button.
81 people responded to the form.
As evident, none of the indicators correspond to the message readings. Various tests were carried out, all of which revealed the same reading error within the app.

![Error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/64184113/2ec8ad23-938b-4717-b6ab-4ed5bed84fdd)

Could you help me with a solution for the error the application is experiencing?

**Comment by gsv022** [comment]
Hi @Cazara2912 ,
Thank you for raising the query. Please share the repository URL and branch. Here is the reference
<img width="590" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/60b17f32-d42a-4984-b7e4-b1e326220dad">

**Comment by Cazara2912** [comment]
URL attached for error verification.

I look forward to the comments, thank you.

https://github.com/cristianoag/microsoft-teams-apps-company-communicator.git


![Imagen de WhatsApp 2023-11-13 a las 07 26 24_91a91c3f](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/64184113/f4dfa9a0-d5af-4d1f-8bed-6e38c47d5440)

**Comment by gsv022** [comment]
Hi @Cazara2912 ,

- Number of reads is the feature yet to be implemented in official version of CC.

- Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version. 

Official Repository URL: -https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

- Could you please confirm whether you are able to access CC application right now.
