### ISSUE TITLE
"Problem Reaching this app" error (similar to closed issue #4249)

### ISSUE THREAD

**Issue by tgainey** [OfficeDev/microsoft-teams-apps-company-communicator#1211]
Published version 5.3.1.

I'm using the app via Teams online. We were able to use the app a week ago, and now receiving the following page:

CC error 11323

Cleared browser history and no change.

Restarted services in azure and no change.

**Comment by gsv022** [comment]
Hi @tgainey ,
Thank you for raising the query.  Please respond to the below queries.

- What is the error displayed when trying to access author app? Please share a screenshot of it.

- Could you please point to this issue _CC error 1132_ you are pointing to with a link or supporting screenshot

- Please share the repository URL and branch. Here is the reference
<img width="590" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/60b17f32-d42a-4984-b7e4-b1e326220dad">

**Comment by tgainey** [comment]
![CC error 11323](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143223810/11cc7015-cc72-457a-ab3b-420426925713)

**Comment by tgainey** [comment]
![CC Repo and Branch 111323](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143223810/7aafeb89-5f7e-4178-82e9-b3ffd64a8c2b)

**Comment by gsv022** [comment]
Hi @tgainey ,
Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version. 

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
