### ISSUE TITLE
Communicator app and frontdoor WAF Custom Rule

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1213]
Hi 
We are planning to setup the custom rule with IP restriction so that external users will not be accessing the azure resources .

we would like to get information on Communicator app and frontdoor WAF Custom Rule.  If we want to have a restriction for the IP range besides the organisation IP range should we also allow IP range of Teams for cmmunicator to work ?

Please help to provide some information  and best practice for IP restriction in frontdoor WAF Custom Rule

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Thanks for raising the query.
Please note that our support scope is very limited to official version of CC. Please contact with your internal IT team on this requirement. Here is the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option) for custom domain recommendations.

**Comment by sponlinedev** [comment]
Thanks for the information .

we are planning to have IP range restriction in frontdoor WAF custom rule.  We will enabled the IP range of our organization but we would like to clarify .  do we need to whitelist any IP from MS like teams IP range etc.

**Comment by gsv022** [comment]
@sponlinedev , We can't comment on whitelisting of IP's. It will be organizational specific. Our support scope is very limited to official version of CC. Please reach out to your internal infrastructure team to get to know more about this.

Do let us know if you have any queries w.r.t standard version of CC we are happy to assist you.
