### ISSUE TITLE
Teams IP Whitelisting at Front Door

### ISSUE THREAD

**Issue by weixian-zhang** [OfficeDev/microsoft-teams-apps-company-communicator#1215]
Hi,

We wish to IP whitelist CC App to Teams (and on-premises Team clients which we will handle) only and not expose CC App to the Internet.
Can you please provide some guidance on what are the Teams IP addresses to include in the whitelisting?
Thanks.

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Thank you for the patience. We can't comment on whitelisting of IP's. Our support scope is very limited to official version of CC. Please reach out to your internal infrastructure team to get to know more about this. 

Please let us know if you have any queries w.r.t standard version of CC we are happy to assist you.
