### ISSUE TITLE
Error when accessing CC authors app: CAA20004

### ISSUE THREAD

**Issue by rafi4242** [OfficeDev/microsoft-teams-apps-company-communicator#1216]
Hi,

I successfully installed the communicator using the automatic PowerShell script. After Installing the authors app to a team and trying to access i get the following error:
Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: {appId}({appName}). Resource value from request: {resource}. Resource app ID: {resourceAppId}. List of valid resources from app registration: {regList}.

Seems as if teams is not allowed to access the company communicator app:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/e9bc50be-eb0a-4013-b34a-a4eec0901cd8)

**Comment by gsv022** [comment]
Hi @rafi4242 ,
Thanks for raising the query. 

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select app service(web app) from list of resources-->Go to Deployment Center-->Click on logs-->Share the screenshot

- Please share the application insight logs. 
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8af97c7e-1627-4790-a0bc-788805d31f7b)

**Comment by rafi4242** [comment]
- 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/8ee0a778-77ad-435f-87ee-40c0ff5649af)


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/09bebce8-cbdd-4e9f-9cdf-3a2e001e1e89)

**Comment by gsv022** [comment]
Hi @rafi4242,
Please ensure you have proper permissions and role to access the application. Here is the [list](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#prerequisites) of prerequisites

**Comment by rafi4242** [comment]
> Hi @rafi4242 , Thanks for raising the query.
> 
> * Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select app service(web app) from list of resources-->Go to Deployment Center-->Click on logs-->Share the screenshot
> * Please share the application insight logs.
>   Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat.
>   ![image](https://user-images.githubusercontent.com/98143492/283028819-8af97c7e-1627-4790-a0bc-788805d31f7b.png)

What i attached is enough?

**Comment by rafi4242** [comment]
> Hi @rafi4242, Please ensure you have proper permissions and role to access the application. Here is the [list](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#prerequisites) of prerequisites

Yes, my user has User Access Administrator in this subscription, and i added my users as authorizedcreatorsUpns.

**Comment by Karspi** [comment]
Facing the same issues. Our App Insights are filled with errors 401
With browser investigation we can see the error is coming from a permant redirect and thereafter a 401 failed log in.
The 401 failed login does not include the bearer token


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44868218/feecc828-7c81-477a-a5f2-bee71e36ecf1)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44868218/87967b9c-81a2-4ab1-8f9d-0a168ef22e40)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/44868218/1f90350f-5791-4f8b-84d8-c4efa86c61f2)

**Comment by gsv022** [comment]
Hi @rafi4242 ,
Could you please share the screenshots of the deployment status of app service. Here is the reference.
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center
<img width="596" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/1db3daa1-362f-4d9a-baed-79872affe60c">

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f116cba9-4728-4e58-8ba4-3a78059be05e)

**Comment by rafi4242** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/c0fa2c93-055e-4b81-b415-7a9d00925966)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/944325ca-ec45-4080-9f3b-60d56bc6b0ac)

BTW, is this product not covered by Microsoft official support? In case I do manage to install and use this app, future support in case of issues will be solely from this GitHub?

**Comment by gsv022** [comment]
Hi @rafi4242 ,

- Please SYNC the app service. Once done it will be appearing as below

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a5396457-3554-44b5-94f2-71fa68095d50)

- Now try accessing the application and do let us know the behavior

**Comment by rafi4242** [comment]
Hi,

I synced and now it looks like you showed:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/451f9a6e-c224-4fc5-ae59-82c0f2b77575)


But I still get the same error:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/a85ddd04-6619-4b5a-9221-95da79485510)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/addc59e1-088b-4849-8570-07ad8aef7019)

**Comment by gsv022** [comment]
Hi @rafi4242 ,
Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication). Please share the screenshots as shown in deployment guide it would be helpful for better troubleshooting.

**Comment by rafi4242** [comment]
Thanks, it seems this part was missing from the auto powershell installation:

```
Click Add a client application, under Authorized client applications. In the flyout that appears, enter the following values:

Client ID: 5e3ce6c0-2b1f-4285-8d4b-75ee78787346
Authorized scopes: Select the scope that ends with access_as_user. (There should only be 1 scope in this list.)
Click Add application to commit your changes.

Repeat the previous two steps, but with client ID = 1fec8e78-bce4-4aaf-ab1b-5451cc387264. After this step you should have two client applications (5e3ce6c0-2b1f-4285-8d4b-75ee78787346 and 1fec8e78-bce4-4aaf-ab1b-5451cc387264) listed under Authorized client applications.
```

I will now proceed to test the application!
