### ISSUE TITLE
Teams Author App Error while launching

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1217]
We have deployed the Autor app and user app .  when we add the Autor app we get the below error 

Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.  Intially it load screen partially after a second this error appear.

All the graph permission is created and multi tenant is created for user app and auher app as per the deployment guide 

Please advice how to see detail erorr and also other places to check if all configuration is correct 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/ab3f56ab-2cf5-4976-bf2c-5967178b6463)

Graph App - Registration 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/67dab888-f78e-44cb-843c-5baaa1bfc706)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/2576b848-48ca-45c6-b1d7-fd035444bd10)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/920e15d4-72db-445e-b6a2-bd410a17b89e)

Graph Permission 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/2df2beb9-5a9a-4a61-9b60-914605ac76a3)

Author App Registration
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/84406f26-fe68-45cb-9937-f40bd88c08a9)

Function App deployment status
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/103d402b-632c-4ca6-8a7b-6623fde7e863)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/bec0a84b-0b02-477f-82e9-c9afe66dcabd)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/2196c1db-20c0-4de1-b5ba-e8d88d295cf3)

Azure solution are deployed in Tenant A and Teams app and App registration are done in Tenant B.  During the setup tennant id given is Tenant B (tems app installed and app registration)

application insight does not show any error , refer to the image below 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/27e84971-60c1-480b-99c4-66d333a453cd)
From dev tool i can see some error on azure functions not sure if this is related
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/bbf4955a-a80a-472f-a90a-99eb0a03c9f5)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/d54ee697-c7a0-429b-b45a-fe1863ab95d0)

Checked the CROS setting for app services frontdoor url is added in the allowed list
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/57736182/26857b8f-2638-4671-bfa8-f3f9969ef6a2)

**Comment by ahlim0011** [comment]
I have the same error, but I see I have a few things different then yours, if you fix it can we please have a call or any sort of help, I am really struggling on making this work :(

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Thanks for raising the query. 

-  From your screenshots, within the graph api permissions there is one delegated permission missing. Please check and update. 
- Hope you have updated manifest section within graph app registration.
------------------------------------------------------------------------------------------------
Please cross verify the secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by sponlinedev** [comment]
i have verified the client id , secret and teannt id its correct.

which permission is missing in grap app registration ?

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Could you please share the zipped manifest files used for uploading to the teams

**Comment by sponlinedev** [comment]
[Communicator_Author.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13364894/Communicator_Author.zip)

**Comment by ahlim0011** [comment]
Please can you tell me what I can do?


ABDUL HALIM
IT Support Administrator
***@***.***
+44 20 7665 5009 direct
12 Gough Square
​London ​EC4A 3DW
+44 20 7665 5000
hausfeld.com
This email is confidential and may be legally privileged. If you have received it in error, please contact me immediately. Hausfeld & Co. LLP is a limited liability partnership registered in the State of New York and is authorised and regulated by the Solicitors Regulation Authority ('SRA') in England & Wales with number 513826.

**Comment by sponlinedev** [comment]
> > attaching mainefest file zip
> > [Communicator_Author.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13364894/Communicator_Author.zip)
> > Can we have a teams call ? short one?
> 
> If you have a fix, please can we have a call?

wait till we find the root casue and fix,.  i will update the thread if we find the solution / fix

**Comment by sponlinedev** [comment]
@gsv022 
Also check the CORS error mentioned in the issue description and previous response for mainfest files for author app

**Comment by ahlim0011** [comment]
should I check the same? If so can you please tell me how to do that

**Comment by ahlim0011** [comment]
[company-communicator-users.zip.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13366560/company-communicator-users.zip.zip)
[communicator-hasfeld.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13366564/communicator-hasfeld.zip)

Attached both of my zip files

**Comment by TomSawyer03** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85331597/8a8a7c4e-c103-4d66-a301-8c1a6e3da096)

We have our company communicator running and working but just now, we are receiving the below exception when we try to access it in Teams
Microsoft.Azure.Cosmos.Table.StorageException: 

GET SentNotifications/GetSentNotifications
GET <storage account>/NotificationData

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85331597/be544e8d-b8c8-4e85-8d89-7ceb03f1a5f6)

**Comment by gsv022** [comment]
@sponlinedev , Issue is being followed internally

**Comment by sponlinedev** [comment]
@gsv022  The issue we faced on CROC issue is due to URL whitelisting , after whitelisting we are able to launch the application .  

However message are not delivering 
Failed to install application for user: 153c3008-0de3-4d3b-9c6f-c47af6193e43. Exception: Code: BadRequest Message: Unable to create 1on1 conversation between user and BotFailed to execute Skype backend request CreateThreadS2SRequest. Inner error: Code: InvalidRequest Message: Unable to create 1on1 conversation between user and BotFailed to execute Skype backend request CreateThreadS2SRequest. Inner error: AdditionalData: date: 2023-11-24T07:07:22 request-id: 3a70e9e9-b7cf-4613-a034-3d43fdb034d1 client-request-id: 3a70e9e9-b7cf-4613-a034-3d43fdb034d1 ClientRequestId: 3a70e9e9-b7cf-4613-a034-3d43fdb034d1

**Comment by gsv022** [comment]
We are following the issue internally

**Comment by gsv022** [comment]
Hi @sponlinedev ,
Please let us know the status of the issue.
