### ISSUE TITLE
messages get stuck in the queue

### ISSUE THREAD

**Issue by MarkusMGB** [OfficeDev/microsoft-teams-apps-company-communicator#1219]
We are having issues that our messages get stuck in the queue and are not send. Last time working was on 9.11. Is this related due latest issues?

Thanks

Markus

**Comment by MarkusMGB** [comment]
Hi Sai Venkat

Thanks for your reply, so here is the screenshot

[cid:333bd10f-e20b-4ec2-b4d6-45c795250a0e]

regarding the logs not sure. if i click on failures i see the dashboard and view in logs

[cid:db66cd0d-c243-46f3-b411-84e4f8ef4b27]

What exactly I need to paste?

thanks & regards

Markus
________________________________

**Comment by gsv022** [comment]
Hi @MarkusMGB ,
Please copy the logs of each one. Paste it a file and share it here. Here is the screenshot for reference
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/e5423b97-b006-47ad-a068-62458736f506)

**Comment by MarkusMGB** [comment]
Copy you the screenshots still not sure what exactly you want.....

[cid:e1a7ac03-05a3-426c-b7e5-475cf7464137]



[cid:1ca08940-45f9-4903-9bbf-2ffb9e75be4b]
[cid:13b0a615-cc6e-4f19-a828-96d8dd12281c]

**Comment by MarkusMGB** [comment]
[cid:b05d5113-f1a7-4d70-a66a-3991800c350b]

________________________________

**Comment by MarkusMGB** [comment]
[cid:cfcff71d-b40b-4111-900d-18f59c0c0d05]

________________________________

**Comment by gsv022** [comment]
Hi @MarkusMGB,
This is how the message is coming for us. They are in masked state.  Please share the screenshots over GitHub directly
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/1faa38a7-18b2-4ba6-b48f-3bd17bfada9a)

**Comment by MarkusMGB** [comment]
Hi @gsv022  here are the screenshots

![CC4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151055891/e4c1f327-f5fc-4279-a6b5-fedb023bfeb2)

![CC1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151055891/b4bcdc97-d394-45bf-98a3-c1bf3d9583f9)

![CC2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151055891/b9b2e1be-589c-46f0-965e-ee3a2cc933cd)

![CC3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151055891/019c8c78-8c90-4070-a053-2a71150ad393)

**Comment by gsv022** [comment]
Hi @MarkusMGB ,
Thank you for sharing the logs. 

- What is the version of the app?

- Could you please share the screenshots of the deployment status of app service. Here is the reference.

Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center
<img width="596" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/1db3daa1-362f-4d9a-baed-79872affe60c">

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f116cba9-4728-4e58-8ba4-3a78059be05e)

**Comment by MarkusMGB** [comment]
We updated the the app two weeks ago (when the problem appeared)  to the latest build which was 5.31. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151055891/14310e16-9c36-4380-a9e1-27e1d991c706)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151055891/3d83a0d2-bef5-4e56-b6b2-c80786817f7f)

**Comment by gsv022** [comment]
Hi @MarkusMGB ,
Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version.

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
