### ISSUE TITLE
Teams channel not found in "New Message" modal dialog

### ISSUE THREAD

**Issue by weixian-zhang** [OfficeDev/microsoft-teams-apps-company-communicator#1223]
I have setup authentication according to this [reference  ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication)
* have configured "senderUPNList" and "AuthorizedCreatorUpns" in app settings of App Service  
* have added CC App (User) to Teams channels
* did not encounter any authentication prompt/error  
  
I am still not able to find any Teams channel, can anyone please advise, thanks.

<img width="1122" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/dce3fc50-e7ee-4fd6-879e-187141ea2698">  

<img width="1127" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/43234101/dcbe8b02-105c-4388-8be3-b3040b4deae3">

**Comment by gsv022** [comment]
Hi @weixian-zhang ,
Thanks for raising the query. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by weixian-zhang** [comment]
Hi @gsv022,

Have done [this](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message), there is still no channels in the drop down.

**Comment by weixian-zhang** [comment]
Resolved after deleting existing Teams channels. Newly created channels can be found in dropdown
