### ISSUE TITLE
Disable app block option in teams

### ISSUE THREAD

**Issue by cencosudregional** [OfficeDev/microsoft-teams-apps-company-communicator#1225]
Hi, i hope you are doing well.
Can you help us to disable the app block option in Microsoft Teams?
<img width="201" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143105447/1d73d059-b0c7-4009-9a4a-2dca64afb495">

Thanks.

Regards-

Luis Araya.

**Comment by gsv022** [comment]
Hi @cencosudregional ,
Thanks for raising the query. Those options are provided by MS Teams and our CC application don't have control over it. Please reach out to MS Teams support team to get to know more on your requirement

**Comment by gsv022** [comment]
Hi @cencosudregional ,
We confirm that our CC code has no control over disable option.

**Comment by cencosudregional** [comment]
Perfect. Thanks for your answer. Regards.

**Comment by gsv022** [comment]
@cencosudregional , We are closing out this issue as we provided the required response. Please fee free to log a new issue if anything comes with official version of CC.
