### ISSUE TITLE
Select all Teams option fails 

### ISSUE THREAD

**Issue by David-hughes8** [OfficeDev/microsoft-teams-apps-company-communicator#1231]
When we select all Teams it appears to select them but when the message comes to be sent, it only sends it to 12 out of 5K teams.  The report seems to indicate that the message was only set-up to send to 12 teams.  Further investigation i.e. saving a message to all teams then re-editing it, shows that it loses all but a handful of teams from it's send list.
This is happening in 2 out of three domains.

**Comment by gsv022** [comment]
Hi @David-hughes8 ,
Thank you for raising the query. We will get back to you soon.

**Comment by gsv022** [comment]
Hi @David-hughes8 ,
Through which sending option, the message has been sent.

**Comment by David-hughes8** [comment]
The version in question is the community version, which has the option to **Select All** the teams which have TCC installed in them.
However we are also experiencing the same problems, after the update in relation to actually accessing the Authors page in the two domains we've updated to the resolve the authentication problem, caused by the update to accommodate Teams 2.

**Comment by gsv022** [comment]
Hi @David-hughes8 ,
Please share your mail d id(teams id or outlook id) so that we can discuss the issue internally.
