### ISSUE TITLE
Message updates not saved

### ISSUE THREAD

**Issue by David-hughes8** [OfficeDev/microsoft-teams-apps-company-communicator#1232]
In one of our domains, it's not saving changes to the title  or body of the message after an message has been re-edited.   There is no error message appearing, but when you look at the saved list nothing has changed and if you then go back in to re-edit it, the original message is as was.  This has only just started happening since Wednesday.

**Comment by gsv022** [comment]
Hi @David-hughes8 ,
Thanks for raising the query. Could you please share the screenshots of the deployment status of app service. Here is the reference.
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App(App Service) --> Go to Deployment Center
<img width="596" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/1db3daa1-362f-4d9a-baed-79872affe60c">

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f116cba9-4728-4e58-8ba4-3a78059be05e)

**Comment by gsv022** [comment]
Hi @David-hughes8 ,
Please share the screenshots as above.
