### ISSUE TITLE
azure sync V5.5 failed

### ISSUE THREAD

**Issue by mavistangtpl** [OfficeDev/microsoft-teams-apps-company-communicator#1233]
I hope sync in azure about microsoft-teams-apps-company-communicator 5.5 version.
But there are failed.
<img width="364" alt="Screenshot 2023-11-24 182310" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/a33b581e-5d9d-4bab-9650-cad6692c3dfc">
[
<img width="375" alt="Screenshot 2023-11-24 182336" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/eecf371f-1158-4dc9-b9fc-8a8109414d81">
](url)

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Thank you for raising the query. Please change the app service plan to S2. Then go for a sync of app service(web app).

Keep us posted
