### ISSUE TITLE
Migration from 5.4.1 previous versions to new version

### ISSUE THREAD

**Issue by Nadeem21210** [OfficeDev/microsoft-teams-apps-company-communicator#1234]
Dear team

I have app service with version 5.4.1 and was pushing it for hotfix after facing an issue while using CC.

While applying changes using below migration guide (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) , i am facing the issue in power shell screenshot of which is attached for reference.

I have logged in subscription via powershell and despite validating myself, the error message is same.

![CC](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140392236/06602ffb-71ba-40cc-97f7-9903bed865b7)

**Comment by Nadeem21210** [comment]
Azure CLI is already installed.
tried from different machines.
No change in error message.
Appreciate if we can connect over MS Teams to close this

**Comment by gsv022** [comment]
Hi @Nadeem21210 ,
If the repository is v5.4.1 already, please add the parameters from [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) which ever is not there in the app service configuration. Then perform SYNC for app service. Here is the reference of the parameter that need to be added.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/e41c32e1-d019-49ef-9331-3e81c1466766)
