### ISSUE TITLE
We're sorry, there was an error trying to access this service.

### ISSUE THREAD

**Issue by casticod2** [OfficeDev/microsoft-teams-apps-company-communicator#1235]
We have had the following error for a few days: We're sorry, there was an error trying to access this service.
After seeing another thread in this forum we have followed the instructions and we get an error when synchronizing again. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/90576784/a2c54c3c-d183-45dd-8d31-fae93d83e5c2)

If we pay attention to the url that I have configured, the ending is different: https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git
If I use :https://github.com/OfficeDev/microsoft-teams-company-communicator It doesn't let me save the changes. 

Anything else I can do? Any help would be welcome.

**Comment by gsv022** [comment]
Hi @casticod2 ,
Thanks for raising the query. 

- The repository URL that we provided and existing URL both will land on the same page. You might have went for disconnect and connect to the external git in this case, once the disconnection happens it will take sometime to delete the repository. Then the repository can be connected.
- It seems that the previous version of CC is v5.1. Please follow the migration guide to upgrade to the latest version if not done already.

**Comment by casticod2** [comment]
Ok, we have decided to update to version 5.5, but it will take us several days. You can close the ticket, thanking you for your information.

**Comment by gsv022** [comment]
Thank you for the update.
