### ISSUE TITLE
Upgrading from 4 to 5 - Advice

### ISSUE THREAD

**Issue by normansolutions** [OfficeDev/microsoft-teams-apps-company-communicator#1237]
Hello

I hope this is the right forum for my query. We are currently using version 4 of 
microsoft-teams-apps-company-communicator on a large-scale site and are considering an upgrade to version 5. However, due to the complexity of the system, we are unable to fully simulate this in a test environment. I was hoping someone could provide some insights into the following questions:

- Are there any significant issues that we should be aware of when upgrading from version 4 to version 5?
- Is it feasible to run two versions of the product _concurrently_ within a single Azure Tenant?
- Has anyone encountered any problems with the latest version functioning in “New Teams”?

Any advice would be greatly appreciated. Thank you.

**Comment by gsv022** [comment]
Hi @normansolutions ,
Thanks for raising the query. We recommend you to follow the migration guide. 

- _Are there any significant issues that we should be aware of when upgrading from version 4 to version 5?_
Here are the few cautions need to be taken care.
1. Base Resource name keep it same which used in v4.
2. Please make sure secrets are updated(if they are nearing to expiry)
3. Graph App registration- supported account type is set to my organization only
We recommend you to follow the migration guide. Please follow the steps and we will be assisting you in case of any issue occurred. 


- _Is it feasible to run two versions of the product concurrently within a single Azure Tenant?_
    Yes, it is fine to run two different versions of CC on same tenant. 
- _Has anyone encountered any problems with the latest version functioning in “New Teams”?_
We have checked that latest version of CC is working on new Teams.

**Comment by normansolutions** [comment]
Thanks so much @gsv022 - much appreciated 👍
