### ISSUE TITLE
Unable to add external git to web app/app service

### ISSUE THREAD

**Issue by LycheeYum** [OfficeDev/microsoft-teams-apps-company-communicator#1238]
The external git of the web service was pointing to the wring url.  When I try to change it, I get the error.  "Cannot find SourceControlToken with name GitHub"

<img width="998" alt="Screenshot 2023-11-29 005002" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/7239280/e4bca2d5-2a7e-42b3-a632-c855232252ee">

The github url is working for all the functions, only the app service has this issue.

**Comment by gsv022** [comment]
Hi @LycheeYum <
Thanks for raising the query. Soon after disconnecting the repository, it takes sometime to delete the existing repository. Then connect again. It will work.

**Comment by LycheeYum** [comment]
@gsv022 You're right, it worked after I waited a few hours.

One last question.  How long after I hit the sync button for the web app will the redeployment usually take?

**Comment by LycheeYum** [comment]
The deployment ran but failed here is the log.  Should I point at the main branch or the 5.5 branch?


Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.416

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.4.1
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

npm notice 
npm notice New major version of npm available! 8.19.2 -> 10.2.4
changed 250 packages in 9m
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>

npm notice Run `npm install -g npm@10.2.4` to update!
247 packages are looking for funding
npm notice 
  run `npm fund` for details
Building the client app (this can take several minutes)

> company-communicator@5.4.1 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Failed to compile.

TS7006: Parameter 'c' implicitly has an 'any' type.
    207 |     setAllUsersState(false);
    208 |     if (teams && teams.length > 0) {
  > 209 |       const teamsSelected = teams.filter((c) => messageState.teams.some((s) => s === c.id));
        |                                           ^
    210 |       setTeamsSelectedOptions(teamsSelected || []);
    211 |       const roastersSelected = teams.filter((c) => messageState.rosters.some((s) => s === c.id));
    212 |       setRostersSelectedOptions(roastersSelected || []);


Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock.json file was created with an old version of npm,\r\nnpm WARN old lockfile so supplemental metadata must be fetched from the registry.\r\nnpm WARN old lockfile \r\nnpm WARN old lockfile This is a one-time fix-up, please be patient...\r\nnpm WARN old lockfile \r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.4.1\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.\r\nnpm notice \r\nnpm notice New major version of npm available! 8.19.2 -> 10.2.4\r\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>\r\nnpm notice Run `npm install -g npm@10.2.4` to update!\r\nnpm notice \r\nBrowserslist: caniuse-lite is outdated. Please run:\r\n  npx update-browserslist-db@latest\r\n  Why you should do it regularly: https://github.com/browserslist/update-db#readme\r\nBrowserslist: caniuse-lite is outdated. Please run:\r\n  npx update-browserslist-db@latest\r\n  Why you should do it regularly: https://github.com/browserslist/update-db#readme\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.51108.6494\bin\Scripts\starter.cmd deploy.cmd

**Comment by LycheeYum** [comment]
More info: I've confirmed that the function apps are pointing to runtime version- ~4 and app service to .Net 6.

**Comment by LycheeYum** [comment]
Update Disconnected/Reconnectred external git and now the deployment was successful.  

However, now it appears that the app is still on on 5.4.1 instead of 5.5.  Parameters like the 'AuthorizedDeleteUpns' are not under configuration/application settings

**Comment by gsv022** [comment]
Hi @LycheeYum ,
As per the migration guide, please add the parameters required for v5.5 explicitly within the configuration section of app service. Here is the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-)

**Comment by LycheeYum** [comment]
I've confirmed that the function apps are pointing to runtime version- ~4 and app service to .Net 6.  I think it just need a few hours to sync the right commit.

It's all working now.
