### ISSUE TITLE
App(v 5.4.1) not working on both "Web browser" and on "New Teams", but it works on desktop app when using "Old Teams"

### ISSUE THREAD

**Issue by AonicSS** [OfficeDev/microsoft-teams-apps-company-communicator#1239]
Hi, It seems the app (v 5.4.1) does not work at all on the browser, no matter if using the "Old Teams" or "New teams" and it only works on "Old Teams" when using the desktop app.

I have seen that the issue has been fixed but it means changing to version 5.5 which we do not want to do at this moment since it has some additional features that we do not require. Can this issue be fixed without upgrading to version 5.5?

<img width="685" alt="Screenshot 2023-11-29 153354" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/92783480/9e4933b7-0830-4a58-9f00-787b1a49aa31">
<img width="954" alt="Screenshot 2023-11-29 153447" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/92783480/baaef96f-959d-4c92-835d-4f21d8fdfd99">

**Comment by AonicSS** [comment]
Is there no way to make it work without updating to the new version? We really don't want to upgrade to a new version since we have made some modifications to the app. Will there be another branch where this issue will be fixed for earlier versions? If not, then could you point me to the direction as to why version 5.4 does not work on "New Teams" and on the web browers and how this has been fixed on the new version?

**Comment by isracp3** [comment]
Hola, buen día.

Levante un caso con Microsoft TrackingID#2311220040007768
Me apoyo Ericka De la Paz Chaves, me comento que levantara un reporte aquí para saber cuándo se liberara la versión de Company Communicator con la nueva versión de Teams.

Me apoyarían con lo solicitado por favor.

Quedo atento a sus comentarios.

Cordial Saludo.
