### ISSUE TITLE
Microsoft Company Communicator Application: HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by mccjayme** [OfficeDev/microsoft-teams-apps-company-communicator#1241]
Our Microsoft Teams Client or Web Client when access the Company Communicator Application via MS Teams Channel we've set up where we send out Communications Company Wide is now presenting the following Error:

HTTP Error 500.30 - ANCM In-Process Start Failure

Screen Shot -  
![43ec38d6-9752-4adc-a5d3-fdf0c381b7a2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/97609953/08625742-098d-42ee-a3f0-f165b7cddf08)

When I click on -> For more information visit: https://learn.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-8.0

Per the App Error 500.30 In-Process Startup Failure 

I'm working with Tier 2 Microsoft Support and do not know of any Vault Information from Azure? We're wanting to see if GitHub Team has any reports of this or can guide on where the Vault Information is located in Azure or advisement...

‎Microsoft Case Number: ‎2311280040008893‎

Jayme McClendon 
Principal – Unified Communications Architect 
SUTHERLAND GLOBAL
Single Number Reach: +1 585-450-4476
E: [Jayme.McClendon@sutherlandglobal.com](mailto:Jayme.McClendon@sutherlandglobal.com)

CST – Central Standard Time - (GMT-6)

**Comment by gsv022** [comment]
Hi @mccjayme ,
Just a follow up here. Could you please let us know the status.

**Comment by mccjayme** [comment]
Hi Sai Venkat,

As of this week - Week 50 December 11th - 15th, 2023 - We Sutherland Global are meeting with your Microsoft Account Team to look at an alternate option to Company Communicator called Viva Amplify while our Product Owner who is looking to update our Version of our Company Communicator to to the newest per your advisement. 

You can close our Case #1241 out till further notice. Thanks
