### ISSUE TITLE
Deploy failed with"There was a conflict. Conflict with existing ScmType: ExternalGit"

### ISSUE THREAD

**Issue by reterfreeman** [OfficeDev/microsoft-teams-apps-company-communicator#1245]
Hi, I deploy CC 5.5 in another tenant, but it was failed, I found the closed issue#1078, follow the way (disconnect and reconnect, wait for Log show up: success(Active), and redeploy again, but it still fail with There was a conflict. Conflict with existing ScmType: ExternalGit
![image](https://user-images.githubusercontent.com/151904936/287186316-b8d7f07c-331f-49da-8856-b76968263075.png)
I go back Deployment Center and External Git show up "Error fetching information", however I disconnect and connect again, redeploy always failed with "There was a conflict. Conflict with existing ScmType: ExternalGit"
![image](https://user-images.githubusercontent.com/151904936/287186863-7bd980f9-0813-4877-be75-daa1d4afa4d0.png)
I am sure not any underscore (_) or space in any of the field values, include subscription & resource group.
![image](https://user-images.githubusercontent.com/151904936/287189672-92eda4d9-53d8-4493-8e3a-06f1795eeff9.png)
![image](https://user-images.githubusercontent.com/151904936/287189692-c968323f-854a-4072-8530-7354d3965267.png)
![image](https://user-images.githubusercontent.com/151904936/287189729-a40dc29d-2182-403c-81d3-73210a568d06.png)

**Comment by reterfreeman** [comment]
@gsv022 It's working, and deployed success. thanks for your support.

**Comment by gsv022** [comment]
Hi @reterfreeman ,
Thanks for the update. Please feel free to log a issue if anything comes up w.r.t standard version of CC
