### ISSUE TITLE
Publish error!

### ISSUE THREAD

**Issue by mavistangtpl** [OfficeDev/microsoft-teams-apps-company-communicator#1246]
When I publish my CC APP, got error below:

<img width="779" alt="Screenshot 2023-12-01 182359" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/53459c72-d4b4-402b-be3e-cfa9786eaf30">

I try to run "npm install" / "npm run build", there are same problems.

**Comment by gsv022** [comment]
Hi @mavistangtpl,
Thanks for raising the query. Could you kindly share the origin or repository link of the code snippet?

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl, Thanks for raising the query. Could you kindly share the origin or repository link of the code snippet?

<img width="421" alt="Screenshot 2023-12-04 124345" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/96de41af-9c09-42ef-b289-dd6cfce3990e">

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Are you still facing the issue? Please confirm
