### ISSUE TITLE
Issue is back

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1247]
Hi, 

I am having the same issue again, when searching distribution groups I don't see any options? Are you able to help?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thanks for raising the query. 

- Could you please provide the screenshot of the issue. 
- Please share the application insight logs. Please filter the time at which issue started showing up. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/eb77a86c-d517-4ecd-a2ae-fcc6d4b1dee0)

**Comment by ahlim0011** [comment]
![Screenshot](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/cbedd4c0-96e9-4960-8127-bccba1bb1d4d)
Please see attached screen, the issue is when I want to send a message and search any email groups no searches display.

**Comment by ahlim0011** [comment]
![new](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/7da01b1b-51d2-451f-97f9-799bba2b3a89)
Please see attached also not sure if this helps?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
The error says that secret ID is copied instead of secret Value. Please perform the procedure as discussed over the call. Here is the [reference](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1208).

**Comment by ahlim0011** [comment]
But we did all of them on the call? Which one did I miss

ABDUL HALIM
IT Support Administrator
***@***.***
+44 20 7665 5009 direct
12 Gough Square
​London ​EC4A 3DW
+44 20 7665 5000
hausfeld.com
This email is confidential and may be legally privileged. If you have received it in error, please contact me immediately. Hausfeld & Co. LLP is a limited liability partnership registered in the State of New York and is authorised and regulated by the Solicitors Regulation Authority ('SRA') in England & Wales with number 513826. 
________________________________

**Comment by gsv022** [comment]
@ahlim0011 , The same instance we checked the functionality over the call after correcting the secrets. It was working fine right! 
And how about other sending options?

**Comment by ahlim0011** [comment]
correct and now no options are working 🙁 maybe we can have a 15mins call and we can just check all of them?

ABDUL HALIM
IT Support Administrator
***@***.***
+44 20 7665 5009 direct
12 Gough Square
​London ​EC4A 3DW
+44 20 7665 5000
hausfeld.com
This email is confidential and may be legally privileged. If you have received it in error, please contact me immediately. Hausfeld & Co. LLP is a limited liability partnership registered in the State of New York and is authorised and regulated by the Solicitors Regulation Authority ('SRA') in England & Wales with number 513826. 
________________________________

**Comment by gsv022** [comment]
We will reach out to you internally.
