### ISSUE TITLE
Communicator sent messages stuck

### ISSUE THREAD

**Issue by rafi4242** [OfficeDev/microsoft-teams-apps-company-communicator#1249]
Hi,

After successfully installing the app via the automatic powershell script, I try to send messages to team user's chat or to teams general channel (or to all users), and they are stuck in sent messages:

It's like this for several days. I tried restarting the web app service but didn't work.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/f18612e3-44d0-45ae-91cf-49b4659ca355)

**Comment by gsv022** [comment]
Hi @rafi4242 ,
Thanks for raising the query. 

-  Could you please share the deployment status of app service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5f09116e-4605-4d29-84cc-c6e690fb13d5)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8fad1fcd-30a4-4658-bc32-1c9fd333a45c)

- Please share the application insight logs. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/eb77a86c-d517-4ecd-a2ae-fcc6d4b1dee0)

**Comment by rafi4242** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/82702c0a-7f3c-402a-a265-75922eaf70aa)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/e7b518a1-ed14-464e-8e01-d1da420167a8)


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/96187050/1285c867-061b-49f5-93f7-b1945d223a9d)

**Comment by gsv022** [comment]
Hi @rafi4242 
Please cross verify the secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by rafi4242** [comment]
Hi, thanks for your reply. Due to too many issues while installing Company Communicator with the automatic PS script, and the fact that this app is not under Microsoft Official support, we decided not to use it. 
We are a big company and giving our internal communications dept. this app which one day it might break and we'll be dependent on github is problematic. Though there is fast and useful replies here.
Thank you anyway for your help.
