### ISSUE TITLE
Manual steps for dotnet6 migration in migration guide

### ISSUE THREAD

**Issue by EMEAWebEnvironmentsTeam** [OfficeDev/microsoft-teams-apps-company-communicator#1250]
Hi all,

We are a bit stuck when trying to run the dotnet6 migration powershell script in the migration guide (we are migrating from 5.3 to latest). This is due to global policy settings in our company which we are unable to change.

Would there be any alternative to running this powershell script, say manual steps in the Azure portal?

Appreciate any help with this one.

**Comment by gsv022** [comment]
Hi @EMEAWebEnvironmentsTeam ,
Thanks for raising the query. Please follow the below steps

- Go to Azure portal
- Open the resource group where deployment has been done
- Click  data-function from the three function apps
- Open Azure CLI within the function app
- Then run the below command
`az functionapp config set --net-framework-version v6.0 -n <baseresourcename>-data-function -g <resourcegroupname>`
- Go to configuration. Change the function runtime version to **~4**. Here is the reference
<img width="435" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9f76dafe-8502-492c-ba97-0d989923bcde">

- Please repeat the above steps for other two function apps
`az functionapp config set --net-framework-version v6.0 -n <baseresourcename>-function -g <resourcegroupname>`
`az functionapp config set --net-framework-version v6.0 -n <baseresourcename>-prep-function -g <resourcegroupname>`

- For further steps, please follow migration guide.
