### ISSUE TITLE
Message sending result: Failure

### ISSUE THREAD

**Issue by JakAug** [OfficeDev/microsoft-teams-apps-company-communicator#1251]
Hello!

We have successfully deployed the app using powershell script, unfortunately we are not able to send any message.
We have a team that have Author app added. We have another team with users where the users app is added.
Once we send any message there is a count of failure (the numbers reflects the number of users team member)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152910332/6e8b7fe6-f734-47c3-afbc-0b2cb8e6ee6f)

Some logs from Application Insights:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152910332/c4314e66-8933-4d67-9373-bbfa94da96bc)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152910332/27f115fa-d454-4a6e-8ca6-5d5e1c5253a8)

Worth to mention: 
When we choose how do we want to send message, only the last option (send in chat to members of the following M365 groups) is able to do the group lookup. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152910332/4be6827f-484a-46ee-999a-a0d18e9cf786)

The first and second one is not able to find any results.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152910332/b1672b7b-52bd-458c-bede-cdb8d47cb42e)

Thanks in advance for your reply!

**Comment by gsv022** [comment]
Hi @JakAug ,
Thanks for raising the query. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue
