### ISSUE TITLE
M365 groups does not list when selecting the drop down

### ISSUE THREAD

**Issue by Axael85** [OfficeDev/microsoft-teams-apps-company-communicator#1253]
Hello Team,
we are having Company communicator V5.5 with all settings in place, when we are trying to send message to specific Security group or M365 group it doesn't show any of them. Not even when writting down the name of the group.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/9005db0e-e74f-438b-814c-924db8382c23)

We have reviewed permissions , security keys. What else can be do?

**Comment by v-jaygupta** [comment]
Hello @Axael85 ,

Thanks for reaching out to us!
Please try to search the name of the secuirty group without giving any spaces and it will load suggestions as per your search.

**Comment by gsv022** [comment]
Hi @Axael85 ,

- _do we need to install first the User application for the "users that are into the security group"? If yes, how do we install for specific security group?_
Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue. 
-------------------------------------------------------------------------------
Please cross verify the secrets. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by gsv022** [comment]
Hi @Axael85 ,
For the 4th sending option, the user app should be available at the tenant level. Upon selecting a security group, CC will verify the presence of the user application within the tenant. Subsequently, it will install the user application for all members of the specified security group, facilitating the seamless delivery of the intended message.

**Comment by Axael85** [comment]
Hello @gsv022 ,

Thanks for clarification, I was trying to find which is the user expierence once the User application is installed through Teams. Do you have some info?

REgards

**Comment by gsv022** [comment]
Hi @Axael85 ,
Thanks for the patience. There are four sending options
- Send to the General channel of specific teams:  To make the this option work, user app has to be added to the specific team(s). This will post the message in the general channel of the teams. Below is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a926d1b4-469f-4170-b14c-7c08cc8416e2)

- Send in chat to members of the following teams: To make this option work, user app has to be added to the specific team(s). The members in the team will receive the message individually(one-one). 
- Send in chat to everyone: To make this option work, user app should be present at the tenant level/organization level. 

- Send in chat to members of the following M365 groups, Distribution groups or Security groups:
To make this option work, user app should be present at the tenant level/organization level.  The members of the distribution group will receive the message individually(one-one). 

**Proactive installation**: During the custom deployment process, if one has set the proactive installation as true then the users in the tenant gets the app installed automatically. If false, user must install it manually.  
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/bb69ebd2-150f-48f6-b308-dec00fd19213)


Please let us know if you have any queries on user application.

**Comment by Axael85** [comment]
Hello @gsv022 ,
Just wanted to retake and open this case due the issue still happen, we are not able to use the step 4 even if the application is already installed for all users. 
Is there any other API permissions required for the USer app to work? We currently having these ones:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/03ba45ba-0448-410d-a659-c51af8ec8b14)
