### ISSUE TITLE
How to export old, posted messages in Company Communicator v3

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1254]
Hi @gsv022 

We have the old company communicator version 3 in production that will decommission soon as a fresh new dedicated installation (NOT an upgrade from v3) of Company Communicator v5.5 instance will be scheduled next Thursday 14th on the production tenant.

My question is if the end-users want to have back up copy/export of all the old messages in company communicator version 3, before the messages gets deleted to be replaced with the new data storage in v5, **what is the best approach to export all the messages as CSV/ZIP format in the current version 3**?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/9847d9ea-4d42-4d05-a40c-df8d05899a39)

Thanks and look forward to your reply this week before next week.

kind regards
David

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thanks for the patience.

- Could you please let us know the reason for taking back up of old(v3) instance.

**Comment by David-Liong** [comment]
Hi @gsv022 
The reason is because the organisation has a retention policy to keep archive data for certain period of time.
So they like to align the policy with the company communicator app, which is why I have raise this request, to verify if there is an easy way to backup sent messages and exported it out to file .e.g csv, etc..

**Comment by gsv022** [comment]
Hi @David-Liong ,
We would recommend to go with downloading the sent messages in CSV format only.
