### ISSUE TITLE
Is there a character length limit to the AuthorizedCreatorUpns configuration settings in CC v5.5

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1255]
Hi,

Is there a limitation on the total character length that you enter in the configuration box for the **authorizedcreatorupns** for company communicator v5.5? 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/f64e3a5e-7f11-4270-8e19-9ed902f83ea0)

If there is total number of character length limitation on the value box this will limit how many users will have access to the author app.

I am asking this question because we are planning to have at least going to have up to 20 or more email addresses being entered in the authorizedcreatorupns config field, who will have access to post messages via the Author app in Teams.

Thanks and hear from the team soon.

Kind regards
David

**Comment by v-jaygupta** [comment]
Hi @David-Liong ,
Thanks for raising the query. We will check on this and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @David-Liong ,
There is no restriction at the code level. AuthorizedSenderUPN can accommodate good number of UPN's. Please let us know if you are facing any issue in adding more UPN's
