### ISSUE TITLE
Will the secret password for bus, application insight and storage account that are stored in the CC v5.5 vault be expired?

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1256]
Hi,

I have installed a new instance of Company Communicator v5.5 and aware that author, graph and user app's client secrets stored in the dedicated company communicator key vault will expired in 24 months later from its respective app registration. Which means the vault and the configuration settings will need to be manually updated when its secrets expires.

**My question for concern is do you know if the bus, application insight and storage account secrets that are stored in the CCv5 key vault will ever get expired in 12-24 months in the system as well?**

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71060262/af6798f7-7cad-4f18-97e2-7bdb169a4fc6)

If the answer is yes, please provide Wiki updated link or put instruction in this ticket on where and how to renew secrets for the bus, application insight and storage account in the CCv5 key vault.

Thanks
Kind regards 
David

**Comment by v-jaygupta** [comment]
Hi @David-Liong ,
Thanks for raising the query. We will check on this and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thanks for the patience. The highlighted parameters won't get expired.

**Comment by David-Liong** [comment]
Great you can now close this ticket @gsv022
