### ISSUE TITLE
supporting security group or DL for AuthorisedCreatorUPN andAuthorisedDeleteUPN

### ISSUE THREAD

**Issue by sponlinedev** [OfficeDev/microsoft-teams-apps-company-communicator#1257]
Please consider the inclusion of a feature request to provide support for security groups or distribution lists (DL) in order to manage the Authorized Creator UPN and Authorized Delete UPN. This enhancement will help facilitate easy management, particularly in scenarios where there are frequent changes to authors.

**Comment by v-jaygupta** [comment]
Hi @sponlinedev ,

Thanks for highlighting the requirement.
We will consider this as an enhancement & add it to the backlog and depending on the priority we will be taking up in future releases post the discussion with the internal team.

Thank you.
