### ISSUE TITLE
Formatted Text not showing

### ISSUE THREAD

**Issue by JasGo00** [OfficeDev/microsoft-teams-apps-company-communicator#1259]
I noticed one thing worth improving in the SendApp. 
When adding an unordered list, the text below is always displayed just below the list. I tried adding some blank lines between the list and the last sentence of the message, but unfortunately it didn’t work.
So, trying to find a solution, I discovered that there was an option to add a line between, it was displayed in the preview option of the editor:
 
 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/b5d81482-c7d1-4c7e-b442-9a04d972a9a7)

**Comment by gsv022** [comment]
Hi @JasGo00 ,
Thank you for the patience.

- Here is the [link](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html) for text formats supported in CC application.
