### ISSUE TITLE
Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request.

### ISSUE THREAD

**Issue by sudheeshrajan1** [OfficeDev/microsoft-teams-apps-company-communicator#1261]
We have recently renewed the certificates and secrets on the communicator app since then not able to send any messages. I am getting an error "Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request."

Can you please help on this.

Thanks,

Sudheesh Rajan

**Comment by gsv022** [comment]
Hi @sudheeshrajan1 ,
Thanks for raising the query. Hope you are on latest version. Please cross verify once again w.r.t secrets renewal with the below steps.
- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.
<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">
- If the secrets are not visible, Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
<img width="359" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/eec3cc6d-1455-477f-8918-dd44eb5b2290">

- Grab the new  secret identifier 
<img width="516" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/046b83b5-e8b6-42f4-a4e6-8184cb8d9584">

- Paste it in the configuration sections of  app service, 3-function apps. Here is the reference of updating the author app password in app service configuration. 
<img width="779" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d9444a9a-fe5b-4d09-8f96-53b70ab40121">

-  Follow the same procedure for the user app password and graph app password updating.

- For graph app, please dont forget to  update the password in **AzureAd Client Secret** as well. here is the reference
<img width="574" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/287f2d3b-52a7-41bf-852e-541de7ccf02a">
