### ISSUE TITLE
Take action to stop domain fronting on your application before 8 January 2024

### ISSUE THREAD

**Issue by SynHam** [OfficeDev/microsoft-teams-apps-company-communicator#1264]
Hello,

Has it been confirmed this won't be an issue with CC?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/127293724/b59751a1-3c42-49ed-bf3b-e6d71723dfc2)

Thanks

**Comment by gsv022** [comment]
Hi @SynHam ,
Thanks for raising the query. We will check into it and get back back to you with proper response soon

**Comment by SynHam** [comment]
Hi, whilst we haven't noticed any issues, is there any update on this?
Thanks

**Comment by gsv022** [comment]
Hi @SynHam ,
Our CC application is working fine. We have tested for this impact and no issues found. Please let us know if you are facing any issues.

**Comment by SynHam** [comment]
> Hi @SynHam , Our CC application is working fine. We have tested for this impact and no issues found. Please let us know if you are facing any issues.

Hi, All good my side still.
