### ISSUE TITLE
Unable to deploy the company communicator app

### ISSUE THREAD

**Issue by lsborroto12** [OfficeDev/microsoft-teams-apps-company-communicator#1267]
"There was a conflict. Conflict with existing ScmType: ExternalGit"}]}"
![image (1)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/124916189/e2a632ce-7396-475e-b120-fa25ab20ec84)

**Comment by gsv022** [comment]
Hi @lsborroto12 ,
Thanks for raising the query. 
No need to go for re-deploy again.  Perform the below procedure.
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **function** from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.

**Comment by lsborroto** [comment]
I am adding the screen shoots
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/59449977/d070f4fa-3515-4ebb-b347-ba4f1066c4ab)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/59449977/727ca767-a979-41ec-a44f-4ff3b57b8dd6)

**Comment by lsborroto** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/59449977/112b7a61-67f6-492a-9ca0-c63d3013446b)

**Comment by lsborroto** [comment]
<img width="857" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/59449977/098c7b6c-1840-4601-b03c-c661a4cdeca1">
<img width="973" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/59449977/f4e40079-561a-42f0-aa22-1d708fc7f33b">
<img width="839" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/59449977/6624a946-847c-42c7-b02c-6e89d51dd9b2">
<img width="915" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/59449977/951ce53c-1702-48c0-a97b-213b589d7b5d">

**Comment by lsborroto** [comment]
HI. Any additional help here?

**Comment by gsv022** [comment]
Hi @lsborroto ,
Thanks for the patience. Please connect to the main branch for data function and app service(web app)  as well. Once the status shows successful in logs section. Then proceed with remaining steps of deployment.
