### ISSUE TITLE
communicator function app failures - 3

### ISSUE THREAD

**Issue by larrysteele** [OfficeDev/microsoft-teams-apps-company-communicator#1269]
Function app failures after deploying latest version from main on all 3 function apps:

data-function
function
pre-function

Functions runtime error
Microsoft.Azure.WebJobs.Script: Error building configuration in an external startup class. Microsoft.Azure.WebJobs.Script: One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later. .
Wednesday, December 13, 12:30:41 PM
AZFD0005
Error building configuration in an external startup class.
Learn more
Wednesday, December 13, 12:27:12 PM
80

**Comment by gsv022** [comment]
Hi @larrysteele ,
Thanks for raising the query. Could you please confirm on the below points

- Please share the runtime version of function app. Here is the reference.
<img width="412" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62a9df44-c077-4e86-957a-01bdcb16edac">


- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5f09116e-4605-4d29-84cc-c6e690fb13d5)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8fad1fcd-30a4-4658-bc32-1c9fd333a45c)
