### ISSUE TITLE
Support for new Teams 2.0 client?

### ISSUE THREAD

**Issue by bolsoncdn** [OfficeDev/microsoft-teams-apps-company-communicator#1270]
We have been using Company Communicator for several years using the classic Teams client but have started moving our users to the Teams 2.0 client which will become Microsoft's default over the next few months.  

Users are still receiving messages when using the new 2.0 client, but authors are unable to load the sending app from the new client.

The app looks like it's loading initially and the drafts and sent sections are visible for a second, but that is quickly replaced by a "sorry, an error occurred while trying to access this service" error. 

This is affecting all authors.  They all are able to toggle back to the classic client and can still send messages normally there, so it's just when using the new client that this error occurs.

![CompanyCommunicator_error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/99512707/3a2efda7-f6df-4fc9-89f7-eb8d62e8ef9d)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/99512707/e3f91d0c-e99b-45fc-abcb-e0aa3272d7cb)

**Comment by gsv022** [comment]
Hi @bolsoncdn ,
Thanks for raising the query. Could you please confirm on the below points.

- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5f09116e-4605-4d29-84cc-c6e690fb13d5)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8fad1fcd-30a4-4658-bc32-1c9fd333a45c)

**Comment by bolsoncdn** [comment]
We are still running an older version that's been working fine for us to date, so we haven't upgrade to the latest release yet.  We're trying to determine if doing that upgrade would allow our authors to access the send app when using the new Teams client.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/99512707/2a5dd063-11d2-443d-b81b-b3eda16fcd37)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/99512707/4c3c0c4c-c440-4d63-8bdc-8baea3dd7d37)

**Comment by gsv022** [comment]
Hi @bolsoncdn ,
Thanks for the patience. Yes, we recommend you to go to the newer version of CC-v5.5. It works fine on new version of teams. Here is the migration guide [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide)
