### ISSUE TITLE
Page not found Company Communicator Authors

### ISSUE THREAD

**Issue by marcelojrm** [OfficeDev/microsoft-teams-apps-company-communicator#1273]
We are no longer able to open the Author of the company communicator. Displays this error when opening the application:

"portal.azure.com decided to receive call"

"page not existing https://cteams.azurefd.net/configtab"

Note: cteams is the name of our resource

**Comment by gsv022** [comment]
Hi @marcelojrm ,
Thanks for raising the query. Please confirm on the below points.

- Is this issue happening when trying to add the author app to a specific team?
- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5f09116e-4605-4d29-84cc-c6e690fb13d5)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8fad1fcd-30a4-4658-bc32-1c9fd333a45c)

**Comment by marcelojrm** [comment]
Deployment Center:
![Deployment Center cteams - Company communicator](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/108140854/cf799752-dcfc-4499-b69f-55230ce83f02)

The error in question appears when adding to any team, and the team it was working on has stopped loading.

**Comment by gsv022** [comment]
Hi @marcelojrm ,
Please share the logs section screenshot as well. Reference screenshot has already been shared above.

**Comment by marcelojrm** [comment]
Hi @gsv022, subscription Azure 1 it had expired, everything indicates that this is it, thank you for your help. (Translate)

**Comment by marcelojrm** [comment]
Hi @gsv022, subscription Azure 1 it had expired, everything indicates that this is it, thank you for your help. (Translate)
