### ISSUE TITLE
What's the impact of latest CC with Microsoft depreciating Application Insight in Feb 20024

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#1275]
Dear team,

Microsoft has announced in https://azure.microsoft.com/en-au/updates/we-re-retiring-classic-application-insights-on-29-february-2024/ that they are going to retire application insight in **Feb 2024**

So how will this have an impact on the existing Company Communicator v5.5 that I have installed for the organisation in the production tenant which uses application insight?

- Will you be updating the GitHub repo code to accommodate replacing application insight to use another alternative service and when?
- Will I need to click the sync button later on for this patch update?

Thanks.

**Comment by gsv022** [comment]
Hi @David-Liong ,
Thanks for bringing the information of application insights to our notice. We will be taking necessary steps. We will keep you posted.

**Comment by SynHam** [comment]
HI, is there any update on this potential impact?

**Comment by gsv022** [comment]
Hi @David-Liong ,
We are taking care of moving app insights from classic to workspace. Soon, it will be pushed as a part of next release.
