### ISSUE TITLE
Updating versions

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1276]
Hi,

Can I please find out how to update versions and where I need to start? I have just started on version one. 

Thanks,

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thanks for raising the query. Currently, we are supporting the migration from v3.x-->v4.x and v4.x to v5.x and to latest. We have relevant migration guides present in the wiki section already. Here is the [v4-migration-link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide) and [v5-migration-link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide). The versions prior to the v3.x are not supported

**Comment by ahlim0011** [comment]
![new 1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/09828712-af55-496f-a35b-faeb129ccfff)
![New](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150195103/57e63b5f-f58a-4b57-b55b-297556b6cb09)

As discussed please find attached.

**Comment by gsv022** [comment]
@ahlim0011 , There is no need for updating as the deployed version is of latest type.
