### ISSUE TITLE
.NET 6.0 upgrade shows Functions runtime error

### ISSUE THREAD

**Issue by StevieBleeds** [OfficeDev/microsoft-teams-apps-company-communicator#1282]
I've been trying to upgrade our version of the app to .NET 6.0 as per the instructions, but upon restarting the functions, I'm seeing a runtime error across all three. Whilst the error is ambiguous, I was able to see the error **AZFD0005: External startup exception** on one function.

![func_error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39305886/683d0605-09e1-47de-815d-bae273b6df0b)

**Comment by gsv022** [comment]
Hi @StevieBleeds ,
Thanks for raising the query. Could you please confirm on the below points.

Thanks for raising the query. Could you please confirm on the below points

- Please share the runtime version of function app. Here is the reference.
<img width="412" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62a9df44-c077-4e86-957a-01bdcb16edac">


- For this error-_AZFD0005: External startup exception_, please disconnect and connect to repository once again. The reason might be the code has not got pulled properly.

**Comment by StevieBleeds** [comment]
Thanks @gsv022.

I have disconnected the repository as instructed, reconnected it and that seems to have worked.

![curr_success](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39305886/2ec1a140-bdcb-47a3-8997-257587a0b095)

However, the Azure Functions are still throwing a Runtime error, but are set up for Runtime version ~4

![curr_runtime](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39305886/f1e07b62-6877-4ae6-b009-51ede8dcd7c6)

![curr_error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39305886/49a6841a-b55f-4bf7-a16a-2a699da93b10)

**Comment by cifofs** [comment]
Hello everyone...  I have the same issue...

**Comment by gsv022** [comment]
@StevieBleeds , Please let us know if you have queries otherwise we can make it to closure.

**Comment by StevieBleeds** [comment]
> @StevieBleeds , Please let us know if you have queries otherwise we can make it to closure.

How do I resolve the issue with the Functions?

**Comment by gsv022** [comment]
Hi @StevieBleeds ,
Try disconnecting and connecting the function app once again. If it fails, please share your mail id so that we can discuss the issue internally.

**Comment by StevieBleeds** [comment]
Thanks @gsv022 

Disconnected and reconnected the Functions as instructed, the Runtime version has now stopped showing error and is showing the following:
![err_2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39305886/59c4c5ee-b11d-43fb-9755-8e8fe6fc428d)

However, at the top of all three Functions, I'm seeing the following error:
![err_1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39305886/f00e2cc5-e120-49b2-ae2d-bb18b4014259)

**Comment by gsv022** [comment]
Please share your mail id(outlook id or teams id) so that we can discuss the issue internally.

**Comment by StevieBleeds** [comment]
> Please share your mail id(outlook id or teams id) so that we can discuss the issue internally.

Sure it's stevielovesbots@outlook.com, thanks again.

**Comment by gsv022** [comment]
@StevieBleeds , I have mailed you. Now, we can discuss the issue internally.

**Comment by StevieBleeds** [comment]
Confirmed working in our environment now. Issue was related to a local firewall rule.
