### ISSUE TITLE
Company Communicator (Author) cannot send message to the members M365, you need permissions. Ask to the admin for more information

### ISSUE THREAD

**Issue by binruis** [OfficeDev/microsoft-teams-apps-company-communicator#1283]
Two days ago the Communicator (Author) is showing us the following message when we are trying to send a message to M365 members: "You need permissions. Ask to the admin for more information". 

Yesterday we at least was able to modify the message, but since today we cannot even modify it.

Attaching error screenshots:

<img width="490" alt="CommunicatorFailed" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/9791ff8d-b62e-4b4b-9cd6-4e9f54e78eee">

<img width="232" alt="CommunicatorCantModifyMessage" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/fc284764-de14-4361-9fb6-a4107c673ef5">

![CommunicatorModifyMessage](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/5061468e-8d71-4ddf-a595-e713cb5197d5)

**Comment by gsv022** [comment]
Hi @binruis ,
Thanks for raising the query. Could you please cross-verify the configuration end-end once again. 

- Please share the screenshots showing [graph app authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) as per the deployment guide.

**Comment by binruis** [comment]
Hello @gsv022 ,
About the graph app, cannot provide you the screenshots, cause we are using the old version of Company Communicator, that only required two Applications (Author and Users). Nevertheless, when trying to watch the permissions that are configured in the Author Communicator, we found out that the app is missing.

![CommunicatorAuthorMiss](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/716382aa-8779-4301-80b1-e4bc9902677c)

**Comment by binruis** [comment]
In addition, we found that our Author secret was expired, but even after renewing it, the problem it still there, we cannot send any message to the group, when we have the enough permissions for it.

**Comment by gsv022** [comment]
Hi @binruis ,

- is author app present?
- Secret value is updated in all the places of app service and function app configuration sections

**Comment by binruis** [comment]
Yes, we have the Author App in Teams, we just updated the value in the app service, should we update it also in the functions apps? Which one's?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/4311790a-ebe2-4b4f-876f-f2857148b932)

**Comment by gsv022** [comment]
@binruis Yes, the secrets need to be updated in all the 3-function apps that you are showing.

**Comment by binruis** [comment]
After modifying all of them it showed again the Communicator Author App, but still the same problem, cannot send any message to members and asking for permissions, we checked the Author permissions, but it's okay

**Comment by binruis** [comment]
i checked the secrets and it's all correct, im sharing you my email so we can talk internally. 

email:  binrui.sun@vasscompany.com

**Comment by gsv022** [comment]
@binruis , We started the conversation internally.

**Comment by gsv022** [comment]
@binruis , Upon user confirmation, we are making the ticket to closure.
