### ISSUE TITLE
Company communicator is not working on Modern Microsoft teams

### ISSUE THREAD

**Issue by JamaliShoaib** [OfficeDev/microsoft-teams-apps-company-communicator#1284]
The Company Communicator Author is not working on Modern Microsoft Teams. When I switch back to the classic Teams version, the Communicator Author is working properly, showing the error message 'Sorry, an error occurred while trying to access this service.' I have attached a screenshot below.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/29330750/b2f85976-3e1c-4f89-85eb-33d1278390b9)

**Comment by gsv022** [comment]
Hi @JamaliShoaib ,
Thanks for  raising the query. Please confirm on the below points.

-  Could you please share the deployment status of app service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/5f09116e-4605-4d29-84cc-c6e690fb13d5)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8fad1fcd-30a4-4658-bc32-1c9fd333a45c)

- Please share the screenshot showing the working status of CC on older version of Teams

**Comment by JamaliShoaib** [comment]
Hello @gsv022 ,
Thank you for your reply. Please find below 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/29330750/25ccf5ff-1693-4a8c-8aa2-ff04c1910628)

**Comment by gsv022** [comment]
Hi @JamaliShoaib ,
Our support scope is very limited with the standard version as the area of code modification is not known to us for customized versions. We will not be able to provide much assistance on this issue as the deployed instance is a customized version. Please let us know if you have any issues with the standard version.

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

**Comment by JamaliShoaib** [comment]
Hi @gsv022 ,

I have a couple of queries that require your support. Can we migrate from customized versions to the standard version? What will be the impact, such as access level and data? The current version is working fine with MS Classic Teams, and will the Standard version support Modern Teams? Additionally, can we use the same applications (User app, Author App, Graph App) for deployments?

Thank you.
