### ISSUE TITLE
Company communicator deployment issue

### ISSUE THREAD

**Issue by ManasaMShastri** [OfficeDev/microsoft-teams-apps-company-communicator#1285]
We are trying to deploy Company communicator app but we are facing issue Kindly help on the same.

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
Thanks for raising the query. Please share the deployment logs and the screenshot showing the failed resources would be helpful. Here is the reference.
<img width="789" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/477c2538-460b-403b-84ff-e1da9fd2cbdf">
