### ISSUE TITLE
Cannot Access to server with FTPS connection to get the manifest 

### ISSUE THREAD

**Issue by binruis** [OfficeDev/microsoft-teams-apps-company-communicator#1286]
I'm trying to get the manifest file so i can modify the parameters and generate the two zips, one for Author and the other one for Users, but cannot access to server, it showing the error when i try it

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/7190f5bb-11e5-43ad-88fa-40a345a745ba)

**Comment by gsv022** [comment]
Hi @binruis ,
Thanks for raising the query. Could you please download the code from [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) and perform the procedure
