### ISSUE TITLE
Can't find groups

### ISSUE THREAD

**Issue by silva1512** [OfficeDev/microsoft-teams-apps-company-communicator#1287]
Hi,
As mentioned at the Issue #1274, I was able to update to version 5.5

Unfortunately, I can't find any groups to send the message, I attached a screenshot.
Can you help me?

![group-error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/b3a86c19-8b42-4b45-970b-bd5b54f3f6ec)
![group-error2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/d4c40d7a-33c9-4671-9b67-a23fd9be4767)

**Comment by gsv022** [comment]
Hi @silva1512 ,
Thanks for raising the query.

- For fourth sending option, please type the name of the team name without any spacings, it will give the details.

- This is for 1st and 2nd sending options. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue.

**Comment by silva1512** [comment]
Hi,

For fourth sending option, I tried what you recommended but no success, I'm attaching the screenshot.

For 1st and 2nd sending options, I tried what you recommended but no success, it shows an error, I'm attaching the screenshot.

I was able to identify an error when looking at app insights logs, i'm attaching the screenshots.
It says something about the secret being wrong, I already checked and it's there and it's matching what we have...
Anyways, I know that it might be where the problem is because I didn't understand 100% if there's anything more that I have to do with the secret, the explanation on the migration and deployment guide about the secret were difficult to understand since english isn't my first language, I don't know if I've done everything correctly. Can you help me?

![4th-option](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/41ad3e35-b4c0-4f60-9e5a-39e743cecc33)
![1st2nd-option](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/4eaf4f7a-41f5-41ab-9a6c-cd5e8f003c66)
![app-Insights](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/99144cdc-dbf9-403c-af54-c31b0b82915f)

**Comment by silva1512** [comment]
Hi @gsv022 ,
It seems like I was able to solve the invalid cliente secret issue.
But now, it appeared another issue and I don't know what do, can you help me?
I'm still unable to find any groups when trying to send a message.

![null-error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/ffb46528-a3bb-4ae9-b36d-1c9fe8f3f7cf)

**Comment by silva1512** [comment]
Hi @gsv022 ,
I'm not sure if  I was able to solve this issue where I can't find groups, but another error just appeared (it's the 4th time I solve an issue and another appear...)

I'm attaching the screenshot but it's showing "Failed to sync all users" and the message isn't being sent.
Can you help us? I took some time to read the issue #579 since it's the same issue that I'm having.
I'm attaching the screenshots showing that the secrets are successfully configured.

![imagem (8)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/523aa300-f96b-44d1-bc5f-32b8323e8d29)
![config-success](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/f18eb580-6c23-4d21-8dda-afee209e65c0)

**Comment by gsv022** [comment]
Hi @silva1512 ,
Please share your mail id(outlook id or teams id) so that we can discuss the issue internally.

**Comment by silva1512** [comment]
Here it is:  matheus.silva@innuvem.com

Verifying the config, I was able to see that the functions are showing Key Vault Reference errors.
(function, prep-function, data-function) They are all showing the same errors.

![function-keys](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154267052/f98fcdaf-634f-4fec-94c8-a18cf7282920)

**Comment by gsv022** [comment]
Hi @silva1512 , please follow the below procedure.
- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.
<img width="793" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/62fb1be1-0fa3-47d4-ad7e-5851e5fd45a7">

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
<img width="918" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b4e29cd5-2fe8-4b15-a0ce-08245346683f">
- If the secrets are not visible, Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
<img width="359" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/eec3cc6d-1455-477f-8918-dd44eb5b2290">

- Grab the new  secret identifier 
<img width="516" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/046b83b5-e8b6-42f4-a4e6-8184cb8d9584">

- Paste it in the configuration sections of  app service, 3-function apps. Here is the reference of updating the author app password in app service configuration. 
<img width="779" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d9444a9a-fe5b-4d09-8f96-53b70ab40121">

-  Follow the same procedure for the user app password and graph app password updating.

- For graph app, please dont forget to  update the password in **AzureAd Client Secret** as well. here is the reference
<img width="574" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/287f2d3b-52a7-41bf-852e-541de7ccf02a">

**Comment by silva1512** [comment]
Hi @gsv022 ,
I was able to solve the issue!
It turns out I had to update the secrets in the functions too, I did it only at the company communicator web app.

Thank you for your help! I wouldn't have done it without your support. 
Best Regards!
