### ISSUE TITLE
Restore Backups

### ISSUE THREAD

**Issue by gvelez83** [OfficeDev/microsoft-teams-apps-company-communicator#1288]
Solicito de su colaboración con el fin de poder identificar dentro del Storage Account creado por la plantilla de Company Communicator, donde son almacenadas las comunicaciones enviadas, dado que dentro de los contenedores que se encuentran data-funtion, funtion y prep-funtion, no se logra evidenciar de manera apropiada la carpeta donde son almancenadas las comunicaciones. 

Adjunto imágenes  de referencia, la solución lleva implementada aproximadamente 6 meses con un envío de 30 comunicaciones.
[Evidencias Backups Company.docx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13789537/Evidencias.Backups.Company.docx)

**Comment by gsv022** [comment]
Hi @gvelez83 ,
Thanks for raising the query. Please translate the same in English so that we would be able to help you out

**Comment by gvelez83** [comment]
again re post the peticion, regrads your help for this question

**Comment by gvelez83** [comment]
againt i repost the question in english, regrads your help with the question, about funtion of company comunicator

**Comment by gvelez83** [comment]
I request your collaboration in order to be able to identify within the Storage Account created by the Company Communicator template, where the sent communications are stored, given that within the containers that are data-function, function and prep-function, they are not manages to appropriately reveal the folder where the communications are stored.

I attach reference images, the solution has been implemented for approximately 6 months with a shipment of 30 communications.

**Comment by gsv022** [comment]
Hi @gvelez83 ,
We are considering this as a duplicate to #1292  and can continue the discussion there. Closing out the issue here.
