### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by joejony** [OfficeDev/microsoft-teams-apps-company-communicator#129]
After adding the application inside the Teams, the signing process keeps in loop. 
We successfully log in the application inside Teams, and in the end, the application requests a new sign-in.
This happens for the readers and for the authors.
![behavior-communicator](https://user-images.githubusercontent.com/19648959/67902672-7aebc680-fb48-11e9-82b0-f9b47893e781.jpg)

**Comment by NaterBeard** [comment]
JoeJony- I am experiencing the same issue only it only occurs with iOS devices, Android, desktop client & web all work fine. I opened up a ticket with MSFT and have not made any progress.

**Comment by rashmi-dixit** [comment]
Please check below options and try.

• Check if the app registration, Company Communicator deployment and instance of Teams are in the same tenant. If they are different, then at the time of providing parameters, in the custom template while deploying, the tenant id of teams instance needs to be provided.
image

To get the teams instance tenant id –
Go to any team -> click on three dots besides the team name -> click on ‘get link to team’ -> Copy the link -> Extract the ‘tenantId’ field from the copied link.

To change tenant id after deployment -
Go to ‘Configuration’ settings of App Service -> change the "AllowedTenants" & "Tenant id" field value to the one you copied and Save -> Restart the App service -> refresh the tab under Teams.

• In the app registrations check if the supported account types is multiple organizations.

**Comment by kahopkin** [comment]
Everything is correct in my deployment, yet I am stuck in the Sign in loop....any other suggestions?

**Comment by juna-gupta** [comment]
@kahopkin The tenant Id should match the tenant where you plan to use the Company Communicator application.

Example: You may have an Azure subscription in tenant **A**, and may want to deploy the application for tenant **B**. In this scenario, you should provide tenant **B's** ID. 

If you've already deployed, update the tenant Id in the configuration for all the resources.

Closing the issue, please re-open if you still face it.
