### ISSUE TITLE
Unable to upload the authors app under Teams "Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error"

### ISSUE THREAD

**Issue by sudheeshrajan1** [OfficeDev/microsoft-teams-apps-company-communicator#1290]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/153543509/9b8d9ad7-c1ef-42d7-bb0d-1526f1cb2150)

I am trying to upload the Authors app but keep on getting the error "Mgmt.AppCatalog.LOBApp.Upload.BadRequest.Error" . 
Attaching the files, Please help on this.
[Reminders_branded.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13818063/Reminders_branded.zip)

**Comment by gsv022** [comment]
Hi @sudheeshrajan1 ,
Thank you for raising the query. Please make sure that description-short is not exceeding 80 characters. Modify it and verify using validator again. Here is the [link](https://dev.teams.microsoft.com/appvalidation.html) for validation.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/2d95e93d-7177-4fb8-9f55-9c69052e307c)

**Comment by sudheeshrajan1** [comment]
Thanks that worked. Thanks for providing the validator that really helps in future.
