### ISSUE TITLE
Deployment keeps failing for Company Communicator

### ISSUE THREAD

**Issue by benhales** [OfficeDev/microsoft-teams-apps-company-communicator#1291]
We have tried to deploy Company Communicator the manual way and the powershell route. Both ways are failing. The web app portion is failing and I'll provide a .txt file of the error it has. The error we are seeing from the deployment side says: 
"There was a conflict. Conflict with existing ScmType: ExternalGit". We have tried to disconnect and re-connect the git repository and then re-sync but are still having issues. Any help would be appreciated. 

[Command deploy.cmd.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13823173/Command.deploy.cmd.txt)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/24461743/c2d490d7-6cba-4e2e-accb-2258edb02486)

**Comment by benhales** [comment]
I should notate. The Function Apps are all showing a Success(Active) Status. It's just the web app that is having issues.

**Comment by gsv022** [comment]
Hi @benhales ,
Thanks for raising the query.  It is noticed in the logs that the issue is- "_FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory_".  So please upgrade the app service plan to S2. And then try sync again.

**Comment by benhales** [comment]
Thanks for the response @gsv022. Scaling up to a S2 app service plan did the trick for us. It is now successfully connected. Thank you for the assistance.
