### ISSUE TITLE
respaldo

### ISSUE THREAD

**Issue by gvelez83** [OfficeDev/microsoft-teams-apps-company-communicator#1292]
I request your collaboration in order to be able to identify within the Storage Account created by the Company Communicator template, where the sent communications are stored, given that within the containers that are data-function, function and prep-function, they are not manages to appropriately reveal the folder where the communications are stored.

I attach reference images, the solution has been implemented for approximately 6 months with a shipment of 30 communications.

**Comment by gsv022** [comment]
Hi @gvelez83 ,
Thanks for raising the query. Please elaborate more with reference images.

**Comment by gvelez83** [comment]
> Hi @gvelez83 , Thanks for raising the query. Please elaborate more with reference images.

Hi, thanks for your help. I attach evidence of the blue storage account, where you can see some folders, but we know (and we need to know where) in which of these folders is the history of images sent via company communicator for the last 7 months

thanks for cooperating with this,

[Evidencias.Backups.Company.docx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/13878231/Evidencias.Backups.Company.docx)

**Comment by gsv022** [comment]
@gvelez83 , We will check and get back to you with proper response soon

**Comment by gvelez83** [comment]
We are very attentive to your support, I greatly appreciate your validation of how to access this history please.

**Comment by gsv022** [comment]
We are checking on it. Please give us sometime, we will get back to you shortly.

**Comment by gsv022** [comment]
Hi @gvelez83,
The history of images sent can be seen in images section present under blob containers of storage browser. To view each image, there is a need to generate SAS token and hit the Blob SAS URL in the browser.

- Go to Storage account
- Click Storage Browser
- Select images present under Blob Container.
<img width="917" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/1c44b83b-1eb4-408e-86cf-614d2bd9e848">

- Generate SAS Token for the selected image
<img width="562" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/286aeb10-64ba-4c95-adeb-b001310deb73">

- Copy the  Blob SAS URL and hit in the browser.
- It will get downloaded. Covert the file extension to required format(jpeg, png etc.,)
