### ISSUE TITLE
Change App Name After Publishing

### ISSUE THREAD

**Issue by ColinDPo** [OfficeDev/microsoft-teams-apps-company-communicator#1293]
Can you advise how we can change the name of the communicator user application after its been added to the Team app catalogue?  Id like to change the name people see when they receive the communications as a all user message from "Company Communicator"  to "A new specified name"

Is there a way I can change this when I don't have the original manifest files.

**Comment by gsv022** [comment]
Thanks for raising the query here. Please follow the below steps.
To update name of CC

- Login to Azure Portal with Global Admin Credentials (portal.azure.com)
- Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
-  Click on Azure Bot(user) --> under settings click bot profile-->Change display name as per the organizational need.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/98143492/213981428-e5af8e1e-8623-4731-b413-8cc62cc3c475.png">

- And update the names in the manifest files for user. Re-upload the manifest file again. Here is the place for reference.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/98143492/213983428-68678fb4-03ae-4a95-933e-0d8e4b4f802d.png">

- _Is there a way I can change this when I don't have the original manifest files._
Please download the manifest from code [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) and update the user manifest as per the  [6th-step](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) of deployment guide

**Note**:- 
There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.

**Comment by ColinDPo** [comment]
Thank you for the guidance I will try that now and report back, later today.

**Comment by ColinDPo** [comment]
Thank you this worked, I now just need to change the icon with the user app which is my next challenge.
