### ISSUE TITLE
Hello @gsv022 ,

### ISSUE THREAD

**Issue by Axael85** [OfficeDev/microsoft-teams-apps-company-communicator#1296]
Hello @gsv022 ,
Just wanted to retake and open this case due the issue still happen, we are not able to use the step 4 even if the application is already installed for all users. 
Is there any other API permissions required for the USer app to work? We currently having these ones:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/03ba45ba-0448-410d-a659-c51af8ec8b14)

As well the error is the same, the drop down does not show the Security group name :
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/77cae79d-b20c-4154-9136-e70c95da4cae)

_Originally posted by @Axael85 in https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1253#issuecomment-1883924787_

**Comment by gsv022** [comment]
Hi @Axael85 ,
As per the deployment guide, the permissions need to be updated for graph app registration only but not for author and user. The screenshot shared above showing user app-api permission section s having extra permissions. Please check it out and remove unwanted permissions.

**Comment by Axael85** [comment]
Hello @gsv022 ,

I've already removed the extra permissions on User App registration. The only one that has API permissions is the API App registration.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/47f95851-d271-413f-b19c-83ee8b8d5acd)

Unfortunately still same error. I need to double check if the user app is already installed on Tenant level. 
How is the best to deploy users app to entire company?

REgards

**Comment by gsv022** [comment]
@Axael85 , Thanks for the patience.
Even in the Graph app, please keep only required permissions and remove all the other permissions. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/3ac51d5f-ea42-49f4-a4e6-aa34f902728d)
