### ISSUE TITLE
Azure Front door and domain fronting will be blocked

### ISSUE THREAD

**Issue by win-lobo** [OfficeDev/microsoft-teams-apps-company-communicator#1297]
Hi,
We received an email from MS recommending to take action. 

"_**Recommended action**
If your application or API uses a different TLS SNI extension than the request Host header, and these two values aren’t added as domains to Azure Front Door in the same subscription, you’ll need to update your application or API by 8 January 2024, to avoid any potential impact from this change.
If you need any further assistance, please submit a [support request](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest) with your subscription details and your Front Door or Azure CDN from Microsoft resource information._"

After contacting MS Support they provided the same information as [here](https://www.microsoft.com/en-us/security/blog/2021/03/26/securing-our-approach-to-domain-fronting-within-azure/) which does not resolve our question.

I'm looking to clarify if our CC implementation is having the discrepancies that MS mention in the email to make sure we will not have disruptions in our implementation. Could you please help with this?

FYI, this is the  host name and custom domain option we are using: https://appName.azurefd.net/

<img width="701" alt="Untitled 4343434" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/33344125/1ae951af-261e-489d-a336-3620907f7e50">

Thanks,
Edwin

**Comment by gsv022** [comment]
Hi @win-lobo ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by emiludev** [comment]
Hello everyone, have you had any progress with this request? I also received this email, and we have several implementations of Company communicator for different customers, what will be the procedure to update these implementations?

**Comment by gsv022** [comment]
Hi @win-lobo ,
Thanks for the patience.  Keeping this domain fronting into consideration, we tested for CC and it is working fine. Please let us know if you are facing any issue.

**Comment by win-lobo** [comment]
We are not facing any issue so far. We were just warned about this fronting behavior from Microsoft and wanted to check here. Please feel free to close this issue.
