### ISSUE TITLE
App Author and User published but in Author cannot send message, select groups nothing

### ISSUE THREAD

**Issue by binruis** [OfficeDev/microsoft-teams-apps-company-communicator#1298]
We have published both apps, but when we are trying to test them, the Author app cannot send message, select any groups, cant do nothing.

Is there any documentation that explains how can we use the apps?

**Comment by gsv022** [comment]
Hi @binruis ,
Thanks for raising the query. Could you please confirm on the below points.

- Apart from 4th sending option, are other sending options working ass expected?
- There are multiple possibilities for this 4th sending issue,  please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly or not. Especially check for **supported account type** should be- **My Organization**  for graph app. 
Author app- Multiple Organization
User app- Multiple Organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

- _Is there any documentation that explains how can we use the apps?_
 You can find the detailed information on the features available in Company Communicator app in this [section](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/User-manual) .

**Comment by binruis** [comment]
hello @gsv022 

About the first point, we cannot select any group in any option, and about the second point, we checked the manifest and looks good

**Comment by gsv022** [comment]
@binruis ,Could you please share the screenshot of graph app registration overview section.

**Comment by binruis** [comment]
yes here is the overview 
![app graph](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/fbfdee44-75f5-40e5-926a-686b5a09eac8)

**Comment by gsv022** [comment]
Hi @binruis ,
Mostly the issue is coming due to incorrect configuration only. Please share the author app-home page screenshot.

**Comment by binruis** [comment]
by home page u mean sharing you the overview of author registration?

**Comment by binruis** [comment]
![Author App 1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/8717bc4c-f558-4e0c-8789-320644656c40)

**Comment by binruis** [comment]
Hello @gsv022  any advacements about the issue?
![Author App 1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/86f526fa-5f67-4537-99d6-226c750edd2c)

**Comment by gsv022** [comment]
Hi @binruis ,

- You have published the app on teams right! please share the screenshot of landing page of CC- author app.
- Could you please share the deployment status of app service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/ed03b41a-e4dd-4e34-b558-882d44a84730)

**Comment by binruis** [comment]
Hello @gsv022  here are the screenshots 
<img width="451" alt="Communicator App NEW" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/35af3bb2-8aaa-4f64-96cc-d62a67cb70b0">

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/f6634f9c-07da-4f55-9d22-c8d661f128a4)

**Comment by gsv022** [comment]
Hi @binruis ,
After adding the author app to the team, please share the screenshot like below
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/7100782c-3cbf-44ca-8000-721c9ad70f2f)
