### ISSUE TITLE
App published but user does not receives messages

### ISSUE THREAD

**Issue by asilesj** [OfficeDev/microsoft-teams-apps-company-communicator#1299]
Hello,

We have both apps published, Author and User. It seems Author cand send messages correctly but the users never receive them.

When this method is executed: `GET /api/draftnotifications/scheduledDrafts` it gives a 401 error response

There is some problem related to the container account:
`Azure.RequestFailedException: The specified container already exists. RequestId:3f6196a2-901e-005b-498a-42a40d000000 Time:2024-01-08T23:30:02.8029114Z Status: 409 (The specified container already exists.)`

Is there something we may have done wrong during the deployment? We have followed the guide but we don't know wether is a problem of us or is the app.

Thanks!

**Comment by gsv022** [comment]
Hi @asilesj ,
Thanks for raising the query. Could you please share the screenshot of Company Communicator landing page(Home page).

**Comment by asilesj** [comment]
Hello @gsv022 ,

Thanks for answering. I don't know if you are talking about this page: https://adifcommunicator55.azurewebsites.net or the teams application.

In the first one the page is blank and it doesn't show anything. In the second one we have this:

![imagen](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/145332276/88c1467d-6931-4e46-b63e-ae329e1468b3)

Hope it helps, if you need anything else let me know ;)

**Comment by gsv022** [comment]
Hi @asilesj ,

- Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly or not. Especially check for **supported account type** should be- **My Organization**  for graph app. 

Author app- Multiple Organization
User app- Multiple Organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

**Comment by asilesj** [comment]
Hi @gsv022 

We have checked and everything in the  set-up guide is done correctly but we still get no messages from the author app.
We still get a 401 error code when we send a message from the author app.

**Comment by asilesj** [comment]
Hi @gsv022

We have checked and everything in the set-up guide is done correctly but we still get no messages from the author app.
We still get a 401 error code when we send a message from the author app.

**Comment by gsv022** [comment]
Hi @asilesj ,
We suspect that secrets are incorrectly configured.  Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by asilesj** [comment]
Hi @gsv022 

We have checked and we have the secrets configured correctly. Just in case we tried again but the users still get no messages.
Could it be something else?

Thanks

**Comment by gsv022** [comment]
Please share your mail id so that we can discuss the issue internally.

**Comment by asilesj** [comment]
Hello @gsv022,

Do you want my personal email or something else?

Thanks

**Comment by gsv022** [comment]
Hi @asilesj ,
Yes, Please share it so that we can discuss over the mail and can get into call if needed.

**Comment by asilesj** [comment]
Hi @gsv022 , sorry for the delay.
My email is asilesj@minsait.com. You can mail me whenever you want.

Thanks ;)

**Comment by gsv022** [comment]
Hi @asilesj ,
We shared a mail. Please check and respond

**Comment by gsv022** [comment]
Hi @asilesj ,
Please let us know if you are still facing the issue

**Comment by gsv022** [comment]
Sure, we will try to reach out via mail shortly.

**Comment by gsv022** [comment]
Hi @asilesj ,
We made a follow back recently over mail. Please let us know if you are having issue otherwise we can make it to closure.

**Comment by MirianaRebeggianiSacmi** [comment]
I'm facing with the same issue.. can you help me? 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/141223858/1229ecd5-4b57-4a29-84c6-2069ba55bf13)
