### ISSUE TITLE
Send to all user - Sends to all teams users regardless of Company Communicator Installation

### ISSUE THREAD

**Issue by dmwiggett** [OfficeDev/microsoft-teams-apps-company-communicator#130]
I have an issue in that the experience I am having of the Company Communicator application is different to the documentation. I noted in limitations that for a user to receive a message they need the application installed, I take it this is referring to the Company Communicator User App. 

I send a test message (Send in chat to everyone) and the message is sent to all Teams users regardless of company communicator user app installation status and regardless of Team membership. 

I did find the documentation a bit ambiguous in that there is mention to the App and i am uncertain if it is referring to Teams as the app or company communicator as the app. Company communicator is registered in app services.

Is the limitation information incorrect or am I experiencing something unique here or when the limitation documentation mentions to the App is it referring to Microsoft Teams?

**Comment by rashmi-dixit** [comment]
For a user to receive message in personal scope (1:1), the company communicator(CC) user app must be installed. Hence

'Send in chat to everyone' option in the CC authors app will send a message to all users who have CC user app installed.

In the Limitations documentation, the app referred is company communicator app.

**Comment by juna-gupta** [comment]
@dmwiggett We have addressed the limitation in the latest version. Please try the latest code.

In the previous version, the Send to everyone option used to send messages to all the users who have the application installed. 

Closing the issue.
