### ISSUE TITLE
Service Plan

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1300]
Hi, 

Not really an issue but I wanted to check if I move from Standard S2 service plan to S1 will this have any impact on the bot?

Thanks,

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
Thanks for raising the query. It is mandatory for the latest version of CC to have app service plan- S2. We recommend you to stay on the same app service plan or increase it to avoid any issues.

**Comment by ahlim0011** [comment]
Do you know how we can reduce the cost, as it seems to be charging us even if we are not sending messages via the bot.

**Comment by ahlim0011** [comment]
Also I accidently moved to S1 and now switched back to S2 and the app isn't allowing me to send messages, do you know what I need to do>

**Comment by ahlim0011** [comment]
Any update on the above?

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
If not using the application, you can downgrade the app service plan to S1.

**Comment by ahlim0011** [comment]
I do use it, but I want to know is there a way we can use it so it only chargers us when we use it?

Thanks,

**Comment by gsv022** [comment]
Hi @ahlim0011 ,
App Services status do not have an impact on chargeability, i.e. If an app is stopped, it will still be charged (if the plan is chargeable) So downgrading the app service plan when not in use is a good away to incur less charges.
