### ISSUE TITLE
Unable to send message

### ISSUE THREAD

**Issue by rfari** [OfficeDev/microsoft-teams-apps-company-communicator#1301]
Hi team,

I'm unable to send message using the author app. The 1 and 2 options shows "We couldn´t find any matches", already tried to re-add the user bot to a Team but still empty, already checked the TeamData table and is filled correctly. The 4 option is not returning any group.

Already checked:
- synced all functions and app service
- set-up authentication 
- secrets
- manifest

![Screen1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/156439746/6a59b287-39ce-48a4-8758-d24cad7e3c90)
![Screen2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/156439746/f40865ce-b07b-41ec-a09b-66821e9152ee)
![Screen3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/156439746/1b5af461-7efe-423d-91f4-1c61c6bbabd6)
![Screenshot 2024-01-09 172356](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/156439746/968dc631-46f7-4fa1-91cd-fb030f418e73)

**Comment by gsv022** [comment]
Hi @rfari ,
Thanks for raising the query. Please share your mail id(outlook id or teams id ) so that we can discuss the issue internally.

**Comment by rfari** [comment]
Hi @gsv022 ,

v-rfarias@microsoft.com

**Comment by gsv022** [comment]
Following the issue internally

**Comment by gsv022** [comment]
@rfari ,
Closing out the issue for now. Please feel free to open a new issue again if you encounter any issue w.r.t standard version of CC.

Thank you.
