### ISSUE TITLE
Error uploading app to Teams.

### ISSUE THREAD

**Issue by Duzima** [OfficeDev/microsoft-teams-apps-company-communicator#1302]
I get an error when I upload the app to Teams.
The error brings the following message:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

I'll attach some images to try to help.

![Captura de tela 2024-01-12 135209](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/7ab9f622-7220-4ad6-86fa-fc359c7b8600)
![Captura de tela 2024-01-12 135246](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/c6dc6824-3829-48cc-9d21-663442570be7)
![Captura de tela 2024-01-12 135345](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/777699c8-8fb9-4675-956f-5fd1601eb234)
![Captura de tela 2024-01-12 135450](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/988e4b7c-3611-4a82-83e7-712392986d57)

**Comment by Duzima** [comment]
![Captura de tela 2024-01-12 135935](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/06bef424-eb27-4a71-9fec-92fb45cb7ad1)

**Comment by Duzima** [comment]
Hi @gsv022 !

The problem was in the "Web App", I had created a "Web App" before performing the "CC" deployment and I forgot to delete it. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/c2dfe941-8d31-447b-a6d1-4458b2675af8)

Then I carried out the deployment and there ended up being a conflict between the "Web App" that I created manually and the "Web App" that would be created by the deployment. This way the "Web App" was left without the necessary settings. However, I deleted all the resources to do a clean installation and now I'm getting deployment failure.
Can you help me with this new problem?

Deployment Error:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/444ee019-6150-4124-9d1e-0ecfad38edeb)

**Comment by gsv022** [comment]
Hi @Duzima ,
To redeploy the app service issue please follow the below steps: Go to app service 

1. Click on Source and select external git.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/98143492/157680674-714c774a-d5d9-415c-abc1-21884ee5d7dd.png)


2. Go to repository paste this  [https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git](url)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/98143492/157680778-321a0ceb-3f07-473e-857d-9751c572405b.png)

3. Branch should be main
4. Click Save.
5. Track the deployment status in logs section in deployment center. Once the status turns successful, please try adding the application to team.

**Comment by Duzima** [comment]
Hi @gsv022 !


I added the URL as requested and saved. I tested the following URLs:
1) https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git
2) https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/5b553fe3-e43b-473e-8213-4b5aa6c48715)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/984885fd-e21e-4015-a201-74961cbfa297)

I did "Redeploy", but I received an error again. I did some other tests, but also without success.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/6fe912d0-cf33-4d2c-9ae8-c30ad4575636)

**Comment by gsv022** [comment]
Once the SYNC is performed at the resource level no need to go for re-deploy again.

**Comment by Duzima** [comment]
Hi @gsv022!

Got it, I'll test the installation. Once finished, I'll let you know if it worked.

**Comment by gsv022** [comment]
Hi @Duzima,
Could you please let us know the status

**Comment by Duzima** [comment]
Hi @gsv022!

I'm still having trouble adding it to Teams.
Error: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/80268174/260ea332-21b8-4b9c-b609-db188ef40b34)

I'm trying to follow these cases: #268, #284 and #404.
I'm also following this troubleshooting guide: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure

**Comment by gsv022** [comment]
Hi @Duzima ,
Please share your mail id(outlook id or teams id) so that we can discuss the issue internally.
