### ISSUE TITLE
Application Deployed but Stuck in 401 Unauthorized Loop

### ISSUE THREAD

**Issue by robterrins** [OfficeDev/microsoft-teams-apps-company-communicator#1303]
I have followed the deployment steps outlined for a PowerShell deployment of version 5.5 and successfully added the author app to my team but when viewing the app it isn't able to be interacted with and when checking the dev tools console, appears to be stuck in an infinite loop of:

_Failed to load resource: the server responded with a status of 401 (Unauthorized).              
GET https://XXXXXXX.azurewebsites.net/api/draftnotifications net::ERR_ABORTED 401 (Unauthorized)
GET https://XXXXXXX.azurewebsites.net/api/draftnotifications/scheduledDrafts net::ERR_ABORTED 401 (Unauthorized)    
GET https://XXXXXXX.azurewebsites.net/api/sentnotifications net::ERR_ABORTED 401 (Unauthorized)_

Based on other user's experiences I then subsequently manually added the application ID URI and relevant scopes to the graph app registration as described in 3. Set-up Authentication section of the manual deployment guide - but this still has not rectified the issue and so I am unsure how to proceed with troubleshooting:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/51408938/309a4e6d-268f-4a3e-bbf1-7549646123f1)

**Comment by gsv022** [comment]
Hi @robterrins ,
Thanks for raising the query. Could you please confirm on the below points.

- Please share the screenshots of authentication, API Permissions, manifest from the graph app registration.
- Please share the deployment status of app service, all the three function apps(data-function, function, prep-function). Here is the reference.
Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **function app** from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- Just do for other resources as mentioned and share the screenshot of them as well.

**Comment by gsv022** [comment]
Hi @robterrins ,
Please share your mail id (outlook id or teams id ) so that we can discuss the issue internally.

**Comment by robterrins** [comment]
Hi Sai,

Thanks, you can reach me at ***@***.***

Appreciate your help with this.

Rob

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gsv022** [comment]
Hi @robterrins ,
Please share your mail id directly here. Because  I am the mail id in a masked state like below
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d1a4192b-cb58-4ba6-a476-4fb19f22be3a)

**Comment by robterrins** [comment]
Hi Sai,

I did try to reply to the email but it obviously didn’t work.

My work ID is

***@***.***

Thanks

Rob

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robterrins** [comment]
Hi,

I did try to reply to the email but it evidently didn’t work, here it is:
r.terrins@reply.com

Thanks
Rob

**Comment by gsv022** [comment]
Hi @robterrins ,
Thanks for sharing. We have started the conversation internally over Teams.

**Comment by robterrins** [comment]
Following call, happy to close. 
Issue was regarding not having uploaded the authors app to the team properly.

**Comment by gsv022** [comment]
Thanks for the confirmation.
