### ISSUE TITLE
Changing the User Icon when receiving a message

### ISSUE THREAD

**Issue by ColinDPo** [OfficeDev/microsoft-teams-apps-company-communicator#1304]
Hi,

Can I please get some guidance on how I can change the icon of the messaging app for users when they receive a communication?  I have changed the outline icon file but this does not reflect when the users receive messages.

              Thank you this worked, I now just need to change the icon with the user app which is my next challenge.

_Originally posted by @ColinDPo in https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1293#issuecomment-1885000072_

**Comment by gsv022** [comment]
Hi @ColinDPo ,
We can continue the conversation in #1293 only. As this is a duplicate to it, hence we are closing this issue.
