### ISSUE TITLE
Unable to list Distribution groups or distribution lists when sending messages

### ISSUE THREAD

**Issue by pmkinyua** [OfficeDev/microsoft-teams-apps-company-communicator#1305]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151738749/2e0db8da-7f1d-4da5-8225-665f1db90046)

Am also not able to "Send in chat to everyone" coz i keep getting Sync error

Send in chat to everyone
Warnings
Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request.

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Thanks for raising the query. Could you please confirm on the below points.

- Are you able to send the messages using 1st and 2nd sending options?
- There are multiple possibilities for this issue,  please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly or not. Especially check for **supported account type** should be- **My Organization**  for graph app. 
Author app- Multiple Organization
User app- Multiple Organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

**Comment by pmkinyua** [comment]
Hi Sai,

Yes I am able to send using options # 1& 2.
I have also reviewed all the configurations including the API permissions for the apps as per the documentation and all looks good.






Peter Kinyua

IT Systems Manager



M-KOPA | ***@***.*** | +254 723 511 347

[cid:046be3b0-9c84-4d79-aa6a-d25187e215d4]

________________________________

**Comment by gsv022** [comment]
@pmkinyua , Could you please share the screenshot showing Graph API Permissions

**Comment by pmkinyua** [comment]
Here are my permissions;

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151738749/933fe12e-834c-4f4b-8cab-04c624cbc00b)

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Below are the required permissions and rest all can be removed. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0c011976-d29b-4e56-9b87-be7c3b12039b)

**Comment by pmkinyua** [comment]
So is this the reason I can see the DLs when sending messages?







Peter Kinyua

IT Systems Manager



M-KOPA | ***@***.*** | +254 723 511 347

[cid:852458b0-58c4-4cd8-8d54-b942701218c3]

________________________________

**Comment by pmkinyua** [comment]
I have removed unnecessary permissions. Below is the current config;

[cid:53ba8e49-101d-4257-be04-dd97b23a3a49]






Peter Kinyua

IT Systems Manager



M-KOPA | ***@***.*** | +254 723 511 347

[cid:75ddf83c-6a7e-482a-9dac-4e46c00721b5]

________________________________

**Comment by gsv022** [comment]
Hi @pmkinyua ,
If the issue still exists, please share your mail id (outlook id or teams id) so that we can discuss the issue internally.

**Comment by gsv022** [comment]
@pmkinyua , Please share you mail id directly here. I am getting like below
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f3f92f87-8326-4ab2-ac53-0453d08a7053)

**Comment by pmkinyua** [comment]
My email is ***@***.***






Peter Kinyua

IT Systems Manager



M-KOPA | ***@***.*** | +254 723 511 347

[cid:eba9268c-8a42-43f1-8b54-a13264a7d43d]

________________________________

**Comment by gsv022** [comment]
Please share the id directly here in this GitHub conversation.

**Comment by pmkinyua** [comment]
> Please share the id directly here in this GitHub conversation.

peter.kinyua@m-kopa.com

**Comment by gsv022** [comment]
We will continue the conversation internally

**Comment by gsv022** [comment]
We tried out reaching you over mail or Teams. Please respond to which ever is feasible for you.

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Please let us know if you require any inputs otherwise we can make it to closure.
