### ISSUE TITLE
How to apply line break

### ISSUE THREAD

**Issue by eddie201400** [OfficeDev/microsoft-teams-apps-company-communicator#1306]
Try to deliver message but unable to able line break between paragraphs.
Try add 2 x space + return  but no use

**Comment by gsv022** [comment]
Hi @eddie201400 ,
Thanks for raising the query. Yes it's a known issue, this is the limitation with adaptive cards which doesn't support formatting.
However, the issue has been added to the backlog already. We will review it and do the needful.
