### ISSUE TITLE
Company Communicator (Authors) needs permission to upload this file to your OneDrive

### ISSUE THREAD

**Issue by AndresGav** [OfficeDev/microsoft-teams-apps-company-communicator#1307]
Hello, i'm having issues when trying to download the .zip file with the results of sending a message.

Mssg: "Something went wrong. Please try again."

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/013fda6f-2eb8-4b48-b0b9-cac6db380526)

**Comment by gsv022** [comment]
Hi @AndresGav ,
Thanks for raising the query. Could you please check the Graph App API permissions. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/7d37bf73-95b0-47a1-9004-7b40b3648213)

**Comment by AndresGav** [comment]
Yes

![Azure](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/1ea6de1b-c496-4652-8a01-0f7f1c9f1214)

**Comment by gsv022** [comment]
Hi @AndresGav ,
Could you please share the screenshots of Graph App- Overview section, Authentication section, Expose an API section, Manifest section with **optional claims** added.

**Comment by AndresGav** [comment]
Overview Section
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/c0b827e2-be22-4761-b0d6-10d548f616e7)



Authentication section
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/079d0a72-4f16-41f6-98ed-80bd9cf354f1)



Expose an API section
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/5218623d-9011-4c65-bec4-fe27acb46666)



 Manifest section with optional claims added
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/8452edd2-fa0c-4297-bd2a-ffe0c0c1b0fd)

**Comment by AndresGav** [comment]
Currently, the issue has been resolved. For other users experiencing the same inconvenience, please check the permissions on OneDrive (read, write, and file upload), as the application adds the .zip files to a folder in OneDrive.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/4207807b-40b8-4178-9012-125239f1fe98)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/50000912/ac20182f-e4d1-4e3e-aaf2-417051e492ce)

**Comment by victorsimonlee** [comment]
Hi @AndresGav I am facing the same issue and saw your post saying this can be solved by giving permissions in OneDrive. Would you be able to elaborate a bit? Which user must be given permission and on what folder?

Thank you in advance!

**Comment by AndresGav** [comment]
Hi @victorsimonlee, sure, sign in with the user you are trying to use to download the .zip on OneDrive. You just need to log in to OneDrive with the user you want to download with. It's likely that you’re accessing OneDrive for the first time, so once you log in, make sure the "Applications" folder is created.

If this doesn’t work, we can meet and take a look together.
