### ISSUE TITLE
Chat notification popup is redirecting to Apps Page and NOT to the message sent by the BOT

### ISSUE THREAD

**Issue by kumaranupam21** [OfficeDev/microsoft-teams-apps-company-communicator#131]
I configured the Company communicator App and deployed to multiple users using Teams Setup policy. The issue is when any message is sent to the users using the BOT Author interface, users get a a message notification that "Company Communicator sent a card", but when users click on that notification, they get redirected to "Apps" screen instead of the message.

![Chat-1](https://user-images.githubusercontent.com/57713084/68764211-965fd280-061a-11ea-9650-bd05a914616d.jpg)
![Apps-1](https://user-images.githubusercontent.com/57713084/68764210-965fd280-061a-11ea-82ed-8113e8661977.jpg)

**Comment by v-smahaj** [comment]
Hi @kumaranupam21 
Thanks for reporting this. 
Let us know if you are still facing this issue.
