### ISSUE TITLE
Can't list Distribution or Security Groups in CC Authors app.

### ISSUE THREAD

**Issue by gavinwecc** [OfficeDev/microsoft-teams-apps-company-communicator#1310]
When drafting messages, I am unable to search for and select groups to send the messages to. No groups show up at all and in the box it says "We couldn't find any matches". 

I deployed this via Powershell, but upon looking at other open issues with similar symptoms, I noticed that the CC App registrations in Azure didn't have any of the permissions required. I added those API permissions, ensured they Supported the correct account types, and double checked the deployment center which shows a successful deployment. After double checking those areas, I'm still experiencing the issue.

If you would prefer to discuss this internally, my email is gkeith@wecc.org

![CC Error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157054565/dad60f6e-c8c1-4db2-986c-a7741d10d10a)

**Comment by gsv022** [comment]
Hi @gavinwecc ,
Thanks for raising the query. Could you please share the application insight logs. Here is the reference,
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat. Even the screenshots would be more helpful. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/4747b16e-067a-47ad-a764-ae38a5f67a89)

**Comment by gavinwecc** [comment]
![CCError](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157054565/f01b0358-8e6d-4e80-854c-7bc8556adc62)

Here is a screenshot of the application insight failures.

**Comment by gavinwecc** [comment]
Hi @gsv022 ,

Thanks for getting back to me.

Looked like my powershell deployment had been missing these steps. I completed these, waited 24 hours and tried it again. I'm getting the same result.

Another symptom that I'm experiencing if this helps find the root cause, is that in the first and second send options, I can see the Teams that have been assigned the Company Communicator app, however when I try to send to the teams or the users within the team, it gets stuck on sending. And it appears to get stuck on canceling messages as well. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157054565/90882bdc-fe5c-470e-87b1-f00b42fff00c)

Let me know if you have any other ideas. I appreciate your help thus far.

**Comment by gsv022** [comment]
Hi @gavinwecc ,
Thanks for the patience. How about a call Friday IST working hours(11am-7pm)? Please confirm on your availability, we will send out a meeting invite accordingly.

**Comment by gavinwecc** [comment]
<Limited-Disclosure>

Hello,

I am unavailable during those times. Are you available Monday during similar hours?

Thanks,

Gavin Keith
Systems Administrator
(385) 224-7978
www.wecc.org<http://www.wecc.org/>

**Comment by gsv022** [comment]
We are bit pre-occupied on that day. We will send it for Tuesday. Hoe it works.

**Comment by gavinwecc** [comment]
<Limited-Disclosure>

Hey Sai,

When would be your next availability to take a look at this? Or do you think it might be valuable for me to start my deployment over from the beginning doing the manual route instead of powershell?

Thanks,

Gavin Keith
Systems Administrator
(385) 224-7978
www.wecc.org<http://www.wecc.org/>

**Comment by gsv022** [comment]
Thanks for the patience. We will available on Tuesday/Wednesday/Thursday (2PM-7PM IST). Please let me in which day you are fine with.

**Comment by gavinwecc** [comment]
<Limited-Disclosure>

Hello,

Unfortunately, those times don’t work for me. I am in MST, so our time zones are far apart. Is it possible to continue troubleshooting over email?

Thanks,

Gavin Keith
Systems Administrator
(385) 224-7978
www.wecc.org<http://www.wecc.org/>

**Comment by gsv022** [comment]
Hi @gavinwecc ,
I have sent you a mail, please check and respond

**Comment by tiwariShiv7** [comment]
Thank you @gavinwecc for confirming the behavior. We are happy we could troubleshoot the issue. As per the confirmation received over the internal e-mail, we are closing this issue.
