### ISSUE TITLE
Error message in CC Author with the new teams (web and desktop version)

### ISSUE THREAD

**Issue by cencosudregional** [OfficeDev/microsoft-teams-apps-company-communicator#1311]
I try to send a new message from cc author and i found this error message in the new teams version (web and desktop version).

<img width="575" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143105447/c4cfbb81-72e8-4988-b86a-a159525b3084">

We are working now with this version:
Versión 4.1.5

Can you help us to fix this issue? 
Thanks.

**Comment by gsv022** [comment]
Hi @cencosudregional ,
Thanks for raising the query. Could you please share the screenshot of deployment status of App Service. Here is the navigation

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on Logs. 

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6b02124a-cd7b-4c37-872e-7b7136d277ec">

**Comment by cencosudregional** [comment]
Hi @gsv022 
<img width="674" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143105447/ef3b4cc5-7a68-4fbe-904d-54197993e6f2">

**Comment by gsv022** [comment]
@cencosudregional , It seems that repo is not pointing to official repository of CC. Please check with the concerned team to look into the issue. Our support scope is very limited to official version of CC. 
Repository that we support- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

Do let us know if you have any queries w.r.t standard version of CC we are happy to assist you.
