### ISSUE TITLE
New Feature Request:  Another Teams app that only allows creating messages for approval

### ISSUE THREAD

**Issue by LycheeYum** [OfficeDev/microsoft-teams-apps-company-communicator#1314]
Hello, 

I'm trying to make a power app to attempt do this however, maybe this could be included in the app.  

I'd like to offer the ability to create/draft messages to everyone in our org.  However, users shouldn't be able to send messages only draft them and they should only be able to see their own messages.  The actual authors listed as AuthorizedCreatorUpns will do the sending/approving.

The current Teams app would work if it filtered the NotificationData table on the current user and removed the ability to send messages.  

A bonus would be if it let the user select from a predetermined list of groups.

If I could do this with the current app, if you should point me in the right direction, I wouldn't mind digging in.

**Comment by gsv022** [comment]
Hi @LycheeYum ,
Our support scope is very limited with the standard version. We won't be able to assist on this request. Please let us know if you have any issues with the standard version.

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

**Comment by LycheeYum** [comment]
Closing.  Please consider the creation of a draft creating only app that can be open to an entire org
