### ISSUE TITLE
How to turn off Public Network Access without getting a outage to the app?

### ISSUE THREAD

**Issue by TomSawyer03** [OfficeDev/microsoft-teams-apps-company-communicator#1315]
Recently, we have been requested to Disable the public network access of the storage account. When I did the app became inaccessible. Can you let us know if we can disable it and what are the other options aside from public network access.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85331597/7340d5b8-95ba-4e39-92f8-de48f88ed769)

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
Thanks for raising the query. We will check the behavior from our side and get back to you with proper response

**Comment by TomSawyer03** [comment]
Do you have any update on this?

**Comment by TomSawyer03** [comment]
Follow up on this please

**Comment by TomSawyer03** [comment]
> Hi @TomSawyer03 , Thanks for raising the query. We will check the behavior from our side and get back to you with proper response

Follow up on this please

**Comment by TomSawyer03** [comment]
> Hi @TomSawyer03 , Thanks for raising the query. We will check the behavior from our side and get back to you with proper response

Follow up on this inquiry please

**Comment by gsv022** [comment]
Hi @TomSawyer03 ,
Thanks for the patience. The migration of the storage account from a public endpoint to a private endpoint makes app inaccessible. Currently this feature is in the backlog. we do not have an estimated time of completion (ETA) at the moment.

However, we encourage you to stay informed by regularly checking the [release notes](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Release-notes) where we promptly post updates for each release. Your patience is appreciated, and we will keep you updated on any developments.
