### ISSUE TITLE
Company Communicator creation for second time

### ISSUE THREAD

**Issue by ManasaMShastri** [OfficeDev/microsoft-teams-apps-company-communicator#1317]
Hi we are creating Company Communicator for second time but we are getting the following issue.

![image (3)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148181089/07d76278-6b6b-4ddc-8ed0-2f5a71b469cb)

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
Thanks for raising the query. Please clarify below points.

- Is there instance of CC already up and running?
- Or  are you trying to re-deploy since you might have encountered deployment failure.

**Comment by gsv022** [comment]
@ManasaMShastri , Closing this issue here as it is a duplicate to #1309. We can continue the conversation there to avoid ambiguity.
