### ISSUE TITLE
Message summary ignoring all newlines in the text

### ISSUE THREAD

**Issue by kumaranupam21** [OfficeDev/microsoft-teams-apps-company-communicator#132]
When preparing the message using Author's app, we can put newlines just by pressing enter between multiple paragraphs, but when that message is delivered, it removes all the additional lines from the message. It also doesn't seem to respect some of the markdown symbols like \n\n.

Author screen:
![Author-1](https://user-images.githubusercontent.com/57713084/68765322-cf994200-061c-11ea-8c94-063b482e118c.jpg)

What recipients see:
![Receipients-1](https://user-images.githubusercontent.com/57713084/68765338-d7f17d00-061c-11ea-8e41-32315ea719a7.jpg)

**Comment by rashmi-dixit** [comment]
For adding a newline to a CC message, type two spaces at the end of the line of text followed by hitting "enter" to insert a newline. 
So it should be like:
hi  
how are you
 
(with two spaces after the 'hi' and hit 'enter')
Note: The preview in Task Module should show the text on two different lines. 
CC doesn't work by typing  "\n" in the actual text box.

**Comment by kumaranupam21** [comment]
Tried this... 2 spaces after end of the sentence and then hit enter... doesn't work. Looks good in the Preview window, but delivered messages has all the new lines removed.

This is what I prepared and sent:
![Sent](https://user-images.githubusercontent.com/57713084/79329489-2e3e5100-7f18-11ea-9736-52e2677c43f6.jpg)

This is what was received by users:
![Received](https://user-images.githubusercontent.com/57713084/79329521-3dbd9a00-7f18-11ea-9d7b-4839f4498405.jpg)

Any more ideas?

**Comment by rashmi-dixit** [comment]
Using the above mentioned trick would show the text on two different lines. IThe message received by users has the sentences in 2 different lines
![image](https://user-images.githubusercontent.com/57787129/81599719-608f8100-93e6-11ea-81cd-16ef463121d4.png)

It won't insert multiple blank /new lines.
