### ISSUE TITLE
Incorrectly ran Sync on previous version

### ISSUE THREAD

**Issue by fajr365** [OfficeDev/microsoft-teams-apps-company-communicator#1320]
Incorrectly ran Sync on previous version 5.4.1 - now the deployment is stuck on "Running Deployment Command...
How can i correct this issue? Can I stop the deployment and start over?

**Comment by gsv022** [comment]
Hi @fajr365 ,
Thanks for raising the query. What is the error coming on app service -logs? Screenshot would be much better for troubleshooting Below is the reference.
<img width="290" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f70aa554-6d5f-4e11-b204-df020eaaf41f">
.

**Comment by fajr365** [comment]
I noticed that the .NET was already set to 6 so I ran nothing other than the Sync. It works in the Teams web and the New teams client on one PC but not another. Cleared all Teams Cache, uninstall both versions of Teams rebooted and reinstall Teams.
Also this is for the CC Author as a Tab.

[A screenshot of a computer  Description automatically generated]

Thank You,


***@***.***
Frank Adorney Jr.
IT System Engineer SR.
Main Line Health
SouthPoint Two
1180 W. Swedesford Road
Berwyn, Pa 19312
484.596.1871 (Office)
[signature_456468037]<https://landing.mainlinehealth.org/be-seen/>
***@***.***Chat with me on ***@***.***>

From: Sai Venkat ***@***.***>
Sent: Thursday, January 25, 2024 9:48 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Adorney, Frank ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-apps-company-communicator] Incorrectly ran Sync on previous version (Issue #1320)


This message originated from outside MLHS systems. Any attachments or links should be carefully considered before proceeding. Messages from our business partners still need to be reviewed and should not be opened if suspicious.
Please use the report phishing button to report a questionable email.

________________________________

Hi @fajr365 [github.com]<https://urldefense.com/v3/__https:/github.com/fajr365__;!!K_I4mMC9zg!p0HSDivqtl5Yn1hvU52myQw6T7U2CjECOYY_jp-AJmraWYD9b6tLwjXmHcEXA25sLNCQ31jsNkfDloTqOz0HV5k$> ,
Thanks for raising the query. What is the error coming on app service -logs? Screenshot would be much better for troubleshooting Below is the reference.
image.png (view on web) [github.com]<https://urldefense.com/v3/__https:/github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f70aa554-6d5f-4e11-b204-df020eaaf41f__;!!K_I4mMC9zg!p0HSDivqtl5Yn1hvU52myQw6T7U2CjECOYY_jp-AJmraWYD9b6tLwjXmHcEXA25sLNCQ31jsNkfDloTqXBvqdbo$>
.

**Comment by fajr365** [comment]
Where would I go to see those logs?

From: Sai Venkat ***@***.***>
Sent: Thursday, January 25, 2024 9:48 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Adorney, Frank ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-apps-company-communicator] Incorrectly ran Sync on previous version (Issue #1320)


This message originated from outside MLHS systems. Any attachments or links should be carefully considered before proceeding. Messages from our business partners still need to be reviewed and should not be opened if suspicious.
Please use the report phishing button to report a questionable email.

________________________________

Hi @fajr365 [github.com]<https://urldefense.com/v3/__https:/github.com/fajr365__;!!K_I4mMC9zg!p0HSDivqtl5Yn1hvU52myQw6T7U2CjECOYY_jp-AJmraWYD9b6tLwjXmHcEXA25sLNCQ31jsNkfDloTqOz0HV5k$> ,
Thanks for raising the query. What is the error coming on app service -logs? Screenshot would be much better for troubleshooting Below is the reference.
image.png (view on web) [github.com]<https://urldefense.com/v3/__https:/github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/f70aa554-6d5f-4e11-b204-df020eaaf41f__;!!K_I4mMC9zg!p0HSDivqtl5Yn1hvU52myQw6T7U2CjECOYY_jp-AJmraWYD9b6tLwjXmHcEXA25sLNCQ31jsNkfDloTqXBvqdbo$>
.

**Comment by fajr365** [comment]
This is the only Error type for today:
There was an error during processing of the managed application service auto-start for application pool: 'MLHCommunicator'.  Some application services may not have been processed correctly.  Please check the configuration for application service auto-start for the application(s) assigned to this application pool.  The data field contains the error code.
MLHCommunicator
02000780

**Comment by gsv022** [comment]
Hi @fajr365 ,
_Where would I go to see those logs?_

Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center -->Click on Logs.
<img width="916" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/16828539-d597-4f2f-a444-010840a8becd">

**Comment by fajr365** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/63668120/a224991f-41d2-4356-9ef9-98a14f802bd2)

**Comment by fajr365** [comment]
What are the required API Permissions for:
Communicator App
Communicator Author
Communicator User

**Comment by gsv022** [comment]
Hi @fajr365 ,
To make CC application run on new version of Teams, please make sure that cache is cleared. Here is the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1337) for the detailed steps-
