### ISSUE TITLE
Message stuck in queue

### ISSUE THREAD

**Issue by boscohwang** [OfficeDev/microsoft-teams-apps-company-communicator#1322]
When restarting the app service, user trying to send the message.

Then all message are stuck at queue status. and cannot cancel it.

**Comment by boscohwang** [comment]
when trying to restart the prep-function, we encounter the issue:
Microsoft.Azure.WebJobs.Script: Error building configuration in an external startup class. Microsoft.Azure.WebJobs.Script: One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType DurableTaskWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289' does not meet the required minimum version of 2.4.1. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.4.1 or later. ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later. .

**Comment by gsv022** [comment]
Hi @boscohwang ,
Thanks for raising the query.  Please perform the below procedure.

- Disconnect the repository 
- Wait for 30-40minutes
- Then connect to repository again.
- Do the same for function apps which are showing this issue

Keep us posted

**Comment by boscohwang** [comment]
> Hi @boscohwang , Thanks for raising the query. Please perform the below procedure.
> 
> * Disconnect the repository
> * Wait for 30-40minutes
> * Then connect to repository again.
> * Do the same for function apps which are showing this issue
> 
> Keep us posted

I will try and let you know the result. Thanks

**Comment by boscohwang** [comment]
Issue resolved and thanks
