### ISSUE TITLE
New Teams cannot access Company Communicate

### ISSUE THREAD

**Issue by boscohwang** [OfficeDev/microsoft-teams-apps-company-communicator#1323]
Follow the guide to update from 5.11 to 5.5, (it looks like only update the .net 6)
then also try to sync the app service. but it look like nothing change

**Comment by gsv022** [comment]
Hi @boscohwang ,
Thanks for raising the query. Please provide inputs on the below points

- Is application working fine on older version of teams?
- Does runtime version for function apps are changed to ~4? if yes, please share a screenshot

**Comment by boscohwang** [comment]
> Hi @boscohwang , Thanks for raising the query. Please provide inputs on the below points
> 
> * Is application working fine on older version of teams?
> * Does runtime version for function apps are changed to ~4? if yes, please share a screenshot

Hi it is working fine in the old version. And yes we have Chang to 4. and I will provide the screenshot tomorrow. Thanks

**Comment by boscohwang** [comment]
kindly check the screenshot as below

**Comment by MNL79** [comment]
Same for us - I upgraded today, but not working in new Teams. Can only access the authors app via classic Teams.

**Comment by boscohwang** [comment]
<img width="467" alt="MicrosoftTeams-image (27)" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157669286/ef5340b1-24b1-4ae7-b314-121d94ff093b">
<img width="500" alt="MicrosoftTeams-image (26)" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157669286/c5267f26-e36a-49ab-9c51-84750bcf44d3">
<img width="488" alt="MicrosoftTeams-image (25)" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157669286/961c5571-9aef-4ae8-8309-86267cf5292e">
Kindly let me know if the screenshot not you are requesting for

**Comment by gsv022** [comment]
> > Hi @boscohwang , Thanks for raising the query. Please provide inputs on the below points
> > 
> > * Is application working fine on older version of teams?
> > * Does runtime version for function apps are changed to ~4? if yes, please share a screenshot
> 
> Hi it is working fine in the old version. And yes we have Chang to 4. and I will provide the screenshot tomorrow. Thanks

@boscohwang , Could you please share the screenshots of author app-home page from both classic teams and new teams

**Comment by boscohwang** [comment]
![tmp_cb54ce45-5095-4735-8d63-b371fa80ed89](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157669286/707003f7-12a9-4d38-adba-7cdd55004402)
![Uploading tmp_e3d059d7-a76c-4fdd-ad1f-a2e5e28e0b03.png…]()

**Comment by boscohwang** [comment]
![tmp_cb54ce45-5095-4735-8d63-b371fa80ed89](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157669286/31e19874-0efd-4d25-8527-430aa6a6704f)
![tmp_e3d059d7-a76c-4fdd-ad1f-a2e5e28e0b03](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157669286/5ceb0111-b6c5-48dc-8298-802ec7d73ba3)

**Comment by gsv022** [comment]
Hi @boscohwang ,
Could you please verify all the parameters mentioned in the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) are added in the app service configuration section.

**Comment by boscohwang** [comment]
> Hi @boscohwang , Could you please verify all the parameters mentioned in the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) are added in the app service configuration section.

Hi we did not. Since we consider such parameters features are not necessarily for daily operation.is it a must?

**Comment by gsv022** [comment]
Hi @boscohwang ,
If not added, please add the parameters in app service configuration. It is mandatory.

**Comment by Carme99** [comment]
Hi All,

Is the current release of Company Communicator confirmed as compatible with the new Teams client as we're also experiencing the same issues with new Teams.

**Comment by victorsimonlee** [comment]
Experiencing the same issue with the  new Teams. 

Our is not a new installation of Company Communicator, but rather, a version 5.5 that's been working fine since October last year. Stopped working on new Teams (and web).

**Comment by Carme99** [comment]
Still not resolved.

**Comment by ndl7** [comment]
Also facing the same issue. Followed the upgrade guide, checked and double-checked everything, still getting an error. All three functions are giving 2 errors:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/32853239/e558ac47-2bd7-4087-8ffc-56783515e49b)

Functions runtime error
Microsoft.Azure.WebJobs.Script: Error building configuration in an external startup class. Microsoft.Azure.WebJobs.Script: One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType DurableTaskWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289' does not meet the required minimum version of 2.4.1. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.4.1 or later. ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later. .

AZFD0005
Error building configuration in an external startup class.

**Comment by djaw123** [comment]
Hello all, 

I found solutions which work in my company, I updated version from 5.2 to 5.5, and then on windows 11, go to Setting in windows - Application - Installed Applications - Microsoft Teams (work or school) **NEW**

and try FIX (in screen Napraw)
and Reset (on screen Resetuj)

and it start works on 2 different author accounts and PC's

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/158998710/e482073d-800a-4e3d-a1c0-96c77f16941a)

**Comment by djaw123** [comment]
this fix also working check language spelling in NEW Teams :D
