### ISSUE TITLE
Deploying the Company Communicator with a private endpoint storage account

### ISSUE THREAD

**Issue by KimmoBergius** [OfficeDev/microsoft-teams-apps-company-communicator#1324]
One of our customers and their security are asking whether the storage account that is being used for the company communicator app can be moved behind a private endpoint? I have seen some references to this here, in issues #528 and #503, but both of those have been closed. #528 does mention that private endpoints are on the devteam backlog, but that issue was closed in 2022 and I can't find any other references. So can anyone comment on whether using a private endpoint storage account is possible?

**Comment by gsv022** [comment]
Hi @KimmoBergius ,
Thanks for raising the query. We will look into this and get back to you with proper response soon

**Comment by KimmoBergius** [comment]
OK, thanks @gsv022. If you need any additional information, just ping me - I'll be happy to provide any details you may need.

**Comment by gsv022** [comment]
Hi @KimmoBergius ,
Currently, the migration of the storage account from a public endpoint to a private endpoint is in the backlog, and unfortunately, we do not have an estimated time of completion (ETA) at the moment.

However, we encourage you to stay informed by regularly checking the [release notes](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Release-notes) where we promptly post updates for each release. Your patience is appreciated, and we will keep you updated on any developments.

**Comment by KimmoBergius** [comment]
Thanks for the information. It would be good, though, to have some kind of an estimate on this issue: this was first mentioned nearly two years ago in one of the issue items I have referred to above, and already then there was a mention about it going into the backlog. Now what we would need is some kind of an estimate: is it going to take months or years for this to be tackled - this has a big impact on the custmers plans to implement Company Communicator, if this will still take a long time, they will look for alternate solutions.

**Comment by gsv022** [comment]
We are committed to add new features/bug fixes consistently. Currently, we don't have any ETA on this feature but we will update you as soon as we have a visibility on the dates for it. You can also keep a check on the feature page [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Release-notes).
