### ISSUE TITLE
HTTP Error 500.30 - ASP.NET Core app failed to start

### ISSUE THREAD

**Issue by lazarovidiu** [OfficeDev/microsoft-teams-apps-company-communicator#1327]
Updated from version 5.3 to 5.5. Sync was successful but we are now getting the below error when opening the app in Teams:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/89b3b35b-e4fd-4796-94bb-4fe80ae53451)

**Comment by gsv022** [comment]
Hi @lazarovidiu ,
Thanks for raising the query. Could you please navigate to the below place and share a screenshot.
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center --> Click on logs
<img width="712" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a1cdab6c-9451-4568-ad9e-7cf9ff5d9622">

**Comment by lazarovidiu** [comment]
@gsv022 Hi, no visible issues with the deployment. Note that I also tried to Sync again and it was successful both times but the issue persisted.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8112409/938c5271-ae31-4eee-a4ac-6356acb4da41)

**Comment by gsv022** [comment]
Hi @lazarovidiu ,
please share the zipped manifest files uploaded to teams

**Comment by lazarovidiu** [comment]
Hello, I have attached the two manifest files we use.
Note that I have not changed the app packages in Teams after the update, as it was not specified in the documentation.
[manifest.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/14110150/manifest.zip)

**Comment by gsv022** [comment]
Hi @lazarovidiu ,
Manifest files are fine. Have you  performed [migration-steps.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version)?Please cross verify. If already done, please share screenshots of app service configuration showing the parameters and dotnet runtime version functions

**Comment by lazarovidiu** [comment]
Hi @gsv022 , I have performed the migration steps and cross-verified multiple times but nothing seems wrong.
I have attached a zip file with the exported configuration of the app service as well as the dotnet runtime for the 3 functions.
[Config.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/14164024/Config.zip)

**Comment by gsv022** [comment]
Thanks for the confirmation
