### ISSUE TITLE
Company communicator is not working on Modern Microsoft teams

### ISSUE THREAD

**Issue by JamaliShoaib** [OfficeDev/microsoft-teams-apps-company-communicator#1328]
The Company Communicator Author is not working on Modern Microsoft Teams. When I switch back to the classic Teams version, the Communicator Author is working properly, and on Modern Microsoft Teams showing the error message 'Sorry, an error occurred while trying to access this service.' I have attached a screenshot below.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/29330750/2065087f-c79f-42cd-a847-1ba7cd483bf8)

**Deployment status of app service.**
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/29330750/4d31a9e3-3d0a-44ec-bbfc-ed83910b8d27)

**I have a couple of queries that require your support. Can we migrate from customized versions to the standard version? What will be the impact, such as access level and data? The current version is working fine with MS Classic Teams, and will the Standard version support Modern Teams? Additionally, can we use the same applications (User app, Author App, Graph App) for deployments?**

**Comment by gsv022** [comment]
Hi @JamaliShoaib ,
Thanks for raising the query. 

- Please share the screenshot of logs section 
<img width="405" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0789362e-46d1-42f3-9d64-295445bba7bc">

- Share the screenshot of author apps-home page of both classic teams and new teams.
- _Can we migrate from customized versions to the standard version?_  
No, we won't recommend it. The better option is to go with fresh deployment of CC only.

- _What will be the impact, such as access level and data?_ 
Possibilities of UI mismatch, configuration mismatch, some functionalities may be in extra/less. Overall it leads to break in functionality.

- _The current version is working fine with MS Classic Teams, and will the Standard version support Modern Teams?_ 
Yes, our application works with both classic and new version of teams

- _can we use the same applications (User app, Author App, Graph App) for deployments?_ 
If the app registration already used for one deployment then those can't be used for other.

**Comment by gsv022** [comment]
If you are still facing the issue, please don't hesitate to log a new issue
