### ISSUE TITLE
Need help with bearer token

### ISSUE THREAD

**Issue by LycheeYum** [OfficeDev/microsoft-teams-apps-company-communicator#1329]
I can successfully send a POST to XXXXXXXXX.azurewebsites.net/api/draftnotifications and create a draft notification.

However, I can only do this if I reuse an existing bearer token.

What I'm stuck on is how to generate the needed bearer token.  I believe I'm close though. The snip below generates a token, but that token doesn't work with api/draftnotifications.   Any help or advise would be awesome. Thank you!

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/7239280/1d390736-a47a-4077-b892-d0dda2414725)

**Comment by gsv022** [comment]
Hi @LycheeYum ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @LycheeYum ,
This is not the recommended way to draft messages within CC as this might comes with security risks for the deployed application. However, the token can be generated from [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer).
