### ISSUE TITLE
Confirmation of Change - NotificationData Table

### ISSUE THREAD

**Issue by LycheeYum** [OfficeDev/microsoft-teams-apps-company-communicator#1330]
Hello,

In version v5.4.1 we were able to add rows to the NotificationData table and drafts were created.  Has this ability been removed in version 5.5?

If so, is there a setting that can enable this ability?

**Comment by gsv022** [comment]
Hi @LycheeYum ,
Thanks for raising the query. Could you please let us know the reason for adding the entry directly in NotificationData table. Are you not able to draft the messages at the application level?

**Comment by LycheeYum** [comment]
I'd like to use Microsoft Forms & even Power Apps and Power automate to allow anyone to submit a draft for approval by the authorized authors.

Like this [Power ](https://github.com/Hickey77/ccapproval)

**Comment by gsv022** [comment]
Hi @LycheeYum ,
Our support scope is very limited with the standard version. We won't be able to assist on this request as it will fall under customization. Please let us know if you have any issues with the standard version.

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

**Comment by LycheeYum** [comment]
I understand.  What this a change that was made between 5.41 and 5.5?

**Comment by gsv022** [comment]
@LycheeYum , Please refer to [release section](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Release-notes) for more details
