### ISSUE TITLE
Some Users are not receiving Cards - 16000 users

### ISSUE THREAD

**Issue by JasGo00** [OfficeDev/microsoft-teams-apps-company-communicator#1331]
We have 16000 users that are not receiving messages from the communicator
![Communicator error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/dd80d01d-e0a0-448f-b9a5-27e13d37fef0)

**Comment by gsv022** [comment]
Hi @JasGo00 ,
Thanks for raising the query. Could you please share the export results of the latest sent message

**Comment by JasGo00** [comment]
also I do not understand what Mail ID is ? do you need my email address?

**Comment by gsv022** [comment]
@JasGo00 , Share your email id(outlook id or teams id) so that we can discuss the issue internally.

**Comment by JasGo00** [comment]
jasmin.gokovic@us.bosch.com

**Comment by JasGo00** [comment]
OK, waiting on your email :)

**Comment by JasGo00** [comment]
I can not see the Teams chat you have invited me to here is the message I get when I try to join the chat

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/d91cf721-4dd3-45a7-a760-270ee8c187b6)

**Comment by gsv022** [comment]
No Problem, We have sent a mail just now. Please respond accordingly.

**Comment by JasGo00** [comment]
I am still waiting on your reply about the troubleshooting meeting... I am still available Today and Tomorrow 10:30am-12am EST, and on Friday from 9-10am EST

**Comment by gsv022** [comment]
> I am still waiting on your reply about the troubleshooting meeting... I am still available Today and Tomorrow 10:30am-12am EST, and on Friday from 9-10am EST
@JasGo00 , Call Summary-
•	User mentioned that he performed migration from v4.x to v5.x recently.
•	As a part of troubleshooting, we noticed that within the graph, author app there are good number of extra permissions were added. So, we removed unwanted permissions and kept required one as per migration guide.
•	The reason that "sending 0 of x" showing is due to deployment failure occurred in send function. So, we performed sync for send function. The issue got cleared.
•	We asked user to send the message again, it is getting delivered with no errors.
•	But for 4th sending option, we asked user to wait for some time to reflect API permissions as there were modifications performed in the call.

**Comment by JasGo00** [comment]
we do not have any message to send to the entire organization at the moment, so this test will have to wait

**Comment by JasGo00** [comment]
Hello
We have sent another message to the entire company and still see over 10K undelivered messages, so the issue has not been resolved

**Comment by JasGo00** [comment]
any update on this

**Comment by freserovski** [comment]
We have the same problem
**From reading out the "SentNotificationData" azure table:**
TotalMessageCount		Succeded		RecepientNotFound                Failed
15088					14181		752 (404-user not found)        155 (that was users who blocked bot)

**On form in message details is written:**
Results
Success : 14,181
Failure : 155

When user is related to 404 error it helps that we clean up the entry from "UserData" azure table. New entry is created with **same values** as before and after that it works for user again. Question is, why it wasn't working before, the ConversationID is the same when it's re-created.
Problematic is also, that 404 errors are not in visible statistics on Message details and we get "blured" image about success rate of send out.

**Comment by JasGo00** [comment]
@freserovski Thanks for your message. Our table is so large that if I sort for error 404 it fails and I can not get any information, also I have 15000 failed 404 users and I would have to go line by line to delete, this is not possible for me.

**Comment by JasGo00** [comment]
the actual failure count has increased from before 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/60f49282-3497-4691-aadb-7532af8220f5)

**Comment by gsv022** [comment]
We are following internally.

**Comment by gsv022** [comment]
@JasGo00 , We have shared a work around over the mail. Please check and perform.

**Comment by freserovski** [comment]
Hi

I would also kindly ask for the update if it was implemented.

Have a nice day
Marko

**Comment by JasGo00** [comment]
The workaround did not work for me because the data that we need to delete is not in the same table as the one we query. 
I replied to the email with more info.

**Comment by gsv022** [comment]
Hi @JasGo00 ,
Could you please send couple of messages org wide and let us know how it goes.

**Comment by JasGo00** [comment]
why? did you change something on the back end? what's different this time?

**Comment by JasGo00** [comment]
we just sent another message and see many failing again so nothing has changed, still the same issue

**Comment by JasGo00** [comment]
Please do not close this issue

**Comment by gsv022** [comment]
Hi @JasGo00 ,
We will be closing this issue for now, once the implementation is done we will keep you posted over mail.

Thank you.
