### ISSUE TITLE
Post deployment of crop communicator 

### ISSUE THREAD

**Issue by ManasaMShastri** [OfficeDev/microsoft-teams-apps-company-communicator#1332]
Hi 
Post deployment of crop communicator 

in teams we are not able to search the users

Kindly find the SS for the same
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148181089/5e0f2a04-8747-4bb2-ab46-423bb169431f)

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by ManasaMShastri** [comment]
Hi we have tried the steps but we are getting the same issue.

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
How about fourth sending option- able to send the message to any groups?

**Comment by ManasaMShastri** [comment]
No Actually we are not getting the option in the fourth sending option also.

**Comment by ManasaMShastri** [comment]
In fourth sending option also we are getting the same issue.
