### ISSUE TITLE
UpdateSiteSourceControl not reachable via ARM installation

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-company-communicator#1333]
When trying to do an installation via the ARM template, I'm getting the following error. Any idea why I'd be getting a 503 error here? It's pretty consistent.

Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (503) Server Unavailable.

**Comment by gsv022** [comment]
Hi @glblinck ,
Thanks for raising the query. 
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function** from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by glblinck** [comment]
So this install should not be completing successfully anymore, no matter how many times it's tried? This is normal? 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/61463212/d0e2f1a5-d1a2-4341-8df7-aaa04c751bd2)

**Comment by gsv022** [comment]
@glblinck , We already mentioned in the above response saying that after updating individual resources no need to go for re-deploy again. Please proceed with next steps of deployment if the resources turned successful in the logs section individually.

**Comment by glblinck** [comment]
The prep-function still does not get to a completed state in the logs. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/61463212/ddc3c602-ff2c-4646-9bb2-4614e559d91f)
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd
  Creating directory "C:\local\Temp\8dc28074f9c2016\SyncAllUsersActivity".
One or more errors occurred.
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd

**Comment by gsv022** [comment]
Hi @glblinck ,
Please perform SYNC for prep-function again. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/79f87e6c-8395-442b-b43c-b908c4abd59c)

**Comment by glblinck** [comment]
I found that I had to disconnect the app service and all three function apps from GitHub, then fully redeploy. Once I did that, then I got to a successful deployment. I've had this multiple times, as well. This doesn't seem to get to a successful completion the on the first install attempt anymore.

**Comment by gsv022** [comment]
Hi @glblinck ,
The deployment comprises of multiple resources creation and follows incremental approach. Please make sure that there is proper network connectivity, not going into idle state etc., 

Please let us know if you are facing any issue currently, we will be happy to assist you.
