### ISSUE TITLE
Company communicator message not able to send its Queued.

### ISSUE THREAD

**Issue by ManasaMShastri** [OfficeDev/microsoft-teams-apps-company-communicator#1334]
Hi,

Kindly find the SS after sending the msg the msg is queued for long time and and sent

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/148181089/f074d74e-f272-4869-9343-85a683cc76d2)

**Comment by gsv022** [comment]
Hi @ManasaMShastri ,
Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly or not. Especially check for **supported account type** should be- **My Organization**  for graph app. 
Author app- Multiple Organization
User app- Multiple Organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

- _Is there any documentation that explains how can we use the apps?_
 You can find the detailed information on the features available in Company Communicator app in this [section](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/User-manual) .

**Comment by alliehutch** [comment]
I am having the same issue.  I went through and verified all of those settings and everything appears to be correct.  I did get the first common error listed in the troubleshooting log (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure) but I followed the steps and did a "sync" and it appears that it was successful.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/158630126/8fd0364a-98d3-46cb-b1e8-0750c5f3d5c2)

**Comment by alliehutch** [comment]
And actually I guess I am not having the exact issue.  Mine is not stuck on queued it is stuck on sending:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/158630126/2c3dedec-4dd8-4929-893e-ffc96f1c3fbc)

**Comment by mchandu2020** [comment]
We are facing the same issue messages are queued and we have provide all permissions but its not working. Is there any documentation guide to troubleshoot the issue?
