### ISSUE TITLE
Author UI Crash on NEW Teams

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#1335]
Hello there. 

As many recently, we are also experiencing the same issue with the **new** Teams (classic works fine). 

Important to notice that our app is being stable (no syncs/releases) since October last year. Just recently stopped working (with the **new** Teams).

Screenshot of our last Sync:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/42776398/c498c811-1bf2-4622-8a23-7abb7822afa4)

**Comment by gsv022** [comment]
Hi @victorsimonlee ,
 Thanks for raising the query. Please perform SYNC for app service and let us know how it goes.

**Comment by victorsimonlee** [comment]
Hello, thanks for following up.

SYNC performed with success for the app service, but it did not solve the problem.

I also tried clearing Teams cache, no difference.

**Comment by victorsimonlee** [comment]
Hello again, @gsv022 .

After the SYNC, I have cleared my browser and new Teams cache, and now it is working again!

Please see for reference: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1337
