### ISSUE TITLE
Error in CC Author with the new teams desktop version only

### ISSUE THREAD

**Issue by Boy2607** [OfficeDev/microsoft-teams-apps-company-communicator#1336]
Follow the guide to update from 5.4x to 5.5 and verified all the parameters mentioned in the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) are added in the app service configuration section, then I found this error message in the new teams version (Desktop version only) at cc author. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/300cbaf3-0363-4e06-806a-1ea11e5f1606)

It is working properly on web version.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/090cadbc-7805-4f19-9781-f6a33b2f6900)

All runtime version for function apps are changed to ~4

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/b7d34cd4-7b04-4ea8-be38-53ae854b9bbe)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/aeb9aae3-f5f3-40f9-aabe-191d17bd9566)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/1d3bb66e-2186-4901-8cb7-2082f23492d1)

Deployment status of app service >> We synced app service many time but it's still occur this issue.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/4fd6b7ba-2e89-4177-bbcf-3d5817e46fc9)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/129176882/966a2c91-bcdc-4ecf-a339-caa21f4f1627)

Kindly advise how to fix this issue?

**Comment by gsv022** [comment]
Hi @Boy2607 ,
Thanks for raising the query. There will be some cache issue occurred at the desktop client. Please give sometime and even restart the system would also do the needful.

**Comment by fajr365** [comment]
The Cache Location has changed. It worked for my issues.
Adjusted instructions that cover both app types.
1.	If Teams is still running, right-click the Teams icon in the taskbar, and then select Quit.
2.	Open the Run dialog box by pressing the Windows logo key + R
3.	In the Run dialog box, copy/paste:
•	**new Teams app: C:\Users\%username%\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe** 
•	classic Teams app: %appdata%\Microsoft\Teams
4.	Delete all files and folders in the directory.
5.	Restart Teams.
