### ISSUE TITLE
New Teams Cache Location to Clear - Not an Issue but General Information

### ISSUE THREAD

**Issue by fajr365** [OfficeDev/microsoft-teams-apps-company-communicator#1337]
Adjusted instructions that cover both app types.
1.	If Teams is still running, right-click the Teams icon in the taskbar, and then select Quit.
2.	Open the Run dialog box by pressing the Windows logo key + R
3.	In the Run dialog box, copy/paste:
•	**new Teams app: C:\Users\%username%\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe** 
•	classic Teams app: %appdata%\Microsoft\Teams
4.	Delete all files and folders in the directory.
5.	Restart Teams.

**Comment by victorsimonlee** [comment]
Hello there.

Just to let everyone know that clearing the cache for the new Teams has solved the issue of the Authors app crashing.!
Also true for the browser version - clearing the cache made it work.

one note though: **DO NOT** delete everything under **MSTeams_8wekyb3d8bbwe**. Or Teams won't open anymore.. Delete the **LocalCache** folder only!

**Comment by gsv022** [comment]
Hi @fajr365 @victorsimonlee ,
Thanks for sharing the detailed steps. Please let us know if you are facing any issue with new teams otherwise we can make it closure.

**Comment by victorsimonlee** [comment]
@gsv022 after clearing the Teams cache, bot new Teams & Web versions are working just fine. 
Thank you.

**Comment by ichiro22-koji** [comment]
皆さんこんにちは
Teamsの「バックグラウンドでアプリケーションを開く」の設定を変えたとき、
この設定情報はキャッシュのどこに保存されるでしょうか？
MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\tfw　
よろしくお願いします。
