### ISSUE TITLE
Powershell Deployment failing

### ISSUE THREAD

**Issue by allthetrouts** [OfficeDev/microsoft-teams-apps-company-communicator#1343]
Hi - The latest powershell deployment is forcing a minimum cli version of 2.49 
Azure CLI is installed and meets the minimum required version (2.49.0). 
- Application insights says cli needs to be atleast 2.5+ so if you install the latest cli it will then fail saying:
ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False

Based on a previous issue it looks like cli above 2.36 isnt recommended? Which versions of these software will this actually currently work with? Currently I seem to be stuck.

**Comment by gsv022** [comment]
Hi @allthetrouts ,
There is a existing issue with PowerShell deployment which we will be addressing in the future releases of CC. To unblock yourself, we recommend you to proceed with manual deployment procedure.
