### ISSUE TITLE
SSO Support for Company Communicator

### ISSUE THREAD

**Issue by marianocalero** [OfficeDev/microsoft-teams-apps-company-communicator#1344]
Hello team,

Does the Company Communicator app support SSO? 

I have a customer that is unable to use CC on mobile due to having Conditional Access policies set up that are blocking sign in. 

Typically, SSO is used to avoid this error on mobile devices. 

If SSO is supported, can you please guide me on how this can be set up? 

Thank you.

**Comment by gsv022** [comment]
Hi @marianocalero ,
Thanks for raising the query. Could you please share the error details observed while trying to access CC on mobile with supporting screenshots.
