### ISSUE TITLE
Errors with 404 are not included in statistics

### ISSUE THREAD

**Issue by freserovski** [OfficeDev/microsoft-teams-apps-company-communicator#1345]
We are sending out message to AD Group with cc 15000 members.

**From reading out the "SentNotificationData" azure table:**
- TotalMessageCount: 15088			
- Succeded: 14181				
- RecepientNotFound: 752 (404-user not found)                
- Failed: 155 (that was users who blocked bot)

**On form in message details is written:**
Results
- Success : 14,181
- Failure : 155

When user is related to 404 error it helps, that we clean up the entry for that user from "UserData" azure table. New entry is created with **same values** as before and after that it works for user again.
Question is, why it wasn't working before, the ConversationID is the same when it's re-created.
Problematic is also, that 404 errors are not in visible statistics on Message details and we get "blured" image about success rate of send out.
There are missing - RecepientNotFound: 752 (404-user not found errors from azure table "SentNotificationData")    

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/724034/228c9cda-7911-41a3-a925-c1a7edf8a0a9)

**Comment by freserovski** [comment]
I think issue could be connected to the following problem:
[https://learn.microsoft.com/en-us/answers/questions/1477908/ms-teams-bot-receiving-404-when-sending-user-messa](https://learn.microsoft.com/en-us/answers/questions/1477908/ms-teams-bot-receiving-404-when-sending-user-messa)

**Comment by gsv022** [comment]
Hi @freserovski ,
Thanks for raising the query. 

- Recipient Not Found(752), whether you are able to see this failed users data on export data or not. Please confirm.

- Please elaborate more here.
_we get "blured" image about success rate of send out._

**Comment by freserovski** [comment]
Hi
_Recipient Not Found(752), whether you are able to see this failed users data on export data or not. Please confirm._
On export i can't see that data, only 403 (when user block bot). It's not calculated in the Recipients summary in company communicator app.

Please elaborate more here.
we get "blured" image about success rate of send out.
Blured i've meant that there aren't all errors taken in consideration when summary is calculated on message details form:
Results
Success : xyz
Failure : xy

**Comment by gsv022** [comment]
Hi @freserovski ,
We are looking into it and will get back to with proper response soon.

**Comment by gsv022** [comment]
Hi @freserovski ,
Once the message status falls under the category -**Recipient Not Found**. It will be not counted in either as success or failure. But this can be overcome in next sent message. For every message, the failure count seems to be same and failure status showing as recipient not found then we can discuss the issue internally.
