### ISSUE TITLE
Cannot send message to the three first options in Company Communicator

### ISSUE THREAD

**Issue by binruis** [OfficeDev/microsoft-teams-apps-company-communicator#1347]
When we try sending a message with one of the first three options with the author app, it cannot find any group of it, only works the fourth option M365
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/154450580/30c89714-82be-4b3f-8554-f3c8d10e6eb2)

**Comment by gsv022** [comment]
Hi @binruis ,
Thanks for raising the query.  Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue.
