### ISSUE TITLE
After Upgrade from 5.3 to 5.5, Groups Not Populating in Authors App

### ISSUE THREAD

**Issue by Ukiman1014** [OfficeDev/microsoft-teams-apps-company-communicator#1348]
After successfully syncing the app service and functions and installing the Authors app to a team for testing, it's not pulling up any M365 groups.  I am not sure if the down arrow is supposed to show a listing of groups, but I've tried entering in group names with and without spaces, but nothing is coming up.

We did see that the app secrets had expired, so we created new ones, adding them to the key vault, then restarting the app and functions, as outlined in [this issue](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/820). I also checked the app config and none of the key vault references have errors.  Also, we validated that the graph app registration and it has the correct permissions.  I'm at a loss as to what's going on.

Here are the failures:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/22643106/473f88fc-d627-4c27-a9c4-c70418f7ebfe)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/22643106/b9252dcf-8321-4492-95d0-b92bb54b05ff)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/22643106/9996e924-293f-4c8b-ab09-69ea4889895b)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/22643106/e18b07b6-7c0f-400d-9a4c-a35e0cee8f46)

**Comment by Ukiman1014** [comment]
I should also mention that we deployed 5.3 a little over a year ago and it worked fine in testing but then was shelved until now.

**Comment by gsv022** [comment]
Hi @Ukiman1014 ,
I see there is a ticket already opened with ticket no: #1338 by you. Please avoid opening multiple tickets for the same issue. We suggest you to close one of the tickets and continue in only one place.


Coming to the issue it might be due to incorrect update of new secrets in respective places. So please share your mail id(outlook id or teams id) so that we can discuss the issue internally.

**Comment by Ukiman1014** [comment]
> Hi @Ukiman1014 , I see there is a ticket already opened with ticket no: #1338 by you. Please avoid opening multiple tickets for the same issue. We suggest you to close one of the tickets and continue in only one place.
> 
> Coming to the issue it might be due to incorrect update of new secrets in respective places. So please share your mail id(outlook id or teams id) so that we can discuss the issue internally.

Sorry, I was out on PTO since last week.  I would rather not post my ID here, can that be done through some sort of direct messaging?

I thought this might be a separate issue from #1138, but next time I'll try to keep the same issue open.

**Comment by Ukiman1014** [comment]
Okay.  My email is swright@customersbank.com.  Thanks.

**Comment by gsv022** [comment]
We have initiated the conversation internally.

**Comment by gsv022** [comment]
Hi @Ukiman1014 ,
Thanks for joining the call. It is noticed that secrets are incorrectly updated and we corrected it and app started up and running.

User confirmed that issue can be closed.
