### ISSUE TITLE
Export results queued / "InProgress" - never completes

### ISSUE THREAD

**Issue by jdolat-kyndryl** [OfficeDev/microsoft-teams-apps-company-communicator#1350]
We have a new installation version 5.5, App is working well sending messages but export continues to be queued and status in azure table says "in progress".  
One thing I noticed is on a working app the App ID in Teams matches the app ID in the App config table.  
On the not working one for export we noticed that on sending the message the app ID in the app config table did not match the users application client Id.  

We then incremented the two manifests versions and re-uploaded them as version 5.5.1 and issue still persists.  Messages are sent, but no export options.  
Also we changed the ID in the app config table to match our users app to test and still no change

What kind of pictures would help? Or since this is a public forum, would a quick meet be more appropriate?

**Comment by gsv022** [comment]
Hi @jdolat-kyndryl ,
Thanks for raising the query. What is the count of targeted user base?

**Comment by jdolat-kyndryl** [comment]
Our company has 7 communicators set up with a target audience of 115K when each are used to their full potential.  
This one being new, is still in it's testing phase, so we are only sending messages to a M365 security group consisting of 5 individuals (myself included)

**Comment by gsv022** [comment]
Hi @jdolat-kyndryl ,
Please share your mail id(outlook id or teams id) so that we can discuss the issue internally.

**Comment by jdolat-kyndryl** [comment]
Hi @gsv022 - my e-mail is joe.dolat@kyndryl.com

**Comment by jdolat-kyndryl** [comment]
Hi @gsv022 - Please let me know when you have time to discuss. Thanks!

**Comment by gsv022** [comment]
We have started the conversation internally. Please check and acknowledge.
