### ISSUE TITLE
Advice on whether to upgrade or re-install?

### ISSUE THREAD

**Issue by normansolutions** [OfficeDev/microsoft-teams-apps-company-communicator#1351]
Not sure if this is the best place to post a question - but in short, we are running Version 4.1.2 and clearly need to get this updated to the most recent release.

Would the general advice be to attempt the upgrade path (which almost feels like a re-install anyway - probably due to the difference in version numbers) or would it be better to create a new install side by side (named slightly differently etc) and then remove the old version?  Would this be a safer and more recommended approach or is an in-place upgrade recommended?

Many thanks

**Comment by gsv022** [comment]
Hi @normansolutions ,
Thanks for asking! It's best to follow the migration guide step by step. Take some time to read through it and get everything ready before you start. That way, the migration should go smoothly without any surprises.

If you're not worried about keeping the older data in version 4.1.2, it's okay to start fresh with the new version of the CC application. This might make things easier and cleaner.

**Comment by normansolutions** [comment]
Thanks so much for the information - much appreciated
