### ISSUE TITLE
current view boot of company in actual version

### ISSUE THREAD

**Issue by gvelez83** [OfficeDev/microsoft-teams-apps-company-communicator#1352]
Good day

congrats your hels, today we have use company comunicator throught teams in version 5.4.1, inside that version the final user (rol author) dont look the atributes to company or button to compapy witch sending messanger to all users to organizacion.

previusly microsoft gave us recomendation to update new version (5.4.1) BOOT OF COMPANY;  appreciate your help to know how this update should be done and if possible if someone from the community gives us a space and guides us in a small call via teams how to do this teams boot update

in attach file have the evidence, 

![current actual view of companny](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/155109470/42338d39-f410-4504-b1a2-a812d2dceb4f)

Thans for your help, attent to comentaries
congrats!

**Comment by gsv022** [comment]
Hi @gvelez83,
Thanks for raising the query. Could you please share the screenshot showing the deployment status of App service. Here is the reference.
<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">
