### ISSUE TITLE
Author App is partially available to users if published.

### ISSUE THREAD

**Issue by Sheshank-TCS** [OfficeDev/microsoft-teams-apps-company-communicator#1354]
Hi Team, In the recent version (5.5.1) of the Company Communicator, I deployed both the Author and User apps via the Teams admin console. In earlier versions, if a non-authorized UPN user attempted to add the Author app, it would get added in Teams but would not open, displaying an authorization error. However, in version 5.5.1, users can add the app and also view the card design module, which was previously unavailable. Despite this, they still cannot send messages from the Author app. Can we enforce the same level of restriction as in the earlier version, where non-authorized users were completely restricted from accessing the app?

Below are the screenshots of the old version author app added by random users after publishing it in Teams admin via Manage Apps.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/daee5ff4-e5c4-4091-88c7-71a8abc05965)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/f74eab15-b30d-4999-b06b-4a265e262407)
Below is the screenshot of the new version 5.5.1 author app added by random users after publishing it in Teams Admin via Manage Apps.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/744973b8-1d6d-465c-b122-954d0c94fddc)

**Comment by gsv022** [comment]
Hi @Sheshank-TCS ,
Thanks for raising the query. Normally, in any version unauthorized users won't have access to CC author app unless their UPN is added to the UPN list. Coming to the error, check with that specific user on browser version of teams so that user will get relevant error when tries to access the application.

**Comment by Sheshank-TCS** [comment]
Hi @gsv022  I have validated on teams web version also and its still available. Though the message cannot be sent but its not giving any access denied error. Please suggest how this can be fixed.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/b0fc4fff-e902-4e35-8351-2ecf345a10d9)

**Comment by gsv022** [comment]
Hi @Sheshank-TCS ,
Is it happening in New Teams as well?

**Comment by Sheshank-TCS** [comment]
Yes, this is happening with New teams, Old teams and Web version. However old Company communicator app is restricted everywhere for the users who are not Authors.

**Comment by gsv022** [comment]
Hi @Sheshank-TCS ,
Please share your mail id so that we can discuss the issue internally.

**Comment by Sheshank-TCS** [comment]
sheshank.dhoot@outlook.com you can use this one.

**Comment by gsv022** [comment]
I have sent a mail. Please check and respond

**Comment by Sheshank-TCS** [comment]
Hi Sai, Thanks for your response, I have reverted to it.

**Comment by chrischowsos** [comment]
I am facing the same issue, is there any update of this issue?

**Comment by Sheshank-TCS** [comment]
Hey Chris, Still waiting to hear from the team.

**Comment by gsv022** [comment]
Hi @Sheshank-TCS ,
We have tried in different tenants and not able to replicate the issue. Please deploy one more instance and see the issue if persists.

Keep us posted

**Comment by Sheshank-TCS** [comment]
Working towards the implementation will keep you posted.

**Comment by gsv022** [comment]
Sure, please keep us posted

**Comment by Sheshank-TCS** [comment]
Hi Sai, Just a query, have you validated setting up a second instance when existing instance exist. May be if you are setting up a single new instance it is not giving error.

**Comment by gsv022** [comment]
Hi @Sheshank-TCS ,
We will check out this scenario and let you know.

**Comment by Sheshank-TCS** [comment]
@gsv022 We tried setting up the new instance and the Function app failed. Please suggest whether should I manually sync the resource from the deployment center again.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/29fe9a6d-af8e-467f-a0a7-f61673ce9dc9)

**Comment by gsv022** [comment]
Hi @Sheshank-TCS ,
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(Any failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by Sheshank-TCS** [comment]
We have successfully deployed the latest App version 5.5.2 and the issue has been resolved it's throwing the disclaimer message as expected when nonauthorized members add the App. Thank you Sai for all the help and support, appreciate it.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/708678be-9cea-40f3-8320-9e7ccb5e95f1)
