### ISSUE TITLE
How to update the "About Tab" in the User communicator App

### ISSUE THREAD

**Issue by Axael85** [OfficeDev/microsoft-teams-apps-company-communicator#1355]
Hello Team,

I was trying to find information about this but it is not showed on the USers guide. Could you please help us to understand where we can update the the "About" Tab in the user communicator app?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/f8e84ed9-e2c4-4fba-b231-580f0158df6c)

Regards

**Comment by gsv022** [comment]
Hi @Axael85 ,
Thanks for raising the query. 

- In the user manifest file, about section can be updated as per your requirement.
<img width="674" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9cf1b60f-e4b2-4183-a7d9-d71aaac3202a">

- Once the modifications are done, delete the existing user app from teams and re-upload again with new modifications.
