### ISSUE TITLE
Infinite Loop Issue in useEffect for Requesting Draft/Sent/Scheduled Messages

### ISSUE THREAD

**Issue by Mirko92** [OfficeDev/microsoft-teams-apps-company-communicator#1356]
The following useEffect hooks create a loop until their response is empty.

```ts
React.useEffect(() => {
    if (scheduledMessages && scheduledMessages.length === 0) {
      GetScheduledMessagesAction(dispatch);
    }
  }, [scheduledMessages]);
```

```ts
 React.useEffect(() => {
    if (draftMessages && draftMessages.length === 0) {
      GetDraftMessagesAction(dispatch);
    }
  }, [draftMessages]);
```

```ts
React.useEffect(() => {
    if (sentMessages && sentMessages.length === 0) {
      GetSentMessagesAction(dispatch);
    }
  }, [sentMessages]);

```

Possible fix: 
Consider to use a useEffect hook with empty array as dependency.

```ts
React.useEffect(() => {
    if (sentMessages && sentMessages.length === 0) {
      GetSentMessagesAction(dispatch);
    }
  }, []);

```

ADVICE
Consider leaving at least one draft and scheduled message to avoid triggering the loop until a fix is implemented. This helps in preventing unnecessary thousand requests to the app service.

**Comment by gsv022** [comment]
Hi @Mirko92 ,
Thanks for sharing your suggestions. We will check and do the necessary.

**Comment by Mirko92** [comment]
I see: Needs author feedback. 

Have you got any questions ?
Any news ?

**Comment by gsv022** [comment]
Nothing from our end, we will review it. If there are no further queries, you can close out the issue.
