### ISSUE TITLE
Company Communicator

### ISSUE THREAD

**Issue by rsterlin** [OfficeDev/microsoft-teams-apps-company-communicator#1358]
I recently followed the GitHub documentation to standup the company communicator application in our environment and when i began testing its functionality the tasks are stuck on "queued" and a message is never sent.

**Comment by rsterlin** [comment]
![2024-02-28_14h05_52](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161730652/b1766c4f-a481-4b92-b830-db88cd6be66f)

**Comment by gsv022** [comment]
Hi @rsterlin,
Please cross-verify the set-up authentication [steps](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) done for graph app correctly or not. Especially check for **supported account type** should be- **My Organization**  for graph app. 
Author app- Multiple Organization
User app- Multiple Organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

**Comment by rsterlin** [comment]
Does the APi Permissions and authentication settings need to be updated on all three app registrations or just the author app registration?

**Comment by rsterlin** [comment]
![2024-03-04_15h19_44](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161730652/f8e13ad8-b45b-43f4-aa0f-32dea9c5db19)
![2024-03-04_15h20_31](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161730652/9c370ed1-fa51-477f-bb2e-2cb1edc0715a)

**Comment by gsv022** [comment]
Hi @rsterlin ,

- _Does the APi Permissions and authentication settings need to be updated on all three app registrations or just the author app registration?_
This step should be done for graph app registration. 

- Please remove unnecessary permissions added in the API permission section. Permissions should be as per the deployment guide.

**Comment by rsterlin** [comment]
This has been corrected and the issue still persist. Can we troubleshoot the issue through a telephone call?

**Comment by rsterlin** [comment]
I can be reached out teams. Randall.Sterling@stryker.com or   +1 551 500 2510

**Comment by gsv022** [comment]
We have started the conversation internally. Please check and respond

**Comment by rsterlin** [comment]
Responding back to the thread to continue support via email/phone

Randall Sterling, CSM
IT Telecom Sr Administrator, Digital Collaboration
Stryker
2 Pearl Court
Allendale, NJ 07401
O: (551) 500-2510
***@***.******@***.***>
Certified ScrumMaster(r)<https://certification.scrumalliance.org/accounts/1589609-randall-m-sterling/certifications/1867223-csm>

***@***.******@***.***<https://www.credly.com/badges/33d77349-21c8-47db-968f-3b21c5c85f6d/public_url>

Harmony | Individualization | Responsibility | Realtor | Learner

**Comment by rsterlin** [comment]
Good day, Company Communicator team.

I’m the Microsoft CSAM for this customer and am looking to get an update on the progress of this support ask.  Can you please reply here and let us know how we can connect?

I do not know what your comment below means:   “We have started the conversation internally. Please check and respond.”  Who are you advising to “check and respond?


Thank you.

[Microsoft]
Nichole Martin
Sr. Customer Success Acct Mgr
Health and Life Sciences

Office: 248-200-5279
Mobile: 586-596-6025
***@***.******@***.***>

﻿If at any time during your contract with Microsoft Services, you feel that the services received
are not of the quality that you expect, please tell me so I can address your concerns.

***@***.***[Microsoft Certified: Security, Compliance, and Identity ***@***.***

Upcoming OOO Alert:
TBD



From: Sterling, Randall ***@***.***>
Sent: Tuesday, March 12, 2024 3:36 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; Nichole Martin ***@***.***>; Ashton, Russell ***@***.***>; Duane Friedlander ***@***.***>; Thaddeus Kurowski Jr ***@***.***>
Cc: Mention ***@***.***>
Subject: [EXTERNAL] RE: [OfficeDev/microsoft-teams-apps-company-communicator] Company Communicator (Issue #1358)

Responding back to the thread to continue support via email/phone

Randall Sterling, CSM
IT Telecom Sr Administrator, Digital Collaboration
Stryker
2 Pearl Court
Allendale, NJ 07401
O: (551) 500-2510
***@***.******@***.***>
Certified ScrumMaster®<https://certification.scrumalliance.org/accounts/1589609-randall-m-sterling/certifications/1867223-csm>

***@***.******@***.***<https://www.credly.com/badges/33d77349-21c8-47db-968f-3b21c5c85f6d/public_url>

Harmony | Individualization | Responsibility | Realtor | Learner

**Comment by gsv022** [comment]
Hi @rsterlin ,
We have started the conversation over teams. Please check and respond
<img width="725" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/2ed6bafd-670d-4aba-b1b5-b2a04a81b220">
