### ISSUE TITLE
New install of 5.5.1 Sending doesn't complete

### ISSUE THREAD

**Issue by JTyler70** [OfficeDev/microsoft-teams-apps-company-communicator#1359]
I have a few issues with a new installation. The first is that no teams show up when I try to send choose that option. I can use the bottom two options, send chat to every and send to chat of o365 groups.
<img width="352" alt="deployment" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161762248/69085a75-9606-4251-b29c-9ef9b9dbe129"> . The second issue is that when I send to all users or to an  o365 group the message does successfully send to all users and to the group but it never shows as complete in the metrics. here's a screenshot 
<img width="596" alt="metrics" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161762248/81d89145-cfca-44df-b618-f84ec250502d"> , If I click on the delivery status they all show suceeded 
<img width="483" alt="succeed" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161762248/d1a89c59-f0b9-4ea3-9399-f9d960628c28">

**Comment by gsv022** [comment]
Hi @JTyler70,
Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by JTyler70** [comment]
awesome that fixed the first issue. Any idea on the second issue?

**Comment by gsv022** [comment]
Hi @JTyler70 ,
Please try deleting the author and user app from the teams admin center and re-upload them. 

Keep us posted.
