### ISSUE TITLE
Sorry, an error occurred while trying to access this service

### ISSUE THREAD

**Issue by dkassis-rag** [OfficeDev/microsoft-teams-apps-company-communicator#1360]
Hello,
When I switched to the new Team Pro Desktop APP and try to open teams company communicator. 
I got this error (Sorry, an error occurred while trying to access this service)

<img width="590" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/114713093/6dca0a5a-eb5b-473b-97ee-8f0ec4b2df55">

Thank you,
David

**Comment by gsv022** [comment]
Hi @dkassis-rag ,
Thanks for raising the query. 

- What is the version of the application?
- Please open the teams in any browser and try accessing the application.

**Comment by Sid2204** [comment]
Hello,

I am also facing the same issue. When trying to open the author app on new version of teams it gives error "Sorry, an error occurred while trying to access this service." However as soon as I switch to the older version of teams it starts working. 

1) New version of teams:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134293914/f31ba7ac-f650-4e1b-a313-4474a2361efa)

2) When switched back to classic teams:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134293914/983edd31-6de3-451b-9cf6-8f1a8e24c7dd)

**Comment by Sid2204** [comment]
@dkassis-rag  where you able to resolve this, If yes can you please share the steps with me as well.  
@gsv022 
Can you please assist here I have checked the status of App Service and its is successfully:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134293914/487c60c8-cbf0-49f8-a860-80431c40cfda)
 
Have restarted the app service as well. Still showing the same error on new version of teams.

**Comment by dkassis-rag** [comment]
It's resolved now please close this ticket. 

Thank you,
David

**Comment by Sid2204** [comment]
@dkassis-rag Can you please share the steps you followed to resolve this issue.
