### ISSUE TITLE
Drop Down List 

### ISSUE THREAD

**Issue by kdcrhoward** [OfficeDev/microsoft-teams-apps-company-communicator#1361]
Hi. Thanks for all the work you guys do developing this.
With an older version (5.4) we tested we could send to office 365 groups.  The new Version 5.5 it is not working.  BTW the whole application had to be installed manually as the powershell scripts do not work anymore.  mismatch with az cli versions. which apparently is a known issue.  Sending in chat to everyone seems to work
<img width="514" alt="CC Dropdown error" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161986756/660d62af-f85a-438c-aa37-95abc8bddc01">

**Comment by gsv022** [comment]
Hi @kdcrhoward ,
Thanks for raising the query. Could you please respond to the below queries.

- Were all sending options working earlier in v5.4?
- As per the migration guide, check whether the [parameters](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) mentioned are added to the app service configuration or not.
- Please migrate the application insights as per [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#migrating-classic-application-insights-to-workspace-based-application-insights)

**Comment by gsv022** [comment]
Hi @kdcrhoward,

- Are you able to export the data for any of the sent messages? if yes, please share a screenshot.
- For fourth sending option, please type the name of the team name without any spacings, it will give the details (if not tried)
- Please cross-verify set-up authentication step in the graph app registration correctly done or not. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/37be910d-f15e-4ba3-b74e-812b41d2bfa2)

**Comment by kdcrhoward** [comment]
Hello Sai.
A full resync has fixed the issue.  All working as it should now.

Thank you for your efforts
R

**Comment by gsv022** [comment]
Please feel free to log the issue if you encounter any. We will be happy to assist you. Thank you
