### ISSUE TITLE
Unable to migrate the company communicator- Getting Conflict & Rolebased issues. 

### ISSUE THREAD

**Issue by Prasadj2024** [OfficeDev/microsoft-teams-apps-company-communicator#1362]
we are facing the issue's company communicator migration. we are facing some issue. Microsoft people are asking to connect GitHub support. I am getting this error.
"Tenant ID, application ID, principal ID, and scope are not allowed to be updated. (Code: RoleAssignmentUpdateNotPermitted)"

<img width="257" alt="Error" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161813768/ff5f22b9-a300-4ebd-9ed4-c3735b171d8a">

**Comment by gsv022** [comment]
Hi @Prasadj2024 ,
Thanks for raising the query. Please respond to the below query

- From which version the migration is being performed?

**Comment by Prasadj2024** [comment]
Hi Sai,
Thanks for your email, I am performing from v4.

Thanks,
Prasad.

**Comment by gsv022** [comment]
@Prasadj2024 , As you are migrating v4 to latest please follow this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5) step by step.

Please share the screenshot showing the deployment failure along with the resources failed.

**Comment by Prasadj2024** [comment]
Hi Team,
Yes we followed the same steps, V4 to V5.

Under the deployment section, it’s failing. We tried multiple times, Pls see the below screenshot.

Currently, I am getting below error. Let us know your free time, will have a remote session.
{
  "code": "BadRequest",
  "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",
  "details": [
    {
      "message": "There was a conflict. Conflict with existing ScmType: ExternalGit"
    },
    {
      "code": "BadRequest"
    },
    {}
  ]
}

Thanks,
Prasad.

**Comment by Prasadj2024** [comment]
Hello Sai,

We are facing issues with Teams packages, GUID’s. Shall we connect remotely? pls provide your availability.

Thanks,
Prasad

**Comment by Prasadj2024** [comment]
Hi Sai,
finally we did the migration, but we are not able to change the name’s in manifest. if we change the names not able to upload the package into Teams admin apps. Will you be able to help?

***@***.***

Can we maintain External Git for two Resource groups in same tenant. Like one is UAT and another is PROD with different names? Or do we need to maintain Azure repo?

***@***.***

Thanks,
Prasad.

**Comment by gsv022** [comment]
Hi @Prasadj2024 ,
Please share the manifest files with the updated names. We will look into it.

**Comment by Prasadj2024** [comment]
Hi Sai,

We started the Prod migration, unfortunately, we are getting below error while sync the code in deploy centre. Pls see the below screenshot.

***@***.***


I am attaching the UAT manifest files as well for name change issue.


Thanks,
Prasad.

**Comment by Prasadj2024** [comment]
This is the error we are receiving Sai. While deploying.

***@***.***

Thanks,
Prasad.

From: Prasad Jonnalagadda ***@***.***>
Sent: Monday, 18 March 2024 1:11 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

Hi Sai,

We started the Prod migration, unfortunately, we are getting below error while sync the code in deploy centre. Pls see the below screenshot.

***@***.***


I am attaching the UAT manifest files as well for name change issue.


Thanks,
Prasad.

**Comment by Prasadj2024** [comment]
We did scale up and tried, now getting this error “The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'”

{
  "code": "DeploymentFailed",
  "target": "/subscriptions/c0a4331c-093c-478b-a1b3-d997816b2300/resourceGroups/rg-corpitcomm-01/providers/Microsoft.Resources/deployments/Microsoft.Template-20240318165748",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "ResourceDeploymentFailure",
      "target": "/subscriptions/c0a4331c-093c-478b-a1b3-d997816b2300/resourceGroups/rg-corpitcomm-01/providers/Microsoft.Web/sites/sincorpsyscomm/sourcecontrols/web",
      "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
    }
  ]
}

Thanks,
Prasad.

From: Prasad Jonnalagadda
Sent: Monday, 18 March 2024 4:08 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

This is the error we are receiving Sai. While deploying.

***@***.***

Thanks,
Prasad.

From: Prasad Jonnalagadda ***@***.******@***.***>>
Sent: Monday, 18 March 2024 1:11 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

Hi Sai,

We started the Prod migration, unfortunately, we are getting below error while sync the code in deploy centre. Pls see the below screenshot.

***@***.***


I am attaching the UAT manifest files as well for name change issue.


Thanks,
Prasad.

**Comment by gsv022** [comment]
Hi @Prasadj2024 ,
Thanks for raising the query. 
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by Prasadj2024** [comment]
Hello Sai,

Same thing we did, still getting below error

***@***.***

***@***.***

Thanks,
Prasad.

**Comment by Prasadj2024** [comment]
In Addition, I am seeing this also in some of the functions

***@***.***

Thanks,
Prasad

From: Prasad Jonnalagadda ***@***.******@***.***>
Sent: Monday, 18 March 2024 8:11 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

Hello Sai,

Same thing we did, still getting below error

***@***.***

***@***.***

Thanks,
Prasad.

**Comment by Prasadj2024** [comment]
Hello Sai,

Actually we are doing in Production, we requested only one day for downtime. Now unable to complete, Pls  provide your convenient time, we will do live troubleshooting. In All functions we are getting below error.

***@***.***

***@***.***

Thanks,
Prasad
+65-86708039
From: Prasad Jonnalagadda
Sent: Monday, 18 March 2024 8:41 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

In Addition, I am seeing this also in some of the functions

***@***.***

Thanks,
Prasad

From: Prasad Jonnalagadda ***@***.******@***.***>
Sent: Monday, 18 March 2024 8:11 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

Hello Sai,

Same thing we did, still getting below error

***@***.***

***@***.***

Thanks,
Prasad.

**Comment by Prasadj2024** [comment]
In App service,

Below is the error we are getting

Error: Cannot find module 'C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\fork-ts-checker-webpack-plugin\lib\index.js'. Please verify that the package.json has a valid "main" entry
Failed exitCode=1, command=npm run build
    at tryPackage (node:internal/modules/cjs/loader:353:19)
An error has occurred during web site deployment.
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-dev-utils\ForkTsCheckerWebpackPlugin.js:10:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',

From: Prasad Jonnalagadda
Sent: Monday, 18 March 2024 9:23 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

Hello Sai,

Actually we are doing in Production, we requested only one day for downtime. Now unable to complete, Pls  provide your convenient time, we will do live troubleshooting. In All functions we are getting below error.

***@***.***

***@***.***

Thanks,
Prasad
+65-86708039
From: Prasad Jonnalagadda
Sent: Monday, 18 March 2024 8:41 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

In Addition, I am seeing this also in some of the functions

***@***.***

Thanks,
Prasad

From: Prasad Jonnalagadda ***@***.******@***.***>
Sent: Monday, 18 March 2024 8:11 pm
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Unable to migrate the company communicator- Getting Conflict & Rolebased issues. (Issue #1362)

Hello Sai,

Same thing we did, still getting below error

***@***.***

***@***.***

Thanks,
Prasad.

**Comment by gsv022** [comment]
Hi @Prasadj2024 ,
We are getting like below. Please share the screenshots directly here. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/a5060f16-7036-451f-b811-3b4c46442489)

**Comment by Prasadj2024** [comment]
Hi Sai, finally we deployed. 

How to change the MS logo? 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161813768/72faa5fa-0d38-4564-83a4-ec71ece2d0c9)

**Comment by gsv022** [comment]
Hi @Prasadj2024 ,

- Go to app service --> Configuration--> Update React_App_HeaderImage and text. For image, please make sure that the url should be valid type and publicly accessible.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/c16f8923-4459-4897-9aac-a8261bf0f8ac)
