### ISSUE TITLE
Teams author app is not adding to a team. 

### ISSUE THREAD

**Issue by SalmanBaig18** [OfficeDev/microsoft-teams-apps-company-communicator#1363]
Not sure what the issue is here as it is a textbook deployment straight from the deployment guide. Require urgent assistance. Please refer to the screenshot below. 

![2222](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/95561493/0aeb2920-4efc-4499-87dc-a2e1d8e48172)

**Comment by gsv022** [comment]
Hi @SalmanBaig18 ,
Thanks for raising the query. Could you please share the zipped author manifest file used for uploading to tenant.

**Comment by SalmanBaig18** [comment]
Hi @gsv022 I have attached the author file. Please let me know if there's any faults in it. 
[Author Manifest.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/14505839/Author.Manifest.zip)

**Comment by gsv022** [comment]
@SalmanBaig18 ,
Could you please share the application insight logs. Here is the reference.
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat. Even the screenshots would be more helpful. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/4747b16e-067a-47ad-a764-ae38a5f67a89)

**Comment by SalmanBaig18** [comment]
@gsv022 
Here are the screenshots of the logs. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/95561493/82886cc4-1276-4de7-a670-2c99c14ab097)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/95561493/2b02b90d-9206-4424-89c0-d1e970cd6ce8)

do you think it would be better to investigate this over a call as this is a highly time-sensitive matter?

**Comment by gsv022** [comment]
Hi @SalmanBaig18 ,
Please share your mail id we can discuss the issue internally.

**Comment by SalmanBaig18** [comment]
@gsv022 you can contact me on salman.baig@sulava.com

**Comment by gsv022** [comment]
We have started the conversation internally

**Comment by SalmanBaig18** [comment]
Hi @gsv022 , still waiting for your message. Please let me know your availability to connect.

**Comment by gsv022** [comment]
@SalmanBaig18 ,We have started the conversation already over Teams. Please check and respond
<img width="634" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/7d41e268-334b-4b0a-a69e-2c87ee25d975">
