### ISSUE TITLE
Exporting detailed results does not work properly

### ISSUE THREAD

**Issue by Axael85** [OfficeDev/microsoft-teams-apps-company-communicator#1364]
Hello Team,

This is regarding issues trying to export the detailed results from a "Sent" message. 
When we click the "export detailed results" we the permissions for OneDrive access is never asked/pop up and the message is not received

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/4a17dbee-d75e-4729-8e77-7b939c7fb688)

Is there something we are missing to get te exported details?

REgards

**Comment by gsv022** [comment]
Hi @Axael85 ,
Thanks for raising the query.

- Is it a fresh deployment or migration?
- Are you able to send the message through 4th sending option?
- Could you please perform SYNC for all 3 function apps- Prep, Data, Send and try exporting it again

**Comment by Axael85** [comment]
HEllo  @gsv022 ,

1.- This is not a new deployment
2.- I cannot send message through 4th sending step( it is not showing the groups when trying to deploy) 
3.- Have performed the sync for the function apps still failing.

REgards  :(

**Comment by Axael85** [comment]
Hello @gsv022 ,

I have checked the Graph App authentication  part. Everything seems configured properly   

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/eee960f5-a10b-49fc-8a61-cb4e044e590f)

**Comment by Axael85** [comment]
As well, checked directly on the storage account for datablobs , and the exportdatablobs is empty. Seems is not triggering anything:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/e1ec2b0e-a20f-4ee1-bfea-b351f1dfa5fc)

**Comment by gsv022** [comment]
@Axael85 ,

For fourth sending option, please type the name of the team name without any spacings, it will give the details(if not tried already)

Secondly, We suspect that secrets are incorrectly configured.  Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by Axael85** [comment]
Hello team,

Thanks for the feedback, I have checked for the secrets from keyvault and all of them are correctly configured. Not sure what else is failing. 
As well have been any change on the applicaiton, currently I cannot create any other mesage :

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/cf0c6620-a119-48f9-929b-30426b5c6ab0)

**Comment by gsv022** [comment]
Hi @Axael85 
Please share your mail id so that we can discuss the issue internally

**Comment by Axael85** [comment]
Hello SaiVenkat

My email address is ***@***.***

**Comment by Axael85** [comment]
Hello @gsv022 

I was able to sort the issue about company communicator, now I'm able to connect this one and send messages. For the downloading issue now I'm able to receive the alert to "Allow or Decline" but show now the next error:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/189ec662-8fbf-4dc6-ab42-0f6a2ac44267)


Could this be related to the Client secret?

REgards

**Comment by gsv022** [comment]
Hi @Axael85 ,
Are you able to send the message using 4th sending option?

**Comment by Axael85** [comment]
Hi @gsv022 ,

YEs the 4th sending option is working now. the only pending item is the capability to download the report.

https://private-user-images.githubusercontent.com/150716965/315896215-189ec662-8fbf-4dc6-ab42-0f6a2ac44267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDczMzAsIm5iZiI6MTcxMTQwNzAzMCwicGF0aCI6Ii8xNTA3MTY5NjUvMzE1ODk2MjE1LTE4OWVjNjYyLThmYmYtNGRjNi1hYjQyLTBmNmEyYWM0NDI2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQyMjUwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTc0NzhiN2U5N2Y1ODJkOGJiOTBiZTllYzA0ZTJhYjJkOWVlNTg1MmRjYzFjZGVjNTI0ZmM4MDUwMjIyOGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7yqvy14cvgWGQVo6CjotJ73TiAk4rQpkirbdrBZZGcs

**Comment by gsv022** [comment]
@Axael85 ,Could you share the screenshot of the graph API permissions. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/cbda924e-b28f-4d2e-9b66-b74d70a9a35c)

**Comment by gsv022** [comment]
Hi @Axael85 ,
Please remove the extra permissions which are not mentioned in the deployment guide.

**Comment by Axael85** [comment]
Permissions removed 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/d136d61f-c0f0-4b09-883d-55c4d255a5d9)

But we can still see the issue here :

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/c8fef4a7-954e-462f-9610-62566bbe9ab4)

**Comment by gsv022** [comment]
Please check the same for author app and user app registrations.

**Comment by Axael85** [comment]
Quick question, which permissions does the Author and user app registration required? Couldnt find them on the wiki.

**Comment by gsv022** [comment]
As per deployment guide there are no permissions need to be added for author/user. By default once app registration is created, user.read will be the permission created and apart from that permission no permission should be there. There are chances that permissions of graph app might got added for author/user. Please check it.

**Comment by Axael85** [comment]
No permissions were presented :
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/154fd812-a900-431c-bc73-d082e7a66e1e)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/248513f2-cc18-49e8-887c-41f3ef181b3a)

REgards

**Comment by gsv022** [comment]
upon creation of app registration, user.read permission(delegated type) will be created and by any chance that permission is deleted?

**Comment by Axael85** [comment]
Hello @gsv022 ,

Yes the user.read permission was removed from both app registration ( Author and user)

**Comment by gsv022** [comment]
@Axael85 , Please add that permission. It should be there.

**Comment by Axael85** [comment]
Hello @gsv022 ,

Both app registration now have the user.read ( delegated type) permission.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/4de29277-965e-4f16-9b12-f072c02c9447)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/680b3c13-c6d7-41a2-abaa-2828fc237e9c)


However it is same problem :

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/0eb8a4a8-b431-4743-be9c-2384e8e31509)


Regards

**Comment by gsv022** [comment]
Hi @Axael85 ,
Please share the email id directly here so that we can discuss the issue internally

**Comment by Axael85** [comment]
Hello Sai,

This is my email address ***@***.******@***.***> I'm working on CST Mexico time.

Regards

**Comment by gsv022** [comment]
Please share the mail id directly on this GitHub platform 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/33ebcdc5-620f-44e1-9a36-b4726b16bf07)

**Comment by Axael85** [comment]
hello @gsv022 ,

this is my email address: christianivan.luna@dxc.com

**Comment by gsv022** [comment]
We have initiated the conversation internally. Please check and respond

**Comment by Axael85** [comment]
Hello @gsv022 ,

I'm not able to open the conversation on Teams. Having below error:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/67d0afd2-b483-44b6-9ce2-80d6cbdfd0e1)

**Comment by gsv022** [comment]
Hi @Axael85 ,
We will send out the mail. Please check and respond

**Comment by Axael85** [comment]
Hello @gsv022 ,

NEvere received a meeting invite to collaborate or fix the problem. The issue still exists!

**Comment by gsv022** [comment]
Please log an new issue.
