### ISSUE TITLE
Dynamic Distribution Lists

### ISSUE THREAD

**Issue by brent-lea** [OfficeDev/microsoft-teams-apps-company-communicator#1365]
I've seen dynamic distribution lists mentioned a couple of years ago. Can someone confirm if these lists are still unsupported by Company Communicator?

Many thanks.

**Comment by gsv022** [comment]
Hi @brent-lea ,
Thanks for raising the query. Currently, our CC does not support dynamic distribution lists. We've added this feature request to our backlog already, but we do not have an estimated time for its implementation at this time.
