### ISSUE TITLE
Failed to create or update User app in Azure Active Directory. Exiting...

### ISSUE THREAD

**Issue by Vernhout** [OfficeDev/microsoft-teams-apps-company-communicator#1367]
<img width="947" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/49403979/65110859-dc5c-4f2b-87e5-66d703ec60da">

**Comment by gsv022** [comment]
Hi @Vernhout ,
Thanks for raising the query. There is a existing issue with PowerShell deployment which we will be addressing in the future releases of CC. To unblock yourself, we recommend you to proceed with manual deployment procedure.

**Comment by seddon** [comment]
Hi, this is still an open issue - i have just ran into it myself. Can the ticket be reopened please?

**Comment by albert-widjaja** [comment]
Hi Team,
yes, even when using the latest deploy.ps1 and the latest azure cli
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/24cb91c6-96f3-40bc-b064-a2290890b42e)

I am still having issues with these errors:

```
ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False
Failed to create or update User app in Azure Active Directory. Exiting...
```

Any help and suggestion would be greatly appreciated.
