### ISSUE TITLE
v5 upgrade Wiki is incorrect for updating Authors list.

### ISSUE THREAD

**Issue by Ukiman1014** [OfficeDev/microsoft-teams-apps-company-communicator#1368]
This portion of the v5 migration guide points to the "Configuration" blade, when the list of authors is in "Environment Variables".
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#4-deploy-to-your-azure-subscription

"7. Update the "Sender UPN List", which is a semicolon-delimited list of users (Authors) who will be allowed to send messages using the Company Communicator.

For example, to allow Megan Bowen ([meganb@contoso.com](mailto:meganb@contoso.com)) and Adele Vance ([adelev@contoso.com](mailto:adelev@contoso.com)) to send messages, set this parameter to meganb@contoso.com;adelev@contoso.com.

**You can change this list later by going to the App Service's "Configuration" blade.**"

**Comment by gsv022** [comment]
Hi @Ukiman1014 ,
Thanks for raising the query. 

- Previously, there was no environment variables section where configuration section contains both application settings and general settings. Here is the reference

<img width="956" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/7666faa9-d3c2-4484-a869-47013b0660fa">


- Recently,  these two sections has been bifurcated where application settings are residing in environment variables and configuration contains general settings.
<img width="508" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/9829281a-5e9e-4ef0-b2b4-a1bc2e8fcded">

<img width="479" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/d896d33c-e740-4a17-9cdc-d9606b908eae">

- The guide was implemented when configuration section contained both sections.  Anyway thank you for bringing this to our attention. We will do the necessary.
