### ISSUE TITLE
Companay Communicator in New teams threw connection error even though it was successfully updated to V5.5.1 

### ISSUE THREAD

**Issue by tyi1473** [OfficeDev/microsoft-teams-apps-company-communicator#1369]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/65746803/aae63b44-ab5f-4799-b25d-a744f300410a)

Deployment Center status
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/65746803/35cd0e2f-d0b0-4807-b3b7-6a5a9e3253b1)

**Comment by mpftDigital** [comment]
Same here on the new version of teams, ok still on classic.

**Comment by gsv022** [comment]
Hi @tyi1473 ,
Thanks for raising the query. Please follow the procedure mentioned in this ticket- #1337 and let us know if it helped in solving the issue.

**Comment by tyi1473** [comment]
Deleting both directory under new teams and classic helped New teams to gain the sight of author apps. Thx

**Comment by gsv022** [comment]
Hi @tyi1473 ,
Please let us know if you have any queries otherwise we can make it to closure.

**Comment by JFus8** [comment]
I'm also receiving this error even after I cleared the cache for new and classic teams.  Classic teams isn't installed on my PC anymore.
