### ISSUE TITLE
Send notifications via SMS

### ISSUE THREAD

**Issue by MBlondin** [OfficeDev/microsoft-teams-apps-company-communicator#1370]
Is there a plan to extend Company Communicator to send notifications via SMS as well as in Teams.

**Comment by gsv022** [comment]
Hi @MBlondin ,
Thank you for your inquiry. Regrettably, the feature you've mentioned isn't currently supported. We'll take note of your request and discuss it internally to determine our next steps. At this time, we're unable to provide an estimated timeframe for when this feature might be implemented.
