### ISSUE TITLE
The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'”

### ISSUE THREAD

**Issue by Prasadj2024** [OfficeDev/microsoft-teams-apps-company-communicator#1372]
We are doing company communicator migration in Production, we re getting below error 
"message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."

**Comment by gsv022** [comment]
Hi @Prasadj2024 ,
Thanks for raising the query. 
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by gsv022** [comment]
@Prasadj2024, we are closing this issue as this is a duplicate to #1362.
