### ISSUE TITLE
Can't see new teams channel in Company Communicator

### ISSUE THREAD

**Issue by Heindrick03** [OfficeDev/microsoft-teams-apps-company-communicator#1373]
Dear suport,
"Company Communicator" has been deployed late august 2023 and it works until Microsoft deployed a kind of security feature that disabled "upload custom apps" in Teams policy. Since then, I can't target new teams channels. With some help and through a workaround, I can make it works for new teams channels but have to apply the workaround one by one.

I have raised a case with Microsoft but the support redirected me to GitHub support.

Can you please assist?
Regards,

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
Thanks for raising the query. Did you enable upload custom apps option in teams admin center?

**Comment by Heindrick03** [comment]
Hello,

Yes it's already enabled.
Microsoft support did the check also before asking me to raise a ticket to GitHub support

Cordialement / Regards /真诚地,
Didier TAIN (Ingenico partner)
Phone: +33186998888
________________________________
De : Sai Venkat ***@***.***>
Envoyé : mardi, mars 19, 2024 6:15 AM
À : OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc : Didier TAIN ***@***.***>; Mention ***@***.***>
Objet : Re: [OfficeDev/microsoft-teams-apps-company-communicator] Can't see new teams channel in Company Communicator (Issue #1373)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @Heindrick03<https://urldefense.com/v3/__https://github.com/Heindrick03__;!!KtIQeTNdMUQ6!5NcUn4NLcx8BeJQ0YWSC2Iga1GktEW4k6RUCDsHCiXv9Ve2YCo7Wc-r6HYIoqRvnRPD_k-pMWd6iNoElST3C0-LKvm0$> ,
Thanks for raising the query. Did you enable upload custom apps option in teams admin center?

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
Could you please elaborate more on the issue. Are you installing user app manually to users?

**Comment by Heindrick03** [comment]
Hello Sai,

The issue is not regarding the installation of the app.
It can be added without any issue to a Teams channel.
The problem is once installed, I can not use to send messages to that channel because it’s not listed when I create a message.

Do you have any availabilities so that I can show you through a remote session?

Cordialement / Regards,



Didier TAIN
Digital WorkSpace

Tel: +33 1 86 99 88 88
Email: ***@***.******@***.***>

**Comment by Heindrick03** [comment]
Hi Sai,
Can I have a feedback please?

Cordialement / Regards,



Didier TAIN
Digital WorkSpace

Tel: +33 1 86 99 88 88
Email: ***@***.******@***.***>

From: Didier TAIN
Sent: 27 March 2024 12:07
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Can't see new teams channel in Company Communicator (Issue #1373)

Hello Sai,

The issue is not regarding the installation of the app.
It can be added without any issue to a Teams channel.
The problem is once installed, I can not use to send messages to that channel because it’s not listed when I create a message.

Do you have any availabilities so that I can show you through a remote session?

Cordialement / Regards,


Didier TAIN
Digital WorkSpace

Tel: +33 1 86 99 88 88
Email: ***@***.******@***.***>

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
please share your mail id here so that we can discuss the issue internally.

**Comment by Heindrick03** [comment]
Hi @gsv022 ,
How can I make this chat private?
I don't want to have my phone or email being public

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
Please share it here only. Once I acknowledge it, you can delete the comment from your side. Hope that works

**Comment by Heindrick03** [comment]
Sure but what is your business hours?
I'm based in Europe.

**Comment by gsv022** [comment]
No worries. Please share your mail id and we will try to match your work timings.

**Comment by Heindrick03** [comment]
Hi @gsv022 
Here it is:
didier.tain@ingenico.com

**Comment by gsv022** [comment]
I have sent a mail. Please check and respond

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
 Could you please let us know the status

**Comment by Heindrick03** [comment]
Hi @gsv022 ,
Thank you for your time and to follow this case, unfortunately, I won't have time this week to check the "Authentication configuration" part.
I will keep you in touch next week.

**Comment by gsv022** [comment]
Sure, Please keep us updated.

**Comment by Heindrick03** [comment]
Hi @gsv022 ,
Can you please help me to identify how I can get the %appDomain% value?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144246703/320b461a-33f4-4d22-8a81-5fc18c354983)
The app has been create by an colleague who left the company :-(

**Comment by gsv022** [comment]
@Heindrick03 , The error is expected. Because Application id URI is updated already in another app registration and updating the same in user app registration creating a conflict here. And authentication step need to be performed for author app if it is v4 /graph app if it is v5. Please don't perform authentication step for user app. We recommend you to refer the deployment guide for more information.

**Comment by Heindrick03** [comment]
Hi @gsv022 ,
Sorry, can we schedule a teams call for May 3rd at 3:30PM CET?

**Comment by gsv022** [comment]
@Heindrick03 , We are following the issue internally.

**Comment by gsv022** [comment]
@Heindrick03, Could you please let us know the issue that you are encountering

**Comment by Heindrick03** [comment]
Hello @gsv022 ,
Please leave until friday to get back to you, I have to complete other tasks first.

**Comment by Heindrick03** [comment]
Hi @gsv022 ,
I tried to configure the author app following this instruction
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144246703/c23a72c6-1a2e-45eb-8f0c-fee6474e6ef7)
and I encountered this error:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144246703/fc027d64-65b2-484b-a1d4-b642dbcee344)
Can you please assist?

**Comment by gsv022** [comment]
Hi @Heindrick03 ,
The step that you are performing need to be done for Graph app not for Author app. The error says that app domain has been already used by another app registration(mostly it will be graph). Please cross-verify

**Comment by Heindrick03** [comment]
Hi @gsv022,
Regarding Graph app, the settings look correct.
What is the next step for the troublshooting?

**Comment by gsv022** [comment]
It  creates confusion if the issue is followed up on two platforms. Lets continue the conversation on teams

**Comment by Heindrick03** [comment]
Hi @gsv022 ,
Authors users encountered this error while trying to create a message:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/144246703/3147fb23-6988-4280-90e1-ca1d6c20a0cb)
Can you please assist?

**Comment by Heindrick03** [comment]
Same issue with web client

**Comment by gsv022** [comment]
@Heindrick03 ,
The issue was due to conflict in choosing graph app registration. Upon updating relevant graph app registration with all the details as per deployment guide resolved the issue.


Please feel free to raise the ticket if you encounter any issue with CC.
