### ISSUE TITLE
Re-Branding Company Communicator

### ISSUE THREAD

**Issue by brent-lea** [OfficeDev/microsoft-teams-apps-company-communicator#1374]
My company would like to rebrand our existing deployment of Company Communicator. They just want to change the name of the application as it appears in Teams, as well as change the images used. What is the best way to accomplish this? Do we need to fully redeploy the solution, or is there a quick way to just change the name and images?

**Comment by gsv022** [comment]
Hi @brent-lea ,
Thanks for raising the query.
**To update name of CC**
•	Login to Azure Portal with Global Admin Credentials (portal.azure.com)
•	Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
•	Click on Azure Bot(user/author) --> under settings click bot profile-->Change display name as per the organizational need. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/cae48233-dfd5-4094-8862-692fd2165eaf)
•	And update the names in the manifest files for user/author. Re-upload the zipped manifest file again. Here is the place for reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/3212ca98-1e39-4631-b1b4-284c1b634e8a)

 
**To change the icon,** 
•	Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
•	Click on Azure Bot(user/Author) --> under settings click bot profile-->Upload custom icon. Change the icon as per the organizational requirement.
•	In the manifest folder, update the same icon. Please make sure that it is having the required dimensions same as default icons.
**Note:-**
•	There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.
•	In the ‘Icon’ field, it is recommended to upload the size 192x192.
•	The same procedure can be performed for both author and user apps.
•	To change the header logo and header text in the below place.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/35c1a3db-db59-4483-af9b-e356ec118f12)  
•	Go to app service --> Configuration--> Update React_App_HeaderImage and text. For image, please make sure that the url should be valid type and publicly accessible.
      
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/c16f8923-4459-4897-9aac-a8261bf0f8ac)
