### ISSUE TITLE
Company Communicator - Cannot send to a 365 / resource / security group

### ISSUE THREAD

**Issue by nicsywhu** [OfficeDev/microsoft-teams-apps-company-communicator#1375]
We recently upgraded Company Communicator from 5.1 to 5.5.

We can send a message using options 1 to 3 - general channel of a team, members of a team and whole organisation, by adding the user app (bot) to specific teams. However when we try to send to a 365 group, the list has no values and searching for a group is non responsive. Do we need to do anything to make them available? 

Other things we have done are:

- Published the app to all employees and pinned it to their Teams menu
- Verified the graph API permissions are applied correctly with admin consent granted

I've seen other issues reference a permissions problem, but we do not get that, as you can see from the image below where no values are being returned.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/164152583/709ff85c-1faa-43a1-a5b7-efc3450c4014)

**Comment by gsv022** [comment]
Hi @nicsywhu ,
Thanks for raising the query. Could you please confirm on the below queries.

- When the application was running on v5.1, was 4th sending option up and running?
- Since you mentioned that other 3 sending options, are you able to export the result for any sent messages.
- Please share the screenshots of runtime version for 3-function apps, .NET version set for app service as depicted in the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#1-update-the-net-version-of-azure-functions-and-app-service-to-support-net-60-)

**Comment by nicsywhu** [comment]
Hi
Answer to your queries are as follows:


  1.  When v5.1 was working, I can confirm we were able to use option 4. In fact, this was the main use case. However, 5.1 did stop working, hence we upgraded to v5.5
  2.  Enclosed is an export of a chat we sent during 5.5 testing.
  3.  Below are screenshots of the .net and runtime versions

***@***.***

***@***.***

**Comment by nicsywhu** [comment]
Hi

One further point. I did notice you sent the migration guide – please note that although we previousloy used v5.1, we didn’t upgrade to v5.5 as that didn’t resolve our original issue. We deleted and reinstalled creating new resource groups etc so this is a fresh install.

Thanks
Chris
From: Christopher Nicholson
Sent: Tuesday, March 26, 2024 9:45 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Company Communicator - Cannot send to a 365 / resource / security group (Issue #1375) [EXTERNAL]

Hi
Answer to your queries are as follows:


  1.  When v5.1 was working, I can confirm we were able to use option 4. In fact, this was the main use case. However, 5.1 did stop working, hence we upgraded to v5.5
  2.  Enclosed is an export of a chat we sent during 5.5 testing.
  3.  Below are screenshots of the .net and runtime versions

***@***.***

***@***.***

**Comment by gsv022** [comment]
Hi @nicsywhu ,
Please share the screenshots directly here. As we see them in masked state like below.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/6aa0d612-0670-408b-a1ba-22dd13e2dce3)

**Comment by nicsywhu** [comment]
Is this ok?

**Comment by gsv022** [comment]
Hi @nicsywhu ,
please share them directly here using the options available in this GitHub text box.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/c6d94082-7a55-4f55-bf3d-0d7be14b434b)

**Comment by Yalnux** [comment]
Hello we have the same problem , we cannot find any team on Teams 
We didn't have any issue installing V5.5 and the ARM deployment worked fine, also double checked GraphApp Permissions and they look exactly as in troubleshooting guide.

however when we use the Author Bot we could not find any Team
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/97951ca0-7713-4a27-9eb3-7404143b09a1)
On the Option related to M365 GROUPS I can see the group where I previously installed the Author App and the User App
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/8bcf164d-0a08-4031-b50f-9cd2cfb599e5)

On the Company Communicstor Tab I have the next message after trying to send the message.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/f9159823-88c0-418b-adbc-31f7e2695d15)
....
On the Azure Environment my Graph App has the following config.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/bb078996-0382-402e-9fa1-4c04e0374b1b)

**Comment by nicsywhu** [comment]
All images were loaded as requested - please confirm you have received them and someone is now looking at our issue.

**Comment by gsv022** [comment]
_All images were loaded as requested - please confirm you have received them and someone is now looking at our issue._

I am not able to see the images. Please send the images directly on GitHub

**Comment by nicsywhu** [comment]
Enclosing files again 

![Comp_Comm_dotnet](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/164152583/252fb141-347d-44d6-a85d-2c38f2feab47)
![Comp_Comm_runtime](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/164152583/622ffbf0-044a-4e0f-bb00-4823f15e7506)

**Comment by gsv022** [comment]
Hi @nicsywhu ,
The search bar of 4th sending option will give the references of team names once we type first 3 letters of it. It doesn't come just by typing first letter of team name.

Please try it and keep us posted.

**Comment by nicsywhu** [comment]
Please see below screenshots where we used groups beginning with Business .... as our example and when adding at least 3 characters makes no difference in the search bar.

![CC_Business_Groups_Example](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/164152583/b22b86f1-501f-4afb-bd92-4d1235c2b6d9)
![CC_Business_Example](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/164152583/bc67160a-a7e4-429d-89f8-9df46a1e96d2)

**Comment by Landsec-SteveG** [comment]
The Graph permissions are correct:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/60216229/91a0dcd3-996e-4909-b3cc-00d479cb07bd)

And the redirect URI is already in place:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/60216229/4ecb6e19-4194-43db-a169-9f9900e660d8)

Authentication:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/60216229/df3be580-6c0f-484d-aa42-834c96b8356d)

Expose API:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/60216229/bc54de05-009e-40f3-869c-fdf771e43865)

Is there anything else we need to check?
