### ISSUE TITLE
Scheduled messages not sent and were sitting there in the schedule window in New Teams. Any timezone issues ?

### ISSUE THREAD

**Issue by tyi1473** [OfficeDev/microsoft-teams-apps-company-communicator#1376]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/65746803/d7429e91-4987-4417-b4f3-b9c1df537a73)

**Comment by gsv022** [comment]
Hi @tyi1473 ,
Thanks for raising the query. Please ensure that when you enable the scheduled send, you adjust the timing to be half an hour ahead from the current time before clicking on the schedule button. If you leave the time unchanged (though it showing 30min ahead) and proceed to schedule directly, the message will not be sent at the scheduled time and will remain in the scheduled messages section only.

**Comment by tyi1473** [comment]
Yes. I followed the instruction that I set the timing to be at least 30mins ahead. Otherwise, it won't let me save the scheduled one. I did myself several times and someone in another team sent me message about not working with the scheduled message. "Looks like the schedule on the Communicator doesn't work"

**Comment by tyi1473** [comment]
I know something in the background is going to refresh the page. But nothing happened. I want to know what time the communicator app is using and how to verify the communicator current time compared to my local time.

**Comment by gsv022** [comment]
Hi @tyi1473 ,
The message will be scheduled as per you system time only.

**Comment by tyi1473** [comment]
What do we need for working correctly? I tested it never worked.

**Comment by gsv022** [comment]
Hi @tyi1473 ,
Please share your mail id so that we can discuss the issue internally

**Comment by tyi1473** [comment]
I already sent to your email box.

**Comment by gsv022** [comment]
Could you please share the subject of the mail

**Comment by tyi1473** [comment]
Scheduled messages not sent and were sitting there in the schedule window in New Teams. Any timezone issues ? #1376

**Comment by ori204** [comment]
Hello to you I have exactly the same problem. my original version is 5.3.0 I recently upgraded via Migration to v5 to version 5.2.2. everything works fine except the schedule messages. what can we check or do to make them work?

**Comment by gsv022** [comment]
> Subject : Scheduled messages not sent and were sitting there in the schedule window in New Teams. Any timezone issues ? #1376 ![image](https://private-user-images.githubusercontent.com/65746803/317331216-f664f133-1a44-47e5-b9e6-3d092380f6b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTMwMjMsIm5iZiI6MTcxMjMxMjcyMywicGF0aCI6Ii82NTc0NjgwMy8zMTczMzEyMTYtZjY2NGYxMzMtMWE0NC00N2U1LWI5ZTYtM2QwOTIzODBmNmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEwMjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzN2I5MzdiMjJhMTZmZGJkNWJhOTc1ZDI0ODYyNDIzNjQzNDZjZTQ4NWEyOWRhMjQ2ZjA5YWQ3MTJjZGNhYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wDlzSp6x8F0QV5k0dkx8JKgExlBbuEi1jdvzkrZusaE)

@tyi1473 ,This doesn't work. Please share your mail id directly here so that I will send out the mail and discuss further

**Comment by ori204** [comment]
Hello, did you find a solution to this problem?

**Comment by tyi1473** [comment]
I sent the email but if you insisted it, here it is tony.yi@tceq.texas.gov

**Comment by gsv022** [comment]
Yes, please send your email address(outlook id or teams id) so that we can reach out to you via that platform

**Comment by ori204** [comment]
> Hello to you I have exactly the same problem. my original version is 5.3.0 I recently upgraded via Migration to v5 to version 5.5.2. everything works fine except the schedule messages. what can we check or do to make them work?

Hi

Did you manage to solve this problem??? Please advise what can be done to make these scheduled messages work

**Comment by tyi1473** [comment]
@gsv022 

Here is my email address: tony.yi@tceq.texas.gov

**Comment by gsv022** [comment]
I have sent you a mail. Please check and respond

**Comment by ori204** [comment]
> Sync up the rest of 3 function apps. It is working great. Thanks for your help.

Hi @tyi1473 

Thank you for your help, that's exactly what it was about. I did sync on all 3 function apps and it worked beautifully. Scheduled messages work correctly.
