### ISSUE TITLE
When trying to send message, the page keep loading

### ISSUE THREAD

**Issue by yvtszcheung** [OfficeDev/microsoft-teams-apps-company-communicator#1378]
We are able to save the message, but when we try to send the message, the page just keep loading and I will not be able to send the message out.
HAR is collected, let me know if you will need it.

**Comment by gsv022** [comment]
Hi @yvtszcheung ,
Thanks for raising the query. Please share the logs and error screenshots as well.

**Comment by yvtszcheung** [comment]
Thanks for the help. can you let me know where can I upload the har file. Or can I share to you via E-mail?

**Comment by gsv022** [comment]
Please share the logs directly here.

**Comment by yvtszcheung** [comment]
[](url)

**Comment by yvtszcheung** [comment]
https://m365x61017047-my.sharepoint.com/:u:/g/personal/tszminhc_ytcheung_asia/EU8HtaOampdLsYg4XPDJyoUB-xruclwcgCsS65GDqIn7Zw?e=ouXXJQ
PLS refer to the file from the link

**Comment by gsv022** [comment]
Thanks for the patience. Please share your email id so that we can discuss the issue internally.

**Comment by yvtszcheung** [comment]
***@***.*** thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gsv022** [comment]
Please share the mail id directly here. I am getting like below.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/813fce17-953e-4893-9d52-fb2c6f438aeb)

**Comment by yvtszcheung** [comment]
Tszminhc@msft.Work thanks.

**Comment by gsv022** [comment]
@yvtszcheung ,We have sent you a mail. Please check and respond
