### ISSUE TITLE
Parameter file is updated, error comes out when I run deploy.ps1

### ISSUE THREAD

**Issue by chan228228** [OfficeDev/microsoft-teams-apps-company-communicator#1380]
Here is the error message that I received:
---------------------------------------------------------------------------------------------------------------------------
ADAppUpdateDisplayName : Cannot bind argument to parameter 'appId' because it is null.
At C:\temp\microsoft-teams-apps-company-communicator-main\Deployment\deploy.ps1:1085 char:26
+         ADAppUpdateDisplayName $userAppCred.appId $currentAppName $us ...
+                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ADAppUpdateDisplayName], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,ADAppUpdateDisplayName
---------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157443060/80bfb3e8-98d4-4765-8040-793d4cc02d58)

Please advise, thanks.

**Comment by gsv022** [comment]
Hi @chan228228 ,
Thanks for raising the query. Please follow the [manual deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) to unblock yourself. There is a issue with PowerShell deployment which will be addressed in the future releases of CC
