### ISSUE TITLE
Error accessing company communicator(V1) in new Teams client

### ISSUE THREAD

**Issue by sujeetkumarsharmahenkel** [OfficeDev/microsoft-teams-apps-company-communicator#1381]
We are receiving below error when trying to open the company communicator app in new Teams client.
_"Sorry, an error occurred while trying to access this service."_

We are not sure whether this is happening because of older version of company communicator(V1). We tried to check the documentation on how to upgrade from V1 to V5 or latest. But, the documentation is not clear whether direct upgrade is possible or not.
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide

Please help resolve this issue before classic Teams client is deprecated.
![communicator error](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/165150535/b341dca7-5f3f-4503-aabd-b310737fb83c)

**Comment by gsv022** [comment]
Hi @sujeetkumarsharmahenkel ,
Thanks for raising the query. We generally support migration from v4-->v5--> latest. Could you please share the screenshot showing the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/26955650-5cbc-4ff8-9004-d187fb918ed7)

<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">

**Comment by sujeetkumarsharmahenkel** [comment]
@gsv022 let me get this information.

**Comment by gsv022** [comment]
Yes, Please keep us posted

**Comment by sujeetkumarsharmahenkel** [comment]
@gsv022 Please find the attached screenshots.
We are willing to upgrade to latest version. But, not sure how to do so.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/165150535/616b5e92-c9c1-4032-b9ee-9405fa6447c2)
![image (1)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/165150535/38eb1f89-c663-4607-950a-49ee76aeec3d)

**Comment by gsv022** [comment]
Hi @sujeetkumarsharmahenkel ,
It seems to be CC is sitting on older version. The master branch deleted long back and migration is not possible for version less than 4.x. So we recommend you to deploy new version pointing to official repository and branch should be main.

**Comment by sujeetkumarsharmahenkel** [comment]
> Hi @sujeetkumarsharmahenkel , It seems to be CC is sitting on older version. The master branch deleted long back and migration is not possible for version less than 4.x. So we recommend you to deploy new version pointing to official repository and branch should be main.

@gsv022 We cannot loose the existing communications done on old app. Is there a way we can install the latest CC and point this DB's to old one(user app) without loosing data?

**Comment by gsv022** [comment]
Hi @sujeetkumarsharmahenkel ,
Our support scope is very limited to Official version. The requested task remains unaddressed due to its association with an outdated version of CC. Transitioning to the newest version of CC might not seamlessly accommodate older storage account and could introduce multiple complexities. Regrettably, our assistance in this matter is limited. We highly recommend opting for a fresh deployment as the most viable solution to ensure continued use of CC.

Thank you.
