### ISSUE TITLE
Support for .NET 6 ends on 12 November 2024—upgrade your Azure Functions apps to .NET 8

### ISSUE THREAD

**Issue by djaw123** [OfficeDev/microsoft-teams-apps-company-communicator#1382]
Hi, we received this email from ms:

"You have one or more Azure Functions apps that use .NET 6. 

In alignment with the end of community support, on 12 November 2024, support for .NET 6 in Azure Functions will end. Your apps that are hosted on Functions will continue to run, but security updates will no longer be available and we'll no longer provide customer service for .NET 6. Learn more about Azure Functions stack version support.

Required action
To avoid potential security vulnerabilities and take advantage of the latest features, follow the steps to upgrade your Functions apps to .NET 8 by 12 November 2024."

is there any actions required from us to do? or you will do small update? or if we change .NET here to 8 is enough?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/158998710/36ee5f56-3dce-4685-9e25-6240d799ba05)

**Comment by MohnJadden** [comment]
We also received the same email and are facing the same situation.

**Comment by gsv022** [comment]
Hi @djaw123 ,
Thanks for bringing this to our attention. We will look into it and take necessary action.

**Comment by djaw123** [comment]
bump
