### ISSUE TITLE
Action required: Migrate your .NET apps in Azure Functions to the isolated worker model

### ISSUE THREAD

**Issue by MohnJadden** [OfficeDev/microsoft-teams-apps-company-communicator#1383]
We are using Company Communicator.  We received the following email from Microsoft earlier this week:

Migrate your .NET apps in Azure Functions to the isolated worker model by 10 November 2026 
You’re receiving this email because you use the in-process model with .NET applications in Azure Functions.
Beginning 10 November 2026, the in-process model for .NET apps in Azure Functions will no longer be supported. To ensure that your apps that use this model continue being supported, you’ll need to transition to the isolated worker model by that date.
You may still use your .NET apps with the in-process model beyond 10 November 2026, but they will no longer receive security and feature updates from Microsoft.

The isolated worker model offers all the same functionality as the in-process model, plus improvements such as: 
•	Full control of the dependency chain.
•	Isolation from platform lifecycle activities. 
•	The ability to target [Standard Term Support (STS)](https://dotnet.microsoft.com/platform/support/policy/dotnet-core#release-types) versions of .NET. 

Required action 
To ensure your .NET apps in Azure Functions continue to receive support, [migrate to the isolated worker model](https://aka.ms/af-dotnet-isolated-migration) by 10 November 2026.

The migration steps basically involve changing the code in the Function App and redeploying.  

What steps do we need to take on our Azure resources to deploy updated and corrected code?

**Comment by gsv022** [comment]
Hi @MohnJadden ,
Thanks for bringing this to our attention. We will look into it and take necessary action. BTW, any issue that you are encountering while handling the application. Please keep us posted
