### ISSUE TITLE
Support for Azure TLS 1.0/1.1 ends on 31 Octber 2024, Any action required?

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#1385]
Support for Azure TLS 1.0/1.1 ends on 31 Octber 2024.

The storage account of our Company Communicator requires   minimum TLS version  1.0.  

Do I need to update the storage account  to be  minimum TLS version 1.2 ?

**Comment by gsv022** [comment]
Hi @ATshirai ,
Thanks for raising the query. We will check and do the needful. No action is needed from your until further notice.
