### ISSUE TITLE
Company Communicator issues with Gateway in prevention mode

### ISSUE THREAD

**Issue by RepsolUser** [OfficeDev/microsoft-teams-apps-company-communicator#1387]
Our infrastructure is secured through a Gateway, everything works correctly, except in the case in which messages are sent with attached images of more than 128 KB, in which case the Gateway blocks us with an error 413.
Could you give us an alternative so that this development works correctly without having to remove the gateway?

Thanks in advance

**Comment by gsv022** [comment]
Hi @RepsolUser ,
Thanks for raising the query. 

Our support scope is very limited with the standard version. We won't be able to assist on this request as it will fall under customization. Please let us know if you have any issues with the standard version.

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
