### ISSUE TITLE
Help required for the Author App. "we can't find any match .. for any of the Options"   V5.5 fresh install

### ISSUE THREAD

**Issue by Yalnux** [OfficeDev/microsoft-teams-apps-company-communicator#1388]
Hello we have a problem on the Author App , we cannot find any team on Teams 
We didn't have any issue installing V5.5 and the ARM deployment worked fine, also double checked GraphApp Permissions and they look exactly as in troubleshooting guide.

however when we use the Author Bot we could not find any Team
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/97951ca0-7713-4a27-9eb3-7404143b09a1)
On the Option related to M365 GROUPS I can see the group where I previously installed the Author App and the User App
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/8bcf164d-0a08-4031-b50f-9cd2cfb599e5)

On the Company Communicator Tab I have the next message after trying to send the message.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/f9159823-88c0-418b-adbc-31f7e2695d15)
....
On the Azure Environment my Graph App has the following config.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/66656241/bb078996-0382-402e-9fa1-4c04e0374b1b)

**Comment by v-jaygupta** [comment]
Hello @Yalnux ,

Thank you for reaching out to us!

For using the first 2 sending option in CC author app, you need to first upload the user app manifest package to your organization's app catalog as mentioned in the 5th and 6th step of our [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) and then add the user app to the respective teams. Please share the error you are getting for the sent message using 4th sending option to troubleshoot further.

**Comment by y4lnux** [comment]
Thank you all for your feedback , I tried to install in a test environment with a new organization, followed all the steps , I installed User app in couple of users , then the Author app , and still couldn't find teams.
TBH  we have stopped using the app, and we are trying  other solution.
