### ISSUE TITLE
Update Company Communicator User description

### ISSUE THREAD

**Issue by Axael85** [OfficeDev/microsoft-teams-apps-company-communicator#1389]
Hello team,
Is there a way that we can update the company communicator description?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/150716965/ce40a068-2c9c-41ac-bb06-483decd53c41)

**Comment by gsv022** [comment]
Hi @Axael85 ,
Thanks for raising the query.  It can be changed from the below place.
<img width="536" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/90abd1ae-d94e-4c3c-b22f-585e4567596c">
