### ISSUE TITLE
Manual Deployment Failed creating resources in Azure / ccscommunicatorv5-prep-function/web

### ISSUE THREAD

**Issue by CarlosGuadamuz** [OfficeDev/microsoft-teams-apps-company-communicator#1390]
Even if we are using the lates the CC template 5.5.1, we are getting the following errors during the manual deployment:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85959949/32ae6092-7783-4f3a-be59-b79891f08d41)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/85959949/ae0ba6c2-30c6-49d5-b435-a64698f66701)

**Comment by tiwariShiv7** [comment]
We are following this internally on continued email thread with a new subject of "Github Issue 1390 : Manual Deployment Failed"

**Comment by tiwariShiv7** [comment]
We had meeting on this and as per our last conversation all the function apps and app service/ Web app is deployed successfully now. Waiting for the  confirmation about closing the ticket.

**Comment by mibohlindemo** [comment]
Seeing the same error 
[CC Deployment error.docx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/14951750/CC.Deployment.error.docx)

**Comment by gsv022** [comment]
Hi @CarlosGuadamuz ,
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again
