### ISSUE TITLE
Authors Enabled for Company Communicator are getting Error - Permissions needed. Ask your IT admin to enable this option

### ISSUE THREAD

**Issue by tayalHima** [OfficeDev/microsoft-teams-apps-company-communicator#1392]
our Authorised (Authors) Enabled for Company Communicator are getting the following Error  Permissions needed. Ask your IT admin to enable this option for you.

When Author select "Choose how you want to send your message" then select M365 groups, Distribution groups or Security groups -> then Author not able to get any information in drop down 
Please help n this issue ASAP as we need to give demo to End-User

![AuthorIssue](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/92294825/0d243f45-94b4-4170-8e86-c59b6632072d)

**Comment by v-jaygupta** [comment]
Hello @tayalHima ,

Thank you for reaching out to us!

The user need to search the name of the respective M365 group or distribution group or security groups to get the suggestions as a form search results and values will be populated within the dropdown.
However, if you are getting the error - " Permissions needed. Ask your IT admin to enable this option for you", while selecting the 4th sending option then, can you please cross check the values of client secret for User, Author & Graph app from azure key vault and make sure the values are same as generated at the time of App registrations or there might be chance that the secrets might have expired.

**Comment by tayalHima** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/92294825/0fc175a7-a50e-439a-9a85-a396553e1ffb)

I can't find any key value in the key vault section. Can we have a screen sharing session and help me on setup 

Also, We are using Author App and its working for me as I can access the drop down value but my team member trying to search in drop down and no result found.

**Comment by gsv022** [comment]
Hi @tayalHima ,

- Please check the [set-up authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) part whether it has been configured correctly or not.
- In the overview section of Graph app, Supported account type for graph app should be **My Organization**
- Coming to secrets view, Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by gsv022** [comment]
@tayalHima , Share the screenshots mentioned in this authentication step.
- Please check the [set-up authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) part whether it has been configured correctly or not.
