### ISSUE TITLE
Unable to locate AuthorBotId and UserBotId after code deployment failure

### ISSUE THREAD

**Issue by GavinFullerTX** [OfficeDev/microsoft-teams-apps-company-communicator#1393]
Hello,

I attempted to perform a deployment via ARM template, and received a code deployment failure. Following the steps in the deployment guide, I navigated to the webapp and performed a redeployment successfully.
To get the AuthorBotId and UserBotId, I followed the instructions saying to look under Configuration in the web app. However, I am unable to locate them. I also checked the environment variables, and was unable to locate those specific values.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131713392/bc474a80-6ddc-409e-8631-e39864ab6cbe)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131713392/3a03c719-b4c7-4991-9f96-6187b2ae9640)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131713392/0a21b652-6015-4df0-8054-887f6485b8a4)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/131713392/928eead1-5542-4722-99c8-2ee1bcf440ee)

Am I missing something, or is there somewhere else or some other way I can find these values?

Any help would be greatly appreciated.

**Comment by v-jaygupta** [comment]
Hello @GavinFullerTX  ,

Thanks for reaching out to us!
If your deployment is successfull, you can find the author and the user app id in the environment variables section of the app serivce with other app service configurations as depicted in the below screenshot - 
<img width="627" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/0824e4be-c188-4ea8-b710-3a2e3f61338a">
