### ISSUE TITLE
.NET Error Post Upgrading the Communicator App to v5

### ISSUE THREAD

**Issue by sunil-tammisetti** [OfficeDev/microsoft-teams-apps-company-communicator#1394]
hi,

recently we upgraded the communicator app to v5 version and followed the instructions that are provided in the migration document.
post upgrade of the version we are facing .NET version issue.
<img width="604" alt="MicrosoftTeams-image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69713538/e89eba9e-0888-460c-a249-cec3c693e298">
please suggest what can be done to fix the .NET issue.
Thanks

**Comment by gsv022** [comment]
Hi @sunil-tammisetti ,
Thanks for raising the query.  Could you please share the screenshot showing the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/26955650-5cbc-4ff8-9004-d187fb918ed7)

<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">

**Comment by gsv022** [comment]
Hi @sunil-tammisetti ,
Could you please perform restart for App service.

**Comment by sunil-tammisetti** [comment]
Hi @gsv022,
just restarted the web app now and verified. but still the same error.
Thanks

**Comment by gsv022** [comment]
Please share your mail id so that we can discuss the issue internally

**Comment by sunil-tammisetti** [comment]
sunil.tammisetti@outlook.com
Thanks

**Comment by gsv022** [comment]
I have mail you. Please check and respond

**Comment by gsv022** [comment]
Hi @sunil-tammisetti ,
Thanks for joining the call. Here is the summary.
During the call it is observed that author app is not getting added after performing migration v4 to v5. It is throwing 500.30 error while adding the author app.

- As a part of troubleshooting, we noticed that all the three function apps are pointing to master branch. So we disconnected and connected to main branch as master is removed long back.

- Some steps of v4-->v5 migrations has been missing. So we made a walk through to the migration guide.  

- Firstly, clear the authentication part for author app registration as per the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5). Then add the same authentication steps to graph app registration.

- Now, click on deploy to azure. Fill all the parameters and perform deployment. If any resource is failed, visit the resource individually and check the status in deployment center (logs section) of that resource. If they are failed there, perform SYNC there.

- Now open the teams in web client and access the application. 

Please perform the steps with little caution and keep us posted.
If you feel like stuck and post the same in this chat section, we will be ready to assist you.

**Comment by gsv022** [comment]
@sunil-tammisetti , Thank you for the update. We are closing the issue for now, if you face any issue in the future please feel free to log an issue on GitHub. We will be more than happy to assist you.
