### ISSUE TITLE
Uploading Videos on Communicator app

### ISSUE THREAD

**Issue by pmkinyua** [OfficeDev/microsoft-teams-apps-company-communicator#1396]
Hi Everyone,

Does communicator app support uploading of videos? I am am not able to select videos when uploading images

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Thanks for raising the query. Currently, it doesn't support video type. Here is the [reference](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html) for supportive formats of CC.
