### ISSUE TITLE
While configuring company communicator we are getting errors

### ISSUE THREAD

**Issue by chethankumarsg** [OfficeDev/microsoft-teams-apps-company-communicator#1397]
![image002](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/ed16a076-83dc-4692-8285-98892f969792)

**Comment by gsv022** [comment]
Hi @chethankumarsg ,
Thanks for raising the query. The screenshot shows the multiple deployment failures. 

- Could you please share the details of the error.
- What are the resources that are failed in the latest deployment?

**Comment by chethankumarsg** [comment]
Please check the detailed error screen shot for the same.
![image024](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/8507101a-d3b2-4bc7-a771-c2ca5b0c9798)
![image023](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/ed2880a1-2f8a-4670-b581-8f6caada1a7a)
![image022](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/bf843bce-95b5-427c-a6cc-0a91dff23cc2)
![image021](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/855d2491-e55a-441f-be70-93c92095f5df)
![image020](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/c0b6c549-aea3-4575-8ef5-addb94f04dd0)
![image019](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/e840e7df-40fb-4282-905d-6db4e635dd74)
![image018](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/6a9bb909-d2de-4fe3-932a-69dc5f991627)
![image017](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/b5d2d7c6-55e4-49ff-a5b9-535049ee45c1)
![image016](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/a758a029-c8bb-4708-9da4-ed2e67bafda4)
![image015](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/af021d1c-4a0b-449e-a241-724f7d9b7094)

**Comment by gsv022** [comment]
@chethankumarsg , please open this

**Comment by chethankumarsg** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/c66a3568-ba0e-491b-8b1e-e47d2432a08e)


Please find the requested screenshot

**Comment by chethankumarsg** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/72dab1d1-8343-4082-8d73-d1376bd29f36)
Please find the resource details...

**Comment by chethankumarsg** [comment]
![image003](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/ce16d910-af76-490b-9aeb-7d81885c7903)
![image002 (1)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/55e316e0-f445-45f2-a25e-13736b81c5d4)
![image001 (2)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/79150d90-4ce5-4e8f-9a8d-2e65dca151ea)

Please find the above screenshots for the requested details.

**Comment by gsv022** [comment]
Hi @chethankumarsg ,
Thanks for sharing the relevant screenshots. There are two issues observed.

- First issue is roleassignment one. For this please utilize this [link](https://www.guidgenerator.com/online-guid-generator.aspx) to generate 7 new guid's. Click on re-deploy option, keep all the parameters as it is and update the last 7 parameters with new guids and go for re-deployment again. This will solve the role assignment issue.
----------------------------------------------------------
- There are two other resources prep-function and data-function got failed. **Caution**- First perform the above step related to role-assignment issue and then perform the below steps.
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by chethankumarsg** [comment]
We are working on this we will update the status.

**Comment by chethankumarsg** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/3fcb7938-069a-43e6-9294-c12348b84250)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/9f286918-4d50-47d1-acf1-07271f9b04fc)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/39c00d05-f471-4640-a3d3-72cc3f34f03e)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/a184617c-71ca-4140-8688-0ff0ea03b615)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/b5fde892-28ed-456e-a2f1-af47891202e7)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/cbbd44aa-3763-4338-b6c1-1016f1141123)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/ae259a9b-fec8-4b7b-bafc-94e238dfae19)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/157361957/7b5de84f-9024-48fa-92df-0dfddace6762)


Please find the screen shot for your reference

**Comment by gsv022** [comment]
Hi @chethankumarsg ,
Once you update the last 7 guid's that you highlighted and re-deployed, any resources got failed?

**Comment by chethankumarsg** [comment]
guid's are created 

Please find the details below 

1caf4285-b5eb-4e81-8704-059f238c9705
a21e4d65-424d-4889-83aa-a5e24bca4b03
12e1cdc7-3c27-4428-8dab-a3a5aab0c72e
a2e3f433-08a9-4d37-b235-366118b4eb60
125dbfbd-dc4f-4b59-b661-745e08974c02
4d14f17d-8c0e-433d-bcca-66816e3a590d
5016c767-066b-4bf3-87ed-36a688d70dd7

**Comment by chethankumarsg** [comment]
Can i get any update on this one.

**Comment by gsv022** [comment]
After adding the newly generated GUID's in the template, any resources got failed in the redeployment?

**Comment by chethankumarsg** [comment]
We are checking with our internal team will update you

**Comment by chethankumarsg** [comment]
“Yes, we have seen the one Key vault resources fail we have seen the error like conflict and duplicate. So we have removed all the resources in the resource group and re-deployed from scratch onwards. After re-deploying with our new GIUDs and again  we are facing the errors, which we have already shared with you”

**Comment by gsv022** [comment]
No, after deploying the resources with new GUID's I dont see any screenshot containing failed resources. Could you please share them

**Comment by chethankumarsg** [comment]
We are working on this, we will let you know the status.

**Comment by gsv022** [comment]
Please keep us posted

**Comment by chethankumarsg** [comment]
we are working on this we will update you

**Comment by chethankumarsg** [comment]
Can we connect

**Comment by gsv022** [comment]
Could you please share the details of the error here that you are encountering

**Comment by chethankumarsg** [comment]
“Yes, we have seen the one Key vault resources fail we have seen the error like conflict and duplicate. So we have removed all the resources in the resource group and re-deployed from scratch onwards. After re-deploying with our new GIUDs and again we are facing the errors, which we have already shared with you”

We dont have the error screen shot

**Comment by chethankumarsg** [comment]
can i get any update on this

**Comment by gsv022** [comment]
Hi @chethankumarsg ,
Please change the base resource name and do the deployment. Keep us informed
