### ISSUE TITLE
Send in chat to members of the following M365 groups, Distribution groups or Security groups option is empty.

### ISSUE THREAD

**Issue by lbgrasso** [OfficeDev/microsoft-teams-apps-company-communicator#1398]
Hi everyone,
When I try to send a message using the "Send in chat to members of the following M365 groups, Distribution groups or Security groups" option, no groups are listed in the search box.
This is what I see:
<img width="267" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/89993166/d6da5c18-1b56-43c1-8d67-c4b732828993">
All the app permissions in Azure have been given.
Could you please help me?
Thanks

**Comment by gsv022** [comment]
Hi @lbgrasso ,
Thanks for raising the query.
- For fourth sending option, please type the name of the team name without any spacings, it will give the details.

- Please cross-verify set-up authentication step in the graph app registration correctly done or not. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/37be910d-f15e-4ba3-b74e-812b41d2bfa2)

**Comment by lbgrasso** [comment]
Set-up authentication in the graph app registration is correct. I've done all the steps correctly.

**Comment by gsv022** [comment]
How about first 3 sending options, are you able to send the messages using those options?

**Comment by lbgrasso** [comment]
Yes! The only one I didn't try was the third one, because I can't send a message to everyone in my company.

**Comment by gsv022** [comment]
Are you able to export the results for the sent messages?

**Comment by lbgrasso** [comment]
Yes, that works fine.

**Comment by gsv022** [comment]
@lbgrasso ,We suspect that secrets are incorrectly configured.  Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by gsv022** [comment]
ID- refers to mail id through which you are accessing azure portal

**Comment by gsv022** [comment]
whatever the id used for logging into the azure portal, please type in the principal section, you will get the access to view the secrets through that id.

**Comment by lbgrasso** [comment]
I can see the secrets, but the third option is still not working.

**Comment by gsv022** [comment]
Since you see the secrets, please compare the secrets from keyvault with app registration secrets

**Comment by lbgrasso** [comment]
Yes, I've already compared them and they are the same. Plus I realized the Recipients column shows 0 for both succeeded and failed, when that's not correct. I don't know if that may have something to do with this.

**Comment by gsv022** [comment]
@lbgrasso ,
- Please check the [set-up authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) part whether it has been configured correctly or not.
- In the overview section of Graph app, Supported account type for graph app should be **My Organization**

**Comment by lbgrasso** [comment]
That's correct too. Take into account that the other sending methods work properly.

**Comment by gsv022** [comment]
Please let us know if you are having any issue

**Comment by lbgrasso** [comment]
I still have the same issue, there was no solution.

**Comment by lbgrasso** [comment]
lbgrasso@tenaris.com

**Comment by gsv022** [comment]
We have started message over teams. Please check and respond

**Comment by gsv022** [comment]
@lbgrasso , Thanks for joining the call. Here is the summary.
Fourth sending option started working upon updating the AzureAd:ClientSecret value in App service configuration section with relevant value. Please let us know if you face any issues otherwise we will make it to closure.

**Comment by erikdiaz** [comment]
@lbgrasso Hi, I have the very same issue,

I have cross-verified set-up authentication step in the graph app registration.

And I have verified the secrets in the key vault, they match.

However, the fourth option (Send in chat to members of the following M365 groups, Distribution groups or Security groups) keeps saying "Permissions needed. Ask your IT admin to enable this option for you."

Would you please help me?

**Comment by erikdiaz** [comment]
Hi @gsv022 

I have the very same issue,

I have cross-verified set-up authentication step in the graph app registration.

And I have verified the secrets in the key vault, they match.

However, the fourth option (Send in chat to members of the following M365 groups, Distribution groups or Security groups) keeps saying "Permissions needed. Ask your IT admin to enable this option for you."

Would you please help me?

**Comment by gsv022** [comment]
@lbgrasso , Closing out the issue as the secret was incorrectly configured  and upon updating the parameter-AzureAd:ClientSecret with GraphApp Password in App service configuration section, 4th sending option started working.
