### ISSUE TITLE
What to remove an option

### ISSUE THREAD

**Issue by salviroshan89** [OfficeDev/microsoft-teams-apps-company-communicator#1399]
Hi Team, 

From the Company Communicator (Autors) App we want to remvoe below option:

"Send in chat to everyone"

Could you provide the steps to do so?

![image (16)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/108810665/6343a481-e864-47d6-b0c9-65581f9db4ef)

**Comment by gsv022** [comment]
Hi @salviroshan89 ,
Thanks for raising the query. Our support scope is very limited to official version of CC. Any procedure to remove or to add a feature on top of official version will be considered as customization. We won't be able assist much here. Please let us know if you are having issues w.r.t standard version.

**Comment by salviroshan89** [comment]
The thing is we dont want Authors to accidently send a mass message using Send in Chat to everyone option, so if you could provide a way to block this option then that would be much appreciated.

**Comment by gsv022** [comment]
Hi @salviroshan89 ,
Currently, we don't have enable disable feature for respective sending options.
This has been added to our backlog list and will be planning to implement it in future releases post the discussion with our internal team.

-
