### ISSUE TITLE
Issue with CC V5.5.2 - Sending Messages

### ISSUE THREAD

**Issue by srojas1591** [OfficeDev/microsoft-teams-apps-company-communicator#1400]
Hello,

Recently, we deployed version 5.5.2 of Company Communicator; however, when we send the message, it doesn't reach all users, only about 60%.

When we review the report, it indicates that many users don't have the app installed, but we have verified that they do have it installed correctly.

tenant id 1e315b97-afad-4dd3-8924-d10acb763960

<img width="349" alt="imagen" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39104462/7126a03f-e8e3-498c-9a2a-a445824e41a7">

We see this errors in the export

![Screenshot 2024-04-10 172024](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/39104462/fe7b6db6-69f5-4417-b154-bcb333e573bf)

We appreciate your assistance

**Comment by gsv022** [comment]
Hi @srojas1591 ,
Thanks for raising the query.. Could you please respond to the below queries,

- Is there increase in the every message delivered?
- Through which sending option the message has been sent?
