### ISSUE TITLE
Manual Deployment failed when creating prep-function/web and function/web

### ISSUE THREAD

**Issue by mibohlindemo** [OfficeDev/microsoft-teams-apps-company-communicator#1401]
Documented the error in doc 
[CC Deployment error.docx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/14951765/CC.Deployment.error.docx)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/105378019/5f01413c-052f-4ac9-893b-439d093cb3d8)

**Comment by gsv022** [comment]
Hi @mibohlindemo ,
Thanks for raising the query. 
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again
