### ISSUE TITLE
What is the procedure to backup messages from company communicator app?

### ISSUE THREAD

**Issue by disana8131** [OfficeDev/microsoft-teams-apps-company-communicator#1402]
Hello, I have a public sector customer that is trying to migrate their company communicator app to the new application, however before working on that they need to backup their messages because of the audit process they need to present.

**Comment by gsv022** [comment]
Hi @disana8131 ,
Thanks for raising the query. 

- What is the current version of the application?
- If the migration is going to be done from existing version to the latest version, old data will be preserved and no data loss observed.

**Comment by disana8131** [comment]
Hello, please see below my comments:

1. Version 4.0
2. The idea is to migrate to viva amplify

**Comment by gsv022** [comment]
Hi @disana8131 ,
If it is going to be fresh deployment due to the old version has some issues then moving the history of data from older version to new version is a tedious task which may have some bad consequences. We are of no use in this scenario here as we have not done  it till now. We recommend you to try it on your own.

Thank you.

**Comment by disana8131** [comment]
Thanks a lot for this information, however the customer wants to try this activity, is it possible you can send me the steps require to execute the backup? even know this is not recommend it?

**Comment by gsv022** [comment]
> Thanks a lot for this information, however the customer wants to try this activity, is it possible you can send me the steps require to execute the backup? even know this is not recommend it?

Normally keeping the storage account untouched in a resource group would be the best option but please check it out from your end and we can't comment much here. Thank you
