### ISSUE TITLE
RoleAssignmentUpdateNotPermitted upon deployment using Powershell

### ISSUE THREAD

**Issue by seddon** [OfficeDev/microsoft-teams-apps-company-communicator#1404]
Hi,

I tried deploying via the powershell deployment (i reverted back to known working version 2.30.0 of the Azure CLI to get around the Entra App registration errors), but i am getting the following error when it tries to deploy the Azure resources:

`[
  {
    "additionalInfo": null,
    "code": "BadRequest",
    "details": [
      {
        "additionalInfo": null,
        "code": null,
        "details": null,
        "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",
        "target": null
      },
      {
        "additionalInfo": null,
        "code": "BadRequest",
        "details": null,
        "message": null,
        "target": null
      },
      {
        "additionalInfo": null,
        "code": null,
        "details": null,
        "message": null,
        "target": null
      }
    ],
    "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  }
]
`

**Comment by gsv022** [comment]
Hi @seddon ,
Thanks for raising the query. Please follow this [troubleshooting guide-2nd question](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#2-app-deployment-failure---roleassignmentupdatenotpermitted) to overcome this issue.
