### ISSUE TITLE
User Icon

### ISSUE THREAD

**Issue by ColinDPo** [OfficeDev/microsoft-teams-apps-company-communicator#1406]
Hi

I am responding to an earlier issue reported under #1293 - I have followed the guidelines to update the user icon but my users are still receiving messages which have the default bot icon. I've tried this on the web and client versions and its still not showing the udpated icon i've set in the deployment.  Can someone please advise where I could look or may be going wrong?

**Comment by gsv022** [comment]
Hi @ColinDPo ,
Thanks for raising the query. Could you please share the supporting screenshots where it is getting reflected and where it not getting reflected.

**Comment by ColinDPo** [comment]
Hi,

Thanks for the response, the below is what I was advised to configure

![Company Communicator Bot Profile](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/155746940/b2f42f7a-8f9d-437b-9531-09887e9501a2)
![Company Communicator Recipient Icon](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/155746940/d33ec23e-29b6-483f-b84a-e764068fc146)

The images show the icon on the bot profile and also the icon received by end users when they get the message.

**Comment by gsv022** [comment]
Hi @ColinDPo ,
Please share your mail id so that we can discuss the issue internally.

**Comment by ColinDPo** [comment]
Hi,

Do you mean my email address which you have from this email?



Colin Power

Enterprise Architect








________________________________

**Comment by gsv022** [comment]
Please share the mail id directly here on GitHub

**Comment by ColinDPo** [comment]
colin.power@slough.gov.uk

**Comment by gsv022** [comment]
Started the conversation internally.

**Comment by gsv022** [comment]
Hi @ColinDPo ,
Please respond if you are still facing the issue over teams chat other wise we will make it to closure

**Comment by gsv022** [comment]
Closing out the issue as user confirmed that issue got resolved.
