### ISSUE TITLE
Send in chat 'M365 Groups, Distribution Groups and Security Groups' not working

### ISSUE THREAD

**Issue by AnderOllive** [OfficeDev/microsoft-teams-apps-company-communicator#1407]
Hi all, 

**When I select this option in Company Communicator, appear message bellow!**
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88772391/8d1c29a5-8802-4d92-b492-949d9f82f766)

**In App Registration 'Company Communicator APP', I add these options:**
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88772391/e55817f5-3079-41b3-835e-5d4b2d8dbec2)

I don’t know where I add permissions for this option to be active. Someone can help me, please!

**Comment by gsv022** [comment]
Hi @AnderOllive ,
Thanks for raising the query.

- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/26955650-5cbc-4ff8-9004-d187fb918ed7)

<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">

**Comment by AnderOllive** [comment]
Hi @gsv022, follows the prints below

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88772391/6a141c71-1798-415e-98ff-41a827f5cced)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88772391/6919e4b3-6d9c-492f-a7e5-f365915b1795)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88772391/7cc79c2a-d641-496f-9ee1-448177fa9eba)

**Comment by gsv022** [comment]
Hi @AnderOllive ,
Thank you for sharing the screenshots. Our support scope is very limited with the standard version. We won't be able to assist on this request as it will fall under customization. Please let us know if you have any issues with the standard version.

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
