### ISSUE TITLE
Error sending msgs company communicator [The orchestrator function 'SyncRecipientsOrchestrator']

### ISSUE THREAD

**Issue by AMPA-PND** [OfficeDev/microsoft-teams-apps-company-communicator#1408]
After updating the client secrets, the application displays the following error:

Errores
Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.". See the function execution logs for additional details.

And the consequent warnings:

Failed to get members for group e73795xxxxxxxxx98: Code: generalException Message: An error occurred sending the request. Failed to get members for group e73795xxxxxxxxx98: Code: generalException Message: An error occurred sending the request. Failed to get members for group e73795xxxxxxxxx98: Code: generalException Message: An error occurred sending the request.

The version of the app is : 4.0

Thanks for any advice

**Comment by gsv022** [comment]
Hi @AMPA-PND ,
Thanks for raising the query.

- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/26955650-5cbc-4ff8-9004-d187fb918ed7)

<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">

- So before updating the secrets, was aplication working fine?
- What are the steps performed for updating secrets?

**Comment by guisantiClair** [comment]
Hi, good evening!
I'm having the same problem. Is there a solution?
