### ISSUE TITLE
Sending to distribution list fails CC 5.5.2

### ISSUE THREAD

**Issue by wstokes64** [OfficeDev/microsoft-teams-apps-company-communicator#1409]
We have customer with new deployment of Company Comminucator 5.5.2. When they send to a teams channels messages work fine however they send to mail enabled group all messages fail except for the message to me.

Errors in the log report a 403 failed error

Microsoft.Bot.Schema.ErrorResponseException:   Operation returned an invalid status code 'Forbidden'        at   Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String   conversationId, String activityId, Activity activity, Dictionary`2   customHeaders, CancellationToken cancellationToken)        at   Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations   operations, String conversationId, String activityId, Activity activity,   CancellationToken cancellationToken)        at   Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext   turnContext, Activity[] activities, CancellationToken   cancellationToken)        at   Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter\|1>d.MoveNext()     --- End of stack trace from previous location ---        at   Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity,   CancellationToken cancellationToken)        at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext()   in   C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94     --- End of stack trace from previous location ---        at   Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action,   Context context, CancellationToken cancellationToken, ExceptionPredicates   shouldRetryExceptionPredicates, ResultPredicates`1   shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount,   IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean   continueOnCapturedContext)        at   Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context,   CancellationToken cancellationToken, Boolean continueOnCapturedContext)        at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext()   in   C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94
--

This is a new app install with the customs app allowed in the TA,

**Comment by gsv022** [comment]
Hi @wstokes64 ,
Thanks for raising the query. Could you please confirm on the below queries.

- Please share the export results of the latest sent message
- If it is a team, please try adding user app to that team and send the message using 2nd sending option.

**Comment by wstokes64** [comment]
Attached is he a sample of the export report now. 

Sending to a team is working fine this error occurs when send to distribution list

[report.xlsx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/15031012/report.xlsx)

**Comment by gsv022** [comment]
@wstokes64 , Could you please create a test team(not DL/Group) add these users to that team and add the user app to that team. Then try sending a message using 2nd sending option.

Once it is done then try using 4th sending option

**Comment by wstokes64** [comment]
I have created a test teams group. Added myself and a colleague to it added the user bot to the team. When I send it I get a failure for all users but mine. Attahced are the logs. 

<img width="741" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88414069/eee8b8c6-b3e4-471e-bd0e-56b80900a608">
[ExportData_dbae91d8-8606-4f7b-ab51-1afd71cac060.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/15055086/ExportData_dbae91d8-8606-4f7b-ab51-1afd71cac060.zip)

**Comment by wstokes64** [comment]
@gsv022 can we schedule a call? I am based in NZT

**Comment by gsv022** [comment]
Sure, please share your outlook id so that we can discuss internally

**Comment by wstokes64** [comment]
will.stokes@synergytech.co.nz

**Comment by wstokes64** [comment]
Can you have a catch up on this issue @gsv022

**Comment by gsv022** [comment]
We have reached out to you via mail.  Please check and respond
