### ISSUE TITLE
What's the support structure and SLA for the Company Communicator?

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1410]
I have a question regarding the support structure and SLA for the Company Communicator after deploying its components on the Azure platform. 

How do we log the support ticket to Microsoft is it M365 (teams) or Azure team?

Thank you in advance.

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Thanks for raising the query. 

- Please refer to the [support-policy](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Support-policy) for detailed information on CC.

- _How do we log the support ticket to Microsoft is it M365 (teams) or Azure team?_
    Depending upon the subjected issue please reach to the relevant support team, we don't have much information here.

**Comment by albert-widjaja** [comment]
Thank you @gsv022

**Comment by gsv022** [comment]
We are closing out the issue as the query is responded. Please feel free to log the issue if you encounter any issue w.r.t CC
