### ISSUE TITLE
V5.5.2 - No " delete messages " button

### ISSUE THREAD

**Issue by mavistangtpl** [OfficeDev/microsoft-teams-apps-company-communicator#1415]
I don't see a "delete message" button in the CC app, but I can see a "delete message button " in the code. I'm also using v5.5.2. How should I modify this?

![Screenshot 2024-04-22 120440](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/8edb2521-9132-467b-a8a1-5fe07fbff834)

![Screenshot 2024-04-22 120514](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/9460052b-4b4c-4329-adf3-81fbf8e3e554)

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Thanks for raising the query.

- Please make sure that all the parameters present in the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) are added to the configuration of App Service. After addition of parameters, perform SYNC by visiting the deployment center of app service.  Below are the parameters must be present.
_**REACT_APP_AUTHORIZED_USERS_EMAIL** : Semicolon-delimited list of the user principal names (UPNs) allowed to delete historical messages.
**AuthorizedDeleteUpns** : Semicolon-delimited list of the user principal names (UPNs) allowed to delete historical messages.
**DataFunctionUrl** : https://[BASE_RESOURCE_NAME]-data-function.azurewebsites.net/api/CompanyCommunicatorDataCleanUpFunction_

- After sync, try opening the teams in browser(preferably incognito/in private window) and then try accessing the application, the option to delete will be visible.

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , Thanks for raising the query.
> 
> * Please make sure that all the parameters present in the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-) are added to the configuration of App Service. After addition of parameters, perform SYNC by visiting the deployment center of app service.  Below are the parameters must be present.
>   _**REACT_APP_AUTHORIZED_USERS_EMAIL** : Semicolon-delimited list of the user principal names (UPNs) allowed to delete historical messages.
>   **AuthorizedDeleteUpns** : Semicolon-delimited list of the user principal names (UPNs) allowed to delete historical messages.
>   **DataFunctionUrl** : https://[BASE_RESOURCE_NAME]-data-function.azurewebsites.net/api/CompanyCommunicatorDataCleanUpFunction_
> * After sync, try opening the teams in browser(preferably incognito/in private window) and then try accessing the application, the option to delete will be visible.

I have updated REACT_APP_AUTHORIZED_USERS_EMAIL, AuthorizedDeleteUpns and DataFunctionUrl already, but can't find the "delete message button".
![Screenshot 2024-04-23 113110](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/6ca33d47-bff9-409d-8e34-d3d3286c1952)

**Comment by gsv022** [comment]
Did you perform SYNC after adding the parameters in App Service configuration? If not, please perform. If already performed, do it again and open the teams in incognito window and access the application.

**Comment by mavistangtpl** [comment]
> * How about this parameter, what is the value kept here?
>   _**DisableDeleteUpnCheck** : True or False to enable to delete historical messages feature._
> * Did you perform SYNC after adding the parameters in App Service configuration? If not, please perform. If already performed, do it again and open the teams in incognito window and access the application.

- DisableDeleteUpnCheck : False 


- Did you mean SYNC in deployment Center again? Because I've already SYNC to v5.5.2.
   I have restart app service and 3 functions. Also tried open the teams in incognito window and access the application.

**Comment by gsv022** [comment]
Yes, once the changes are updated in configuration section of App service, there is need for SYNC to be performed. Please do it.

**Comment by mavistangtpl** [comment]
> Yes, once the changes are updated in configuration section of App service, there is need for SYNC to be performed. Please do it. The SYNC can be performed in deployment center of App service

After SYNC can be performed. But if I download the zip file in github and publish. I can't find the delete msg button again, Why? How can I slove this problem?

After SYNC :
![Screenshot 2024-04-25 181550](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/684e443c-d9be-4b8c-ba67-d5070ed3febb)

 After publish :
 
![Screenshot 2024-04-22 120440](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/19a09e2a-359f-4cc5-8729-423ad5d99484)

**Comment by mavistangtpl** [comment]
> > Yes, once the changes are updated in configuration section of App service, there is need for SYNC to be performed. Please do it. The SYNC can be performed in deployment center of App service
> 
> After SYNC can be performed. But if I download the zip file in github and publish. I can't find the delete msg button again, Why? How can I slove this problem?
> 
> After SYNC : ![Screenshot 2024-04-25 181550](https://private-user-images.githubusercontent.com/68589208/325837088-684e443c-d9be-4b8c-ba67-d5070ed3febb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDc2MzEsIm5iZiI6MTcxNDQ0NzMzMSwicGF0aCI6Ii82ODU4OTIwOC8zMjU4MzcwODgtNjg0ZTQ0M2MtZDliZS00YjhjLWJhNjctZDUwNzBlZDNmZWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAzMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTBjZmFiMGVmNGQ0YWZmNjYwMzNlNmIwZDM3NTBiMTJkYmMzZTk2MjA2NjU2NjQ3NTFjMDgwMmJjNzc2NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UZ1_N2Yzp3GJtV4bmb9JIRicJW7Ti2C0Ofzxqxge9yE)
> 
> After publish :
> 
> ![Screenshot 2024-04-22 120440](https://private-user-images.githubusercontent.com/68589208/325837211-19a09e2a-359f-4cc5-8729-423ad5d99484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDc2MzEsIm5iZiI6MTcxNDQ0NzMzMSwicGF0aCI6Ii82ODU4OTIwOC8zMjU4MzcyMTEtMTlhMDllMmEtMzU5Zi00Y2M1LTg3MjktNDIzYWQ1ZDk5NDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAzMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NDIzM2U5NjU1Yzk4ZjBlZWFjNmJiYzAwOWVjMGZhYTg1ODJiNTk4MGQ5MjhiNDcyMzFkZGY2ZDdjM2ZmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zp8UeNarPbpPKWQzeM7Dr5Ip4eTd_Q4sY4OpTC9lHTI)

@gsv022 Please help to solve the problem. Thanks!

**Comment by gsv022** [comment]
Once we perform SYNC, there is no need to re-upload the manifest files again.

**Comment by mavistangtpl** [comment]
> Once we perform SYNC, there is no need to re-upload the manifest files again.

@gsv022 After downloading the v5.5.2 zip file, when I publish it to Azure in Visual Studio, the "delete message button" disappears. How can I solve this?

**Comment by gsv022** [comment]
There is no need of downloading the zip file as there will already a manifest files uploaded. The only step is to perform SYNC. It seems that you have already completed. Now, if you are re-uploading, please do it via teams admin center

**Comment by mavistangtpl** [comment]
> There is no need of downloading the zip file as there will already a manifest files uploaded. The only step is to perform SYNC. It seems that you have already completed. Now, if you are re-uploading, please do it via teams admin center

@gsv022 Why isn't the method of publishing to Azure working? Because I want to use the publish method, but there's no "delete message" option. I saw that it should be included in 'app.ts'. Thank you!

**Comment by gsv022** [comment]
Our support scope is very limited to deployment and functionality issues. The procedure is restricted to either manual/PowerShell. Please proceed as per the deployment guide.

Let us know if any blockers are observed

**Comment by mavistangtpl** [comment]
> Our support scope is very limited to deployment and functionality issues. The procedure is restricted to either manual/PowerShell. Please proceed as per the deployment guide.
> 
> Let us know if any blockers are observed

@gsv022 So now, after publishing, I'm missing the "delete message button" and would like to know how to resolve this.

**Comment by gsv022** [comment]
> Our support scope is very limited to deployment and functionality issues. The procedure is restricted to either manual/PowerShell. Please proceed as per the deployment guide.
> 
> Let us know if any blockers are observed

I stress the point again. We couldn't assist much here.
