### ISSUE TITLE
Azure front door configtab error author app

### ISSUE THREAD

**Issue by YubiPopper** [OfficeDev/microsoft-teams-apps-company-communicator#1417]
I'm having a problem adding the author app to a team, the tab page errors with "page not found", the URL is the /configtab.

Manifest is the same as before when added on an old team, the tab no longer loads on that old team. I have sync'ed the deployment which has a successful state, not sure what is going wrong? 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88183612/1710cce1-8e4f-465b-ae34-770998a8ebf1)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/88183612/9234638a-7cb6-433a-ba36-88a52deb5452)

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
  "manifestVersion": "1.5",
  "version": "5.5.2",
  "id": "1c07cd26-a088-4db8-8928-ace382fa219f",
  "packageName": "com.microsoft.teams.companycommunicator.authors",
  "developer": {
    "name": "redacted",
    "websiteUrl": "redacted",
    "privacyUrl": "redacted",
    "termsOfUseUrl": "redacted"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Daily update (Authors)",
    "full": "Daily update (Authors)"
  },
  "description": {
    "short": "Broadcast messages to multiple teams and people in one go",
    "full": "Broadcasts messages to multiple teams and individuals through channel posts and chat messages"
  },
  "accentColor": "#64A2CC",
  "configurableTabs": [{
    "configurationUrl": "https://redacted.azurefd.net/configtab",
    "canUpdateConfiguration": true,
    "scopes": [
      "team"
    ]
  }],
  "bots": [{
    "botId": "c34656e0-9725-41d0-969b-2ea05cf0d035",
    "scopes": [
      "team"
    ],
    "supportsFiles": true,
    "isNotificationOnly": true
  }],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "https://redacted.azurefd.net"
  ],
  "webApplicationInfo": {
    "id": "c34656e0-9725-41d0-969b-2ea05cf0d035",
    "resource": "api://https://redacted.azurefd.net"
  }
}

**Comment by YubiPopper** [comment]
Tried the manifest change but still the same

**Comment by gsv022** [comment]
Hi @YubiPopper ,
Thanks for raising the query. Please share the zipped manifest files of both author and user

**Comment by YubiPopper** [comment]
Hi, I did a re-deployment for the resource group which has fixed the front door page not found. Not really sure what changed but working now...
