### ISSUE TITLE
Message not delivered for large audience. V5.5.1

### ISSUE THREAD

**Issue by itsmeprodyut** [OfficeDev/microsoft-teams-apps-company-communicator#1419]
The Company Communicator App version 5.5.1 has been deployed successfully on the production tenant. However, while sending messages to 'everyone in chat', there's been a significant failure rate of 40-50%, affecting 80,000 out of 140,000 users. Despite the error message indicating a failure to install the user app due to unavailability in the App catalog, this doesn't seem to be the case universally. Further investigation reveals 404 and transportation connection errors for the failed requests in the App Insight. Interestingly, previous versions (V5.4) of the app were able to broadcast messages seamlessly to 150,000 users. The query now is to identify the potential issues with this current version of the app. Any insights or feedback on this matter would be highly appreciated.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/137884321/1d55ee49-708a-4274-ab8f-6f2c4793dd95)

<img width="930" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/137884321/dd09855d-144d-4290-aa5e-669fdea0da39">

<img width="650" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/137884321/2b64342b-d092-4269-8109-f283214d92e1">

**Comment by gsv022** [comment]
Hi @itsmeprodyut ,
Thanks for raising the query. Please confirm on the below queries.

- Could you please share the export data of one message which delivered to all 150k users in v5.4 and one with 80k failure in latest version
- Once you updated to the latest version, did you observe any gradual increase or decrease in the success count?

**Comment by itsmeprodyut** [comment]
Thank you for your attention to the ongoing issue we're encountering with our Microsoft Teams app deployment.

To provide some context, we have initiated a separate deployment of version 5.5.1 to a distinct resource group, accompanied by a dedicated Azure AD app registration. This approach was undertaken to prevent any potential conflicts with the previous version, which remains active. However, as the previous version is incompatible with New Teams, we have maintained the Azure resources for this version while we ensure the successful integration of the new version.

Unfortunately, despite our efforts, the installation of the app for approximately 80,000 users has failed after an extended period of 4 to 5 hours. Regrettably, due to the sensitive nature of client data, we are unable to share detailed logs or information in an open forum. Our client is a significant entity with an established unified support system with Microsoft, emphasizing the importance of confidentiality and stringent data handling protocols.

Upon further investigation, we observed that the proactive installation settings were incorrectly configured for the data-function and send-function, with the values set to false. Subsequent adjustments were made to set these values to true for both the prep-function and data function. As a result, we re-initiated the broadcasting, successfully reaching 60,000 out of 150,000 users. While this adjustment yielded a notable increase in user reach, it raises questions about the necessity of such changes, as outlined in a relevant troubleshooting blog.

We suspect that the installation failure for the remaining 80,000 users may be attributed to throttling issues or other technical constraints. As sharing logs and detailed information publicly is not feasible, we propose re-initiating this discussion internally with Microsoft and in collaboration with our client through our unified channel. We believe that involving your team in this investigation could provide valuable insights and expedite the resolution process.

Given that our environment is in production, with approximately 140,000 real-time users, replication in a UAT/DEV environment is impractical. Furthermore, testing by repeatedly sending messages from production to live users is not viable due to potential disruption.

We appreciate your understanding and support in addressing this critical issue. Please let us know the best course of action to proceed with collaboration and investigation.

**Comment by itsmeprodyut** [comment]
Hi @gsv022 , 

We have retry sending message today and this time it has failed for 37K users. Looks like there is an increase of numbers in each iteration. Now we have 37K users left for the proactive installation and that will potentially work in next iteration ! Any suggestion ?

**Comment by gsv022** [comment]
Hi @itsmeprodyut ,
We will get back to you with proper response soon
