### ISSUE TITLE
new team not displaying Company Communicator properly‎ (#‎2404240040004149‎)

### ISSUE THREAD

**Issue by thomj005** [OfficeDev/microsoft-teams-apps-company-communicator#1420]
Company Communicator had name change done in Author bot. Changes made properly in json file. However in New Teams, only, the old information is still showing along with her picture. This is bringing up 2 issues. We have to remove the users name because they are not with the Comp. anymore. Also, access is not working for us on the author bot unless we switch back to Classic Teams. This makes the Company Communicator unusable for us. Please have someone create a Teams meeting ASAP so we can resolve this. Will this app work in new teams how do we remove the name that still exists? How do we remove the picture. Please advise as soon as possible.

**Comment by gsv022** [comment]
Hi @thomj005 ,
Thanks for raising the query. 

### **To update name of CC**
•	Login to Azure Portal with Global Admin Credentials (portal.azure.com)
•	Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
•	Click on Azure Bot(user/author) --> under settings click bot profile-->Change display name as per the organizational need. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/cae48233-dfd5-4094-8862-692fd2165eaf)
•	And update the names in the manifest files for user/author. Re-upload the zipped manifest file again. Here is the place for reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/3212ca98-1e39-4631-b1b4-284c1b634e8a)

 
### **To change the icon:** 
•	Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
•	Click on Azure Bot(user/Author) --> under settings click bot profile-->Upload custom icon. Change the icon as per the organizational requirement.
•	In the manifest folder, update the same icon. Please make sure that it is having the required dimensions same as default icons.
**Note:-**
•	There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.
•	In the ‘Icon’ field, it is recommended to upload the size 192x192.
•	The same procedure can be performed for both author and user apps.
•	To change the header logo and header text in the below place.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/35c1a3db-db59-4483-af9b-e356ec118f12)  
•	Go to app service --> Configuration--> Update React_App_HeaderImage and text. For image, please make sure that the url should be valid type and publicly accessible.
      
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/c16f8923-4459-4897-9aac-a8261bf0f8ac)
                
------------------------------------------------------------------------
###  **Also, access is not working for us on the author bot unless we switch back to Classic Teams.**

Could you please share the screenshot showing the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/26955650-5cbc-4ff8-9004-d187fb918ed7)

<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">

**Comment by Rajatextoutokumpu** [comment]
Hi @gsv022 , I am also facing the same issue , when opening the Authors bot in New teams , it says like this "Your administrator has configured the application Company Communicator App to block users unless they are specifically granted ('assigned') access to the application. The signed in user 'abc@mail.com' is blocked because they are not a direct member of a group with access, nor had access directly assigned by an administrator. Please contact your administrator to assign access to this application. But my admin has assigned policies to me , and given every access. This issue is not there in older teams

**Comment by thomj005** [comment]
Upgraded successfully to 5.3.1 yesterday. Verified access list and that I am still on it. However I still cannot access the teams channel. Please see attached. I have no idea what is causing this.
![2024-04-26_06h49_31](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168004094/2ecee5ae-69fc-4a58-9946-1385ad46c731)
![2024-04-26_06h50_11](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168004094/6b3bce35-429a-4e8f-94bb-e2beb63329f3)
![2024-04-26_06h49_31](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168004094/f9a86067-3b93-42f8-b1be-10af9fe24ada)

**Comment by thomj005** [comment]
Oh, and I do not get the error when I use teams classic. I also forgot one other screenshot.

![2024-04-26_07h04_04](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168004094/8615d9b3-87aa-442c-8fcd-bf83ccfcc936)

**Comment by mtlozl** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168128049/9007eeb0-916f-4dcb-853e-0c25c3dd1ed2)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168128049/382355e5-55c5-44f5-9517-de6d1b219b9c)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168128049/38f2a5e6-81ea-4420-9bef-b91d7604e1cf)

**Comment by thomj005** [comment]
Not sure what the above is meaning or trying to point to.

**Comment by mtlozl** [comment]
Author mode is not working on the new teams app. But classic teams app it works for author..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thomj005** [comment]
Correct so how do we fix it?

**Comment by gsv022** [comment]
Hi @mtlozl,
Thank you for sharing the screenshots. Our support scope is very limited with the standard version. We won't be able to assist on this request as it will fall under customization. Please let us know if you have any issues with the standard version.

Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

**Comment by mtlozl** [comment]
> Hi @mtlozl, Thank you for sharing the screenshots. Our support scope is very limited with the standard version. We won't be able to assist on this request as it will fall under customization. Please let us know if you have any issues with the standard version.
> 
> Official repository:- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

Hello Venkat,

We use official repo and we could not use author module in the new teams app.

Regards

Mutlu

**Comment by gsv022** [comment]
> Oh, and I do not get the error when I use teams classic. I also forgot one other screenshot.
> 
> ![2024-04-26_07h04_04](https://private-user-images.githubusercontent.com/168004094/325970262-8615d9b3-87aa-442c-8fcd-bf83ccfcc936.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjkyMTQsIm5iZiI6MTcxNDQ2ODkxNCwicGF0aCI6Ii8xNjgwMDQwOTQvMzI1OTcwMjYyLTg2MTVkOWIzLTg3YWEtNDQyYy04ZmNkLWJmODNjY2ZjYzkzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwOTIxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjU5MmNjNWZiZTllOTMyZDRmYWFmMjhhMTBiMDE5ZmM4M2MwYTA4ZTU2ODE3M2M1NWQyM2M2ZGU1NTYzNjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vqbc-XNAnfMYJlyYJRheu5H1Zr54qt24ryBcg-as45M)

The above screenshot is pointing to custom version. Please clarify whether the deployment done initially connected to custom repo, after that disconnected custom repo and connected to official repo.

**Comment by mtlozl** [comment]
> Correct so how do we fix it?

Hello,

i have to resolve my problem with below steps;
- Step-1: Apply to "Disconnect" button in the Deployment Center ( for all functions and for app service )
- Step-2: Wait for delete process, approx. 1 hour
- Step-3: Change App Service Plan from S1 to S2 ( for memory problem, when you deploy app service )
- Step-4: Add "External Git" repo in the Deployment Center for all functions and for app service, with BRANCH: "main" ( "main" name is the goal for the problem )
- Step-5: Wait and Watch the Deployment Logs from Deployment Center > Logs ( for all functions and for app service )
- Step-6: When complete the Deployment ( you will see the result for deployment logs ) and then restart all functions and app service
- Step-7: Logout, New Teams App and login again. Success..
