### ISSUE TITLE
Queries reg. to upgrading from version 5.3.0 to latest version 5.5.2 of the company communicator

### ISSUE THREAD

**Issue by SachinWandale111** [OfficeDev/microsoft-teams-apps-company-communicator#1421]
Hello team
Our tenant is currently using CC version 5.3.0, however we wanted to update to the more recent version, 5.5.2.
These are the general procedures that we followed after going through the migration guide, which we were able to view inside.
i) Get the latest version (5.5.2) of the Solution folder from GitHub. - We have it downloaded already.
ii) Bring the current.Azure Functions and App Service's Net version  to .NET 6.0 LTS
iii) Select Function runtime settings by clicking on *-prep-function, then Configuration.
Choose ~4 as the runtime version. Select for *-function and *-data-function in a similar manner.

Since steps number ii) and number iii) have already been finished during 5.3.0 migration, we currently have a .Net version  to .NET 6.0 LTS of Azure Functions and App Service that supports function runtime settings to 4.
Does this mean we have to repeat these steps? or not necessary. Also can you share the required steps only for migrating to new version 5.5.2?
After you confirm the aforementioned inquiries, we will contact you regarding the remaining migration-related inquiries.  Please find below screenshot for your reference.

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
Thanks for raising the query. Since you are on v5.3. Follow the below steps

- Perform migration of classic application insights to workspace application insights. Here is the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#migrating-classic-application-insights-to-workspace-based-application-insights). Choose any of the two approaches which ever you feel comfortable.
- Skip the first step in upgrading from v5.x to latest as it is already completed.
- Go to [Step 2-Validate and update app config settings and sync to the latest code](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#2-validate-and-update-the-config-settings-and-sync-to-the-lastest-code-). Check whichever parameter is missing in app service configuration, add them
- You might have observed 401 in the logs coming constantly, to overcome this issue we have introduced a permanent fix. Please follow this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)

**Comment by SachinWandale111** [comment]
Hello Sai
I appreciate your quick reply. We have finished "Step-2 Validate and update the config settings and sync to the latest code" and inserted all necessary details during the 5.3.0 version upgrade. The actions listed below are already in place as mentioned on GitHub version upgrade guide.
What are the last few steps we should think about taking to upgrade from version 5.3.0 to the most recent version 5.5.2?

Please clarify if we also need to upload the users and author manifest files to Teams Admin Center as well.


<img width="568" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/f7c17b99-49be-49b2-8020-f9cc8aeebf0d">

**Comment by gsv022** [comment]
@SachinWandale111 , 

- After v5.3 there are some new features which got introduced like schedule send, Delete the sent messages etc., so there are new parameters added to configuration of app service. Below is the reference showing the parameters.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/056a37ae-7ffb-4d35-b594-a6aec249aa68">

- If these parameters are not added, add them and perform SYNC in the deployment center.

- _Please clarify if we also need to upload the users and author manifest files to Teams Admin Center as well._
   No need to re-upload the manifest files again.

- After the above steps are completed, try opening the teams on browser and access the application.

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Thanks for your clarification. We have few more quires listed below.
i) What actions must be considered if the requester wants to modify the application name for the user and author?
ii) Does the manifest file need to be reuploaded again for the same?
iii) Is it possible to obtain/download the current user and author application manifest file? If so, could you please share the instructions?
iv) If not is there any way to check the all existing values inside to user and author menifest file as currently we are using 5.3.0 version?
for example: author application
name": {
 "short": "<name>",
 "full": "<full name>",
"botId"
"validDomains"
"webApplicationInfo"
"id": "<id>",
    "resource": "api://<<->>"

**Comment by SachinWandale111** [comment]
Hello @gsv022 ,
Could kindly update us on above query asap please?

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
_i) What actions must be considered if the requester wants to modify the application name for the user and author?_
To update name of CC

- Login to Azure Portal with Global Admin Credentials (portal.azure.com)
- Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
-  Click on Azure Bot(user) --> under settings click bot profile-->Change display name as per the organizational need.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/98143492/213981428-e5af8e1e-8623-4731-b413-8cc62cc3c475.png">

- And update the names in the manifest files for user. Re-upload the manifest file again. Here is the place for reference.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/98143492/213983428-68678fb4-03ae-4a95-933e-0d8e4b4f802d.png">

- _Is there a way I can change this when I don't have the original manifest files._
Please download the manifest from code [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) and update the user manifest as per the  [6th-step](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) of deployment guide

- The above procedure is applicable for both author and user app.

**Note**:- 
There might be chance that desktop app will get cached. However, it can be validated by checking in the browser version of the app.

-----------------------------------------------------------------------------------------------------------------------------
_ii) Does the manifest file need to be reuploaded again for the same?_

Yes
-------------------------------------------------------------------------------------------------------------------------------
_iii) Is it possible to obtain/download the current user and author application manifest file? If so, could you please share the instructions?_

No, it is not possible. If current manifest files are not available, then please download the manifest from code [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) and update the user/author manifest as per the  [6th-step](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) of deployment guide
--------------------------------------------------------------------------------------------------------------------------
_iv) If not is there any way to check the all existing values inside to user and author manifest file as currently we are using 5.3.0 version?_

Three parameters are required for manifest files. 
appdomain- <<Base Resource Name>>.azurefd.net. 
Author Bot Id - Author(application/client id)
User Bot Id - User(application/client id)

All the three parameters can be obtained at one place. Here is the navigation

Go to Azure portal-->Select Resource Group--> In the LHS, under settings, choose deployments--> Select the latest by date microsoft.template(failed/succeeded)-->In the LHS, open inputs-->Base Resource Name, Author Id, User Id can be found here.

**Comment by SachinWandale111** [comment]
Hi @gsv022 ,
Thanks for clarification, regarding to step iv) you mentioned only below three details required in manifest file.
a) Appdomain
b) Authot Bot ID
c) user bot ID

But when we downloaded the manifest file for author its asking for below details as well. Kindly confirm what values we need to enter there as well? For any further additional queries we will get in touch with you.

<img width="250" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/d64bc919-b9fe-46f8-ab7f-7ecfdb754ead">

<img width="230" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/f408b81b-3dbd-4e5e-9d0e-5555e865d293">

**Comment by SachinWandale111** [comment]
Hello @gsv022,
Could kindly assist on above query quickly as soon as possible please? We are awaiting your response.

**Comment by gsv022** [comment]
@SachinWandale111 ,

- _But when we downloaded the manifest file for author its asking for below details as well. Kindly confirm what values we need to enter there as well?
For author manifest file we need to enter author bot id inside to "webApplicationInfo"?_
Yes

- _ii) If our user and author name is same (common) inside to teams app store, then how do we identify between them which one applications is really user and which is author?_
Author manifest and user manifest can be bifurcated by _Support Files_ present within manifest files. If it is true, then it is a author manifest otherwise user manifest
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/07c12e62-37e7-4a88-94a6-de0c7a0dd05f)

- From the user perspective, please name it with accordingly in the 8 line of manifest file before uploading it.
_iii) We also tried to upload the Manifest files for both application (user and author) from Team Admin Center but we are encountered an error, "There's no manifest file in your app package. Check the app package and try again."
As we checked manifest file already present in both user and author zip files. Refer below screenshots. Kindly advise._
Before uploading to teams admin center- validate the manifest file using this link- [App Validator](https://dev.teams.microsoft.com/appvalidation.html)

**Comment by SachinWandale111** [comment]
Hi @gsv022,
i) I appreciate the update. We are running into the following problem when we attempt to upload the manifest files for both users and authors using the [App Validator](https://dev.teams.microsoft.com/appvalidation.html) link. Is there any way we could have a quick conversation to talk about this error? If at all possible, kindly inform us. What is the next course of action for this specific problem, "Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package". Below screenshot is for your reference.

<img width="714" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/287423f4-08da-442b-a336-1457ee20b283">

ii) If our user and author name is same (common) inside to teams app store, then how do we identify between them which one applications is really user and which is author?
Author manifest and user manifest can be bifurcated by Support Files present within manifest files. If it is true, then it is a author manifest otherwise user manifest
image ==> Is it possible to verify the user and author app in teams app store or TAC without checking manifest file, if so kindly confirm.

iii) Also regarding to query we asked "i) What actions must be considered if the requester wants to modify the application name for the user and author?
We are interesting while changing names for user and author application, so in teams app store end user can easily identify between user ad author application. hence we requested to share the steps.
For example for user app "Company Communicator -Users"
For author app we need "Company Communicator -Authors"

**Comment by SachinWandale111** [comment]
Hello @gsv022 
Could kindly assist on above query quickly as soon as possible please? We are awaiting your response.

**Comment by gsv022** [comment]
Please share the zipped manifest files of both author and user

**Comment by SachinWandale111** [comment]
Hi @gsv022 ,

Kindly find the needed zipped files for the author and user applications. Please respond as soon as you can, as this is causing our version upgrade to the most recent version—5.5.2—to be delayed. Please let us know if additional details required.

[company-communicator-users.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/15245225/company-communicator-users.zip)
[company-communicator-authors.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/15245227/company-communicator-authors.zip)

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Due to some Company policy restrictions, we couldn't be able to upload the manifest file here.
Instead, could you kindly able to help us why this error coming? As other customers also might raise case for the similar issue earlier. What are the steps we need to perform to resolve this issue? Also, we can't provide you the client details which are available inside to users and author manifest file.
Also, could you kindly confirm on below parameters which requires to update in manifest file.

i) "configurationUrl": "https://<<appDomain>>/configtab"
For example: our default domain name is "xyz.azurewebsites.net" then the configurationUrl would be like below?

"https://xyz.azurewebsites.ne/configtab" or it need to take from Front Door and CDN profile, for example if the Front end door for our application is hosted on, "https://xyz.azurefd.net" then configurationUrl would be like below?
 "https:///xyz.azurefd.net/configtab"

ii) Also specify below details.

validDomains": [
    "<<appDomain>>" =======> Please refer point number (i) and confirm to us 
  ],
  "webApplicationInfo": {
    "id": "<<botId>>", ========> We need to use user bot id (Client/application id) for user application and author bot id (Client/application id) for author app, please confirm.
    
iii) Also please confirm, "manifestVersion": should be updated as  "1.5" or recent one which is 1.17 in user and author application manifest file?
    "resource": "api://<<appDomain>>"

Please confirm as soon as possible please due this our version upgradation is getting delayed.

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Thanks for confirming. Can you kindly confirm on below two queries one more time.
i) Where we can cross verify the below URL's are correct one? Do we able to verify it from TAC or Azure portal?
 "websiteUrl": "<<websiteUrl>>",
    "privacyUrl": "<<privacyUrl>>",
    "termsOfUseUrl": "<<termsOfUseUrl>>"

ii) Also where to verify the app domain name which we are using right now is correct one?
Do we able to verify it from Azure portal? and how, please share the details steps in azure.

iii) Is there is any way we can setup call to discuss this?

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
_i) Where we can cross verify the below URL's are correct one? Do we able to verify it from TAC or Azure portal?
"websiteUrl": "<>",
"privacyUrl": "<>",
"termsOfUseUrl": "<>"_

These will be URL's of your organization where you can grab those and paste it in the above places.
_ii) Also where to verify the app domain name which we are using right now is correct one?
Do we able to verify it from Azure portal? and how, please share the details steps in azure._
This can be cross verified from App service- configuration part. Here is the reference.
<img width="915" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/96b8a647-30ae-43c6-928e-6c7053a39112">


Please let us know if any queries are there

**Comment by SachinWandale111** [comment]
Hi @gsv022 ,
Thank you for providing the information. We will review it and let you know if we have any more questions.
Please be sure to highlight and disclose all the necessary information that has to be added to the users' and authors' manifest files.
Additionally, kindly share the format with all necessary details. As we are unable to share the Manifest file due to some security concern.

Please provide any template for a manifest file as an additional example.

**Comment by gsv022** [comment]
It is clearly mentioned in the deployment guide on what needs to be updated within manifest file. Moreover I think I have responded to the queries related to manifest files in the above conversation. Please let me know if you have any blockers on manifest files

**Comment by SachinWandale111** [comment]
Hi @gsv022 
We have made all the necessary adjustments to our users' and authors' manifest files in accordance with the deployment guide, however when we attempt to upload the two manifest files (user's and authors) into TAC, an error message appears.  
Error from teams admin center => "We can't read the manifest file. Try again later."
Therefore, it would be very appreciated if you could provide all the information that has to be added to the manifest file once, and if that's feasible, you could also provide the manifest file template for reference. Our version upgrade is being delayed as a result of this.

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
Actually in version upgrade, no need of re-uploading the manifest file because the id's and app domain in the manifest files won't change. Please make sure that after upgrading app is up and running or not.

**Comment by SachinWandale111** [comment]
Hi @gsv022,

As discussed earlier you already confirmed we need to upload the new manifest file for user as well as author application as requester want to modify the existing name of the user and author application in teams app store. Please see below screenshot for the same.
However when we attempt to upload the two manifest files (user's and authors) into TAC, an error message appears.
Error from teams admin center => "We can't read the manifest file. Try again later." Hence we deleted the existing user and author apps from teams admin center and tried to upload it again but still we are getting same error.
Therefore, it would be very appreciated if you could provide all the information that has to be added to the manifest file once, and if that's feasible, you could also provide the manifest file template for reference. Our version upgrade is being delayed as a result of this.


<img width="418" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/431f977a-1844-46a6-a421-d8c9e5933ae7">

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
`If you are facing issues with manifest files, please share them. We will check it`

As I mentioned earlier, please share the manifest files we will verify it.

**Comment by SachinWandale111** [comment]
Hi @gsv022 
Kindly confirm, The data (manifest files for users and authors) which are you requested is it covered under NDA with Microsoft? as we already inform you earlier we are unable to share the Manifest files due to some security concern. Thanks

**Comment by gsv022** [comment]
Please share your mail id so that we can discuss the issue internally

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Could you kindly confirm, once we share the mail ID with you, are you going to share meeting invite to discuss this issue internally or you are going to share any steps over email for further instructions? Thanks

**Comment by SachinWandale111** [comment]
Hi @gsv022, 
Can you kindly confirm on above ask please? Thanks

**Comment by gsv022** [comment]
@SachinWandale111, We will check the issue w.r.t manifest file that you are encountering. May be you can share the manifest files over the personal chat once you share the id and also  if required we can get into call for further troubleshooting

**Comment by SachinWandale111** [comment]
Hi @gsv022,
We will update you on this. Thanks

**Comment by gsv022** [comment]
@SachinWandale111 ,Please keep us posted

**Comment by SachinWandale111** [comment]
Sure. We are discussing on it internally.

**Comment by SachinWandale111** [comment]
Hi @gsv022 
We are still discussing on it internally. Once we have an update will notify you. Thanks

**Comment by gsv022** [comment]
@SachinWandale111 , Please feel free to log a new issue if you have any, even this ticket is closed.

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Kindly keep this case open as we are discussing this internally and taking necessarily approvals for sharing manifest files. Thanks

**Comment by gsv022** [comment]
Any update here?

**Comment by SachinWandale111** [comment]
Hi @gsv022 ,
We are still checking the necessary approval for uploading manifest file on GitHub portal. We will update you soon once we received any updates. Thanks

**Comment by SachinWandale111** [comment]
Hi @gsv022,
We are still checking the necessary approval for uploading manifest file on GitHub portal. We will update you soon once we received any updates. Please keep this keep open. Thanks

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Please find attached manifest files for both user and author application.
Also please note that in both users and authors manifest files, I have removed the below confidential data:
 
i) App ID or Bot ID "<<botId>>", for user bot and author bot
ii) <<appDomain>>"  removed from user and author manifest.
iii) "configurationUrl" removed from author manifest.
[company-communicator-users.zip](https://github.com/user-attachments/files/15982834/company-communicator-users.zip)
[company-communicator-authors.zip](https://github.com/user-attachments/files/15982836/company-communicator-authors.zip)
