### ISSUE TITLE
Author mode is not work in the new teams app

### ISSUE THREAD

**Issue by mtlozl** [OfficeDev/microsoft-teams-apps-company-communicator#1422]
In the teams classic mode it works perfect. but when you need to use author mode in the new teams app, it getting service error.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168128049/3fdb0e00-afd1-4b5e-bdf1-deff96d7ca5b)

**Comment by gsv022** [comment]
Hi @mtlozl ,
Thanks for raising the query. Please follow the below procedure for desktop client.
If Teams is still running, right-click the Teams icon in the taskbar, and then select Quit.

- Open the Run dialog box by pressing the Windows logo key + R

- In the Run dialog box, copy/paste:

- new Teams app: C:\Users%username%\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe
   classic Teams app: %appdata%\Microsoft\Teams

- Delete the **LocalCache** folder only!

- Restart Teams.

**Comment by mtlozl** [comment]
Hi Venkat,

I applied your procedure but not resolved. 

**Teams Classic App**: Author Mode, it works perfect.

**New Teams App**: Author Mode does not work, and it gets this error: "Sorry, an error occurred while trying to access this service."
**Teams Mobile App**:  Author Mode does not work and it gets this error: "Sorry, an error occurred while trying to access this service."


Regards

Mutlu

**Comment by mtlozl** [comment]
Hello Venkat,

Thanks for help, i have to resolve my problem with below steps;
- Step-1: Apply to "Disconnect" button in the Deployment Center ( for all functions and for app service )
- Step-2: Wait for delete process, approx. 1 hour
- Step-3: Change App Service Plan from S1 to S2 ( for memory problem, when you deploy app service )
- Step-3: Add "External Git" repo in the Deployment Center, with BRANCH: "main" ( "main" name is the goal for the problem )
- Step-4: Wait and Watch the Deployment Logs from Deployment Center > Logs
- Step-5: When complete the Deployment ( you will see the result for deployment logs ) and then restart all functions and app service
- Step-6: Logout, New Teams App and login again. Success..

**Comment by mtlozl** [comment]
You will close this case.
