### ISSUE TITLE
Can we delete cards/messages which are already sent to users? 

### ISSUE THREAD

**Issue by Sheshank-TCS** [OfficeDev/microsoft-teams-apps-company-communicator#1425]
If a card or message was sent out to all users, but there's an error in its preparation or text. Is it possible to remove it from the backend for all users from Azure?

**Comment by Sheshank-TCS** [comment]
I attempted using ~~<text>~~ for the strike-through feature. While it appeared to work in the draft, it didn't reflect when sent to end users.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/33bc803a-2c39-4dd2-86eb-549f31c8a024)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/71570629/2dd97f50-a381-4ee2-8961-020c5cd993c9)

**Comment by v-jaygupta** [comment]
Hello @Sheshank-TCS ,

Thanks for reaching out to us!
We will check on this and get back to you with a proper response soon.

**Comment by Sheshank-TCS** [comment]
Thanks for confirming, I was looking for an option in Azure to delete the sent messages for all users if that is possible.

**Comment by gsv022** [comment]
This deletion option purpose is to free up the memory, which is piling up in the storage account. This deletion happens only for sent messages from author side. There will no control on users who received the messages.
