### ISSUE TITLE
Company Communicator unable to deploy using azure cli v2.30.0 and v2.60.0

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1426]
Hi Team,

I am having an issue in installing the Company Communicator v5.2 with the latest edition of Azure CLI v2.60.0 hence I uninstalled it with the specific version 2.30 as suggested in https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1179#issuecomment-1770459448

However, the issue still persisting as shown in the screenshot below:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/df841713-c395-473e-9c5e-4c03265fffc5)

Any help would be greatly appreciated.

Thank you.

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Thanks for raising the query. There is an issue with PowerShell deployment. To unblock yourself, please proceed with manual deployment if any issue occurs it would be the best approach to troubleshoot it.

**Comment by albert-widjaja** [comment]
Sure, @gsv022 thank you so much for the confirmation, yes itis working again now.

**Comment by gsv022** [comment]
Closing out the issue as the query has been responded
