### ISSUE TITLE
KeyVault deployment issue due to the BaseResourceName value is longer than 24 characters.

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1428]
Hi Team,

Can you please advise, which line in the Deploy.PS1 file I must edit to hardcode the KeyVaultname to mitigate the 24 characters limitations?

I have already edited the $keyVaultName variable in the 3x lines to be:

`$keyVaultName = 'cc-keyvault'
`
However, when I retry to execute the .\deploy.ps1 file, I always stuck in the below error:

```
ERROR: {
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "target": "/subscriptions/GUID/resourceGroups/CompanyCommunicator-RG/providers/Microsoft.Resources/deployments/azuredeploy",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "VaultNameNotValid",
                "message": "The vault name 'mycompanynamecommunicatorvault' is invalid. A vault's name must be between 3-24 alphanumeric characters. The name must begin with a letter, end with a letter or digit, and not contain consecutive hyphens. Follow this link for more information: https://go.microsoft.com/fwlink/?linkid=2147742"
            }
        ]
    }
}
```

Your help is greatly appreciated.

Thank you.

**Comment by gsv022** [comment]
Hi @albert-widjaja,
Thanks for raising the query. 
Could you please confirm us on the base resource name length. If it is less than 24 characters, then here is a possible resolution. 
While doing the "Deploy to Azure subscription" step i.e., 4th step mentioned in GitHub deployment guide, please do the following -
•	Click on Edit Template 
•	Go to line No: 305 having KeyvaultName as a parameter and replace the highlighted line with the below (refer to the screenshot) 
"keyvaultName" : "[variables('botAppName')]"
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/acb4f576-30df-499c-a49a-40ee9dc70b75)

 
•	Validate the template
•	Click on “Review & Create”

Once the deployment is successful, then you can proceed with remaining steps as mentioned in the migration guide.
Please let us know if it helped in the solving the issue.

**Comment by albert-widjaja** [comment]
@gsv022 ,
yes, that works and solves the issue. thank you for the reply.

**Comment by gsv022** [comment]
Closing out the issue as the query has been responded
