### ISSUE TITLE
Failed to create or update User app in Azure Active Directory. Exiting...

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1429]
Hi Team,

May I know where can I find the detailed error logs when the .\Deploy.ps1 file is throwing the error:

`Failed to create or update User app in Azure Active Directory. Exiting...
`
This is after deleting all resource group content and also all three Application Registrations in my Entra ID.

Thank you.

**Comment by gsv022** [comment]
@albert-widjaja , Thanks for raising the query. There is an issue with PowerShell deployment. To unblock yourself, please proceed with manual deployment if any issue occurs it would be the best approach to troubleshoot it.

**Comment by albert-widjaja** [comment]
OK, @gsv022 , this case can be closed as it is working now.
