### ISSUE TITLE
azuredeploy error in communicator-data-function/web and communicator-function/web

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1431]
I am receiving this error when deploying the Company Communicator using the .\Deploy.PS1 after downgrading the Azure CLI to v2.30.0

How to fix the issue below?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/fd149a01-50e7-44a7-939c-a18428e4792b)

Shall I click on the Redeploy button ?

Thank you.

`Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway. at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Utilities\WebRequestHelper.cs:line 81 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 756 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\SiteRepositoryProvider.cs:line 349 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Providers\ExternalSiteRepositoryProvider.cs:line 78 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass372_1.<<UpdateSiteSourceControl>b__1>d.MoveNext() in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Controllers\WebCloudController.cs:line 11163 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func) at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl) in C:\__w\1\s\src\Hosting\AdministrationService\Microsoft.Web.Hosting.Administration\Controllers\WebCloudController.cs:line 11158.`

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Thanks for raising the query. 
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by albert-widjaja** [comment]
@gsv022 ,
Spot on, yes, that resolve the issue now, thank you so much for the assistance in this matter.

**Comment by gsv022** [comment]
Closing the issue as the query as has been responded.  Please feel free to log the issue if any encountered.
