### ISSUE TITLE
App Service plan downgrade from S2 when not in use?

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1435]
Hi team,

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview#app-service

To reduce the cost when not in use during the after-hours and over the weekend, would it be possible to scale down the App Service Plan from the (Legacy) Standard S2 into the Free F1 tier or keep it under the Standard S1 instead?

Using: https://learn.microsoft.com/en-us/powershell/module/az.websites/set-azappserviceplan?view=azps-11.5.0

Scale Up: 
`Set-AzAppServicePlan -Name $appServicePlanName -ResourceGroupName $resourceGroupName -Tier "StandardS1"  -NumberofWorkers 1 -WorkerSize "Medium"`

Scale Down:
`Set-AzAppServicePlan -Name $appServicePlanName -ResourceGroupName $resourceGroupName -Tier "FreeF1"  -NumberofWorkers 1 -WorkerSize "Small"`

If not what are the alternatives to minimize the running cost when not in use?

Thank you in advance.

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Thanks for raising the query. App Services status do not have an impact on chargeability, i.e. If an app is stopped, it will still be charged (if the plan is chargeable) So downgrading the app service plan when not in use is a good away to incur less charges. You can downgrade the service plan to S1 in the weekends.

**Comment by albert-widjaja** [comment]
Thank you @gsv022 ,
May I know if the above command will work or not?

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Whenever not in use, go to CC resource group--> Open app service plan resource-->Under settings, choose Scaleup(App service plan)-->Downgrade to S1 and save it.


We are not sure of the commands that you have provided.

**Comment by albert-widjaja** [comment]
OK, thanks @gsv022
