### ISSUE TITLE
Error on Company Communicator Author App

### ISSUE THREAD

**Issue by teiselt96** [OfficeDev/microsoft-teams-apps-company-communicator#1436]
Recently noticed an error when trying to access the Commpany Communicator Authors app that says; "Sorry, an error occured white trying to access this service". We are on the new Teams as well. I also tried to Sync from the GitHub and it is still not working after restarting the app. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/34378652/6b2ae70d-84e1-45c2-833a-bb1e08144f45)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/34378652/6a0a8e52-923b-440e-b854-ef8708cc8b34)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/34378652/70d3b9e9-18c9-4e24-8c51-b6db708e49d2)

**Comment by gsv022** [comment]
Hi @teiselt96 ,
Thanks for raising the query. Please try opening in browser and access the application. Keep us informed.

**Comment by gsv022** [comment]
@teiselt96 ,
Please follow the below procedure for desktop client.

- If Teams is still running, right-click the Teams icon in the taskbar, and then select Quit.

- Open the Run dialog box by pressing the Windows logo key + R

- In the Run dialog box, copy/paste:
new Teams app: C:\Users%username%\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe
classic Teams app: %appdata%\Microsoft\Teams

- Delete the LocalCache folder only!

- Restart Teams.
