### ISSUE TITLE
Can't find any teams when trying to post a new message

### ISSUE THREAD

**Issue by thowardtw** [OfficeDev/microsoft-teams-apps-company-communicator#1437]
So I've gone through the deployment, added both apps to our team channel as you can see below:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/d8776dd3-b1af-4efc-949e-712e57e53057)

When trying to compose a new message I can post to any teams:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/794c9169-a0f4-48bf-97fb-966ef78f489e)

I also can't post to any groups even though the permissions are correct:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/86790c8e-ffea-402c-9f39-ba705b5cc000)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/0332dea3-859c-4c66-ad3e-9640d3a73700)

**Comment by gsv022** [comment]
Hi @thowardtw,
Thanks for raising the query.

- Cross verify the supported account type is set to **My organization** for graph app registration and Multiple Organization for author, user app registrations.
- There might be a chance that secrets might have incorrectly configured. Please cross-verify them

**Comment by thowardtw** [comment]
Hi @gsv022 

Thanks, I've double checked and the account type is set correctly:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/612dd0f3-494b-46f4-9942-bee5994c81d8)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/e677ca75-9024-42f0-bb98-ddb07ad69ead)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/999c8647-a531-4f4e-a4a8-68dc9fabade2)

When you say incorrectly configured, what's the best way to check they're setup correctly?

Worth noting during the deployment the sourcecontrol function/web failed due to reaching terminal provisioning state failed. I ran a sync as described in the troubleshooting doc. Not sure if this is related at all.

**Comment by thowardtw** [comment]
@gsv022 I've just compared the secret values and they match exactly. Is there anything else I can check?
