### ISSUE TITLE
Unable to send message from Teams to Company Communicator?

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1439]
Hi Team,

I have successfully deployed the company communicator using the .\Deploy.PS1 method.

however, despite logging in with the author login, I cannot send anything on the Teams window as below and the Icon is still broken.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/e0bf18d3-8b4d-4585-9749-d30da84f5864)

This is the App registrations page where the icon and the user assignment (Owners) are assigned:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/7a44681b-4775-4c08-a702-79f73e885b09)

Any help would be greatly appreciated.

Thank you.

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Thanks for raising the query. We mentioned to proceed with manual deployment approach as there is a issue with Azure CLI issue in the current code. 

What is the error that is getting displayed in the author app? Please share supporting screenshot.

**Comment by albert-widjaja** [comment]
@gsv022 ,
The first screenshot shows the issue. Can you provide additional error messages? The application is still not working and Azure charge is increasing.

**Comment by gsv022** [comment]
Since there is a issue with PowerShell deployment, we strongly recommend you to go with manual deployment
