### ISSUE TITLE
How to allow users to start using the Company Communicator bot and all of its features?

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1440]
Hi Team,

Can specific groups of users be defined as authors to make them Power Users or Admins of the Company Communicator?

While the rest of my users in the company should be able to access the Company Communicator App after allowing the Enterprise Application like below?

**Enterprise Application | Properties**
Enabled for users to sign-in? YES
Assignment required? NO
Visible to users? YES

**Enterprise Application | Users and groups**
User1
User2
...
UserX

Can you confirm if this is the correct method to use Company Communicator?

Thank you.

**Comment by albert-widjaja** [comment]
@gsv022 ,
Where can I see or get into that page to enter the UPN for the users that will be the author of this application ?

**Comment by gsv022** [comment]
@albert-widjaja ,
Here is the place where UPN can be updated. 

- Go to resource group-->Click on app service/web app-->Goto configuration section(old)/environment variables(new)-->add/remove 'n' number of UPN within AuthorizedCreatorUPN's.

<img width="857" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/ddfe09a1-7212-48df-99dd-397449e176b0">

- Separate each UPN with semicolon(;)

**Comment by albert-widjaja** [comment]
@gsv022 ,
Thank you, can I use the security group as the input rather than the user name in the above screenshot?

**Comment by gsv022** [comment]
Security group won't work here
