### ISSUE TITLE
How to determine which Company Communicator App registrations is the defacto or in use ?

### ISSUE THREAD

**Issue by albert-widjaja** [OfficeDev/microsoft-teams-apps-company-communicator#1441]
Hi Team,

From this Azure page https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/RegisteredApps
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/1a1ac59c-5afb-4495-8631-4a15a21ee379)

How can I determine which registrations for the Company Communicator App registrations are active or in use, so I can delete any duplicates or inactives?

Thank you.

**Comment by gsv022** [comment]
Hi @albert-widjaja ,
Thanks for raising the query. The app registrations once used in the deployment, there is a chance that which app registration has been used for deployment so for this 
Go to Resource Group-->In the LHS, click deployments under settings-->Choose latest Microsoft.Template-->In the LHS, go to input section-->Grab the application id of any app and paste in the app registration.

In this we can get confirmation. Hope the query is answered.

**Comment by albert-widjaja** [comment]
Is it under this one, @gsv022 ?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/c3f76e20-6d21-4b4d-adb8-aa8915834afa)

**Comment by gsv022** [comment]
Since you went with PowerShell deployment, please open Azure Deploy

**Comment by albert-widjaja** [comment]
@gsv022 ,
This is the error details from the azuredeploy raw error:

```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "message": "There was a conflict. Conflict with existing ScmType: ExternalGit"
    }
  ]
}
```

**Comment by gsv022** [comment]
@albert-widjaja ,
Thanks for raising the query. 
- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select **prep-function**(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference. 

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again



--------------------------------------------------------------
_Bot is not valid. Errors: The Microsoft App ID is already registered to another bot application_

To overcome this issue, please create new app registrations and fill the template again

**Comment by albert-widjaja** [comment]
@gsv022 ,
yes it is already showing the same, from the Web App
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/67a99e36-0ea5-47b7-93de-f909475b144e)

Function App,
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/d32bbc47-13b8-47e4-9ad0-0d84c2627e14)

**Comment by gsv022** [comment]
If it is already connected and showing the data as expected then it is fine. Please let us know if you have any queries
