### ISSUE TITLE
Users are missing in the Microsoft Teams Company Communicator app's send delivery report.

### ISSUE THREAD

**Issue by lumsk20** [OfficeDev/microsoft-teams-apps-company-communicator#1442]
We are reaching out to address a concern which we have observed with our CC delivery report. Each new dispatch has shown a shortfall in the number of recipients, that is the reason why we seek your assistance.
 
For example: Upon reviewing our send delivery report, we observed that the distribution list was supposed to include 10K recipients. 
 
However, it shows that only 9K deliveries were successful. There were also few instances of undeliverable messages. Notably, there appears to be a shortfall, as around 900 users did not receive the message, and these individuals are not listed in the send delivery report. 
We also checked in TAC center the company communicator App Permission and App SetUp policies are already assigned to the 900 users for whom the message did not get delivered.

Can you please check and assist on this case ?

**Comment by gsv022** [comment]
Hi @lumsk20,
Thanks for raising the query. Could you please share your mail id so that we can discuss the issue internally

**Comment by SachinWandale111** [comment]
Hi @gsv022 ,
I am following up this case on behalf of my collogue, Can you kindly refer below similar case which we have raised earlier for reference for similar issue and provide us further assistance?

We have confirmed as mentioned in case description, We also checked in TAC center the company communicator App Permission and App Setup policies are already assigned to the 900 users for whom the message did not get delivered.

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1148

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Could kindly assist on above query quickly as soon as possible please? We are awaiting your response.

**Comment by lumsk** [comment]
Hi @gsv022,
Can you please take this case on priority and provide your inputs ?

**Comment by SachinWandale111** [comment]
Hi @gsv022 
Can you please take this case on priority and provide your inputs ?

**Comment by SachinWandale111** [comment]
Hi @gsv022 
Can you please take this case on priority and provide your inputs ? As we are awaiting your feedback on this case. Thanks

**Comment by SachinWandale111** [comment]
Hi @gsv022 Can you please take this case on priority and provide your inputs ? As we are awaiting your feedback on this case. As we are sending you multiples reminders but still we are awaiting your response. Thanks

**Comment by gsv022** [comment]
Hi @SachinWandale111 ,
Please share your id so that we can discuss the issue internally

**Comment by lumsk** [comment]
hi @gsv022,
Which id do you want us to share with you ?

**Comment by SachinWandale111** [comment]
Please update on above query.

**Comment by karloscri** [comment]
We have the same issue. Do you know what is the solution? 
this is the error message:
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)   at Microsoft.Bot.Builder.CloudAdapterBase.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()--- End of stack trace from previous location ---   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94--- End of stack trace from previous location ---   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)   at Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext() in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line 94

**Comment by SachinWandale111** [comment]
Hi @gsv022,
Could you kindly confirm, Which id do you want us to share with you?

**Comment by lumsk** [comment]
Hi team,
Please do not close this request without our approval. Kindly check the above comments and respond.

**Comment by SeanMLG** [comment]
Hi, as there bee a solution to this?
