### ISSUE TITLE
Already renewed secrets,  but still get "Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request" error

### ISSUE THREAD

**Issue by mricanohearst** [OfficeDev/microsoft-teams-apps-company-communicator#1443]
Unable to send messages in company communicator, get the following error. 
Have already performed the following actions:
Restarted Application Services
Restarted Function applications
Upgraded Application version
generated new secrets since current had expired, as found in a previous github article.

**Comment by gsv022** [comment]
Hi @mricanohearst ,
Thanks for raising the query. Could you please share the screenshot of status of sent message

**Comment by mricanohearst** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/169369687/281f35f2-8495-4a4f-ac8a-33831ce4d679)

**Comment by gsv022** [comment]
Hi @mricanohearst ,
Could you please confirm whether AzureAd:ClientSecret is updated with new Graph App secret, if not please update and try accessing the application over web client.

**Comment by gsv022** [comment]
@mricanohearst , 

- Which app registrations had the secrets expired.
- What are the places where new secret has been updated?
