### ISSUE TITLE
Receiving error While Deploying

### ISSUE THREAD

**Issue by kundan76** [OfficeDev/microsoft-teams-apps-company-communicator#1444]
I am following the installtion and getting the eeror while deployment of App

Azure AD App: APP-Team-Communicator-APP-users registered successfully.
Failed to create or update User app in Azure Active Directory. Exiting...

**Comment by gsv022** [comment]
Hi @kundan76 ,
Thanks for raising the query. There is an issue with PowerShell deployment, to unblock yourself please follow the manual deployment guide.
