### ISSUE TITLE
'UpdateSiteSourceControl' operation failed with System.Net.WebException:  (502) Bad Gateway.   

### ISSUE THREAD

**Issue by ErinComms** [OfficeDev/microsoft-teams-apps-company-communicator#1446]
Hi all,

I have a single point of failure with the above -error
<img width="531" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/169253818/35ab3821-cae6-46bc-9a54-043aecbf9a2b">
.

I followed the steps mentioned at -  https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1431

to troubleshoot but the mentioned value are as prescribed
<img width="406" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/169253818/09993178-c1fd-4f44-9ebe-0637cec9af27">
<img width="542" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/169253818/eaeea990-3128-4b86-85a5-4836e27afe6b">

Due to the failed deployment I don't have any outputs to continue the deployment with.

Please advise

**Comment by gsv022** [comment]
Hi @ErinComms ,
Thanks for raising the query. Deployment got failed due to one/few of the failed resources. Upon visiting resources individually, if the status shows **Success(Active)** then please proceed with the next steps of deployment. Don't for re-deployment again. Leave the deployment failure as it is .

As you mentioned there are no outputs. Below can be considered as the outputs that can be used in further steps.

authorBotId- Author Application(Client) ID

userBotId- User Application(Client) ID

App Domain- **Base resource name**.azurefd.net

**Comment by ErinComms** [comment]
Hi there, I have continued with the steps as advised thank you. I now have a new problem with the Authors App tab - the save button isn't available
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/169253818/2fbc8bd9-d7d8-4e47-b4fd-f2ef997afc59)

**Comment by gsv022** [comment]
Please share the zipped manifest files of author and user

**Comment by ErinComms** [comment]
[company-communicator-users.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/15304705/company-communicator-users.zip)
[company-communicator-authors.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/15304708/company-communicator-authors.zip)

**Comment by ErinComms** [comment]
Good morning, not sure if I was meant to respond here on on GH directly.

Please see attached
________________________________

**Comment by gsv022** [comment]
Hi @ErinComms ,
In the author manifest, there is extra front slash added. This is the reason it is causing the issue. Please remove it and zip it again then reupload it will work. Here is the reference.
