### ISSUE TITLE
Cannot send message

### ISSUE THREAD

**Issue by mavistangtpl** [OfficeDev/microsoft-teams-apps-company-communicator#1447]
I have check deployment center, restart 3 functions and app service.

![Screenshot 2024-05-14 172344](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/a8367ab0-a94f-41c8-b76e-4ea3a58a131f)

![Screenshot 2024-05-14 172454](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/9f6bb40b-22ea-4fbe-bf1e-966e5683d2e9)

Function sync failed :
![Screenshot 2024-05-14 181328](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/c667a2a2-a56e-49e3-a515-720affe80e23)

How to resolve the issue of being stuck in the "Sending" stage when sending a message?

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Thanks for raising the query. 
- Please check the [set-up authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) part whether it has been configured correctly or not.
- In the overview section of Graph app, Supported account type for graph app should be **My Organization**
-------------------------------------------------------------------------
 There might be chance of secrets incorrectly configured. Please cross-verify.

-  Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by mavistangtpl** [comment]
Thanks @gsv022 

I've already compared each secret according to your steps, but the situation remains the same. The sync of the "Function App" still fails.

**Comment by gsv022** [comment]
@mavistangtpl , Please disconnect and give some time then connect function app in the deployment center. This would make function app successful.

**Comment by mavistangtpl** [comment]
@gsv022, Sorry for the confusion. I'd like to clarify which function app is being disconnected: data-function, prep-function, or function? Also, approximately how long does it take to reconnect?

**Comment by gsv022** [comment]
@mavistangtpl , As quoted by you- _The sync of the "Function App" still fails._ 
Perform disconnect, give some 10 minutes of time. Then connect it to the official repository. This would take around 10-15minutes.

**Comment by mavistangtpl** [comment]
> @mavistangtpl , As quoted by you- _The sync of the "Function App" still fails._ Perform disconnect, give some 10 minutes of time. Then connect it to the official repository. This would take around 10-15minutes.

@gsv022 , I've already tried your method, but the result is still a failure.

![Screenshot 2024-05-16 173118](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/fe3870d8-1a71-4373-a335-7fdd8fd400f1)

![Screenshot 2024-05-16 173513](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/41e685aa-6821-4121-9509-c4c7a0c5dd0d)

![Screenshot 2024-05-16 173530](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/28726b20-01d1-431e-b015-6b124bf52531)

**Comment by gsv022** [comment]
@mavistangtpl ,Please share your id so that we can discuss the issue internally
