### ISSUE TITLE
After change Secret ID 

### ISSUE THREAD

**Issue by ricbm11** [OfficeDev/microsoft-teams-apps-company-communicator#1448]
Hello, after changing the secret ID in the app, messages are not sent and I receive this error.

Falha ao preparar a mensagem para envio: The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.". See the function execution logs for additional details.
Avisos
Falha ao obter Membros para 45fbf9c2-1c34-4646-a5d7-5710a0f70e62 de Grupo: Code: generalException Message: An error occurred sending the request. Falha ao obter Membros para 45fbf9c2-1c34-4646-a5d7-5710a0f70e62 de Grupo: Code: generalException Message: An error occurred sending the request. Falha ao obter Membros para 45fbf9c2-1c34-4646-a5d7-5710a0f70e62 de Grupo: Code: generalException Message: An error occurred sending the request.

**Comment by gsv022** [comment]
Hi @ricbm11 ,
Thanks for raising the query. As you mentioned secret ID, we should grab secret Value not Secret ID. Please make a note of it.
<img width="650" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/0ec3d9a6-d034-4265-bbd5-e4d0f5dd9ee9">

**Comment by ricbm11** [comment]
I expressed myself wrong, yes it was the value ID that I used. I checked again and it has the correct values, as shown in the figure, the check box is green, 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/104456849/1f1ad184-5c5f-4cf0-bdc3-b59b95883406)

**Comment by ricbm11** [comment]
Hi, thank you for your support. I've made all the changes, and everything works well.

**Comment by gsv022** [comment]
Great thank you for the update.
