### ISSUE TITLE
In which tenant should I register the Azure AD apps?

### ISSUE THREAD

**Issue by neidantaslopez** [OfficeDev/microsoft-teams-apps-company-communicator#1449]
In my case, the solution deployment will be carried out in a subscription belonging to a **tenant A** and the authors app and user app will be installed in Teams whose directory is located in a **tenant B**.

That being said, even after reading the documentation, I'm confused about:

1. In which Azure AD tenant should I register the "User," "Authors," and "App" apps? In **tenant A** or **tenant B**?
2. In my case, subscriptionId and subscriptionTenantId should be filled with the subscription ID and tenant ID of **tenant A**, while tenantId should be filled with the tenant ID of **tenant B**?
3. userObjectId should be filled with the Object Id of the appropriate user (with appropriated permission) from the **tenant A** or **tenant B**?

Notes:

1. What should "**associated with**" mean in this case? In the documentation, we have the following:
    > subscriptionId - Azure subscription to deploy the solution to (MUST be **associated with** the Azure AD of the Office 365 tenant that you wish to deploy this solution to.) e.g. 22f602c4-1b8f-46df-8b73-45d7bdfbf58e.

3. It seems that admin consent permissions are required for app registrations. In this case, should I grant admin permissions to the apps in **tenant A** or **tenant B**? I do not have permissions to grant admin permissions in **tenant A**.

**Comment by gsv022** [comment]
Hi @neidantaslopez ,
Thanks for raising the query. 

- _In which Azure AD tenant should I register the "User," "Authors," and "App" apps? In tenant A or tenant B?_
You mentioned in the first line that author, user app are installed in **tenant B** then app registrations must be done in **tenant B** only. 

- _In my case, subscriptionId and subscriptionTenantId should be filled with the subscription ID and tenant ID of tenant A, while tenantId should be filled with the tenant ID of tenant B?_
SubcriptionId- This id needs to be grabbed from tenant where deployment is done. In your case it is **tenant A**
subscriptionTenantId- This id need to be grabbed from **tenant A** only.

- _userObjectId should be filled with the Object Id of the appropriate user (with appropriated permission) from the tenant A or tenant B?_
As you are going with PowerShell deployment- there is a issue with the current script, you may encounter issues. We recommend you to proceed with manual deployment.  Coming to your query, userObjectId- this should be you, your userobjectid need to be filled, which can be found from AzureAD.
