### ISSUE TITLE
Sign-in Issue

### ISSUE THREAD

**Issue by kgazar** [OfficeDev/microsoft-teams-apps-company-communicator#145]
After uploading Author Package to MS teams, i added the authors app to team(Author defined as admin in that team). The issue when author navigate to company communicator Tab, it keep showing message say "Please sign in to continue". when click on sign-in it gives me windows attached and even when i sign in with admin, it still same.
![Capture1](https://user-images.githubusercontent.com/38635592/76391567-ce84e100-6380-11ea-8775-f7ce02196b34.JPG)
![Capture2](https://user-images.githubusercontent.com/38635592/76391571-cfb60e00-6380-11ea-8853-a98041b1dc63.jpg)

Any thoughts

**Comment by rashmi-dixit** [comment]
Please check below options and try.

• Check if the app registration, Company Communicator deployment and instance of Teams are in the same tenant. If they are different, then at the time of providing parameters, in the custom template while deploying, the tenant id of teams instance needs to be provided.

![image](https://user-images.githubusercontent.com/57787129/79153458-81ff4c00-7deb-11ea-9a1d-75d64afe1314.png)


To get the teams instance tenant id –
Go to any team -> click on three dots besides the team name -> click on ‘get link to team’ -> Copy the link -> Extract the ‘tenantId’ field from the copied link.

To change tenant id after deployment -
Go to ‘Configuration’ settings of App Service -> change the "AllowedTenants" & "Tenant id" field value to the one you copied and Save -> Restart the App service -> refresh the tab under Teams.

• In the app registrations check if the supported account types is multiple organizations.

**Comment by kahopkin** [comment]
I checked all the settings, everything is correct yet the problem persists with the sign in loop

**Comment by makandmozart** [comment]
I have the same problem

My tenant configuration is fine

**Comment by dtyler3349** [comment]
I am also facing the same issue.  I am stuck in the loop.  I have checked all the settings and everything is correct.  Please advise.

**Comment by cbielefeld19** [comment]
Same issue and I've created two different packages and same issue with both

**Comment by dtyler3349** [comment]
I opened a ticket with Microsoft and I ended up having to delete the package all together from Azure and re-install.  That fixed it.  The engineer did say that if you upgraded from a previous version of Company Communicator, that they have seen where sometimes the upgrade process does not go well and they suggest people just delete the app and start fresh.

**Comment by cbielefeld19** [comment]
That is what I did was deleted the first package and created another one and got the same issue

**Comment by fabiofrota** [comment]
I'm having the same issue. Double checked tenantID and it's correct.
What should I do?

**Comment by DikshantMalik** [comment]
same issue.. any luck??

**Comment by hunaidhanfee20** [comment]
Hello @kgazar, @fabiofrota, @DikshantMalik,
Can you please check Expose an API Uri in Author's app registration and confirmed same is given in app service configuration

You can also have a look at these issues : #397, #188, #219.
Let us know if it still persists.
Thanks

**Comment by merwindz** [comment]
Hello, I have same issue with sign-in and its goes in circles. Checked the sign-in logs and its success and no errors. Anyone got any advise how to resolve this issue? thanks Merwin

**Comment by merwindz** [comment]
I have fixed issue after updating the API URI

Back under Manage, click on Expose an API.

Click on the Set link next to Application ID URI, and change the value to api://%appDomain% e.g. api://appName.azurefd.net.

**Comment by botval22** [comment]
@merwindz : Your solution worked in my case. Great!!!! Thanks

**Comment by botval22** [comment]
> Click on the Set link next to Application ID URI, and change the value to api://%appDomain% e.g. api://appName.azurefd.net.

Click on the Set link next to Application ID URI, and change the value to api://%appDomain% e.g. api://appName.azurefd.net.
