### ISSUE TITLE
Company communicator author tab not working in Teams Desktop

### ISSUE THREAD

**Issue by Naveenkumar023** [OfficeDev/microsoft-teams-apps-company-communicator#1451]
Company communicator author tab not working in Teams Desktop. But we could be able to access on web teams.
<img width="715" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/101704715/cf53fde9-e114-41dc-bc33-6dda44b7b835">

**Comment by gsv022** [comment]
Hi @Naveenkumar023 ,
Thanks for raising the query.

- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/26955650-5cbc-4ff8-9004-d187fb918ed7)

<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">

**Comment by gsilvaads** [comment]
Hello @gsv022! 

I have a similar problem. When adding Teams Communicator to the Channel tab, it shows the home screen, but when clicking on Send New Message, it shows an error without reference. Would you help me?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/1dd257c6-b82f-416a-b603-db9614d314ba)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/23f0f396-1877-47b6-9932-9ab08a19e8a9)

I checked the Deployment Center, and the logs are in active status:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/0e5cb1c0-d1db-4557-8850-0c201ed1f25a)
