### ISSUE TITLE
Cancel sent message doesn't work

### ISSUE THREAD

**Issue by lbgrasso** [OfficeDev/microsoft-teams-apps-company-communicator#1453]
HI everyone!
The "cancel" action on sent messages is not working. When I click on cancel, the message is delivered anyway.
Could you please help me to make it work?
Thanks!

**Comment by gsv022** [comment]
Hi @lbgrasso ,
Thanks for raising the query. We will check it out rom our end and get back to you.

**Comment by lbgrasso** [comment]
Hi! Any news about this?

**Comment by gsv022** [comment]
Hi @lbgrasso ,
It is working as expected. The phases of cancellation will be like below. 
<img width="685" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/22306e95-7797-4bff-a56a-a580f448d8bf">

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/8110f9ca-cc4e-4e09-9302-ef79eef97bab)

- Could you please grab the screenshots like once you click on cancel button how the message getting effected.

**Comment by lbgrasso** [comment]
When I click on cancel, nothing happens, the message is delivered anyway: <img width="675" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/89993166/f1140f0f-9950-41d8-aa42-4f36d9e602f1">

**Comment by gsv022** [comment]
Could you please share all the screenshots of right from the click of cancel button.

**Comment by lbgrasso** [comment]
<img width="681" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/89993166/5db1d57d-9b46-4600-b5ac-a573d2a1079e">

**Comment by gsv022** [comment]
Hi @lbgrasso ,
- Please check the [set-up authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) part whether it has been configured correctly or not.
- In the overview section of Graph app, Supported account type for graph app should be **My Organization**
-------------------------------------------------------------------------
 There might be chance of secrets incorrectly configured. Please cross-verify.

-  Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by lbgrasso** [comment]
Everything you mentioned is correct! I already checked that for another issue I had and that wasn't the problem.

**Comment by lbgrasso** [comment]
lbgrasso@tenaris.com

**Comment by gsv022** [comment]
@lbgrasso , We have initiated the conversation internally

**Comment by v-jaygupta** [comment]
Hi @lbgrasso, 

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.
You may also always open a new issue or respond here if something does come back up.

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed as we didnt received any response from user
