### ISSUE TITLE
Sync Failed on the Communicator Web App

### ISSUE THREAD

**Issue by AliRaeis** [OfficeDev/microsoft-teams-apps-company-communicator#1454]
Hi

We are trying to complete the migration to allow support for the Teams v2 client.  Our deployment is working with the classic client however as we know this is retiring, we want to ensure we can still use the CC.

The sync appears to be failing with the logs below, can anybody provide any guidance on how to resolve this?
![Failed](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/170537870/68ca5ac1-fd7c-46ed-9723-9e8d4bcee845)

Log Details
Commit ID: 876fbbab9e27387f612e84ffed9be9a8c55cc054

2:19:46 PM
Updating branch '876fbbab9e27387f612e84ffed9be9a8c55cc054'.
2:19:47 PM
Updating submodules.
2:19:47 PM
Preparing deployment for commit id '876fbbab9e'.
2:19:48 PM
Running custom deployment command...
2:19:48 PM

Running deployment command...
Show Logs...
2:33:25 PM
Deployment Failed.
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 

up to date in 2m

248 packages are looking for funding
  run `npm fund` for details
Building the client app (this can take several minutes)

> company-communicator@5.5.2 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Failed to compile.

static/css/main.e69aa8e4.css from Css Minimizer plugin
Error: Cannot find module 'csso/lib/restructure/prepare/specificity'
Require stack:
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\lib\css-tools.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\lib\svgo\css-style-declaration.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\lib\svgo\jsAPI.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\plugins\mergeStyles.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\plugins\preset-default.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\plugins\plugins.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\lib\svgo\config.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\lib\svgo.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\node_modules\svgo\lib\svgo-node.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\postcss-svgo\src\index.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\cssnano-preset-default\src\index.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\cssnano\src\index.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\css-minimizer-webpack-plugin\dist\minify.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\jest-worker\build\workers\threadChild.js

Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock.json file was created with an old version of npm,\r\nnpm WARN old lockfile so supplemental metadata must be fetched from the registry.\r\nnpm WARN old lockfile \r\nnpm WARN old lockfile This is a one-time fix-up, please be patient.

**Comment by gsv022** [comment]
HI @AliRaeis ,
Thanks for raising the query. Please disconnect and give 30 minutes of time  then try connecting to the official repository again. It will work

**Comment by AliRaeis** [comment]
Thanks for the feedback.  I have tried that however this has not been successful. The logs appear to be the same.

**Comment by gsv022** [comment]
Hi @AliRaeis ,
What is the app service plan? And please give it one more try. Disconnect it and leave it for half of the day then connect to the repository.

**Comment by AliRaeis** [comment]
I have since deleted and redeployed a fresh copy.  Thanks
