### ISSUE TITLE
Secondary Bot Within Same Organisation

### ISSUE THREAD

**Issue by ColinDPo** [OfficeDev/microsoft-teams-apps-company-communicator#1455]
I am trying to ascertain how I can create a secondary instance of the communicator app within the same installation which can be branded and used for a secondary business function, is this possible?

**Comment by gsv022** [comment]
Hi @ColinDPo , 
Thanks for raising the query. Multiple instances can be deployed on to the same tenant. Two checks before going for multiple deployments

- For the first instance, the user app external id can be default value. But from second instance and so on, the parameter user app external id need to be updated with a valid GUID and the same GUID need to be updated in the user manifest file. Below are the two places which needs to be updated with a new valid GUID.
<img width="380" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/953b0875-81c4-4545-8076-e6c50a7d48f7">

<img width="459" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/edf67004-4e3a-495e-8891-5945186252c7">

- For the first instance, no need to worry about author app but for second instance, grab a new valid GUID and paste in the author manifest file. Below is the reference.
<img width="406" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/3aa1e9e1-0938-4a58-815a-d84332ef8695">

- Rest all remains same.

**Comment by lbgrasso** [comment]
Hi! To make multiple instances work, is it necessary to do as many deployments as instances? So there will be multiple App Services, Key Vaults, Storage accounts, etc.?

**Comment by gsv022** [comment]
Closing the issue as we have responded to the query. Please feel free to log the ticket if you have any queries w.r.t CC
