### ISSUE TITLE
Export Detailed Results for messages does not work

### ISSUE THREAD

**Issue by JasGo00** [OfficeDev/microsoft-teams-apps-company-communicator#1456]
After new message is sent when accessing "view status" option and after clicking on "export detailed results" I get the "export is queued" message but these results are never delivered. when I check the storage all the jobs that were ever triggered are in progress status and never delivered

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/171352cb-acc2-4886-98d1-b2f8ba5b4426)

**Comment by gsv022** [comment]
Hi @JasGo00 ,
Thanks for raising the query. Please respond to the below queries.

- Are you able to send the message using 4th sending option?
- Please share the deployment status of App service. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/26955650-5cbc-4ff8-9004-d187fb918ed7)

<img width="905" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/787f1615-8969-44f5-abb4-ede80b02e429">

**Comment by JasGo00** [comment]
Hello

Are you able to send the message using 4th sending option? 
    _I do not know what this is?_

here is our deployment:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/70ddd5cf-5bed-4618-9f48-858a1123e625)


![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/134404674/144bbace-ebea-4b69-bf20-c6d77bdc2e21)

**Comment by gsv022** [comment]
@JasGo00 ,
Are you able to send the message using 4th sending option-_Send to a M365 group/Distribution List/Team?_

**Comment by JasGo00** [comment]
Yes , this is not an issue with sending messages, its an issue with getting the send reports

Best regards

Jasmin Gokovic

BD/WPA-UCS1 / MS Teams/Skype
Mobile +1(248)310-2978 | ***@***.******@***.***>

**Comment by gsv022** [comment]
Hi @JasGo00 ,
The reason for asking is 4th sending option and export have a link. Could you please re-sync the functions again

**Comment by JasGo00** [comment]
Yes I was able to use the 4th option but did not see any link...

Best regards

Jasmin Gokovic

BD/WPA-UCS1 / MS Teams/Skype
Mobile +1(248)310-2978 | ***@***.******@***.***>

**Comment by JasGo00** [comment]
I also ran the sync again

**Comment by JasGo00** [comment]
I will send you my ID via Teams chat

**Comment by JasGo00** [comment]
Please do not close, I provided feedback via email

**Comment by v-jaygupta** [comment]
Issue is continued to be discussed internally, working on the query generation, will provide it shortly.

**Comment by v-jaygupta** [comment]
We have shared the query for fetching the list of affected users, please follow the other shared steps and update us on the status.

**Comment by JasGo00** [comment]
query worked, but you can only execute 300 lines at the time so to delete 16000 users took a long time

**Comment by peddivyshnavi** [comment]
Hi @JasGo00 
This is only possible way to work with query. there are no other possibilities for checking.
Could you please confirm whether issue got resolved.

**Comment by JasGo00** [comment]
yes the issue was resolved
