### ISSUE TITLE
Is the Company Communicator ready for the domain changes announced by Microsoft?

### ISSUE THREAD

**Issue by neidantaslopez** [OfficeDev/microsoft-teams-apps-company-communicator#1457]
It's about the following post:

https://devblogs.microsoft.com/microsoft365dev/action-required-ensure-your-microsoft-teams-apps-are-ready-for-upcoming-domain-changes/

The post states that the following actions must be taken:

1. Upgrade [Teams JS library](https://www.npmjs.com/package/@microsoft/teams-js) to version 2.19 or higher.
2. Update your x-frame-options/CSP headers to allow for the new domains. To ensure the app keeps working across existing and future Microsoft 365 hosts, please ensure to allow “*.cloud.microsoft”.

Where should these actions be carried out in the Company Communicator solution, or how can I check if they have already been performed in an existing deployment?

**Comment by gsv022** [comment]
Hi @neidantaslopez ,
Thanks for bringing it to our notice. We are already looking into this on priority. We will keep you posted on this.

**Comment by gsv022** [comment]
Hi @neidantaslopez ,
We tested within new domain already. Currently this domain change has no impact on CC. We will let you know in future if there is any impact or any updates required

**Comment by neidantaslopez** [comment]
Is there no impact on any version of the CC or just the current version? How can I check this in my environment?

**Comment by gsv022** [comment]
We have checked on the current version of CC.  To validate, change the URL to teams.cloud.microsoft.com and test the application
