### ISSUE TITLE
unable to use CC Bot to write messages.

### ISSUE THREAD

**Issue by jeeva2828** [OfficeDev/microsoft-teams-apps-company-communicator#1458]
I added a few more IDs to the CC BOT after it was created, however they are unable to utilize the CC Bot author program, despite our attempts to use it on both the web and desktop.

**Comment by gsv022** [comment]
Hi @jeeva2828 ,
Thanks for raising the query. Please respond to the below queries.

- Are you able to access application?
- Upon adding multiple id's  those users are not able access author bot. Please share the procedure that has been followed on adding id's.

**Comment by jeeva2828** [comment]
Hi Team,

I can able to compose message through that BOT,
I added two more ID they can't able to compose message,

Please find the below snap.

***@***.***

***@***.***



Regards,
Jeevanandam A

**Comment by gsv022** [comment]
- Where were the two id's added?
- Have you performed SYNC after adding the id's?

**Comment by jeeva2828** [comment]
Hi Team,

In web app services I added those two ID's in Authorized creator UPNS.


***@***.***


Please find the below snap, after adding those ID's I have restarted the web app here.


***@***.***

Regards,
Jeevanandam A

**Comment by gsv022** [comment]
@jeeva2828 , Please go to deployment center of app service and perform SYNC again. 

let us know how it goes

**Comment by jeeva2828** [comment]
Hi Team,

App services has been re synced.

***@***.***

Regards,
Jeevanandam A

**Comment by gsv022** [comment]
We are following the issue internally

**Comment by v-jaygupta** [comment]
Hello @jeeva2828 ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.
You may also always open a new issue or respond here if something does come back up.
