### ISSUE TITLE
New Teams 

### ISSUE THREAD

**Issue by ricbm11** [OfficeDev/microsoft-teams-apps-company-communicator#1459]
After updating my Teams client to the new version, I am unable to use the author communicator client.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/104456849/4c0d245c-0dd7-435b-a7a3-b15737772036)

**Comment by ricbm11** [comment]
Please find below:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/104456849/eb136cab-32a7-4ca3-a4cf-8cb215142617)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/104456849/dddb1433-4e1b-42a6-bdfd-afa2784b69ca)

**Comment by brent-lea** [comment]
We are also having issues with the new Teams client. Here is a screenshot of our error message.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/126486364/b4752da9-2ce5-4cc5-ad12-8d68f9bd9ecc)

If we switch back to the old "classic" Teams client. Everything works normally.

Here are screenshots of our function app settings.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/126486364/7f0b9343-28fe-4969-89ae-7da0e0a4c368)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/126486364/e991f4d8-b3fe-4183-abf8-23af4f307a78)

**Comment by gsv022** [comment]
Hi @ricbm11 ,
We recommend the below steps to overcome the issue.

- Please follow the steps mentioned in this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)

- Perform SYNC for all the resources such as- App Service(Web app), 3-Function apps.

**Comment by ricbm11** [comment]
Thank you for the information; I followed your recommendation and it was successful.

**Comment by brent-lea** [comment]
This did not resolve our issue. I am still unable to use Company Communicator in the new Teams client. It does work in the classic client. I did clear the cache for the client per the instructions.
