### ISSUE TITLE
upgrading to version 5.x how to update package

### ISSUE THREAD

**Issue by allthetrouts** [OfficeDev/microsoft-teams-apps-company-communicator#1460]
We've done aother upgrade of the CC following the instructions: Upgrading from v5.x to latest version

It does not mention anywhere to create new package, just sync and restart. However nothing has changed on the teams admin side and it still doesnt work with new Teams.. Please advise how to process this update, and probably include that in your instructions.. Do I have to create a new package?

**Comment by gsv022** [comment]
Hi @allthetrouts ,
Thanks for raising the query. if the steps mentioned in the migration guide are followed correctly then try to open teams on desktop client and access the application.

No need to update the manifest file and re-upload them to teams admin center as the app id's, app domain are not going to change.

**Comment by allthetrouts** [comment]
The steps were followed correctly, there arent very many of them. I can assure you its not updating. Having been deploying and updating this app for over a year it never works like the documentation. Looking at yet another full redeploy.

**Comment by gsv022** [comment]
@allthetrouts ,
- What was the version before migrating?
- Please share the screenshot of author app.
