### ISSUE TITLE
Unbale to show the spaces in Summary In Preview and Deliver mode. 

### ISSUE THREAD

**Issue by Prasadj2024** [OfficeDev/microsoft-teams-apps-company-communicator#1461]
In Summery section, while filling the content we are giving spaces in between lines.  But in Preview mode and Delver mode those spaces are not showing. pls see the below screenshots for reference  
<img width="337" alt="Summary_PreviewAndDelvermode" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161813768/535aded7-93ba-4e57-8bdc-4afc4271dbc6">
<img width="455" alt="Summary Draft" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/161813768/7d0f11d8-ddb8-4b23-af1a-9060e322dc2b">

**Comment by Prasadj2024** [comment]
When can we expect to resolve this issue? earlier versions, in summary we can add bullet points and hyperlinks, bold, etc.. but nothing is working in new version.

**Comment by gsv022** [comment]
Hi @Prasadj2024 ,
Please check this [text formatting](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html) link.  Bullet points, bold, italic, Ordered lists are supported.

**Comment by Prasadj2024** [comment]
Hi Sai,

Thanks for respond, yes using shortcuts we are displaying/drafting fine. However, coming to the preview and deliver mode it is not showing properly due to line space issue or whatever.

Thanks,
Prasad.

**Comment by gsv022** [comment]
We have noted the issue and will try to address the issue in future releases. Thank you.
