### ISSUE TITLE
Adaptive Card unable to render markdown on Teams iOS mobile

### ISSUE THREAD

**Issue by mchuong22** [OfficeDev/microsoft-teams-apps-company-communicator#1462]
![issue2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/84984442/e305ebe8-dd70-4be1-a294-3fe97f4d21ff)

- any type of markdown done in the adaptive card will change the font to Times New Roman for iOS Teams. 

![issue1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/84984442/f9b2e29e-d1ae-4a4b-a815-73df78fe2432)

- Nested markdown will not work at all for iOS. This is rendered perfectly fine in Desktop and Web Teams. Issue shows up on iOS mobile for Teams.

**Comment by gsv022** [comment]
Hi @mchuong22 ,
Thanks for raising the query. We will check this from our end and keep you posted.
