### ISSUE TITLE
Break line in preview vs Break line in message

### ISSUE THREAD

**Issue by win-lobo** [OfficeDev/microsoft-teams-apps-company-communicator#1463]
Hello - We are having an issue with the break lines in messages.

We are on version 5.5. Could you please help us fix this?

Preview text with break lines 
<img width="113" alt="1716953326656_1099" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/33344125/7e5675c2-bc56-4ccd-b9e1-5e435e8deca9">

Actual message (no break lines)
<img width="315" alt="1716953326694_1240" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/33344125/65b03464-677c-475e-ba37-8f3dc806c973">

**Comment by gsv022** [comment]
Hi @win-lobo ,
Thanks for raising the query. We will check this from our end and will keep you posted.

**Comment by win-lobo** [comment]
Hello @gsv022 , is there any update on this case?

**Comment by gsv022** [comment]
Hi @win-lobo ,
Yes it's a known issue, this is the limitation with adaptive cards which doesn't support formatting.
However, the issue has been added to the backlog already. We will review it and do the needful.

**Comment by gsv022** [comment]
We don't have ETA currently. But you can expect this issue to be resolved in upcoming versions of CC.

**Comment by win-lobo** [comment]
Thanks!

**Comment by gsv022** [comment]
We have noted the issue and will be taken care in future releases.
