### ISSUE TITLE
Unable to send messages

### ISSUE THREAD

**Issue by ErinComms** [OfficeDev/microsoft-teams-apps-company-communicator#1464]
Help please: I have installed the communicator but I'm receiving this message, Is anyone able to have a call with me to see where I went wrong?

Failed to create conversation with teams user: 29:1tesixF8vC-LpXFIOP659zNhw2y14L5aGj3-Af0V19TSyzOmr5zTi2snBNh4XbENwj8KCYxn9QHQyWSu5jb2ykw. Exception: Failed to acquire token for client credentials. (AADSTS700016: Application with identifier 'a189f9b9-26fa-4958-8b20-cb38dc011f77' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. Trace ID: 49578168-3c08-44fd-bfaf-325cce5ec800 Correlation ID: c7a16214-92d6-42fe-80bf-a2f4a23b4c02 Timestamp: 2024-06-04 01:24:38Z)

**Comment by gsv022** [comment]
Hi @ErinComms ,
Thanks for raising the query.
We suspect that secrets are incorrectly configured.  Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by SteveWedge** [comment]
@ErinComms , Did you resolve this issue and if so what was the cause/resolution? I have the same problem, although this occurred immediately after initial deployment.
