### ISSUE TITLE
Issue installing Company Communicator "App Not Installed"

### ISSUE THREAD

**Issue by SeanMLG** [OfficeDev/microsoft-teams-apps-company-communicator#1465]
Hi, 

We've been able to deploy the company communicator successfully in our 30k+ users department. When sending a message out to everyone, it's not pushed to all users and the logs indicates that the app is not installed. The app has been added to the Setup policies + Permission policies and ProactiveIntallUserApp is set to True. Any suggestions?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/171859810/0080f1e8-fb4f-4a2a-9fd6-1cf129e5e481)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/171859810/a2e6d900-af4f-4f4f-b593-7d0b9dc9e2c2)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/171859810/24ac62cb-ec11-4891-a108-79f3cc09e916)

**Comment by gsv022** [comment]
Hi @SeanMLG ,
Thanks for raising the query. 

- did you observe gradual increase or decrease in the success count for every sent message?
- Please share the latest export data results.

**Comment by SeanMLG** [comment]
> Hi @SeanMLG , Thanks for raising the query.
> 
> * did you observe gradual increase or decrease in the success count for every sent message?
> * Please share the latest export data results.

Hi @gsv022 , yes, the success number slowly goes up.

**Comment by SeanMLG** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/171859810/73acff63-1b47-46b7-b8b5-e0d270709388)

**Comment by gsv022** [comment]
Please share your mail id so that we can discuss the issue internally

**Comment by SeanMLG** [comment]
> Please share your mail id so that we can discuss the issue internally

Hi, you can reach me at sean.leclerc@tpsgc-pwgsc.gc.ca

**Comment by gsv022** [comment]
We have started the conversation internally,

**Comment by SeanMLG** [comment]
For anyone reading this in the future: 

We received no support. 

The only method we found to force the app installation on user's end was to add the Company Communicator(User) app to an MS team, add the users to this team as members and use the Company Communicator(Author) to push a message to the team members(Send in chat to members of the following teams).

**Comment by v-jaygupta** [comment]
Thanks @SeanMLG for connecting internally.  As discussed we are taking this issue to closure as the users are now able to recieve the messages.

**Comment by v-jaygupta** [comment]
Clsoing the issue
