### ISSUE TITLE
Provided add-in package was not understood error when uploading app

### ISSUE THREAD

**Issue by pmkinyua** [OfficeDev/microsoft-teams-apps-company-communicator#1466]
Hi,

I am trying to upload the company Communicator Users app manifest and getting below error.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151738749/54e1b7d6-e955-4a39-8fe8-adf56dec6c9d)

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Thanks for raising the query. Could you please share the manifest files of author and user zip files
