### ISSUE TITLE
Teams Company Communicator is not notifying Some recipients

### ISSUE THREAD

**Issue by jeff-wade-msft** [OfficeDev/microsoft-teams-apps-company-communicator#1467]
Our Company Communicator (Microsoft App that we Run through Teams) is not notifying some of the recipients in the distribution groups. For Example, I created a small distribution group with 3 people, one of them was one of the affected users. I sent a card to the group, and she did not receive it. There are some additional users who have reported missing cards in the past as well.

**Comment by gsv022** [comment]
Hi @jeff-wade-msft ,
Thanks for raising the query. Please confirm on the below points.

- The user(s) who is/are not receiving the messages, are they having valid teams license or not? And make sure that they are not guest user type.
-  Could you please confirm whether the user has deleted the user app from their side or blocked it. If this is the case, it is expected that user won't be the receiving the messages.

**Comment by dhgrande** [comment]
Im facing the same issue, users have valid license and user has not deleted the app

error is:

403 : Failed	Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'

**Comment by JamesClapper** [comment]
Hi, I'm from the affected Org here.  Jeff (OP) is our rep who submitted this on our behalf.  The user has a valid license and is not a guest user.  We see the same behavior whether we send to all users or if we send to a 365 group that she's in.  We're currently suspicious that we might need to upgrade the version of our CC.  We are currently on 5.2.0.

I see that you asked -> Could you please confirm whether the user has deleted the user app from their side or blocked it. If this is the case, it is expected that user won't be the receiving the messages.

How do I go about figuring out of the user did this?  Is is something I would see from their computer or is it something that I can see from the teams admin center?

**Comment by dhgrande** [comment]
Im on latest 5.5.2 and have the same behavior as James

**Comment by alphaz18** [comment]
We're running into similar issues lately. digging further we're getting 404's for some users.
this is from the storage account under the SentNotificationData Table, it shows 404, conversationid and recipientnotfound under delivery status. its like its saying 404 to the conversationid for certain people, which tracks with others complaining about 404s 
https://learn.microsoft.com/en-us/answers/questions/1477908/ms-teams-bot-receiving-404-when-sending-user-messa
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/20524585/d56fba49-0774-4bf7-9787-bcb3949505d1)

**Comment by danizt** [comment]
Im 5.5.2 and have the same behavior

**Comment by JamesClapper** [comment]
Thank you for bringing this issue to my attention. I am looping in the Incident Manager, @Mironica ***@***.***>, to follow up on this case. It seems that CSS is not receiving your replies, James. Mironica, can you please investigate this and provide an update on the situation?

Regards,
Jeff

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: James Clapper - Contractor ***@***.***>
Sent: Monday, June 17, 2024 11:11:35 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; Jeff Wade ***@***.***>
Cc: Comment ***@***.***>
Subject: [EXTERNAL] RE: [OfficeDev/microsoft-teams-apps-company-communicator] Teams Company Communicator is not notifying Some recipients (Issue #1467)


@Jeff ***@***.***> Did you see this? I don’t think they’re reading what I added even though I mentioned that I was the affected user.







________________________________

James Clapper - Contractor
Solutions Engineer
***@***.******@***.***>
Work: 843-245-1914
Mobile: 18033153447
1801 Main Street Suite 1100
Columbia, SC - 29201
www.scdhhs.gov <https://scdhhs.gov/>


[FacebookLogo]<https://www.facebook.com/SCMedicaid>  [XLogo] <https://twitter.com/scmedicaid>   [LinkedinLogo] <https://www.linkedin.com/company/sc-department-of-health-and-human-services>

[SCDHHSLogowithpadding]<http://www.scdhhs.gov/>

[SCDHHSHealthBanner]



Healthy Connections and the Healthy Connections logo are trademarks of South Carolina Department of Health and Human Services and may be used only with permission from the Agency.

**Comment by JamesClapper** [comment]
Do you think I should just submit a new one with the same content?


________________________________

James Clapper - Contractor
Solutions Engineer
***@***.******@***.***>
Work: 843-245-1914
Mobile: 18033153447
1801 Main Street Suite 1100
Columbia, SC - 29201
www.scdhhs.gov <https://scdhhs.gov/>


[FacebookLogo]<https://www.facebook.com/SCMedicaid>  [XLogo] <https://twitter.com/scmedicaid>   [LinkedinLogo] <https://www.linkedin.com/company/sc-department-of-health-and-human-services>
[SCDHHSLogowithpadding]<http://www.scdhhs.gov/>
[SCDHHSHealthBanner]

Healthy Connections and the Healthy Connections logo are trademarks of South Carolina Department of Health and Human Services and may be used only with permission from the Agency.

**Comment by JamesClapper** [comment]
Can we get some feedback on why this got closed?  Was this fixed in some way? Do we need to apply some fix or patch?

**Comment by danizt** [comment]
For me, the problem was solved by deleting the entries of the affected users from the UserData table.

My issue at logs was "Failed to decrypt conversation id".
