### ISSUE TITLE
Author unable to select all options to send messages

### ISSUE THREAD

**Issue by terryseddonpm** [OfficeDev/microsoft-teams-apps-company-communicator#1468]
One of our users has been added to a Teams channel contacting the App, however when they create a message, they only receive the following option for sending:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8710713/bbb1a96f-08e2-4298-8f8a-e388022f3703)

I have confirmed their UPN is added in the Azure app config.

To compare, I get this:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/8710713/d3a091a7-1896-4977-ab75-6ea85943b6e5)

**Comment by gsv022** [comment]
Hi @terryseddonpm ,
Thanks for raising the query.  Please verify the below points.

- Since the user is added to the author list, Open the teams on web client and may be on incognito/InPrivate window would be better to avoid cache issue if not ready already.

**Comment by terryseddonpm** [comment]
So I managed to find the issue. You can't see it on the screenshot, but the scroll bar has disappeared! The app's page automatically focuses towards the bottom or button of the page, and sometimes the scrollbar is not apparent, and/or disappears after a short amount of time, so the user does not realise they need to scroll up to see the other options.

Could the app be altered to focus on the top of the form?

**Comment by gsv022** [comment]
Hi @terryseddonpm ,
This issue has not been reported from any other users. However we will replicate the scenario from our end and check the screen.
