### ISSUE TITLE
Bot Icon not changing even after successfully uploading the package with correct Icons

### ISSUE THREAD

**Issue by pmkinyua** [OfficeDev/microsoft-teams-apps-company-communicator#1469]
The company communicator user bot icon still shows the default image even after successfully uploading the app package

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Thanks for raising the query. 
To update name of CC

- Login to Azure Portal with Global Admin Credentials (portal.azure.com)
- Go to Resource Groups and Under your subscription select the resource group where the app is deployed.
-  Click on Azure Bot(user) --> under settings click bot profile-->Change display name as per the organizational need.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/98143492/213981428-e5af8e1e-8623-4731-b413-8cc62cc3c475.png">

- And update the names in the manifest files for user. Re-upload the manifest file again. Here is the place for reference.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/98143492/213983428-68678fb4-03ae-4a95-933e-0d8e4b4f802d.png">


Please follow the above steps to update the name of user app

**Comment by pmkinyua** [comment]
Hello Sai,

I have followed the instructions but still not change. Below is my current bot profile configuration.

[cid:67484f31-d455-4878-bd1d-158e52408da3]

And this is how the bot appears on Teams.

[cid:a318a694-48c7-4f32-8d2a-ab884a827bd7]






Peter Kinyua

IT Systems Manager



M-KOPA | ***@***.*** | +254 723 511 347

[cid:774ebf5d-4dba-4624-9ba6-198b6cc1a9cc]

________________________________

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Could you please share the screenshots directly on to this github conversation. I am getting the screenshots in a masked state. Below is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/b724abe9-5f64-41ac-9cbe-c17f408980f9)

**Comment by pmkinyua** [comment]
Hi Sai,

Please see below, my bot profile configuration and how its appearing on Teams

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151738749/8274d8cb-448a-49d2-abd5-7b1c5e3e2bf1)

And then on Teams,

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/151738749/4485fd32-0cfb-42cc-abda-a0c57dbbe0cf)

**Comment by gsv022** [comment]
Hi @pmkinyua ,
Please share your mail id so that we can discuss the issue internally
