### ISSUE TITLE
 microsoft-teams-apps-company-communicator-common file !!!

### ISSUE THREAD

**Issue by mavistangtpl** [OfficeDev/microsoft-teams-apps-company-communicator#1472]
I would like to ask how to publish "Microsoft.Teams.Apps.CompanyCommunicator.Common" to Azure, or what file and type it corresponds to within the Azure resource group?

![Screenshot 2024-06-12 165024](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/d0e28a9b-9809-4605-bbc3-9b611ba7e16f)

![Screenshot 2024-06-12 165052](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/68589208/cfed8d05-e1a8-4274-810f-a47fc2f84b20)

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
Thanks for raising the query. Please give us sometime, we will get back to you with proper response soon

**Comment by mavistangtpl** [comment]
> Hi @mavistangtpl , Thanks for raising the query. Please give us sometime, we will get back to you with proper response soon

Hi @gsv022 
I hope to receive your response soon. Thank you.

**Comment by gsv022** [comment]
Hi @mavistangtpl ,
This folder contains build files, secret handling and basically source part of code. Simply, this folder acts as a data access layer to all other folders such as app service, 3-functionapps. This folder doesn't need to be published

**Comment by v-jaygupta** [comment]
We are closing this issue, please log a new issue if you have any further queries regarding CC app
