### ISSUE TITLE
Deployment with "publicNetworkAccess": "Disabled" is not working

### ISSUE THREAD

**Issue by lbgrasso** [OfficeDev/microsoft-teams-apps-company-communicator#1473]
HI everyone.
I'm trying to do a deployment with the "Deploy to Azure button", and I've set the parameter "publicNetworkAccess" to Disabled. But the deployment fails with **The gateway did not receive a response from 'Microsoft.Web' within the specified time period**. Could this setting be the reason why the deployment is failing?
Thanks!

**Comment by gsv022** [comment]
Hi @lbgrasso ,
Thanks for raising the query. It is expected that once Network access is disabled functionality breaks. Current functionality works fine with -"enable it for all networks"

**Comment by lbgrasso** [comment]
The thing is that for security reasons, I'm being asked to change that parameter to disabled. Is there any way that it could work being disabled?

**Comment by gsv022** [comment]
Currently, the functionality works only with publicNetworkAccess as enabled only. if it is set to disabled it will be considered as customization. Our support scope is very limited to standard version of CC. We won't be able to assist much here.

**Comment by lbgrasso** [comment]
Okey, thank you.

**Comment by v-jaygupta** [comment]
@lbgrasso , Can we mark this issue as complete as no further action is required from our side. Please do let us know if you have any furhter queries regarding official version of CC.
