### ISSUE TITLE
Teams Communicator - Unexpected Error

### ISSUE THREAD

**Issue by gsilvaads** [OfficeDev/microsoft-teams-apps-company-communicator#1474]
I have a problem. When adding Teams Communicator to the Channel tab, it shows the home screen, but when clicking on Send New Message, it shows an error without reference. I need help with this issue.

When I click on New Message, the error is displayed:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/d56b765b-bd74-42e1-a9d8-3dbbba69ae47)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/177c9323-535b-4728-91a9-7de78d3152cd)

Data Function:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/04f68783-3015-41d3-ad5c-57877aeccd28)

Function:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/9ee8423f-ab7f-45e9-8968-edbc663fb0db)

Prep Function:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/ed5dad74-9e5e-4e47-bcf3-426759bb1217)

**Comment by gsv022** [comment]
Hi @gsilvaads ,
Thanks for raising the query. Could you please share the application insight logs. Here is the reference.
Go to resource group-->Application Insights-->Under investigate click Failures. Copy the logs and paste it in this chat. Even the screenshots would be more helpful. Here is the reference.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/98143492/4747b16e-067a-47ad-a764-ae38a5f67a89)

**Comment by gsilvaads** [comment]
Hello @gsv022! Tks for your help!

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/a3a0d726-1e29-4131-b888-23ee29e49275)

About logs, what is the best option in this case?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/04fe91b9-7d49-4bf4-a9b4-1a81314883d2)

**Comment by gsv022** [comment]
Hi @gsilvaads ,
There might be a chance that secrets might have incorrectly configured. Please cross-verify them. Here is the procedure for comparison. 

- Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

- Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault  from list of resources

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret. 

---------------------------------------
- Cross verify the supported account type is set to My organization for graph app registration and Multiple Organization for author, user app registrations.

**Comment by gsilvaads** [comment]
Hi @gsv022 !

I needed to do a new deployment of Teams Communicator for reasons of credits in the Azure Subscription.

So, I did the new deployment using the secrets correctly, and the application loaded normally this time.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/3fca0309-a6f6-4997-8915-c0e0c8859629)


However, I am unable to send the messages successfully, all sending tests have failed. 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/ac52313b-d755-4bae-b50e-2f56da140518)

I tried sending with the users I entered in SendersUPNList during deployment.

Can you help me with this error?

Tks for your help!

**Comment by gsv022** [comment]
Hi @gsilvaads ,
Have you added CC-user app to the teams that you are targeting for ?

**Comment by gsilvaads** [comment]
Hi @gsv022 , yes, Teams Communicator Users added:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/78f7ffe5-9b34-4ba6-8c46-9916c3a126cc)

New test:

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/809f9367-90be-46cd-bffe-03b377820c19)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/dc91459f-bc53-411e-bdba-f81b1bc55a56)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/122485340/be8dca4b-090f-4d91-aad1-db98bfa51dfa)

**Comment by v-jaygupta** [comment]
@gsilvaads ,

Please share the error screenshot you are getting in the send message screen also, please checks the failure logs from Apps Insights in Azure portal and see if there are any failures getting captured
