### ISSUE TITLE
Can't find any teams when trying to post a new message

### ISSUE THREAD

**Issue by thowardtw** [OfficeDev/microsoft-teams-apps-company-communicator#1476]
I had raised this issue before (#1437) but didn't get round to resolving it and wanted to see if there was anything else I can check?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/14c3aad4-45c2-4e5c-ad0f-ca34f1dff215)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/82a3ee48-212e-473f-be2a-8d47074bc7d6)

This message keeps coming up when I open the author app. If I click continue nothing happens.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/cdf5af32-d903-4b90-9595-a9b6f70249bc)

Its also getting stuck on fetching like this.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/b1de4dc5-058f-4cf7-9eeb-c96ae9ce392c)

The API permissions are setup and I've also redeployed this a few times and make sure the secrets etc. are all correct.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/168735484/4aa0f1be-1022-4d94-b285-a9d020927d5a)

The support account type is set to My organization for graph app registration and Multiple Organization for author, user app registrations.

I've also tried in a private browser and get the same error.

**Comment by gsv022** [comment]
Hi @thowardtw ,
Thanks for raising the query. Please make sure that these custom apps are allowed in the permission policy section of teams admin center. If not, get them allowed from your concerned administrator in your organization.

**Comment by thowardtw** [comment]
Hi @gsv022 
Yes I have a permission policy which allows the apps and is assigned to my user account

**Comment by gsv022** [comment]
Hi @thowardtw ,
Please share your mail id so that we can discuss the issue internally.

**Comment by thowardtw** [comment]
Is there anyway I can share my email privately instead of posting it here?

**Comment by v-jaygupta** [comment]
Hello @thowardtw ,

You can share your Id here and once we initiate the convesation internally, you can delete the comment from here.

**Comment by thowardtw** [comment]
its t.howard@taylorwessing.com

**Comment by v-jaygupta** [comment]
We have started the communication with the user internally.

**Comment by victorsimonlee** [comment]
Hi. I am facing a similar issue..

We have been using CC for over 2 years now, without issues. 

And, just recently we noticed we when composing new draft messages, the option to send to M365 Groups does not work anymore! The TEAMS option / dropdown is still working. But the GROUPS dropdown does not show anything anymore.

In short: I am experiencing the same issue as the OP, but with the **M365 Group** option.

**Comment by v-jaygupta** [comment]
Hello @thowardtw ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.
You may also always open a new issue or respond here if something does come back up.

**Comment by thowardtw** [comment]
Hi @v-jaygupta 

I am still facing the issue yes.

**Comment by peddivyshnavi** [comment]
we have connected internally with user over call :
while troubleshooting App registrations we identified user have updated wrong url in expose API i.e Graph App registrations and after update we have restarted App service
reinstalled author app in teams then we have added team to user app.
we see teams which were added are visible for 1st and 2nd option

**Comment by peddivyshnavi** [comment]
Closing this ticket as issue got resolved
