### ISSUE TITLE
Suddenly Can't access Company Communicator on Teams

### ISSUE THREAD

**Issue by navadjones** [OfficeDev/microsoft-teams-apps-company-communicator#1477]
We now get this error:
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/ed0d1868-2462-4942-84a2-9bac4f2f0a5f)

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/836248cd-0d5f-468c-9f3d-8d51121b400d)

**Comment by gsv022** [comment]
Hi @navadjones ,
Thanks for raising the query. Could you please clarify on the below points.

- What is the current version of CC application?
- Was it working earlier?
-Is it happening on both desktop client and web client as well?

**Comment by navadjones** [comment]
It shows up up on web but it's a blank page when I click on New
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/27c5d585-915b-457f-9bf6-61422bbe6695)


How do I find the current version?

**Comment by navadjones** [comment]
I think it's version 5.5?
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/b933010e-94b1-4f5a-9b5e-24d05bb20d4e)



If it helps, I can see these error messages:




![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/67797be8-3112-49b8-9927-95b991df00c8)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/1e5b5bad-632a-458b-9df5-60ff31e1921f)

**Comment by v-jaygupta** [comment]
Hello @navadjones ,

Could you please share us the error screenshot from Apps Insights from Azure portal. In addition to this, can you please cross check the values of client secret for User, Author & Graph app from azure key vault and make sure the values are same as generated at the time of App registrations.

**Comment by navadjones** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/ca95b662-7ba3-43de-9715-456fa269585e)

Is this what you're after?

I've redeployed the template so now it's succeeded but still not working on Teams. I've double checked all the secrets and IDs

The app doesn't show at all on New Teams. But on the old Teams/Browser, I can click on New Message, but comes up with a blank screen. It's been like this since April.

**Comment by v-jaygupta** [comment]
@navadjones Could you please update us on the status of the issue
