### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by clarkec2** [OfficeDev/microsoft-teams-apps-company-communicator#1478]
We are running into an issue with the resource/web portion of the deployment, which is failing due to a bad request with this message, {"code":"BadRequest","message":"There was a conflict. Conflict with existing ScmType: ExternalGit","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"},{"code":"BadRequest"},{}]}. We have attempted to point it to the repository hosted on https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git using the main branch and resyncing without success. This is the only portion of the deployment failing and we would like some assistance if possible. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/6ff1698a-d008-4bdd-b4fd-45df788fd044)

**Comment by v-jaygupta** [comment]
Hello @clarkec2,

Thank your for contacting us!
To overcome the failed resources issue please follow the below steps - 
 Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select prep-function(or failed resource) from list of resources-->Go to Deployment Center-->Click on **SYNC**. Below is the screenshot for reference.
image
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/b2730e09-7b2d-4960-9797-aedb9ab61893)

- If the resource is not pointing to intended repository and showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by v-jaygupta** [comment]
Hi @clarkec2 ,

Could you please let us know if the deployment issue got resolved ?

**Comment by clarkec2** [comment]
Updated the ARM Template to point to the right repo
