### ISSUE TITLE
Suddenly the field "search for groups" doesn't work

### ISSUE THREAD

**Issue by eravamocariamici** [OfficeDev/microsoft-teams-apps-company-communicator#1480]
I have been using Company Communicator for about a year. The initial installation was done with version 5.4.2. Since April 2, 2024, I have been regularly using version 5.5.2. I am writing to report that for the past 2 days, I have been unable specific groups for selecting recipients no longer works.

<img width="568" alt="group" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/11669795/7d5487db-cbb2-4ea1-bce7-df13a5691441">

**Comment by eravamocariamici** [comment]
The secret key had expired.

**Comment by victorsimonlee** [comment]
@eravamocariamici  - I believe I'm experiencing the same issue. Could you please give me some pointers on how to fix the secret key expiration issue? Thank you.
