### ISSUE TITLE
Services application configuration

### ISSUE THREAD

**Issue by mayerliv20** [OfficeDev/microsoft-teams-apps-company-communicator#1481]
Hello, 

currently the deployment of the app services is active, but in the configuration the author bot id, appdomain and the user bot id do not appear.  A version and .NET details configuration topic appears but you do not see this confirmed data?

**Comment by v-jaygupta** [comment]
Hello @mayerliv20 ,

Thanks for reaching out to us!
Could you please confirm if the deployment is done or its in progress. These details will be mentioned in the output section of the deployment once the deployment gets completed successfully. If the deployment fails due to any reason then, the output section will be blank. The author and the user app id will be the **app client ids** of the **user** and the **author app registrations** and app domain url will be **https://[appName].azurefd.net**

**Comment by mayerliv20** [comment]
The implementation finished but generated an error in the implementation of the template, due to an issue with the service application, due to git, I adjusted it, but when I adjusted it, the implementation of the service application remained active, but in the same way when I go to the configuration of this service application, it does not show me those values. because it is?

**Comment by v-jaygupta** [comment]
@mayerliv20 , Can you please share the error screenshots for the issue you are facing. This will help us to understand and resolve the issue quickly.

**Comment by mayerliv20** [comment]
<img width="269" alt="Screenshot 2024-06-26 141830" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143755367/9f57776c-98f6-44e3-ab87-5613349fa350">
<img width="260" alt="Screenshot 2024-06-26 141954" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143755367/b11b6ff7-017e-4620-a730-9143064885e1">
Hello, yes, I attach two images, once the error that generated us, currently tells us that it is the git issue, we made a deployment only of that error, but it continues to generate the same error and we did the manual git of the service application, but it still does not show us the bot author and user.
<img width="227" alt="Screenshot 2024-06-26 142209" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143755367/9b9a4635-d541-4a8d-b899-43f9b063c745">

**Comment by v-jaygupta** [comment]
To overcome the failed resources, please follow below mentioned steps - 
Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select prep-function(or whatever resources that failed in the ARM template deployment) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/0de29e53-d633-4c62-a59e-cd293ef7de1e)

- If the resource is not pointing to intended repository and showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again.

**Comment by mayerliv20** [comment]
Hello.
Yes, we already did that and the synchronization remained active, but I still cannot obtain the author bot id and user bot id

**Comment by v-jaygupta** [comment]
@mayerliv20 , the author and the user bot id's that we get in the output section of the ARM deployment is nothing but the app registration client id's of the user and the author apps. Also, the app domain in the output will be in below mentioned format - 
**[appservicename].azurefd.net** 
where appservicename will be the replaced by the name of your deployed app service resource in azure.

Please proceed with the further steps of deployment

**Comment by mayerliv20** [comment]
Hello, We managed to make the connection but now in teams we have this error.
![caso](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143755367/cc5c5a34-fd52-4351-94b8-1264d0a8cba4)

**Comment by mayerliv20** [comment]
Hello, We managed to make the connection but now in teams we have this error.
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143755367/2c5807b8-ba54-4af3-a9f2-fa821fadcc91)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/143755367/7842e72b-ab5c-43c9-9e85-e6a73f9cdafe)

**Comment by mayerliv20** [comment]
@gsv022
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.421

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)

npm notice 
changed 83 packages in 13m
npm notice New major version of npm available! 8.19.2 -> 10.8.2

npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.2>
249 packages are looking for funding
npm notice Run `npm install -g npm@10.8.2` to update!
  run `npm fund` for details
npm notice 
Building the client app (this can take several minutes)

> company-communicator@5.5.2 build
> react-scripts build

node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module 'C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\css-minimizer-webpack-plugin\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\config\webpack.config.js:20:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\css-minimizer-webpack-plugin\\package.json',
  requestPath: 'css-minimizer-webpack-plugin'
}
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock.json file was created with an old version of npm,\r\nnpm WARN old lockfile so supplemental metadata must be fetched from the registry.\r\nnpm WARN old lockfile \r\nnpm WARN old lockfile This is a one-time fix-up, please be patient...\r\nnpm WARN old lockfile \r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm notice \r\nnpm notice New major version of npm available! 8.19.2 -> 10.8.2\r\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.2>\r\nnpm notice Run `npm install -g npm@10.8.2` to update!\r\nnpm notice \r\nnode:internal/modules/cjs/loader:361\r\n      throw err;\r\n      ^\r\n\r\nError: Cannot find module 'C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\css-minimizer-webpack-plugin\dist\index.js'. Please verify that the package.json has a valid "main" entry\r\n    at tryPackage (node:internal/modules/cjs/loader:353:19)\r\n    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)\r\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\r\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\r\n    at require (node:internal/modules/cjs/helpers:102:18)\r\n    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\config\webpack.config.js:20:28)\r\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\r\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\r\n    at Module.load (node:internal/modules/cjs/loader:981:32) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  path: 'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\css-minimizer-webpack-plugin\\package.json',\r\n  requestPath: 'css-minimizer-webpack-plugin'\r\n}\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.10502.001\bin\Scripts\starter.cmd deploy.cmd

**Comment by mayerliv20** [comment]
@gsv022 Permisiunile au fost deja validate și confirmate și așa mai departe, dar această eroare apare în Teams

**Comment by v-jaygupta** [comment]
Hello @mayerliv20 ,
Could you please check and confirm if the [Authorization Issue Fix](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix) has been made in the Azure Frontdoor resource of the deployed app?

**Comment by mayerliv20** [comment]
Hello @v-jaygupta
Yes, it was validated but that is not active according to the correction. But I don't know what else it could be?

**Comment by mayerliv20** [comment]
![image](https://github.com/user-attachments/assets/3784d4b9-c90e-4ddb-80f6-413ccc01c629)
