### ISSUE TITLE
All messages are Queued

### ISSUE THREAD

**Issue by mchandu2020** [OfficeDev/microsoft-teams-apps-company-communicator#1483]
All messages are queued and we have provided all permissions but it's not working. Is there any documentation guide to troubleshoot the issue?

**Comment by v-jaygupta** [comment]
Hello @mchandu2020 ,

Thank you for contacting us!
Could you please share us the error screenshot from Apps Insights from Azure portal. In addition to this, can you please cross check the values of client secret for User, Author & Graph app from azure key vault and make sure the values are same as generated at the time of App registrations.
