### ISSUE TITLE
Something Went Wrong - Issues opening app in Teams

### ISSUE THREAD

**Issue by clarkec2** [OfficeDev/microsoft-teams-apps-company-communicator#1484]
We were able to get past an ARM Template issue, however when attempting to open the app in the Teams Client or in Web we are met with a generic error "Something Went Wrong". We have double and triple checked the deployment and see no issues. The only error we are seeing is a 400 Bad Request in a trace with no other indicators of what is causing the bad request...

**Comment by v-jaygupta** [comment]
Hello @clarkec2 ,

Thank you for contacting us!
Please share the deployment status of the app service and the three function apps deployed via the ARM template deployment also confirm if the deployment is success . Below is the reference - 
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/3e535112-eab3-4cf6-91d6-817cf3a7aad3)
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/2e686fbb-924e-4d22-9502-ba4646742a08)

**Comment by clarkec2** [comment]
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***



General Business

**Comment by v-jaygupta** [comment]
Hi @clarkec2 ,

We aren't able to view the images sent by you via email. Can you please attach the screenshots on the GitHub Issue [#1484](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1484)

**Comment by clarkec2** [comment]
![1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/cecde761-d0bf-4acb-9940-b7fc539fa004)
![2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/73f18680-0fed-48c1-a4f4-edc3588c8f99)
![3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/5b3f6c70-a230-4715-b77f-e2b425bd5d8d)
![4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/95d7a112-612f-47ae-bf7e-8ce7b70c2d72)
![5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/09f6f2ba-8bf6-4e4b-b31d-3cfcce227b75)
![6](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/26fb2636-3ada-4579-b5be-b594fe956125)
![7](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/40007696-b944-4419-ade9-1a85f43ce14e)
![8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/22be13b1-8b1a-416f-b39a-247c9b9b9c23)

**Comment by clarkec2** [comment]
Hello, 

We were able to work past the previous error however, when attempting to draft a new message I am met with another error message after it briefly shows the new message form: "Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists." When inspecting the API I see that it is making thousands of fetch calls to the following...

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/cfb42462-ec36-405d-be13-56b8431c5e4d)

Is that normal? 

I am also seeing this directly after clicking Draft Message
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/e50aa84a-1fba-4da8-8fa1-c984ce1ba2c6)

and
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/a2b5e463-64e5-495b-b799-5c0fa0284134)

**Comment by will-smothers** [comment]
I am getting this same error and I have validated that all three Function Apps (Communicator-data-function, Communicator-Function, and Communicator-prep-function) all us the same Deployment settings:

> Source = External Git
> Repository = https://github.com/OfficeDev/microsoft-teams-company-communicator-app.git
> Branch = main
> Status = Success (Active)

@clarkec2 - You said in your last post that you were able to work past the previous error, can you share how you did that?

**Comment by clarkec2** [comment]
@will-smothers The issue lied in the manifest that was uploaded to Teams. When We took a look at it we noticed that the data on line 34, 49 and 50 was incorrect prompting us in updating the BOT ID under bots, and the ID and RESOURCE under WebApplicationInfo

**Comment by will-smothers** [comment]
@clarkec2 - Ours turned out to be a timing issue. I waited a few hours and apparently it had time to register with the Azure services and now I can get it to load but I am getting an error now with accessing the Company Communication - Author tab in the Teams channel. It keeps telling me "Sorry, you do not have permission to access this page. Please contact your administrator to be granted permission" even though my UPN is listed in the AuthorizedCreateorUpns. 

Now to troubleshoot that. Thanks for the response!

**Comment by clarkec2** [comment]
@v-saikirang Has anyone had a chance to take a look at this? I am completely stumped, and this is hampering our comms as it is the primary tool used in Teams.

**Comment by v-saikirang** [comment]
Hi @clarkec2,

Sorry for the delayed response. Please allow us some time. We will get back to ASAP.

Thanks.

**Comment by tiwariShiv7** [comment]
Hey @clarkec2, Can you please Share the Screenshot of failures ? To Do this,
- Go to resource group-->Resource of type Application Insights-->Under investigate click Failures

Also, Please Click on the Response code given on the side (Highlighted By Red Arrow in the below image) and Click on 1st suggested box (Refer 2nd Image with Blue Arrow For this) -> Send the screenshot of the page appeared. 

<img width="959" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152329231/c37c6a19-47d7-46da-8d22-cd6ba83d4ccc">


<img width="812" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152329231/070f0c60-af26-4f63-8de7-2cb9af7401fb">

**Comment by clarkec2** [comment]
There are 4 in the Azure Table, they are identical...
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/2a5d0202-9e72-4a02-9b08-5f976c83ef8e)

One in Microsoft.Storage
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/b9c5cf4b-5dec-4b49-ae92-32bfeeb8a3da)

And One in the Azure Blob
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/140619924/11bb0acf-58a0-4bdf-88fc-9d9623bda559)

**Comment by tiwariShiv7** [comment]
Hi @clarkec2, Please share your ID we can continue the conversation over Teams

**Comment by clarkec2** [comment]
Is there anyway to provide that privately?



General Business

**Comment by clarkec2** [comment]
Apologies, I replied via email. Is there a way to pass that on privately? Or could you provide your contact?

**Comment by tiwariShiv7** [comment]
Hi @clarkec2 Sorry there is no way to provide it privately as of now. You can add your contact id here that can be deleted later as we start the conversation over Teams
