### ISSUE TITLE
CC app not sending chat to all users

### ISSUE THREAD

**Issue by Numotion-ITCommsGit** [OfficeDev/microsoft-teams-apps-company-communicator#1486]
We're seeing an issue where a, seemingly, random subset of our 3,000 employees are not receiving messages send to 'all users' via chat. When looking at these individuals they do not appear in the message log as either sent or failed.
When looking at the SentNotificationData table I can find the user IDs for the people stating they've never received messages and they all have status 404 RecipientNotFound
We are on build 5.5.2

**Comment by v-jaygupta** [comment]
Hello @Numotion-ITCommsGit ,

Thanks for reaching out to us!
Once the message status falls under the category -Recipient Not Found. It will be not counted in either as success or failure. But this can be overcome in next sent message as once the user sync kicks in the user app installation will happen for affceted user. If the failure count seems for every message to be same and failure status showing as recipient not found then we can discuss the issue internally.

**Comment by Numotion-ITCommsGit** [comment]
The users experiencing this issue have never and continue to not receive any messages sent from the bot. All messages sent to them show the same recipient not found message.
I have verified the employee has the user app installed on their side. It shows zero messages when opened.
I have the user app set as a default app to be deployed to all non-guest users in our tenant via the Teams Admin Center.

**Comment by v-jaygupta** [comment]
@Numotion-ITCommsGit , Please share your mail id/ teams id so that we can discuss the issue internally.

**Comment by Numotion-ITCommsGit** [comment]
> @Numotion-ITCommsGit , Please share your mail id/ teams id so that we can discuss the issue internally.

scott.wheeler@numotion.com
Thank you for the assistance

**Comment by Numotion-ITCommsGit** [comment]
Good morning. Is there any update on this?

**Comment by tiwariShiv7** [comment]
Hey @Numotion-ITCommsGit , We are currently discussing it internally. We will soon start the conversation over the Teams chat.

**Comment by Numotion-ITCommsGit** [comment]
[like]  Scott Wheeler reacted to your message:
________________________________

**Comment by v-jaygupta** [comment]
Hello @Numotion-ITCommsGit ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.
You may also always open a new issue or respond here if something does come back up.

**Comment by Numotion-ITCommsGit** [comment]
Hi,
Yes I'm still experiencing this issue and would like assistance in resolving the bug. It has persisted through version upgrades and others on the Git have expressed that they are experiencing the same or similar issue.
Thank you

**Comment by peddivyshnavi** [comment]
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
We are closing this ticket due to no response. Feel free to open a new GitHub issue if you encounter any problems.

**Comment by v-jaygupta** [comment]
Resolved the original issue by connecting with the user over call, hence taking this issue to closure.
