### ISSUE TITLE
Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID

### ISSUE THREAD

**Issue by sujeetsharma** [OfficeDev/microsoft-teams-apps-company-communicator#1487]
I have recently deployed the CC in my orgainization tenant. One deployed instance is running perfectly fine. But when trying to send message from another deployed instance of the CC getting below error. 

`System.AggregateException: Failed to acquire token for client credentials. (A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'GUID'. Trace ID: e2ab7b14-d156-442a-ab84-a8bf8610eb00 Correlation ID: 063a326b-db94-42f8-96cd-e293ed5b6d4c Timestamp: 2024-06-28 14:25:27Z)`

**Troubleshooting steps done:**
1. I am double-tripple check the correct configuration in environment variables. UserAppPassword has correct keyvault value. Still same issue.
2. Created a new version(same secret) of app secret in keyvault and updated the environment variables. Re-sync the deployment. Still same issue.
3. Create a new app secret in azure app registrations. Updated the same in keyvault. Then updated environment variables. Re-sync the deployment. Still same issue.

Could you please help identify the issue and help resolve this.

**Comment by tiwariShiv7** [comment]
Hello @sujeetsharma , 
Thanks for reaching out to us! The error seems to be pretty much with mismatch in secret. 
Can you please send a screenshot of first 3 letters of secret in App registration and same from the key vault for all 3 app registration (Author, User and Graph apps)? 
Also Please make sure Graph app registration type is My organization and for other 2 it should be Multiple organization.

**Comment by tiwariShiv7** [comment]
Thank you I will check internally and get back to you soon

**Comment by tiwariShiv7** [comment]
Hi @sujeetsharma, 
There are multiple places where secret need to be updated- Web app/App Service, Function apps such as Prep-function, Data-Function, Function.

Not only AuthorAppPassword, UserAppPassword, GraphAppPassword but also AzureAD:ClientSecret need to be updated with GraphAppPassword. Can you please cross-verify these places.

**Comment by sujeetsharma** [comment]
> Hi @sujeetsharma, There are multiple places where secret need to be updated- Web app/App Service, Function apps such as Prep-function, Data-Function, Function.
> 
> Not only AuthorAppPassword, UserAppPassword, GraphAppPassword but also AzureAD:ClientSecret need to be updated with GraphAppPassword. Can you please cross-verify these places.

@tiwariShiv7 The error is specific to the UserAppPassword. And yes, I have updated in the web-app, all function apps. 
During provisioning the template, I have used the correct secrets. Same way I had setup another instance.

`Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'GUID'`

The GUID here was for the UserApp.
Do you know if we can debug this and correct the source of this error?

[Error Stack.txt](https://github.com/user-attachments/files/16094657/Error.Stack.txt)

**Comment by tiwariShiv7** [comment]
Hey @sujeetsharma, Yes we can discuss this. Meanwhile we are discussing this internally, Can you please share your contact e-mail to contact over Teams / outlook and availability time zone ?

**Comment by sujeetsharma** [comment]
@tiwariShiv7 Please find my contact details as below:
sujeetkumar.sharma@henkel.com
Work hours 9AM-6PM CET(12PM-9PM IST)

We are already federated, so you can directly IM me on Teams.

**Comment by tiwariShiv7** [comment]
We are following it over the Teams

**Comment by sujeetsharma** [comment]
@tiwariShiv7 @v-jaygupta Update - I have done the redeployment of instance and after which the new deployment is working as expected.
