### ISSUE TITLE
Can't read the manifest file

### ISSUE THREAD

**Issue by Nadeem-hussain-mafgs** [OfficeDev/microsoft-teams-apps-company-communicator#1488]
I am deploying the company communicator and was uploading the author file where in i got the error that the application with same app is already uploaded. I verified author app id, and it was one newly generated. 

I saw that one more user was facing the same issue where in recommendation was to change the manifest file id, however after doing that it's showing a different error that We can't read the manifest file.

**Comment by tiwariShiv7** [comment]
Hi @Nadeem-hussain-mafgs, Thanks for reaching out. Probability is high that there is some issue with manifest file that you are trying to upload. 
- Please make sure that manifest file is valid. You can take help of online manifest validation tool for this purpose. 
- Also, make sure that it is zipped correctly as mentioned in [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages)
- Please retry with getting the latest manifest file from the freshly cloned repository 

Let us know in case you continue to face the issue

**Comment by Nadeem-hussain-mafgs** [comment]
Hi Tiwari

I have validated the file and all the ID's are valid.

Appreciate if we can connect over Teams to close this.

**Comment by tiwariShiv7** [comment]
Sure @Nadeem-hussain-mafgs, Please let us know you contact ID to connect over Teams/ Outlook along with time zone you are available in.

**Comment by Nadeem-hussain-mafgs** [comment]
nadeem.hussain-e@maf.ae

We can connect today at 4.30 PM IST, please confirm as soon as you will receive this message as i would require deleting the ID from here.

**Comment by tiwariShiv7** [comment]
We started continuing the discussion over the chat
