### ISSUE TITLE
Issue not fixed. It got closed when I went on Leave!

### ISSUE THREAD

**Issue by navadjones** [OfficeDev/microsoft-teams-apps-company-communicator#1490]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/35564943/cb176b00-341a-4504-8ea0-86b26b600330)

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1477

I did try that but still not worked.

**Comment by navadjones** [comment]
Suddenly Can't access Company Communicator on Teams #1477

**Comment by tiwariShiv7** [comment]
Hi @navadjones , We will discuss it internally and get back to you soon.

**Comment by navadjones** [comment]
Hi, do you have any updates?

**Comment by v-jaygupta** [comment]
@navadjones , 
Please share your mail id/ teams id so that we can discuss the issue internally.

**Comment by navadjones** [comment]
kassie.navarasi@blackpool.gov.uk

**Comment by tiwariShiv7** [comment]
Hi @navadjones, meanwhile we are working internally please fill [Auth Issue Fix](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)

**Comment by navadjones** [comment]
Hi, this was suggested on the post that was closed. I've already tried this but not working.

**Comment by v-jaygupta** [comment]
Hi @navadjones ,
We have initiated the conversation internally. Please check and respond.

**Comment by navadjones** [comment]
Hi, i've just seen the message on teams, I've replied

**Comment by tiwariShiv7** [comment]
Internal discussion is in progress on this issue
