### ISSUE TITLE
Error commit App Service repo upgrade last version CC 5.5.2

### ISSUE THREAD

**Issue by clecca** [OfficeDev/microsoft-teams-apps-company-communicator#1491]
Error commit:

Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)

up to date in 3m

249 packages are looking for funding
  run `npm fund` for details
Building the client app (this can take several minutes)

> company-communicator@5.5.2 build
> react-scripts build

node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module 'C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\tryer\src\tryer'. Please verify that the package.json has a valid "main" entry
Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\bfj\src\streamify.js:9:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\tryer\\package.json',
  requestPath: 'tryer'
}
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock.json file was created with an old version of npm,\r\nnpm WARN old lockfile so supplemental metadata must be fetched from the registry.\r\nnpm WARN old lockfile \r\nnpm WARN old lockfile This is a one-time fix-up, please be patient...\r\nnpm WARN old lockfile \r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnode:internal/modules/cjs/loader:361\r\n      throw err;\r\n      ^\r\n\r\nError: Cannot find module 'C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\tryer\src\tryer'. Please verify that the package.json has a valid "main" entry\r\n    at tryPackage (node:internal/modules/cjs/loader:353:19)\r\n    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)\r\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\r\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\r\n    at require (node:internal/modules/cjs/helpers:102:18)\r\n    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\bfj\src\streamify.js:9:15)\r\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\r\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\r\n    at Module.load (node:internal/modules/cjs/loader:981:32) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  path: 'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\tryer\\package.json',\r\n  requestPath: 'tryer'\r\n}\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.10502.001\bin\Scripts\starter.cmd deploy.cmd

**Comment by clecca** [comment]
Hi @tiwariShiv7 , I am deploying it manually, as it does not work through powershell, and I have not been able to solve the problem.

**Comment by tiwariShiv7** [comment]
Sure Please Keep us updated in case of any issue or success.

**Comment by clecca** [comment]
Any suggestions regarding this error?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/62079031/f1749acf-278d-4f71-afbf-1ca892d36914)


Log Details
Commit ID: 876fbbab9e27387f612e84ffed9be9a8c55cc054

7:24:53 PM
Updating submodules.
7:24:53 PM
Preparing deployment for commit id '876fbbab9e'.
7:24:53 PM
Running custom deployment command...
7:24:53 PM

Running deployment command...
[Show Logs...](https://functions.azure.com/feature/subscriptions/d3acbc7a-56e2-4a34-935e-fbc9d3d0fced/resourcegroups/rg-companycommunicator/providers/microsoft.web/sites/kmmpcompanyc/deploymentcenter?correlationid=cd45d4a5-85cb&sessionid=9c7289f1a34a4ec7be7c5b61a8b50b44&frameid=aac692f8-8f6a&appsvc.react=true&elasticscaleout=true&newoverviewblades=true&appsvc.bladetype=frameblade&clientOptimizations=undefined&l=en.en-us&trustedAuthority=https%3A%2F%2Fportal.azure.com&shellVersion=undefined#a9e71907-afab-45e1-aca4-0a420bbcdade)
7:40:56 PM
Deployment Failed.
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.421

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: company-communicator@5.5.2
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.14.0" from react-dom@16.14.0
npm WARN node_modules/react-dom
npm WARN   react-dom@"^18.2.0" from the root project
npm WARN   4 more (react-redux, @fluentui/react, ...)

npm notice 
changed 56 packages in 6m
npm notice New major version of npm available! 8.19.2 -> 10.8.1

249 packages are looking for funding
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.1>
npm notice Run `npm install -g npm@10.8.1` to update!
  run `npm fund` for details
npm notice 
Building the client app (this can take several minutes)

> company-communicator@5.5.2 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

<--- Last few GCs --->

[7528:047955F8]   545471 ms: Scavenge (reduce) 487.6 (510.7) -> 487.6 (510.7) MB, 7.9 / 0.0 ms  (average mu = 0.436, current mu = 0.089) allocation failure 
[7528:047955F8]   545484 ms: Scavenge (reduce) 487.9 (510.7) -> 487.8 (510.9) MB, 1.3 / 0.0 ms  (average mu = 0.436, current mu = 0.089) allocation failure 
[7528:047955F8]   548713 ms: Mark-sweep (reduce) 488.5 (511.4) -> 487.6 (511.4) MB, 3210.8 / 0.1 ms  (average mu = 0.339, current mu = 0.187) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 01445D3F v8::internal::Heap::AllocateExternalBackingStore+1551
Failed exitCode=134, command=npm run build
An error has occurred during web site deployment.
npm WARN old lockfile \r\nnpm WARN old lockfile The package-lock.json file was created with an old version of npm,\r\nnpm WARN old lockfile so supplemental metadata must be fetched from the registry.\r\nnpm WARN old lockfile \r\nnpm WARN old lockfile This is a one-time fix-up, please be patient...\r\nnpm WARN old lockfile \r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm WARN ERESOLVE overriding peer dependency\r\nnpm WARN While resolving: company-communicator@5.5.2\r\nnpm WARN Found: react@16.14.0\r\nnpm WARN node_modules/react\r\nnpm WARN   react@"^18.2.0" from the root project\r\nnpm WARN   12 more (@reduxjs/toolkit, react-dom, react-i18next, react-redux, ...)\r\nnpm WARN \r\nnpm WARN Could not resolve dependency:\r\nnpm WARN peer react@"^16.14.0" from react-dom@16.14.0\r\nnpm WARN node_modules/react-dom\r\nnpm WARN   react-dom@"^18.2.0" from the root project\r\nnpm WARN   4 more (react-redux, @fluentui/react, ...)\r\nnpm notice \r\nnpm notice New major version of npm available! 8.19.2 -> 10.8.1\r\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.1>\r\nnpm notice Run `npm install -g npm@10.8.1` to update!\r\nnpm notice \r\nBrowserslist: caniuse-lite is outdated. Please run:\r\n  npx update-browserslist-db@latest\r\n  Why you should do it regularly: https://github.com/browserslist/update-db#readme\r\n\r\n<--- Last few GCs --->\r\n\r\n[7528:047955F8]   545471 ms: Scavenge (reduce) 487.6 (510.7) -> 487.6 (510.7) MB, 7.9 / 0.0 ms  (average mu = 0.436, current mu = 0.089) allocation failure \r\n[7528:047955F8]   545484 ms: Scavenge (reduce) 487.9 (510.7) -> 487.8 (510.9) MB, 1.3 / 0.0 ms  (average mu = 0.436, current mu = 0.089) allocation failure \r\n[7528:047955F8]   548713 ms: Mark-sweep (reduce) 488.5 (511.4) -> 487.6 (511.4) MB, 3210.8 / 0.1 ms  (average mu = 0.339, current mu = 0.187) allocation failure scavenge might not succeed\r\n\r\n\r\n<--- JS stacktrace --->\r\n\r\nFATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory\r\n 1: 01445D3F v8::internal::Heap::AllocateExternalBackingStore+1551\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.10502.001\bin\Scripts\starter.cmd deploy.cmd

**Comment by clecca** [comment]
In the Functions resources if the commit is correctly deployed, this error is only in the App Service.

**Comment by tiwariShiv7** [comment]
I would suggest please disconnect the repo From Deployment center of App service then wait for 20-30 mins All logs will get cleared. Once there is nothing in the logs Please select External Git -> Enter Repo Name and Branch name as 'main'. Click save and Sync it one more time. 
 
 Refer [Troubleshooting guide Point #5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#5-app-service-sync-throws-npm-error)

**Comment by clecca** [comment]
Yes, I had already done that, however, the problem persisted. But, I managed to find the solution, the problem was due to the fact that due to a cost issue I was deploying the app service plan in S1, I changed it to S2 and it was executed correctly. 👍
