### ISSUE TITLE
Sorry, an error occurred while trying to access this service.

### ISSUE THREAD

**Issue by clecca** [OfficeDev/microsoft-teams-apps-company-communicator#1492]
Hello, good afternoon, I am experiencing the following error "Sorry, an error has occurred while trying to access this service" this has happened when using new version of Teams, however with the Classic if it worked, was made upgrade to version 5.5.2 and the problem persists, and users can no longer to return to the Classic version of Team, the option is no longer available.

![Captura de pantalla 2024-07-01 101044](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/62079031/5fe6ee55-f60d-4f40-8bef-7080b62d898e)

**Comment by tiwariShiv7** [comment]
Hi @clecca , Thanks for reaching out to us. Can you please verify if the [Authorization-issue-fix](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix) changes are successfully applied after migration?

**Comment by clecca** [comment]
Hi @tiwariShiv7, la configuración sugerida se encuentra tal cual como se muestra.

**Comment by tiwariShiv7** [comment]
Hi @clecca , Can you please share the screenshot of App insights log to do this. Go to resource group-->Resource of type Application Insights-->Under investigate click Failures. Copy the screenshots and paste it here. 

Also, please try to open Teams in Incognito / in-private mode of browser and verify there as well

**Comment by clecca** [comment]
Hi @tiwariShiv7, I attach a screenshot.

![Captura](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/62079031/13beaf6a-35c1-4da6-a7e9-87e14e27ac86)

Additionally I see the following commit error in the appservice

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/62079031/3f7ee056-4850-4c17-ae9a-674f882ce6fb)

**Comment by clecca** [comment]
Is this OpenSource solution compatible with the new version of Microsoft Teams?

**Comment by tiwariShiv7** [comment]
Hi @clecca, Yes it is currently compatible with the new version of Microsoft Teams. We would advise you to, 

1. Disable the routing rule 2 as mentioned in the [FIX Guide ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)
2. For the commit error, 
- Please Refer to [Troubleshooting Guide's #5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)
- After following this please click on Sync. 

3. Please Following point #2 for all the function apps type resources as well if they failed. 

It should fix the error.

**Comment by clecca** [comment]
Hi @tiwariShiv7 , thank you very much, the problem was solved with this fix, however, I still have an error in the sync of the app service with the ExternalGit repository, but at the app Teams level I already have the CC Authors.

Detail with app service sync problem
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1491

**Comment by tiwariShiv7** [comment]
Thank you for the confirmation. I am closing this issue here. We will continue to follow on 1491 for the app service related issue.
