### ISSUE TITLE
Mutliple users are not receiving alerts On their Teams Applications after clearing the chat

### ISSUE THREAD

**Issue by gurr05** [OfficeDev/microsoft-teams-apps-company-communicator#1493]
Multiple users in our tenant are not receiving the alerts on their Teams App. these user are part of the target audience.

**Comment by tiwariShiv7** [comment]
Hey @gurr05 , Thanks for reaching out to us. Please confirm if the issue can be rephrased as, 
- You are trying to send a message to a group of users and it is failing for some.

If the above is true, Please give us more details, 
- How many users you are trying to send message to ? 
- How many are not receiving the message? 
- Which sending option you are trying to send with. 
- Please help us with the screenshot of sent message table.

**Comment by gurr05** [comment]
thanks Tiwari for the response.

few of the users who have cleared the chat from the Company Communicator cannot receive any alerts from the day they cleared the chat.

we tried clearing the Teams cache and also removed the teams app permission for the users and re-assigned it, still they're unable to receive the alerts on their teams

**Comment by tiwariShiv7** [comment]
Hi @gurr05, Thanks for the response. We will discuss this internally if there is any chance we can correct this. I am back from long holidays today and will try to get back in couple of days. Please allow me some time.

**Comment by v-jaygupta** [comment]
Hello @gurr05 ,
Could you please share your contact e-mail to contact over Teams / outlook and availability time zone to discuss the issue internally ?

**Comment by gurr05** [comment]
Hi Jay,

here is my email address - ***@***.******@***.***>.

Please find my availability for tomorrow and next week.

Tomorrow (7/12) – Between 9:00 to 10:00 AM ,12:00 to 1:30 PM and 3:30 to 5:30 PM EST
Monday (7/15) – Between 10:30 to 12:30 PM and 1:00 to 5:30 PM EST

Thanks
Aravind Siddhartha Gurram
M365 Support Engineer
Health System Shared Services - Technology Deployment
614-685-3179 Office / 302-252-8011 Mobile
***@***.******@***.***>
Working Hours: Mon-Fri 08:00 - 17:00 EST



From: v-jaygupta ***@***.***>
Date: Wednesday, July 10, 2024 at 11:17
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Gurram, Aravind Siddhartha ***@***.***>, Mention ***@***.***>
Subject: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Mutliple users are not receiving alerts On their Teams Applications after clearing the chat (Issue #1493)
Hello @gurr05 , Could you please share your contact e-mail to contact over Teams / outlook and availability time zone to discuss the issue internally ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving


Hello @gurr05<https://urldefense.com/v3/__https:/github.com/gurr05__;!!AU3bcTlGKuA!DiVOfnTlMFY5K7_8K0l0sDii_9d-lqXFXM1yiG_KMLibHtwixodtie5QjF-AvQjmBYStdeIz58TpQZBN-AFERJ9aALr9XfNtuOzhvQ$> ,
Could you please share your contact e-mail to contact over Teams / outlook and availability time zone to discuss the issue internally ?

**Comment by tiwariShiv7** [comment]
Hi @gurr05, We are not able to see your email id here and it is looking as shown below. 

<img width="749" alt="image" src="https://github.com/user-attachments/assets/2049bc4d-4edd-46e0-a03e-eda7e1f9bc87">

**Comment by gurr05** [comment]
Hi Tiwari,

Looks like its hiding my emailaddress.

This is the format of our email address firstname.lastname  @ osumc.edu – aravindsiddhartha.gurram @ osumc.edu

Thanks
Aravind Siddhartha Gurram
M365 Support Engineer
Health System Shared Services - Technology Deployment
614-685-3179 Office / 302-252-8011 Mobile
***@***.******@***.***>
Working Hours: Mon-Fri 08:00 - 17:00 EST

**Comment by tiwariShiv7** [comment]
Hey @gurr05, Thank you we will soon start the conversation over the Teams.
