### ISSUE TITLE
Post new message to user list by csv file

### ISSUE THREAD

**Issue by clecca** [OfficeDev/microsoft-teams-apps-company-communicator#1494]
Error en el mensaje:

Errors
Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: "Invalid audience select for notification id: 2516822752142608683". See the function execution logs for additional details.

file csv
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/62079031/bf547c19-e516-4aca-810f-e8473788d778)

**Comment by tiwariShiv7** [comment]
Hi @clecca ,
Thanks for raising the query.

Please recheck graph app API permissions and make sure no permission is missing. 
Hope you have updated manifest section within graph app registration.

Please cross verify the secrets. Here is the procedure for comparison.

Go to app registration-->open author app registration-->click certificate and secrets-->Grab secret value(not id)

Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select keyvault from list of resources

Go to Access Policy--> Click on Create

<img width="403" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152329231/9f0a1856-c500-46f2-a46e-bde40b6aa0a2">


Select Key, secret and certificate management
<img width="305" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152329231/07fc64c0-88d3-4f13-b03a-b75ec10c72b4">


Give the Id through which one can view the secrets
<img width="318" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/152329231/71ec0fa0-0371-4797-bbc5-f73bc6f65302">

3rd step is optional
Go for Review+Create
Then go to Secrets. You will be able to view the secrets. Compare each app secret from keyvault with app registration secret.

**Comment by clecca** [comment]
Thank you very much, however, I notice that the option is not available in the latest version 5.5.2, because I have updated correctly and the option of UPNs by CSV does not appear anymore. Is this correct?

**Comment by v-jaygupta** [comment]
It appears from the previous conversation that you were utilizing a customized version of the app, rather than the official one, which includes features such as sending messages via CSV, among others.
This feature is on our backlog, and we plan to implement it in upcoming releases based on priority and available resources; however, we do not have an estimated time for its completion.
