### ISSUE TITLE
Migration options v3 to v5

### ISSUE THREAD

**Issue by felipeschulz** [OfficeDev/microsoft-teams-apps-company-communicator#1495]
hi, i need migrate from v3.1 to the latest version, but i need to know what is the best pratice: 

- Migrate to v4 and then migrate to v5? 
- migrate from v3 to v5 is possible? 
- or a new deploy is recommended? (if a new deploy is the best choice, i will lose my previous data or it is possible to do an import/restore ?)

**Comment by v-jaygupta** [comment]
Hello @felipeschulz ,

Thanks for reaching out to us!
If you want to retain your data then we would suggest to go for step by step upgrade i.e. upgrade to v4 first by following [v4 migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide) and then upgrade from v4 to v5 or the latest version by following [v5 migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide).
But the quickest way will be to deploy a new instance of CC side by side within your tenant, test it out and then you can switch to the newly deployed CC instance. In this case you will not be able to restore previous data.

**Comment by felipeschulz** [comment]
ok, I tried to do a new installation while waiting for this response, but when I follow the deployment through powershell, I can't proceed because an AzureAD module was deprecated and the "Connect-AzureAD" command on line 1068 no longer works

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/54079684/68520d59-3a2c-41ab-a764-15448000c852)

any suggestion?

**Comment by tiwariShiv7** [comment]
Hey @felipeschulz , Can you please try with manual deployment in this case ?

**Comment by felipeschulz** [comment]
I did this, but now I have another problem: queued messages:
![image](https://github.com/user-attachments/assets/7a11d4d6-7467-4dd9-8dfe-7e907ab5e4bf)
 i tried re-sync webapp (because it failed on the first deployment), but it didn't work:
![image](https://github.com/user-attachments/assets/5f7ddbc0-baf3-452c-9260-054eb8d9f8d8)
![image](https://github.com/user-attachments/assets/faaacb34-3b3c-4f4f-bbc0-366ad9600766)


i guess someting (bot maybe?) doesn´t retrive messages in queue on Service bus

**Comment by v-jaygupta** [comment]
Hello @felipeschulz, 
The 1st and the 2nd sending options will be enabled once we add the user app against the particular team, then it will start to display Team names in the dropdown.
For the message queue issue, can you please check and share the app insights screenshots and logs to troubleshoot further.

**Comment by felipeschulz** [comment]
Hi @v-jaygupta 
Of course:

![image](https://github.com/user-attachments/assets/638fb7de-db41-4b8a-a2fe-8f6892c4c955)


When i send a draft messagem:
![image](https://github.com/user-attachments/assets/3aec6631-9926-4fac-ad3b-dfb791672b4d)

HTTP 409:
Time	11:40:32
Duration	8 ms
Outgoing command	PUT sgghi6kw4xve4
Result code	409
AspNetCoreEnvironment	Production
ClientRequestId	56cf922e-c460-4fce-8331-90bb9a0119f4
Container	images
ServerRequestId	7f393013-b01e-007a-36c4-d6377d000000
_MS.ProcessedByMetricExtractors	(Name:'Dependencies', Ver:'1.1')
https://sgghi6kw4xve4.blob.core.windows.net/images?restype=container
Time	11:40:32
Duration	11 ms
Outgoing command	BlobContainerClient.Create
AspNetCoreEnvironment	Production
Error	Azure.RequestFailedException: The specified container already exists. RequestId:7f393013-b01e-007a-36c4-d6377d000000 Time:2024-07-15T14:40:32.0800550Z Status: 409 (The specified container already exists.) ErrorCode: ContainerAlreadyExists Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists. RequestId:7f393013-b01e-007a-36c4-d6377d000000 Time:2024-07-15T14:40:32.0800550Z</Message></Error> Headers: Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0 x-ms-request-id: 7f393013-b01e-007a-36c4-d6377d000000 x-ms-client-request-id: 56cf922e-c460-4fce-8331-90bb9a0119f4 x-ms-version: 2021-08-06 x-ms-error-code: ContainerAlreadyExists Date: Mon, 15 Jul 2024 14:40:31 GMT Content-Length: 230 Content-Type: application/xml at Azure.Storage.Blobs.ContainerRestClient.CreateAsync(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken) at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
_MS.ProcessedByMetricExtractors	(Name:'Dependencies', Ver:'1.1')

![image](https://github.com/user-attachments/assets/1b9615f3-8f09-4b46-9992-7d3c0ef676fc)

do you need any specific query for logs?

**Comment by v-jaygupta** [comment]
@felipeschulz ,
Could you please check the failure section and share the failure logs screenshot which are outlined. Before viewing the logs I would request you to please try to access and send a new message so that the latest errors can be captured in the app insinghts logs.
