### ISSUE TITLE
Sorry an error occurred while trying to access this service.

### ISSUE THREAD

**Issue by sravanthiGITHUB** [OfficeDev/microsoft-teams-apps-company-communicator#1496]
1. We used to have Company Communicator V 5.0 last year. 
2. We were getting an error "Sorry an error occurred while trying to access this service" from Feb 2024. 
3. Recently we have upgraded the app to latest version
4. Saw this link https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix, but could not find "Azure Front Door Resource" in the CC resource group.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/109225932/272b8368-3f80-4774-887e-b181f3cdd7f4)

**Comment by v-jaygupta** [comment]
Hello @sravanthiGITHUB ,

Thanks for reaching out to us!
Could you please share the repor URL and the branch name used for the deployed CC instance. You can find these info by follwing the below steps - 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center - 

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/115773960/01385426-16af-450b-b68f-1165579af1a4)

**Comment by sravanthiGITHUB** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/109225932/5567f220-cd79-4cdb-a029-fc41997b6d99)


I tried the steps mentioned in this link and the error is now gone. But the messages are queued up. Please find below screenshots.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/109225932/afc81260-1e94-4278-8440-3838eda31b55)

**Comment by sravanthiGITHUB** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/109225932/97d49b59-e9d7-4de0-ad4e-aaad3eb1f205)


Messages are queued up now. The earlier is gone after disabling the routing rule 2 from front door resource and resetting Teams app.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/109225932/182ce8f6-bd1b-426a-8ed3-377af54b39a5)

**Comment by sravanthiGITHUB** [comment]
Also I see below errors in the data function.

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/109225932/79144a83-dad6-4c42-979d-10a37ba01389)

**Comment by tiwariShiv7** [comment]
HEy @sravanthiGITHUB, We need one more quick info on this. Can you please share the sync logs of all function app and app service ? To do this, 

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service)  / *-function apps --> Go to Deployment Center -> Click logs -> Paste the screenshot here.
