### ISSUE TITLE
Query reg. what are the features present in the company communicator's latest version 5.5.2

### ISSUE THREAD

**Issue by SachinWandale111** [OfficeDev/microsoft-teams-apps-company-communicator#1497]
Hello, team.
We wanted to know all of the features present in the communicator's latest version 5.5.2 in comparison to the previous version 5.3.0.
Could you please tell us what's new in the current version?
Also, please offer more details on the following features for the current version 5.5.2. Also find attached screenshot for reference. Thanks

App Features: 
Tabs
Use in a tab at the top of a chat or channel.

<img width="473" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/160738265/f12b74e6-ef27-44a7-92bd-e2cf7753bc20">

**Comment by tiwariShiv7** [comment]
Hi @SachinWandale111, All the features of official version of Company Communicator are listed here [RELEASES ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Release-notes)

For 5.5.2 We have made the Company Communicator fully compatible with New Teams where we saw users facing issues.

Let me know if this helps. Also, please confirm the repository you are using is the official repository of Company Communicator 
Which is "https://github.com/OfficeDev/microsoft-teams-apps-company-communicator"

**Comment by SachinWandale111** [comment]
As we are going to the provided [RELEASES](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Release-notes) article, but we did not see about schedule message feature and Delete send messages feature listed in 5.5.2 which is available in the latest version.

Also we could not see any answer for above query as well. Please provide your input on this.

<img width="213" alt="image" src="https://github.com/user-attachments/assets/d8040745-625c-44d2-babd-72f27a1f8be2">

**Comment by tiwariShiv7** [comment]
Hi @SachinWandale111 , Yes before commenting on these features we would require the URL and branch name used for the Company Comminutor instance deployed. You can find these info by following the below steps -
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

**Comment by v-jaygupta** [comment]
@SachinWandale111 ,
the queries have answered internally, we are checking on the other requests for now, we will share an update soon

**Comment by SachinWandale111** [comment]
Hi @v-jaygupta,
Thanks for your feedback on internally. 
Meanwhile could you also take a look of other two queries which we asked above?
i) (in New Version 5.5.2 we can see in Author Bot =>Use in a tab at the top of chat or channel) => What does it mean?
ii) can you kindly confirm how do we Validate "upgrade classic app insight to workplace based app insight" is successful or not in our new version deployment. Please provide the steps to verify it.
 
<img width="579" alt="image" src="https://github.com/user-attachments/assets/0b434ae0-2e05-4e68-a551-6546deb3cfb3">

**Comment by SachinWandale111** [comment]
Hi @v-jaygupta,
Could you kindly update us on above tow queries please? The first query we are already discussing with you internally where also we are awaiting your feedback. Thanks

**Comment by SachinWandale111** [comment]
Hi @v-jaygupta,
Thanks for following up with us internally. We will keep you updated if we still we have any query.

**Comment by v-jaygupta** [comment]
All the queries have been addressed internally, therefore, we are proceeding to close this issue.
