### ISSUE TITLE
The manifest file in Microsoft Teams apps Company Communicator is not working.

### ISSUE THREAD

**Issue by ARV-IT-Github** [OfficeDev/microsoft-teams-apps-company-communicator#1499]
I am unable to upload the manifest file to Microsoft Teams. Would you be able to verify that the manifest file on GitHub is working?

**Comment by tiwariShiv7** [comment]
Hi @ARV-IT-Github , Thanks for reaching out. Please check your manifest here [https://dev.teams.microsoft.com/appvalidation.html](https://dev.teams.microsoft.com/appvalidation.html) 

In case of any error please send us the screenshot here

**Comment by v-jaygupta** [comment]
@ARV-IT-Github , 
Could you please update us on the status of the issue ?
