### ISSUE TITLE
Blank Line is not showing any more

### ISSUE THREAD

**Issue by malikahoffer** [OfficeDev/microsoft-teams-apps-company-communicator#1501]
In order to structure our messages, we often use blank lines. It makes the messages more clear. But since some time we cannot insert blank lines anymore, and they don't show in the old cards as well. After checking a lot of possiblities with markdown, I can say that it does not work anymore.
In the preview section the blank lines appear, but not in the sent card.
Preview:
![image](https://github.com/user-attachments/assets/7e9b970c-0d02-4483-b657-c8f72b3ffb44)
Card:
![image](https://github.com/user-attachments/assets/f8728076-35b7-4ac7-b5cf-6c537c7e06d9)

I tried e.g.: 
- enter enter
- at the end of the line space space enter space space enter
- enter enter space enter enter
Communicator version 5.5.2

**Comment by v-jaygupta** [comment]
Hello @malikahoffer 

Thanks for reaching out to us!
We will check on this and get back to you with a proper response soon.

**Comment by captainhook** [comment]
We are seeing this issue too - checked on both v5.2 and then a fresh install of v5.5.2.

**Comment by captainhook** [comment]
I've just had confirmation from our users that this is no longer an issue - possibly fixed by a recent Teams client update?

**Comment by malikahoffer** [comment]
Since the update to the newest version of the Siemens Communicator, we have the blank lines again. Maybe it is coincicence, since captainhook had the issue with the newest version as well.
