### ISSUE TITLE
Functions Sync Issue while upgrading to v5

### ISSUE THREAD

**Issue by jammanapallikiran** [OfficeDev/microsoft-teams-apps-company-communicator#1502]
Microsoft.Azure.WebJobs.Script: Error building configuration in an external startup class. Microsoft.Azure.WebJobs.Script: One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later. .

Tried to Sync the function apps, below is the error message. 

Using Msbuild from 'C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin'.
C:\home\site\repository\Source\CompanyCommunicator\Microsoft.Teams.Apps.CompanyCommunicator.csproj : error : Version 3.1.426 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.

**Comment by tiwariShiv7** [comment]
Hi @jammanapallikiran , Thanks for reaching out. To start with can you please share the following info? 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].  

<img width="243" alt="image" src="https://github.com/user-attachments/assets/b0120a92-7d82-4a65-b8cd-10f714121d34">

**Comment by jammanapallikiran** [comment]
![image](https://github.com/user-attachments/assets/48d32527-e352-4fc3-86c7-38656804cf88)

![image](https://github.com/user-attachments/assets/dda1f517-b714-42db-8e51-d43e279e4377)

**Comment by tiwariShiv7** [comment]
Hi @jammanapallikiran, We are currently in internal discussion for this issue. We will update you ASAP

**Comment by jammanapallikiran** [comment]
@tiwariShiv7  - Thank you for looking into this. Really appreciated.

**Comment by v-jaygupta** [comment]
@jammanapallikiran , We have noticed that the app service and the function apps are pointing to a different branch (**master**).
We would recommend you to disconnect the repo and use below details to connect to the official GitHub repo and continue further with the migration steps from the migration guide -
**GitHub Repo URL -** https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
**Branch Name -** main

**Comment by jammanapallikiran** [comment]
Thank you for the response, have update the Repo URL  - below is the error log.

> company-communicator@5.5.2 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Failed to compile.

TS2307: Cannot find module 'axios' or its corresponding type declarations.
  [0m [90m 2 |[39m [90m// Licensed under the MIT License.[39m
   [90m 3 |[39m
  [31m[1m>[22m[39m[90m 4 |[39m [36mimport[39m axios[33m,[39m { [33mAxiosResponse[39m[33m,[39m [33mAxiosRequestConfig[39m } [36mfrom[39m [32m"axios"[39m[33m;[39m
   [90m   |[39m                                                          [31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m[31m[1m^[22m[39m
   [90m 5 |[39m [36mimport[39m [33m*[39m [36mas[39m microsoftTeams [36mfrom[39m [32m"@microsoft/teams-js"[39m[33m;[39m
   [90m 6 |[39m [36mimport[39m i18n [36mfrom[39m [32m'../i18n'[39m[33m;[39m
   [90m 7 |[39m[0m

**Comment by tiwariShiv7** [comment]
Hi @jammanapallikiran , Please disconnect and give 30 minutes of time then try connecting to the official repository again. It will work

**Comment by jammanapallikiran** [comment]
Tried with disconnecting repository for more than an hour and sync again for the app service. It gave same error as above. 

![image](https://github.com/user-attachments/assets/d12a182a-f4b0-4f06-85c0-7e40d331a8f7)
![image](https://github.com/user-attachments/assets/722eff1a-3226-43b0-8573-47fcfb7ca054)

**Comment by tiwariShiv7** [comment]
Hi @jammanapallikiran , From the last screenshot Repository name is not correct. 
Please give the following as input. 
Repository : https://github.com/OfficeDev/microsoft-teams-apps-company-communicator.git
Branch : main

**Comment by jammanapallikiran** [comment]
Have disconnected old repo, gave an hour gap, reconnected to new GITHIB repo and shows same error again. 
![image](https://github.com/user-attachments/assets/11bdbc10-ab2c-4921-9bf4-3efb1019ca35)
![image](https://github.com/user-attachments/assets/cd5d8934-fc7f-4779-ac39-5cce7792892a)
![image](https://github.com/user-attachments/assets/9c73913d-9eb3-47a6-b25e-73c3f41d47b6)

**Comment by jammanapallikiran** [comment]
@v-jaygupta  - k.jammanapalli@zurichna.com

**Comment by jammanapallikiran** [comment]
Hello all, Can any one assist app service/functions sync issue. Genuine support is really appreciated.

**Comment by tiwariShiv7** [comment]
We have started to continue the discussion internally.

**Comment by jammanapallikiran** [comment]
Hello. Have asked one question a day(some times repetitive) from past 3 weeks. Shared all info needed. Have did follow up as well, haven’t heard back any. Please let me know if any needed. Attaching screenshot for reference.
![image](https://github.com/user-attachments/assets/09d6f2b1-ea21-4a79-a34e-376c47772c4b)

**Comment by tiwariShiv7** [comment]
Hi @jammanapallikiran, Thanks for your patience. We are continuosly looking to improve our efforts towards improvising support for Company Communicator. Please be assured we are currently working on scheduling a right time for the call. We will soon be reaching out to you through internal chat.

**Comment by bbarona** [comment]
Good afternoon, I also have the same problem and I have followed the steps as indicated and the same thing happens. Could you help me too, thank you (Error building configuration in an external startup class.) 
![image](https://github.com/user-attachments/assets/bcc4208d-e141-414c-84b5-73c56d1bb5c5)

**Comment by v-jaygupta** [comment]
Hello @jammanapallikiran , 
Could you please update us the status of the issue?
