### ISSUE TITLE
Deployment Failed 

### ISSUE THREAD

**Issue by lsborroto** [OfficeDev/microsoft-teams-apps-company-communicator#1504]
<img width="380" alt="pointat" src="https://github.com/user-attachments/assets/79bba10d-9b89-4b20-9a7e-21df10728171">
<img width="290" alt="Error" src="https://github.com/user-attachments/assets/fa525d5c-bc96-4330-9cc5-49d7c6dca016">
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "target": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxx/resourceGroups/CompanyComunicatorCEI/providers/Microsoft.Web/sites/CompanyCEI-function/sourcecontrols/web",
        "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
    }
}
resource: xxxx-function/web

**Comment by tiwariShiv7** [comment]
Hi @lsborroto, Thanks for Reaching out. Please Click on sync for the apps failing. Click on the Logs under deployment center and if it is successful please continue with rest of the steps.

**Comment by lsborroto** [comment]
I will try again, and let you know.
