### ISSUE TITLE
company comminicator chatbot stooped working

### ISSUE THREAD

**Issue by ramadanfares** [OfficeDev/microsoft-teams-apps-company-communicator#1505]
Hi

we have an issue with company communicator chatbot not working after classic teams retired

**Comment by tiwariShiv7** [comment]
Hi @ramadanfares, please follow Auth Issue Fix (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix). It will solve the issue. Please confirm.

**Comment by ramadanfares** [comment]
Hello i tried the fix in the document but doesn't work

**Comment by tiwariShiv7** [comment]
Hi @ramadanfares , 

1. Can you please share the screenshot of the Front Door Designer as showing in [Auth Issue fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)? 

2. Please share the screenshot of Company Communicator instance as what is error being shown there. 

3. Please try once in Browser version of Teams app to avoid any cache issue.

**Comment by ramadanfares** [comment]
hi
i tried in browser same error appears. 


![Elaraby Comminicator1](https://github.com/user-attachments/assets/5cb029bf-0ac5-4749-9ba3-80ffebe6fc0b)
![image (1)](https://github.com/user-attachments/assets/351db6eb-1eb8-4dec-86cf-11182e91c941)

**Comment by tiwariShiv7** [comment]
Thanks @ramadanfares , Please share the below information 

Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].
![image](https://github.com/user-attachments/assets/2faa30a2-2b35-4295-a8cc-a232c9ec17ec)

**Comment by tiwariShiv7** [comment]
Hi @ramadanfares , 

This is how it is visible to us.

**Comment by ramadanfares** [comment]
![image (2)](https://github.com/user-attachments/assets/7c1c1ee4-ffd8-4e28-b45a-8be1d26ae91b)

**Comment by v-jaygupta** [comment]
Hello @ramadanfares ,

Could you please share the error details and the supporting screenshot of error from application insights resource from the deployed resource group to investigate further on this issue.

Go to resource group where CC app is deployed --> Go to Application insight type resource -->Under investigate section Click on failures --> share the screenshot and stack trace for Top 3 response codes.

**Comment by ramadanfares** [comment]
kindly check

![image (3)](https://github.com/user-attachments/assets/271208fb-0151-4536-abf4-fbd564162c12)

**Comment by tiwariShiv7** [comment]
Hi @ramadanfares , Can you please share the below info as well ?

**Comment by ramadanfares** [comment]
[cid:4377ff5a-fb40-49a4-84ee-5bb1c2ca1ce9]
________________________________

**Comment by ramadanfares** [comment]
Anyupdate please
________________________________

**Comment by ramadanfares** [comment]
still not resovled. anyupdate please?
