### ISSUE TITLE
Change logo and name

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1506]
Hi,

It's not really an issue, but is there a way to customise the branding, including the name and app logo?

**Comment by tiwariShiv7** [comment]
Please refer to this [FAQ #12](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Frequently-Asked-Questions-(FAQ)#12-how-to-update-the-banner-title-and-the-logo)

**Comment by ahlim0011** [comment]
![Screenshot 2024-07-24 114247](https://github.com/user-attachments/assets/a8560a8f-84f3-499d-88cf-c20bf3dbad39)
do you know why I don't see the option mentioned on the FAQ
