### ISSUE TITLE
Problema ao subir o manifesto do user no teams

### ISSUE THREAD

**Issue by taysa-barbosa** [OfficeDev/microsoft-teams-apps-company-communicator#1507]
Fiz todo o procedimento do zero e na hora de subir o manifesto do user, apresenta o seguinte erro:

![TEAMS](https://github.com/user-attachments/assets/0332d307-1537-4833-93ee-5b27a8d4534f)
![TEMS3](https://github.com/user-attachments/assets/80ec0268-cc5d-4cd5-ac81-eb2401c147e1)

E também fiz a besteira de excluir do canal onde iria utilizar o author e  agora quando tento adicionar novamente, apresenta o seguinte erro: 

![TEAMS2](https://github.com/user-attachments/assets/4f07ad98-890d-4575-bc46-dd052aaed34e)

Utilizei ate o validador de vocês:
![TEAMS4](https://github.com/user-attachments/assets/fdb84883-6a2b-4477-9d75-7d55b36714a6)

**Comment by tiwariShiv7** [comment]
Hi @taysa-barbosa, Please share the zipped manifest file here. We can check the same

**Comment by taysa-barbosa** [comment]
[company-communicator-users.zip](https://github.com/user-attachments/files/16362177/company-communicator-users.zip)

**Comment by taysa-barbosa** [comment]
O manifesto tem dados sensiveis, como vou postar aqui?

**Comment by tiwariShiv7** [comment]
Alright @taysa-barbosa , We will get back to you within 24 hours. we can try changing the ID of the manifest file having issue. I'll confirm you  if it is needed

**Comment by taysa-barbosa** [comment]
Pode entrar em contato comigo com urgência, por favor.. estamos a mais de 25 dias parados por conta disso.

**Comment by taysa-barbosa** [comment]
Pessoal, preciso de um suporte com um pouco mais de urgência, vocês teriam algum canal qual posso falar diretamente com algum analista?

**Comment by v-jaygupta** [comment]
Hello @taysa-barbosa ,

Seems like you are the app

**Comment by taysa-barbosa** [comment]
Porque você encerrou? ainda não esta resolvido.

**Comment by v-jaygupta** [comment]
I have updated the above comment please check, this should resolve the issue

**Comment by taysa-barbosa** [comment]
Eu entendi onde devo substitui porém não entendi, onde gero o novo id (GUID)?

**Comment by v-jaygupta** [comment]
Please use the below link to generate a new GUID - 
https://www.guidgenerator.com/online-guid-generator.aspx
Also, you need to update it in the manifest files that is mentioned in the step-5 of the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) and for the configuration of App service and Prep-Function I have provided the steps in previous comment

**Comment by taysa-barbosa** [comment]
É só na function de preparação? as outras não precisa atualizar esse valor?

**Comment by taysa-barbosa** [comment]
Agora apresenta esse erro:
![teams5](https://github.com/user-attachments/assets/326315d2-9cc2-4566-9e0c-ca248a7d3fde)

será que gerei o GUID do jeito certo?

**Comment by tiwariShiv7** [comment]
HI @taysa-barbosa Can you please take a Screenshot of the files present in your zipped folder and paste it here ?

**Comment by taysa-barbosa** [comment]
Esses são os arquivos presentes
![image](https://github.com/user-attachments/assets/a979cb31-394d-4b6e-b348-edf18d8ebb53)

**Comment by tiwariShiv7** [comment]
Thanks @taysa-barbosa. Please share your email-id. We can continue discussion over Teams chat.

**Comment by taysa-barbosa** [comment]
taysa.barbosa@cogna.com.br

**Comment by tiwariShiv7** [comment]
Hi @taysa-barbosa, Yes we have added this to our queue. We will soon start the conversation over Teams

**Comment by taysa-barbosa** [comment]
Poxa, em breve quando? to precisando disso com certa urgência.

**Comment by v-jaygupta** [comment]
Hello @taysa-barbosa ,

Upon internal review, it appears that the user manifest file is named **"manifest_user.json"** within the user app package. Please rename the file to **"manifest.json"** repackage the app, and then upload it to Teams. Before uploading the app package, you can validate it using the [Teams App Validator](https://dev.teams.microsoft.com/appvalidation.html)

**Comment by taysa-barbosa** [comment]
Boa tarde pessoal, deu certo as alterações que eu fiz, além de editar o nome do manifesto, eu também adicionei as variaveis no app service do botid e authorid, ai subiu.. porém, uma dúvida que eu tenho, como eu faço para enxergar meus grupos do AD?
![image](https://github.com/user-attachments/assets/b5e35739-92f5-46d0-bdac-1da72a40a5a0)

**Comment by taysa-barbosa** [comment]
Pessoal, uma dúvida.. Consegui configurar porém quando eu faço o envio, ele sobe um chat também do company, teria como retirar essa notificação por chat?
![image](https://github.com/user-attachments/assets/cc64b71e-7838-4c13-b3c7-6181a478e9b3)

**Comment by victorsimonlee** [comment]
@taysa-barbosa - as mensagens enviadas pelo communicator são feitas através de um bot (por isso esse chat). As opcao para nao ter esse chat, seria enviar a mensagem para um Team - voce tem varias opcoes de envio.

**Comment by v-jaygupta** [comment]
@taysa-barbosa ,
Could you please update us the status of the issue?
