### ISSUE TITLE
Company Commuicator started giving this error on 7/19, was working fine on 7/16

### ISSUE THREAD

**Issue by stehodge** [OfficeDev/microsoft-teams-apps-company-communicator#1508]
We have made no changes to our configuration.  We get this error when clicking the author app tab in the Team.  It appears to load for a brief second then errors out.

Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

**Comment by tiwariShiv7** [comment]
Hi @stehodge , Thanks for reaching out. Can you please share the Failures Screenshot ? 
Yes We can connect tomorrow. Please share the screenshot of failures as well. 
To do this, 
1. Navigate to the Resource group with which the instance is deployed.
2. Go to  Application insight type resource.
3. Under investigate -> Click on failures.
4. Share the screenshot here

**Comment by stehodge** [comment]
***@***.***

***@***.***

Steven Hodge l FLUOR l Global IT - End User Services l ***@***.******@***.***> l Office 864.281.4334 | IODC (8) 20-4334

**Comment by tiwariShiv7** [comment]
<img width="465" alt="image" src="https://github.com/user-attachments/assets/5d4ed857-8ce4-4b56-9dba-deee79a27233">


Hi @stehodge . This is how it is visible to us. Can you please try to paste the screenshot here on GitHub?

**Comment by stehodge** [comment]
![2024-07-25_10-26-37](https://github.com/user-attachments/assets/0adbbc17-cc66-432e-93e9-9ae9eb0f47ba)
screen shot

**Comment by stehodge** [comment]
done

Steven Hodge l FLUOR l Global IT - End User Services l ***@***.******@***.***> l Office 864.281.4334 | IODC (8) 20-4334

**Comment by tiwariShiv7** [comment]
Hi @stehodge, Thanks can you please verify if [Auth Issue fixes](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix). 

Let us know if this is same as guided also please confirm if there is any recent change in the version of Teams (classic to new Teams)

**Comment by stehodge** [comment]
Routing rule 2 was already disabled.

We are in the process of switching all of our users to New Teams.

Steven Hodge l FLUOR l Global IT - End User Services l ***@***.******@***.***> l Office 864.281.4334 | IODC (8) 20-4334

**Comment by tiwariShiv7** [comment]
Got it lastly can you please share the below information as well ? 

Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

<img width="349" alt="image" src="https://github.com/user-attachments/assets/9264671c-75e1-4586-8352-3462ee7f2be9">

**Comment by stehodge** [comment]
![2024-07-30_09-17-01](https://github.com/user-attachments/assets/0d602c13-6c08-4a9d-8f0d-c04cc97e8898)
![2024-07-30_09-17-19](https://github.com/user-attachments/assets/9deb9fc6-65ab-4125-ad3c-b741d06127cd)

**Comment by stehodge** [comment]
done

Steven Hodge l FLUOR l Global IT - End User Services l ***@***.******@***.***> l Office 864.281.4334 | IODC (8) 20-4334

**Comment by tiwariShiv7** [comment]
Hi @stehodge, Can you please share your contact ID to continue discussion over Teams?

**Comment by stehodge** [comment]
***@***.***

Steven Hodge l FLUOR l Global IT - End User Services l ***@***.******@***.***> | 864.281.4334 | IODC (8) 20-4334
________________________________

**Comment by tiwariShiv7** [comment]
<img width="443" alt="image" src="https://github.com/user-attachments/assets/0ba7e229-a637-44d8-a121-bb4c3696c7c9">


Hi Steven it is  currently not visible to us as it is masked

**Comment by stehodge** [comment]
steven.hodge@fluor.com

**Comment by tiwariShiv7** [comment]
We are following this issue internally.

**Comment by sivanikakuru09** [comment]
Is this issue resolved, We are seeing same error 

Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

**Comment by stehodge** [comment]
This issue has not been resolved.  Please contact me with the next steps.

**Comment by sivanikakuru09** [comment]
Good Morning

I have a question, we are GCC regular. Should we use single tenant while creation of app registration or follow this guide which tells first two apps should be selected as multiple tenant and third app as single?


Deployment guide * OfficeDev/microsoft-teams-apps-company-communicator Wiki (github.com)<https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide>

Thanks,
Sivani Kakuru
Senior M365 Support Engineer, (Contractor - Focused Management, Inc.)
Phone: (301) 504-0235
Mobile: (301) 639-1868

**Comment by stehodge** [comment]
Sivani Kakuru-
Please open a new case for your issue.  This case is to track the issue I opened.  These back and forth emails may be confusing for the team working on the issue.

**Comment by peddivyshnavi** [comment]
Hi @stehodge 
Could you please update us on the status of the issue?

**Comment by stehodge** [comment]
Deployment failed again.

**Comment by stehodge** [comment]
After repairing the deployment, I get this error adding the author's app to a Team.
"Something went wrong when loading tab configuration dialog, please try again later."
