### ISSUE TITLE
Can't search for teams/distribution groups. (similar to #1476)

### ISSUE THREAD

**Issue by DukesOC** [OfficeDev/microsoft-teams-apps-company-communicator#1509]
Good afternoon, 

we are having the same issues as [1476](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1476)

I have just upgraded to v5 and cannot search for teams. I have checked we have the correct app permissions as well as redeploying to confirm secrets are correct.

Any help would be greatly appreciated. 

Many thanks,
Troy

**Comment by tiwariShiv7** [comment]
Hi @DukesOC , Thanks for reaching out. Can you please try Export to Excel functionalities and see if it is working fine by after sending a message with any other option to 1-4 users for test ? 
Please inform us in any case

**Comment by DukesOC** [comment]
Hi Thanks for your reply, 

I'm can't see anywhere to export to excel in the teams app, however i was not aware of the failures insight page and this has given some good insight. 
![image](https://github.com/user-attachments/assets/348595bf-b29e-4b07-a17a-78f8e7b8cbb8)

The error we got for teams searching is: 
A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '1ec0c6b1-8c80-4132-b899-36cb7ff88eac'. Trace ID: 13cc84dd-758b-4e4d-bca5-a72be9f75000 Correlation ID: 3dada6c0-115f-4b01-808f-1704cf3e66ff Timestamp: 2024-07-23 15:31:48Z 

this suggests we have provided the wrong values so i will go back to the config and reconfirm all our details are correct.

Thanks again for the help

**Comment by tiwariShiv7** [comment]
Thanks @DukesOC . Please confirm once you validate it

**Comment by DukesOC** [comment]
Good Morning, 

I can confirm with the correct values for the secrets this is now working. 

Thanks for the help in pointing me to the insights page.

Kind Regards,
Troy

**Comment by DukesOC** [comment]
closing
