### ISSUE TITLE
Application not working from IOS Iphone 11 pro max

### ISSUE THREAD

**Issue by mohamedmagdy001** [OfficeDev/microsoft-teams-apps-company-communicator#151]
Hello All application not working from mobile device (Iphone) and give me this error message sorry an error occurred while trying to access this service
![WhatsApp Image 2020-03-31 at 9 02 29 PM](https://user-images.githubusercontent.com/38833560/78073689-a564d880-73a1-11ea-9155-e24cbe581732.jpeg)

**Comment by mohamedmagdy001** [comment]
Any help please

**Comment by rashmi-dixit** [comment]
Please share below details-
1. Repro steps (when do you get this error)
2. Detailed error from app insights (go to azure portal).

**Comment by tinatien** [comment]
I also got the same error on my mobile app (iOS 13.3) while it works fine on the desktop app.
The error code form app inights showed 401 error. 
Please let me know what else information I need to provide for defining the error. Thanks!

**Comment by hunaidhanfee20** [comment]
Hello @mohamedmagdy001,
Can you please try upgrading app to the latest v4.1.

Let us know if issue still persists.
Thanks

**Comment by malimal99** [comment]
What was the resolution for this?
