### ISSUE TITLE
The Company Communicator sample tab is not loading and is having issues

### ISSUE THREAD

**Issue by Mohammed-MSFT** [OfficeDev/microsoft-teams-apps-company-communicator#1510]
I have set up and run the sample after completing all configurations and deployment as per the README, but the sample tab is not loading and is encountering issues. 

I need this tab to load without any errors, as I have to implement some additional functionality on it.
![image](https://github.com/user-attachments/assets/567bdf64-5b4b-4102-961f-4f45d92b60b5)

**Errors While running**
While running the sample, some APIs are being called continuously. Due to this, the ngrok limits keep increasing, and after some time, it gives an error saying the maximum limit has been reached. As you can see from the number below TTL, it increased from 1 to 1000 within 2-4 minutes.
![image](https://github.com/user-attachments/assets/d55e6ebc-2c38-4a50-b84d-c7bbd9557cc7)
<img width="737" alt="image" src="https://github.com/user-attachments/assets/d8de5f01-5d89-4ba6-95a8-8184c30889f3">
![image](https://github.com/user-attachments/assets/a4ddc44a-4084-4e45-8f35-48bae423aca1)

Kindly provide your inputs and please update the sample to be error-free.

**Thanks!!**

**Comment by tiwariShiv7** [comment]
HI @Mohammed-MSFT, Can you please provide the below information. 
- Could you please share the repor URL, the branch name and logs for the deployed CC instance. You can find these info by follwing the below steps -
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center
Also click on logs And send the screenshot. 

<img width="367" alt="image" src="https://github.com/user-attachments/assets/2c0e5c57-04ee-44c4-9beb-338835d24691">

**Comment by Mohammed-MSFT** [comment]
Hi @tiwariShiv7 

Kindly verify the below information and please let me know if anything else is required, **Thanks !**

![Dep-Cent](https://github.com/user-attachments/assets/fd32d68d-3602-40cd-a149-265ed5706f2f)
![Log](https://github.com/user-attachments/assets/0d050ccf-e53e-4ac1-a837-786472be88de)

**Comment by tiwariShiv7** [comment]
Thanks. This is correct. Can you please share the failures log as well. 

To do this,

Navigate to the Resource group with which the instance is deployed.
Go to Application insight type resource.
Under investigate -> Click on failures.
Share the screenshot here

**Comment by Mohammed-MSFT** [comment]
Hi @tiwariShiv7 
We could not find any failure logs. Am I sharing the right screen with you? Please confirm

**Fyi** 
![image](https://github.com/user-attachments/assets/a14f352a-51e0-4c88-9518-09d67899163b)

Let us know if we can set up the call for this sample to check.

**Thanks!!**

**Comment by tiwariShiv7** [comment]
Hi @Mohammed-MSFT, We got an internal ticket poitning to this ticket from Anshul Jethwani. Please confirm if this is for same purpose. If yes we can follow it over email and close from here.

**Comment by Mohammed-MSFT** [comment]
Hi @tiwariShiv7 
Yes, that ticket is related to this issue.

**Comment by tiwariShiv7** [comment]
Thanks for the confirmation : As we are already following it on the internal platform. I am closing this ticket here. We will continue to communicate internally over this

**Comment by Mohammed-MSFT** [comment]
Hi @tiwariShiv7 
Could you please provide updates on this issue? If needed, we can set up a call to review the sample and check everything.

**Thanks !**
