### ISSUE TITLE
Delivery Failures

### ISSUE THREAD

**Issue by MNL79** [OfficeDev/microsoft-teams-apps-company-communicator#1514]
The number off users not getting posted messages from CC, is steadily increasing. At first, I was ok with 11 failures and 22,071 successful. But, the number keeps rising and now is creeping towards 50:

![image](https://github.com/user-attachments/assets/58017616-f350-49b2-a684-fa3f066ee514)

Would deleting the UserData table from DataStorage (Azure>Storage Accounts) - regenerate and fix the issue?

![image](https://github.com/user-attachments/assets/550fadf3-05f7-4def-83fb-45b10b061e60)

Just would like confirmation that deleting the UserData table, will not break anything!

Any advice greatly appreciated.

**Comment by tiwariShiv7** [comment]
Hi @MNL79 We generally do not delete the userdata table. Instead we delete the entries only for users which are not getting messages by searching the user ID. you can get the User ID for failed users from exported excel of Company communicator

**Comment by MNL79** [comment]
Hi - I can see the users where it is failing (by exporting the delivery report in the Authors app), but I have one user that got the very first messages sent to All Users - but has never received one since.

Is the 'Export detailed results' from sent messages, what you are meaning when searching for the user ID? Or is this in Azure App Services or Storage Browser?

**Comment by tiwariShiv7** [comment]
Hi @MNL79,  by the 'Export detailed results' from sent messages I mean the same delivery report in the author app that you would be reading for failures error message.

**Comment by MNL79** [comment]
> Hi @MNL79, by the 'Export detailed results' from sent messages I mean the same delivery report in the author app that you would be reading for failures error message.

That's fine - I can see that and that is what I've been looking at.

I've deleted the users that had failures or other issues from the UserData table - they have not reappeared, I'm assuming that when a new all company message is sent - the app will, at the point, resync all users and then the users deleted will appear? And hopefully will be successful this time.

**Comment by tiwariShiv7** [comment]
Correct @MNL79.

**Comment by v-jaygupta** [comment]
@MNL79 ,

Could you please update us the status of the issue?

**Comment by peddivyshnavi** [comment]
Hi @MNL79 
Could you please update us on the status of the issue?

**Comment by MNL79** [comment]
Pleased to report, that going in and deleting all the users where it failed - then worked for the next message sent. Went from 44 failures, down to a nearly perfect 1.

**Comment by peddivyshnavi** [comment]
Hi @MNL79 
We believe issue got resolved could you please let us know if there are any other queries 
if issue is resolved please let us know so we can mark ticket as complete

**Comment by MNL79** [comment]
Deletion of AAD IDs/users with failures resolved the issue. On the next message sent, the app synched users up again and was successful this time.
