### ISSUE TITLE
Some users are not receiving the messages from the app author

### ISSUE THREAD

**Issue by neidantaslopez** [OfficeDev/microsoft-teams-apps-company-communicator#1515]
Currently, we have identified two users who are not receiving the messages sent by the app author. They simply do not appear in the report (it is as if they do not exist since they do not show up even as a failed delivery).

We have tried sending messages both using the "everyone" option and directly to their chats through a group they are part of, but they still do not receive the messages. We have also tried reinstalling the app client for these users and checked their Microsoft Teams/M365 licenses, and everything is correct.

By identifying the UserId of these users in the UserData table and then searching for them in the SentNotificationData table, I can find several records with the following content:

AllSendStatusCode: 404,
DeliveryStatus: RecipientNotFound
ErrorMessage: {"error":{"code":"ConversationNotFound","message":"Conversation not found."}}
StatusCode: 404

I have seen some other issues recorded here on this subject, but in none of them did I find any definitive answer on the matter.

In one of these issues (#1467), a user reported solving an apparently similar problem by removing the problematic users' records from the UserData table. However, I have not tried this yet as I would like to understand if this will really solve the problem.

Why does this problem occur and how can I fix it? Thank you.

**Comment by tiwariShiv7** [comment]
Hey @neidantaslopez, Thanks for reaching out. Yes "removing the problematic users' records from the UserData table" should ideally work. There is possibility that users might have deleted the chat previously and that may cause this issue.

**Comment by MNL79** [comment]
Please can you provide guidance on how to remove a problematic user record from the UserData table?

**Comment by MNL79** [comment]
Once a user that is having issues is deleted from the UserData table - I assume that they will then reappear on the next user sync with the tenant?

**Comment by MNL79** [comment]
Been a couple of days, user hasn't reappeared - is this then done, once the next message is sent out from the Author app? Does it then re-sync all users at that stage??
