### ISSUE TITLE
Company Communicator Doesn't Send Messages to any users

### ISSUE THREAD

**Issue by fsausa** [OfficeDev/microsoft-teams-apps-company-communicator#1516]
Hi,
i updated Company Communicator App, but when i try to send a test message any user is retrieved from the Team and message stucks in queued. 
I already checked app permissions and it seems configure properly. 
Could you please help me to check the configuration ?
![communicator](https://github.com/user-attachments/assets/00f42f14-b924-48aa-8f7e-2ab437c735bf)
![Screenshot 2024-08-06 162546](https://github.com/user-attachments/assets/01795ec1-cd86-4ac0-b43c-c697b111fed2)

Many Thanks

**Comment by tiwariShiv7** [comment]
Hey @fsausa , Thanks for reaching out. Please share the failures screenshot to help us underastand what could have been wrong. 
Also how many users are you trying to send messages to ? 
For failures : 

Navigate to the Resource group with which the instance is deployed.
Go to Application insight type resource.
Under investigate -> Click on failures.
Share the screenshot here

**Comment by fsausa** [comment]
Hi @tiwariShiv7, 
here you can see the Failures.
I tried to send a message in a Team where Communicator App is installed with 5 people inside.
![image](https://github.com/user-attachments/assets/26608d0d-7758-4bd5-af34-01ea2da35d37)

**Comment by victorsimonlee** [comment]
![image](https://github.com/user-attachments/assets/49685144-d53e-45e1-842f-c0820c2a54f7)

**Comment by tiwariShiv7** [comment]
Hi @fsausa, 
 Thanks for your patience. We would like to understand this case a lil.
Just wanted to understand,

What was the previous version of the app that was getting used. 
Please reverify all the fields are in accordance with [Migration Guide to 5.x ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version)

**Comment by fsausa** [comment]
Hi @tiwariShiv7 ,
sorry for the delay.
When i saw that application after the migration didn't work, i tried to redeploy all component from scratch, so i'm pretty sure that the fields should be correct.
Do you have any suggestions to solve this issue ?
