### ISSUE TITLE
When opening a new message, the message "an error occurred while accessing this application" appears

### ISSUE THREAD

**Issue by dbove-bz** [OfficeDev/microsoft-teams-apps-company-communicator#1517]
When opening a new message, the message "an error occurred while accessing this application" appears:

![image](https://github.com/user-attachments/assets/269e9529-01ba-493a-b63c-01a96d121a68)

This problem occurs with some users

**Comment by dbove-bz** [comment]
Logs:

![image](https://github.com/user-attachments/assets/42ba2fa0-f9b3-4f40-940b-04aa7a854950)

![image](https://github.com/user-attachments/assets/04709748-c233-4194-a36e-86e9a0cbc34a)

![image](https://github.com/user-attachments/assets/72755654-1f1a-4232-8384-52f310f30bd9)

**Comment by tiwariShiv7** [comment]
Hi @dbove-bz , Can you please reverify the "AuthorizedCreatorUpns" and "AuthorizedDeleteUpns" are updated correctly with users' name who is trying to access the Company communicator app ? 

To check this 
1. Open Azure Portal 
2. Go to resource group your CC app is deployed with 
3. Navigate to web app (The resource of type App service in the Resources' list)
4. Expand setting and click on Environment variables. 
5. Here you can search for both  "AuthorizedCreatorUpns" and "AuthorizedDeleteUpns"

**Comment by dbove-bz** [comment]
@tiwariShiv7,
 
I checked and people are registered there. I disabled this check using the "DisableCreatorUpnCheck" variable and the problem persists.

This UPN check is also done on the first page, the problem occurs when you click on the new message button.

**Comment by tiwariShiv7** [comment]
Hi @dbove-bz ,  Thanks for your patience. We would like to understand this case a lil.
Just wanted to understand,

If this is the fresh case of deployment or the earlier message were successful.
if existing deployment has suddenly started to give error. Please inform if there is any recent change with Classic Teams to new Teams/ Upgrade in CC version / Any secret keys related update we made.

**Comment by dbove-bz** [comment]
Hi, @tiwariShiv7.

It's a new installation.


It only works with my username

My user:
![image](https://github.com/user-attachments/assets/7bae75ef-16c9-4469-add5-bcb582ffd4c6)

other users
![image](https://github.com/user-attachments/assets/450f9d7e-1871-4900-8b20-31181b9c961c)

**Comment by tiwariShiv7** [comment]
please make sure that the email id you are using to access the app is added in AuthorizedCreatorUpns, AuthorizedDeleteUpns. you can recheck the same from

1. Go to resource group where the app is deployed.
2. Navigation to the Resource of type app service.
3. Click settings and search for AuthorizedCreatorUpns, AuthorizedDeleteUpns this should be semicolon seperated e-mail ids who are having access to author app.
4. You can add email id here if you want access

<img width="848" alt="image" src="https://github.com/user-attachments/assets/c280cd22-48f3-45e3-aa2c-8e173e78bf64">

**Comment by dbove-bz** [comment]
Yes, the emails have been added.

When I remove the email, the person cannot access the first page.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peddivyshnavi** [comment]
Hi @dbove-bz 
Could you please verify whether secrets of app registration got expired.
if that's the case please follow the steps:
Please cross verify once again w.r.t secrets renewal with the below steps.
Go to Azure Portal
Go to App registration
Create a new secret value for app registration and grab secret value. Here is the reference.
![image](https://github.com/user-attachments/assets/304b5b7f-fe7c-488d-aab6-b5f0719e5c73)

Then go to resource group. Select key vault from list of resources.
Click on secrets under object section.
![image](https://github.com/user-attachments/assets/b5a23593-f051-4813-a2c0-77c25af0cadf)
If the secrets are not visible, Go to Access Policy--> Click on Create
![image](https://github.com/user-attachments/assets/8520bca6-6fc3-4158-8fc6-39a2ff5c821a)
Select Key, secret and certificate management
![image](https://github.com/user-attachments/assets/10e1444b-cc8a-4774-b2e4-a01c18d32fb9)

Give the Id through which one can view the secrets
![image](https://github.com/user-attachments/assets/e8a75f28-2404-4fbc-9542-154d6180a1c6)

3rd step is optional
Go for Review+Create
Then go to Secrets. Open author/user/graph app password
Click new version
![image](https://github.com/user-attachments/assets/c36e1386-40da-4b32-af3a-69abd3930909)

Grab the new secret identifier
![image](https://github.com/user-attachments/assets/1c461351-b280-4e44-b78f-2e8cfa04e8aa)

Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.
![image](https://github.com/user-attachments/assets/262f71e7-170d-4972-9bc9-8dd8777ae053)

Follow the same procedure for the user app password and graph app password updating.
For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference
![image](https://github.com/user-attachments/assets/031dc052-d6a8-421d-b8d2-444d7494fa5d)
