### ISSUE TITLE
failed to prepare the message for sending. the orchestrator function 'syncrecipientsorchestrator" failed

### ISSUE THREAD

**Issue by Nadeem-hussain-mafgs** [OfficeDev/microsoft-teams-apps-company-communicator#1518]
![CC](https://github.com/user-attachments/assets/b68e8a16-e4ae-4d6a-92d1-bf558aa5e088)

to prepare the message for sending. the orchestrator function 'syncrecipientsorchestrator" failed

Getting this error while trying to send the message.
Requesting your immediate support here

**Comment by tiwariShiv7** [comment]
Hi @Nadeem-hussain-mafgs , Please send the failures screnshot. Also please help us with details when it is occuring ? Are the messages getting draft ? 

To check failures 

Navigate to the Resource group with which the instance is deployed.
Go to Application insight type resource.
Under investigate -> Click on failures.
Share the screenshot here

**Comment by Nadeem-hussain-mafgs** [comment]
![1518](https://github.com/user-attachments/assets/1418a532-828d-42a3-bdfe-19216eb53785)

Thanks Tivari, Attached is the screenshot

**Comment by Nadeem-hussain-mafgs** [comment]
Dear team
Do we have any feedback here?

**Comment by victorsimonlee** [comment]
I have the same issue after upgrading to latest version. I will open a new ticket as well.

**Comment by Nadeem-hussain-mafgs** [comment]
Dear Tiwari

Do we have any updates here ?

**Comment by tiwariShiv7** [comment]
Hi @Nadeem-hussain-mafgs, Thanks for your patience. We would like to understand this case a lil. 
Just wanted to understand, 
1. If this is the fresh case of deployment or the earlier message were successful. 
2. if existing deployment has suddenly started to give error. Please inform if there is any recent change with Classic Teams to new Teams/ Upgrade in CC version / Any secret keys related update we made.

**Comment by Nadeem-hussain-mafgs** [comment]
Hi Tiwari

Please find the responses below

1. It was deployed more than a year back and all the earlier messages are successful.
2. No, there is no recent change

May you please schedule a call to connect further.

Regards
Nadeem

**Comment by tiwariShiv7** [comment]
Hi @Nadeem-hussain-mafgs , Please recheck all the 3 apps used for this deployment. This might be the case where secrets are expired or updated recently .

**Comment by v-jaygupta** [comment]
@Nadeem-hussain-mafgs ,
As per our internal discussion last week, closing this issue as the app is working fine after updating the renewing and updating the secrets at various places.
