### ISSUE TITLE
TeamData table - only shows 2 Teams

### ISSUE THREAD

**Issue by MNL79** [OfficeDev/microsoft-teams-apps-company-communicator#1519]
Hi,

When sending via the Author app - only 2 Teams are available to send to:

![image](https://github.com/user-attachments/assets/faa07722-c2bb-423a-8598-4768198ca0bf)

On checking the TeamData table - it does only show 2 teams (which are the two above):

![image](https://github.com/user-attachments/assets/3289af42-1fea-4802-b46c-0988b5995d40)

The first team was there from the installation of the app - the 2nd team has been added at the end of July. No action was taken to add this - so not sure how it added itself.

How do you add more teams or get it to sync up to display all Teams?

**Comment by tiwariShiv7** [comment]
Hi @MNL79 m The Team gets added when you add Company Communicator Author/ User app to a team by selecting the app and clicking on add to team. In case you do not want it you can simply 

GO to Teams Apps -> Click on Manage Apps -> Search for Company Communicator instances and expand it -> You will be able to see the Teams chat it is added to and will also get the option to delete it.

**Comment by MNL79** [comment]
Thanks for the reply - I can see how to do that, it is more the Teams that show when composing a new message in the app itself. I'll just use the M365 Group option instead.

**Comment by tiwariShiv7** [comment]
sure. We are closing this ticket with the answered label
