### ISSUE TITLE
Cannot send the messages via Microsoft Teams Company Communicator.

### ISSUE THREAD

**Issue by ARV-IT-Github** [OfficeDev/microsoft-teams-apps-company-communicator#1520]
I use the company communicator app on Microsoft team to broadcast the announcement to users.
However, I am no longer able to transmit the announcement to users after upgrading from v4 to v5.

<img width="1032" alt="CompanyCom_Queued" src="https://github.com/user-attachments/assets/d687980d-badd-48bb-a4ab-3af6d3a23c19">

**Comment by victorsimonlee** [comment]
Hi @ARV-IT-Github  can you see an error message when you click on the three dots (...) menu and open the message details?

**Comment by tiwariShiv7** [comment]
Hi @ARV-IT-Github , Please recheck the fields are updated correctly or not ? 

Also, when upgrading from v4 to the latest version you need to go through step wise upgrade. This means, you have to first follow [V4 to V5 ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5)then [V5 to latest version](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version) guides. Please ensure all the fields generated out of this are correct.

**Comment by ARV-IT-Github** [comment]
> Hi @ARV-IT-Github , Please recheck the fields are updated correctly or not ?
> 
> Also, when upgrading from v4 to the latest version you need to go through step wise upgrade. This means, you have to first follow [V4 to V5 ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5)then [V5 to latest version](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version) guides. Please ensure all the fields generated out of this are correct.

I think i field all attributes correctly.

**Comment by victorsimonlee** [comment]
@ARV-IT-Github  I had a similar issue recently, and the problem was the Key Vault connection on the functions were showing an error... In my case, the Key Vault secrets had expired. 

So, I had to generate new secrets and update the Key Vault connection strings in each of the app functions > environment settings.

good luck

**Comment by tiwariShiv7** [comment]
Hi @victorsimonlee , Can you please reverify the [Step 3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) and [Step 4 ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) of deployment Guide ?

**Comment by peddivyshnavi** [comment]
@victorsimonlee 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@victorsimonlee 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by peddivyshnavi** [comment]
@victorsimonlee 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed
