### ISSUE TITLE
Company Communicator stop working after keys were renew.  

### ISSUE THREAD

**Issue by RicCan1969** [OfficeDev/microsoft-teams-apps-company-communicator#1522]
We are having a problem with Company Communicator; it stopped working when we try to access from a Teams Channel.  We need help to identify the problem.  Please let me know if you need any other information.  Screens attached.  

<img width="753" alt="GitHub1" src="https://github.com/user-attachments/assets/ab7ebc0d-ca1c-48b5-a510-537e32d25a89">
<img width="642" alt="GitHub2" src="https://github.com/user-attachments/assets/0ed8d22d-1874-48b8-afa8-440237da24f8">
<img width="297" alt="GitHub3" src="https://github.com/user-attachments/assets/4f5463af-ac5f-4f9a-ada9-3a09361deca5">

**Comment by tiwariShiv7** [comment]
HI @RicCan1969 , Thanks for reaching out. Please help us with the Teams you are using. 
- Is it classic Teams or new Teams? 
- Is this a fresh deployment or we recently updated Company Communicator? 
- Did we make any other changes recently ?

**Comment by RicCan1969** [comment]
Hello,
Thaks for getting back to me.

  *   Is it classic Teams or new Teams?
     *   It is the same behavior on both, we were on Classic a couple of weeks ago, we are now on New Teams, Same behavior.
  *   Is this a fresh deployment or we recently updated Company Communicator?
     *   No, this tool was deployed a couple of years ago.  Keys expired and renewed but no luck to get it to work.   Getting following error when trying to open CC.
     *   ***@***.***
  *   Did we make any other changes recently ?
     *   We upgraded the application to this version.
     *   ***@***.***
Please let me know if you have any other information.

Thanks,

Ricardo A. Cantoral
Lead Infrastructure Core Services Specialist
New York Power Authority
123 Main Street White Plains, New York 10601
Office (914) 681-6419 | Mobile (914) 346-4049
***@***.******@***.***>    www.nypa.gov<http://www.nypa.gov/>
[A picture containing text  Description automatically generated]

**Comment by victorsimonlee** [comment]
@RicCan1969 did you update the key vault references in the app service and functions settings? 

When I had to renew my keys a while ago, the app stopped working until I updated the key vault references in the app settings.

**Comment by tiwariShiv7** [comment]
Hi @RicCan1969 , Some of the screenshot / Details you have given is looking encrypted to me. Please paste images directly here in the chat so it will start showing up. 

Instead of these. Please verify that you have updated key vault correctly for new secrets, only instances with the new secrets are enabled in key vault and Lastly the new connection strings are updated in Function apps and app service environment varriables under settings

**Comment by RicCan1969** [comment]
***@***.***

Thanks,

Ricardo A. Cantoral
Lead Infrastructure Core Services Specialist
New York Power Authority
123 Main Street White Plains, New York 10601
Office (914) 681-6419 | Mobile (914) 346-4049
***@***.******@***.***>    www.nypa.gov<http://www.nypa.gov/>
[A picture containing text  Description automatically generated]

**Comment by tiwariShiv7** [comment]
Closing this issue. Considering the response.

**Comment by RicCan1969** [comment]
Why is this ticket being closed?  I did not get an answer.

Thanks,

Ricardo A. Cantoral
Lead Infrastructure Core Services Specialist
New York Power Authority
123 Main Street White Plains, New York 10601
Office (914) 681-6419 | Mobile (914) 346-4049
***@***.******@***.***>    www.nypa.gov<http://www.nypa.gov/>
[A picture containing text  Description automatically generated]
