### ISSUE TITLE
Urgent need for help: Error after a few seconds of loading 

### ISSUE THREAD

**Issue by Altinio** [OfficeDev/microsoft-teams-apps-company-communicator#1523]
We get this error when clicking the author app tab in the Team and trying to create and send a new message. It appears to load for a brief second, then errors out.  
The screen shows the following after a short loading time:  
Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists. @tiwariShiv7

**Comment by victorsimonlee** [comment]
I had a similar issue not long ago and the problem was that some of the key secrets (used by the app's connection strings) had expired. I generated new secrets and the issue was gone.

May be worth checking it out while you wait for a CC dev to jump in.

Cheers

**Comment by tiwariShiv7** [comment]
Hi @Altinio Thanks to reach out to us. @victorsimonlee Thanks for your intent to help. 
- Yes please check if secrets are correct and active and we have used Secrets value correctly. 
- If you have upgraded recently  please check if it meets [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix) changes. 
- If it is a new deployment case, Also revalidate [Set Up Auth ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) and [Add permissions ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) step

**Comment by KatePang** [comment]
@victorsimonlee are you able to share the steps you have taken?

**Comment by Altinio** [comment]
![image](https://github.com/user-attachments/assets/98010b4c-1f49-4ee9-be9a-ff877f7e1428)
![image (1)](https://github.com/user-attachments/assets/109e78d7-62cc-4e0e-81d0-759529d9698e)
![image (2)](https://github.com/user-attachments/assets/98c6e572-8875-462c-b13a-48b206400153)
![image (3)](https://github.com/user-attachments/assets/058dac47-8941-4fe8-aeaa-d5c2691bcd04)

I have now checked every secret, and everything seems to be alright. I have also already followed the steps to fix the authentication issue. I really don’t know why it is not working. Do you have any other ideas why it might not be working, and could you provide me with some guidelines on how to fix it properly?

**Comment by tiwariShiv7** [comment]
Hi @Altinio , 
Could you please share the error details and the supporting screenshot of error from application insights resource from the deployed resource group to investigate further on this issue.

Go to resource group where CC app is deployed --> Go to Application insight type resource -->Under investigate section Click on failures --> share the screenshot and stack trace for Top 3 response codes.

**Comment by Altinio** [comment]
![Erorr](https://github.com/user-attachments/assets/41307a75-7171-4bfd-8a6f-3840a8ba8405)
![Erorr 2](https://github.com/user-attachments/assets/6d24baa8-acd2-4048-ba8b-ebcb984c3d22)
![Erorr 3](https://github.com/user-attachments/assets/e70aa413-2c4f-40ea-8f32-0436d3ba123e)

This is what I got from the failure list. I hope I did it right. If you need more information, please let me know so we can fix this problem as soon as possible. Thank you in advance.

**Comment by Altinio** [comment]
![image (4)](https://github.com/user-attachments/assets/22e53cd6-3a52-4fec-aebc-b877fbd38de3)
![image (5)](https://github.com/user-attachments/assets/7864f7b6-4c78-451e-a8f2-a24343b08365)
Do I need to set the redirect URL only in one application, and if so, in which one? How does it work when you want to test the change? Is restarting the app service sufficient?

**Comment by tiwariShiv7** [comment]
Hey @Altinio , Yes you need to set Redirect URI to only one app registration. 
The correct app to do this setup is the one created for single tenant. To identify the correct App please check the supported account type in overview section of the app. It should be "My Organization only" rest 2 apps will be having "Multiple Organization". 

<img width="625" alt="image" src="https://github.com/user-attachments/assets/f91aa7ba-b722-4f9d-8e87-b757b60072bc">

**Comment by Altinio** [comment]
![image](https://github.com/user-attachments/assets/65a20c49-cbe5-4480-9a9f-b21ec50023ba)

![image](https://github.com/user-attachments/assets/9fa2e3f4-6653-40ec-a019-55f20f10bf2c)
 Did it right here but still nothing changed...

**Comment by tiwariShiv7** [comment]
Hey @Altinio , I believe you are missing Bullet 4 Of [Step 3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) Of Expose An API. Please recheck [Step 3 ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication)AND [step 4 ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) of the deployment guide completely

**Comment by Altinio** [comment]
![image](https://github.com/user-attachments/assets/7fc7923e-1fc5-40c5-a089-f29d22952b2e)
![image](https://github.com/user-attachments/assets/d5d07a8c-683f-4635-bc42-8bc31065d6dd)
![image](https://github.com/user-attachments/assets/2f92a431-38b6-4dbb-a075-c35f8382bc88)
![image](https://github.com/user-attachments/assets/9364170b-0a2f-444f-9691-6e78b73ae066)
I have added everything as you said, but it's still not working. Is there any possibility that we could have a call or something like that and try to solve the problem in a live chat? It's very important that I fix this problem as soon as possible****

**Comment by peddivyshnavi** [comment]
@Altinio 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@Altinio 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
marking this ticket as closed
