### ISSUE TITLE
Application Deployment Issue - Not creating tabs

### ISSUE THREAD

**Issue by Electric-Velcro** [OfficeDev/microsoft-teams-apps-company-communicator#1524]
Receiving this when trying to add the Authors app to teams:

![image](https://github.com/user-attachments/assets/3ffce932-8eeb-4ae8-bb59-bf15bfd65d33)

It does not allow me to save and add/create the application.

**Comment by tiwariShiv7** [comment]
Hi @Electric-Velcro, Please try in incognito / Inprivate windows of a Browser to check if it is a cache issue. Let us know if this works .

**Comment by v-jaygupta** [comment]
@Electric-Velcro ,
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
hi @Electric-Velcro 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@Electric-Velcro 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by peddivyshnavi** [comment]
@Electric-Velcro 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed
