### ISSUE TITLE
Company Communicator Apps (Unable to Approve)

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1525]
I have uploaded both the Company Communicator user and Company Communicator apps to Teams.  When attempting to install them with my Teams client, I am to search and "Request" the apps.

I do see these Requests in the Teams Admin console.  However, I do not see the option to Approve my requests despite making both applications available to Everyone in the organization.

**Comment by tiwariShiv7** [comment]
Hi @khenry1111, Thanks for reaching out. Please Check with your organization / IT team if there is any other restrictions for the the Teams apps. Meanwhile we will also discuss this internally and will get back to you if there is anything else.

**Comment by khenry1111** [comment]
Update: No changes were made but today I am able to both the Company Communicator and Company Communicator apps to Teams.   HOWEVER, I now see a new error immediately when clicking the CC Author Tab in Teams:  "Sorry, you do not have permission to access this page. Please contact your administrator to be granted permission."

**Comment by tiwariShiv7** [comment]
Hi @khenry1111 , please make sure that the email id you are using to access the app is added in AuthorizedCreatorUpns, AuthorizedDeleteUpns. you can recheck the same from 
1. Go to resource group where the app is deployed. 
2. Navigation to the Resource of type app service.
3. Click settings and search for  AuthorizedCreatorUpns, AuthorizedDeleteUpns this should be semicolon seperated e-mail ids who are having access to author app. 
4. You can add email id here if you want access 
<img width="953" alt="image" src="https://github.com/user-attachments/assets/7ab6fbe2-0216-4c29-91f6-ceebbfd1943c">

**Comment by khenry1111** [comment]
This worked, thank you.

**Comment by tiwariShiv7** [comment]
Thanks for the confirmation Closing this issue
