### ISSUE TITLE
Encounter error when click on new message

### ISSUE THREAD

**Issue by BernardHyh** [OfficeDev/microsoft-teams-apps-company-communicator#1527]
Encounter error when trying to create new message. This is an existing setup that is working all along.

[
![IMG_7234](https://github.com/user-attachments/assets/da1fd845-92f0-4eb6-83ba-d9092f7bbc62)
![IMG_7235](https://github.com/user-attachments/assets/bf19cc78-06bd-4873-9bc8-aa06424a1092)
](url)

**Comment by BernardHyh** [comment]
In addition, I am

**Comment by BernardHyh** [comment]
I am currently running on release 5.5.2 with the auth issue fix already implemented since the upgrade in May.

**Comment by BernardHyh** [comment]
I am currently running on version release 5.5.2 with the auth issue fix already implemented since the upgrade in May.

**Comment by BernardHyh** [comment]
Test

**Comment by tiwariShiv7** [comment]
Hi @BernardHyh , THanks for reaching out to us. can you please help us with the screenshot of failures.
To do this,

Navigate to the Resource group with which the instance is deployed.
Go to Application insight type resource.
Under investigate -> Click on failures.
Share the screenshot here

Please inform us in any case

**Comment by v-jaygupta** [comment]
@BernardHyh ,
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
Hi @BernardHyh 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@BernardHyh 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete
