### ISSUE TITLE
Message Send Dropdown

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1529]
I am able to send to specific groups in the Authors application.  However, I am unable to send to either "Send to the General channel of specific teams" or "Send in chat to members of the following teams" options.  Nothing populates in the dropdown including when I try to type in Teams.

![image](https://github.com/user-attachments/assets/b48ec2bb-ca6b-476b-82f3-bae98b07aa82)

**Comment by tiwariShiv7** [comment]
Hi @khenry1111 , For these options please add the user app to the Teams channel you wanna send message to, once done Teams with user app installed will be visible in the dropdown. 

After adding user app to Teams 
Go to Apps -> Manage apps / Built for org -> select Company Communicator User App -> Click on add to a Team -> Select the Team you want to send message to -> Click on add/ set up 

Once done Team channel would be visible in the dropdown of Author app to select. 
Let me know if this works

**Comment by khenry1111** [comment]
Hello,

I followed the instructions, but unfortunately the Team(s) are still not populating in the dropdown.

**Comment by tiwariShiv7** [comment]
Thanks @khenry1111, Can you please send us the screenshot of User App dropdown and see for which Teams it got added. 

Also please check Failure to check failures : 

1. 1. Navigate to the Resource group with which the instance is deployed.
2. Go to Application insight type resource.
3. Under investigate -> Click on failures.
4. Share the screenshot here

Please inform us in any case

**Comment by khenry1111** [comment]
I was able to get this to work.  The issue can be closed.

**Comment by tiwariShiv7** [comment]
Thanks @khenry1111
