### ISSUE TITLE
The subscription is not registered to use namespace 'Microsoft.AlertsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code: MissingSubscriptionRegistration)

### ISSUE THREAD

**Issue by sivanikakuru09** [OfficeDev/microsoft-teams-apps-company-communicator#1530]
What is the resolution of this error?
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/478

The subscription is not registered to use namespace 'Microsoft.AlertsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code: MissingSubscriptionRegistration)

**Comment by tiwariShiv7** [comment]
Hi @sivanikakuru09 , Thanks for reaching out. Please help up with
1. Are we trying to set the company Communicator locally ?
2. Please share the repo URL and branch we are using here. To do this 
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select Web App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

**Comment by sivanikakuru09** [comment]
Hi Microsoft.AlertsManagement is resolved by adding the subscription in Resource providers

**Comment by tiwariShiv7** [comment]
Thanks for the confirmation. I am closing this ticket now.
