### ISSUE TITLE
Can open Company Communicator

### ISSUE THREAD

**Issue by Nicto-dev** [OfficeDev/microsoft-teams-apps-company-communicator#1531]
Our company has installed all portions of Company Communicator.  When I try to open program in a Team I get the error Sorry, an error occurred while trying to access this service.

We worked with a MS engineer who help verify that our Azure services are turned on for authentication.

Anyone seen this issue before and how to fix this?

We are in a GCC tenant.

**Comment by tiwariShiv7** [comment]
Hi @Nicto-dev , Please refer to [Auth Issue fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)to solve this issue

**Comment by tiwariShiv7** [comment]
Hi @Nicto-dev , Please Review, [step 4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-for-GCC#step-4-set-up-authentication) and [step 5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-for-GCC#step-5-add-permissions-to-your-app)

- Navigate to the Resource group with which the instance is deployed.
- Go to Application insight type resource.
- Under investigate -> Click on failures.
- Share the screenshot here

Please inform us in any case

**Comment by Nicto-dev** [comment]
I am waiting for feedback from my Azure Admin team as to steps 4 and 5.

**Comment by peddivyshnavi** [comment]
Hi @Nicto-dev 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@Nicto-dev 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by Nicto-dev** [comment]
I am meeting with our Azure Team today to have them look at the recommended solution.  i will update after the meeting.

**Comment by Nicto-dev** [comment]
ran through steps 4 and 5 again with the Azure team.  There seems to be some progress, i dont get the error screen immediately, but when i try clicking on any options to create a message it then give e the error.  I will be working with the team again this week when they have time to continue looking at our options.

**Comment by peddivyshnavi** [comment]
@Nicto-dev
Could you please update us on the status of the issue?

**Comment by Nicto-dev** [comment]
No further updates since my last post.  The Team i work with are only able to meet once a week.  Im working on setting up another meeting to continue working on the issue.

**Comment by Nicto-dev** [comment]
Currently the Azure Admin working on this issue for our group is off until next Monday 9-16.  we have another meeting scheduled for the 17th to continue working.

**Comment by peddivyshnavi** [comment]
Could you please update us on the status of the issue?

**Comment by Nicto-dev** [comment]
Next update wont be until Tuesday when our Azure admin returns.

**Comment by peddivyshnavi** [comment]
@Nicto-dev
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@Nicto-dev
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
marking this ticket as closed as we didnt received any responce
