### ISSUE TITLE
Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

### ISSUE THREAD

**Issue by sivanikakuru09** [OfficeDev/microsoft-teams-apps-company-communicator#1532]
When submitting new message showing up with screen for few seconds and then it throws this error 

Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

**Comment by tiwariShiv7** [comment]
Hi @sivanikakuru09, please send us the failure screenshot of below 

1. Navigate to the Resource group with which the instance is deployed.
2. Go to Application insight type resource.
3. Under investigate -> Click on failures.
4. Share the screenshot here

Please inform us in any case

**Comment by peddivyshnavi** [comment]
Hi @sivanikakuru09 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@sivanikakuru09 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by peddivyshnavi** [comment]
@sivanikakuru09 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed
