### ISSUE TITLE
Company Communicator User app deployment

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1534]
I am looking for a mechanism to perform an automated deployment of the Company Communicator User app out to specific groups within the organization.

Is there way to achieve this through Teams admin or some other mechanism?

**Comment by tiwariShiv7** [comment]
Hi @khenry1111 , Yes There is an option to add user app to specific group. To do this 
1. Install User app. 
2. Create a Teams channel with the people or Group you want to trigger user app installation to. 
3. Navigate to installed user app from apps -> manage apps in Teams. 
4. Click on the app and Select an option of Add to a Team. 
5. Select created / desired Teams channel from Dropdown.
6. Click on set up / Submit button. 

This will trigger user app installation to the Team members added to the channel.

**Comment by khenry1111** [comment]
The instructions worked and this was successful on the test performed. 

The follow up question is what access is required to perform this?  To clarify, can any employee associate the Company Communicator App with any Team which would then result in the Company Communicator app being installed on other employee systems?

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
No, only the employee associated with Company Communicator App will have CC installed. For remaining users or other employee systems CC won't be installed.

**Comment by khenry1111** [comment]
Thank you.
