### ISSUE TITLE
Functions Sync Issue while upgrading to v5 and App services

### ISSUE THREAD

**Issue by bbarona** [OfficeDev/microsoft-teams-apps-company-communicator#1535]
Good afternoon, I also have the same problem and I have followed the steps as indicated and the same thing happens. Could you help me too, thank you (Error building configuration in an external startup class.)
image

Microsoft.Azure.WebJobs.Script: Error building configuration in an external startup class. Microsoft.Azure.WebJobs.Script: One or more loaded extensions do not meet the minimum requirements. For more information see https://aka.ms/func-min-extension-versions. ExtensionStartupType ServiceBusWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.2.1.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.ServiceBus to 4.2.1 or later. .

Tried to Sync the function apps, below is the error message.

Using Msbuild from 'C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin'.
C:\home\site\repository\Source\CompanyCommunicator\Microsoft.Teams.Apps.CompanyCommunicator.csproj : error : Version 3.1.426 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.

![image](https://github.com/user-attachments/assets/b5486791-b1c4-463d-b021-508e77ced6c5)

**Comment by peddivyshnavi** [comment]
Hi @bbarona 

Thanks for reaching out to us.
Could you Please confirm us with the following.

- Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select function App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

And please share the screenshots of all three Function Apps and Deployment Center

**Comment by peddivyshnavi** [comment]
Hi @bbarona 
Could you please update us on the status of the issue?

**Comment by bbarona** [comment]
Ofcourse,

App Service > Centro de implementación > Configuración

![image](https://github.com/user-attachments/assets/ec592a7f-54ab-4021-be51-f419cd59a23a)

App Service > Centro de implementación > Registros
![image](https://github.com/user-attachments/assets/dbb73594-4a5b-4727-998f-eff780baa80f)



3 Function Apps 

![image](https://github.com/user-attachments/assets/03a78d34-7a13-4e29-abe3-0f1703fee3f4)

Function Apps > MTCCOM-data-function > Centro de implementación > Configuración
![image](https://github.com/user-attachments/assets/2dcb1346-3fbd-4117-8e11-e36a7e6d10f8)





Function Apps > MTCCOM-function > Centro de implementación > Configuración


![image](https://github.com/user-attachments/assets/6c288371-f218-4663-8a88-cef746315e44)



Function Apps > MTCCOM-prep-function > Centro de implementación > Configuración

![image](https://github.com/user-attachments/assets/6bf06787-7d1f-4051-8990-2c22fd30456f)

**Comment by peddivyshnavi** [comment]
Hi @bbarona 
From the screenshot provided we see you are trying upgrade CC could you please follow [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide)

**Comment by bbarona** [comment]
In a few minutes, I will conduct the session with the client to gather evidence of the process carried out

**Comment by bbarona** [comment]
[Evicencias de implementacion actualizacion company.pdf](https://github.com/user-attachments/files/16822256/Evicencias.de.implementacion.actualizacion.company.pdf)
The update process has been successfully completed. The parameters and settings have been verified again. Additionally, the synchronization of the functions in the App Services was successfully performed. However, upon executing the synchronization, we encountered the attached error.
![image](https://github.com/user-attachments/assets/ac97a182-d162-4531-8d52-0f9dcb33381d)
![image](https://github.com/user-attachments/assets/e5ee73d4-a8e7-4536-9405-2931e4d0c629)

**Comment by peddivyshnavi** [comment]
Hi @bbarona 
I would suggest please disconnect the repo From Deployment center of App service then wait for 20-30 mins All logs will get cleared. Once there is nothing in the logs Please select External Git -> Enter Repo Name and Branch name as 'main'. Click save and Sync it one more time.

Refer [Troubleshooting guide Point #5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#5-app-service-sync-throws-npm-error)

**Comment by bbarona** [comment]
Hi @peddivyshnavi 

we have already followed the process you recommended several times. This issue is becoming critical for my client. Could we possibly discuss this in a session? Please reach out to me at [Brayanb@visionsoftware.com.co](mailto:Brayanb@visionsoftware.com.co) so we can schedule a meeting. Thank you.

**Comment by peddivyshnavi** [comment]
Started discussing internally

**Comment by peddivyshnavi** [comment]
We were trying to reproduce this issue from our end to troubleshoot so that we can fix this issue we will update with resolution you as soon as possible

**Comment by peddivyshnavi** [comment]
Hi @bbarona 
We tried reproducing issue with all possibilities from our end but we were unable to reproduce could you please go for redeployment of Company Communicator

**Comment by peddivyshnavi** [comment]
@bbarona 
Could you please update us on the status of the issue?

**Comment by bbarona** [comment]
Good morning @peddivyshnavi , on Monday, September 23, we will implement the solution from scratch.

**Comment by peddivyshnavi** [comment]
Thanks, @bbarona. Please inform us if you encounter any further issues.

**Comment by peddivyshnavi** [comment]
Thanks, @bbarona. Could You Please create a new issue if you face any issues while deploying CC.
