### ISSUE TITLE
Unable to see the exporting detailed results

### ISSUE THREAD

**Issue by CaioCPSilva** [OfficeDev/microsoft-teams-apps-company-communicator#1536]
When i click the Export detailed results button of the sent messages nothing happens.
How can i check the logs of this operation to tshoot this issue?

**Comment by v-jaygupta** [comment]
Hi @CaioCPSilva ,
Could you please share the error details and the supporting screenshot of error from application insights resource from the deployed resource group to investigate further on this issue.

Go to resource group where CC app is deployed --> Go to Application insight type resource -->Under investigate section Click on failures --> share the screenshot and stack trace for Top 3 response codes.

**Comment by peddivyshnavi** [comment]
Hi @CaioCPSilva 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by CaioCPSilva** [comment]
Hi @peddivyshnavi ,
Sorry for the delay.

![image](https://github.com/user-attachments/assets/db93faa7-7a98-46d5-9efa-966075ebb5f6)

![image](https://github.com/user-attachments/assets/093d04a8-68ca-47b4-be24-4e49244a3a34)

**Comment by peddivyshnavi** [comment]
Hi @CaioCPSilva 
Could you please verify [Graph app](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) were added correctly 
and please share screenshot of the graph API permissions. Here is the reference.
![image](https://github.com/user-attachments/assets/acb57c24-44b4-4edf-9919-12782536f5ab)

**Comment by CaioCPSilva** [comment]
> Hi @CaioCPSilva Could you please verify [Graph app](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) were added correctly and please share screenshot of the graph API permissions. Here is the reference. ![image](https://private-user-images.githubusercontent.com/177909774/363703021-acb57c24-44b4-4edf-9919-12782536f5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjYwMTIsIm5iZiI6MTcyNTMyNTcxMiwicGF0aCI6Ii8xNzc5MDk3NzQvMzYzNzAzMDIxLWFjYjU3YzI0LTQ0YjQtNGVkZi05OTE5LTEyNzgyNTM2ZjVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwMTA4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDcxMjY2ZGVmYTNjYTczNGNkNTkyMmZhMzI5ODY3MjkzZWMwODNjZDUyZGEwOWEwYzhkODJlZjNhY2JlYThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YQLzHpSsq3Gz9OvEUMMvjZeFl-J6Erb9SQV8QhdIX_g)

It's all set.

![image](https://github.com/user-attachments/assets/bedff705-4f55-4ed5-bf3f-84f630dadf65)

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
marking this ticket as closed , as we didnt received any response.
