### ISSUE TITLE
Failed to install the app for the user

### ISSUE THREAD

**Issue by CaioCPSilva** [OfficeDev/microsoft-teams-apps-company-communicator#1537]
Everytime i send a new messages some users throws the following excpetion:

Failed to install the app for the user: 2bf8d4ec-####-####-####-08d0dbfa2cf8. Exception: Code: Forbidden Message: App is blocked by app permission policy. TenantId: 2f75752d-####-####-####-2fa29227f529, UserObjectId: 2bf8d4ec-####-####-####-08d0dbfa2cf8, AppId: bb29fe1f-####-####-####-dd9960ed7c86, AppType: Private Inner error: Code: AccessDenied Message: App is blocked by app permission policy. TenantId: 2f75752d-####-####-####-2fa29227f529, UserObjectId: 2bf8d4ec-####-####-####-08d0dbfa2cf8, AppId: bb29fe1f-####-####-####-dd9960ed7c86, AppType: Private AdditionalData: date: 2024-08-19T03:50:04 request-id: f2ce25d8-####-####-####-83af28956584 client-request-id: f2ce25d8-####-####-####-83af28956584 ClientRequestId: f2ce25d8-####-####-####-83af28956584

How can i get the logs of the function that executes this operation?

**Comment by v-jaygupta** [comment]
Hi @CaioCPSilva ,

Could you please review the app setup and the app permission policy assigned to the users who aren't getting the messages delivered in Teams Admin Center. We believe the policy might be different for the app and the users which is causing this issue.

**Comment by peddivyshnavi** [comment]
Hi @CaioCPSilva 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by CaioCPSilva** [comment]
Hi @peddivyshnavi !
Sorry for the delay.

I'm not applying any permission policy for users, the apps are available for everyone.
Also i have de setup policy pinning and installing the app for the users.

![image](https://github.com/user-attachments/assets/7bdae1e5-edb4-4cba-a18c-196a7ac28fad)


![image](https://github.com/user-attachments/assets/908a57b6-2cd0-468d-b59f-c64cde3fbd1b)

**Comment by CaioCPSilva** [comment]
> Hi @peddivyshnavi ! Sorry for the delay.
> 
> I'm not applying any permission policy for users, the apps are available for everyone. Also i have de setup policy pinning and installing the app for the users.
> 
> ![image](https://private-user-images.githubusercontent.com/32173948/363217624-7bdae1e5-edb4-4cba-a18c-196a7ac28fad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjk4ODksIm5iZiI6MTcyNTAyOTU4OSwicGF0aCI6Ii8zMjE3Mzk0OC8zNjMyMTc2MjQtN2JkYWUxZTUtZWRiNC00Y2JhLWExOGMtMTk2YTdhYzI4ZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE0NTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NzFiZjBjM2JjOTk1OWY4MjZmMTcxZjgzMzk1MTdmODFjZTAyNzk0Zjg2MWExNmU3ZmU4MTExOGJlZDZjNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8pfj7L_fWL2OHYrTHPZ4DI8H2YfgwH2iHo9yBDmB32E)
> 
> ![image](https://private-user-images.githubusercontent.com/32173948/363218281-908a57b6-2cd0-468d-b59f-c64cde3fbd1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjk4ODksIm5iZiI6MTcyNTAyOTU4OSwicGF0aCI6Ii8zMjE3Mzk0OC8zNjMyMTgyODEtOTA4YTU3YjYtMmNkMC00NjhkLWI1OWYtYzY0Y2RlM2ZiZDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE0NTMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmODRiMWYzODNiNWQyZTkxYTY1NzA2YjJkMjc0ZGUyY2YyYjM5YzhkNjRlNTRhZDk4ODZiYWI2MTM4ZGI4ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRtF14xSRuRzk3DRCZ_hSObsQu9YQV0b_2Xk8dmkqM0)

**Comment by peddivyshnavi** [comment]
Hi @CaioCPSilva 
Could you please verify [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) and [Graph app Permission](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) from deployment guide are correctly verified or not

**Comment by peddivyshnavi** [comment]
Hi @CaioCPSilva 
We suspect there are restriction from organization level could you please check with your organization regarding restriction.

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@CaioCPSilva 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
marking this ticket as closed , as we didnt received any response.
