### ISSUE TITLE
company comminicator

### ISSUE THREAD

**Issue by ramadanfares** [OfficeDev/microsoft-teams-apps-company-communicator#1538]
after migrate to new MS teams the communicator Bot not working

**Comment by v-jaygupta** [comment]
Hello @ramadanfares ,

Could you please check and confirm if the [Authorization Issue Fix](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix) has been made in the Azure Front door resource of the deployed Company Communicator app in Azure?

**Comment by ramadanfares** [comment]
yes i did try this and opened an issue #1505  and it's closed without solve my issue

**Comment by peddivyshnavi** [comment]
Hi @ramadanfares 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@ramadanfares 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by peddivyshnavi** [comment]
@ramadanfares 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed
