### ISSUE TITLE
Question: Send automatic messages using PowerAutomate

### ISSUE THREAD

**Issue by gomescnb** [OfficeDev/microsoft-teams-apps-company-communicator#1540]
---

Is there any way to send a message through this app using an external source? 

For example, I need to fetch some data using an API, then compose a message, and send this message to all users, using Company Communicator. I am familiar with using Power Automate if that helps in finding a solution. 

**Can I do that? Is there any possible way to achieve this?**

---

**Comment by tiwariShiv7** [comment]
Hi @gomescnb , I am not aware of this capability at the moment. I'll discuss it internally and we will get back to you with the correct response.

**Comment by gomescnb** [comment]
Thanks for the feedback, just to explain my use case:
i have to send 500 or more messages (max of 4500) in a relatively short amount of time, to notify various users of the days lunch menu. PowerAutomate works well for the api and message creation, but the teams connector has a quota that i could not figure out yet how to work around. Now i am trying using the graph api, but dont know if it will work, so i saw that my company uses communicator already, and am looking into deploying the latest one to see if i can use it for my purpose. If you have any recommendations, or think that i should customize Company Communicator to receive dynamically the messages to send let me know.

**Comment by peddivyshnavi** [comment]
Hi @gomescnb 
Thanks for reaching out to us!
The above scenario seems to be more related to the customization of Company Communicator code for drafting messages externally and sending via CC is currently not implemented and we don't recommend doing any customizations as it may lead to various issues. If in future this will be implemented we will update the GitHub.

**Comment by gomescnb** [comment]
thank you for the attention
