### ISSUE TITLE
"Something went wrong. Please try again." when downloading exported results

### ISSUE THREAD

**Issue by EMEAWebEnvironmentsTeam** [OfficeDev/microsoft-teams-apps-company-communicator#1541]
Hello,

We are having an issue since deployment when trying to export detailed results, the file becomes available to download, but at the stage it says "GTS Incident Alerts (UAT) A needs permission to upload this file to your OneDrive", clicking the Allow button gives the error message "Something went wrong. Please try again."
<img width="392" alt="Screenshot 2024-08-20 112410" src="https://github.com/user-attachments/assets/1e93ba79-975c-446c-bc80-8aee6639b009">

In Failures, it comes back with error code 409 "Azure.RequestFailedException: The specified container already exists." under BlobContainerClient.Create

In BlobClient.Upload, the command (replaced data with x) https://x.blob.core.windows.net/exportdatablobs/ExportData_x.zip appears, but when browsing to this page, it gives the error "Public access is not permitted on this storage account."

However, in the storage account Networking, public access is enabled:
<img width="253" alt="image" src="https://github.com/user-attachments/assets/338276e8-36ef-4919-a768-1a3501890087">

Any suggestions for what we can check would be appreciated!

**Comment by peddivyshnavi** [comment]
Hi @EMEAWebEnvironmentsTeam 
Thanks for reaching out to us.
Could you Please confirm us with the following.

- Are you able to send or draft message using 4 different ways.
- could you please check the permissions for Graph App API it should be like following.
<img width="931" alt="image" src="https://github.com/user-attachments/assets/2fe7b34a-ad12-4b9e-96f2-20e2b4df6a12">

**Comment by EMEAWebEnvironmentsTeam** [comment]
Thanks for your response.

We appear to have the correct api permissions set up:
![image](https://github.com/user-attachments/assets/a983e786-8162-40cb-8a83-4e318eec23db)

As for sending 4 different ways, the first two options give a 'we couldn't find any matching...' error
<img width="245" alt="image" src="https://github.com/user-attachments/assets/dce32148-e1e1-4f3b-9f66-2f3311337b88">
<img width="239" alt="image" src="https://github.com/user-attachments/assets/bc3cfdce-3333-45d3-8f38-c7799e63f6b1">
Sending to all users we assume works, but we have a lot of different users and so don't want to confuse them with a message. 
<img width="245" alt="image" src="https://github.com/user-attachments/assets/03c6b781-8c83-42a7-95af-616c313b3659">
The last option is working and sends messages successfully
<img width="254" alt="image" src="https://github.com/user-attachments/assets/5e2c48fa-88a3-4fb6-bb02-5494aedeb9a0">

**Comment by peddivyshnavi** [comment]
Hi @EMEAWebEnvironmentsTeam 
**As for sending 4 different ways, the first two options give a 'we couldn't find any matching...' error:**
For making teams visible we need to add User app from manage apps so that teams will be visible while sending message via first two sending options.
**We appear to have the correct api permissions set up:**
could you please go through deployement guide whether [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) added correctly or not.
and please share the error the supporting screenshot of error from application insights resource from the deployed resource group.
Go to resource group where CC app is deployed --> Go to Application insight type resource

**Comment by peddivyshnavi** [comment]
Hi @EMEAWebEnvironmentsTeam 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@EMEAWebEnvironmentsTeam 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark ticket as complete

**Comment by peddivyshnavi** [comment]
@EMEAWebEnvironmentsTeam 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed
