### ISSUE TITLE
Company Communicator - Author Guardrails

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1542]
I have a question about how to apply guard rails to Company Communicator authors, specifically who they can send messages to within the organization.

I see that the Authors are set in the "AuthorizedCreatorUPNs" variable, which can be updated.   However, I don't see how to limit the groups or recipients individually authors can send to.

For example, if I wanted to limit some authors to only have the ability to send to a Sales or a Marketing team, how would I go about doing this?

**Comment by tiwariShiv7** [comment]
Hi @khenry1111 , According to my understanding as of now this is not possible to restrict Authors for sending the message. I can get back to you tomorrow upon internal discussion if it is possible in any way with the current version of Company communicator.

**Comment by khenry1111** [comment]
Ok, thank you.  If there are any known solutions even outside of the communicator app itself, would be interested in those as well.

**Comment by tiwariShiv7** [comment]
Hi Khenry, first to confirm yes this is not possible with official version of company communicator. Currently, we are not aware of any known solutions to fix this issue.

**Comment by khenry1111** [comment]
ok, thank you.  Closing ticket.
