### ISSUE TITLE
Unable to add a TXT record to the domain DNS for the validation in Front Door and CDN profile

### ISSUE THREAD

**Issue by NikhilDhumal734** [OfficeDev/microsoft-teams-apps-company-communicator#1544]
We followed the steps from Microsoft article : https://techcommunity.microsoft.com/t5/modern-work-app-consult-blog/migrating-company-communicator-between-azure-subscriptions/ba-p/3646546

But After creating Azure Front Door and CDN profiles manually we are getting message as The domain should be validated for traffic delivery. You should add a TXT record to the domain DNS for the validation.

As we unable to add a TXT record  to the domain DNS for the validation.
![image](https://github.com/user-attachments/assets/276e0cb1-ca70-4080-acea-db8c6eb4f13b)

Looking forward for your help

**Comment by tiwariShiv7** [comment]
Hi @NikhilDhumal734 , Thanks for reaching out to us. We will be able to respond upon this following an internal discussion. We will get back to you within 48 Hours.

**Comment by tiwariShiv7** [comment]
Hi @NikhilDhumal734 , Azure Front Door and CDN profiles gets created automatically with official version deployment. I think we are following custom deployment here and I am afraid according to our support scope this is [out of scope ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Support-policy#our-support-scope)

**Comment by NikhilDhumal734** [comment]
Hi @tiwariShiv7 

To update, we copied all the existing company communicator resource files from one resource group to another as we need to change the subscription, we followed the below article for Front-door migration
Link : https://learn.microsoft.com/en-us/azure/frontdoor/migrate-tier

As we unable to copy existing Front door and CDN profile so we created manually and after we are getting message as The domain should be validated for traffic delivery. You should add a TXT record to the domain DNS for the validation. 

Unfortunately, our network admin team also has no control/scope to add a txt record to Domain Name System.
Please help to assist us further on this case.

**Comment by peddivyshnavi** [comment]
@NikhilDhumal734 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@NikhilDhumal734
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@NikhilDhumal734 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
marking this ticket as closed as we didnt received any response from user
