### ISSUE TITLE
No team is found in the second option when trying to send a new message

### ISSUE THREAD

**Issue by neidantaslopez** [OfficeDev/microsoft-teams-apps-company-communicator#1545]
![image](https://github.com/user-attachments/assets/6b055c7e-8c16-4617-8de3-aa33b1bbdae8)

The user app is correctly installed both for the users and for the team I am using for testing, yet the issue still occurs.

I have already checked the status of all three functions, verified the IDs and secrets, as well as all configurations.

In Application Insights, I see the following errors:

![image](https://github.com/user-attachments/assets/5282862d-0f59-43f0-b4c7-a68a204db9bb)

![image](https://github.com/user-attachments/assets/bdc0fc67-daff-400f-a719-e7746a391691)

![image](https://github.com/user-attachments/assets/cf20b826-5c84-4436-b3ec-06cf48313f65)

Could you help find and resolve the issue? Thank you.

**Comment by almatosbr** [comment]
We got exactly the same issues as Nei, as you can see below:

![image](https://github.com/user-attachments/assets/0816dd20-2fee-4394-b4fc-c6b639bd51e1)

**Comment by almatosbr** [comment]
@neidantaslopez  @peddivyshnavi 
There is this Graph API update that could be causing the issue.
https://techcommunity.microsoft.com/t5/microsoft-entra-blog/important-update-azure-ad-graph-api-retirement/ba-p/4090534

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Thanks for reaching out to us.
Could you please confirm us with the following.
For making teams visible we need to add User app  for teams which should appear in dropdown.
could you please go through deployment guide whether [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) and [Add Permissions to your Microsoft Graph Azure AD app](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) are added correctly or not

**Comment by silvapf** [comment]
I’m experiencing the exact same scenario. Nothing has changed in our environment. The last time CC communications were sent out to end users was on August 9th, and there were no issues then. Something must have changed since.

**Comment by neidantaslopez** [comment]
> Hi @neidantaslopez Thanks for reaching out to us. Could you please confirm us with the following. For making teams visible we need to add User app for teams which should appear in dropdown. could you please go through deployment guide whether [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) and [Add Permissions to your Microsoft Graph Azure AD app](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) are added correctly or not

User app is already added to the team I want to appear in dropdown:

![image](https://github.com/user-attachments/assets/279291e3-2104-4d3f-bec0-27c8b7e8f5ff)


**Set-up Authentication:**

![image](https://github.com/user-attachments/assets/e5d3dfe5-ad20-46b2-bed9-166b07c69694)

![image](https://github.com/user-attachments/assets/741ad0f5-ffc8-4b27-bdb4-62e2f3c53099)

![image](https://github.com/user-attachments/assets/155c5094-ec74-42b5-8f19-60f62dcd8340)

![image](https://github.com/user-attachments/assets/8dd8564e-2809-467d-aae9-1b0b75a8f290)

**Add Permissions to your Microsoft Graph Azure AD app:**

![image](https://github.com/user-attachments/assets/ec951626-b0a9-40c2-b2ec-665a7458bf6d)

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
For making teams visible we need add that particular team to user app
Please follow below steps for making team visible:

- Install User app.
- Create a Teams channel with the people or Group you want to trigger user app installation to.
- Navigate to installed user app from apps -> manage apps in Teams.
- Click on the app and Select an option of Add to a Team.
- Select created / desired Teams channel from Dropdown.
- Click on set up / Submit button.
<img width="531" alt="userapp" src="https://github.com/user-attachments/assets/f8dc2e15-de9b-45fa-88d4-8c6527cf2a0c">

**Comment by neidantaslopez** [comment]
> Hi @neidantaslopez For making teams visible we need add that particular team to user app Please follow below steps for making team visible:
> 
> * Install User app.
> * Create a Teams channel with the people or Group you want to trigger user app installation to.
> * Navigate to installed user app from apps -> manage apps in Teams.
> * Click on the app and Select an option of Add to a Team.
> * Select created / desired Teams channel from Dropdown.
> * Click on set up / Submit button.
> 
> <img alt="userapp" width="531" src="https://private-user-images.githubusercontent.com/177909774/360954160-f8dc2e15-de9b-45fa-88d4-8c6527cf2a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjMxMDQsIm5iZiI6MTcyNDQyMjgwNCwicGF0aCI6Ii8xNzc5MDk3NzQvMzYwOTU0MTYwLWY4ZGMyZTE1LWRlOWItNDVmYS04OGQ0LThjNjUyN2NmMmEwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxNDIwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzQ0NjBlZGExOGYxZjgyN2E4ZTFiMjlkOGUyZDM2M2ZiNGYzMjA3ZWQ1ZDgwNjVjNWZmNTUwMDExYTI3MzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MGmyiQzr3E1aIxJK6mEzON6NzrWlw-0wQDRlF14b8yQ">

I have already followed all the steps. The user app is added to the team we want to appear in the dropdown, but the team still does not show up (which is why I created this issue).

Is there anything else I should check?

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Could you please perform the below procedure.

- Please uninstall the user app completely. Wait for sometime
- Again re-install/ upload the user app at the tenant level
- Add the user app to the specific team.
- And try checking the option in the dropdown.

**Comment by neidantaslopez** [comment]
> Hi @neidantaslopez Could you please perform the below procedure.
> 
> * Please uninstall the user app completely. Wait for sometime
> * Again re-install/ upload the user app at the tenant level
> * Add the user app to the specific team.
> * And try checking the option in the dropdown.

We have already done that...

Do we have any other thing to check?

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Can you also please confirm validating this
The error indicating that the issue might be due to policies. However please reverify if it meets the [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)requirements

**Comment by neidantaslopez** [comment]
> Hi @neidantaslopez Can you also please confirm validating this The error indicating that the issue might be due to policies. However please reverify if it meets the [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)requirements

I don't think that that could be the problem because in the page you sent me it said:
 
"...The users in your organization might see an error while accessing the message authoring experience in the Company Communicator app in Teams, with the error message “Sorry, an error occurred while trying to access the service”."
 
We don't see and error while accessing the message authoring experience. The problem is that we are not able to pick Teams in the dropdown menu even though we have user app installed for them.

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Could you please share screenshot of userapp
open teams-->Apps-->manage apps-->userapp
[
![Screenshot 2024-08-26 223035](https://github.com/user-attachments/assets/a1d3ed4c-f08a-468e-8dd7-9fcc756be2d6)
](url)

**Comment by peddivyshnavi** [comment]
Hi Nei Dantas Lopez
we can start discussing about this ticket internally

**Comment by peddivyshnavi** [comment]
From internal discussion , after sync all the three functions then reinstall user app issue got resolved marking ticket as closed.
