### ISSUE TITLE
Company Communicator Version: V5.5.2 | Error Message: “Something Went Wrong”

### ISSUE THREAD

**Issue by ArunkumarTMEYGDS** [OfficeDev/microsoft-teams-apps-company-communicator#1546]
HI Team,

While adding Admin App to Teams Channel, we are getting the error message:  “Something Went Wrong”.

Attached screenshots for error in Azure Application insights. 
<img width="727" alt="A1" src="https://github.com/user-attachments/assets/d6268a20-c76e-4bc9-9890-5dba6a6fe0be">
<img width="749" alt="A2" src="https://github.com/user-attachments/assets/049699df-0332-4642-a9ec-92c73581033d">
<img width="726" alt="A3" src="https://github.com/user-attachments/assets/d12401a6-d4c6-4bbc-88e5-23faad847466">

Please advise.

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
Thank you for Reaching out 
Could you Please verify whether app service and the three function apps deployed successfully.
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select function App (App Service) -->
 Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

**Comment by malvarezColabra** [comment]
Hi, looks like I have the same error.
This is what I get when I goes to Deployment Center of the App Service.

![image](https://github.com/user-attachments/assets/f8703bfc-0c3c-46fa-b9b8-c1ce749a2d5a)

Greetings!

**Comment by ArunkumarTMEYGDS** [comment]
> Hi @ArunkumarTMEYGDS Thank you for Reaching out Could you Please verify whether app service and the three function apps deployed successfully. Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select function App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

Hi @peddivyshnavi ,

While opening Teams in browser we were getting this error : "Something Went Wrong".

When we tried today adding the Admin App using Teams Desktop client, the app loads for few seconds and throws the same error again.

Sharing the requested screenshots as well.
<img width="667" alt="S1" src="https://github.com/user-attachments/assets/0150b699-2d0d-4515-bb11-ac1f5c6f889e">
<img width="672" alt="S2" src="https://github.com/user-attachments/assets/3e0c5d5a-77bb-4de8-8628-7ef49ef54ebd">
<img width="670" alt="S3" src="https://github.com/user-attachments/assets/302f96f6-3ede-45db-8f5c-74ffc7a8cb3b">
 <img width="672" alt="S4" src="https://github.com/user-attachments/assets/749135e9-11a7-4a09-96d6-a979f2a2d24f">
<img width="672" alt="S5" src="https://github.com/user-attachments/assets/064ef3db-669d-4a3a-a2aa-d4edf739cdd7">
<img width="674" alt="S6" src="https://github.com/user-attachments/assets/bd7f32dd-5037-4512-9ce7-edeabff3e3ba">

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
Could you please verify whether 3rd and 4th step from deployment guide are correctly or not

**Comment by ArunkumarTMEYGDS** [comment]
@peddivyshnavi,

Can you please confirm if we need to replace the ID "5e3ce6c0-2b1f-4285-8d4b-75ee78787346" and "1fec8e78-bce4-4aaf-ab1b-5451cc387264" with our Client IDs of Author and User App registerations? 

**Click Add a client application, under Authorized client applications. In the flyout that appears, enter the following values:
Client ID: 5e3ce6c0-2b1f-4285-8d4b-75ee78787346
Authorized scopes: Select the scope that ends with access_as_user. (There should only be 1 scope in this list.)
Click Add application to commit your changes.

Repeat the previous two steps, but with client ID = 1fec8e78-bce4-4aaf-ab1b-5451cc387264. After this step you should have two client applications (5e3ce6c0-2b1f-4285-8d4b-75ee78787346 and 1fec8e78-bce4-4aaf-ab1b-5451cc387264) listed under Authorized client applications.**

**Comment by ArunkumarTMEYGDS** [comment]
> @peddivyshnavi,
> 
> Can you please confirm if we need to replace the ID "5e3ce6c0-2b1f-4285-8d4b-75ee78787346" and "1fec8e78-bce4-4aaf-ab1b-5451cc387264" with our Client IDs of Author and User App registerations?
> 
> **Click Add a client application, under Authorized client applications. In the flyout that appears, enter the following values: Client ID: 5e3ce6c0-2b1f-4285-8d4b-75ee78787346 Authorized scopes: Select the scope that ends with access_as_user. (There should only be 1 scope in this list.) Click Add application to commit your changes.
> 
> Repeat the previous two steps, but with client ID = 1fec8e78-bce4-4aaf-ab1b-5451cc387264. After this step you should have two client applications (5e3ce6c0-2b1f-4285-8d4b-75ee78787346 and 1fec8e78-bce4-4aaf-ab1b-5451cc387264) listed under Authorized client applications.**

@peddivyshnavi Can you please advise. This is a roadblocker for us.

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 

- **Can you please confirm if we need to replace the ID "5e3ce6c0-2b1f-4285-8d4b-75ee78787346" and "1fec8e78-bce4-4aaf-ab1b-5451cc387264" with our Client IDs of Author and User App registerations?**
   No we cant replace these Ids

- Could you please verify whether 3rd and 4th step from deployment guide are correctly or not

- Can you also please check [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)requirements

**Comment by ArunkumarTMEYGDS** [comment]
> Hi @ArunkumarTMEYGDS
> 
> * **Can you please confirm if we need to replace the ID "5e3ce6c0-2b1f-4285-8d4b-75ee78787346" and "1fec8e78-bce4-4aaf-ab1b-5451cc387264" with our Client IDs of Author and User App registerations?**
>   No we cant replace these Ids
> * Could you please verify whether 3rd and 4th step from deployment guide are correctly or not - **Yes**
> * Can you also please check [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)requirements - **Yes we checked this article but couldnt find any routingRule2 created in the Azure Front door**

Screenshots attached.

Hi @peddivyshnavi,

Please see our responses above

<img width="594" alt="O1" src="https://github.com/user-attachments/assets/971e2338-fc09-45f7-964e-45239929b330">
<img width="777" alt="O2" src="https://github.com/user-attachments/assets/09c51290-c44b-432c-930e-cf74008b88b5">

We are stuck on this from last week. Can you advise what else might be causing this issue.

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
Could you please check whether [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) from deployment guide is deployed correctly.

**Comment by ArunkumarTMEYGDS** [comment]
> Hi @ArunkumarTMEYGDS Could you please check whether [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) from deployment guide is deployed correctly.

Hi @peddivyshnavi 

We checked the permissions, it turned out to be issue with Tenant ID that was by default pointing prod environment internally. We had resolved it by changing this ID to our respective dev environment as we have done a multi tenant deployment.

Now we are able to view the app and able to create message, but while sending message, it throws below errror.

<img width="400" alt="Error" src="https://github.com/user-attachments/assets/aff3df6c-6858-446f-9adf-8ee7a8b635f0">

Help us troubleshoot this issue further.

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
Could you please share the error the supporting screenshot of error from application insights resource from the deployed resource group.
Go to resource group where CC app is deployed --> Go to Application insight type resource --> share the screenshot and stack trace for Top 3 response codes.

**Comment by ArunkumarTMEYGDS** [comment]
> Hi @ArunkumarTMEYGDS Could you please share the error the supporting screenshot of error from application insights resource from the deployed resource group. Go to resource group where CC app is deployed --> Go to Application insight type resource --> share the screenshot and stack trace for Top 3 response codes.

@peddivyshnavi  Sharing requested screenshots.

<img width="938" alt="V1" src="https://github.com/user-attachments/assets/75ea427a-a34a-45ec-b69a-bf35bede4e7b">
<img width="954" alt="V2" src="https://github.com/user-attachments/assets/cd5464c4-5690-45de-b141-dc008a388d7c">
<img width="949" alt="V3" src="https://github.com/user-attachments/assets/e6bc1e22-7134-4644-b445-3565c77b8612">

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
Could you please verify whether [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) from deployment guide is deployed correctly
Please share your email id so we can start discussing issue internally

**Comment by ArunkumarTMEYGDS** [comment]
> Hi @ArunkumarTMEYGDS Could you please verify whether [Set-up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) from deployment guide is deployed correctly Please share your email id so we can start discussing issue internally

We have already followed the steps from guide and checked twice.  
Sharing contact email address: **arunkumar.t.m@gds.ey.com**

Please revert once the email is copied (back up). I would have to remove it from this post.

**Comment by peddivyshnavi** [comment]
Started discussing internally

**Comment by peddivyshnavi** [comment]
we have connected internally with user, we have identified id values were configured incorrectly. after updating the values user was able to send message but still, we see failure count. and we have observed that's because of user didn't installed CC.

**Comment by ArunkumarTMEYGDS** [comment]
@peddivyshnavi 

As adviced by your Team for troubleshooting, sharing status of the action items below:

1. Add the app to both the installed apps and pinned apps sections in the Teams Admin Center, then attempt to send a message. **This has not worked**
2. If the error continues after the first step, delete the user app in the Teams Admin Center, wait for an hour, then re-upload the user app and wait a few more hours before testing the app again. **This has not worked**
3. Sync the app service to ensure the 'delete message' button appears on the homepage of the CC author app after any modifications are made to the environmental variables of the UPNs. **This has worked and resolved issue**

Requesting further assistance. Sharing the errors we see now in logs.
<img width="664" alt="1" src="https://github.com/user-attachments/assets/cc2469f6-2843-4a60-bc61-b17e59386515">
<img width="666" alt="2" src="https://github.com/user-attachments/assets/1263ab76-5e72-46d5-8915-232c3c7a45b7">

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
We were checking on this we will get back to you in 48hours

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
we suspect this issue is related to app policies.
As a part of troubleshooting call which we have attended for GitHub issue(https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1546) we see team's policies are not assigned to Global (Org-wide default) they were assigned to custom policies.
could you please reassign it to Global (Org-wide default)
