### ISSUE TITLE
Unable to send messages through the first and second options

### ISSUE THREAD

**Issue by neidantaslopez** [OfficeDev/microsoft-teams-apps-company-communicator#1547]
First and second option **does not** work (user app is added to the team I want to appear in the dropdown):

![image](https://github.com/user-attachments/assets/ae36c884-ed3e-43a4-b344-32df54d70c72)

![image](https://github.com/user-attachments/assets/b4e03b32-b368-4e06-a6d5-23bcbb6cdefd)

Third and fourth options **work fine** (I am able to create and send messages, and users who have the user app installed receive the messages without any issues through these sending options):

![image](https://github.com/user-attachments/assets/2926753e-b4e4-4958-8109-46db654364d6)

I couldn't identify any error/exception in Application Insights that could be causing this issue:

![image](https://github.com/user-attachments/assets/f68349c0-80e2-4405-bb82-a67b0b9f32c7)

It seems curious to me that I can find M365 DL, SG in the fourth sending option of the Company Communicator, but I cannot find teams in the first and second sending options of the Company Communicator. Is the search mechanism for these groups different, or do both use the Graph API?

Just a note: I also recently created issue 1545, but this issue refers to a different environment with another problem.

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Thanks for reaching out to us.
For making teams visible we need add that particular team to user app
Please follow below steps for making team visible:

- Install User app.
- Create a Teams channel with the people or Group you want to trigger user app installation to.
- Navigate to installed user app from apps -> manage apps in Teams.
- Click on the app and Select an option of Add to a Team.
- Select created / desired Teams channel from Dropdown.
- Click on set up / Submit button.
<img width="531" alt="userapp" src="https://github.com/user-attachments/assets/c1a2149b-f0ad-4ca6-a913-6a84de9227ac">

**Comment by neidantaslopez** [comment]
> Please follow below steps for making team visible:

I have already followed all the steps. The user app is added to the team we want to appear in the dropdown, but the team still does not show up (which is why I created this issue).

Is there anything else I should check?

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Could you please perform the below procedure.

Please uninstall the user app completely. Wait for sometime
Again re-install/ upload the user app at the tenant level
Add the user app to the specific team.
And try checking the option in the dropdown.

and we see [1545](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1545) both are created by you with same issue could you please close any ticket we can continue having one ticket opened

**Comment by neidantaslopez** [comment]
> Hi @neidantaslopez Could you please perform the below procedure.
> 
> Please uninstall the user app completely. Wait for sometime Again re-install/ upload the user app at the tenant level Add the user app to the specific team. And try checking the option in the dropdown.
> 
> and we see [1545](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1545) both are created by you with same issue could you please close any ticket we can continue having one ticket opened

We have already done that...
They are different issues. In one of them we got 401 and 403 and in the other one we do not. I have mentioned that in the issue!

Is it possible to set up a meeting so that we could solve this?

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Can you also please confirm validating this

The error indicating that the issue might be due to policies. However please reverify if it meets the [Auth Issue Fix ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Authorization-issue-fix)requirements

**Comment by peddivyshnavi** [comment]
Hi @neidantaslopez 
Could you please try to open teams in incognito mode and check whether the same repeats

**Comment by neidantaslopez** [comment]
> Hi @neidantaslopez Could you please try to open teams in incognito mode and check whether the same repeats

We have tried it. The problem still happens.

**Comment by peddivyshnavi** [comment]
Hi Nei Dantas Lopez
we can start discussing about this ticket internally

**Comment by peddivyshnavi** [comment]
From internal discussion , after sync all the three functions then reinstall user app issue got resolved marking ticket as closed.

**Comment by peddivyshnavi** [comment]
From internal discussion , after sync all the three functions then reinstall user app issue got resolved marking ticket as closed.
