### ISSUE TITLE
UPN - Groups Supported?

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1548]
Is it possible to enter AD Group or Distribution List instead of individual UPNs in the UPN author list?

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
Thanks for reaching out to us.
we will verify and let you know regarding this shortly.

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
we can't send messaged by adding AD Group or Distribution List instead of individual UPNs in the UPN author list

**Comment by khenry1111** [comment]
Ok, thank you.
