### ISSUE TITLE
Adaptive cards not working

### ISSUE THREAD

**Issue by MBlondin** [OfficeDev/microsoft-teams-apps-company-communicator#1549]
We recently deployed v 5.5.2 and the adaptive cards are not working/used

![image](https://github.com/user-attachments/assets/06803d1c-c81c-4f30-91bc-e4d67a33fc3c)

Is there a setting that was missed ?

**Comment by peddivyshnavi** [comment]
Hi @MBlondin 
Thanks for reaching out to us.
we will verify and let you know regarding this shortly.

**Comment by peddivyshnavi** [comment]
Hi @MBlondin 
Could you please confirm us whether are you able to send messages from first two options. and could you please elaborate the issue.

**Comment by peddivyshnavi** [comment]
@MBlondin 
Could you please update us on the status of the issue?

**Comment by MBlondin** [comment]
We are able to send out messages but the output seems to not use the adaptive cards and formatting is disregarded (i.e.: Lines, Bold, Italic, etc.).

**Comment by peddivyshnavi** [comment]
Hi @MBlondin 
These are the text formats Company communicator supports could you please go through the [link](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html). and CC supports Italic and bold

**Comment by MBlondin** [comment]
Hi @peddivyshnavi ,

Thank you for the info but this doesn't respond as to why our version is not displaying in adaptive cards. Is there a setting or step you think we have missed.

**Comment by peddivyshnavi** [comment]
Hi @MBlondin 
From previous comment we got to know youre using version 5.5.2
and we see Adaptive cards are working as expected. we were able to format text in bold,italic,unorderedlist,hyperlinks
we have tested the same please find attached screenshots for reference:

![Screenshot (35)](https://github.com/user-attachments/assets/9e1435d0-e5fe-45ca-9c26-e118d9d409e0)
![Screenshot (36)](https://github.com/user-attachments/assets/7b732ca0-0f23-462b-b4bb-51198585f01f)

and we see preview is also working as expected
![Screenshot (37)](https://github.com/user-attachments/assets/127ab14c-84e2-4f25-9fbf-527665fd2c31)

**Comment by MBlondin** [comment]
Interesting. We will try again.

**Comment by peddivyshnavi** [comment]
Hi @MBlondin 
could you please let us know if you are still facing this issue

**Comment by peddivyshnavi** [comment]
Hi @MBlondin 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed as we didnt received any response from user
