### ISSUE TITLE
Upgrading ASE v2 to ASE V3, how can I redeploy only the App Service Components and bots

### ISSUE THREAD

**Issue by GhouseShaik1** [OfficeDev/microsoft-teams-apps-company-communicator#1550]
We are using Company Communicator v4.1 from past 4 years and was deployed on ASE v2. Since Microsoft is retiring the ASE v2, how can I redeploy the code again with out impacting any changes to existing Bots, or non ASE components. Please suggest

what will happen post ASE v3 in place upgrade if I run the ARM template again? will it create all the non ASE components again such as Bots, Service Bus, Key Vault, Storage account etc.

My plan is to keep the non ASE configurations as is and to redeploy? how do I redeploy. I want to avoid recreating a new resource group and setup everything from the scratch. Thanks!

**Comment by peddivyshnavi** [comment]
Hi @GhouseShaik1 
Thanks for reaching out to us.
we will verify and let you know regarding this shortly.

**Comment by peddivyshnavi** [comment]
Hi @GhouseShaik1 
Could you please follow [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) for migrating v4.1 to new version

**Comment by peddivyshnavi** [comment]
@GhouseShaik1 
Could you please update us on the status of the issue?

**Comment by GhouseShaik1** [comment]
Apologies for the delay. Few queries before migrating to newer version
1. Please confirm that, our current version https://github.com/campanaandschott/companycommunicator-v4.1 is suitable to migrate to v5 version https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/  ?

**Comment by GhouseShaik1** [comment]
also any end date for using v4.1 ?

**Comment by peddivyshnavi** [comment]
@GhouseShaik1 
Could you please update us on the status of the issue?

**Comment by GhouseShaik1** [comment]
I was successfully able to upgrade to ASE v3, please close this issue.
Thanks for your support

Rgds
Ghouse

**Comment by peddivyshnavi** [comment]
closing this issue as issue got resolved.
