### ISSUE TITLE
Company Communicator is not working in MS Teams

### ISSUE THREAD

**Issue by RocioAbreuO** [OfficeDev/microsoft-teams-apps-company-communicator#1551]
Note: We had posted this issue before ([Ticket 2954482) and we are asked to reach out Microsoft Support. Accordingly we engaged Microsoft Teams Support. As per their feedback Microsoft Teams Support is responsible for deployment and setup, but if there are issues or bugs with the application that is all handled via Github only.
The same is discussed with The Github support person as well.

We are having problems sending a message through Company Communicator, it shows us the errors in the screenshots attached to the case. It does not allow viewing reports of previously sent messages. 

Error message: "Failed to prepare the message for sending: The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'BatchRecipientsActivity' failed: "Object reference not set to an instance of an object.". See the function execution logs for additional details.". See the function execution logs for additional details."

![Screenshot 2024-08-20 090246](https://github.com/user-attachments/assets/a3b60061-5c1e-44b3-8a43-5f487ee5b18a)
![Screenshot 2024-08-20 090324](https://github.com/user-attachments/assets/00972b12-0a8d-40fc-93ca-32f3f8d91802)
![Screenshot 2024-08-20 090940](https://github.com/user-attachments/assets/acb1bea0-066b-44f4-9291-34a0f8b891f0)

**Comment by peddivyshnavi** [comment]
Hi @RocioAbreuO 
Thanks for reaching out to us.
we will verify and let you know regarding this shortly.

**Comment by peddivyshnavi** [comment]
Hi @RocioAbreuO 
Thanks for reaching out.
This issue might be due to multiple reasons.
Is this a fresh deployment? Please confirm on this.
There is a chance of incorrect configuration, have a thorough check from start-end and mainly verify the all three app client secret is correctly copied while creating ARM template or not.

**Comment by RocioAbreuO** [comment]
Hi @peddivyshnavi !

No, it is not a recent deployment. We have not even tried to re-deploy the application.
Where or how can I validate the client secret?

**Comment by peddivyshnavi** [comment]
Hi @RocioAbreuO 
For validating or verifying secrets we need to navigate to app registration then app functions 
Go to Azure Portal -->App registrations-->app functions which got created while deploying the app
and also could you please check whether secrets got expired.

**Comment by RocioAbreuO** [comment]
Hi @peddivyshnavi,

Yes, they are. The Client Secret are expired :(
Can you guide me where I can update within the company communicator app?

![Client-Secret-CCommunicator](https://github.com/user-attachments/assets/08f0e62a-661f-4b9e-b5bf-3df740d61a1c)

**Comment by peddivyshnavi** [comment]
Hi @RocioAbreuO 
Please follow below steps:

- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference

![image](https://github.com/user-attachments/assets/13c59b61-f0d9-4525-9d41-a052968b3417)

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.

![image](https://github.com/user-attachments/assets/2daad3eb-08e2-4073-ba10-146ea40742ad)

- If the secrets are not visible, Go to Access Policy--> Click on Create

![image](https://github.com/user-attachments/assets/9103e2d5-b361-4a0e-aeae-98fec3709fc0)

- Select Key, secret and certificate management

![image](https://github.com/user-attachments/assets/41f174da-07ef-4624-8b71-c4784b9c75fc)

- Give the Id through which one can view the secrets

![image](https://github.com/user-attachments/assets/6ebcf3bf-fbba-4376-a534-ac1df1aff2ab)

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version

![image](https://github.com/user-attachments/assets/e4da17e0-8053-4508-ab4b-f1265c6ae4cf)

- Grab the new secret identifier

![image](https://github.com/user-attachments/assets/71ae6644-3fa4-46dd-8526-429c1cc78076)

- Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.

![image](https://github.com/user-attachments/assets/dc5c3228-9046-4ce7-9237-fcd2afe46d34)

- Follow the same procedure for the user app password and graph app password updating.
- For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference

![image](https://github.com/user-attachments/assets/8c7a65fa-6adf-4f8e-b54b-b76bc3ad280d)

**Comment by RocioAbreuO** [comment]
Hi @peddivyshnavi!

I completed the steps. After, I told with the user to send a message thought Company Communicator and he still receive the error.
Is neccesary to restart the app service or something like that?

Are you able to have a MS Teams sesion in order to validate the steps that I completed or something else?

![Captura de pantalla (776)](https://github.com/user-attachments/assets/493b8089-b4ea-4153-9c11-350ce577c96d)

**Comment by peddivyshnavi** [comment]
Hi @RocioAbreuO 
could you please validate whether secrets got updated correctly or not.

**Comment by peddivyshnavi** [comment]
Hi @RocioAbreuO 
Could you please share the error the supporting screenshot of error from application insights resource from the deployed resource group.
Go to resource group where CC app is deployed --> Go to Application insight type resource --> share the screenshot and stack trace for Top 3 response codes.

**Comment by RocioAbreuO** [comment]
Hi @peddivyshnavi 

Below the printscreen:

![image](https://github.com/user-attachments/assets/190c0fd3-9090-4583-ab88-68e9c6716e95)

**Comment by peddivyshnavi** [comment]
Hi @RocioAbreuO 
Could you please share your email id so that we can start discussing the issue internally

**Comment by RocioAbreuO** [comment]
Hi @peddivyshnavi!

Sure!
My email address is: rocio_abreu@claro.com.do

**Comment by peddivyshnavi** [comment]
We have started discussing internally

**Comment by RocioAbreuO** [comment]
Hi @peddivyshnavi!

Please as you can, send me the schedule meeting.

**Comment by peddivyshnavi** [comment]
We have connected internally for issue ,

we see secrets for all app registration got expired and user created new secrets, we have updated secrets in all app functions accordingly.

**Comment by RocioAbreuO** [comment]
We have not yet received confirmation from Authors users. As soon as they confirm me, I will update you. Thank you very much.

**Comment by RocioAbreuO** [comment]
Hi @peddivyshnavi!

The "Authors users" confirmed that the application is working fine now.

**Comment by peddivyshnavi** [comment]
Closing ticket as user mentioned issue got resolved
