### ISSUE TITLE
CC Retention Policy

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1552]
Is there a way to configure retention policy for sent messages.  

For example, if only want to keep the last month of messages, can automatically delete messages beyond month.

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
Thanks for reaching out to us.
we will verify and let you know regarding this shortly.

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
We dont have any retention policy for automatic delete messages

**Comment by peddivyshnavi** [comment]
@khenry1111 
Could you please update us on the status of the issue?

**Comment by khenry1111** [comment]
This can be closed if this capability does not exist.
