### ISSUE TITLE
CC app is not working 

### ISSUE THREAD

**Issue by i7asko** [OfficeDev/microsoft-teams-apps-company-communicator#1554]
it's been a while company communicator app is not working & I tried the client & browser same result 

![zi comm](https://github.com/user-attachments/assets/353ea488-5d5f-4b7b-bd59-b788d88b8593)

**Comment by i7asko** [comment]
hi @peddivyshnavi 

no it an old deployment 

FYI

![image](https://github.com/user-attachments/assets/e8e16d18-98a1-48dd-aa53-1bf1781ddae4)

![image](https://github.com/user-attachments/assets/6fbaf001-dd9e-42f3-a79a-61cabb690a7f)

![image](https://github.com/user-attachments/assets/d69170cf-21b5-4278-9acb-45e755e8bf19)

**Comment by v-jaygupta** [comment]
@i7asko ,
Could you please share the call stack of error from application insights resource from the deployed resource group.
Go to resource group where CC app is deployed --> Go to Application insight type resource --> Go to Failures section from Left hand side menu --> share the screenshots and stack trace for Top 3 response codes.

**Comment by i7asko** [comment]
hi @v-jaygupta 

FYI
![image](https://github.com/user-attachments/assets/e5efb446-d78e-4f1f-8569-3b4316a30bfe)

![image](https://github.com/user-attachments/assets/ddae4c26-ee96-488b-8b4a-8bec83ab9d1b)

![image](https://github.com/user-attachments/assets/e125a4a1-0bb2-45ce-9e48-6b3293848ad1)

**Comment by peddivyshnavi** [comment]
Hi @i7asko 
By checking screenshots provided we see its pointing to different repo. Please note, that we are only able to troubleshoot versions that are from our [main repo](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator). Even though they may be using out of the box features, the fact that they are indeed running a customized version means there are other variables present and the team is unable to dive into all the potential differences between our version vs custom changes. We will be unable to further troubleshoot unless it is the main repo / non customized version. 

If we can be of any help for future issues, please do continue and engage. Hope you understand out limitations as it is with our inability to support customized versions (not just for this app template, but for any of the app templates).

**Comment by peddivyshnavi** [comment]
@i7asko 
Could you please update us on the status of the issue?

**Comment by i7asko** [comment]
hi @peddivyshnavi 

please allow me some im checking with Microsoft to figure out , our current version pulled from which repo & I'll update you ASAP

**Comment by peddivyshnavi** [comment]
Hi @i7asko 
Could you please update us on the status of the issue?

**Comment by i7asko** [comment]
hi @peddivyshnavi , thanks for your follow up 
i still have communication & logs going on with Microsoft  as of now  i don't know what the next action plan

**Comment by peddivyshnavi** [comment]
@i7asko 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@i7asko
Could you please update us on the status of the issue?
