### ISSUE TITLE
Can Communicator Communicate Outside of Teams

### ISSUE THREAD

**Issue by Chris-USDA** [OfficeDev/microsoft-teams-apps-company-communicator#1556]
Is there a way to get Communicator Communicate Outside of Teams. Such as email SMS, etc?
Expecting more out of Company Communicator than just sending emails to Teams Groups.
Is there something I am overlooking?

**Comment by peddivyshnavi** [comment]
Hi @Chris-USDA 
Thanks for reaching out to us!
we don't have functionality of sending mails. we can send messages inside teams by using company communicator

**Comment by albert-widjaja** [comment]
@peddivyshnavi ,
Can we message out to the external tenants team as well?

**Comment by peddivyshnavi** [comment]
@Chris-USDA 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
Hi @Chris-USDA 
Could you please update us on the status of the issue?
