### ISSUE TITLE
Deployment Fails to the build the /communicator/web resource due to command not finding the .net framework, that is properly installed

### ISSUE THREAD

**Issue by michaelhadams36** [OfficeDev/microsoft-teams-apps-company-communicator#1557]
Receive this error when the ARM template deployment is running the Microsoft.Web/sites/sourcecontrol.  The .net framework/SDK's referenced in the error exist and are available.  The error is a template because, there are NO other .net frameworks installed as indicated in the error.  Not sure what to update on the computers from which I run the deployment or in the ARM template to overcome this deployment error.

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "target": "/subscriptions/#####################/resourceGroups/np-usce-rp-rg-gs-vra-cp/providers/Microsoft.Web/sites/M365communicator/sourcecontrols/web",
        "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."
    }
}

**Logged error from web app deployment:**

Command: deploy.cmd
You must install or update .NET to run this application.

App: C:\Program Files (x86)\dotnet\sdk\6.0.424\dotnet.dll
Architecture: x86
Framework: 'Microsoft.NETCore.App', version '6.0.32' (x86)
.NET location: C:\Program Files (x86)\dotnet\

The following frameworks were found:
  1.0.16 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  1.1.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.0.9 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.1.30 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.2.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  3.0.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  6.0.29 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.19 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  8.0.5 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  8.0.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.32&arch=x86&rid=win-x86&os=win10
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
Failed exitCode=-2147450730, command=dotnet restore "C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln"
An error has occurred during web site deployment.
You must install or update .NET to run this application.\r\n\r\nApp: C:\Program Files (x86)\dotnet\sdk\6.0.424\dotnet.dll\r\nArchitecture: x86\r\nFramework: 'Microsoft.NETCore.App', version '6.0.32' (x86)\r\n.NET location: C:\Program Files (x86)\dotnet\\r\n\r\nThe following frameworks were found:\r\n  1.0.16 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  1.1.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.0.9 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.1.30 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.2.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  3.0.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  6.0.29 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  7.0.19 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  8.0.5 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  8.0.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n\r\nLearn more:\r\nhttps://aka.ms/dotnet/app-launch-failed\r\n\r\nTo install missing framework, download:\r\nhttps://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.32&arch=x86&rid=win-x86&os=win10\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.100729.001\bin\Scripts\starter.cmd deploy.cmd

**Comment by peddivyshnavi** [comment]
Hi @michaelhadams36 
Could you please share the resources which got failed during the deployment with a supporting screenshot.

**Comment by michaelhadams36** [comment]
The resource that failed was the M365communicator/web resource.
![DeploymentFailureShot1](https://github.com/user-attachments/assets/5d848727-9d43-4327-95aa-2f2bcbe800fd)


![CommErrorShot2](https://github.com/user-attachments/assets/cfa5154f-6d3e-4446-8473-dc486af0e1b2)

Details about Resource -
![WebAppDetails](https://github.com/user-attachments/assets/ae0cd152-f2e4-47b7-9916-d5fb439448a5)

Error deploying Web = 
![WebAppDeploymentLog1](https://github.com/user-attachments/assets/cc94d00e-3d64-4fb9-88f4-eba34881f398)


Text of error doing Web deployment = Command: deploy.cmd
You must install or update .NET to run this application.

App: C:\Program Files (x86)\dotnet\sdk\6.0.424\dotnet.dll
Architecture: x86
Framework: 'Microsoft.NETCore.App', version '6.0.32' (x86)
.NET location: C:\Program Files (x86)\dotnet\

The following frameworks were found:
  1.0.16 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  1.1.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.0.9 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.1.30 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.2.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  3.0.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  6.0.29 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.19 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  8.0.5 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  8.0.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.32&arch=x86&rid=win-x86&os=win10
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
Failed exitCode=-2147450730, command=dotnet restore "C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln"
An error has occurred during web site deployment.
You must install or update .NET to run this application.\r\n\r\nApp: C:\Program Files (x86)\dotnet\sdk\6.0.424\dotnet.dll\r\nArchitecture: x86\r\nFramework: 'Microsoft.NETCore.App', version '6.0.32' (x86)\r\n.NET location: C:\Program Files (x86)\dotnet\\r\n\r\nThe following frameworks were found:\r\n  1.0.16 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  1.1.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.0.9 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.1.30 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.2.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  3.0.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  6.0.29 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  7.0.19 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  8.0.5 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  8.0.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n\r\nLearn more:\r\nhttps://aka.ms/dotnet/app-launch-failed\r\n\r\nTo install missing framework, download:\r\nhttps://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.32&arch=x86&rid=win-x86&os=win10\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.100729.001\bin\Scripts\starter.cmd deploy.cmd

It looks like the ARM template is attempting to deploy the web site but when running the (x86)\SiteExtensions\Kudu\102.100729.001\bin\Scripts\starter.cmd deploy.cmd from the solution downloaded from the https://github.com/OfficeDev/microsoft-teams-apps-company-communicator the correct .net framework is not detected, but the correct .net framework is available on the server/desktops we run the ARM deployment template from.

**Comment by peddivyshnavi** [comment]
Hi @michaelhadams36 
could you please follow the steps:

- Go to the "Deployment center" section of the app service that failed to deploy.
- Click on "Sync" to restart the deployment

![image](https://github.com/user-attachments/assets/da1c3610-4dbc-42cf-8e93-782cc1236124)
after sync is succeesful you might not have received the authorBotId, userBotId and appDomain values at the end of the deployment. To find them, go to the "Configuration" section of your Web App.

- authorBotId: It can be found in the "AuthorAppId" field of your configuration , it will be referred to as %authorBotId%.
- userBotId:It can be found in the "UserAppId" field of your configuration , it will be referred to as %userBotId%.
- appDomain: This is the base domain for the Company Communicator app It is the value in the "AzureAd:ApplicationIdURI" field of your configuration without the "api://" e.g. appName.azurefd.net. For the following steps, it will be referred to as %appDomain%.

**Comment by michaelhadams36** [comment]
I have attempted this based the troubleshooting help and receive another error -   Status "Failed"  - Log Details "Fetching changes."  

![image](https://github.com/user-attachments/assets/bdaf117d-ddfe-498f-8366-fc58e08dec42)

**Comment by michaelhadams36** [comment]
I followed the instructions... multiple times the end result is still the original error - 
![34e post](https://github.com/user-attachments/assets/9ca02b7d-2f05-4779-b6b4-4dc940bcace7)

This is the error that occurs every time I attempt to deploy the solution to the web application - Not sure how or why the solution is looking for a version of the .net framework that can not be deployed to the web application?

**Comment by peddivyshnavi** [comment]
Hi @michaelhadams36 
could you please disconnect the repository and wait for 30 minutes ,try to reconnect to original repository

**Comment by michaelhadams36** [comment]
I reconnected the Repo after over an hour of waiting and I still get the same .net framework issue 
![anothererror](https://github.com/user-attachments/assets/53991725-a28b-4cfa-8c0c-3d90d9597e56)

It is not clear to me why the deployment command is failing based a .net framework version verification when we are deploymen to an Azure web app.

**Comment by peddivyshnavi** [comment]
@michaelhadams36 
Could you please share your email id so we will start discussing this issue internally.

**Comment by michaelhadams36** [comment]
***@***.***

**Comment by peddivyshnavi** [comment]
@michaelhadams36 
We are checking on it we will update you shortly

**Comment by michaelhadams36** [comment]
Ok, thanks for the update.

Michael Adams

**Comment by peddivyshnavi** [comment]
We were trying to reproduce this issue from our end to troubleshoot so that we can fix this issue we will update with resolution you as soon as possible

**Comment by peddivyshnavi** [comment]
Hi @michaelhadams36 
We tried reproducing issue with all possibilities from our end but we were unable to reproduce could you please go for redeployment of Company Communicator

**Comment by peddivyshnavi** [comment]
@michaelhadams36 
Could you please update us on the status of the issue?

**Comment by michaelhadams36** [comment]
I have retried multiple time and still get the same issue when building the
web applications as outlined in the original issue

**Comment by peddivyshnavi** [comment]
Hi @michaelhadams36 
As previously stated, please proceed with redeploying CC. we suspect you are facing issue in [Deploy to your Azure subscription](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#2-deploy-to-your-azure-subscription) for that please follow below steps:
Could you please delete old resource group once after you delete old Resource group we need to purge key vaults as they will be soft deleted we need to purge key vaults manually,
 
and the steps for purge key vaults 
for that open azure portal where we have CC resource group and then search key vault and then go to manage deleted vaults then select subscription then purge the key vaults

open azure portal-->key vaults -->manage deleted key vaults-->select subscription-->select RG -->click on purge
![image](https://github.com/user-attachments/assets/ee4f29dc-b01b-446c-a3d6-edb816c4e8b6)
 or
please use different baseresourcegroup name while proceeding 2nd step

If our understanding is incorrect, could you please provide a screenshot of the error so that we can troubleshoot accordingly?

**Comment by peddivyshnavi** [comment]
@michaelhadams36 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
We are closing this ticket due to no response. Feel free to open a new GitHub issue if you encounter any problems.
