### ISSUE TITLE
Can Communicator send to multiple Teams Groups

### ISSUE THREAD

**Issue by Chris-USDA** [OfficeDev/microsoft-teams-apps-company-communicator#1558]
Can Company Communicator send messages to more than one Teams Group at a time, If answer is yes is it possible to push Company Commutator to all groups in an environment?

**Comment by peddivyshnavi** [comment]
Hi @Chris-USDA 
Thanks for reaching out to us!
We can send messages to different teams by using Company communicator. for sending to particular group we need to send message by using first option in company communicator, for sending all members in groups we need to send message using second or forth option in company communicator. but before sending via first or second option we need to make user app is added to respective teams which we need to send messages.

**Comment by peddivyshnavi** [comment]
@Chris-USDA 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
@Chris-USDA 
Could you please update us on the status of the issue?
