### ISSUE TITLE
Delivery status shows as RecipientNotFound

### ISSUE THREAD

**Issue by saranRK05** [OfficeDev/microsoft-teams-apps-company-communicator#1559]
Tried sending messages to wider company colleagues we see users are getting missed/skipped from triggering message. No logs or events showing up for those skips. We tested it with few users added to Csv and upload the same with my ID included, where only my ID received the message and another one didn't. but the report stats displayed the below, when it had two users in it. Checked Application insight failure logs and found the below exception. Kindly advise. 
**Operation:** SendMessageFunction
**Exception thrown:** Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound'.

Could see user under UserData table when we try to filter.

**Comment by peddivyshnavi** [comment]
Hi @saranRK05 
Thanks for raising the query. Could you please respond to the below queries.

- What is the version of the app?
- What the count of members in the team?
- Please share Success and failure count, supporting screenshot would be helpful
- Is this a first message?

**Comment by saranRK05** [comment]
@peddivyshnavi  - Thanks for your reply. 

Please find my response below. 

What is the version of the app? **Version 5**
What the count of members in the team? **its a AAD Security group and there were 4 members in it.** 
Please share Success and failure count, supporting screenshot would be helpful. **Below, it doesnt show any faulures, below but on sentNotificationTable we can see error with message "Recipient not found" against that user**
![image](https://github.com/user-attachments/assets/83f91fd2-66dc-4283-8813-7683a1471d7c)

Is this a first message? **Yes for the affected users. I recon.**

**Comment by peddivyshnavi** [comment]
Hi @saranRK05 
By seeing screen shot provided we see 3 users out 4 were able to receive message could you please check the one who didn't received might be admin or author.

**Comment by josh-coop** [comment]
We are seeing the same with our users, with the number of Recipient not found errors increasing with each message. It's affecting users who previously have received messages also.

**Comment by saranRK05** [comment]
> Hi @saranRK05 By seeing screen shot provided we see 3 users out 4 were able to receive message could you please check the one who didn't received might be admin or author.

No @peddivyshnavi, they are not any admin or author of the app, they are just a regular users.

**Comment by peddivyshnavi** [comment]
HI @saranRK05 
Could you please share your email id so that we can start discussing this ticket internally

**Comment by saranRK05** [comment]
@peddivyshnavi  - it would be Saran.Rajkumar@mnscorp.net

**Comment by peddivyshnavi** [comment]
Started discussing about ticket internally

**Comment by peddivyshnavi** [comment]
Connected internally and we see user was able to able to receive the messages.
Please let us know if we can close this issue as no further action is required from our end

**Comment by peddivyshnavi** [comment]
@saranRK05 
Could you please update us on the status of the issue?

**Comment by saranRK05** [comment]
@peddivyshnavi  - Yes, for affected users we had to remove the entry from UserData table and retrigger them, but this is just a Workaround and needs a fix for this issue. Not really sure what is the reason for this behavior as we normally send it to large list of recipients.

**Comment by peddivyshnavi** [comment]
@saranRK05 
Mark the ticket as closed if issue got resolved

**Comment by peddivyshnavi** [comment]
@saranRK05 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
Marking this ticket as closed
