### ISSUE TITLE
Is there a way to remove the 30-minute limitation?

### ISSUE THREAD

**Issue by Chris-USDA** [OfficeDev/microsoft-teams-apps-company-communicator#1561]
Can you send Company Communicator send messages sooner than 30 minutes? Is there a way to remove the 30-minute limitation? t

**Comment by peddivyshnavi** [comment]
Hi @Chris-USDA 
Time taken to send messages using company communicator won't take that time.
could you please confirm us whether you're referring to scheduled messages. if that's the case we can't send soon for every scheduled message it will take 30minutes of time as it is standard time to send scheduled message.

**Comment by kpalmer05** [comment]
Can this 30 minute default window be adjusted to send at a shorter interval ?
Is there a configuration/parameter that can be modified to change the default from 30 mins?

**Comment by peddivyshnavi** [comment]
@Chris-USDA 
Could you please update us on the status of the issue? if issue is resolved please feel free to mark this ticket as closed
