### ISSUE TITLE
Secret Key change

### ISSUE THREAD

**Issue by ClaudiuVio** [OfficeDev/microsoft-teams-apps-company-communicator#1562]
Hello,

Where can I find documentation for changing the secret key of the company communicator?

Thank you!

**Comment by peddivyshnavi** [comment]
Hi @ClaudiuVio 
please follow below steps for updating secrets:

- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference
![image](https://github.com/user-attachments/assets/b6f71e7b-89dd-4b92-a4b4-cad7a26aecc1)

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
![image](https://github.com/user-attachments/assets/6c162dc1-d462-4945-9eb3-1e846e0b1709)

- If the secrets are not visible, Go to Access Policy--> Click on Create

![image](https://github.com/user-attachments/assets/0821b9c7-e4d9-4e98-bd66-d4b8932193a3)

- Select Key, secret and certificate management
![image](https://github.com/user-attachments/assets/4eb27af4-7bf0-464a-b85b-7c844efc0309)

- Give the Id through which one can view the secrets
![image](https://github.com/user-attachments/assets/7982c326-6679-4194-9e88-ca02bdcdee1e)

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
![image](https://github.com/user-attachments/assets/44ec74fc-212a-4a03-92d2-f2db516f909c)

- Grab the new secret identifier
![image](https://github.com/user-attachments/assets/fa5a2de1-938a-476d-9017-5514f8cf934b)

- Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.
![image](https://github.com/user-attachments/assets/b6d4e4a8-2083-42ff-a3e2-eb5834725576)

- Follow the same procedure for the user app password and graph app password updating.
- For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference
![image](https://github.com/user-attachments/assets/ce369dbb-8aef-47bf-8e8f-06f5db1ff642)

**Comment by ClaudiuVio** [comment]
Thank you!

I did this already but I was not sure where to change it.
