### ISSUE TITLE
Sending Messages takes 3x the time than prior to updating to v5.5.2

### ISSUE THREAD

**Issue by bbruenings** [OfficeDev/microsoft-teams-apps-company-communicator#1564]
Hello together,

after we did the Update to the v5.5.2 of the Communicator, sending a message takes about 3x of what it used to be before the update.

Prior to v5.5.2
![image](https://github.com/user-attachments/assets/81d19215-ce8a-4f2c-ba78-fad97e3b88bd)

After the update to v5.5.2
![image](https://github.com/user-attachments/assets/bfa2f3b4-14bf-4a18-9eaf-87a3eccb5619)

There you can see that the SendMessage Function now takes around 4,3 seconds per message. It used to be around 1.5 before the update.

This a big issue for our customer as there company-wide messages now take up to 12 hours to be send.

I hope you can help us resolve the issue.

I'm happy to share what ever you need.

Thanks and best regards
Bennet

**Comment by MSFT-klpinhac** [comment]
Please note: a large number of people are in focus for this instance of the company communicator, so the time it takes to send the messages does actually have significant impact

**Comment by bbruenings** [comment]
Hi @peddivyshnavi 
Thanks for confirming. That also surprised me that there was no change there but we still see the change after the Deployment. Is there anything I can provide to further investigate the issue? As of my knowledge there is nothing else that changed during the update.

**Comment by peddivyshnavi** [comment]
Hi @bbruenings 
As mentioned earlier we didnt added any logic to send functionality .we will analyze further and will update you

**Comment by bbruenings** [comment]
Hi @peddivyshnavi 

I double checked which version we were coming from on production.

The update not only included the newest version 5.5.2 but also 5.5.1 and 5.5. as we were coming from 5.4.1.

Sorry for the confusion 5.5 included changes to the send feature as it included the scheduled message feature correct?

Thanks and best regards
Bennet

**Comment by peddivyshnavi** [comment]
Hi @bbruenings 
we were checking on this we will update you as early as possible

**Comment by peddivyshnavi** [comment]
HI @bbruenings 
Schedule send is separate component in send functionality we didnt added or merged schedule send with send functionality

**Comment by peddivyshnavi** [comment]
@bbruenings 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
Sure we will check accordingly

**Comment by peddivyshnavi** [comment]
we were closing ADO ticket for avoiding duplicate and we will continue discussing this issue over here.
thanks
