### ISSUE TITLE
Office Communicator App Some Features Not Working correctly in Teams

### ISSUE THREAD

**Issue by cruzrichard2527** [OfficeDev/microsoft-teams-apps-company-communicator#1565]
The application is not working at all we check with Microsoft Support Team, regarding the application configuration have been configured correctly and the application uploaded normally to the desktop Application nothing in the configuration finding the application in Teams, but the application is not working overall and there is something from the application itself so kindly we appereciate your help as per dev support team recommendation as this is very important and impacting us.

![Communicator](https://github.com/user-attachments/assets/cfa00fb3-36a5-4d11-82b4-b34fe72fbb78)

**Comment by peddivyshnavi** [comment]
Hi @cruzrichard2527 

- Could you please let us know whether its fresh deployment or old 

- could you please screenshots of all function apps

Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select function App (App Service) -->Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

- could you please share top3 traces of application insights

Go to resource group where CC app is deployed --> Go to Application insight type resource --> share the screenshot and stack trace for Top 3 response codes.

**Comment by cruzrichard2527** [comment]
Dear,

This is newly deployed it works for few days but after that it stops. Below the screenshot of the Azure Resources.

Richard

**Comment by peddivyshnavi** [comment]
Hi @cruzrichard2527 
Could you please provide mentioned screenshots for further investigation.

**Comment by peddivyshnavi** [comment]
Hi @cruzrichard2527 
could you please send screenshots in github instead of sending in mail

**Comment by cruzrichard2527** [comment]
Attached the Screenshot 
[Communicator.pdf](https://github.com/user-attachments/files/16918242/Communicator.pdf)

**Comment by cruzrichard2527** [comment]
Hi any response for this issue i already share the Screenshot in PDF format. Do let me know if you need any other information's.

**Comment by cruzrichard2527** [comment]
> Hi @cruzrichard2527 could you please send screenshots in github instead of sending in mail

I already share in PDF Format

**Comment by peddivyshnavi** [comment]
Hi @cruzrichard2527 
We will get back to you within 48 Hours.

**Comment by peddivyshnavi** [comment]
We are closing this ticket as its not pointing to our Repository
