### ISSUE TITLE
App Service Plan pricing tier Legacy Standard S2

### ISSUE THREAD

**Issue by CryogenicPotato** [OfficeDev/microsoft-teams-apps-company-communicator#1566]
The App Service Plan pricing tier that is currently being set is, if I'm not mistaken, **Standard S2** which is now considered Legacy in the Azure portal

![image](https://github.com/user-attachments/assets/b665db7c-9405-4144-827a-360f01e022e7)

I'm wondering what other Production tier you would suggest, I would go with **Premium v3 P0V3**, which offers slightly more Memory but has only one vCPU (instead of two).

What tier do you suggest choosing to replace Standard S2?

**Comment by peddivyshnavi** [comment]
Hi @CryogenicPotato 
Thanks for reaching out to us!
We will get back to you within 48 Hours.

**Comment by CryogenicPotato** [comment]
> Hi @CryogenicPotato Thanks for reaching out to us! We will get back to you within 48 Hours.

Hello? Any thoughts on this?

**Comment by peddivyshnavi** [comment]
Hi @CryogenicPotato 
For CC we support S2 app service which means v3 P1V3 app service

**Comment by CryogenicPotato** [comment]
> Hi @CryogenicPotato For CC we support S2 app service which means v3 P1V3 app service

Thank you very much!
