### ISSUE TITLE
Teams Admin - User App Installation

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1567]
Is there a way to determine which users have the Company Communicator User Application installed?

For example, if the CC User App was pushed centrally through Teams Admin but some users did not receive, it would be beneficial to have this visibility.

**Comment by peddivyshnavi** [comment]
Hi @khenry1111
Thanks for reaching out to us!
We will get back to you within 48 Hours.

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
After sending message there will be option called view status ,if you open view status you can view export detailed result click on it this will send excel report to your chat .
![Screenshot (46)](https://github.com/user-attachments/assets/c3f85af4-3b9b-4e6e-9829-b256d918fb8c)

After you allow , download the report .in downloaded file you will have message_delivery.csv file open that file.
in that file there are seperate columns called UserId ,Status Reason ,in that you can know whether app is installed in user 
<img width="481" alt="image" src="https://github.com/user-attachments/assets/650217b0-9e27-406f-9fee-7a6890d51c0a">

**Comment by khenry1111** [comment]
Ok, thank you.
