### ISSUE TITLE
“Schedule send message” and “Delete the messages” features are missing new CC version 5.5.2

### ISSUE THREAD

**Issue by SachinWandale111** [OfficeDev/microsoft-teams-apps-company-communicator#1568]
i)	We have upgraded the company communicator version from 5.3.0 to 5.5.2 recently. In team’s app the version is showing updated to 5.5.2 for both users and author applications.
ii)	During the 5.5.2 version upgradations, we have set the values (UPNs) list for “REACT_APP_AUTHORIZED_USERS_EMAIL” and “AuthorizedDeleteUpns” as they allowed to delete historical send messages.
iii)	Then saved the changes and restart the app service and sync to latest changes and changes deployed successfully as per logs in deployment center as well.
iv)	Changed the placeholder fields in both manifest files to required values appropriately.
v)	Then uploaded the new manifest files for both users and author applications from Teams admin center. Manifest uploaded successfully.
vi)	Then again restarted the app service again.
vii)	Sign-out the team’s applications and sign in again.

Note: Please refer to below screenshot which shows recent version in teams app store to 5.5.2 for company communicator app.

<img width="385" alt="image" src="https://github.com/user-attachments/assets/528cc920-798a-410d-b560-3b4d070d2be5">

**Comment by peddivyshnavi** [comment]
we have started discussing internally

**Comment by peddivyshnavi** [comment]
we have started internal discussion

**Comment by SachinWandale111** [comment]
Hi @v-jaygupta,
As discussed internally. Issue has been fixed already. Kindy close this case. Thanks

**Comment by peddivyshnavi** [comment]
Closing this ticket as this issue has been resolved by syncing three function apps.
