### ISSUE TITLE
Urgency Flag

### ISSUE THREAD

**Issue by kpalmer05** [OfficeDev/microsoft-teams-apps-company-communicator#1569]
In Microsoft Teams, I can set the priority/urgency of a message that is sent, this allows a message flagged as Urgent to notify recipients (via audible Chime/bell) when they get a message - every 2 mins until they acknowledge it.
Is there an option to set a message sent via Company Communicator as Urgent or Important ?

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
Thanks for reaching out to us!
We will get back to you within 48 Hours.

**Comment by kpalmer05** [comment]
I am a little confused. 
I am not really trying to schedule 2 minute messages, I am trying to set the Urgent flag on a CC message so that the default notification behavior (found in your Teams message window - "+" button --> "Set Delivery Options") is used. See setting below...

![Screenshot 2024-09-09 103153](https://github.com/user-attachments/assets/0d5850f6-bb95-4f27-8012-1a556af113a6)

How can I set this for a CC message (classified as urgent) ?

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
We dont support this feature as of now. We have added this feature in backlog, and we will be taking this in future depending on bandwidth and priority.

**Comment by peddivyshnavi** [comment]
@kpalmer05 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
Marking this ticket as closed as we didnt received any response from user
