### ISSUE TITLE
Expanded Reporting

### ISSUE THREAD

**Issue by kpalmer05** [OfficeDev/microsoft-teams-apps-company-communicator#1570]
Hello,
      I am trying to get more detail in the metadata report (csv) - I would like to get insight into not just which individuals received the message sent through CC but when they opened/acknowledged or interacted with the message.
Is there any way to add extra information to the metadata report ?

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
Thanks for reaching out to us!
We will get back to you within 48 Hours.

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
**I would like to get insight into not just which individuals received the message sent through CC but when they opened/acknowledged or interacted with the message.**

we can know delivery status of message 
Once after we send message we have option called view status ,if you open view status you can view export detailed result click on it this will send excel report to your chat .
![image](https://github.com/user-attachments/assets/2bc5b878-fac6-44dd-94bc-0489138ca350)
After you allow , download the report .in downloaded file you will have message_delivery.csv file open that file.
in that file there is option called status of message
![image](https://github.com/user-attachments/assets/f3b97682-d72b-4409-bf1e-bf9ab661c158)

**Comment by kpalmer05** [comment]
Does Status 201 indicate that the message was seen ?
A message could be sent and I can certainly use the report or CSV metadata file to determine the individuals that the message was "successfully" sent to - In addition to this, I am trying to determine if the individual "saw" the message....
See examples of how MS-Teams normally captures this info...just need to know how to expose this info in the CSV (metadata) report.....

![Screenshot 2024-09-09 104310](https://github.com/user-attachments/assets/18fdb774-eb37-4543-922e-cc3e6b5ddede)

![Screenshot 2024-09-09 104649](https://github.com/user-attachments/assets/d2368052-ad5f-4249-8089-5b7abfff48d8)

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
As mentioned earlier we can see delivered status of message like its been send successfully or not. we don't have any functionality or feature to say message by individual is seen or not.

**Comment by kpalmer05** [comment]
Thanks - hopefully the devs can make this an enhancement for a future CC release

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
As of now we don't support this functionality but will check in future enhancements.
Thanks 
if issue is resolved please fell free to close ticket
