### ISSUE TITLE
Missed message notification

### ISSUE THREAD

**Issue by kpalmer05** [OfficeDev/microsoft-teams-apps-company-communicator#1571]
Within the settings for Teams, I can allow Teams to set the option to send me an email 1 hour after a message is received if I have not seen or acknowledged it.
Is there a way to allow CC to leverage this setting - After testing this, I do not seem to be getting emails regarding missed CC messages ( all other non-CC messages generate a missed message email).

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
Thanks for reaching out to us!
We will get back to you within 48 Hours.

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
we don't have functionality of sending mails. we can send messages inside teams by using company communicator.

**Comment by kpalmer05** [comment]
I am not sure if CC needs to have this functionality or just use the setting already within MS-Teams for Missed Activity....again, see screenshot with activity flag highlighted in yellow:

![Screenshot 2024-09-09 105052](https://github.com/user-attachments/assets/68fb7757-b962-4d93-9f92-9276ff132add)

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
we will check on this and we will update

**Comment by peddivyshnavi** [comment]
Hi @kpalmer05 
we don't have functionality of sending mails.

**Comment by peddivyshnavi** [comment]
Marking This ticket as closed
