### ISSUE TITLE
no channels of specific teams

### ISSUE THREAD

**Issue by malvarezColabra** [OfficeDev/microsoft-teams-apps-company-communicator#1574]
Hello dev team, I have a problem with the app, the app is not showing channel or teams in the 2 first options, as you can see in the picture bellow
![Captura de pantalla 2024-09-09 100518](https://github.com/user-attachments/assets/3e071512-66e8-4993-8902-f2315c67372a)

I saw a similar post, but I can't get it to show me the teams in the first two options.
![Captura de pantalla 2024-09-09 100519](https://github.com/user-attachments/assets/fd0ddbc7-78d1-4a91-a42c-f49c3bce3f79)

Everything works perfectly, I send messages to Azure groups, and they arrive without problems, but I can't send to teams.

I appreciate your help in advance.

**Comment by peddivyshnavi** [comment]
Hi @malvarezColabra 
For making teams visible we need to add user manifest file to respective teams follow below steps:
Install User app.
Create a Teams channel with the people or Group you want to trigger user app installation to.
Navigate to installed user app from apps -> manage apps in Teams.
Click on the app and Select an option of Add to a Team.
Select created / desired Teams channel from Dropdown.
Click on set up / Submit button.
This will trigger user app installation to the Team members added to the channel.

**Comment by malvarezColabra** [comment]
You are the man, resolved in a minute
