### ISSUE TITLE
App installation error (BaseResourceName-prep-function-web)

### ISSUE THREAD

**Issue by PomskieCastillo** [OfficeDev/microsoft-teams-apps-company-communicator#1578]
During the reinstallation of the Company Communicator after deleting the whole deployment an error has been encountered. Below is the screenshot and attach is the error log from the installation.

[Uploading CompCom Deployment error prep-function-web.txt…]()
![Uploading CompanyCommunicator Screengrab error.PNG…]()

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
Thanks for reaching out to us !
Could you please share screenshot failed resource 
as the URL mentioned in ticket were redirecting to this page itself

**Comment by PomskieCastillo** [comment]
<img width="938" alt="CompanyCommunicator Screengrab error" src="https://github.com/user-attachments/assets/ac82a7b1-eb9f-4f9c-90cb-99941cc92496">

**Comment by PomskieCastillo** [comment]
[CompCom Deployment error prep-function-web.txt](https://github.com/user-attachments/files/17037805/CompCom.Deployment.error.prep-function-web.txt)

**Comment by PomskieCastillo** [comment]
Screenshot and error log has been uploaded

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 

- To overcome the failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select prep-function(or failed resource) from list of resources-->Go to Deployment Center-->Click on Settings. Below is the screenshot for reference.

![image](https://github.com/user-attachments/assets/265a66c7-f63b-482f-90d3-6a275c73ade9)

- If the resource is not pointing to intended repository and showing empty. Please connect to the external Git and point to the official repository(like above)
- Once the status turns to Success(active) in the logs section then good to proceed with remaining steps of deployment.
- Please do the same for other failed resource as well.
- After performing the above steps, don't attempt for re-deploy again

**Comment by PomskieCastillo** [comment]
After completing and updating the repository, how will I continue the deployment? or will it continue automatically? If I will not going to re-deploy the application.

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
after sync is succeesful you might not have received the authorBotId, userBotId and appDomain values at the end of the deployment. To find them, go to the "Configuration" section of your Web App.

- authorBotId: It can be found in the "AuthorAppId" field of your configuration , it will be referred to as %authorBotId%.

- userBotId:It can be found in the "UserAppId" field of your configuration , it will be referred to as %userBotId%.

- appDomain: This is the base domain for the Company Communicator app It is the value in the "AzureAd:ApplicationIdURI" field of your configuration without the "api://" e.g. appName.azurefd.net. For the following steps, it will be referred to as %appDomain%.

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
after sync is succeesful for all three function app and app service you might not have received the authorBotId, userBotId and appDomain values at the end of the deployment. To find them, go to the "Configuration" section of your Web App.

- authorBotId: It can be found in the "AuthorAppId" field of your configuration , it will be referred to as %authorBotId%.

- userBotId:It can be found in the "UserAppId" field of your configuration , it will be referred to as %userBotId%.

- appDomain: This is the base domain for the Company Communicator app It is the value in the "AzureAd:ApplicationIdURI" field of your configuration without the "api://" e.g. appName.azurefd.net. For the following steps, it will be referred to as %appDomain%.

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
after sync is successful for all three-function app and app service you might not have received the authorBotId, userBotId and appDomain values at the end of the deployment. To find them, go to the "Configuration" section of your Web App.

- authorBotId: It can be found in the "AuthorAppId" field of your configuration , it will be referred to as %authorBotId%.

- userBotId:It can be found in the "UserAppId" field of your configuration , it will be referred to as %userBotId%.

- appDomain: This is the base domain for the Company Communicator app It is the value in the "AzureAd:ApplicationIdURI" field of your configuration without the "api://" e.g. appName.azurefd.net. For the following steps, it will be referred to as %appDomain%.

**Comment by PomskieCastillo** [comment]
I understand, but should I do anything from my side to continue the deployment? or it will continue automatically? and how will I know that the deployment is complete? Thank you!

**Comment by PomskieCastillo** [comment]
<img width="877" alt="CompanyCommunicator Screengrab error-1" src="https://github.com/user-attachments/assets/c93166ae-4e6a-42d4-a8d7-c5845b777e86">

**Comment by peddivyshnavi** [comment]
@PomskieCastillo 
Once after all three function apps got success please copy all values mentioned above and continue with 3rd step [setup authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication)

**Comment by PomskieCastillo** [comment]
Thank you. Can you please provide a simple screenshot on how can I get the authorBotId and userBotId? I know it was stated in the previous comment to go to the "Configuration" section of your Web App, but I am quite lost. My first time working on this deployment.

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
In first step of deployment, we will be doing three app registrations right one for author bot, one for user bot and another for graph app.
in overview page of each app registrations we will have there respective appids for example in author app registration overview page we will be able to see applicationid i.e its  authorBotId
![image](https://github.com/user-attachments/assets/3ce81f6b-e04c-471b-bdfd-093e358e068b)
similarly for userBotId

**Comment by PomskieCastillo** [comment]
I see, so the BOTID's are the as the application ID of the webapps (Author/Client)? is that correct?

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
as mentioned earlier,
Author Appication Id, it will be referred to as %authorBotId%.
UserApplication Id , it will be referred to as %userBotId%.

**Comment by peddivyshnavi** [comment]
@PomskieCastillo 
Could you please update us on the status of the issue?

**Comment by PomskieCastillo** [comment]
I understand Thank you, I will update once done testing. Will proceed with the next step.

**Comment by PomskieCastillo** [comment]
Hello again, where can I look up for the %AppDomain%, just making sure I get the correct value.

Thank you!

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
%AppDomain% refers to Base Resource Name.azurefd.net and Base Resource Name will be resource name which you have used in [Deploy to your Azure subscription](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-certificate#2-deploy-to-your-azure-subscription) for example if you have given user as base resource name then %AppDomain% will be user.azurefd.net

**Comment by PomskieCastillo** [comment]
Thank you, I will update once done testing. Will proceed with the next step.

**Comment by PomskieCastillo** [comment]
I have completed the installation and was able to deployed both Author and Users application in our Teams tenant. But when I tried to add the Teams Author app in an MS Teams group I have created I got this error below:

![image](https://github.com/user-attachments/assets/daa7f4e7-9a11-47f2-83f3-630bf9c11362)

**Comment by PomskieCastillo** [comment]
Successfully installed Company Communicator Author app, but when tried to add it to the MS Teams channel "SAVE" button is greyed out.

![image](https://github.com/user-attachments/assets/1c88ec87-5fca-4db6-8edc-237e2f36f2de)

**Comment by PomskieCastillo** [comment]
![image](https://github.com/user-attachments/assets/dbad2912-d1f7-4572-9510-347c8203ee9f)

**Comment by PomskieCastillo** [comment]
Any update on this issue?

**Comment by peddivyshnavi** [comment]
We apologize for the delay in our response and will get back to you as soon as possible.

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
Could you please check if the following have been deployed correctly: [SetUpauthentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) ,[graph app permissions](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app),[manifest file](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages)

**Comment by PomskieCastillo** [comment]
Will check them but initially during deployment the values are correct and followed the steps correctly.

**Comment by peddivyshnavi** [comment]
We are closing this ticket due to no response. Feel free to open a new GitHub issue if you encounter any problems.

**Comment by PomskieCastillo** [comment]
> Hi @PomskieCastillo Could you please check if the following have been deployed correctly: [SetUpauthentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) ,[graph app permissions](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app),[manifest file](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages)

Performed the following and doubled checked and made some changes but when I tried to add the Author again in a Channel still SAVE button is disabled.

Do I need to restart anything? I mean restart the application or anything else needs tobe done.
