### ISSUE TITLE
Resend functionality only to failed recipients

### ISSUE THREAD

**Issue by nianton** [OfficeDev/microsoft-teams-apps-company-communicator#158]
On an installation with around 8K users, on some enterprise-wide messages the intended recipients will be all of them. After having a few failed dispatches, currently there is a no way to resend the message only to failed ones or no easy way to target them on a subsequent duplicated message.

Feature request: Would it possible to add an option to resend a message when there are failures, to the recipients for which the previous dispatch failed.

**Comment by rashmi-dixit** [comment]
Thank you for sharing the idea and will be shared with concerned team.
