### ISSUE TITLE
Company Communicator not working after the Secret key got expired

### ISSUE THREAD

**Issue by Nadeem-hussain-mafgs** [OfficeDev/microsoft-teams-apps-company-communicator#1580]
Company Communicator not working after the Secret key got expired.
Create and updated new secret keys but still error is same.

The Error message says "Sorry, an error occurred while trying to access this service".

Checked it from Client and same isue

**Comment by peddivyshnavi** [comment]
Hi @Nadeem-hussain-mafgs 
Please cross verify once again w.r.t secrets renewal with the below steps.

- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.

![image](https://github.com/user-attachments/assets/33406630-0ae4-4077-8dbc-960a545ddcdf)

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
![image](https://github.com/user-attachments/assets/7f5dd8f8-8bef-42dc-8e62-4af44eb59f8a)

- If the secrets are not visible, Go to Access Policy--> Click on Create
![image](https://github.com/user-attachments/assets/e777dd98-ffd5-4610-9fc0-59b54d15337d)

- Select Key, secret and certificate management

![image](https://github.com/user-attachments/assets/eb76d98a-8f38-433e-a024-02a459786d72)

- Give the Id through which one can view the secrets
![image](https://github.com/user-attachments/assets/768af960-ab4f-4c86-9223-c931619da0d6)

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
![image](https://github.com/user-attachments/assets/98890622-9f7e-4708-8f75-2a3c907b7c39)

- Grab the new secret identifier
![image](https://github.com/user-attachments/assets/0f786726-88f6-4d80-8223-01597fbda0a0)

- Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.
![image](https://github.com/user-attachments/assets/6e2933de-557b-4b5f-a4e0-030c4e4a698a)

- Follow the same procedure for the user app password and graph app password updating.
- For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference
![image](https://github.com/user-attachments/assets/47b0443a-0e79-41da-96ff-c81a3384e53d)

**Comment by peddivyshnavi** [comment]
Hi @Nadeem-hussain-mafgs 
connected internally Let us know if you still have any problems; otherwise, please close the ticket.
