### ISSUE TITLE
App not installed error for User Company Communicator App (users are not recieving messages)

### ISSUE THREAD

**Issue by Saraanuzzi** [OfficeDev/microsoft-teams-apps-company-communicator#1581]
We have been able to deploy the company communicator app.

As a part of testing we tried sending message to Team, where a test users were part of.
We are able to draft and preview the message in Author app. While trying to send it to the users via Team (M365 Group) we are getting error with no users recieving messages. On checking the report logs, it mentions App not installed for all the users, where as as logged in as test user, we can see the App present and can open to check for messages.

Sharing screenshot of Log report:
![image](https://github.com/user-attachments/assets/9aaae014-608f-4878-9ebe-6a2612696ef0)

**Comment by peddivyshnavi** [comment]
Hi @Saraanuzzi 
Could you please confirm us whether you were able to send messages via 1st and 2nd option.

also Please confirm whether the issue affects only these two users or everyone. Also, could you check if there are any app policies restricting these users?

**Comment by Saraanuzzi** [comment]
Hello, @peddivyshnavi 
I did some tests, created a new distribution list, inserted the two users and generated a new message without success.
The problem is affecting around 30/40% of the company, I used this log from my last test, but I am experiencing failure with a lot of users, including mine, mine is not receiving it.
The policy is enabled for all users in the organization.

![image](https://github.com/user-attachments/assets/32cd784e-522a-4681-8bbe-c7010c44cd75)

**Comment by peddivyshnavi** [comment]
Hi @Saraanuzzi 
We will get back to you as soon as possible

**Comment by peddivyshnavi** [comment]
Hi @Saraanuzzi 
Could you please share mail id so that we can start discussing this issue internally

**Comment by Saraanuzzi** [comment]
Hi @peddivyshnavi 

Of course, it would be the corporate email, right?
sara.pereira.tobrasil@cnpseguradora.com.br

**Comment by peddivyshnavi** [comment]
We have started discussing this issue internally

**Comment by Saraanuzzi** [comment]
Hello,
 
Procedure carried out unsuccessfully.
 
I followed the instructions step by step and still have the same problems.
![image](https://github.com/user-attachments/assets/f52f65d2-93a9-4615-9a11-29999b0ef33f)

**Comment by Saraanuzzi** [comment]
Hello @peddivyshnavi 

After disconnecting and reconnecting the function applications, I carried out a new test and still have the same error.

![Captura de tela 2024-11-05 121734](https://github.com/user-attachments/assets/36295412-ec1f-4603-8d8f-4664ff346ab0)

Guys, our organization is very impacted by the incident, I need an alternative to be able to use the application.
And I don't know what happened, I can't view the chat on Teams anymore

**Comment by tiwariShiv7** [comment]
Hi @Saraanuzzi, Can you please send the Failures screenshot ?
TO do this 
Go to resource group where CC app is deployed --> Go to Application insight type resource --> Go to Failures section from Left hand side menu --> share the screenshots and stack trace for Top 3 response codes and Top 3 failures

**Comment by Saraanuzzi** [comment]
Hello @tiwariShiv7 

Failures follow as requested.
I would like to point out that my case was already being analyzed by @peddivyshnavi e we have already gone through this stage.
I would like to suggest that we implement CC again, I believe it will be faster and maybe solve the problem.
![Falha CC](https://github.com/user-attachments/assets/1c308fd0-88a6-47d4-a32b-eaca541fba3d)

**Comment by tiwariShiv7** [comment]
Hi @Saraanuzzi Thanks for this. One more thing can you also check Reason for the failure by exporting the sent message data and send us the screenshot?

**Comment by Saraanuzzi** [comment]
![17309773690335156232648692708960](https://github.com/user-attachments/assets/fdd34fb2-1890-49ce-9d43-dc9365ad3560)

**Comment by Saraanuzzi** [comment]
Hello @tiwariShiv7 
Any feedback?

**Comment by tiwariShiv7** [comment]
Hi @Saraanuzzi , I'll check this internally with Teammate who attended the call earlier and will share the suggestions from our side.

**Comment by Saraanuzzi** [comment]
Hello @tiwariShiv7
Any feedback?

**Comment by Saraanuzzi** [comment]
Hello @tiwariShiv7
Any feedback?

**Comment by Saraanuzzi** [comment]
Hello @tiwariShiv7
Any feedback?

**Comment by Saraanuzzi** [comment]
Hello @tiwariShiv7
Any feedback?

**Comment by Saraanuzzi** [comment]
Good afternoon.

We have not received any feedback and the problem is unresolved, can you please give us a response?

**Comment by tiwariShiv7** [comment]
Hey @Saraanuzzi , Thanks for your patience. Last we checked you tried to reconnect and sync again. Can you please send us the screenshot of error from Failures once ?

**Comment by Saraanuzzi** [comment]
Hello, I managed to resolve the error I was getting before by uninstalling and installing again.
Now I'm getting another error:
![image](https://github.com/user-attachments/assets/1412c7d7-84d7-48c7-8687-b79b425b98e2)

![image](https://github.com/user-attachments/assets/e573d305-ba4c-4542-b8f7-58e1028be59d)

**Comment by v-jaygupta** [comment]
@Saraanuzzi ,
Thanks for the conifrmation! 
If no further action is required at this time, and we do not receive a response, we will close this issue in two business days. Should any concerns arise, you may open a new issue or respond to this message.
