### ISSUE TITLE
Issue with Admin app not loading in Teams Channel tab   

### ISSUE THREAD

**Issue by ArunkumarTMEYGDS** [OfficeDev/microsoft-teams-apps-company-communicator#1582]
Hi Team, 

We were able see the Admin app (v 5.5.2) in PROD environment and send test message until yesterday for one of the **MS Team** Members. Others were not able to send though. But today none of our **MS Team** Members are able to load the Admin app. 
It shows blank white screen for first few minutes and throws the error as shown in screenshots below.

<img width="716" alt="A1" src="https://github.com/user-attachments/assets/42c96d70-eae3-4584-8ed2-77d074308302">
<img width="723" alt="A2" src="https://github.com/user-attachments/assets/d7531e16-eaaa-4caf-b967-eedbd9821e91">

Sharing screenshot of error logs in Azure where there is no error as well.
<img width="670" alt="A3" src="https://github.com/user-attachments/assets/68118f54-29ee-439e-9bed-7618f6fb813d">

**Note that App service and all three function apps are already successfully in sync.**

Please consider this on high priority as this is a roadblocker for us at organization level.

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
The problem appears to be at the Azure level. Could you please provide a screenshot of the dependencies on the application insights page

**Comment by ArunkumarTMEYGDS** [comment]
> Hi @ArunkumarTMEYGDS The problem appears to be at the Azure level. Could you please provide a screenshot of the dependencies on the application insights page

Sharing requested screenshot.
<img width="673" alt="A4" src="https://github.com/user-attachments/assets/0d2405cc-5ce3-490d-bce2-028cdfc7d9ec">

**Comment by ArunkumarTMEYGDS** [comment]
Hi All, 

We were able to fix the above mentioned issue. We were checking on health check of all the Apps services. Since the service seemed to be down, we checked on the URLs of Azure front door host and App default domain by using ping in command prompt as well as via browser to get same results of service unavailable as shown below.

<img width="671" alt="X1" src="https://github.com/user-attachments/assets/83e01160-6b5a-4bcf-b569-80927c075d1b">
<img width="601" alt="X2" src="https://github.com/user-attachments/assets/5f6f41b4-71d4-434d-bf73-721d2c875c73">
<img width="265" alt="X3" src="https://github.com/user-attachments/assets/f3f05de3-e843-4cfd-a61c-d9d331187b72">
<img width="345" alt="X4" src="https://github.com/user-attachments/assets/17b192d9-ba4e-42a6-9d4c-96a4c9c8b6fc">
<img width="672" alt="X5" src="https://github.com/user-attachments/assets/603e5772-1f30-4717-8d48-272c688dab30">
<img width="227" alt="X6" src="https://github.com/user-attachments/assets/816fc9c6-a028-4732-9ddc-d74ee370209f">

This helped us identify and troubleshoot. We went to Web App Health check section -> Instances as shown below

<img width="672" alt="X7" src="https://github.com/user-attachments/assets/47afc444-7b29-44d6-9ce8-666e6411db16">

Here we simply Restarted the server instance and after some the everything started working. 
Not sure if this would be recurring concern but its been a week now and still up and running.

**Comment by peddivyshnavi** [comment]
We apologize for the delay in our response and will get back to you as soon as possible.

**Comment by peddivyshnavi** [comment]
Hi @ArunkumarTMEYGDS 
Issue seems to be resolved
