### ISSUE TITLE
when try to add the app to a teams channel "Something went wrong"

### ISSUE THREAD

**Issue by Chuksphil** [OfficeDev/microsoft-teams-apps-company-communicator#1583]
Hello 

Please I get this error message "Something went wrong" when I try to add the app to a team's channel, also when adding the app from inside the teams channels the save button is greyed out

<img width="463" alt="commsapp" src="https://github.com/user-attachments/assets/baf8ac73-db7c-40ac-bf78-203b8a56800b">

<img width="463" alt="Screenshot 2024-09-24 102816" src="https://github.com/user-attachments/assets/35e94199-edf0-43c8-9760-c2db8006cfb0">

Please I need assistance om this and also any document or video on troubleshooting teams company communicator app

**Comment by peddivyshnavi** [comment]
Hi @Chuksphil 
Could you please check if the following have been deployed correctly:  [SetUpauthentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) ,[graph app permissions](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app),[manifest file ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages)

**Comment by peddivyshnavi** [comment]
We apologize for the delay in our response and will get back to you as soon as possible.

**Comment by peddivyshnavi** [comment]
Hi @Chuksphil 
Could you please validate the [manifest file](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages)
