### ISSUE TITLE
Deployment sync fails with .NET error

### ISSUE THREAD

**Issue by lazarovidiu** [OfficeDev/microsoft-teams-apps-company-communicator#1584]
Hi,
We have updated to Workspace-based Application Insights as per the documentation with no issue.
Afterwards we followed the steps to update the application from 5.2.0 to the latest version and the sync is failing with the below error.
I have tried disconnecting the deployment and reconnecting it but it still failed.

Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
Failed exitCode=-2147450730, command=dotnet restore "C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.sln"
You must install or update .NET to run this application.
An error has occurred during web site deployment.

App: C:\Program Files (x86)\dotnet\sdk\6.0.424\dotnet.dll
Architecture: x86
Framework: 'Microsoft.NETCore.App', version '6.0.32' (x86)
.NET location: C:\Program Files (x86)\dotnet\

The following frameworks were found:
  1.0.16 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  1.1.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.0.9 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.1.30 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  2.2.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  3.0.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  6.0.29 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.19 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  8.0.5 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  8.0.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.32&arch=x86&rid=win-x86&os=win10
You must install or update .NET to run this application.\r\n\r\nApp: C:\Program Files (x86)\dotnet\sdk\6.0.424\dotnet.dll\r\nArchitecture: x86\r\nFramework: 'Microsoft.NETCore.App', version '6.0.32' (x86)\r\n.NET location: C:\Program Files (x86)\dotnet\\r\n\r\nThe following frameworks were found:\r\n  1.0.16 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  1.1.13 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.0.9 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.1.30 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  2.2.14 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  3.0.3 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  3.1.32 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  5.0.17 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  6.0.29 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  7.0.19 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  7.0.20 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  8.0.5 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n  8.0.7 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]\r\n\r\nLearn more:\r\nhttps://aka.ms/dotnet/app-launch-failed\r\n\r\nTo install missing framework, download:\r\nhttps://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.32&arch=x86&rid=win-x86&os=win10\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.100729.001\bin\Scripts\starter.cmd deploy.cmd

**Comment by peddivyshnavi** [comment]
Hi @lazarovidiu 
Thanks for reaching out to us.
Could you Please confirm us with the following.

Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select function App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].
And please share the screenshots of all three Function Apps and Deployment Center

**Comment by lazarovidiu** [comment]
Hi @peddivyshnavi 
Thank you for the quick reply.
App Service Deployment Center settings and logs:
![image](https://github.com/user-attachments/assets/589b466a-6159-44f0-9998-fc5ab896204f)
![image](https://github.com/user-attachments/assets/279835e6-ffc9-4432-8c99-367affa7c49a)
![image](https://github.com/user-attachments/assets/52a823d7-c78f-43e6-ac28-b06eeb85e0c0)

All three functions (data-function, prep-function and function) have the same settings and logs:
![image](https://github.com/user-attachments/assets/f4aa3a4d-810d-44c8-95e9-206e780ebd18)
![image](https://github.com/user-attachments/assets/43fb4bc2-1b2a-47ae-9c43-cc2faed1d696)

**Comment by peddivyshnavi** [comment]
Hi @lazarovidiu 
I would suggest please disconnect the repo From Deployment center of App service then wait for 1 to 2 hours All logs will get cleared. Once there is nothing in the logs Please select External Git -> Enter Repo Name and Branch name as 'main'. Click save and Sync it one more time.

Refer [Troubleshooting guide Point #5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#5-app-service-sync-throws-npm-error)

**Comment by lazarovidiu** [comment]
Hi @peddivyshnavi I have left it over 2 hours disconnected and reconnected the deployment and we are still getting the same error.
![image](https://github.com/user-attachments/assets/3601061e-6c03-445f-ae04-6259c0339a8a)

**Comment by ndl7** [comment]
Same issue here, tried different branches, but no luck.

**Comment by lazarovidiu** [comment]
Hi @peddivyshnavi, any updates you can provide on this issue?

**Comment by peddivyshnavi** [comment]
We apologize for the delay in our response and will get back to you as soon as possible.

**Comment by peddivyshnavi** [comment]
Hi @lazarovidiu 
We have attempted various methods to replicate the issue on our end to find a solution, but nothing is working as expected. Could you please try redeploying CC

**Comment by peddivyshnavi** [comment]
Hi @lazarovidiu 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
We are closing this ticket due to no response. Feel free to open a new GitHub issue if you encounter any problems.
