### ISSUE TITLE
Is it possible to have multiple communicator bots?

### ISSUE THREAD

**Issue by thowardtw** [OfficeDev/microsoft-teams-apps-company-communicator#1585]
Hi

Is it possible to have multiple communicator bots for different departments in the business?

For example, one controlled by IT to send out IT updates and another one controlled by the Marketing team to send out updates.

Is it a case of deploying another set of communicator resources in Azure and uploading another set of Teams apps?

Thanks

**Comment by thowardtw** [comment]
I think I've answered this from a previous ticket - Secondary Bot Within Same Organisation #1455

Looks like it is possible.

**Comment by peddivyshnavi** [comment]
Hi @thowardtw 
Thanks for reaching out to us!
It is possible to have multiple instances of Company Communicator within the same tenant, but we need to perform two checks before continuing.

- For second instance the parameter user app external id need to be updated with a valid GUID and the same GUID need to be updated in the user manifest file. Below are the two places which needs to be updated with a new valid GUID.
![image](https://github.com/user-attachments/assets/2ec8f2ec-976d-4ef0-817e-bf006f1a1342)

![image](https://github.com/user-attachments/assets/bc8c62bf-ea88-4749-94a0-c36bcd099072)

-  for second instance and so on, grab a new valid GUID and paste in the author manifest file. Below is the reference.
![image](https://github.com/user-attachments/assets/3f856f2e-6889-45f8-9d85-a56f55f8cf1d)

 for reference please refer [Multiple instance of Company Communicator in the same tenant](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#4-multiple-instance-of-company-communicator-in-the-same-tenant-action-items)
