### ISSUE TITLE
Change profile picture

### ISSUE THREAD

**Issue by maureris** [OfficeDev/microsoft-teams-apps-company-communicator#1588]
I need to change the profile picture. But we can't. Is there any topic about this subject?

**Comment by peddivyshnavi** [comment]
Hi @maureris 
Thanks for reaching out to us 
We will respond to you as soon as possible.

**Comment by peddivyshnavi** [comment]
Hi @maureris 

- To update the Profile Picture or Logo, in manifest file replace the ‘color’ image with the logo customer want to use, please make sure to use the same size and dimension of the image

- Please delete the uploaded manifest file and create a new zip file with these changes and reupload in the Teams admin centre 

- Make sure to clear the Teams cache, you can find the steps [here](https://answers.microsoft.com/en-us/msteams/forum/all/clear-cache/0810ce4f-af14-4269-b01f-adc89a0af4c4)

**Comment by maureris** [comment]
Hi @peddivyshnavi,

Thank you for fast response, I will try this anda come back today to give feedback.

**Comment by peddivyshnavi** [comment]
Hi @maureris 
Could you please update us on the status of the issue?

**Comment by peddivyshnavi** [comment]
Hi @maureris
Could you please update us on the status of the issue?

**Comment by maureris** [comment]
Hi @peddivyshnavi ,
Sorry for the delay, today we had confirmation that it worked.
Thank you
