### ISSUE TITLE
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by stehodge** [OfficeDev/microsoft-teams-apps-company-communicator#1589]
Please reference case 1508 for history.  After a new installation and new deployment, when adding the authors app back to a Team, I get the following error.  The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by peddivyshnavi** [comment]
Hi @stehodge 
Thanks for reaching out to us 
We will respond to you as soon as possible.

**Comment by peddivyshnavi** [comment]
Hi @stehodge 

- Could you verify if the app domain value in the Author manifest file has been entered correctly?


- App service deployment failure could be the reason. So, Please verify the deployment status as mentioned here: [Troubleshooting · OfficeDev/microsoft-teams-apps-company-communicator Wiki (github.com)](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure)

**Comment by stehodge** [comment]
The three values match up in the author's manifest file.

**Comment by peddivyshnavi** [comment]
We have started discussing about this ticket internally

**Comment by stehodge** [comment]
ok
