### ISSUE TITLE
Error when creating NEW Message after adding the Author App to Teams channel after fresh install.

### ISSUE THREAD

**Issue by PomskieCastillo** [OfficeDev/microsoft-teams-apps-company-communicator#1590]
When adding the Company Communicator Author app from a fresh install I got blank dialog box and save button is disabled

![image](https://github.com/user-attachments/assets/9be08ac9-7e7c-4ffa-aed0-07d13619bd5e)

**Comment by PomskieCastillo** [comment]
An update, able to setup and add Author App in Teams Channel, but an error appears when trying to create NEW MESSAGE

![image](https://github.com/user-attachments/assets/740e3c1c-1b6f-4648-9d5b-1e3ae8b92b7c)

**Comment by PomskieCastillo** [comment]
AuthorizedcreatorUPNS is correct and that is me by the way.

![image](https://github.com/user-attachments/assets/0bc30af4-4f11-419c-b859-6397ec7cea87)

**Comment by PomskieCastillo** [comment]
Any support here wants to answer the queries?

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
Could you please check whether [app permission ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) where added correctly i.e those permissions needs to be added only for graph app registration.

**Comment by PomskieCastillo** [comment]
Hi @peddivyshnavi yes, upon checking the App Permission are added correctly based on the instruction stated in the wiki. Please see screenshot below:

![image](https://github.com/user-attachments/assets/5ff33b11-9be3-4154-8c1a-3d7642776024)

**Comment by peddivyshnavi** [comment]
Hi @PomskieCastillo 
please share your email id so that we will start discussing this issue internally

**Comment by PomskieCastillo** [comment]
you may contact me using sherwin.castillo@notified.com (email address/MSTeams)

**Comment by andresioncm** [comment]
Hello guys, also I´m having the same issue is possible to include a copy for andre.sion@cloudmotion.com.br ?

**Comment by peddivyshnavi** [comment]
Connected with customer internally marking this ticket as closed as issue got resolved
