### ISSUE TITLE
Messages stuck on Queued then vanishes after .Net 6 update

### ISSUE THREAD

**Issue by DonMudi** [OfficeDev/microsoft-teams-apps-company-communicator#1594]
Hi,

Messages are not sending they are sitting on Queued and then disapperars.

**Comment by peddivyshnavi** [comment]
Hi @DonMudi 
Thanks for reaching out to us
We will get back to you ASAP

**Comment by peddivyshnavi** [comment]
Hi @DonMudi 
Could you please inform us if this is a fresh deployment, or you are trying to migrate from an existing version to a new version?
if you are trying to migrate, Have you performed the scripting that is present in the migration guide. If yes, please share the screenshots of function apps showing the run time version as ~4 and app service is set to .NET 6.0. Here is the reference [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#1-update-the-net-version-of-azure-functions-and-app-service-to-support-net-60-)

**Comment by DonMudi** [comment]
Hi,

App was working flawlessley for 2 years, then Secrets expired. I renewed secrets and applied in keyvault and changed where necessary. Restarted services, it didnt come back up. Then i saw the .net 6 update. 

I have followed the steps and updated to  .NET 6.0 made sure it it has ~4 runtime version.

Issue still remains same, messaged only queued, not sending.

Do you have remote help available?

**Comment by peddivyshnavi** [comment]
Hi @DonMudi 
Please cross verify once again w.r.t secrets renewal with the below steps.

- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.
- 
![image](https://github.com/user-attachments/assets/18e5a17f-9d49-4ce5-a672-c6f8312da122)

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
- 
![image](https://github.com/user-attachments/assets/27ed0cfb-2c06-41a0-bdeb-026a9adf3ecd)

- If the secrets are not visible, Go to Access Policy--> Click on Create
- 
![image](https://github.com/user-attachments/assets/fe832c79-2d55-4492-b40d-34433b59df2f)

- Select Key, secret and certificate management
- 
![image](https://github.com/user-attachments/assets/9208628a-8afe-4da9-895a-3080bbc9b5f3)

- Give the Id through which one can view the secrets
- 
![image](https://github.com/user-attachments/assets/ea3ff3fa-6e5b-4d98-ac93-230f5f802f89)

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
- 
![image](https://github.com/user-attachments/assets/5d78c473-5890-4c32-b099-c3ef5b8905a4)

- Grab the new secret identifier
- 
![image](https://github.com/user-attachments/assets/1eecce4e-2a32-4710-b0ed-2d796eedf818)

- Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.
- 
![image](https://github.com/user-attachments/assets/12f1495c-9acb-4673-9311-f3a97966d68f)

- Follow the same procedure for the user app password and graph app password updating.
- For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference
![image](https://github.com/user-attachments/assets/9864019f-c848-40e7-aa92-bbaf1f956303)

**Comment by DonMudi** [comment]
Hi There,

I have already followed the instructions and now verified. 
Access policy
![image](https://github.com/user-attachments/assets/907b4e8a-b03d-4479-ac97-827ccbd4320b)

**Comment by DonMudi** [comment]
We got rid of the app after 2 years. .Net 6 upgrade and certificate renew broke the application.
