### ISSUE TITLE
Query around TLS version upgrade on Azure Bus service Namespace used in CC App

### ISSUE THREAD

**Issue by saranRK05** [OfficeDev/microsoft-teams-apps-company-communicator#1595]
Hello Team, 
Just need some clarifications around TLS version changes to our company communicator instances that are hosted in our Azure RG;s. 

As of Microsoft health advisory, it has been advise to update azure resources to TLS 1.2 or later. We have looked through certain azure resources within CC App like Azure service Bus Namespace and can see its set to TLS 1.0 minimum. Would needs change to 1.2 or later? if so will it have any impact to other interactions. 

![image](https://github.com/user-attachments/assets/6b32c375-97e4-41c1-a306-cafe365ee989)

**Comment by peddivyshnavi** [comment]
Hi @saranRK05 
Thanks for reaching out to us
We will check and will get back to you

**Comment by peddivyshnavi** [comment]
Hi @saranRK05 
We tried to reproduce this scenario from our end by changing TLS from 1.0 to 1.2 in service bus.
There is no issue in CC regarding sending messages and other functionality like delete.

**Comment by saranRK05** [comment]
@peddivyshnavi  - Thanks for your update, I will try to test from my end and shall update. Meanwhile can you also help to check if there are any other resources with In CC App that users TLS 1.0? I will checking all the configs, but wanted to take some help. Thanks.

**Comment by peddivyshnavi** [comment]
Hi @saranRK05 
Upon investigation, we have observed that for other functionalities within the resource group, TLS version 1.2 is set as the default.

**Comment by saranRK05** [comment]
@peddivyshnavi  - Thanks for the update. You can close this thread off. I will test from my end and shall get back if we encounter any issues.

**Comment by peddivyshnavi** [comment]
Marking this ticket as closed
