### ISSUE TITLE
Issue updating Logo and changing name

### ISSUE THREAD

**Issue by ahlim0011** [OfficeDev/microsoft-teams-apps-company-communicator#1596]
Hi,

Could we schedule a Teams call? I tried updating the company logo and name, but it has caused some issues. Thanks!

**Comment by peddivyshnavi** [comment]
Hi @ahlim0011 

- Please share screenshots of the Short name in the users and author manifests you uploaded in Teams as mentioned above.
- also please share bot profile

**Comment by peddivyshnavi** [comment]
@ahlim0011 
Could you please update us on the status of the issue?

**Comment by v-jaygupta** [comment]
Hello @ahlim0011 ,
Could you please update us on the status of the issue?

**Comment by ahlim0011** [comment]
Hi,

This didn’t work, can we have a teams call?


ABDUL HALIM
IT Support Administrator
***@***.***
+44 20 7665 5009 direct
12 Gough Square
​London ​EC4A 3DW
+44 20 7665 5000
hausfeld.com
This email is confidential and may be legally privileged. If you have received it in error, please contact me immediately. Hausfeld & Co. LLP is a limited liability partnership registered in the State of New York and is authorised and regulated by the Solicitors Regulation Authority ('SRA') in England & Wales with number 513826.

**Comment by tiwariShiv7** [comment]
Hi @ahlim0011, We can start a Teams Conversation. Please share your Timezone and e-mail ID to reach out.

**Comment by ahlim0011** [comment]
Hi,

Do you have any slots this afternoon 2pm London time?


ABDUL HALIM
IT Support Administrator
***@***.***
+44 20 7665 5009 direct
12 Gough Square
​London ​EC4A 3DW
+44 20 7665 5000
hausfeld.com
This email is confidential and may be legally privileged. If you have received it in error, please contact me immediately. Hausfeld & Co. LLP is a limited liability partnership registered in the State of New York and is authorised and regulated by the Solicitors Regulation Authority ('SRA') in England & Wales with number 513826.

**Comment by tiwariShiv7** [comment]
Hi @ahlim0011, Yes we can become available during the mentioned time on a different date but to connect with you we would be needing your e-mail address to connect.

**Comment by v-jaygupta** [comment]
@ahlim0011 ,
Could you please share your email id so that we can start discussing this issue internally over teams?

**Comment by v-jaygupta** [comment]
@ahlim0011 ,
Could you please update us on the status of the issue. If the issue still persist, please share your email id so that we can start discussing this issue internally over teams?

**Comment by v-jaygupta** [comment]
@ahlim0011 ,
Could you please let us know if the issue still persists. If not, can we close this issue?

**Comment by ahlim0011** [comment]
Sorry was on leave can we have a meeting this week?


ABDUL HALIM
IT Support Administrator
***@***.***
+44 20 7665 5009 direct
12 Gough Square
​London ​EC4A 3DW
+44 20 7665 5000
hausfeld.com
This email is confidential and may be legally privileged. If you have received it in error, please contact me immediately. Hausfeld & Co. LLP is a limited liability partnership registered in the State of New York and is authorised and regulated by the Solicitors Regulation Authority ('SRA') in England & Wales with number 513826.

**Comment by ahlim0011** [comment]
Hi,

Was on leave, can you we still have a meeting.


ABDUL HALIM
IT Support Administrator
***@***.***
+44 20 7665 5009 direct
12 Gough Square
​London ​EC4A 3DW
+44 20 7665 5000
hausfeld.com
This email is confidential and may be legally privileged. If you have received it in error, please contact me immediately. Hausfeld & Co. LLP is a limited liability partnership registered in the State of New York and is authorised and regulated by the Solicitors Regulation Authority ('SRA') in England & Wales with number 513826.

**Comment by ahlim0011** [comment]
Hi, can we open this ticket please, thanks.
