### ISSUE TITLE
Problema ao acessar o aplicativo de autores

### ISSUE THREAD

**Issue by devSLMIT** [OfficeDev/microsoft-teams-apps-company-communicator#1597]
Após realizar o deploy e conceder todos os acessos, ao abrir o aplicativo já adicionado à equipe é apresentado o erro da imagem.
![image](https://github.com/user-attachments/assets/e96deeed-4f64-4309-a1b2-c7a5275a4e76)

**Comment by peddivyshnavi** [comment]
Hi @devSLMIT 
Thanks for reaching out to us
Could you please share a screenshot of the app service status 

- for that please navigate to resource group where CC is deployed 
- and open app service ,under deployment click on deployment center

<img width="665" alt="image" src="https://github.com/user-attachments/assets/fd5113fb-a2ec-4e2d-beb1-4b4b42884cae">
<img width="720" alt="image" src="https://github.com/user-attachments/assets/e6831407-a437-41e3-b3a7-e731ee1a8f3e">
and also please share the status of all functions also.

**Comment by devSLMIT** [comment]
Obrigado! Foi resolvido, era permissão ao usuário nas variáveis de ambiente.
Eu atualizei a variável que faz a validação de Authors para true para desativar essa validação.
Muito obrigado!
