### ISSUE TITLE
Unable to resolve service for type 'Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.MicrosoftGraph.IUserService

### ISSUE THREAD

**Issue by moonncat** [OfficeDev/microsoft-teams-apps-company-communicator#1598]
We found some errors in API since the end of 2023:
the /api/userD throws error mentioning "Unable to resolve service for type 'Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.MicrosoftGraph.IUserService' which attempting to activate 'Microsoft.Teams.Apps.CompanyCommunicator.Controller.UserDataController'."
so the user list can't be up to date.

**Comment by peddivyshnavi** [comment]
Hi @moonncat 

- could you please let us know whether its fresh deployment or old deployment

- Could you please share the error the supporting screenshot of error from application insights resource from the deployed resource group.

Go to resource group where CC app is deployed --> Go to Application insight type resource --> share the screenshot and stack trace for Top 3 response codes.

- also please share Top 3 response codes

- Could you please share a screenshot of the app service status

- for that please navigate to resource group where CC is deployed
- and open app service ,under deployment click on deployment center
- 
![image](https://github.com/user-attachments/assets/79a9d95a-8fee-459c-8f98-b0c6336c8f7f)

![image](https://github.com/user-attachments/assets/e73eb479-0eca-488c-886a-8a99af3627c5)

and also please share the status of all functions also.

**Comment by moonncat** [comment]
Thanks for your swift response. your support is appreciated.

1，it is a old deployment which happened in June/2022.
2, the application insights shows below error:
at Microsoft.Identity.Client.AcquireTokenSilentParameterBuilder.Validate(...
Microsoft.Identity.Client.AbstractAcquireTokenSilentParameterBuilder`1.ValidateAndCalculateApiId (...
at Microsoft.Identity.Web.TokenAcquisition (...

It seems got error in building the IUserService implementation.

3, all the response code in GET UserData/GetAllUserData are 500.

4, sorry for the security restrictions, I can't share the screenshot. but i have checked the deployment center, it is not yet setup. I think it is because we used a package to deploy instead of source code.

5, all functions are running normally.

6, the build of the dotnet version is v3.1
Graph version is 3.22
Microsoft.Identify.Web is 0.1.3-preview
Micosoft.Aspnetcore is 3.1

**Comment by peddivyshnavi** [comment]
Hi @moonncat 
Could you please check whether app registrations got expired

**Comment by moonncat** [comment]
hi @peddivyshnavi , I have renewed all the secrets in all environment variables:
1, AppSecretUser / AppSecretAuthor etc in app service.
2, we did the similar update in Azure Function as well.
3, Secret in AKV also got updated.

please kindly advice is there anything missed out? thanks.

**Comment by peddivyshnavi** [comment]
Hi @moonncat 
We suspect secrets got configured incorrectly Please cross verify once again w.r.t secrets renewal with the below steps.

- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.
- 
![image](https://github.com/user-attachments/assets/162776e1-58db-48ca-879c-144de358d5df)

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
- 
![image](https://github.com/user-attachments/assets/e2295922-6201-4e28-b360-caac037506ef)

- If the secrets are not visible, Go to Access Policy--> Click on Create
![image](https://github.com/user-attachments/assets/f926c393-5246-4bfc-b4b1-4350627c7b99)

- Select Key, secret and certificate management
- 
![image](https://github.com/user-attachments/assets/9d6c0b8c-6596-49c0-be6b-12b753a016b6)

- Give the Id through which one can view the secrets
- 
![image](https://github.com/user-attachments/assets/b50f3a39-f9eb-472f-acd3-49b60c422cce)

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
- 
![image](https://github.com/user-attachments/assets/2a7b91c4-fe8c-4dce-bfed-e176c0c0ea13)

- Grab the new secret identifier
- 
![image](https://github.com/user-attachments/assets/23348dcb-c71d-4134-a93e-1bd389fd9149)
Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.
![image](https://github.com/user-attachments/assets/7f630e36-568e-4856-9f7a-7e9e70ecad5e)

- Follow the same procedure for the user app password and graph app password updating.
- For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference
- 
![image](https://github.com/user-attachments/assets/310dc147-e183-4e00-9f38-d726a6b86cba)

**Comment by peddivyshnavi** [comment]
@moonncat 
Could you please update us on the status of the issue?

**Comment by moonncat** [comment]
Hello @peddivyshnavi , thanks for your guidance.
However, I have checked the password and client id, they both looks correct.
just one thing is different, the API permissions of the Graph App only got Group.Read.All
is permission GroupMember.Read.All and Teams.AppInstallation.ReadWrite 
 required in the Graph App?

**Comment by peddivyshnavi** [comment]
Hi @moonncat 
yes, The permissions listed in the [graph app](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) are required. If there are any other permissions not mentioned here, please remove them.

**Comment by moonncat** [comment]
hello Peddi, we have verified it is service principle API permission issue. thanks for the support
