### ISSUE TITLE
Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

### ISSUE THREAD

**Issue by dahazeman** [OfficeDev/microsoft-teams-apps-company-communicator#1599]
A previous issue with this error was not resolved. A screenshot was requested. Here is my screenshot:

[screenshot removed since the problem is resolved]

I see 500 and 401 errors, but cannot figure out where the problem is coming from. All client secrets were updated two weeks ago and expire in 2025.

**Comment by dahazeman** [comment]
It seems that I missed updating one environment variable in the app service, pointing to the new key vault entry for the Graph App Password. Updated, saved, restarted, and now all is well.

**Comment by peddivyshnavi** [comment]
Hi @dahazeman 
Thanks for reaching out to us!
we will check and we will get back to you ASAP

**Comment by peddivyshnavi** [comment]
Hi @dahazeman 
Based on the comments, it appears that you have renewed secrets.
**We need to update the secrets in the environment variables for all app functions and the app service.**

Please cross verify once again w.r.t secrets renewal with the below steps.

- Go to Azure Portal
- Go to App registration
- Create a new secret value for app registration and grab secret value. Here is the reference.

   ![image](https://github.com/user-attachments/assets/a2466acb-76f7-4d78-aac4-4993d059a0b4)

- Then go to resource group. Select key vault from list of resources.
- Click on secrets under object section.
   ![image](https://github.com/user-attachments/assets/13d95e55-71e4-4069-bbc4-51875288a5fe)

- If the secrets are not visible, Go to Access Policy--> Click on Create
  ![image](https://github.com/user-attachments/assets/5fc22a97-83df-4949-ac13-f37df580c726)

- Select Key, secret and certificate management
  ![image](https://github.com/user-attachments/assets/1671da70-9235-466f-9a62-3ff78b970b81)

- Give the Id through which one can view the secrets
   ![image](https://github.com/user-attachments/assets/91e06118-edd6-421b-83da-24490c2dafdb)

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. Open author/user/graph app password
- Click new version
   ![image](https://github.com/user-attachments/assets/ddd5fabf-fe2f-4b8b-9939-0fd880b49e0f)

- Grab the new secret identifier
   ![image](https://github.com/user-attachments/assets/35667865-20aa-44b7-a6e3-626c90ac6a13)

- **Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.**
  ![image](https://github.com/user-attachments/assets/63722e18-cba9-4b01-9f54-4d88cb058b07)

- Follow the same procedure for the user app password and graph app password updating.
- For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference
   ![image](https://github.com/user-attachments/assets/8326d873-f6fa-46e3-8584-cd64f42c1c7b)

**Comment by peddivyshnavi** [comment]
@dahazeman 
Could you please update us on the status of the issue?

**Comment by tiwariShiv7** [comment]
According to the comment by @dahazeman 

It seems that I missed updating one environment variable in the app service, pointing to the new key vault entry for the Graph App Password. Updated, saved, restarted, and now all is well.


We are closing this issue

**Comment by jeeva2828** [comment]
While following the above given steps i can't able to find graph password update steps please check and confirm

**Comment by jeeva2828** [comment]
I have followed the above given steps still facing the same issue please check

**Comment by jeeva2828** [comment]
Above given steps have been followed still facing the same issue please check
