### ISSUE TITLE
Teams - permissions issues

### ISSUE THREAD

**Issue by khenry1111** [OfficeDev/microsoft-teams-apps-company-communicator#1600]
Several users are receiving the following error message "Sorry, you do not have permission to access this page.  Please contact your administrator to be granted permission", when attempting to access the Company Communicator (Authors) application tab in Teams channel.  

Looking for feedback on where this permissions setting exists?

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
Thanks for reaching out to us 
we will check and we will get back to you ASAP

**Comment by peddivyshnavi** [comment]
Hi @khenry1111 
please make sure that the email id you are using to access the app is added in AuthorizedCreatorUpns, AuthorizedDeleteUpns. 

- Go to resource group where the app is deployed.
- Navigation to the Resource of type app service.
- Click settings and search for AuthorizedCreatorUpns, AuthorizedDeleteUpns this should be semicolon seperated e-mail ids who are having access to author app.
- You can add email id here if you want access
  ![image](https://github.com/user-attachments/assets/1c5bc2b0-9a28-4c29-844d-e3a802d353e7)

**Comment by khenry1111** [comment]
Great, thank you.  This works.  ticket can be closed.

**Comment by peddivyshnavi** [comment]
@khenry1111 
marking this ticket as closed as issue got resolved 
Thanks
