### ISSUE TITLE
i can't Add more buttons to new messages

### ISSUE THREAD

**Issue by kennyquintal** [OfficeDev/microsoft-teams-apps-company-communicator#1601]
Hi, i already installed to new versión of company communicator (5.5.2) however when i tried to add a new button like version 5.1 i can't, the option is not visibile or existent

![image](https://github.com/user-attachments/assets/0a845487-4aa6-49ed-ac20-fe8a8e62e662)

How can add new buttons to my message? I need for multiple URL's in messages

**Comment by peddivyshnavi** [comment]
Hi @peddivyshnavi 
Thanks for reaching out to us
we will get back to you with proper response

**Comment by peddivyshnavi** [comment]
Hi @kennyquintal 
Could you Please confirm us with the following.
Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select function App (App Service) 
--> Go to Deployment Center -> 
Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].

**Comment by kennyquintal** [comment]
> Hi @kennyquintal Could you Please confirm us with the following. Go to Azure Portal --> Go to Resource Group (where the CC deployment has been done) --> Select function App (App Service) --> Go to Deployment Center -> Share the Screenshot of this -> In the same tab Click on logs [send a screenshot of this].


Hi @peddivyshnavi i share you the requested
![image](https://github.com/user-attachments/assets/fae4c1cb-02a3-45b5-96d7-83b78e047f22)

![image](https://github.com/user-attachments/assets/4ec4b05b-7be1-4326-be79-092061aefafb)

**Comment by peddivyshnavi** [comment]
Hi @kennyquintal 
upon our analysis we dont have multiple button option in 5.1 version.

**Comment by v-jaygupta** [comment]
Hi @kennyquintal ,
Could you please confirm if we can close this issue, as no further action is required from our side?

**Comment by v-jaygupta** [comment]
@kennyquintal ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.
You may also always open a new issue or respond here if something does come back up.

**Comment by v-jaygupta** [comment]
Closing this issue as no response received from the user.
Please open a new issue if you have any issues with Company Communicator app.
