### ISSUE TITLE
CC blank page

### ISSUE THREAD

**Issue by CarlosGuadamuz** [OfficeDev/microsoft-teams-apps-company-communicator#1603]
Followed the guidance in [Deployment guide powershell · OfficeDev/microsoft-teams-apps-company-communicator Wiki · GitHub](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-powershell) but the Communication App is not functioning
 
After the deployment the App is loading in teams but not function:

![image](https://github.com/user-attachments/assets/df2cf6d8-e9f6-4ded-9b3f-0254fd4f7312)

 
Tried to access it through web browser is also not working:
 
 
![image](https://github.com/user-attachments/assets/cfb0b39f-fc39-40d9-9489-de286aa45f3d)

Action performed on Azure Front Door side:
 
We asked cx to test to the Communicator App directly without Front Door and we were getting the same blank page,
Front Door is a proxy meaning whatever it gets from the origin/backend is what Frond Door passing to the user, in the case the Communicator App sent blank page and that was what we were getting on AFD
 
Ask here : Cx followed all the guidance in Githutb and still the App is not working, need assistance to get the App to work
Deployment guide powershell
Company Communicator app template. Contribute to OfficeDev/microsoft-teams-apps-company-communicator development by creating an account on GitHub.

**Comment by peddivyshnavi** [comment]
Hi @CarlosGuadamuz 
We recommend you follow the manual deployment over PowerShell approach as there is existing issue script that is not compatible with Azure CLI version. In addition, good troubleshooting is possible with manual approach.
[Manual approach](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

**Comment by v-jaygupta** [comment]
Hi @CarlosGuadamuz ,
Could you please update us on the status of the issue?

**Comment by v-jaygupta** [comment]
@CarlosGuadamuz ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue in 2 business days.
You may also always open a new issue or respond here if something does come back up.

**Comment by v-jaygupta** [comment]
Closing this issue as no response received from the user.
Please open a new issue if you have any issues with Company Communicator app.
