### ISSUE TITLE
There are some users are missing from the blob storage UserData Table

### ISSUE THREAD

**Issue by moonncat** [OfficeDev/microsoft-teams-apps-company-communicator#1605]
There are some users are missing from the blob storage UserData Table.
it may be caused by the conversation creation failed.
Can we find a way to retriger the CreateConversation Activity from backend side?

**Comment by tiwariShiv7** [comment]
Hi @moonncat, Thanks for reaching out to us. Can you please inform this. 
- Is this happening after sending the message to users? 
- Please inform us the organisation name as well. 
- Have we recently deleted any record from UserData table ?

**Comment by moonncat** [comment]
Hi @tiwariShiv7 , thanks for your response.
please find the information below:
1, A lot of new joiner reported that they didn't receive any activity sent by the Company Communicator bot, then we checked the UserData Table and found out the user records are missing.
2, Sorry for the security restrictions, I can't tell my organization name in public site. we have got thousands users.
3, We didn't do manual deletion in the table. is there any way to retriger the initialization for a specific user?

**Comment by tiwariShiv7** [comment]
Hi @moonncat, 
There are two ways to trigger the Initialization. 
1. Pick any one or two users and send a sample message to see if those user IDs appearing in the userData table or if they are receiving the messages. 
2. Create a Teams channel with users not receiving message and install user app to this Team. We can again take 1 or 2 users for testing and check the userData table for records. OR try sending message Everyone of this sample Teams channel and check whether they are receiving messages.

**Comment by v-jaygupta** [comment]
@moonncat ,
Could you please update us on the status of the issue?

**Comment by moonncat** [comment]
Hi @v-jaygupta , thanks for your advices.
we have try the second option, the user can receive message from Teams Channel.
but for the first option, we can't find the entrance of sending message to an individual. and there is a way to upload a list to send message, but seems not working. not sure if caused by the invalid upload template.

**Comment by tiwariShiv7** [comment]
Hi @moonncat , Thanks for the details. Can you export the data of successfully sent message and check the user ID for which earlier it was failing and now getting delivered ? Compare both user IDs and re-search in UserData table under rowkey column. 
Let us know what happens. 

For list can you give screenshot of the error if it is giving any ?

**Comment by moonncat** [comment]
Hi @v-jaygupta , there are some new joiners to the organization. but there is no corresponding record in the UserData table. We can't reinstall the CC for all users, the risk is too high - we have got around 30k users.
and the admin decline to use powershell to re-install the CC as well.
is there any way to get the conversation id and user id and put it to UserData table?

**Comment by v-jaygupta** [comment]
@moonncat ,
Can you please share your email-id so that we can start our conversation internally over teams.
