### ISSUE TITLE
Re-add a user's record to the UserData table

### ISSUE THREAD

**Issue by neidantaslopez** [OfficeDev/microsoft-teams-apps-company-communicator#1606]
Considering #1515, I noticed that after removing a user’s record from UserData table, this record was not automatically recreated in the UserData table.

In which situations are user records recreated in the UserData table by CC?
Is there anything the user can do from the Microsoft Teams perspective (for example, reinstalling the CC User App) to have their record recreated in this table?

Thank you.

**Comment by tiwariShiv7** [comment]
Thanks for reaching out. 
There are two ways it can be done @neidantaslopez. 
1. Retry sending the message to user. 
2. As an admin add user to a Teams channel and Installing user app for that Team channel.

**Comment by v-jaygupta** [comment]
@neidantaslopez ,
Could you please update us on the status of the issue?

**Comment by neidantaslopez** [comment]
Hi @v-jaygupta.

The user is currently on vacation. We expect to be able to test it again by next week.

**Comment by tiwariShiv7** [comment]
Sure Thanks for the update. Let us know whenever possible

**Comment by v-jaygupta** [comment]
Could you please update us on the status of the issue?

**Comment by v-jaygupta** [comment]
Closing this issue as no response is received from the customer
