### ISSUE TITLE
Company Communicator - Can't find Group or Channel for preview

### ISSUE THREAD

**Issue by Nadeem-hussain-mafgs** [OfficeDev/microsoft-teams-apps-company-communicator#1607]
Company Communicator - Can't find Group or Channel for preview

<img width="384" alt="ias" src="https://github.com/user-attachments/assets/aed8807a-a490-4430-b8d1-ae10d8478ac8">

**Comment by v-jaygupta** [comment]
Hi @Nadeem-hussain-mafgs ,
Thank you for reaching out to us!
For making teams visible for the 1st and 2nd sending otption, we need to add user app to respective teams follow below steps:
Create a Teams channel with the people or Group you want to trigger user app installation to.
Navigate to installed user app from apps -> manage apps in Teams.
Click on the app and Select an option of Add to a Team.
Select created / desired Teams channel from Dropdown.
Click on set up / Submit button.
This will trigger user app addition to the Team and list of teams will be populated in the dropdown of 1st and 2nd sending option.

**Comment by v-jaygupta** [comment]
Connected with the user internally and helped the user to add the user app to the Team which listed the teams in the 1st and 2nd sending options. Closing this issue now as no further action is required from our side.
