### ISSUE TITLE
After Client Secret Key Expired, App is not working

### ISSUE THREAD

**Issue by EkremERs** [OfficeDev/microsoft-teams-apps-company-communicator#1608]
Hi,

App scret key have been expired, And I created new secret key on app registration but now CC is not working.

İ get help on below links but it still not working.
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/820

İ am owner on subscription. 
My user and app registration are owner on key vault service bu i see that issue;

On Key Vault services, List is empty and "You are unauthorized to view these contents"

On App Services," Either this secret is disabled or you do not have the "Get" secret permission" but my user and app registration have all permission.

on app > chanels > teams channels - "Conversation not found."

İ cant understrand and solve the problem. Can you help me please? Thanks

**Comment by tiwariShiv7** [comment]
Hi @EkremERs 
Please cross verify once again w.r.t secrets renewal with the below steps.

Go to Azure Portal
Go to App registration
Create a new secret value for app registration and grab secret value. Here is the reference.
![image](https://github.com/user-attachments/assets/ac9abef0-0871-48f4-a5c4-d73cec21c7a3)

Then go to resource group. Select key vault from list of resources.
Click on secrets under object section.
image

If the secrets are not visible, Go to Access Policy--> Click on Create
image

Select Key, secret and certificate management
image

Give the Id through which one can view the secrets
image

3rd step is optional
Go for Review+Create
Then go to Secrets. Open author/user/graph app password
Click new version
image

Grab the new secret identifier
image

Paste it in the configuration sections of app service, 3-function apps. Here is the reference of updating the author app password in app service configuration.
image

Follow the same procedure for the user app password and graph app password updating.
For graph app, please dont forget to update the password in AzureAd Client Secret as well. here is the reference
image

**Comment by EkremERs** [comment]
Hi,

Thank you for support but it still not working. Message isn't sending to recipients. I would be happy if you could review my issue again.

!
![Screenshot 2024-11-06 093542](https://github.com/user-attachments/assets/82181b4c-665f-4774-bdb2-0bfbcb614fd8)

Thanks.

**Comment by v-jaygupta** [comment]
@EkremERs ,

Could you please share the error details and the supporting screenshot of error from application insights resource from the deployed resource group to investigate further on this issue.

Go to resource group where CC app is deployed --> Go to Application insight type resource -->Under investigate section Click on failures --> share the screenshot and stack trace for Top 3 response codes.

**Comment by EkremERs** [comment]
Hi,

![image](https://github.com/user-attachments/assets/1ae3fe04-5f2d-4b6b-9527-73d5f6d8719b)

**Comment by EkremERs** [comment]
Hi,
Thank you for taking the time to do so.

For 401:
![resim](https://github.com/user-attachments/assets/93e24715-8560-4e81-a5ba-0113784f558b)

For 403:
![resim](https://github.com/user-attachments/assets/6fb84ca9-2a74-47a3-bf40-cbbdaf9819f7)

For 0:
![resim](https://github.com/user-attachments/assets/bc332cf1-ced6-452c-bf35-1b11f39233d4)

Thanks.

**Comment by v-jaygupta** [comment]
Hi @EkremERs ,
Could you please share your email id so that we can start discussing this issue internally over teams

**Comment by v-jaygupta** [comment]
Started the conversation internally.

**Comment by v-jaygupta** [comment]
Hello @EkremERs ,

As per our trouble shooting, we found that the app registrations secrets are stored directly in the function apps rather than storing the reference of the key vault. We updated the key vault reference for the author, graph and the user app in all 3 function apps.
Also, we found that the function apps are pointing to v5.2 version of the CC app whereas the app service is pointing to the latest version of the app i.e. v5.5.2.
We would request you to follow the [migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version) properly and complete all the steps for the migration of the function apps.
Please keep us posted with the updates.

**Comment by v-jaygupta** [comment]
Hi @EkremERs ,
Could you please let us know if the issue still persists. If not, can we close this issue?

**Comment by EkremERs** [comment]
Hi,

Thank you for support. You can close the case.

**Comment by v-jaygupta** [comment]
As per the above confirmation from user, closing this issue.
