### ISSUE TITLE
Not able change Banner Logo (Microsoft) using 'REACT_APP_HEADERIMAGE'

### ISSUE THREAD

**Issue by ArunkumarTMEYGDS** [OfficeDev/microsoft-teams-apps-company-communicator#1609]
Hi Team, 

We are not able to change Banner Logo (Microsoft) using 'REACT_APP_HEADERIMAGE'.
We have followed the below steps as mentioned guide.

1.	Go to deployed Azure Resource Group -> Azure App Service.
2.	Select the configuration blade from the Azure App service and update the 'REACT_APP_HEADERIMAGE' and 'REACT_APP_HEADERTEXT' configuration values.
3.	Save the changes
4.	Navigate to 'Deployment Center' and click 'Sync'
5.	Check the status of the deployment in the 'Logs' tab, once the status is success, the changes will reflect automatically.

**Comment by tiwariShiv7** [comment]
Hi @ArunkumarTMEYGDS, Thanks for reaching out to us. 

For updating Name
Update Short name in users manifest, author manifest and deploy the updated manifest in teams admin center.
![image](https://github.com/user-attachments/assets/e343037f-564d-4188-905d-567de55edd56)

For updating Logo

Open Azure portal
Navigate to respective resource group
Open “Web app bot”
Click on “Bot profile”
Update “Display name” as required and click on Apply
![image](https://github.com/user-attachments/assets/65a45b2a-d9e3-4023-8cf1-1b823afb953e)

To update the logo, replace the ‘color’ image with the logo customer want to use, please make sure to use the same size and dimension of the image

![Uploading image.png…]()


Please delete the uploaded manifest file and create a new zip file with these changes and reupload in the Teams admin centre

Make sure to clear the Teams cache, you can find the steps [here](https://answers.microsoft.com/en-us/msteams/forum/all/clear-cache/0810ce4f-af14-4269-b01f-adc89a0af4c4)

**Comment by ArunkumarTMEYGDS** [comment]
Hi @tiwariShiv7,

We want to change the Microsoft logo in the Admin App as shown in screenshot. 
We followed the above step mentioned in guide but it is still showing Microsoft logo.
<img width="704" alt="Q" src="https://github.com/user-attachments/assets/6fb17b4c-d8a3-4590-b5e3-511932f50f27">

**Comment by v-jaygupta** [comment]
Could you please check the same in the Teams web app, it might be not showing the updated image in the desktop app due to cache issue.

**Comment by ArunkumarTMEYGDS** [comment]
Hi @tiwariShiv7
 
In the Teams web app the image is not loading properly though we can see the URL is of what we have uploaded.
**https://xxxxxxxxxxxxx.blob.core.windows.net/images/EYLogoAdmin.png**
 
Where can we upload the image to set it as logo? Currently we have uploaded a logo.png file in the below location?
**Resource Group > Storage account > Storage browser > Blob containers > images**

**Comment by v-jaygupta** [comment]
Could you please confirm if the same link has been updated in the Environment Variables section of the app service for variable - "REACT_APP_HEADERIMAGE". Also, make sure the image diemensions of the newly uploaded logo are same as the default existing logo.

**Comment by ArunkumarTMEYGDS** [comment]
Hi @v-jaygupta,

Yes. we have updated REACT_APP_HEADERIMAGE Environment Variables as well. 
The URL is being shown in Teams Web browser but is not rendering.

<img width="699" alt="SS" src="https://github.com/user-attachments/assets/e97ab58c-2823-448e-8362-7fa316150a8a">

We have tried uploading the image in same resource group blob storage as mentioned above as well as SharePoint site Shared library of the Team where Admin App is deployed but both resulted in same behaviour.

**Comment by tiwariShiv7** [comment]
Hi @ArunkumarTMEYGDS , I'll check and update you in next 24 hours

**Comment by tiwariShiv7** [comment]
Hi @ArunkumarTMEYGDS, Can you please recheck the logo size. Most probably it would be a logo size issue.

**Comment by ArunkumarTMEYGDS** [comment]
@tiwariShiv7 Our logo is of size **192x192px - 2.86kb**. We check the default MS Logo is of size **1000x1000px - 5.46kb**. Should our logo be of 1000x1000px as well? A smaller resolution and size logo won't render?

**Comment by ArunkumarTMEYGDS** [comment]
Quick update. The logo seems to appearing now after 3 days. We had already cleared cache and everything as still was not working. We tried switching to different browser as well. As shown above the URL was showing correct path but image was not showing.

What could be the cause for this? Is the delay expected? 

**Note we uploaded logo (192x192px - 2.86kb) in SharePoint site Shared library of the Team where Admin App is deployed, in other words, Teams Channel Files location**.

**Comment by v-jaygupta** [comment]
@ArunkumarTMEYGDS ,
This could be due to cache issues in Teams client side however, we have reached out to respective team to gain more insights about it, will keep you posted.

**Comment by tiwariShiv7** [comment]
Hi @ArunkumarTMEYGDS , Just to recheck, are you still facing the same issue? Which is, is it still not appearing in Teams Desktop Application ?

**Comment by v-jaygupta** [comment]
Closing this issue as the logo is visible in the Teams Web Client, and intermittently visible on the Teams Desktop client which seems to be a cache issue at teams
