### ISSUE TITLE
Clean up messages

### ISSUE THREAD

**Issue by pablolimainfo** [OfficeDev/microsoft-teams-apps-company-communicator#1611]
Hello, I need to clear the history of sent test messages while we test this solution. I thought about deleting data from "SendNotification Data" and "Notification Data", but I’m afraid to creating inconsistencies… Is there a procedure for that?

Thanks.

**Comment by v-jaygupta** [comment]
@pablolimainfo ,
Could you please update us on the status of the issue?

**Comment by tiwariShiv7** [comment]
Hi @pablolimainfo, Ideally when you upgrade to our latest version it should show the delete option. Can you please share the screenshot of Deployment center and logs for all function apps (*-function)and web app (of type app service)

To navigate to deployment center. 
- Go to Resource group in which this instance of CC is deployed. 
- Select from resource 
- Under Deployments - > Deployment center. 
- Send this screenshot. 
- On this screen only you will get logs option click on it. 
- Sent the screenshot.

**Comment by pablolimainfo** [comment]
Hello,

Just to give you some context, let me share the background I have. The company started using the app as early as 5.5.2. 

There was no git version upgrade, but the business area asked to make small changes to the look and feel of the app application (nothing related to the area where this missing button is located). 

In short, the official version 5.5.2 was deployed first and then a new customized version 5.5.2 was uploaded via FTPS. We are currently using this customized version.

App Service:
![Pasted Graphic](https://github.com/user-attachments/assets/f0d3a598-2860-42a2-b4cb-b442c792e3f5)
![Pasted Graphic 1](https://github.com/user-attachments/assets/ae57d58d-0aff-4d9c-ba24-83e97ab5fe55)

Function Apps:
![Pasted Graphic 2](https://github.com/user-attachments/assets/81dfda76-613b-4a7a-b7a4-0509697c3bdc)

![Pasted Graphic 3](https://github.com/user-attachments/assets/b20af55a-c408-41a3-8346-7b4a3d12a8a7)


![External Git](https://github.com/user-attachments/assets/598444b5-1c13-4646-8ee1-6a8dee1d608f)

![Pasted Graphic 5](https://github.com/user-attachments/assets/042497bd-f244-463d-ad28-669f95042209)


![Pasted Graphic 6](https://github.com/user-attachments/assets/baed2da9-53ec-4704-a863-db0a2e33665a)

![Pasted Graphic 7](https://github.com/user-attachments/assets/eca7c7b7-93e0-4000-ab6e-398593029baa)

Thanks.

**Comment by v-jaygupta** [comment]
@pablolimainfo ,
If an entry has been added to the field - AuthorizedDeleteUpns, please re-sync the app service. For re-sycning the app service please follow the below steps - 

- Go to portal.azure.com. Navigate to resource group where all CC resources are deployed.
- Click on App Service.
- Go to the deployment center.
- Click on Sync
![image](https://github.com/user-attachments/assets/19168791-70b9-4fda-b5ba-5870917fe061)
- Once the status turns to Success(active) in the Logs section, please open the Teams app in a webbrowser and check the CC author app.
Note: After adding any entry in the **AuthorizedDeleteUpns** field, we need to perform the sync for the changes to get reflected for the added user.

**Comment by pablolimainfo** [comment]
@v-jaygupta on click on "Sync" button, will the Deployment Center pull the code from Repository and override our customized version?

**Comment by tiwariShiv7** [comment]
Yes It might override the customized version. But we can not certainly comment on this. Just to keep you informed that our support scope is also very much limited to Official version of Company Communicator according to [support policy.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Support-policy)
