### ISSUE TITLE
For new users, Communicator bot is not adding by default when publish the posts/articles

### ISSUE THREAD

**Issue by Prasadj2024** [OfficeDev/microsoft-teams-apps-company-communicator#1612]
Generally, when ever publish the post in communicator. It should go to new users by default, Recently i observed. For new users are not receiving the posts.  

New users need to go to My Apps in Teams and add communicator bot manually then only they receiving the posts.

Users without adding the bot it should populate automatically, but it's not happening, Can you help me on this.

**Comment by v-jaygupta** [comment]
Hello @Prasadj2024 ,
Thanks for reaching out to us!
Could you please check and confirm if "ProactivelyInstallUserApp" setting is marked as **True** in the Environment Variables Section of the deployed app service instance of Company Communicator application.
Also, please confirm if the new users are having the same app setup policy as the old users who are receing the messages in the Teams Admin Center.

**Comment by Prasadj2024** [comment]
Hello Team,

Yes, Proactive is true only, Is there any setup policy need to be verify. Is there any changes happening in Teams policy settings?
[cid:2cbf526c-cdeb-4a2d-b740-a3fc4e947dc3]
Thanks,
Prasad.
________________________________

**Comment by v-jaygupta** [comment]
@Prasadj2024 , 
Please check the app setup policy in the Teams Admin Center of the tenant where the CC app is deployed.
We are unaware of any policy changes occurring at your tenant as we don't have any visibility over it.

**Comment by v-jaygupta** [comment]
Could you please update us on the status of the issue?

**Comment by Prasadj2024** [comment]
Hello Team,

The issue has been resolved. Some upgradation on MS teams polices. Pls archive this case.

Thanks,
Prasad.

________________________________

**Comment by v-jaygupta** [comment]
Thanks for the confirmation. We will close this issue
