### ISSUE TITLE
CC BOT Not responding 

### ISSUE THREAD

**Issue by jeeva2828** [OfficeDev/microsoft-teams-apps-company-communicator#1613]
Certificate got expired i have created the new certificate please guide me update the certificate

while trying to compose message we are getting the error please find the below snap,

![Untitled](https://github.com/user-attachments/assets/678e85ed-7dc5-4947-9d04-7df4502096b7)

**Comment by v-jaygupta** [comment]
Hello @jeeva2828 ,

Thanks for reaching out to us!
Please follow the below set of instructions mentioned in the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/1599#issuecomment-2436956229) to renew the expired secrets.

**Comment by jeeva2828** [comment]
Hi Team,

While performing the below given steps we can't find AzureAd client Secret where to be updated please help us to resolve.

Regards,
Jeevanandam A

**Comment by jeeva2828** [comment]
Hi Team,

Please find the below trail mail and help us to resolve ASAP.

Regards,
Jeevanandam A

From: Jeevanandam A (ITIM)
Sent: 22 November 2024 14:51
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] CC BOT Not responding (Issue #1613)

Hi Team,

While performing the below given steps we can't find AzureAd client Secret where to be updated please help us to resolve.

Regards,
Jeevanandam A

**Comment by v-jaygupta** [comment]
After reviewing the configuration and application insights, it was found that the secrets for the author app, graph app, and user app had expired. The secret identifiers were subsequently updated in the relevant locations of App Service and three function apps. As a result, messages were successfully delivered to the end users.
