### ISSUE TITLE
Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists

### ISSUE THREAD

**Issue by WBCInfrastructure** [OfficeDev/microsoft-teams-apps-company-communicator#1614]
Hi

I am getting the following error when trying to load the Company Communicator App in Teams.  
It seems to load the app for about a second then I get the Oops error.

Please can you help?

Thanks

Reuben

![Oops! An unexpected error seems to have occurred](https://github.com/user-attachments/assets/e1a9f6f5-eb05-48ac-9e66-dd03ecd2e336)

I have looked at similar error's and checked the whole environment secrets, environment etc variables and it looks to be configured correctly.

When looking in application insights for ColleagueAlert-function I can find the following error pointing to the storage account.  Looks like a reference to /NotificationData which does not exist on the storage account.

![image](https://github.com/user-attachments/assets/ff4c8465-fc6f-499c-9b8f-33fa23e0c31d)

![image](https://github.com/user-attachments/assets/cc5dde2d-4f77-4982-9e35-fe4d04d33267)

**Comment by v-jaygupta** [comment]
Hi @WBCInfrastructure ,
Thanks for reaching out to us!
Could you please share the deployment status screenshots of all the Function apps and App service from the deployment center. Here is the reference for App service status. Please do the same for 3 function apps(Data Function, Send Function, Prep Function).
![image](https://github.com/user-attachments/assets/fb6d2a76-5e1d-44d6-bed4-d7b132b5fcbe)

 Also, please check and make sure that the secret value was used during the deployment process and not secret id.

**Comment by WBCInfrastructure** [comment]
Hi @v-jaygupta 
PLease, see screenshots, all seems ok, thanks
![image](https://github.com/user-attachments/assets/221603a7-3af2-4fb4-9d40-7e39f1550140)

![image](https://github.com/user-attachments/assets/534a185b-5959-401e-9784-ef820fb223ad)

![image](https://github.com/user-attachments/assets/b744e0f6-313e-414f-a72f-d020edb602cf)


![image](https://github.com/user-attachments/assets/f52ca92b-ddf4-41ed-8e4c-544d14269ec7)

**Comment by v-jaygupta** [comment]
Hi @WBCInfrastructure ,
Could you please share your email id so that we can start discussing this issue internally over teams?

**Comment by WBCInfrastructure** [comment]
reuben.smither@wokingham.gov.uk

**Comment by v-jaygupta** [comment]
@WBCInfrastructure ,
Thanks for joining the call yesterday!
We verified multiple configuration settings in the deployed Company Communicator app, including app registrations, key vaults, and app insights. We identified an issue with the configuration URL in the Author manifest file. We have shared the next steps internally and request that you keep us updated on the progress.
