### ISSUE TITLE
CC App not accessible to all authors

### ISSUE THREAD

**Issue by tgainey** [OfficeDev/microsoft-teams-apps-company-communicator#1615]
Published version 5.5.2.  I can access without issue, but another author cannot.  He gets a message:  

There was a problem reaching this app.
![CCerror 111524](https://github.com/user-attachments/assets/69562fa3-aa92-4096-b3d9-06425d083288)

**Comment by tiwariShiv7** [comment]
Hi @tgainey, Thanks for reaching out. 

- Go to Resource Group where the app is deployed.
- Navigate to the Resource of type app service.
- Click settings and search for AuthorizedCreatorUpns, AuthorizedDeleteUpns this should be semicolon seperated e-mail ids who are having access to author app.

In case everything seems correct, please send us the screenshot and we will reverify from our end. 

![image](https://github.com/user-attachments/assets/c58e1654-763e-407c-89a3-71a608ddaf32)

**Comment by tgainey** [comment]
I have verified that the user is listed in the AuthorizedCreatorUpns

![image](https://github.com/user-attachments/assets/d2bd52ad-198b-45e5-9003-f85b9c790640)

**Comment by renidantass** [comment]
Hi everyone, any update about this issue? I have a similiar problem with creators listed on environment variables too.

**Comment by tiwariShiv7** [comment]
Hi @tgainey, Can you please retry accessing page on the Web Version of Teams by logging into some browser. 
If it still shows the same error please send us below Screenshots and info

Could you please share the error details and the supporting screenshot of error from application insights resource from the deployed resource group to investigate further on this issue.

Go to resource group where CC app is deployed --> Go to Application insight type resource -->Under investigate section Click on failures --> share the screenshot and stack trace for Top 3 response codes.

**Comment by v-jaygupta** [comment]
We have started the conversaiton internally over Teams
