### ISSUE TITLE
A user has stopped receiving Company Communicator notifications

### ISSUE THREAD

**Issue by osevilla6** [OfficeDev/microsoft-teams-apps-company-communicator#1616]
The user received notifications via Teams using the correctly installed app. The user accidentally left the group associated with Company Communicator and when he was added back he no longer received notifications sent from the Company Communicator app. In the log detail of the message sending, it does not even give an error with the user, it is simply as if it did not exist and indicates that the message has been sent correctly to as many members of the group that has been selected for the notification except one, but it does not show it as an error, it simply does not count it in the sending.
The following actions have been taken with the user to resolve the incident, all without success:
a. All types of notifications allowed by Company Communicator have been tried (sending to a team's general channel, sending to the personal chat of team members, and sending to the personal chat of an M365 group) and the same thing happens in all of them; the user is not detected as a member.
b. The user has been removed from all groups that have a policy and has been added back.
c. The policies have been removed from Teams and have been added back.

The error in Azure gives the following message:
AllSendStatusCodes:404
ErrorMessage: {"error":{"code":"ConversationNotFound","message":"Conversation not found."}}

**Comment by v-jaygupta** [comment]
Hello @osevilla6 ,
Thanks for reaching out to us!
Could you please share your email id so that we can start discussing this issue internally over teams?

**Comment by osevilla6** [comment]
Hola,

En el perfil? Si es ahí ya lo he actualizado el email.

Gracias.

**Comment by tiwariShiv7** [comment]
Hey @osevilla6, Can you please paste your e-mail ID here on the GitHub so that we can reach out to you over the Microsoft Teams or Outlook.

**Comment by v-jaygupta** [comment]
@osevilla6 ,
Could you please update us with the above requested information?
