### ISSUE TITLE
Oops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

### ISSUE THREAD

**Issue by jeeva2828** [OfficeDev/microsoft-teams-apps-company-communicator#1617]
Given Steps have been followed still facing the same issue 
app password has been updated, and service has been re started

<img width="584" alt="{F2BA57EB-1579-43F7-AF94-BBBD6947C771}" src="https://github.com/user-attachments/assets/a8c5473a-569c-4032-acf5-d179b94ef33e">

**Comment by v-jaygupta** [comment]
Hi @jeeva2828 ,
Thanks for reaching out to us!
We have started the conversation internally for troubleshooting the issue.

**Comment by v-jaygupta** [comment]
@jeeva2828 ,
Thanks for connecting over call!
After reviewing the configuration and application insights, it was found that the secrets for the author app, graph app, and user app had expired. The secret identifiers were subsequently updated in the relevant locations of App Service and three function apps. As a result, messages were successfully delivered to the end users.
