### ISSUE TITLE
v5 migration guide

### ISSUE THREAD

**Issue by hamounir** [OfficeDev/microsoft-teams-apps-company-communicator#1619]
As reference Microsoft ticket number: RE: [EXTERNAL] RE: VIP - Teams cannot access Co... - TrackingID#2411290050002538

we need remote session support to migrate our company communicator to be v5 migration guide.
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide

Regards,
Hamid
call me on +201123202342
email to me: hamounir@mantracgroup.com

**Comment by v-jaygupta** [comment]
Hi @hamounir,
Thanks for reaching out to us!
Please let us know which is the version of the Company Communicator app which is currently deployed in your tenan?
If the deployed version is v5.x, please follow the [v5 migration guide ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v5x-to-latest-version)to upgrade to the latest version of CC app i.e. v5.5.2.

**Comment by hamounir** [comment]
I didn't get any help, so how can you close it?
Regards,

**Comment by v-jaygupta** [comment]
@hamounir ,
Please share the details requested earlier in the previous comments

**Comment by v-jaygupta** [comment]
@hamounir,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at the moment and no response is received, we will close out the issue by tomorrow EOD.
You may also always open a new issue over [GitHub ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues)if something does come back up.

**Comment by hamounir** [comment]
Close it.

**Comment by v-jaygupta** [comment]
Thanks for the confirmation, we are closing the issue.
You may also always open a new issue over [GitHub ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues)if something does come back up.
