### ISSUE TITLE
Users cannot receive messages 

### ISSUE THREAD

**Issue by rmerino06** [OfficeDev/microsoft-teams-apps-company-communicator#1620]
I have one user that was receiving message, and suddenly stop receiving message from cc since last month (nov 2024). I even tested creating a test DL including her and 2 other user and in the result only shows the two other users as ok, on the other user doesn't receive the message from cc and I don't see any error message in the report. 
Those 3 users has the same licenses and are part of the same DL. What could be the issue?

Thanks

**Comment by jvrabel88** [comment]
I have a similar issue at my company.  There are a few users that are not receiving messages.   It does not even register the attempt to send the message to that user.  If a group has 3 users and one of those users is one of the impacted users, it will say that it successfully sent to 2 users and had 0 failures.

**Comment by v-milibiswas** [comment]
Hi @rmerino06,
Thanks for reaching out to us!
We will check and get back to you.

**Comment by v-milibiswas** [comment]
Hi @jvrabel88,
Thanks for reaching out to us.
Could you please raise a new ticket with relevant details. This will help us to track things easily.

**Comment by tiwariShiv7** [comment]
Hey @rmerino06, Thanks for reaching out.

**Comment by rmerino06** [comment]
> For Error Detail : Please export the report excel from sent messages table and see the user for which message is in Failed State. You will get error code / Reason with this entry. Please send us both the details.

_**There is no error message in the report from Teams. IF I sent to 3 people, it will show me 2 success and 0 failed. But I tried with a 2nd cc solution and with that cc the 3 people receive the message**_

 
> For application Insight Go to resource group where CC app is deployed --> Go to Application insight type resource -->Under investigate section Click on failures --> share the screenshot and stack trace for Top 3 response codes.
**_![3 response codes](https://github.com/user-attachments/assets/b6095197-9540-4125-b2e0-c9e2764ce591)_**

**Comment by rmerino06** [comment]
Any news on this? can we schedule a teams call to review it?

**Comment by rmerino06** [comment]
Any news?
