### ISSUE TITLE
is:open label:enhancement: Need old option where we could have multiple buttons/Labels for click which could navigate accordingly

### ISSUE THREAD

**Issue by Saivb** [OfficeDev/microsoft-teams-apps-company-communicator#1621]
#open label:enhancement: Previously during 4.x.x version, we use to have multiple buttons option to post where we could use it for links navigating to particular source's like with pdf content & videos.,etc which was very helpful. However during this recent version of 5.x.x this option was limited to only one button, so we were unable to add multiple content sources for users to navigate and get more information, if we could bring back to multiple buttons options this could be a great feature. Needs: enhancement 
<img width="368" alt="CC1" src="https://github.com/user-attachments/assets/b8bf1b04-5bbb-4cdd-9f1d-d451556b1baa">
Previously it use to be multiple as shown above, but now only one button click we have as below
<img width="397" alt="CC2" src="https://github.com/user-attachments/assets/628a9ea6-4471-4543-8504-428495628699">

**Comment by v-milibiswas** [comment]
Hi @Saivb,
Thanks for reaching out to us.
We will review it and will update you soon.

**Comment by tiwariShiv7** [comment]
Hi @Saivb , Can you please share a  few screenshot, just for us to go through history of this instance.
 
Can you please share the screenshot of Deployment center and logs for all function apps (*-function)and web app (of type app service)

To navigate to deployment center.

- Go to Resource group in which this instance of CC is deployed.
- Select from resource
- Under Deployments - > Deployment center.
- Send this screenshot. 
- On this screen only you will get logs option click on it.
- Sent the screenshot.

**Comment by Saivb** [comment]
@tiwariShiv7 Thank you for your reply and please find the screenshots, believe this helps to analyze 
<img width="690" alt="Dep1" src="https://github.com/user-attachments/assets/14903a22-acca-4120-b2d0-54d554fe86c2">

**_Log screenshot_**
<img width="737" alt="Log1" src="https://github.com/user-attachments/assets/f4a324bd-1cf8-460d-b21c-93778f2c755b">

**Comment by tiwariShiv7** [comment]
Hey @Saivb, Thanks for this I can see currently you are using the older version of CC. Can you confirm if you have surely updated this instance or are you planning to upgrade ? 
As the official version of the company communicator was not having this option ever you might be using a custom version of Company Communicator.

To Confirm, Can you please send the screenshot of Setting section of Deployment center as well ?

**Comment by Saivb** [comment]
@tiwariShiv7 I have downloaded the 5.5.2 (microsoft-teams-apps-company-communicator-5.5.2) and deployed it to our environment during May month, after which I do not have an option for multiple buttons, as requested pls find below screenshot
<img width="749" alt="DC1" src="https://github.com/user-attachments/assets/ce4d41d7-56c8-4ea2-b46a-685042769d63" />

**Comment by v-jaygupta** [comment]
Hi @Saivb ,
There has been no reduction in functionality in the [official version](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) of the Company Communicator application. It appears from the previous conversation that you were utilizing a customized version of the app, rather than the official one, which includes features such as adding multiple buttons in a message, among others.

This feature is on our backlog, and we plan to implement it in upcoming releases based on priority and available resources; however, we do not have an estimated time for its completion.
