### ISSUE TITLE
Company Communicator doesn't work after migrated to another subscription

### ISSUE THREAD

**Issue by cifofs** [OfficeDev/microsoft-teams-apps-company-communicator#1630]
Hi there...

I am getting the follow error after migrate the CC to another subscription:

Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://cocoteams.servicebus.windows.net/company-communicator-prep'.

This happen when I try to send a message and the sent messages keep in queued..

Shall you help me please?

**Comment by v-milibiswas** [comment]
Hello @cifofs, 
Thank you for reaching out to us!
We will review it and get back to you soon.

**Comment by cifofs** [comment]
Hello, I finally resolved the issue clearing Teams cache...  Thanks!
