### ISSUE TITLE
How to know the number of recipients who have received or using the Custom app in teams?

### ISSUE THREAD

**Issue by AanandKarki** [OfficeDev/microsoft-teams-apps-company-communicator#166]
Hi Guys,

Not sure if this is the best platform to ask but is there a way to identify the number of users who have received the message / Card once the Custom app is deployed manually or via policy in MS Teams?

I can see it gives the recipient status for success, failure and warning but does not have anything to indicate the actual person in those categories.

can we get such logs via Azure? if yes could you share the steps how to enable and activate the feature?

![image](https://user-images.githubusercontent.com/64951436/81267118-44f44580-9089-11ea-988f-904a1f05da8a.png)

**Comment by rashmi-dixit** [comment]
You can check the details in storage account (table 'sentNotificationData', refer column 'AADID' for user's object id)

To get the storage account name (in case you are not able to find):
Go to app service configuration blade > Look for 'StorageAccountConnectionString' value > Copy the 'AccountName' property (This is the storage account name)
