### ISSUE TITLE
After adding App manifest in Teams I am getting Permission Error

### ISSUE THREAD

**Issue by mpsabarish1990** [OfficeDev/microsoft-teams-apps-company-communicator#169]
I did Azure app deployment and Registration without any errors. But after adding Manifest package in the Teams, the app got added when I click the Tab I getting below permission error.
"Sorry, you do not have permission to access this page. Please contact your administrator to be granted permission".

Where to give the permission?

**Comment by rashmi-dixit** [comment]
Only the users listed in the 'Sender UPN list' will be allowed to compose and send messages.
Seems, your email is not added in this parameter.

Update this list by going to the app service's "Configuration" blade and add the user separated by semicolon who will be allowed to send messages using Company Communicator.
For example, to allow Megan Bowen (meganb@contoso.com) and Adele Vance (adelev@contoso.com) to send messages, set this parameter to meganb@contoso.com;adelev@contoso.com

**Comment by The737** [comment]
Hi rashmi-dixit. I can't find the Sender UPN list in the App Service configuration blade. Do you have any idea where I can find it? Thanks.

**Comment by rashmi-dixit** [comment]
@The737 - Go to company communicator app service in azure portal > click on configuration from left pane > edit ValidUpns property. 
![image](https://user-images.githubusercontent.com/57787129/87430709-3a16dd80-c603-11ea-8455-86aac156a332.png)

**Comment by The737** [comment]
Thanks a mill. Was looking for a while to find it.
Hoped to fix an issue with that, didn't though.

**Comment by zshanthi** [comment]
The sender UPN is just an email id isnt it? I am trying to install company communicator in a teams app for which I'm the admin and my email address is xxxxxx@gmail.com and I'm not using a custom domain at all. So can I enter just my email id xxxxxx@gmail.com in the sender UPN list? I have added it but still I receive **"Sorry, you do not have permission to access this page. Please contact your administrator to be granted permission"** When I try to add the app to a tab in my teams app?

**Comment by hunaidhanfee20** [comment]
Hello @mpsabarish1990, @The737 
Is this issue resolved? 
Let us know if issue still persists.

@zshanthi Yes you can enter Gmail, just make sure that enter that account which are using to sign-in into Teams. You can also search for yourself at [Portal](https://portal.azure.com) in _Users_.

Thanks
