### ISSUE TITLE
Chat notification popup is redirecting to Apps Page 

### ISSUE THREAD

**Issue by pabbinedi** [OfficeDev/microsoft-teams-apps-company-communicator#171]
Hi..
I have deployed communication app and noticed on Desktop client chat notifications are redirecting to Apps Page instead of directly opening the chat. This is stopping us for deploying the app for all users.

**Comment by pabbinedi** [comment]
Hi..Do we have any update for the query?

**Comment by rashmi-dixit** [comment]
Are you saying that users get a desktop client notification when any message is sent to them using the Author tab, but when users click on that notification, they get redirected to "Apps" screen instead of the message?

**Comment by kumaranupam21** [comment]
Yes, I am facing the same issue. Even tried updating the apps by changing the version in manifest files... still the issue persists...

**Comment by hunaidhanfee20** [comment]
Hello @pabbinedi,
We are not able to repro this issue. Which version of Company communicator you are using? Please try to update it to latest.

Let us know if issue still persists
Thanks.
