### ISSUE TITLE
We couldn´t find any matches

### ISSUE THREAD

**Issue by belasor** [OfficeDev/microsoft-teams-apps-company-communicator#172]
I published the app yesterday, and tried to send out some messages to some teams or users. 
Unfortunately I always get the message:"We couldn´t find any matches"

<img width="192" alt="Error" src="https://user-images.githubusercontent.com/65898854/82806749-b5bba000-9e86-11ea-82ac-f24307550e9a.png">

**Comment by rashmi-dixit** [comment]
Can you please in table storage if there is any record in TeamData table?

Go to azure portal > Under Storage account, search for the storage which was created during deployment > Click on 'Storage Explorer (preview)' from left pane > Under Tables > click on 'TeamData' table > see if there is any record

In case, you do not have storage account details follow below steps-
Go to Azure portal > Click on company communicator app service > click on 'Configuration' under settings > click on 'StorageConnectionString' name > in value field, copy 'AccountName' (this is storage account name)

![image](https://user-images.githubusercontent.com/57787129/82837348-5f7e4980-9ee6-11ea-9363-d37c8563cbc4.png)

**Comment by belasor** [comment]
Hello rashmi-dixit,

thank you for the quick response. Unfortunately there are no data in the 'TeamData' table.

I already tried to add the authors tab to see if it works after that, unfortunately this time it is also not working.

**Comment by rashmi-dixit** [comment]
@belasor - Ok, so are you saying that after you added authors app in a new team it worked? Sorry, I am little bit confused here.

**Comment by belasor** [comment]
Yes, sorry for the confusion. After I´m adding the app into the Teams space as a new tab, it is available. I though this step is only necessary for the users.

**Comment by DebGwynne** [comment]
I've got the same issue - I have the authors app installed as a tab to one team, and the users app installed to another team and via policy to a couple of test users, but it's not finding anything, not users nor teams.  I've probably done something daft, but if people could point me in the direction of my daftness, I would appreciate!

**Comment by juna-gupta** [comment]
@DebGwynne Are you searching for users while sending the message or trying the "Send to everyone" option?

If you're searching for users, the Company Communicator app doesn't support it.
If you're searching for a Team, you can only search for teams that you're part of. You could search for a distribution/security/M365 group and send messages to a set of users as well.

We have added pro-active bot installation support in the latest version, you no longer need Users to sideload/install the User's application.

Closing the issue, please re-open if you still face the issue.

**Comment by heyalter** [comment]
Hi Team

I have the same issue and checked all API Permission and the table is also empty on my side. Need urgently help
