### ISSUE TITLE
How can we tell why there are failures when sending a communication

### ISSUE THREAD

**Issue by scjohnmsft** [OfficeDev/microsoft-teams-apps-company-communicator#177]
We are sending communications to roughly 300K users and have seen at the last send there were about 13K failures.  Is there a way to tell why these failed, which users may have received the failure (so we can check and see if the communication was finally received), etc.  

Here is a list of the the recent sends & failures, as you can see the failures are increasing and we need to know why.  

Date   Started | Date completed | Success | **Failures** | Duration
6/11/2020   9:40 PM | 6/12/2020   1:39 AM | 297986 | **13354** | 3:58:07
5/28/2020   5:53 PM | 5/28/2020   9:32 PM | 303756 | **3060** | 3:39:13
5/14/2020   11:25 PM | 5/15/2020   3:27 AM | 300467 | **1929** | 4:01:50
4/23/2020   11:12 PM | 4/24/2020   1:53 AM | 293227 | **722** | 2:40:30
4/9/2020   1:04 AM | 4/9/2020   3:42 AM | 282482 | **438** | 2:37:38
3/23/2020   12:54 AM | 3/23/2020   2:37 AM | 214566 | **189** | 1:43:18

**Comment by shridharp-ms** [comment]
@scjohnmsft have you tried exporting the report for each message which has logs from app insights available?

**Comment by hunaidhanfee20** [comment]
Hello @scjohnmsft,
You can try as @shridharp-ms said. Let us know if issue still there.

Thanks
