### ISSUE TITLE
404 errors from users who have left the tenant should not be reported as delivery failure

### ISSUE THREAD

**Issue by aosolis** [OfficeDev/microsoft-teams-apps-company-communicator#179]
404 errors are reported as errors in the delivery report. Instead we should:
1. Remove users from the table who have left the tenant
2. When a 404 is encountered, remove the user from the list of recipients and do not report the error. We still want to log this event, as a warning.

**Comment by sergiorru** [comment]
Hi, suggested a pull request to working around this issue.

#187  

Best Regards!
SO.
