### ISSUE TITLE
Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

### ISSUE THREAD

**Issue by The737** [OfficeDev/microsoft-teams-apps-company-communicator#185]
Hi All. I have done everything as per the deployment guide, yet unfortunately when trying to preview or send the message I am getting a generic error message: "Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.". Any idea on how to get past it? Thank you.

**Comment by bungleweed** [comment]
I fixed this by adding the end user app to the **same team** as the Authors app is added to as a tab.

**Comment by hunaidhanfee20** [comment]
Hello @The737,
Can you please share logs or detail. Try to upload to latest if not done yet. 

Thanks
