### ISSUE TITLE
Authors ConfigTab - unavailable

### ISSUE THREAD

**Issue by RiverChen1988** [OfficeDev/microsoft-teams-apps-company-communicator#189]
![image](https://user-images.githubusercontent.com/63580108/90120770-ba109e80-dd8d-11ea-9d1c-d3a4ebb5a1b2.png)

I got this error after deploy to the Authors' team.
I did all the steps following the guide V2, 
Except that I found Step 4  that has some warnings:
![image](https://user-images.githubusercontent.com/63580108/90120953-f2b07800-dd8d-11ea-920f-0522d6622e1d.png)

I'm not sure if it's caused by this, I am still waiting for my Admin's approval.

**Comment by RiverChen1988** [comment]
Hi, my was resolved, it's because the deploy failed, after retried, it works. Thanks

**Comment by sergiorru** [comment]
> No, the same error appears on the webpage: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

That's probably an error on the config of the manifest of the admins teams app. Check the URL of the app generally is base app resource name plus .azures.net (if you're using azure front door setting).

**Comment by juna-gupta** [comment]
Closing as the issue seems to be resolved. @brad-reider Most likely the deployment failed. Please retry.
