### ISSUE TITLE
Issue with Author Tab [Help]

### ISSUE THREAD

**Issue by samuel990705** [OfficeDev/microsoft-teams-apps-company-communicator#193]
When I access the tab on the channel of authors I get the following error
![screenshot6](https://user-images.githubusercontent.com/32914066/91251815-ca157e80-e78e-11ea-85b6-fa277f4f7a82.jpg)
I have tried both on the Teams desktop app as well as a browser, neither works.

I believe it has something to do with the tenant I deployed the app in? I deployed it in a testing environment tenant. Something to do with the Tenant ID?

**Comment by sergiorru** [comment]
Hi Samuel, 

This is probably occurring because the property AuthorizedCreatorUpns does not contains your account.

Check it in the App Service.

**Comment by lampeTechnidoo** [comment]
I have  put the main email-adress before start the deployment in **AuthorizedCreatorUpns**. 
After deployed and installed to teams this error occured, so I put other mail-adresses into **AuthorizedCreatorUpns** and tried it with them, it doesn't work to.
It possible to try to debug it , to get more information? Has anyone goot ideas for best breakpoint set? I am new in the programming context so help  or hints would be usefull.

**Comment by lampeTechnidoo** [comment]
I have  put the main email-adress before start the deployment in **AuthorizedCreatorUpns**. 
After deployed and installed to teams this error occured, so I put other mail-adresses into **AuthorizedCreatorUpns** and tried it with them, it doesn't work to.
It possible to try to debug it , to get more information? Has anyone goot ideas for best breakpoint set? I am new in the programming context so help  or hints would be usefull.

**Comment by ilamb** [comment]
I have  put the main email-adress before start the deployment in **AuthorizedCreatorUpns**. 
After deployed and installed to teams this error occured, so I put other mail-adresses into **AuthorizedCreatorUpns** and tried it with them, but it doesn't work too. For a short time (part of a second) the correct screen was shown after that a screen similar to the posted screenshot was shown.
It possible to try to debug it , to get more information? Has anyone goot ideas for best breakpoint set? I am new in the programming context so help  or hints would be usefull.

**Comment by juna-gupta** [comment]
@ilamb Please check if the tenantId configured matches the tenant Id where you are installing the teams application.

**Comment by snailCorpse** [comment]
I'm having this issue too, after a fresh install. What was the outcome?
