### ISSUE TITLE
Error with Company Communicator app in Teams after deployment

### ISSUE THREAD

**Issue by manish141989** [OfficeDev/microsoft-teams-apps-company-communicator#194]
After deploying the app in my Teams channel I am getting this error:

Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

Even after refreshing the page the error occurs.

**Comment by juna-gupta** [comment]
@manish141989 Could you upgrade to latest version and retry? We have improved the error messages to reflect the teal problem in many scenarios.

**Comment by manish141989** [comment]
Please share the link for the updated version.

Regards
Manish Kumar
Collaboration Specialist Office 365
Electrolux IT
________________________________

Mobile; +48 662 124 463
E-mail: manish.kumar@electrolux.com
________________________________
[cid:image001.png@01D6C7F7.C77C4CF0]

**Comment by juna-gupta** [comment]
@manish141989 The code is pushed to the master branch in the same [repository](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator).

**Comment by manish141989** [comment]
Do I need to follow the process again as per the deployment guide Deployment guide · OfficeDev/microsoft-teams-apps-company-communicator Wiki · GitHub<https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#2-deploy-to-your-azure-subscription> ?

Any way where I can just update the code? And after that do I need to update the app in Teams app in teams admin center too with users and authors zip package?

Regards
Manish Kumar
Collaboration Specialist Office 365
Electrolux IT
________________________________

Mobile; +48 662 124 463
E-mail: manish.kumar@electrolux.com
________________________________
[cid:image001.png@01D6C95B.BEABB7E0]

**Comment by strojasc** [comment]
I have the same issue..testing

![image](https://user-images.githubusercontent.com/59068075/111001054-b9061680-8348-11eb-8d0e-3fc378f785e1.png)

**Comment by v-smahaj** [comment]
@manish141989 : You can follow migration guides for various versions to get latest code for your app. This way, your original data will also be retained.
- [v4 migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide)
- [v3 migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v3-migration-guide)
- [v2 migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v2-migration-guide)
