### ISSUE TITLE
Image URL

### ISSUE THREAD

**Issue by kgazar** [OfficeDev/microsoft-teams-apps-company-communicator#198]
When send a new message, i am trying to add Image URL from sharepoint but it doesn't appear. i think the issue related to limited dimensions or image size.

Please i need to know that is the   limited dimensions or image size i can add in Image URL

**Comment by jwsheppa** [comment]
The image needs to be stored on a publicly accessible location. SharePoint sites require authentication to view the images.

**Comment by kgazar** [comment]
In case its internal memo inside the organization and it should be only viewed internally. Is it possible?

**Comment by juna-gupta** [comment]
@kgazar Adaptive cards support public urls or DataURIs. You could explore DataURIs for internal resources.

Closing the issue. Please re-open if you face any problem with DataURIs.
