### ISSUE TITLE
Issue in setting up Dev environment 

### ISSUE THREAD

**Issue by kumaranupam21** [OfficeDev/microsoft-teams-apps-company-communicator#200]
I am trying to setup a development environment where the Actual Teams Apps are deployed in a different Office 365 tenant and the Azure resources are deployed in different one. Is that type of configuration possible? Where should I register the Azure AD app in that case in dev tenant or prod tenant?

**Comment by dj1298** [comment]
I was able to get this to work today. In step #1 of the deployment guide, it has you create an AAD app registration. This needs to be done in the tenant that has the users. 

Then in step #2, click the deploy to Azure, you will sign in to portal.azure.com for the account of where you want the Azure resources to run. For the deploy form, you must use the details from the app registration, where the users are. 

     Bot Client Id
     Bot Client secret
     sender UPN list
     Tenant Id

If you already have this deployed, you can check how you set these. Log in to portal.azure.com where the resources are deployed. Go to the resource group\App Service\Configuration. There you will see these variables. These should all come from the user's tenant app registration. 

- AllowedTenants - Tenant ID where the users are
- AuthorizedCreatorUpns - semicolon delimited list of authors UPNs
- AzureAd:ApplicaitonIdUri - api://baseresourcename.azurefd.net
- AzureAd:ClientId- App Registrations client ID from where the users are
- AzureAd:ClientSecret- secret from the app registration
- AzureAd:TenantId - Tenant ID where the users are
- MicrosoftAppId - App Registrations client ID from where the users are
- MicrosoftAppPassword - secret from the app registration


Then navigate to the Resource group, and select the web app bot. On the settings menu, the "Microsoft App ID" must be the App Registrations client ID from where the users are.

The last item is the Teams app manifest. Make sure that that 
     valid domains has the baseresourcename.azurefd.net, 
     that webApplicationInfo section you specified the Bot ID (same as the App Registrations client ID) and the api://baseresourcename.azurefd.net.
