### ISSUE TITLE
Team Communicator Author keeps failing to send to recipeients

### ISSUE THREAD

**Issue by angelovithoulkas** [OfficeDev/microsoft-teams-apps-company-communicator#201]

**Comment by angelovithoulkas** [comment]
Also when i try preview the message i keeping getting the following message
Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

**Comment by juna-gupta** [comment]
@angelovithoulkas  If possible, could you share the failures logs/ stack trace from the Application Insights?
