### ISSUE TITLE
Node-Sass Module Issues Causing Failing Deployments

### ISSUE THREAD

**Issue by bungleweed** [OfficeDev/microsoft-teams-apps-company-communicator#202]
Was getting this error over and over doing a fresh deployment today.

./src/components/SendConfirmationTaskModule/sendConfirmationTaskModule.scss
Error: ENOENT: no such file or directory, scandir 'D:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass\vendor'

Upon further investigation was getting some dependency warnings related to node-sass in the debug logs.

Fixed it by going to the console (Kudu) and running the command npm rebuild node-sass

I suspect its intermittent. https://github.com/sass/node-sass/issues/1579

**Comment by jwsheppa** [comment]
I also ran into this issue. I ended up having to completely redeploy the application.

**Comment by hunaidhanfee20** [comment]
Hello @bungleweed,
Tried syncing the app service?

Let us know if the issue still persists.
Thanks

**Comment by aosolis** [comment]
Thank you for the bug report! node-sass is no longer a dependency of this project.
