### ISSUE TITLE
Send to Security Group Fail (Authors App)

### ISSUE THREAD

**Issue by cankanat** [OfficeDev/microsoft-teams-apps-company-communicator#204]
When I try to send a news to a security group in Authors App it gives an error and the interesting part is that,  I get this error a few seconds after typing the name of the security group and this error occurs in some security groups. This does not occur in any other security group with the same properties.

The error message : **"Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists."**

This is general error message under **ClientApp/src/components/ErrorPage/errorPage.tsx**

**Comment by priyank29** [comment]
Can you please share the stack trace and the request from network panel ?

**Comment by dbernalf** [comment]
I have similar error, but failed when try validate de access calling GET /api/groupdata/verifyaccess returned a error 
Microsoft.Identity.Client.MsalUiRequiredException
 AADSTS500131: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was 'api://xxxxx.azurefd.net' and the expected audience is '7bc7xxxxxxxxxxxxxxxxxxxxxx360c4' or one of the Application Uris of this application with App ID '7bc7bxxxxxxxxxxxxxxx83a1360c4'(Company Communicator). The downstream client must request a token for the expected audience (the application that made the OBO request) and this application should use that token as the assertion.

**Comment by shridharp-ms** [comment]
@priyank29 Could you check this one?

**Comment by priyank29** [comment]
@dbernalf Do you still have this issue ? If yes, can you please check if you have given Group.Read.All permission ?
