### ISSUE TITLE
Text Formatting in the Summary

### ISSUE THREAD

**Issue by grsandeep** [OfficeDev/microsoft-teams-apps-company-communicator#206]
Can we enable Text formatting capabilities for the Summary field ?

**Comment by dbernalf** [comment]
If I am not mistaken you can use the MarkDown marking allowed on the Adaptive Cards that is explained [here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html). We are using it and it looks correctly.

**Comment by juna-gupta** [comment]
Closing the issue. As mentioned above, you can format a message with Markdown.
