### ISSUE TITLE
Images not loading on Android Teams App in Mobile

### ISSUE THREAD

**Issue by grsandeep** [OfficeDev/microsoft-teams-apps-company-communicator#207]
For us Images are not loading on Android Teams App in Mobile. Is there any resolution for this ?

**Comment by v-smahaj** [comment]
Hi @grsandeep 
Are you still facing this issue in latest version of app?

**Comment by grsandeep** [comment]
Yeah, we are still facing the issue with the latest version

**Comment by malimal99** [comment]
What was the resolution for this?
