### ISSUE TITLE
Additional Button and URL

### ISSUE THREAD

**Issue by grsandeep** [OfficeDev/microsoft-teams-apps-company-communicator#208]
Team,

We have a requirement for an additional Button and an URL, can u please help us to know where to update into the code to get a new button title and button url?

**Comment by dj1298** [comment]
Look in the Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\src\components\NewMessage folder. There you will find the newMessage.tsx.

[https://github.com/OfficeDev/microsoft-teams-company-communicator-app/blob/master/Source/Microsoft.Teams.Apps.CompanyCommunicator/ClientApp/src/components/NewMessage/newMessage.tsx](url)

This component is where you would add the button and URL.
