### ISSUE TITLE
Deleting existing messages

### ISSUE THREAD

**Issue by fosenma** [OfficeDev/microsoft-teams-apps-company-communicator#213]
Doesn't appear there's a way to delete/remove existing messages. If there is it's not clear/intuitive.

**Comment by rafagranado** [comment]
I guess there isn't. I guess it wouldn't be functional if we could.

**Comment by dj1298** [comment]
I can confirm, the Authors app does not have an option to delete messages after sending. Each recipient is getting an individual message.

**Comment by juna-gupta** [comment]
The Company Communicator app doesn't support deleting Sent messages. The authors may delete Draft messages.

If the intent is to clear all the past messages, you could delete all entities in the SentNotifications partition manually (NotificationData table). Refer to [Data Store ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Data-stores#notification-data)for more details.

Closing the issue.
