### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by kunalkankariya** [OfficeDev/microsoft-teams-apps-company-communicator#216]
I get this error after deployment was successfully completed when and accessing the azure appservice.

HTTP Error 500.30 - ANCM In-Process Start Failure

**Comment by steve-prentice** [comment]
If you're following the "Custom-domain-option" doc page, and you found the 500.30 error at step 6... then move to step 7 and fill in the ApplicationIdURI and then try step 6 again... fixed it for us. That ApplicationIdURI being blank makes the site error when trying to start, so filling in the relevant value makes it work. The doc page needs fixing.
