### ISSUE TITLE
send in chat to members of Sec/Dist/M365 groups  - Permissions needed

### ISSUE THREAD

**Issue by GHNinja** [OfficeDev/microsoft-teams-apps-company-communicator#217]
when trying to send message to members of Security group, i get this message
'Permissions needed. Ask your IT Admin to enable this option for you'

how do i enable this option?

![CC Sec group issue](https://user-images.githubusercontent.com/72394244/95569760-ea875880-0a1d-11eb-976a-5e921e530551.PNG)

**Comment by dj1298** [comment]
Look at your AAD App registration. Then go to API permissions menu. In step 4.3 of the deployment guide, it has you set 3 API permissions. I could repro this exact message when I do not have Application\Group.Read.All permissions. Can you verify you have:

Delegated - Group.Read.All

Application - Group.Read.All, and User.Read.All

**Comment by GHNinja** [comment]
i have added these App permissions now and admin consent granted.
would i then need to do anything else ? mine still says permissions needed

**Comment by biancafrigerioMS** [comment]
I have the same error! have you resolved @GHNinja ?

Thank you

**Comment by GHNinja** [comment]
i have managed to resolve it by giving it following permissions
![CC App Permisions](https://user-images.githubusercontent.com/72394244/99889358-36980080-2c4c-11eb-86f8-b29bc0e6fbfe.PNG)
