### ISSUE TITLE
Unable to logged into Company Communicator app

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#219]
Dear Developer Team,

I have completed all the[ steps from 1 to 6](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-company-communicator-app%2Fwiki%2FDeployment-guide&data=04%7C01%7Cmspmrs%40microsoft.com%7C7d56ca1f446142cd3a5f08d870bb1e19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637383296268295127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vU%2BKFepqgo0aphxy3ekQmSu3bHhiHSJRzg97TJamuPI%3D&reserved=0) to deploy the app in the organisation test tenant. 

When I tried to start the company communicator app for authors in Teams desktop client (Same issue in Teams web browser), I get the following prompt message below and then step 3 & 4 goes in an infinite loop, asking me to repeatedly logged in.

Step 1 - I sign in to Teams after clicking on the tab for Communicator app for authors
Step 2 - Pop up windows appears
Step 3 - MS Teams ask me to click "Continue" or Cancel button. I click continue 
Step 4 - Teams ask me to sign in again. So I select my MS Office account from the Microsoft login screen
Step 5 - Hour glass appears in Teams.

I suspect the following:

- The issue could be narrowed down somewhere in the configuration settings between step 3 and 4 of MS [deployment guide](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-company-communicator-app%2Fwiki%2FDeployment-guide&data=04%7C01%7Cmspmrs%40microsoft.com%7C7d56ca1f446142cd3a5f08d870bb1e19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637383296268295127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vU%2BKFepqgo0aphxy3ekQmSu3bHhiHSJRzg97TJamuPI%3D&reserved=0)
-  During my sign in process for communicator app in Teams that perhaps there was a hidden popup dialogue window that I can't see in Teams, where this hidden window was actually asking the global admin to give me consent/grant access to the communicator app? If this is the case please provide me the URL that I can pass it to our global admin to grant me access to the company communicator app.

Thank you and look forward to hearing from you soon.

Kind regards
David

**Comment by juna-gupta** [comment]
@David-Liong  This could happen if the tenant Id configured is different from the tenant where you've installed the teams application. 

If that is the case, could update the tenantId for all the resources to the tenant where you're using the application and check if the issue is resolved?

**Comment by hunaidhanfee20** [comment]
Hello @David-Liong ,
Following could be the reason:
1. If tenant where resources are deployed is different than o365 tenant where bot is installed then you need to update the tenant  in configurations. Let us know if this is the case we will help you in doing that.
2. Please make sure that you have entered proper URL in _Manfiest, App registration -> "Authentication" and "Expose an API"_ and followed the [step 3.5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication). 


Answer to your question 
> During my sign in process for communicator app in Teams that perhaps there was a hidden popup dialogue window that I can't see in Teams, where this hidden window was actually asking the global admin to give me consent/grant access to the communicator app? If this is the case please provide me the URL that I can pass it to our global admin to grant me access to the company communicator app.

https://login.microsoftonline.com/common/adminconsent?client_id=%appId%. Replace the %appId% with the Application (client) ID of Microsoft Teams author bot app (from above). (Mentioned in [Deployment Guide Step 4.4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app))

Let us know if issue still persists for you.
Thanks
