### ISSUE TITLE
Feature request: Importance setting

### ISSUE THREAD

**Issue by NickSevens** [OfficeDev/microsoft-teams-apps-company-communicator#226]
Hello,

Would it be possible to add an _Importance_ setting when creating a new message?
It would be nice to be able to send _Important_ or _Urgent_ messages for e.g. crisis communication.

Thank you in advance.

**Comment by v-smahaj** [comment]
For this app template repository, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
