### ISSUE TITLE
Users receiving messages without the receiving app

### ISSUE THREAD

**Issue by upcreek** [OfficeDev/microsoft-teams-apps-company-communicator#227]
It seems that if messages are sent to members of a team, those members will receive the message even if they don't have the receiving app installed and they get added to the UserData table. Is this the intended behaviour?

@upcreek As you say - I manually removed the three unwanted entries from the user table and no messages went.  Lovely.  Until I messaged a team they were part of, and back into the user table they went.  Not sure if that's expected behaviour or not.

_Originally posted by @DebGwynne in https://github.com/OfficeDev/microsoft-teams-company-communicator-app/issues/224#issuecomment-717785399_

**Comment by juna-gupta** [comment]
@upcreek Yes, this is expected when an author sends a message to members of a Team.

And with the latest release, we have also added pro-active bot installation support (configurable), and app will install the User app for recipients (users) who do not have it. (for all options - Send to everyone, send to members of a security, distribution or M365 group).

Closing the issue.
