### ISSUE TITLE
Users not added to Usertable

### ISSUE THREAD

**Issue by DebGwynne** [OfficeDev/microsoft-teams-apps-company-communicator#228]
We've been testing this app with a limited number of users and getting some confusing behaviour.

I added the users to a permissions policy that allows the communicator app; our global app permission policy has this switched off.
I also added them to a setup policy that included the communicator app.

Of our 19 test users, 3 did not appear in the user table.
1 appeared after his laptop crashed and he rebooted.  (Asking the others to manually sign out and back in made no difference).
1 has now appeared after I added her to a test team and then used the author app to message all members of that team.  As noted in #228, I'm not sure if it is expected behaviour, but it appears possible to (ab)use this functionality to force users into the user table.
The third is not in this week, but her AAID is not showing in the user table so I expect her to still be failing.

In a test group of <20 users, this is rather a high incidence of failure, leaving unsure if the app is robust enough to roll out comms to around 7500 users.  I'm happy to accept I may have misconfigured something, but different responses between users mostly added at the same time/date to different policies is concerning.  

Advice appreciated!!

**Comment by SubbaReddi** [comment]
I doubt it is issue with Permissions policy.  Set the permissions policy to allow all custom apps. After 24 hours try by reinstalling the bot for users .

**Comment by DebGwynne** [comment]
Our company policies do not allow us to enable all custom apps across the board, so that's a non-starters, I'm afraid.

**Comment by juna-gupta** [comment]
@DebGwynne You are probably on Company Communicator v2.x, the user table should reflect entries for all the users who install the application. If an author sends a message to all the members of a specific Team, they (members) are also added to the User table.

Could you try the latest version?

We have recently added pro-active installation support which will install the User app for users who do not have it installed.
