### ISSUE TITLE
Old Message status download Expired

### ISSUE THREAD

**Issue by Sheshank-TCS** [OfficeDev/microsoft-teams-apps-company-communicator#231]
Dear Team,

I keep on getting this error/message again and again. I tried to download a Status report for a sent message and same was done by one more Author and we keep on getting this message at specific time. How can this be stopped as its annoying. It can report it once that's it but every day 4 messages are being sent.

Please assist. Rest downloading and Company Communicator App functions are fine.

![image](https://user-images.githubusercontent.com/71570629/97719249-da2e3f00-1aec-11eb-9f7e-65f3d35fe878.png)

**Comment by garystewart247** [comment]
I am having the same issue...was this resolved for you?  If so, what steps did you take to resolve?

**Comment by priyank29** [comment]
@Sheshank-TCS @garystewart247 Do you still have this issue ? Please upgrade to latest version and let us know if its still happening.

**Comment by garystewart247** [comment]
I am not having any issues.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
