### ISSUE TITLE
Company Communicator - Deployment Failure - Conflict error in Azure resources

### ISSUE THREAD

**Issue by Nandinisreenivasa** [OfficeDev/microsoft-teams-apps-company-communicator#232]
we are facing some conflict errors while trying to integrate the Company communicator in our environment. We tried this multiple times but same error in every instance (also tried after deleted the older instance of company communicator app)

![image](https://user-images.githubusercontent.com/67216379/97958562-739e6f00-1dd3-11eb-93a7-5795f82b874c.png)

**Comment by Kressmark** [comment]
I am seing the same issue in several tenants and several regions.

**Comment by SubbaReddi** [comment]
Please follow as described in troubleshooting guide: https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Troubleshooting

**Comment by juna-gupta** [comment]
@Nandinisreenivasa @Kressmark Did you explore the troubleshooting guide? Please update if you are still getting this issue.

**Comment by Kressmark** [comment]
Yes, it works to go the Deployment Center and hit Sync again, thanks. But the first step fails 100% of the times I tried this.

**Comment by juna-gupta** [comment]
@Kressmark Thank you for updating! Yes, its not ideal, we are tracking this and plan to improve the deployment process in future updates.

Closing the issue.
