### ISSUE TITLE
Can you use the created environment to send messages from other things like Logic App?

### ISSUE THREAD

**Issue by steve-prentice** [OfficeDev/microsoft-teams-apps-company-communicator#235]
So we've installed it and it's working in Teams, thanks, that's awesome.

However we'd love to be able to use Logic Apps to send a 1:1 chat message to someone using this service (rather than using the build in Flow bot)... can we send a correctly formatted message to the Azure Functions or some such? Thanks!

**Comment by ssleeper** [comment]
I'm trying to do something similar.  It does look like getting the correctly formatted message into the company-communicator-prep queue should allow it to get automatically picked up, processed by the proper functions/queues and delivered but I'm struggling to work out what the formatting of the message should be.  If someone could confirm if this is even possible it would save me a bit of digging and experimenting.  If I do find something I'll make sure to post here to hopefully save others some time.

**Comment by shridharp-ms** [comment]
@priyank29 Could you guide here?

**Comment by steve-prentice** [comment]
Yes please @priyank29 that would be good if you can comment. :)

**Comment by priyank29** [comment]
@steve-prentice Can you please explain your scenario in detail ? I would need to understand what all components do you need and what is that you want from Logic App.
Note : The app is dependent on bots as they are used to communicate messages so they have to be part of the solution. 
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview Please see if this helps to understand the current solution overview and the dependencies.

**Comment by steve-prentice** [comment]
@priyank29 Hey. So, and I'm not sure how much sense I'll make here... but at the moment if I have a Logic App that I want to send a message as a 1:1 chat to a user in Teams I have to use the Microsoft Teams connector to "Post a message as the Flow bot to a user", that goes to the user as coming from the Flow Bot in teams. We'd like to customise that so that a message comes from some sort of corporate branded messaging bot... We've set up Company Communicator, partly with this in mind, but can't figure out how to actually do that as a 1:1 chat to a user directly from Logic Apps... the solution overview says about the Function App - Send Function... and I know Logic Apps can easily talk to Function Apps, so it almost seems a case of sending the correctly formatted stuff to the Send Function and maybe that'd do the trick... but I've no idea what to do from there. 😃 Does that make sense at all? Thanks!

**Comment by shorties** [comment]
Has anyone figured out a solution to this? I figured out how to add data to the table in Azure, so that it becomes listed as a draft, I just don't seem to know how to trigger the sending of it to all users via a flow app.

**Comment by steve-prentice** [comment]
@shorties Unfortunately not here, no. :-/ @priyank29 showed some interest briefly, but nothing came of it.

**Comment by shorties** [comment]
If there was some sort of documentation on exactly how the preparing to send function works, that solution overview is too generalized to be able to figure out how to hook into the preparing to send process. I just want to be able to trigger it to send via Power Automate. I did find this that helped me get to the point of using power automate to populate the draft messages: https://github.com/Hickey77/ccapproval

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by steve-prentice** [comment]
I would indeed still like an answer… please. It’s been over a year now.

**Comment by gsv022** [comment]
Hi @steve-prentice ,
Thanks for the suggestion. Currently we don't have this feature. We will consider it as a enhancement and add it in the future releases.

**Comment by v-royavinash** [comment]
@steve-prentice   Thanks for highlighting the feature. We have added it to the backlog and will implement in the future releases considering the priority and impact. For now we are closing the request.
