### ISSUE TITLE
Support hyperlinks in summary text

### ISSUE THREAD

**Issue by bungleweed** [OfficeDev/microsoft-teams-apps-company-communicator#237]
Hi, it would be really useful to support hyperlinks in the summary text field.

Appreciate you can have a button with a link but if you've got a message where you need to embed more than one link the ability to support hyperlink in the summary text would be really useful.

**Comment by juna-gupta** [comment]
@bungleweed You may add hyperlinks to the message summary with Markdown. Check this [link ](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#formatting-cards-with-markdown)for more details.
