### ISSUE TITLE
Source code deployment issue

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-company-communicator#238]
![image](https://user-images.githubusercontent.com/11201670/98532650-0a1ad680-2293-11eb-9f50-645b8d46e8be.png)

**Comment by Mikhail2k15** [comment]
Downgraded sdk version in global.json 
{
  "sdk": {
    "version": "3.1.108"
  }
}

**Comment by sandytsang** [comment]
@Mikhail2k15  thanks. Same issue here with deployment. It was working a few days ago. Hope someone fixes this soon.

**Comment by priyank29** [comment]
@Mikhail2k15 @sandytsang  Can you try to sync it again ? Let us know if you face this issue.
