### ISSUE TITLE
App auto install issues

### ISSUE THREAD

**Issue by bungleweed** [OfficeDev/microsoft-teams-apps-company-communicator#239]
Hi, 

Deployed the latest version and enabled the option to auto install the app. Get this error when sending messages out to a m365 group where some of the users don't already have the app installed. Seems like the auto proactive deploy app option isn't working. I've checked the external app ID is correct in the app service and the prep function. Also treble checked the API permissions in the app registration. The app is uploaded to the app catalogue with the correct app id in the manifest.json. Does anyone have the auto install option working? Warning message in the azure table:

**Failed to install application for user: . Exception: Code: NotFoundMessage: Not FoundInner error:	AdditionalData:	date: 2020-11-06T19:55:03	request-id: 6e1ff2ab-a46b-4e51-8d3b-162637cb92b4	client-request-id: 6e1ff2ab-a46b-4e51-8d3b-162637cb92b4ClientRequestId: 6e1ff2ab-a46b-4e51-8d3b-162637cb92b4Failed to install application for user: . Exception: Code: NotFoundMessage: Not FoundInner error:	AdditionalData:	date: 2020-11-06T19:55:03	request-id: 4954fd1b-cceb-4947-a0b3-4b5891b0fe89	client-request-id: 4954fd1b-cceb-4947-a0b3-4b5891b0fe89ClientRequestId: 4954fd1b-cceb-4947-a0b3-4b5891b0fe89Failed to install application for user: . Exception: Code: NotFoundMessage: Not FoundInner error:	AdditionalData:	date: 2020-11-06T19:55:03	request-id: a3ca3adb-dfd4-477e-b876-00822812df6d	client-request-id: a3ca3adb-dfd4-477e-b876-00822812df6dClientRequestId: a3ca3adb-dfd4-477e-b876-00822812df6dFailed to install application for user: . Exception: Code: NotFoundMessage: Not FoundInner error:	AdditionalData:	date: 2020-11-06T19:55:03	request-id: cee05e82-cd17-43b6-975b-fe32750d83e2	client-request-id: cee05e82-cd17-43b6-975b-fe32750d83e2ClientRequestId: cee05e82-cd17-43b6-975b-fe32750d83e2Failed to install application for user: . Exception: Code: NotFoundMessage: Not FoundInner error:	AdditionalData:	date: 2020-11-06T19:55:03	request-id: 4809a121-a434-452f-979b-908649c70da6	client-request-id: 4809a121-a434-452f-979b-908649c70da6ClientRequestId: 4809a121-a434-452f-979b-908649c70da6Failed to install application for user: . Exception: Code: NotFoundMessage: Not FoundInner error:	AdditionalData:	date: 2020-11-06T19:55:03	request-id: 6ab504ae-510c-4aa6-9879-03b7c4e73e71	client-request-id: 6ab504ae-510c-4aa6-9879-03b7c4e73e71ClientRequestId: 6ab504ae-510c-4aa6-9879-03b7c4e73e71Failed to install application for user: . Exception: Code: NotFoundMessage: Not FoundInner error:	AdditionalData:	date: 2020-11-06T19:55:03	request-id: 1ec144a0-ca01-4f32-9c24-b81bca2c9955	client-request-id: 1ec144a0-ca01-4f32-9c24-b81bca2c9955ClientRequestId: 1ec144a0-ca01-4f32-9c24-b81bca2c9955**

![image](https://user-images.githubusercontent.com/29515438/98560095-4f450580-229f-11eb-92e9-23f978dad8f5.png)

![image](https://user-images.githubusercontent.com/29515438/98560172-64219900-229f-11eb-9615-84c4420c4d6d.png)

![image](https://user-images.githubusercontent.com/29515438/98560362-98955500-229f-11eb-942a-0be71a6d9c6b.png)

**Comment by juna-gupta** [comment]
@bungleweed This could happen if the User Application was uploaded to App store and then removed/deleted. The error code "Not Found" says that the application didn't find the User application in your organization's app catalog.

Following should unblock:
1. Re-uploaded the user application to your organizations app catalog.
2. Delete/Clear the "userAppId" entity in AppConfig. (Refer to [this documentation ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Data-stores#appconfig-collection) for more details). The application id will be re-fetched and updated.
3. Restart the app service and prep function, this will update the in memory cache.

We will improve the error message in next release.

**Comment by ssleeper** [comment]
I'm running into the same issue.  I deleted the userAppId entity from the AppConfig table but it never re-populated.  The user application was never removed/deleted from the org's app catalog so I'm unsure if I should delete and re-upload as part of this.

I'm also a touch confused if the ID in the JSON file for the User app (left as default) should be what should appear as the "userAppId" entry or if it should be the "botId" that matches the Azure app registration that sets the permissions.  
Also, should this (botID) be what appears as the App ID for the Organizations app that is listed in the Teams Admin center?
