### ISSUE TITLE
Error with validation of Bearer Token

### ISSUE THREAD

**Issue by marc-ag-raona** [OfficeDev/microsoft-teams-apps-company-communicator#242]
Hi,

I'm trying the new CCv3 release and I'm facing with the next problem when the app is deployed to teams:

All my requests are failing with a status of 401 and the following http header:

WWW-Authenticate Bearer error="invalid_token", error_description="The issuer '(null)' is invalid"

Do someone faced this issue or could know of a cause of this problem? To check which is the issuer of my JWT Token I've debugged it on JWT.io and the issuer seams fine to me (I have removed some parts that could be sensible):

![imagen](https://user-images.githubusercontent.com/74311936/98836679-42ace280-2442-11eb-85a7-bb9928e33213.png)

And I followed the steps indicated on the deployment that you provided, so I'm a bit out of ideas :(

Any help would be appreaciated.

Thanks.

**Comment by marc-ag-raona** [comment]
Hi again, I've finally noticed that it was because we have the resources on another tenant than the azure AD app, and the configuration needs to be updated accordingly. But the error is a bit weird, because in this other app ([](https://github.com/OfficeDev/microsoft-teams-apps-newemployeeonboarding)) it says that the issuer https://sts.windows.net/TENANT_ID is invalid, not "(null)", so maybe that could be a minor issue to look at.

**Comment by hunaidhanfee20** [comment]
Hello @marc-ag-raona,
Seems like you have found a solution.
Let us know if this issue still persists for you.

Thanks
