### ISSUE TITLE
Send it to everyone is sending it only to few people in chat.

### ISSUE THREAD

**Issue by grumm90** [OfficeDev/microsoft-teams-apps-company-communicator#244]

**Comment by juna-gupta** [comment]
@grumm90 Can you share more details?

Note: Send to everyone option sends a message to all the users (except Guest users) in the organization who have a valid Teams license.

**Comment by grumm90** [comment]
Yes, we wanted to send a msg to all users but it only sent it to 8 and I am not sure the reason why.
When we sent it to an Org wide team, everyone got the msg.

**Comment by juna-gupta** [comment]
@grumm90 It could happen if the users do not have a valid team's license or are guest users.

In the latest version, we filter out non-licensed (Teams license) and "Guest" users with the "Send to everyone" option. However, when you send to members of Teams or members of a group (DG, SG, or M365), we do not add the filter logic.

Could you confirm if that is the case here?

If you would like to change this behavior, you could modify the filter logic and re-deploy. Please refer to [this section ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview#prepare-to-send-function) for more details.

**Comment by grumm90** [comment]
I think something related to that logic. We sent it to a large group and all of them received it.
All of our users have valid teams licenses.
The idea is to send only the licensed members is great but seems to cause some issues for us.
Could you please advise?
Do you need logs?
Regards,
Gabor

**Comment by ahmedmahmoudR** [comment]
I have the same issue 
can anyone help to solve this issue

**Comment by shridharp-ms** [comment]
Closing due to insufficient details
