### ISSUE TITLE
Issue in signing in from Teams

### ISSUE THREAD

**Issue by biancafrigerioMS** [OfficeDev/microsoft-teams-apps-company-communicator#245]
Hello, I have issues in signing in the app from Teams

I created first the resources on my personal azure subscription (bianca_frigerio@yahoo.com) in which I'm the administrator.

 
Then I gave the access as global administrator to azure subscription to a demo tenant user: **admin@M365x505974.onmicrosoft.com**

I added **admin@M365x505974.onmicrosoft.com** as AuthorizedCreatorUpn.

I added the applications (author and user) in teams and I have problems in signing in with admin@M365x505974.onmicrosoft.com.

Bianca Frigerio

**Comment by juna-gupta** [comment]
@biancafrigerioMS Could you confirm if the tenantId configured is the same as the tenant where you're using the Teams application?

**Comment by biancafrigerioMS** [comment]
@juna-gupta the tenantIds are different because are two different users (admin@M365x505974.onmicrosoft.com and bianca_frigerio@yahoo.com), in one I have Office365 (administrator role) in the other I have the azure subscription. How can I set this differently?

**Comment by juna-gupta** [comment]
@biancafrigerioMS You should put the demo tenant id. (M365x505974.onmicrosoft.com)

If you would like to use an existing deployment, update the tenant id in the configuration for all the resources.

**Comment by biancafrigerioMS** [comment]
@juna-gupta I added the tenant id in the App service configuration and in the prep-function configuratio, the only two resources where i can add the tenantId in the configuration tab

**Comment by juna-gupta** [comment]
@biancafrigerioMS Happy to know! Closing the issue.
