### ISSUE TITLE
How to update expired bot secret key in communicator app?

### ISSUE THREAD

**Issue by David-Liong** [OfficeDev/microsoft-teams-apps-company-communicator#246]
Dear team,

I have successfully installed the company communicator app from beginning to the entire end process. In regards to step 5 of https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#1-register-azure-ad-application, I have created the bot secret that will expired in 1 year time.

My question is prior to when the bot secret has  or will expired on the due date next year, **can you please tell me the process steps on how to update an expired bot secret in Azure vault and where else in the app/config settings that uses the bot secret value will need to be manually updated?**
![image](https://user-images.githubusercontent.com/71060262/99347327-d282de80-28d1-11eb-9dee-82e157de6572.png)

Perhaps if you can update the instruction on how to update an upcoming expired bot secret in the deployment guide (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) would be much appreciated for end-users who are currently using company communicator app.

Thanks.

Kind regards
David

**Comment by David-Liong** [comment]
Hi @aosolis 

Would you be able to help in giving updated instructions to the community on how to update the company communicator app if the bot secret key value has expired? 

Thanks.

**Comment by v-smahaj** [comment]
You can directly update new secret in App service's configuration. New Author's app registration secrets needs to updated at following places AuthorAppPassword, AzureAd:ClientSecret and other User app registration secrets need to update at UserAppPassword.
