### ISSUE TITLE
Problem to send messages to everyone in our organization

### ISSUE THREAD

**Issue by flpmoreno** [OfficeDev/microsoft-teams-apps-company-communicator#247]
Hi,

I am facing a problem to send message **to everyone** in our organization. we are getting some errors:

These errors are related to:
-  **TeamsConversationActivity**
- Exception while executing function: TeamsConversationActivity The remote server returned an error: (400) Bad Request

When the same message are sent to **Team or a specified people**, it works normally,

Anyone has an idea?

**Comment by juna-gupta** [comment]
Hello @flpmoreno,

TeamsConversationActivity has a different logic when an author sends a message to members of specific Teams.

Could you try following:
1. Send a message to members of an M365 / Distribution / Security group
2. Send a message to everyone
3. Share the error message captured in the message status for step 1, step 2.
4. If possible, share the failed requests from Application Insights with errors/exception details. (Go to Application Insights and check for failed requests)

**Comment by flpmoreno** [comment]
Hi @juna-gupta 

Thank you for your guideline here. It was useful.
The error was solved by setting ProactiveInstallApp to TRUE and some changes directly in the TABLE.
I got MS support to help me.

Thanks in advanced and congrats for all support here,
