### ISSUE TITLE
Messages from Authors app are queued

### ISSUE THREAD

**Issue by himani-chi** [OfficeDev/microsoft-teams-apps-company-communicator#248]
I did a new deployment of this app and all the messages sent from the Authors app are queued. If I see the service bus, I see them as scheduled. There's nothing that has moved to 'Active. It has been more than 24 hours. How do I troubleshoot?

![image](https://user-images.githubusercontent.com/48687096/99704590-90d76c80-2a66-11eb-81c1-c5ca45675696.png)

**Comment by Viniciuscs01** [comment]
Any updates on this issue?

**Comment by doshijay** [comment]
@himani-chi  or @Viniciuscs01  did you get any resolution of the issue?

**Comment by Viniciuscs01** [comment]
Hi @doshijay, 
Sorry the delay. I didn't see the notification. 
By this time, I expect that your problem is solved, but just for the records what I had to do was just resynchronize my App Service and all of Function Apps with the source control from the Azure Deployment Center.

**Comment by hunaidhanfee20** [comment]
Hello @himani-chi,
Please reopen the issue if you are still facing it.

Thanks.
