### ISSUE TITLE
Stuck on Syncing Recipients

### ISSUE THREAD

**Issue by Loic-do** [OfficeDev/microsoft-teams-apps-company-communicator#249]
Hi,

I'm testing the application in my environment.
When I try to sent a message to the whole users, the status of the message stuck on Syncing Recipients and the message is never delivered.

Regarding the installation of the application, I got some issues to deploy the template with Azure but a redeploy of the app service solve the issue. Permissions on AzureAD seems to be good to retrieve the users : 
![image](https://user-images.githubusercontent.com/74790940/99838226-117e9180-2b69-11eb-8ea3-dd8825c946ce.png)

Is there any logs to understand what's wrong with my environement ?

Thanks,
Loïc.

**Comment by juna-gupta** [comment]
@Loic-do Do you see any errors in the message status?  You can open message summary by tapping on the message under Sent messages.

It would help if you could share any failures/stack traces from Application Insights.
