### ISSUE TITLE
Permissões necessária:Apenas os organizadores e apresentadores da reunião podem gerenciar a guia para esta reunião.

### ISSUE THREAD

**Issue by ccoelho2711** [OfficeDev/microsoft-teams-apps-company-communicator#251]
Ao carregar o aplicativo personalizado para uma equipe fica aparecendo a mensagem de erro abaixo:
Permissões necessárias
Apenas os organizadores e apresentadores da reunião podem gerenciar a guia para esta reunião.
![erro-teams](https://user-images.githubusercontent.com/74799665/99860272-54446780-2b71-11eb-8b10-1a75c0362301.png)

**Comment by flpmoreno** [comment]
@ccoelho2711 tudo bem?
Sempre que abrir uma pergunta aqui, sugiro fazer em ingles. Voce vai obter respostas mais rapidas. :-)

Sobre sua questão, você setou para que os Custom Apps sejam liberados na sua organização?

https://docs.microsoft.com/pt-br/microsoftteams/manage-apps
