### ISSUE TITLE
Bot sending message to Guest accounts as well. Is it expected behavior?

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-apps-company-communicator#252]
Guest account were added to team and tried to send message using an option "Send in chat to members of the following teams". So, bot message delivered to guest accounts.

After that, tried to send message using an option "Send in chat to everyone". Here also message sending to guest accounts.
Is it expected behavior?

**Comment by juna-gupta** [comment]
@SubbaReddi When an author sends a message to members of a team, the app sends it to all the members (we do not filter Guest users). The user data is saved to UserTable for future reference.

When an author sends a message to everyone, the application syncs all the users who have a valid Teams license in that tenant except Guest users. It then sends the message to all the users in the UserTable. (the table may include Guest users if a message was sent to them in the past)

**Comment by SubbaReddi** [comment]
Thank you
