### ISSUE TITLE
Grant Consent failed

### ISSUE THREAD

**Issue by alfredolepuf** [OfficeDev/microsoft-teams-apps-company-communicator#253]
While granting consent for API permissions  with a Global Admin user the system cannot grant access for the application permission. 

There is also a warning about verified publishers for multitenant apps that started on November 9th. 2020, which I don't know if have any impact in this app.

![Screen Shot 11-25-20 at 09 03 AM 001](https://user-images.githubusercontent.com/75013143/100203563-0e85f700-2f03-11eb-90b6-7a7ebfb23d50.JPG)

**Comment by juna-gupta** [comment]
@alfredolepuf It looks like the logged-in user is not a Global administrator in the tenant. Did you try sign-in with an admin account?

Prepare link - https://login.microsoftonline.com/common/adminconsent?client_id=%appId%. Replace the %appId% with the Application (client) ID of Microsoft Teams bot app and share with the global administrator to grant the requested permissions.

Refer to this [section](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app) for more details.

**Comment by hunaidhanfee20** [comment]
Hello @alfredolepuf ,
You need to be Global administrator to consent these permissions. Please make sure that you are using Global Admin account.

To confirm this please follow these steps-
1. Navigate to portal.azure.com.
2. Sign-in with the account
3. Search or select Users.
![image](https://user-images.githubusercontent.com/64194049/118972281-037dc200-b98e-11eb-8844-2a3455bbc644.png)
4. Search Admin by the name or email and open the profile.
5. Select and check Assigned roles in left menu.
6. It should be like image below
![image](https://user-images.githubusercontent.com/64194049/118972683-72f3b180-b98e-11eb-8638-e025687422ba.png)

Let us know if issue persists. 
Thanks
