### ISSUE TITLE
Cannot find any teams when sending

### ISSUE THREAD

**Issue by Pawel-Malinowski** [OfficeDev/microsoft-teams-apps-company-communicator#262]
When choosing the audience to send the message the only available option for me is the last one because drop downs don't populate with any teams ("We couldn't find any matches"). What might be the cause of that issue? I didn't find any clues in Application Insights. I'm using the account which is the owner of the team i'm looking for.

Cannot see any teams in drop down to choose from:
![image](https://user-images.githubusercontent.com/41694313/101338557-6e728b00-387d-11eb-920a-aed020aabd63.png)

The last option works ok, i'm able to search for particular team:
![image](https://user-images.githubusercontent.com/41694313/101338233-fdcb6e80-387c-11eb-885f-3963f28fce9c.png)

As for the app version - App Service is deployed latest from master branch:
![image](https://user-images.githubusercontent.com/41694313/101341886-096d6400-3882-11eb-9b2f-6d4300c6a9ad.png)

**Comment by bungleweed** [comment]
The missing teams one is normally because you haven't installed the end user app in the team. The team needs the app installed under Manage Teams/Apps for it to add the team ID to the Team Data table in the Azure table storage.

**Comment by bungleweed** [comment]
The other issue where you cannot see any groups might be API permissions. Have you set those correctly?

**Comment by Pawel-Malinowski** [comment]
So i have both Authors and Users apps installed for that team (second one is the Users App).
![image](https://user-images.githubusercontent.com/41694313/101348841-9e755a80-388c-11eb-9cad-cbca2b9102d9.png)
But at the same time there is no rows in TeamData table storage:
![image](https://user-images.githubusercontent.com/41694313/101348904-b8af3880-388c-11eb-9aaf-ea9789670ace.png)
For the permissions i double checked and they look ok to me:
![image](https://user-images.githubusercontent.com/41694313/101348995-e1cfc900-388c-11eb-8de3-e455d7d31805.png)

**Comment by Pawel-Malinowski** [comment]
i removed the app from the team and readded it which fixed the issue, TeamData has one row and the dropdown is populated correctly
![image](https://user-images.githubusercontent.com/41694313/101350796-e2b62a00-388f-11eb-9f47-51ad964db0aa.png)

**Comment by Rykimaruh** [comment]
I have this issue too. So let me understand...the Teams needs to have the End User version of the app installed?

Is there a way to install it to every teams in the organization?
