### ISSUE TITLE
Stuck on Syncing Recipients and AppConfig table is empty

### ISSUE THREAD

**Issue by sandytsang** [OfficeDev/microsoft-teams-apps-company-communicator#264]
Hello, 

I have successfully deployed it a few times in my test tenant, but when I tried to deploy the solution again, it always stuck on syncing recipients when sending messages, and AppConfig table is empty. 

I don't understand what did I do wrong here, each time when I deploy this solution, all the steps are exactly the same, and with the same configurations. Do I need to delete the Azure Application and create a new Azure Application each time when I re-deploy this solution?

**Comment by sandytsang** [comment]
pre-function failed.
Executing 'SyncAllUsersActivity' (Reason='(null)', Id=24ba6d78-a224-4a75-9b05-f679de0ca5c7)
None.

And UserData table is also missing

**Comment by sandytsang** [comment]
I manually created UserData table in StorageAccount, now the Syncing Recipients is not stuck anymore, but give errors in the end. Failed to install the Communicator client app for users. AppConfig table only has Settings for UserAppId, not ServerUrl (I compare that with another working setup). What should do so that these table configuration will show up? Thanks!

**Comment by hunaidhanfee20** [comment]
Hello @sandytsang,
Like you said you have already deployed several times. Are you updating manifest or uploading them again every time?
If updating only then you can try to uninstall it from Team and and install again. 
Else you can also try to uninstall the app from app catalogue and upload them.

When bot get installed these values get updated in table.
Let us know if issue still persists.
Thanks

**Comment by sandytsang** [comment]
Hello. Thanks for getting back on this. I think the v4 version has lots of improvement. We managed deploy v4 for our customer and everything went ok. No issues at all. :)
