### ISSUE TITLE
Not found in the Directory

### ISSUE THREAD

**Issue by franzbuenaventura** [OfficeDev/microsoft-teams-apps-company-communicator#267]
When I installed the Author application I got an error: 
"Sign in
Sorry, but we’re having trouble signing you in.

AADSTS700016: Application with identifier '3bd1b8f2-452b-4ac3-a11d-12345e32e2f0' was not found in the directory 'a0343913-a606-4477-8d29-12345eb4cb08'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant."

The application identifier is correct when I double check. 

The only thing I'm not sure is the Tenant Id, since the Azure Subscription directory is different to my target Teams Tenant, per instruction I changed the tenant id to point on my Teams Tenant. 

Any theory on what went wrong?

**Comment by hunaidhanfee20** [comment]
Hello @franzbuenaventura,
It seems like there something wrong with Authors app registration. Can you please that steps 1, 3 and 4 are done correctly.
and Tenant Id should be of O365 tenant and is given while deployment.

Let us know if issue still persists.
Thanks
