### ISSUE TITLE
Company Communicator: Configtab - The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by Kenzeno** [OfficeDev/microsoft-teams-apps-company-communicator#268]
Hello,

Just checking out the company communicator and I'm stumbling upon the following error message when I try to add the the app as a new tap in Teams:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

This seems to be most likely because I cannot access the configuration URL: https://mydomain.azurefd.net/configtab

If I'm opening the app domain then Azure tells me that the app service if up and running.

Redeployment or sync in the deployment center did not work for me.

Any ideas?

**Comment by ruhleg** [comment]
I am also having the same issue.. did you resolve?

**Comment by haze0316** [comment]
Same issue

**Comment by nedian91** [comment]
I am also facing the same issue.

**Comment by Ochuwa-sophie** [comment]
lol, same issue. Is there support for this application?

**Comment by golubenkoff** [comment]
Hi, The same  error here - when trying to add author app  to teams -
checked everything, doing sync in deployment center and checked parameters, id's, urls, permissions.
Checked urls ( from AppService ) - the same error there.
How can we fix this ?

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by hunaidhanfee20** [comment]
Hello @Kenzeno,
The issue is resolved for many users by resyncing the app after stopping all the app services. 
Please refer to these issues : #404, #284.

Let us know if issue still persists or need any help.
Thanks

**Comment by vermagautam85** [comment]
<img width="359" alt="Screenshot 2022-06-09 at 07 44 33" src="https://user-images.githubusercontent.com/106654581/172795066-89c38065-f30e-4abb-8858-c33fb6b6168b.png">
same issue

**Comment by stevenffrench** [comment]
We are encountering this issue as well, any guidance would be greatly appreciated.

**Comment by v-royavinash** [comment]
@stevenffrench ,
This issue is already closed with the resolution. Could you please create a new issue and share us more details of the error that you are getting?
