### ISSUE TITLE
Migration From V1.x to V2.x doesn't work

### ISSUE THREAD

**Issue by SantanuPati** [OfficeDev/microsoft-teams-apps-company-communicator#270]
I have deployed version V1.x branch and wanted to migrate to V2.x. I have followed all the steps mentioned in the V2 Migration guide. Although the migration deployment succeeded but still the code branch is pointing to V1.x(see below snippet) branch in all the Azure function as well as App Service. Even new updates are not reflected. Any one have any solution?

![image](https://user-images.githubusercontent.com/76060963/102243399-24467500-3f21-11eb-8d32-6ee1d68129a7.png)

**Comment by hunaidhanfee20** [comment]
Hello @SantanuPati,
Company Communicator v4.1 is now available. Can you please try to migrate to the latest?

Let us know if the issue still persists.
Thanks
