### ISSUE TITLE
export detailed results not working in v2.x

### ISSUE THREAD

**Issue by SantanuPati** [OfficeDev/microsoft-teams-apps-company-communicator#271]
Giving below message when trying to export 
![image](https://user-images.githubusercontent.com/76060963/102272356-a09f7f00-3f46-11eb-8d18-80137a8e51f3.png)

**Comment by hunaidhanfee20** [comment]
Hello @SantanuPati,
Can you please try upgrading the Company communicator to the latest v4.1.

Let us know if you have any questions.
Thanks
