### ISSUE TITLE
Permission needed. Ask your IT admin to enable this option for you

### ISSUE THREAD

**Issue by sandytsang** [OfficeDev/microsoft-teams-apps-company-communicator#272]
![teamscc](https://user-images.githubusercontent.com/28437644/102378741-ca9c8400-3fce-11eb-9c80-5bd9b58d129b.jpg)

Would you tell me what permissions am I missing here? I have Group.Read.All permission to the app, both delegated and application permission.

**Comment by SantanuPati** [comment]
Is admin consent is provided for the permissions ?

**Comment by sandytsang** [comment]
Yes. I have give admin consent to the correct permissions. But I have redeployed the solution again, now it works.

**Comment by haze0316** [comment]
Hi Sandy. where did you give the admin consent? I have the same situation

**Comment by sandytsang** [comment]
@haze0316  from API permission page, where you add those correct permission. There is "Grant admin consent" next to "Add permission". Some times it might show only three dots like "...", depends on your browser size.
