### ISSUE TITLE
All my Teams not showing when choosing "Send in cchat to members of the following teams" 

### ISSUE THREAD

**Issue by jonnunez** [OfficeDev/microsoft-teams-apps-company-communicator#273]
Whenever I try to select this scope to send data in the author version of this app, it only gives like 2 Teams I can send it to. However I am an owner of more than 2 teams...

how does this work?

what do i need in order to see more than the 2 teams i see and send my messages to the people in those teams?

**Comment by v-smahaj** [comment]
Company Communicator User(manifest_users.json) bot needs to be installed in teams in which you want to broadcast message.
Can you confirm if it is installed?
