### ISSUE TITLE
401 error when I try to install author app onto microsoft teams

### ISSUE THREAD

**Issue by zshanthi** [OfficeDev/microsoft-teams-apps-company-communicator#274]
When I try to install the user app in teams it installs no problem

But when I try to install the author app it says

"Sorry an error occurred while trying to access this service"

On further investigations it shows

xxxxxxxxxx.azurewebsites.net/api/draftnotifications:

1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by bungleweed** [comment]
Did you ever get this resolved? Getting this same issue now accessing api/sentnotifications and api/draftnotifications for a fresh install in the application insight logs.

**Comment by snailCorpse** [comment]
Getting this error too? Is there an answer?

**Comment by cristianoag** [comment]
Well. It seems you are using a wrong AppDomain on the manifest. Check the config value for AzureAd:ApplicationIdURI in the App Service. Make sure you are using it on the manifest and not the one with azurewebsites.net.

**Comment by hunaidhanfee20** [comment]
Hello @zshanthi,
Let us know if you are still facing this issue.

Thanks.
