### ISSUE TITLE
Card preview doesn't support markup 

### ISSUE THREAD

**Issue by markusmiet** [OfficeDev/microsoft-teams-apps-company-communicator#277]
When creating a new card markup seems not to be supported, altought code calls `adaptiveCard.reder();`. I can do it manually by replacing **, etc. with html markup. But should this work by default?

![image](https://user-images.githubusercontent.com/45357894/102860314-431f9c80-4436-11eb-8b16-429fb67a3de9.png)

**Comment by hunaidhanfee20** [comment]
Hello @markusmiet,
In Preview markdown doesn't work but once you send this message it will make the test bold.
![image](https://user-images.githubusercontent.com/64194049/120653107-056f7700-c49e-11eb-8735-92b355700278.png)

Thanks
