### ISSUE TITLE
Images uploaded in a public Sharepoint not showing in the company communicator message prompt

### ISSUE THREAD

**Issue by Rykimaruh** [OfficeDev/microsoft-teams-apps-company-communicator#278]
i am trying to upload an image from the company communicator using an image from sharepoint and it's not showing. Is there a way to make this show? 

The sharepoint is public for everyone, so the app should be able to see it as well...

Any solution to this?

**Comment by hunaidhanfee20** [comment]
Hello @Rykimaruh,
Even if SharePoint is public, image is not accessible to people outside a domain. Try hitting that URL in incognito mode. You will probably not able to access it or it will ask you to sign-in. 

Let us know if you have any questions.
Thanks
