### ISSUE TITLE
cloudways.com.br requesting permission first time opening the app

### ISSUE THREAD

**Issue by haze0316** [OfficeDev/microsoft-teams-apps-company-communicator#282]
After Installing the app,

I'm getting the following Notification for first time opening the app. Is this expected? How is this related to the app? 
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/57536820/103697228-9a148e00-4f6d-11eb-9133-1fec2b1c7631.png)

**Comment by v-smahaj** [comment]
Yes, this is expected. It is asking for you to grant the permissions for the app. You can grant admin consent to all users directly from portal itself. if you are admin. Go to your Authors app registration created in step 1 of Deployment Guide. Go to API permission under Manage and click Grant admin consent. It is also mentioned in Deployment Guide Step 4.4.
