### ISSUE TITLE
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by haze0316** [OfficeDev/microsoft-teams-apps-company-communicator#284]
When trying to add the communicator author app in a team's channel, I'm getting the following message: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." 
:(

**Comment by SubbaReddi** [comment]
App service deployment might failed. Check the fix which was mentioned here: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure

**Comment by haze0316** [comment]
Thanks, I was to get it working by following the steps on the migration from v3-v4.  I was creating it from scratch at the beginning /having multiple instances of the project.

**Comment by adejeg** [comment]
I deployed an Angular App using Github Actions, and I get this error **The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.** whenever I refresh the page. I have a web.config file in my root folder but that is not working.

This error started when I started deploying using Github Actions.

Can you help me understand and fix the error?
