### ISSUE TITLE
Stuck on installing apps.

### ISSUE THREAD

**Issue by Mubarak86** [OfficeDev/microsoft-teams-apps-company-communicator#285]
I sent two messages to **every one** but stuck on installing apps. I disabled ProactivelyInstallUserApp in prep-function and app service. I deployed app through Team admin portal to all users.

I got below error when I open the message :

Warnings
Failed to install application for user: . Exception: Code: NotFound Message: Not Found Inner error: AdditionalData: date: request-id:  client-request-id:  ClientRequestId:

Any suggestion?

Thank you.

**Comment by hunaidhanfee20** [comment]
Hello @Mubarak86,
Please have a look at this issue #296.

Let us know if issue still persists.
Thanks
