### ISSUE TITLE
No Support for Right to Left Text

### ISSUE THREAD

**Issue by njglenuk** [OfficeDev/microsoft-teams-apps-company-communicator#286]
Text inserted which is written right to left is not displayed in the card as right to left, instead it is left to right. 

Teams fully supports right to left support but not the Company Communicator app. 

It would be great if this support was brought to the product, as it is required for languages such as Arabic and Hebrew.

**Comment by hunaidhanfee20** [comment]
Hello @njglenuk,
Please upgrade to the latest version of company communicator. The feature has been added.
If you have installed v3 you can migrate by following this guide.
[Company Communicator v4 Migration Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide#company-communicator-v4-migration-guide)

Let us know if you face any issue.
