### ISSUE TITLE
'serviceUrl' cannot be null or empty (Parameter 'serviceUrl')

### ISSUE THREAD

**Issue by snailCorpse** [OfficeDev/microsoft-teams-apps-company-communicator#288]
When trying to send the message to a group or users, the following message is displayed.

Exception while executing function: SendMessageFunction 'serviceUrl' cannot be null or empty (Parameter 'serviceUrl')

I have investigated to the best of my limited ability and it seems that the ServiceUrl is not present in the AppConfig table?

**Comment by snailCorpse** [comment]
@salaman, @yinaa , @NT-D, @shashishailaj is there any feedback?
I want to go live, but no messages are sending and the service fails with the message above. 

Can I revert to an earlier version?

**Comment by hunaidhanfee20** [comment]
Hello @snailCorpse,
Can you please uninstall and then install the Author bot in your teams again. Sometime bot wasn't able to update service URL. By doing this issue might get resolved. 

Let us know if issue still persists for you.
Thanks

**Comment by bahTeams** [comment]
Hi @snailCorpse ,
Did you solved this issue please ?
I have the same issue when i try to send message to office 365 group.
Thanks,
