### ISSUE TITLE
Scheduling of Messages

### ISSUE THREAD

**Issue by snailCorpse** [OfficeDev/microsoft-teams-apps-company-communicator#289]
Hi

**Enhancement request:**

Please add the ability to schedule a message for release at a certain date or time?

**Comment by hunaidhanfee20** [comment]
Hello @snailCorpse,
As of now we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

Thanks for the sugesstion.

**Comment by ssleeper** [comment]
@hunaidhanfee20  Someone did exactly that.  There is a pull request (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/pull/386) from April 8th that does implement a scheduling feature and image upload.  Can this be reviewed and possible merged in to provide a fantastic feature that I'm sure would be well received by the users of this product.

**Comment by v-smahaj** [comment]
Thanks @ssleeper.
Will take a look at pull request and request concerned team to merge with main branch.
