### ISSUE TITLE
Deployment in two tenant environment

### ISSUE THREAD

**Issue by veskunopanen** [OfficeDev/microsoft-teams-apps-company-communicator#290]
The guide has an error if you are deploying the app in a situation where Azure subscription is in another tenant than Office 365. Steps 1, 3 & 4 (App Registrations & related configurations) need to be done in the Office 365 tenant.

**Comment by v-smahaj** [comment]
Thanks @veskunopanen for reporting this. 
Will update the deployment guide to reflect mentioned changes.
