### ISSUE TITLE
Redirect URI setting missing from Users app

### ISSUE THREAD

**Issue by veskunopanen** [OfficeDev/microsoft-teams-apps-company-communicator#291]
In step 3. Set-up Authentication the Redirect URI setting (with ID Tokens) needs to be done also to Users application registration. The guide states the changes only to Authors app, but without adding the Redirect URI to Users app it won't work.

**Comment by bungleweed** [comment]
Yes I had this issue as well and had to manually enter the app URI before the app would startup properly.

**Comment by hunaidhanfee20** [comment]
Hello @veskunopanen,
In the latest version of it is working with the steps mentioned in Deployment Guide. Let us know if you are facing this issue in the latest. 
We have tried without setting Authentication in User app registration and it works fine. 

Thanks.
