### ISSUE TITLE
Adding additional authors

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-company-communicator#292]
I need to add another user to be able to publish messages via our current instance of Company Communicator.

What is the best way to do this?

**Comment by haze0316** [comment]
You need to add them in the Teams for the company communicator and in the sender UPN list of the app configuration in Azure. See no. 7 https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#2-deploy-to-your-azure-subscription

**Comment by ldougan92** [comment]
Easiest way we found was (If you've deployed the App):

- Log into portal.azure.com
- Go to App Services
- Open the Company Communicator App
- Under Settings > Configuration > AuthorizedCreatorUpns
- Add all the Authors you require
- Click OK
- Click Save

**Comment by andersonafp** [comment]
**Newest and easiest in 2025:**

- Log into portal.azure.com
- Go to App Services
- Open the "Company Communicator" (App Type: Web App)
- Under Settings > **Environment variables** > AuthorizedCreatorUpns
- Under Value: Add all the Authors you require (**email@domain.com;email@domain.com**[...]) 
- Click Apply
- Click Save
