### ISSUE TITLE
Version and Upgrading

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-company-communicator#293]
How do I know which version I am on of the communicator?

I would like to upgrade to v4.

**Comment by haze0316** [comment]
In the manifest file you uploaded. It will say what version version. ALso in the app in Teams, The version is there. 
<img width="863" alt="Screen Shot 2021-01-13 at 2 10 45 PM" src="https://user-images.githubusercontent.com/57536820/104498150-4e836500-55a9-11eb-93a2-ac243194867b.png">

**Comment by bungleweed** [comment]
If you look in Azure and the resource group and then the app service. If you go to deployment centre it will tell you which code version you are using from github. You cna then match that to v1/2/3 etc.

**Comment by JoeSMGraham** [comment]
Cheers for the above, do we have to deploy the app from scratch to update to v4?

**Comment by JoeSMGraham** [comment]
Can anyone comment on the process to upgrade an existing version to v4?

**Comment by haze0316** [comment]
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide

**Comment by JoeSMGraham** [comment]
Do I use the same guide if updating from v1 straight to v4?

Or is it worth a fresh installation?

**Comment by v-smahaj** [comment]
You can follow the [v4 migration guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide) to update the app to v4.
