### ISSUE TITLE
Warning/errors- Won't send, (AADSTS700016: Application with identifier

### ISSUE THREAD

**Issue by haze0316** [OfficeDev/microsoft-teams-apps-company-communicator#294]
Hello,

Getting the following errors/warning when I Hit send to the following scenarios. It won't send to anyone 

**Send in Chat to the following members of teams:**

Errors:
Failed to prepare the message for sending:The orchestrator function 'SendQueueOrchestrator' failed: "The activity function 'DataAggregationTriggerActivity' failed: "Specified argument was out of the range of valid values. (Parameter 'Recipient count should be > 0. Value: 0') Actual value was .". See the function execution logs for additional details.". See the function execution logs for additional details.

Warnings:
Failed to get members for team 19:19129812313144fb9c7ee3ac0287f87d@thread.tacv2: Failed to acquire token for client credentials. (AADSTS700016: Application with identifier 'eef2c663-5646-4dbb-b008-xxxxx' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. Trace ID: 166e9125-3339-4e35-9dcd-c126e23c6f00 Correlation ID: f632a923-ffe0-48f2-8301-d489ee0260f9 Timestamp: 2021-01-12 19:53:45Z)

The application with identifier doesn't seem to match to the appid/botid that i put in the author/client manifest

**Comment by DikshantMalik** [comment]
any luck with this error? i am facing same issue

**Comment by hunaidhanfee20** [comment]
Hello @haze0316 ,
It seems like there something wrong with Authors app registration. Can you please verify that permissions are granted by admin on portal. 
You can also try this way:
Go to "Microsoft Teams admin center" go to "Teams apps"->"Manage Apps" and select the Company Communicator author app.; after clicking the author app you can go to the Permissions section and click "Review permissions and consent". This action will grant consent to the author app to read the groups info.

Let us know if issue still persists.
Thanks
Let us know if this works for you.
Thanks.
