### ISSUE TITLE
Message Stuck on "Installing App" - How to Cancel

### ISSUE THREAD

**Issue by mbearchell** [OfficeDev/microsoft-teams-apps-company-communicator#296]
I'm currently testing the app and have disabled custom apps in the Teams admin center. I attempted to send a message to all users in the company and I have been stuck on "Installing App..." for 14 hours now. Is there any way to cancel the message to remove it from the queue?

Another note - in the v3 to v4 upgrade documentation ([found here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide)) under the "Add Permissions to Your App" section, I'm not clear if I'm supposed to add these permissions to the v3 app or the v4 app. The article is about deploying the v4 app, but the screenshots show the v3 app. I applied the permissions to the v4 app - not sure if that's related to the issue.

**Comment by bungleweed** [comment]
Think applying to the v4 app is correct. You should have 2 registered apps with v4. There's an authors app (needs the API permissions) and the end user app which doesn't apart from read users.

**Comment by bungleweed** [comment]
If allow custom apps is not permitted by policy or in the org wide settings the app won't proactively install. It will run through each target user and fail the proactive install. So how long it takes probably depends on how many users you're trying to send the message to. If you go into the Azure resource group you can see the tranctions under the Application Insights resource.

**Comment by mbearchell** [comment]
Thank you so much @bungleweed! You nailed it. After waiting a couple of days, the message would ultimately fail to most users. After disabling the "Auto Install" and republishing the "Authors" app, everything works great. I'll manage the app installation using a Teams policy. Thanks again for your responses!

**Comment by lukman-oyee** [comment]
Hi, **@mbearchell** can you please elaborate on how you resolve this issue. am stuck at this right now. I have a tenant with users of up to 17000, The message got deliver if I use teams or security groups. but stuck at installing if we sent to everyone.  Note we deploy the user app to org-wide using the policy. thank you

**Comment by mbearchell** [comment]
Hey @lukman-oyee  - sure thing! In my case, we were blocking custom apps in our Global Teams App Permission Policy. This meant that Company Communicator wasn't able to install the application if you enabled "Auto Install" since it's a custom app (which is blocked on the tenant level). 

In our case, the solution was:

1. Change the "Custom App" setting in the global Teams "App Permission Policy" to "Allow specific apps and block all others" then select "Company Communicator" as an app we're going to allow. 
2. Change the global Teams "App Setup Policy" and selected "Company Communicator" to auto-install on all user instances of Teams by default (so that it would get installed, even before a message is sent out). 
3. Redeploy the app to Azure using the desired "Auto Install" setting. I have found that simply changing this setting in Azure doesn't seem to work as desired, but republishing the app does.

I hope that helps!

**Comment by hunaidhanfee20** [comment]
Thank you @mbearchell  and @bungleweed.
We are closing this issue as it is solved.
