### ISSUE TITLE
How to prevent Guest Users in our Tenant seeing the Company Communicator with Teams?

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-company-communicator#298]
We need to understand how to control access to the Company Communicator App, currently guest users are able to see messages sent for internal use when they login to their teams account.

Can you advise how to prevent this?

**Comment by bungleweed** [comment]
What version are you running? I believe in the older versions of the app when you selected the send to everyone options guests were included. I believe they are now filtered out automatically in the latest version. The option to send to M365 groups etc was also introduced in a later version too. Also the option to proactively install the end user app if its not already installed was added, which removes the need to pin the app globally or install it globally in the app setup policies. 
![image](https://user-images.githubusercontent.com/29515438/105241497-ab60bb80-5b65-11eb-89da-9ab5b7a38a75.png)

**Comment by cristianoag** [comment]
You can also leverage app setup policies to block access from guests to the CC application.  

- Step 1. Create a dynamic group with guests and another with all internal users. [info](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-dynamic-membership)
- Step 2. Create and assign policies to those groups. [info](https://docs.microsoft.com/en-us/microsoftteams/assign-policies)

**Comment by hunaidhanfee20** [comment]
Hello @JoeSMGraham,
Let us know if issue still persists.
Thanks

**Comment by cristianoag** [comment]
There is no issue here. You just need to use the app setup policies. Do not use the global policy to install cc. That policy also covers guests. Use a new policy to install the app just for non-guests. Disable the proactive installation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
