### ISSUE TITLE
Button URL link with special chars (orthographic accents in Spanish) it does not work

### ISSUE THREAD

**Issue by jjgargantilla** [OfficeDev/microsoft-teams-apps-company-communicator#300]
Hi !!

I'm going to describe a problem we have with the "BUTTONLINK" (Button URL link), when this links have special characters. (Accents in Spanish)

In sharepoint we create "Communication Sites" with "news pages" that have words with accents in the name:

https://xxxxxx.sharepoint.com/sites/sitio1/Página-con-acentos.aspx

Normally, when this url is pasted from the clipboard into the form of communicator, it transforms it into a valid url like this:
https://xxxxxx.sharepoint.com/sites/Office3652/SitePages/P%C3%A1gina-con-acentos.aspx

When this happens it is saved correctly, with this last format in the table "NotificationData" in azure, and the button link is Ok.

But in some special circumstances, like for example in a safari browser on MAC, when copying the url in the BUTTONLINK form field, it copies it with the characters and saves it with those characters in "NotificationData", that is, it saves it like this :
https://xxxxxx.sharepoint.com/sites/sitio1/Página-con-acentos.aspx

When you save it this way, the BUTTONLINK doesn't work, since it considers it the wrong url. 

Curiously, from an android mobile, this link works.
At some point the encoding is not done well.

Any idea how to solve this problem?

If possible, the solution is not to remove the accents from the page ;-)

Best Regards

**Comment by JorgeALeitao** [comment]
Are extended characters support in URL strings? 

Which RFC?

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
