### ISSUE TITLE
Feature Request - Analytics and Reporting

### ISSUE THREAD

**Issue by bungleweed** [OfficeDev/microsoft-teams-apps-company-communicator#301]
Feature Request.

Could any reporting info be provided as to how many people have read or opened the message in Teams chat? Then if they have clicked the link/button? Maybe the data could somehow be captured via an event logged with the Graph API?

If it could be provided in a excel report or written to an azure table (which could then be pulled into PowerBi for example). That would be great.

**Comment by hunaidhanfee20** [comment]
Hello @bungleweed ,
Thanks for reaching out to us.

We are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

**Comment by hunaidhanfee20** [comment]
You can export Excel file of  the message notification status using *Export detailed results**. There you will be able to see if message is sent successfully and what is team/user name.
