### ISSUE TITLE
Feature Request - Support Different Message Templates/Layouts

### ISSUE THREAD

**Issue by bungleweed** [OfficeDev/microsoft-teams-apps-company-communicator#302]
Feature Request

Could support for different message templates be added? Maybe with a drop down menu for common types of message. This has been done and looks similar in this app which appears to be v similar to this app template.

https://forteams.co/listing/botcast-app/

**Comment by hunaidhanfee20** [comment]
Hello @bungleweed,
For Company Communicator we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.

Thanks.
