### ISSUE TITLE
Source Controls error everytime i deploy the App Template 

### ISSUE THREAD

**Issue by rhajj19** [OfficeDev/microsoft-teams-apps-company-communicator#303]
Hello Team, 

I am deploying company communicator for a couple of customers and all return with the same error: Source Control Conflict. It says the deployment failed with a conflict whenever it reaches the source controls creation. Can you please support on this as it seems to be the case for 3 of my customers already

**Comment by priyank29** [comment]
@rhajj19 Are you still facing this issue? Can you check this [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure).

**Comment by rhajj19** [comment]
@priyank29  i have tried but still gives an error

**Comment by matheuschulz** [comment]
Hi everyone,

@rhajj19 did you solve your problem?

Im facing the same issue, tried installing in different subscriptions/directories and still receiving the same error.
And always in the same azure function...

Resource = *-prep-function/web
Type = Microsoft.Web/sites/sourcecontrols
Status = Conflict

Status Message

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}

After following the [workaround](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#1-code-deployment-failure), as @priyank29 suggested, Im still having some issues in this function...

For example, the most recent:
[Error] Executed 'SyncGroupMembersActivity' (Failed, Id=66b646e8-593b-475c-8d73-47e345d6d024, Duration=19ms)System.ArgumentNullException : Value cannot be null. (Parameter 'clientSecret')

I followed all steps in the deployment guide and double checked every client secret.


Thank you guys in advance!

**Comment by hunaidhanfee20** [comment]
Hello @rhajj19, @matheuschulz,
The issue related to Source Control Conflict it should get resolved after syncing it as @priyank29 mentioned. You can try upgrading app service plan just for sync and try. 

Also while doing sync please stop all the service and functions then sync it. It helps many user to solve this problem.

Let us know which version you are using and if issue is still there.
Thanks
