### ISSUE TITLE
Reporting about Authors' actions

### ISSUE THREAD

**Issue by sandytsang** [OfficeDev/microsoft-teams-apps-company-communicator#307]
Hello, how can I have a report of which authors have send messages at what time and to which group/team/users? Especially when there are multiple authors, would like to have a report telling who used it to send those messages.

**Comment by hunaidhanfee20** [comment]
Hello @sandytsang,
As of now there isn't such feature available in company communicator but you can see details in Azure storage created on [Azure portal](https://portal.azure.com).
You can search it by the base-resource name. 

Once you have opened the storage account. Follow these steps:
1.  Click on _Storage explorer_. 
![image](https://user-images.githubusercontent.com/64194049/120636855-c9cbb180-c48b-11eb-8217-0d30716de8b3.png)
2.  Expand the "_Tables_" and select _"NotificationData"_ 
![image](https://user-images.githubusercontent.com/64194049/120637040-08616c00-c48c-11eb-90b3-a27e7bb02da9.png)
3. There you will see rows created for each notification and you can _"Query"_ the data according to your need.
![image](https://user-images.githubusercontent.com/64194049/120637236-452d6300-c48c-11eb-9eab-2da50cbbcdd6.png)

Let us know if you have any questions.
Thanks
