### ISSUE TITLE
Message keep fall in the Queued, User never receive the communication

### ISSUE THREAD

**Issue by doshijay** [OfficeDev/microsoft-teams-apps-company-communicator#308]
I have successfully deployed the author and user app. The author app is opening and I can able to send the communication message however it keeps staying in Queued state and the User is not able to get any communication sent by the author.

![image](https://user-images.githubusercontent.com/28859173/106143615-0c594680-6199-11eb-9a10-f3432d699a40.png)

Azure Service Bus:
![image](https://user-images.githubusercontent.com/28859173/106143750-3ad72180-6199-11eb-9683-388d22d6464d.png)

**Comment by doshijay** [comment]
> I have successfully deployed the author and user app. The author app is opening and I can able to send the communication message however it keeps staying in Queued state and the User is not able to get any communication sent by the author.

**Comment by doshijay** [comment]
@bungleweed

**Comment by Qkhan463** [comment]
Hi, i have the same issue. Did you find an answer to this issue?.

**Comment by ATshirai** [comment]
Hi, I got the same issue, yesterday.
After I synced the  prep-function application in Deploy Center(classic), it was  solved.
Company Communicator sent all queued messages.
 
Please see #248

**Comment by Qkhan463** [comment]
Does anyone know what the issue here is as i am also experiencing this after the upgrade to V4.

**Comment by jascox19** [comment]
Is there any update on this issue? I have a customer who is experiencing this exact thing. Any information that this will get solved in the next update?

**Comment by hunaidhanfee20** [comment]
Hello @doshijay,
This issue seems to be solved for some users after restarting azure functions and app service.
We are not able to repro this issue. Can you please share some logs or step to repro.

Thanks

**Comment by ITGeekBrian** [comment]
I am working with a client and we have this deployed into a Beta Environment and we are facing the queued message issue. We have  restarted the functions and the app service, but then has not helped
