### ISSUE TITLE
"We couldn't find any matches"

### ISSUE THREAD

**Issue by work-kyo** [OfficeDev/microsoft-teams-apps-company-communicator#309]
I'm fairly new to all of this and having some trouble figuring this out and would love to get some help please.

Author app is created and installed; added to teams and cannot seem to search:
![1](https://user-images.githubusercontent.com/78166802/106174354-f2047600-6162-11eb-94ba-8170351b7f10.PNG)

The "Send in chat to members of the following M365 groups" gives me the same result:
![2](https://user-images.githubusercontent.com/78166802/106174506-1b250680-6163-11eb-88b5-13093a0275eb.PNG)

In the Authors application, under Manage/API Permissions, verified:
![3](https://user-images.githubusercontent.com/78166802/106174624-3e4fb600-6163-11eb-915f-229b337833c6.PNG)

I have tried sending a message through "Send in chat to everyone", in which I'm the only one who also has the user app installed and verified it is sending through.

Is this by any chance due to the "Add MPN ID to verify publisher?"

**Comment by laracloud123** [comment]
Hi, 
Actually I have the same issue. 
<img width="748" alt="Test_CC" src="https://user-images.githubusercontent.com/75142069/106433606-ba524280-6470-11eb-8f37-e2678c9d282f.png">

**Comment by ldougan92** [comment]
@work-kyo @laracloud123  Have you added the user app to the teams in which you wish to communicate? You can do this from the Teams Admin Centre

**Comment by work-kyo** [comment]
@ldougan92 I think that was it!  Thank you!
I went into the Team itself, then general, clicked on the + at the top, manage apps, and then uploaded the user app.

Is there a way to possibly push this out by default to any team>?

**Comment by ldougan92** [comment]
@work-kyo You can publish it as an Installed App to users from the Teams Admin Centre > Teams Apps > Setup Policies > (Policy) but I think the app needs to be added to each team individually or deployed via PowerShell.

**Comment by Cusawin** [comment]
Getting the same result.  Looking in Azure Storage explorer, it appears that the "TeamData" table isn't getting populated with the Teams in the tenant.

I've deployed the app multiple times in the past week with the same result.

![image](https://user-images.githubusercontent.com/50845350/106827343-ea9f0a00-6645-11eb-90cb-4ca43efa2441.png)

**Comment by ldougan92** [comment]
@Cusawin have you added the user app to the Team you want to send communications to?

**Comment by Cusawin** [comment]
I have not.  I have ProactiveAppInstallation set to true in the configuration of the App Service.  Is it necessary to add the app to the Team(s) if this is set?  Additionally, should I add TeamsAppInstallation.ReadWriteSelfForTeam.All and TeamsAppInstallation.ReadWriteSelfForUser.All to the permissions of the Users app registration?

**Comment by ATshirai** [comment]
Hi,
I have the same issue, too.

**Comment by ldougan92** [comment]
@Cusawin @ATshirai the only way we could get this to work was to install the app manually to each team that you wish to send communications to. 

@Cusawin I have checked our permissions and we do not have them enabled they are set to admin consent required.

**Comment by Cusawin** [comment]
@ldougan92 - Thanks.  After more testing, I found the same too.  While an admin can install the users app via a setup policy, the authors app has to be added to each team.  So I created a short powershell script to add the Authors app to every team in the tenant. It's not really a scalable solution, but useful for a workshop I'm creating.

thanks for your help.

````
# It is  required to download the Teams PowerShell Public Preview module found at
# https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-install#install-teams-powershell-public-preview
$CCAppID = "<<CompanyCommunictorTeamsAppId>>"
Connect-MicrosoftTeams
$teams = Get-Team

Foreach ($team in $teams)
{
	$i = Get-TeamsAppInstallation -AppID $CCAppID -TeamId $team.GroupId
	If ($i.TeamsAppId -ne $CCAppID)
	{
		write-host "adding app to " $team.DisplayName
		Add-TeamsAppInstallation -AppID $CCAppID -TeamId $team.GroupId
	}
	else
	{
		write-host "app already installed in " $team.DisplayName
	}
}

**Comment by ldougan92** [comment]
@Cusawin no problem and thanks for the script! It was something I probably should have spent more time looking into that but we're only testing with a few teams at the moment.

**Comment by hunaidhanfee20** [comment]
Hello @work-kyo,
To see the teams you need to install user bot in each team you wanted to see in the list. 

Let us know if issue persists.
Thanks
