### ISSUE TITLE
how to set up a local instance and debug this application.

### ISSUE THREAD

**Issue by asingh263** [OfficeDev/microsoft-teams-apps-company-communicator#310]

**Comment by hunaidhanfee20** [comment]
Hello @asingh263,
To debug locally you will need all resources required for Company communicator should be deployed on your Azure subscription. You need to download the code and start it in Visual studio using its [.sln](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/master/Source) file or you can fork and clone the git repo in VS.

You need to follow [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) Step 1, 3 and 5.

There are two way you can proceed from this point. You need following resources as mentioned in [appsettings.json](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/master/Source/CompanyCommunicator/appsettings.json).
First is, You can do the deployment using ARM Template option ([Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)) and from the configuration of App service, you will get the required information. 

Or you need to create all resources manually. 
Once you have all the required information you need to fill the [appsettings.json](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/master/Source/CompanyCommunicator/appsettings.json).

For _AppDomain_ you will [ngrok ](https://ngrok.com/) or equivalent tunneling solution. You need to run it for the local host app is running on. 

Follow Step 5 of [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) just replace app domain with ngrok url.

Once done run the code using VS.
I hope this will help you in debugging.
Thanks

**Comment by sourabhnighot1991** [comment]
I tried this..but when opening the tab in Teams im getting the following error:

The reply URL specified in the request does not match the reply URLs configured for the application
