### ISSUE TITLE
How do we hide the Preview in Channel option in the Author CC App

### ISSUE THREAD

**Issue by DipanjanGhosh85** [OfficeDev/microsoft-teams-apps-company-communicator#313]
We have a unique requirement that we need to hide the **Preview in this Channel** option in the Author app for the Company Communicator .
Kindly let us know the how to go ahead and do this .
Also let us know where are the dependent html files stored for this page. Is it in the blob container ?

**Comment by hunaidhanfee20** [comment]
Hello @DipanjanGhosh85,
If you want to remove this option 
![image](https://user-images.githubusercontent.com/64194049/120478551-9a08a500-c3ca-11eb-8bfb-cd91c079afb1.png)
You need to make changes in this file : 
[/Source/CompanyCommunicator/ClientApp/src/components/OverFlow/draftMessageOverflow.tsx ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/9f23314f1cb258002b89a52dc5cb1900aaa99559/Source/CompanyCommunicator/ClientApp/src/components/OverFlow/draftMessageOverflow.tsx#L81).
You need to remove this node from there. 
Person having good knowledge of React, is best suited for this job.

The front end is created in React JS so you will find all dependent UI screens inside [/Source/CompanyCommunicator/ClientApp/src/components/](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/9f23314f1cb258002b89a52dc5cb1900aaa99559/Source/CompanyCommunicator/ClientApp/src/components)
Please let us know if you need any help.
Thanks
