### ISSUE TITLE
Failed to acquire token for client credentials..... was not found in the directory 'botframework.com'. 

### ISSUE THREAD

**Issue by haze0316** [OfficeDev/microsoft-teams-apps-company-communicator#314]
Getting the following error when sending

**Failed to create conversation with teams user:** 29:1PYk9BzSRAVKfbea2odcqVNW7MOqbmocfQzWYcKY2ZK5rqSSS8U_pN3ht8BXiRJVoCV-r8lXDDDA1mltsrazd3Q. Exception: Failed to acquire token for client credentials. (AADSTS700016: Application with identifier 'e0e02112-82a7-42a8-a4ad-8b792bbeass' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

I tried everything that I can think of (ie. Resync Functions & App Service, double check that I followed the authentication setup correctly, double check the uploaded manifests in teams, regrant admin consent in API permissions for the registrations, double checked the configurations in the associated App Service).

**Comment by etepetepe2022** [comment]
Hi, I had the same issue. Please check your secret at the app registration and at your web bot configuration.

**Comment by haze0316** [comment]
Solved this by deleting my app registrations and resource group..then reinstalling it again
