### ISSUE TITLE
Send message to M365 group - Permissions needed. Ask your IT admin to enable this option for you.

### ISSUE THREAD

**Issue by etepetepe2022** [OfficeDev/microsoft-teams-apps-company-communicator#316]
Hi everybody,

It is not possible for me to send messages to the M365 group. Which setting do I have to change in the admin center so that this is possible?
![Unbenannt](https://user-images.githubusercontent.com/76773199/107145261-aca12f00-6940-11eb-9813-a81ba3ffbf5e.PNG)

**Comment by sergiorru** [comment]
Hi,

Check the steps of grant permissions to the app: [Add permissions to your app](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app)

**Comment by fogacabr** [comment]
hi, i have the same issue, but the permissions are ok

![image](https://user-images.githubusercontent.com/81701653/113887006-7e509c00-9797-11eb-80dd-b11aff555799.png)

**Comment by noissaka** [comment]
Same issue with a new deployment. I provided the author app the required permissions on MS Graph. I can send messages through the app to channels, to everyone, and also to members of a MS Team. However it fails for M365 Groups only with the message described above.
Any tip where we can look for troubleshooting ?

**Comment by faranzazu** [comment]
Hi, I have the same issue. I already checked the API permissions for the authors app (please see next figure) but I'm still unable to send messages to M365 Groups. Any idea is welcome, thanks!
![image](https://user-images.githubusercontent.com/70083954/119212361-6d28c980-ba7d-11eb-84eb-3aca7debaeb4.png)

**Comment by faranzazu** [comment]
I found a solution: in the "_Microsoft Teams admin center_" go to "_Teams apps_"->"_Manage Apps_" and select the Company Communicator author app.; after clicking the author app you can go to the _Permissions_ section and click "_Review permissions and consent_". This action will grant consent to the author app to read the groups info.

I successfully tested this process in in two different tenants!

**Comment by hunaidhanfee20** [comment]
Hello @etepetepe2022,
If all the permission are granted by admin from portal for the authors apps then you should definitely try what @faranzazu is suggesting. 
Thank you for the solution @faranzazu.

OR 

Maybe you can try doing this by URL consent.
Mention at Deployment Guide's Step [4.4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app).

> Prepare link - https://login.microsoftonline.com/common/adminconsent?client_id=%appId%. Replace the %appId% with the Application (client) ID of Microsoft Teams author bot app (from above).

Let us know if the issue still persists for you.
Thanks.
