### ISSUE TITLE
"We couldn't find any matches" - in multi-tenant scenario

### ISSUE THREAD

**Issue by Rowdy** [OfficeDev/microsoft-teams-apps-company-communicator#317]
I have installed the Company Communicator App according to the instructions and have also looked through the extensions of [Vesa regarding Multi-Tenant Setup](https://myteamsday.com/2021/01/13/cc-multitenant/).

Unfortunately, the search for teams does not work for all options except the last one :-(
![2021-02-08 14_38_19-General (Company Communicator) _ Microsoft Teams](https://user-images.githubusercontent.com/309042/107228996-961cd580-6a1d-11eb-9279-2a52b748d9f1.png)

![2021-02-08 14_38_34-General (Company Communicator) _ Microsoft Teams](https://user-images.githubusercontent.com/309042/107228980-92894e80-6a1d-11eb-8551-4a7b3e787e59.png)

During setup I had an error that a wrong URI for the WEB redirect was entered in the Azure App Registration - Company Communicator Author. I already corrected this mistake a couple of days ago. Otherwise everything should fit.

Is this a bug or is there still an error in the configuration? 
Weird thing is that it's working for the last option.

**Comment by v-smahaj** [comment]
To see teams in the search you need to install manifest_users.json in teams you wish to send messages. Please confirm that you have installed User bot in teams. 
Let us know if your issue is not resolved.
