### ISSUE TITLE
The orchestrator function 'SendQueueOrchestrator' failed. Failed to sync all users. Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by TGiersberg** [OfficeDev/microsoft-teams-apps-company-communicator#318]
Same issue.

Hello,

Getting the following errors/warning when I Hit Send in chat to everyone. It won't send to anyone.

**Send in chat to everyone**
Errors:
Failed to prepare the message for sending:The orchestrator function 'SendQueueOrchestrator' failed: "The activity function 'DataAggregationTriggerActivity' failed: "Specified argument was out of the range of valid values. (Parameter 'Recipient count should be > 0. Value: 0') Actual value was .". See the function execution logs for additional details.". See the function execution logs for additional details.

Warnings:
Failed to sync all users. Status Code: Forbidden Exception: Code: Authorization_RequestDenied Message: Insufficient privileges to complete the operation. Inner error: AdditionalData: date: 2021-02-08T14:55:27 request-id: 652e22c8-14b6-4d49-8ee6-11e2655699e0 client-request-id: 652e22c8-14b6-4d49-8ee6-11e2655699e0 ClientRequestId: 652e22c8-14b6-4d49-8ee6-11e2655699e0

**Comment by haze0316** [comment]
Did you add the account you are using to send notification to the "sender UPN List?"
. also make sure you grant admin permission https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app

**Comment by TGiersberg** [comment]
Yes
![image](https://user-images.githubusercontent.com/77725352/107482191-9fbe4e80-6b7f-11eb-8e13-13477b3078ef.png)
and yes
![image](https://user-images.githubusercontent.com/77725352/107482446-fd529b00-6b7f-11eb-99e7-a7e0d2109d46.png)

**Comment by hunaidhanfee20** [comment]
Hello @TGiersberg,
It happens due to permission but I can see you have added all the permission. Please try once with admin account and just confirm that you have added "_**Semicolon-delimited** list of the user principal names (UPNs)_" in  _AuthorCreatorUpn_.

Let us know if issue still persists.
Thanks

**Comment by hunaidhanfee20** [comment]
Hello @TGiersberg,
You should also have a look at this issue. #316 
A user has mention 

> I found a solution: in the "Microsoft Teams admin center" go to "Teams apps"->"Manage Apps" and select the Company Communicator author app.; after clicking the author app you can go to the Permissions section and click "Review permissions and consent". This action will grant consent to the author app to read the groups info.
I successfully tested this process in two different tenants!

Let us know if this works for you.
Thanks.
