### ISSUE TITLE
Ressource not found when setting up Author App in Teams

### ISSUE THREAD

**Issue by bash0ra** [OfficeDev/microsoft-teams-apps-company-communicator#319]
Following the guide and installing the app(s) went fine. 
Adding the Cosumer part app even works fine in Teams.
However when trying to add the Authors App and trying to set ip up to a Team, where the UPN user allowed to author is owner of the Team fails with the following error:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
What could have gone wrong here?

**Comment by billcurran21** [comment]
Have you found a solution to this. I have a client who is having this same issue when deploying the author app as well.

**Comment by bash0ra** [comment]
Unfortunately we did not find a solution up to day. Did you manage to solve it in the meantime?

**Comment by bash0ra** [comment]
Just redeployed Version 4.1.0 from scratch. Now it's working. Unfortunately I cannot tell what I did differently to the last deployment except Naming the app not like the default in the first place.
