### ISSUE TITLE
Deployment Guide - Step 5

### ISSUE THREAD

**Issue by JamesDurrant21** [OfficeDev/microsoft-teams-apps-company-communicator#320]
I'm following the deployment guide, which is excellent so far...successfully completed to the end of Step 4. 

Step 5 (Create the Teams App Packages - https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) is where I'm stuck:

_"Make sure you have cloned the app repository locally."_ What? How? Where??

Tips much appreciated.

**Comment by v-smahaj** [comment]
Thank you for asking. We just updated the documentation to include steps for cloning repository. Please refer [FAQ](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Frequently-Asked-Questions-(FAQ)) page for guidance on cloning repository.
