### ISSUE TITLE
Error when deploying - The resource operation completed with terminal provisioning state 'Failed

### ISSUE THREAD

**Issue by datarchitect** [OfficeDev/microsoft-teams-apps-company-communicator#322]
Error summary below. Screenshot attached. I tried the known issues list, however it seems to be old and the template nomenclature has changed now.

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    },
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    },
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    },
    {
      "code": "Conflict",
      "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
    }
  ]
}
![error1](https://user-images.githubusercontent.com/10121511/107574096-6995d300-6c42-11eb-8bcf-499981d0c699.png)

**Comment by jupam18** [comment]
Could you solve it? Im getting the same error on the first line.

**Comment by tlingenf** [comment]
Following. I'm having the same issue.

**Comment by aprmike** [comment]
I have this issue too. I deployed to a new resource group, but still the same result.

**Comment by hunaidhanfee20** [comment]
Hello @datarchitect,
Can you please try to resync the app services and function?
1. Go into your **App service** . On the left hand side menu select _"Deployment center"_.
![image](https://user-images.githubusercontent.com/64194049/120198951-4ff3b800-c240-11eb-91ef-73f676195caa.png)

2. Once you have selected that you can "_Sync_" the app service.
![image](https://user-images.githubusercontent.com/64194049/120198984-58e48980-c240-11eb-8575-4d819001f2a0.png)

OR

You can also try this way #355 

Let us know if issue still persists.
Thanks

**Comment by rpi-drm** [comment]
Hi,

yes, after a while - maybe the third - deploy was successful.

Thank you anyway,
Peter



On 2021. May 31. at 15:18:26, hunaidhanfee20 ***@***.******@***.***>) wrote:

Hello @datarchitect<https://github.com/datarchitect>,
Can you please try to resync the app services and function?

  1.  Go into your App service . On the left hand side menu select "Deployment center".
[image]<https://user-images.githubusercontent.com/64194049/120198951-4ff3b800-c240-11eb-91ef-73f676195caa.png>

  2.  Once you have selected that you can "Sync" the app service.
[image]<https://user-images.githubusercontent.com/64194049/120198984-58e48980-c240-11eb-8575-4d819001f2a0.png>

OR

You can also try this way #355<https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/pull/355>

Let us know if issue still persists.
Thanks
