### ISSUE TITLE
Feature Request - User Read Receipts

### ISSUE THREAD

**Issue by Christopher-Henry** [OfficeDev/microsoft-teams-apps-company-communicator#323]
Feature Request

Would it be possible to extend the app to be able to provide reports on users that have read/viewed the message.

**Comment by SubbaReddi** [comment]
No feature(API) available to get read receipt information. So, app cannot be extended to achieve above requirement

**Comment by hunaidhanfee20** [comment]
Hello @Christopher-Henry,
I found this API that might help: [Get messages](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=csharp)
It require time to check if it is feasible or not.

For company communicator, we are currently only making changes to fix critical bugs or deployment failures. Please consider forking the repository to implement your improvement and post back here if you're successful.
Thanks
