### ISSUE TITLE
Sending messages to dynamic distribution groups

### ISSUE THREAD

**Issue by vladpoint** [OfficeDev/microsoft-teams-apps-company-communicator#324]
We area trying to use the option to send communications to M365 distribution groups, when we search for a static group we don't have issues but when we try to search a dynamic group no results found and we can´t send the communication to them, this is a limitation on the app, a limitation on dynamic groups or an issue on the app?

**Comment by sergiorru** [comment]
Hi Vladimir,

That’s a disign behavior, the query used to get the groups from graph api filter only the groups that have the groupTypes equals to 
Unified. On the other hand, dynamic user groups uses Unified and DynamicMembership types.

I don’t know if adding this extra parameter will incur in further problems. Btw the test is valid.

Best regards!

**Comment by ATshirai** [comment]
We want to know about that, too.

We think  to send a message to M365 dynamic groups with membership rule, so we tried it.
The result was Company Communicator 4.1 was able to  find to M365 dynamic groups and send to it.

The "\Source\CompanyCommunicator.Common\Services\MicrosoftGraph\Groups\GroupsService.cs"   has the source line: 
string filterQuery = $"groupTypes/any(c:c+eq+'Unified') and mailEnabled eq true and (startsWith(mail,'{query}') or startsWith(displayName,'{query}'))"; .

Microsoft Graph Explorer(API 1.0)
 returns some M365 groups  including the Dynamic ones, when we executed the GET request,  
  https://graph.microsoft.com/v1.0/groups?$filter=groupTypes/any(c:c+eq+'Unified') and mailEnabled eq true and  startsWith(displayName,'TEST_')&$select=displayName,groupTypes" .

Is it ok that we think Company Communicator can use M365 dynamic groups ?

**Comment by shridharp-ms** [comment]
We are investigating the ask. Presently, only static groups are supported cc: @aosolis @priyank29

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by bahTeams** [comment]
Hi @Porkai-Pandian any update on this please regarding dynamic groups ? i'm using the 5.1.0 version and still can't to search for dynamic groups.
