### ISSUE TITLE
Author tab fails to install

### ISSUE THREAD

**Issue by JesseGorlicki** [OfficeDev/microsoft-teams-apps-company-communicator#326]
I have deployed v4 app per the guide. User and author apps installed, but authors tab fails to install with following error

"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

Tried re-deploying the app several times but did not resolve issue.

Help is greatly appreciated. Thank you.

**Comment by ccampora** [comment]
Having the same issue. Just deployed today.

**Comment by ccampora** [comment]
I did a sync and waited for about 40 min to redeploy and now is working.

**Comment by JesseGorlicki** [comment]
> I did a sync and waited for about 40 min to redeploy and now is working.

how do you do a sync? do you just re-deploy?

**Comment by JesseGorlicki** [comment]
bump..
how is one to go about syncing the app? Thank you

**Comment by jeff29922** [comment]
I am a Microsoft Teams CE that is assisting a customer to install the Company Communicator App, I am running into the same issue.  We have reproduced the issue and pulled network logs in Chrome.

**Comment by jeff29922** [comment]
I've had a chance to do some analysis on this.  I have reviewed the manifest for the both the user and author tab's and they look fine, The issue actually occurs when installing the author tab, it looks like Teams is attempting to access the configuration url for the web app and it's failing.  Here is the error:

**The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.** 

The web app install seemed to go fine, I didn't see any errors during the deployment, but I didn't have hands on keyboard, the customer's Azure admin did the install and I was over the shoulder.   I will post more information as I continue to troubleshoot, in the meantime, if anyone can jump in and provide some guidance that would be great.

**Comment by ccampora** [comment]
If you are syncing from the github repository, go to the App Service that
was deployed on your subscription, then go to Deployment Center Fasttab and
do a Redeploy/sync by clicking the button with the same name. That fixed
the issue for me.

**Comment by JesseGorlicki** [comment]
@ccampora
Yeah, I redeployed like four times already over a span of two weeks. Did not make any difference.

Thanks.

**Comment by jeff29922** [comment]
@ccampora thank you for the response, we will try that.  Also we did the initial deployment manually (step by step from the deployment guide).  There is also a PowerShell script to automate the installation, I would suggest using the script as all the heavy lifting is done in Azure (minimal impact to M365).  The resource group where the web app is hosted can always be deleted without impacting the production environment.

**Comment by hunaidhanfee20** [comment]
Hello @JesseGorlicki,
Best possible solution is to to resync. As you said you have already tried that. I insist you to do it one more time after stopping the app services.

You can checkout the same issue which are solved:
1. #284
2. #404  

Is it your fresh deployment?
You can also check if deployment guides steps 3 and 4 are followed correctly.

Let us know if issue still persists.
Thanks.
