### ISSUE TITLE
Certificates insted of Client Secret

### ISSUE THREAD

**Issue by zaulich** [OfficeDev/microsoft-teams-apps-company-communicator#327]
Hi,

In both App registrations, the guide tells us to use Client Secret. Even though this is not the best practices from Microsoft. 
Can this app be used with a certificate as well? 

**_Best practices from Microsoft:_**
_Protect and manage your confidential app credentials for web apps, web APIs and daemon apps. Use certificate credentials, **not password credentials (client secrets)**. If you must use a password credential, don't set it manually. Don't store credentials in code or config, and never allow them to be handled by humans. If possible, use managed identities for Azure resources or Azure Key Vault to store and regularly rotate your credentials._ [https://docs.microsoft.com/en-us/azure/active-directory/develop/identity-platform-integration-checklist#security](url)

**Comment by v-smahaj** [comment]
Thank you for reporting this, we have added it to our backlog of issues to fix. It does not meet the bar to fix at the moment. We are currently only making changes to fix critical bugs or deployment failures.
