### ISSUE TITLE
Feature Addition - User Reactions Stats

### ISSUE THREAD

**Issue by adeelfareed** [OfficeDev/microsoft-teams-apps-company-communicator#328]
Feature - User Reactions Stats

We have recently added functionality to capture the reactions of users and store them into the Azure Tables. So what's the procedure to added that feature into the actual repository?

**Comment by v-smahaj** [comment]
Please consider forking the repository to implement your improvement and create a pull request with your solution.

**Comment by chandni-agarwal** [comment]
Hi @adeelfareed, I am working on similar customization....did you publish it somewhere....Thanks!
