### ISSUE TITLE
Failed to export detailed results on view status in sent message

### ISSUE THREAD

**Issue by jjgargantilla** [OfficeDev/microsoft-teams-apps-company-communicator#330]
When I click on "export detailed results",in a sent message, it gives the following error "Something went wrong. Try exporting the results again."
The message was sent to 5290 users.
any suggestions to this error?
Thanks

**Comment by sagarm09** [comment]
@jjgargantilla please verify your teams channel is private or public ? if its private then use public channel to add authors app it will work.

**Comment by MirianaRebeggiani** [comment]
Same issue, but I've installed the Company Communicator in a public Channel (General)

**Comment by victorsimonlee** [comment]
Hi. Any closure to this issue? I am facing the very same problem. I tried to add the app using a public team as someone suggested above, but I get the same error.

I click the "Allow" button but the file is not exported. Same thing as here: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/518
