### ISSUE TITLE
UI Missing

### ISSUE THREAD

**Issue by haspden** [OfficeDev/microsoft-teams-apps-company-communicator#331]
I've followed the deployment guide all the way through to building, installing and distributing the apps. Both the Company Communicator and Company Communicator Author app have been successfully deployed to Teams, however I have no UI for composing messages etc in fact, no UI at all, 

I've had a look at troubleshooting to see where I might have gone wrong, but can't see anything. Any pointers?

Thanks

![image](https://user-images.githubusercontent.com/4039041/108216308-3d8abe00-712a-11eb-9390-407afd3fe659.png)

**Comment by haspden** [comment]
p.s. the message delete was a shared file I shared then deleted in an attempt to sand a distribution message that way

**Comment by snailCorpse** [comment]
Make sure you install the Author app to a Team and select a channel. It will pop up as a tab on your channel and then you will get the UI

**Comment by v-smahaj** [comment]
Please install the Company Communicator Author bot in the team of senders/authors. There you will see a tab "Company Communicator", click on it and you will see the UI, you are looking for.
