### ISSUE TITLE
Messages are not received in the User app

### ISSUE THREAD

**Issue by EZ-NY** [OfficeDev/microsoft-teams-apps-company-communicator#333]
I configure and upload the Company Communicator as per instruction. All seems ok.
But, sending message seems to ok (no error in the log: Sync recipient, sending...) but nothing sent and received by the end user on the User Company communicator app. 
No logs to tell what can be wrong.

**Comment by hunaidhanfee20** [comment]
Hello @EZ-NY,
You can try to uninstall the User app and install it again and see if that works. 

Let us know if this works.
Thanks
