### ISSUE TITLE
3 hours to send 15K messages?

### ISSUE THREAD

**Issue by DanStevensonMSFT** [OfficeDev/microsoft-teams-apps-company-communicator#334]
I'm working with a company trying to use CC to send messages to 15K users... and it's taking 3 hours. Is that realistic? Is there a design guideline or best practice to help here?

**Comment by sergiorru** [comment]
I have an similar scenario I just upgraded the app service scale and this time dropped significantly.

**Comment by bungleweed** [comment]
I think there's an API throttle in Azure somewhere.

**Comment by ATshirai** [comment]
Hi, sergiorru-san.
May I ask you how long your scenario took ?
I have a scenario to send a message to a security group with 30K users.

**Comment by ATshirai** [comment]
Our CC took 41 min.  to  send messages to 31K users.

**Comment by hunaidhanfee20** [comment]
Hello @DanStevensonMSFT,
Time will get reduce on scaling up the app service.

Thanks
