### ISSUE TITLE
Rich text formatting

### ISSUE THREAD

**Issue by Ochuwa-sophie** [OfficeDev/microsoft-teams-apps-company-communicator#335]
I will like to know if the following are possible presently in the Microsoft-teams-apps-company-communicator 

- UI to allow authors use rich text formatting when typing messages.
- Ability to update logic to create Adaptive cards.

**Comment by shridharp-ms** [comment]
@Ochuwa-sophie These are not possible in this app template. You can use the customizations worked on, by Mikhail above.
