### ISSUE TITLE
Error deploying Company Communicator

### ISSUE THREAD

**Issue by hrobjartz** [OfficeDev/microsoft-teams-apps-company-communicator#336]
We are trying to deploy the communicator template to our portal but we are constantly running into issues.
Any advice? Redeploying the solution or synching the app service did not work.

Last error we got:
---
Creating an optimized production build...
Failed to compile.
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
Determining projects to restore...
All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN sass-loader@8.0.2 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
up to date in 162.09s
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.

Building the client app (this can take several minutes)

> company-communicator@4.0.0 build C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/components/SendConfirmationTaskModule/sendConfirmationTaskModule.scss
Error: ENOENT: no such file or directory, scandir 'C:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator\ClientApp\node_modules\node-sass\vendor'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! company-communicator@4.0.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the company-communicator@4.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\local\AppData\npm-cache\_logs\2021-02-25T08_16_13_054Z-debug.log
Failed exitCode=1, command=npm run build
An error has occurred during web site deployment.
npm WARN sass-loader@8.0.2 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.\r\n\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! company-communicator@4.0.0 build: `react-scripts build`\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the company-communicator@4.0.0 build script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR! C:\local\AppData\npm-cache\_logs\2021-02-25T08_16_13_054Z-debug.log\r\nC:\Program Files (x86)\SiteExtensions\Kudu\91.30201.5050\bin\Scripts\starter.cmd deploy.cmd

**Comment by ATshirai** [comment]
I've had the similer error in deploying the company communicator 4.0.
So, I made a new resource group and deployed company communicator to the new one.

**Comment by hrobjartz** [comment]
Great, thanks for the help!
Will try it.

**Comment by hunaidhanfee20** [comment]
Hello @hrobjartz,
Please try to upgrade the app service then resync it. 
Once it is synced you can revert back to initial plan.

Let us know if issue still persists.
Thanks.
