### ISSUE TITLE
Permissions is clear in document

### ISSUE THREAD

**Issue by hanwesh** [OfficeDev/microsoft-teams-apps-company-communicator#339]
From step 3 and step 4, my understanding is we only see to setup the permission for author app, not user app. Is it correct? The document is not super clear to me.

Thanks,

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app

**Comment by ATshirai** [comment]
Hi hanwesh-san
 
From Issues #316, I setup the authentication(step 3) to my user app.
It works fine.

**Comment by hunaidhanfee20** [comment]
Hello @hanwesh,
Yes, you need to add those permissions in **Author's** app only.

Thanks.
