### ISSUE TITLE
upgraded from v3 to V4

### ISSUE THREAD

**Issue by Qkhan463** [OfficeDev/microsoft-teams-apps-company-communicator#340]
Hi, i have recently upgraded from v3 to v4 and my messages are just stuck in the queue. Any suggestions as to what could be causing this issue?

**Comment by SubbaReddi** [comment]
Try restarting azure functions and app service.

**Comment by Qkhan463** [comment]
Hi thanks for that, tried that still same issue. Anything else i could try or check?.

**Comment by Qkhan463** [comment]
> Try restarting azure functions and app service.

Hi thanks for that, tried that still same issue. Anything else i could try or check?.

**Comment by hunaidhanfee20** [comment]
Hello @Qkhan463,
We aren't able to repro this issue at our end.
Can you please check logs and post us back.

Thanks
