### ISSUE TITLE
Change the 'Sent a card' text

### ISSUE THREAD

**Issue by manish141989** [OfficeDev/microsoft-teams-apps-company-communicator#341]
Is it possible to change the 'Sent a card' text when a new message arrives from Company Communicator app. Something from the message text like chat or something from our choice?

**Comment by hunaidhanfee20** [comment]
Hello @manish141989,
Can share the screenshot where you want to update it. We will let you know how to do it.
Mostly it is possible to do such changes, for such changes you need to update it in code and publish on the app service.

Thanks.
