### ISSUE TITLE
We couldn't find any matches - Company Communicator (Authors) 

### ISSUE THREAD

**Issue by jcwl2021** [OfficeDev/microsoft-teams-apps-company-communicator#344]
I've created 5 Test Teams (DO1.0 to DO5.0) but I am only able to search for DO1.0.  

I've added the necessary API permissions for both CC (User) app and CC (Author) app but I am still unable to search for other test teams (i.e. DO2.0 - DO5.0). Please advise!

![CC Issue 1](https://user-images.githubusercontent.com/80032876/111115338-696d5800-859f-11eb-8bb6-a46717c52563.png)

**Comment by Hickey77** [comment]
The Team(s) you are trying to target need the Communicator App installed.  After adding the User app, those teams should show in dropdown

**Comment by jcwl2021** [comment]
i have uploaded the user app to the app catalog and manually added the user app to each test team but i was still unable to search for other test teams. 

i was only successful after i logged into my teams admin center to manually add each test team into the communicator app (user). 

my question is, why wasnt the user app proactively installed for the users? Do I have to logged into my team admin center to add a new test team in order for it to appear in my search?

**Comment by jcwl2021** [comment]
During my research on this app, I came upon this clip https://www.youtube.com/watch?v=_dzu8HEu1AU posted in Feb 2021, which shows that it is now possible to schedule sending of messages and the message metrics of the App now extends beyond delivery status to include users' replies and reactions.

Can we confirm on the above please? @juna-gupta

**Comment by shridharp-ms** [comment]
@jcwl2021 This is not part of the company communicator app template. It is a customization you will have to develop on top of the available code base

**Comment by Hickey77** [comment]
Check out this this fork https://github.com/cristianoag/microsoft-teams-apps-company-communicator/wiki

Is not the official build but should be incorporated (IMHO).  Has scheduled send and image upload.  Shout out to @cristinoag
