### ISSUE TITLE
Send to everyone errors out

### ISSUE THREAD

**Issue by work-kyo** [OfficeDev/microsoft-teams-apps-company-communicator#348]
Got company communicator setup and it is able to send to messages to teams.
When trying to send to everyone, it only seems to send to handful of users

The error message we get:
Warnings
Failed to sync all users.  Status Code: BadRequest Exception: Code: Request_UnsupportedQuery Message: DeltaLink older than 30 days is not supported. Inner error: AdditionalData: date: 2021-03-17T13:56:54

Any idea what could be causing this?  I found a previous thread that seems to point to a SyncAllUsersActivity.cs recommendation but I can't seem to find that setting anywhere.

**Comment by SubbaReddi** [comment]
Check by following below steps:
Open application storage account
Open "UserData" table
Remove last record which is having following values:
![image](https://user-images.githubusercontent.com/69682598/111901478-7f2ac380-8a5e-11eb-9507-0f5a20054c35.png)

And then send new message which should populate deleted record and send messages.

**Comment by hunaidhanfee20** [comment]
Hello @work-kyo,
Please try what @SubbaReddi has mentioned. It sometime happens.

Please let us know if your issue still persists.
Thank you.
