### ISSUE TITLE
Sending embedded video

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-company-communicator#351]
Is this possible?  We are looking to send a video to people using company communicator?

**Comment by SubbaReddi** [comment]
Playing video inside an Adaptive Card is not supported. So, it won't work.

**Comment by hunaidhanfee20** [comment]
Hello @JoeSMGraham, 
As of now Adaptive card doesn't support video. 
Also teams is not supporting any video cards too. 

Let us know if you have any other issue.
Thanks.
