### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by Ryan-Bender** [OfficeDev/microsoft-teams-apps-company-communicator#352]
Is there an accepted file type to use in the image url? None of our images will render out?

**Comment by SubbaReddi** [comment]
Image URL must be publicly accessible to render(Ex: Images which are in SharePoint won't work. because it requires authentication). And follow the guidelines as mentioned here: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#inline-card-images

**Comment by hunaidhanfee20** [comment]
Hello @Ryan-Bender,
As @SubbaReddi said the image should be publicly accessible then only it will get render.
Also Images must be at most 1024×1024, in PNG, JPEG, or GIF format, and do not support animated GIF.

Are you able to see image on preview screen? 
![image](https://user-images.githubusercontent.com/64194049/119787868-47714980-beef-11eb-9d50-b844723f5021.png)


Please let us know if your issue still persists.
Thanks
