### ISSUE TITLE
Sending message stuck on "Syncing Recipients" 

### ISSUE THREAD

**Issue by Abhisheik-athi** [OfficeDev/microsoft-teams-apps-company-communicator#354]
Hi Team, 

We have migrated the our company communicator app to version 3 and when trying to send the message to everyone, the status is stuck in "Syncing Recipients" (for around 12 hours) . Later we found that the message wasn't sent to anyone. 

After digging through the backend data we get below error message.

1. **Error message in Notification Data storage table**
*Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'SyncAllUsersActivity' failed: "Timeout value of 01:00:00 was exceeded by function: SyncAllUsersActivity". See the function execution logs for additional details.". See the function execution logs for additional details.*

![cc2](https://user-images.githubusercontent.com/75985662/112167650-9d3b2400-8c16-11eb-9f06-3dd1518679df.jpg)

---

2. **Error message in PrepareToSendFunctionTaskHubInstances storage table**
*Orchestrator function 'SyncRecipientsOrchestrator' failed: The activity function 'SyncAllUsersActivity' failed: "Timeout value of 01:00:00 was exceeded by function: SyncAllUsersActivity". See the function execution logs for additional details.*

![cc1](https://user-images.githubusercontent.com/75985662/112166644-d2934200-8c15-11eb-8ddf-dcce930eb677.jpg)

**Comment by TheProfessional-ai** [comment]
Having the same issue has anyone figured out why this is happening?

**Comment by DikshantMalik** [comment]
same issue.. any solutions?

**Comment by Abhisheik-athi** [comment]
Hope the below resolutions helps in your case:
Due to large number of users the function is timing out at the time of syncing user activity. 
Note: Syncing of all users happen only for first time and subsequent time only the delta is synced. 

To resolve this error, please increase the function timeout. 
1.  Add the below property to the configuration of *-prep-function. 
“AzureFunctionsJobHost__functionTimeout”:”01:00:00” 
2. The current timeout is set to 1 hr, please increase the timeout as per the current total user count. 
Use the below calculation for timeout:
x: total number of users 
Timeout : (2x/(30x60x60)) hr

**Comment by hunaidhanfee20** [comment]
Hello @Abhisheik-athi,
Thanks for sharing the resolution for the issue. 

Please reopen and let us know if you are still facing any issue?
Thanks
