### ISSUE TITLE
"View Status" of V4.1  doesn't work fine with Dark mode of Teams desktop client.

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#358]
Hi, I deployed company communicator application v4.1 yesterday.
"View Status" of V4.1  doesn't work fine with Dark mode,
but  it of V4.0 works  fine.
![v41-issue-viewstatus](https://user-images.githubusercontent.com/77769064/112591393-a232ea00-8e47-11eb-8261-19714ce11e36.PNG)

**Comment by ATshirai** [comment]
I doubt this issue is caused by  the source codes of  "view status page" that specifies background style only.

Source/CompanyCommunicator/ClientApp/src/components/StatusTaskModule/statusTaskModule.tsx

Flex column className="formContainer" vAlign="stretch" gap="gap.small" styles={{ background: "white" }}

**Comment by priyank29** [comment]
@ATshirai Thanks for reporting this, the fix will be available soon. Thanks!
