### ISSUE TITLE
Generic error during .zip upload: Manifest parsing has failed

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-company-communicator#359]
Hi, I continue to have a generic error on Manifest Parsing but my manifest is standard... where I can check more details?
![image](https://user-images.githubusercontent.com/72658126/112638471-93e0d000-8e3f-11eb-9766-1c56bfb8daa6.png)

**Comment by SubbaReddi** [comment]
Upload to app studio to understand  the reason. 
teams-> app studio-> manifest editor -> import an existing app

**Comment by faalive** [comment]
> Upload to app studio to understand the reason.
> teams-> app studio-> manifest editor -> import an existing app

Issue solved: I was forgetting to put https:// before URL
