### ISSUE TITLE
Author app upload is working fine. Tried to upload the user app getting error something went wrong

### ISSUE THREAD

**Issue by Naveen-bot-creator** [OfficeDev/microsoft-teams-apps-company-communicator#361]
Author app upload is working fine. Tried to upload the user app getting error something went wrong. Tried from Teams admin center and Teams client as well same issue.

**Comment by Naveen-bot-creator** [comment]
Checked the global setting upload a custom app option is also enabled.
[company-communicator-users.zip.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/6228803/company-communicator-users.zip.zip)

**Comment by ATshirai** [comment]
Hi Naveen-bot-creator 

I have v4.1 and it works fine.

I found 2 difference between your users mainfest and mine.
1) line 29
yours: "personal"     without ","(comma)
mine: "personal",

2) line 40
yours:  "api://..."
mine:  no "api://"  domain name only 

I hope the above information helps you.

**Comment by Naveen-bot-creator** [comment]
> Hi Naveen-bot-creator
> 
> I have v4.1 and it works fine.
> 
> I found 2 difference between your users mainfest and mine.
> 
> 1. line 29
>    yours: "personal"     without ","(comma)
>    mine: "personal",
> 2. line 40
>    yours:  "api://..."
>    mine:  no "api://"  domain name only
> 
> I hope the above information helps you.

Thanks for the help it worked

**Comment by Naveen-bot-creator** [comment]
One more issue i am facing can i add the URL of SharePoint image in the author. I tried the SharePoint image link, image is not getting displayed in the author message. Does it takes the URL of image which is based on internet?

**Comment by SubbaReddi** [comment]
SharePoint images will not work. Image URL should be publicly accessible without authentication like blob image URL with public access.
