### ISSUE TITLE
Unable to upload the communicator (author) app zip file to a Team. 

### ISSUE THREAD

**Issue by Guru-S** [OfficeDev/microsoft-teams-apps-company-communicator#365]
Unable to upload the communicator (author) app zip file to a Team. 
Getting the error below -
_The resource you are looking for has been removed, has its name changed, or is temporary unavailable._

![image](https://user-images.githubusercontent.com/62424706/113310308-62b54380-9308-11eb-9117-cd91736985d0.png)

**Comment by jontheophilus** [comment]
I'm getting the same thing.

**Comment by SubbaReddi** [comment]
Two possible reasons:
1. URL might have given wrong in manifest. So, double check URL given manifest
2. App service deployment might failed. Check and resync code as mentioned in step 1 [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#problems-deploying-to-azure)

**Comment by fabiofrota** [comment]
I'm having the same issue. Deleted everything and followed the steps again, but ended up with the same problem.

**Comment by golubenkoff** [comment]
Hi, The same  error here - when trying to add author app  to teams -
checked everything, doing sync in deployment center and checked parameters, id's, urls, permissions.
Checked urls ( from AppService ) - the same error there.
How can we fix this ?

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by faranzazu** [comment]
Hi @fabiofrota and @golubenkoff, I had the same issue and it was fixed syncing again the app service.

**Comment by hunaidhanfee20** [comment]
Hello @Guru-S 
You can check what @SubbaReddi has mentioned.

Please let us know if issue still persists.
Thanks
