### ISSUE TITLE
What happens to the application if I remove the Azure (owner / admin) permissions from the account with which the Company Communicator was deployed?

### ISSUE THREAD

**Issue by JessicaSanMrtn** [OfficeDev/microsoft-teams-apps-company-communicator#366]
Hi everyone.
My question is What happens to the application if I remove the Azure (owner / admin) permissions from the account with which the Company Communicator was deployed? Will this affect the application in my Microsoft Teams in any way or is there no problem if I remove the permissions from the azure account once the application is installed and running without problems?

**Comment by v-smahaj** [comment]
@JessicaSanMrtn - Didn't get your question completely. Are you talking about removing API permissions or removing admin or owner from Azure tenant.
