### ISSUE TITLE
Single vs. Multitenant

### ISSUE THREAD

**Issue by laracloud123** [OfficeDev/microsoft-teams-apps-company-communicator#367]
Hello, 

I was wondering, if it the support account type makes a difference when registering the app (single tenant vs. multitenant). I have recently deployed the Company Communicator with an app registered for single tenant purposes and it is not working. I am wondering if that might be the reason. 

Thank you in advance, Lara

<img width="719" alt="Screenshot 2021-04-07 140928" src="https://user-images.githubusercontent.com/75142069/113864373-1c9a2d00-97ab-11eb-8f9f-e1030fd58dbd.png">

**Comment by hunaidhanfee20** [comment]
Hello @laracloud123,
Please have look at 
[Is it mandatory to choose multi-tenant account types while app registration?](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Frequently-Asked-Questions-(FAQ)#is-it-mandatory-to-choose-multi-tenant-account-types-while-app-registration)

Let us know if have any doubt.
Thanks
