### ISSUE TITLE
Does not list specific team channels or chats - Company Communicator (authors) 

### ISSUE THREAD

**Issue by naldo-gomes** [OfficeDev/microsoft-teams-apps-company-communicator#369]
Hello Team!

Can someone help me
The list of channels for specific teams or chat rooms is not appearing.

Choose how you want to sed your message

Send to General channel of specific teams
Send in chat to members of the following teams

![image](https://user-images.githubusercontent.com/75033869/115076332-cd52ab80-9ed2-11eb-95e5-0823c13d7a9a.png)

**Comment by bash0ra** [comment]
I have the same problem here. Are there any permissions missing for the bot?

**Comment by naldo-gomes** [comment]
bash0ra I also have this problem, I have already applied several permissions on the bot, but without success!

**Comment by bash0ra** [comment]
Actually you need to add the Client App manually through the Teams admin panel or via powershell to the Team where you want to send announcements to. Doing so showed the Teams to address for me. This is only necessary when you want to send to specific Teams only.

**Comment by naldo-gomes** [comment]
Thanks for the help bash0ra :D
