### ISSUE TITLE
Grant consent issue

### ISSUE THREAD

**Issue by jboehmmufg** [OfficeDev/microsoft-teams-apps-company-communicator#370]
During the install (following the guide) we are seeing this message:

_Starting November 9th, 2020 end users will no longer be able to grant consent to newly registered multitenant apps without verified publishers._

Is there a way to bypass this? It is asking for our MPN ID. (we do not have one)

**Comment by hunaidhanfee20** [comment]
Hello @jboehmmufg,
It is not required if you are using Admin's account. Just click on "Grant Admin Consent"
![image](https://user-images.githubusercontent.com/64194049/119654309-f22d2d80-be45-11eb-92af-0203679db8f8.png)
It's done.
OR
You can follow [Step 4.4.a](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app)
Let us know if issue still persists.
Thanks.
