### ISSUE TITLE
Can we add Task Module on the bot side

### ISSUE THREAD

**Issue by theogumilang** [OfficeDev/microsoft-teams-apps-company-communicator#371]
Hi, I want to add a task module to open a new HTML resource to be able to zoom the Image, but when I add a new button with task/fetch type and when I click the button it returns unable to reach the app. When I add a breakpoint on the bot controller it doesn't even hit any suggestion to add this functionality?
Here is the error message
![image](https://user-images.githubusercontent.com/29269601/115491507-50388500-a28a-11eb-8346-086cfdfb2228.png)

and here is the code I used to add the button 
![image](https://user-images.githubusercontent.com/29269601/115491600-72ca9e00-a28a-11eb-9710-7e74b532e2e7.png)

This is my controller I add a new action on the controller
![image](https://user-images.githubusercontent.com/29269601/115491675-97bf1100-a28a-11eb-914e-adbb358afa56.png)

**Comment by Mikhail2k15** [comment]
In order to add Task Module to the user bot, you need to handle OnTeamsTaskModuleFetchAsync event.

**Comment by theogumilang** [comment]
Hi thanks for your reply, I already figured it out now. thanks
