### ISSUE TITLE
Archival of olders posts in the company communicator app

### ISSUE THREAD

**Issue by Ruchi11177** [OfficeDev/microsoft-teams-apps-company-communicator#372]
Is there any way that, admins can archive the older posts of Company Communicator App.
Please let us know if there is a workaround to archive older post to a storage account. How to link it with storage account

**Comment by hunaidhanfee20** [comment]
Hello @Ruchi11177,
Sorry, I didn't get you. The sent messages can be duplicate later and can be seen in Author tab itself.
Please let us know what exactly you want to do.

Thanks.
