### ISSUE TITLE
Update wiki documentation with these FAQ

### ISSUE THREAD

**Issue by jacemoreno** [OfficeDev/microsoft-teams-apps-company-communicator#374]
Hi team - as requested by Adrian and Kiran, myself and our team have been together a comprehensive FAQ that we'd like to please add to the FAQ wiki so others can leverage. All the updated FAQ is in the PDF here: https://aka.ms/TeamsBroadcastHubPublicFAQ. I have the original (editable) file, happy to share if you would like.

**Comment by jasonwbaxter** [comment]
hi @jacemoreno  can you send me the editable file , i'll create a pull request for you. and format it in markdown so that it appears on Github.

**Comment by jacemoreno** [comment]
Awesome thanks! [​docx icon]  The Microsoft Teams Broadcast Hub 🔊 FAQs.docx<https://microsoft.sharepoint.com/:w:/t/TheMicrosoftTeamsBroadcastHub/Ea4CINdNx6dHvEz_nkLFEVkBYgLTk3i-N9l8sQGMYuTm0w?e=pxXdyS>
If you would, please save a separate copy and we’re happy to help make this easier on you so please let us know if we can. 🤜🤛

Jace Moreno | Microsoft Teams Platform Lead, Customer Success |
P: +1 -425-722-9592 | E: ***@***.******@***.***>

***@***.***D73CD9.D203C070]


Polite disclaimer: if you haven’t heard back from me, it’s probably because I don’t check this email thing very often. Try me on Teams 🙌

**Comment by jacemoreno** [comment]
Hi team – I don’t see the updated FAQ in the wiki. Did we move it somewhere else? Thanks!

Jace Moreno | Microsoft Teams Platform Lead, Customer Success |
P: +1 -425-722-9592 | E: ***@***.******@***.***>

***@***.***D756BF.9097F8E0]


Polite disclaimer: if you haven’t heard back from me, it’s probably because I don’t check this email thing very often. Try me on Teams 🙌

**Comment by jacemoreno** [comment]
Hi Jason – did this get uploaded? I got confirmation that it was closed but don’t see it up on the repo. Thank you.

Jace Moreno | Microsoft Teams Platform Lead, Customer Success |
P: +1 -425-722-9592 | E: ***@***.******@***.***>

***@***.***D757A7.CF677DA0]


Polite disclaimer: if you haven’t heard back from me, it’s probably because I don’t check this email thing very often. Try me on Teams 🙌
