### ISSUE TITLE
Send message to M365 group - Permissions needed

### ISSUE THREAD

**Issue by noissaka** [OfficeDev/microsoft-teams-apps-company-communicator#375]
I have an issue with the company communicator app I deployed for a customer. Deployment all went fine and app works except when trying to send messages to M365 Groups. Then we get a permission notice : 

![image](https://user-images.githubusercontent.com/44372101/116130465-cb4ed080-a6ba-11eb-9dcb-aa6df6ecc327.png)

I have checked all permissions in the documentation. I mean the Author app has all permissions required on Ms Graph as per the article (delegated and app permissions).

**Comment by nicoleralph** [comment]
We had to update the permissions for our client to fix this issue (see image below) 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/83247214/116568469-82736380-a8d6-11eb-9cc2-eb2f91c97d1c.png)

**Comment by hunaidhanfee20** [comment]
Hello,
You can check for as @nicoleralph said.
Please let us know if your issue still persists.

Thanks
