### ISSUE TITLE
Unable to upload Author or User App to Teams

### ISSUE THREAD

**Issue by JohnK-hub** [OfficeDev/microsoft-teams-apps-company-communicator#377]
Hi,
I am receiving the message 'We can't upload the App please try again' for both the Author and User App. I have checked and my Permissions policies allow uploading of custom apps. I have run a debug on the manifests and altered a few errors but cannot see where this may be failing. Any help gratefully received. Kind regards, JohnK
![We can't upload the App](https://user-images.githubusercontent.com/83338520/116382705-19281d80-a80e-11eb-844a-8ccb6c50063b.PNG)
[Company-Communicator-Authors.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/6390770/Company-Communicator-Authors.zip)
[Company-Communicator-Users.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/6390771/Company-Communicator-Users.zip)

**Comment by Mikhail2k15** [comment]
I you have a lot of mistakes in app manifest. 
![image](https://user-images.githubusercontent.com/11201670/116461251-b4ea7580-a870-11eb-8b8c-fce8079ef548.png)
![Uploading image.png…]()

**Comment by hunaidhanfee20** [comment]
Hello @JohnK-hub,
As mentioned by @Mikhail2k15. I am adding few more fields to correct.
1. You need to update developer block in both the app manifest.
2. In authors manifest botId is incorrect at both places
![image](https://user-images.githubusercontent.com/64194049/119652336-95c90e80-be43-11eb-8ba2-5af998840b22.png)
![image](https://user-images.githubusercontent.com/64194049/119652452-c0b36280-be43-11eb-9c42-ebdffd73c386.png)
You need to remove ">>" brackets.
3. I see your manifest file name is Manifest_.json and Manifest.json but it should be manifest.json (lowercase) 

Thanks
