### ISSUE TITLE
Unable to debug this Application - Sign In Issue

### ISSUE THREAD

**Issue by dipincluster** [OfficeDev/microsoft-teams-apps-company-communicator#378]
Here is what I have done so far,

1. I am using Ngrok to tunnel the requests 
![image](https://user-images.githubusercontent.com/10240411/116476722-3f46cf80-a899-11eb-8166-1c55cb8a4a78.png)

2. I have created a test Teams Author Application by changing the config url and sso url to Ngrok url
![image](https://user-images.githubusercontent.com/10240411/116476995-a2386680-a899-11eb-8531-c811ae990127.png)

3. I have added Ngrok url to the Redirect URL list in my AD App
![image](https://user-images.githubusercontent.com/10240411/116477150-d7dd4f80-a899-11eb-9843-3584be9e1d98.png)

The Requests are tunneling through as you can see in the first screenshot but the problem is in the Teams Author App the Tab is not loading(it shows draft and sent messages loading view for few seconds) and its showing Sign In Button. even after Sign in its the same.
Is there anything I am missing here

![image](https://user-images.githubusercontent.com/10240411/116477903-e1b38280-a89a-11eb-87d4-6c6a73f4b5ed.png)

**Comment by dipincluster** [comment]
I made a small change to the 2nd step where I am setting  sso url to Ngrok url, now instead of that I am using the application id uri set in expose API  tab azure. Still I am getting below error

![image](https://user-images.githubusercontent.com/10240411/116511096-8c4f9380-a8e3-11eb-8b47-4dff0846c3ef.png)

**Comment by hunaidhanfee20** [comment]
Hello @dipincluster,
To debug application locally you need to put ngrok URL in Authentication(as you already entered), Expose An API, Manifest -> [validDomains, webApplicationInfo, configurableTabs] as well as in bot channel registration. 

Few points you can have look again.
1. Please make sure that you have added all permission _(mentioned in deployment guide's step 4)_ and granted admin consent
2. Please check that you have properly followed deployment guide's step 3.5
![image](https://user-images.githubusercontent.com/64194049/118954994-ed670600-b97b-11eb-8e8a-b1aeed6281c8.png)
3. Please check if you are using the correct Bot Id.

Let us know if issue still persists for you.
