### ISSUE TITLE
Markdown doesn't work in new message dialog. 

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-company-communicator#379]
![image](https://user-images.githubusercontent.com/11201670/116508644-741f4a80-a8ca-11eb-8bad-600a318e20f2.png)

![image](https://user-images.githubusercontent.com/11201670/116508401-f8250280-a8c9-11eb-8756-ec6ed7460d5c.png)

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by Porkai-Pandian** [comment]
It's supported with latest version of the CC app, hence closing it

**Comment by Mikhail2k15** [comment]
@Porkai-Pandian I don't see it in the latest version. Could you merge this old but still actual? PR #376

**Comment by Porkai-Pandian** [comment]
Thanks @Mikhail2k15, yes we verified it and this feature will be released in v5.2 along with other features, current ETA for v5.2 is Jul 2022.
