### ISSUE TITLE
Need to know what transformation is applied to store ConversationId. 

### ISSUE THREAD

**Issue by JorgeALeitao** [OfficeDev/microsoft-teams-apps-company-communicator#381]
Need to know what transformation is applied to store ConversationID in CC's Data Store. 

In order to troubleshoot send errors where logs show Unable to Decrypt ConversatinID for some users. 

Using Graph we could retrieve current ConversationID between user and bot, but can't compare with data stored under CC Data Store as format is different - most likely hashed.

Thanks in advance.

**Comment by hunaidhanfee20** [comment]
Hello @JorgeALeitao ,
There is no transformation applied to conversation Id.
You can see here [UserDataService.cs](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/9f23314f1cb258002b89a52dc5cb1900aaa99559/Source/CompanyCommunicator.Common/Services/User/UserDataService.cs#L91).

You can also have look at:  [IConversationUpdateActivity](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.iconversationupdateactivity?view=botbuilder-dotnet-stable#properties).

Thanks
