### ISSUE TITLE
AuthCode, instead of Implicit, in authentication step 3?

### ISSUE THREAD

**Issue by UbhiTS** [OfficeDev/microsoft-teams-apps-company-communicator#383]
In setting up authentication below in step number 3 below
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication

Can we switch from the implicit flow
![image](https://user-images.githubusercontent.com/3799525/116952675-154a3000-ac40-11eb-9880-7ac39d92900e.png)

to auth_code flow for added security ?
![image](https://user-images.githubusercontent.com/3799525/116952608-e7fd8200-ac3f-11eb-80cb-3130ebd89b2e.png)

**Comment by priyank29** [comment]
### Company Communicator : SSO without Implicit Flow

**1) Pre-Consenting the application :**

- For new apps, at the time of registration
- Under Manage, click on Authentication to bring up authentication settings
- Add a new entry to Redirect URIs:
    >    - Type: Web
    >    - Redirect URI: Enter https://%appDomain%/signin-simple-end for the URL e.g. https://appName.azurefd.net/signin-simple-end
    >  - Do not check anything under Implicit grant.
    >  - Click Save to commit your changes.

- For old app registration, please go to authentication following above steps and uncheck ID Token box.
- After the code deployment and before installing the app, ask the admin to consent the application for all users in the tenant. https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app
- When the author installs the app, the app can be used without any consent.

**2) User consenting the application :**

- For new apps, at the time of registration
- Under Manage, click on Authentication to bring up authentication settings
- Add a new entry to Redirect URIs:
    
    > - Type: Web
    > - Redirect URI: Enter https://%appDomain%/signin-simple-end for the URL e.g. https://appName.azurefd.net/signin-simple-end
    > - Do not check anything under Implicit grant.
    > - Click Save to commit your changes.

- For old app registration, please go to authentication following above steps and uncheck ID Token box.
- When the author installs the app, the app has to be consented by the author.
- For graph permissions, please follow the steps in Deployment Guide https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app
