### ISSUE TITLE
I have upgraded the App from v1 to v4

### ISSUE THREAD

**Issue by ajinkya-ghare** [OfficeDev/microsoft-teams-apps-company-communicator#384]
I have upgraded the App from v1 to v4, the app deployment didn't had any error, but when we have uploaded the author app we are getting "Sorry, you do not have permission to access this page. Please contact your administrator to be granted permission." through the upn is already included

**Comment by cristianoag** [comment]
Are you sure you're using the UPN? I've seen this error before with people using the email address in setups with UPN != email.

**Comment by hunaidhanfee20** [comment]
Hello @ajinkya-ghare,

As @cristianoag mentioned. Please confirm that you have entered right UPN. You can check it in App Service configuration by opening the App service and select Configuration at the left menu as you can see in image below.
![image](https://user-images.githubusercontent.com/64194049/118953216-3f0e9100-b97a-11eb-8b50-342b6b05b4d3.png)

Also please make sure that if you have more than one UPN then it should be semicolon separated. You can also check App insights for the errors.
Let us know if issue still persists for you.
