### ISSUE TITLE
Why adaptive card can't adapt to the width of message?

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-company-communicator#387]
Customer feedback: "Why adaptive card can't adapt to the width of message? I sent the card using the CC, and it looks like this: 
![image](https://user-images.githubusercontent.com/11201670/117179131-7eb27600-addb-11eb-98c5-cf2fe7e18095.png)

How do I adjust the adaptive card so that it can fill the blank space of the message?"

**Comment by hunaidhanfee20** [comment]
Hello @Mikhail2k15,
The feature to make Adaptive card full width is released recently. This feature is not currently implemented in current version of Company Communicator.

Here's how you can do that:
[Full Width Adaptive Card (Microsoft Docs)](https://developer.microsoft.com/en-us/microsoft-teams/blogs/five-new-features-enhancing-adaptive-cards-in-microsoft-teams/)

Here's the link to the newly released features:
[Five new features enhancing Adaptive Cards in Microsoft Teams](https://developer.microsoft.com/en-us/microsoft-teams/blogs/five-new-features-enhancing-adaptive-cards-in-microsoft-teams/)

**Comment by Mikhail2k15** [comment]
dear @hunaidhanfee20 as you can see I implemented this in a linked PR #382
