### ISSUE TITLE
General Channel of Specific teams & Chat to members of the following teams

### ISSUE THREAD

**Issue by dipincluster** [OfficeDev/microsoft-teams-apps-company-communicator#389]
The dropdown control for the following 2 options is not auto filling on change 
1. send to the General Channel of Specific teams
2. send in chat to members of the following teams
![image](https://user-images.githubusercontent.com/10240411/117261929-5aec4000-ae6e-11eb-963d-da897d3e51f6.png)

is it missed when developing or is it a bug?

in the Client App code there is only 1 controller to get the group data which is used by (groups, Distribution groups or security groups ) option to get the groups data on the change event.
![image](https://user-images.githubusercontent.com/10240411/117262326-bfa79a80-ae6e-11eb-94a4-45ff4e63f76d.png)

Below is the Code to render Groups radio button, and onSearchQueryChange is set and the same is calling the controller to get data but this is missing in the above 2 options.
![image](https://user-images.githubusercontent.com/10240411/117263219-b10db300-ae6f-11eb-8e0e-3aec69234f3a.png)

there is no onSearchQueryChange event which is doing the same for the above mentioned first 2 options.

![image](https://user-images.githubusercontent.com/10240411/117263128-96d3d500-ae6f-11eb-863a-66644ff3a505.png)

**Comment by golubenkoff** [comment]
The same for me - did you fix this?

**Comment by priyank29** [comment]
@dipincluster @golubenkoff If you are using version 4.0 or greater then you have to install the user app to the team you want to send message.
