### ISSUE TITLE
 Status remains 'sending...' after message has been sent on the Author app

### ISSUE THREAD

**Issue by shina00** [OfficeDev/microsoft-teams-apps-company-communicator#390]
After sending a message with the Author app, the message status remains 'sending...', and the recipients remain 0 for both success and failed messages, this is after the users have successfully received the message. I have tried refreshing, it doesn't work. I need a suggestion please

**Comment by hunaidhanfee20** [comment]
Hello @shina00,
Can you please more details from Application insights?
 It should get reflected even without refreshing. 
Are you able to "_view status_" or "_duplicate_" the message.

We were not able to repro this issue. Let us know if issue still persists for you.
Thanks.
