### ISSUE TITLE
The Company Communicator Author app does not see Teams, DLs and Identities. 

### ISSUE THREAD

**Issue by Tech-Savi** [OfficeDev/microsoft-teams-apps-company-communicator#392]
I have recently deployed the Company Comms Author app and can successfully send out comms to all. However when I trying and select a Team, Identity or DL it does not seem to have visibility. Can anyone please advise? TIA.

![image](https://user-images.githubusercontent.com/76950409/117819026-0deade00-b261-11eb-88f8-14319cd7a3dd.png)

You can see there are Teams created on the left.

**Comment by deniscooper** [comment]
same issue here too

**Comment by Tech-Savi** [comment]
Hi Denis. Thank you for your reply. I installed and deployed the user app. My understanding is that the author app should be capable of targeting specific identities, not just all. Unfortunately the author app cannot see any identities of users, DL’s or Teams names.

**Comment by Tech-Savi** [comment]
I have now tested this @deniscooper and you were spot on. Thank you!
