### ISSUE TITLE
I need help to assess the impacts of changing the use HTTPS Only and FTPS Only

### ISSUE THREAD

**Issue by WellRamos198307** [OfficeDev/microsoft-teams-apps-company-communicator#395]
Good afternoon, I need help to assess the impacts of changing the use of HTTPS Only and FTPS Only on the authentication of the Company Communicator interface and services. Will it be necessary to change the source code?
![MicrosoftTeams-image (1) format](https://user-images.githubusercontent.com/45700759/118032961-9b503000-b33e-11eb-835f-63776e6b1f13.png)

**Comment by shridharp-ms** [comment]
@priyank29 Could you share inputs on this one? Thx

**Comment by aosolis** [comment]
There should be no impact for this change. No need to change the source code.
Httpsonly is now set in the ARM template: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/36a00a7009379c440a4e41b668ea8f575017003f/Deployment/azuredeploy.json#L266
In the next release, we will also disable FTP deployment by default.
