### ISSUE TITLE
Bot is not valid. Errors: The bot name is already registered to another bot application/ Login Loop in Authors App

### ISSUE THREAD

**Issue by Max-Enrico** [OfficeDev/microsoft-teams-apps-company-communicator#397]
I've tried to install the app some times, even with removing all components at the beginning. 

Most, i got an error: Bot is not valid. Errors: The bot name is already registered to another bot application. Errors: The bot name is already registered to another bot application.
The bot app was already removed by deleting the resource group and the app registration as well as enterprise applications in Azure AD are cleaned up before. Where is the problem here?

Nevertheless, i got it installed with one interesting message:
"Bot is not valid. Errors: The bot name is already registered to another bot application."

After uploading the apps i got an login loop for the authors app.
Azure and O365 have the same tenant id.

I read an other issue entry for the logon loop with the outcome, that the naming of resources should not contain "Company" or "Communicator" but here i ran into the first issue with the bot.

Any suggestions? 

Here the full powershell log:
----------------------------------------------------------------
.\deploy.ps1
Checking if Azure CLI is installed.
Azure CLI is installed.
Checking if the required modules are installed...
Az module is available.
AzureAD module is available.
WriteAscii module is available.
All the modules are available!
Validating all the parameters from parameters.json.
                                                                                                         _               _                           _  _
  ___   ___   _ __ ___   _ __    __ _  _ __   _   _      ___   ___   _ __ ___   _ __ ___   _   _  _ __  (_)  ___   __ _ | |_   ___   _ __    __   __| || |
 / __| / _ \ | '_ ` _ \ | '_ \  / _` || '_ \ | | | |    / __| / _ \ | '_ ` _ \ | '_ ` _ \ | | | || '_ \ | | / __| / _` || __| / _ \ | '__|   \ \ / /| || |_
| (__ | (_) || | | | | || |_) || (_| || | | || |_| |   | (__ | (_) || | | | | || | | | | || |_| || | | || || (__ | (_| || |_ | (_) || |       \ V / |__   _|
 \___| \___/ |_| |_| |_|| .__/  \__,_||_| |_| \__, |    \___| \___/ |_| |_| |_||_| |_| |_| \__,_||_| |_||_| \___| \__,_| \__| \___/ |_|        \_/     |_|
                        |_|                   |___/                                                                     
Starting deployment...
Login with with your Azure subscription account. Launching Azure sign-in window...

WARNING: The default web browser has been opened at https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
WARNING: You have logged in. Now let us find all the subscriptions to which you have access...
Azure AD sign-in...
Checking for resources availability...
resource: CompCommunicator of type webapp is available.
resource: CompCommunicator-data-function of type webapp is available.
resource: CompCommunicator-function of type webapp is available.
resource: CompCommunicator-prep-function of type webapp is available.
Application Insights resource (CompCommunicator) is available.

Creating Azure AD App: CompCommunicator...
Waiting for app creation to finish...
Azure AD App: CompCommunicator is created.
Updating app secret...
WARNING: The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
Azure AD App: CompCommunicator registered successfully.

Creating Azure AD App: CompCommunicator-authors...
Waiting for app creation to finish...
Azure AD App: CompCommunicator-authors is created.
Updating app secret...
WARNING: The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see https://aka.ms/azadsp-cli
Azure AD App: CompCommunicator-authors registered successfully.
Creating resource group test-companycommunicator...
Scan CompCommunicator source control configuration for conflicts
ERROR: (ResourceNotFound) The Resource 'Microsoft.Web/sites/CompCommunicator' under resource group 'test-companycommunicator' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Scan CompCommunicator-prep-function source control configuration for conflicts
ERROR: (ResourceNotFound) The Resource 'Microsoft.Web/sites/CompCommunicator-prep-function' under resource group 'test-companycommunicator' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Scan CompCommunicator-function source control configuration for conflicts
ERROR: (ResourceNotFound) The Resource 'Microsoft.Web/sites/CompCommunicator-function' under resource group 'test-companycommunicator' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Scan CompCommunicator-data-function source control configuration for conflicts
ERROR: (ResourceNotFound) The Resource 'Microsoft.Web/sites/CompCommunicator-data-function' under resource group 'test-companycommunicator' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

Deploying app services, Azure function, bot service, and other supporting resources... (this step can take over an hour)
Finished deploying resources. ARM template deployment succeeded.
Sync CompCommunicator code from latest version
Sync CompCommunicator-prep-function code from latest version
Sync CompCommunicator-function code from latest version
Sync CompCommunicator-data-function code from latest version
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...                                                                          Source control deployment is still in progress. Next check in 2 minutes.                                                Checking source control deployment progress...                                                                          Source control deployment is still in progress. Next check in 2 minutes.                                                Checking source control deployment progress...                                                                          Source control deployment is still in progress. Next check in 2 minutes.                                                Checking source control deployment progress...                                                                          Source control deployment is still in progress. Next check in 2 minutes.                                                Checking source control deployment progress...                                                                          Source control deployment is still in progress. Next check in 2 minutes.                                                Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Checking source control deployment progress...
Source control deployment is still in progress. Next check in 2 minutes.
Source control deployment is done.
Reading deployment outputs...
Updating required parameters and urls...

User app already configured.

Admin consent permissions is required for app registration using CLI
Do you want to proceed?
[Y] Yes  [N] No  [?] Hilfe (Standard ist "N"): y
Waiting for admin consent to finish...
Admin consent has been granted.

Updating authors app...
Another object with the same value for property identifierUris already exists.
App URI set
App reply-urls set
App optionalclaim set.
Scope access_as_user added.
Teams mobile/desktop and web clients applications pre-authorized.

Generating package for authors...
Package has been created under this path C:\installation\company-communicator\manifest\CC-authors.zip

Generating package for users...
Package has been created under this path C:\installation\company-communicator\manifest\CC-users.zip
     _               _                                        _                                      _        _              _
  __| |  ___  _ __  | |  ___   _   _  _ __ ___    ___  _ __  | |_      ___   ___   _ __ ___   _ __  | |  ___ | |_   ___   __| |
 / _` | / _ \| '_ \ | | / _ \ | | | || '_ ` _ \  / _ \| '_ \ | __|    / __| / _ \ | '_ ` _ \ | '_ \ | | / _ \| __| / _ \ / _` |
| (_| ||  __/| |_) || || (_) || |_| || | | | | ||  __/| | | || |_    | (__ | (_) || | | | | || |_) || ||  __/| |_ |  __/| (_| | _
 \__,_| \___|| .__/ |_| \___/  \__, ||_| |_| |_| \___||_| |_| \__|    \___| \___/ |_| |_| |_|| .__/ |_| \___| \__| \___| \__,_|(_)
             |_|               |___/                                                         |_|                        

Account                              SubscriptionName           TenantId                             Environment
-------                              ----------------           --------                             -----------
xxxxxx.xxxxxxx@xxxxxxxx.onmicrosoft.com Nutzungsbasierte Bezahlung xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx AzureCloud
----------------------------------------------------------------
 thanks in advance,
 Enrico

**Comment by hunaidhanfee20** [comment]
Hello @Max-Enrico,
It seems like the deployment is completed successfully. Are you facing this issue while installing manifest in Teams?

Please let us know
Thanks

**Comment by Max-Enrico** [comment]
Hello @hunaidhanfee20,

no, installing the apps to teams works. When i assign the authors app to a team and go to the authors tab, i can't sign in.
My account is the install account and is set within the web app setting AuthorizedCreatorUpns. 

For that i saw an similar closed issue described here: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/343
So i tried to remove all and reinstall it with different names, but there my deployment failed with the already registered bot name.

Do you have an idea, what can i do or check to solve it.
 
thank you in advance,
Enrico

**Comment by hunaidhanfee20** [comment]
Hello @Max-Enrico,

I would like you to confirm few things:
1. Can you please check Authentication -> Redirect Uri and Expose an API in Author's app registration. 
Redirect Uri should be https://{your_app_domain}//signin-simple-end.
Expose an API should be api://{your_app_domain} and if you scroll down you should see two App Ids.
![image](https://user-images.githubusercontent.com/64194049/119639584-601d2900-be35-11eb-8849-21fbed60cb34.png)


 * For this you need to go to [Azure Portal](https://portal.azure.com) -> Sign-in with Id you used while doing PowerShell deployment.
 * Go to App registration and search for your app {Base Resource Name}-authors.
 * On the left hand side you will find **"Authentication"** and **"Expose an API"**.

2. If you are trying to re-install the manifest in team and your getting a pop-up like this 
![image](https://user-images.githubusercontent.com/64194049/119636160-fe0ef480-be31-11eb-82db-859c1ea8e812.png)
Then you should Go to "Apps" and select "Built for {your org}" and then look for your app & uninstall from there. After this you will be able to install again.
![image](https://user-images.githubusercontent.com/64194049/119636918-bd63ab00-be32-11eb-871a-adaefb2e92dc.png)
(You can also do this from [Teams Admin](https://admin.teams.microsoft.com/).)
4. You can just try to uninstall the app from Authors team and re-install it.
* For this click " **...** " next to your team name  and select "Manage Team" from option and go to "Apps" uninstall from there.
![image](https://user-images.githubusercontent.com/64194049/119638421-4202f900-be34-11eb-8d61-feec22bb14f5.png)

I hope one of the solution will work for you.
Please let us know if issue still persists.

Thanks

**Comment by Max-Enrico** [comment]
Hello @hunaidhanfee20,

thank you for your instruction. I checked that out.
The Redirect URI is set correctly to https://compcommunicator.azurefd.net/signin-simple-end.

At Expose an API/ Set the App ID URI i have an ID api://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
If i want to change it to api://compcommunicator.azurefd.net i got an error message
"Failed to update  application property. Error detail: Another object with the same value for property identifierUris already exists. [looks like a secret]"

I've checked the other App registrations but no one is set to tapi://compcommunicator.azurefd.net

Thank you,
Enrico

**Comment by hunaidhanfee20** [comment]
Hello @Max-Enrico,
I forgot to mention one thing that you need to look in Authors app registration: {baseResourceName}-authors.

So, lets check few more thing:
1. It should be "_api://compcommunicator.azurefd.net_" everywhere.
2. Update it in Author's app registration -> "_Expose an API_".
1. Verify this URL "_api://compcommunicator.azurefd.net_" should be in App service's Configuration -> AzureAd:ApplicationIdURI.
2. Verify the same inside Author's manifest -> webApplicationInfo -> resource.
2. If at any place its not like that please update it.

Let us know if issue still persists.
Thanks

**Comment by Max-Enrico** [comment]
Hello @hunaidhanfee20 ,

i have an issue at updating "Expose an API". Here i got the error message "Failed to update application property. Error detail: Another object with the same value for property identifierUris already exists. [looks like a secret]". The value like secret in brackets seems like changing every time. I've tested the updating also by powershell Az module with the same error message :(

I've checked the other App registrations but i can't find "api://compcommunicator.azurefd.net" there.

Tested updating Expose an API with a similar name which works.
Mhmm, checked also "deleted applications" but nothing is there.

a) do you see an option to find out that already existing URI? It seems to be an Azure bug.
b)is there an option to rename all to a new api? what i have to do for that? 

thanks,
Enrico

**Comment by hunaidhanfee20** [comment]
Hello @Max-Enrico,
Thanks for the reply. It seems like we are missing something here. Can you please share screenshot where you are trying to change _"Expose an API"_  maybe by hiding your private information.

You can also search Authors app registration using Authors app Id. 
![image](https://user-images.githubusercontent.com/64194049/120517111-b4a04580-c3ed-11eb-9372-86c7db156dfb.png)

Are you able to see configuration of _App service_ so that you can check App Id of Author and User  app registration.

If nothing works for you. You can also try deployment by the [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

Thanks

**Comment by Max-Enrico** [comment]
Hello @hunaidhanfee20,

yes, i found the Authors app registration in tab "All applications".
As first i had a long id as api. Even time i want to change it to the right URI, i got an error. So i tested it with a similar name, which worked. (append "cc" on the target-uri, no pls do not wonder).
![image](https://user-images.githubusercontent.com/83983695/120848993-ca407700-c575-11eb-83b0-a93d8accde61.png)

When i want to change it to the right uri
![image](https://user-images.githubusercontent.com/83983695/120849052-dcbab080-c575-11eb-9f18-4756378467a6.png)
i got an this error message
![image](https://user-images.githubusercontent.com/83983695/120849136-f65bf800-c575-11eb-8b8a-ea61643da82a.png)
The value within the bracket is changing every time.
I've double checked all other application registrations, the target uri api://compcommunicator.azurefd.net
 is not set there. Deleted applications (Preview) is cleaned up already.

Within app service the setting is set correctly.
![image](https://user-images.githubusercontent.com/83983695/120849870-f7d9f000-c576-11eb-822c-aaee9ed25ef5.png)

Any idea's what can i check?

thank you,
Enrico

**Comment by hunaidhanfee20** [comment]
@Max-Enrico Its really weird that it not allowing you to put that Uri. As you said earlier that you have already checked all URI and didn't find match. I am stuck at this point too. I have never face this issue before where portal say it exist but it isn't in any registation.

Just want to give one more try: Try searching in Enterprise applications
![image](https://user-images.githubusercontent.com/64194049/121048664-9f079300-c7d4-11eb-84bd-3b4cddf84ad8.png)

Look for some app registration which might be used for CC earlier. 
Other than this I think best possible way is to re-deploy using [Deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

Thanks

**Comment by Max-Enrico** [comment]
Hello @hunaidhanfee20,

thank you, yes it is very curious. I've checked the enterprise applications but can't find an old entry. Cleaned up them before reinstallation.

Yes, i tried the reinstallation by cleaning up and installing the app according the deployment guide by using other names.
Here i run into the issue "Bot is not valid. Errors: The bot name is already registered to another bot application. Errors: The bot name is already registered to another bot application.".

For that i've checked the bot services again, but the one and only remaining bot app is for the icebreker app.
Do you have an idea, what can i check here?

thank you in advance,
Enrico

**Comment by hunaidhanfee20** [comment]
Hello @Max-Enrico,
Sorry for being so late have you tried with different name?

Thanks.

**Comment by Max-Enrico** [comment]
Hi @hunaidhanfee20,

yes i tried it with different names. Unfortunately, every time i got this error.

**Comment by Max-Enrico** [comment]
Solved it by a new installation of the app and https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/448 .

Thank you
