### ISSUE TITLE
Unable to download report

### ISSUE THREAD

**Issue by Abhisheik-athi** [OfficeDev/microsoft-teams-apps-company-communicator#398]
![image](https://user-images.githubusercontent.com/75985662/118657261-f2577880-b808-11eb-86ca-c6d91340ec15.png)
Team, need assistance on the above issue. Getting error when clicking on 'Allow' when trying to download the report.

**Comment by hunaidhanfee20** [comment]
Hello @Abhisheik-athi,
Can you please check author's manifest -> supportedFiles is set to true. 
We were not able to repro this issue. Let us know if issue still persists for you.

**Comment by shridharp-ms** [comment]
@Abhisheik-athi Is the issue resolved?

**Comment by Abhisheik-athi** [comment]
> Hello @Abhisheik-athi,
> Can you please check author's manifest -> supportedFiles is set to true.
> We were not able to repro this issue. Let us know if issue still persists for you.

@shridharp-ms @hunaidhanfee20 
Fyi I was able to export once before noticing the issue ... and yes I am still having this issue

**Comment by shridharp-ms** [comment]
@priyank29 Need your inputs here. Thx

**Comment by dceraso1985** [comment]
Hi, i have a one error for export details.

![image](https://user-images.githubusercontent.com/49043078/121430083-085ee180-c94e-11eb-94cb-6b2c94c6c6c6.png)

**Comment by priyank29** [comment]
@Abhisheik-athi @dceraso1985 Can you please share the logs from application insights ? Which version of the app you are running ?

**Comment by Abhisheik-athi** [comment]
![aa1](https://user-images.githubusercontent.com/75985662/124221059-93ca2d80-db1c-11eb-9005-4d136d73ee61.png)

@priyank29  This is the error that i get in the App Insights . i am using v3.x.

**Comment by priyank29** [comment]
@Abhisheik-athi  I will suggest to update the app to the latest version, as there was some issue with export in v3 version and was fixed in v4.0 or greater. Thanks

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
