### ISSUE TITLE
error running .\deploy.ps1 - powershell deployment 

### ISSUE THREAD

**Issue by thiagobeier** [OfficeDev/microsoft-teams-apps-company-communicator#400]
we have an azure subscription running on a different tenant that's not the same as where o365 

Starting deployment...
Login with with your Azure subscription account. Launching Azure sign-in window...
WARNING: Unable to acquire token for tenant 'dc411c63-1f52-4491-bb51-c4d215a1de23'

WARNING: The default web browser has been opened at https://login.microsoftonline.com/06cf07c8-a863-46bb-afa9-6878b267a932/oauth2/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.

hitting the url we get 

Request Id: 55cdf2eb-1beb-4bed-8c79-e03d1cc71b00
Correlation Id: 98b31408-0a53-4c02-99e4-c7c99b1d24af
Timestamp: 2021-05-19T05:00:20Z
Message: AADSTS900144: The request body must contain the following parameter: 'client_id'.

**Comment by hunaidhanfee20** [comment]
Hello @thiagobeier,
We are not able to repro this issue. Can you please confirm few things:

1. There are two sign-in screen one for Azure Subscription and other Azure Active Directory. Which of the sign-in screen you are facing this issue?
2. Is it opening any browser for sign-in?
3. The account you are using for sign-in should have **contributor role** or higher and should belongs to subscription tenant.
4.  Please check subscription Id, subscription tenant Id is correct.

You cannot sign-in with that URL if you copy and paste manually.

If you are unable to do deployment using PowerShell, I prefer you to follow portal [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).

Please let us know if you are still facing this issues.
Thanks
