### ISSUE TITLE
deploy to azure

### ISSUE THREAD

**Issue by thiagobeier** [OfficeDev/microsoft-teams-apps-company-communicator#401]
we have an azure subscription running on a different tenant that's not the same as where o365 

following the https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide
we go through browser authentication into the correct azure subscription (deploy to azure)
the deploy starts and then we get the following error after a few minutes
1. failed with time out, will re-run later
2. it's running now ... 12 minutes 7 seconds
[https://bn1301files.storage.live.com/y4p8Zj03QS20fItOi9-rvvTkNkvYCOoiiEIgB6jJMZb-GsTHXrO4YVZQMmUStUFWbIL-krXZRifvVVAa5CvfQIEigwbx8u2vb1wYDEYrejfKOzbaJiOPt7qCiByC2kEnF7AZg9NlZoIWQUNsfHn-7QOidgX7g9wPbg0eOyIM1fMmsDpXBfB40e6t5P-OSkM6Hv9/2021-05-19_1-01-07.png?psid=1&width=1271&height=620](url)

**Comment by thiagobeier** [comment]
the deployment took hours and we got ERROR

commv3/web
Microsoft.Web/sites/sourcecontrols
Conflict
Operation details

{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}

**Comment by hunaidhanfee20** [comment]
Hello @thiagobeier,
If all the resources are created successfully then you can go into your _App service_ . On the left hand side menu select _Deployment center_.
![image](https://user-images.githubusercontent.com/64194049/118935861-96583580-b969-11eb-924b-027e353ae43e.png)
Once you have selected that you can check the logs and sync the app service.
![image](https://user-images.githubusercontent.com/64194049/118937835-935e4480-b96b-11eb-96d3-50e9498f5891.png)
 
I suggest you to first sync the app service and if that doesn't work then please post the logs here.
Thanks

**Comment by Mikhail2k15** [comment]
Try to use my way. #355

**Comment by shridharp-ms** [comment]
@thiagobeier Are you still facing the issue?
