### ISSUE TITLE
Impossible to create new message for Editor for authorized editor

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-company-communicator#402]
Hi, we have installed app two days ago (40k active users) and one of authorized editor sent first message.

Today we noticed that 4 authorized editor cannot create message anymore, they see just a grey page under Company Communicator Author tab and message has been opened by just 7k users (but I think that has been stopped). 

Any ideas about cause? I'm considering that this could be generated by Azure plan but I'm not sure.

Regards

**Comment by SubbaReddi** [comment]
@faalive: Check console logs in browser to see the error. Please make sure your azure resources are up and running.
