### ISSUE TITLE
Error in c

### ISSUE THREAD

**Issue by Ochuwa-sophie** [OfficeDev/microsoft-teams-apps-company-communicator#403]
Good day,
I have company communicator on azure and it only runs fine when I use the v3.x branch for deployment.
I attempted to change it from v3.x to v4.x because when I use master, it gives an error saying "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.". But when I go into the app service deployment centre to change the branch it points to, the changes are not reflected.
after changing the branch and clicking on sync, is there something else I'm supposed to do?
I tried redeploying but the redeployment failed with this error
    "code": "BadRequest",
    "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",
    "details": [
        {
            "message": "There was a conflict. Conflict with existing ScmType: ExternalGit"
        },
        {

**Comment by hunaidhanfee20** [comment]
Hello @Ochuwa-sophie,
We are not able repro this issue at our end. I want to confirm that have you followed [v3 Migration Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v4-migration-guide)?

Please let us know more details.
Thanks
