### ISSUE TITLE
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by golubenkoff** [OfficeDev/microsoft-teams-apps-company-communicator#404]
Hi, - when trying to add author app  to teams - we getting error:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

checked everything, doing sync in deployment center and checked parameters, id's, urls, permissions.
Checked urls ( from AppService ) - the same error there when opening url from without front-door.

How can we fix this ?

**Comment by golubenkoff** [comment]
Also found Log on App Service Plan:
Log Details

Commit ID: temp-c651b694

Time
Activity
Log
3:32:07 PM
Fetching changes.
3:36:19 PM
An unknown error has occurred. Check the diagnostic log for details.


No additional details. Tried Full Stop of AppService & Sync \ redeploy commit - and success. Now all is or - just for everyone if you have the same issue.

**Comment by Ochuwa-sophie** [comment]
Hi, how did you fix this?

**Comment by golubenkoff** [comment]
Select AppServices and stop all of them. Next in DeploymentCenter push Sync and wait when completed- it will take long time to finish. Then start apps and all is ok

**Comment by vms87** [comment]
> Select AppServices and stop all of them. Next in DeploymentCenter push Sync and wait when completed- it will take long time to finish. Then start apps and all is ok

When I click on Sync the process ends very fast and still does not work

**Comment by adejeg** [comment]
I deployed an Angular App using Github Actions, and I get this error **The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.** whenever I refresh the page. I have a web.config file in my root folder but that is not working.

This error started when I started deploying using Github Actions.

Can you help me understand and fix the error?

**Comment by siddarthmarri-png** [comment]
Puget Sound Lowlands This region includes famous landmarks such as the Space Needle, Pike Place Market, and the Fremont Troll.
Isaac Stevens  He was the first governor of Washington Territory and played a major role in negotiating treaties with Native American tribes.
Okanogan Highlands  This region includes Omak, Colville, and the Ruby Ghost Town, showing both modern communities and historic mining areas.
Located in southeastern Washington, this site was used during World War II to produce and p
During World War II, Seattle shipyards built these cargo ships at an incredible rate, with one Liberty Ship completed about every four days to support the war effort.
