### ISSUE TITLE
Company Communicator app missing from App Services

### ISSUE THREAD

**Issue by monovex** [OfficeDev/microsoft-teams-apps-company-communicator#405]
The app is deployed and working, but missing from App Services.  I am attempting to access App Services so that I may update the SenderUpn field.  Any thoughts on why I would not be able to see this in App Services?

**Comment by hunaidhanfee20** [comment]
Hello @monovex,
First thing I would like to confirm if you had done deployment and installed bot in two different tenant then please make sure that you are looking in the right tenant, the one where you done the deployment you need to look in that. You may have already but you can also try to search in Azure portal using base resource name. 

You can also check in resource group which you have selected during deployment. Here are the steps for where to check.
1. Go to Resource groups -> Open your resource group. or directly search it by name.
2. Look for _Deployments_ in the right menu -> Click on it.
![image](https://user-images.githubusercontent.com/64194049/118931926-1af48500-b965-11eb-86f5-775851018a15.png)
3. Search for your deployment, select it and expand the Deployment details.
![image](https://user-images.githubusercontent.com/64194049/118930733-be449a80-b963-11eb-92d0-2330baa6f2ba.png)
4. You should find your app service there too.

Please reopen and let us know if you still facing this.
