### ISSUE TITLE
Can AuthorizedCreatorUpns receive a security group?

### ISSUE THREAD

**Issue by JorgeALeitao** [OfficeDev/microsoft-teams-apps-company-communicator#406]
As security groups are also security principals could one be used to manage access to Authors?

I was browsing the code but could not find the point where the current user's UPN is checked against the list.

**Comment by aosolis** [comment]
No, the current implementation is a direct check of the UPN in the incoming token (after it's been validated) against the list of authorized UPNs: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/de2520965d5cff88eb382f5254ac69a793e9386e/Source/CompanyCommunicator/Authentication/MustBeValidUpnHandler.cs#L72
