### ISSUE TITLE
Documentation enhancement suggestions

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-apps-company-communicator#407]
Some general comments on the documentation:
Number all steps in the model of **1.1.2** 
 
Missing information on the "Proactive install" - version 4 (The user app must be uploaded to the app store. The authors app can be side-loaded.) 

Add to the top of guide - which version will this guide install (base version or latest)?
 
Specific comments:
2.5 > the name contosocommunicator must be available (not taken); How do we check if the name is available or not? Most beginners will use the name "contosocommunicator" as that is the default in this documentation.
 
2.6.6 > Proactively Install User App [Optional]: Default value is true. You may set it to false if you want to disable the feature. This feature must be documented somewhere - what is it doing? How does it work?
 
2.12 >Why are we renaming these values? keep the same name through out the app and the documentation.
authorBotId is called AuthorAppId userBotId is called UserAppId appDomain is found as part of AzureAD:ApplicationIdURI
 
3.2 > Go to App Registrations page here and open the author app you created (in Step 1) from the application list. 
Suggestion to change to: Go to App Registrations page here and open the author app you created (in Step 1.1-3) from the application list.
 
3.3 > Under Manage, click on Authentication to bring up authentication settings.
Add: 
> Click on "Add a platform", select "Web".
> Add a new entry to Redirect URIs:
 
3.3.3 > Click Save to commit your changes. Should be "Click Configure" to commit your changes.
 
3.4.7 Repeat the previous two steps
Better to write Repeat the two steps 3.4.5 and 3.4.6 but with client ID = 1fec8e78-bce4-4aaf-ab1b-5451cc387264.
Also, mention that these are two hardcoded IDs not to be changed.
 
4. > Continuing from the Azure AD app registration page where we ended Step 3. Go to App Registrations page here and open the author app you created (in Step 1.1-3) from the application list.
 
Troubleshooting:
1.2 Forgetting the botId or appDomain If you forgot to copy your authorBotId, userBotId and appDomain values from the end of the deployment. You can find them in the "Configuration" section of your Web App.
> of your Web App.
 It should say:
> of your App Service. 
 
Same comment for 2.0 (below): If you forgot to copy your authorBotId, userBotId and appDomain values from the end of the deployment. You can find them in the "Configuration" section of your Web App.

**Comment by hunaidhanfee20** [comment]
Hello @SubbaReddi,
Thank you for sharing suggestions with us. We will soon look into it.
