### ISSUE TITLE
Adding bot to team is failing

### ISSUE THREAD

**Issue by monovex** [OfficeDev/microsoft-teams-apps-company-communicator#408]
I side-loaded the app into our Teams app store.  When I go to add it to a team it states that "the resource you are looking for has been removed, had its name changed, or is temporarily unavailable".  I've reviewed my deployment and it all appears to be good.  I can browse to the app domain URL and it gives me the default app page, but when I add /configtab or /simple-sign-end it states the same thing, "resource not found...".  I double-checked the app IDs and everything appears to match with the manifest.  Any suggestions?

**Comment by hunaidhanfee20** [comment]
Hello @monovex,
Can you try uninstalling bot from App store and re-install it. 

Please share the screenshot where you are having this issue. 
Thanks.
