### ISSUE TITLE
Company Communicator

### ISSUE THREAD

**Issue by carlosatsantos** [OfficeDev/microsoft-teams-apps-company-communicator#412]
Hi,

When I write the message the image appears.

But when sending it doesn't show the image.

![cc_image](https://user-images.githubusercontent.com/85307218/120682471-65f9b680-c494-11eb-93e8-babddd344bdd.png)
Thanks.

CS

**Comment by shridharp-ms** [comment]
@carlosatsantos Could you share screenshots from both author app & user application? Is the Image URL you are using in composition a public URL or a private URL?

**Comment by carlosatsantos** [comment]
Hi,
In the author app everything works well.
In the user app the image showa like I send in the in attach file.
A private URL.

Thanks.

Carlos Santos

**Comment by shridharp-ms** [comment]
@carlosatsantos Adaptive cards expect public URL. Could you try with a public URL image & let me know if the issue persists? Thx

**Comment by carlosatsantos** [comment]
Ok.
Thanks.
CS

**Comment by carlosatsantos** [comment]
Hi again

It is possible to store the images in sharepoint online picture library?
I tried, it shows the picture in browser but not in teams.

Thanks.

CS

**Comment by shridharp-ms** [comment]
Hi @carlosatsantos I believe that will be an authenticated end point. Hence, it will not be supported by adaptive cards.
