### ISSUE TITLE
Posting to non-General channel

### ISSUE THREAD

**Issue by monovex** [OfficeDev/microsoft-teams-apps-company-communicator#413]
Are there any plans to update the app or is it possible for us to customize the app to allow posting to non-General channels?

**Comment by shridharp-ms** [comment]
@priyank29 Is it supported, if the end user application is installed in non-general channel?

**Comment by aosolis** [comment]
@shridharp-ms No, this is not supported by the app. Note that in general, apps are installed to teams, not to individual channels (setting aside private channels.)

**Comment by aosolis** [comment]
@monovex At this point, we don't have plans to add the ability to post to a channel other than General. You can add this functionality, which will require a UX change to add a way to pick the channel, and save that to the data store. Then the send function will need changes to recognize this new option and support sending the message to a channel.

The mechanics of sending a message to a specific channel ID is the same as when sending it to the General channel, except that the conversation (channel) ID is different. So the bulk of the work will likely be in the author app.
