### ISSUE TITLE
Duplicate posts were made in General

### ISSUE THREAD

**Issue by monovex** [OfficeDev/microsoft-teams-apps-company-communicator#414]
I setup the CC app and had a user post a message.  When the message was sent to the General channel, it was posted 3 times. The first two had the name of our Authors app whereas the last one had the name of the user app.

![image](https://user-images.githubusercontent.com/84472071/120705185-7eaea000-c485-11eb-9bef-71260b90b7db.png)

![image](https://user-images.githubusercontent.com/84472071/120705022-4909b700-c485-11eb-90ab-f9ab2bee92a4.png)

**Comment by hunaidhanfee20** [comment]
Hello @monovex,
Is it happening for every message being sent?

There might be some issue at runtime at that time. Can you please confirm?
Thanks
