### ISSUE TITLE
Authoring of messages does not support dark theme in teams

### ISSUE THREAD

**Issue by snailCorpse** [OfficeDev/microsoft-teams-apps-company-communicator#416]
The page for authoring of messages does not support the Dark theme in Teams. 
![image](https://user-images.githubusercontent.com/25774180/120893807-6a011200-c615-11eb-9ce4-bb7432ec0c7e.png)
![image](https://user-images.githubusercontent.com/25774180/120893826-813fff80-c615-11eb-9615-0a27159832f9.png)

**Comment by shridharp-ms** [comment]
@priyank29 this is supported now right?

@snailCorpse Which is the version you have deployed?

**Comment by snailCorpse** [comment]
Version 4.1

**Comment by aosolis** [comment]
Thanks for the bug report. This is now fixed in v4.1.1.
