### ISSUE TITLE
Sorry, an error occurred while trying to access this service.

### ISSUE THREAD

**Issue by Miclarsen1** [OfficeDev/microsoft-teams-apps-company-communicator#418]
Hi 

After adding the author app to Teams I am getting this error when I access the company communicator tab:

Sorry, an error occurred while trying to access this service.

I was able to add the app with no issues at all, but quite simply cannot figure out why it is not working. 
I went through the whole configuration two times, but it seems to be in order according to the deployment guide.

Let me know if you need more info

UPDATE

I looked into application insights for the app and it seems there is and issue with some failed dependencies:

**Type | Azure table |
Result code | 409 | 
Call status | false | 
Duration | 566 ms | 
Remote dependency name | POST ruyljbyaow5m2/Tables | 
Id | cdce30dc7054d047 | 
Base name | ruyljbyaow5m2.table.core.windows.net | 
Performance | 500ms-1sec | 
Telemetry type | dependency**

There is also a command related to this:

**https://ruyljbyaow5m2.table.core.windows.net:443/Tables()**

**Finally I am also seeing a response code 401 in relation to GET /api/sentnotifications and GET /api/draftnotifications**

I have no idea what any of this means, so I am hoping some in here can point me in the right direction.

Regards,
Michael

**Comment by snailCorpse** [comment]
Hi

I had the same problem. I found the following worked:

In the application configuration, make sure all the urls are pointing to the uri for the service and not the frontdoor url.

I noticed that when the bit is deployed by the arm template it uses the azurefd.net address

**Comment by Miclarsen1** [comment]
Hi 

But it should be possible to use the azurefd.net address right?
Or I am just not sure what the url for the service would like then.

Are you able to give me an example?

**Comment by SubbaReddi** [comment]
@Miclarsen1 : It must be working with azurefd.net URL.
Please double check Author app registration [authentication configuration](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) and make sure correct values entered in ARM template deployment:
![image](https://user-images.githubusercontent.com/69682598/121907369-9de0e380-cd49-11eb-83b7-512b76f782d8.png)

**Comment by Miclarsen1** [comment]
Hey @SubbaReddi,

Ok thanks for the hint.
The Issue was the Application settings in Azure. For some reason the AllowedTenants and AzureAd:TenantId were both wrong, but after correcting that it all worked as intended. 

Thank you again for the assist, you are a gentleman and a scholar :-)

Best regards,
Michael
