### ISSUE TITLE
Deploying new features

### ISSUE THREAD

**Issue by asensionacher** [OfficeDev/microsoft-teams-apps-company-communicator#419]
I'm trying to develop new features, however, when I deploy to my WebApp the new code with a minor change (changing an string for testing), the change not appears to be applied on the Teams App.

How I have to replace the old code with the new one on my WebApp?

**Comment by SubbaReddi** [comment]
@asensionacher: Once you deploy the changes, Can you clear cache and retry to open teams app and check.
