### ISSUE TITLE
Error when Preview Channel

### ISSUE THREAD

**Issue by theogumilang** [OfficeDev/microsoft-teams-apps-company-communicator#425]
Hi, I have this error when trying to use the preview channel.  I already install both the user and author app to the channel. But I kept getting this error
Code = "BotNotInConversationRoster",
Message = "The bot is not part of the conversation roster."
Any suggestion on what do I miss in here. I already tried to install it on different channels but it has the same results.

**Comment by sagarm09** [comment]
@theogumilang please check teams channel is private or public if its private then use public channel to add authors app it will work.
