### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by erikasarmi** [OfficeDev/microsoft-teams-apps-company-communicator#426]
How can I upgrade from v4.0 to v4.1?

**Comment by priyank29** [comment]
You can upgrade by syncing code through Deployment Center in Azure app service and the same for azure functions.

**Comment by erikasarmi** [comment]
Tried that and getting the following error for the Azure functions, saying that the file doesn't exist:

Command: deploy.cmd
Handling function App deployment with Msbuild.
Using Msbuild from 'D:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin'.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Test\CompanyCommunicator.Test\obj\project.assets.json
Restored D:\home\site\repository\Source\Test\CompanyCommunicator.Test\Microsoft.Teams.Apps.CompanyCommunicator.Test.csproj (in 17.73 sec).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Test\CompanyCommunicator.Send.Func.Test\obj\project.assets.json
Restored D:\home\site\repository\Source\Test\CompanyCommunicator.Send.Func.Test\Microsoft.Teams.Apps.CompanyCommunicator.Send.Func.Test.csproj (in 2.49 sec).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Test\CompanyCommunicator.Prep.Func.Test\obj\project.assets.json
Restored D:\home\site\repository\Source\Test\CompanyCommunicator.Prep.Func.Test\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.Test.csproj (in 379 ms).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\Test\CompanyCommunicator.Common.Test\obj\project.assets.json
Restored D:\home\site\repository\Source\Test\CompanyCommunicator.Common.Test\Microsoft.Teams.App.CompanyCommunicator.Common.Test.csproj (in 183 ms).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\CompanyCommunicator\obj\project.assets.json
Restored D:\home\site\repository\Source\CompanyCommunicator\Microsoft.Teams.Apps.CompanyCommunicator.csproj (in 756 ms).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\CompanyCommunicator.Send.Func\obj\project.assets.json
Restored D:\home\site\repository\Source\CompanyCommunicator.Send.Func\Microsoft.Teams.Apps.CompanyCommunicator.Send.Func.csproj (in 430 ms).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\CompanyCommunicator.Prep.Func\obj\project.assets.json
Restored D:\home\site\repository\Source\CompanyCommunicator.Prep.Func\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj (in 258 ms).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\CompanyCommunicator.Data.Func\obj\project.assets.json
Restored D:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj (in 204 ms).
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\home\site\repository\Source\CompanyCommunicator.Common\obj\project.assets.json
Restored D:\home\site\repository\Source\CompanyCommunicator.Common\Microsoft.Teams.Apps.CompanyCommunicator.Common.csproj (in 229 ms).

NuGet Config files used:
D:\home\site\repository\Source\NuGet.Config
C:\DWASFiles\Sites\#1BancoBiceCCCL-data-function\AppData\NuGet\NuGet.Config

Feeds used:
https://api.nuget.org/v3/index.json
All projects are up-to-date for restore.
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: D:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin\MSBuild.exe" "D:\home\site\repository\Source\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj" /p:DeployOnBuild=true /p:configuration=Release /p:publishurl="D:\local\Temp\8d92f50fc545c7e"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\94.30524.5227\bin\Scripts\starter.cmd deploy.cmd



I checked and between v4.0 and v4.1 some file paths changed (example: from "Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func\\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj"" to "CompanyCommunicator.Prep.Func\\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj")
Could this be the problem? If so, what else do I need to do?

**Comment by ATshirai** [comment]
Can I upgrade from v4.1 to v4.1.1 by that?

**Comment by shridharp-ms** [comment]
@ATshirai Yes, the same
