### ISSUE TITLE
Customizing Company Communicator Issue 

### ISSUE THREAD

**Issue by gleason7** [OfficeDev/microsoft-teams-apps-company-communicator#428]
Hi Team,

Please need your urgent help. I'm trying to customize company communicator as per our requirement.
I'm trying to add some new packages in the clientapp & its working fine in localhost. But when I try to redeploy 
from azure app service through Deployment Center its getting failed. Attaching failed logs & screenshot along with this ticket.

[Deploy_Issue.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/6663094/Deploy_Issue.txt)
 ![image](https://user-images.githubusercontent.com/69605707/122220163-b2e67f80-cecd-11eb-828b-8e1f6ef5a8e4.png)

**Comment by hunaidhanfee20** [comment]
Hello @gleason7,
Can you share your package.json? 

Thanks

**Comment by gleason7** [comment]
Hi @hunaidhanfee20 ,
PFA for the package.json & package-lock.json file.
[package.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/6668303/package.zip)

Thanks

**Comment by hunaidhanfee20** [comment]
Hello @gleason7,
Seems like you are using "_immutable_" package somewhere but I can't find it in package.json. Can you please try adding it like this:
![image](https://user-images.githubusercontent.com/64194049/122372589-6b6bfc00-cf7e-11eb-89fa-24198c8a5c41.png)
Once added push to branch and sync.

PFA updated package.json.
[pkg.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/6669153/pkg.zip)


If this also doesn't work try to delete package-lock.json and then try.

Let me know if this helps.
Thanks

**Comment by Mikhail2k15** [comment]
@gleason7 kudu service is very unstable to deploy projects with many npm packages. Use GitHub Actions instead. You can find an idea in my PR #355
