### ISSUE TITLE
When  the Teams global app setup policy is used to install Company Communicator to all users

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#433]
H, Team.
Do you mean that  the V4.1.1 doesn't send a message to guest users  when ​the Teams global app setup policy is used to install Company Communicator to all users ?

**Comment by Mikhail2k15** [comment]
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Excluding-guest-users-from-messages
