### ISSUE TITLE
2 installations of Company Communicator: communications sent under the 2ns Company Communicator installation do not leave the queue, are not sent

### ISSUE THREAD

**Issue by rgs170170hotmail** [OfficeDev/microsoft-teams-apps-company-communicator#437]
for a concrete customer it has been requested a 2 installations of the Company Communicator App. The first one works as expected, second installation (where we had to do some changes on IDs), when messages are sent, these are kept on the queue, never get them sent

**Comment by rgs170170hotmail** [comment]
is there any guidance about how to install 2 instances of the CC app?

**Comment by SubbaReddi** [comment]
@rgs170170hotmail 
Follow below steps to deploy second instance of company communicator in single tenant:
Register Azure AD Applications as mentioned in [Step 1](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#1-register-azure-ad-application)
While doing ARM Template deployment which is given in [Step 2](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#2-deploy-to-your-azure-subscription), update “User App External Id” with following value: 148a66bb-e83d-425a-927d-09f4299a927**5**
Proceeding with remaining steps [3](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication), [4](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-app)
In [Step 5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages), Please update user app [manifest id](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/master/Manifest/manifest_users.json#L5) from 148a66bb-e83d-425a-927d-09f4299a927**4** to 148a66bb-e83d-425a-927d-09f4299a927**5** and please update author app manifest id from 1c07cd26-a088-4db8-8928-ace382fa219**f** to 1c07cd26-a088-4db8-8928-ace382fa219**d**
performance remaining steps as mentioned in deployment guide.

If you miss to update “User App External Id” in step 2, you can update value in following sections:
•	Open second instance azure resource group -> Open App service -> Configuration (in left navigation) -> update “UserAppExternalId” value to 148a66bb-e83d-425a-927d-09f4299a927**5** -> Click on “ok” -> Click on “save” and restart app service.

•	Open second instance azure resource group -> Open function app which is ending with “-prep-function”-> Configuration (in left navigation) -> update “UserAppExternalId” value to 148a66bb-e83d-425a-927d-09f4299a927**5** -> Click on “ok” -> Click on “save” and restart function app.
And make sure user manifest id change as mentioned above.

**Comment by renearreaza** [comment]
Followed suggestions from SubbaReddi and still encountering the same issue. Any guidance?

**Comment by SubbaReddi** [comment]
@renearreaza : Then please check app insight logs to understand the failure reason.
