### ISSUE TITLE
Unable to Sign in to Author App

### ISSUE THREAD

**Issue by cueball59** [OfficeDev/microsoft-teams-apps-company-communicator#440]
After installing the Author App into a Team I am unable to sign-in. App acts like its loading then shows a Sign In button. Clicking the button opens up a separate window to complete the sign-in process but then just pops back to the sign in button. I checked to make sure my UPN was in the SenderUPNList and can confirm thats correct. I can see my sign-ins to the app in Azure AD were successful. 
![image](https://user-images.githubusercontent.com/47506540/122941911-ce291300-d343-11eb-9128-580260da7b51.png)
![image](https://user-images.githubusercontent.com/47506540/122942158-fca6ee00-d343-11eb-9ad8-fe44f5df6ec3.png)

**Comment by shridharp-ms** [comment]
@cueball59 Hi, do you have an alias? this might be different from your email address, can you try adding that in the UPN list & try accessing the author application?
