### ISSUE TITLE
Not able to see the Draft notification after adding the new message in the App getting 500 error in the app insights for getAllDraftNotificationAsync

### ISSUE THREAD

**Issue by BharathiSeelam** [OfficeDev/microsoft-teams-apps-company-communicator#442]
Not able to see the Draft notification after adding the new message in the App getting 500 error in the app insights for getAllDraftNotificationAsync
getting the error message
t Microsoft.Teams.Apps.CompanyCommunicator.Controllers.DraftNotificationsController+<GetAllDraftNotificationsAsync>d__17.MoveNext (Microsoft.Teams.Apps.CompanyCommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Teams.Apps.CompanyCommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\Jomy\Projects\Latest\Comcast_0622GitLatest\Microsoft.Teams.Apps.CompanyCommunicator\Controllers\DraftNotificationsController.csMicrosoft.Teams.Apps.CompanyCommunicator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 253)

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
