### ISSUE TITLE
Company Communicator Author

### ISSUE THREAD

**Issue by 0Emma0** [OfficeDev/microsoft-teams-apps-company-communicator#444]
When We try to add the **Company Communicator Author** to a specific team in Microsoft Teams, We receive the following message **"An error has occurred"**.

We have the **Company Communicator Author** running on another Team. But we can't add it in a new team.

We try a sync, but we get the same error.

Can you help me please.

Thank you!

**Comment by 0Emma0** [comment]
When we go to Azure > Resource Groups, Web App Bot > Channels, we have Warnings for Microsoft Teams, with the following message: **Failed to decrypt conversation id**

**Comment by SubbaReddi** [comment]
To resolve "Failed to decrypt conversation id", follow below step:
Navigate to Azure resource group cc app -> Open storage account -> Click on Storage explorer(preview)->Delete "UserData" table and recreate the table.
When you send the message next time user data will be reloaded.

Once it resolved, check whether author app adding works.
