### ISSUE TITLE
At first installation of Company Communicator i got the error: Bot is not valid. Errors: The bot name is already registered to another bot application

### ISSUE THREAD

**Issue by Max-Enrico** [OfficeDev/microsoft-teams-apps-company-communicator#448]
ERROR: Deployment failed. Correlation ID: a6c14cd2-e2ad-4e4e-aca2-2ed673b5e378. {
  "error": {
    "code": "InvalidBotData",
    "message": "Bot is not valid. Errors: The bot name is already registered to another bot application..  See https://docs.microsoft.com/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0 for detailed requirements."

Initial started with the manual installation, which failed with that error. 
A second try by installing it with the powershell script i run into the same error.

Any suggestions?

thanks!

**Comment by priyank29** [comment]
@Max-Enrico Did you change the App Name in the second try ? If not, can you please try doing that ?

**Comment by Max-Enrico** [comment]
Hi @priyank29 , 

i solved it by using a different baseResourceName.
It was not clear to to that this name must be unique globally, not only tenant wide.
Now it works. 

Perhaps you can update the section for the baseResourcename, that i become more clear, that the entry must be unique globally.

thanks in advance!
