### ISSUE TITLE
Messages are getting failed in large numbers that are 'unknown'

### ISSUE THREAD

**Issue by Abhisheik-athi** [OfficeDev/microsoft-teams-apps-company-communicator#451]
Hi Team ,

We have been facing issue in sending to a large number of users (>400k). The messages are getting failed to send and also many are showing unknown in the Author app. PFB details
The send queue is getting filled even though the message is triggered only for around 500k users in total at a time.

We have deployed v3.x in our tenant. 

  ![MicrosoftTeams-image](https://user-images.githubusercontent.com/75985662/124221567-a8f38c00-db1d-11eb-8285-979e388323d1.png)
  
  ![image](https://user-images.githubusercontent.com/75985662/124221441-6c279500-db1d-11eb-8431-69b67e704971.png)
  
  ![image](https://user-images.githubusercontent.com/75985662/124221708-e9eba080-db1d-11eb-8ac7-53180ff60eb0.png)
  
  ![image](https://user-images.githubusercontent.com/75985662/124221721-ee17be00-db1d-11eb-9790-aa8618d88770.png)
  
  ![image](https://user-images.githubusercontent.com/75985662/124221729-f243db80-db1d-11eb-8ee6-9c2eda93e540.png)
  
  ![image](https://user-images.githubusercontent.com/75985662/124221746-f8d25300-db1d-11eb-9541-5c24b6b64227.png)
  
  ![image](https://user-images.githubusercontent.com/75985662/124221765-01c32480-db1e-11eb-91f7-f3b5b8d55f15.png)
  

Thanks !!

**Comment by priyank29** [comment]
@Abhisheik-athi What is the App Service plan of the instance ?

**Comment by Abhisheik-athi** [comment]
@priyank29  - S1

**Comment by priyank29** [comment]
@Abhisheik-athi Thanks! Can you also share the exception details here with the ClientRequestId ?

**Comment by Abhisheik-athi** [comment]
@priyank29  - Could you please mention the where & how to get that information ?

**Comment by Abhisheik-athi** [comment]
> @Abhisheik-athi Thanks! Can you also share the exception details here with the ClientRequestId ?

@priyank29  -  Could you please mention the where & how to get that information ?

**Comment by Porkai-Pandian** [comment]
Hi @Abhisheik-athi,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
