### ISSUE TITLE
Detailed User Stats

### ISSUE THREAD

**Issue by defrian** [OfficeDev/microsoft-teams-apps-company-communicator#452]
Dear all,

I was hoping that I would not only get stats about successful delivery but also about how many users have read the message and how many of them have clicked the button. Is this information already stored somewhere or do I have to implement it myselt?

Best
Defrian

**Comment by defrian** [comment]
Alright, by searching in the closed issue I now understand that I have to implement this functionality myself. Problem is, I have no idea how to do this. Can someone post me a link to a beginner tutorial on how to extend and develop app templates.

**Comment by shridharp-ms** [comment]
@defrian bots on microsoft teams today do not support read receipts of messages. The alternative way to achieve is through tracking user reactions to the messages. Here is how to do it with bot events - https://docs.microsoft.com/en-us/javascript/api/botbuilder/teamsactivityhandler?view=botbuilder-ts-latest#onReactionsAdded_BotHandler_ . You will have to log these into telemetry to start receiving them in the reports.
