### ISSUE TITLE
Unable to sign in 

### ISSUE THREAD

**Issue by ChrisStoneham** [OfficeDev/microsoft-teams-apps-company-communicator#453]
Exactly the same as the closed (but unresolved) issue #440 - I'm experiencing the same issue where the sign-in just loops and won't ever complete.

**Comment by shridharp-ms** [comment]
@ChrisStoneham Do you have an alias? Have you ensured both are whitelisted in validUPNs?

**Comment by ChrisStoneham** [comment]
When you say validUPNs I'm assuming you mean the AuthorizedCreatorUPNs application setting for the App Service?

I've added my "onmicrosoft.com" aliases, and, something has happened, it gets further, but, now I'm just greeted with spinning loading icons and it never loads:

![image](https://user-images.githubusercontent.com/33757550/124923313-36d5e800-dff2-11eb-8134-3786f7851530.png)

**Comment by ChrisStoneham** [comment]
I think I've resolved this specific issue now. Appears that the APIs weren't exposed by the deployment script.
