### ISSUE TITLE
Images don't show up in mobile apps

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-company-communicator#454]
After upgrading to 4.1.2, I've gotten reports that images don't show up in mobile apps for Company Communicator. This is after making sure that the image size, internet availability, and image format were all correct. I've now tried this in a separate tenant and with separate mobile clients and am able to reproduce it.

I'm not sure if this is related to 4.1.2, but I didn't get reports of this problem before the update.

**Comment by bungleweed** [comment]
Are you using PNG files?

**Comment by glblinck** [comment]
I've tried both PNG and JPG files. Both file formats work fine on desktop and web clients, but neither works on the mobile client.

One other thing that might come into play is that the Teams piece of this solution is being used in GCC tenants. I have a demo GCC tenant available if this would help with getting it working.

**Comment by bungleweed** [comment]
Tested mobile images with latest code release. Works fine. This is in a standard enterprise tennat, not GCC.

**Comment by glblinck** [comment]
> Tested mobile images with latest code release. Works fine. This is in a standard enterprise tennat, not GCC.

Okay, so this must be a GCC thing. Would there be any hope of getting this working in the GCC environments, too? The other functions seem to be fine.

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
