### ISSUE TITLE
Deployment failure due to network policy: Storage Account Should Restrict Network Access

### ISSUE THREAD

**Issue by kayobrasilicatu** [OfficeDev/microsoft-teams-apps-company-communicator#455]
Cannot pass trought ARM template validation step, it asks to configure network rules, so only applications from allowed networks can access the storage account.

After this, tried add "networkAcls > defaultAction > Deny" inside Storage Account properties on template.json, but the deployment of Web Apps fails due to access denied to storage account.

![error](https://user-images.githubusercontent.com/87320575/125307308-54fb5b00-e306-11eb-8673-29bec11524be.png)

<img width="300" alt="template_json_modified" src="https://user-images.githubusercontent.com/87320575/125307342-5b89d280-e306-11eb-85d1-941b5f5554e3.png">

Does anyone have a workaround to this?

**Comment by bungleweed** [comment]
Is that because you have your own policy that mandates storage account needs to be restricted to only internal networks? I suspect the ARM templates conflicts with your policy on that.

**Comment by kayobrasilicatu** [comment]
> Is that because you have your own policy that mandates storage account needs to be restricted to only internal networks? I suspect the ARM templates conflicts with your policy on that.

Thanks for the comment, @bungleweed ! Yes, it's a conflict  between Company Communicator ARM Template and an active policy on my environment. The question is, how can I proceed with instalation without disabling the policy? Is there any other way?

**Comment by bungleweed** [comment]
There's a deploy with powershell script option. That runs a deploy.ps1 script. Maybe you could amend that where it deploys the storage account to honour your policy.

**Comment by bungleweed** [comment]
![image](https://user-images.githubusercontent.com/29515438/125979304-3d972bc9-61bd-4690-8dc7-0ec90bee6355.png)
It's this bit that violates your policy. I wonder if you could get the ARM template and just amend the bit that provisioned the storage account and add the parameters to the network access down to the template. Then deploy it from that.

**Comment by bungleweed** [comment]
Or.....get a one off exception to deploy and then lock it down post install.

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by ahmedsaid313** [comment]
Team, we are facing the same issue and we need supported resolution to go for.
