### ISSUE TITLE
Commpany communicator redirect url is not working 

### ISSUE THREAD

**Issue by Vijay2704** [OfficeDev/microsoft-teams-apps-company-communicator#456]
Hi Team,

Url "https://XXXXXXX.azurefd.net/configtab"  
https://XXXXXXX.azurefd.net/signin-simple-end
after deployment iam trying to access this url but i got below error.
**"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."**

i am referring the below link for creating the company communicator
[Link]("https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide')

**Comment by bungleweed** [comment]
You might need to deploy the web app service again. Go into the web app service and click deployment centre. Click sync to deploy it from github. This is usually the cause of this error.
