### ISSUE TITLE
Update Company Communicator 4.1.0 to 4.1.3

### ISSUE THREAD

**Issue by nigelzin** [OfficeDev/microsoft-teams-apps-company-communicator#474]
Hi =), 
How to update this application from 4.1.0 to 4.1.3? I need go to : resource groups > settings > deployments and check the template and redeploy? 

Anyone can confirm ? Thx for helping.

**Comment by priyank29** [comment]
@nigelzin you need to go to: resource groups > app service > deployment center > then click on sync. This has to be repeated for all the 3 functions and make sure to restart the app after sync. Thanks!
