### ISSUE TITLE
The Author app doesn't get the teams channels,

### ISSUE THREAD

**Issue by alejandroroberto** [OfficeDev/microsoft-teams-apps-company-communicator#475]
Hello, can you help me with the next error?

The Author app doesn't get the teams channels, it doesn't get the members either

![image](https://user-images.githubusercontent.com/43283504/127031897-4ff12be0-6dde-4270-80ad-c9d593d9f2ad.png)

**Comment by priyank29** [comment]
@alejandroroberto  please check this [369](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/369).

**Comment by NiallM2016** [comment]
Have you explored the "Add-TeamsAppInstallation" PowerShell cmdlet? The Microsoft Graph API may also be helpful for this purpose for bulk adding of APP to teams
https://docs.microsoft.com/en-us/powershell/module/teams/add-teamsappinstallation?view=teams-ps
https://docs.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-1.0&tabs=http
