### ISSUE TITLE
Video that depicts non-existing features.

### ISSUE THREAD

**Issue by JorgeALeitao** [OfficeDev/microsoft-teams-apps-company-communicator#476]
This YouTube video https://www.youtube.com/watch?v=_dzu8HEu1AU published by Microsoft at 0:0:36 depicts the ability to schedule a time for messages to be send and at 0:0:49 it depicts the ability to measure success of announcement by analyzing the number of views, replies or reactions a message had.

AFAIK none of that is currently available, thus I suggest that this video should be taken down or changed to highlight that some of the features shown are possibilities that would require further development.

**Comment by iiza** [comment]
it´s a joke. Most of clients are asking about that.

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. We don't have control over these contents and also may not be able confirm if these features will be available in future releases right now, please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by JorgeALeitao** [comment]
The video was posted in Youtube under Microsoft Central and Eastern Europe channel (https://www.youtube.com/channel/UCJ-jBSURYSJG28a1FfxQxdw)

We must be able to figure out internally who is responsible for that channel and get the video removed. 
The longer it remains available the more people will be frustrated.

**Comment by SankarMicrosoft** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. We don't have control over these contents and also may not be able confirm if these features will be available in future releases right now.

Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
