### ISSUE TITLE
Company Communicator App Stuck in Save as Draft Page (Author Experience)

### ISSUE THREAD

**Issue by anshubp** [OfficeDev/microsoft-teams-apps-company-communicator#477]
CC Author App always remains stuck in attached page. Also, while looking for general channel in Teams or selecting any of the option there, it is not able to find details there. Clicking on Save as Draft don't make any changes.
![Error2](https://user-images.githubusercontent.com/88111014/127383720-16475e95-424f-4d35-8a9b-e01d9897b29d.jpg)

![Error1](https://user-images.githubusercontent.com/88111014/127383467-2354ad60-65f7-48bb-8064-4ffba307f048.jpg)

**Comment by jackdawsonnv** [comment]
I am also experiencing a similar issue except it only occurs when I click on an incoming chat notification while editing a draft message in Company Communicator. After clicking the chat notification window, I can see the Teams client switching to the Chat message but the Company Communicator (Authors) card is left open and the Save as Draft button is not functional. When this issue occurs, the only resolution to get out of the Company Communicator (Author) card is to restart the Teams desktop app.

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
