### ISSUE TITLE
"Failure Anomalies" in deployment

### ISSUE THREAD

**Issue by mark3grahams** [OfficeDev/microsoft-teams-apps-company-communicator#478]
I just set this up in a dev tenant using the Powershell script. The script had no errors, but when I look at the RG > Deployments, I see "Failure-Anomalies-Alert-Rule-Deployment" (along with "azuredeploy")

{
    "status": "Failed",
    "error": {
        "code": "MissingSubscriptionRegistration",
        "message": "The subscription is not registered to use namespace 'Microsoft.AlertsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions.",
        "details": [
            {
                "code": "MissingSubscriptionRegistration",
                "target": "Microsoft.AlertsManagement",
                "message": "The subscription is not registered to use namespace 'Microsoft.AlertsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions."
            }
        ]
    }
}

Company Communicator seems to be working as expected. Should I register Microsoft.AlertsManagement provider and redeploy? or is this something that does not matter?

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by sivanikakuru09** [comment]
What is the resolution of this as I received same error 

The subscription is not registered to use namespace 'Microsoft.AlertsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions. (Code: MissingSubscriptionRegistration)
