### ISSUE TITLE
Documentation Improvement - Teams App Permission Policies

### ISSUE THREAD

**Issue by bungleweed** [OfficeDev/microsoft-teams-apps-company-communicator#479]
Hi,

I've had a number of customers following the deployment guide but getting stuck with the proactive installation of the end user app due to their App Permissions Policies in Teams blocked usage of custom apps. When they then try and send a message out the proactive install fails as the graphi api request to install the app for the end user fails with a 403 exception, which can be seen the app insight transction logs. Once the policies are updated to allow the end user to use the custom app the installation works fine. Might be worth just updating the section on importing apps into Teams to mention to check the permissions policies for ensuring the end user app can be run using this guide? https://docs.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#how-custom-app-policies-and-settings-work-together

**Comment by Porkai-Pandian** [comment]
Thank you for providing the guidance on the documentation, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. Thank you!
