### ISSUE TITLE
Deployment fails when template is deployed to southindia 

### ISSUE THREAD

**Issue by geo-msft** [OfficeDev/microsoft-teams-apps-company-communicator#480]
Hi, 

One customer is having this deployment failure when choosing southindia region: 

{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Region doesn't support non-consolidated component creation"
    }
}

This is coming from the App Insights (Microsoft/Insights/Components) and leads to the whole template failing. 
Could you contact me in private Teams chat and advise how to deploy this template in South India? 
How can he deploy the template without app insights, so that the deployment succeeds? 

Thank you.

**Comment by geo-msft** [comment]
Feedback from the customer: 
In the template docs, we do not clearly state which regions are supported for the resources in the template.
This led to multiple issues in its deployment.

**Comment by Porkai-Pandian** [comment]
Thank you for submitting the feedback, documentation has been updated on supporting regions, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
