### ISSUE TITLE
CC Author App can't be added to channel

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-company-communicator#481]
When trying to add the company communicator author app to a channel, we get the error "something went wrong". No other error that I can find to help point to what might have gone wrong. I've attached the app manifest in case you can find an issue. The manifest looked fine to me.
[CompanyCommunicatorAuthors.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/6926803/CompanyCommunicatorAuthors.zip)

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
