### ISSUE TITLE
Ooops! An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

### ISSUE THREAD

**Issue by vikasssdn1** [OfficeDev/microsoft-teams-apps-company-communicator#483]
Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

FYI...For testing purpose, we have deployed the template with AZURE free subscription.

Kindly suggest as we would be moving to production environment very soon.

**Comment by shorties** [comment]
I'm having the same issue, with the same setup, I just set it up today.

**Comment by vikasssdn1** [comment]
> I'm having the same issue, with the same setup, I just set it up today.

I have re-deploying using this youtube video, let's if this helps.

https://www.youtube.com/watch?v=uyEpzu53TUg 

Thanks!

**Comment by shorties** [comment]
> > I'm having the same issue, with the same setup, I just set it up today.
> 
> I am re-deploying using this youtube video, let's if this helps.
> 
> https://www.youtube.com/watch?v=uyEpzu53TUg
> 
> Thanks!



Let me know if that fixes your problem

**Comment by vikasssdn1** [comment]
> > > I'm having the same issue, with the same setup, I just set it up today.
> > 
> > 
> > I am re-deploying using this youtube video, let's if this helps.
> > https://www.youtube.com/watch?v=uyEpzu53TUg
> > Thanks!
> 
> Let me know if that fixes your problem

My issue has been resolved now. I have followed re-sync step in troubleshooting guide and it works great.
