### ISSUE TITLE
App upgraded from V3 to latest version - Failing to send messages to everyone

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-apps-company-communicator#486]
App upgraded from V3 to latest version 4.1.3
And it is working fine to send using M365 group and teams
But it is failing to send using "Send chat to everyone":
Failed to prepare the message for sending:The orchestrator function 'TeamsConversationOrchestrator' failed: "The activity function 'TeamsConversationActivity' failed: "Value cannot be null. (Parameter 'UserType')". See the function execution logs for additional details.". See the function execution logs for additional details.

Shared application insight logs with Priyank

**Comment by vikasssdn1** [comment]
@SubbaReddi I have reviewed your video and able to deploy CC v3 in my test environment. I really appreciate and Thanks for video.
Few things are not working like not able to send messages to Teams and channel, getting message can't find but able to send messages to all users and 365 groups. Do you know any solution so we can send messages to Teams and channel (First 2 options).

**Comment by SubbaReddi** [comment]
@vikasssdn1 : Check if this helps: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#7-when-upgrading-company-commmunicator-from-a-version-prior-to-v4-please-ensure-that-the-users-app-is-installed-in-the-teams-to-send-messages-to-the-team-or-its-members

You would require to install user bot app to required teams channels. then respective teams channels will display in the dropdown(first two options)

**Comment by SubbaReddi** [comment]
Above mentioned issue is resolved by following below steps:
Open storage account in azure portal and delete "UserData" table
After couple of minutes, recreate "UserData" table
And data will be populated in next run.
