### ISSUE TITLE
Guidance in setting up a development env for ui development 

### ISSUE THREAD

**Issue by oclify** [OfficeDev/microsoft-teams-apps-company-communicator#487]
I am currently trying to run the Client App through localhost, while still pointing everything to the services within azure.  I've tried updating the manifest to point to localhost but I'm having very little success.  Any guidance is appreciated!

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
