### ISSUE TITLE
Authors app not able to search Teams groups or Channels while drafting the message

### ISSUE THREAD

**Issue by vikasssdn1** [OfficeDev/microsoft-teams-apps-company-communicator#488]
Authors app not able to search Teams groups or Channels while drafting the message and Getting error message - We could not find any matches.

Getting same message while searching any user.

**Comment by SubbaReddi** [comment]
@vikasssdn1 : Check if this helps: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#7-when-upgrading-company-commmunicator-from-a-version-prior-to-v4-please-ensure-that-the-users-app-is-installed-in-the-teams-to-send-messages-to-the-team-or-its-members

You would require to install user bot app to required teams channels. then respective teams channels will display in the dropdown(first two options)
