### ISSUE TITLE
Steps for Two installations of company communicator app 

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-apps-company-communicator#489]
Follow below steps to deploy second instance of company communicator in single tenant:

Register Azure AD Applications as mentioned in Step 1

While doing ARM Template deployment which is given in Step 2, update “User App External Id” with following value: 148a66bb-e83d-425a-927d-09f4299a9275

Proceeding with remaining steps 3, 4

In Step 5, Please update user app manifest id from 148a66bb-e83d-425a-927d-09f4299a9274 to 148a66bb-e83d-425a-927d-09f4299a9275 and please update author app manifest id from 1c07cd26-a088-4db8-8928-ace382fa219f to 1c07cd26-a088-4db8-8928-ace382fa219d

and proceed with remaining steps as mentioned in deployment guide.

If you miss to update “User App External Id” in step 2, you can update value in following sections:
• Open second instance azure resource group -> Open App service -> Configuration (in left navigation) -> update “UserAppExternalId” value to 148a66bb-e83d-425a-927d-09f4299a9275 -> Click on “ok” -> Click on “save” and restart app service.

• Open second instance azure resource group -> Open function app which is ending with “-prep-function”-> Configuration (in left navigation) -> update “UserAppExternalId” value to 148a66bb-e83d-425a-927d-09f4299a9275 -> Click on “ok” -> Click on “save” and restart function app.

And make sure user manifest id change as mentioned above.

**Comment by bchamnarnkit** [comment]
Hi @josjohns Just confirming, do we need to adjust anything in Azure App Service with the new Author app manifest ID?

**Comment by bchamnarnkit** [comment]
Hi @SubbaReddi Thanks for the comments, you mentioned updating the Author App Manifest ID from 1c07cd26-a088-4db8-8928-ace382fa219f to 1c07cd26-a088-4db8-8928-ace382fa219d. Is there anything in Azure resource group / app services that we need to adjust to the new author app manifest ID as well? Thanks in advance

**Comment by SubbaReddi** [comment]
@bchamnarnkit: Yes, it would require changes in app service/azure function config. But if you change in ARM template deployment, respective changes will be taken care automatically.

**Comment by bchamnarnkit** [comment]
Hi @SubbaReddi - thanks for the response, can you please provide more details as to why specifically in Azure app service / functions needs to be updated with the new author app manifest ID? I know the user ID is updated via the “UserAppExternalID”, however I’m not sure what values needs to be updated with when it comes to author app manifest ID. Thanks a lot!

**Comment by ostumm** [comment]
@SubbaReddi what is happening if the same ID is already in use somewhere else on Tenant? I would expect, that such IDs must be unique. Furthermore, is it required to change some ID for the author app, too?

**Comment by rramos9771** [comment]
It sends me this problem when adding the user zip to teams

![image](https://user-images.githubusercontent.com/96545484/169594853-b64bb7b6-ae5f-4bb3-8f7e-25060e229a1d.png)
