### ISSUE TITLE
Our services aren't available right now

### ISSUE THREAD

**Issue by InspecJ** [OfficeDev/microsoft-teams-apps-company-communicator#490]
My deployment stopped working, I receive below error when I open the app:
_Our services aren't available right now
We're working to restore all services as soon as possible. Please check back soon.

0VJ8bYQAAAAABziYK118hQZeL+qoqf//4TE9OMjFFREdFMDIxMQBlZGIzYzQ4YS0xZTQ2LTRhYjgtODViZS1jMThiZWY4MDRmODk=_

I decided to start with a clean test Tenant and reinstall the company communicator app. Here I also receive the same error (different error code). I am on version 4.1.0 and 4.1.3

Anyone similar experience?

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
