### ISSUE TITLE
Unable to search for Teams as Author

### ISSUE THREAD

**Issue by gruhle** [OfficeDev/microsoft-teams-apps-company-communicator#491]
There are a few threads with similar questions. I've tried all the suggestions but still running into issues.  Ive checked permissions, storage accounts, urls, etc.  

I've side loaded the Author App in one team, and side loaded the user app into another team i'm a member of both teams.  I'm not able to see any Teams/groups as an author.

**Comment by Tech-Savi** [comment]
Hi @gruhle. I'm getting the same experience that I cant see the Teams Groups as an author, however I can see distribution groups. Did you manage to get this sorted?

**Comment by bungleweed** [comment]
You need to install the end user app into a Team for it to be listed. Do this under manage team|apps|upload custom app. You can check the TeamData table in the Azure Storage account for any teams listed in there.

**Comment by jhicksnyc** [comment]
I followed @bungleweed 's suggestion and my TeamData table is empty.  I cannot search for Teams or Groups.
When trying "Send in chat to everyone" I get this error:

> Errors
Failed to prepare the message for sending:The orchestrator function 'SendQueueOrchestrator' failed: "The activity function 'DataAggregationTriggerActivity' failed: "Specified argument was out of the range of valid values. (Parameter 'Recipient count should be > 0. Value: 0') Actual value was .". See the function execution logs for additional details.". See the function execution logs for additional details.

![image](https://user-images.githubusercontent.com/91708649/135552568-1619a432-e933-4c20-b254-d37aaa4c8328.png)

**Comment by kayobrasilicatu** [comment]
Check if you author bot endpoint is blocked from Microsoft's IP Address.

**Comment by bch90** [comment]
Hello, having the same issue here. Any updates please?

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
