### ISSUE TITLE
Communicator author app not working in Teams

### ISSUE THREAD

**Issue by mattomeara5150** [OfficeDev/microsoft-teams-apps-company-communicator#496]
Hi there, We are in the process of setting up your app for our Teams environment. We are right at the end of the deployment, however when we try and "Add to a Team" with the Company Communicators (Authors) we get an error message saying "Something went wrong"
Please see attached screenshot
![error message](https://user-images.githubusercontent.com/29084145/131936744-baa5b030-a6e6-41b2-bce8-143704e0dc1a.JPG)

**Comment by mattomeara5150** [comment]
Can anyone please assist me with this issue?

**Comment by bungleweed** [comment]
Can you open the zip file in an App named App Studio? IT's available in the Teams App store. Open it and then import your zip file. Make sure it opens without any errors.

**Comment by mattomeara5150** [comment]
It imported into App Studio with no problems

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
