### ISSUE TITLE
Issue When Uploading The Company Communicators Authors Zip File

### ISSUE THREAD

**Issue by mreed75** [OfficeDev/microsoft-teams-apps-company-communicator#500]
![image](https://user-images.githubusercontent.com/86731249/133113105-6dea022b-b840-4759-b27c-afb07eddab08.png)

**Comment by bungleweed** [comment]
This normally happens if there was a failure deploying the template in Azure under step 2. You need to resync the App Service. It's in the troubleshooting guide.

**Comment by mreed75** [comment]
Can you provide the steps on how to do this?

Mike Reed
________________________________

**Comment by bungleweed** [comment]
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting

**Comment by billcruze** [comment]
Has this been resolved? I'm also experiencing this but no errors on the deployment.

**Comment by mreed75** [comment]
Yes it is all set now

Mike Reed
________________________________

**Comment by billcruze** [comment]
Did you just sync in app service?

**Comment by mreed75** [comment]
No, that didn’t work.  I had to delete everything and start over.

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
