### ISSUE TITLE
status stuck at sending 0 of... but messages are received

### ISSUE THREAD

**Issue by djjuice** [OfficeDev/microsoft-teams-apps-company-communicator#501]
I can send messages using all of the options and selecting different teams (general channel). The messages are received yet the sent messages always says Sending... 0 of X (where X is the number of users).

I have refreshed the tab but there is no change, (logging out/in doesnt work either)

thanks in advance

**Comment by priyank29** [comment]
@djjuice Can you please restart the data-function. Also check the application insights if there is any failure logged.

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
