### ISSUE TITLE
Company Communicator - Message is stuck on installing app

### ISSUE THREAD

**Issue by medicineshow** [OfficeDev/microsoft-teams-apps-company-communicator#502]
I have installed the latest version of the Company Communicator author application to a specific Team. I have uploaded the user app to the Teams catalogue and made it available through app permission policy to a single user. I want to test sending to all users but only have a single user that is allowed to install the app. ProactivelyInstallUserApp is set to true. 
I have successfully sent to the user by sending to a specific AD group and the adaptive card was received, however, if I send to all users, the users has not received the message and in sent messages, the message shows a status of installing apps with no recipients and no errors.
![image](https://user-images.githubusercontent.com/17124284/133241783-c0ab2a00-a2cf-4062-929c-f6a79292ec9c.png)

**Comment by priyank29** [comment]
@medicineshow There was issue with this scenario and have been fixed with this #509. Closing this for now.

**Comment by medicineshow** [comment]
can you please point me to upgrade instructions?
