### ISSUE TITLE
Using Private Endpoints for Azure Services

### ISSUE THREAD

**Issue by JeromeVigne** [OfficeDev/microsoft-teams-apps-company-communicator#503]
Assuming we can use private endpoints for Service Bus, App Service on VNET, Azure Functions on VNET and private endpoints for the storage account.

Could the documentation be updated to talk about such an implementation?

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by Ario5o** [comment]
> 
I am interested in the same documentation around implementing private endpoints and network restrictions. I am reviewing Azure Secure Score for the subscription the company communicator is provisioned within and there are entries suggesting these types of hardening should be implemented
