### ISSUE TITLE
Size of the images in the draft messages

### ISSUE THREAD

**Issue by KaterinaCejas** [OfficeDev/microsoft-teams-apps-company-communicator#506]
After installation, we wanted to create a draft message with an image, but when importing the image, the following message appears:

>The image is too big! Please upload a JPEG (or equivalent) compressed image with maximum size of 30178 bytes.

![image](https://user-images.githubusercontent.com/49104903/134684032-bd3aa0da-ef8f-4f9a-819d-ba1ebc874ab3.png)

However, the image is smaller than the maximum size. We have tried even smaller images, but the result remains the same.
Could you help us solve this matter? What are the recommended measurements for images?

**Comment by Porkai-Pandian** [comment]
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
