### ISSUE TITLE
Error with Entity Size Limit in Storage Table

### ISSUE THREAD

**Issue by nhtngo** [OfficeDev/microsoft-teams-apps-company-communicator#507]
With ProactiveInstallationOn, when the User App fails to install for users, the error message for the failed user is saved in the following:
**Resource**: StorageAccount
**Table**: NotificationData
**PartitionKey**: SentNotification
**Column**: WarningMessage

However, after about 93 failed users, the WarningMessage column does not update anymore and the following errors are thrown in ApplicationInsights:
![image](https://user-images.githubusercontent.com/91352558/134749342-60ed7128-d82c-4301-ba76-18e382b9d2ab.png)

with the following exception:
![image](https://user-images.githubusercontent.com/91352558/134749426-066c4f7d-5c11-42e5-a474-db877dfa06fb.png)

It seems that it hit a limit for the entity.

**Comment by priyank29** [comment]
@nhtngo the latest PR #509 fixes this. Closing the issue.
