### ISSUE TITLE
HandleFailureActivity throws System.Runtime.Serialization.SerializationException

### ISSUE THREAD

**Issue by nhtngo** [OfficeDev/microsoft-teams-apps-company-communicator#508]
Discovered alongside #507, when trying to handle the error thrown by TeamsConversationOrchestrator. 

In PrepareToSendOrchestrator function, it calls [TeamsConversationOrchestrator](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/f6ccd25034065898952db2ce0639be1dcdc8e23f/Source/CompanyCommunicator.Prep.Func/PreparingToSend/Orchestrators/PrepareToSendOrchestrator.cs#L87). But TeamsConversationOrchestrator calls TeamsConversationActivity which throws the error mentioned in #507. 

The function catches the error, and try to call [HandleFailureActivity](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/f6ccd25034065898952db2ce0639be1dcdc8e23f/Source/CompanyCommunicator.Prep.Func/PreparingToSend/Orchestrators/PrepareToSendOrchestrator.cs#L117), but throws the following error:
![image](https://user-images.githubusercontent.com/91352558/134750774-5470b3e9-3da6-4d2a-b171-a8353bf00daa.png)

with the following exception message:
![image](https://user-images.githubusercontent.com/91352558/134750806-154da6e9-5bab-4901-9c27-efed4c4f3fd7.png)

**Comment by priyank29** [comment]
@nhtngo the latest PR #509 fixes this. Closing the issue.
