### ISSUE TITLE
Restrict Appservice access to Azure Front door only?

### ISSUE THREAD

**Issue by nadishs** [OfficeDev/microsoft-teams-apps-company-communicator#510]
Hi,
Since the default implementation of this plugin has an Azure front door instance and given front door's security features, shouldn't access to appservice be restricted to only be through azure front door? Is there a reason why this is not the case in default deployment?

**Comment by gsv022** [comment]
Hi @nadishs,
Thanks for your suggestion. The default option does not restrict the app service to being accessible only through the front door. But the configuration can be customized to make it accessible through the front door. We will review your suggestion and post that will take a decision to provide the restriction with default deployment.
