### ISSUE TITLE
"Preview in this channel" and "Export detailed results" aren't working. I get error 403 BotNotInConversationRoster

### ISSUE THREAD

**Issue by Branyac** [OfficeDev/microsoft-teams-apps-company-communicator#514]
Hello,

I have problems with Company Communicator. I get the error 403 when I click on the buttons: "Preview in this channel" and "Export detailed results".

This issue does not affect the other Company Communicator features, for example: I can create and send messages correctly.

In logs I saw that the error has the code "BotNotInConversationRoster" and the message "The bot is not part of the conversation roster." I think the error may be in Company communicator (Authors) bot.

Company communicator is installed in a private Microsoft Teams channel.

I tried these things to solve the error, but none worked:
  - I uninstalled and installed again Company Communicator in the same Channel.
  - I mentioned Company Communicator (Authors) in the channel.

Is any other thing I can try to solve my issue?

Regards.

**Comment by kayobrasilicatu** [comment]
Same problem here after deploy v4.1.4. On version 4.1.3 it did not happen.

**Comment by Branyac** [comment]
I'm still getting the same error messages.

This is the message when exporting detailed results:
![image](https://user-images.githubusercontent.com/1702716/136509756-572f2df2-91d8-4bff-a1c4-d11b28c2acf1.png)

And this is when I try use "Preview in this channel":
![image](https://user-images.githubusercontent.com/1702716/136509955-fb1999b8-9067-4e77-931c-654fcb2cc09d.png)

**Comment by SubbaReddi** [comment]
Bots in private channel doen't work. So,it is expected behavior.
