### ISSUE TITLE
Message cannot be sent to Dynamic group

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-company-communicator#516]
Hi, someone know if Security Dynamic Group in Azure cannot receive message? It's by design?

**Comment by bungleweed** [comment]
M365 dynamic group should work. You can securiry enable those as well.

**Comment by gsv022** [comment]
Hi @faalive ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
