### ISSUE TITLE
Export Detailed Results for multiple sent messages stuck in "Export in progress" For days 

### ISSUE THREAD

**Issue by NiallM2016** [OfficeDev/microsoft-teams-apps-company-communicator#518]
I have sent messages successfully, and downloaded Export Detailed Results successfully, But looking back through send messages "Export Detailed Results" is greyed out on some of my historical messages, not all messages just some. When I hover over them I get message "Export in progress" some of these are over a week old. 
![image](https://user-images.githubusercontent.com/30409784/135848787-af781644-3263-4fd3-abb2-b69729542152.png)

**Comment by kayobrasilicatu** [comment]
I think is the problem discussed on #514 .

**Comment by NiallM2016** [comment]
Export in progress issue,  route cause not defined but resolution workaround!!
If we go back into Company communicator chat , when the export is Queued you need to give app permission to upload to your OneDrive. We had selected Allow quite a few times, but it seemed to be stuck and not approving , as soon as we selected decline on these problem downloads it freed up the export in progress,  and now we are able to re-export all reports that had been stuck, will continue to monitor, it is possible that colleagues may have started an export at the same time and got into some kind of conflict etc.. as we are currently using shared test logins in our test environment, will divide these logins out to remove possible conflict .
![image](https://user-images.githubusercontent.com/30409784/136009993-02a13991-83b6-4095-8e7b-9d7691f54188.png)

**Comment by kayobrasilicatu** [comment]
Can't allow or decline. The result is the same:

![image](https://user-images.githubusercontent.com/87320575/136023010-db74826d-c048-4e88-a61e-197cb55f5b07.png)

**Comment by kayobrasilicatu** [comment]
My problem is that our WAF service was blocking Microsoft's IP Address from reaching Company Communicator Web App.

**Comment by gsv022** [comment]
Hi @NiallM2016 ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by victorsimonlee** [comment]
Hi. Any closure to this issue? I am facing the very same problem. 

I click the "Allow" button but the file is not exported.

**Comment by GabrielPitondo** [comment]
Hi guys, any updates from the developers, I'm facing the same error... When I click the "Allow" button, this message appers:

![Capturar](https://user-images.githubusercontent.com/76107067/221257095-53b0f50a-2187-4f5b-acc8-bf17a488c692.PNG)

And the file is not exported

**Comment by victorsimonlee** [comment]
Hi @GabrielPitondo, 

even with this error you can still have access to the export file - given you have permissions in the Azure Portal.

Export the results. Do **not** click on Permitir/Recusar. Then:

1- Login to the Azure portal 
2- Select the company communicator storage account
3-  Go to Data Storage > Containers.
4- Select the one named "exportdatablobs"

There, you will find your exported reports.

Cheers
