### ISSUE TITLE
Lack of order result trimming in send to distribution group dropdown

### ISSUE THREAD

**Issue by MarcBayeTokiota** [OfficeDev/microsoft-teams-apps-company-communicator#521]
If you've got lots of distribution groups with very similar names and you're looking for a group whose name matches the beginning of the name of many other groups, the target group may not appear in the dropdown (maybe due to the top 20 limit and by the lack of ordination on the results prior to apply that top 20?)

If you're looking for XYZ and you've got XYZ, XYZ01, XYZ02, ..., XYZ99, you expect to find XYZ at the top of the list, but it isn't there, making it impossible to select it.

Looking for the existing group "SecurityGroup_ALL-Latam-Brasil", it doesn't appear while other longer ones do:
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/91940885/137279015-760a2d25-4f19-4d90-aa90-5ec9d67728a9.png)

**Comment by Porkai-Pandian** [comment]
Hi @MarcBayeTokiota,

Thanks for raising the query, we're looking into your query, will get back to you as early as possible with response.

**Comment by gsv022** [comment]
Hi @MarcBayeTokiota ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
