### ISSUE TITLE
IS company-communicator Support for Right to Left Text ? 

### ISSUE THREAD

**Issue by ahmedmahmoudR** [OfficeDev/microsoft-teams-apps-company-communicator#523]
Text inserted which is written right to left is not displayed in the card as right to left, instead it is left to right.

Teams fully supports right to left support but not the Company Communicator app.

It would be great if this support was brought to the product, as it is required for languages such as Arabic

**Comment by Porkai-Pandian** [comment]
Hi @ahmedmahmoudR,

Thanks for sharing your feedback on the app, we're looking into your query, will get back to you as early as possible with response.

**Comment by Mikhail2k15** [comment]
Company Communicator uses Adaptive Cards. Adaptive Cards in Teams doesn't support RTL. https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Known-limitations#2-adaptive-card-doesnt-support-rtl

**Comment by ahmedmahmoudR** [comment]
Thanks for your response but what about (Begining in 1.5, users will now be able to set this optional rtl )

**Comment by ahmedmahmoudR** [comment]
@Mikhail2k15
  Can I use horizontalalignment = right  with Company Communicator  Adaptive Cards ?

**Comment by ahmedmahmoudR** [comment]
![This is an image](https://i.imgur.com/kwsb327.png)

Like This

**Comment by OritOrlanczyk** [comment]
Is there an option to add RTL support to languages like Hebrew?
I tried to add "rtl": true attribute to adaptive card json file and it works.

**Comment by ahmedmahmoudR** [comment]
@Porkai-Pandian  Any Update ?

**Comment by gsv022** [comment]
Hi @ahmedmahmoudR ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
