### ISSUE TITLE
Restrict "Send in chat to everyone" to set of users

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/microsoft-teams-apps-company-communicator#524]
"Send in chat to everyone" is very sensitive option and should be restricted to a set of users.

**Comment by Porkai-Pandian** [comment]
Hi @nanddeepn,

Thanks for raising the query, we're looking into your query, will get back to as early as possible with response.

**Comment by Porkai-Pandian** [comment]
Hi @nanddeepn,

Thank you for sharing your feedback on the app, we'll discuss your suggestion with our PM team and take the action in future releases of CC, however this option was explicitly asked by few users to send the message in their organization.

**Comment by nanddeepn** [comment]
Hi @Porkai-Pandian 
Thank you for your reply.

We should definitely have this option. However, may be from the configuration we should restrict this feature to be visible to certain set of Authors.
Thank you!

**Comment by gsv022** [comment]
Hi @nanddeepn ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!
