### ISSUE TITLE
Company Communicator as a private deployment ??

### ISSUE THREAD

**Issue by NiallM2016** [OfficeDev/microsoft-teams-apps-company-communicator#528]
We have deployed Company communicator into our test environment as per normal deployment guide.

concerns from our security team 

We have quite a few given to us , but a few of the main items 
•	It’s public facing
•	Its deployed via a public arm template, we normally deploy via internal Teraform, 
•	Deployed from an open source github repo ( we would prefer internal github to our company)
•	No integration with conveyor for deployment

Our cloud security does not like Azure functions to put it mildly. 
The first three points being public really is a pain point,  Has anyone attempted to make the deployment private , 
App service environment , needs to private (  it is public URL ) if that is at all possible 
Then what would this mean for access between the Azure storage and Azure functions etc. 
Even if some are not possible,  would like to the have that education when dealing with our own security team if we are to push them along the recommended deployment path.

**Comment by Porkai-Pandian** [comment]
Hi @NiallM2016,

Thanks for raising the query, we're looking into your query, will get back to as early as possible with response.

**Comment by adrianfernandezcas** [comment]
Howdy! I have the same issues as @NiallM2016 , we want to deploy the Company Communicator but our security team doesn't like at all that the app has to be configured as multitenant.

I apologise in advance if this is obvious to others, but: after checking the FAQ and other related threads, it'd seem that: 

- the only reason why multitenancy is required is that "Bot Channels Registration only supports multi-tenant account types"; 
digging deeper I see in the [documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=singletenant) that 
- this resource being deprecated
- there are mentions all over the place to multi-tenant apps
- I also read somewhere else that multitenancy was only required if you manually register the application. 
- @Mikhail2k15 mentioned [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/519) that multitenancy was on the way.

So is this still an issue? It sounds like there should be a workaround, if only a manual one.

Thank you

**Comment by gsv022** [comment]
Hi @NiallM2016 ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by adrianfernandezcas** [comment]
@gsv022 
The issue certainly still exists, Company Communicator is by default a public, multitenant app and it can't be changed, but cibersecurity really doesn't like it.

Is there a way to change this? I've read elsewhere that this is partly due to the SDK version. How hard would it be to change the SDK version manually? Roughly, what steps would I have to follow and with what tools?

**Comment by gsv022** [comment]
Hi @NiallM2016 ,
Thanks for the suggestion. As of now, the default implementation is multitenant. We will review your suggestion and do the necessary. But now, we can't provide guidance on this.

**Comment by v-royavinash** [comment]
@NiallM2016  we're closing this issue since this feature is already added to our backlog and will be considered in future releases of CC based on the priority.
