### ISSUE TITLE
The Application is not working after send 100000 messages 

### ISSUE THREAD

**Issue by reinaldo27** [OfficeDev/microsoft-teams-apps-company-communicator#534]
Hello, i need your help because, we have a company communicator and send a 100K messages (all my users), the app broke for a two weeks and not sen any messages to the users, in the application the appear the warning that said 

**Our Services aren't available rigth now**  

**We're working to restore all services as soon as posible. Please check back soon**

Attache the screenshots of the error 
![Screenshot_20211022_102508](https://user-images.githubusercontent.com/87042078/139914752-ab43fe54-62d9-4cd7-9457-751524ed8a5e.jpg)
![Screenshot_20211022_102524](https://user-images.githubusercontent.com/87042078/139914784-731fafc7-e99e-4963-9cee-bc4155d118dd.jpg)

**Comment by Porkai-Pandian** [comment]
Hi @reinaldo27,

Thanks for raising the query, we're looking into your query, will get back to as early as possible with response.

**Comment by Porkai-Pandian** [comment]
Hi @reinaldo27,

Can you please try the below steps and let us know if it resolves the issue,

Login to Azure portal and navigate to resource group, 
-> Click on Azure function which name is ending with Prep function 
-> Open Prep function URL (https://*************.prep-function.azurewebsites.net
-> Add. SCM in URL like https://*************.prep-function.scm.azurewebsites.net 
-> Click on Debug console 
-> Click on CMD 
-> Navigate to Site -> wwwroot 
-> Open host.json file by clicking on edit icon 
-> Add "maxOrchestrationActions": 150000 and save.

After the above changes are completed, go back to the azure prep function, and restart the service.

**Comment by Porkai-Pandian** [comment]
Hi @reinaldo27,

Please let us know if the solution provided above resolved the issue and if we can close this issue

**Comment by Porkai-Pandian** [comment]
Closing the issue, if still not resolved please create new issue
