### ISSUE TITLE
App not installed for users who didn't activate Teams account

### ISSUE THREAD

**Issue by yalcindizdar** [OfficeDev/microsoft-teams-apps-company-communicator#535]
We added the end user app to Global Setup policy in Teams Admin. Proactive app install feature was also enabled. But when we try to send a message to all users, message sent status is stuck at "Installing App" stage and the message is not sent to anyone.

![image](https://user-images.githubusercontent.com/75633412/140056718-26261a02-0a67-4d0c-a5ec-370f2c99ced5.png)

We disabled the proactive app installation feature. In this case the message is delivered to nearly half of the users and the other half doesn't receive it. 

![image](https://user-images.githubusercontent.com/75633412/140056275-aa8de10c-33d1-442e-9b01-de26d76a134a.png)

We made a test and discovered that the app is not installed for the users who haven't ever logged in to Teams from any type of Teams client, hence the messages we sent are not delivered to those users . 

How can we make the end user app installed even to the users who haven't logged in to their Teams account?

**Comment by Porkai-Pandian** [comment]
Hi @yalcindizdar,

Thanks for raising the query, we're looking into your query, will get back to as early as possible with response.

**Comment by Porkai-Pandian** [comment]
Hi @priyank29,

Can you please check this issue, is there a chance the app will not be installed for the users who have not logged in to Teams, just wondering if this is expected or any other ways to address this issue?

**Comment by priyank29** [comment]
@yalcindizdar Global setup policy will not install the app for users who haven't logged into their Teams account. The proactive installation feature can install the app in this case. 
As you mentioned, the app was stuck with Installing App, so please check the Application insights for the error logs and share for further analysis.

**Comment by yalcindizdar** [comment]
Here are some screenshots from the Application Insights failure logs:

![image](https://user-images.githubusercontent.com/75633412/142191817-80934d6d-b24d-4d8f-8797-490eb5ac9eae.png)

![image](https://user-images.githubusercontent.com/75633412/142192213-11438ec0-f92b-4c62-827a-2d5b64094502.png)

![image](https://user-images.githubusercontent.com/75633412/142192649-c24c802d-1a5d-44e4-ad45-ba638a9fe64f.png)

Would these be adequate? 

Thanks for your support !

**Comment by SubbaReddi** [comment]
@yalcindizdar: I see Graph API calls failing with 403 forbidden error. App permission policy in Teams admin center could be blocking ​. So, Can you validate app permission policy?

Reference: https://docs.microsoft.com/en-us/microsoftteams/teams-app-permission-policies

**Comment by yalcindizdar** [comment]
Hi @SubbaReddi , sorry for the late response. We have checked the app permission policy in Teams admin center and confirmed that Company Communicator is in the allowed custom apps list. So, it seems that there is no blocking configuration set.

**Comment by yalcindizdar** [comment]
Hi @SubbaReddi ,

Here are some screenshots from App Permissions in Teams Admin:

![image](https://user-images.githubusercontent.com/75633412/144555698-bf56ff88-e5cd-46d5-811b-d250ac85a39e.png)

![image](https://user-images.githubusercontent.com/75633412/144555781-5b82fd2b-66e4-4dd8-8f70-7fc4c4221e89.png)

![image](https://user-images.githubusercontent.com/75633412/144556002-07a68d03-0805-480e-920e-934cca7d9507.png)

Are those enough?

Thank you very much for your suppoprt !

**Comment by mhark033** [comment]
> @yalcindizdar: We may need to validate configurations in screen share

Can you support me on this one too? I have the same problem like this now in Production.

**Comment by gsv022** [comment]
Hi @yalcindizdar ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
