### ISSUE TITLE
Adding Company Communicator to Teams Channel doesn't Work

### ISSUE THREAD

**Issue by lman-SL** [OfficeDev/microsoft-teams-apps-company-communicator#537]
Hey,

I tried adding the Company Communicator to a Teams Channel.
When trying to add it I get following error:

![image](https://user-images.githubusercontent.com/91659941/140082922-8afb671d-6afc-4667-a2f5-e258dd68d65c.png)

Thanks for your support.

**Comment by Porkai-Pandian** [comment]
Hi lman-SL,

Thanks for raising the query, we're looking into your query, will get back to as early as possible with response.

**Comment by Porkai-Pandian** [comment]
Hi @lman-SL,

We need few more information to determine the issue, we can see the 'Save' button is disabled, can you please confirm if you're the owner of the Teams channel where you're installing the app, also do you've have admin permissions to author app

**Comment by lman-SL** [comment]
Hi,

I confirm that I am the owner of the Teams Channel where I'm trying to install the app and I should have admin permissions to the author app.
How do I check this?

Perhaps we could also schedule a call for troubleshooting the issue together.
Please tell me when you're available.


With Kind regards
Manuel Leuzzi

---
Swiss Life AG
Manuel Leuzzi
General-Guisan-Quai 40
Postfach, 8022 Zürich
Office: BC0248, Binz Center, Grubenstrasse 49, 8045 Zürich
T +41 43 284 50 08
***@***.***
www.swisslife.ch<http://www.swisslife.ch/>

Disclaimer
This e-mail and any associated files may be confidential. If you have received this e-mail in error, I/we ask you not to distribute this message any further, copy it, forward it or make use of it in any other way. Please notify the sender immediately by e-mail if you have received this message in error and ensure that this message is permanently deleted from your system. Me/thank you you.

**Comment by lman-SL** [comment]
Hey,

Do you have any update?

Thanks.


With Kind regards
Manuel Leuzzi

---
Swiss Life AG
Manuel Leuzzi
General-Guisan-Quai 40
Postfach, 8022 Zürich
Office: BC0248, Binz Center, Grubenstrasse 49, 8045 Zürich
T +41 43 284 50 08
***@***.***
www.swisslife.ch<http://www.swisslife.ch/>

Disclaimer
This e-mail and any associated files may be confidential. If you have received this e-mail in error, I/we ask you not to distribute this message any further, copy it, forward it or make use of it in any other way. Please notify the sender immediately by e-mail if you have received this message in error and ensure that this message is permanently deleted from your system. Me/thank you you.

**Comment by magurrapu** [comment]
Hi Manuel,

Can you verify the below step from deployment guide Step 2.7 and make changes if your account is not added to the Sender UPN List.?

Update the "Sender UPN List", which is a semicolon-delimited list of users (Authors) who will be allowed to send messages using the Company Communicator. 

Thanks,
Machander

**Comment by Porkai-Pandian** [comment]
Hi @lman-SL, do you've any update on this issue?

**Comment by lman-SL** [comment]
Hi,

Yes, the problem seems to be solved.
I found it out by myself in the end.


With Kind regards
Manuel Leuzzi

---
Swiss Life AG
Manuel Leuzzi
General-Guisan-Quai 40
Postfach, 8022 Zürich
Office: BC0248, Binz Center, Grubenstrasse 49, 8045 Zürich
T +41 43 284 50 08
***@***.***
www.swisslife.ch<http://www.swisslife.ch/>

Disclaimer
This e-mail and any associated files may be confidential. If you have received this e-mail in error, I/we ask you not to distribute this message any further, copy it, forward it or make use of it in any other way. Please notify the sender immediately by e-mail if you have received this message in error and ensure that this message is permanently deleted from your system. Me/thank you you.

**Comment by Porkai-Pandian** [comment]
Thank you for the confirmation @lman-SL, glad that the issue resolved, we'll proceed with closing the issue, would you mind share the fix you implemented so that it'll help us in resolving similar issues in future
