### ISSUE TITLE
teams users can replay to company communicator message

### ISSUE THREAD

**Issue by abdelbakyismail** [OfficeDev/microsoft-teams-apps-company-communicator#539]
when we send an announcement to users using the company communicator app they can repaly to this message

**Comment by faalive** [comment]
Same for me: randomly chat appear as open also if "isNotificationOnly":  is set to true. 
I have had same issue a couple of month ago when there's been a conflict with a Teams update...all is come back as standard when Microsoft has released a fix directly on tenant

**Comment by Porkai-Pandian** [comment]
Hi abdelbakyismail,

Thanks for raising the query, we're looking into your query, will get back to as early as possible with response.

**Comment by abdelbakyismail** [comment]
Dears,

Thanks for response. I resolved it by change in the permission option property in the manifest.json file of users file Package and remove "messageTeamMembers" and remove from it .

Thanks & Regards,

Abdelbaky Ismail
MWP Consultant
M (+2) 010 91393822
[Logo]<http://www.gbrands.com/>

**Comment by Porkai-Pandian** [comment]
Hi @abdelbakyismail,

Thanks for your response, we're glad that you're able to resolve the issue, we'll proceed with marking this issue as closed.

**Comment by faalive** [comment]
Hi, I have tried your solution but error persist :(
Today I have other three customer with same issue: in total 25k users affected

**Comment by abdelbakyismail** [comment]
The issue still exist ill you uninstall the users package and install it a gain. D if it still exist you can delete teams users cache and sign in to teams in this case it will work fine. By the way by default it should reflected to the users and work fine without clearing teams cache, but may be there is a big delay from teams setup policy update to take affect on end users.

Abdelbaky Ismail
MWP Consultant
M (+2) 010 91393822
[Logo]<http://www.gbrands.com/>

**Comment by faalive** [comment]
Hi, I continue to have issue (now I saw also on my test tenant), but there's a procedure to clear Teams cache centrally? Ho can do it for all cx employee?
