### ISSUE TITLE
SentNotificationData is growing with notification:1 partition keys

### ISSUE THREAD

**Issue by cristianoag** [OfficeDev/microsoft-teams-apps-company-communicator#540]
I noticed that since 4.1.5 upgrade the SentNotificationData table is creating two records for each sent message. That is causing the table to grow very fast. Why do we need a notificationid:1 records on that table?

**Comment by priyank29** [comment]
@cristianoag This is the optimization to handle large scale data. Earlier the data was handled in-memory and used to cause issues when sending messages for large number of users. Now, the data is saved in the table and :1 denotes the batch count number and is processed in batches.

**Comment by cristianoag** [comment]
Thanks @priyank29, I imagined from analyzing the code. The thing I see with the approach is that the table will grow twice as fast. We need a way to housekeep those records as soon as the message is sent. IMHO.

**Comment by gsv022** [comment]
Hi @cristianoag ,
We have added the enhancement/feature in our backlog items and we will taking it in the future sprints depending on the priority and bandwidth.
