### ISSUE TITLE
Power Shell deployment reliability 

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-company-communicator#543]
PS deployment process stuck after successful authentication without any reasons 
![image](https://user-images.githubusercontent.com/11201670/140878706-9df55f11-e82c-4de9-a880-3e6fb3f351c6.png)

After several attempts, the deployment was failed
Different reasons the last one was this^
![image](https://user-images.githubusercontent.com/11201670/140878063-d51bbbc8-fca8-41b1-8010-98a16e9ac33c.png)

**Comment by Porkai-Pandian** [comment]
Hi @Mikhail2k15,

Thanks for raising the query, we're looking into the issue with PS deployment, will get back to you as early as possible with response.

**Comment by gsv022** [comment]
Hi @Mikhail2k15 ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you still require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
