### ISSUE TITLE
ARM template doesn't follow azure best practices. Part 1

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-company-communicator#544]
- To follow security best practices and the latest PCI compliance standards, Microsoft recommends enabling the latest version of TLS protocol (TLS 1.2).
- Bot Channels Registration and Web App Bot were deprecated on Sept 1st, 2021 and the official recommendation is to use Azure Bot instead.
- According to the latest recommendation, https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview softDelete must be enabled.

**Comment by Porkai-Pandian** [comment]
Hi @Mikhail2k15,

Thank you for your recommendations and pointing out on best practices, we'll review internally and add it to our backlog and incorporate the same in future releases.

**Comment by Mikhail2k15** [comment]
@Porkai-Pandian could you merge my corresponding PR #545  into v5.x branch?

**Comment by Porkai-Pandian** [comment]
Hi @Mikhail2k15,

Currently I don't have access to approve it, it should be the engineering team who needs to approve it

**Comment by Porkai-Pandian** [comment]
Hi @Mikhail2k15, 

Thank you for the changes you've made, it has been incorporated and will be available in the next version of the release that will happen in the next 2 weeks, hence closing this issue.
