### ISSUE TITLE
Problem upgrading from version 4.1

### ISSUE THREAD

**Issue by arelraptor** [OfficeDev/microsoft-teams-apps-company-communicator#546]
HI all

Previously, we had version 4.1 and it was working fine.

Today, we have tried to upgrade it using Deployment Center (Sync Option)

![image](https://user-images.githubusercontent.com/74198534/140966194-c6ed7e27-f950-4de5-b9fd-1b4a77fd00b7.png)

We have done this step for App Service and for the 3 Azure Function. All process ended successfully.

![image](https://user-images.githubusercontent.com/74198534/140966369-19d299e7-39df-47ab-8817-0e288b6acef2.png)

Nevertheless, now it is unusable.

App Service (or trying to use Authors app), I get this error.

![image](https://user-images.githubusercontent.com/74198534/140966530-b47b73fb-7f82-42e3-88ca-460eec0fcba5.png)

Azure Functions (all of them) shows these errors:

![image](https://user-images.githubusercontent.com/74198534/140966722-c5e7c38e-3099-40b1-8b2b-a7d03432e027.png)

![image](https://user-images.githubusercontent.com/74198534/140966781-60228c4a-d77b-433e-ad9c-fadf009d2d78.png)

Regarding "Azure Functions runtime is unreachable" error, I have reviewed and storage account seems to be OK (it has no change), configuration parameters in Azure Functions are right pointing to right storage account with right connection string, etc

Obviously, I have tried to restating Azure services, redeploying, etc without success.

Any idea?

**Comment by Porkai-Pandian** [comment]
Hi @arelraptor,

Thanks for raising the query, we're looking into your query, will get back to you as early as possible with response.

**Comment by arelraptor** [comment]
Thanks!!
Let me know if you need some additional information.
It is important for us to try to solve it asap.

Thanks for your collaboration

**Comment by Mikhail2k15** [comment]
Upgrade process from 4.x to 5.x is not just a sync process. Did you follow up the migration guide from 4.x to 5.x?

**Comment by Porkai-Pandian** [comment]
Thanks @Mikhail2k15 for the response.

Hi @arelraptor,

Here is the link for the migration guide to latest version 5.x, please follow the steps and let us know if you still have issues

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide

**Comment by arelraptor** [comment]
Hi

Version 5? It seems that latest version is 4.2

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator

And version 4.2 is the version number that is showed in the second screenshot.

I am a quite lost

**Comment by Mikhail2k15** [comment]
Yes, it is pretty confusing, but the current version is 5.0 and you have to follow up on the new migration guide.

**Comment by arelraptor** [comment]
Obviously, It is quite confusing.

I mean, in the main page I can see references to version 4.1 or version 4.2...and if I click on right, latest version is 4.1.5.

And moreover, number version after Azure deployment sync is 4.2...and It is referred to #532 ....and this #532 is showed in the main page as 4.2 (and updated 2 days ago).

I'm sorry, but it is very difficult to understand from my side.

Is there any way to rollback Azure deployment to previous state or other 4.x version? For internal reasons, I must bring it back ASAP.

**Comment by Mikhail2k15** [comment]
If you take a look at current branches in this repo you can try to roll back to the 4.1.4 version if you change the "sync" branch from master to v4.x Only @priyank29  or someone from project owners can update this branch to 4.1.5.

**Comment by arelraptor** [comment]
Thanks for your answer.

Please, allow me an additional question. How can I change the sync branch?

Thanks for your comprehension.

**Comment by Mikhail2k15** [comment]
In your screenshot above there is a disconnect link. Disconnect then set up a new External git connection with the same repo but instead of master use v4.x branch.

**Comment by arelraptor** [comment]
Hi

After changing sync branch, our Company Communicator is alive again. 

Thanks for your support 

@Mikhail2k15 I have seen you have opened an issue to update version info and it has been updated some hours ago.

![image](https://user-images.githubusercontent.com/74198534/141088206-646042d7-2278-41d6-bf6c-9af556f23a84.png)

Thanks for your collaboration
