### ISSUE TITLE
Versioning hell

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-company-communicator#549]
Everywhere in repo you have the 4.2 version, but in reality, it is 5.0 now. Many customers are confused with that 
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/546#issuecomment-964492342
![image](https://user-images.githubusercontent.com/11201670/141052482-cf6e33f7-bcc0-4cc9-9bb2-6d646e108faa.png)

![image](https://user-images.githubusercontent.com/11201670/141052856-ca37d825-5438-4f1d-bbb8-cc22ce2b9ae2.png)

**Comment by Porkai-Pandian** [comment]
Hi @Mikhail2k15,

There was a delay in releasing v5.0 causing confusion, however it is released and you can find release 14, please confirm if this can be closed.

**Comment by Mikhail2k15** [comment]
I don't understand what do you mean by "release 14". 
Anyway, after @aosolis update, it looks better, but please update the home page as well, add something like that: 
1) the current version is 5.0, to migrate, additional work is required, 
2) add a link to the migration guide and release notes. 
I have several customers who just pushed the sync button, and now they are in trouble because there is no way to roll back.  Maybe make sense to provide roll back guidance to 4.1.5

**Comment by Porkai-Pandian** [comment]
Highlighted release 14 which is the latest version v5.0, yes will update the documentation to eliminate confusions related to latest version

![image](https://user-images.githubusercontent.com/87537966/141171323-44a35d39-df62-4e06-968b-b1a73aa60a55.png)

**Comment by Porkai-Pandian** [comment]
Hi @Mikhail2k15, please let us know if you're good to close this issue as the documentation is updated.
