### ISSUE TITLE
when selecting group get "We couldn't find any matches"

### ISSUE THREAD

**Issue by joseescm** [OfficeDev/microsoft-teams-apps-company-communicator#554]
Permissions have all been added according to document but all is not able to find groups to be able to send message using first option.   Get the message, "We couldn't find any matches."   Is there a particular permission that is missing.  These are the ones currently being applied. 

Select “Microsoft Graph”, then select Delegated permissions and check the following permissions,

GroupMember.Read.All
AppCatalog.Read.All
then select Application permissions and check the following permissions,

GroupMember.Read.All
User.Read.All
TeamsAppInstallation.ReadWriteForUser.All

**Comment by Porkai-Pandian** [comment]
Hi @joseescm,

Thanks for raising the issue, please check if the user app in installed to the Teams channel, Team group names will appear in the dropdown only if the user app in installed.

**Comment by Porkai-Pandian** [comment]
Hi @joseescm,

Please let us know if you have any updates or can we close this issue.

**Comment by joseescm** [comment]
We can close it.  The solutions given corrected the issue.

Thanks,

***@***.***
THE UNIVERSITY OF TEXAS
RIO GRANDE VALLEY
UTRGV.EDU
Tony Escamilla
Data Center Systems Engineer III
Information Technology - Data Center
956-665-5042
***@***.******@***.***>
Brownsville * Edinburg * Harlingen
