### ISSUE TITLE
Default Parameters Field

### ISSUE THREAD

**Issue by msft-limchenglei** [OfficeDev/microsoft-teams-apps-company-communicator#557]
Please advise on the situation that we will need to replace the default value for the following parameters:

- userAppExternalId
- serviceBusWebAppRoleNameGuid
- serviceBusPrepFuncRoleNameGuid
- serviceBusSendFuncRoleNameGuid
- serviceBusDataFuncRoleNameGuid
- storageAcccountWebAppRoleNameGuid
- storageAccountPrepFuncRoleNameGuid

Assuming if there is multiple Company Communicator deployment in the same subscription.

**Comment by Porkai-Pandian** [comment]
Hi @msft-limchenglei, thank you for raising the query, we're looking into it and will get back to you as early as possible.

**Comment by priyank29** [comment]
@msft-limchenglei yes you have to change the values in case of multiple Company Communicator deployment in the same subscription.

**Comment by msft-limchenglei** [comment]
Where can we extract/generate the new values to replace for the second Company Communicator?

**Comment by priyank29** [comment]
@msft-limchenglei the vaules are GUID. Any GUIDs can be used.
