### ISSUE TITLE
How do I know my version?

### ISSUE THREAD

**Issue by acanton5** [OfficeDev/microsoft-teams-apps-company-communicator#558]
Hi all,

How do I know my version? I started to work in a new company and they already have it but I do not know what version they have.

Kind regards,
Alexander

**Comment by Porkai-Pandian** [comment]
Hi @acanton5,

Thank you for raising the query, you can find the version installed in the about tag of the application, screenshot below for reference,

![image](https://user-images.githubusercontent.com/87537966/143082995-9ecb2ead-656c-4706-a756-9a062b0c16dc.png)

**Comment by acanton5** [comment]
Thank you a lot :)
