### ISSUE TITLE
The activity function 'StoreMessageActivity' failed:

### ISSUE THREAD

**Issue by acanton5** [OfficeDev/microsoft-teams-apps-company-communicator#560]
Dear team,

I get this error:

Failed to prepare the message for sending: The activity function 'StoreMessageActivity' failed: "Invalid URI: The hostname could not be parsed.". See the function execution logs for additional details.

do you know anything about it?

**version 5**

Kind regards,
Alexander

**Comment by Porkai-Pandian** [comment]
Hi @acanton5,

Thank you for raising the query, issue seems to be in your xxxx-prep-function, please check your configuration in the prep function to make sure the URI's updated are correct, if so you can check the logs in Application insights for more information.

**Comment by acanton5** [comment]
Hello,
you mean here? I don't see any URI value. Just KeyVault:Url.

![image](https://user-images.githubusercontent.com/73191514/144079346-a4b6aae9-95da-4379-86ec-a4234ab2a748.png)

**Comment by acanton5** [comment]
Hello @Porkai-Pandian can you help here?

**Comment by Porkai-Pandian** [comment]
Worked over the call with customer and issue is resolved as confirmed with customer, hence closing the issue
