### ISSUE TITLE
Cannot send message

### ISSUE THREAD

**Issue by mhark033** [OfficeDev/microsoft-teams-apps-company-communicator#561]
I tried to follow the guide accurately and it's ups and down. 
When I finally deployed it, I can't use the app. See below error message

I already tried to resync it but still the same error

<img width="1038" alt="Screen Shot 2021-11-30 at 10 12 56 AM" src="https://user-images.githubusercontent.com/61768253/143974110-a8fe8b4c-72c4-4462-959b-263b09c001f4.png">
 
<img width="970" alt="Screen Shot 2021-11-30 at 10 21 08 AM" src="https://user-images.githubusercontent.com/61768253/143974181-cb89d6ed-fc2d-4650-82dd-ba6d1529a675.png">

**Comment by Porkai-Pandian** [comment]
Hi @mhark033 

Thank you for raising the query, there could be multiple reasons why the messages are not delivered,

- Please check if the deployment is successful, if not redeploy the app again
- If deployment is successful, then try out the below steps,
1. Open Azure portal 
2. Navigate to respective resource group
3. Open “******-prep-function” azure function
4. Click on “Restart” and wait for few minutes.
5. App should be able to pick up existing messages in queue to send or else try to send new message.
- If still messages are queued, check the application insights logs and share the exception you see for us to troubleshoot further.

**Comment by mhark033** [comment]
Hi Here’s the error message in Application Insight logs

***@***.***
***@***.***
***@***.***


Regards,
Tom

AMIS - Platform Engineering - Enterprise Messaging
***@***.*** ***@***.***%20%0d>
Direct: +1 3368906439

OUT OF OFFICE:

Working hours:
Sunday - Thursday (4PM-1AM) Eastern Time

**Comment by mhark033** [comment]
Just to add,
operation_Name
failedCount
impactedUsers
UploadActivity
12
1
PUT Export/ExportNotification
1
1
***@***.***

Regards,
Tom

AMIS - Platform Engineering - Enterprise Messaging
***@***.*** ***@***.***%20%0d>
Direct: +1 3368906439

OUT OF OFFICE:

Working hours:
Sunday - Thursday (4PM-1AM) Eastern Time

From: Tomas, Rey Mhark
Sent: Tuesday, November 30, 2021 7:51 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Cannot send message (Issue #561)

Hi Here’s the error message in Application Insight logs

***@***.***
***@***.***
***@***.***


Regards,
Tom

AMIS - Platform Engineering - Enterprise Messaging
***@***.*** ***@***.***%20%0d>
Direct: +1 3368906439

OUT OF OFFICE:

Working hours:
Sunday - Thursday (4PM-1AM) Eastern Time

**Comment by Porkai-Pandian** [comment]
Hi @mhark033,

Unfortunately, we're unable to view the logs shared by you, can you please share it as screenshot or a file, it seems the information you shared is masked.

**Comment by mhark033** [comment]
Here. 

operation_Name	                   failedCount	           impactedUsers
UploadActivity  	                    12	                             1
PUT Export/ExportNotification    1                                       1
![error 3](https://user-images.githubusercontent.com/61768253/144177132-6908584e-fbd6-4744-813c-145a8607429a.png)
![error 2](https://user-images.githubusercontent.com/61768253/144177135-cd7a7754-0f86-4e43-a7c7-f0de643b54b7.png)
![error 1](https://user-images.githubusercontent.com/61768253/144177137-2034335e-5a2b-4ac8-9e95-0519dea146c1.png)
![error 4](https://user-images.githubusercontent.com/61768253/144177138-e50618f6-c8e0-46d0-ab3a-947e1d6489ec.png)

**Comment by gsv022** [comment]
Hi @mhark033 ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by TomSawyer03** [comment]
Yes it is still showing...

**Comment by gsv022** [comment]
Hi @mhark033 ,
Please share the MS Teams ID, we will reach out to you over the chat and will discuss the issue.

**Comment by mhark033** [comment]
***@***.***

Regards,
Tom

AMIS - Platform Engineering - Enterprise Messaging
***@***.*** ***@***.***%20%0d>
Direct: +1 3368906439

OUT OF OFFICE:

Working hours:
Sunday - Thursday (4PM-1AM) Eastern Time

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
