### ISSUE TITLE
Run and debug in Local

### ISSUE THREAD

**Issue by jmfloreszazo** [OfficeDev/microsoft-teams-apps-company-communicator#565]
Please, I need to know the steps to be able to run and debug this locally.

I have already deployed, I have changed the values ​​in appsettings.

But when I launch ngrok, I can't get it to route the urls properly.

Someone has a guide.

Thank you.

**Comment by v-royavinash** [comment]
Hi @jmfloreszazo 

To debug locally you will need all resources required for the Company communicator should be deployed on your Azure subscription. You need to download the code and start it in Visual studio using its .sln file or you can fork and clone the git repo in VS.

You need to follow the [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
There is two way you can proceed from this point. You need the following resources as mentioned in [appsettings.json.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/master/Source/CompanyCommunicator/appsettings.json)

- You can do the deployment using the ARM Template option (Deployment Guide) and from the configuration of the App service, you will get the required information.

- Or you need to create all resources manually.

Once you have all the required information you need to fill the [appsettings.json](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/master/Source/CompanyCommunicator/appsettings.json).

For AppDomain you can use ngrok or an equivalent tunneling solution. You will have to run it for the localhost app is running on.

Following [Step 5 of Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) just replace the app domain with ngrok URL.

Also on Azure Portal follow the below steps:

- Go to Azure Portal --> Resource Group for CC app --> Author Web App Bot --> Configuration --> Replace the Messaging Endpoint with the ngrok URL.
- Similarly, replace the Messaging Endpoint for User Web App Bot.
- Go to App Registration --> Add Redirect URL with the ngrok URL.

![image](https://user-images.githubusercontent.com/94480537/144419978-ff9bb2a0-a9a4-475a-ac9d-6ea8ffb8cf53.png)

- Go to  Expose an API and change the Domain name of the Application ID URI.

![image](https://user-images.githubusercontent.com/94480537/144420009-5e052027-9366-42dd-af02-5e2bb1dd2780.png)

Once done run the code using VS and add the debugger point to validate.
Let me know if it works. If not please elaborate on the error you are getting.

**Comment by jmfloreszazo** [comment]
The problem persists.

Step I have done:

-  Change appsettings.json
-  Change manifest with ngrok url (I have ngrok pro)
-  Change the Bot Endpoint in Azure as mentioned before

![settings](https://user-images.githubusercontent.com/9931443/144500362-530e7945-8aea-412e-a0e9-4fa4968bdedf.png)

Run ngrok start --all.

Run the program in Visual Studio 2019.

And test with:

![InTeams](https://user-images.githubusercontent.com/9931443/144500735-88026e98-d541-450d-bb3f-39823ec86170.png)

This test are in browser:

![localhost](https://user-images.githubusercontent.com/9931443/144500418-d7b0f88c-6095-4594-a015-d52b61175684.png)

![ngrok](https://user-images.githubusercontent.com/9931443/144500434-dfea7fba-fc98-4cd5-866e-962df0af7777.png)

![info_ngrok](https://user-images.githubusercontent.com/9931443/144500444-c4d55f3c-52f7-488f-920e-22fae600f7de.png)

And with this ngrok configuration:

![myngrokfile](https://user-images.githubusercontent.com/9931443/144500477-e72e6e4b-8902-4eb1-a5de-ca3930cc7387.png)

This is the Author manifest:

![Error1](https://user-images.githubusercontent.com/9931443/144501075-553ba721-563d-4e03-b92f-5976d523d12c.png)

If I change the manifest:

![Error2](https://user-images.githubusercontent.com/9931443/144502404-73d7cddc-0b89-40c1-90ef-5e7566c7b033.png)

Hope this can help.

I think it may be the ngrok configuration I use, but I have also used Thttps: //github.com/OfficeDev/microsoft-teams-tunnelrelay and I have the same problem.

Thank you very much for your help.

**Comment by jmfloreszazo** [comment]
Please, some help about last message: @v-royavinash @Porkai-Pandian 

Thanks

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
