### ISSUE TITLE
Comunications in Chat to not respect spaces between paragraphs

### ISSUE THREAD

**Issue by iahindes** [OfficeDev/microsoft-teams-apps-company-communicator#567]
Hello, 

We are seeing that when a comunication is sent via chat through teams it does not respect the spaces between paragraphs, whilst through channels it does. Is this a known issue or do we have a way to fix? Thank you very much

**Comment by Mikhail2k15** [comment]
It is a known issue in Teams product.

**Comment by CaseyLittlechild** [comment]
We also have this issue, and our communications team are considering stopping using Company Communicator because of this. Do we know if this issue will be fixed?

**Comment by v-royavinash** [comment]
@CaseyLittlechild As pointed it's an issue with the Team's product. However, we'll review internally and will let you know if there is a way to address the issue for the Company Communicator.

**Comment by gsv022** [comment]
Hi @iahindes ,
The issue has been added to the backlog already. We will review it and do the needful.
