### ISSUE TITLE
The details procedures of how to change app and sender icon in this app

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#568]
I can find both steps 2.8 and 5 in deployment guide mentioned can configurate app icon and name.
May I know the relationship of those 2 configurations? Which one is really can change the sender icon and name when user receive message? or Both?

**Comment by v-royavinash** [comment]
Hi @rex-ma 

As mentioned, it can be done from both steps. The preferred way is to do it through [Step 5](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) while creating the team's package. In this, you will have more flexibility if you want to update the icon and name again in the future and re-deploy the team’s package.

- For Icon: Please use the different Icon with the same name of color.png under the Manifest folder.
- For Name: Please update the [name --> short] in the manifest files for Author and User bot.

![image](https://user-images.githubusercontent.com/94480537/144638324-2965f02d-5d2f-4eda-bc19-01f1e791c836.png)

**Comment by Porkai-Pandian** [comment]
Hi @rex-ma

Please let us know if you've any queries or we can close this issue

**Comment by Mikhail2k15** [comment]
Looks like changes in app manifests are not enough. In toast notification on Desktop Client, a user will see a standard icon.

**Comment by rex-ma** [comment]
Hi @Mikhail2k15 , may we know what is "toast notification on Desktop Client"? Thanks
