### ISSUE TITLE
Deployment failed using Powershell: RoleAssignmentUpdateNotPermitted

### ISSUE THREAD

**Issue by hcyhome** [OfficeDev/microsoft-teams-apps-company-communicator#569]
My account is service admin of the Azure subscription and I've also added myself to the "user access admin" role, but still get below error, what's going on?

One of my doubts is the M365 tenant I want to deploy is different from the tenant where the Azure service is deployed, but I've filled in different tenant id in parameters.json.

[
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  }
]

**Comment by v-royavinash** [comment]
Hi @hcyhome 

Could you please change the **role name GUIDs** in case of another in progress Company Communicator Deployment in the same subscription and retry the deployment steps? Let me know if you still get the error.

**serviceBusWebAppRoleNameGuid**: Default value is 958380b3-630d-4823-b933-f59d92cdcada.

**Comment by Porkai-Pandian** [comment]
Hi @hcyhome, 

As discussed over IM, closing this issue since the deployment is successful.
