### ISSUE TITLE
Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

### ISSUE THREAD

**Issue by lman-SL** [OfficeDev/microsoft-teams-apps-company-communicator#570]
I installed the Company Communicator with the Powershell Guide, now after adding it to a Team I get following error:

"Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists."

I'm in the UPN-Sender List and the deployment was successful.

Thanks for your help.

![image](https://user-images.githubusercontent.com/91659941/145036654-69d59d82-c20d-4660-849a-851c82f3a20f.png)

**Comment by Porkai-Pandian** [comment]
Hi @lman-SL,

Thank you for raising the query, there are multiple reasons why this error might occur, can you please double check during the app registration process you’ve selected multi-tenant for author and user apps. If yes, can you also check the app insights to see if any exceptions getting logged there and share it with us to troubleshoot further.

**Comment by lman-SL** [comment]
Hi @Porkai-Pandian

Thank you for your response.
Following for the App registration:

**Communicator App registration:**

- API Permissions all granted
- I seem to have 2 Client Secrets
- I have following error in the token Config:

![image](https://user-images.githubusercontent.com/91659941/145173793-6fb01533-45ad-43de-94f8-2ecfcb0138b4.png)

**Communicator-Author App Registration:**

- Again 2 Client Secrets
- No API Permission here


**Communicator-Users App Registration:**

- 2 Client Secrets here again
- No API Permissions



For the Communicator App registration only Single-Tenant
For the Author and User App registration Multi-Tenant



![image](https://user-images.githubusercontent.com/91659941/145175047-d57a8eb1-4a34-4d04-aece-f6d20dc0d59e.png)

**Comment by lman-SL** [comment]
@Porkai-Pandian 

Maybe we could schedule a Teams Meeting together to have a look at the current problem I'm facing and to analyze further.
Please send me your E-Mail Address so I can schedule a Meeting for us.

**Comment by jmfloreszazo** [comment]
I have the same problem with V5.

The steps followed in V5 are the same as indicated in the instructions.

I have removed all security in the API and it allows me to work "correctly".

![image](https://user-images.githubusercontent.com/9931443/145763149-2ae00593-1fc4-478f-9882-d82fb2587e7d.png)

Thank you

**Comment by lman-SL** [comment]
I haven't found where to set this setting?
Could you please tell me where I can change that?

Kind regards
Manuel

**Comment by jmfloreszazo** [comment]
@lman-SL This code is in the solution. Find all "[Autorize" and comment it. Deploy the apps service and test.

Be careful that we are left without security.

**Comment by Porkai-Pandian** [comment]
@jmfloreszazo it's advisable not to modify the authorize which might lead to other issues and we'll not be able to support in such cases.

@lman-SL you shared the exception count, can you please share the exception details

**Comment by jmfloreszazo** [comment]
@Porkai-Pandian Thanks for the advise, I understand the derived problems, it was to see where the error occurred. It is already limited and it is an authorization problem.

**Comment by ostumm** [comment]
Hi everyone, is this resolved already? I have the same issue

**Comment by cordinario** [comment]
Hi @Porkai-Pandian I'm having the same issue in my demo tenant.  It seems to happen when I draft my first message after not having been signed in for at least a day.  Usually after the first (sometimes second) failure, it seems to work.

**Comment by gsv022** [comment]
Hi @lman-SL ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
