### ISSUE TITLE
Proactive installation issues

### ISSUE THREAD

**Issue by emiludev** [OfficeDev/microsoft-teams-apps-company-communicator#571]
Version 4.1.3

Hello, we installed company communicator to a customer, proactive installation is on, we test this feature by sending a communication to an active directory security group, total of members of this group are 7 people, however the application was not installed for 2 of them.

We have validated the following:

- Users have a Teams license.
- Do not have restrictions on use with custom applications in the setup and permissions policies in teams.
- All users are in the global setup and permission policies, without restricting the use of custom or third-party applications.
- The function apps work correctly.

We would like to know what other configuration we should consider for troubleshooting and grant that the application is installed to all members of this group.

Greetings.

**Comment by Porkai-Pandian** [comment]
Hi @emiludev,

Thank you for raising the query, can you please check app insights for exceptions logged related to installation failure for the 2 users mentioned, ideally whatever you validated seems to be good.

**Comment by gsv022** [comment]
Hi @emiludev ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
