### ISSUE TITLE
Can't send message to everyone with v5

### ISSUE THREAD

**Issue by bzbwqz** [OfficeDev/microsoft-teams-apps-company-communicator#575]
Completed the deployment with powershell script for v5.0 and tried to send message to everyone in the teams, but it always below error. I tried twice on another test tenant environment.

Warnings
Failed to sync all users. Status Code: Unauthorized Exception: Code: Authorization_IdentityNotFound Message: The identity of the calling application could not be established. Inner error: AdditionalData: date: 2021-12-11T07:05:31 request-id: 67a----0-48ba-a108-6ad6174cf4df client-request-id: xxxxxxxcf4df ClientRequestId: 6647a9e5..............................f4df Failed to sync all users. Status Code: Unauthorized Exception: Code: Authorization_IdentityNotFound Message: The identity of the calling application could not be established. Inner error: AdditionalData: date: 2021-12-11T07:05:37 request-id: ff20d..............................652c34cae client-request-id: ff20d069-....bacd-f66652c34cae ClientRequestId: ff20d.....6-

**Comment by Porkai-Pandian** [comment]
Hi @bzbwqz,

Thank you for raising the query, it seems to be issue with client secrets, can you please check if you've updated the Client Secrets correctly during deployment?

**Comment by reivson** [comment]
Hello @Porkai-Pandian what do mean with client secrets how can I check this information? The deployment was successful, and I have the same issue.

**Comment by eliudvazqueztti** [comment]
I have the same issue with a new implementation, version 5.0.0, 

Failed to sync all users. 
Status Code: 
Unauthorized Exception: 
Code: 
Authorization_IdentityNotFound Message: The identity of the calling application could not be established. 
Inner error: 
AdditionalData: date: 2022-04-20T21:53:22 
request-id: xxxx
client-request-id: xxxx
ClientRequestId: xxxx

**Comment by gsv022** [comment]
Hi @bzbwqz ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
