### ISSUE TITLE
Application gateway instead of Front Door

### ISSUE THREAD

**Issue by Mykhailo-D** [OfficeDev/microsoft-teams-apps-company-communicator#576]
Is it possible to use Azure app gateway instead of FD? If yes, what would be the setup?
We've tried to specify a gateway with 2 rules (forward and redirect, same as in the FD) and failed. 
Getting an error "Sorry, an error occurred while trying to access this service." in the Authors app. And we're getting 401 response when trying to reach https://appServiceURL/api/draftnotifications (or /sentnotifications). 
What should I look into?

**Comment by Porkai-Pandian** [comment]
Hi @Mykhailo-D 

Thank you for raising the query, if you don't want to use Front Door, you can go with custom domain option, more info on the same will be available [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option)

**Comment by v-royavinash** [comment]
@Mykhailo-D , Could you please confirm do you need any other additional info or we are good to close this request?
