### ISSUE TITLE
Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request.

### ISSUE THREAD

**Issue by zamilgroupholdingco** [OfficeDev/microsoft-teams-apps-company-communicator#579]
All of a sudden the system is giving the following error:

Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request.

**Comment by zamilgroupholdingco** [comment]
After installing it was working perfectly for a whole year then this  error came out

**Comment by Porkai-Pandian** [comment]
Hi @zamilgroupholdingco,

Thank you for raising the query, it seems to be issue with client secrets, can you please check if your client secret you provided in the application is still active and not expired?

**Comment by zamilgroupholdingco** [comment]
What you mean how can i check ?

**Comment by zamilgroupholdingco** [comment]
Please advise the steps

**Comment by Porkai-Pandian** [comment]
Hi @zamilgroupholdingco below are the steps to check if the client secret is expired or not, if expired provided the steps how to create newly and update it, please let me know if you've any follow up questions.

1)	To find author bot app id, go to Azure portal -> look for Company Communicator App services -> Configuration -> Author AppId
 
![image](https://user-images.githubusercontent.com/87537966/146255217-0a090734-203c-4171-8b0a-b849d2399ec4.png)

2)	Click show values and copy the Id
3)	Go to App Registration and search for the app with id you copied above
4)	Go the author app registration -> Certificates & secrets -> Check for expiry date of the secret
 
![image](https://user-images.githubusercontent.com/87537966/146255243-cafb2d56-0ab5-4503-bcfc-5000667eda03.png)
5)	If the secret is already expired, click ‘New client secret’ and generate it
6)	Copy the value, navigate to the Azure key vault for Company Communicator -> Secrets -> update the AuthorAppPassword
![image](https://user-images.githubusercontent.com/87537966/146255251-45fbd4db-5b2e-4786-859e-35d0872b25b8.png)
7)	Restart the app services, function apps

**Comment by zamilgroupholdingco** [comment]
Hello, can we connect on MS Teams so you may support me I have no clue how to do this ????!!?!!? :)

**Comment by zamilgroupholdingco** [comment]
I Could not find (6) AuthorAppPassword  could not find it ?

**Comment by v-royavinash** [comment]
Hi @zamilgroupholdingco, Could you please share your MS Teams Id we will connect over Teams.

**Comment by Porkai-Pandian** [comment]
Hi @zamilgroupholdingco,

Have you checked the client secret, is it expired then? Also, may I know which version of the app do you have issues with?

**Comment by zamilgroupholdingco** [comment]
> Hi @zamilgroupholdingco, Could you please share your MS Teams Id we will connect over Teams.

communications@zamil.com

**Comment by zamilgroupholdingco** [comment]
> Hi @zamilgroupholdingco,
> 
> Have you checked the client secret, is it expired then? Also, may I know which version of the app do you have issues with?

yes version of the app can be found by the teams admin

**Comment by mdish** [comment]
Hi, we need your assistance please contact us on communications@zamil.com
