### ISSUE TITLE
Will "Send Everyone" option deploy the client app to all users without user app deployed? Even choose false for "Proactively Install User App"?

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#580]
Will "Send Everyone" option deploy the client app to all users without user app deployed? Even choose false for "Proactively Install User App"?

**Comment by SalmanBaig18** [comment]
No, from my understanding, it will only send it to the users who have the user app installed in their Teams environment. Suggest you create a Teams App permission policy to restrict the app from everyone and then create a second policy to allow the app for the specific users. This helps if you want to use the application only for a certain group of people or for the testing phase of the application

**Comment by rex-ma** [comment]
Thanks, I assumed the confirmation may bounced back to default when process re-deploy.
