### ISSUE TITLE
Cannot send message 

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#581]
We cannot send message after deploy the app

![LE_Error1](https://user-images.githubusercontent.com/25476072/146334675-453f2f36-1302-48a1-a7ff-6187cc5b727d.PNG)

**Comment by v-royavinash** [comment]
Hi @rex-ma, 

Thank you for raising the query, there could be multiple reasons why the messages are not delivered,

Please check if the deployment is successful, if not redeploy the app again
If deployment is successful, then try out the below steps,
Open Azure portal
Navigate to the respective resource group
Open “******-prep-function” azure function
Click on “Restart” and wait for a few minutes.
The app should be able to pick up existing messages in the queue to send or else try to send a new message.
If still messages are queued, check the application insights logs and share the exception you see for us to troubleshoot further.

**Comment by rex-ma** [comment]
The issue finally fixed by another re-sync of those 3 functions
