### ISSUE TITLE
Any limitation has to concern for push more then 14,000 messages to users when click send to everyone with version 4.1.5?

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#582]
Any limitation has to concern for push more then 14,000 messages to users when click send to everyone with version 4.1.5?

**Comment by v-royavinash** [comment]
Hi @rex-ma, Company communicator v4.x and above supports sending 1M messages. However, if you still face any errors while sending please do reach out to us.

**Comment by rex-ma** [comment]
Will it stop at the middle of sending, and sender have to wait 30 minutes or 1 hours to continue like 3.x version?

**Comment by Porkai-Pandian** [comment]
Hi @rex-ma 

Please let us know if you've any other queries, if not we'll proceed with closing the issue.
