### ISSUE TITLE
Deployment successful, but author app won't authenticate

### ISSUE THREAD

**Issue by glblinck** [OfficeDev/microsoft-teams-apps-company-communicator#584]
After getting a successful deployment using the PowerShell deployment, the author app won't authenticate. Clicking on continue has the app trying to authenticate, but it just goes back to the same spot. I've tried wiping the install and re-doing the deployment a few times, but each time I'm getting the same result. Any idea on where to look for the issue?
![image](https://user-images.githubusercontent.com/61463212/146969986-99d05490-29ea-435a-9656-84dce6627318.png)

It just goes back here:
![image](https://user-images.githubusercontent.com/61463212/146970661-7b4e52c7-0c94-4ed7-ae78-f3e6a0cfadbd.png)

**Comment by Porkai-Pandian** [comment]
Hi @glblinck 

Thank you for raising the query, can you please check the application insights to see if any exceptions logged for this issue, if so request you to share the error details for us to troubleshoot better.

**Comment by laracloud123** [comment]
hi @Porkai-Pandian I have the same issue. Would be great to get some advice. Thanks.

**Comment by gsv022** [comment]
Hi @glblinck ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
