### ISSUE TITLE
Messeges are not sent

### ISSUE THREAD

**Issue by OritOrlanczyk** [OfficeDev/microsoft-teams-apps-company-communicator#587]
Messeges are not sent.
Error 404 in GET DraftNotificationByID function.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/17028406/147056576-ed72913c-4444-45d6-8d76-0c604e77ca42.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/17028406/147056615-78a0a0a4-afe2-4e64-9fe8-9aa69a89692d.png">

Any idea?

**Comment by OritOrlanczyk** [comment]
After adding GroupMember.ReadAll permission to AzureAD authors app the issue seems to be resolved but I'm not sure it's best practice.

**Comment by Porkai-Pandian** [comment]
@OritOrlanczyk glad that issue resolved, we'll close the issue.
