### ISSUE TITLE
Anyone solution to prevent new users can see the test message that author app sent before?

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#589]
We have an author app sent some test message to some test group users before only, how can we prevent other user see those test message next time when we send to everyone in Org?

**Comment by Porkai-Pandian** [comment]
Hi @rex-ma,

As I mentioned over email thread earlier, there is no such restriction with CC app, even though if the message is sent already, if the message is sent again at the organization level, all the users will receive the message again.

**Comment by Porkai-Pandian** [comment]
Hi @rex-ma,

Please let us know if you've any other queries, if not we'll proceed with closing the issue.
