### ISSUE TITLE
Markdown of creating new lines/spacing not working for customer

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-company-communicator#590]
Dear Company Communicator AppTemplate-team,

my customer is trying to use markdowns in the summary field of the Company Communicator.

They want to use spacing/creating new & empty lines between paragraphes.

Unfortunately, no matter what they do, this is not working and the final Company Communicator message is always smushing paragraphs and text together without leaving the intended line blank.

Could you please help with this issue.

Example for the problem.

Correct formatting:

"This is sample text.

This is the next paragraph.

This is the next paragraph."

What the Company Communicator is formatting:

"This is sample text.
This is the next paragraph.
This is the next paragraph."

**Comment by Porkai-Pandian** [comment]
Hi @apptemplatequestions,

Yes it's a known issue, this is the limitation with adaptive cards which doesn't support formatting.

**Comment by gsv022** [comment]
Hi @apptemplatequestions ,
The issue has been added to the backlog already. We will review it and do the needful.
