### ISSUE TITLE
Error by sent message to all users

### ISSUE THREAD

**Issue by Karspi** [OfficeDev/microsoft-teams-apps-company-communicator#591]
Hello community,

I have installed the Comp Communicator App with the PowerShell deployment.  After the installation, a try to send a message to all users led to the following error 

Warnings
Fehler beim Synchronisieren aller Benutzer. Status Code: Unauthorized Ausnahme: Code: Authorization_IdentityNotFound Message: The identity of the calling application could not be established. Inner error: AdditionalData: date: 2021-12-24T13:42:14 request-id: 1a57074d-bb43-4ed5-bd4a-0ff759fa7642 client-request-id: 1a57074d-bb43-4ed5-bd4a-0ff759fa7642 ClientRequestId: 1a57074d-bb43-4ed5-bd4a-0ff759fa7642 Fehler beim Synchronisieren aller Benutzer. Status Code: Unauthorized Ausnahme: Code: Authorization_IdentityNotFound Message: The identity of the calling application could not be established. Inner error: AdditionalData: date: 2021-12-24T13:42:22 request-id: d20370e7-fbe4-42ba-8894-e417d5a70095 client-request-id: d20370e7-fbe4-42ba-8894-e417d5a70095 ClientRequestId: d20370e7-fbe4-42ba-8894-e417d5a70095

What am I missing here? 

Thank you

Kind regards
Spikar

**Comment by v-royavinash** [comment]
Hi @Karspi ,

 Could you please check if you've updated the Client Secrets correctly during deployment? It seems to be an issue with client secrets,?

**Comment by JasthiKalyani** [comment]
Hi @Karspi,

Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
