### ISSUE TITLE
Can I deploy the second instance with the first one's version?

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#593]
We use the company communicator v4.1
I know the latest one is v5.0.
I'm not sure  how to deploy the second instance as the same version as the first one.
Please teach me how to that.

Thanks advance.

**Comment by v-royavinash** [comment]
Hi @ATshirai ,
You can deploy any of the versions listed from the releases link : 
[https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/releases](url)

- Download the source code of the specific version. Under the Deployment folder--> Copy content of azuredeploy.json.

![image](https://user-images.githubusercontent.com/94480537/147482178-62e11d8c-820e-4a19-b8ad-7d0bf49dbeef.png)

- Click on [Deploy to Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOfficeDev%2Fmicrosoft-teams-company-communicator-app%2Fmaster%2FDeployment%2Fazuredeploy.json)

- Click on **Edit template** to edit the app template. Paste the content copied previously.

![image](https://user-images.githubusercontent.com/94480537/147482613-7f84b560-ea42-45fe-981d-75f08cfbf400.png)

- During custom deployment change the branch name to the specific version you are deploying.

![image](https://user-images.githubusercontent.com/94480537/147482704-81194ac5-8fdf-4148-81d2-9d86e90fbecf.png)

- You can get the branch name as shown below:

![image](https://user-images.githubusercontent.com/94480537/147482043-7cc7b37b-24a8-49cb-9ba1-8b27fabbc356.png)

**Comment by ATshirai** [comment]
Hi @v-royavinash 

Thanks a lot for your information.
I'll try it with the above way.

**Comment by v-royavinash** [comment]
@ATshirai , Could you please confirm if we are good to close this issue?
