### ISSUE TITLE
failed to create conversation with teams user 

### ISSUE THREAD

**Issue by hinsharm** [OfficeDev/microsoft-teams-apps-company-communicator#594]
![CC error](https://user-images.githubusercontent.com/62093194/147533622-973aadae-3b18-471e-bca7-eb5307448812.PNG)

**Comment by v-royavinash** [comment]
Hi @hinsharm,

There may be multiple reasons for this issue. Could you please check if the secret values at the app registration are the same as mentioned in the app service configuration?

**Comment by hinsharm** [comment]
@Nirajkumar ***@***.***> CPOR partner working on ground on this issue.

Hi Niraj,

Could you please check the configurations values mentioned below and confirm.

Best Regards,
Hina Sharma
Mobile 7718846577
***@***.******@***.***>
***@***.***<https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d1-d9ce92fda706e72da63dcd4893bc5f55/views/imgo>

**Comment by hinsharm** [comment]
Hi Team,

Requesting you to please guide us to check this remotely, as we are not able to retrieve the app registration secret id.

Looping in @Manish ***@***.***> from AU Bank.

Regards,
Niraj Pandey
(+91-9136027669)

From: Hina Sharma ***@***.***>
Sent: Tuesday, December 28, 2021 3:50 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; Nirajkumar Pandey ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] failed to create conversation with teams user (Issue #594)

@Nirajkumar ***@***.***> CPOR partner working on ground on this issue.

Hi Niraj,

Could you please check the configurations values mentioned below and confirm.

Best Regards,
Hina Sharma
Mobile 7718846577
***@***.******@***.***>
***@***.***<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fus-prod.asyncgw.teams.microsoft.com%2Fv1%2Fobjects%2F0-eus-d1-d9ce92fda706e72da63dcd4893bc5f55%2Fviews%2Fimgo&data=04%7C01%7Cniraj.pandey%40embee.co.in%7C8fe9d7215e55495dd8b208d9c9eba188%7C718a99124d8d4d9daf9aabe3dca42cb2%7C0%7C0%7C637762836151639472%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=es8%2F9KXe4ZvzJKwTJdEDhV%2Bn78xlmPyZoNefDmkN4HQ%3D&reserved=0>

**Comment by hinsharm** [comment]
Hi Team,

There is a significant impact because of this issue, requesting your help to expediate it.
Let me know what I can do to get this addressed.

Thanks in advance!

Best Regards,
Hina Sharma
Customer Success Manager
Mobile 7718846577
***@***.******@***.***>
***@***.***<https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d1-d9ce92fda706e72da63dcd4893bc5f55/views/imgo>
From: Nirajkumar Pandey ***@***.***>
Sent: Tuesday, December 28, 2021 4:40 PM
To: Hina Sharma ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; Manish Kumar ***@***.***>
Cc: Mention ***@***.***>
Subject: [EXTERNAL] RE: [OfficeDev/microsoft-teams-apps-company-communicator] failed to create conversation with teams user (Issue #594)

Hi Team,

Requesting you to please guide us to check this remotely, as we are not able to retrieve the app registration secret id.

Looping in @Manish ***@***.***> from AU Bank.

Regards,
Niraj Pandey
(+91-9136027669)

From: Hina Sharma ***@***.******@***.***>>
Sent: Tuesday, December 28, 2021 3:50 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; Nirajkumar Pandey ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] failed to create conversation with teams user (Issue #594)

@Nirajkumar ***@***.***> CPOR partner working on ground on this issue.

Hi Niraj,

Could you please check the configurations values mentioned below and confirm.

Best Regards,
Hina Sharma
Mobile 7718846577
***@***.******@***.***>
***@***.***<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fus-prod.asyncgw.teams.microsoft.com%2Fv1%2Fobjects%2F0-eus-d1-d9ce92fda706e72da63dcd4893bc5f55%2Fviews%2Fimgo&data=04%7C01%7CHina.Sharma%40microsoft.com%7C058dea0eee9841bc209b08d9c9f291e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637762866022681883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XZ8rlFwJsZQWAB9s1JPt5%2BihCSq4v9WvkO9gGwVf5W4%3D&reserved=0>

**Comment by v-royavinash** [comment]
Hi @nirajkumar,

You cannot view the secret again. It can be viewed only once just after its creation. For a workaround, the first 3 letters can be viewed. Please try to match it with the first 3 letters of the secret mentioned in the app service. The other way around is to create a new secret and manually update it at the configs.

**Comment by hinsharm** [comment]
Hi Team,
Greetings for the day...!
Would require your assistance over here to overcome the issue faced by AU Bank.
Regards,
Niraj Pandey
(+91-9136027669)

From: Hina Sharma ***@***.***>
Sent: Tuesday, December 28, 2021 4:50 PM
To: Nirajkumar Pandey ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; Manish Kumar ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] failed to create conversation with teams user (Issue #594)

Hi Team,

There is a significant impact because of this issue, requesting your help to expediate it.
Let me know what I can do to get this addressed.

Thanks in advance!

Best Regards,
Hina Sharma
Customer Success Manager
Mobile 7718846577
***@***.******@***.***>
***@***.***<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fus-prod.asyncgw.teams.microsoft.com%2Fv1%2Fobjects%2F0-eus-d1-d9ce92fda706e72da63dcd4893bc5f55%2Fviews%2Fimgo&data=04%7C01%7Cniraj.pandey%40embee.co.in%7C1d4970b7bb24407197c608d9c9f3f8e0%7C718a99124d8d4d9daf9aabe3dca42cb2%7C0%7C0%7C637762871981450677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1H4r%2BBXtjHUnJC8dgd9vG799zFK74UsN02wsvpjTAAc%3D&reserved=0>
From: Nirajkumar Pandey ***@***.******@***.***>>
Sent: Tuesday, December 28, 2021 4:40 PM
To: Hina Sharma ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; Manish Kumar ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: [EXTERNAL] RE: [OfficeDev/microsoft-teams-apps-company-communicator] failed to create conversation with teams user (Issue #594)

Hi Team,

Requesting you to please guide us to check this remotely, as we are not able to retrieve the app registration secret id.

Looping in @Manish ***@***.***> from AU Bank.

Regards,
Niraj Pandey
(+91-9136027669)

From: Hina Sharma ***@***.******@***.***>>
Sent: Tuesday, December 28, 2021 3:50 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>; Nirajkumar Pandey ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [OfficeDev/microsoft-teams-apps-company-communicator] failed to create conversation with teams user (Issue #594)

@Nirajkumar ***@***.***> CPOR partner working on ground on this issue.

Hi Niraj,

Could you please check the configurations values mentioned below and confirm.

Best Regards,
Hina Sharma
Mobile 7718846577
***@***.******@***.***>
***@***.***<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fus-prod.asyncgw.teams.microsoft.com%2Fv1%2Fobjects%2F0-eus-d1-d9ce92fda706e72da63dcd4893bc5f55%2Fviews%2Fimgo&data=04%7C01%7Cniraj.pandey%40embee.co.in%7C1d4970b7bb24407197c608d9c9f3f8e0%7C718a99124d8d4d9daf9aabe3dca42cb2%7C0%7C0%7C637762871981450677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1H4r%2BBXtjHUnJC8dgd9vG799zFK74UsN02wsvpjTAAc%3D&reserved=0>

**Comment by v-royavinash** [comment]
@hinsharm , As discussed over teams, the above issue is addressed. Could you please confirm if we are good to close this issue?

**Comment by hinsharm** [comment]
Yes, please - Thank you!
