### ISSUE TITLE
"send to everyone" brought Author app with StatusCode 500

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#595]
We sent a message to about 4.8k users using "send to everyone"  for 4.8k users.
Among sending messages , the following strange events occurred.
 The web app's http response became late.
 The Author app continued to display "StatusCode 500 Internal server error" on Teams client.

![image](https://user-images.githubusercontent.com/77769064/147628577-3a247e61-3959-4570-8034-e8f2cf255b70.png)

It took about an hour for "send to everyone" to be done, but the above events have finished when  we shutdown  the web app on the next day.
Our Company Communicator is v4.1.0,  and the proactive install option is enable.
Does anyone know  why that happened?

**Comment by v-royavinash** [comment]
Hi @ATshirai ,

Could you please share the application insights logs to understand the actual error thrown?

**Comment by ATshirai** [comment]
@v-royavinash 

Sorry to be late to share logs.
I'm not sure that the application insights's screenshots and logs are useful to understand the actual error thrown.
[Issue-#595.xlsx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/7811924/Issue-.595.xlsx)

**Comment by ATshirai** [comment]
Hi @v-royavinash , 

The issue timeline was the following:  
12:56 
  "send to everyone" started to send
around 13:15
   web app began to be late response
13:31 
    auto healing rebooted the web app
14:09 
    "send to everyone" completed 

We found two errors around the time(13:15) that the web app's http responses began to be late.
1) Installed Apps 409 error
2) TaskHub Instance 404 error

Please let me know why 409 and 404 errors occurred.
[Issue#595_20220106.xlsx](https://github.com/OfficeDev/m
[Issue#595_20220106.xlsx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/7820554/Issue.595_20220106.xlsx)
icrosoft-teams-apps-company-communicator/files/7820550/Issue.595_20220106.xlsx)

**Comment by ATshirai** [comment]
In our case, the web app called  the  proactive install tasks about 6600 times.
Does the issue mean the service plan S1 was not enough to do that ?

**Comment by v-royavinash** [comment]
Hi @ATshirai ,

Could you please share your MS team's Id? We can connect over teams to troubleshoot the issue.

**Comment by ATshirai** [comment]
Hi @v-royavinash 
Thanks for your offer.
What do you mean the MS team's ID ?
May I ask you how to check our MS team's ID ?

**Comment by v-royavinash** [comment]
Hi @ATshirai,

Are you using Microsoft Teams?

**Comment by ATshirai** [comment]
Hi @v-royavinash 

Yes.
I'm  using Micosoft Teams.

**Comment by v-royavinash** [comment]
@ATshirai , Could you please share your Microsoft Teams alias?

**Comment by ATshirai** [comment]
Hi @v-royavinash 
Do you mean "your Microsoft Teams alias" is my Team's sign in account  and  to invite us to your team to troubleshoot  for the issue ?

**Comment by Porkai-Pandian** [comment]
@ATshirai basically we want to sync with you over Teams to troubleshoot the issue, yes share your Team's sign in account or your email

**Comment by v-royavinash** [comment]
@ATshirai Are you still facing the issue?

**Comment by ATshirai** [comment]
Hi @Porkai-Pandian 

Thank you for your offer.
We have an evaluation tenant .
From some reasons, I want  to use this tenant's mail address,  so please send a mail to the following address:
<PattiF@M365x470631.onmicrosoft.com>

I'll let you know our mail addresses in the reply.

**Comment by ATshirai** [comment]
Hi @v-royavinash 

No, not facing .
Our issue has resolved since our application administrator rebooted the web apps on that next day.
But we need to know  why this issue occured.

Application Insight reported SNAT ports ran out.  
Do you think many proactive install tasks over 6000 cause SNAT ports to run out?

**Comment by Porkai-Pandian** [comment]
@ATshirai it might be, I see you're using v4.1 of CC, please update to latest version v5.x which contains performance improvements and supports sending messages to more than 1M users.

**Comment by gsv022** [comment]
Hi @ATshirai ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by gsv022** [comment]
Hi @ATshirai ,
We are closing this issue request as we provided the necessary information.
Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
