### ISSUE TITLE
App Deployment failure - RoleAssignmentUpdateNotPermitted 

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-company-communicator#596]
Hi,
any time that I try to deploy CC receive this error about **Role Assignment Update Not Permitted**; there are some changes to do at permission level also if I'm using Global Admin to deploy but I don't remember which permission must be enabled: can suggest me about changes to do it and update troubleshooting documentation?

Regards

**Comment by v-royavinash** [comment]
Hi @faalive,
This issue normally arises when attempting multiple deployments with the same GUID. As per suggestion it is recommended to have new GUID’s generated for each deployment if it is performed in the same subscription.

![image](https://user-images.githubusercontent.com/94480537/148262700-72ebb676-f763-46ff-b1b6-32c413a07d1c.png)

![image](https://user-images.githubusercontent.com/94480537/148262719-9f677aeb-3a41-4ed5-8852-51b5e88b1b07.png)

**Comment by v-royavinash** [comment]
@faalive , Could you please confirm if the above provided details are good enough to close this issue request?

**Comment by faalive** [comment]
Perfect. Thank you for support
