### ISSUE TITLE
What does  the timestamp of Userdata show?

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#597]
May I ask what user data tables timestamp show?
Does it tell the time  when users installed the user app?

**Comment by Porkai-Pandian** [comment]
Hi @ATshirai,

Thank you for raising the query, yes to start with it'll log the time when the app is installed for the user, it keeps updated if any activity performed by author.

**Comment by ATshirai** [comment]
Hi @Porkai-Pandian ,

Thanks for your quick answer.
I got it.
