### ISSUE TITLE
Installation behind a proxy

### ISSUE THREAD

**Issue by jeff-bb** [OfficeDev/microsoft-teams-apps-company-communicator#599]
While not specific to this product per se, it wouldn't hurt to include proxy information in the troubleshooting or documentation pages.

The az cli tools will honor the environment variables of HTTP_PROXY and HTTPS_PROXY. They can be set in the PowerShell session before running deploy.ps1 with 

$env:HTTP_PROXY="http://proxy.contoso.com:8080"
$env:HTTPS_PROXY="http://proxy.contoso.com:8080"

**Comment by Porkai-Pandian** [comment]
Hi @jeff-bb,

Thanks for your suggestions, we'll review it and update the documentation accordingly.

**Comment by gsv022** [comment]
Hi @jeff-bb ,
We are closing this request and noted your suggestions. Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
