### ISSUE TITLE
Friendly Name for Export Data

### ISSUE THREAD

**Issue by TomSawyer03** [OfficeDev/microsoft-teams-apps-company-communicator#601]
Can we have a user friendly name for the export data because some of the authors are not technical people
![Screenshot 2022-01-06 184737](https://user-images.githubusercontent.com/85331597/148468432-ea3cbac3-a01b-4002-9803-889cd2c2610c.png)
.

**Comment by Porkai-Pandian** [comment]
Hi @TomSawyer03,

Thanks for your suggestion, we'll review it and take necessary action in future releases.

**Comment by Porkai-Pandian** [comment]
This feedback has been added to product backlog and will be incorporated in future releases, hence closing this issue.
