### ISSUE TITLE
Change Image - User App in Teams

### ISSUE THREAD

**Issue by JoeSMGraham** [OfficeDev/microsoft-teams-apps-company-communicator#602]
Do I have to reupload the manifest zip to update the image for the User app in Teams?

We would like to use a custom image as the thumbnail

**Comment by v-royavinash** [comment]
Hi @JoeSMGraham ,

You will have to reupload the manifest zip to use the custom image.

**Comment by v-royavinash** [comment]
@JoeSMGraham , Could you please confirm if we are good to close this request?
