### ISSUE TITLE
When message was sent through the authors app, the results show success:0, Failure:0 

### ISSUE THREAD

**Issue by Prad-dfa** [OfficeDev/microsoft-teams-apps-company-communicator#603]
Hello All,

Was hoping someone has come across a similar issue, we had deployed company communicator, and when we try sending messages to the general channel of a team the message is not sent to the team.
When we look at the status, the results say
Success: 0
Failure: 0
I don't see any errors, hoping someone has seen an issue like this before.
Thanks in advance.

Prad

**Comment by v-royavinash** [comment]
Hi @Prad-dfa,

Could you please check the app insight logs and confirm if you see any errors?

**Comment by Prad-dfa** [comment]
Hi @v-royavinash,

Here is the trace result
[query_data.csv](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/7855156/query_data.csv)
)

Regards
Prad

**Comment by Porkai-Pandian** [comment]
Hi @tyi1473,

Based on the error message provided it seems you've provided incorrect client secret, please check your configuration and update accordingly.
