### ISSUE TITLE
public access url image

### ISSUE THREAD

**Issue by Elomax31** [OfficeDev/microsoft-teams-apps-company-communicator#604]
is posible create an image repository with anonymous access but which cannot be reached from the Internet and is only accessible from the company network or from the Azure Tenant?

**Comment by v-royavinash** [comment]
Hi @Elomax31,

Yes, it can be done. The end goal is to make sure the Web bot service should be able to communicate with the app service irrespective it's being on the company network or publically available.

**Comment by v-royavinash** [comment]
@Elomax31 , Could you please confirm if we are good to close this issue?

**Comment by MrHueb** [comment]
Following up on this. Do you mind providing more information on how to enable this?

**Comment by v-royavinash** [comment]
@MrHueb, We won't be able to provide the relevant information to set up the network. However you can take help of Azure support team for the same.
