### ISSUE TITLE
Error on Sending Message

### ISSUE THREAD

**Issue by ayotwice** [OfficeDev/microsoft-teams-apps-company-communicator#605]
Hello all,

I get this error when sending messages:

Failed to prepare the message for sending:The activity function 'StoreMessageActivity' failed: "Invalid URI: The hostname could not be parsed.". See the function execution logs for additional details.

Was able to send earlier.

Anyone Encountered this?

**Comment by v-royavinash** [comment]
Hi @ayotwice,

Thanks for reaching out to us. We will check the possible reason for the above error. Meanwhile could you please confirm what is the version of app you are using?

**Comment by ayotwice** [comment]
Version 5

**Comment by v-royavinash** [comment]
Hi @ayotwice ,

This error is thrown due to an invalid Image link Url or the button link Url. Could you please re-check if the URL you are providing while creating the message is a valid one? If not, please try re-sending a message with no image and button link and check if it works?

**Comment by v-royavinash** [comment]
@ayotwice , We have provided information related to the issue. Are we good to close this thread?

**Comment by gsv022** [comment]
Hi @ayotwice ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. 

You may also always open a new issue or respond here if something does come back up. Thank you!
