### ISSUE TITLE
Upgrade v3 to v4 (in preparation to upgrade to v5)

### ISSUE THREAD

**Issue by scjohnmsft** [OfficeDev/microsoft-teams-apps-company-communicator#606]
While performing the “Company Communicator App” upgrade from v3 to v4, we did the below code update in Author’s app manifest file as per the instructions provided in the v4 deployment guide. 

"optionalClaims": {
        "idToken": [],
        "accessToken": [
            {
                "name": "upn",
                "source": null,
                "essential": false,
                "additionalProperties": []
            }
        ],
        "saml2Token": []
    },

After updating the code, we received the below error under “Token configuration”. So, we did a work around by adding “profile” permission for Microsoft Graph for Author App [but this permission is not mentioned in the deployment guide].  Looking for confirmation this workaround is sufficient.

**Comment by v-royavinash** [comment]
Hi @scjohnmsft ,

Could you please confirm are you able to send the test messages post doing the workaround?

**Comment by scjohnmsft** [comment]
Will do once I confirm with my customer

**Comment by scjohnmsft** [comment]
Ran into issues when sending a test message post the workaround "failed to update XYZABC-v4-QA application.  Error detail Another object with the same value for property identifierUris already exists.

**Comment by Porkai-Pandian** [comment]
Hi @scjohnmsft,

As confirmed over email thread, issue is resolved, hence closing this ticket, in case of any other queries, please create new one.
