### ISSUE TITLE
Any actions require for switch Azure Storage TLS certificate?

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#608]
Any actions require for switch Azure Storage TLS certificate? after the company communicator deployed.
The deployed version is v3 and v4 without customization, thanks

**Comment by v-royavinash** [comment]
Hi @rex-ma ,

Currently, the minimum TLS enforced version of Azure storage is 1.0. We are planning to enable the latest version of the TLS protocol (TLS 1.2) as suggested by Microsoft in future releases.
However as of now directly increasing the TLS version on the portal might prevent connections using a lower TLS version from connecting to this storage account and without proper testing won’t be able to answer as to what other steps have to be done to switch between the TLS versions.

**Comment by rex-ma** [comment]
Hi v-royavinash, I want to ask the concern of switch TLS certificate, e.g.: From Baltimore CyberTrust CA Root (May 2025) to the DigiCert Global G2 CA Root (Jan 2038) , thanks

**Comment by Porkai-Pandian** [comment]
@rex-ma do you've any pending queries on this issue, we've already responded to this query over email. Please let us know if you've any follow up questions, if not we'll close this issue.

**Comment by rex-ma** [comment]
Hi Porkai,

I prefer you can copy the reply in email in here for other, and I will close the issue

**Comment by Porkai-Pandian** [comment]
Here is the response, closing out the issue, please create new one in case of any other queries.

Changing the certificate authority will not create any issue in CC connecting to Azure storage.

In fact, this is recommended as mentioned in Tech Community blogs, however if any issue occurs, then request customer to reach out to their IT support team to make sure storage account is accessible to the application.

https://techcommunity.microsoft.com/t5/azure-storage-blog/azure-storage-tls-critical-changes-are-almost-here-and-why-you/ba-p/2741581
