### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by ayotwice** [OfficeDev/microsoft-teams-apps-company-communicator#609]
Hello All, 

Trying to Deploy Company Communicator but getting this error.

![image](https://user-images.githubusercontent.com/16527776/149952272-d62a0fac-8284-4a0b-9e5b-42372045dde0.png)

{
    "status": "Failed",
    "error": {
        "code": "RoleAssignmentUpdateNotPermitted",
        "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    }
}

**Comment by v-royavinash** [comment]
Hi @ayotwice ,
This issue normally arises when attempting multiple deployments with the same GUID. As per suggestion, it is recommended to have new GUID’s generated for each deployment if it is performed in the same subscription.

![image](https://user-images.githubusercontent.com/94480537/148262700-72ebb676-f763-46ff-b1b6-32c413a07d1c.png)

![image](https://user-images.githubusercontent.com/94480537/148262719-9f677aeb-3a41-4ed5-8852-51b5e88b1b07.png)

**Comment by ayotwice** [comment]
@v-royavinash How do I generate a new one? Thank you kindly.

**Comment by Porkai-Pandian** [comment]
@ayotwice you can use any online tool to generate new GUID's

**Comment by v-royavinash** [comment]
@ayotwice , Could you please confirm the closure of this issue?

**Comment by ayotwice** [comment]
Not yet, I generated with https://www.guidgenerator.com/online-guid-generator.aspx but still getting error.

**Comment by v-royavinash** [comment]
@ayotwice , Please provide more details of the error you are getting? Is it the same error you were getting previously?

**Comment by Jonroberts84** [comment]
I am having the same error, I've not used Company Communicator before - I did have a previous failed install so I've removed the resource groups, do I need to remove anything else?

**Comment by Porkai-Pandian** [comment]
@Jonroberts84 even if you delete the resource group, the value might be cached, hence we recommend using new GUID's for the values highlighted in the above screenshot so that deployment will not fail.

**Comment by v-royavinash** [comment]
@ayotwice , We are closing this request as we have provided the expected resolution steps. If you still face any further issue please request you to raise a new request.
