### ISSUE TITLE
Security Group for Approved Senders

### ISSUE THREAD

**Issue by malimal99** [OfficeDev/microsoft-teams-apps-company-communicator#610]
Feature request to allow admins to add a #security group in the Approved Senders field. Sometimes a different group manages Teams and Azure. Would be nice to delegate approved senders with a security group. 

Thank you.

#406

**Comment by v-royavinash** [comment]
Thanks, @malimal99  for your suggestion. We have taken note of it and will review the feasibility and then add it to our backlog. We will keep you updated on the progress.

**Comment by MohnJadden** [comment]
I would like to see this as an option as well.

**Comment by Porkai-Pandian** [comment]
Hi @malimal99, we're closing this request as this feedback is already added to our backlog and will be taken up in the future releases of Company Communicator based on the priority.
