### ISSUE TITLE
Error when you try to send to Office365 group

### ISSUE THREAD

**Issue by MSPFE2019** [OfficeDev/microsoft-teams-apps-company-communicator#611]
We are getting this error when you use the search box to send to Office365 Group.
Any ideas?

![CompanyComm Error](https://user-images.githubusercontent.com/57810061/150233880-7e9ca041-a0fd-45f9-87c5-514df19cb66a.jpg)

**Comment by v-royavinash** [comment]
@MSPFE2019, Could you please check if you have given Group.Read.All permission. If yes, please share the application insight logs for further investigation.

**Comment by CeciliaRavera** [comment]
I have the same problem.. and I ve given the permission

**Comment by gsv022** [comment]
Hi @CeciliaRavera ,
Could you please confirm whether the issue has been resolved or not?

**Comment by gsv022** [comment]
Hi @CeciliaRavera ,
We are closing the issue request . Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
