### ISSUE TITLE
error logging in, and url's giving me blank pages

### ISSUE THREAD

**Issue by SamerTakieddine** [OfficeDev/microsoft-teams-apps-company-communicator#614]
So I've followed step by step both guides using the powershell way and the manual deployment way with secrets. Both gave me the same issue where after uploading it to teams, it would give me a sign in option. When I click it, it opens a blank page and then teams tab gives me an error. 
Teams Tab Error: "Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists."
Any advice would be grateful because I've been trying to fix this for a week now.

**Comment by v-royavinash** [comment]
Hi @SamerTakieddine, 

Can you please check and confirm, if you have multiple instances of the Company Communicator package uploaded to the Teams?

If not, please check if the Application ID URI is added correctly under Expose an API section of the app, and also we would advise you to re-verify the steps mentioned for Set-Up Authentication.

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication

**Comment by SamerTakieddine** [comment]
> 

Thanks for the reply. I double checked all the config and URIs and everything is correct. The app loads on teams but it keeps asking for a sign in. https://gyazo.com/90a261cf68f1bcee8947a78d779241cf

**Comment by sharlotlek** [comment]
I am also getting the same error as @SamerTakieddine.

Can you kindly assist?

**Comment by SamerTakieddine** [comment]
@sharlotlek I've resolved the issue by using the onmicrosoft account's tenant microsoft gave me when creating a dev demo. It seems giving permission wasn't enough. Hope that helps.
