### ISSUE TITLE
New Field for who is sending the announcements

### ISSUE THREAD

**Issue by mhark033** [OfficeDev/microsoft-teams-apps-company-communicator#617]
As we all know, we can add different authors from different team. Example, we have an author from corporate communications department, HR department, and etc. 

We would like to suggest to add new field to know who which department is creating the announcements.

![9A461BF2-9CE9-488B-8426-8DC3319B319B](https://user-images.githubusercontent.com/61768253/151077508-129374f2-77a5-4653-8bac-20771a0842c0.png)

we would like also to see it here in the red box

![C6D74185-4469-4065-9B49-55F648334F66](https://user-images.githubusercontent.com/61768253/151077630-43b9f2b6-7841-4992-ba65-03fd35c01b6f.jpeg)

**Comment by Porkai-Pandian** [comment]
Hi @mhark033,

Thanks for the suggestion, we'll review your changes and added it to backlog to be implemented based on the priority in future releases.

**Comment by Porkai-Pandian** [comment]
This has been added to product backlog and will be taken up in future releases, closing this issue.
