### ISSUE TITLE
"Send to General channel" and "Send in Chat to members" won't populate Team names

### ISSUE THREAD

**Issue by gavinjhunter** [OfficeDev/microsoft-teams-apps-company-communicator#619]
I've finished deploying and the "Send in chat to everyone" and "Send in chat to members of the following M365 groups, Distribution groups or Security groups" functions work perfectly fine.

The top 2 options for either "General channel" or "chat to members of the following teams" does not populate, even for teams which the logged in user is in (example below).

![image](https://user-images.githubusercontent.com/59952908/151744653-22202156-b05b-4c2e-82a0-4b4774232920.png)

Any ideas of where to look to diagnose?

**Comment by v-royavinash** [comment]
Hi @gavinjhunter ,

If the user bot is added to the Teams channel, then only specific team names will be shown in the dropdown.

Could you please follow the below steps, 

- There is a table named "**TeamData**". Can you check if the table has data related to teams information? 
- If the table does not have any data. Can you remove the app from the Team channel and re-add it to the respective team.
- Refresh the "**TeamData**" table and verify if it has populated the specific Team data. 

Let me know if these steps worked?

**Comment by siddiquiaslam** [comment]
> I've finished deploying and the "Send in chat to everyone" and "Send in chat to members of the following M365 groups, Distribution groups or Security groups" functions work perfectly fine.
> 
> The top 2 options for either "General channel" or "chat to members of the following teams" does not populate, even for teams which the logged in user is in (example below).
> 
> ![image](https://user-images.githubusercontent.com/59952908/151744653-22202156-b05b-4c2e-82a0-4b4774232920.png)
> 
> Any ideas of where to look to diagnose?

Hi @gavinjhunter,

You need to install user app in all Teams; which you want to be available in author app. In other words, teams where user app is installed, will be available in author app.

Thanks.

**Comment by gavinjhunter** [comment]
Thanks @siddiquiaslam ! That was the issue. I'd somehow missed the App needed to be installed individually per-Team. I'll update our documentation to call it out specifically :)
