### ISSUE TITLE
Source control deployment failed. The resource operation completed with terminal provisioning state 'Failed'

### ISSUE THREAD

**Issue by jeff-bb** [OfficeDev/microsoft-teams-apps-company-communicator#621]
Deploy from Powershell failed.

Snip from the logs --

    "operationName": {
        "value": "Microsoft.Web/sites/sourcecontrols/write",
        "localizedValue": "Update Web App Source Control Configuration"
    },
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "properties": {
        "statusCode": "Conflict",
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceDeploymentFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\"}}",

**Comment by v-royavinash** [comment]
Hi @jeff-bb ,

Navigate to the deployment center and check the deployment status for the failed resources in the Azure portal. Check the error logs to understand why the deployment failed.

In most of the scenarios you may need to either redeploy the application (using scripts) or sync manually.

You can manually fix the issue by following the below steps:

- 	Go to the Azure portal --> Resource group which got created--> App Service
- 	Go to the "Deployment center" section of the app service that failed to deploy.
- 	Click on "Sync" to restart the deployment.

![image](https://user-images.githubusercontent.com/94480537/152098197-618b3bc3-b48b-4fca-ae6b-c5edc9664663.png)

- 	Post successful deployment of app service the Status will change as “Success”.
- 	If you don’t see the Git URL mapped to app service, then please add External Git repo URL and then click on Sync.
- 	Repeat the same steps for the failed Azure functions as well

**Comment by jeff-bb** [comment]
Gateway timeout was the only other errors I could find. I ended up removing the Resource Group, starting over (and getting the same error). Ultimately, I removed the Resource Group and created it under a different name and it went through without issue.
