### ISSUE TITLE
Change Bot Display Name

### ISSUE THREAD

**Issue by jeff-bb** [OfficeDev/microsoft-teams-apps-company-communicator#622]
While the application name in Teams has been customized via the manifest and displays correctly, the Display Name of the bot contunes to show "Company Communicator" or "Company Communicator (Authors)". I've confirmed the bot display name is our modified value for both Web App Bot in Azure at Web App Bot -> Bot Profile -> Display Name.

Where is the Bot Display Name changed? Can it be changed after deployment?

**Comment by Porkai-Pandian** [comment]
Hi @jeff-bb,

Thank you for reaching out to us, please delete the uploaded manifest file and update short name in users manifest, SME manifest and deploy the updated manifest in Teams admin center.

![image](https://user-images.githubusercontent.com/87537966/152034823-b541388f-f514-4919-b27d-4bb0b3b64399.png)

**Comment by jeff-bb** [comment]
This changes the application name, yes. but it doesn't change appear to change the name of the bot sending the messages. They continue to show with the original manifest name.

I've blacked out identifying information in this screenshot, but as you can see the icon and app name have accepted the changes fine, but the messages themselves continue to use the original name. The icon appears to just be a caching issue as some will show the updated icon and some won't.

I'm incrementing the version of the manifest and re-uploading it; should I be deleting the app and re-adding it?

![image](https://user-images.githubusercontent.com/38505668/152036166-14b91b9b-96a9-423f-b00a-64861f0d8690.png)

**Comment by Porkai-Pandian** [comment]
Yes @jeff-bb delete the app from Teams and re-upload the updated manifest file, also refer to [URL ](https://answers.microsoft.com/en-us/msteams/forum/all/clear-cache/0810ce4f-af14-4269-b01f-adc89a0af4c4)to clear the Teams cache

**Comment by jeff-bb** [comment]
Thanks for assistance. This is a great documentation / FAQ opportunity on how to rename the bot post deployment.

**Comment by 298029lkk** [comment]
Hmmmm, I tried it and still no success. And this method is more difficult to deal with, we can't ask most users to do this operation of clearing the cache
