### ISSUE TITLE
Use Linux in App Service Plan over Wiindows

### ISSUE THREAD

**Issue by siddiquiaslam** [OfficeDev/microsoft-teams-apps-company-communicator#623]
Hi

Is it possible to use Linux over Windows in App service plan?

Thanks.

**Comment by Porkai-Pandian** [comment]
Hi @siddiquiaslam,

Thank you for raising the query, the default app service plan for CC deployment is Windows, if you want to use Linux, then you need to customize the ARM template to deploy it under Linux and go for fresh installation with the customized version.

**Comment by v-royavinash** [comment]
Hi @siddiquiaslam ,

We are closing the request as we have provided the required inputs for the query raised. Incase of any further assistance please raise a new issue.
