### ISSUE TITLE
Adaptive card addition in Teams 

### ISSUE THREAD

**Issue by Sheshank-TCS** [OfficeDev/microsoft-teams-apps-company-communicator#624]
Hi Team,

I have deployed Company Communicator 5.0 in my environment. I need to enable Custom message and Adaptive cards.
Will need a low level details and steps to enable this. I see there are templates available in Github but how to enable in the first place.
Do I need to edit code to make custom image upload option and Custom message option in New message window.
Below is the reference links I went through but its not clear how to enable those options. 
https://www.youtube.com/watch?v=wDVVbiaNbjk
https://tech-peanuts.com/2021/06/24/more-company-communicator-features/ (This link also enable option to add multiple link and button)

I am also learning this let me know if you need any other details.

![image](https://user-images.githubusercontent.com/71570629/152543224-576de663-ff1f-4b58-a3b8-01b27b6ffc30.png)
![image](https://user-images.githubusercontent.com/71570629/152544226-2960d92e-2980-43fb-b989-521a0dba6f4a.png)

**Comment by v-royavinash** [comment]
Hi @Sheshank-TCS,

We don't provide feature to upload the image and custom message creation. The original Company communicator template can be customized to add these features however we won't be able to provide support for the customized version of the template.

**Comment by Sheshank-TCS** [comment]
Hi @v-royavinash,

I also see the features like using Bold Italics and URL in message area which are through adaptive cards and are mentioned on Github can you assist with that how can those be enabled.

Also to get it customized who can assist as the Youtube link which I shared is from Microsoft Development team only.

**Comment by Sheshank-TCS** [comment]
@Mikhail2k15 Can you check and assist on this ?

**Comment by cristianoag** [comment]
Those features cannot be enabled in the original CC. Those are part of a community effort to improve features and run in a parallel version. If you want to use those features you need to use the community version or perform the same changes on the original version code.

**Comment by v-royavinash** [comment]
@Sheshank-TCS , We won't be able to help for the customization on top of company communicator. If you have any query related to the original app please let us know.

**Comment by v-royavinash** [comment]
@Sheshank-TCS , We are closing the issue request as we won't be help for the customized version of the CC. If you have any query related to the original app please raise a new request.
