### ISSUE TITLE
What do we need to do for Classic Application Insights retirement ?

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#625]
I found the following message in the Application Insights page of our Company Communicator's Web app:
"Classic Application Insights is deprecated and will be retired in February 2024"

![20220207-1](https://user-images.githubusercontent.com/77769064/152769581-d25cb3d3-c294-4266-b972-278234e58a30.PNG)

What do we need to do for this ?

**Comment by Porkai-Pandian** [comment]
Hi @ATshirai,

This is announcement from Microsoft to retire classic App insights in 2024 which is 2 years from now, this is not related to CC app in specific, depending upon the new releases of App insights, CC will be updated in future releases as well. No action item from your side on the same.

**Comment by Porkai-Pandian** [comment]
Closing this issue as there is no action item on this, please open a new issue in case of any other queries.
