### ISSUE TITLE
Popup Toast Notification Links To Activity Feed

### ISSUE THREAD

**Issue by GrantOliasani** [OfficeDev/microsoft-teams-apps-company-communicator#627]
Hello,

In the latest version V5 - the popup toast notification generated from a Company Communicator message in chat does not link correctly to the app or chat with the bot. When a user clicks on the popup - it takes them to their latest activity feed notification (instead of the chat with the CC bot). I have reproduced the error on the web and desktop. I have noticed some users on the GitHub Issues page indicated the notification takes them to the App store.

**Comment by Porkai-Pandian** [comment]
Hi @GrantOliasani,

Thank you for raising the query, can you please share a screenshot of the issue which you mentioned above for us to get more context.

**Comment by GrantOliasani** [comment]
User clicks notification from Company Communicator:
![3a98a31f-326c-462e-b6e2-4a6798b5f222](https://user-images.githubusercontent.com/6586170/152899928-f3a86ae4-5e97-4784-8d6b-b6857b45f249.jpg)

Takes them to activity feed with latest activity highlighted
![a3e4519d-388f-4037-ac87-32afaed96603](https://user-images.githubusercontent.com/6586170/152899909-6a502cfd-fa86-4930-9ff6-06c2e53054d6.jpg)

**Comment by GrantOliasani** [comment]
@Porkai-Pandian I assume it is supposed to take them to the chat conversation with the bot instead of the activity feed.

**Comment by v-royavinash** [comment]
@GrantOliasani , We will check on the issue and will keep you updated.

**Comment by GrantOliasani** [comment]
Hello @v-royavinash, any update on this?

**Comment by v-royavinash** [comment]
Hi @GrantOliasani , We have taken a note of the suggestion. Even we observed that the pop-up notification is taking to Activity feed. We are suspecting it as a bug and post review will provide the fix (if issue is with code). We won't be able to commit for any ETA.

**Comment by Mikhail2k15** [comment]
It is a Teams Platform issue, not CC.

**Comment by RobWood1** [comment]
Is there any update on when this issue might be resolved? We're looking to roll out CC shortly but have also encountered the same issue.

**Comment by gsv022** [comment]
This issue has not been observed in the latest version of CC. Hence we are closing it.
