### ISSUE TITLE
Messages get stuck in queue

### ISSUE THREAD

**Issue by marc-faure** [OfficeDev/microsoft-teams-apps-company-communicator#628]
Hi,
I have deployed the solution in my personal Tenant, with admin access. I can see 2 issue when i try to send messages :
- messages get stuck in queue for 24 hours before being sent. I don't know why
- Sending report always shows 0 recipient and 0 failure after the message have been sent (see screener). Actualy, the message is not delivered to recipients ...
![Untitled](https://user-images.githubusercontent.com/94625972/153192358-858b8328-112e-4683-9efa-983de03caa20.png)
![Untitled2](https://user-images.githubusercontent.com/94625972/153192510-0a473c84-4e75-43b5-90e2-586bfe1286a9.png)

**Comment by v-royavinash** [comment]
@marc-faure  There can be multiple reason for the issue. Could you please try the below steps and let us know if it works?

- Open Azure portal 
- Navigate to respective resource group
-  Open “******-prep-function” azure function
- Click on “Restart” and wait for few minutes.
- App should be able to pick up existing messages in queue to send or else try to send new message.

**Comment by marc-faure** [comment]
Hi @v-royavinash 
yes, i saw the tips in the troubleshoot. I did it several times and i just did it again. It changes nothing (old messages still in queue, new one as well).

**Comment by marc-faure** [comment]
@v-royavinash 
I did it step by step. There was 7 messages and none in send queue. I received all in the prep queue one by one, sync and restart the function ... and still have the issue 
![Untitled](https://user-images.githubusercontent.com/94625972/153249023-47510333-c23f-4449-a987-5183447dc1ff.png)
:

**Comment by v-royavinash** [comment]
@marc-faure , We acknowledge your response. We are checking for the other possible fix and will keep you posted.

**Comment by gsv022** [comment]
Hi @marc-faure ,
We would request you to please re-deploy the application as we suspect there are some configuration issues.

**Comment by gsv022** [comment]
Hi @marc-faure ,
Could you please confirm whether the issue has been resolved or not?

**Comment by gsv022** [comment]
Hi @marc-faure ,
We are closing the issue request. Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
