### ISSUE TITLE
Deployment Unsuccessful

### ISSUE THREAD

**Issue by Tones-Bates** [OfficeDev/microsoft-teams-apps-company-communicator#630]
Hi Team, 
I am having trouble with deploying to Azure.  I have attached the error and included the log.  I have tried changing the .json file still no luck.  Initially I have the change the name of the app as it was too long.  Here are the logs and some screenshot which seem important.

[logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-stickers/files/8037536/logs.zip)

![image](https://user-images.githubusercontent.com/99375713/153324063-2b17ffe5-45b6-4f26-a4df-7885b1810b34.png)
![image](https://user-images.githubusercontent.com/99375713/153323965-2065f225-3656-423c-a13e-4ade374890d0.png)
![image](https://user-images.githubusercontent.com/99375713/153324966-2db73bcd-896f-4ea1-afd6-3a3118b0d7fe.png)

Can you please let me know where I going wrong.

Cheers 

Tony

**Comment by v-royavinash** [comment]
@Tones-Bates  ,

You might have attempted multiple deployment with same GUID, as per suggestion it is recommended to have new GUID’s generated for each deployment if it is performed in same subscription.

![image](https://user-images.githubusercontent.com/94480537/152844424-0230c65f-d7cb-452a-b847-bf0ab18464ed.png)

![image](https://user-images.githubusercontent.com/94480537/152844440-fd22a975-bd59-4aa6-958b-feec36501422.png)

**Comment by v-royavinash** [comment]
Hi @Tones-Bates ,

We are closing the issue request as we have provided the required resolution steps. Incase of any further assistance please raise a new issue.
