### ISSUE TITLE
Are users notified of app installation after sending message when proactiveAppInstallation is enabled?

### ISSUE THREAD

**Issue by bahTeams** [OfficeDev/microsoft-teams-apps-company-communicator#631]
Hello Team,
Are users notified on their teams of app installation after sending message to all organization employees when proactiveAppInstallation is enabled ?
Thanks in advance

**Comment by v-royavinash** [comment]
Hi @bahTeams , Proactive installation will install the user app automatically when author sends the messages. For installation the user won't get any notification, but user can see/find the company communicator user app in MS Teams. Once author sends the message the user will receive the message.

**Comment by bahTeams** [comment]
> Hi @bahTeams , Proactive installation will install the user app automatically when author sends the messages. For installation the user won't get any notification, but user can see/find the company communicator user app in MS Teams. Once author sends the message the user will receive the message.

Thanks @v-royavinash  for your reply.
