### ISSUE TITLE
Private channels: will this be possible?

### ISSUE THREAD

**Issue by Siyaho** [OfficeDev/microsoft-teams-apps-company-communicator#632]
Asking for a client: is it possible to send messages to a private channel or is it (and will it stay) only for the general channel?

**Comment by v-royavinash** [comment]
@Siyaho  We don't provide support to send message to private channels.

**Comment by Siyaho** [comment]
Got it, thank you. Any plans to do so, in the (near) future?

**Comment by v-royavinash** [comment]
Hi @Siyaho ,

We don't have any planned backlog for private channels. We will review your request/suggestion and mark it as a feature/functionality request.

**Comment by v-royavinash** [comment]
Hi @Siyaho, This feedback is added to our backlog and will be incorporated in future releases of Company Communicator, hence closing this issue.
