### ISSUE TITLE
Company Communicator limits

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-company-communicator#634]
Hi, I'm sending every week a message to more than 100k users, CC is supported for that? Which strategy is suggested in this case?

Regards

**Comment by v-royavinash** [comment]
@faalive , Which version of the CC app you are using? The latest version support up to ~1 million messages.

Let us know if you are facing some issue in sending 100k messages?

**Comment by faalive** [comment]
Actual version is 4.1.5

**Comment by Porkai-Pandian** [comment]
@faalive 4.1.5 supports sending 100k messages, however we heard from users that they see slowness once the records keep piling in the Azure Storage. Would suggest upgrading to latest version v5.0 so that you'll face any performance issues.

**Comment by gsv022** [comment]
Hi @faalive ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.

 Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. 

You may also always open a new issue or respond here if something does come back up. 
Thank you!
