### ISSUE TITLE
What actions are require when deploy the 2nd or 3rd instance of Company Communicator in the same tenant?

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#635]
What actions are require when deploy the 2nd or 3rd instance of Company Communicator in the same tenant?

**Comment by v-royavinash** [comment]
@rex-ma ,
Follow the below steps to deploy the second instance of company communicator in single-tenant:

- Register Azure AD Applications as mentioned in Step 1.
- While doing ARM Template deployment which is given in Step 2, update “User App External Id” with following different value example: 148a66bb-e83d-425a-927d-09f4299a9275
- And it is recommended to have new GUID’s generated for each deployment if it is performed in the same subscription.

 
![image](https://user-images.githubusercontent.com/94480537/153810732-0b756f13-6746-4b17-b201-ca4f04bf209c.png)

![image](https://user-images.githubusercontent.com/94480537/153810740-5bf58f3d-3338-4c2e-94d1-22d00d0f494d.png)

 
Proceeding with remaining steps 3, 4

- In Step 5, Please update user app manifest id from 148a66bb-e83d-425a-927d-09f4299a9274 to 148a66bb-e83d-425a-927d-09f4299a9275 and please update author app manifest id from 1c07cd26-a088-4db8-8928-ace382fa219f to 1c07cd26-a088-4db8-8928-ace382fa219d (Different value)
and proceed with the remaining steps as mentioned in deployment guide.

If you miss updating “User App External Id” in step 2, you can update the value in the following sections:

- Open second instance azure resource group -> Open App service -> Configuration (in left navigation) -> update “UserAppExternalId” value to 148a66bb-e83d-425a-927d-09f4299a9275 -> Click on “ok” -> Click on “save” and restart app service.
- Open second instance azure resource group -> Open function app which is ending with “-prep-function”-> Configuration (in left navigation) -> update “UserAppExternalId” value to 148a66bb-e83d-425a-927d-09f4299a9275 -> Click on “ok” -> Click on “save” and restart function app.

And make sure user manifest id change as mentioned above.

**Comment by rex-ma** [comment]
Thanks v-royavinash,

1. May I confirm the 148a66bb-e83d-425a-927d-09f4299a9275 and 1c07cd26-a088-4db8-8928-ace382fa219d (New values) are random for both author and user app? may I replace them by other GUID?

2. If I choose v4, may I know what is the different steps compare to your reply?

3. I can see the new user app ID apply in App service and prep-function in your reply. But how about new author app ID? just apply it in manifest?

**Comment by v-royavinash** [comment]
@rex-ma  , Please find the my comments **inline**, 

May I confirm the 148a66bb-e83d-425a-927d-09f4299a9275 and 1c07cd26-a088-4db8-8928-ace382fa219d (New values) are random for both author and user app? may I replace them by other GUID?   - **Yes that correct**.



If I choose v4, may I know what is the different steps compare to your reply? - **Our recommendation will be to deploy the latest version. For v4 also the steps remains same, the GUID fields might differ.**

I can see the new user app ID apply in App service and prep-function in your reply. But how about new author app ID? just apply it in manifest? - **Yes correct**

**Comment by rex-ma** [comment]
Thanks for detail reply
