### ISSUE TITLE
Can we set the app service plan in cc app to free version when the app is not using in a month?

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#636]
Can we set the app service plan in cc app to free version when the app is not using in a month? and set it back to S1 a month later when use?

**Comment by v-royavinash** [comment]
@rex-ma ,
The custom deployment currently has the support of Basic, Standard, and Premium plans.

![image](https://user-images.githubusercontent.com/94480537/153811964-3779ea36-5e68-4163-857e-74e07e5d54c7.png)

**Comment by rex-ma** [comment]
Hi v-royavinash,

Just want to confirm the app will still work after we modify the plan basic? or after modify from basic to standard?

Thanks

**Comment by v-royavinash** [comment]
Yes @rex-ma  the app will work. Are we good to close this query request?

**Comment by rex-ma** [comment]
Hi v-royavinash,

Which option below that you mean it will work?
- Stay in basic plan?
- After from basic plan back to standard plan?

But the way, if stay in basic plan can work, do we still have to deploy the app with S1 at the beginning?

Regards,
Rex

**Comment by v-royavinash** [comment]
Hi @rex-ma , We would not recommend to downgrade to Basic plan as there are limitation to the storage provided in Basic plan. Ideal recommendation is to stay with the Standard plan. We are closing this issue request as we have provided the required inputs. Please raise a new issue in case of further assistance.
