### ISSUE TITLE
Does Company Communicator use Java v12 SDK？

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#638]
Hi, team.

I'd like to know if Company Communicator v4.1 use Java v12 SDK.
Please let me know if Company Communicator v4.1 use the following Java SDK version to access the Azure Storage.

Blob SDK(azure-storage-blob): 12.0 - 12.6.1
Data Lake  SDK (azure-storage-file-datalake): 12.0 - 12.1.2
Files SDK(azure-storage-file-share): 12.0 - 12.4.1

I hope you will be able to provide the information.

**Comment by Porkai-Pandian** [comment]
Hi @ATshirai,

Thank you for raising the query, no Company Communicator is using Java SDK to connect to Azure storage, the app is developed using Microsoft .NET Framework and this is used to connect to the storages. Please let us know if you've any follow up queries.

**Comment by ATshirai** [comment]
Hi @Porkai-Pandian

Thank you for your reply.
That's exactly what I wanted to ask.
