### ISSUE TITLE
Issue with Company Communicator Admin App

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-company-communicator#639]
Two Company Communicator admins are unable to access Admin app (V3.0) and either getting blank screen (desktop client) or error (web client).
We have cross verified the below points
1.	Both the users are admins of the Teams channel
2.	Both the users email address is present in UPN list
Note : The users are accessing MS Teams via PC on demand(EY provided virtual machine)
Full troubleshooting details in document attached

[Company Communicator Admin App Issue.docx](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8072586/Company.Communicator.Admin.App.Issue.docx)

**Comment by Porkai-Pandian** [comment]
Hi @EYSue,

Thank you for raising the issue and provide the logs, can you please provide few more details to troubleshoot the issue,

- Were the users able to login earlier?
- What version of the application are you using, when you say Admin app (V3.0)?

**Comment by EYSue** [comment]
Hi Porkai

Please see my answers below in red.

Also copying in the EY project team @Lokanath ***@***.***> and @Anjaly ***@***.***>

Regards

Sue

**Comment by gsv022** [comment]
Hi @EYSue ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.
As you have already logged another issues #688 and #702. We are closing this issue.
