### ISSUE TITLE
Can't logon to Company Communicator Admin on Teams

### ISSUE THREAD

**Issue by Jonroberts84** [OfficeDev/microsoft-teams-apps-company-communicator#640]
I've been through deployment, uploaded the custom app - then I get this error when trying to log on to the tab..

1. Almost there - we need to ask for additional permissions. You should only need to do this once for Company Communicator (Authors).
2. Something went wrong - we couldn't sign you in. If this error persists, contact your system administrator and provide the error code CAA20004.

AADSTS650057 - Invalid Resource.
The client has requested access to a resource which is not listed in the requested permissions in the client's application registration.

**Comment by bevbev3** [comment]
Hi, Im getting the same error this morning.  Have deployed this successfully previously. Have checked all permissions on the app to be ok, and in the app registrations are the same as the documented steps. Please help

**Comment by Jonroberts84** [comment]
Glad this isn’t just me, desperately need to deploy this!
________________________________

**Comment by Porkai-Pandian** [comment]
Hi @Jonroberts84,

Thank you for raising the query and sharing the error message that you received, the error that you see mostly occurs when the authentication set up and the permissions for the Graph App are not provided correctly. Please double check if you've followed the steps mentioned in the guide and provided correct permissions.

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication

**Comment by Jonroberts84** [comment]
I ran the automated powershell script, should I be doing manual steps as we’ll?
________________________________

**Comment by bevbev3** [comment]
Thanks for directing me to the correct place to look. I review the documentation again, and it looks like I missed a step, where it said to repeat a group of step.  Its working now for me
![step3](https://user-images.githubusercontent.com/99768318/154168921-638fa6f4-3e11-4d7b-ad0f-364b4ef830dd.JPG)

**Comment by Porkai-Pandian** [comment]
Thanks @bevbev3 for the confirmation, glad the issue is resolved.

@Jonroberts84 will check on it related to PS deployment and get back to you

**Comment by sbrile** [comment]
Incase anyone else runs into this problem, the powershell install script did not correctly set my scope and authorized client applications.  I had to manually do some of the steps in the authentication section after running the powershell deploy.
