### ISSUE TITLE
Unable to select Teams/Users from Communicator Authors App

### ISSUE THREAD

**Issue by Jonroberts84** [OfficeDev/microsoft-teams-apps-company-communicator#644]
Can anyone help me with this? I've got the apps (Author and User) installed in 2 teams, but neither are listed, I've applied all API permissions to Company Communicator App - do the same need to be applied to Author and User apps, I'm sure I'm just missing a step somewhere.

![image](https://user-images.githubusercontent.com/23524426/154354038-71ac9243-8c85-42e9-915d-6b271a8d0141.png)

I was able to find a mail enabled security group selecting the 4th option and sent a test message to the group but it failed, I found this error in app insights.

Failed to send message. Exception message: Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'

**Comment by Porkai-Pandian** [comment]
Hi @Jonroberts84,

Thank you for raising the query, no you don't need to provide the permissions to author and user apps as long as you've provided the permissions to CC app. I've you uploaded the user app to the Teams channel where you wanted to access the app. Regarding the forbidden error you're getting, please check if you've the necessary permission to send the messages to the DL you selected. Also please verify if your organization does not block any custom apps

**Comment by Jonroberts84** [comment]
I've added the app to our tenancy so that any user can install it, so it shouldn't be blocked. All permissions are set correctly in the main app - what would cause teams and users not to show?
________________________________

**Comment by Jonroberts84** [comment]
I also get this issue when trying to export the logs

![image](https://user-images.githubusercontent.com/23524426/154435624-9748a5c2-7b7b-4c35-b5e9-c9e35b7e0c25.png)

**Comment by Jonroberts84** [comment]
My fault again - I had the AuthorID not the UserID in the user teams app...
