### ISSUE TITLE
Issue with sending to M365 groups, Distribution groups or Security groups feature 

### ISSUE THREAD

**Issue by SammiRasha** [OfficeDev/microsoft-teams-apps-company-communicator#647]
Hi team,

Got quite a problematic issue which needs solving. Seems to be happening to a lot of people I have spoken to and I have tested it myself and can confirm there is a bug of some sort. Essentially, even though we have granted the correct permissions **(with admin consent)** we cannot use the option to send a message to the O365 groups. It shows the same "Permissions needed. Ask your IT admin to enable this option for you" warning message that is normally visible if you haven't yet granted admin permissions.

I know people with CC installed on their demo tenants and it was working fine and randomly this issue came to them and won't go away. Customers I have deployed to recently also have this issue. 

**To preface this before you ask**: yes I have permitted admin consent and I have followed the guide and added the correct permissions, screenshot below of my permissions. And yes, I can confirm this is in the graph app, not the author or the bot app. For me, I can send 'messages to general chats', 'in chat to members of a team' and 'in chat to everyone'. It is just that o365 groups and distribution lists feature which does not work. The screenshots below are the latest v5 version of Company Communicator,.

![image](https://user-images.githubusercontent.com/10238857/155231926-22728e05-d02d-4910-b2b5-485d8a63a1f2.png)

![image](https://user-images.githubusercontent.com/10238857/155231293-0499362e-e01d-4a22-81c4-57b0f82c643a.png)

This seems to be happening with the Cristiano fork build also (latest build)- Just deployed it with a customer and I saw they had this issue. 

I remember reading an issue thread (cannot find it) where someone suggested they had this issue with the certificate deployment but when they deployed via Powershell they did not have this issue. I have tried to test this claim myself but the Powershell script will not deploy correctly for me -- I will raise a separate issue for that. I will go away and try Powershell some more and let you know of any findings but for now this needs to get looked at.

**Comment by Porkai-Pandian** [comment]
Hi @SammiRasha 

Thank you for raising the query and providing detailed information on this issue and the steps you've taken to make sure everything is correct. I can see you've not included GroupMember permissions as mentioned in the [Wiki](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app) and rather added Group permissions. Can you please add this permission as this is needed to read the distribution groups of the organization? Screenshot of the correct permissions below for reference,

![image](https://user-images.githubusercontent.com/87537966/155237157-ba71dc9a-adbb-4347-8145-29422d422336.png)

**Comment by SammiRasha** [comment]
Hi @Porkai-Pandian,  so the reason why I put group.read.all is due to the screenshots in the deployment guide, they are outdated and have been taken from the v4 guide. These need to be updated - can confirm that when I changed them to groupmember.read.all this fixed it for me. 

However - I have a colleague who also has this issue. They have the correct permissions (photos posted below). He is on v5 also

![09b82283-d60c-4111-b30f-4709d4e92509](https://user-images.githubusercontent.com/10238857/155312705-c4a5e4ff-5ab5-47c4-82a4-1d31924d8cec.jpg)

![8ca5e2b7-25f1-44bc-ac06-8ce36c5e979c](https://user-images.githubusercontent.com/10238857/155313670-34743fda-f5ce-4bc9-90c8-b40b3db18399.jpg)

**Comment by SammiRasha** [comment]
Seems like V4 also has this issue. Checked the permissions on a colleagues tenant -- they had the group.read.all (which was what they were meant to put according to the V4 guide) but still didn't have permission. I tried now to add the groupmember.read.all permissions also, and it still wouldn't work

**Comment by v-royavinash** [comment]
Hi @SammiRasha , Could you please add the below permission as well.

![image](https://user-images.githubusercontent.com/94480537/155356102-a17752c7-b5db-48e9-a03a-3df3efaa0e4d.png)

Also after adding the permission it might take up to 48 hrs. to reflect. Request you to please wait for 48hrs and then try login to MS  Teams web version and check if the 4th option is enabled or not.

**Comment by SammiRasha** [comment]
@v-royavinash thanks for your reply.

Will try this with both the v4 and v5 versions and update the issue tomorrow

**Comment by SammiRasha** [comment]
@v-royavinash Tried this and it still did not work, issue is still there

**Comment by SammiRasha** [comment]
Found the error -- in v4 in the app service there is the author secret, user secret (which makes sense as those are the two app registrations generated during deployment) but there is also an Azure Ad secret. 

It turns out that the clientID for the AzureAd, in the app service, is the same as the author ID but the secret was not. To fix this, simply replace the author secret into the AzureAD secret to match, save and restart the app service.
