### ISSUE TITLE
teams  Incoming Webhook usage issue

### ISSUE THREAD

**Issue by ShimingLee** [OfficeDev/microsoft-teams-apps-company-communicator#648]
I want to use incoming Webhook to notify a channel on teams and @mention someone. 
I implemented sending messages to a channel from an external application, but how can I mention someone, I haven't found a solution. 
Anybody know how to do that?

**Comment by Porkai-Pandian** [comment]
Hi @ShimingLee,

Thank you for raising the query, do you've any queries related to Company Communicator app, if so can you please elaborate more on your ask?

**Comment by ShimingLee** [comment]
Thanks for your response. If I want to ask some API questions about Teams where can I ask them. @Porkai-Pandian Let me know if you know. Thank you

**Comment by gsv022** [comment]
Hi @ShimingLee ,

We are closing the issue request as the query seems more relevant to teams not of CC .

Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
