### ISSUE TITLE
403 user blocked the conversation with the bot

### ISSUE THREAD

**Issue by ajaifeanyi** [OfficeDev/microsoft-teams-apps-company-communicator#650]
Hi everyone, I deployed CC, uploaded user and author manifest file and everything was been working very fine.
Starting from yesterday, when I send a communication using CC everyone gets it but just for a user. I downloaded the zip and extracted the excel file, the error I saw was "403 user blocked the conversation with the bot"

Any idea to what that could cause the error.

**Comment by v-royavinash** [comment]
Hi @ajaifeanyi ,
The permission policy set for the particular user is blocking the company communicator user bot. Please update the policy to allow the Company communicator user app and try re-sending the message. Lets us know if this resolved the issue.

**Comment by v-royavinash** [comment]
Hi @ajaifeanyi ,
The permission policy set for the particular user is blocking the company communicator user bot. Please update the policy to allow the Company communicator user app and try re-sending the message. Lets us know if this resolved the issue.

**Comment by v-royavinash** [comment]
Hi @ajaifeanyi , We closing this request as we have provided the resolution response. If you face any further issue please raise a new request in GitHub.
