### ISSUE TITLE
Error doing migration from v4 to v5

### ISSUE THREAD

**Issue by SammiRasha** [OfficeDev/microsoft-teams-apps-company-communicator#651]
Deployed v4 via powershell, works fine. Tried to do the migration from v4 to v5 and I get this error: "There was a conflict. Conflict with existing ScmType: ExternalGit" during deployment. Screenshot provided below

![image](https://user-images.githubusercontent.com/10238857/155573900-54a71c6a-eab7-44c8-b04b-518e1367116c.png)

Tried to sync the function apps and app service and re run deployment, still gives the same error

**Comment by v-royavinash** [comment]
Hi @SammiRasha , 

We could you there are multiple issues you are experiencing in deploying the company communicator. We have reached out to you over MS Teams for further details of the issue.

**Comment by gsv022** [comment]
Hi @SammiRasha ,
We are closing this issue as we have provided enough inputs to this issue. If you face any issue with company communicator please raise a new issue for further assistance.
