### ISSUE TITLE
Endless loop after adding the author app to a team

### ISSUE THREAD

**Issue by SammiRasha** [OfficeDev/microsoft-teams-apps-company-communicator#653]
Deployed v5 via powershell -- everything deployed fine and no errors in the script. Added the user app to the org catalogue without issues, but upon adding the author app to a team it throws an endless error that goes between the two screenshots below

![88b837c1-e7fd-4bea-8d44-402ca84a2524](https://user-images.githubusercontent.com/10238857/155720154-b86ccd8f-7b88-436f-8bcd-a64c6f48591f.jpg)

![00c0093f-fb14-48c5-bb2c-49e772c6f3fe](https://user-images.githubusercontent.com/10238857/155720165-0e322a10-6f09-4e03-9968-d09b967aecee.jpg)

I can confirm that permissions in the graph ad app are already granted as admin. Tried going through that loop with a global admin account and it still happens. Tried it both as a customised app upload and having uploaded it to the org catalogue, still the same issue

**Comment by v-royavinash** [comment]
Hi @SammiRasha ,

Could you please check if the Application ID URI is added correctly under Expose an API section of the graph app registration? 

If yes, we would recommend to deploy the company communicator manually and if the issue still persists the we can connect over MS Teams to troubleshoot the issue over call.
