### ISSUE TITLE
API Group.read.all Permission Issue

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-company-communicator#654]
I am in the process of upgrading Company Communicator and the Service Owners are pushing back on approving the Group.read.all API permission. We are trying to move away from granting these permissions as it allows access to all Group connected content (including documents in about 500K+ global underlying SharePoint sites). I need to know exactly why these permissions are needed by Company Communicator and would Groupmember.read.all permissions allow the same functionality?

**Comment by v-royavinash** [comment]
Hi @EYSue  In Company Communicator V5 **Group.Read.All** permission is not required. Only below permission is to be added. Please refer the [WIKI](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide) for more details.



Delegated permissions
- GroupMember.Read.All
- AppCatalog.Read.All

Application permissions

- GroupMember.Read.All
- User.Read.All
- TeamsAppInstallation.ReadWriteForUser.All

**Comment by v-royavinash** [comment]
Hi @EYSue , We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Comment by EYSue** [comment]
Many thanks for MSFT assistance

Regards

Sue
