### ISSUE TITLE
custom domain document update

### ISSUE THREAD

**Issue by ninjarish** [OfficeDev/microsoft-teams-apps-company-communicator#657]
Looks like in the below documentation, step 7 needs to be performed before step 6.
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option#fresh-deployment

**Comment by v-royavinash** [comment]
Thanks for the suggestion @ninjarish . We will review it internally and if required we will update the WiKi.

Are you facing any issue regarding the Custom Deployment for which we will can help you out?

**Comment by ninjarish** [comment]
I am good for now but will reach out if needed, thanks for offering to help.

________________________________
