### ISSUE TITLE
ISSUE OF INSTALLING COMPANY COMMUNICATOR APP. 

### ISSUE THREAD

**Issue by Waqasshafique123** [OfficeDev/microsoft-teams-apps-company-communicator#658]
Hi Team: We have a customer having 360k plus users , we deployed company communicator app successfully but when we send messages "Everyone in the organization" its not pushing message to anyone. We have waited for around 16 hours but still even a single user unable to receive message.
![654](https://user-images.githubusercontent.com/100826207/156508967-cd939050-573e-4d81-8e7d-8eda60d875b0.jpg)
the users unable to get the messages

We are really looking forward for your prompt response to fix the issue at earliest.

**Comment by SammiRasha** [comment]
@Waqasshafique123 Do you have proactive install enabled? You will need to make sure that the user app is uploaded to the org catalogue for proactive install to work. Additionally, you can also upload the user app below as shown in the screenshot:

![image](https://user-images.githubusercontent.com/10238857/156537293-0dc85345-2a12-47fe-9073-448e1a1d53f1.png)

That should also download it for everyone Let me know if that works or if you have already done these steps

**Comment by Waqasshafique123** [comment]
@SammiRasha thanks for your response. Its already added in the catalog and users are able to see the app above chat option in Microsoft Teams. but as Author we are unable to send message all across organization ,however we could send it to a specific group

**Comment by mustafafarooq** [comment]
Have you verified the correct permissions are assigned 
![image](https://user-images.githubusercontent.com/1696026/156556362-34416f08-6b70-451b-96e5-5803ac777379.png)

**Comment by Waqasshafique123** [comment]
Yes this is properly setup we ensured to setup all permission properly  @SammiRasha

**Comment by mustafafarooq** [comment]
A similar issue was raised sometime before, maybe you can try the steps they did, 

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/239

also do your Teams Permissions policies block any custom apps ?

![image](https://user-images.githubusercontent.com/1696026/156560440-5f919550-5ca3-4c5d-a50e-adb121425ebf.png)

**Comment by Waqasshafique123** [comment]
Is there any way connect over call, i have all the policies properly setup as advised by you, still customer facing issue

**Comment by v-royavinash** [comment]
Hi @Waqasshafique123 , Could you please what is the version of App? And also please share you MS teams Id.

**Comment by mustafafarooq** [comment]
Has any solution been discovered for this issue ?

**Comment by mustafafarooq** [comment]
Was the issue figured out ?

**Comment by Waqasshafique123** [comment]
@mustafafarooq  No , the CC app out of 367000 users on the tenant sent messages to only 50,000 users. Attached the image as reference. its been like a month we are trying to figureout. Do you have any solution for this @mustafafarooq  please ???
![error234](https://user-images.githubusercontent.com/100826207/159003551-282bc974-17f0-4d2a-9f81-eb3df11d8eb4.jpg)

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/100826207/159003294-4b4e4af9-d7d5-4c8d-92dc-23e3c6077209.png)

**Comment by gsv022** [comment]
Hi @mustafafarooq ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. 

Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. 

You may also always open a new issue or respond here if something does come back up. 

Thank you!

**Comment by gsv022** [comment]
Hi @mustafafarooq ,
We are closing the issue due to no confirmation from the author.
