### ISSUE TITLE
Support single tenant app and user assigned managed id for user and author bots

### ISSUE THREAD

**Issue by runceel** [OfficeDev/microsoft-teams-apps-company-communicator#659]
Azure Bot Service have been supporting sigle tenant app and user assigned managed id from Nov 2021. 
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned

Do you have any plan to support single-tenant app and user assienged managed id on Company Communicator?
I guess that multi tenant app is typical blocker to install production environment. Because some companies doesn't allow multitenant app on AAD.

**Comment by v-royavinash** [comment]
Hi @runceel , 
Thanks for your suggestion. We will review the request internally and post that will add it to backlog items for future releases. As of now we don't have the support and also we won't be able to provide any ETA for this.
