### ISSUE TITLE
Support for multiple Office 365 tenants

### ISSUE THREAD

**Issue by GrantOliasani** [OfficeDev/microsoft-teams-apps-company-communicator#660]
Is there any configuration where one Company Communicator instance and authoring app can send messages to multiple of the same user bot in different tenants? 

Example: Contoso has Company Comm deployment. Fabrikam is a subsidiary of Contoso, but they are in a different Office 365 tenant. Can Fabrikam install the same User Bot manifest as Contoso, and then receive messages? 

Is that what the field "AllowedTenants"  is for in the App Service? Does this field accept a list of Office 365 tenants GUID's? 

![image](https://user-images.githubusercontent.com/6586170/157117168-00657f20-724a-4bf7-9f05-5b00c9064f06.png)

**Comment by v-royavinash** [comment]
HI @GrantOliasani ,

Sending messages to multiple tenant at a time is not be possible due to restrictions from Azure side. However you can install another instance of company communicator to different tenant.

**Comment by gsv022** [comment]
Hi @GrantOliasani,
Could you please confirm if the issue logged is fixed and we are good to close the request. If you have any further issue request you to please log another issue.

**Comment by gsv022** [comment]
Hi @GrantOliasani ,
We tested the suggested approach to support multi-tenant. The messages were getting delivered as expected. However, we won't be able to confirm on go-ahead with a production deployment as while sending >100K messages we are not sure about how the behavior will be. Our recommendation will be to deploy another instance of CC for a different tenant. 

However, if you are not willing for another instance, then the same instance can be used with the work around steps shared over Teams but it won't be our recommended approach.
Let us know if anything required and we are good to close the request.

**Comment by gsv022** [comment]
Hi @GrantOliasani ,
We are closing the issue due to no confirmation from the author.

**Comment by manuelsambade** [comment]
Hi,

Even if not recommended, what are the configurations needed to use only one instance of company communicator for multiple Office 365 tenants?

Is just adding the tenant Id to the "AllowedTenants" enough?

Thank you
