### ISSUE TITLE
Unable to upload authors app to a team - "UpdateBotTeamMembershipInSkypeFailed"

### ISSUE THREAD

**Issue by nmtoblum** [OfficeDev/microsoft-teams-apps-company-communicator#662]
Dear company communicator team,

I need help with the last installation step:
I was able to perform powershell installation without errors or warnings but I'm not able to upload / sideload the cc_authors.zip package to a fresh team. This fails with "something went wrong". In the browser console I can at least see that the upload request fails with HTTP 400 and the response:   
{"errorCode":"UpdateBotTeamMembershipInSkypeFailed"}

<img width="864" alt="image" src="https://user-images.githubusercontent.com/57751598/157516026-e9ea8c84-d4a5-40c8-82d5-415eeb65993c.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/57751598/157516312-768f1d7a-a7c2-4f50-a6ef-da5eeb09752f.png">

Do you have an idea what goes wrong here? I wasn't able to find something similar in other issues.

Greetings
Tobias

**Comment by gsv022** [comment]
Hi @nmtoblum ,
We would recommend using App Studio and validating the ***.zip file. App Studio will highlight if the **.zip file is valid or it has some issue. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/98143492/157594672-f776fbe2-e89b-4d33-9eb6-9a3896e44a88.png)

**Comment by nmtoblum** [comment]
Hi @v-royavinash,

thank you for your fast response.
I forgot to mention that I already checked this. Just two warnings because of the domain for the privacy URL ("TOU / Privacy URL must not be hosted in a domain different from Company/Website URL"). No errors.

Any idea what this error message "UpdateBotTeamMembershipInSkypeFailed" could mean?

Greetings

**Comment by jimmymaise** [comment]
@nmtoblum : How can you solve this issue?

**Comment by nmtoblum** [comment]
@jimmymaise Unfortunately I didn't find a solution yet.
Perhaps @gsv022 would like to take on this topic again? :-)

**Comment by jimmymaise** [comment]
@nmtoblum:  In my case, the solution is you should add MS Team as a channel to your bot.

**Comment by JasthiKalyani** [comment]
Hi @jimmymaise,

Kindly let us know if you are still facing the issue.

**Comment by JasthiKalyani** [comment]
Hi @jimmymaise,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by 2toLeadMike** [comment]
Just had this issue as well, be sure that your manfiest `botId` and `webpplicationinfo->id` are targeting the right app.
