### ISSUE TITLE
GroupMember. vs Group. Permissions in Instructions

### ISSUE THREAD

**Issue by BattleAxeNelson22** [OfficeDev/microsoft-teams-apps-company-communicator#664]
The deployment guide states that groupmember.read.all permissions must be added but the accompanying screenshot is group.read.all. Which is the correct permission?

**Comment by BattleAxeNelson22** [comment]
based on research of my own groupmember.read.all is the correct permission, the screenshot is incorrect but i have seen it being provided as a troubleshooting step in other responses.

**Comment by gsv022** [comment]
Hi @BattleAxeNelson22 ,
In V5 Group.Read.All permission is not required. Below permission is to be added. We will be updating the screenshot in the upcoming release.

Delegated permissions:
1)GroupMember.Read.All
2)AppCatalog.Read.All

Application permissions:
1)GroupMember.Read.All
2)User.Read.All
3)TeamsAppInstallation. ReadWriteForUser.All

**Comment by v-royavinash** [comment]
Hi @BattleAxeNelson22 , We are closing this request as we have provided the requested details. If you face any further issue with company communicator please log a new issue.
