### ISSUE TITLE
Documentation on re-building

### ISSUE THREAD

**Issue by riddhichaplot** [OfficeDev/microsoft-teams-apps-company-communicator#668]
Dear team,

I am trying to do some changes and trying to re built the entire solution, do you have any documentation on what all changes needs to be done in Azure, Teams and the code itself if we are doing any code changes. 

Thanks in advance.

**Comment by gsv022** [comment]
Hi @riddhichaplot ,

To debug locally you will need all resources required for the Company communicator should be deployed on your Azure subscription. You need to download the code and start it in Visual studio using its .sln file or you can fork and clone the git repo in VS.

You need to follow the [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide).
There is two way you can proceed from this point. You need the following resources as mentioned in [appsettings.json.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/master/Source/CompanyCommunicator/appsettings.json)

You can do the deployment using the ARM Template option (Deployment Guide) and from the configuration of the App service, you will get the required information.

Or you need to create all resources manually.

Once you have all the required information you need to fill the [appsettings.json](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/master/Source/CompanyCommunicator/appsettings.json).

For AppDomain you can use ngrok or an equivalent tunneling solution. You will have to run it for the localhost app is running on.

Following [Step 5 of Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)[](https://user-images.githubusercontent.com/94480537/144419978-ff9bb2a0-a9a4-475a-ac9d-6ea8ffb8cf53.png)[](https://user-images.githubusercontent.com/94480537/144420009-5e052027-9366-42dd-af02-5e2bb1dd2780.png) just replace the app domain with ngrok URL.
![image](https://user-images.githubusercontent.com/98143492/157869786-71ca397f-0d60-4e00-9be2-c2187a048fe5.png)


Also on Azure Portal follow the below steps:

Go to Azure Portal --> Resource Group for CC app --> Author Web App Bot --> Configuration --> Replace the Messaging Endpoint with the ngrok URL.
Similarly, replace the Messaging Endpoint for User Web App Bot.
Go to App Registration --> Add Redirect URL with the ngrok URL.
image

Go to Expose an API and change the Domain name of the Application ID URI.
image
![image](https://user-images.githubusercontent.com/98143492/157869828-2d656885-dbf1-45a9-96b8-03bc0664ceb7.png)


Once done run the code using VS and add the debugger point to validate.
Let me know if it works. If not please elaborate on the error you are getting.

**Comment by riddhichaplot** [comment]
Thank you @gsv022 for the quick answer, let me follow these steps and then will let you know if I get any error.

**Comment by gsv022** [comment]
Hi @riddhichaplot,
Could you please confirm if the issue logged is fixed and we are good to close the request. If you have any further issue request you to please log another issue.

**Comment by riddhichaplot** [comment]
Hi @gsv022, I tried with the steps that you said above. I have followed the following steps:
1. Done deployment using Deployment guide. The solution works perfectly fine.
2. Did npm start, ran ngrok with the port which comes after this npm start.
3. Changed all the appdomain(in Azure portal that you said above) to the ngrok url
4. Following step 5, changed manifests files and created the packages.
5. When I am uploading the authors package in teams, I am getting the error which is attached below:
![image](https://user-images.githubusercontent.com/60658803/158557275-976023b1-b3d6-4a2c-853a-1ad05c10bb27.png)

Please let me know if I am doing anything wrong. I am new to this so all this might sound silly as well. Please bear with me.

**Comment by gsv022** [comment]
Hi @riddhichaplot ,
We will look into this and will get back to you.

**Comment by gsv022** [comment]
Hi @riddhichaplot ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
