### ISSUE TITLE
Company Communicator only sending message to selective users

### ISSUE THREAD

**Issue by SalmanBaig18** [OfficeDev/microsoft-teams-apps-company-communicator#669]
Hi Guys, 

So there is a bit of an issue with the company communicator installed in our tenant where the users receiving the messages are very limited. (7 people out of 16,000 users) and I have checked if there are any app permission policies set up and it shows that there are none. Also, proactively install to all users was "False" during the initial installation, we changed it to "True" and yet it still causes the same issue. Would require urgent support on this if possible.

**Comment by gsv022** [comment]
Hi @SalmanBaig18 ,
Could you please share the error details by exporting the previously sent message?

The export will have the response message as what the reason the message did not get delivered.

Also could you please confirm whether the proactive installation was enabled (True) manually after the deployment or it was done during the deployment?

**Comment by SalmanBaig18** [comment]
hi @gsv022 , 
Thanks for the prompt response. 

So with regards to exporting the the error details, the export is not really exporting anything. There is no error message given as well for the messages not delivered. 

The proactive installation was enabled manually, was there some further steps to be taken after that?

**Comment by robinmeure** [comment]
Check the contents of the azure tables (SentNotificationData, PrepareToSendFunctionTaskHubInstances and the AzureWebJobHost..) for the actual errors why its failing.

**Comment by SalmanBaig18** [comment]
@robinmeure  so the error states that app is not installed for the user whereas I have changed the proactively install user app from false to true. My understanding is that even if I change it in the App Service configuration, it is still not changing the command on the backend. Is there another way to change the proactive install apart from the bot service configuration tab?

**Comment by mustafafarooq** [comment]
you can have the app installed through the app setup policy in teams admin center.

**Comment by SalmanBaig18** [comment]
@mustafafarooq Already done that. Still doesn't seem to work..

**Comment by robinmeure** [comment]
Can you confirm if the main app has the "TeamsAppInstallation.ReadWriteForUser.All" set and consented?
 (Azure Portal -> App registrations -> App (without user or author) -> API Permissions)

**Comment by SalmanBaig18** [comment]
@robinmeure yup, that is done as well.

**Comment by robinmeure** [comment]
Ok, so we can cross that from the equation :)

Did you, apart from the App Service 'Configuration' also update all Azure Function configurations? Since every AzureFunction has its own configuration 'implementation' as well and they do not read the configuration of the AppService as far as I know.

**Comment by gsv022** [comment]
Hi @SalmanBaig18 ,
As you mentioned you enabled the proactive Installation manually. Could you please confirm if you have updated ProactiveInstallation flag for the App service and *-prep-function?

**Comment by SalmanBaig18** [comment]
Hi @gsv022, 

it was the Prep-Function causing the error. It now works fine. Thanks for your assistance!
