### ISSUE TITLE
Can the PowerShell deploy successfully when Azure Tenant is different to M365 Tenant?

### ISSUE THREAD

**Issue by nrogoff** [OfficeDev/microsoft-teams-apps-company-communicator#670]
Hi,

I am trying to deploy to CC where the Azure Subscription is associated with a different Tenant to the M365/Teams tenant.

It appears this is possible due to the two Tenant Id's in the parameters.json.

- **subscriptionTenantId** is set to the Azure Tenant
- **tenantId** is set to the M365/Teams Tenant

When I try to log into the Author App in Teams we get

```
AADSTS700016: Application with identifier '6adea000-5ba8-4570-a9eb-a307d12df157' 
was not found in the directory 'nrogoffavanade'. 
This can happen if the application has not been installed by the administrator of the 
tenant or consented to by any user in the tenant. You may have sent your 
authentication request to the wrong tenant.
```

I see the App Registrations are made only in the Azure Tenant and not the M365 Tenant and assume this is the key issue.

The PowerShell ran fine and I logged in using an account that is M365 Global Admin, that was also Global Admin in the Azure Tenancy and Owner of the Azure Subscription.

I am trying to do something that can't be done, or is there a manual fix I can apply to get this working as planned?

**Comment by nrogoff** [comment]
I think I may have found the issue

line 1038 of deploy.ps1 is

``` ps1
    $ADaccount = Connect-AzureAD -Tenant $parameters.subscriptionTenantId.Value -ErrorAction Stop
```
and I think it should be
``` ps1
    $ADaccount = Connect-AzureAD -Tenant $parameters.subscriptionId.Value -ErrorAction Stop
```
to match the next line and register the apps in the correct AD Tenant. Going to try it, but would like to know if there are any other consequences? Has anyone deployed cross tenants?

**Comment by gsv022** [comment]
Hi @nrogoff ,
Yes, it can be done.
If you face any issue please go ahead with manual deployment. We have cross validated at our end and can confirm that you can deploy to cross tenant.

**Comment by nrogoff** [comment]
Great thanks...good to know. I have been working on the deploy.ps1 file and I can now see there are quite a few things that break and I am now see if I can adjust the script to login to different tenants for different things.

**Comment by v-royavinash** [comment]
Hi @nrogoff , We are closing this request as we have provide the required alternative for multi tenant deployment. If you have any further query, request you please do raise a new request.
