### ISSUE TITLE
Allow the Company Communicator to send to Dynamic Distribution Lists

### ISSUE THREAD

**Issue by stehodge** [OfficeDev/microsoft-teams-apps-company-communicator#671]
We would like the company communicator Teams app to be able to send to dynamic distribution lists.  Currently it will only send to M365 groups, distribution groups or security groups.

**Comment by gsv022** [comment]
Hi @stehodge ,
We currently don't support this. We will add it to as a feature request for future releases.

**Comment by stehodge** [comment]
We found a work around where we can create a dynamic Security group.  We select dynamic membership rules and for the rule syntax, we populate it with the same value we used to create the DDL.  This Security group can then be selected by company communicator and a message can be sent and delivered to the members.

Steven Hodge l FLUOR l Global IT - End User Services l ***@***.*** l O 864.281.4334 | IODC (8) 20-4334

From: Sai Venkat ***@***.***>
Sent: Thursday, March 17, 2022 6:42 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Steven Hodge ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [OfficeDev/microsoft-teams-apps-company-communicator] Allow the Company Communicator to send to Dynamic Distribution Lists (Issue #671)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @stehodge<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstehodge&data=04%7C01%7CSteven.Hodge%40fluor.com%7C7873649dbb6b41a5c47f08da0802cf87%7C75864cfef26d419cb69dc638695b5533%7C0%7C0%7C637831105430963097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z9PcK40ITyuZbLz0a6LjWbLpSMxX0Gq9H3FMJfD3mtU%3D&reserved=0> ,
We currently don't support this. We will add it to as a feature request for future releases.

-
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fissues%2F671%23issuecomment-1070775518&data=04%7C01%7CSteven.Hodge%40fluor.com%7C7873649dbb6b41a5c47f08da0802cf87%7C75864cfef26d419cb69dc638695b5533%7C0%7C0%7C637831105430963097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UE1ZdTvE2AOiqlQmQHGxaG5MccCoVlKH1O1SXTO9Ngg%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYIFL2H4PKX36VJDNDOYXLTVAMD73ANCNFSM5Q4KQ55Q&data=04%7C01%7CSteven.Hodge%40fluor.com%7C7873649dbb6b41a5c47f08da0802cf87%7C75864cfef26d419cb69dc638695b5533%7C0%7C0%7C637831105430963097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CWkMXvKnS6fs7JxzBkPhNT4h7X9cxeLQjN5v1KGdmJM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CSteven.Hodge%40fluor.com%7C7873649dbb6b41a5c47f08da0802cf87%7C75864cfef26d419cb69dc638695b5533%7C0%7C0%7C637831105430963097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8AXR136cAJ%2Bd94RI%2BgWSH1JpLPiNkDAQh68Oh5DvAfU%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CSteven.Hodge%40fluor.com%7C7873649dbb6b41a5c47f08da0802cf87%7C75864cfef26d419cb69dc638695b5533%7C0%7C0%7C637831105431119338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jU933rZgzNxBcsMfof2u2LfjYXoJ1q%2FyQJbOnxd%2BrRw%3D&reserved=0>.

**Comment by gsv022** [comment]
Hi @stehodge ,
Thanks for the workaround steps to create a dynamic Security group. We are proceeding to close the issue as no further action items are required from our end.

Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.

**Comment by stehodge** [comment]
So there are no plans to enable the current DDLs for use with Teams and Communicator?

Steven Hodge l FLUOR l Global IT - End User Services l ***@***.*** l O 864.281.4334 | IODC (8) 20-4334

From: Sai Venkat ***@***.***>
Sent: Thursday, March 31, 2022 2:08 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Steven Hodge ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [OfficeDev/microsoft-teams-apps-company-communicator] Allow the Company Communicator to send to Dynamic Distribution Lists (Issue #671)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @stehodge<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstehodge&data=04%7C01%7CSteven.Hodge%40fluor.com%7C0bff2976634e44c112a608da12dce3f7%7C75864cfef26d419cb69dc638695b5533%7C0%7C0%7C637843037176022697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=d9jDPFH4yIM5J%2Bimk4KuaAHUysC6KgUXjr8GVA0iAOY%3D&reserved=0> ,
Thanks for the workaround steps to create a dynamic Security group. We are proceeding to close the issue as no further action items are required from our end.

Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.

-
