### ISSUE TITLE
COMMUNICATOR APP ERROR (Messages on queue & User App nor installing for users)

### ISSUE THREAD

**Issue by CPSDevOps** [OfficeDev/microsoft-teams-apps-company-communicator#672]
Following on our recent deployment on clients' environment the following are the activities that have been successfully completed;

Deployment of communicator app to the Azure Environment
Deployment of Author Module of the Application
Deployment of the User Module of the Application
However, we are facing the following challenges as shown in the screenshots below

When the Author send communication it queues for a long time without sending the communication to the targeted user

Users assigned the User Module of the Communicator App cannot install the application in the teams app

 **TROUBLESHOOTING ACTIVITIES DONE**

Restart and Resync of all App services deployed
Checking the Teams Admin policies on whether  Communicator App Modules have been allowed and whether users are allowed to install and upload custom Apps.
Redeployment of the User Module of the Communicator Application
NB:  After trying to troubleshoot we are still experiencing the same Error as shown in the attached screenshote
![Author Module message queueing](https://user-images.githubusercontent.com/61407825/158951855-b8c2ac2e-4fa2-47f1-971a-7ad9ebae0f52.png)
![User Module when being Installed](https://user-images.githubusercontent.com/61407825/158951890-0b87dbf0-602b-45bc-ad71-e79d93e048be.png)
.

**Comment by v-royavinash** [comment]
Hi @CPSDevOps ,

There can be multiple reasons for the issue.
Could you please check and provide your inputs on the below points? It will help us to understand the possible reasons for the issue. 

1.	How are you uploading the User App? Is it Tenant level or it’s done through the permission policies for a specific set of users?
2.	If at the Tenant level, Go to Teams Admin Center. Check if the User App is uploaded to the Teams catalog. Also please confirm it by sharing a screenshot.
3.	Have you enabled Proactive installation while deploying the app?

4.	Please confirm if the resources are successfully deployed after Re-Sync.

    - Go to the Azure portal --> Resource group which got created --> App Service
    - Click on the "**Deployment Center**" section of the app service.
    - Navigate to the **Logs** tab and please confirm if the status is showing as “**Success**”
    - Please repeat and confirm the same for all other 3 Azure functions under the same resource group.

5.	Also please share with us the error logs of App Insights.

**Comment by gsv022** [comment]
Hi @CPSDevOps ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses.

Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. 

Thank you!

**Comment by v-royavinash** [comment]
We are closing out the issue due to no confirmation from the author.
