### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by ostumm** [OfficeDev/microsoft-teams-apps-company-communicator#673]
Hi all,

is it planned to support inserting emojis into the text field for future releases? Currently no emojis could get added to the text.

Best regards,
Oliver

**Comment by gsv022** [comment]
Hi @ostumm y,
we will consider it as a backlog and will add it in the future releases.

**Comment by gsv022** [comment]
Hi @ostumm ,
We are closing the issue request as we don't provide support for direct customization.
However, we have noted down your suggestion for Emoji Support and will be adding it to our backlog.
Also, please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
