### ISSUE TITLE
Upgrade to v5.0 hosting plan selection

### ISSUE THREAD

**Issue by scjohnmsft** [OfficeDev/microsoft-teams-apps-company-communicator#675]
When customer is upgrading from v4 to v5, using the below V5.0 ARM template where the SKU plan size is automatically selected as 1. After the ARM template deployment, we are noticing the below warning message for app service and all the azure function.  When we cross check with the migration guide for V5.0, it is mentioned to use the ARM template that is pointing to Master GitHub branch and also the SKU plan size is automatically selected as 2.
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOfficeDev%2Fmicrosoft-teams-company-communicator-app%2Fmaster%2FDeployment%2Fazuredeploy.json

![CC warning upgrade to v5](https://user-images.githubusercontent.com/64435811/159706272-7ddbe806-12a0-408b-963f-66bbf69881cf.png)

Can we validate if we should choose SKU plan size as 2 while deploying through the v5 ARM template itself and will this eliminate the warning message.

**Comment by gsv022** [comment]
Hi @scjohnmsft ,

SKU size places an important role while deploying the resources. By default for V5, we recommend S2 Instance to have a better performance of the App. Seeing the below error, it seems the S1 instance has already reached its memory limit hence please choose an higher instance of App service plan i.e. S2 or above.

Let us know if this resolved the error messages.

**Comment by gsv022** [comment]
Hi @scjohnmsft ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Comment by scjohnmsft** [comment]
Ok to close and thank you for the quick response
