### ISSUE TITLE
Message is displayed wrong on mobile device

### ISSUE THREAD

**Issue by malikahoffer** [OfficeDev/microsoft-teams-apps-company-communicator#676]
A message that is displayed correctly in the Teams desktop app/ webapp, looks different in the mobile app. On some the links are written in plain text, on some there are no more line breaks

**Comment by gsv022** [comment]
Hi @malikahoffer ,
We don't support mobile version as of now. It will be planned for future releases.

**Comment by gsv022** [comment]
Hi @malikahoffer ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Comment by malimal99** [comment]
> Hi @malikahoffer , We don't support mobile version as of now. It will be planned for future releases.

So using the author app on mobile is not supported right now?
