### ISSUE TITLE
Cannot make changes to Notification summary

### ISSUE THREAD

**Issue by riddhichaplot** [OfficeDev/microsoft-teams-apps-company-communicator#678]
Hi team,

I have been trying to make changes to the notification summary referring the below blog:
https://techcommunity.microsoft.com/t5/iis-support-blog/how-to-change-notification-text-when-bot-sends-an-adaptive-card/ba-p/1945008

but the changes are not reflecting.

Can you please look into it?

**Comment by gsv022** [comment]
Hi @riddhichaplot ,
We won't support for customization of the Company Communicator app. Please proceed on your own.

**Comment by gsv022** [comment]
Hi @riddhichaplot,
We are closing the issue request as we don't provide support for customization.
However, we have noted down your suggestion for the modification related to the Adaptive card and will be adding it to our backlog for internal review and future releases.
Also, please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
