### ISSUE TITLE
Not able to send message through CC bot to everyone

### ISSUE THREAD

**Issue by Lekhip** [OfficeDev/microsoft-teams-apps-company-communicator#679]
Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request. Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request. Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request. Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request. Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request. Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request. Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request. Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request.

**Comment by nrogoff** [comment]
Have you looked for error in the Application Insights? I found this can help work out what's wrong.

**Comment by gsv022** [comment]
Hi @Lekhip,
We will look into it and will get back to you soon.

**Comment by gsv022** [comment]
Hi @Lekhip ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
