### ISSUE TITLE
Is userObjectId used anywhere? If not, should it be removed?

### ISSUE THREAD

**Issue by nrogoff** [OfficeDev/microsoft-teams-apps-company-communicator#680]
Hi,
I can't seem to trace any use of the Parameter 'userObjectId'. a good understanding of what it is for and which user object id this should be.
If it's not used, should it be removed?
If it is used, then can we get a better explanation of what is should be populated here?

Thanks
Nicholas

**Comment by gsv022** [comment]
Hi @nrogoff ,
Please provide a supporting screenshot of where exactly you got this parameter.

**Comment by nrogoff** [comment]
I don't think a screenshot is applicable. It's a parameter in the Deployment/parameters.json file!

`"UserObjectId": {
    "Value": "<<value>>",
    "Description": "User Object Id."
  },`
and described in the documentation at

> userObjectId - Object Id of the user to deploy to (If you are not sure how to get Object ID, please check Azure Active Directory in Azure Portal. Under Manage, click Users and select the appropriate user. The Object ID is shown in the Identity section). e.g 98f3ece2-3a5a-428b-aa4f-4c41b3f6eef0.

**Comment by gsv022** [comment]
Hi @nrogoff ,
As per first impression its seems like its not been used, but will confirm after the internal review.

**Comment by nrogoff** [comment]
> Good morning. This also appears to be required in the custom deployment template but it is not included anywhere in the documentation for certificate deployments. Can you please clarify how this is being used and which user object ID should be inputted?
> 
> ![image](https://user-images.githubusercontent.com/103449762/164493682-263242a6-737a-480d-86c3-da89318c5d19.png)

That doesn't explain what 'to deploy to' means and the previous message confirmed that it is in fact not used at all!

**Comment by gsv022** [comment]
Hi @nrogoff ,
We will review it and post review if that parameter is found as unused, we will remove it in our next release.

**Comment by gsv022** [comment]
Closing out the issue as we have provided the required response. If you have any further queries please raise a new GitHub request.

**Comment by neidantaslopez** [comment]
> Closing out the issue as we have provided the required response. If you have any further queries please raise a new GitHub request.

Sorry to reopen this one, but I don't see where in this issue the required response was provided.

Is the userObjectId used anywhere? Could you provide more details on its purpose, if it serves any purpose?
