### ISSUE TITLE
Service Bus Web App Role Name Guid handling for 2nd deployment in same tenant for v5/v4

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#682]
![image](https://user-images.githubusercontent.com/25476072/160793146-e63131ad-a575-49e0-bdf2-fde5271b7e8c.png)

![image](https://user-images.githubusercontent.com/25476072/160793422-1a83aaff-ce88-43ce-a352-d76aea7f3216.png)

In step 2, if I forgot to modify the above GUIDs to other new random GUIDs in 2nd deployment in same tenant for v5.
Do I have to remove all Azure components generated  in 2nd deployment and re-process the step 2 again?

In 2nd deployment in same tenant for v4, where can I find above GUIDs to change in step2 or later deployment steps?

Thanks for your help in advance

**Comment by gsv022** [comment]
Hi @rex-ma ,
If v5 second deployment failed then re-deployment is needed.
V4 don't have dependency on Azure RBAC, so its not required to update.

**Comment by gsv022** [comment]
Hi @rex-ma ,
For now we are closing this issue request as we provided the necessary information.
Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
