### ISSUE TITLE
Deployment with ARM template

### ISSUE THREAD

**Issue by chandni-agarwal** [OfficeDev/microsoft-teams-apps-company-communicator#683]
Can we create all the resources manually and then connect with one another instead of deploying using an ARM template. Can someone  guide with the steps to do so.

**Comment by gsv022** [comment]
Hi @chandni-agarwal ,
Yes, it can be done. But it will be very lengthy process as all the configuration has to be done manually.
We won't be able to share or draft the steps.

**Comment by gsv022** [comment]
Hi @chandni-agarwal ,
We are closing the issue request as we wont be able to provide steps to deploy resources  manually instead of ARM template.

 Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
