### ISSUE TITLE
Send message to everyone errors out

### ISSUE THREAD

**Issue by Pa623** [OfficeDev/microsoft-teams-apps-company-communicator#684]
Hi team, while sending messages to everyone via CC was possible until 1 month ago, it now errors out. Warning is: Failed to sync to all users and DeltaLink older tan 30 days is not supported. The delta link error message was there before, but sending to everyone was still possible. 

Any idea what to do?

**Comment by gsv022** [comment]
Hi @Pa623 ,
User was not able to send the message through 3rd option- Send in chat to everyone. The error was “DeltaLink older than 30 days is not supported”. 

We performed the following things to fix the above error.
•	Deleted an entry with PartitionKey UsersSyncData in UserData.
•	Restarted all the services.
•	Verified that the message was getting delivered using other three options.

We suggested to send a message to all the users again and keep us updated regarding the message was sent to all or not.

**Comment by gsv022** [comment]
Hi @Pa623 ,
The data function seems to be causing the issue.
As it was 4.0.2 version, we were not able to re-deploy the data function. We suggested to migrate the version from v4 to v5 and said to keep us posted.

**Comment by gsv022** [comment]
Hi @Pa623,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
