### ISSUE TITLE
Pull requests not getting approved or feedback given.

### ISSUE THREAD

**Issue by jasonwbaxter** [OfficeDev/microsoft-teams-apps-company-communicator#685]
Hi , i submitted pull requests in Nov last year(2021) with crucial troubleshooting information for all customers but i have not received any feedback

There are pull requests dating back to September 2018 still waiting in the queue.

**Comment by gsv022** [comment]
Hi @jasonwbaxter ,

We will review the PR and those relevant will be included in the next release.
But we won't be able to share any ETA for the next release.

**Comment by gsv022** [comment]
Hi @jasonwbaxter ,
For now we are closing this issue request. We will review the PR and do the necessary.
Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
