### ISSUE TITLE
Subscription Type is not permitted

### ISSUE THREAD

**Issue by nahcyrret** [OfficeDev/microsoft-teams-apps-company-communicator#686]
![SubscriptionType](https://user-images.githubusercontent.com/39899353/161239704-df888ec5-ae45-4c1d-bf1a-9bf314caff2b.JPG)

What subscription type should I use to solve the above deployment problem?

**Comment by gsv022** [comment]
Hi @nahcyrret ,

Could you please follow the manual deployment steps and try deploying under the same subscription. If the same issue occurs please use another subscription. Also please check the Prerequisites for deploying the resources as the subscription should have support to deploy the mentioned resources.

**Comment by nahcyrret** [comment]
![read](https://user-images.githubusercontent.com/39899353/161412061-09261429-e18a-4ce6-bb4e-8cdea04f0dd9.png)

I use another account with the read permission problem. How to grant read access to subscription ID?

**Comment by nahcyrret** [comment]
How to ensure the subscription have support for deploying the mentioned resources? I have no idea of what steps to do.

**Comment by gsv022** [comment]
Hi @nahcyrret ,


To check if you have permission to do this,

- Goto the subscription page in Azure portal. Then, goto Access Control(IAM) and click on View my access button.

Click on your role and in search permissions text box, search for Microsoft.Authorization/roleAssignments/Write.

- If your current role does not have the permission, then you can grant yourself the built in role **User Access Administrator** or create a custom role.

- Please follow this [link](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles#steps-to-create-a-custom-role) to create a custom role. Use this action Microsoft.Authorization/roleAssignments/Write in the custom role to assign roles in Azure RBAC.
- 

These are the steps for validating the access for the subscription.

**Comment by nahcyrret** [comment]
![ARMDeployError](https://user-images.githubusercontent.com/39899353/163333102-17d1891e-0799-4c1c-a1b9-4a902cef0139.png)

I encountered the ARM template deployment error with the following error in the log.

{
    "additionalInfo": null,
    "code": "ResourceDeploymentFailure",
    "details": null,
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "target": null
  },
  {
    "additionalInfo": null,
    "code": "RoleAssignmentUpdateNotPermitted",
    "details": null,
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
    "target": null
  },

**Comment by gsv022** [comment]
Hi @nahcyrret ,

- Please go for re-deployment.

- Role assignment issue normally arises when attempting multiple deployments with the same GUID. As per suggestion it is recommended to have new GUID’s generated for each deployment if it is performed in the same subscription.
![image](https://user-images.githubusercontent.com/98143492/165703068-d061b03f-3dfa-48bc-b8c0-5e9bc8a399f3.png)

- Go to [GUID](https://www.guidgenerator.com/online-guid-generator.aspx) tool and paste the newly generated ID's in the parameters shown on above image.

-  We recommend to go for manual deployment if the issue persists.

We are closing this issue and can continue the conversation in #701
