### ISSUE TITLE
Image not loading in Company Communicator V5.0 notification

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-company-communicator#688]
We have noticed a peculiar issue with  Company Communicator V5.0 notification where the image is not loading in the user app notification card if it is from the below url.

https://s7.gifyu.com/images/TestImage.png
https://s4.gifyu.com/images/TestImage.png

But There is no issue if we use the image url from below location. if you check the url then the host names are different but the domains are same. 

https://s10.gifyu.com/images/TestImage.png 
https://s9.gifyu.com/images/Format-Background.gif 
![image](https://user-images.githubusercontent.com/91881396/161929614-07ac2b89-d1a7-4be4-90da-7e037d3fbc09.png)

**Comment by gsv022** [comment]
Hi @EYSue ,
We are closing this as the issue got resolved over the call. Please feel free to reach out to us on the deployment or functionality issues of Company Communicator app by logging the new issue.
