### ISSUE TITLE
Azure Front Door Service Config not found

### ISSUE THREAD

**Issue by stfenix** [OfficeDev/microsoft-teams-apps-company-communicator#691]
Hi,

 After successfully completing the Powershell deployment guide I get a "Page not found" error when adding the Authors tab to the Team. I have given it over 12 hours and I am still getting the same error. When clicking any of the available links on the error page I get a "azure.microsoft.com refused to connect" error. 

What am I doing wrong? :( 

Regards

**Comment by gsv022** [comment]
Hi @stfenix 
We have noted your issue and will get back to you.

**Comment by Porkai-Pandian** [comment]
Hi @stfenix,

Please check you manifest file if you've updated the configurationURL and resource correctly, if possible request you to share the manifest file of author bot for us to troubleshoot.

**Comment by stfenix** [comment]
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
    "manifestVersion": "1.11",
    "version": "5.0.0",
    "id": "1c07cd26-a088-4db8-8928-ace382fa219f",
    "packageName": "com.microsoft.teams.companycommunicator.authors",
    "developer": {
        "name": "Imperial Logistics",
        "websiteUrl": "https://www.imperiallogistics.com/",
        "privacyUrl": "https://www.imperiallogistics.com/terms-conditions.php",
        "termsOfUseUrl": "https://www.imperiallogistics.com/terms-conditions.php"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "Imperial Comms (Authors)",
        "full": "Imperial Communicator (Authors)"
    },
    "description": {
        "short": "Broadcast messages to multiple teams and people in one go",
        "full": "Broadcasts messages to multiple teams and individuals through channel posts and chat messages"
    },
    "accentColor": "#64A2CC",
    "configurableTabs": [
        {
            "configurationUrl": "https://impcommsbase.azurefd.net/configtab",
            "canUpdateConfiguration": true,
            "scopes": [
                "team"
            ]
        }
    ],
    "bots": [
        {
            "botId": "c6d59fc4-8650-4b57-b952-27309a68ed59",
            "scopes": [
                "team"
            ],
            "supportsFiles": true,
            "isNotificationOnly": true
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "impcommsbase.azurefd.net"
    ],
    "webApplicationInfo": {
        "id": "c6d59fc4-8650-4b57-b952-27309a68ed59",
        "resource": "api://impcommsbase.azurefd.net"
    }
}

**Comment by v-royavinash** [comment]
Hi @stfenix ,

The manifest seems valid. Could you please share the below details,

- Go to the Resource group created during the deployment
- Click on Overview

 ![image](https://user-images.githubusercontent.com/94480537/162451280-a0622ea1-bb57-4fdc-8864-3337965e5a73.png)

- Click on the Deployments and click on the Template deployment link and share the entire resource creation steps during the deployment for further troubleshooting.

**Comment by stfenix** [comment]
Hi @v-royavinash 

![image](https://user-images.githubusercontent.com/1441016/162679107-64cd56ae-3306-491a-a9f9-4cfb87522411.png)

All deployments completed succsesfully

**Comment by v-royavinash** [comment]
Hi @stfenix ,

If you still facing the issue, please share with us your MS Teams Id so that we can connect over a call to troubleshoot it.

**Comment by gsv022** [comment]
Hi @stfenix ,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by stfenix** [comment]
Hi

Thanks, the issue has been resolved. we manually deployed via the GUI
without any issues.
