### ISSUE TITLE
Export Results Issue - "Go back to the main window to see this content"

### ISSUE THREAD

**Issue by malimal99** [OfficeDev/microsoft-teams-apps-company-communicator#692]
Hello, when I export the results of a sent message the author bot on the desktop client shows "Go back to the main window to see this content". 

![Receipt cards error](https://user-images.githubusercontent.com/48032390/162206908-3341dd6f-5b9a-4bed-b56c-8f3b15b90810.png)

If I open the Author chat in the web client its shows the proper message asking you to allow or decline permissions to OneDrive. Selecting allow will then show the correct card in the desktop client to download the file.

I have uninstalled the app, cleared the cache, and clean uninstalled Teams. Also tried it on a different laptop.

**Comment by v-royavinash** [comment]
Hi @malimal99 ,

As you mentioned the company communicator app is working fine for the MS team's Web client, hence the issue seems specific to your Teams setup not related to the company communicator app.

We won't be able to provide much help on this.

**Comment by gsv022** [comment]
Hi @malimal99 ,
We are closing this request as we have provided the requested details. If you face any further issue with company communicator please log a new issue.
