### ISSUE TITLE
Failure while syncing the Azure Functions

### ISSUE THREAD

**Issue by LeandrewP** [OfficeDev/microsoft-teams-apps-company-communicator#695]
There seems to be a failure every time I try and sync the 3 Azure functions to the external Git and when I open the log for the failed sync, I get the following message. 
![Error sync message](https://user-images.githubusercontent.com/86063509/162961805-be1fb88a-e95d-42a5-b2d0-b2cc8a55d299.png)

A portion of the error message I get is:

> Build started 4/12/2022 12:02:33 PM.
> C:\home\site\repository\Source\CompanyCommunicator.Prep.Func\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj : error : Version 3.1.417 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
> Project "C:\home\site\repository\Source\CompanyCommunicator.Prep.Func\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj" on node 1 (default targets).
> C:\home\site\repository\Source\CompanyCommunicator.Prep.Func\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
> Done Building Project "C:\home\site\repository\Source\CompanyCommunicator.Prep.Func\Microsoft.Teams.Apps.CompanyCommunicator.Prep.Func.csproj" (default targets) -- FAILED.
> Build FAILED.

I have also ensured that the correct External Git Repo URL is linked. Please could I get some guidance on this sync issue.

**Comment by gsv022** [comment]
Hi @LeandrewP ,

1. Could you confirm that the issue occurring is only for prep function or for all 3 functions?
2. You mentioned that Git repo URL is correct, Could you please share the repo URL ? And screenshot of that will be helpful for better troubleshooting.
3. Is it the first time that you are deploying the app or migrating to higher versions?
4. If it is the first time that the deployment has been done and facing this issue, please share the MS Teams id for troubleshooting purpose.
5. Could you mention what is the instance of app service plan that is being used?

**Comment by rramos9771** [comment]
It sends me the same error too
in prep-function, data-function and in function

![image](https://user-images.githubusercontent.com/96545484/163048999-54ed7a2e-5b15-4459-8b7f-7e7f2ef91260.png)

**Comment by LeandrewP** [comment]
Thank you for the response @gsv022. 

- Yes, the sync is failing on all 3 functions. However, it had a successful sync in the App service.
- ![Sync URL](https://user-images.githubusercontent.com/86063509/163174035-c3b44860-f950-4f80-a940-34791ed6ef50.png)
- This is a clean deployment, so it is the first time doing the deployment
- It is the S2 App Service Plan

**Comment by cristianoag** [comment]
This is happening with all functions when syncing to the official CC version. I was able to fix in my fork just updating the deploy.function.cmd to use a newer version of msbuild. 
![image](https://user-images.githubusercontent.com/48498602/163248223-39afc31e-f04d-49a7-97c1-a3dcf87741eb.png)

**Comment by jesusfer** [comment]
I can repro exactly the same with a clean install.

**Comment by MohnJadden** [comment]
I'm having the same issue with a clean install, following the [Powershell deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-powershell).  

- It affects all three functions created by the template; all other resources seem to be OK
- Git repo URL is https://github.com/OfficeDev/microsoft-teams-apps-company-communicator.git 
- I am deploying the app for the first time in this tenant
- App service plan is Y1

I had similar errors in cristianoag's fork.

**Comment by cristianoag** [comment]
That is not happening with my fork anymore. It was fixed last week. Make sure you are syncing the latest version.

**Comment by MohnJadden** [comment]
> That is not happening with my fork anymore. It was fixed last week. Make sure you are syncing the latest version. 

I'm downloading the zip from https://github.com/cristianoag/microsoft-teams-apps-company-communicator/archive/refs/heads/master.zip, extracting the contents to a new folder, then copying /Deployment/parameters.json from my attempted deploy over /Deployment/parameters.json on the files from your fork.  

When I run deploy.ps1, it throws an error that at least one resource deployment operation fails.  The activity log shows that the Update Web App Source Control Configuration deployment failed for the -function, -prep-function, and -data-function.   

Deployment Center for any of the three failed app services shows basically the same error as OP, pasted below.  Not sure if I did something incorrectly in the deployment but I've basically followed the deployment guide from either your fork or the original.  Please do let me know if I messed something up, happy to re-try.

Command: deploy.cmd
Handling function App deployment with Msbuild.
Using Msbuild from 'C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin'.
Nothing to do. None of the projects in this solution specify any packages for NuGet to restore.
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/20/2022 7:32:28 PM.
C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj : error : Version 3.1.417 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
Project "C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj" on node 1 (default targets).
C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
Done Building Project "C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj" (default targets) -- FAILED.

Build FAILED.

  C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj : error : Version 3.1.417 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.4.0.56107. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.


"C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj" (default target) (1) ->
  C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:02.06
Failed exitCode=1, command="C:\Program Files (x86)\MSBuild-16.4\MSBuild\Current\Bin\MSBuild.exe" "C:\home\site\repository\Source\CompanyCommunicator.Data.Func\Microsoft.Teams.Apps.CompanyCommunicator.Data.Func.csproj" /p:DeployOnBuild=true /p:configuration=Release /p:publishurl="C:\local\Temp\8da23046cb99307"
An error has occurred during web site deployment.
\r\nC:\Program Files (x86)\SiteExtensions\Kudu\96.40113.5578\bin\Scripts\starter.cmd deploy.cmd

**Comment by cristianoag** [comment]
Powershell doesn’t download my code. It is still pointing to the official repo. You need to follow deployment guide manual setup instructions if you want to use my version.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MohnJadden** [comment]
You are right - I hadn't changed the gitRepoUrl value in parameters.json when I tried your fork.  Fixed and re-trying on your fork.  Thank you for pointing that out!

**Comment by MohnJadden** [comment]
I had a few 502 errors but those may have been because I had hyphens in the resource names and the deployment didn't like that.  Removing the hyphens and starting with a fresh baseResourceName parameter worked - I was able to deploy successfully.  Thank you!
