### ISSUE TITLE
Can I change the app service plan without any problems?

### ISSUE THREAD

**Issue by rooobeert** [OfficeDev/microsoft-teams-apps-company-communicator#696]
Hi, 

we have configured our app service plan to S2. 
We would like to change the plan to S1. This is technically available in the Resource Group.

![image](https://user-images.githubusercontent.com/87785803/162987767-de9c3154-d1fd-480b-b459-49522160cede.png)

Do I have to redeploy the app or adjust any other services?

Thanks!

**Comment by gsv022** [comment]
Hi @rooobeert ,
Yes, the service plan can be changed to S1 without going for re-deployment. The recommended instance is S2, however the app will work for S1 as well.

**Comment by rooobeert** [comment]
Alright! Thank you very much :)
