### ISSUE TITLE
Cannot find any Teams or Teams Users in Recipients

### ISSUE THREAD

**Issue by rooobeert** [OfficeDev/microsoft-teams-apps-company-communicator#697]
Hi! 

We imported the solution and everything worked great so far. We forgot to consent the App Registration and just did that after we installed the app to the teams room. 
Now when we try to send a message and have to choose the recipients, we get "No results". 

Are there any other things we might have missed or should we reimport the apps to teams?

![image](https://user-images.githubusercontent.com/87785803/162992607-3cfad8e0-8371-4ca0-ac3d-680972988e5d.png)

**Comment by gsv022** [comment]
Hi @rooobeert ,
Thanks for raising the issue, please check if the user app in installed to the Teams channel, Team group names will appear in the dropdown only if the user app in installed.
![image](https://user-images.githubusercontent.com/98143492/163108966-e8802c19-0cb9-4f97-8bba-de06716faaeb.png)

**Comment by rooobeert** [comment]
If I understood correctly: 
1. Teams only show up when I install the user app to every teams room I have in my tenant?
2. User will show up as soon as the user app is installed/pinned to my users teams?

Thanks!

**Comment by v-royavinash** [comment]
@rooobeert , Closing out the issue as we have provided the required response. If you have any further queries please raise a new GitHub request.
