### ISSUE TITLE
Unable to add uploaded app to a team - "UpdateBotTeamMembershipInSkypeFailed

### ISSUE THREAD

**Issue by jimmymaise** [OfficeDev/microsoft-teams-apps-company-communicator#698]
I have the same issue with this guy.
AppStudio checked it without any error
Any idea what this error message "UpdateBotTeamMembershipInSkypeFailed" could mean?

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/662

**Comment by gsv022** [comment]
Hi @jimmymaise ,

It seems there is an ongoing issue with MS Teams in uploading the manifest, you can find the issue thread [here](https://techcommunity.microsoft.com/t5/teams-developer/mgmt-appcatalog-lobapp-upload-badrequest/m-p/3281493)

**Comment by jimmymaise** [comment]
@gsv022 : Really? I don't think so as #662 created 1 month ago :(

**Comment by jimmymaise** [comment]
Hello, I can confirm that this is not the same with the issue @gsv022 mentioned. I still can upload but can't add the uploaded app to Teams
Here is my manifest
[app_test.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8478723/app_test.zip)

**Comment by gsv022** [comment]
Hi @jimmymaise ,
We are working on it and will get back to you.

**Comment by gsv022** [comment]
Hi @jimmymaise ,

1. The zip file attached containing **_MACOSX** needs to be deleted.

2. The manifest file contains this below error. Remove comma. Rename logo-color as color and logo-outline as outline.

   <img width="251" alt="image" src="https://user-images.githubusercontent.com/98143492/163119457-715b95ee-2e7e-4ed3-a685-3cfa08aaabbc.png">

3. After that zip them all.

   <img width="605" alt="image" src="https://user-images.githubusercontent.com/98143492/163120435-ab7e7252-66e0-4016-ba4e-9f37ed679273.png">

4.  Upload the zip file again.

5.   After the above changes are completed, go back to the azure prep function, and restart the service. 

Hope it helps.

**Comment by jimmymaise** [comment]
[app.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8483123/app.zip)
It still doesn't work @v-royavinash @gsv022

**Comment by Porkai-Pandian** [comment]
Already responded to your other issue #700, closing this as it is duplicate.
