### ISSUE TITLE
Valid schema json and zip file  but still unable to add uploaded app to a team - "UpdateBotTeamMembershipInSkypeFailed"

### ISSUE THREAD

**Issue by jimmymaise** [OfficeDev/microsoft-teams-apps-company-communicator#700]
I solved all issues having mentioned at https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/698 (sorry for duplicating but I need to solve this issue ASAP)
My schema is valid: No error in the JSON file
My zip file is valid: No other file, folder in a zip file
Icon files have been updated in name (in manifest.json as well)

Still cannot add this application to team: Get error UpdateBotTeamMembershipInSkypeFailed
[app.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8483263/app.zip)

**I'm using a development account so I'm not sure if it is a problem? I downloaded an other sample application in the internet but has the same issue. My account is admin@wwhp0.onmicrosoft.com**
Sample app: https://drive.google.com/drive/folders/18mljMbF-BwS1rci1SttFOlBVrF4hRlSS
My account created from this program: https://developer.microsoft.com/en-us/microsoft-365/dev-program

Here is the steps I have done:
- Go to Teams--> Developer Portal--> Import App
- Publish App, Try to click Prevew in Team but not successful (Manifest error )
- Go to Microsoft Teams admin center--> Approve the above App
- Come back Team-->Apps: Search the above App
- Click in it and select add to Team, select Team and channel
- Got error "UpdateBotTeamMembershipInSkypeFailed"

<img width="539" alt="image" src="https://user-images.githubusercontent.com/23382935/163232984-b7064c4f-4c1e-4246-8cf3-28e4cad0b030.png">

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/23382935/163232345-bbd23f6b-dae4-4c6c-b1f2-3e5f74b8d02b.png">
<img width="945" alt="image" src="https://user-images.githubusercontent.com/23382935/163232634-c12fa007-eb79-4ae0-b402-c4a316bb981b.png">

I also found that when I clicked in the Preview in Team, it also has Manifest error but not sure what's the error
<img width="946" alt="image" src="https://user-images.githubusercontent.com/23382935/163232870-abe094ba-21d7-40d4-8ba4-7c5e98454f8d.png">
after closing the below popup, i got an alert
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/23382935/163235000-8f0f0c32-8db4-4a7b-9ee3-7713f394763a.png">

**Comment by Porkai-Pandian** [comment]
Hi @jimmymaise,

Can you please confirm for which app (author or user) this manifest is related to and where you've taken this manifest file, because it is missing below sections, kindly use manifest file from [this](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/master/Manifest) location

- permissions
- validDomains
- webApplicationInfo

**Comment by jimmymaise** [comment]
Thank @Porkai-Pandian . 

I tried to use the author manifest from the place you mentioned. But it still does not work
[app-author.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8485524/app-author.zip)
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/23382935/163294407-1f681a7f-5791-4648-b2be-2e3fc3b62fb7.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/23382935/163294208-a6254d8e-6a11-44fb-92be-253aad8ff4e3.png">
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/23382935/163294301-c4e5bc17-8079-4947-afbe-e0ad265bbb51.png">

**Comment by Porkai-Pandian** [comment]
Hi @jimmymaise,

I'm trying to understand your testing here, I see you updated some random URL's to valid domain and resource, please let us know if you are following the correct steps as mentioned [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages) to create the zip file.

![image](https://user-images.githubusercontent.com/87537966/163311996-afc0cbda-b7dc-4412-8f7b-53e3b6ccb227.png)

**Comment by jimmymaise** [comment]
Hello, 

I found the issue: 
I didn't add MS Team as a channel of the bot.
