### ISSUE TITLE
How to delete the role assignment if it cannot be updated?

### ISSUE THREAD

**Issue by nahcyrret** [OfficeDev/microsoft-teams-apps-company-communicator#701]
![ARMDeployError](https://user-images.githubusercontent.com/39899353/163666126-a2aa468a-cd41-4f50-9c5c-c0c6575926c9.png)

How to delete the role assignment if it cannot be updated?

{
"additionalInfo": null,
"code": "ResourceDeploymentFailure",
"details": null,
"message": "The resource operation completed with terminal provisioning state 'Failed'.",
"target": null
},
{
"additionalInfo": null,
"code": "RoleAssignmentUpdateNotPermitted",
"details": null,
"message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated.",
"target": null
},

**Comment by gsv022** [comment]
Hi @nahcyrret ,
You might have attempted multiple deployment with same GUID, as per suggestion it is recommended to have new GUID’s generated for each deployment if it is performed in same subscription. Please update the below values and re-try the deployment. 

![image](https://user-images.githubusercontent.com/98143492/163821085-11fe79b0-3032-4f3a-8233-d88fa5f92eb8.png)

**Comment by nahcyrret** [comment]
Do you mean I can change the above GUID to any values? Can I just change the last character of all the GUID to "1"?

**Comment by gsv022** [comment]
Hi @nahcyrret ,
The value should be a valid GUID. You can generate GUIDS using online tools like [this.](https://www.guidgenerator.com/online-guid-generator.aspx)

**Comment by nahcyrret** [comment]
The deployment script had been run before with a long resource group name and failed to create the key vault. So, it was rerun with a shorter resource group name. Is it necessary to delete the resources created in the long resource group name (as this resource group contains resources other than those for company communicator, I don't want to delete wrongly) or it doesn't matter as it will not affect the deployment in the new shorter resource group name?
How to proceed in this situation?

**Comment by gsv022** [comment]
Hi @nahcyrret,
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
