### ISSUE TITLE
Issue with Company Communicator V5.0 Upgrade

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-company-communicator#702]
We are facing issue with the ARM template deployment for Tech News/Company Communicator V5.0 upgrade in Production where we are getting the below error and the deployment is failed. We tried with resync the appservice and all 3 azure function after point to External Git Repos v5.x branch and then tried the ARM template redeployment again but it still failed.

{
"code": "DeploymentFailed",
"message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
"details": [
{
"message": "There was a conflict. Conflict with existing ScmType: ExternalGit"

This issue seems to be the same as #695

**Comment by gsv022** [comment]
Hi @EYSue ,
We will be releasing a separate MSBuild fix today. We will keep you updated once we release the fix.

**Comment by EYSue** [comment]
Hi MSFT

This is great news, please let me know as soon as this is available.

Regards

Sue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by EYSue** [comment]
Hi

We tried to resync all the 3 azure function again by pointing to Company Communicator GitHub V5.x branch but it is still failing with the below message.
![image](https://user-images.githubusercontent.com/91881396/164701609-e97cd94c-4a0f-4916-9b4e-638f7eb69c04.png)

 
When I checked the Github branch the yesterday code changes are pushed to the master branch and not to the V5.x branch from where we are syncing the code to the azure function and app service for V5.0 upgrade. Would you please guide after discussion with the developers whether we should use master branch itself for syncing the latest code or the yesterday code changes will be pushed to V5.x branch also for us to use to for V5.0 upgrade.


![image](https://user-images.githubusercontent.com/91881396/164701650-dd6b949f-fd18-4c45-a85f-dbf4132363a6.png)
![image](https://user-images.githubusercontent.com/91881396/164701675-9f6ac5b2-3a39-4ae8-8282-e72064224738.png)

**Comment by EYSue** [comment]
Hi

We tried to resync all the 3 azure function again by pointing to Company Communicator GitHub V5.x branch but it is still failing, I added full details and screenshots to Github ticket #702

Regards

Sue

**Comment by gsv022** [comment]
Hi @EYSue ,
We request you to use the master branch to upgrade the app to 5.0.

V5.x is a backup branch created that does not have the latest code as in master.

**Comment by EYSue** [comment]
We tried to run arm template deployment using master branch as per below path but still get these below errors.
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOfficeDev%2Fmicrosoft-teams-company-communicator-app%2Fmaster%2FDeployment%2Fazuredeploy.json

Error Logs: 
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    },
    {
      "code": "RoleAssignmentUpdateNotPermitted",
      "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    }
  ]
}

When we tried to resync the app service with master branch this time it failed with the below errors. But rest all the 3 azure functions got synced with master branch successfully.

Error details:
Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN @fluentui/react-context-selector@0.52.1 requires a peer of [scheduler@>=0.19.0](mailto:scheduler@%3e=0.19.0) but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of [type-fest@^0.13.1](mailto:type-fest@%5e0.13.1) but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of [webpack-hot-middleware@2.x](mailto:webpack-hot-middleware@2.x) but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of [webpack-plugin-serve@0.x](mailto:webpack-plugin-serve@0.x) || 1.x but none is installed. You must install peer dependencies yourself.
up to date in 80.397s
npm WARN [jest-config@26.6.3](mailto:jest-config@26.6.3) requires a peer of [ts-node@>=9.0.0](mailto:ts-node@%3e=9.0.0) but none is installed. You must install peer dependencies yourself.
npm WARN [jsdom@16.4.0](mailto:jsdom@16.4.0) requires a peer of [canvas@^2.5.0](mailto:canvas@%5e2.5.0) but none is installed. You must install peer dependencies yourself.
npm WARN [sass-loader@10.1.1](mailto:sass-loader@10.1.1) requires a peer of [node-sass@^4.0.0](mailto:node-sass@%5e4.0.0) || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN [sass-loader@10.1.1](mailto:sass-loader@10.1.1) requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN [ws@7.4.6](mailto:ws@7.4.6) requires a peer of [bufferutil@^4.0.1](mailto:bufferutil@%5e4.0.1) but none is installed. You must install peer dependencies yourself.
npm WARN [ws@7.4.6](mailto:ws@7.4.6) requires a peer of [utf-8-validate@^5.0.2](mailto:utf-8-validate@%5e5.0.2) but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@2.1.2](mailto:fsevents@2.1.2) (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@2.1.2](mailto:fsevents@2.1.2): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
Building the client app (this can take several minutes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@1.2.13](mailto:fsevents@1.2.13) (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@1.2.13](mailto:fsevents@1.2.13): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@1.2.13](mailto:fsevents@1.2.13) (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@1.2.13](mailto:fsevents@1.2.13): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@2.3.2](mailto:fsevents@2.3.2) (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@2.3.2](mailto:fsevents@2.3.2): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})


> [company-communicator@5.0.0](mailto:company-communicator@5.0.0) build D:\home\site\repository\Source\CompanyCommunicator\ClientApp
> react-scripts build

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [company-communicator@5.0.0](mailto:company-communicator@5.0.0) build: `react-scripts build`
Failed exitCode=1, command=npm run build
npm ERR! Exit status 1
npm ERR! 
An error has occurred during web site deployment.
npm ERR! Failed at the [company-communicator@5.0.0](mailto:company-communicator@5.0.0) build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2022-04-22T15_07_45_218Z-debug.log
npm WARN @fluentui/react-context-selector@0.52.1 requires a peer of [scheduler@>=0.19.0](mailto:scheduler@%3e=0.19.0) but none is installed. You must install peer dependencies yourself.\r\nnpm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of [type-fest@^0.13.1](mailto:type-fest@%5e0.13.1) but none is installed. You must install peer dependencies yourself.\r\nnpm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of [webpack-hot-middleware@2.x](mailto:webpack-hot-middleware@2.x) but none is installed. You must install peer dependencies yourself.\r\nnpm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of [webpack-plugin-serve@0.x](mailto:webpack-plugin-serve@0.x) || 1.x but none is installed. You must install peer dependencies yourself.\r\nnpm WARN [jest-config@26.6.3](mailto:jest-config@26.6.3) requires a peer of [ts-node@>=9.0.0](mailto:ts-node@%3e=9.0.0) but none is installed. You must install peer dependencies yourself.\r\nnpm WARN [jsdom@16.4.0](mailto:jsdom@16.4.0) requires a peer of [canvas@^2.5.0](mailto:canvas@%5e2.5.0) but none is installed. You must install peer dependencies yourself.\r\nnpm WARN [sass-loader@10.1.1](mailto:sass-loader@10.1.1) requires a peer of [node-sass@^4.0.0](mailto:node-sass@%5e4.0.0) || ^5.0.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN [sass-loader@10.1.1](mailto:sass-loader@10.1.1) requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN [ws@7.4.6](mailto:ws@7.4.6) requires a peer of [bufferutil@^4.0.1](mailto:bufferutil@%5e4.0.1) but none is installed. You must install peer dependencies yourself.\r\nnpm WARN [ws@7.4.6](mailto:ws@7.4.6) requires a peer of [utf-8-validate@^5.0.2](mailto:utf-8-validate@%5e5.0.2) but none is installed. You must install peer dependencies yourself.\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@2.1.2](mailto:fsevents@2.1.2) (node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@2.1.2](mailto:fsevents@2.1.2): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@1.2.13](mailto:fsevents@1.2.13) (node_modules\webpack-dev-server\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@1.2.13](mailto:fsevents@1.2.13): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@1.2.13](mailto:fsevents@1.2.13) (node_modules\watchpack-chokidar2\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@1.2.13](mailto:fsevents@1.2.13): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@2.3.2](mailto:fsevents@2.3.2) (node_modules\react-scripts\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@2.3.2](mailto:fsevents@2.3.2): wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\n\r\n'react-scripts' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! [company-communicator@5.0.0](mailto:company-communicator@5.0.0) build: `react-scripts build`\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the [company-communicator@5.0.0](mailto:company-communicator@5.0.0) build script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     D:\local\AppData\npm-cache\_logs\2022-04-22T15_07_45_218Z-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\96.40113.5578\bin\Scripts\starter.cmd deploy.cmd

**Comment by gsv022** [comment]
Hi @EYSue,

1. It seems that the deployment got failed. So, the existing resources needs to be deleted. Re-deployment has to be done from the start and during this please update GUID's as mentioned below.

2. . **Role assignment issue:**-
The mentioned issue can occur if customer might have attempted multiple deployment with same GUID, it is recommended to have new GUID’s generated for each deployment if it is performed in same subscription.
 
Please ask customer to modify the highlighted fields with newly generated GUID’s and continue with deployment.


-  Go to [GUID Generator](https://www.guidgenerator.com/online-guid-generator.aspx). Copy unique GUID and paste it in the parameters below.

![image](https://user-images.githubusercontent.com/98143492/165026853-17f154f6-cddb-4fa3-8e1e-d638ba946ad0.png)

3. After the updation, if the app service got failed then go for re-sync option.

**Comment by EYSue** [comment]
We tried to run arm template deployment using master branch again and this time it is completed successfully without any error.

But when tried to resync the app service with master branch this time it failed again with the below errors. But rest all the 3 azure functions got synced with master branch successfully.
 
![image](https://user-images.githubusercontent.com/91881396/165077457-b06cf4ce-bcf7-49a0-955c-84b2861baa5b.png)

**Comment by v-royavinash** [comment]
We cross verified at our end of the app service re-deployment is working as expected or not. It seems to be working as expected.
Hence the issue customer is facing is specific to the CC instance of their deployment. Could you please confirm what’s the instance of the App service plan that has opted during deployment (S1 or S2)? 
 
![image](https://user-images.githubusercontent.com/94480537/165110843-6ab46d30-f769-4a56-acdb-0c6696321739.png)

Also, allow us some time to investigate the probable cause of the error.

**Comment by gsv022** [comment]
Hi @EYSue ,
We are closing this issue as it was cleared over the call. You may also always open a new issue for further assistance on issues related to Company Communicator.
