### ISSUE TITLE
Security issue for open to the internet resources

### ISSUE THREAD

**Issue by musentur** [OfficeDev/microsoft-teams-apps-company-communicator#705]
Security department stated that some services launched with the company communicator is open to the internet which is a security risk and they are asking for restricting access to these resources. Is it possible to help us for assessing whether it is possible to restrict access to these resources and what will be the effect of this?

**Comment by gsv022** [comment]
Hi @musentur ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
