### ISSUE TITLE
Customize Message Subject Line

### ISSUE THREAD

**Issue by RobWood1** [OfficeDev/microsoft-teams-apps-company-communicator#707]
Hi, please could you advise how to change the subject line of the message. Currently set to "Sent a card" but we would like to customize it. I found this article but can't see where to update in the code base: https://techcommunity.microsoft.com/t5/iis-support-blog/how-to-change-notification-text-when-bot-sends-an-adaptive-card/ba-p/1945008 

Guidance would be much appreciated 👍

**Comment by gsv022** [comment]
Hi @RobWood1,
We won't be able to assist on the customization part. If you have any enhancement suggestions please do let us know. Post our internal review we may consider it for future sprints.

**Comment by gsv022** [comment]
Hi @RobWood1 ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
