### ISSUE TITLE
Update Cost Estimate section

### ISSUE THREAD

**Issue by pgriziotti** [OfficeDev/microsoft-teams-apps-company-communicator#708]
From version 5 we recommend the S2 plan for the service plan. the cost estimation pages are not updated in the 
"Sku recommendations" section and in the "Estimated cost" section

**Comment by gsv022** [comment]
Hi @pgriziotti,
Thanks for your suggestion. We have already taken a note of it and we will be updating it in upcoming releases and will also keep you updated.

**Comment by gsv022** [comment]
Hi @pgriziotti ,
We are closing this issue request and please feel free to reach out to us on the deployment or functionality issues of Company Communicator app by logging the new issue.
