### ISSUE TITLE
Company communicator deployment error

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#709]
Hi Github support team,

We have a CC App deploy successfully, but we found the Azure Service App component sync fail. (Other 3 functions sync success). 
We tried to re-sync but the sync task fail in a minute, although the Git repo has set and correct.
Appreciate you can share some advice, thanks for advance 

The following is the sync log

---------------------------------------------------------------------------------------------------------------------------------------------------  

Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.16.7 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
up to date in 82.078s
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-hot-middleware@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
npm WARN jest-config@26.6.3 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
Building the client app (this can take several minutes)
npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.2.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.2.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.7 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.5.7 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN The package papaparse is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

> company-communicator@4.1.5 build C:\home\site\repository\Source\CompanyCommunicator\ClientApp
> react-scripts build 

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
Failed exitCode=1, command=npm run build
npm ERR! errno 1
An error has occurred during web site deployment.
npm ERR! company-communicator@4.1.5 build: `react-scripts build `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the company-communicator@4.1.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\local\AppData\npm-cache\_logs\2022-04-26T09_08_27_678Z-debug.log
npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.16.7 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-hot-middleware@2.x but none is installed. You must install peer dependencies yourself.\r\nnpm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.\r\nnpm WARN jest-config@26.6.3 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN sass-loader@10.2.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN sass-loader@10.2.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN ws@7.5.7 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN ws@7.5.7 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN The package papaparse is included as both a dev and production dependency.\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):\r\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})\r\n\r\n'react-scripts' is not recognized as an internal or external command,\r\noperable program or batch file.\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! errno 1\r\nnpm ERR! company-communicator@4.1.5 build: `react-scripts build `\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the company-communicator@4.1.5 build script.\r\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     C:\local\AppData\npm-cache\_logs\2022-04-26T09_08_27_678Z-debug.log\r\nC:\Program Files (x86)\SiteExtensions\Kudu\96.40113.5578\bin\Scripts\starter.cmd deploy.cmd

**Comment by v-royavinash** [comment]
@rex-ma ,

This seems an issue with npm install. Can you please try below steps and let us know if this fixes the issue,

- Go to the Deployment center. Click on **Disconnect**.

![image](https://user-images.githubusercontent.com/94480537/165309010-18d87656-c668-4f95-8019-4b986823b945.png)

- Wait for 5 to 10 minutes until the entry under the **LOGS** tab will be deleted automatically. 

![image](https://user-images.githubusercontent.com/94480537/165309211-2dc939e8-af60-47a6-b579-8740521d14e6.png)

- Once the disconnection is completed. Go to  Settings and select External Git and add below URL and branch name.

![image](https://user-images.githubusercontent.com/94480537/165309348-b4c8c096-e074-4c49-ac05-31231334bc6c.png)


- https://github.com/OfficeDev/microsoft-teams-apps-company-communicator.git
- **Branch Name:** **master** (If you are using older version of CC, please select the branch name accordingly.)

Click on **Save** and then on **Sync**. Verify if the re-deployment is successful.

**Comment by gsv022** [comment]
Hi @rex-ma ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
