### ISSUE TITLE
Clarification about the Cancel the sending messages option

### ISSUE THREAD

**Issue by JorgeALeitao** [OfficeDev/microsoft-teams-apps-company-communicator#716]
QQ just to clarify the just launched release 5.1

•	Cancel option to allow customers to cancel the sending messages

Is it to cancel a batch that has just been triggered and still in been processed or to delete a post that was sent a few hours or days ago?

Thanks!

**Comment by gsv022** [comment]
Hi @JorgeALeitao ,
The **cancel** option is to cancel a batch that has just been triggered and still in been processed.

**Comment by gsv022** [comment]
Hi @JorgeALeitao ,
For now we are closing this issue request as we provided the necessary information.
Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
