### ISSUE TITLE
Problems using send to teams and send to team members.

### ISSUE THREAD

**Issue by caiodente** [OfficeDev/microsoft-teams-apps-company-communicator#717]
Hi, I'm just having trouble using send to teams and send to team members. For everyone I haven't tested it yet and the group one is working fine. What can it be, please?
image error:

![image](https://user-images.githubusercontent.com/65661915/165938594-561bebfa-a8d3-479d-9c52-1b3aa2c04af1.png)
![image](https://user-images.githubusercontent.com/65661915/165938614-f367c82c-648d-4a65-b450-d36dca6a379d.png)
![image](https://user-images.githubusercontent.com/65661915/165938736-60a3af04-8fb7-4f47-8b63-670e307c5f7f.png)

**Comment by gsv022** [comment]
Hi @caiodente ,
Go to issue no-**8** in this [Troubleshooting Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message)
Probably it will help you to solve this issue.
