### ISSUE TITLE
Messages did not send out to all users by using option 'send to Teams members'

### ISSUE THREAD

**Issue by pikachuxmoonpal** [OfficeDev/microsoft-teams-apps-company-communicator#718]
Messages did not send out to all users by using option **'send to Teams members'**

**Notice :**
1. Only 1 member of the Teams didn't receive any messages from **'Company Communicator'**
2. The member in [1.] is **an admin** who set up/installed custom app in MS Teams

**Screen Capture :** Total 4 files
- Admin Screen (who set up/installed custom app in MS Teams)
![image](https://user-images.githubusercontent.com/21459360/166208048-538b9a71-0854-43b0-9b93-d81f499b0c57.png)

- Sender (author) & Other Receivers Screen
![image](https://user-images.githubusercontent.com/21459360/166208107-be025b0d-8355-4edf-9c8c-2a6529a29ff6.png)
![image](https://user-images.githubusercontent.com/21459360/166209462-7ece06ce-0d40-4c75-bba6-5ed718c5d9d9.png)

- Sending Result Screen
![image](https://user-images.githubusercontent.com/21459360/166208325-6a242c9d-8384-44b9-8cf9-1ad0f5683ade.png)

**Comment by pikachuxmoonpal** [comment]
> 

Hi @gsv022 , 
Please advise, how/where to get the error code

**Comment by gsv022** [comment]
Hi @pikachuxmoonpal ,

- Click on the message where one user didn't receive the message. Click on **export detailed results**. Then go to chat section-->Click on **allow**. Download the Zip file.
  <img width="616" alt="image" src="https://user-images.githubusercontent.com/98143492/166619791-c93a6d71-2397-4b1a-bff0-828c0cfc25ec.png">

- To get the error code, please go for **application insights** in the resource group which you created.
  <img width="953" alt="image" src="https://user-images.githubusercontent.com/98143492/166627596-7602a30e-1bc2-4364-9e34-61878fc974b9.png">

**Comment by gsv022** [comment]
Hi @pikachuxmoonpal ,
Could you please confirm the issue got resolved or not?

**Comment by gsv022** [comment]
Hi @pikachuxmoonpal ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up. Thank you!

**Comment by JasthiKalyani** [comment]
Hi @pikachuxmoonpal,

We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
