### ISSUE TITLE
Error opening links - URGENT

### ISSUE THREAD

**Issue by aidab98** [OfficeDev/microsoft-teams-apps-company-communicator#721]
Hello,

When opening the link from the button, this error shows up. 
Any idea what the problem is. The link was opening before but now shows this error.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/86289425/167795229-86bb57a0-cba3-4a74-80fa-12ab01d4a15f.png)

**Comment by gsv022** [comment]
Hi @aidab98 ,
Could you please clarify like on clicking of which button is making you to direct to this page? Supporting screenshot would be more helpful.

**Comment by gsv022** [comment]
Hi again,
We will test the scenario from our end and will keep you posted.

**Comment by cristianoag** [comment]
@aidab98 - Link click tracking is not a feature of the official CC. Please open an issue at https://github.com/cristianoag/microsoft-teams-apps-company-communicator/issues if you still need help. @gsv022 - You can close this issue.

**Comment by gsv022** [comment]
Hi @aidab98 ,
We are closing this issue request as we don't provide support for customization.
Please do reach out to us if you face any issues with the functionality or deployment of the Company Communicator.
