### ISSUE TITLE
Message sending failed

### ISSUE THREAD

**Issue by shreebharaath** [OfficeDev/microsoft-teams-apps-company-communicator#723]
Hi Team ,

              When we try to send bulk messages using the company communicator App we are getting the below error for a certain group of people can you please clarify a few points

1. Should the Users app be installed for every receiver to receive a broadcast message 
2. Should Teams app be logged in in the last few days [ if the user has not used teams for 2 months will he get the message]
3. If the user is Part of AD with a M365 account but has not installed or used teams will the message get delivered to him 

![image](https://user-images.githubusercontent.com/39901961/168125749-1fa22840-57dd-4533-bb43-4a6b28d0ce70.png)

**Comment by JasthiKalyani** [comment]
Hi @shreebharaath,

1. Should the Users app be installed for every receiver to receive a broadcast message:
 Proactive installation plays an important role for user app installation. If Proactive installation is enabled and user app is uploaded at the Tenant level, user app will be installed automatically while the message is sent. However, if Proactive installation is set as false then app must be manually installed for every intended user.

2. Should Teams app be logged in in the last few days [ if the user has not used teams for 2 months will he get the message]: The message will be delivered for all the Active user for which User app is installed.

3. If the user is Part of AD with a M365 account but has not installed or used teams will the message get delivered to him : User should be an Active user of Teams.
