### ISSUE TITLE
Affect of Azure topic on CC

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#724]
Hello,

The new Azure topic had the following:
[Public preview: Control the minimum TLS version used with Azure Service Bus](https://azure.microsoft.com/ja-jp/updates/policy-to-control-the-minimum-tls-version-used-with-azure-service-bus-now-in-public-preview/)
[Enforce a minimum required version of Transport Layer Security (TLS) for requests to a Service Bus namespace (Preview)](https://docs.microsoft.com/en-us/azure/service-bus-messaging/transport-layer-security-enforce-minimum-version)
Is it possible to cause adverse effects such as transport problems?
Greetings.

 (CC:@ATshirai)

**Comment by gsv022** [comment]
Hi @MK202204 ,
We will look into this and reply you soon.
Thank you.

**Comment by v-royavinash** [comment]
@MK202204 ,
We are using minimum TLS 1.2 version for the resources created. We will review the impacts on CC but if you have any recommendation please do share with us.
