### ISSUE TITLE
Image does not load when the message is sent.

### ISSUE THREAD

**Issue by nona020** [OfficeDev/microsoft-teams-apps-company-communicator#725]
In draft, it shows image. Image is publicly available.( in blob storage) I can access from my private pc or mobile.

![image](https://user-images.githubusercontent.com/93933448/168550309-5bebdd75-70de-4503-ac5c-5fc7daae2137.png)
![image](https://user-images.githubusercontent.com/93933448/168550356-3a967c54-d1c4-4a10-a5d9-6bf1c43a482c.png)
 
I think that line should be the image…
 
![image](https://user-images.githubusercontent.com/93933448/168550273-a0cf0982-9ae5-49a0-9d71-a66fec8c38b9.png)

**Comment by gsv022** [comment]
Hi @nona020 ,
We are working on this and will get back to you.
