### ISSUE TITLE
Specified service namespace is invalid.

### ISSUE THREAD

**Issue by onlize** [OfficeDev/microsoft-teams-apps-company-communicator#726]
Hello,

I am at the step where I have to create a template. I fill out the form and click on Create. I receive error messages and I am not sure how to fix them:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":

[{"code":"ResourceDeploymentFailure","message":"Encountered internal server error. Diagnostic information: timestamp '20220517T183238Z', subscription id 'f7de535f-96c8-4c70-a710-e43a746e3277', tracking id '95a02f90-0268-4ccc-9699-49ad6b354e7e', request correlation id '1820d2e2-79f8-41b3-8b5b-84361f3a254f'."},{"code":"BadRequest","message":"The specified service namespace is invalid. CorrelationId: 1820d2e2-79f8-41b3-8b5b-84361f3a254f"}]}

Can you help me with this?
Thank you.

**Comment by JasthiKalyani** [comment]
Hi @onlize,

Could you please try using a different base resource name in lower case and kindly let us know if you are able to deploy.

**Comment by onlize** [comment]
Using different base resource name and different GUID numbers for all those roles fixed my issue. Thank you.
