### ISSUE TITLE
Read status from bot framework

### ISSUE THREAD

**Issue by ShalinShah84** [OfficeDev/microsoft-teams-apps-company-communicator#727]
Can we track if user has read the send messages or not in bot framework ?

**Comment by gsv022** [comment]
Hi @ShalinShah84 ,
Thanks for highlighting this feature.
We have already added it to backlog and will be taking up in future releases.

**Comment by Porkai-Pandian** [comment]
Hi @ShalinShah84, we're closing this issue since this feature is already added to our backlog and will be considered in future releases of CC based on the priority.
