### ISSUE TITLE
Company Communicator failed to upload CSV as Error the file is too big

### ISSUE THREAD

**Issue by MSFTHarry** [OfficeDev/microsoft-teams-apps-company-communicator#729]
There is an issue from my customer that when they uploads CSV with a picture it keeps always showing below error the file is too big, but in fact even there is only one email address with the CSV, it will be failed still except remove the image.

May I know if the app counts the whole things size together here? What's the limitation.
![169196395-94caa8c1-ba1e-4262-b16e-9319a1144534](https://user-images.githubusercontent.com/105835083/169306893-0a24fc54-4e93-40a2-81db-5ca7e775759c.jpg)

**Comment by JasthiKalyani** [comment]
Hi @MSFTHarry,

The deployed repository in the screenshot is referring to customized version of company communicator. We don't provide a feature to support CSV format upload. Hence we won't be able to provide assistance for customized features.

**Comment by MSFTHarry** [comment]
Hey @JasthiKalyani , but I saw below message in the FAQ, there should have this upload CSV feature
![image](https://user-images.githubusercontent.com/105835083/169344926-63993238-26f1-4b77-bc8d-d5c4f16c9068.png)

**Comment by cristianoag** [comment]
@MSFTHarry - This is a feature that is not part of the official CC version. It is a variant that has the CSV file upload feature. Please open an issue on https://github.com/cristianoag/microsoft-teams-apps-company-communicator/issues @JasthiKalyani - You can close the issue here.
