### ISSUE TITLE
Azure front Door Service Error

### ISSUE THREAD

**Issue by Veronica-RP** [OfficeDev/microsoft-teams-apps-company-communicator#730]
In October 2021 Company Communicator was succesfully installed in customer tenant. Last month they tried to change the name of the App from "HR Global" to "Sami News" and first it threw us error of an Azure service when they wanted to enter the "authors" app.

Here's the complete error: Oops!  We weren't able to find your Azure Front Door Service configuration. If it's a new configuration that you recently created, it might not be ready yet. You should check again in a few minutes. If the problem persists, please contact Azure Support 
 
Then with the support of the partner they re-implement both apps (authors & users), now it does not throw Azure error and allows to open the "Author" app but when they want to add the "user" app to some Teams team it throws us the following error message: "There was an error".

And if they try to send a message they get a log that the app is not installed.
![image](https://user-images.githubusercontent.com/105876246/169388189-f0608023-ee9b-46c6-afdd-b3d237480580.png)
![image](https://user-images.githubusercontent.com/105876246/169388263-08d6cca0-a555-4ae6-9d37-4b03e2fb7717.png)
![image](https://user-images.githubusercontent.com/105876246/169388328-f9a35114-88cf-4999-8061-2dfc38817d1c.png)

**Comment by gsv022** [comment]
Hi @Veronica-RP ,

- There might be issue in the manifest file of user. Please validate the manifest file in App Studio. 

<img width="554" alt="image" src="https://user-images.githubusercontent.com/98143492/169520117-1dfd4cde-e758-4b6e-8dc9-ed770b995b37.png">

- And share the manifest files for better troubleshooting from our end.

**Comment by Veronica-RP** [comment]
[SaMiNews 4.1.8.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8740609/SaMiNews.4.1.8.zip)
[Error VALIDATION SAMINEWS.pdf](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8740611/Error.VALIDATION.SAMINEWS.pdf)
Hi!

Here the files required.

Thank you!

**Comment by gsv022** [comment]
Hi @Veronica-RP ,

-In the manifest file, it seems that the version is 4.1.8. Could you please share the repo URL ?

**Comment by gsv022** [comment]
Hi @Veronica-RP ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Could you please confirm the issue got resolved or not?

**Comment by Veronica-RP** [comment]
Hello! getting more insight from the partner. Will instruct him to reply to this thread with details. Thank you!

**Comment by Veronica-RP** [comment]
hello!
They had another session and this is what happened:
1.	New packages were created, with the new icon "color.png" the icon was built based on good practices (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-package#outline).
2. They tested the packages before uploading them to The Teams admin in the portal https://dev.teams.microsoft.com/appvalidation.html, and we didn't have any bugs or warnings.
3. They updated the packages in Teams Central Admin. The new version was instantly displayed only for the Authors application, but for the User application it has not been possible to view the new version and 14 hours have passed.
Is there a way to view logs when custom apps are uploaded or installed in Teams or other suggestions?

**Comment by gsv022** [comment]
Hi @Veronica-RP ,
Could you please share the details what is happening when trying to upload the user app to the tenant/Teams central Admin. Supporting screenshots would be more helpful and share the manifest files of author and user too for better troubleshooting from our end.
