### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by shrnnd** [OfficeDev/microsoft-teams-apps-company-communicator#731]
When using company communicator to post message in General Channel of a selected Team, there is no notification.  Is there a way to turn on notification? 

Can the system auto stamp message author & message sender?  Currently, author & sender information do not appear on screen

**Comment by JasthiKalyani** [comment]
Hi @shrnnd 
kindly follow the below steps to enable the notifications
settings>>Notifications>>custom>>shown and pinned channels>>select "banner and feed" in the dropdown.
Regarding the author information display on screen, we don't have this functionality, we can add it to our backlog and take it in future release.

**Comment by Porkai-Pandian** [comment]
Hi @shrnnd, this feedback is already added to our backlog and will be incorporated in future releases of Company Communicator, hence closing this issue.
