### ISSUE TITLE
Redeployment error

### ISSUE THREAD

**Issue by raghavendrakumbhar** [OfficeDev/microsoft-teams-apps-company-communicator#733]
Hi, 

When I am trying to redeploy the company Communicator app.. getting deployment failed error. 

It says Source Control deployment failed. 

I am deploying through powershell for version 4.0

The error is coming pointing to line no 524 in the deployment script.

Kindly assist here.

**Comment by raghavendrakumbhar** [comment]
Hi @gsv022 ,  The first time deployment went without any issues using the script deployment. However, the issue is coming from 2nd time. In the powershell deployment script is failing on line no 524. The resources are getting created, but the output manifest zip files are not getting generated.  The issue might be happening due to some conflict from second time.

**Comment by JasthiKalyani** [comment]
Hi @raghavendrakumbhar,
Could you please send the screenshot of failed resources with the below steps:
Resource group>>deployments(open link below this and send the details of failed resources).
![CCdeployment](https://user-images.githubusercontent.com/104886868/171349019-4c169f56-b407-49d9-95c7-6f26820cb885.png)
