### ISSUE TITLE
The max length of configuration "AuthorizedCreatorUpns"

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#734]
Hi Team,

May I know the max length of configuration "AuthorizedCreatorUpns", thanks

Regards,
Rex

**Comment by gsv022** [comment]
Hi @rex-ma ,
The parameter-"AuthorizedCreatorUpns" is of string type. So the length can't be fixed. Let us know if you are facing any issue regarding the length of it and what's the no. of users you are trying to accommodate?

**Comment by rex-ma** [comment]
Hi @gsv022 ,
We are not trying to fix the length, but we want to know the current length limit.
We are not facing any issue, but we would like to do some planning.
Based on your reply, can I assume the parameter-"AuthorizedCreatorUpns" can contain unlimited character? even 10,000 users or more?

**Comment by rex-ma** [comment]
Hi team, any update?

**Comment by SankarMicrosoft** [comment]
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
