### ISSUE TITLE
Deployment error: ״Failed to create or update User app in Azure Active Directory״

### ISSUE THREAD

**Issue by OritOrlanczyk** [OfficeDev/microsoft-teams-apps-company-communicator#736]
az cmdlets with deprecated attributes need to update to:
az ad app update --id $app.appId --sign-in-audience "AzureADMultipleOrgs" --enable-access-token-issuance $AllowImplicitFlow
az ad app create --display-name $appName --sign-in-audience "AzureADMultipleOrgs" --enable-access-token-issuance $AllowImplicitFlow

**Comment by gsv022** [comment]
Hi @OritOrlanczyk ,
We are testing this scenario from our end and will keep you posted.

**Comment by markuspelto** [comment]
I'm having the exact same issue as OP. I tried to run the deploy.ps1 yesterday starting from fresh (including PowerShell modules), but it always fails, when it tries to create the azure ad apps. I checked that none of the apps were created. Ran the script step by step to confirm it fails to the azure ad app creation, even tho I'm running as global admin.

I need to try to fiddle with the az commands as recommended by OP.

**Comment by markuspelto** [comment]
@gsv022 I can confirm the fix. Made the following changes and it started to work.
Running PS 5.1 build 20222 rev 653
Az 8.0.0

Replaced in line 309:
This: az ad app update --id $app.appId --available-to-other-tenants $MultiTenant --oauth2-allow-implicit-flow $AllowImplicitFlow

With this: az ad app update --id $app.appId --sign-in-audience "AzureADMultipleOrgs" --enable-access-token-issuance $AllowImplicitFlow

And in line 323:
This: az ad app create --display-name $appName --available-to-other-tenants $MultiTenant --oauth2-allow-implicit-flow $AllowImplicitFlow

With this: az ad app create --display-name $appName --sign-in-audience "AzureADMultipleOrgs" --enable-access-token-issuance $AllowImplicitFlow

**Comment by gsv022** [comment]
Hi @OritOrlanczyk ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by OritOrlanczyk** [comment]
Hello, the script still has this issue... just had it with customer... please fix!
