### ISSUE TITLE
Message not sent to a large number of users "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond"

### ISSUE THREAD

**Issue by bchamnarnkit** [OfficeDev/microsoft-teams-apps-company-communicator#738]
Hi Team, Need help here. We are facing issues relating to communicator where some users are not getting messages and need to understand what the issue is. The error message we are getting for this set of users is "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond". This happens to almost 1,000 users out of 12,000 users sent to.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/84174370/170468744-5c66bf5a-0c8e-4d0b-8221-1f409a2b02ad.png">

Thanks in advance.

**Comment by gsv022** [comment]
Hi  @bchamnarnkit ,
These errors shared will required some analysis from our side. If required, we can get over call to troubleshoot it. We will keep you posted with update.

**Comment by bchamnarnkit** [comment]
Thanks for your. Do you happen to know what could potentially be causing this? I can also schedule a call  but if we have some assumptions or initial thoughts on why this is failing do let me know? Thanks

**Comment by bchamnarnkit** [comment]
Thanks @v-royavinash , I will work with my customer to try it and provide revert back if there are any issues
