### ISSUE TITLE
Company Communicator Stopped Sending to a Specific Dist. List which is was able to send to before. 

### ISSUE THREAD

**Issue by williamalee** [OfficeDev/microsoft-teams-apps-company-communicator#739]
Company Communicator Stopped Sending to a Specific Dist. List which is was able to send to before. 

The group has 18,528 members and contains actual recipients, not nested types.

**Comment by JasthiKalyani** [comment]
Hi @williamalee,

To get better view of the issue. Please provide your inputs for the below queries
- What is the version of the app that is deployed?
- When was the app deployed?
- Please confirm whether the proactive installation is active or not?
- Could you please share the **export results** if possible?

Supporting screenshots would be more helpful.
