### ISSUE TITLE
Company Communicator stuck on sending

### ISSUE THREAD

**Issue by navadjones** [OfficeDev/microsoft-teams-apps-company-communicator#740]
![image](https://user-images.githubusercontent.com/35564943/170718699-7549c4a0-4787-40a3-a048-e725856a7c86.png)

I have refreshed the tab multiple times but it seems stuck!

**Comment by JasthiKalyani** [comment]
Hi @navadjones,

The fsevents library is causing the app service deployment to fail. We are working on the fix and will keep you updated. To unblock the deployment please follow the below steps as a quick workaround,

1.  Go to portal.azure.com. Navigate to resource group where all CC resources are deployed.
2. Click on the App service -> Click on Configuration.
3. Click on WEBSITE_NODE_DEFAULT_VERSION.
4. Update the default value to 16.13.0 (previous value ->10.15.2).
5. Click on Overview and Re-Start the app service.
6. Once the app service is restarted. Navigate to Deployment Center and click on Sync.
7. Wait till the deployment is completed. You can validate this once the status changes to Success under logs.
![740_2](https://user-images.githubusercontent.com/104886868/170924587-55e548b7-6eb7-4930-8748-8482d901ea75.png)
![740_1](https://user-images.githubusercontent.com/104886868/170924600-d391aa77-22e5-416f-9c6c-f33d3e5537f2.png)

For azure function failure, please refer this troubleshooting guide [issue-1] (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting)

**Comment by navadjones** [comment]
Hi Jasthi,

I followed your steps but now get this error message on Teams

![image](https://user-images.githubusercontent.com/35564943/170956207-34bed36d-d0d4-4755-92c6-429de9125075.png)

**Comment by JasthiKalyani** [comment]
Hi @navadjones,

Could you please let me know your teams id so that we can connect over call to check the issue.

**Comment by navadjones** [comment]
@JasthiKalyani It's Kassie.navarasi@blackpool.gov.uk

**Comment by JasthiKalyani** [comment]
@navadjones, Could you please let me know your feasible time to schedule a call

**Comment by navadjones** [comment]
@JasthiKalyani Anytime now until 4:30pm

**Comment by JasthiKalyani** [comment]
@navadjones we will reached out to you over teams to continue the troubleshooting and analysis.

**Comment by navadjones** [comment]
@JasthiKalyani, no one contacted me

**Comment by laracloud123** [comment]
@JasthiKalyani we got the same problem. Do you have any suggestion? Your step you mentioned above didnt help :/

**Comment by navadjones** [comment]
Hi Jasthi,

It’s ***@***.******@***.***>

Thanks
kassie
