### ISSUE TITLE
How to upgrade from V1 to current (V5)?

### ISSUE THREAD

**Issue by mplwork** [OfficeDev/microsoft-teams-apps-company-communicator#743]
We seem to have version 1 installed and want to upgrade to the current version. The migration guides only tell to got one step at the time (1->2, 2->3 etc). Do we really have to do all those steps (and keep bothering our site admin with grant requests) or could this be done somehow in a single step?

**Comment by JasthiKalyani** [comment]
Hi @mplwork,
Yes, there is a way that can be done i.e., you have to go for a fresh deployment of specific version. If data loss is major concern, then migration is a better path as it follows incremental approach (1->2,2->3....).

**Comment by JasthiKalyani** [comment]
Hi @mplwork,

You have to delete previous resource group and create a new resource group for fresh deployment.

**Comment by JasthiKalyani** [comment]
Hi @mplwork,

We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
