### ISSUE TITLE
Messages fail to send to some users. Error: 403 The bot is not part of the conversation roster.

### ISSUE THREAD

**Issue by gracesivaya** [OfficeDev/microsoft-teams-apps-company-communicator#744]
Even though the app setting Proactive Install User App is set to true, the message fails to send to users who have never installed the bot. Error: 403 The bot is not part of the conversation roster.

![image](https://user-images.githubusercontent.com/77342295/171040501-0caa3dd3-eaba-40d7-b9cf-afc1541c13e9.png)

**Comment by Porkai-Pandian** [comment]
Hi @gracesivaya, this error normally occurs if the user bot is not installed to the users, did the customer choose proactive installation flag to true during the deployment which will automatically install the user bot?
