### ISSUE TITLE
Even after providing all the required permissions, send in chat to members of the following M365 groups, Distribution groups or Security groups option is Disabled.

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#746]
Already checked the workaround provided in the [troubleshooting](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#3-send-in-chat-to-members-of-the-following-m365-groups-distribution-groups-or-security-groups-option-is-disabled) page. 

All the necessary permissions are in place, but getting error as "Permission needed. Ask your IT admin to enable this option for you."

![image](https://user-images.githubusercontent.com/15922771/171095797-bc05a295-0ed2-4ca0-a90f-bd0efc24f2a9.png)

Please let me know what additional step needs to be done for enabling this option.

**Comment by JasthiKalyani** [comment]
Hi @PrithuMahisha, 

  What is the version of the app that is being deployed? 
               - a) For 4.x version, API permissions needs to be done for author app. There might   be chance that it has been 
                  done to user app. 
                - b) For 5.x version-->API permissions needs to be done for graph app. There might be chance that it has been 
                      done to user app or author app. 
     **Note** : For v5.x, if everything seems to be fine then check for secrets that are present in the key vault and compare with 
                   app registration secrets.  
Please let us know if you are still facing the issue.

**Comment by PrithuMahisha** [comment]
Hi @JasthiKalyani, 
Thanks for your response. We have deployed V5.0 and I verified that the permissions are added to the Graph app only. 
Still we are facing the issue mentioned.

**Comment by Porkai-Pandian** [comment]
Hi @PrithuMahisha, please check the steps mentioned in [troubleshooting guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#3-send-in-chat-to-members-of-the-following-m365-groups-distribution-groups-or-security-groups-option-is-disabled) and verify if the admin has granted the consent as mentioned in the troubleshooting guide.

**Comment by PrithuMahisha** [comment]
> 
Hi @Porkai-Pandian,
Yes, admin consent is also granted.

**Comment by PrithuMahisha** [comment]
Hi @JasthiKalyani ,
Please contact me on Mythili@devtenanttesting.onmicrosoft.com.
