### ISSUE TITLE
Message sent from Author app is not received for anyone in a Team. 

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#747]
Tried to send a message from the author app using 'Send in chat to members of the following teams'. But the message is not delivered to anyone. 
![image](https://user-images.githubusercontent.com/15922771/171097267-14218042-c348-431d-ab19-99fb8c076302.png)

While checking the status, it shows as below.
![image](https://user-images.githubusercontent.com/15922771/171097409-23d4d4b4-e822-4948-99f1-5ffad53ea4fe.png)

Then I clicked on download Export details Option. I am getting the message as follows. But I don't receive the report notification in the app. 

![image](https://user-images.githubusercontent.com/15922771/171097785-b1e50de0-c0b4-498e-97c8-400df3abc38e.png)

Not able to figure out what is the issue here. Can anyone please help on this?

**Comment by JasthiKalyani** [comment]
Hi @PrithuMahisha,

Could you please crosscheck the configuration once, if the details were updated correctly? Meanwhile please share the manifest files for better troubleshooting from our end.

**Comment by PrithuMahisha** [comment]
> 

Hi @JasthiKalyani 
I have attached the manifest file for your reference. 
[manifest.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8813714/manifest.txt)

**Comment by JasthiKalyani** [comment]
Hi @PrithuMahisha,

We have observed that, in the author manifest file "botId" is "internal-data-removed"(please refer the below attachment), here you have to provide the Author app registration client id.
<img width="288" alt="747" src="https://user-images.githubusercontent.com/104886868/171868326-0ffeca7c-1306-4198-ab20-f85528867907.PNG">
Kindly check the user manifest once, if bot id and "appdomain" were given correctly.

**Comment by PrithuMahisha** [comment]
> 

Hi @JasthiKalyani ,
I had intentionally made the botId value as 'Internal-data-removed' as it is a confidential data. Also the app domain value is given correctly.

**Comment by JasthiKalyani** [comment]
Hi @PrithuMahisha,

It seems that there are multiple issues, could you please share your team's id so that we can troubleshoot the issues over the call.

**Comment by PrithuMahisha** [comment]
> Hi @PrithuMahisha,
> 
> It seems that there are multiple issues, could you please share your team's id so that we can troubleshoot the issues over the call.

Hi @JasthiKalyani , this is my email ID - infosys.mythili@extaccount.com
