### ISSUE TITLE
Failed to deploy 

### ISSUE THREAD

**Issue by mahmoudabogewela** [OfficeDev/microsoft-teams-apps-company-communicator#748]
Hello, can someone help me 

I am trying to deploy the communicator on Azure but I got this failed massage 

{

    "status": "Failed",

    "error": {

        "code": "ResourceDeploymentFailure",

        "message": "Encountered internal server error. Diagnostic information: timestamp '20220531T083255Z', subscription id '4da2bc35-33d2-4a3d-a4f2-34449ff7dcef', tracking id 'cfad10db-d004-40fb-9124-2f22b06f89ca', request correlation id '9e12b29a-4581-4502-a2b4-9909916a694b'."

    }

}

**Comment by JasthiKalyani** [comment]
Hi @mahmoudabogewela,

Could you please send the screenshot of failed resources with the below steps:
Resource group>>deployments(open link below this and send the details of failed resources).
![image](https://user-images.githubusercontent.com/104886868/171134801-99fd8c32-7bf9-4051-8bb9-b798b53054ef.png)

Please try to follow the below points 
1. If any one of the function apps or App service got failed please try to resync and check.
2. If App service is failed please follow the below steps:
   Go to portal.azure.com. Navigate to resource group where all CC resources are deployed.
            -         Click on the App service -> Click on Configuration
            -         Click on WEBSITE_NODE_DEFAULT_VERSION.
            -         Update the default value to 16.13.0 (previous value ->10.15.2)
            -         Click on Overview and Re-Start the app service.
            -         Once the app service is restarted. Navigate to Deployment Center and click on Sync.
            -         Wait till the deployment is completed. You can validate this once the status changes to Success under logs.

**Comment by mahmoudabogewela** [comment]
It's working now, thanks

**Comment by JasthiKalyani** [comment]
Hi @mahmoudabogewela,

We are closing this request as we have provided the inputs for the query raised.If you face any issue with company communicator please raise a new issue for further assistance
