### ISSUE TITLE
Will Dynamic concurrency work for Company Communicator's Azure functions ?

### ISSUE THREAD

**Issue by ATshirai** [OfficeDev/microsoft-teams-apps-company-communicator#749]
Hello,
Last week, Microsoft has  released Dynamic concurrency in Azure Functions.
[Generally available: Dynamic concurrency in Azure Functions](https://azure.microsoft.com/en-us/updates/generally-available-dynamic-concurrency-in-azure-functions/)

Will it work for  Company Communicator's Azure functions?
We are using Company Communicator v4.1.0.

(CC: @MK202204)

**Comment by v-royavinash** [comment]
@ATshirai , 
Thanks for highlighting this. By default dynamic concurrency is not enabled for the Azure functions deployed in CC. But it can be manually enabled by adding required settings in the configuration part.

We are currently reviewing the impact on performance. But for now we don't have any specific plan to enable it with the default implementation.

**Comment by ATshirai** [comment]
@v-royavinash 
Thank you for reviewing this issue.

> we don't have any specific plan to enable it with the default implementation.

I 'm glad to get the answer like the above.
