### ISSUE TITLE
AzureAD PowerShell Error

### ISSUE THREAD

**Issue by sambetts** [OfficeDev/microsoft-teams-apps-company-communicator#750]
We get to the last stage, and the PowerShell fails:

```
Get-AzureADMSApplication : Object reference not set to an instance of an object.
At C:\Users\sambetts\Desktop\microsoft-teams-apps-company-communicator\Deployment\**deploy.ps1:739** char:12
+     $app = Get-AzureADMSApplication -ObjectId $applicationObjectId
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADMSApplication], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Open.MSGraphV10.PowerShell.GetMSApplication
```

My machine:
- Win11 - 21H2 - 22000.675
- PowerShell: 5.1.22000.653 (default PS shell)
- Module "AzureAD": 2.0.2.140

**Comment by JasthiKalyani** [comment]
Hi @sambetts,

Could please confirm if the app registration was created successfully. Looking at the error it seems the app registration creation failed because of which the object Id is coming as Null.

We will require the entire logs to analyze the possible cause of the issue. To keep you unblocked we would recommend using Manual deployment.

**Comment by sambetts** [comment]
Yep, it's created fine. Just the last stage:
```

Waiting for admin consent to finish...
The underlying Active Directory Graph API will be replaced by Microsoft Graph API in Azure CLI 2.37.0. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
Admin consent has been granted.
The underlying Active Directory Graph API will be replaced by Microsoft Graph API in Azure CLI 2.37.0. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
Account                           SubscriptionName              TenantId                             Environment
-------                           ----------------              --------                             -----------
admin@M365x352268.onmicrosoft.com Microsoft Azure Sponsorship 2 ffcdb539-892e-4eef-94f6-0d9851c479ba AzureCloud
Get-AzureADMSApplication : Object reference not set to an instance of an object.
At C:\Users\sambetts\Desktop\microsoft-teams-apps-company-communicator\Deployment\deploy.ps1:739 char:12
+     $app = Get-AzureADMSApplication -ObjectId $applicationObjectId
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADMSApplication], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Open.MSGraphV10.PowerShell.GetMSApplication

Graph application is already configured.

Generating package for authors...
Package has been created under this path C:\Users\sambetts\Desktop\microsoft-teams-apps-company-communicator\manifest\CC-authors.zip

Generating package for users...
Package has been created under this path C:\Users\sambetts\Desktop\microsoft-teams-apps-company-communicator\manifest\CC-users.zip

```

No other logs to send. 

Are there manual setup instructions for this? Can't see them in the documentation at least...

**Comment by sambetts** [comment]
For the record, I've tried on another VM, a WinServer 2019 machine and have the same result.

**Comment by JasthiKalyani** [comment]
Hi @sambetts,
Could you please send the screenshot of failed resources with the below steps:
Resource group>>deployments(open link below this and send the details of failed resources).
![CCdeployment](https://user-images.githubusercontent.com/104886868/171346184-f654048f-2b11-482d-be6c-930f0ca345b3.png)

meanwhile if you would like to go through manual deployment please check the below link
[Deployment-guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide)

**Comment by sambetts** [comment]
Hi, 

There are no failed deployments; all the Azure components in the resource groups are created just fine. For some reason the AD PS falls apart after running the deploy script. 

It just means the last stage has to be done by hand, which isn't the end of the world, but not great either.


// Sam

**Comment by GTPOCPROJ** [comment]
I face the same issue. Am not sure which part went wrongly. Look forward to the resolution.
