### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by mplwork** [OfficeDev/microsoft-teams-apps-company-communicator#752]
While deploying a fresh install I received this (XXXXXXXXXX redacted name 10 characters in length):

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"ResourceDeploymentFailure","message":"Encountered internal server error. Diagnostic information: timestamp '20220531T170427Z', subscription id '47375977-1c6e-460d-88cd-aaf8e007e1c1', tracking id 'dc1dece9-d665-499a-8dfd-511e4e524ee8', request correlation id 'ac9d2950-24cb-49f6-80a7-db0a4c7a3295'."},{"code":"VaultNameNotValid","message":"The vault name 'XXXXXXXXXXcommunicatorV5vault' is invalid. A vault's name must be between 3-24 alphanumeric characters. The name must begin with a letter, end with a letter or digit, and not contain consecutive hyphens. Follow this link for more information: https://go.microsoft.com/fwlink/?linkid=2147742"}]}
```

How to proceed?

**Comment by Porkai-Pandian** [comment]
Hi @mplwork,

Thank you for raising the query, please make sure to provide the base resource name (XXXXXXXXXXcommunicatorV5) not more than 18 characters, based on the base resource name, other resources name will be created. Azure has limitation to have the key vault name with maximum of 24 characters. Hence the deployment failed.

**Comment by mplwork** [comment]
Thanks for the reply. Maybe I wasn't clear but the real question is how to correct this now? The deployment created all sorts of things except this vault thing. Should I rerun the deployment but with a shorter resource name? Will this clean up the mess created?

**Comment by Porkai-Pandian** [comment]
Hi @mplwork, yes you need to perform new deployment again with short resource name, while deploying please make sure to change GUID's as mentioned [here](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#2-app-deployment-failure---roleassignmentupdatenotpermitted), you can delete the resource group that got created previously,
