### ISSUE TITLE
sourceControl deployment failed

### ISSUE THREAD

**Issue by vermagautam85** [OfficeDev/microsoft-teams-apps-company-communicator#753]
Even after adding Source "External Git" and repository, the deployment failed:
`Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)
npm WARN @fluentui/react-context-selector@0.52.1 requires a peer of scheduler@>=0.19.0 but none is installed. You must install peer dependencies yourself.
up to date in 55.38s
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-hot-middleware@2.x but none is installed. You must install peer dependencies yourself.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none is installed. You must install peer dependencies yourself.
npm WARN jest-config@26.6.3 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN node-fetch@2.6.7 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
Building the client app (this can take several minutes)
npm WARN sass-loader@10.1.1 requires a peer of node-sass@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@10.1.1 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})

> company-communicator@5.1.0 build C:\home\site\repository\Source\CompanyCommunicator\ClientApp
> react-scripts build

Creating an optimized production build...
Compiled with warnings.

src\components\OverFlow\sentMessageOverflow.tsx
  Line 53:32:  Expected '!==' and instead saw '!='  eqeqeq
  Line 53:74:  Expected '!==' and instead saw '!='  eqeqeq

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  385.39 KB  build\static\js\2.9c1bfd2a.chunk.js
  11.36 KB   build\static\js\main.5f619969.chunk.js
  2.9 KB     build\static\css\main.4cde98bd.chunk.css
  784 B      build\static\js\runtime-main.b28065c8.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

Building the application
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Microsoft.Teams.Apps.CompanyCommunicator.Common -> C:\home\site\repository\Source\CompanyCommunicator.Common\bin\Release\netstandard2.1\Microsoft.Teams.Apps.CompanyCommunicator.Common.dll
  Microsoft.Teams.Apps.CompanyCommunicator -> C:\home\site\repository\Source\CompanyCommunicator\bin\Release\netcoreapp3.1\Microsoft.Teams.Apps.CompanyCommunicator.dll
  Microsoft.Teams.Apps.CompanyCommunicator -> C:\home\site\repository\Source\CompanyCommunicator\bin\Release\netcoreapp3.1\Microsoft.Teams.Apps.CompanyCommunicator.Views.dll
  Restoring dependencies using 'npm'. This may take several minutes...
  Building the client app using 'npm'. This may take several minutes...
  Finished building the client app
  Microsoft.Teams.Apps.CompanyCommunicator -> C:\local\Temp\8da439c4379cd2d\
Creating app_offline.htm
KuduSync.NET from: 'C:\local\Temp\8da439c4379cd2d' to: 'C:\home\site\wwwroot'
Copying file: 'Microsoft.Teams.Apps.CompanyCommunicator.deps.json'
Copying file: 'ClientApp\build\asset-manifest.json'
Copying file: 'ClientApp\build\favicon.ico'
Copying file: 'ClientApp\build\index.html'
Copying file: 'ClientApp\build\manifest.json'
Copying file: 'ClientApp\build\image\imagePlaceholder.png'
Copying file: 'ClientApp\build\locales\ar-SA\translation.json'
Copying file: 'ClientApp\build\locales\de-DE\translation.json'
Copying file: 'ClientApp\build\locales\en-US\translation.json'
Copying file: 'ClientApp\build\locales\es-ES\translation.json'
Copying file: 'ClientApp\build\locales\fr-FR\translation.json'
Copying file: 'ClientApp\build\locales\he-IL\translation.json'
Copying file: 'ClientApp\build\locales\ja-JP\translation.json'
Copying file: 'ClientApp\build\locales\ko-KR\translation.json'
Copying file: 'ClientApp\build\locales\pt-BR\translation.json'
Copying file: 'ClientApp\build\locales\qps-ploc\translation.json'
Copying file: 'ClientApp\build\locales\qps-ploca\translation.json'
Copying file: 'ClientApp\build\locales\qps-plocm\translation.json'
Copying file: 'ClientApp\build\locales\ru-RU\translation.json'
Copying file: 'ClientApp\build\locales\zh-CN\translation.json'
Copying file: 'ClientApp\build\locales\zh-TW\translation.json'
Copying file: 'ClientApp\build\static\css\main.4cde98bd.chunk.css'
Copying file: 'ClientApp\build\static\css\main.4cde98bd.chunk.css.map'
Copying file: 'ClientApp\build\static\js\2.9c1bfd2a.chunk.js'
Copying file: 'ClientApp\build\static\js\2.9c1bfd2a.chunk.js.LICENSE.txt'
Copying file: 'ClientApp\build\static\js\2.9c1bfd2a.chunk.js.map'
Copying file: 'ClientApp\build\static\js\main.5f619969.chunk.js'
Copying file: 'ClientApp\build\static\js\main.5f619969.chunk.js.map'
Copying file: 'ClientApp\build\static\js\runtime-main.b28065c8.js'
Copying file: 'ClientApp\build\static\js\runtime-main.b28065c8.js.map'
Copying file: 'ClientApp\build\static\media\getFetch.582d29c4.cjs'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Light.14c3e6f0.eot'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Light.66561737.ttf'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Light.6d0fa9a8.woff'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Light.73e6fac8.svg'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Light.e8bd73e2.woff2'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Regular.59b42e51.woff2'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Regular.5da5870e.eot'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Regular.7239f6ef.svg'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Regular.a49d84c5.woff'
Copying file: 'ClientApp\build\static\media\TeamsAssets-Regular.ace6ce92.ttf'
Copying file: 'Connected Services\Application Insights\ConnectedService.json'
Copying file: 'de-DE\Microsoft.Teams.Apps.CompanyCommunicator.Common.resources.dll'
Copying file: 'es-ES\Microsoft.Teams.Apps.CompanyCommunicator.Common.resources.dll'
Copying file: 'fr-FR\Microsoft.Teams.Apps.CompanyCommunicator.Common.resources.dll'
Copying file: 'he-IL\Microsoft.Teams.Apps.CompanyCommunicator.Common.resources.dll'
Copying file: 'ja-JP\Microsoft.Teams.Apps.CompanyCommunicator.Common.resources.dll'
Copying file: 'ko-KR\Microsoft.Teams.Apps.CompanyCommunicator.Common.resources.dll'
Omitting next output lines...
Finished successfully.
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
Input string was not in a correct format.`

**Comment by v-royavinash** [comment]
@vermagautam85  Are you able to deploy the application following the steps shared above?

**Comment by JasthiKalyani** [comment]
Hi @vermagautam85,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, 
we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by vermagautam85** [comment]
Status of all App service and function is success but still getting attached error with "Configtab"
<img width="359" alt="Screenshot 2022-06-09 at 07 44 33" src="https://user-images.githubusercontent.com/106654581/172773276-3b1a89de-7bb2-454c-a2b8-afdf26ebee41.png">
.

**Comment by vermagautam85** [comment]
Stopped App Service, re-sync and then restarted app. Still no luck.

**Comment by gsv022** [comment]
Hi @vermagautam85 ,

Could you please confirm all the function apps and app service are showing the status as success after updating the node version.

**Comment by vermagautam85** [comment]
it did not solve after updating the node version but yes solved after new redeployment. This issue can be closed
