### ISSUE TITLE
Error "connection attempt failed" in "sent messages" report

### ISSUE THREAD

**Issue by timoleo23** [OfficeDev/microsoft-teams-apps-company-communicator#756]
When sending a message to users, we get lots of error messages of thet kind - Targeted audience: ~13K users | Number of error message in Teams "send report": ~2K => it's ~15% of send error

201 : System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

-2 : System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by v-royavinash** [comment]
@nanddeepn 
Thanks for sharing your observation.
We came across few customers facing similar errors for 4.x. We are checking at our end. We will keep you looped with updates.

**Comment by v-royavinash** [comment]
Hi @timoleo23 ,

The _connection attempt failed_ errors was thrown due to the Azure bot services and the issue has been fixed. Could you please re-try sending the messages and share the below observations.

- Volume of target audience
- Time taken to send the messages.
- Connection attempt failed count (If any related to )

**Comment by gsv022** [comment]
Hi @timoleo23 ,
Could you please share us the observations after sending the message.

**Comment by timoleo23** [comment]
We're planing to send a new communication to check if everything is back to normal.
