### ISSUE TITLE
Collapse Message sent by Communicator

### ISSUE THREAD

**Issue by stfenix** [OfficeDev/microsoft-teams-apps-company-communicator#758]
Hi, 

Is it possible to collapse the Text message sent with the company communicator so that the user has "read more" as per the attached WhatsApp image? Currently a wall of text is being thrown at the user and they need to scroll up to view the message from the top.
![image](https://user-images.githubusercontent.com/1441016/171629718-cc4dacfb-a569-443d-84bb-75386500072e.png)

**Comment by gsv022** [comment]
Hi @stfenix ,
Thanks for highlighting the feature. We have added it to the backlog and will implement in the future releases.
