### ISSUE TITLE
Unable to add CC Author App in the Teams to see the "Export detailed Results" file

### ISSUE THREAD

**Issue by Pkoli81** [OfficeDev/microsoft-teams-apps-company-communicator#760]
![image](https://user-images.githubusercontent.com/105282162/172329640-8cd19e57-a0a6-4fa1-a654-e33c8a2abcfa.png)
![image](https://user-images.githubusercontent.com/105282162/172329739-01a531cf-1076-4f68-a13e-839ad5af03ab.png)

**Comment by Pkoli81** [comment]
Hi Kalyani, 

Don't get any error, however, the only option is to add it to the Teams channel,
![image](https://user-images.githubusercontent.com/105282162/172387828-9303276a-6e1d-47b2-b826-a6e10f5a1860.png)
![image](https://user-images.githubusercontent.com/105282162/172387909-2d17410e-8e2c-4f17-9a3c-c436fae3fbd1.png)
![image](https://user-images.githubusercontent.com/105282162/172387968-fc95ba88-315c-45a3-bcd1-dc2d0fa5cf2a.png)
![image](https://user-images.githubusercontent.com/105282162/172388096-0217306a-fd7d-4c07-8321-26311f00cd19.png)
Then it comes here, I don't see any option to see the "Export Detailed Results" file, since it's grayed out

**Comment by Pkoli81** [comment]
The storage table still shows, export "in-progress"

![image](https://user-images.githubusercontent.com/105282162/172528069-1dccc726-e7f3-4ece-ab4b-08631255a53b.png)

**Comment by JasthiKalyani** [comment]
Hi @Pkoli81,

Previously there was a issue with bot services which is fixed now, could you please try resending the messages.

**Comment by Pkoli81** [comment]
The issue still persists, it doesn't fix itself.
