### ISSUE TITLE
Clicking on notification while creating message

### ISSUE THREAD

**Issue by l2marsha** [OfficeDev/microsoft-teams-apps-company-communicator#761]
This has an issue with both v4 and v5. This happens when you are in the Company Communicator Author app view and creating a message to send (both the message creation view as well as the send options view).

When you receive a message and click on the notification pop up in the bottom right, the background of your teams opens up to the chat but then you are stuck in the message view pane. You cannot click "esc", click the "x" button or "save as a draft" to get out of the view. The only way to get out is to close the Teams app completely and re-open it. Clicking "Save as a draft" will also not get you out of the view, but will create a draft every time you click it.

Screenshots are attached

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/88155490/172390847-8878e327-8241-436d-a2c8-05754ea53b46.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/88155490/172390870-158fb775-6833-498a-9682-8260c08f9f2a.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/88155490/172390897-96b18642-efb8-46ac-b3ec-3f6c27bbfeec.png)

**Comment by gsv022** [comment]
Hi @l2marsha ,
Thank you for the observation. We will test this scenario from our end and will keep you posted.

**Comment by SankarMicrosoft** [comment]
Not an issue
