### ISSUE TITLE
No login, requires additional permissions Error: CAA20004

### ISSUE THREAD

**Issue by JuliettaCOL** [OfficeDev/microsoft-teams-apps-company-communicator#762]
I have an application implemented version 5.0 in 2 Tenants, the configurations of:
- Authentication
- API Permissions
- Expose and API 
-
Are according to the guide, the Apps are registered in the O365 tenant and the template was executed in the Azure subscription tenant.

But when I try to load the Author App I get the following message: 

![issue](https://user-images.githubusercontent.com/107083999/172501504-ae3e25fa-8d38-41b6-9bb6-4f75de8df246.png)
![image](https://user-images.githubusercontent.com/107083999/172501842-7eeb482f-d8a1-44e9-bd04-694dd1bc9439.png)

What other option could I validate? appreciate the help.

**Comment by gsv022** [comment]
Hi @JuliettaCOL ,
Could you please share the manifest files.

**Comment by gsv022** [comment]
Hi @JuliettaCOL ,
The manifest files seems to be fine.  As the two icons were removed, we can't validate the zip file. Please do the following.
- Upload the M_Author.zip file containing   manifest.json,color.png, and outline.png in the App Studio and validate them. Do the same for user manifest as well. Keep us posted.
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/98143492/157594672-f776fbe2-e89b-4d33-9eb6-9a3896e44a88.png)

**Comment by gsv022** [comment]
Hi again,
Please share author and user manifest zip files containing manifest.json, color.png, and outline.png.

**Comment by JuliettaCOL** [comment]
[ManifestAutor.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/8870790/ManifestAutor.zip)

Sure! Thanks for your support

**Comment by gsv022** [comment]
Hi @JuliettaCOL ,
It seems that the color.png and outline.png are not in correct format. 
For Color.png-->192x192,  outline.png-->32x32. Please follow this dimensions and try to upload them. Keep us posted.

**Comment by JuliettaCOL** [comment]
Hi @gsv022 

As you requested, I made the change in the dimension of the icons but it still presents the error, in fact I installed again the version from scratch but the message continues. And I have another similar case, although the error message does not appear, it remains in a bug trying to log in, the same error reported here: 
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/772

**Comment by gsv022** [comment]
Hi @JuliettaCOL ,
Please share the MS Teams id, so that we can connect over the call and troubleshoot the issue.

**Comment by JuliettaCOL** [comment]
Sure!

erikaprieto@microsoft.com

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by JuliettaCOL** [comment]
Hello
Thanks for replying, I still keep the difficulty in two different tennat, I don't know if there is any additional recommendation I should keep in mind....

**Comment by JuliettaCOL** [comment]
Hello Team 

Any update on this issue? So far I can't find a solution, let me know if proxy policies could cause this?

**Comment by v-royavinash** [comment]
@JuliettaCOL  We will reach out to you over teams to troubleshoot the issue.

**Comment by gruiz-barbosa** [comment]
**Hi, I have the same problem, has anyone found a solution?**

**Comment by v-royavinash** [comment]
@gruiz-barbosa  There can be multiple reason of the same issue. Can you please log a new issue and share the complete details of the error. It would be great if you share the app insights logs while logging the new issue for troubleshooting.

**Comment by gsv022** [comment]
Hi @JuliettaCOL ,

Due to author inactivity, we are closing this issue. If you face any issue with company communicator please raise a new issue for further assistance and we are happy to discuss.

Thank you.
