### ISSUE TITLE
Sending message stuck on "Syncing Recipients"

### ISSUE THREAD

**Issue by OritOrlanczyk** [OfficeDev/microsoft-teams-apps-company-communicator#765]
Sending to everyone is still in progress for 4 hours already.
Function.SyncAllUsersActivity is still running.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/17028406/172870832-f8e3d5b4-1284-4156-929b-b617d289105a.png)

**Comment by gsv022** [comment]
Hi @OritOrlanczyk ,
Could you please confirm  if it is happening for remaining three sending options as well?

**Comment by v-royavinash** [comment]
Hi @OritOrlanczyk ,

Could you please try below steps and let us know your observations?

1.	You can send the messages and messages are delivered, but the status is not updating?
2.	If yes, 

  - Go to Azure portal. Go to the resource group where all the resources are deployed.
  - Go to azure function and open the 3 functions in different tabs with name *prep-function, *data-function, *-function.
  - Click on Deployment Center and then to logs and check what’s the status showing for all three functions.
  - If the status is showing as failed, please click on Sync to deploy the resources until the status changes to Success. Check and repeat for all 3 functions.
  - Re-start the functions and try sending the message and lets us know if it worked.

**Comment by OritOrlanczyk** [comment]
Yes, the status wasn't updated. There was a problem with data function, after syncing successfully we can see the final status.
Still need to re-send the message, waiting for Sunday to check since this is production environment.

**Comment by OritOrlanczyk** [comment]
@v-royavinash seem like the issue has resolved :)
Thank you for your help.
