### ISSUE TITLE
Secrets stored in storage container instead of Key Vault

### ISSUE THREAD

**Issue by nadishs** [OfficeDev/microsoft-teams-apps-company-communicator#767]
Hi ,
Why are webjobs secrets for this app stored in azure storage container shown above, and not in Key Vault? Is this not a security concern? Is this planned to be resolved?
container:
azure-webjobs-secrets
![image](https://user-images.githubusercontent.com/13271317/173326230-7bb35ee2-fb0e-4dfe-a6f3-e99eb2ad2efd.png)

**Comment by gsv022** [comment]
Hi @nadishs ,
We will look into it and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @nadishs ,
Thanks for your suggestion. This is as per the previous implementation. We will look into this and update accordingly.

**Comment by gsv022** [comment]
Hi @nadishs 
We have added the enhancement/feature in our backlog items and we will taking it in the future sprints depending on the priority and bandwidth.
