### ISSUE TITLE
Step 2.11 The Deployment "Outputs" Tab shows no outputs

### ISSUE THREAD

**Issue by rajivsr23** [OfficeDev/microsoft-teams-apps-company-communicator#77]
The Deployment was successful. In Step 2.11, it says to note down the values in the Deployment "Outputs" tab but it is empty. Please see the screenshot below-

Any help on this matter would be greatly appreciated!
<img width="337" alt="Deployments" src="https://user-images.githubusercontent.com/12613472/63466183-ba06e880-c430-11e9-9d7a-404c12a39201.PNG">
<img width="561" alt="Deployments_2" src="https://user-images.githubusercontent.com/12613472/63466244-e589d300-c430-11e9-8fe0-7f789142fc35.PNG">

**Comment by rajivsr23** [comment]
@aosolis  I still don't see the values in the Outputs tab. What do I need to do in order to make this work?

**Comment by juna-gupta** [comment]
The issue was addressed and verified. Closing the issue. Please re-open if you're still facing the issue.
