### ISSUE TITLE
Move to "Custom domain option" after deployed company communicator with Azure Front Door

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#770]
Hi Team,

May I know if we can move to "Custom domain option" after deployed company communicator with Azure Front Door?
If yes, may I have the procedures?

Thanks

**Comment by gsv022** [comment]
Hi @rex-ma ,
We will discuss it internally and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @rex-ma ,
This can be done. But we wont be able to hep out.
For more information please visit [Custom domain option](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Custom-domain-option)
