### ISSUE TITLE
The default branch was changed but not in ARM template

### ISSUE THREAD

**Issue by Mikhail2k15** [OfficeDev/microsoft-teams-apps-company-communicator#776]
You renamed the default branch last Friday but didn't do the same in ARM templates. You'll have a version hell. Please take a look at this PR #775

**Comment by v-royavinash** [comment]
Thanks @Mikhail2k15 for highlighting this.

The branch name was updated and auto approve with one of the PRs. We have an upcoming PR which is under testing which will update all files with main as default branch. For now, main and master both works and doesn't break during deployment. We will confirm same post our testing.

**Comment by Mikhail2k15** [comment]
IMO You have to merge this PR  #775 ASAP in other case you will have versioning hell. For those who is trying to deploy now will have 2 commit behind from the current.

**Comment by Porkai-Pandian** [comment]
Hi @Mikhail2k15, this was taken care with the [PR](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/pull/779), hence marking this issue as closed.
