### ISSUE TITLE
Select Image url from Sharepoint Library

### ISSUE THREAD

**Issue by raghavn** [OfficeDev/microsoft-teams-apps-company-communicator#777]
Hi,

We would like to store the images in Sharepoint library and use its url while composing message by authors.. We tried this, however images are not shown from sharepoint library, we have given permission to everyone except external users still it wont show.

Kindly guide us here

**Comment by v-royavinash** [comment]
Hi @raghavn ,

The images should with public and available on internet without any authentication. Can you please share the urls of images which you are trying to update?

Regards,
Avinash Roy

**Comment by raghavn** [comment]
Hi @v-royavinash ,

We are using Company Communicator app for intranet purpose, business will not agree to keep the images on internet with access to public. Kindly let us know if any alternative options..

**Comment by v-royavinash** [comment]
HI @raghavn , For now we don't have any alternative to it. However in upcoming 5.2 version we mostly will provide an option to upload the images which might solve your problem.

**Comment by gsv022** [comment]
Hi @raghavn ,

Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by captainhook** [comment]
Hi @SankarMicrosoft, is there any sort of ETA around this?

I can see there is a fork of this where this feature is available - https://github.com/cristianoag/microsoft-teams-apps-company-communicator

**Comment by SankarMicrosoft** [comment]
@captainhook ,
For now we don't have any alternative to it. However in upcoming 5.2 version we mostly will provide an option to upload the images which might solve your problem.
