### ISSUE TITLE
Company Communicator: Configtab - The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by stevenffrench** [OfficeDev/microsoft-teams-apps-company-communicator#778]
We are unable to use the publish the author bot to a channel, we always get the error 

Company Communicator: Configtab - The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by v-royavinash** [comment]
Hi @stevenffrench ,

Can you please check if the app service is deployed successfully?

> Go to the resource group --> app service --> Deployment Center --> Logs.

Verify if the status is Success. Also please share the screenshot with us with the URL and Log of the app service.

Regards,
Avinash Roy

**Comment by stevenffrench** [comment]
Screenshots below,  when we try to go to when we try to go to https://%appdomain%.azurefd.net/configtab <app domain hidden> we get that same message.

![500c2304-4e42-4c20-adf6-396fb59f2e88](https://user-images.githubusercontent.com/65608383/174688528-3b37116c-411c-4eda-9549-88bbaaefc803.jpg)
![7b4b99d4-4608-4f1f-82a0-1b7c0d9bbf3f](https://user-images.githubusercontent.com/65608383/174688535-5dd585ec-d0bc-4ca2-8701-9c3784168528.jpg)
![ac5a6f68-0a7c-4dbd-afa1-39d570751fc7](https://user-images.githubusercontent.com/65608383/174688539-e020598d-4831-4dd6-ab92-8018c9cd05d3.jpg)

**Comment by gsv022** [comment]
Hi @stevenffrench ,

In the logs it seems that **no deployments found**. Please click on **disconnect**(under External Git) in the settings.  Go to open Source-->click external git-->Paste the  repo URL and branch name. This will result in running the App service. Once the status is **Success(active)** in the logs, try sending the message again.

Please keep us posted.

**Comment by GTPOCPROJ** [comment]
same problem here

**Comment by cristianoag** [comment]
Folks, dev team changed the name of the branch from master to main. Just replace the branch to main and you will be fine. Dev team, you will have a lot of people complaining about that. I do recommend at least leave the master branch over there.

**Comment by cristianoag** [comment]
@stevenffrench - That is a different problem. I would recommend open a new issue on that and post the logs from application insights.

**Comment by cristianoag** [comment]
got it. maybe you can just create a new one called master with "git branch master <commit id>". for new deployments changing the deployment templates will fix. I'm more concerned about the rollouts that are already using master and will stop syncing.

**Comment by v-royavinash** [comment]
@stevenffrench ,
Author app UI is loading it means the app service is deployed successfully. Could you please check if the other 3 Azure functions are successfully deployed.

If any of the azure function deployment status is not Success, please perform the [steps](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-company-communicator%2Fwiki%2FTroubleshooting%23fix-3&data=05%7C01%7Cv-royavinash%40microsoft.com%7Ce72e0bae977b4c2e5c7408da53c67537%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637914409106845076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DRsJhqYoeflXSVj7F4zsBooHsbGxY09ueiST%2FZCR8B8%3D&reserved=0) to fix the deployment failure. Kindly restart the App service and Azure functions and re-try sending the message.

Even after successful azure functions deployment, if the issue remains, please share us the application insights logs for further troubleshooting. If you face any issue in generating the logs please share you MS teams alias.

**Comment by stevenffrench** [comment]
@v-royavinash Will you please detail the exact steps you meant to link to?  https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#fix-3 jumps to the middle of a set of steps.
