### ISSUE TITLE
Firmwide Message does not send after V5.0 Upgrade

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-company-communicator#782]
We have recently upgraded to V5.0 and successfully sent messages to targeted groups. Yesterday we tried to send a firmwide message for the first time and getting the following error
![image](https://user-images.githubusercontent.com/91881396/175282252-cd43e8aa-e68d-4409-9945-29ab572d2cc7.png)

**Comment by Mikhail2k15** [comment]
@EYSue from which version did you upgrade? 3.x or 4.x?
Could you post here the sync history for prep function?

**Comment by gsv022** [comment]
Hi @EYSue ,

Could you please confirm the issue got resolved or not? Please let us know.

Thank you.

**Comment by gsv022** [comment]
Hi @EYSue ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Comment by EYSue** [comment]
Hi Sai

Thanks for your help.

Regards

Sue
