### ISSUE TITLE
Cannot deploy second version of Company Communicator in same tenant

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-company-communicator#785]
Hi,

my customer is having an issue with the deployment of the second version of the Company Communicator in one tenant.

When deploying, the following error appears:

![deployment error](https://user-images.githubusercontent.com/69305126/175825857-bc53c531-1519-40f9-8ca5-8a6f79ada9ac.png)

Can you provide help with this issue?
Thank you

**Comment by gsv022** [comment]
Hi @apptemplatequestions ,

- Please try using different base resource name and different resource group.
- While doing the deployment, replace GUID's with newly generated [GUID]( https://www.guidgenerator.com/online-guid-generator.aspx) here
