### ISSUE TITLE
Issue: Failed to proactively install user apps, as well as message send state in failure!!

### ISSUE THREAD

**Issue by Sandeep-FED** [OfficeDev/microsoft-teams-apps-company-communicator#786]
1. App is not getting proactively installed to users.
2. Either messages are not sending. [PS: please find the attached image.]

**Kindly help on solving this issue**

![Failure](https://user-images.githubusercontent.com/36669540/175883465-089332d3-d841-4e15-8489-4808897db9b2.png)

**Comment by Sandeep-FED** [comment]
Hi @gsv022 ,

- User app is installed at Tenant level, permission policy has assigned only for specific user and blocked for other users(Since I'm deploying to production).
- And also the proactive installation is set to True by default.

**Comment by gsv022** [comment]
Hi @Sandeep-FED ,
Could you please share the export results.

**Comment by Sandeep-FED** [comment]
Hi @gsv022,

Sharing with you the export result. Kindly let us know a fix for this issue. Since its customer focused. 

Kindly do the needful

![175996263-2a67d60a-8a39-4d36-81bf-24f8c835bac9](https://user-images.githubusercontent.com/36669540/176595700-ef1dd288-a8c2-4ad7-acb6-cefaeb7e9229.png)

**Comment by gsv022** [comment]
Hi @Sandeep-FED ,

Since you mentioned proactive installation is set to true, can you try sending a message through 3rd sending option-? If already sent and the result was same as above then please share your teams id so that we can discuss the issue over the call.

Thank you.

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
