### ISSUE TITLE
Securing App service with vNet

### ISSUE THREAD

**Issue by raghav-nie** [OfficeDev/microsoft-teams-apps-company-communicator#787]
Hi,

We are having concerns from our business for keeping the app service open to public. We would like to know if the Company Communicator app works fine if we apply security changes to the public facing components like app service and function app, adding these to a separate vNet which is open to public.

If, yes request to please share us the steps to make this configuration work, please guide us on this. Thank you

**Comment by gsv022** [comment]
Hi @raghav-nie ,

We will discuss this situation with our team and get back to you with proper response soon.

Thank you.

**Comment by v-royavinash** [comment]
Hi @raghav-nie ,
Company communicator will work as expected even the resources are move in a vNET. The only requirement is author and user azure bot should be able to access the app service and the azure functions, storage.

We won't be able to help you in doing the customized configuration settings. However you can reach out to Azure support team for further configuration details and securing your resources.

**Comment by v-royavinash** [comment]
We provided the query response hence closing the issue.
