### ISSUE TITLE
Send message to all option - make it configurable

### ISSUE THREAD

**Issue by raghav-nie** [OfficeDev/microsoft-teams-apps-company-communicator#788]
Hi,

We have received concerns from business for keeping send message to all option enabled. because if by mistake the user app gets uploaded at tenant level, then the broadcast message will get sent to entire organization, which may be a bit risky option. 

Can you make the third option (send message to all) as configurable, and give option to enable or disable this feature through configuration parameter (may be through app service configuration). Coz only few in the organization have privilege to send message to entire organization. So, by making this option configurable we can control the risk which is a bit obvious from business side.

**Comment by v-royavinash** [comment]
Hi @raghav-nie ,

Thanks for the suggestion. As of now we don't have enable disable feature for the "Send to All" option. However the workaround is to disable proactive installation, so that even if the user app is uploaded at the tenant level, the message will not be sent for those users which doesn't have the app.

The other approach can be, to restrict the User app installation based on teams admin permission policy.

**Comment by raghav-nie** [comment]
Hi @v-royavinash ,

Thank you for your response.

So if we keep proactive installation as false, and upload the user app to only 2 teams and try below scenario what would be the result, please let us know.
1. User 1st option to send message in General channel of both teams where the user app is installed
2. Use 2nd option to send message in chat to members of both teams where the user app is installed
3. Use 3rd option to send message to everyone
4. Use 4th option to send message in chant to a any of the existing M365 group or distribution group.

Please let us know the result in each of above 4 scenarios. (Please note we will not upload the user app at tenant level, only uploading it to the 2 teams using custom upload option)

**Comment by gsv022** [comment]
Hi @raghav-nie ,
Closing this issue request as the query got answered in #790 and considering this as a duplicate.
