### ISSUE TITLE
Export popup screen getting stuck on Teams

### ISSUE THREAD

**Issue by raghav-nie** [OfficeDev/microsoft-teams-apps-company-communicator#789]
Hi, 

While testing the company communicator app, after sending the message when i clicked on export report it showed me popup "your export is queued" and asked to approve the request. I approved the request, however the teams popup is not going off even after clicking on the close button. I tried it several times but the popup isnt going. PFA attached screen shot.
Kindly help resolve the issue.
![popup_issue](https://user-images.githubusercontent.com/26272632/176927645-45c5e3c0-3e47-4aeb-9c6a-cded7eb3fd1b.PNG)

**Comment by v-royavinash** [comment]
@raghav-nie  Could you please sign out and sign in and re-try exporting. You will receive a bot notification with the export data in you teams.

**Comment by gsv022** [comment]
Hi @raghav-nie ,

Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by v-royavinash** [comment]
Closing the issue as duplicate. The latest conversation can be tracked #793
