### ISSUE TITLE
Hi @v-royavinash ,

### ISSUE THREAD

**Issue by raghav-nie** [OfficeDev/microsoft-teams-apps-company-communicator#790]
Hi @v-royavinash ,

Thank you for your response.

So if we keep proactive installation as false, and upload the user app to only 2 teams and try below scenario what would be the result, please let us know.
1. User 1st option to send message in General channel of both teams where the user app is installed
2. Use 2nd option to send message in chat to members of both teams where the user app is installed
3. Use 3rd option to send message to everyone
4. Use 4th option to send message in chant to a any of the existing M365 group or distribution group.

Please let us know the result in each of above 4 scenarios. (Please note we will not upload the user app at tenant level, only uploading it to the 2 teams using custom upload option)

_Originally posted by @raghav-nie in https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/788#issuecomment-1172029391_

**Comment by raghav-nie** [comment]
Ok @v-royavinash  Thank you for your response.

Just one more question, If we add someone to a team which is having Company Communicator app installed. then the user will get message if we use option 1 or 2, the app will get automatically installed to the user.

Consider a scenario where the user leaves the team, then he would still receive message if we send message using 3rd (send message to all) or 4th (send message to group) option as the app is still installed for them.

What options do we have if we want to automate uninstallation of app if user leaves a team and we don't want to send them message even if we use 3rd or 4th option?

**Comment by v-royavinash** [comment]
@raghav-nie If the user is a active on Teams and is part of Tenant then the user will receive the message through _Send to All_. And it make sense as _Send to All_ sends message to all members of the tenant.

Regarding the 4th option, if the users is removed from the Teams channel or DL, then message will not be delivered to that user.

As there are multiple other duplicate issues created. Closing this.
