### ISSUE TITLE
Upgrade functions to v4.0

### ISSUE THREAD

**Issue by spireob** [OfficeDev/microsoft-teams-apps-company-communicator#791]
Welcome,
Are there any plans to upgrade functions from version 3 to 4? 
Beginning on December 3, 2022, function apps running on versions 2.x and 3.x of the Azure Functions runtime can no longer be supported.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cin-process%2Cv4&pivots=programming-language-csharp

Durring validation there is one error:
Observation: Functions 4.x removes support for the WebJobs dashboard.
Recommended Action: Your Function app has a value set for the AzureWebJobsDashboard app setting, indicating you may be using the Azure WebJobs Dashboard for monitoring function executions. The Azure Functions 3.x runtime logs data to the WebJobs dashboard as a legacy feature; Azure Functions 4.x removes support for the WebJobs dashboard entirely.

and one warning:
Description: The correct pattern for using `HttpClient` with dependency injection is to request an `IHttpClientFactory` and use it to create an `HttpClient` instance. In Azure Functions 3.x, `HttpClient` is a registered service that can be requested directly. Azure Functions 4.x removes this service registration from the runtime, which will break customer code that does not follow the correct usage pattern.

Recommended Action: Ensure your code follow best practices for using HttpClient with dependency injection.

**Comment by gsv022** [comment]
Hi @spireob ,
Thanks for highlighting, We will discuss with our team and get back to you with proper response soon.

**Comment by v-royavinash** [comment]
@spireob  we're closing this issue since this feature is already added to our backlog and will be considered in future releases of CC based on the priority.

**Comment by AnotherCorto** [comment]
Does the latest release include Function App update? Couldn't see in the release log.
