### ISSUE TITLE
"Your export is queued" - pop is not going from teams

### ISSUE THREAD

**Issue by raghav-nie** [OfficeDev/microsoft-teams-apps-company-communicator#793]
Hi,

I went to the dashboard report on teams and clicked on one of the report and tried to download it. Received a message to approve the download request and also got a pop saying "your message is queued" (see attached screenshot).

Now, the pop is still there with "message your message is queued" even after closing it multiple times, the pop is not going at all. 
This behavior does not happen if i open teams using browser, however if we do it using teams client the popup is not going at all.

Kindly help!
![popup_issue](https://user-images.githubusercontent.com/26272632/177263061-b1c911b5-95b1-462d-afc7-8ea7885610f6.PNG)

**Comment by v-royavinash** [comment]
@raghav-nie ,
The behavior is not specific to company communicator as on the browser it seems working fine. We recommend you to sign out from Teams and re-try it. If the issue still persists its better to reinstall the teams and check.

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. As mentioned earlier, We are closing this issue. You may also always open a new issue or respond here if something does come back up.
