### ISSUE TITLE
Couldn't find Azure Front Door Service configuration

### ISSUE THREAD

**Issue by RIMAZ14** [OfficeDev/microsoft-teams-apps-company-communicator#794]
I have installed the app company communicator. But when I tried to add the registration card to a team, I always get the error "Page not found
Oops! We weren't able to find your Azure Front Door Service configuration. If it’s a new configuration that you recently created, it might not be ready yet. You should check again in a few minutes. If the problem persists, please contact Azure support" as you can see in the picture. In Azure portal the configuration are set to always on. How can I fix the error?

<img width="537" alt="Screenshot 2022-07-05 113734" src="https://user-images.githubusercontent.com/92548663/177299986-978a6861-a1de-4c85-95a8-3444e7ed9040.png">

**Comment by v-royavinash** [comment]
@RIMAZ14 , Either company communicator manifest is incorrectly configured or the app service deployment is not successful. 

- Can you re-confirm if the manifest has been uploaded with correct endpoints. Refer the [steps.](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#5-create-the-teams-app-packages)

- If yes, can you share the status of app service deployment? 
Go to app service --> Deployment center --> Logs and share us the screenshot.

**Comment by RIMAZ14** [comment]
@v-royavinash I checked the app package with Teams app validator and everything seems to be fine.

<img width="989" alt="Dep" src="https://user-images.githubusercontent.com/92548663/177933890-cc9799ad-1477-49c7-938e-3cd0da9d2588.png">

**Comment by SankarMicrosoft** [comment]
Hi @RIMAZ14, 
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
