### ISSUE TITLE
Page not found-issue when trying to add CC author application to channel in Teams

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-company-communicator#795]
Hi there,

I am working with a company that is currently trying to deploy and test the Company Communicator.
They have successfully deployed the solution, but when trying to install the author application in a channel, they are getting a "page not found"-error message (see screenshot attached).

Can you please help to debug this issue?

**Comment by apptemplatequestions** [comment]
![Page Not Found Company Communicator](https://user-images.githubusercontent.com/69305126/177554157-c40c80cd-0ccd-429e-80e3-6e8fe35f1c0c.png)

**Comment by gsv022** [comment]
Hi @apptemplatequestions ,
There might be chance that app service might got failed. Could you please check  whether it is pointing to intended repository and in the logs check for status. To reach app service.

Go to Azure portal-->Resource Group-->Click on App Service--> Deployment Center-->Settings(Check for repo url)-->Logs(Success/Failed)
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98143492/177586857-84763cc7-94df-4620-95a1-b8d37b283714.png">


Thank you.
