### ISSUE TITLE
PowerShell script is failing

### ISSUE THREAD

**Issue by Rafaelki** [OfficeDev/microsoft-teams-apps-company-communicator#796]
After executing the ARM templates and Admin consent permissions the script fails with 
```
Get-AzureADMSApplication : Object reference not set to an instance of an object.
At C:\R\Deployments\companycommunicatorv5\Deployment\deploy.ps1:739 char:12
```
I tried 2 different tenants with the same problem

![image](https://user-images.githubusercontent.com/24438807/177577840-b800bf2f-0f41-4570-a45d-7f48bb8159c7.png)

**Comment by gsv022** [comment]
Hi @Rafaelki ,

As you facing issue with PowerShell deployment, Can you please try manual deployment steps. Please refer the wiki for the deployment steps.

Thank you.

**Comment by gsv022** [comment]
Hi @Rafaelki ,

Thanks for your patience. For Powershell deployment if Azure CLI installed is of latest version, please uninstall it and try installing version 2.30.0 and continue the deployment.

Please keep us posted on this.
