### ISSUE TITLE
Failed to prepare the message for sending

### ISSUE THREAD

**Issue by jtournierit** [OfficeDev/microsoft-teams-apps-company-communicator#797]
Hi guys,

I have an issue with sending a msg, its strange, 2 weeks age it worked fine. Now it's look like this:
Failed to prepare the message for sending:The activity function 'DataAggregationTriggerActivity' failed: "Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://ccrenew.servicebus.windows.net/company-communicator-data/$management'. TrackingId:8156c34b-f641-47f0-a0cd-e6fb54242e2e_G44, SystemTracker:NoSystemTracker, Timestamp:2022-07-07T05:32:47". See the function execution logs for additional details.

**Comment by gsv022** [comment]
Hi @jtournierit ,

Could you please send the screenshot of previous sent successful messages and share the details of the error from Application Insight logs.

Thank you.

**Comment by SankarMicrosoft** [comment]
Hi @jtournierit ,
Please send the screenshot of the error from logs to proceed further.

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by jtournierit** [comment]
Hi,

You Can close task. When I restarted ServiceApp all started to work fine.

Best regards.
