### ISSUE TITLE
Unlicensed user behavior

### ISSUE THREAD

**Issue by 07JP27** [OfficeDev/microsoft-teams-apps-company-communicator#798]
I selected "Send to All" as the destination in the Company Communicator app and sent the message.
After sending, I exported the log details and checked the Message_Delivery.csv and found that the status of sending to accounts not licensed for Teams was "successful".
Is this expected behavior?

**Comment by gsv022** [comment]
Hi @07JP27 ,

We will check this scenario and get back to you .

Thank you.

**Comment by v-royavinash** [comment]
@07JP27 ,  Can you please create a test DL, add the unlicensed accounts to the test DL and try sending the message to the members of Test DL and share your observation on below points,

- Is the message was successfully delivered to those accounts?
- What's the message send status shown on the UI and export?

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
