### ISSUE TITLE
Company Communicator v5 not sending messages

### ISSUE THREAD

**Issue by dtyler3349** [OfficeDev/microsoft-teams-apps-company-communicator#802]
I have migrated Company Communicator from v4 to v5 and since the migration I am not able to send messages.  I am receiving the error message below
<img width="469" alt="Screenshot 2022-07-12 193558" src="https://user-images.githubusercontent.com/77506935/178615968-1bafe539-4af6-4c11-801b-11f0297b29e4.png">

I have checked permissions for the app and they are correct.

<img width="662" alt="Screenshot 2022-07-12 194154" src="https://user-images.githubusercontent.com/77506935/178616539-f405ea2a-bf86-404a-8da8-b6af4f37a430.png">

I do have a question about the 'secrets'.  Should it be the 'value' or the 'secret id' in the keyvault?  I do not know the value and it states that it can only be viewed immediately after creation and I do not have it written down.

<img width="773" alt="Screenshot 2022-07-12 194623" src="https://user-images.githubusercontent.com/77506935/178616878-ffeda15c-956a-4acd-b504-ff47d5e103e1.png">

Any help is appreciated.  Thank You

**Comment by SankarMicrosoft** [comment]
Hi @dtyler3349, 
Can you please try manual deployment steps. Please refer the wiki for the deployment steps.
Could you please delete the old Client Secret and create a new one. Please note down the secret value immediately after the creation this time. we will use this **"secret value"** for future deployments.

**Comment by dtyler3349** [comment]
Hi @SankarMicrosoft , I actually got this resolved and was just about to close this.  You are correct though, it was the Client Secret.  I had to create a new one for the User app and Author app and that fixed it.  Thanks
