### ISSUE TITLE
Change App name and logo

### ISSUE THREAD

**Issue by raghav-nie** [OfficeDev/microsoft-teams-apps-company-communicator#803]
Hi, 

Is it possible to change the name of the app and logo after the deployment.

Thanks,

**Comment by SankarMicrosoft** [comment]
Hi @raghav-nie ,
It is possible to change the name and logo of the app after the deployment.
It can be achieved in 2 ways.
1. We can change the Manifest ID in Physical folder do the upload and redeployment.
2. We can modify the Icon and Display Name under Resource Group > Bot Profile.

**Comment by bchamnarnkit** [comment]
Hi @SankarMicrosoft can you please confirm if this still works? I tried testing it out and seems like it is not possible to change it just in Azure (Your option 2) for it to be reflected. Please see how I have configured this below:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/84174370/190959556-3c0d538b-67af-4319-b0b6-1c769a167bba.png">
However, after waiting for 2-3 days it is still using the default logo as shown below in Teams 
<img width="905" alt="image" src="https://user-images.githubusercontent.com/84174370/190959647-045904c7-aa6b-42f7-aeb7-835852bd95b7.png">
I can confirm also that the logo is using a 30k max png as instructed in Azure Bot Profile configuration. Thanks
