### ISSUE TITLE
Multiple app deployment in a single Tenant

### ISSUE THREAD

**Issue by raghav-nie** [OfficeDev/microsoft-teams-apps-company-communicator#804]
Hi,

We have single Azure tenant, and we have deployed Company Communicator app in a separate resource group which is used as Test instance.

Now, we need to setup Production instance of Company Communicator app in the same tenant, we would be creating separate resource group for the same.

We are doing deployment using Manual approach.

Please let us know if we need change any paraments before the app deployment for production as its 2nd deployment in same tenant,

For Ex: Do we need to change the parameter value of User App ExternalId [Optional], the default value is 148a66bb-e83d-425a-927d-09f4299a9274. Do we need to update this with different value?

Anything apart from above if we need to change before deployment please let us know as this is our second app deployment in the same tenant with different resource group.

**Comment by SankarMicrosoft** [comment]
Hi @raghav-nie ,
1. Please let us know whether you are deploying both the instance of Company Communicator at the tenant level
2. If you are not targeting tenant level deployment, trying to deploy in two different teams, no need to change User App External ID.
3. If you are trying to deploy both the instance at tenant level, then have to change User App External ID and Manifest ID.
4. It's possible that the deployment can be failed and if it fails, please modify the all the GUIDs during the deployment and try again.
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss.

**Comment by raghav-nie** [comment]
Hi @SankarMicrosoft,

There are two things involved here, first one is deployment of ARM Company Communicator to Azure tenant and second one is when ARM deployment succeeds, create teams app zip files and upload to either Teams tenant level or only at Teams level.

My query is specific to first one, i.e ARM Company Communicator deployment to Azure tenant based on the manual deployment instructions given on your site.

We have already done the deployment of ARM Company Communicator app on azure resource group, uploaded the app zip file on few teams and verified its working fine. This was done for testing purpose.

Now we need to setup 2nd instance which will be used as Production, we have created 2nd Azure Resource group, now we need to once again deploy company communicator ARM deployment with manual deployment approach. 

So my query is , do we need to change any of the parameters before doing the 2nd ARM Company Communicator deployment or we can just complete the deployment with default parameter values only ??

Please let me know if i need to provide more details

**Comment by raghav-nie** [comment]
Just to give some more info,

We tried to deploy the 2nd instance of Company Communicator App ARM template to Azure with Manual deployment approach on a different resource group. The deployment is getting failed with multiple errors. The deployment was done keeping the parameters including all the GUIDs as default values.

Sharing below the error log details,

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."},{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."},{"code":"ResourceDeploymentFailure","message":"Encountered internal server error. Diagnostic information: timestamp '20220715T142441Z', subscription id '349ea109-6aab-490e-bacb-899d1008a960', tracking id '65e1003a-8727-40b4-96ed-a19cdce91b51', request correlation id '8b4df151-f010-4712-bf87-0021680eba38'."},{"code":"ConflictError","message":"A vault with the same name already exists in deleted state. You need to either recover or purge existing key vault. Follow this link https://go.microsoft.com/fwlink/?linkid=2149745 for more information on soft delete."},{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."},{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."},{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."},{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."},{"code":"RoleAssignmentUpdateNotPermitted","message":"Tenant ID, application ID, principal ID, and scope are not allowed to be updated."}]}

**Comment by SankarMicrosoft** [comment]
Hi @raghav-nie ,
Could you please do a deployment with a different set of GUIDs.
You can get new GUIDs in the below link,
https://www.guidgenerator.com/online-guid-generator.aspx
Once you have done the deployment, If you are facing any issue, Please send us a screenshot of the error.
It will help us to fix the issue quickly.

**Comment by gsv022** [comment]
Hi @raghav-nie ,

Could you please give us  the status.
