### ISSUE TITLE
Deploy location issue

### ISSUE THREAD

**Issue by tommyoo2** [OfficeDev/microsoft-teams-apps-company-communicator#805]
I just tried to deploy the app for a APAC resource account, however it shows an error:  this region has quota of 0 instance for your subscription.

May I confirm if we want to deploy the app in azure, must we have a resource account of US?
<img width="336" alt="Screenshot 2022-07-15 113716" src="https://user-images.githubusercontent.com/109327306/179145339-d0a159df-e5ed-48c2-8677-30dcee50b080.png">
<img width="365" alt="Screenshot 2022-07-15 113705" src="https://user-images.githubusercontent.com/109327306/179145344-10b43bc9-c398-42f7-90d7-496156533ef2.png">

**Comment by tommyoo2** [comment]
@SankarMicrosoft  I just use the Microsoft   [Visual Studio Enterprise Subscription](https://portal.azure.com/#)
5867633a-25ab-4c21-bf30-7bb4bb6d20c0

**Comment by tommyoo2** [comment]
any updates @SankarMicrosoft

**Comment by SankarMicrosoft** [comment]
Hi @tommyoo2 ,
Can you please check whether your subscription allows you to create two instances of App Service?
If not, you need to upgrade your subscription license.

**Comment by tommyoo2** [comment]
@SankarMicrosoft  if our subscription do not allow 2 instances, then if we change the location of the resource group to US, then we will still fail to deploy the app, is it? so I think we support that

**Comment by SankarMicrosoft** [comment]
@tommyoo2,
Can you please check whether your subscription allows you to create S2 instance of App Service?

**Comment by tommyoo2** [comment]
@SankarMicrosoft  may I know how to check whether my subscription allow S2 instance of App Service?

**Comment by tommyoo2** [comment]
@SankarMicrosoft  could you  please go back to the question I asked？
**May I confirm if we want to deploy the app in azure, must we have a resource account of US?**

**Comment by SankarMicrosoft** [comment]
@tommyoo2 
Please go to Your Resource Group > App Service > App Service Plan.
Send us the complete screenshot of App Service too. 
It will help us find the issue quickly.

**Comment by tommyoo2** [comment]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/109327306/180780000-b53af75b-2456-4798-8bc0-2b303d4425b7.png">

**Comment by tommyoo2** [comment]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/109327306/180780092-b4ef0ade-b539-422e-a461-a25a3bc76337.png">

**Comment by tommyoo2** [comment]
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/109327306/180781013-e14cd22e-40fd-4027-8fd2-53f6a43b328f.png">

**Comment by tommyoo2** [comment]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/109327306/180782064-e7e09124-ed59-43ee-9fef-43dee1c3fe55.png">

**Comment by tommyoo2** [comment]
@SankarMicrosoft  I cannot find any APAC resource groups in App Service plans. in above screenshot, I just use resource group (APAC) ----**tommyappAPAC_group**, however, this resource group cannot be found in the App Service plans
*you could check all info you want in above screenshots

**Comment by gsv022** [comment]
Hi @tommyoo2 ,

- When we click on **deploy to Azure** option in the deployment guide, the default location is East US. Please fill the template for this location.
- And in the above screenshot  status showing **validation failed** in that there is parameter called **Tenant Id**. Could you please fill that parameter as well while creating template and try validating it.

Please keep us posted.

**Comment by tommyoo2** [comment]
@SankarMicrosoft  as per discussion, I tried to put that parameter: tenant ID, but still failed to deploy it

**Comment by gsv022** [comment]
@tommyoo2 , have you tried the default location **East US**? If still causing the same issue. Please let us know

**Comment by tommyoo2** [comment]
@gsv022 @SankarMicrosoft 
  I mentioned before, when I select US resource group, then the deployment will be successfully done. 

The reason why I raise this ticket is to know **whether we support deploy the app for a non-us resource group**. because cx is from sg government, they do not want to deploy the app by using US resource group, also, if they just dare the app data will be stored in us, this should not be allowed by sg government


**could you please help escalate the ticket a bit to make sure we can get the result by Friday? and do not always let me to test and test again.**

**Comment by tommyoo2** [comment]
I have selected a us resource group, and the app was successfully deployed**, but this is not allowed by cx**

**Comment by gsv022** [comment]
@tommyoo2 ,Please neglect the previous response.

Regarding this, there are two level of checks, 
Check if Serverfarm is listed under the resource provider explorer.
- Check if **Serverfarm** is enabled for the specific region for specific subscription. 
- If both are true and valid and either choose another reason or check with Azure support team why they are not able to create App service plan for specific reason.  
![image](https://user-images.githubusercontent.com/98143492/181470595-61370563-72cf-433b-a54d-50c23ff27b6e.png)
![image](https://user-images.githubusercontent.com/98143492/181470666-c7b46bf3-6a90-446e-af47-d0ea58205021.png)

- For more information check out [Azure Products by Region](https://azure.microsoft.com/en-us/global-infrastructure/services/?products=storage,app-service,monitor,service-bus,functions)

**Comment by tommyoo2** [comment]
@gsv022  when  I checked the above information, I find:
1)  Serverfarm is enabled for the **South East Asia** for the subscription.
2) **South East Asia** server farm is not listed in the resource provider explorer. (When check in the image you provided)

**Comment by tommyoo2** [comment]
@gsv022 if South East Asia server farm is not listed in the resource provider explorer, can this indicate the resource group cannot be used to deploy this app?

**Comment by v-royavinash** [comment]
@tommyoo2 We request you to raise Azure Support Ticket and check with Azure Team why you are not able to create the app service plan for South East Asia. The issue/query specific to Azure subscription not related to the Company Communicator.
