### ISSUE TITLE
Company Communicator not showing up on Teams

### ISSUE THREAD

**Issue by navadjones** [OfficeDev/microsoft-teams-apps-company-communicator#807]
I had issues previously where the app was working for a bit, and then it suddenly got stuck on sending.

I was advised by a staff to make some changes but I tried the steps and the app stopped working altogether.
On the call, I was advised again to delete the whole thing and re-start from scratch.

I followed the steps but now after uploading the manifest zip onto Teams, I can see the app on the actual teams user interface.

**Comment by SankarMicrosoft** [comment]
Could you please provide the error screenshots. It will help us to fix the issue quickly

**Comment by navadjones** [comment]
So here's my teams admin where I've uploaded the communicator app.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/35564943/179705557-489d8fc5-4a6f-4efc-9484-214dacad1e75.png)

But on the teams app itself, i can't see the company communicator to add it to a teams channel.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/35564943/179705592-926fe4e2-78ea-4c0b-b2e5-7e7b13cdcec9.png)

**Comment by SankarMicrosoft** [comment]
Hi @navadjones ,
1) When the author and user manifest files are added to the Teams admin center it might take some time to get reflected. Just check it out today at the tenant level. If not available, please check for 2nd option

2)In the permission policies of Teams admin center, there might be chance that permission might have blocked for custom apps.
![image](https://user-images.githubusercontent.com/107609794/179959585-602d6351-cac3-4fc4-bb29-dd8ce84f74b7.png)

![image](https://user-images.githubusercontent.com/107609794/179959671-3d037c9a-de3f-4737-9a0c-a0ab961b118d.png)

**Comment by navadjones** [comment]
Hi Sankar,

I've managed to add the app via Custom app but still not able send messages:

***@***.***

**Comment by gsv022** [comment]
Hi @navadjones ,

Please try the below steps:
- As you mentioned that apps are visible in Teams admin center, please delete the Company communicator Author and Company communicator User.
<img width="845" alt="image" src="https://user-images.githubusercontent.com/98143492/180968778-05a3164a-fb81-4d00-9398-c4e0ea1c1246.png">

- Refresh the Teams Admin center and check for the apps related to company communicator if any missed from deleting.
- Go to the Tenant and try uploading directly. It won't take much time to get reflected.
- Add them to a specific  team and try sending a message.


Keep us posted.

**Comment by SankarMicrosoft** [comment]
Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by navadjones** [comment]
![image](https://user-images.githubusercontent.com/35564943/181713353-47eb6ee3-2c46-4300-b5f0-9bd6e3de2bcf.png)

So I've been able to add it to the Teams now but it's not picking up any group. It's just saying no match found

**Comment by gsv022** [comment]
Hi @navadjones ,

Please refer to question number **8** in [ troubleshooting guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting) to understand more on this issue, kindly let us know if it helped in resolving the issue”.

**Comment by navadjones** [comment]
Hi,

sorry i don't understand. Should this not apply to the whole organisation?

**Comment by v-royavinash** [comment]
@navadjones The 1st and 2nd option to send message are Teams specific. Teams to which you will explicitly add the User app will appear in the dropdown. You can use the 4th option to send to the DLs and 3rd option to send the organization wise message.

**Comment by gsv022** [comment]
Hi @navadjones ,

Could you please let us know the status of the issue.
