### ISSUE TITLE
User app installation notification

### ISSUE THREAD

**Issue by Mykhailo-D** [OfficeDev/microsoft-teams-apps-company-communicator#808]
When installing User app via Teams setup policy, users see a notification "Your IT admin has added a new app". Is there a way to add it silently, without any notification?

**Comment by SankarMicrosoft** [comment]
Hi @Mykhailo-D ,
This is not in a scope of Company Communicator application. This is a behavior of Admin Teams. We won't be able to provide any inputs on this.
