### ISSUE TITLE
Azure Front Door Capability not Shown on Architecture Diagram 

### ISSUE THREAD

**Issue by nyaladzi** [OfficeDev/microsoft-teams-apps-company-communicator#809]
We have a customer - that was advised to Use Azure Front Door when deploying the Company Communicator App

But in the Architecture Diagram here there is no Azure Front Door on this 

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Solution-overview

The customers Architecture review board needs the diagram showing the dependecy of Azure Front Door

**Comment by SankarMicrosoft** [comment]
Thank you for raising your concern. We are checking now. We will get back to you soon.

**Comment by v-royavinash** [comment]
We have the shared the updated architecture diagram over mail with front door dependencies. Let us know if any thing else is require or we can close the issue.
