### ISSUE TITLE
Master UPN Admin

### ISSUE THREAD

**Issue by Zeinab-mohamed-lotfy** [OfficeDev/microsoft-teams-apps-company-communicator#810]
There is a field in the deployment template named (Master UPN Admin) what this field is used for ?
There's no mention for it in the documentation.

**Comment by SankarMicrosoft** [comment]
Hi @Zeinab-mohamed-lotfy ,
Could you please update us which field you are referring to?
A Screenshot would help us to give the clarification quickly.
In our deployment guide, we have only Sender UPN List, a place where we will update email ids of the author of the company communicator. only those users mentioned here will be able to access company communicator app.

**Comment by Zeinab-mohamed-lotfy** [comment]
![Capture9](https://user-images.githubusercontent.com/82738064/180637814-62430c49-eb99-433e-8ece-bbb432add5fe.PNG)

**Comment by SankarMicrosoft** [comment]
@Zeinab-mohamed-lotfy This Seems to be some Customized Company Communicator app. Can you share us GitHub repo URL of the code that you are deploying it.

**Comment by Zeinab-mohamed-lotfy** [comment]
https://github.com/cristianoag/microsoft-teams-apps-company-communicator/wiki/Deployment-Guide

**Comment by gsv022** [comment]
Hi @Zeinab-mohamed-lotfy ,

- Thanks for sharing the guide link. It seems to be a customized version, we won't be able to provide assistance on this. 
- It is recommended to use this [Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) and consider the **main** branch. 


 Please let us know if you are facing the issues.
