### ISSUE TITLE
Company Communicator stops working from time to time and needs to be restarted in Azure with limited success

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-company-communicator#816]
Hi,

I am working with a customer that has the company communicator apptemplate deployed for a couple of months.
Since the initial deployment, the CC has been working unreliable, meaning:
- the app will stop working from time to time and stop sending out messages to employees
- the app then needs to be restarted in Azure which often results in the same message being sent out 2 times to the employees or not at all

The customer would like a fix for this solution as it is not user-friendly.

**Comment by SankarMicrosoft** [comment]
Thanks for highlighting, We will discuss with our team and get back to you with proper response soon.

**Comment by SankarMicrosoft** [comment]
Hi @apptemplatequestions ,
We will follow it up on Internal Issue, https://dev.azure.com/servicemgmt/MIFT/_workitems/edit/6251

**Comment by gsv022** [comment]
Hi @apptemplatequestions ,
We are closing this issue as it is conveyed that user is going to update it to the latest version. If you face any issue with company communicator please raise a new issue for further assistance.

Thank you.
