### ISSUE TITLE
does not send message

### ISSUE THREAD

**Issue by maye-vargas** [OfficeDev/microsoft-teams-apps-company-communicator#819]
When I send the communicator with the authors within a team in teams, they do not receive the card, and the communication is sent but it is correct: 0 and error: 0. I don't know what it could be.

**Comment by SankarMicrosoft** [comment]
Hi @maye-vargas Thanks for highlighting, We will discuss with our team and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @maye-vargas ,

- Could you please confirm that message is delivered to the respective user. Supporting screenshot would be more helpful.
- Is it happening to all the sending options or only to one of the sending options?
- And check whether function apps were deployed successful or not?
- If they are successful and issue persists then please share the app service logs.
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98143492/181744792-b4c4b9ff-01db-4645-8610-bba88c86dbc3.png">

**Comment by maye-vargas** [comment]
Hi @gsv022, 
1. Currently I do not have a screenshot since the implementation was carried out in production with a client, the process is carried out in sessions and currently I do not have screenshots. But the implementation issue in the app service, its status is correct (active).
2. When I send the communication, it is happening with all the communications that I send, they are sent but they never arrive and they are correct: 0, error: 0
3. The last time I reviewed them, your process was correct in the functions, but I would have to review them again.

I don't know what other service could check that this is the error?

**Comment by gsv022** [comment]
@maye-vargas , 
yes, please keep us posted on function apps working state and just to re-iterate "Is it happening to all the sending options or only to one of the sending options?"

**Comment by maye-vargas** [comment]
@gsv022 To all shipping options.}
Apart from the functions, what other topic could I review?

**Comment by v-royavinash** [comment]
@maye-vargas  There might be multiple reason of the above error. Below few configuration you can cross verify

- Check the status of Azure functions.
- Go to Graph App registration and verify if the Expose an API, Authentication and Manifest are updated as per the deployment guide.
- If above steps looks good, please go the application insights and share the the details error logs. It will give us the exact area it is throwing error.

**Comment by gsv022** [comment]
Hi @maye-vargas ,
Could you please share the status.

**Comment by maye-vargas** [comment]
![image](https://user-images.githubusercontent.com/86726190/182854344-4571acbc-9de6-4640-b01f-65fb4c922cbe.png)

**Comment by gsv022** [comment]
Hi @maye-vargas,

Please share the export details of the above message that you tried to sent.

**Comment by maye-vargas** [comment]
Thanks you, I managed to correct the error.
