### ISSUE TITLE
Issues in using Company Communicator App after Deployment

### ISSUE THREAD

**Issue by roset0130** [OfficeDev/microsoft-teams-apps-company-communicator#820]
Hi Team, 

Asking for your inputs on the error below after us deploying the Company Communicator application on Teams. We are able see the application on Teams but when we try to create/compose a message we are receiving this error. Appreciate your insights/help on this issue.

 
![CCerror](https://user-images.githubusercontent.com/110209823/181665329-5b931ec1-f7f7-43d9-a3da-2995e039ae9a.png)

**Comment by gsv022** [comment]
Hi @roset0130 ,
Can you check if the client secret you provided in your app service and/or Key Vault is the same as what you got from your app registration? 
From the error message, the secret provided may be 1) incorrect or 2) expired

**Comment by roset0130** [comment]
> 

Hi,

The client secret was newly generated when we deployed the applications using the Azure admin center. We also did not receive the error in deploying the application. But to be safe, how can we check the secret key on the app? We did not use the powershell deployment for your reference.

**Comment by gsv022** [comment]
@roset0130 , below are the steps to check if the client secret is expired or not, if expired provided the steps how to create newly and update it, please let me know if you've any follow up questions.

- To find author bot app id, go to Azure portal -> look for Company Communicator App services -> Configuration -> Author AppId

![image](https://user-images.githubusercontent.com/98143492/181808085-7306e9ce-293a-45e0-b50e-41159f6226ab.png)

- Click show values and copy the Id.

-  Go to App Registration and search for the app with id you copied above.

-  Go the author app registration -> Certificates & secrets -> Check for expiry date of the secret

![image](https://user-images.githubusercontent.com/98143492/181808218-42cb1c1d-6035-4589-89aa-e987cd412611.png) 
If the secret is already expired, click ‘New client secret’ and generate it

- Copy the value, navigate to the Azure key vault for Company Communicator -> Secrets -> update the AuthorAppPassword

![image](https://user-images.githubusercontent.com/98143492/181808294-59ddf2cc-92bb-4cd5-a295-b94705fdedba.png)

-  Restart the app services, function apps

**Comment by roset0130** [comment]
The Secret key is not expired, but when I go to Key Vault to check the ID, it says "List" is not enabled and I am not authorised to view the contents.
![image](https://user-images.githubusercontent.com/110209823/182114234-1636854a-3a83-4f65-9355-c86f2322ad77.png)

I'm clearly the Owner:
![image](https://user-images.githubusercontent.com/110209823/182113976-06e05607-04a5-42fd-acb5-5c67ff054333.png)

And I've allowed "List" under Access Policies:
![image](https://user-images.githubusercontent.com/110209823/182114123-12c3d27e-b271-49b5-85c0-d9971b30cc53.png)


Please check on what are the other options that we need to take to use the Company Communicator

**Comment by gsv022** [comment]
Hi @roset0130 ,

Did the above steps work and solved the issue? Please let us know.

Thank you.

**Comment by oed-mueckek** [comment]
Hello, maybe we have a problem with the secrets as well as the sign in log for the Communicator App says:
![CC-Error](https://user-images.githubusercontent.com/110909794/183645988-afa59e51-70dc-47f8-b9a4-15a863e67fa0.png)

I already changed the secret for the author app to a new one and restarted the app service and function apps, but no luck :(

any ideas?

**Comment by gsv022** [comment]
Hi @roset0130 ,

- Please do make sure that the secret value is being copied instead of  secret ID. 

<img width="756" alt="image" src="https://user-images.githubusercontent.com/98143492/183964972-2ee70545-7a71-44eb-a8df-64d7c45d0729.png">

- The copied secret value in author app should be pasted in configuration of app service. The same has to be done for prep-function and data function as well.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/98143492/183973236-63b6cf0d-0f62-4a5c-a290-cc961af2cbc8.png">

- Re-sync the app service and function apps again.

**Comment by gsv022** [comment]
Hi @roset0130 ,
Could you please let us know the status whether above steps helped or not.
