### ISSUE TITLE
Is `Under Implicit grant, check ID tokens.` required step?

### ISSUE THREAD

**Issue by runceel** [OfficeDev/microsoft-teams-apps-company-communicator#821]
The deployment guide has a step "Under Implicit grant, check ID tokens" on section "3. Set-up Authentication".

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication

Is this required step or not? I had un-checked those, and I have deployed Company Communicator. it worked fine.

**Comment by gsv022** [comment]
Hi @runceel ,
We are working on this scenario and will get back to you with proper response soon.

**Comment by runceel** [comment]
I found an issue #383.
@priyank29 guided un-checked steps.
If it is unnecessary step, I think removing the step is prefer for security.

**Comment by v-royavinash** [comment]
@runceel Our initial testing suggests the app works as expected even if we un-check the implicit grant tokens field. However we will have to do rigorous end to end testing before we confirm and update from the deployment guide. We will be internally reviewing and test it and make necessary modification in our future versions.

**Comment by runceel** [comment]
@v-royavinash Thank you for checking it. :)
A customer I faced does't allow this option, if un-checked is OK, deploying Company Communicator to production tenant is easyer than now.

**Comment by gsv022** [comment]
Hi @runceel ,
The issue has been added to the backlog already. We will review it and do the needful.
