### ISSUE TITLE
Allow download of reports only for specific people

### ISSUE THREAD

**Issue by ostumm** [OfficeDev/microsoft-teams-apps-company-communicator#823]
Hi all,

one of our customers is looking for the possibility to allow the download of reports only for specific people. Like we can configure the UPNs for authors, we might be able to configure UPNs for 'Allow Download Reports' in future, too. This is needed because of data privacy issues.

Would be nice if this could get on the list of future features if not already there

Looking forward

Cheers
Oliver

**Comment by v-royavinash** [comment]
@ostumm  Thanks for your inputs. We will review your request and consider it for future releases. Currently the Authors has access to download the reports. However as you pointed out it would be better if we separate the UPNs for download and actual authors.

**Comment by ostumm** [comment]
@v-royavinash many thanks for your answer and for your consideration. Hope it will make it into the code, as lots of customers in Germany pointing out dta privacy

**Comment by PrithuMahisha** [comment]
Hi Team, @v-royavinash,
Could you please provide answers for the following questions
1. When is the expected release of the next version which would have the enablement of this option.
2. Please provide more information about the retention policy of reports and messages in the current version - 
           i. How long the authors can download the reports, 
           ii. How long the messages will be available in the chat and posts.

**Comment by PrithuMahisha** [comment]
@v-royavinash Could you please provide some answers for the questions posted above?

**Comment by gsv022** [comment]
Hi @ostumm,
We have added the enhancement/feature in our backlog items and we will taking it in the future sprints depending on the priority and bandwidth.
