### ISSUE TITLE
Where to change senderUPNList?

### ISSUE THREAD

**Issue by nullvalueset** [OfficeDev/microsoft-teams-apps-company-communicator#824]
Hi,
Two questions:
1. Where to change senderUPNList when the app is up and running.
2. Can it be handled with group membership instead of exact user UPN?

**Comment by gsv022** [comment]
Hi @nullvalueset ,

- To change the SenderUPNList,

Go to Azure Portal-->Select the resource Group-->Click App Service-->Under Settings, select configuration-->Click AuthorisedCreatorUPNs-->Add semicolon in between id's
  
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98143492/182590237-a0492751-3ec5-4a0d-b8f1-2d043354b342.png">

- For the 2nd query, we will get back to you with proper response soon


Hope this helps

**Comment by gsv022** [comment]
Hi @nullvalueset ,

From our testing it is observed that only by keeping individual id's separated by **";"** will work as expected where as group id wont. Please make a note of this.

Thank you.
