### ISSUE TITLE
How to block access to the app service for non-Teams/CC app users?

### ISSUE THREAD

**Issue by infinitesimalinfo** [OfficeDev/microsoft-teams-apps-company-communicator#825]
Hi there - my security team is concerned that the creation of the app service with FQDNs ccxxx.azurefd.net and ccxxx.azurewebsites.net published to the internet presents a security risk. Since Company Communicator should only be used by the Teams client, how can I ensure that only the Teams app can access the app service?

They would like to see an unauthorised/blocked response when accessing  ccxxx.azurewebsites.net and ccxxx.azurefd.net with a web browser.

I have tried implementing an access restriction allowing only the Azure front door service tag but this blocks access from the Teams app as well. I have also tried to see if an Azure conditional access policy could help, however, I do not see the app service listed as a cloud app.

I know that this may be a little off-topic but I can't seem to find any guidance elsewhere.

Please help!

**Comment by gsv022** [comment]
Hi @infinitesimalinfo ,

Thanks for raising the query. We will get back to you with proper response soon.

**Comment by infinitesimalinfo** [comment]
> 

Hi @gsv022,

Thanks, I'm looking forward to your response.

**Comment by infinitesimalinfo** [comment]
I guess I'm looking forward to @v-royavinash's response?

**Comment by v-royavinash** [comment]
@infinitesimalinfo  As rightly pointed out the default implementation of CC does not provide any option to restrict it with in the same network. From technical point of view, app service can be configured to be accessible within the same organization. The overall idea is that the app service should be able to communicate with the Author and User bot.

However, we won't be able to help in configuring the customization as we provide support with the default version of CC.

**Comment by gsv022** [comment]
Hi @infinitesimalinfo ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
