### ISSUE TITLE
Company communicator does not work on ipads with version 15.6

### ISSUE THREAD

**Issue by casticod2** [OfficeDev/microsoft-teams-apps-company-communicator#828]
We have a large number of ipads with version 15.6 on which the CC by App does not work, neither author nor client. The screen remains blank. 
However, if the chat messages sent by CC are received (I insist that the failure only occurs if we enter through the pineada App and deployed by policies).
Meanwhile, if we test the app with the same user on teams with Windows, or on iPads with earlier versions (12.5.5) it also works.
Does it happen to anyone else?

**Comment by gsv022** [comment]
Hi @casticod2 ,
Thanks for raising the issue. We will look into it and get back to you with proper response soon.

**Comment by casticod2** [comment]
More Information: 
IOS 12.4.5 Teams Version 3.18.2 NOT WORK 
IOS 12.5.5 Teams Versions 3.18.0 WORK
IOS 14.0.1 Teams Version 4.14.0 NOT WORK
IOS 15.6.0 Teams Version 4.14.0 NOT WORK

**Comment by gsv022** [comment]
Hi @casticod2 ,
We currently won't support for this . Please let us know if you have any queries related  to Company Communicator.

Thank you

**Comment by casticod2** [comment]
Of course, my question is about company communicator, which is displayed correctly but is not visible on specific versions of Ipads, the page remains blank when opening the APP. 
However (using the same user) it is displayed correctly on other systems.

**Comment by gsv022** [comment]
@casticod2 , We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
