### ISSUE TITLE
Update version info in package.json

### ISSUE THREAD

**Issue by kushalbhabra** [OfficeDev/microsoft-teams-apps-company-communicator#830]
We've started using the v5.2.0 and it works good. Kudos to team!

Just noticed in deployment logs, it still displays v5.1.0. Suggest to update version info wherever applicable to avoid confusion during deployments.

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/2158df0bad5dc0446296b14f86e26663ba35a77e/Source/CompanyCommunicator/ClientApp/package.json#L3

**Comment by gsv022** [comment]
Hi @kushalbhabra ,
Thanks for highlighting. We will do the modification.

**Comment by gsv022** [comment]
@kushalbhabra , We have addressed this issue in the latest version so closing it out and please raise a new issue if you have any concerns related to Company Communicator.

Thank you.
