### ISSUE TITLE
Clear Teams cache - Suggestion for troubleshooting steps

### ISSUE THREAD

**Issue by kushalbhabra** [OfficeDev/microsoft-teams-apps-company-communicator#831]
While upgrading the app from v.5.1.0 to v5.2.0, it appeared that initially changes were not getting reflected. 

We then realized Teams client was picking client app resources (js and css) from cache. (Similar behavior on Teams web client)

It would be nice to add a troubleshooting step as "Clear cache" such as [in this article](https://docs.microsoft.com/en-us/microsoftteams/troubleshoot/teams-administration/clear-teams-cache) in case changes don't get reflected while testing version upgrade.

**Comment by v-royavinash** [comment]
@kushalbhabra Thanks for your suggestion. We have added clearing the cache steps in our FAQ and migration guide.

**Comment by kushalbhabra** [comment]
Awesome, thanks.
