### ISSUE TITLE
FTPS only alert in Azure Advisor recommendations

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#834]
Hi Teams,

Please kindly advise if we can follow the following remediation advises in Company Communicator, from Azure Advisor recommendations:

![Capture01](https://user-images.githubusercontent.com/25476072/183937416-56a597f6-0824-4182-ad99-60ef9e12172f.PNG)
![Capture02](https://user-images.githubusercontent.com/25476072/183937601-80d7a9b2-47d3-42bd-945b-1db08fd90ea2.PNG)
![Capture03](https://user-images.githubusercontent.com/25476072/183937700-e2397a5e-f5a8-4f9c-b58e-3df1049d4b5d.PNG)

Thanks

**Comment by gsv022** [comment]
Hi @rex-ma ,

We will look into this and get back to you with proper response soon.

Thank you.

**Comment by gsv022** [comment]
Hi @rex-ma ,
Our initial testing suggest that by changing the FTP state from **all allowed** to **FTP's only**, functionality remains undisturbed.
However as this is not part of official release.
