### ISSUE TITLE
Accessibility: Image Alt Text

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#837]
Hello,

I see Teams Adaptive Cards supports images having an Alt Text (at least in the "HTML Format for Office 365 Connector Cards' ([https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=connector-md%2Cconnector-html])

**Question: can I add an Alt-text to the image in the messages?**

Thank you.

**Comment by gsv022** [comment]
Hi @victorsimonlee ,
It cannot be customized from user point-of-view. Currently we will add it to the backlog and will review it later.

Thank you.

**Comment by gsv022** [comment]
Hi @victorsimonlee ,
We have added the enhancement/feature in our backlog items and we will taking it in the future sprints depending on the priority and bandwidth.
