### ISSUE TITLE
Changing the "Sent a card" message on the chat preview

### ISSUE THREAD

**Issue by Scheiderichv094** [OfficeDev/microsoft-teams-apps-company-communicator#838]
Is there a way to change the preview message from "Sent a card" to show the title within the message?

**Comment by v-royavinash** [comment]
@Scheiderichv094  We have Preview functionality before sending the message. The drafted message will be posted in the General channel of the Teams for Preview.

![image](https://user-images.githubusercontent.com/94480537/184406985-598e95d4-68a4-4057-a297-11f2f8c8899d.png)
