### ISSUE TITLE
Documentation (v5 migration) - Misleading Image

### ISSUE THREAD

**Issue by victorsimonlee** [OfficeDev/microsoft-teams-apps-company-communicator#840]
**2.  Register Azure AD application.**

- The image in this section shows a different name than the one suggested in the instructions 
- The image also shows a different option selected (multitenant) and the instructions says to select (Single Tenant)

[https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide](url)

**Comment by v-royavinash** [comment]
@victorsimonlee  Thanks for your suggestion. We have the updated migration guide with the correct image showing the single tenant selection.
Also, added steps to follow while upgrading from v5.x to latest version

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide

**Comment by victorsimonlee** [comment]
Thank you, it looks great.
