### ISSUE TITLE
App service fails to sync, deployment error when trying to deploy 5.2

### ISSUE THREAD

**Issue by infinitesimalinfo** [OfficeDev/microsoft-teams-apps-company-communicator#841]
Hello devs,

My v5.2 deployment is failing at the app service portion, when trying to deploy the template or sync the app service. I am using the deployment guide [arm template](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FOfficeDev%2Fmicrosoft-teams-company-communicator-app%2Fmain%2FDeployment%2Fazuredeploy.json).

The deployment error from the app service deployment log is as follows:

Command: deploy.cmd
Handling ASP.NET Core Web Application deployment.
Restoring NuGet packages
  Determining projects to restore...
  All projects are up-to-date for restore.
Restoring npm packages (this can take several minutes)

up to date in 27s

142 packages are looking for funding
  run `npm fund` for details
Building the client app (this can take several minutes)

> company-communicator@5.1.0 build
> react-scripts build

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './Tapable'
Require stack:
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\tapable\lib\index.js
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\webpack\lib\Compiler.js
Failed exitCode=1, command=npm run build
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\webpack\lib\webpack.js
An error has occurred during web site deployment.
- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\scripts\build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\tapable\lib\index.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\tapable\\lib\\index.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\webpack\\lib\\Compiler.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\webpack\\lib\\webpack.js',
    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\react-scripts\\scripts\\build.js'
  ]
}
node:internal/modules/cjs/loader:936\r\n  throw err;\r\n  ^\r\n\r\nError: Cannot find module './Tapable'\r\nRequire stack:\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\tapable\lib\index.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\webpack\lib\Compiler.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\webpack\lib\webpack.js\r\n- C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\react-scripts\scripts\build.js\r\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:778:27)\r\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\r\n    at require (node:internal/modules/cjs/helpers:102:18)\r\n    at Object.<anonymous> (C:\home\site\repository\Source\CompanyCommunicator\ClientApp\node_modules\tapable\lib\index.js:8:19)\r\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\r\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\r\n    at Module.load (node:internal/modules/cjs/loader:981:32)\r\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\r\n    at Module.require (node:internal/modules/cjs/loader:1005:19) {\r\n  code: 'MODULE_NOT_FOUND',\r\n  requireStack: [\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\tapable\\lib\\index.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\webpack\\lib\\Compiler.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\webpack\\lib\\webpack.js',\r\n    'C:\\home\\site\\repository\\Source\\CompanyCommunicator\\ClientApp\\node_modules\\react-scripts\\scripts\\build.js'\r\n  ]\r\n}\r\nC:\Program Files (x86)\SiteExtensions\Kudu\97.40711.5827\bin\Scripts\starter.cmd deploy.cmd

**Comment by v-royavinash** [comment]
@infinitesimalinfo  Could you please let us know if this is a fresh deployment or a migration from previous version of CC. 
If migration, please refer the resolution steps mentioned in the troubleshooting guide issue#14.

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#14-app-service-deployment-failed-while-sync-operation-with-below-error

**Comment by infinitesimalinfo** [comment]
@v-royavinash This is a fresh deployment. And syncing the app service does not work as described.

**Comment by v-royavinash** [comment]
@infinitesimalinfo  Can you please your MS teams alias?

**Comment by infinitesimalinfo** [comment]
dlpcentralnotification@infinitesimal.info

**Comment by infinitesimalinfo** [comment]
I've wiped it out and am doing another fresh deployment. Will let you know how it goes.

**Comment by infinitesimalinfo** [comment]
I was able to successfully deploy but as with other deployments, the first deployment failed and only succeeded on the redeployment attempt.
