### ISSUE TITLE
Company Communicator ver. Mibom have adhoc Power bi ? 

### ISSUE THREAD

**Issue by arruzarmas** [OfficeDev/microsoft-teams-apps-company-communicator#843]
i am install Company Communicator mibon version but result not avalibel in export excel and i need result  in power bi too
or did i can export insight from azure storage ?
![image](https://user-images.githubusercontent.com/7442082/185914928-0f5a16a7-fe61-4b91-a5b1-8f8b66c0b16b.png)

**Comment by gsv022** [comment]
Hi @arruzarmas ,
Thanks for raising the issue. We currently won't support for the customized version . Please let us know if you have any queries related to Company Communicator.

**Comment by kushalbhabra** [comment]
The results section in screenshot looks interesting in useful. Is this from a custom implementation of CC? If anyone can share link of the repo.

Also are there any plans to integrate these kind of reports in official CC?

**Comment by v-royavinash** [comment]
@kushalbhabra , We have feature already created in backlog, however as of now there is not specific ETA for this.

**Comment by kushalbhabra** [comment]
Alright thanks
