### ISSUE TITLE
No login, requires additional permissions Error: CAA20004 Ref: Issue #762

### ISSUE THREAD

**Issue by JuliettaCOL** [OfficeDev/microsoft-teams-apps-company-communicator#844]
I have an application implemented version 5.0 https://github.com/cristianoag/microsoft-teams-apps-company-communicator in 2 Tenants, the configurations of:

- Authentication
- API Permissions
- Expose and API

![image](https://user-images.githubusercontent.com/107083999/186015100-9b5cb14e-bce8-441c-8877-7ab77cb57529.png)

Are according to the guide, the Apps are registered in the O365 tenant and the template was executed in the Azure subscription tenant.

![image](https://user-images.githubusercontent.com/107083999/186015144-bb3c6982-44a1-4d75-a6c9-bef66a84407d.png)

**But when I try to load the Author App I get the following message:

![image](https://user-images.githubusercontent.com/107083999/186014850-aba8b59c-46b6-4608-b180-1d06e7bc2cad.png)

![image](https://user-images.githubusercontent.com/107083999/186014915-33ae4686-9de3-47a1-958b-cb0a15e97124.png)

This is the same reported case # 762 that has not yet been fixed. https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/762

**Comment by gsv022** [comment]
Hi @JuliettaCOL ,

We are working on this and will send out a meeting invite if needed.

Thank you.

**Comment by gsv022** [comment]
Hi @JuliettaCOL ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
