### ISSUE TITLE
ProactivelyInstallUserApp - Usage 

### ISSUE THREAD

**Issue by kushalbhabra** [OfficeDev/microsoft-teams-apps-company-communicator#845]
I'm just looking for clarification for the app setting 'ProactivelyInstallUserApp' and it's usage exactly.

We're testing CC in pilot phase and would only like to send messages to members of a particular M365 group. 

Queries:

1. Does the setting 'ProactivelyInstallUserApp' as true, install user app for Everyone in organisation?
2. Does it only ensure that the app is installed for the recipients of a message i.e. the M365 group we're sending the message to?
3. When does the installation take place, is it while sending a message? Or running the PowerShell script?
4. Where does it pick the user app manifest file from?

**Comment by v-royavinash** [comment]
@kushalbhabra , Please find the response for the queries inline, 

1.	_Does the setting 'ProactivelyInstallUserApp' as true, install user app for Everyone in organisation?_ : Yes, to enable proactive installation, user app has to be uploaded at tenant level.
2.	_Does it only ensure that the app is installed for the recipients of a message i.e. the M365 group we're sending the message to?_ : Yes, it will ensure the installation if the user app is uploaded at tenant level. 
3.	_When does the installation take place, is it while sending a message?_ Or running the PowerShell script? : While sending the message for the 1st time. 
4.	_Where does it pick the user app manifest file from?_ :  It pick the manifest from the one uploaded at tenant level.
