### ISSUE TITLE
Company Communicator - How to find the Bot analytics?

### ISSUE THREAD

**Issue by yazeedhannan** [OfficeDev/microsoft-teams-apps-company-communicator#846]
We have deployed the Company Communicator in Azure for testing purposes. We are in need of getting the following analytics for the bot activities.

1. The numbers of read count of an message. (Unique and Total)
2. The number of button clicks on the message button. (Unique and Total)
3. The number of reactions made on the message.

Is there a way to find these analytics using Application Insights or any other way?

**Comment by gsv022** [comment]
Hi @yazeedhannan ,
Thanks for raising the issue. We are not tracking of capturing the message reactions. We have already add it to the backlog and will plan it in the future releases.

**Comment by yazeedhannan** [comment]
Hi @gsv022 ,

Is there a way to find the read counts and button clicks? Can you please guide me on how to get those analytics?

**Comment by yazeedhannan** [comment]
@v-royavinash Can you help me with the above question?

"Is there a way to find the read counts and button clicks? Can you please guide me on how to get those analytics?"

**Comment by gsv022** [comment]
Hi @yazeedhannan ,
We have added the enhancement/feature in our backlog items and we will taking it in the future sprints depending on the priority and bandwidth.
