### ISSUE TITLE
Did we can calculate maximum message for Service plan S1?

### ISSUE THREAD

**Issue by arruzarmas** [OfficeDev/microsoft-teams-apps-company-communicator#847]
Hi i have some question
Did we can calculate maximum message for Service plan S1?

e.g 
companyAAA = 3000 employees
need send = 250 massage/month

on Service plan S1 can work ? 
and how many estimate message limit for Service plan S1 ?
how to calculate

**Comment by gsv022** [comment]
Hi @arruzarmas,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @arruzarmas ,
We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
