### ISSUE TITLE
Failed to send - App Not Installed

### ISSUE THREAD

**Issue by thomasmfarmer** [OfficeDev/microsoft-teams-apps-company-communicator#848]
I cannot send messages. The report returns 'App Not Installed'. The user app is installed for the group of users we are targeting.

ExternalAppID matches config
AppIDs and secrets match
API permissions are set correctly on MS Graph App

**Comment by v-royavinash** [comment]
@thomasmfarmer , "App Not Installed" error comes when user app is not installed for the set of users. Could you please confirm if you are sending message to all users or specific members of a Team?

**Comment by thomasmfarmer** [comment]
@v-royavinash, We are using a security group to target the users. All the members of the security group have the user app installed.

**Comment by v-royavinash** [comment]
@thomasmfarmer , Can you please upload the User app at the tenant level and re-try sending the message and share your observation.

**Comment by thomasmfarmer** [comment]
@v-royavinash, The User app was uploaded at the tenant level. Updated the version and uploaded the updated user app at the tenant level. Waited until the updated was displayed in the at the user end. Sent another test message, got the same result, App not Installed.

**Comment by gsv022** [comment]
Hi @thomasmfarmer ,

This issue might occur when the admin reuploads the app to the app catalog by deleting the old one.
### Please follow the below steps

- Navigate to Azure portal and open company communicator deployed resource group

- Click on “Storage account”

- Expand “Tables” section

- Open “AppConfig” table

- Delete the second record where Rowkey is entered as “UserAppId”

So that it populates with the correct value while sending the next message. Let us know if it worked.

**Comment by thomasmfarmer** [comment]
@gsv022, There is only one entry in the AppConfig table "ServiceUrl" - "https://smba.trafficmanager.net/amer/"

**Comment by gsv022** [comment]
Hi @thomasmfarmer,
Could you please do the same as below. Let us know if it worked.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98143492/188617280-568c4b2a-14ea-4126-8de2-d36bc9b2b857.png">

**Comment by thomasmfarmer** [comment]
I cannot delete UserAppId from the AppConfig table as it does not exist. 
![image](https://user-images.githubusercontent.com/11573406/188629320-6e630999-b966-4e89-8452-785183a446c3.png)

**Comment by gsv022** [comment]
Hi @thomasmfarmer ,
Please click on the right most (...) three dots. you will be able to see the delete option. Please let us know if this worked.

**Comment by thomasmfarmer** [comment]
@gsv022, This did not work. The issue remains.

**Comment by gsv022** [comment]
Hi @thomasmfarmer ,
Could you please share the screenshot showing the proactive installation is kept true or not. To check that, please follow as mentioned in the screenshot below.
<img width="434" alt="image" src="https://user-images.githubusercontent.com/98143492/189158117-29636464-1ccc-4c57-bc7f-be7ce3d0eb85.png">
