### ISSUE TITLE
UPN That Was Used to Deploy Company Communicator Has Changed

### ISSUE THREAD

**Issue by mp095821-e** [OfficeDev/microsoft-teams-apps-company-communicator#850]
the UPN i used to authenticate to M365 services & azure, while deploying the CC app recently changed to something else. where do i update my credentials? try redeploying the app, but getting this error msg:

![image](https://user-images.githubusercontent.com/112195316/186957361-6cc1f926-7f81-4473-bc9b-c0cd8114ad93.png)
![image](https://user-images.githubusercontent.com/112195316/186957432-aa1266a5-2da5-4841-933f-28f009b4888d.png)

**Comment by v-royavinash** [comment]
@mp095821-e  Could you please confirm which of the below applies for you,

- Already deployed CC with your previous credentials and now trying to update the upn?
- Or Tring to deploy to deploy fresh instance of  CC?

**Comment by mp095821-e** [comment]
@v-royavinash 

> @mp095821-e Could you please confirm which of the below applies for you,
> 
> * Already deployed CC with your previous credentials and now trying to update the upn?
> * Or Tring to deploy to deploy fresh instance of  CC?

@v-royavinash ,

CC is already deployed, & i'm trying to update my UPN, as i started getting this error right after my IDM team changed our UPNs.
![image](https://user-images.githubusercontent.com/112195316/186973008-21f5604d-e17c-4ed7-87e1-4fe5794e007b.png)

**Comment by v-royavinash** [comment]
@mp095821-e , Please refer FAQ Issue #11 for the resolution steps,

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Frequently-Asked-Questions-(FAQ)#11-can-i-update-the-list-of-authors-after-deploying-the-app

**Comment by mp095821-e** [comment]
thanks, @v-royavinash . but i already read that article. it doesn't address the issue.

**Comment by mp095821-e** [comment]
also, we're still using 4.1. how do i upgrade to v5.2?

**Comment by v-royavinash** [comment]
@mp095821-e , For migration please refer the migration guide https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide .

And regarding the issue we will analyze the possible fix and keep you posted.

**Comment by gsv022** [comment]
Hi @mp095821-e ,
Are you able to migrate to 5.1 version? If not, could you please share the app insight logs.
