### ISSUE TITLE
Upgrading from v5.x to latest version doesn't work

### ISSUE THREAD

**Issue by cifofs** [OfficeDev/microsoft-teams-apps-company-communicator#851]
Hi,
I followed the steps for Upgrade from v5.1 to latest version, but nothing happened:
![image](https://user-images.githubusercontent.com/99551692/187012348-c33c1791-b1f1-4b57-8081-12c5e4e9fc7a.png)

am I missed something? I mean, those are ALL the steps for the upgrade?

Thanks in advance...

**Comment by gsv022** [comment]
Hi @cifofs ,
Hope your GitHub repo URL and branch is pointing to **main** of official repository. If app service was successful, please open the teams through the browser and check for latest changes.  It should reflect.
If not reflecting, please send the screenshot as mentioned below. 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/98143492/187058427-363ee6c8-9fb1-4964-aa4e-4fd2ad53460a.png">


**Note**:- App service and function apps should be pointing to main branch of official repository.

Thank you.

**Comment by cifofs** [comment]
Hello @gsv022,
I opened Teams through the browser and is not reflecting the latest changes:
![image](https://user-images.githubusercontent.com/99551692/187085741-42da1540-d0e5-44c3-94d9-fef20c346f05.png)


This is the screenshot of the App Service:
![image](https://user-images.githubusercontent.com/99551692/187085694-18476c8a-1802-4068-a335-c803cddaad06.png)

Note: The functions are pointing to the same repository and branch

Hope you can help me with that...

**Comment by gsv022** [comment]
Hi @cifofs ,
Thanks for sharing the screenshots. Could you please point the branch to **main** instead of master.
### Please follow the below steps:-
- Disconnect the source. If it is taking time to disconnect. Please refresh the page. 
- Connect the source to external git.
- Point the repository to the same as you highlighted. **Change the branch to main** .
- Save it. Wait for success state in the logs section
- Please do the same for function apps as well. 

**Note**:-Please sign out and sign into the teams to get the latest changes reflected.

**Comment by cifofs** [comment]
Hi @gsv022 ,
Thansk for the support.  I followed the steps and get the latest changes reflected.  Thank you very much!
![image](https://user-images.githubusercontent.com/99551692/187254421-4fc60ff6-5256-4daf-b5f1-f06eebc584e6.png)

**Comment by cifofs** [comment]
Hello @gsv022.
A question about the header image:  I need to use an internal image.  What kind of access I need and for whom?
![image](https://user-images.githubusercontent.com/99551692/187325923-5db7300c-369e-499f-a4b0-fe821f01a1ef.png)


Thanks in advance...

**Comment by captainhook** [comment]
> Hello @gsv022. A question about the header image: I need to use an internal image. What kind of access I need and for whom? ![image](https://user-images.githubusercontent.com/99551692/187325923-5db7300c-369e-499f-a4b0-fe821f01a1ef.png)
> 
> Thanks in advance...

You will need to include the image in the zip file for the app which you upload into Teams admin portal.

**Comment by gsv022** [comment]
Hi @cifofs ,

- Any public valid image URL  can be used in React_Header_Image section. To apply the image which is present locally, it is recommended that please store the image where it is publicly available.
 Eg:-GitHub.
- Grab the URL and paste it in the  React_App_HeaderImage section.
![image](https://user-images.githubusercontent.com/98143492/187621172-bdf34bc2-9497-4873-a450-e53ff5ddbb77.png)

- Save the configuration and re-sync the app service. Once it is successful the latest changes will get reflected to the tenant.

**Comment by cifofs** [comment]
Hello @gsv022,
Thank you very much for the information.  Regards...

**Comment by RavinderRS** [comment]
Hello,

Thanks for the above steps.

I followed all the above steps and on top of it re-uploaded the manifest file with an additional change in the manifest file:

"supportsFiles": false, in User file and "supportsFiles": true, in Author file.

**Comment by bahTeams** [comment]
Hello @gsv022,
i'm preparing to update my application to V5.2 but i would like to know if using the " React_App_HeaderImage" will remplace the logo of my application ?
How about if i migrate without using "React_App_HeaderImage" ?
Thanks
