### ISSUE TITLE
Sent a card preview

### ISSUE THREAD

**Issue by Scheiderichv094** [OfficeDev/microsoft-teams-apps-company-communicator#853]
Is there a way to change when a message is sent out to users, they do not see "sent a card" in the chat window but a brief summary or different title?

**Comment by v-royavinash** [comment]
@Scheiderichv094  Could you please provide more details on what's the issue or query is?

**Comment by gsv022** [comment]
Hi @Scheiderichv094 ,
Please elaborate more on the issue that you are facing?
