### ISSUE TITLE
Unable to open app

### ISSUE THREAD

**Issue by wallyaw** [OfficeDev/microsoft-teams-apps-company-communicator#854]
I've successfully deployed CC using the PowerShell script, however when I go to open the app I receive an error, hopefully someone can point me in the right direction:

  _something went wrong...
  You cannot access this application because it has been misconfigured. Contact your IT department and include the following information:
  Undefined Sign-On URL for application "insigcommunicator"
  
  [Go to Applications](https://account.activedirectory.windowsazure.com/applications/default.aspx)_

**Comment by SankarMicrosoft** [comment]
Thank you for raising your query. We will discuss with our team and get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @wallyaw ,
Could you please share the MS teams id so that we can discuss over the call and try to troubleshoot the issue.

Thank you.
