### ISSUE TITLE
Additional feature enablement query

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#857]
There is a question related to some additional feature enablement in Company Communicator. Please refer the below link.
[https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/823](url)

I have asked a few more questions related to that. Could you please provide answers for the following questions

We need to enable the option for specifying the list of people who only can download the reports generated after an author sends a message from author app. We got to know that it could be enabled in the next version release post internal discussion. 

Below are the questions for which we are seeking some clarification: 
1. When is the expected release of the next version which would have the enablement of "allow the download of reports only for specific people" option.
2. Please provide more information about the retention policy of reports and messages in the current version -
i. How long the authors can download the reports,
ii. How long the messages will be available in the chat and posts.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query. We will discuss with our team and get back to you.

**Comment by v-royavinash** [comment]
@PrithuMahisha , We don't have any ETA for the feature. We have added it to the backlog and depending on the priority we will be taking up in future releases but for now won't be able to commit for any specific timeline.

We will keep you posted when we plan for this feature release.

Regarding second part of your query, there will not expiration time of downloading the reports as the data is fetched from storage and we don't delete any historical data.
