### ISSUE TITLE
Sending to large user group (300k users) fails - timeout and other errors

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-company-communicator#858]
Hi,

my customer has recently updated the Company Communicator to version 5.2.
With the new version, sending messages to small user groups works fine, but when trying to send a message to all users (300.000 recipients) the message fails for over 90% of users and only 30.000 users receive the message.

Customer is on plan S2.

Thanks a lot for your help here.

**Comment by gsv022** [comment]
Hi @apptemplatequestions ,
Thanks for raising the query. Please send the export details of the message sent where only 10% of the group received.

**Comment by apptemplatequestions** [comment]
Looping in @Sayed ***@***.***>.

@Sayed ***@***.***>: Can you please send the team the export details of the message sent where only 10% of group received.

Thank you!

Jan

Von: Sai Venkat ***@***.***>
Gesendet: Mittwoch, 7. September 2022 12:35
An: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Jan Keller ***@***.***>; Mention ***@***.***>
Betreff: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Sending to large user group (300k users) fails - timeout and other errors (Issue #858)


Hi @apptemplatequestions<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapptemplatequestions&data=05%7C01%7CJan.Keller%40microsoft.com%7C74e85811a501402e023a08da90bca014%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637981437078799291%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6Xz0iCf2IRrUWvQxBUeVewayJFALwXgI5fjdKAtZavk%3D&reserved=0> ,
Thanks for raising the query. Please send the export details of the message sent where only 10% of the group received.

-

**Comment by apptemplatequestions** [comment]
Hi Jan,

Actually this is another problem I replied to the team, as we couldn’t get the detailed report as it generates error

Sayed Ali
Sr. CSA-Engineering

Phone: +49 89 3176-2049
(optional) Mobile: +49 15123592599
E-mail: ***@***.***
Microsoft Deutschland GmbH | Walter-Gropius-Straße 5 | 80807 Munich|
Microsoft - Official Home Page<https://www.microsoft.com/de-de?ql=2>
Home | News Center Microsoft<https://news.microsoft.com/de-de/>
Microsoft Privacy Statement - Microsoft Privacy<https://privacy.microsoft.com/de-DE/privacystatement>
Managing Directors: Marianne Janik (Chairwoman), Florian Deter, Benjamin O. Orndorff, Keith Dolliver | Munich District Court, HRB 70438

From: Jan Keller ***@***.***>
Sent: Wednesday, September 7, 2022 1:04 PM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; Sayed Ali ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Mention ***@***.***>
Subject: AW: [OfficeDev/microsoft-teams-apps-company-communicator] Sending to large user group (300k users) fails - timeout and other errors (Issue #858)

Looping in @Sayed ***@***.***>.

@Sayed ***@***.***>: Can you please send the team the export details of the message sent where only 10% of group received.

Thank you!

Jan

Von: Sai Venkat ***@***.******@***.***>>
Gesendet: Mittwoch, 7. September 2022 12:35
An: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
Cc: Jan Keller ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Betreff: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Sending to large user group (300k users) fails - timeout and other errors (Issue #858)


Hi @apptemplatequestions<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapptemplatequestions&data=05%7C01%7CSayed.Ali%40microsoft.com%7Cc6a638a5e0474e0576dc08da90c0a418%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637981454309415608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0HbN50IZF%2F01uOebmZnFPgC%2BxKoLVjZ6wVULEx77Ass%3D&reserved=0> ,
Thanks for raising the query. Please send the export details of the message sent where only 10% of the group received.

**Comment by JohnMonteith** [comment]
Hello, has this been solved? I am experiencing a similar issue - I am also unable to export detailed results.

**Comment by victorsimonlee** [comment]
Hi @JohnMonteith  - not sure what is your error on exporting. I was not able to download the export via MSTeams but later found that every time you click on the "Export detailed results" button in a sent message, the export is saved in the Azure blob: exportdatablobs. From there you can download it to your local.

hope this helps

**Comment by gsv022** [comment]
@apptemplatequestions ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
