### ISSUE TITLE
Failed sending message to more than 300K users

### ISSUE THREAD

**Issue by sayedpfe** [OfficeDev/microsoft-teams-apps-company-communicator#859]
Dears, 

i am facing issue sending message to more than 300K users after upgrading to v5.2
we tried to send the message for first time and we get this error 
Failed to prepare the message for sending:The orchestrator function 'SyncRecipientsOrchestrator' failed: "The activity function 'SyncAllUsersActivity' failed: "Timeout value of 01:00:00 was exceeded by function: SyncAllUsersActivity". See the function execution logs for additional details.". See the function execution logs for additional details.

then we increased the timeout for prep-function to be 8 hours, and we tried to send the message for second time but i was not delivered to all users with the below error message 

![image](https://user-images.githubusercontent.com/13697878/188829948-4a80623a-c0db-4efa-9ff8-8c164f83b91a.png)

anyone can advice for this issue

**Comment by gsv022** [comment]
Hi @sayedpfe ,
Thanks for raising the query. Please send the export details of the message sent.

**Comment by sayedpfe** [comment]
Hi @gsv022 ,

thanks so much for your reply, we couldn't export it, when we tried it gave us error

**Comment by gsv022** [comment]
Hi @sayedpfe 
Please give us sometime to check on the issue and will get back to you with proper response.

**Comment by v-royavinash** [comment]
As confirmed over internal teams conversation for now no further steps need to be taken hence we are closing out the issue.
