### ISSUE TITLE
Permission error after deploy Company Communicator

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#860]
Hi Team, please kindly advise on how to handle the following error after deploy Company Communicator, thanks
![image](https://user-images.githubusercontent.com/25476072/188834326-f43768ea-0db7-41cf-aa57-e5d78b8658d9.png)

**Comment by gsv022** [comment]
Hi @rex-ma ,
Thanks for raising the issue. Could you please respond to the below queries
- What is the version of the CC app?
- Does the user app installed at the teams level or tenant level?
- Could  you please send the screenshot of API permissions from Graph app registration
- Could you please send the screenshot of app permission policies from teams admin center as mentioned below.
![image](https://user-images.githubusercontent.com/98143492/188855049-265d1e10-6278-4ff2-b03a-80ec39a9bb0e.png)

- And send the screenshot of user policies from teams admin center as mentioned below .
![image](https://user-images.githubusercontent.com/98143492/188855781-44198872-4a65-4740-af9b-94dedd13ea27.png)

**Comment by v-royavinash** [comment]
@rex-ma ,

For User app installation the below mentioned permissions is required. Could you please cross verify and make sure the below permissions are [added to the Graph app registrations](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#4-add-permissions-to-your-microsoft-graph-azure-ad-app).  

Delegated permissions,

- GroupMember.Read.All
- AppCatalog.Read.All

Application permissions,

- GroupMember.Read.All
- User.Read.All
- TeamsAppInstallation.ReadWriteForUser.All

![image](https://user-images.githubusercontent.com/94480537/188940608-c20f94c1-be74-46a2-a3ad-16eb91829096.png)
