### ISSUE TITLE
Missing "Create Custom Message" button after the upgrade to V5.2 from V5.0 

### ISSUE THREAD

**Issue by RavinderRS** [OfficeDev/microsoft-teams-apps-company-communicator#861]
We are planning to use the Adaptive Card functionality in the Company Communicator App but, missing "Create Custom Message" button after the upgrade to V5.2 from V5.0  

<img width="398" alt="Img-3" src="https://user-images.githubusercontent.com/6483156/188912711-5c55211a-8fc2-4727-8c2d-337d69b43b91.png">

Thanks
Ravi

**Comment by v-royavinash** [comment]
@RavinderRS , The UI seems different to the one which we have for the CC default v5.2. Could you share the repo URL which is used to deploy the instance of Company communicator in your case?

**Comment by RavinderRS** [comment]
Repo URL:  https://github.com/OfficeDev/microsoft-teams-apps-company-communicator
Branch:   Main
and 
WEBSITE_NODE_DEFAULT_VERSION:   16.13.0  in all the 4 places   App & Az Functions.

Actually its not our image... I just got it from web to show the missing.

Here 
<img width="738" alt="img-4" src="https://user-images.githubusercontent.com/6483156/188986177-f0a93660-f87b-44cf-b471-4d6cc8bece67.png">
is our screenshot:

**Comment by gsv022** [comment]
Hi @RavinderRS ,

- The screenshot which is shared along with "**CREATE CUSTOM MESSAGE**" is not a part of our released version(5.2) and even **upload image** button seems bit different from our release. 

- This is the view of official  CC-v5.2 for **New message**. The custom message option is not a part of the default repo. Please make a note of it.
![image](https://user-images.githubusercontent.com/98143492/189070097-695d2561-2336-4eda-9ed3-579a899d9e51.png).

Please let us know if you have any queries

Thank you.

**Comment by RavinderRS** [comment]
Please ignore the 1st Image, as I mentioned its from the web. ( Ref for the img: https://www.youtube.com/watch?v=wDVVbiaNbjk&ab_channel=Microsoft365Developer )

The second & Third images looks equivalent. Thanks for confirming the button is part of the v5.2

"If the Create Custom Message"  button was not part of the Official CC-V5.2, How can we use the Adaptive Cards, as per the release notes it says Adaptive Cards is supported in v5.2

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/releases/tag/v5.2

**Comment by RavinderRS** [comment]
Any update on this is much appreciated, as we have a Prod Deployment dead line. 

We just need the confirmation if the Adaptive Cards is supported in V5.2 or not, If yes can you help me with how its done with out the "Create Custom Message" button, in order to wrap out our Testing before moving to Prod.

Thanks
Ravi

**Comment by v-royavinash** [comment]
@RavinderRS , 

We do use Adaptive cards to to deliver/send the messages to the Intended audience. Adaptive cards was already used in the previous versions. But we don't support creating custom message or customizing the message template.

The highlighted feature in v5.2 provides an ability to format the message.
![image](https://user-images.githubusercontent.com/94480537/189412291-2c460dce-5395-4931-b3db-491e823d046e.png)

Below are the supported formatting features,

![image](https://user-images.githubusercontent.com/94480537/189412571-796ba3b3-35cb-447d-8c5e-6397fd340e63.png)

https://docs.microsoft.com/en-us/adaptive-cards/authoring-cards/text-features

**Comment by RavinderRS** [comment]
Thank you for confirming....

**Comment by gsv022** [comment]
Hi @RavinderRS ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
