### ISSUE TITLE
New role suggestion

### ISSUE THREAD

**Issue by Balitewicz** [OfficeDev/microsoft-teams-apps-company-communicator#864]
It would be nice if you had a role that didn't allow the sending to all users.  The authors role is all or nothing.  It would be nice if you had a Teams Role that only allowed the sending to Teams and not all users.

**Comment by gsv022** [comment]
Hi @Balitewicz ,
Thanks for raising the query.  We have already add it to the backlog and will plan it in the future releases.

**Comment by GrantOliasani** [comment]
I work with many orgs on standing up this solution and this would be a game changer feature.

**Comment by gsv022** [comment]
Hi @Balitewicz ,
We have added the enhancement/feature in our backlog items and we will taking it in the future sprints depending on the priority and bandwidth.
