### ISSUE TITLE
For a hybrid GOV deployment do we need to have an azure commercial sub 

### ISSUE THREAD

**Issue by jeffswillbejeffs** [OfficeDev/microsoft-teams-apps-company-communicator#868]

**Comment by gsv022** [comment]
Hi @jeffswillbejeffs ,
Thanks for raising the query. Currently we are testing both GCC and GCCH tenants. We will keep you informed on this.

**Comment by gsv022** [comment]
Hi @jeffswillbejeffs 
As of now CC is not working as expected in GCC-H tenant. We will keep you posted on this.

**Comment by jeffswillbejeffs** [comment]
My question is for the Hybrid deployment. Do we need to have both an Azure commercial sub in step 2 and also an azure government subscription in step 3.

**Comment by gsv022** [comment]
Hi @jeffswillbejeffs ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.
