### ISSUE TITLE
Usage of Azure functions

### ISSUE THREAD

**Issue by tomatosis** [OfficeDev/microsoft-teams-apps-company-communicator#870]
The architecture diagram shows  5 Azure functions. From Azure resource group, there are only three Azure functions created , pls see below. Can anyone explain?
![image](https://user-images.githubusercontent.com/107910629/190290229-29377b7c-cdfd-4c3f-a892-62b605214773.png)

**Comment by gsv022** [comment]
Hi @tomatosis ,

To handle the backend services, we have the 3 durable azure functions

- **Prep-Function**:- Prepares the message

- **Send-Function**:- Send the message to the users and picks the message from the **service bus** one-by-one and the messages will be delivered to the respective users.

- **Data-Function**:- This function gives the acknowledgement saying that message got delivered or not.
-------------------------------------------------------------------------------------------------------------------------------

- **Export-Function**:- This function exports notification in a zip file for the admin. It prepares the file by reading the notification data, user graph api. This is a part of prep-function only.

- **Clean-up function**:- This deletes the files in Azure Blob storage and file cards sent to users. This is a part of Data function only.


Hope it helps.

**Comment by tomatosis** [comment]
@gsv022 
Thanks for sharing.
However, my question is why we don't see Export-Function and Clean-up Function when we setup the company communicator using the code provided?

**Comment by gsv022** [comment]
Hi @gsv022 ,
Attaching the screenshots for the reference.

- **Export Function**:-
<img width="958" alt="image" src="https://user-images.githubusercontent.com/98143492/190616843-0ea73c5b-71f2-4259-a0db-59038e0bafab.png">

- **Clean-up Function**:-
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98143492/190617374-bdeabc5a-4b5b-4a4b-a678-4790b798e70e.png">

Hope it conveyed.

**Comment by tomatosis** [comment]
Hi @gsv022,
Thanks for the explanation.
You may close the case.
