### ISSUE TITLE
Error while debugging locally

### ISSUE THREAD

**Issue by angtany** [OfficeDev/microsoft-teams-apps-company-communicator#871]
I am trying to debug this app locally and is working fine till the draft message creation. While clicking send, it is giving following error - 

System.UnauthorizedAccessException","message":"Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://*****.servicebus.windows.net/company-communicator-prep'. 

Looks like it is unable to authorize against Azure Service Bus while running locally. 

As per debugging, this error comes while calling "SendMessageAsync" function for pushing the message to service bus. 

appSettings.json has correct values of Service Bus Namespace and Service Bus Connection String. (hardcoded both.)

Looking for help.

**Comment by gsv022** [comment]
Hi @angtany ,

Thanks for raising the query. Please give us some time and will get back to you with proper response.

**Comment by gsv022** [comment]
Hi @angtany ,
Could you please follow the steps mentioned in issue no [565](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/565) to run the CC locally. There might be a chance that any step got missed.

**Comment by angtany** [comment]
Hello @gsv022 ,

I checked all the steps are followed. Can you please help in understanding how does service bus authentication should take place while debugging locally.

If you share the high level process, I will double check if something is missing out. 

Thanks !

**Comment by angtany** [comment]
Hello @gsv022 , any updates/inputs ?

**Comment by v-royavinash** [comment]
Hi @angtany, Service bus authentication is done with the connection string from the local settings file. Could you please confirm if you have created and added the required values in the local setting Json?

Also can you mask and share the structure of local configuration file.

**Comment by v-royavinash** [comment]
@angtany , Could you please let us know if you are still facing the issue? If yes, please do share the masked configuration file structure  as requested above.
