### ISSUE TITLE
Programmatically send Company Communicator messages

### ISSUE THREAD

**Issue by GrantOliasani** [OfficeDev/microsoft-teams-apps-company-communicator#873]
Is there a way to programmatically send messages from the CC bot? I know we can auto draft notifications by writing to the NotificationData table with a DraftNotifications row. But how can we force it to go ahead and send the message from draft state or bypassing draft state all together?

I have tried modifying the isDraft and isPreparingToSend properties with no success. Any ideas?

**Comment by gsv022** [comment]
Hi @GrantOliasani,
Generally whenever we want to send a message, we draft it and then send it. So its a kind of incremental way. It can be customized but we wont be able to assist on this.

Please let us know if you have any queries.

Thank you.
