### ISSUE TITLE
Steps to create an azure devops repository and deploy from the azure devops repository using the ARM Template

### ISSUE THREAD

**Issue by barcafan** [OfficeDev/microsoft-teams-apps-company-communicator#874]
Hi,

I want to take the main branch code and move it to azure devops repo. What are the changes that need to be done for the deployment to work from the code repository in azure devops? Do I only need to change the repo URL? How do I provide the credentials for the repo in case I use azure devops?

**Comment by gsv022** [comment]
Hi @barcafan ,
Could you please confirm whether you are trying to migrate the code to azure devops or trying to change deployment model through the pipelines? If trying to implement through pipeline model then we wont be able to assist on this.

**Comment by barcafan** [comment]
@gsv022 I am trying to migrate the code to azure devops and then run through the [deployment guide steps](https://github.com/OfficeDev/microsoft-teams-company-communicator-app/wiki/Deployment-guide) from the azure devops location.

**Comment by gsv022** [comment]
Hi @barcafan ,

- If the code is migrated to azure devops already then follow the path mentioned below.  You will be able to pull the code once connected to the Azure repos and it automatically gives a pop-up with  to sign-in. Once it is done 

<img width="626" alt="image" src="https://user-images.githubusercontent.com/98143492/191264705-62ebc12d-1dd1-41a2-8641-0245fa5e5adb.png">


- Please do the same for function apps as well.
- We are not sure of this procedure because we haven't done it before. Please give a try on your own.

**Comment by barcafan** [comment]
HI @gsv022 

Thanks for the reply. 
Could you please elaborate on the steps in this case?
What would be the steps for deployment in this case?
1. Create app registrations.
2. Click on the Deploy to Azure button
3. What are the input values for the gitrepo Url and branch? Do I need to provide those values?

**Comment by v-royavinash** [comment]
Hi @barcafan, 

We recommend using the public GitHub repository for deployment. Having said that it doesn't stop using Azure repos.  You can create pipelines for directly deploying it to your tenant, but we won't be able to help out in creating and setting pipelines.

The other simple and one time way around is, create and deploy the resources using the standard deployment templates using official repo. Once the deployment is completed, go to deployment center of the app service and other azure functions.

Disconnect the existing repos which is pointing to the GitHub repo. It will take ~15 mints to disconnect. Once disconnect, please follow below highlighted approach and point it to your private azure repo. Repeat the steps for all 3 Azure functions. 

![image](https://user-images.githubusercontent.com/94480537/192400231-ee74d1f3-43e6-4ea4-9a19-aecd9de758b6.png)
