### ISSUE TITLE
v5.2 App Manifest file were uploaded without deleting the prior v5.0 

### ISSUE THREAD

**Issue by RavinderRS** [OfficeDev/microsoft-teams-apps-company-communicator#875]
<img width="741" alt="Img-5" src="https://user-images.githubusercontent.com/6483156/190952364-d1287458-e098-4ccb-800e-292ad07f4111.png">

**Comment by gsv022** [comment]
Hi @RavinderRS,
Thanks for raising the query. Once the migration is done from 5.0 to 5.2 and if the changes are not reflecting, please try this.

- Please cross-verify whether the WEBSITE_NODE_DEFAULT_VERSION is update to 16.13.0 or not in App Service configurations.

- Disconnected App Service / Azure Functions from existing connection to External Git in Deployment Center

- Reconnect it to External Git repo on **main** branch.

- Sync the App Service / Azure Functions.

- Clear the browser cache, sign out from teams and Sign in again to see the latest changes.

**Comment by RavinderRS** [comment]
Disconnect and reconnecting the 4 Azure Resources did the trick. Now it looks good, please resolve this one.

Thanks
Ravi
