### ISSUE TITLE
Error while opening Company Communicator from Teams channel

### ISSUE THREAD

**Issue by idanbarshlomo** [OfficeDev/microsoft-teams-apps-company-communicator#876]
![companycomerror](https://user-images.githubusercontent.com/89249098/190973492-d0811d15-3bdc-4252-9260-afd3cb585a20.png)

Getting error (Ooops! An unexpected error seems to have occurred) while trying to open the company communicator from Teams channel. Do you have any idea what can cause that ?

**Comment by gsv022** [comment]
Hi @idanbarshlomo ,
Could you please send the screenshot of  App service status, repo url and branch that you are pointing to. To get that.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/98143492/191021842-680272e0-3c40-44d3-acbf-bea7db7e2206.png">

<img width="794" alt="image" src="https://user-images.githubusercontent.com/98143492/191021881-a9c4ee07-cefc-4416-8a53-6e526358f8ea.png">

**Comment by idanbarshlomo** [comment]
Thanks for the comment, please see below 

![deployment center logs](https://user-images.githubusercontent.com/89249098/191198373-7cec8e24-2224-4d36-afe1-803d5d74e5ec.png)
![deployment center](https://user-images.githubusercontent.com/89249098/191198376-03f95c52-5632-4717-b767-e074e576d0e7.png)

**Comment by idanbarshlomo** [comment]
Thanks for the comment, see below

![deployment center logs](https://user-images.githubusercontent.com/89249098/191198624-8644f522-6b25-4ccc-9381-b659d5f4e56e.png)
![deployment center ](https://user-images.githubusercontent.com/89249098/191198762-e9d3a119-e67f-40df-9c0c-4427d0a0f93a.png)

**Comment by gsv022** [comment]
Hi @idanbarshlomo ,
It seems that app service is still running. Once the status goes to success state, probably that will solve the issue.
Keep us posted.

**Comment by idanbarshlomo** [comment]
Hi @gsv022 
It's on Success state now but the issue still remain. any other ideas ?

**Comment by idanbarshlomo** [comment]
I can also, see that error in one of the functions

![error-prep-function](https://user-images.githubusercontent.com/89249098/191498238-d29413cf-7952-4a71-8f90-70791fe32687.png)

**Comment by v-royavinash** [comment]
@idanbarshlomo Could you please go to the application insights and share the top 5 error listed. And also please go the resource group --> deployments and click on the link and download the deployment logs and share with us to understand the issue.

**Comment by v-royavinash** [comment]
@idanbarshlomo , Could you please let us know if you are still facing the issue? If yes, please do share the logs as requested above.

**Comment by idanbarshlomo** [comment]
Still facing the issue

![communicator](https://user-images.githubusercontent.com/89249098/193440945-66cfff81-a232-4296-a449-27e56a346625.png)

**Comment by gsv022** [comment]
Hi @idanbarshlomo ,
Could you please share the MS Teams id so that we could connect over the call and discuss the issue.

**Comment by idanbarshlomo** [comment]
Still having issues with the app service configuration (see below attached photos), it looks like the app service is missing some permissions to access the key vault how ever it has all the rights.
Let me know if you can jump to Teams call.

![image](https://user-images.githubusercontent.com/89249098/197386843-91f351fb-1b2c-4edd-a005-9e39b926480f.png)
![image](https://user-images.githubusercontent.com/89249098/197386849-834987a4-f94f-47e4-96ba-610af7bac5d0.png)
![image](https://user-images.githubusercontent.com/89249098/197386861-0de489eb-00bb-4040-8253-620751b957d3.png)
![image](https://user-images.githubusercontent.com/89249098/197386872-f3b390a1-fdf2-4f38-88a2-859accea425f.png)
![image](https://user-images.githubusercontent.com/89249098/197386886-481cdc29-8a40-4d46-8d19-a2e09ea87500.png)
![image](https://user-images.githubusercontent.com/89249098/197386900-7b185197-f85f-49a9-9537-cbe06ea50dcc.png)
