### ISSUE TITLE
How to update icons which show up on messages from user or author bot

### ISSUE THREAD

**Issue by barcafan** [OfficeDev/microsoft-teams-apps-company-communicator#878]
Hi,
Can you provide the steps for updating the icons and names that show up when a message is sent by the Author app for detailed export and when the user receives a message from the user app after the deployment is done? Is there an existing document or link that I can use for this information?

e.g., How do I change the icon and teams name which shows up in teams for the author app?
![image](https://user-images.githubusercontent.com/5369170/191263904-e8f7ab50-5271-4c08-9c3d-745004534469.png)

**Comment by gsv022** [comment]
Hi @barcafan ,
To update the name and icon. Please follow the below steps.
- Open Azure portal

- Navigate to respective resource group

- Open “Web app bot”

- Click on “Bot profile”

- Update “Display name” as required and click on Apply.

![image](https://user-images.githubusercontent.com/98143492/191272541-588fcb3e-ccef-41bd-95d3-766ac8cf92b1.png)

- To update the logo, replace the **‘color’** image with the logo customer want to use, please make sure to use the same size and dimension of the image.

![image](https://user-images.githubusercontent.com/98143492/191273007-7737cdfa-a826-487c-8366-6b24d156ac2f.png)

- Please delete the uploaded manifest file and create a new zip file with these changes and reupload in the Teams admin centre
Make sure to clear the Teams cache, you can find the steps [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fanswers.microsoft.com%2Fen-us%2Fmsteams%2Fforum%2Fall%2Fclear-cache%2F0810ce4f-af14-4269-b01f-adc89a0af4c4&data=05%7C01%7Cv-saigattu%40microsoft.com%7Cab7007ee368e41ad066d08da63e9cceb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637932153069494766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QxNdZDeBtc1ZU8gKT%2BFZ%2B3FMqBJN6NyVOBFZv1zH06k%3D&reserved=0)

- To get reflected after the changes done, it will sometime.

Hope this helps and keep us posted.

**Comment by barcafan** [comment]
Hi @gsv022 Thanks for the steps. 
I had the following questions: 
- Do I need to delete the app in teams first before uploading the new zip?
- Do I need to change the version field in the manifest when uploading the zip file?

**Comment by gsv022** [comment]
Hi @barcafan,

1. Do I need to delete the app in teams first before uploading the new zip?

    Yes, it is recommended.

2. Do I need to change the version field in the manifest when uploading the zip file?

    No need to change.

**Comment by bchamnarnkit** [comment]
Hi I am also having a similar problem. Is there a way to change the logo / branding in Azure portal without needing to upload the manifest file? From what I understand this can be done based on the recommendation provided here but it has been unsuccessful for me so far https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/803
