### ISSUE TITLE
Azure Function Code Sync Alternatives

### ISSUE THREAD

**Issue by scjohnmsft** [OfficeDev/microsoft-teams-apps-company-communicator#879]
My customer is facing challenges in their environment in terms of deployment and syncing custom code a partner provided for enhanced reporting, from Local Azure Devops with 4 Azure functions that is used in Company communicator app. The service account through which we perform the azure function code sync in azure portal is not allowed by my customers Infrastructure team to be added to the Azure Devops repos where we have saved the latest custom reporting code. Due to which we will not be able to sync the latest code from Azure Devops repos.

As a workaround, the customer has suggested that we should use azure pipeline to deploy the latest code from Azure Devops repos to all 4 Azure functions that we are using now.  Customer would like to know if this Azure pipeline deployment approach can be used as a workaround for Azure functions code sync and it has no impact on the existing deployment approach.

**Comment by gsv022** [comment]
Hi @scjohnmsft ,
Thanks for raising the query. The pipeline deployment model is also one of the possibilities. But we are not sure of the procedure because we have never implemented till now.
