### ISSUE TITLE
Deployment for GCC but has a Gov azure subscription

### ISSUE THREAD

**Issue by jeffswillbejeffs** [OfficeDev/microsoft-teams-apps-company-communicator#881]
My question is for the Hybrid deployment. Do we need to have both an Azure commercial sub in step 2 and also an azure government subscription in step 3.

**Comment by gsv022** [comment]
Hi @jeffswillbejeffs ,
Thank you for raising the query.  It depends on where the resources need to be created. 

- If the intention is to create the resources in one tenant and deploying the CC in another tenant, it is recommended to go for Azure commercial subscription.
- If the intention is to create the resources in one tenant and deploying the CC in the same tenant, it is recommended to go for Azure gov subscription

Hope it helps.
