### ISSUE TITLE
Hi, Had an issue deploying the Communicator on Azure

### ISSUE THREAD

**Issue by lenamasdo** [OfficeDev/microsoft-teams-apps-company-communicator#882]
Deploying app services, Azure function, bot service, and other supporting resources... (this step can take over an hour)
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"},{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"}]}}
Fetching deployment status to check if deployment really failed...
Collecting deployment logs...
Deployment logs generation finished. Please share Deployment\logs.zip file with the app template team to investigate...
Error occurred while deploying Azure resources.
ERROR: ARM template deployment error.
At C:\TEMP\microsoft-teams-apps-company-communicator-main\microsoft-teams-apps-company-communicator-main\Deployment\deploy.ps1:530 char:17
+                 Throw $deploymentExceptionMessage
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ERROR: ARM template deployment error.:String) [], RuntimeException
    + FullyQualifiedErrorId : ERROR: ARM template deployment error.

**Comment by lenamasdo** [comment]
![image](https://user-images.githubusercontent.com/114112901/191613383-2f72077f-7765-4d9e-a28b-b7614b1646e1.png)

**Comment by gsv022** [comment]
Hi @lenamasdo ,
Thanks for raising the query. It seems that some of the resources got failed.

- Please update the parameters mentioned in the screenshot below with some new valid [GUID](https://www.guidgenerator.com/online-guid-generator.aspx) And re-deploy it. 

![image](https://user-images.githubusercontent.com/98143492/191739118-7634c97e-7ed5-49a9-bcd7-662ecadfdb50.png)

- If function apps or app service got failed. Please go to that resource group-->App service/function app-->deployment center-->**sync**(if the status is showing failed in the **logs** section)
- If facing issue even after doing the above procedure, please share the deployment logs. Then to keep yourself unblocked, please proceed with the manual deployment.
<img width="766" alt="image" src="https://user-images.githubusercontent.com/98143492/191740099-4c00c051-d78e-432b-b9ea-ac016f71b961.png">

**Comment by lenamasdo** [comment]
Yes, thanks it worked. It needed two runs.
