### ISSUE TITLE
Deployment failed at Validation--subscription quota limitation despite not having anything else deployed in subscription. 

### ISSUE THREAD

**Issue by hajac** [OfficeDev/microsoft-teams-apps-company-communicator#884]
Using the Custom Deployment Template in the Deployment Guide, process fails in Validation with the following error(s). I tested trying to create an App Service from scratch and it gave the same error. The tricky thing is, I don't currently have any App Service deployed in this subscription. The only thing I have deployed is a VM. 

Another note, I have tried all US regions, and all SKUs and the error does not change. 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/68866233/192582049-d4187992-e940-4f5f-808d-9ffa761d62c3.png">

<img width="288" alt="image" src="https://user-images.githubusercontent.com/68866233/192582117-36366085-bec8-41b9-a942-1ad217f72258.png">

**Comment by v-royavinash** [comment]
Hi @hajac,

The issue is subscription specific. You can check if app service creation is allowed under your subscription or not. Also its advisable to raise a Azure Support ticket as they will be having better visibility on subscription specific issue.
