### ISSUE TITLE
Update code to latest version of .Net Core and BotFramework

### ISSUE THREAD

**Issue by desmay** [OfficeDev/microsoft-teams-apps-company-communicator#885]
Is the team working on upgrading this solution to later version of .Net Core framework and updating deprecated class like BotFrameworkHttpAdapter ?

**Comment by v-royavinash** [comment]
Hi @desmay, We have future releases planned to upgrade the .NET core version to .NET 6.0. Later we can consider upgrading the bot SDK and removing the deprecated classes.
