### ISSUE TITLE
Power BI Analytics report for CC - Connection issues..

### ISSUE THREAD

**Issue by RavinderRS** [OfficeDev/microsoft-teams-apps-company-communicator#886]
We have installed CC App V5.0.0 and upgraded it successfully to V5.2.0 and its working good so far.

When tried to set up CC Insights PBI Report Template V1.pbit file from downloading [here](https://github.com/natalianikonenko/microsoft-teams-apps-company-communicator/tree/main/InsightsPBIReport)

following the steps discussed [here ](https://github.com/Mikhail2k15/microsoft-teams-apps-company-communicator/wiki/View-analytics-with-Power-BI)we are getting the below errors...

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6483156/193147710-128bff31-ce83-49b6-9bf8-40dce7d8d32e.png)

**Comment by v-royavinash** [comment]
@RavinderRS  We won't be able to provide assistance for setting up the power BI report. Please do let us know if you are facing any issue with the functionalities or features of official repo of company communicator.
