### ISSUE TITLE
Error during publishing Azure Function

### ISSUE THREAD

**Issue by cesarorosa** [OfficeDev/microsoft-teams-apps-company-communicator#887]
I already worked with diferent versions of Company Communicator and I customized and publish those change on Azure services with Visual Studio, now I tried to deploy the last version, without any code modification. At first, I updated SDKs and Nuget package to indicated version on project, next I configure the dependencies to publish as I did in another deployments of this appication. I published the Web Service project (Microsft.Teams.Apps.CompanyComunicator) and works correcly. The problem it's when I try to publish the Azure Functions, in this three cases the publish fail in Zip Deployment step.

![image](https://user-images.githubusercontent.com/75080352/193564149-960839a5-1666-4acd-958f-9956d4868238.png)

Thanks a lots

**Comment by gsv022** [comment]
Hi @cesarorosa ,
Thanks for raising the issue. We will get back to  you with proper response soon.

**Comment by v-royavinash** [comment]
Hi @cesarorosa, Post SDK and NuGet update are you able to build successfully your Azure function in release mode?

**Comment by cesarorosa** [comment]
> Hi @cesarorosa, Post SDK and NuGet update are you able to build successfully your Azure function in release mode?

Hi, thanks for response. The SDK version of .netCore that i user it's the same that appears in global.json ("version": "3.1.108"). For NuGet package I have the following versions:
![image](https://user-images.githubusercontent.com/75080352/193748273-1e5f9eab-5df3-4c11-b628-92a0cc88b53e.png)
![image](https://user-images.githubusercontent.com/75080352/193748310-e831aed1-aade-4c43-8084-bdb68223f27f.png)
![image](https://user-images.githubusercontent.com/75080352/193748342-5e7d836e-dd18-4311-8583-0e8e23a0786f.png)
![image](https://user-images.githubusercontent.com/75080352/193748422-ba228138-18fb-48d0-9ad0-b1e17934d5ea.png)
![image](https://user-images.githubusercontent.com/75080352/193748475-f68545f6-b695-4b71-8cec-57a1d8b09364.png)

Thanks a lot for help me.

**Comment by gsv022** [comment]
Hi @cesarorosa ,
Could you please verify whether **locally build** is working fine when it is kept in **release** mode. Keep us posted.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/98143492/195014942-2a367550-26a8-4102-9374-35dde28362c9.png">

**Comment by cesarorosa** [comment]
> Hi @cesarorosa , Could you please verify whether **locally build** is working fine when it is kept in **release** mode. Keep us posted. <img alt="image" width="632" src="https://user-images.githubusercontent.com/98143492/195014942-2a367550-26a8-4102-9374-35dde28362c9.png">

Hi @gsv022 I builded and tried to publish function in Release mode, but the error still happend
![image](https://user-images.githubusercontent.com/75080352/195015988-149e811b-1b1c-4c4d-9076-d335a4257a07.png)
![image](https://user-images.githubusercontent.com/75080352/195016227-bb080472-1704-4ee3-b57f-c275a8a8d4cc.png)
![image](https://user-images.githubusercontent.com/75080352/195016431-398f895d-1a82-4ed2-bb7e-6d3b7c3a066e.png)

**Comment by v-royavinash** [comment]
@cesarorosa Please let us know if you still need any further assistance on the issue logged.
