### ISSUE TITLE
about the need to update SDK

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#894]
Hello,
Last week Microsoft announced the following information.
Is it necessary to update the SDK library for CCv4.1?
https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/

Regards,
(CC: @ATshirai)

**Comment by v-royavinash** [comment]
Thanks @MK202204  for highlighting this we will review it and keep you posted.

**Comment by gsv022** [comment]
@MK202204 , this has been added to our backlog list and will be planning to implement it in future releases post the discussion with our internal team. For now, we are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
