### ISSUE TITLE
Azure Function Apps v2/v3 End of Support

### ISSUE THREAD

**Issue by AnotherCorto** [OfficeDev/microsoft-teams-apps-company-communicator#895]
Are there any plans to upgrade functions from version 3 to 4?

Beginning on December 3, 2022, function apps running on versions 2.x and 3.x of the Azure Functions runtime can no longer be supported.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cin-process%2Cv4&pivots=programming-language-csharp

as per previous request: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/791

**Comment by v-royavinash** [comment]
@AnotherCorto Thanks for highlighting this. We do have backlog item created to upgrade the azure function version to 4 and we will be taking it in upcoming releases.

**Comment by gsv022** [comment]
@AnotherCorto , The next version of Company Communicator i.e.,v5.3 yet to release will have a updated version of Azure function we use of v4. For now, we are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
