### ISSUE TITLE
I have deployed V5 with Client ID and Client Secret but now want to use Certificates

### ISSUE THREAD

**Issue by bhaskiii** [OfficeDev/microsoft-teams-apps-company-communicator#896]
I dont want to loose existing data but want to use client certificates. Is there any way to do?
Thanks.

**Comment by v-royavinash** [comment]
@bhaskiii Ideally the decision of using certificates or secrets has to be done during the deployment only. The workaround may be is to do a new CC deployment and use the existing storage so that you don't loose the data.

But that is something we won't recommend doing directly on the production deployed instance but you can give it try with the test instances and check if it works.

**Comment by bhaskiii** [comment]
@v-royavinash Thank you for your response. 
I tried to redeploy the CC with certificates and got Preflight validation failed error message
![ccIssue](https://user-images.githubusercontent.com/6095775/196189560-7e087fbe-b3ef-4904-b914-fde3fb53298b.PNG)
Could you please let me know what might be the issue causing this error?

PS: I'm using the existing resource group and existing storage so that i don't loose the data.

**Comment by bhaskiii** [comment]
@gsv022 @v-royavinash Could you please provide any update?

**Comment by gsv022** [comment]
Hi @bhaskiii ,
Thank you for submitting this issue, as we work to ensure consistent responses with items logged in our issues list, we are working to address these items that did not get responses. Please let us know if you are still facing this issue and require assistance and we will be happy to discuss. If no further action is needed at moment and no response is received, we will close out the issue in 3 business days. You may also always open a new issue or respond here if something does come back up.

**Comment by gsv022** [comment]
@bhaskiii ,We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
