### ISSUE TITLE
 Error tenant de login-microsoft-teams-apps-company-communicator

### ISSUE THREAD

**Issue by echavarria26** [OfficeDev/microsoft-teams-apps-company-communicator#899]
Hola, intente implementar [microsoft-teams-apps-company-communicator](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator) pero me brinda el siguiente error de tenant, alguna solución que me puedan apoyar? 

![image](https://user-images.githubusercontent.com/115846137/195954927-37a6ea34-5d93-4d27-8e13-f3ee135bc0c3.png)

**Comment by v-royavinash** [comment]
Hi @echavarria26, Could you please share more details on the issue like which page you are trying to login. Is it something happening when accessing the CC author app?

Form the screenshot we could understand that the user with which you are trying to login does not exists in the tenant configured.

**Comment by echavarria26** [comment]
Hola

El usuario si esta en el tenant con el que fue configurado la app de companny comunnicator

Ese error da al iniciar sesión al CC autor de company, cundo se añade en teams.

[https://itcoint.com/firmas/Firmas-de-correo-Emerson-Beckford-Chavarr%C3%ADa.gif?_t=1660760429]

***@***.***

De: v-royavinash ***@***.***>
Enviado el: viernes, 14 de octubre de 2022 5:38
Para: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
CC: Emerson Beckford Chavarría ***@***.***>; Mention ***@***.***>
Asunto: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Error tenant de login-microsoft-teams-apps-company-communicator (Issue #899)


Hi @echavarria26<https://github.com/echavarria26>, Could you please share more details on the issue like which page you are trying to login. Is it something happening when accessing the CC author app?

Form the screenshot we could understand that the user with which you are trying to login does not exists in the tenant configured.

**Comment by echavarria26** [comment]
Habría la posibilidad de coordinar una sesión para que me puedas ayudar?

[https://itcoint.com/firmas/Firmas-de-correo-Emerson-Beckford-Chavarr%C3%ADa.gif?_t=1660760429]

***@***.***

De: Emerson Beckford Chavarría
Enviado el: viernes, 14 de octubre de 2022 5:41
Para: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
CC: Mention ***@***.***>
Asunto: RE: [OfficeDev/microsoft-teams-apps-company-communicator] Error tenant de login-microsoft-teams-apps-company-communicator (Issue #899)

Hola

El usuario si esta en el tenant con el que fue configurado la app de companny comunnicator

Ese error da al iniciar sesión al CC autor de company, cundo se añade en teams.

[https://itcoint.com/firmas/Firmas-de-correo-Emerson-Beckford-Chavarr%C3%ADa.gif?_t=1660760429]

***@***.***

De: v-royavinash ***@***.******@***.***>>
Enviado el: viernes, 14 de octubre de 2022 5:38
Para: OfficeDev/microsoft-teams-apps-company-communicator ***@***.******@***.***>>
CC: Emerson Beckford Chavarría ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Asunto: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Error tenant de login-microsoft-teams-apps-company-communicator (Issue #899)


Hi @echavarria26<https://github.com/echavarria26>, Could you please share more details on the issue like which page you are trying to login. Is it something happening when accessing the CC author app?

Form the screenshot we could understand that the user with which you are trying to login does not exists in the tenant configured.

**Comment by gsv022** [comment]
Hi @echavarria26 ,
Could you please share the MS Teams Id so that we can discuss more on this issue and troubleshoot over the call if needed.

**Comment by echavarria26** [comment]
Buenas

Me podría indicar tu disponibilidad para poder enviarte la invitación?

[https://itcoint.com/firmas/Firmas-de-correo-Emerson-Beckford-Chavarr%C3%ADa.gif?_t=1660760429]

***@***.***

De: Sai Venkat ***@***.***>
Enviado el: lunes, 17 de octubre de 2022 3:16
Para: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
CC: Emerson Beckford Chavarría ***@***.***>; Mention ***@***.***>
Asunto: Re: [OfficeDev/microsoft-teams-apps-company-communicator] Error tenant de login-microsoft-teams-apps-company-communicator (Issue #899)


Hi @echavarria26<https://github.com/echavarria26> ,
Could you please share the MS Teams Id so that we can discuss more on this issue and troubleshoot over the call if needed.

**Comment by gsv022** [comment]
Hi @echavarria26 ,
The teams id that has been shared seems to be encrypted. Could you please send the MS Teams Id again
