### ISSUE TITLE
.NET Core 3.1 will reach the end of support on 13 December 2022

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#900]
Hi,

Microsoft announced following information.
https://azure.microsoft.com/en-us/updates/staticwebappsdotnet3deprecation/
Does this end of support affect the use of CCv4.1?

Regards,
(CC: @ATshirai)

**Comment by MK202204** [comment]
@v-royavinash Thankyou for replying. Does that mean versions after 5.3?

**Comment by gsv022** [comment]
@MK202204 , The next version of Company Communicator i.e.,v5.3 yet to release will have a updated .NET version i.e., **6**. For now, we are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
