### ISSUE TITLE
CC Cleanup Function failing after the upgrade to V5.2.0 ...

### ISSUE THREAD

**Issue by RavinderRS** [OfficeDev/microsoft-teams-apps-company-communicator#902]
We recently did an upgrade from V5.0.0 to V5.2.0 and the Cleanup Function was failing ever since.. Even though we have successful CC Messages delivered the Cleanup Function kept failing..

<img width="694" alt="img-6" src="https://user-images.githubusercontent.com/6483156/197619659-dd772797-db1a-4df9-a0a7-7a2e53d57ee9.png">

And we see 1 or 2 users here and there failed in delivering the messages...

<img width="704" alt="img-7" src="https://user-images.githubusercontent.com/6483156/197620551-934aa0c2-4e7a-483f-8f79-2277644ff247.png">

**Comment by gsv022** [comment]
Hi @RavinderRS ,
Thanks for raising the query. We are working on this issue and will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @RavinderRS ,
Thanks for the patience. FYI, the CC Cleanup issue got resolved. This issue has been addressed in the latest release v5.3. So it is recommended to upgrade the cc version to v5.3. 

We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
