### ISSUE TITLE
GIFS on mobile devices

### ISSUE THREAD

**Issue by liamcosgrove30** [OfficeDev/microsoft-teams-apps-company-communicator#903]
Hi There, 

I was wondering if anyone had an idea as to why GIFs that we send out using the company communicator can be viewed without any issues on android mobile devices - however when using an iPhone, users cannot view the GIF.

**Comment by gsv022** [comment]
Hi @liamcosgrove30 ,
We don't support for mobile version as of now. It will be planned for future releases. Please make a note of this and let us know if you have any other queries related to Company Communicator.

Thank you.

**Comment by liamcosgrove30** [comment]
Thank you for your quick response, is there a planned date that we should keep in mind?

**Comment by gsv022** [comment]
Hi @liamcosgrove30 ,
As of now we have not planned yet.  We will discuss internally with the team and proceed accordingly.

**Comment by gsv022** [comment]
This has been added to our backlog list and will be planning to implement it in future releases post the discussion with our internal team. For now, we are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
