### ISSUE TITLE
"Client certificate mode" to Require for WebApp

### ISSUE THREAD

**Issue by bhaskiii** [OfficeDev/microsoft-teams-apps-company-communicator#904]
I'm unable to use communicator after setting "Client certificate mode" to Require in Incoming client certificate of App Service configuration. I have deployed the communicator app using certificate.  Do i need to do any settings/modifications for using Client certificate mode to require?

**Comment by gsv022** [comment]
Hi @bhaskiii ,
Thanks for raising the query. Could you please respond to the below queries.

- Are you able to deploy the Company  Communicator? If no, what is the error that is getting displayed.
- It is mentioned that _unable to use CC_ , is this happening after the deployment or during the deployment?
- What is the version of the app?

**Comment by bhaskiii** [comment]
Hi @gsv022,
I have deployed the Company Communicator v5.2 using certificate method.
The deployment was successful but when we want to use this cc in more secure way. So we added a [Azure Policy](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F5bb220d9-2698-4ee4-8404-b9c30c9df609) "App Service apps should have 'Client Certificates (Incoming client certificates)' enabled" to this resource group. 
![IncomingClientCertificate](https://user-images.githubusercontent.com/6095775/199490533-762c49f6-4794-46c2-9bd1-6715591f729d.PNG)
After this i can only see loading screen and unable to use Company Communicator
![cc](https://user-images.githubusercontent.com/6095775/199490711-b28fa35e-6071-4f71-bc1a-edc21cc423e9.PNG)

It is manadatory for us to keep Client Certificate mode as Require.

**Comment by gsv022** [comment]
Hi @bhaskiii ,
Currently the resource **app service** that is deployed will not work if it is restricted using the certificate authentication, because the default implementation of the CC doesn't support it. So if there is a need to have this type of check then it has to be updated/implemented at the code level for this customization is required. For now, we will consider this as a **enhancement**. We will discuss internally and plan for future releases.

**Comment by gsv022** [comment]
@bhaskiii This has been added to our backlog and will be planning to implement it in future releases. We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
