### ISSUE TITLE
API Versions being retired for Azure API Management

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#907]
Hi,

Microsoft announced following information.
https://azure.microsoft.com/en-us/updates/api-versions-being-retired-for-azure-api-management/

I deployed CC4.1 before August 2021.
Will this affect deployed CC?

Regards,
(CC: @ATshirai)

**Comment by gsv022** [comment]
Hi @MK202204 ,
Thanks for raising the query. Please give us sometime and will get back to you proper response soon.

**Comment by gsv022** [comment]
@MK202204 , we're closing this issue since this concern is already added to our backlog and will be considered in future releases of CC based on the priority.
