### ISSUE TITLE
Fail to post massages

### ISSUE THREAD

**Issue by idanbarshlomo** [OfficeDev/microsoft-teams-apps-company-communicator#908]
When trying to post massages I am getting the below error and all recipients not receiving the massages

![image](https://user-images.githubusercontent.com/89249098/200551981-9be3fbd3-fcdc-4b8d-b9cf-229291a6bef4.png)

**Comment by v-royavinash** [comment]
Hi @idanbarshlomo , could you please share what's the error or the status of message that is showing at Author app? Its better, if you can share a screenshot of the Author app for the message which was not delivered.

**Comment by idanbarshlomo** [comment]
Please see below

![image](https://user-images.githubusercontent.com/89249098/200793906-0a5b467e-cb5c-468a-9ed5-29ff68ca89e1.png)

Also adding the results:

![image](https://user-images.githubusercontent.com/89249098/200794417-17b2e8b2-95d3-49f4-b74c-bfabb5a2208b.png)

**Comment by gsv022** [comment]
Hi @idanbarshlomo ,
Could you please verify that user app is installed at the tenant level and then make sure that it is added to the specific team.
Keep us posted.

**Comment by idanbarshlomo** [comment]
Yes, it's installed proactively

![image](https://user-images.githubusercontent.com/89249098/201512479-6583d629-c3d6-4afe-8673-5397cd8b3355.png)

And also published from Teams for all tenant

**Comment by gsv022** [comment]
Hi @idanbarshlomo ,
Could you please respond to the below queries.

- Please send a screenshot showing that user app is uploaded at the tenant level. Below is the screenshot for the reference.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98143492/201624391-35f67357-cdb5-4d2d-9afa-7e936d5d68c9.png">

- If already done, please perform the below procedure
    1.    Navigate to Azure portal and open company communicator deployed resource group.
    2.    Click on “Storage account”
    3.    Expand “Tables” section
    4. Open “AppConfig” table
    5.  Delete the second record where Rowkey is entered as “UserAppId”
 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/201625507-78bb4580-db16-4b34-99c9-ea459b5c8af2.png">

- Try sending a message after doing this. Kindly, let us know if it worked.

**Comment by idanbarshlomo** [comment]
Yes, I can see the app under Built for your org section in all Apps.
I have deleted the file but the issue still remain, let me know if you have other suggestion or can assist in a call.

**Comment by idanbarshlomo** [comment]
Any ideas ?

**Comment by gsv022** [comment]
Could you please share the  MS Teams id so that we can discuss more on the issue over the call if needed.

**Comment by idanbarshlomo** [comment]
Meeting ID: 349 269 278 334

**Comment by gsv022** [comment]
please share the MS Teams ID only.

**Comment by gsv022** [comment]
Hi @idanbarshlomo ,
Apology for the miscommunication. Please share your **email id**(MS Teams Id) so that we can discuss  more on this issue over the call if needed.

**Comment by idanbarshlomo** [comment]
idanba@payoneer.com

**Comment by gsv022** [comment]
It is confirmed that the issue got resolved. We are closing the issue. If you face any issue with company communicator please raise a new issue for further assistance.
