### ISSUE TITLE
Change details from Company communicator v5.0 to v5.2

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#910]
Please provide an elaborate description about the changes done from v5.0 to v5.2.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query. Here is the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Release-notes) gives the features of each release. Please let us know if you need more details.
