### ISSUE TITLE
Client Secret expiration and update

### ISSUE THREAD

**Issue by Sreeraj-kroll** [OfficeDev/microsoft-teams-apps-company-communicator#911]
Hi

We have been using client id and secret based on the documentation. Now that the secret is approaching expiry, we would like to know which resources needs to be updated with the new secret and how. 

Do you have any documentation we can follow.

Thanks

**Comment by gsv022** [comment]
Hi @Sreeraj-kroll,
Please follow the below  procedure. 
- Go to Azure Portal
- Go to App registration
- If the secret is already expired/nearing to expiry, click ‘New client secret’ and generate it.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/201635245-3d3145de-ae45-421a-aeb9-3665b1336ebe.png">
- Copy the value, navigate to the Azure key vault for Company Communicator -> Secrets -> update the AuthorAppPassword
<img width="709" alt="image" src="https://user-images.githubusercontent.com/98143492/201636091-ea516065-5c56-440c-82f5-1a5f25a51efe.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/98143492/201623438-f3d488f2-5d61-4a31-9523-9385893aba6e.png">

- Copy the key vault URL of author app password.  Update the URL in configuration of **app service** and **3 function apps** **wherever necessary**.
**Note:- Please repeat the above steps user App password and Graph App Password(whichever is nearing to expiry).**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98143492/201638001-58696a3f-da22-4a2a-ae1d-7bc1e0e244cf.png">


- Restart the app services, function apps.
