### ISSUE TITLE
Is app insight compulsory for the deployment of communicator?

### ISSUE THREAD

**Issue by tomatosis** [OfficeDev/microsoft-teams-apps-company-communicator#912]
When did a cost estimation and found app insight can cost up to $345 for 150GB data, it would be more than $4k yearly without adding in other components. This is huge amount in terms of a small app. Hence, would like to understand if this is really needed. If yes, how can we estimate the actual ingested data more accurately?

**Comment by v-royavinash** [comment]
@tomatosis, The estimated load for CC application insight will be way less than the one you sited. PFB, the estimated cost for 2 million messages. 

![image](https://user-images.githubusercontent.com/94480537/207209596-5d3af10e-8ffc-486a-9f89-40eada5d305e.png)

Even if the data exceeds 5 GB (very less likely), it will not that much of load on the cost side.

**Comment by gsv022** [comment]
@tomatosis , We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
