### ISSUE TITLE
We couldn´t find any matches

### ISSUE THREAD

**Issue by dheerendrakumarmittal** [OfficeDev/microsoft-teams-apps-company-communicator#914]
I published the app yesterday, and tried to send out some messages to some teams .
Unfortunately I always get the message:"We couldn´t find any matches"

![image](https://user-images.githubusercontent.com/118262579/202184574-f160589c-b575-4833-8109-f3e795b5ca29.png)

**Comment by gsv022** [comment]
Hi @dheerendrakumarmittal ,
Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by dheerendrakumarmittal** [comment]
hi team 

After refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) Still  getting same issue .please guide me .

**Comment by dheerendrakumarmittal** [comment]
hi team

Please Response ASAP

**Comment by gsv022** [comment]
Hi @dheerendrakumarmittal ,
Could you please send the message using the 4th sending option- Distribution list.

**Comment by dheerendrakumarmittal** [comment]
Hi Team 
After using 4th sending option still getting same problem "We couldn't find any matches."
please do needful asap .

**Comment by gsv022** [comment]
Hi @dheerendrakumarmittal 
Could you please share us the MS Teams Id so that we can have discussion over the call if needed.

**Comment by dheerendrakumarmittal** [comment]
Hi Team
4c12d8ac-a35e-4612-8285-25883e2a0c6a    This Is My Team id (groupId)

**Comment by gsv022** [comment]
Hi @dheerendrakumarmittal ,
Sorry for the miscommunication. Please share your **email id**(MS Teams Id) to discuss more on the issue.

**Comment by dheerendrakumarmittal** [comment]
Hi Team

dkumar4616@gmail.com

**Comment by gsv022** [comment]
As discussed a mail has been sent. Please do the necessary.
