### ISSUE TITLE
Bot fails to send a message to a user

### ISSUE THREAD

**Issue by Sreeraj-kroll** [OfficeDev/microsoft-teams-apps-company-communicator#915]
We were testing out Company Communicator to a small group before business wide roll out, and found that one of the bot was unable to send messages to one user. 

We have ensured that the user has the right App Setup policy and Permission Policy. The user was also able to see in the "Company Communicator User" app installed and this was again verified via Graph.

We had also tried to remove and readd the user into the policies but in vain. Any help is much appreciated. 

Please see the error details below.

Status Reason : 403 Failed
Error:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SREERA~1.RAM/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SREERA~1.RAM/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Microsoft.Bot.Schema.ErrorResponseException:   Operation returned an invalid status code 'Forbidden'             at   Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String   conversationId, String activityId, Activity activity, Dictionary`2   customHeaders, CancellationToken cancellationToken)             at   Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations   operations, String conversationId, String activityId, Activity activity,   CancellationToken cancellationToken)             at   Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext   turnContext, Activity[] activities, CancellationToken   cancellationToken)             at   Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass31_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter\|1>d.MoveNext()          --- End of stack trace from previous location where exception was thrown   ---             at   Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity,   CancellationToken cancellationToken)             at   Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_1.<<SendMessageAsync>b__1>d.MoveNext()   in C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94          --- End of stack trace from previous location where exception was thrown   ---             at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3   action, Context context, CancellationToken cancellationToken,   ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1   shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount,   IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean   continueOnCapturedContext)             at   Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context,   CancellationToken cancellationToken, Boolean continueOnCapturedContext)             at   Microsoft.Teams.Apps.CompanyCommunicator.Common.Services.Teams.MessageService.<>c__DisplayClass3_0.<<SendMessageAsync>b__0>d.MoveNext()   in   C:\home\site\repository\Source\CompanyCommunicator.Common\Services\Teams\Messages\MessageService.cs:line   94
--

</body>

</html>

**Comment by Sreeraj-kroll** [comment]
Here is the status output

[Message_Delivery.csv](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10028321/Message_Delivery.csv)

**Comment by gsv022** [comment]
Hi @Sreeraj-kroll ,
Thanks for sharing the logs. Could you please respond to the below queries.

1. What is the version of the app?
2. Through which sending option, did this error occur?
3. Is this happening with all the sending options?
4.  Could you please follow the below procedure and try sending a message again.

-      Navigate to Azure portal and open company communicator deployed resource group

-     Click on “Storage account”

-     Expand “Tables” section

-     Open “AppConfig” table

-     Delete the second record where Rowkey is entered as “UserAppId”
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98143492/202380819-c3bab7c8-692c-4077-8017-4d551146344d.png">

Above is the screenshot for the reference. Let us know if it worked.

**Comment by Sreeraj-kroll** [comment]
Hi Sai


  *   The version is 5.2
  *   We tried, “Send in chat to members of the following team” as well as “Send in chat to members of the following M365 groups, Distribution groups or Security groups”
  *   The “Send to General channel of specific teams” work fine, we have not tried “Send in chat to everyone” as we are currently only testing it for a specific group of users
  *   I tried the deleting the UserAppId from the AppConfig table, but the message was not sent to the user

_____________________________________________
Sreeraj Ramachandran
Senior Microsoft Teams Engineer, Technology

***@***.*** Chat with me on ***@***.***>

***@***.*** +44 7721161887



From: Sai Venkat ***@***.***>
Sent: 17 November 2022 07:17
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Ramachandran, Sreeraj ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-apps-company-communicator] Bot fails to send a message to a user (Issue #915)


Hi @Sreeraj-kroll<https://urldefense.com/v3/__https:/github.com/Sreeraj-kroll__;!!LrwELaEne27E!6rZMvyCRjkDmF7HEHA8y3i7IpIFYGQYLg_CYMwbltWb6YhapT508814oQ_345hKDwx4LUx-oX9fKMOAXRcnuM11z-vlnU2k$> ,
Thanks for sharing the logs. Could you please respond to the below queries.

  1.  What is the version of the app?
  2.  Through which sending option, did this error occur?
  3.  Is this happening with all the sending options?
  4.  Could you please follow the below procedure and try sending a message again.

·          Navigate to Azure portal and open company communicator deployed resource group

  *

·         Click on “Storage account”

  *

·         Expand “Tables” section

  *

·         Open “AppConfig” table

  *

·         Delete the second record where Rowkey is entered as “UserAppId”

  *

[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/98143492/202380819-c3bab7c8-692c-4077-8017-4d551146344d.png__;!!LrwELaEne27E!6rZMvyCRjkDmF7HEHA8y3i7IpIFYGQYLg_CYMwbltWb6YhapT508814oQ_345hKDwx4LUx-oX9fKMOAXRcnuM11zvZ0CxNI$>

Above is the screenshot for the reference. Let us know if it worked.

**Comment by gsv022** [comment]
Hi @Sreeraj-kroll ,
Could you please do the following.

-  Navigate to Azure portal and open company communicator deployed resource group
- Click on “Storage account”
- Expand “Tables” section
- Open UserData Table
- Except "AuthorData" please remove the remaining entities.
- And open “AppConfig” table
- Delete the second record where Rowkey is entered as “UserAppId”


Please let us know if this worked. 
Thank you.

**Comment by Sreeraj-kroll** [comment]
Hi Sai

I did that, but it did not work unfortunately.

I have requested the user to delete any Teams cache.

I’ll keep you posted
Thanks
________________________________
From: Sai Venkat ***@***.***>
Sent: Monday, November 21, 2022 11:50:22 AM
To: OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc: Ramachandran, Sreeraj ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-apps-company-communicator] Bot fails to send a message to a user (Issue #915)


Hi @Sreeraj-kroll<https://urldefense.com/v3/__https://github.com/Sreeraj-kroll__;!!LrwELaEne27E!8BoUBEPRhqOa2xetKC59wIm9DCOKt3sNJfhILd_SrLvSuFd7sp80RjoE6uIeGwOrauw4TPFYjqMfJ-KIBdMNRPVXnEd_P6k$> ,
Could you please do the following.

  *   Navigate to Azure portal and open company communicator deployed resource group
  *   Click on “Storage account”
  *   Expand “Tables” section
  *   Open UserData Table
  *   Except "AuthorData" please remove the remaining entities.
  *   And open “AppConfig” table
  *   Delete the second record where Rowkey is entered as “UserAppId”

Please let us know if this worked.
Thank you.

**Comment by Sreeraj-kroll** [comment]
Signing out from Teams, then clearing the cache using the attached powershell did the job

[Teams cache clean.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10058409/Teams.cache.clean.txt)

**Comment by gsv022** [comment]
Thanks for the update. We are closing the issue.
