### ISSUE TITLE
Issue Purging Old Messages 

### ISSUE THREAD

**Issue by EYSue** [OfficeDev/microsoft-teams-apps-company-communicator#916]
At EY we are looking to improve performance of Company Communicator by purging old messages sent over 6 months ago. Messages are displayed on pages (100 lines max) and there only seems to be an option to delete one page at a time. If this is the case we would need to manually delete thousands of pages manually one by one to complete this activity. Can you advise if there is an easier more efficient way to purge a large number of historical messages at once.

**Comment by gsv022** [comment]
Hi @EYSue ,
Thanks for raising the query. We will be tracking this internally.

**Comment by gsv022** [comment]
Hi @EYSue ,
As we have responded internally to the query. Please let us know if you any other inputs required from our end or else we are good to close the issue.

**Comment by EYSue** [comment]
Hi Sai

I have the information required so you are good to close the case.

Regards

Sue

**Comment by gsv022** [comment]
@EYSue , We are closing this request as the we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
