### ISSUE TITLE
Allow http (not https) link for image and button urls.

### ISSUE THREAD

**Issue by runceel** [OfficeDev/microsoft-teams-apps-company-communicator#917]
Now, for internet, https is by default. However, for intranet, http is still there.

I want to share a http link that is one of intranet contents. But Company Communicator doesn't allow http link.
Is thre any options to send http link on Company Communicator?

**Comment by gsv022** [comment]
Hi @runceel ,
Thanks for raising the query. Currently Company Communicator doesn't support **HTTP**. 

- This is a place where check has been added and it is recommendation from Microsoft. If the modification is a must from your end. Here is the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/blob/main/Source/CompanyCommunicator/ClientApp/src/components/NewMessage/newMessage.tsx) which will direct you to the page where the restriction has been implemented.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/98143492/203041377-b7765991-57b6-4857-8521-06078ba591f5.png">

- Or While sending a message to the intended users. Please caution them during the message drafting by saying that **"Please cross check the URL and remove s from https:// to make it "http://" before browsing the link."**

**Comment by runceel** [comment]
@gsv022 
Thank you for answering.
I will customize Company Communicator to support `http://`.

Do you have any plan to support `http://` in original Company Communicator?

**Comment by gsv022** [comment]
Not yet. It will be planned for future releases post the discussion with internal team. Please let us know if you have any other queries.

**Comment by runceel** [comment]
@gsv022 Thank you! :)
