### ISSUE TITLE
Ms Teams Communicator app don't recognize dynamic distribution group 

### ISSUE THREAD

**Issue by yogeshbhalerao617** [OfficeDev/microsoft-teams-apps-company-communicator#919]
Ms Teams Communicator app don't recognize dynamic distribution group, kindly help to resolve this query. 
Quickly reach me on below contact details.
+91 9762222981
yogesh_bhalerao@persistent.com
yogesh_bhalerao-a@persistent.co.in

**Comment by gsv022** [comment]
Hi @yogeshbhalerao617 ,
Thanks for logging the issue.  CC does not support sending message to dynamic distribution list. We don't have any specific ETA to enable feature to support dynamic distribution group. However we've few partners who did a work around and able to send the msg to DDL, here is the reference.
[Allow the Company Communicator to send to Dynamic Distribution Lists · Issue #671 ·](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/671)

**Comment by gsv022** [comment]
Hi @yogeshbhalerao617 ,
Please let us know if you any queries related to Company Communicator.
