### ISSUE TITLE
Company communicator does not allow sending to M365 groups

### ISSUE THREAD

**Issue by jmcastillog** [OfficeDev/microsoft-teams-apps-company-communicator#920]
Good morning, when trying to send, I get this error, I have verified that:

![image](https://user-images.githubusercontent.com/119298666/204261078-1c563d83-d2ac-418b-b3ac-03a45822897d.png)
(translate to english)
![image](https://user-images.githubusercontent.com/119298666/204261464-1f0fcf6e-3b60-4cbc-863c-ff2d96ba8ba9.png)

The user can send (from the rest of the functions it appears ok)

I have reviewed other related threads and I have seen that there are several solutions, to give that permission for example I have reviewed this:
![image](https://user-images.githubusercontent.com/119298666/204261898-0e2fd318-1b62-4fa4-9e6f-3ee0e71b2351.png)

and This: 
![image](https://user-images.githubusercontent.com/119298666/204262500-da4fc6a9-0912-486d-a6ff-eb8b9fee1531.png)

This configuration is assigned in the authors app only, do I have to do it in the api and the readers too?

Any other idea?

**Comment by gsv022** [comment]
Hi @jmcastillog ,
Thanks for raising the query. Could you please respond to the below query.

- What is the gitrepo URL and branch that has been used while creating the ARM template. Below is the screenshot for the reference.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/98143492/204268766-d68c11c0-d767-4bbc-beda-566a5b1abe48.png">

**Comment by jmcastillog** [comment]
hi @gsv022 
This??
![MicrosoftTeams-image (27)](https://user-images.githubusercontent.com/119298666/204480966-24134bcc-6f0a-41bd-ad7f-84ae9530bade.png)

**Comment by gsv022** [comment]
Hi @jmcastillog ,
These might be the places for possibilities of the error.
1. Could you please verify the graph app [set up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) step was correctly configured or not and check mainly on API permissions.
2. Please verify the graph app client secret is correctly copied while creating ARM template or not. Attaching the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911) where you can compare and check on secrets.

Keep us posted. Thank you.

**Comment by jmcastillog** [comment]
Everithing are solved. The issue was in the application of permissions and the changes of these in version 5.2.  The solution was in the manual, sorry for the inconvenience.

**Comment by gsv022** [comment]
@jmcastillog , Glad that the issue got solved. We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
