### ISSUE TITLE
Microsoft - Teams - Company Communicator Error 

### ISSUE THREAD

**Issue by mccjayme** [OfficeDev/microsoft-teams-apps-company-communicator#921]
As of November 22, 2022 all of our Authorized (Authors) Enabled for Company Communicator are getting the following Error -> Permissions needed. Ask your IT admin to enable this option for you. When select the Send in chat members of the following M365 groups, Distribution groups or Security groups -> Attached Screen Shot:
[](url)
![CompanyCommunicator_Error_Nov22_2022](https://user-images.githubusercontent.com/97609953/204616646-51bfe7af-e56b-47df-85ac-19833e334a21.jpg)

I've been instructed to report this Issue via the GitHub by Microsoft Support - Case # [33997099] Unable to access M365 groups for App... - TrackingID#2211230010001938. 

I can be contacted via the below signature to work through this ASAP so we can continue to Mass Communications to our End Users in our Tenant - Company Audience. 

Thanks,

Jayme McClendon 
Principal – Unified Communications Architect 
SUTHERLAND GLOBAL
Single Number Reach: +1 585-450-4476
E: [Jayme.McClendon@sutherlandglobal.com](mailto:Jayme.McClendon@sutherlandglobal.com)

CST – Central Standard Time – (GMT-6)

**Comment by gsv022** [comment]
Hi @mccjayme ,
Thanks for raising the query. Could you please respond to the below query.

- What is the gitrepo URL and branch that has been used while creating the ARM template. Below is the screenshot for the reference.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/98143492/204268766-d68c11c0-d767-4bbc-beda-566a5b1abe48.png">

**Comment by mccjayme** [comment]
Hi gvs022,

First off thanks for acknowledging our Ticket #921 and offering to assist.

I need you to specifically instruct me step by step where to find this Deployment - Inputs inside my Azure AD please?

I've spend over 10-15 minutes trying to locate this specific information - screen shot and I need your assistance - Please advise and I'll get this to you ASAP. Here is the screen shot of where I'm starting and trying to locate the path to get your specific Ask.



Thanks Jayme McClendon of Sutherland Global UC Team
![Reported_GitHub_921_Issues_Dec_2_2022](https://user-images.githubusercontent.com/97609953/205330723-afa14414-7477-4ff5-9075-ea6c6ccfd6b3.jpg)

**Comment by mccjayme** [comment]
Hi Sai Venkat,

I replied in GitHub to your question – I need assistance in locating the request information per your expertise – Please advise?

Thanks,


***@***.***<http://www.sutherlandglobal.com/>

Jayme McClendon
Principal – Unified Communications Architect
SUTHERLAND GLOBAL
Single Number Reach: +1 585-450-4476
E: ***@***.******@***.***>

CST – Central Standard Time – (GMT-6)

**Comment by gsv022** [comment]
Hi @mccjayme ,
Please follow the procedure mentioned below.

- Go to Azure Portal
- Click on Resource Group
- Under your subscription, select the resource group where deployment has been done
- Please open the highlighted one. Screenshot has been shared for the reference
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png">

- Click on  Microsoft template

<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png">

- Then select **inputs** from left section where you can find the GitHub repo URL and Branch that are used. Please share them.

**Comment by mccjayme** [comment]
Hi gsv022,

Thanks for the exact instructions and path to locate what you need to look at. Per your instructions here is the screen shot of where I pulled the information and to include the information URL's and Branch as follows:

gitReporUrl - https://github.com/microsoft-teams-cc/ccbotcev2
gitBranch - master


![Reported_GitHub_921_Issues_Dec_5_2022](https://user-images.githubusercontent.com/97609953/205680313-edda3869-4af2-4b05-8348-3ef7b07cf301.jpg)


Look forward to your response - Next Step's - Also this reported issue interally is getting escalated - Anyway we can get on a call for next actions or ETA on when we can get this fixed or tested - Please advise and I can set up the meeting if needed... We appreicate your help gsv022.. :)

Thanks

Jayme McClendon 
Principal – Unified Communications Architect 
SUTHERLAND GLOBAL
Single Number Reach: +1 585-450-4476
E: [Jayme.McClendon@sutherlandglobal.com](mailto:Jayme.McClendon@sutherlandglobal.com)

CST – Central Standard Time – (GMT-6)

**Comment by mccjayme** [comment]
Hi gsv022,,

I need a status update on this please ASAP - I'm getting pressure and esclations to why our Company Commnicator is not working. My Microsoft Account Team has referred me to you Guy's here in GitHub - Please advise or I can have phone call or Microsoft Teams meeting to share screens - expedite.

Thanks,

Jayme McClendon
Principal – Unified Communications Architect
SUTHERLAND GLOBAL
Single Number Reach: +1 585-450-4476
E: [Jayme.McClendon@sutherlandglobal.com](mailto:Jayme.McClendon@sutherlandglobal.com)

CST – Central Standard Time – (GMT-6)

**Comment by gsv022** [comment]
Hi @mccjayme ,
These might be the places for possibilities of the error "**_Permissions needed. Ask you IT admin to enable this option for you_** "
1. Could you please verify the graph app [set up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) step was correctly configured or not and check mainly on API permissions.
2. Please verify the graph app client secret is correctly copied while creating ARM template or not. Attaching the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911) where you can compare and check on secrets.

We understand the situation. But the repo URL and branch is not pointing to the official repository. We won't able to provide  much assistance on this.

**Comment by mccjayme** [comment]
Hi gsv022 - Sai,

I've followed your instructions and I'm having a hard time finding the exact information you are asking in Bullet Points 1 and 2. 

Is there any way we can meet via Microsoft Teams Meeting and walk through this together please? 

I was brought into the original project about half way through the initial set-up of Microsoft Company Communicator so I'm not as well versed on exactly everything - Also some of my access I'm Denied so I need to exactly what do via Graph Azure AD app to include Client Secret expiration and update. If I need to pull in additional Admin that has that access I will for the meeting.

Let me know as soon as you can and I'll arrange and make myself available as needed per your schedule. 

Jayme McClendon 
Principal – Unified Communications Architect 
SUTHERLAND GLOBAL
Single Number Reach: +1 585-450-4476
E: [Jayme.McClendon@sutherlandglobal.com](mailto:Jayme.McClendon@sutherlandglobal.com)

CST – Central Standard Time – (GMT-6)

**Comment by gsv022** [comment]
@mccjayme , Following the issue internally.

**Comment by gsv022** [comment]
Hi @mccjayme ,
We had a discussion with the team. As this is a customized version, our support scope is very limited. We will not be able to provide much assistance on this issue. We are closing out the issue as we have provided the required response. Please raise a new issue if you have any observation(s) with standard version.

Thank you.
