### ISSUE TITLE
Permissions needed. Ask your IT admin to enable this option for you in company communicator app

### ISSUE THREAD

**Issue by NikhilDhumal734** [OfficeDev/microsoft-teams-apps-company-communicator#922]
In company communicator Author app, only Send in chat to everyone option is working rest all three options not working at all. I have followed all the steps mentioned in Deployment guide but still not working. Any helps or leads would appreciate.
![Send in chat to distribution,Security groups](https://user-images.githubusercontent.com/119613793/205105305-b8c2d157-61ae-4e39-afbe-a22f4504a159.PNG)
![Send in chat to members of the following teams](https://user-images.githubusercontent.com/119613793/205105310-521545a3-fa5d-4ef3-8d29-9b103c34f7a5.PNG)
![General channel of specific team](https://user-images.githubusercontent.com/119613793/205105314-21525f9f-41d5-470b-be0e-c3ee580689b6.PNG)

**Comment by gsv022** [comment]
Hi @NikhilDhumal734 ,
Thanks for raising the query. These might be the places for possibilities of the error "**_Permissions needed. Ask you IT admin to enable this option for you_** "
1. Could you please verify the graph app [set up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) step was correctly configured or not and check mainly on API permissions.
2. Please verify the graph app client secret is correctly copied while creating ARM template or not. Attaching the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911) where you can compare and check on secrets.
-------------------------------------------------------------------
3. "**_We could not find any matches_**" Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue”.

**Comment by NikhilDhumal734** [comment]
Hi @gsv022,

We have verified Graph app Authentication steps was  set up correctly also required API permissions was granted. but still getting the error as "Permissions needed. Ask you IT admin to enable this option for you ". 

We are still verifying the graph app client secret whether it's correctly copied or not while creating ARM template. will keep you updated on this. Thanks
 
![image](https://user-images.githubusercontent.com/119613793/205688836-838564fc-5d5b-4735-b802-822a9cb08d3d.png)

**Comment by NikhilDhumal734** [comment]
Hi @gsv022,

We have verified Authors, Users and Graph app client secrets which configured correctly while creating ARM template. still we are getting error as "Permissions needed. Ask you IT admin to enable this option for you ". Any workarounds or leads would be helpful!
![image](https://user-images.githubusercontent.com/119613793/207024614-aeb90cb3-486c-4aed-beb7-82d8e8e9957b.png)

**Comment by gsv022** [comment]
Hi @NikhilDhumal734 ,
Could you please verify the **AzureAdClientId** , **AzureAdClientSecret** in the configuration section of App service. There might be a chance that these got incorrectly updated.

- **AzureAdClientId**==**GraphAppId**,  
**AzureAdClientSecret**==**GraphAppPassword**. Below is the screenshot for reference. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/98143492/207029953-fe1135fc-e579-4a67-9ef9-a215379bdcb0.png">

Please keep us posted.

**Comment by NikhilDhumal734** [comment]
Hi @gsv022,
We have verified both the AzureAdClientId , AzureAdClientSecret in the configuration section of App service. which was correctly updated as per the below settings : 
AzureAdClientId==GraphAppId,
AzureAdClientSecret==GraphAppPassword.
![image](https://user-images.githubusercontent.com/119613793/207252731-2ccd4f53-2abd-40a7-a029-ef1d2b5a7973.png)

**Comment by gsv022** [comment]
@NikhilDhumal734 , Could you please share your email id(MS Teams Id) to discuss more on this issue. We will get into the call if needed.

**Comment by NikhilDhumal734** [comment]
Hi @gsv022,

Can I schedule a call for tomorrow 15th December 12:00 PM IST.

**Comment by gsv022** [comment]
Hi @NikhilDhumal734 ,
Please share your outlook Id (emaild/MS Teams Id), we will send out a meeting invite and try to sort out the issue over the call. And it is not permitted to schedule a call from your side.

**Comment by NikhilDhumal734** [comment]
Hello @gsv022 
Please share the meeting invite to nikhildhumal6464@outlook.com 
Thanks

**Comment by gsv022** [comment]
Hi @NikhilDhumal734 ,
We have sent out a meeting invite. Please let us know if that works for you. We will re-schedule accordingly.

**Comment by NikhilDhumal734** [comment]
Hi @gsv022,

That works for me.
Thanks

**Comment by gsv022** [comment]
@NikhilDhumal734, Could you please let us know the status. If no inputs are required from our end, we will be closing out the issue.

**Comment by EmmanuelleC** [comment]
Hi @NikhilDhumal734 and @gsv022 ,

I've exactly the same problem whith de deployment of a second instance.
I check Graph app permission and it's ok : 
![image](https://user-images.githubusercontent.com/74009824/211055484-b0e737d6-37ad-490f-9e15-b1a1e5356fd1.png)
I check in Azure Service App :
AzureAdClientId==GraphAppId,
AzureAdClientSecret==GraphAppPassword.

Could you tell me how you fixed this issue ?

Thanks in advance,
Regards,
Emmanuelle
