### ISSUE TITLE
Permissions Error: Ask IT admin to enable feature

### ISSUE THREAD

**Issue by alexl-2397** [OfficeDev/microsoft-teams-apps-company-communicator#923]
Hi, sorry to bother you all, I can see the other posts and so I've tried following the guidance given on them to resolve this issue.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/105488615/205288492-c84e6669-463d-473b-8c38-af73ffcbf90c.png">

I've updated the Client Secrets in each of the App Registrations, have updated the Keyvault with those details, and have updated the App Service Configuration with the new Key Vault references, however I'm still getting the error.
I have restarted the functions and app service too.

All the API permissions check out too.
Thank you.

**Comment by gsv022** [comment]
Hi @alexl-2397 ,
Thanks for raising the query. These might be the places for possibilities of the error "**_Permissions needed. Ask you IT admin to enable this option for you_** "
1. Could you please verify the graph app [set up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) step was correctly configured or not and check mainly on API permissions.
2. What is the version of the app?
3. Were you able to send the message through remaining 3 sending options?


Please keep us posted.

**Comment by gsv022** [comment]
Hi @alexl-2397 ,
Could you please share your email id(MS Teams Id) so that we can discuss more on this issue and connect over the call if needed.

**Comment by gsv022** [comment]
@alexl-2397 , We are closing this request as the issue got resolved. If you face any issue with company communicator please raise a new issue for further assistance.

**Comment by tomatosis** [comment]
I encounter the same error and no error message showed up for the first 3 sending options. May I know what is the fix? Thanks

**Comment by tomatosis** [comment]
Hi Alex,
Thanks for the reply.

i manage to create a new secret for Author/User/App Registration Secret but not able to update in key vault. As per the forum, looks like we have to update in key vault first and then it will update in configuration.
***@***.***
***@***.***

Btw, AzureAdClientSecret will share the same secret with Graph App Registration ?

***@***.******@***.***

Once we manage to update the secret, do we need to repackage the app?

Thanks for your advise.

Regards,
Grace

**Comment by alexl-2397** [comment]
Hi @tomatosis,
You may need to add the new secret into the Key Vault by adding it as a new version
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/105488615/234892011-dc018cc1-0208-4400-ad45-9caf84547103.png">
I personally updated the keyvault reference myself in the app service, but it may work for you?
And yep, the AdClientSecret and Graph will share the same keyvault ref.

All you'll need to do is restart the app service once done
