### ISSUE TITLE
Bug in CreateAzureADApp function in deploy.ps1

### ISSUE THREAD

**Issue by thomassadowski** [OfficeDev/microsoft-teams-apps-company-communicator#924]
I found an issue in the deploy.ps1 powershell file. Specifically it is in the CreateAzureADApp function (Line 284). The AZ AD App Create and Update commands no longer support the oauth2-allow-implicit-flow switch or the MultiTennant switch. It appears that MultiTennant has been replaced with "Sign-In-Audience".

I fixed this by adding an if statement right after the function parameters as follows...

   if ($MultiTenant) {$audience = "AzureADMultipleOrgs"} else {$audience = "AzureAdMyOrg"}

I then updated the create and update lines like this...
   az ad app update --id $app.appId --sign-in-audience $audience
   az ad app create --display-name $appName --sign-in-audience $audience

**Comment by gsv022** [comment]
Hi @thomassadowski ,
Thanks for raising the query. The Azure CLI version should be 2.30. If it is not same, could you please download the [Azure CLI version](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.30.0.msi) and try creating AzureADApp.

Keep us posted.

**Comment by thomassadowski** [comment]
I checked and the system I was using is on Azure-CLI version 2.42.0.

**Comment by gsv022** [comment]
@thomassadowski , Please uninstall 2.42.0 Azure CLI version and please download the [Azure CLI version](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.30.0.msi) having 2.30.0 version and try creating AzureADApp.

**Comment by thomassadowski** [comment]
That doesn't make sense to me. Since 2.4 is the current version, shouldn't this be updated to support that? Also I succeeded in deploying the resources using 2.4 by making the changes I shared. So I have no further need of help, this is more for your information on maintaining the product.
