### ISSUE TITLE
Can't find Teams or Teams Users in the dropdown

### ISSUE THREAD

**Issue by Durk1969** [OfficeDev/microsoft-teams-apps-company-communicator#925]
Hello, 

We have an issue with finding Teams or Teams Users in the dropdown while sending the message.
We installed the company communicator trough this instruction:
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

Installation went well. We also looked in the issue guide but that also coult not fix our problem.

These are the app permissions:
![image](https://user-images.githubusercontent.com/103175505/205867809-b30a9e19-8ad4-48f7-a39b-33871cdf1b03.png)

![image](https://user-images.githubusercontent.com/103175505/205868240-b1047007-c7f1-4ad5-a58e-bb3bb9e521fe.png)

![image](https://user-images.githubusercontent.com/103175505/205868585-0c73ae73-a94d-4dbe-8796-b88b70209510.png)

I hope someone has the solution to our problem.

**Comment by gsv022** [comment]
Hi @Durk1969 ,
Thanks for raising the query. Could you please share the manifest files for both author and user.

**Comment by Durk1969** [comment]
[company-communicator-users.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10167633/company-communicator-users.zip)
[company-communicator-authors.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10167634/company-communicator-authors.zip)

These are the zip files with the manifest in it.

**Comment by Durk1969** [comment]
@gsv022 thx for the update. I removed the user app in Teams admin center, at permissiosn policies and in the team itself. I wait till tomorros and will then re-install the app again and add it to a team.
I hope this will work

**Comment by Durk1969** [comment]
@gsv022 have you seen my answers? Your solution did not help

**Comment by gsv022** [comment]
@Durk1969 , Please respond to the below queries.

- Share a screenshot of Teams Data  from storage account. Below is the reference.
<img width="667" alt="image" src="https://user-images.githubusercontent.com/98143492/208045766-6939d45c-5444-4fe3-aeea-da52dd544cfe.png">

-  Please share the app service logs. Here is the screenshot for the reference.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/207514341-1ba0aee9-abfd-4578-bb85-e1809c71857d.png">

- Share the screenshot of function app. Below is the reference. Do the same for remaining 2 function apps(Prep-Function, Data Function)
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98143492/208047784-2a9aa840-735d-48a4-afc3-c016db6f6811.png">

**Comment by Durk1969** [comment]
@gsv022 where can i find 

- Teams Data from storage account
- app service logs
- the function app

**Comment by patrickrcdm** [comment]
I´m having exactly the same problem !
can´t locate teams when sending message from author.

**Comment by gsv022** [comment]
Hi @Durk1969 ,
Those can be found from the resource group in  Azure portal

**Comment by Durk1969** [comment]
@gsv022 here are the screenshots.

- Teams Data from storage account
![Teams Data](https://user-images.githubusercontent.com/103175505/208678984-53f97e04-dacf-4156-8dbf-4ad24d2668d9.png)

- app service log
![Logs_01](https://user-images.githubusercontent.com/103175505/208679156-8b22baf4-0b45-45b7-837d-883c6beb9d89.png)

- logs from data-function, function and prep-function
![Logs_03](https://user-images.githubusercontent.com/103175505/208679401-90f23fc7-1dfe-49c5-98a3-d4f5178b30d8.png)

![Logs_02](https://user-images.githubusercontent.com/103175505/208679423-c77c2251-4afa-4e85-bbef-fc6ca0d38d40.png)

![Logs_04](https://user-images.githubusercontent.com/103175505/208679437-b4a43e55-b755-4d1b-86d0-494d7a755c71.png)

**Comment by gsv022** [comment]
Hi @Durk1969 ,
As per the screenshot provided, prep-function got failed. 

- Could you please sync the prep-function. 
- Once after completing the above step, please remove the user app from the teams and re-add it. Then check the Team Data table again.

Keep us posted.

**Comment by Durk1969** [comment]
Hi @gsv022 i did what you explained. I now see e team when i make a message. The message then is for sometime queued but is does not appear as a post in the channel. 
![image](https://user-images.githubusercontent.com/103175505/209293906-fe9fde19-7b98-4c22-86f8-9b08553ae117.png)

I also made a message for everyone. That message is also in the queue for sometime and does only appear in the channel from the team where te commincator is added. Is this how it should work?  I would expect it also in the chat-feed by every user.
![image](https://user-images.githubusercontent.com/103175505/209294289-1da08d2a-8e35-4fd0-b448-01353d693554.png)

**Comment by gsv022** [comment]
@Durk1969 ,
Could you please share the email Id(MS Teams Id) so that we can get into the call and discuss the issue.

**Comment by Durk1969** [comment]
@gsv022 can i send you an PB with the ID and the password? And what time fits you?

**Comment by gsv022** [comment]
@Durk1969, Could you please send us your emaild Id(MS Teams Id) so that we can discuss more on the issue and its not permitted to schedule a meeting from your side.

Thank you.

**Comment by Durk1969** [comment]
@gsv022 you can invite at d.oberman@unive.nl

**Comment by gsv022** [comment]
@Durk1969 , Please share your availability for the next week, so that we can schedule the call accordingly.

**Comment by Durk1969** [comment]
Hi @gsv022 first i wish you a happy new year. My availability for this week not much, i am only available on wednesday.

**Comment by gsv022** [comment]
@Durk1969 , thank you and wish you the same. Please share your time slots on the mentioned day.

**Comment by Durk1969** [comment]
@gsv022 my time slots for tomorrow are 11.00 - 12.00 hour and 15.00 - 16.00 hour. Please note that we are in timezone GMT +01:00 (Amsterdam)

**Comment by gsv022** [comment]
@Durk1969 , we will be sending out a meeting in a while

**Comment by gsv022** [comment]
@Durk1969 , Could you please let us know the status. If no response is required from our end we are good to close out the issue.

**Comment by Durk1969** [comment]
@gsv022 i have been sick so that i did not have the time yet. I hope tomorrow or wednesday to upgrade the solution.

**Comment by Numotion-ITCommsGit** [comment]
I am also having this same issue. I used the Powershell deployment method. The 3 function apps all show successfully deployed.
After adding the Author app to a Team I'm not able to find any Teams to send a message to. I just get a message in the drop down stating "We couldn't find any matches"
If I attempt to enter in an email address of a DL the app appears to crash with error message on screen of "Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists."

**Comment by patrickrcdm** [comment]
Hi @gsv022 how are you ? .. i hope fine !
I´´m having the same problem.

Can we make a call via teams?
I have availability for next Monday or Tuesday, can you? .. invite patrick@brlic.com.br please.

Thank you.
