### ISSUE TITLE
"Can't find this app" on Microsoft Teams

### ISSUE THREAD

**Issue by robsonsb** [OfficeDev/microsoft-teams-apps-company-communicator#929]
Hi,
I installed throught powershell and mannualy (with no errors)
In both cenarios, i get the error ""Can't find this app" on Microsoft Teams (to author and user app).

Apparently everything is normal.
Any help is aprecciated.

Regards

Attached both apps.
[autor.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10185684/autor.zip)
[user.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10185686/user.zip)

**Comment by gsv022** [comment]
Hi @robsonsb ,
Thanks for raising the query. Please respond to the below queries.

- At which part error is getting displayed, please share supporting screenshots for better understanding of the issue.
- What is the version of the app?

**Comment by patrickrcdm** [comment]
> 

Hi @gsv022 . I'm working with @robsonsb , trying to deploy company communicator.
I installed it in another tenant and in another Azure subscription and it had the same behavior as in @robsonsb environment

When I add the custom .zip of the application in Microsoft Teams (client), (author and user) it uploads, but when I click to use it, it gives the message that "app was not found" (in portuguese message is: "não é possível encontrar este aplicativo"
Deploy the "main" version of Company Communicator and 5.2.0 of App.

![Print2 - Error when click to use the app](https://user-images.githubusercontent.com/25817274/206858749-a7a15403-0f56-409f-a684-8f32195cff35.jpg)
![Print2 - App is Uploaded](https://user-images.githubusercontent.com/25817274/206858751-d476af56-eeed-478e-bf88-d79c37b8a298.jpg)
![Print1](https://user-images.githubusercontent.com/25817274/206858752-c1f362f5-6eb2-4587-bf94-6eb3b6e1b57b.jpg)

**Comment by gsv022** [comment]
Hi @robsonsb ,

- Please uninstall the author app and user app completely from the tenant. Wait for sometime until they have completely disappeared from tenant. 
- Again re-install/ upload the  author and user app at the tenant level. 
- Please share the screenshot showing both the apps uploaded.

Please keep us posted.
