### ISSUE TITLE
Sending messages does nothing - installed version 5.2

### ISSUE THREAD

**Issue by jbienstman** [OfficeDev/microsoft-teams-apps-company-communicator#931]
Hi,

After struggling to deploy 5.2 using the PowerShell guide, this last time it looked like everything was deployed successfully - I can add the User app to a Team which then makes it selectable as a target. When I send a message to it says "queued..." for a while, but now a day later nothing has happened yet, no errors no success. 

My previous installation I was able to send to "all users" and to "members of a M365 email address" - but NOT to a "Teams General Channel" or to the "members of a Team" - this threw an error in the Azure Insights which I could not solve so I retried the installation. Now I don't see any error anywhere. 

Between installs I removed the Resource group on Azure & deleted the app registrations from AAD and the two apps from the Teams catalog before trying the deployment again.

I'm not sure how to proceed now...

**Comment by gsv022** [comment]
Hi @jbienstman ,
Thanks for logging the query. I am just trying to understand while sending a message through 1st sending option-General channel, it got stuck in **queued** state right and count of success, failure - **0** . If this is the scenario, please 

- Verify app registrations are done correctly or not and send us the screenshots of overview section of every app registration. Here is the below one for reference.
<img width="941" alt="image" src="https://user-images.githubusercontent.com/98143492/207279719-a01a277b-4eda-47a6-b4be-19299b90812b.png">

**Comment by jbienstman** [comment]
Hi,

I ran the Check-AppRegistrations.ps1 script from the support folder to verify the 3 app registrations:
***@***.***
Kind Regards,

Jim

**Comment by gsv022** [comment]
Hi @jbienstman,

- Please share deployment status of all function apps and app service. Here is the reference for app service status. Please do the same for 3 funtion apps(Data Function, Function, Prep-Function)
<img width="954" alt="image" src="https://user-images.githubusercontent.com/98143492/207515100-3275aedf-83ee-4895-a0eb-0093e3206bd1.png">
- Please share the app service logs. Here is the screenshot for the reference.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/207514341-1ba0aee9-abfd-4578-bb85-e1809c71857d.png">

**Comment by jbienstman** [comment]
Hi,

Thank you for your help already, here is the requested information:
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
I did see some errors actually:
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***
***@***.***


Cheers,

Jim

**Comment by jbienstman** [comment]
I re-deployed in Azure, ran several scripts from the Support folder and suddenly it started working... can't pin point what exactly fixed it..

**Comment by jbienstman** [comment]
I re-deployed in Azure, ran several scripts from the Support folder and suddenly it started working... can't pin point what exactly fixed it..
