### ISSUE TITLE
Company Communicator Stucked in Sign in

### ISSUE THREAD

**Issue by rajnishdev7** [OfficeDev/microsoft-teams-apps-company-communicator#933]
Hi Team,

I have followed this https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide
and created all apps accordingly based on this.

However my author teams app stucked in sign in page.

I have tried in three separate tenants and all three having same issue
There is definitely something wrong with this guidebook.

Please guide
![Screenshot 2022-12-13 151558](https://user-images.githubusercontent.com/30117139/207371742-c8810a04-2325-4ef6-b83b-ee9c855cbd8b.png)

**Comment by gsv022** [comment]
Hi @rajnishdev7 ,
Thanks for logging the query. These might be the places for possibilities of the error.
1. Could you please verify the graph app [set up Authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) step was correctly configured or not and check mainly on API permissions.
2. Please verify all the app client secret is correctly copied while creating ARM template or not. Attaching the [link](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/911) where you can compare and check on secrets.

Keep us posted. Thank you
