### ISSUE TITLE
Two Storage Accounts after upgrade

### ISSUE THREAD

**Issue by angtany** [OfficeDev/microsoft-teams-apps-company-communicator#935]
After upgrading from v4.1.5 to v5.2 following below migration guide, there are two instances of storage account in the resource group. One is the old one. Another gets created with this upgrade. 

Is this a known behavior? If no, how to avoid this ?

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide#upgrading-from-v4-to-v5

**Comment by v-royavinash** [comment]
Hi @angtany, Thanks for reaching out, we will check and will keep you posted.

**Comment by gsv022** [comment]
Hi @angtany ,
We have tested it out from our end, it won't create another storage account on the upgrade. Could you please share the deployment logs of two deployments(one for v4.1.5 and one for upgrade part). Here is the screenshot for the reference.
<img width="721" alt="image" src="https://user-images.githubusercontent.com/98143492/208050781-a9ded24e-8a6b-44f2-ae19-1fb086f24927.png">

**Comment by angtany** [comment]
Thanks for replying. I don't have access to the environment now. I'll share logs as soon as I get the same situation. I have experienced it twice so far.
