### ISSUE TITLE
Problem with expiring SAS Token image URLs

### ISSUE THREAD

**Issue by Lestriffe** [OfficeDev/microsoft-teams-apps-company-communicator#936]
Hi,
The images sent by Company Communicator are expiring after 7 days, how can I change the expiry time of the URL of the images?
Is this configurable in application code?

Communicates sent after 7 days are without the images and only have the text.

![ERRO_URL](https://user-images.githubusercontent.com/120507308/207418884-e92b4328-5751-4a2b-bf3b-9fae4b7feaeb.png)

**Comment by v-royavinash** [comment]
Hi @Lestriffe , The official company communicator does not have any dependency on SAS token. Could you please check which repo did you used during deployment?

**Comment by Lestriffe** [comment]
Hi, @v-royavinash 

I did the deployment following the documentation for version 5: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide

My problem is exactly the same questioned also in this link: https://github.com/cristianoag/microsoft-teams-apps-company-communicator/issues/33

I'll set the mentioned ImageUploadBlobStorage settings to FALSE to check if it will work.

**Comment by gsv022** [comment]
Hi @Lestriffe ,

The official repository of company communicator doesn't use any SAS tokens for sending the images which are uploaded manually. The approach is different from the one which is present in Cristiano's repository.

Thank you.
