### ISSUE TITLE
Need sync operation to update for Company Communicator v5.3?

### ISSUE THREAD

**Issue by runceel** [OfficeDev/microsoft-teams-apps-company-communicator#940]
I have tried upgrade process to v5.3 from v5.2 follow the guide.
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide

After finished "Upgrading from v5.x to latest version" section, my company communicator was broken. All functions had errors like below(sorry my primary language is Japanese, then a few UI labels are Japanese):

![func-error-message](https://user-images.githubusercontent.com/79868/207781952-016a365c-2454-409c-bb29-1065a5b5d9f0.png)

I guess you need sync operation at deploy center of all app service and function apps to deploy latest source code.

**Comment by runceel** [comment]
I didn't notice this. Does this "sync" mean sync at Deploy center?
![image](https://user-images.githubusercontent.com/79868/207798160-80281515-b5fa-4e5e-9c4d-a9e20e6d6114.png)

**Comment by gsv022** [comment]
Hi @runceel ,
Thanks for raising the query. Hoping that PowerShell procedure needed for updating dotnet version, please perform the below procedure.
- Go to Prep-Function in the resource group
- Click on configuration
- Go to Function runtime settings
- select ~4 from the drop down of Runtime version 
- Do the same for Data Function, Function as well.
- Then click on the App service -> Click on Configuration -> Click on General Settings
- Check and confirm the .NET version to be .NET 6 (LTS)

Hope this helps. Keep us posted.

**Comment by runceel** [comment]
@gsv022 Thank you for your response.
I had followed that procedure. My question is, do I need to click the sync button in the deploy center to complete the migration?
When I did the migration I needed to click the sync button but I didn't notice this step just by looking at the migration guide.

**Comment by gsv022** [comment]
@runceel, sync is needed to get the latest code. If still facing the issue, please share your outlook id(email id/ MS Teams Id) to discuss more on this issue. If needed, will get into the call as well.

**Comment by runceel** [comment]
@gsv022 I fixed the issue. Thank you.
