### ISSUE TITLE
Users cannot receive messages when they previously deleted chat from the Company Communicator!

### ISSUE THREAD

**Issue by jbienstman** [OfficeDev/microsoft-teams-apps-company-communicator#941]
After a long struggle to get the app working, to demonstrate the Company Communicator App to colleagues, I decided to clean up the demo users chat  history and "Deleted" the chats sent previously by the Company Communicator.
	• Now it turns out, this is preventing any future message from arriving!
	• I tried it with 3 different users, same result - working as long as you never deleted the chat from Company Communicator - no more messages once you delete the chat.

Repro Steps:
Open 3 Browser profiles, 1 Author - 2 users, logon to teams.office.com
	
	• Author: Send message 1 to Everyone from the CC Author App
	• User 1 & User 2 - Verify chat was received
	• User 2: Delete the chat from Company Communicator
	• Author: Send message 2 to everyone from the CC Author App
	• User 1 & User 2 - Verify chat was received
	• Result:
		○ User 1 - Received
		○ User 2 - Nothing
		
It looks like once you "Delete Chat" from Company Communicator, new messages don’t add the entry back.
I tried uninstalling/adding the "Company Communicator User" app to the user again, didn’t help.

FYI - Just hiding the chat from "Company Communicator" doesn’t break it, then the message arrives, re-appearing the chat history of the CC.

**Comment by gsv022** [comment]
Hi @jbienstman ,
Thanks for raising the query. Please give us sometime to check on this event. We will get back to you with proper response soon.

**Comment by gsv022** [comment]
Hi @jbienstman ,
Thanks for bringing the issue to our notice. We will be considering this as a bug and do the necessary.

**Comment by gsv022** [comment]
Hi @jbienstman ,
We are closing this issue as it has been added to backlog and will be planned in the future releases of CC based on priority.
