### ISSUE TITLE
Proactive messages with user input

### ISSUE THREAD

**Issue by aksridhar** [OfficeDev/microsoft-teams-apps-company-communicator#942]
I am trying to extend the proactive message so that user can get a quick survey to acknowledge. This will be just couple of buttons on the adaptivecard and user has to select a radio button and click on button. Since the proactive message is being sent outside of bot the event handlers of bot dont get called when I click on button in Teams client. Rather I get a "Unable to reach app. Please try again". Do you have any code reference that provides a way to send proactive message and wait for user input?

**Comment by gsv022** [comment]
Hi @aksridhar ,
Thanks for raising the query. We will check with the internal team and get back to you with proper response soon.

**Comment by aksridhar** [comment]
Hi @gsv022 I am closing this issue as I was able to fix that. I am using ngrok for local development and looks like recent code was not running with ngrok and my Teams app was not able to respond. Once I republished the Teams App it started working.
