### ISSUE TITLE
Client secret not updating

### ISSUE THREAD

**Issue by Scheiderichv094** [OfficeDev/microsoft-teams-apps-company-communicator#943]
Good morning,

Our secret for Company Communicator v4 was due to expire 1/6/2023. Our M365 team updated the secret in AppSettings, KeyVault, Azure Bot, AuthorAppPassword, and Graph App Password. Now we are not able to use Company Communicator in MS Teams. Errors we get in Teams are, "Oooops! An unexpected error seems to have occurred." and "Permissions needed. Ask your IT admin to enable this option for you." After looking in AAD, they saw logs on users that say, "Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID. for a secret add to app '(identifier)' 

Are you able to chat via email? We use this org wide to broadcast updates for Major Incidents.
Scheiderichv@outlook.com

**Comment by gsv022** [comment]
Hi @Scheiderichv094 ,
Thanks for raising the query. Could you please respond to the below queries.

- What is the version of the app?
- _Invalid client secret provided_, this comes when client Secret Id has been copied and updated it in respective places. This is causing the issue. Instead of copying the secret Id, **secret value** should be copied. Below is the screenshot for the reference.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98143492/209909182-2305ad53-3365-42ef-8085-38488f4ec08e.png">

**Comment by Scheiderichv094** [comment]
Thank you replying back! Adding my work email and the M365 engineer that has been helping me.

________________________________

**Comment by Scheiderichv094** [comment]
Good morning,

We believe we have version 4 but it has been half a year since we installed it. Is there where a way to check to see what version we have? Also, our M365 engineers made sure to copy the value and not the ID and double checked. Are we able to schedule a screenshare and walk us through it?

Best Regards,

Victor Scheiderich
IT Operations Engineer 2 (HS)
***@***.******@***.***>
[OSUWexMedCtr]

**Comment by Scheiderichv094** [comment]
Any update?

**Comment by Scheiderichv094** [comment]
Any update on being able to schedule a meeting?

**Comment by gsv022** [comment]
Hi @Scheiderichv094 ,
Please share your availability for today(02/01/23) or tomorrow(03/01/23) so that we can schedule a call to discuss the issue.

Thank you

**Comment by Scheiderichv094** [comment]
I am on vacation until January 9th 2023. Are you able to schedule a time Tuesday, January 3rd with ***@***.*** He is the one that helped me deploy it and renewed the secret.

Victor Scheiderich
614-743-9631
________________________________

**Comment by gsv022** [comment]
@Scheiderichv094 , This id is masked could you please share the actual id
<img width="201" alt="image" src="https://user-images.githubusercontent.com/98143492/210208580-4c7f2790-4f13-4ac9-bce4-a19e07b1b54e.png">

**Comment by Scheiderichv094** [comment]
Ricardo.thomas@osumc.edu

**Comment by Scheiderichv094** [comment]
Are you able to see it now?

**Comment by gsv022** [comment]
Thanks for sending it. 3pm-4pm IST tomorrow, does this time work for you?

**Comment by Scheiderichv094** [comment]
We are eastern time so that would be 4:00-5:00am. Anything later in the day?

**Comment by gsv022** [comment]
We have sent you a meeting invite. Please let us know if that the scheduled time works or not

**Comment by Scheiderichv094** [comment]
Ricardo is available from 8am to 5pm today

**Comment by gsv022** [comment]
Thanks for confirming. We will be sending out the meeting invite in a while

**Comment by Scheiderichv094** [comment]
> Thanks for confirming. We will be sending out the meeting invite in a while

Thank you! Let me know if you need further details.

**Comment by gsv022** [comment]
We have sent a meeting invite already. Waiting for the user to attend

**Comment by Scheiderichv094** [comment]
> We have sent a meeting invite already. Waiting for the user to attend

He said he will be free after 8:30am

**Comment by gsv022** [comment]
We started a conversation internally on MS Teams platform with Ricardo.

**Comment by Scheiderichv094** [comment]
> We started a conversation internally on MS Teams platform with Ricardo. 

Great!

**Comment by Scheiderichv094** [comment]
> > We started a conversation internally on MS Teams platform with Ricardo. 
> 
> Great! 

He said he started the Teams meeting and is waiting for you

**Comment by Scheiderichv094** [comment]
> > > We started a conversation internally on MS Teams platform with Ricardo. 
> > 
> > Great! 
> 
> He said he started the Teams meeting and is waiting for you 

You have ricardo.thomas@osumc.edu correct? What is your email so he can invite you?

**Comment by Scheiderichv094** [comment]
> > > > We started a conversation internally on MS Teams platform with Ricardo. 
> > > 
> > > Great! 
> > 
> > He said he started the Teams meeting and is waiting for you 
> 
> You have ricardo.thomas@osumc.edu correct? What is your email so he can invite you?

Are you guys able to meet today? Ricardo said you never joined

**Comment by v-royavinash** [comment]
We are closing out the issue as messages were sent successfully to the ~600 intended users. Please reach out to us if you face any issue in future

**Comment by albert-widjaja** [comment]
Can we use the automated Client secret rotation with this https://learn.microsoft.com/en-us/azure/key-vault/secrets/tutorial-rotation ?

or do we still have to manually update the client secret at the company communicator key vault before it expires?
