### ISSUE TITLE
How to debug the Company Communicator locally?

### ISSUE THREAD

**Issue by yazeedhannan** [OfficeDev/microsoft-teams-apps-company-communicator#945]
Is there a way to locally debug the Company Communicator source code?

Working enviornment is Visual Studio 2022.

Thank You.

**Comment by gsv022** [comment]
Hi @yazeedhannan ,
Thanks for raising the query. Please follow the procedure mentioned in this issue [565](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/565).

Hope this helps.
