### ISSUE TITLE
Issue when granting permissiosn

### ISSUE THREAD

**Issue by adamhastie** [OfficeDev/microsoft-teams-apps-company-communicator#946]
![CCIssue](https://user-images.githubusercontent.com/121858724/210331826-11584751-0eda-40a9-938b-4d10d58c6000.png)

When attempting to grant permission to the CC authors app in the teams admin center, we are getting the above error. Account that is granting the permissions is a global admin. Have contacted MS Support but have so far not been of help.

**Comment by gsv022** [comment]
Hi @adamhastie ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by v-royavinash** [comment]
@adamhastie, Request you to please check the grant permission issue with the Microsoft Customer Support (shown in the screenshot) as this seems to be an tenant specific issue not with the company communicator app.

Also can you please validate if same error is shown while giving permission with other apps?
