### ISSUE TITLE
Edit Azure -App Service- application setting REACT_APP_HEADERIMAGE and REACT_APP_HEADERTEXT not updating

### ISSUE THREAD

**Issue by md-mario** [OfficeDev/microsoft-teams-apps-company-communicator#947]
I am using Company Communicator v5.3
I have change the name and the Icon Url in Azure  - App Service - application setting. I restarted  the App Service after that.

The new ImageLink and the Header Text are unchanged.

```
<div class="cc-header">
    <div class="ui-flex al am an">
        <div class="ui-flex al ao an"><img
                src="https://raw.githubusercontent.com/OfficeDev/microsoft-teams-company-communicator-app/main/Source/CompanyCommunicator/ClientApp/src/assets/Images/mslogo.png"
                alt="Ms Logo" class="ms-logo" title="News"><span class="header-text"
                title="News">News</span></div>
        <div class="ui-flex al ao ap"><a href="https://aka.ms/M365CCIssues" target="_blank" rel="noreferrer"
                class="ui-flex__item"><img src="/static/media/HelpIcon.2940cb9a.svg" alt="Help" class="support-icon"
                    aria-labelledby="tooltip-content-1"></a><a href="https://aka.ms/M365CCFeedback" target="_blank"
                rel="noreferrer" class="ui-flex__item"><img src="/static/media/FeedbackIcon.094038d0.svg" alt="Feedback"
                    class="feedback-icon" aria-labelledby="tooltip-content-2"></a></div>
    </div>
</div>
```

**Comment by gsv022** [comment]
Hi @md-mario ,
Thanks for raising the query. This might be due to cache issue. Could you please try opening the teams in browser once and check whether changes are reflecting or not.

**Comment by md-mario** [comment]
Hi,
the TeamsApp, open in a browser, return the same problem.
I have investigated withe the Edge Developer tools  the Site .azurewebsites.net/messages.
The customHeaderImagePath and the customHeaderText are unchanged.

tabContainer.tsx looks like good

`const customHeaderImagePath = process.env.REACT_APP_HEADERIMAGE;
         const customHeaderText = process.env.REACT_APP_HEADERTEXT == null ? 
                                    this.localize("CompanyCommunicator") 
                                        : this.localize(process.env.REACT_APP_HEADERTEXT);
       

        return (
            <>
                <div className='cc-header'>
                    <Flex gap="gap.small" space='between'>
                        <Flex gap="gap.small" vAlign="center">
                            <img
                                src={ customHeaderImagePath == null ? 
                                            require("../../assets/Images/mslogo.png").default 
                                            : customHeaderImagePath}
                                alt="Ms Logo"
                                className="ms-logo"
                                title={customHeaderText}
                            />
                            <span className="header-text" title={customHeaderText}>{customHeaderText}</span>
                        </Flex>`

Are there any further steps required after changing the app settings?

**Comment by gsv022** [comment]
Hi @md-mario ,
Once the header text and header logo were changed in the App service-configuration, we need to save it then go to deployment center-->sync it. Wait for some time and refresh the teams page, changes will reflect. If not reflecting, please open the teams in browser and check it.

**Comment by gsv022** [comment]
@md-mario , could you please let us know the status if no response is required from our end we are good to close out the issue
