### ISSUE TITLE
Message not sending even after 24 hours

### ISSUE THREAD

**Issue by angtany** [OfficeDev/microsoft-teams-apps-company-communicator#948]
This is for our customer - Infosys. Messages are not being sent for more than 24 hours.

Triggered a message in BOT on Jan3, 3:56 PM to a group containing ~10K members and the message status still shows queued even after 5 hours, here is the snip.

 
![image](https://user-images.githubusercontent.com/39870291/210709459-8c61464d-83a5-4ac7-87c1-bcafde894e41.png)

There was another message triggered by some other author to a group of 9 members and that also completed after 24 hours with 0 success,

 
![image](https://user-images.githubusercontent.com/39870291/210709475-d7a9e069-7c8f-48ae-94ad-0370100e3891.png)

On checking logs for app service: Found "System.Net.Http.HttpRequest.Exception while attempting to establish connection".

[EventLogPrev.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10349618/EventLogPrev.txt)
[EventLog.txt](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/10349619/EventLog.txt)

Attached logs. Require your assistance here to resolve this issue.

**Comment by gsv022** [comment]
Hi @angtany ,
Thanks for raising the query. Could you please respond to the below queries.

- What is the version of the app?
- What is the gitrepo URL and branch that has been used while creating the ARM template. Below is the screenshot for the reference.
--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png">

--Click on  Microsoft template

<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png">

 -- Then select **inputs** from left section where you can find the GitHub repo URL and Branch that are used. Please share them.

**Comment by angtany** [comment]
The app version is v5.2. It is customized on the top of base version v5.2. Customization includes adding multiple buttons, click rate on buttons, reactions-telemetry etc.

**Comment by gsv022** [comment]
Hi @angtany ,
Please note, that we are only able to troubleshoot versions that are from our main repo (non-customized). Even though they may be using out of the box features, the fact that they are indeed running a customized version means there are other variables present and the team is unable to dive into all the potential differences between our version vs custom changes. We will be unable to further troubleshoot unless it is the main repo / non customized version.

Please let us know if you have any queries related to standard versions of company communicator

Hope we conveyed.
