### ISSUE TITLE
Unable to upgrade v5.0 to the latest version

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#950]
I am trying to follow the steps given in the migration guide but I am unable to do so. I have given the error message which I get. Please let me know what needs to be done in order to eliminate this error.
![image](https://user-images.githubusercontent.com/15922771/211286295-1a209de6-2799-4488-b893-96e523792745.png)

**Comment by PrithuMahisha** [comment]
Additional info to the above mentioned:
We have deployed V5.0 in our tenant and we are trying to upgrade to the latest version V5.3.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query. Could you please mention the Azure CLI version.

**Comment by PrithuMahisha** [comment]
@gsv022 Could you please let me know how we can check that?

**Comment by PrithuMahisha** [comment]
@gsv022 I tried to run this command **az --version** - I get the below message 

"The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

I ran this command is the same path. Please let me know if this needs to be run in a different location as mentioned in the above screenshot.

**Comment by gsv022** [comment]
@PrithuMahisha , Below is the screenshot for the reference. Open the command prompt and execute **az --version**.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/98143492/211477093-9e669365-a832-42cf-a70d-ba2fe10d1c63.png">

**Comment by PrithuMahisha** [comment]
@gsv022 I don't have this. I am getting this message.
'az' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gsv022** [comment]
@PrithuMahisha , could you please download the [Azure CLI version](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.30.0.msi) -2.30.0 and do the process again

**Comment by gsv022** [comment]
@PrithuMahisha , could you please let us know the status

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
