### ISSUE TITLE
Azure Pipelines, invalid/unable to run - Microsoft Security Code Analysis (MSCA) extension is retired

### ISSUE THREAD

**Issue by captainhook** [OfficeDev/microsoft-teams-apps-company-communicator#951]
Hi team,

> Effective December 31, 2022, the Microsoft Security Code Analysis (MSCA) extension is retired. MSCA is replaced by the [Microsoft Security DevOps Azure DevOps extension](https://learn.microsoft.com/en-us/azure/defender-for-cloud/azure-devops-extension). Follow the instructions in [Configure](https://learn.microsoft.com/en-us/azure/defender-for-cloud/azure-devops-extension) to install and configure the extension.

source: https://learn.microsoft.com/en-us/azure/security/develop/security-code-analysis-overview

Since the MCSA extension is retired, it can no longer be installed from the marketplace. The replacement for MCSA is Microsoft Security DevOps which has a slightly different configuration.

Please could you add a task to update this to your product backlog?

Thanks

**Comment by gsv022** [comment]
Hi @captainhook ,
Thanks for raising the query. We will get back to you with proper response soon.

**Comment by v-royavinash** [comment]
@captainhook , thanks for your feedback, we have added the feature in our backlog and will prioritize it based on review and bandwidth.

**Comment by gsv022** [comment]
@captainhook ,we're closing this issue since this feature is already added to our backlog and will be considered in future releases of CC based on the priority.
