### ISSUE TITLE
unexpected error in Author team app

### ISSUE THREAD

**Issue by AurelienVieille** [OfficeDev/microsoft-teams-apps-company-communicator#952]
hi :)
i followed the guid line but when i try to access the author app, i can see few seconds the app then i receive an unexpected error msg.
![AuthorTeamsApp](https://user-images.githubusercontent.com/122565888/212165031-faee59d3-e5e8-44a1-a8cb-4fa4dbc6c31c.png)
Aurélien

**Comment by gsv022** [comment]
Hi @AurelienVieille ,
Thanks for raising the query. There might be many reasons but mainly **cross** **check the configuration end-end**. Please respond to the queries below

- What is the version of the app?
- Please share the deployment logs. To reach it, 
--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png">

--Click on  Microsoft template

<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png">
-- Download the logs and share it

**Comment by AurelienVieille** [comment]
I did it multiple time :

***@***.***

The errors during the first deployment were related to
***@***.***
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass347_1.<<UpdateSiteSourceControl>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl).",
        "details": [
            {
                "message": "Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass347_1.<<UpdateSiteSourceControl>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl)."
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}

Then I started again, the deployment went ok except for :
***@***.***
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"}]}

I remove the github config at the Azure App service, tried again, then the deployment succeed.

Which logs do you want ?

Aurélien

De : Sai Venkat ***@***.***>
Envoyé : vendredi 13 janvier 2023 08:55
À : OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc : AURELIEN VIEILLE ***@***.***>; Mention ***@***.***>
Objet : [EXTERNAL]Re: [OfficeDev/microsoft-teams-apps-company-communicator] unexpected error in Author team app (Issue #952)


EXTERNAL: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi @AurelienVieille<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAurelienVieille&data=05%7C01%7Caurelien.vieille%40stellantis.com%7C4c80cdead97c45b53dfd08daf53b89cc%7Cd852d5cd724c41288812ffa5db3f8507%7C0%7C0%7C638091933310714801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zfD%2BUU3%2F9h42FotRHKUpweI9Hh1J5i7jKWqO3WRyC3k%3D&reserved=0> ,
Thanks for raising the query. There might be many reasons but mainly cross check the configuration end-end. Please respond to the queries below

  *   What is the version of the app?
  *   Please share the deployment logs. To reach it,
--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F98143492%2F205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png&data=05%7C01%7Caurelien.vieille%40stellantis.com%7C4c80cdead97c45b53dfd08daf53b89cc%7Cd852d5cd724c41288812ffa5db3f8507%7C0%7C0%7C638091933310714801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GxBQ3ynCYFrKnevYSIJjqh%2B02QqTVYSX1fPdn7RFt5c%3D&reserved=0>

--Click on Microsoft template

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F98143492%2F205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png&data=05%7C01%7Caurelien.vieille%40stellantis.com%7C4c80cdead97c45b53dfd08daf53b89cc%7Cd852d5cd724c41288812ffa5db3f8507%7C0%7C0%7C638091933310714801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T0D5gHXUfEhY5crPGevlkDTV5FaPQAuz8wT48wAfeuk%3D&reserved=0>
-- Download the logs and share it

-

**Comment by AurelienVieille** [comment]
In addition, here is what is see in the Log stream of the App service :

<html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 500.0 - Internal Server Error</title><style type="text/css"></style>
</head><body><div id="content"><div class="content-container"><h3>HTTP Error 500.0 - Internal Server Error</h3><h4>The page cannot be displayed because an internal server error has occurred.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul>               <li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li>         <li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li>                <li>IIS was not able to process configuration for the Web site or application.</li>             <li>The authenticated user does not have permission to use this DLL.</li>           <li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul>              <li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> <li>Check the event logs to see if any additional information was logged.</li>    <li>Verify the permissions for the DLL.</li>         <li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li>            <li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>
<div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModuleV2</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr>
</table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://TeamsACC:80/api/draftnotifications</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\home\site\wwwroot\api\draftnotifications</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
</table><div class="clear"></div></div></fieldset></div>
<div class="content-container"><fieldset><h4>More Information:</h4>This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x00000000,14393">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p>
</fieldset></div></div></body></html>

Aurélien

De : AURELIEN VIEILLE
Envoyé : vendredi 13 janvier 2023 09:58
À : OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>; OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc : Mention ***@***.***>
Objet : RE: [EXTERNAL]Re: [OfficeDev/microsoft-teams-apps-company-communicator] unexpected error in Author team app (Issue #952)

I did it multiple time :

***@***.***

The errors during the first deployment were related to
***@***.***
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass347_1.<<UpdateSiteSourceControl>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl).",
        "details": [
            {
                "message": "Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass347_1.<<UpdateSiteSourceControl>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl)."
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}

Then I started again, the deployment went ok except for :
***@***.***
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message":"There was a conflict. Conflict with existing ScmType: ExternalGit"}]}

I remove the github config at the Azure App service, tried again, then the deployment succeed.

Which logs do you want ?

Aurélien

De : Sai Venkat ***@***.***>
Envoyé : vendredi 13 janvier 2023 08:55
À : OfficeDev/microsoft-teams-apps-company-communicator ***@***.***>
Cc : AURELIEN VIEILLE ***@***.***>; Mention ***@***.***>
Objet : [EXTERNAL]Re: [OfficeDev/microsoft-teams-apps-company-communicator] unexpected error in Author team app (Issue #952)


EXTERNAL: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi @AurelienVieille<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAurelienVieille&data=05%7C01%7Caurelien.vieille%40stellantis.com%7C4c80cdead97c45b53dfd08daf53b89cc%7Cd852d5cd724c41288812ffa5db3f8507%7C0%7C0%7C638091933310714801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zfD%2BUU3%2F9h42FotRHKUpweI9Hh1J5i7jKWqO3WRyC3k%3D&reserved=0> ,
Thanks for raising the query. There might be many reasons but mainly cross check the configuration end-end. Please respond to the queries below

  *   What is the version of the app?
  *   Please share the deployment logs. To reach it,
--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference

[Image supprimée par l'expéditeur. image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F98143492%2F205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png&data=05%7C01%7Caurelien.vieille%40stellantis.com%7C4c80cdead97c45b53dfd08daf53b89cc%7Cd852d5cd724c41288812ffa5db3f8507%7C0%7C0%7C638091933310714801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GxBQ3ynCYFrKnevYSIJjqh%2B02QqTVYSX1fPdn7RFt5c%3D&reserved=0>

--Click on Microsoft template

[Image supprimée par l'expéditeur. image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F98143492%2F205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png&data=05%7C01%7Caurelien.vieille%40stellantis.com%7C4c80cdead97c45b53dfd08daf53b89cc%7Cd852d5cd724c41288812ffa5db3f8507%7C0%7C0%7C638091933310714801%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T0D5gHXUfEhY5crPGevlkDTV5FaPQAuz8wT48wAfeuk%3D&reserved=0>
-- Download the logs and share it

-

**Comment by AurelienVieille** [comment]
hi,
i checked the Client ID and succeed to fix the issue. i mix client ID and Object id. i'm facin another issue but this one is ok.
thks for your help
Aurélien

**Comment by gsv022** [comment]
@AurelienVieille , Thanks for the update. If you are facing any issue related to Company Communicator please log a new issue.
