### ISSUE TITLE
Problems while deploying company communicator app to Azure

### ISSUE THREAD

**Issue by NikhilDhumal734** [OfficeDev/microsoft-teams-apps-company-communicator#953]
Hi Team,

As discussed in our previous call, we have newly set-up all three apps(Author, User and Graph app).
Now while deploying an app to Azure we are getting following error.  please advise.
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass347_1.<<UpdateSiteSourceControl>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl).",
        "details": [
            {
                "message": "Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (502) Bad Gateway.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.Utilities.WebRequestHelper.<GetResponseAsyncWithTimeout>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.TrackerContext.<GetResponseAsync>d__41.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.SiteRepositoryProvider.<SetSettingsAsync>d__31.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.ExternalSiteRepositoryProvider.<UpdateSiteSourceControl>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass347_1.<<UpdateSiteSourceControl>b__1>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1 func)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.UpdateSiteSourceControl(String subscriptionName, String webspaceName, String name, SiteSourceControl siteSourceControl)."
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}

![image](https://user-images.githubusercontent.com/119613793/212275176-0090691c-ffa8-40cb-b452-1b132e5fac13.png)

**Comment by NikhilDhumal734** [comment]
There are 3 functions failed which points to sourcecontrols

![image](https://user-images.githubusercontent.com/119613793/212337179-de9531b7-38d7-4f6e-81f5-21db95fbd7a6.png)

**Comment by gsv022** [comment]
Hi @NikhilDhumal734 ,
It confirms that all the three function apps got failed. Please perform the procedure below.

- Go to portal.azure.com. Navigate to resource group where all CC resources are deployed.
- Click on data function. 
- Go to deployment center. 
- Click on **Sync**
- Please do the same for other two function apps.

**Comment by NikhilDhumal734** [comment]
Hi @gsv022 
To update, we have provided all mentioned steps to Azure admin team, we keep you updated about progress.

**Comment by gsv022** [comment]
@NikhilDhumal734 , 
This is a part of follow up. Please let us know if you need any inputs from our end.

**Comment by sbrile** [comment]
@gsv022 - I encountered same error.   Sync button on the data function is greyed out.

![31-01-2023-04-32-31](https://user-images.githubusercontent.com/5767861/215888077-f05f60b8-9b3f-4dc3-b4e6-e2b185ea66dc.png)

![31-01-2023-04-34-34](https://user-images.githubusercontent.com/5767861/215888486-81f99fb0-f1ee-441c-a479-5f6164c8a610.png)

**Comment by sbrile** [comment]
Is the FTPS login failing?

![31-01-2023-04-44-58](https://user-images.githubusercontent.com/5767861/215890505-fe5984d8-aed5-4ccf-9ac9-e18c5e76513f.png)

**Comment by sbrile** [comment]
Tried running the deploy.ps1 again.   Now there is only one resource failing csteamscom/web.  The error is "There was a conflict. Conflict with existing ScmType: ExternalGit"  Attempting a manual sync and another running deploy.ps1 again.

**Comment by sbrile** [comment]
After re-running the deployment about 10 times, if finally worked

**Comment by gsv022** [comment]
@NikhilDhumal734 , we are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Comment by frankchen76** [comment]
@gsv022, I also got same error message. I am trying to follow the recommended approach to "Sync" the deployment template. I also had a side question. if deployment was failed, how can I get those values "authorBotId", "userBotId" and "appDomain" generated from "Output" tab which was mentioned in step 13?

**Comment by harithzulfaizal** [comment]
> After re-running the deployment about 10 times, if finally worked. I also had to manually setup some steps from the Authentication portion of the manual instructions. The powershell script did not set the scope and client applications properly.

just 10? we're on 7 now and no idea how to fix.. hahah lollolololololo pray for us 🤞🙏
