### ISSUE TITLE
Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists.

### ISSUE THREAD

**Issue by Sandeep-FED** [OfficeDev/microsoft-teams-apps-company-communicator#955]
Hi Team,

We have deployed Company Communicator, but when trying to send messages to the channels or users, getting the following error.

"Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or you can contact your administrator if the problem persists. "

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/36669540/213427987-8016f92e-8bef-4013-b9fa-1ab2cd664189.png)

**Comment by gsv022** [comment]
Hi @Sandeep-FED ,
Thanks for raising the query. There might be multiple reasons for this issue.
- Could you please verify the configuration end-end again.  
- Share the screenshot of  function app . Below is the reference. Do the same for remaining 2 function apps(Prep-Function, Data Function) and App Service. To reach here, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select Function from list of resources-->Go to Deployment Center-->Click on logs
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98143492/208047784-2a9aa840-735d-48a4-afc3-c016db6f6811.png">

**Comment by Sandeep-FED** [comment]
Hi @gsv022,

- Configuration seems fine.
- Please find the below shared screenshots:
![photon-ccv2-data-function - Microsoft Azure 2023-01-23 16-55-16](https://user-images.githubusercontent.com/36669540/214211137-b3d29ab6-fb78-46b6-aa78-b2e0f567df8d.jpg)
![prep](https://user-images.githubusercontent.com/36669540/214211247-eef80596-6fc1-477c-a468-c03ba266381e.png)
![appservice](https://user-images.githubusercontent.com/36669540/214211257-8a73d5c1-b4be-4f83-8a7e-0dba7881c8a4.png)
![send](https://user-images.githubusercontent.com/36669540/214211312-1e455c2d-739b-4686-ae1b-a213754acd3c.png)

**Comment by gsv022** [comment]
Hi @Sandeep-FED ,
Please check the below points:-

- Could you please double check during the app registration process  whether you’ve selected **multi-tenant** for author and user apps. And **my organization** for graph app.
- Check the API permissions whether all permissions are given and granted as per the deployment guide. 
- And confirm whether this is a fresh deployment or migration.
- Please check for client secrets whether they are correctly copied and pasted or not.

**Comment by gsv022** [comment]
@Sandeep-FED, the issue got resolved over the call. Please let us know if you have any queries otherwise we are good to close out the issue.

**Comment by Sandeep-FED** [comment]
@gsv022, let us wait for response from the customer end. Then we can close out this issue.

**Comment by fajr365** [comment]
I have the same issue - can someone share the corrective action?

**Comment by KenDuboisIPC** [comment]
I have the same issue also, hoping someone will post how this was resolved. Thanks!

**Comment by fonsecase** [comment]
I have the same issue also, hoping someone will post how this was resolved. Thanks!

**Comment by fatsbear** [comment]
what was the resolution for this? Experiencing the same issue currenty. 

![image](https://github.com/user-attachments/assets/f7a4ae27-7673-4833-bbf9-efb329c3c414)
