### ISSUE TITLE
How to restart receive messages from CC (Related to the #941)

### ISSUE THREAD

**Issue by MK202204** [OfficeDev/microsoft-teams-apps-company-communicator#956]
Hi,

Related to the #954 and #941、I contacted Microsoft Teams support center about how to restore a deleted chat.
They replied that they could not restore the deleted chat, but that they could start the chat by starting a New chat and searching Company Communicator for the recipient.
If I start a new chat, will I be able to receive messages from CC again?

In other words, I would like to know how to Restart receive messages from CC.

Thankyou. (@ATshirai)

**Comment by gsv022** [comment]
Hi @MK202204 ,
We are working on it and will get back to you with proper response soon

**Comment by gsv022** [comment]
We are making a follow up in #954
