### ISSUE TITLE
Deploy to Azure Errors

### ISSUE THREAD

**Issue by TCTX365** [OfficeDev/microsoft-teams-apps-company-communicator#958]
Attempting to deploy the Company Communicator.  Not using PS method.  App registrations are complete in our test tenant.  The Deploy to Azure step is giving some trouble.  We have a similar deployment for TEOC (apps in test and service in Azure).

![CompanyCommunicator Fails1](https://user-images.githubusercontent.com/123653421/214879072-fce37402-8c9a-411d-9e27-545c95c58c99.png)

![CompanyCommunicator Fails2](https://user-images.githubusercontent.com/123653421/214879143-e8f4e827-20d6-4c29-9d8c-a330a60b70a8.png)

**Comment by GabrielPitondo** [comment]
Same problem here, any updates from the developers??

**Comment by gsv022** [comment]
HI @TCTX365 ,
Thanks for raising the query. It seems that the deployment got failed. The error says that the name given in **base resource name** section seems to be already used. Please give a **unique name** that was never used before and with no underscore added.

**Comment by TCTX365** [comment]
Well, after a lot of deleting and re-deploying with new base names, I was able to get this down to one error during standard deployment.  Is there any guidance on the following:





{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",
        "details": [
            {
                "message": "There was a conflict. Conflict with existing ScmType: ExternalGit"
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}
![New Error](https://user-images.githubusercontent.com/123653421/215607222-ac395dbf-e4a4-4242-bc8e-a969385f3f95.png)

**Comment by gsv022** [comment]
Hi @TCTX365 ,

- It seems that app service got failed. 
- If the resource is not connected to the repo. Please do connect the source to external git. Point the repository and branch  to the official repository of Company Communicator. Here is the reference.
Save it. 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/98143492/215697053-1a357295-10b3-4341-a50a-c52f626dfc43.png">


- Wait for success state in the logs section.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/98143492/215695824-00fb9b13-2662-425f-bc58-8d6edf71cd63.png">

- Then proceed with the remaining steps of deployment.

**Comment by TCTX365** [comment]
That worked for me, however it is a recurring problem when I try a clean deployment.  Is there a way to fix this before deploying, so the deployment is not in a failed state?

{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "There was a conflict. Conflict with existing ScmType: ExternalGit",
        "details": [
            {
                "message": "There was a conflict. Conflict with existing ScmType: ExternalGit"
            },
            {
                "code": "BadRequest"
            },
            {}
        ]
    }
}

**Comment by gsv022** [comment]
Hi @TCTX365 ,
Normally, the deployment will take around 30-50 minutes of time. One of the possible reasons is network issue due to that resource fails in pulling the code from GitHub repository. However this can be fixed by following the steps that I have shared.
