### ISSUE TITLE
Request of modification

### ISSUE THREAD

**Issue by pavankumardk1** [OfficeDev/microsoft-teams-apps-company-communicator#960]
Can we change the name of the app/bot "Company Communicator" to something else when it send message to users, if yes how can we do it?

**Comment by gsv022** [comment]
Hi @pavankumardk1 ,
Thanks for raising the query. Please refer to the issue no: - [957](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/957) where we have given the step by step procedure to change not only the name of Company Communicator but also the icon. 

Hope it helps.

**Comment by pavankumardk1** [comment]
yes, we followed those steps but still name was not changed.

**Comment by gsv022** [comment]
If the steps were followed correctly, changes should reflect. please give some time and open the teams in incognito/in private window to see the changes

**Comment by Scheiderichv094** [comment]
Were you able to sync the name change on users client version of Teams?
