### ISSUE TITLE
Send to specific teams or members does not show any results

### ISSUE THREAD

**Issue by TCTX365** [OfficeDev/microsoft-teams-apps-company-communicator#961]
Trying to use the Author app to send to General channel of specific teams or send in chat to members of the following teams does not give any search results.

We are able to get results when searching for M365 groups and security groups however.

What are we missing?

Standard deployment.  App registrations, users/groups/teams and app deployment are in our test tenant.  
![No Groups](https://user-images.githubusercontent.com/123653421/217361644-b228af4f-086b-4398-b192-cb95b1eeeede.png)

**Comment by gsv022** [comment]
Hi again @TCTX365 ,
This is a common issue which has been already addressed in our troubleshooting guide. Please have a look at the issue no: - [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message)

**Comment by TCTX365** [comment]
Thanks for pointing this out.  I already had created a new Team and a test channel.  I installed the author app with my test account to the new test channel.  Just added the app again to the General channel of the same new Team and same experience.    Creating a new test message in either the General or Test channel, the new message is not finding specific teams or members.

Wondering if we are just using it wrong or a permission is missing somewhere.
![image](https://user-images.githubusercontent.com/123653421/217556642-1b5256f7-ddb6-4d6e-9abc-f2a324d5b007.png)


![image](https://user-images.githubusercontent.com/123653421/217555873-542b370a-ed8c-4c68-bbfb-8dd502453d6a.png)


Also, in the test channel, the draft message is showing in the chat, but is saved as a draft message and unsent.

![image](https://user-images.githubusercontent.com/123653421/217555037-0a09bd04-1302-48bb-a3ef-1058376b6aac.png)

![image](https://user-images.githubusercontent.com/123653421/217555148-d231bea7-bde0-4001-af54-a4ffa778e744.png)

**Comment by gsv022** [comment]
Hi @TCTX365,
Could you please let us know the status, if the issue got resolved we are good to close out the issue.

**Comment by TCTX365** [comment]
Yes, we are working now and testing.  Thank you for the help!
