### ISSUE TITLE
The Azure App Insights key is not a valid GUID (Code: InvalidBotData)

### ISSUE THREAD

**Issue by wi11iamsu** [OfficeDev/microsoft-teams-apps-company-communicator#964]
Hi all,

I'm facing an error when I'm trying to deploy the app.
I'm stucking in "Step2 Deploy to your Azure subscription" in the Deployment Guide.
After I paste the 3 app ID and client secret infomation and trying to create, the error message shows that "The Azure App Insights key is not a valid GUID".
What should I do?

Thank you!

![Insights key error](https://user-images.githubusercontent.com/101968670/218384478-a533e48e-1192-416d-9c70-48eb24a5e6ec.png)

**Comment by gsv022** [comment]
Hi @wi11iamsu ,
Thanks for raising the query. If you are facing this issue, please use this link to generate 7 [GUID](https://www.guidgenerator.com/online-guid-generator.aspx) and paste it in the below 7 places and try validating it.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/98143492/218417396-4b3b2988-e4f3-4fed-95ff-89f56ef89265.png">

**Comment by Gucchiy** [comment]
I've encountered the same problem. I re-created and entered GUIDs, but it's reproduced. Could you please what I should see?
![image](https://user-images.githubusercontent.com/2966953/218424744-fcbdfac6-a475-440e-9c5e-4b01adf856ae.png)

**Comment by EmmanuelleC** [comment]
I've the same issue even after re-created GUID. Please help.

**Comment by gsv022** [comment]
@wi11iamsu , could you please do the app registrations again and try pasting the values while doing the ARM template creation.

Keep us posted.

**Comment by luishdemetrio** [comment]
I am with the same error here. I deleted the app registrations and changed the 7 GUIDs without success. :(

<img width="432" alt="image" src="https://user-images.githubusercontent.com/49683427/218573061-ec46f1d0-5d05-44ab-9762-0fa4fe315e67.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/49683427/218573265-65dfb8bc-1b01-4fd6-a373-e2289aa855f1.png">

**Comment by havlma1** [comment]
I have the same issue. Those 7 GUIDs have been generated as suggested, still it fails for author and graph apps:  
![image](https://user-images.githubusercontent.com/53163982/218584916-26d34122-ab7d-4de8-ac56-f0e1945d4175.png)

**Comment by wi11iamsu** [comment]
> @wi11iamsu , could you please do the app registrations again and try pasting the values while doing the ARM template creation.
> 
> Keep us posted.

Hi @gsv022 , it works with the GUID in your screenshot today.
Thanks for your help.

**Comment by havlma1** [comment]
> Hi @wi11iamsu , Thanks for raising the query. If you are facing this issue, please use this link to generate 7 [GUID](https://www.guidgenerator.com/online-guid-generator.aspx) and paste it in the below 7 places and try validating it. <img alt="image" width="453" src="https://user-images.githubusercontent.com/98143492/218417396-4b3b2988-e4f3-4fed-95ff-89f56ef89265.png">

HI 

> Hi @wi11iamsu , Thanks for raising the query. If you are facing this issue, please use this link to generate 7 [GUID](https://www.guidgenerator.com/online-guid-generator.aspx) and paste it in the below 7 places and try validating it. <img alt="image" width="453" src="https://user-images.githubusercontent.com/98143492/218417396-4b3b2988-e4f3-4fed-95ff-89f56ef89265.png">

Hi @gsv022 when I use default GUIDs then the validation works for ARM template deployment. However I need to deploy a second Company Communicator in our tenant, so when I generate new GUIDs via guidgenerator.com, the validation fails..

**Comment by EmmanuelleC** [comment]
Hi,
Everything works well this morning with new GUIDs. Thanks

**Comment by luishdemetrio** [comment]
It's working now without having to change anything. Do you know what happened? Please feel free to close the issue! 👊

**Comment by havlma1** [comment]
For me it works as well. Thanks

**Comment by gsv022** [comment]
@wi11iamsu , 
We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.

**Comment by CeciliaRavera** [comment]
We are facing the same issue even after re-created GUID... any help?

**Comment by allengeorgek** [comment]
Tried to deploy the app for a customer today & received the following error similar to the ones being discussed.
Generated new GUID & still the same error message while validating the Azure App Insights Key. Says it is not a valid GUID.

Raw Error:
{  "code": "InvalidTemplateDeployment",  "details": [    {      "details": [        {          "code": "InvalidBotData",          "target": "TeamsCommunicator-author",          "message": "The Azure App Insights key is not a valid GUID"        },        {          "code": "InvalidBotData",          "target": "TeamsCommunicator",          "message": "The Azure App Insights key is not a valid GUID"        }      ]    }  ],  "message": "The template deployment 'Microsoft.Template-20230301122158' is not valid according to the validation procedure. The tracking id is '178caf13-3f5b-47d6-874a-c0d5eda0d90f'. See inner errors for details."}

**Comment by manuelsambade** [comment]
Hi,

I am also having the same issue.

It worked the first time yesterday, but I had to delete all the resources and start from zero. It didn't work yesterday, and today I am still unable to deploy the solution even with news GUIDs for the last parameters.

"code": "InvalidBotData"
"The Azure App Insights key is not a valid GUID"

Can someone please advise?

Thank you.

**Comment by faranzazu** [comment]
Hi,

I´m facing the same problem, even after generating the new 7 IDs. Please your help to fix this issue.

Thank you!
