### ISSUE TITLE
Upgrading from v5.x to latest version Failed / Fail to Sync?

### ISSUE THREAD

**Issue by frazermountford** [OfficeDev/microsoft-teams-apps-company-communicator#965]
I Have followed the upgrade guide as below "Upgrading from v5.x to latest version"
https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/v5-migration-guide

It has failed to upgrade and the functions report the Function Extensions version are out of date
https://github.com/Azure/Azure-Functions/issues/1987

If i go to Deployment Centre and perform a sync it does not appear to be updating to the latest version, the version it is using is 
6b57d0d as of June 8th 2022 but does not report any update failures as such

**Comment by gsv022** [comment]
Hi @frazermountford ,
Thanks for raising the query. 

- Could you please send us the supporting screenshots of the error that you are getting. 
- Please send the screenshot of the App service deployment status. Here is the reference.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98143492/218514186-1851d47b-ac06-41da-a8ef-f9caa2048bc5.png">

**Comment by frazermountford** [comment]
Below is the screenshot of the deployment, it appears to me, unless im wrong that this is not the latest version
![Capture](https://user-images.githubusercontent.com/64525373/218518389-be6b6661-a1ca-40b8-aa05-46583ff5b62f.PNG)

**Comment by gsv022** [comment]
Hi @frazermountford ,
If the steps were followed already mentioned in the v5 migration guide. Please share the screenshots of the Azure functions. Here is the reference.
<img width="589" alt="image" src="https://user-images.githubusercontent.com/98143492/218709625-c4a05207-e28e-4d14-885c-46bc493a74d9.png">

**Comment by frazermountford** [comment]
This is the error seen on each function ![image](https://user-images.githubusercontent.com/64525373/218736161-ca1fdada-63d1-485f-829d-581ec83a3d0c.png)

**Comment by frazermountford** [comment]
We have resolved the issue by following the Troubleshooting Guide - 5. App service Sync throws npm error (but performed the reconnect of GIT for the web app and 3 functions)

https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#5-app-service-sync-throws-npm-error
