### ISSUE TITLE
Need assistance changing app name

### ISSUE THREAD

**Issue by Scheiderichv094** [OfficeDev/microsoft-teams-apps-company-communicator#966]
We are trying to follow the steps on how to change the name but some of the steps are not clear. Are we able to schedule a Teams meeting to walk through the steps?

**Comment by gsv022** [comment]
Hi @Scheiderichv094 ,
Could you please share us the detailed situation of the issue. Even supporting screenshots would be more helpful

**Comment by gsv022** [comment]
@Scheiderichv094 , As the requirements is to change only the name,  follow the steps mentioned in issue no: -[957](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/957)

-  In the author manifest we need to change only the name (highlighted place) and same applies to user manifest as well. 

<img width="559" alt="image" src="https://user-images.githubusercontent.com/98143492/219016957-2b2200ea-b101-4e6f-ae6c-ab6cf915a130.png">

- Re-upload the manifest files to the teams again. Changes will reflect after certain period of time

Hope we conveyed.

**Comment by Scheiderichv094** [comment]
We no longer have the original manifest we deployed company communicator with so we're using a new manifest. Do we still only fill those fields out or do we need to fill the whole thing out again?

**Comment by gsv022** [comment]
If the original manifest are missing, check the version of the app first and have the manifest files downloaded of that particular version only and then fill out **all the parameters**  as per the deployment guide for both author and user. Then re-upload them. This should work.
