### ISSUE TITLE
BadRequest

### ISSUE THREAD

**Issue by saifgazo** [OfficeDev/microsoft-teams-apps-company-communicator#968]
I am trying to deploy the app and I am getting the following error "{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"message":"Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: The remote server returned an error: (503) Server Unavailable.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at "

**Comment by gsv022** [comment]
Hi @saifgazo ,
Thanks for raising the query. Could you please share the screenshot showing the resource failed. Here is the reference(yellow highlighted one).
<img width="805" alt="image" src="https://user-images.githubusercontent.com/98143492/219612763-6b7ebfc7-23ed-4fdb-9d6a-6af8b2944901.png">

**Comment by saifgazo** [comment]
Hello there,

[Graphical user interface, application, Teams  Description automatically generated]

**Comment by gsv022** [comment]
@saifgazo , Could you please respond again because the previous response contains the content  which is in a masked state.

**Comment by saifgazo** [comment]
Hi,

I have attached the file and added the screenshot in case one way doesn't work.

Thanks
Saif Gazo
[Graphical user interface, application  Description automatically generated]

**Comment by gsv022** [comment]
@saifgazo , Sorry for the late reply. Could you please share them directly here.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/98143492/223956071-8f41b59b-4ed7-4cd4-96d7-db6bb16ca0cc.png">

**Comment by v-jaygupta** [comment]
Hi @saifgazo ,

Can you please attach the screenshots / logs directly to the GitHub thread [#968](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/968) as we are unable to retrieve them from the mail you sent.

**Comment by saifgazo** [comment]
![error](https://user-images.githubusercontent.com/125609481/226412462-d41975b0-9566-4dd2-b8f6-55933eef13ba.jpg)

**Comment by gsv022** [comment]
It seems that one of the functions got failed. To reach failed resources, Go to azure portal-->Go to resource group(Where the deployment has been done)-->Select Function(the one which got failed) from list of resources-->Go to Deployment Center-->Click on Settings

<img width="592" alt="image" src="https://user-images.githubusercontent.com/98143492/220826419-783f50cb-7868-492e-b35d-9392364b4b97.png">

- If the resource is not pointing to intended repository and  showing empty. Please connect to the external Git and point to the official repository.
- Or if it is already connected to the intended repository and in the logs section showing the status as failed. Please click on **SYNC** 
- Once the status turns to Success(active) then good to proceed with remaining steps of deployment.

**Comment by allthetrouts** [comment]
Same problem here deploying from ARM template:
![image](https://user-images.githubusercontent.com/69280272/228595414-8b485e81-dde0-46b8-9d6b-1311d4c4df45.png)
