### ISSUE TITLE
User not receiving any communication despite app is installed

### ISSUE THREAD

**Issue by gp92** [OfficeDev/microsoft-teams-apps-company-communicator#970]
We are experiencing an issue on a specific user is not receiving any message despite is having the app installed.
She was able to receive messages 6 months ago then suddenly stopped and does not work anymore.
Exporting the logs, the error reported is -2 (app not installed) but we checked with the command: Get-MgUserTeamworkInstalledApp and the result is that the app is installed.
We tried to:

- re-install the app but nothing
- force the installation of the app. An error is raised saying AppEntitlement id: 'XXXXXXX' already exists in thread which means that app is installed

Any advice on how to sort out it?

**Comment by gsv022** [comment]
Hi @gp92,
Thanks for raising the query.  Please follow the below procedure.

- Go to Azure Portal.
- Select the resource group where the app is deployed,
- Go to storage account.
- Click on Storage browser
- Delete the User app Id entry in app config table.
- Try sending a message again.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/98143492/220856308-12784eaa-8fc9-4add-9f38-9b610803c346.png">

**Comment by gp92** [comment]
Hi @gsv022,

I do not have any UserAppId record under the AppConfig table (see below)
![image](https://user-images.githubusercontent.com/5497444/220904219-b254d875-f62f-4bfe-b9cd-a42d0b2996f7.png)

**Comment by gsv022** [comment]
@gp92 , We will check this from our end and will let you know. Meanwhile please share the **repo url** and **branch** that has been used for deployment.

**Comment by gp92** [comment]
@gsv022 here the branch used: https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/tree/v5.0

**Comment by gsv022** [comment]
Please share the Outlook Id to have conversation internally. If needed we shall get into the call and discuss the issue.

**Comment by Sreeraj-kroll** [comment]
Hi @gp92 

I too had the same issue (https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/915) but I managed to resolve it by running the Powershell scripts attached in the comment - https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/915#issuecomment-1322351595 on the affected user's machine.

The jist of the script is that the Teams cache needed to be cleared.

Hope it helps

**Comment by gp92** [comment]
Hi @Sreeraj-kroll,

Already done but still facing the issue. Thanks anyway for the hint

@gsv022 Outlook ID: gpalermo@hotmail.it

**Comment by gsv022** [comment]
@gp92 , we will approach you shortly via MS teams and mail to discuss more on this issue.

**Comment by Sreeraj-kroll** [comment]
> Hi @Sreeraj-kroll,
> 
> Already done but still facing the issue. Thanks anyway for the hint
> 
> @gsv022 Outlook ID: [gpalermo@hotmail.it](mailto:gpalermo@hotmail.it)

Oh that’s a shame…for some users we also had to ask them to sign out and quit Teams in desktop and sign out from web too and sign back in. 

I am assuming you did the same.

Good luck … hope it gets fixed soon

**Comment by gsv022** [comment]
@gp92 , Please share your availability for this week(08-03-2023 to 10-03-2023) including the time zone so that we can share meeting invite to discuss more on this issue.

**Comment by gp92** [comment]
@gsv022 below my availability:
8/3 after 2:30pm
9/3 after 3pm
10/3 after 10am
Timezone: CET

**Comment by gsv022** [comment]
@gp92 , We have sent you a meeting invite for the given mail. Please accept it or in case of change in plan let us know at the earliest.

**Comment by gsv022** [comment]
@gp92 , Could you please let us know the status.

**Comment by gp92** [comment]
@gsv022 we performed the test agreed during the meeting with no luck

**Comment by v-jaygupta** [comment]
Hi @gp92 ,
Please let us know if you are available on 24/03 between 11 AM to 1 PM OR on 25/03 after 7:30 PM 
IST Time Zone to discuss the issue on call

**Comment by gsv022** [comment]
@gp92 , Please respond to the above query.
