### ISSUE TITLE
Second deployment results 'Failed to create or update User app in Azure Active Directory. Exiting...'

### ISSUE THREAD

**Issue by iainRclark** [OfficeDev/microsoft-teams-apps-company-communicator#971]
When attempting to deploy a second Company Communicator via the deployment script I receive the error 'Failed to create or update User app in Azure Active Directory. Exiting...' There are a few non-blocking errors as well, below is the full PowerShell output (minus some personal details)

`Starting deployment...
Login with with your Azure subscription account. Launching Azure sign-in window...

WARNING: A web browser has been opened at https://login.microsoftonline.com/<OMITTED>/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
Azure AD sign-in...
Checking for resources availability...
resource: pwazd1m365devcc of type webapp is available.
resource: pwazd1m365devcc-data-function of type webapp is available.
resource: pwazd1m365devcc-function of type webapp is available.
resource: pwazd1m365devcc-prep-function of type webapp is available.
Application Insights resource (pwazd1m365devcc) is available.

Creating Azure AD App: pwazd1m365devcc-users...
ERROR: unrecognized arguments: --available-to-other-tenants True --oauth2-allow-implicit-flow False

Examples from AI knowledge base:
az ad app create --display-name mytestapp --optional-claims @manifest.json
Create an application with optional claims

az ad app create --display-name mytestapp --identifier-uris https://mytestapp.websites.net/ --app-roles @manifest.json
Create an application with a role

https://docs.microsoft.com/en-US/cli/azure/ad/app#az_ad_app_create
Read more about the command in reference docs
Waiting for app creation to finish...
Azure AD App: pwazd1m365devcc-users is created.
Updating app secret...
ERROR: argument --id: expected one argument

Examples from AI knowledge base:
az ad app credential reset --id 00000000-0000-0000-0000-000000000000
append or overwrite an application's password or certificate credentials (autogenerated)

az ad app credential reset --id 00000000-0000-0000-0000-000000000000 --cert "@~/cert.pem"
Append a certificate to the application with the certificate file.

https://docs.microsoft.com/en-US/cli/azure/ad/app/credential#az_ad_app_credential_reset
Read more about the command in reference docs
Azure AD App: pwazd1m365devcc-users registered successfully.
Failed to create or update User app in Azure Active Directory. Exiting...
Account                        SubscriptionName     TenantId                             Environment
-------                        ----------------     --------                             -----------
<OMITTED>`

1. No resources are created and no apps are registered. 
2. The resource group specified in the parameters.json is an existing resource group.
3. The userAppExternalId was changed to differentiate it from the other solution, as were all the role GUID's

I can upload the parameters.json if that would be useful (omitting certain details).

Thanks,

**Comment by gsv022** [comment]
Hi @iainRclark ,
Thanks for raising the query. Could you please mention the version of Azure CLI?

**Comment by iainRclark** [comment]
"azure-cli": "2.42.0",
"azure-cli-core": "2.42.0",
"azure-cli-telemetry": "1.0.8",
"extensions": {}

**Comment by gsv022** [comment]
@iainRclark ,The Azure CLI version should be 2.30. If it is not same, could you please download the [Azure CLI version](https://azcliprod.blob.core.windows.net/msi/azure-cli-2.30.0.msi) and try the procedure again. Please delete 2.42.0 Azure CLI version if already installed

**Comment by infninfn** [comment]
I am also unable to run the deploy.ps1 script without errors and have tried downgrading to Azure CLI 2.30. However, there is an automatic upgrade process now which upgrades it to 2.45.0 when running Azure CLI commands.

> WARNING: New Azure CLI version available. Running 'az upgrade' to update automatically.
> WARNING: This command is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
> WARNING: Your current Azure CLI version is 2.30.0. Latest version available is 2.45.0.
> WARNING: Please check the release notes first: https://docs.microsoft.com/cli/azure/release-notes-azure-cli
> WARNING: Updating Azure CLI with MSI from https://aka.ms/installazurecliwindows
> WARNING: Downloading MSI to C:\Users\brandop\AppData\Local\Temp\tmp0a436dn_\azure-cli-2.45.0.msi
> WARNING: Installing MSI

Back to the error: 
 --available-to-other-tenants --oauth2-allow-implicit-flow
These options are no longer valid for _az ad app create_.

(https://learn.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create-optional-parameters) shows the new method should be like so:
az ad app create --display-name $appName --sign-in-audience AzureADMultipleOrgs --enable-access-token-issuance $true

Please update the deployment script for the new CLI.

**Comment by albert-widjaja** [comment]
OK, so the latest azure cli will not be working with the deploy.ps1 installation method?

![image](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/assets/69803760/74807b9d-a845-499c-99f0-64f6e9851b9f)
