### ISSUE TITLE
Message stuck in "Queued" status

### ISSUE THREAD

**Issue by BernardHyh** [OfficeDev/microsoft-teams-apps-company-communicator#972]
Message stuck in "queued" status. Tried to cancel the message but encountered error - " Ooops! An unexpected error seems to have occured. Why not try refreshing your page? Or can you contact your administrator if te problem persists." .

**Comment by gsv022** [comment]
Hi @BernardHyh ,
Thanks for raising the query. There are multiple reasons for this issue.

- What is the version of the app?
- One of the reasons might be incorrect configuration. Please verify the configuration end-end.
- Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
Author-multiple
User-multiple
Graph-my organization
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">

Hope it helps

**Comment by BernardHyh** [comment]
- Version of app: 5.2.1
- Doubt is configuration issue as I have no issue sending new messages. Problem only occur to 1 specific message which is currently still under "queued" status.
- multiple organizations

**Comment by gsv022** [comment]
Could you please share the GitHub repo URL and branch. Here is the procedure.
--Go to Azure Portal
-- Click on Resource Group
-- Under your subscription, select the resource group where deployment has been done
-- Please open the highlighted one. Screenshot has been shared for the reference
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/205561751-a76c14c5-8973-4493-ac80-2d15fee28b1a.png">

--Click on  Microsoft template

<img width="952" alt="image" src="https://user-images.githubusercontent.com/98143492/205561956-1689f9fe-f5d0-448f-afab-41212d5b3ef6.png">

 -- Then select **inputs** from left section where you can find the GitHub repo URL and Branch that are used. Please share them.
 <img width="943" alt="image" src="https://user-images.githubusercontent.com/98143492/204268766-d68c11c0-d767-4bbc-beda-566a5b1abe48.png">

**Comment by BernardHyh** [comment]
as attached.

![54A00CBD-76AC-4076-A59B-5E3E711EC383](https://user-images.githubusercontent.com/126217741/221726121-b0fb4af5-bf58-4c1d-8892-3ad1376d9d1e.png)

**Comment by gsv022** [comment]
> * Version of app: 5.2.1
> * Doubt is configuration issue as I have no issue sending new messages. Problem only occur to 1 specific message which is currently still under "queued" status.
> * multiple organizations

As you mentioned Supported type is set multiple organizations. Could you please share the screenshots of Author, User, Graph app **overview** sections showing the supported account type.

**Comment by BernardHyh** [comment]
Please provide the steps and the reference screen capture for the required info.

**Comment by gsv022** [comment]
> Hi @BernardHyh , Thanks for raising the query. There are multiple reasons for this issue.
> 
> * What is the version of the app?
> * One of the reasons might be incorrect configuration. Please verify the configuration end-end.
> * Check whether the **Supported type** parameter for app registration is as per the deployment guide. Here is the reference.
>   Author-multiple
>   User-multiple
>   Graph-my organization
> 
> <img alt="image" width="686" src="https://user-images.githubusercontent.com/98143492/221160735-4a1f8b6f-7361-4f67-ba7b-0d5c2d24ec17.png">
> 
> Hope it helps

Here in the third point, I have highlighted the required in screenshot. Please check and share the same and do it for all three app registrations

**Comment by gsv022** [comment]
@BernardHyh , could you please let us know the status.
