### ISSUE TITLE
Can Company Communicator be integrated into ServiceNow?

### ISSUE THREAD

**Issue by Scheiderichv094** [OfficeDev/microsoft-teams-apps-company-communicator#976]
Working on automating ServiceNow and our Teams company communicator app and wanted to know if you guys know if it's possible and if you know how?

**Comment by gsv022** [comment]
Hi @Scheiderichv094 ,
Thanks for raising the query.  Please share the details of the approach that you are doing. We wont provide any inputs on integration with ServiceNow.

**Comment by gsv022** [comment]
@Scheiderichv094 , Could you please respond to the above queries
