### ISSUE TITLE
Incorrect version number displayed in App details after upgrade to v5.3

### ISSUE THREAD

**Issue by PrithuMahisha** [OfficeDev/microsoft-teams-apps-company-communicator#978]
Upgraded the application to v5.3 using the PowerShell commands provided, but it has been found that the app version number is not updated to the latest version.

Does it has to be manually updated in the manifest file and re-upload the app package in Teams Admin center?
If there is any other approach, please suggest.

**Comment by gsv022** [comment]
Hi @PrithuMahisha ,
Thanks for raising the query. As the manifest file contains bot Id 's and app domain which remain constant irrespective of version. So once it is uploaded there is no need of re-uploading them again.

- As you mentioned using Powershell commands, upgradation has been done. Could you please share the screenshot of the runtime version for function apps. Here is the reference.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/98143492/222490408-1ae69f38-d78b-4c9c-bd91-a14f8a315967.png">

- Please share the screenshot of  App Service(web app). Here is the reference.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/98143492/222491525-01edff0f-e359-40f6-aa18-0f8bfbb27635.png">

**Comment by PrithuMahisha** [comment]
Hi @gsv022 ,

I was mentioning about the app version displayed in the Teams Client App Store. Please refer yellow highlighted in the below image.
![image](https://user-images.githubusercontent.com/15922771/222750929-0acae131-f697-42d6-971e-d09e33848b6e.png)

It shows v5.0.0 even after upgrading to the latest version v5.3.

**Comment by gsv022** [comment]
@PrithuMahisha ,
I got it what you are referring to.  To reflect the latest versions especially at the place you are pointing to, the latest manifest has to be uploaded again.

**Comment by PrithuMahisha** [comment]
Thanks for the clarification. However, I would like to know if this can be done through the powershell commands during the upgrade process itself, for the future upgrades.

**Comment by v-royavinash** [comment]
@PrithuMahisha At this time, the migration steps must be performed manually, as there is no option to perform the migration using PowerShell. Currently, PowerShell only supports a new deployment.
