### ISSUE TITLE
hello  Is there a file for Power BI that can track status, reading, clicks?

### ISSUE THREAD

**Issue by Fadel1949** [OfficeDev/microsoft-teams-apps-company-communicator#981]
Is there a file for Power BI that can track status, reading, clicks?
I looked at the tables in Azure, the reads weren't there.

**Comment by gsv022** [comment]
Hi @Fadel1949 ,
Thanks for raising the query. We have already added this feature to our backlog and will be considered in future releases of CC based on the priority.
