### ISSUE TITLE
User in distribution list, but not receiving messages

### ISSUE THREAD

**Issue by SynHam** [OfficeDev/microsoft-teams-apps-company-communicator#982]
Hi,
We're getting reports of some people not receiving messages, they are in the distribution lists, but don't even show in the export afterwards. The list is made up of around 2300 users, the majority of which have no issues.

Thanks

**Comment by gsv022** [comment]
Hi @SynHam ,
Thanks for raising the query. Please respond to the below queries.

- What is the version of the app?
- Is this happening for only for 1 sending option or for all sending options. Please confirm.
- Share the export results.
- Supporting screenshots will do the needful

**Comment by SynHam** [comment]
Hi @gsv022 
What is the version of the app? - 5.2.0
Is this happening for only for 1 sending option or for all sending options. Please confirm. - We only use distribution lists, all company would sent to over 8000 accounts.
Share the export results. - The user we're focusing on doesn't show up in the export at all.
Supporting screenshots will do the needful - The failures are people who have blocked the bot.
![image](https://user-images.githubusercontent.com/127293724/223693370-5d41ea35-b659-491d-9b8b-06f6bbacec7e.png)

**Comment by gsv022** [comment]
Could you please provide the outlook id so that we can discuss more on this issue internally.

**Comment by SynHam** [comment]
We might of found out why. If the user blocks the bot and deletes the chat they don't show up in the export at all. If we uninstall the app and reinstall it then starts working and shows them in the export.

**Comment by gsv022** [comment]
We are closing out the issue as this is a known issue, we are having this issue type already opened. Here is the reference [954](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/954).
