### ISSUE TITLE
AzureDeploy.Json

### ISSUE THREAD

**Issue by Quson-Team** [OfficeDev/microsoft-teams-apps-company-communicator#983]
I am getting this error when trying to deploy. I have verified the json file is there

Deploying app services, Azure function, bot service, and other supporting resources... (this step can take over an hour)
<< was unexpected at this time.
Fetching deployment status to check if deployment really failed...
ERROR: (DeploymentNotFound) Deployment 'azuredeploy' could not be found.
Code: DeploymentNotFound
Message: Deployment 'azuredeploy' could not be found.
ERROR: (DeploymentNotFound) Deployment 'azuredeploy' could not be found.
Code: DeploymentNotFound
Message: Deployment 'azuredeploy' could not be found.
Collecting deployment logs...

**Comment by gsv022** [comment]
Hi @Quson-Team ,
Thanks for raising the query here. We are making a follow up internally

**Comment by gsv022** [comment]
We are closing the issue as we are following internally.
