### ISSUE TITLE
Failed to create conversation with teams user

### ISSUE THREAD

**Issue by Tamilselvan27** [OfficeDev/microsoft-teams-apps-company-communicator#984]
While Initiating Message, I'm facing this issue. Please help us solve it ASAP. Thanks, in advance.

**Issue:**
Failed to create conversation with teams user: 29:1sehK5sGmCrNsaAjeSaw-tZbtpKT6HuAW9mbEPXoD3eFIZCJpZO75pNez_Er_0wLOOg9H1w8CELUiZH6Obbqs2g. Exception: Failed to create conversation. Error message: {"message":"Authorization has been denied for this request."} Failed to create conversation with teams user: 29:1sehK5sGmCrNsaAjeSaw-tZbtpKT6HuAW9mbEPXoD3eFIZCJpZO75pNez_Er_0wLOOg9H1w8CELUiZH6Obbqs2g. Exception: Failed to create conversation. Error message: {"message":"Authorization has been denied for this request."} Failed to create conversation with teams user: 29:1sehK5sGmCrNsaAjeSaw-tZbtpKT6HuAW9mbEPXoD3eFIZCJpZO75pNez_Er_0wLOOg9H1w8CELUiZH6Obbqs2g. Exception: Failed to create conversation. Error message: {"message":"Authorization has been denied for this request.

**Comment by gsv022** [comment]
@Tamilselvan27 , Could you please respond to the above queries.

**Comment by Tamilselvan27** [comment]
The issue was resolved. Its the Teams channel missed .

**Comment by Tamilselvan27** [comment]
Thanks @gsv022, it's the team's channel was missed in the bot service.
