### ISSUE TITLE
Proactive app installation is not working for User app

### ISSUE THREAD

**Issue by NikhilDhumal734** [OfficeDev/microsoft-teams-apps-company-communicator#986]
Hello Team,

we are getting error when sending out messages to a m365, DL groups where the users don't already have the User app installed. Seems like the auto proactive deploy app option isn't working. Proactive app installation attribute is already set to true.

Please advise or help on Priority. it's bit urgent!!

![image](https://user-images.githubusercontent.com/119613793/225660938-5da03ad9-0cfa-4da8-b7a0-6d43a4fd917e.png)
![image](https://user-images.githubusercontent.com/119613793/225661846-0b21fcb1-24f6-4700-beaf-227f0f87a320.png)

**Comment by gsv022** [comment]
Hi @NikhilDhumal734 ,
Thanks for raising the query. Please refer to question number [8](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message) in troubleshooting guide to understand more on this issue, kindly let us know if it helped in resolving the issue

**Comment by NikhilDhumal734** [comment]
Thanks Sai for the information one more question Can we upload audio and video files and post them as a message through Author app?

**Comment by gsv022** [comment]
No, it is not possible to upload audio and video files. Please let us know if you have any queries otherwise we are good to close out the issue

**Comment by gsv022** [comment]
@NikhilDhumal734 , We are closing this request as we have provided the inputs for the query raised. If you face any issue with company communicator please raise a new issue for further assistance.
