### ISSUE TITLE
Cannot send in chat to members of group

### ISSUE THREAD

**Issue by githubclaw** [OfficeDev/microsoft-teams-apps-company-communicator#988]
When I am trying to send messages to a M365 group, I got the below error "fail to get members for group".
![MicrosoftTeams-image (32)](https://user-images.githubusercontent.com/128158217/225925767-566e054d-17e7-45ac-995f-db9f7c87df1c.png)

I have confirmed that the user app is installed on the group members' Teams.

**Comment by v-jaygupta** [comment]
Hi @githubclaw 
Can you please please go the application insights within resource group where Company Communicator was deployed and share the screenshot of details error logs.

**Comment by gsv022** [comment]
@githubclaw , Could you please let us know the status.
