### ISSUE TITLE
Error: Permission needed. Ask your IT admin to enable this option for you

### ISSUE THREAD

**Issue by rex-ma** [OfficeDev/microsoft-teams-apps-company-communicator#989]
Hi Teams,

I found the follwoing error after the deployment, even I have verified the graph app [**_set up Authentication_**] step in deployment guide was correctly configured already
Please kindly advise if any other configuration can review, thanks

<img width="593" alt="image" src="https://user-images.githubusercontent.com/25476072/226273382-eb1de3b5-f1c5-4200-b3ad-f8df8ebfee04.png">

**Comment by v-jaygupta** [comment]
Hi @rex-ma ,
There are multiple reasons why this error might occur, could you please confirm on below points –

- When was the last time the message was sent to users?

- What is the version of Company Communicator app?

- Could you please cross check the values of client secret for User, Author & Graph app from azure key vault and make sure the values are same as generated at the time of App registrations or there might be chance that the secrets might have expired.

**Comment by rex-ma** [comment]
> Hi @rex-ma , There are multiple reasons why this error might occur, could you please confirm on below points –
> 
> * When was the last time the message was sent to users?
> * What is the version of Company Communicator app?
> * Could you please cross check the values of client secret for User, Author & Graph app from azure key vault and make sure the values are same as generated at the time of App registrations or there might be chance that the secrets might have expired.

1. Never sent message
2. v5.x
3. Please kindly advisr which applciation configuration should match which key vault that generated in the deployment process?
I saw the following reply in another post, and I am confuse why 
<img width="708" alt="image" src="https://user-images.githubusercontent.com/25476072/226502204-75113b6b-b235-4a8f-bf0f-71866a6d622b.png">

**Comment by v-jaygupta** [comment]
Hi @rex-ma ,

Please validate the fields like AzureAd:ClientSecret (its graph app password only), AuthorAppPassword, GraphAppPassword & UserAppPassword from the configuration section of the deployed App service and the three function apps (Data Function, Send Function, Prep Function)

**Comment by gsv022** [comment]
@rex-ma , Could you please let us know the status.
