### ISSUE TITLE
Provided add-in package was not understood.

### ISSUE THREAD

**Issue by OlufemiOlaoye** [OfficeDev/microsoft-teams-apps-company-communicator#991]
I am getting this error message when I try to upload the app package on Developer portal and on Teams.
''Provided add-in package was not understood. Please, make sure that the file being submitted is a valid Office add-in package.''
From the Teams admin center, I get the attached error. 
These errors are from both User app and Author app.
<img width="337" alt="Screenshot 2023-03-25 133837" src="https://user-images.githubusercontent.com/112813965/227717785-fae01758-349f-4d12-90c0-a05dba919d5d.png">
I need help urgently!

**Comment by gsv022** [comment]
Hi @OlufemiOlaoye ,
Thanks for raising the query. Could you please share the manifest files of author and user zip files

**Comment by OlufemiOlaoye** [comment]
Dear @gsv022, thanks for the response.
I have attached both as requested.
Many thanks.
[company-communicator-users.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11074855/company-communicator-users.zip)
[company-communicator-authors.zip](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/files/11074856/company-communicator-authors.zip)

**Comment by OlufemiOlaoye** [comment]
> It is happening because in the manifest_users need to be renamed as manifest before zipping. Do the same for author manifest as well.
> 
> Then try to upload it . It will work.

Thank you very much this worked.

However, I am trying to build another Company Communicator but I'm experiencing the attached issue.

Please assist.

<img width="305" alt="Screenshot 2023-03-29 102052" src="https://user-images.githubusercontent.com/112813965/228488625-5b2cb4a0-ab86-4fdc-8c3f-7200a7dee771.png">

**Comment by OlufemiOlaoye** [comment]
So, I found this resolution - https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues/968 - it worked!

Any idea where I can find _appName.azurefd.net_?

**Comment by gsv022** [comment]
@OlufemiOlaoye , Great that the  first issue got solved. Coming to second issue, here
**appName**.azurefd.net ==> **BaseResourceName**.azurefd.net. Here is the reference.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/98143492/228513876-7e69bdff-efe6-4c31-adea-e7d9469662cb.png">

Please let us know if you have any queries with Company Communicator if not, we are good to close out the issue.

**Comment by OlufemiOlaoye** [comment]
Thanks a lot for your assistance. Everything is working fine now. I have successfully uploaded both User and Author apps on Teams. Tested it and got _Failed to sync all users_. 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/112813965/228515981-4980c525-41b3-4091-b933-720a8d80f623.png">

**Comment by OlufemiOlaoye** [comment]
Hello @gsv022 and @v-royavinash,
Thanks for your help.
I still need help on _Failed to sync all users. Status Code: 0 Exception: Code: generalException Message: An error occurred sending the request._

I have checked the client secret, it has not expired. I also restarted the app service and function apps.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/112813965/229040436-3a66ad3a-6962-40b5-88de-0724714c7390.png">

**Comment by gsv022** [comment]
Hi @OlufemiOlaoye ,
There might be many reasons for this issue. Particularly, could you please cross-verify the  [setup authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) steps are already done as per the deployment guide."

**Comment by gsv022** [comment]
Please respond to the above query

**Comment by OlufemiOlaoye** [comment]
> Hi @OlufemiOlaoye , There might be many reasons for this issue. Particularly, could you please cross-verify the [setup authentication](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide#3-set-up-authentication) steps are already done as per the deployment guide."

Yes, this is already done. See below.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/112813965/230000516-876d2caf-7302-4078-a803-15a6f7e8acce.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/112813965/230000971-d29313b2-7e8c-45e2-8d6e-ce4c12aaa097.png">

<img width="271" alt="image" src="https://user-images.githubusercontent.com/112813965/230001275-ae2c393a-51ce-4cf0-8e3d-5863a0b615a2.png">

**Comment by gsv022** [comment]
Hi @OlufemiOlaoye ,
We are closing the issue because for the subject issue manifest file uploading one, we have responded and glad that issue got resolved. Please log the happening issue as new one otherwise our efforts go untracked.
