### ISSUE TITLE
Client secrets (user and author bots, graph app) are expired. I am trying to follow update Key-vault with Client secrets

### ISSUE THREAD

**Issue by tyi1473** [OfficeDev/microsoft-teams-apps-company-communicator#992]
"The operation " List" is not enabled in this key vault's access policy." is warning me when I am trying to update key vault with new client secret. The Microsoft Document didn't work for me.
From <https://learn.microsoft.com/en-us/azure/industry/training-services/microsoft-community-training/frequently-asked-questions/generate-new-clientsecret-link-to-key-vault?source=recommendations>
Currently V5.3 is running.  What is the best way to update it with new secret?

**Comment by tyi1473** [comment]
Do you have any PowerShell Scripts simply run to update the key vault?
Thanks

**Comment by gsv022** [comment]
Hi @tyi1473 ,
Thanks for raising the query. Please follow the below  procedure. 
- Go to Azure Portal
- Go to App registration
- If the secret is already expired/nearing to expiry, click ‘New client secret’ and generate it.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/98143492/201635245-3d3145de-ae45-421a-aeb9-3665b1336ebe.png">
- Copy the value, navigate to the Azure key vault for Company Communicator -> Secrets -> update the AuthorAppPassword
<img width="709" alt="image" src="https://user-images.githubusercontent.com/98143492/201636091-ea516065-5c56-440c-82f5-1a5f25a51efe.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/98143492/201623438-f3d488f2-5d61-4a31-9523-9385893aba6e.png">

- Copy the key vault URL of author app password.  Update the URL in configuration of **app service** and **3 function apps** **wherever necessary**.
**Note:- Please repeat the above steps user App password and Graph App Password(whichever is nearing to expiry).**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/98143492/201638001-58696a3f-da22-4a2a-ae1d-7bc1e0e244cf.png">


- Restart the app services, function apps.

**Comment by tyi1473** [comment]
@gsv022, I saw that previously. in Company Communicator -> Secrets -> update the AuthorAppPassword , Authorapppassword was not even shown on the secret. "The operation " List" is not enabled in this key vault's access policy." is on the top of the page.

**Comment by tyi1473** [comment]
![List_not_enabled1](https://user-images.githubusercontent.com/65746803/228046560-7293a7d6-0aa5-4fed-872c-af67e437be6d.PNG)

**Comment by tyi1473** [comment]
@gsv022, I saw that previously. in Company Communicator -> Secrets -> update the AuthorAppPassword , Authorapppassword was not even shown on the secret. "The operation " List" is not enabled in this key vault's access policy." is on the top of the page.

**Comment by gsv022** [comment]
@tyi1473 , Please get access to view secrets. Here is the procedure.

- Go to Access Policy--> Click on Create
<img width="604" alt="image" src="https://user-images.githubusercontent.com/98143492/228512304-975a2bb7-7051-4209-97e1-b309aaf5d775.png">

- Select **Key, secret and certificate management**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/98143492/228512570-0ed05c8e-7af0-40ab-8e40-906feada9d7b.png">

- Give the Id through which one can view the secrets
<img width="475" alt="image" src="https://user-images.githubusercontent.com/98143492/228512930-fad4bc98-73ca-4fc6-a1d9-a27e5946cd14.png">

- 3rd step is optional
- Go for Review+Create
- Then go to Secrets. You will be able to view the secrets

**Comment by tyi1473** [comment]
@gsv022, Thanks for your help. It worked for me. I had to configure these codes on 4 app services, individually. (web service and 3 function apps). Do we have any easy way to apply these changes (like user, author and graph id and password)? Is there any scripts or logic app that apply and update the secrets?

**Comment by gsv022** [comment]
@tyi1473 . we understand your concern. As of now, it is recommended to follow the above mentioned manual approach to update the secrets and there is no script or logic app implemented as of now.  If there is any such implementation we will keep you posted.

**Comment by tyi1473** [comment]
@gsv022 Thanks for your answer.  Actually, there is another project that will build another Company communicator under a different tenant. We are trying to move the storage from current tenant to the new one in order to provide the continuous support with the same storage account. How do we transfer the storage from one tenant to another? Thanks

**Comment by tyi1473** [comment]
OK. Close this inquiry now. But I will come back to ask you about moving one storage account from a tenant to another, sometime in the future.
