### ISSUE TITLE
Proactive installation error. User application not found.

### ISSUE THREAD

**Issue by jocaffar** [OfficeDev/microsoft-teams-apps-company-communicator#993]
Hi team. I have a situation where messages are being sent but with a high percentage of failures. The number of failures is different each time, but always a high percentage from the total number of users.

Error message:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/68223287/227993773-c9dfffa5-a996-4968-b7dd-ddc3e319f97f.png">

Proactive installation is switched on. **There is no entry in the “UserAppId” value of the “AppConfig” table.**

Any help is appreciated.

**Comment by gsv022** [comment]
Hi @jocaffar <
Thanks for raising the query. Please respond to the below queries.

- What is the version of the app?
- Please share the export results of the sent message
- Make sure that user app is added to the concerned team. Here is the reference from [troubleshooting guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Troubleshooting#8-cannot-find-any-teams-or-teams-users-in-the-dropdown-while-sending-the-message)

**Comment by jocaffar** [comment]
Hi @gsv022 ,

- Latest version installed
- Data from the export results:

failed messages show the error message in the .csv: User application not found...

- We are sending to users via de Security and M365 Group functionality, thus not requiring to install in the user app in particular teams.

**Comment by jocaffar** [comment]
Hi @gsv022 ,

- Proactive installation set to TRUE during deployment
- User app manifest uploaded to ALL USERS at tenant level -> Global Policy

**Comment by gsv022** [comment]
Hi @jocaffar ,
Please share the screenshot showing that user app is uploaded at the tenant level

**Comment by jocaffar** [comment]
Hi @gsv022 ,

App is uploaded to Teams admin portal and allowed in the Global Policy

<img width="614" alt="image" src="https://user-images.githubusercontent.com/68223287/230034734-a7a10a28-9217-487b-9dd3-1868bc1b4e17.png">

**Comment by gsv022** [comment]
@jocaffar , Please share your outlook id so that we can discuss the issue internally.
