### ISSUE TITLE
Communicator Author keep loading

### ISSUE THREAD

**Issue by Boy2607** [OfficeDev/microsoft-teams-apps-company-communicator#994]
The Author app is not displaying drafts and sent messages; it keeps loading continuously.

![keep loading](https://user-images.githubusercontent.com/129176882/228225670-8324dbbc-858d-4866-b606-86871e613d68.jpg)

After clicking "New message" and selecting the 4th option, we encounter a message stating, "Permissions needed. Ask your IT admin to enable this option for you."

![select group name](https://user-images.githubusercontent.com/129176882/228226258-aca7f247-05a8-4f75-89ba-d08aa041cb0b.jpg)

**Comment by gsv022** [comment]
@Boy2607 ,Could you please respond to the above queries.
