### ISSUE TITLE
GCC Deployment Guide

### ISSUE THREAD

**Issue by desmay** [OfficeDev/microsoft-teams-apps-company-communicator#995]
Tried deploying to an Azure Gov following the [GCC Deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide-for-GCC) and the web app was throwing 503 errors because it's looking for app settings in Azure KeyVault. I had to update all ARM templates to include references for Azure KeyVault to get app to work.

**Comment by desmay** [comment]
I could create a pull request with updated ARM template if this would be helpful

**Comment by v-royavinash** [comment]
Thank you, @desmay , for highlighting this. Please feel free to raise the pull request, and we will review and test it internally. If the changes look good, we will take the necessary action.

**Comment by desmay** [comment]
There are some updates needed on GCC page - https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki 

1. On the deploy bot to commercial steps 10-12 can be deleted once pull request merged since I updated ARM template.
2. Step 1 on the deploy to Azure Gov the deploy to Azure button url should be changed to portal.azure.us for Azure Gov

**Comment by desmay** [comment]
@v-royavinash Anything else needed for this pull request?

**Comment by v-royavinash** [comment]
Thank you for the feedback on wikis and deployment template. However currently, we only support deployment in _O365 GCC tenant and Azure Commercial subscription_. For this, we have [deployment guide ](available at https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/wiki/Deployment-guide) that serves the purpose.

We have a backlog item to support deployment in _O365 GCC tenant and Azure Government subscription_ with the latest versions. We will consider this in future releases based on prioritization. For now we are closing the issue and as we have already added the item in backlog with your suggestions.
