### ISSUE TITLE
Markdown not working for "Preview in this channel"

### ISSUE THREAD

**Issue by fhwebcs** [OfficeDev/microsoft-teams-apps-company-communicator#998]
Hello,

I'm using version 5.3.0 and noticed that not all markdown code is working as expected. I try to use the following markdown formatting in the field "Summary":

```
Lorem ipsum dolore **[click here](https://www.microsoft.com)**

---

## Headline 2

### *Headline 3*

line text  
*new line italic*  
**third line bold**

new paragraph

[![alt text](http://127.0.0.1:8080/readmore-en.png)](https://www.microsoft.com)
```

In edit mode, the preview on the right looks great:

![markdown-edit](https://user-images.githubusercontent.com/7717000/228581042-a153744b-eed6-4bef-800f-c09d0fa6cf74.png)

But if you send it via "Preview in this channel" some formatting is lost:

![markdown-preview-in-channel](https://user-images.githubusercontent.com/7717000/228581227-2212c971-3478-46b3-a669-63142fc7e24a.png)

What is the reason for this and and can this possibly be remedied with little effort in the next version?

Thank you!

**Comment by gsv022** [comment]
Please let us know if you have any queries with respect to CC. If no response is required from your end, we are good to close out the issue.
